### ISSUE TITLE
Wiki for manual continuous deployment setup

### ISSUE THREAD

**Issue by suwatch** [projectkudu/kudu#1003]
We should write one of this.  It should exercise public as well as private repo - with pointer to private submodule scenarios etc.

**Comment by jvano** [comment]
Hi

Kudu will continue to run in Azure App Service. However, this repo will no longer be maintained.
If the problem persists and is related to running on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
