### ISSUE TITLE
WebJobs: Return an error job on failure to find a runnable script (instead of ignoring it)

### ISSUE THREAD

**Issue by amitapl** [projectkudu/kudu#1005]
Currently we ignore a WebJob if the job's directory has no runnable script (in the root), when possible (no one depends on that), we should return an error webjob instead specifying the actual error (no runnable script).

This is when listing the WebJobs / getting a specific WebJob.

**Comment by jvano** [comment]
Hi

Kudu will continue to run in Azure App Service. However, this repo will no longer be maintained.
If the problem persists and is related to running on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
