### ISSUE TITLE
Implement Symbol Server support

### ISSUE THREAD

**Issue by davidebbo** [projectkudu/kudu#1008]
When Kudu builds .NET code, the PDBs end up only existing in Kudu. For some debugging scenarios (e.g dump debugging, IntelliTrace, and profiling tools), it would be interesting to be able to server out those PDBs. Doing it using the standard Symbol Server protocol would be ideal to avoid creating some new special way of doing this.

**Comment by jvano** [comment]
Hi

Kudu will continue to run in Azure App Service. However, this repo will no longer be maintained.
If the problem persists and is related to running on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
