### ISSUE TITLE
Using private git repo's as npm modules

### ISSUE THREAD

**Issue by chrismatheson** [projectkudu/kudu#1044]
I would like to use an npm module from a private git repo. This can be done with npm in the following way.

``` javascript
"dependencies": {
    "myModule" : "git+ssh://user@hostname/project.git#commit-ish"
}
```

[npm docs](https://www.npmjs.org/doc/files/package.json.html)

however when i deploy to azure i get the following error

> npm ERR! git clone git@github.com:[redacted :)] Cloning into bare repository 'C:\DWASFiles\Sites\newvehicle\AppData\npm-cache_git-remotes\git-github-com-[redacted :)]-e17da321'...
> npm ERR! git clone git@github.com:[redacted :)] 
> npm ERR! git clone git@github.com:[redacted :)] Could not create directory '/c/DWASFiles/Sites/newvehicle/UserProfile/.ssh'.
> npm ERR! git clone git@github.com:[redacted :)] Host key verification failed.
> npm ERR! git clone git@github.com:[redacted :)] fatal: Could not read from remote repository.
> npm ERR! git clone git@github.com:[redacted :)] 
> npm ERR! git clone git@github.com:[redacted :)] Please make sure you have the correct access rights
> npm ERR! git clone git@github.com:[redacted :)] and the repository exists.
> npm ERR! Error: Command failed: Could not create directory '/c/DWASFiles/Sites/newvehicle/UserProfile/.ssh'.
> npm ERR! Host key verification failed.
> npm ERR! fatal: Could not read from remote repository.
> npm ERR! 
> npm ERR! Please make sure you have the correct access rights
> npm ERR! and the repository exists.
> npm ERR! 
> npm ERR!     at ChildProcess.exithandler (child_process.js:637:15)
> npm ERR!     at ChildProcess.EventEmitter.emit (events.js:98:17)
> npm ERR!     at maybeClose (child_process.js:735:16)
> npm ERR!     at Process.ChildProcess._handle.onexit (child_process.js:802:5)
> npm ERR! If you need help, you may report this log at:
> npm ERR!     http://github.com/isaacs/npm/issues
> npm ERR! or email it to:
> npm ERR!     npm-@googlegroups.com
> npm ERR! System Windows_NT 6.2.9200
> npm ERR! command "D:\Program Files (x86)\nodejs\0.10.21\node.exe" "D:\Program Files (x86)\npm\1.3.11\node_modules\npm\bin\npm-cli.js" "install" "--production"
> npm ERR! cwd D:\home\site\wwwroot
> npm ERR! node -v v0.10.21
> npm ERR! npm -v 1.3.11
> npm ERR! code 128

which in my limited understanding of the setup with git & azure etc, is because azure will generate a keypair and add this to the github project as a deploy key when i use the _Set up deployment from source control_ button in azure management console. Which is awesome

However when npm tries to checkout the module from a seperate repo, azure will use the keypair it created which only has rights to the original repo and not the private submodule.

i tried adding my keypair into .ssh folder at the top level of my website via FTP to see if this would solve the problem but no luck.

Any advise, pointers, articles to read or whatever would be greatly appreciated

**Comment by Nicholaiii** [comment]
For anyone googling this issue, If you use use Git bash or Git for windows, when using this on Windows, you wont have any issues as long as you use the normal ssh key procedures for github/gitlab/whatever

**Comment by carson-nr** [comment]
> For anyone googling this issue, If you use use Git bash or Git for windows, when using this on Windows, you wont have any issues as long as you use the normal ssh key procedures for github/gitlab/whatever

Can you please further clarify?

I am using the private gitlab instance behind https.

I have added the key found at:
`https://my-app.scm.azurewebsites.net/api/sshkey?ensurePublicKey=1`

I have added this key as a deployment key in all of my private node dependencies

this allows the app service to pull the project, but when installing I get the following error:
```
npm ERR! Unknown+User@my-organization/some_user/my-custom-package.git: Permission denied (publickey).
```
