### ISSUE TITLE
Pushing a non-default branch causes an error

### ISSUE THREAD

**Issue by davidebbo** [projectkudu/kudu#1051]
Repro:
- Clone https://github.com/KuduApps/RepoWithMultipleBranches locally
- Check out the foo/bar branch: `git checkout foo/bar`
- Push it to a new Kudu site: `git push [giturl] foo/bar

Result:

```
Counting objects: 6, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (2/2), done.
Writing objects: 100% (6/6), 470 bytes | 0 bytes/s, done.
Total 6 (delta 0), reused 6 (delta 0)
remote: One or more errors occurred.
remote: Error - Changes committed to remote repository but deployment to website failed, please check log for further details.
```

The fact that it doesn't deploy anything is by design, but it should not cause an error.

**Comment by jvano** [comment]
Hi

Kudu will continue to run in Azure App Service. However, this repo will no longer be maintained.
If the problem persists and is related to running on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
