### ISSUE TITLE
Improve support for chained web.config transforms when deploying from source control

### ISSUE THREAD

**Issue by dariagrigoriu** [projectkudu/kudu#1053]
This is based on a feedback forum related request: http://feedback.azure.com/forums/169385-web-sites/suggestions/4132151-support-chained-web-config-transforms-when-deployi

**Comment by dafergu2** [comment]
@davidebbo I'm having some trouble getting this to work.

I've got three different deployments, ci, staging, and production.  Based on reading the feature request page and this page, I should simply be able to:

1) Have a Web.config and the normal Web.Debug.config and Web.Release.config transform files.
2) Have three additional configs named Web.ContinuousIntegration.config, Web.Staging.config, and Web.Production.config.
![image](https://cloud.githubusercontent.com/assets/1692895/5761943/e10b7ad2-9cac-11e4-90a9-a066c5341c2b.png)

3) Have three Azure Websites setup, each connected to my VSO project.  Publication to each deployment is a matter of triggering a VSO build from either the VSO website or from Visual Studio.
4) In each of my Azure Websites, I have the SCM_BUILD_ARGS configured in the AppSettings section of the website configuration setting as shown in the screenshot.

![image](https://cloud.githubusercontent.com/assets/1692895/5761892/7c155256-9cac-11e4-9a74-922777c5300e.png)

So far, the transforms don't seem to be applied when I launch a build.  Is there any other configuration I need to do?  Does each of the .config files need to be set as Content in Visual Studio?  Do I need a publish profile for each of them?

Based on your comments, it seems like what I've done should work, correct?

**Comment by davidebbo** [comment]
@dafergu2 Kudu is used when connecting with GitHub, Bitbucket, and when pushing to Azure from a local git repo. When publishing via VSO, things works quite differently, as the build is being done on VSO rather than Azure. VSO then just publishes to Azure using WebDeploy. But nothing you see here applies to it. I would suggest asking on the VSO forum, where their experts may have advice on making this work.

**Comment by dafergu2** [comment]
@davidebbo Ah, thanks for the clarification, it wasn't clear from the articles.

**Comment by dafergu2** [comment]
@davidebbo Based on your comments, I ended up having to do something similar to the original poster on http://stackoverflow.com/questions/26548222/visual-studio-online-continuous-deployment-to-azure-website-with-publish-profile

**Comment by davidebbo** [comment]
Yes, in the end this flag needs to be passed. The mechanism by which it's done differs in VSO vs Kudu, but the /p:PublishProfile flag is the same.
