### ISSUE TITLE
SCM_REPOSITORY_PATH value should be consistent

### ISSUE THREAD

**Issue by suwatch** [projectkudu/kudu#1063]
The current value is `repository` or `wwwroot` which is relative under site folder.  However, other apis take path relative to root.  For instance, `site/wwwroot` or `site/repository`.   We should strike for consistency.  To minimize breaking change, we handle `wwwroot` as `site\wwwroot` (common initial clone scenarios).

**Comment by suwatch** [comment]
It turned out both `SCM_REPOSITORY_PATH` and `SCM_TARGET_PATH` do support absolute path today (thanks to `Path.Combine(parent, setting)` call).   If setting is absolute, the parent is ignored.

I tested by setting ...
```
SCM_REPOSITORY_PATH = d:\home\logFiles\repo
SCM_TARGET_PATH = d:\home\logFiles\target
```

This is the output when git push.
```
remote: Updating branch 'master'.
remote: Updating submodules.
remote: Preparing deployment for commit id 'a26cd0b8d4'.
remote: Generating deployment script.
remote: Generating deployment script for Web Site
remote: Running deployment command...
remote: Handling Basic Web Site deployment.
remote: KuduSync.NET from: 'd:\home\logFiles\repo' to: 'd:\home\logFiles\target'
remote: Copying file: 'index.htm'
remote: Finished successfully.
remote: Deployment successful.
```

I have updated the [wiki](https://github.com/projectkudu/kudu/wiki/Deploying-inplace-and-without-repository).   If we think this is sufficient for now, let close the issue.

**Comment by davidebbo** [comment]
@suwatch do we support env variable expansion here? I don't like having to write `d:\home\foo`, but `%HOME%\foo` would be pretty clean.

**Comment by suwatch** [comment]
I am about to support it - since I need to write a test that would run on local kudu and `d:\home` won't work.

**Comment by davidebbo** [comment]
Perfect!
