### ISSUE TITLE
Race condition in Moq for ApplyChangesCoreThrowsIfAnyFileTaskFails test

### ISSUE THREAD

**Issue by mwtian-zz** [projectkudu/kudu#1064]
From @suwatch, sometimes race conditions in Moq cause unit tests failures. We can try to find a way to prevent it. The following is a sample failed test summary.

(new) Kudu.Services.Test.dll: Kudu.Services.Test.DropboxHelperFacts.ApplyChangesCoreThrowsIfAnyFileTaskFails        details » 

Stacktraces: 
(new) Kudu.Services.Test.dll: Kudu.Services.Test.DropboxHelperFacts.ApplyChangesCoreThrowsIfAnyFileTaskFails 
Assert.Equal() Failure
Expected: 9
Actual:   8
   at Kudu.Services.Test.DropboxHelperFacts.<ApplyChangesCoreThrowsIfAnyFileTaskFails>d__43.MoveNext() in c:\Kudu Files\Private\src\master\Kudu.Services.Test\DropboxHelperFacts.cs:line 160

Time Elapsed 00:03:16.04
Step Build - Release (MSBuild) failed
Step 2/5
Build step Deploy Zip for Rapid Update (MSBuild) skipped because of previous step failure
Step 3/5
Build step Version Check (Command Line) skipped because of previous step failure
Step 4/5
Build step Run functional tests (MSBuild) skipped because of previous step failure
Step 5/5
Starting: C:\BuildAgent-CodeSign\temp\agentTmp\custom_script2335637227284407611.cmd
in directory: C:\drops

C:\drops\Kudu-Private\master>echo d172bb2114908344186ffd60b03232da49b28a95  1>C:\ProgramData\JetBrains\TeamCity\system\artifacts\Kudu-Private\master\2868\commit 

C:\drops\Kudu-Private\master>C:\Windows\system32\cmd.exe /c mklink /j 686  C:\ProgramData\JetBrains\TeamCity\system\artifacts\Kudu-Private\master\2868 
Junction created for 686 <<===>> C:\ProgramData\JetBrains\TeamCity\system\artifacts\Kudu-Private\master\2868

C:\drops\Kudu-Private\master>C:\Windows\system32\cmd.exe /c if exist "Latest" rmdir /Q /S "Latest" 

C:\drops\Kudu-Private\master>C:\Windows\system32\cmd.exe /c mklink /j "Latest" 686 
Junction created for Latest <<===>> 686
Process exited with code 0
Waiting for 19 service processes to complete
Publishing internal artifacts
Sending build.finish.properties.gz file
Publishing artifacts
Collecting files to publish: [artifacts]
Sending artifacts
Total: 0 (+0 -0) Errors: 0 (+0 -0)
Build finished

**Comment by jvano** [comment]
Hi

Kudu will continue to run in Azure App Service. However, this repo will no longer be maintained.
If the problem persists and is related to running on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
