### ISSUE TITLE
Better Documentation for Deploying Continuous WebJob Singleton

### ISSUE THREAD

**Issue by ghost** [projectkudu/kudu#1067]
I would like to have a continuous webjob that is a singleton.  I'm planning on deploying my job as part of my MVC website, which I deploy from github. How do I configure this during deployment as described in the post below? I only see how to make it continuous, not a singleton.

http://blog.amitapple.com/post/74215124623/deploy-azure-webjobs/

It looks like there is some sort of a rest API to change settings? I don't want to have to call an API and I don't understand how/when I would even invoke the API.

**Comment by CarlosSardo** [comment]
Hi @amitapl ,

Where can I find the WebJobs wiki that contains this updated documentation on the settings.job?

Thanks!

**Comment by davidebbo** [comment]
See https://github.com/projectkudu/kudu/wiki/WebJobs-API
