### ISSUE TITLE
Site extensions deployed on deployment

### ISSUE THREAD

**Issue by amitapl** [projectkudu/kudu#1085]
We should add a command line tool that (running on azure) can deploy site extensions similar way to nuget using `packages.config` file, we can use `siteextensions.config` in the same format.

This tool should be called from our deployment script and will install the packages/site extensions specified in the `siteextensions.config` file.

We can probably extend `kudu.exe` to do this task.

**Comment by davidebbo** [comment]
ARM Template is the right way to do this.
