### ISSUE TITLE
Add a way to initiate the deployment process

### ISSUE THREAD

**Issue by amitapl** [projectkudu/kudu#1086]
As a step forward in allowing us to run deployment process (including for example a custom deployment script) when deploying outside of kudu (webdeploy/ftp/...), we should add a way to initiate a deployment process externally.

It could be using an API or using the `kudu.exe` with the right environment settings (passed in as configuration file or commandline arguments).

**Comment by jvano** [comment]
Hi

Kudu will continue to run in Azure App Service. However, this repo will no longer be maintained.
If the problem persists and is related to running on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
