### ISSUE TITLE
Support running Chutzpah tests during deployment

### ISSUE THREAD

**Issue by smithkl42** [projectkudu/kudu#1090]
According to the interactions on <a href="http://social.msdn.microsoft.com/Forums/windowsazure/en-US/dbc214b9-9b29-4ea6-99eb-f6198f8391dd/running-jasmine-unit-tests-with-chutzpah-in-kudu-deploy?forum=windowsazurewebsitespreview">this question</a>, it's not possible to run Chutzpah tests during deployment, due to problems with running PhantomJS in the Kudu sandbox. This would be really handy to have supported.

(My apologies if this is being addressed in another issue - I looked and couldn't find any.)

**Comment by jvano** [comment]
Hi

Kudu will continue to run in Azure App Service. However, this repo will no longer be maintained.
If the problem persists and is related to running on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
