### ISSUE TITLE
Push multiple repos to Azure failed 

### ISSUE THREAD

**Issue by suwatch** [projectkudu/kudu#1099]
Just open for tracking.  While investigating other issue, I ran into this.  Not sure how realistic scenario this is - but it could reveal some interesting different Azure behavior since it works well on public kudu but failed on azure.

```
1. clone https://github.com/kudustress/NuGetGalleryOptmized.git
2. push to Azure
3. clone https://github.com/KuduApps/HelloKudu
4. push to Azure  (override with +master)
5. try to push NuGetGalleryOptmized to Azure again.
```

This will failed with `remote: error: unable to write sha1 filename ./objects/pack/pack-9fa53a750a3756b58f7b3366658420b0478a91f8.pack`

I investigated and this file is a read only file created during first push.  On public Kudu (looking at procmon), step 5 got the `Name Collision` error code but it then changes attribute to writable and proceed to overwrite the file.    However, for Azure, it got `Violation Error` and failed right away.

**Comment by jvano** [comment]
Hi

Kudu will continue to run in Azure App Service. However, this repo will no longer be maintained.
If the problem persists and is related to running on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
