### ISSUE TITLE
Kudu.Services.Web fails to run on F5

### ISSUE THREAD

**Issue by amitapl** [projectkudu/kudu#1109]
Currently when we try running the Kudu.Services.Web project directly from VS using F5 it fails since it fails to expand environment variable "%HOME%" (it's not there).

**Comment by jvano** [comment]
Hi

Kudu will continue to run in Azure App Service. However, this repo will no longer be maintained.
If the problem persists and is related to running on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
