### ISSUE TITLE
[Kudu.Web] Handle website creation error better

### ISSUE THREAD

**Issue by mwtian-zz** [projectkudu/kudu#1112]
Currently when website creation fails, Kudu tries to delete it. In all cases I encountered, the deletion got stuck and so does the Create Application UI.

**Comment by jvano** [comment]
Hi

Kudu will continue to run in Azure App Service. However, this repo will no longer be maintained.
If the problem persists and is related to running on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
