### ISSUE TITLE
WebJobs: Retry triggered jobs that are aborted

### ISSUE THREAD

**Issue by amitapl** [projectkudu/kudu#1113]
Consider the scenario where your triggered WebJob is aborted for any reason (not because the process stops), we probably want to retry the job?

**Comment by jvano** [comment]
Hi

Kudu will continue to run in Azure App Service. However, this repo will no longer be maintained.
If the problem persists and is related to running on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
