### ISSUE TITLE
Invoke triggered job via HTTP POST returns 403

### ISSUE THREAD

**Issue by niklaslundberg** [projectkudu/kudu#1127]
A HTTP GET request to https://{mywebsite}.scm.azurewebsites.net/jobs/triggered/{jobname}/ 
works, HTTP status code 200, but a POST to https://{mywebsite}.scm.azurewebsites.net/jobs/triggered/{jobname}/run returns HTTP status code 403.

The only used HTTP header is Authorization. 

The web job was added manually by copying files to ~/App_Data/jobs/triggered/{jobname}

It works to trigger the web job manually from the Azure portal.

**Comment by jstoker** [comment]
@davidebbo @suwatch Hi.
 I'm still getting this issue when trying to talk to the /api/continuouswebjobs/{webjobname}/stop API.
It appears that having a "/" in the User-Agent is causing something to be unhappy with the request, and return a 403 whenever a POST request is sent.

For example, `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36` as a user-agent does not work, however `Mozilla5.0 (Windows NT 10.0; Win64; x64) AppleWebKit537.36 (KHTML, like Gecko) Chrome74.0.3729.131 Safari537.36` (which removes the slashes) works.

**Comment by suwatch** [comment]
what cred are you passing?  basic auth?

**Comment by jstoker** [comment]
Hi Suwat,
We're using the automatically generated site credentials (the one which the username begins with a $) and passing those through in an Authorization header as HTTP Basic auth.
We can successfully retrieve information about the running WebJobs (and interestingly, can deploy a new webjob), but can't call either Start/Stop, without changing the user-agent.

https://github.com/projectkudu/kudu/wiki/Deployment-credentials#site-credentials-aka-publish-profile-credentials

**Comment by suwatch** [comment]
is there a way to share HAR file?   Beware that HAR file contains your cred and you will need to scrub that before sharing.

Also try to run using CURL and pass the user-agent, see if any difference?

**Comment by jstoker** [comment]
Hi,

I've quickly reproduced the issue on a public App Service, and made the PowerShell used to reproduce it available at https://gist.github.com/jstoker/e84203abe508bad06cc6cb4712b3459d.
The work-around for now is going to be explicitly providing a User-Agent, to unblock us, however this is a fairly non-obvious work-around, and smells like some form of bug. :-)

I've further validated this issue against public Azure, running Kudu 
81.10329.3844.0 (14d700a964), using the provided sample code.
The App Service has a small example WebJob deployed into it as a continuous WebJob.

Hope that helps. I can provide further examples, or a similar trace against the original App Service I was having issues with, if that's needed.

**Comment by jstoker** [comment]
Hi @suwatch,

Was the above sample enough to reproduce the issue?
Should this issue get re-opened, or a new one created?
