### ISSUE TITLE
Deployment gets killed if the site is restarted

### ISSUE THREAD

**Issue by davidebbo** [projectkudu/kudu#1134]
I think we always knew that was possible, but never really exercised it. Here is the scenario a user ran into:
- Start a git push of a repo that has a long deployment (e.g. because it needs to install lots of npm packages)
- Go to config page in portal and change a setting

The deployment may be given a little bit of time to complete, but if it doesn't, it gets hard killed.

We should attempt to repro this, and then discuss possible mitigations.

**Comment by jvano** [comment]
Hi

Kudu will continue to run in Azure App Service. However, this repo will no longer be maintained.
If the problem persists and is related to running on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
