### ISSUE TITLE
Restart site after installing Site Extension should take Scm separation into account

### ISSUE THREAD

**Issue by suwatch** [projectkudu/kudu#1179]
Currently we only restart the Scm site.  This works well for most site extensions that only affect Scm site shape and form.  However, if certain site extension happens to do config changes targeting main user site, it would not take affect.   Option could be the restart button may aggressively include restart the user site.

We will need to deal with this differently in multi-instance scenarios.

**Comment by mchaffie** [comment]
I realize this ticket is closed but...

...the Kudu site extension point seems like a clean way to add a third-party native HttpModule to a deployed Web App. For that usecase the main site process has to be cycled after the extension is installed so it will pick up the new config and load the native library. On uninstall the library has to be unloaded which will also only happen after a restart. It would be really nice :-) to be able to do this programatically against the SCM site.  

Is there another deployment method that makes more sense for adding third-party modules to the main site?

**Comment by davidebbo** [comment]
It's not really possible to cleanly restart from the Scm API. However, when an extension is installed through the full Azure API (ARM), the site does get restarted, so your scenario should work. See [here](https://github.com/projectkudu/ARMClient/wiki/Site-Extensions) for details on that ARM API.

**Comment by mchaffie** [comment]
OK, good to know, thanks.
