### ISSUE TITLE
Make a request to the site at the end of the deployment logic

### ISSUE THREAD

**Issue by davidebbo** [projectkudu/kudu#1244]
Soon, we'll get an env variable with the site host name. Using it, we can curl the site at the end of the deployment, which serves to purposes:
1. It warms it up
2. It can check that the site is not completely busted

One tricky thing is that we may not always know what path to hit (it's not always `/`), but we could make this configurable.

**Comment by jvano** [comment]
Hi

Kudu will continue to run in Azure App Service. However, this repo will no longer be maintained.
If the problem persists and is related to running on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
