### ISSUE TITLE
Enabling aspnet:PortableCompilationOutput in Kudu breaks Monaco

### ISSUE THREAD

**Issue by mwtian-zz** [projectkudu/kudu#1269]
When `<add key="aspnet:PortableCompilationOutput" value="false" />` is added to `appSettings` of `Kudu.Services.Web/Web.config`, `Monaco` encounters error `500`. No other `node` test repos in Kudu functional tests have this error. The error message is pasted below:

HTTP Error 500.0 - Internal Server Error
The page cannot be displayed because an internal server error has occurred.

Most likely causes:
IIS received the request; however, an internal error occurred during the processing of the request. The root cause of this error depends on which module handles the request and what was happening in the worker process when this error occurred.
IIS was not able to access the web.config file for the Web site or application. This can occur if the NTFS permissions are set incorrectly.
IIS was not able to process configuration for the Web site or application.
The authenticated user does not have permission to use this DLL.
The request is mapped to a managed handler but the .NET Extensibility Feature is not installed.

Things you can try:
Ensure that the NTFS permissions for the web.config file are correct and allow access to the Web server's machine account.
Check the event logs to see if any additional information was logged.
Verify the permissions for the DLL.
Install the .NET Extensibility feature if the request is mapped to a managed handler.
Create a tracing rule to track failed requests for this HTTP status code. For more information about creating a tracing rule for failed requests, click here.

Detailed Error Information:
Module     iisnode
Notification       ExecuteRequestHandler
Handler    iisnode
Error Code     0x800700b7
Requested URL      https://~1suwatchet01:80/dev/server.js
Physical Path      D:\Program Files (x86)\SiteExtensions\Monaco\1.0.0-20140715\server.js
Logon Method       Anonymous
Logon User     Anonymous

More Information:
This error means that there was a problem while processing the request. The request was received by the Web server, but during processing a fatal error occurred, causing the 500 error.
View more information »

Microsoft Knowledge Base Articles:

294807

**Comment by jvano** [comment]
Hi

Kudu will continue to run in Azure App Service. However, this repo will no longer be maintained.
If the problem persists and is related to running on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
