### ISSUE TITLE
'Illegal characters in path.'

### ISSUE THREAD

**Issue by madstt** [projectkudu/kudu#1273]
When using certain characters, like 'æ', 'ø', 'å', in your solution name or project name, you cannot deploy to an Azure Website. It fails in the 'Preparing deployment for commit id' step with an error saying 'Illegal characters in path.' This makes sense, but sometimes developers actually wanna use such characters.

I've made a sample repo for repro: https://github.com/madstt/-benr-

**Comment by jvano** [comment]
Hi

Kudu will continue to run in Azure App Service. However, this repo will no longer be maintained.
If the problem persists and is related to running on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
