### ISSUE TITLE
PUT /deployments should return a response body with the result of the deployment

### ISSUE THREAD

**Issue by paulbatum** [projectkudu/kudu#1287]
Triggering a deployment via PUT /deployments returns a 204 with an empty response body. This means that the caller has to make several additional calls to figure out if the deployment was successful:
1. GET /deployments, find active one
2. GET /deployments/<id>, extract logURL
3. GET /deployments/<id>/log, extract details URL
4. GET /deployments/<id>/log/<id>

It would be much easier if the PUT /deployments API actually returns a full response body with the details of the deployment result.

**Comment by jvano** [comment]
Hi

Kudu will continue to run in Azure App Service. However, this repo will no longer be maintained.
If the problem persists and is related to running on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
