### ISSUE TITLE
Unclear documentation for FTP Deployment of Node.js site

### ISSUE THREAD

**Issue by msarchet** [projectkudu/kudu#1296]
My team is using a tool that handles our CI and git deployment is not a viable option for us. Because of this we are using FTP to deploy our node.js sites to azure websites.

The documentation is not clear on the full requirements for a node.js site that is being deployed to an azure website (running kudu).

Specifically we did not know, from the kudu docs, that we needed a web.config to get the site to actually be started by kudu.

Suggest that docs be updated to reflect this information.

Thanks to @shanselman and @davidebbo for helping us find what we were missing. We learned of the missing web.config from this [msdn post](http://social.msdn.microsoft.com/Forums/en-US/03fa7b70-2c60-41da-ba35-53352e751baa/nodejs-and-ftp-deployment-seems-broken?forum=windowsazurewebsitespreview)

What would be the prefered location for updating the docs? I'm willing to make the PR to add them.

**Comment by jvano** [comment]
Hi

Kudu will continue to run in Azure App Service. However, this repo will no longer be maintained.
If the problem persists and is related to running on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
