### ISSUE TITLE
Grunt test and Phantomjs - the port number

### ISSUE THREAD

**Issue by xied75** [projectkudu/kudu#1306]
Dear all,
Sorry if this is already answered somewhere, I Bing(ed) a lot but still not clear the issue.

Basically I start with Yeoman (Webapp generator) to scaffolding my website, in it there is Grunt -> Grunt Mocha -> Phantomjs for testing.

I then used Azure Cli to create the Deploymentscript and did the changes to fire Bower and Grunt before Kudu Sync.

The trouble is, when the Grunt is calling test, it show something like this:

```
Running "connect:test" (connect) task
Started connect web server on http://127.0.0.1:9001

Running "mocha:all" (mocha) task
Testing: http://127.0.0.1:9001/index.html
```

On my local machine, it will continue the grunt tasks, to build the dist folder; but on Azure Website, it hangs there, eventually timeout at 61 seconds.

I tried to change the 9001 to process.env.PORT, still hang.

So I wonder is this something to do with we can't listen on a port?
But then I saw this http://www.hanselman.com/blog/HowToInstallTheNodejsGhostBloggingSoftwareOnAzureWebsites.aspx

Totally confused now. Somebody help!

Best regards,

Dong

**Comment by jvano** [comment]
Hi

Kudu will continue to run in Azure App Service. However, this repo will no longer be maintained.
If the problem persists and is related to running on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
