### ISSUE TITLE
when changing AzureTableTraceLevel :StorageException : (415) JSON format is not supported 

### ISSUE THREAD

**Issue by gblence** [projectkudu/kudu#1308]
I have not been successful in changing a tracer listener’s  storage table logging level during runtime. *Note the file system logging works as expected. 
I've spent most of the day scratching my head trying to determine the problem and now I’m not sure where to look next
I am new to Kudu. I don’t have source control integrated.

Simple setup. Azure Website: three trace entries in global.asax in Application_BeginRequest

Trace.TraceWarning("This is trace warning in begin request at time {0}");
Trace.TraceInformation("This is trace information in begin request at time {0}");
 Trace.TraceError("This is trace Err in begin request at time {0}");

I have APPLICATION LOGGING(TABLE STORAGE) on and set to verbose.
Publish website to staging slot(I have also tried production),load a web page and all three traces correctly show up in Azure Table.  Now I want to change the logging level to Error. I have tried doing this three separate ways:

•Through the Azure UI portal.
•Run Power Shell script :
       Enable-AzureWebsiteApplicationDiagnostic -Name "SiteName" -Storage -LogLevel Error   -  StorageAccountName “StorageName”
•Manually editing and saving the settings.json file in ther diganostics folder at Kudu portal site https://site.scm.azurewebsites.net/ 

I confirm the settings were saved. I expect to now load a page and see only the TraceError entry.
## However, nothing gets logged to the Azure Table. I dug through the different kudu logs and get this error each time after changing the logging level.

Microsoft.WindowsAzure.Storage.StorageException: The remote server returned an error: (415) JSON format is not supported.. ---> System.Net.WebException: The remote server returned an error: (415) JSON format is not supported..
   at System.Net.HttpWebRequest.GetResponse()
   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.ExecuteSync[T](RESTCommand`1 cmd, IRetryPolicy policy, OperationContext operationContext)
   --- End of inner exception stack trace ---
   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.ExecuteSync[T](RESTCommand`1 cmd, IRetryPolicy policy, OperationContext operationContext)
   at Microsoft.WindowsAzure.Storage.Table.TableOperation.Execute(CloudTableClient client, CloudTable table, TableRequestOptions requestOptions, OperationContext operationContext)
   at Microsoft.WindowsAzure.Storage.Table.CloudTable.Exists(Boolean primaryOnly, TableRequestOptions requestOptions, OperationContext operationContext)
   at Microsoft.WindowsAzure.Storage.Table.CloudTable.CreateIfNotExists(TableRequestOptions requestOptions, OperationContext operationContext)
   at Microsoft.WindowsAzure.WebSites.Diagnostics.AzureTableTraceListener.ConsumeBuffer()
Request Information
RequestID:6fecd24b-9967-499f-b7a7-9eeabfb5fa47
RequestDate:Mon, 25 Aug 2014 23:49:32 GMT
StatusMessage:JSON format is not supported.
## ErrorCode:JsonFormatNotSupported

I recreated website, storage account, updated all Azure DLLs to the latest version. Microsoft.WindowsAzure.Storage is 4.2.1.0. I can’t find any references on AzureTableTraceListener and little documentation on storage exception response 415 “JSON format is not supported” so I’m not sure where to go from here. 

This issue will persist unless I turn logging off and then back on. 

Greatly appreciate any insight or direction.
Thanks

**Comment by mi-hol** [comment]
@davidebbo @amitapl  is this still active?

**Comment by davidebbo** [comment]
Sorry, ancient issue that was fixed and never closed.
