### ISSUE TITLE
sh.exe changes path separator for some environment variables from \ to /

### ISSUE THREAD

**Issue by ahmelsayed** [projectkudu/kudu#1310]
`sh.exe` when launching `kudu.exe` changes the path separator in `HOME`, `TEMP`, `TMP` from `D:\home` and `C:\DWASFiles\Sites\{siteName}\Temp` to `D:/home` and `C:/DWASFiles/Sites/{siteName}/Temp`

some commands like `del`, `rd`, `dir` don't work with `/`

**Comment by jvano** [comment]
Hi

Kudu will continue to run in Azure App Service. However, this repo will no longer be maintained.
If the problem persists and is related to running on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
