### ISSUE TITLE
Fix zip behavior to throw on error

### ISSUE THREAD

**Issue by amitapl** [projectkudu/kudu#1327]
Using `ZipArchive` to extract files can fail silently if the zip is corrupt.

Adding this check may help:

```
    if (fileInfo.Length != entry.Length)
    {
        throw new Exception(string.Format("Extracted file size not as expected for file: {0} [{1}] vs [{2}]",     fileInfo.Name, fileInfo.Length, entry.Length));
    }
```

**Comment by jvano** [comment]
Hi

Kudu will continue to run in Azure App Service. However, this repo will no longer be maintained.
If the problem persists and is related to running on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
