### ISSUE TITLE
.NET Framework retains file lock on profilers after site stops

### ISSUE THREAD

**Issue by robertmclaws** [projectkudu/kudu#1334]
I have been experiencing the issue in [this StackOverflow thread](http://stackoverflow.com/questions/24755028/azure-deloyment-with-and-new-relic) on all of my Azure Websites deployments. Up until I found that thread, there was no clear way to release the locks, and I had several deployments held up for over an hour while I fiddled with the settings till the lock released.

If you guys are unable to solve the problem for whatever reason, it would be great if Kudu could trigger that flag be shut off automatically when the deployment starts, and turn it back on when the deployment is finished. OR modify the command fired by the portal "stop" button to turn this flag off when the website is stopped.

Please feel free to contact me if you need any help reproing, it happens on my sites all the time. I'm happy to give you guys whatever access you need.

**Comment by advancedrei** [comment]
I am currently trying to deploy a website, and the file locks are still not being removed during WebDeploy. NewRelic.Core is still the culprit in this case. Installing the Websites Extension was the only thing that was able to successfully remove the lock. Just an FYI that you guys might need to re-open this issue.

**Comment by davidebbo** [comment]
This issue was specifically about Kudu scenarios (git deployment), so the fix that was made here does not apply to WebDeploy.

**Comment by advancedrei** [comment]
OK, so how do I open this issue with the WebDeploy team?

**Comment by davidebbo** [comment]
Probably Azure Websites forum is the best place to bring it up.
