### ISSUE TITLE
Support pre-compilation of .net websites

### ISSUE THREAD

**Issue by darrenkopp** [projectkudu/kudu#1341]
To avoid slow startup and wasted cpu cycles, kudu should support [precompiling asp.net websites](http://msdn.microsoft.com/en-us/library/vstudio/bb398860.aspx). If using msbuild, you can run the AspNetCompilerTask, otherwise bootstrap the aspnet_compiler.exe

**Comment by DavidBoike** [comment]
Seeing that this is on the backlog, I did figure out a workaround solution, which is outlined as [an answer on my StackOverflow question](http://stackoverflow.com/questions/27554510/cant-deploy-precompiled-merged-webapp-to-azure/29614694#29614694).

I do hope to be able to undo that workaround someday though.

**Comment by MatthewSteeples** [comment]
Something has changed recently and the views are being compiled (as we get warnings and errors from them now). I don't know whether those compiled views are being deployed yet though.

**Comment by davidebbo** [comment]
Yes, I forgot to close this bug earlier, but this has been deployed for a while.
