### ISSUE TITLE
Kudu API and CORS

### ISSUE THREAD

**Issue by advancedrei** [projectkudu/kudu#1353]
So, I'm trying to build a management web site to complement my public app. It's deployed to Azure Websites, but using Auth0, it is limited to only my company's users. In this app, I'm trying to link together many of the services that we use, so I don't have to keep 15 different status consoles open all day.

So I want to link some of the Kudu APIs into my web app, but I can't at the moment because of cross-domain issues. I could use an controller in my admin app that then marshals the call to Kudu (which will likely be my only option for the time being), but that results in an extra request, which is not ideal seeing as how both sites are running on the same box.

I see several solutions to this problem:
1) Allow the end user to specify CORS domains for API calls in the Kudu console. This seems like the most straight-forward option that allows for the greatest flexibility, and is similar to other services.
2) Automatically add IP addresses and host names that are configured across your Azure Websites. This way any site on the box can access the APIs. Would still need deployment credentials to access the APIs, which is what happens with the deployment endpoint right now (AFAIK).
3) Allow any CORS request with the * filter, and rely on credentials (most likely deployment creds) for access. Alternatively could allow for OAuth token generation & requests.

I understand that the last one could have attack vectors, but there are potentially ways to mitigate that (like OAuth). Right now, if someone has your deployment credentials, there is an awful lot they can do anyways (like log in over FTP and delete your site), so I'm not sure if there is really a difference.

Thanks in advance.
@robertmclaws

**Comment by suwatch** [comment]
The support is live.  Please reopen if any issue.
