### ISSUE TITLE
Ability to supply connection string on deploy.

### ISSUE THREAD

**Issue by catdadcode** [projectkudu/kudu#136]
I am deploying an application via a Github hook. The Github repository is public and thus does not contain sensitive connection string information. When the hook fires a deploy on kudu I'd like to have a connection string setup at that point that it drops in. Any suggestions for how to do this?

Should it be something you can set when setting up an application in kudu? Or is there a better way to add a connection string at deploy time?

**Comment by mi-hol** [comment]
@davidebbo  is this still active?

**Comment by jvano** [comment]
Hi

Kudu will continue to run in Azure App Service. However, this repo will no longer be maintained.
If the problem persists and is related to running on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
