### ISSUE TITLE
NodeJS deployment issue with custom deploy.cmd

### ISSUE THREAD

**Issue by JayBeavers** [projectkudu/kudu#1360]
I have an nodejs/express website that has recently stopped working as expected.  When I look at the logs, I see something suspicious -- it looks like my server is being started before deploy.cmd is completing.  I'm using a customized deploy.cmd to support bower and grunt in addition to npm.  It seems that kudu_sync_cmd is now detecting and executing server.js prior to the rest of the script finishing.

The site is set up off this public template, https://github.com/JayBeavers/webtemplate.  But the site itself is private so I cannot point your directly to its source.  And this used to work fine for me. I think there's been a change in behavior of kudu_sync_cmd, perhaps to detect and launch 'node server.js' prior to deploy.cmd finishing?

I've posted the details to a gist: https://gist.github.com/JayBeavers/6d758a3f76fe34cf5a32

Please contact me at jbeavers@microsoft.com with any thoughts, Lync or email. Thank you.

It also feels like I'm getting an old version from git rather than the most recent code. Not sure if this is related to an improperly timed launch or an up and up bug in the deployment engine.

**Comment by fsbdev** [comment]
I am having the same issue, I have tasks generating compiled files in my deployment script but looking at my site it appears the tasks haven't had effect (my html still points to the folder for uncompiled files and stylesheets are missing etc) - http://scribemania.azurewebsites.net/

My (shortened) log below also seems to indicate that node is starting before my tasks are done. I've tried rearranging the order of tasks in my deployment script but it seems I can't control when server.js is executed.

```
Command: deploy.cmd
Handling node.js deployment.
Using start-up script server.js from package.json.
Generated web.config.
The package.json file does not specify node.js engine version constraints.
The node.js application will run with the default node.js version 0.10.32.
 Running "requirejs:compile" (requirejs) task
 Running "string-replace:dist" (string-replace) task
 Running "stylus:compile" (stylus) task
File public\styles\main.css created.
 Done, without errors.
```

This is the respective deployment section of my deploy.cmd script:

```
::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
:: Deployment
:: ----------

:Deployment
echo Handling node.js deployment.

:: 1. Select node version
call :SelectNodeVersion

:: 2. Run grunt
call :ExecuteCmd npm install grunt-cli
./node_modules/.bin/grunt --no-color build

:: 3. KuduSync
IF /I "%IN_PLACE_DEPLOYMENT%" NEQ "1" (
  call :ExecuteCmd "%KUDU_SYNC_CMD%" -v 50 -f "%DEPLOYMENT_SOURCE%" -t "%DEPLOYMENT_TARGET%" -n "%NEXT_MANIFEST_PATH%" -p "%PREVIOUS_MANIFEST_PATH%" -i ".git;.hg;.deployment;deploy.cmd"
  IF !ERRORLEVEL! NEQ 0 goto error
)

::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
```

**Comment by davidebbo** [comment]
@fsbdev I'm not clear whether you're describing a **deployment** issue (files dont' make it to where they should be), or a **runtime** issue (files are correct but things don't run as you expect). These are very separate things.

**Comment by fsbdev** [comment]
It's a deployment issue, the node server is started before the compilation steps in the deployment as I described.

**Comment by davidebbo** [comment]
That does not make it a deployment issue. After everything is complete, are all the files where they should be or not? If you restart the site, does it make it work?

**Comment by fsbdev** [comment]
No restarting does not help.

**Comment by davidebbo** [comment]
Well, then the question about deployment vs runtime issue stands. You can use Kudu Console to look at the deployed files in wwwroot and help determine which it is.

**Comment by fsbdev** [comment]
The wwwroot folder is missing the results of some of the build tasks. It seems that files generated from first couple grunt tasks are there though (with the last couple's not) so I'm going to try to reorder them to see if it works around the bug.

**Comment by fsbdev** [comment]
I never understood what you meant by runtime error, the app runs fine currently on the VPS I have it on currently - scribemania.com but I'm trying to move it to Azure since I ported my API server to .NET and Azure and would like them in the same data center.

**Comment by fsbdev** [comment]
I still have the same issue but actually looking at the last modified time for my wwwroot folder in Kudu Console it says `2/7/2015, 6:17:12 PM` even though I've deployed (successfully I've been told) several times since then.

**Comment by davidebbo** [comment]
FYI, I just wrote this [wiki page](https://github.com/projectkudu/kudu/wiki/Deployment-vs-runtime-issues) to make it clearer what we mean by Deployment vs Runtime issue (it comes up a fair bit).

BTW, you may want to start a new issue, as this one is closed and might not be quite the same thing as yours.
