### ISSUE TITLE
WebJobs deployed to a staging slot should not run by default.

### ISSUE THREAD

**Issue by robertmclaws** [projectkudu/kudu#1365]
Due to the lack of ability to specify Websites settings that do not get copied into "swapped" slots, when WebJobs are deployed to a deployment slot, they should be disabled by default, so they don't accidentally process jobs meant for the Production slot.

**Comment by ajbeaven** [comment]
Sticky settings have the unfortunate side effect of causing the web app to restart after a slot swap process, thereby defeating the main purpose of deployment slots in my opinion. It would be nice if there was a setting that could be set on the slot configuration which enabled/disabled webjobs without affecting the slot swap process.
