### ISSUE TITLE
Process explorer show SCM process twice with same PID

### ISSUE THREAD

**Issue by suwatch** [projectkudu/kudu#1369]
![processes](https://cloud.githubusercontent.com/assets/1088218/4775259/6c267ca8-5bb6-11e4-9038-158611aa5f69.png)

**Comment by jvano** [comment]
Hi

Kudu will continue to run in Azure App Service. However, this repo will no longer be maintained.
If the problem persists and is related to running on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
