### ISSUE TITLE
Add Kudu REST api to list certs in the store

### ISSUE THREAD

**Issue by suwatch** [projectkudu/kudu#1374]
List of cert in user and local stores,  This includes typical cert property like HasPrivateKey, thumpprint, issuer, name, datetime etc.

**Comment by jvano** [comment]
Hi

Kudu will continue to run in Azure App Service. However, this repo will no longer be maintained.
If the problem persists and is related to running on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
