### ISSUE TITLE
A number of tests that use MVC 3 are broken on local machines due to move to 3.0.0.1

### ISSUE THREAD

**Issue by davidebbo** [projectkudu/kudu#1385]
Recently, the MVC team did a bonehead update that broken the build for many people (see [here](http://stackoverflow.com/questions/26406877/asp-net-mvc-security-patch-to-version-3-0-0-1-breaks-build)). Specifically, they removed MVC 3.0.0.0, and instead GACed 3.0.0.1. At runtime, that's fine, as they have a global policy. But it breaks the build for many of our suites.

I'm yet to see a way to fix this machine level. Instead, the suggested fixes are all about fixing individual apps.

Are you guys still passing all tests on your machine? Try for example the test called 'GetResults'

First, check if you GAC assembly was in fact updated by Windows Update by running `gacutil -l system.web.mvc`. T get:

```
  system.web.mvc, Version=3.0.0.1, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL
  system.web.mvc, Version=4.0.0.1, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL
  system.web.mvc, Version=5.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL
  system.web.mvc, Version=5.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL
```

The error in the test is (warning turns into many errors):

```
C:\Program Files (x86)\MSBuild\12.0\bin\Microsoft.Common.CurrentVersion.targets(1697,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "System.Web.Mvc, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors. 
```

Interestingly, on Azure we still have 3.0.0.0 in the GAC, but it's a matter of time before it gets updated.

**Comment by jvano** [comment]
Hi

Kudu will continue to run in Azure App Service. However, this repo will no longer be maintained.
If the problem persists and is related to running on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
