### ISSUE TITLE
Support ARM request and response if request from Geo ARM

### ISSUE THREAD

**Issue by suwatch** [projectkudu/kudu#1402]
For extension bridge, Geo will flow the ARM request as-is to kudu and forward the response as-is back to ARM.   In this scenario, Kudu is just like a mini RP and should handle request/response properly.

Sample response,

``` json
{
  "value": [
    {
      "id": "/subscriptions/9f0f1d5c-ef09-4a08-887a-0bcd74efc30b/resourceGroups/Default-Web-EastUS/providers/Microsoft.Web/sites/qqqjkljlk/instances/c4aeab8a302da87071539124e2f844282b6183268401500148d1990a47215d35",
      "name": "c4aeab8a302da87071539124e2f844282b6183268401500148d1990a47215d35",
      "type": "Microsoft.Web/sites/instances",
      "location": "East US",
      "tags": null,
      "properties": "c4aeab8a302da87071539124e2f844282b6183268401500148d1990a47215d35"
    }
  ]
}
```

**Comment by jvano** [comment]
Hi

Kudu will continue to run in Azure App Service. However, this repo will no longer be maintained.
If the problem persists and is related to running on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
