### ISSUE TITLE
Application Diagnostics

### ISSUE THREAD

**Issue by ryankekos** [projectkudu/kudu#1403]
In Windows Azure Pack there is no API that the WAP team has been able to give us to enable Application Diagnostics (aka Application Logging (File System) option in WAP) saying it was a complicated process with Kudu. Can this be enabled via Kudu?

**Comment by jvano** [comment]
Hi

Kudu will continue to run in Azure App Service. However, this repo will no longer be maintained.
If the problem persists and is related to running on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
