### ISSUE TITLE
Azure's git hook returns exit code 0 despite a failing deployment

### ISSUE THREAD

**Issue by nickdima** [projectkudu/kudu#1404]
Not sure if this is the right place to post this.

When deploying to Azure via Git, the deployment might fail with:

```
remote: An error has occurred during web site deployment.
remote: 
remote: Error - Changes committed to remote repository but deployment to website failed.
```

Despite this, the hook returns exit code 0 so the git command returns exit code 0.  This is unusable in a continuous integration environment where the build needs to fail if the git push step fails - otherwise the build will be falsely reported as successful.

Can the remote hook be configured or changed to return a non-zero exit code on failure or can you suggest workarounds?

**Comment by jvano** [comment]
Hi

Kudu will continue to run in Azure App Service. However, this repo will no longer be maintained.
If the problem persists and is related to running on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
