### ISSUE TITLE
Files in a shared project are not copied over

### ISSUE THREAD

**Issue by skendrot** [projectkudu/kudu#1407]
When you have a Shared Project in Visual Studio, and referenced by the web project, the files are not copied when deployed. This does work when using the Visual Studio publish tool. 

Reproduction steps:
1. Create a new ASP.NET web project.
2. Add a new shared project to the solution
3. Reference the shared project from the web project
4. Add some js files to the shared project. Put them under a folder named js
5. Reference the files in the web project by including a script tag in the index page that references the file locally

```
<script src="~/js/randomFile.js"></script>
```
1. Commit the solution. When the deployment finishes, open fiddler or browser developer tools. Browse to the page. Notice the file is 404. Try to browse to the js file directly, same problem.

**Comment by jvano** [comment]
Hi

Kudu will continue to run in Azure App Service. However, this repo will no longer be maintained.
If the problem persists and is related to running on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
