### ISSUE TITLE
error in sideband demultiplexer

### ISSUE THREAD

**Issue by psilva261** [projectkudu/kudu#1410]
Hi,

I got this error while deploying an app via git via Azure Websites:

<code>
fatal: The remote end hung up unexpectedly
error: error in sideband demultiplexer
To https://...@xxx.scm.azurewebsites.net:443/yyy.git
   d373646..39e03e1  develop -> master
</code>

A few minutes later the same command just worked. Seems to be a git issue ([discussion on SO](http://stackoverflow.com/q/4582849)), and it's possible to work around by adding another commit and just retry.

Cheers, Philip

**Comment by ilivewithian** [comment]
We deploy about 30 times a day and see this about twice a day. We've been through the linked stackoverflow question, but we still see the issue. Is this there anything that the azure team can do?

**Comment by davidebbo** [comment]
Can you give more details about your scenario? Are you git pushing directly to the site, or do you have continuous deployment set up? I would assume the latter given your deployment frequency, but just making sure.

**Comment by ilivewithian** [comment]
We are deploying via teamcity, which we use for our testing. We then do a simple git push like so:

    git.exe push https://username:password@oursite-staging.scm.azurewebsites.net:443/oursite.git HEAD:master --tags -f

**Comment by davidebbo** [comment]
Can you share the site name, either directly or [indirectly](https://github.com/projectkudu/kudu/wiki/Deploying-inplace-and-without-repository)/

**Comment by ilivewithian** [comment]
One of the sites is pbdev-software.azurewebsites.net and we see this when pushing to the staging slot. We have seen the same issue on a number of the sites in our subscription.

**Comment by davidebbo** [comment]
It could be that the client gets disconnected from the server because of a lack of activity. But that does not imply that the server side is failing. In those cases, what does it look like if you look at the deployment list in the portal? Does it claim that the deployment failed or was successful? You can also look at the full log from there.

From a quick look at some logs, it does seem like some operations are taking a very long time, e.g. I see:

    <entry time="2015-03-19T11:53:19.2586088Z">
      <message>Setting AssemblyInformationalVersion</message>
    </entry>
    <entry time="2015-03-19T11:54:42.744982Z">
      <message>v1.1.2737-dev</message>
    </entry>

Which seems to imply that the `Setting AssemblyInformationalVersion` step is taking 83 seconds. Not saying this is necessarily a problem (if it does expensive things), but looking through the deployment logs can give insight as to what's going on.

**Comment by ilivewithian** [comment]
Ok, that's odd, all that happens between `Setting AssemblyInformationalVersion` and the message `v1.1.2737-dev` is this:

    call D:\Python34\python.exe "%DEPLOYMENT_SOURCE%\tagrelease.py"

and in the python script:

    __author__ = 'mark'
    
    import subprocess
    import re
    import fileinput
    import os
    import string

    os.chdir(os.path.dirname(os.path.realpath(__file__)))

    output = subprocess.check_output(['git', 'describe', '--tags']).decode('utf-8')
    print(output)

Where `print(output)` produces the value `v1.1.2737-dev`. It's possible that the remote branch has a large number of tags, but even so, I wouldn't expect it to take 80 seconds.

I'll try to make sure that we clear down the number of pushed tags and see if that helps.

**Comment by davidebbo** [comment]
One thing you may want to try to isolate from deployment is to go into Kudu Console and run various actions individually (like the python one above). This way we can test in isolation whether they take longer than expected.

**Comment by MarkPieszak** [comment]
Seeing this today as well while deploying a project as well.
Do we know if this is an internal Azure problem?
Just ran into it twice in a row, one time the git push got further than the previous attempt.

Can't get the whole process to just finish.

**Comment by davidebbo** [comment]
Did the deployment end up failing on the server if you look at the history? In some cases, it just means the git client got disconnected from the output stream, with no ill effect on the deployment.

**Comment by MarkPieszak** [comment]
Can't find any logs of it anywhere in Azure, there any specific place you know I should be looking? @davidebbo Thanks for the quick response! 💯 💯

**Comment by davidebbo** [comment]
Look under Deployment Options for your web app, and you should see the deployment log. Click item for details.

**Comment by MarkPieszak** [comment]
So (good news at least) it finally finished the git push process and everything got uploaded! 
Interestingly enough, when looking there, the previous attempts didn't get logged at all. Very strange. Seems like I'll never know what the issue was now :( haha

**Comment by davidebbo** [comment]
It it's the same commit ID, it would replace the old entries. If you hit this again, try looking in portal to see what state things are in.

**Comment by jvano** [comment]
Hi

Kudu will continue to run in Azure App Service. However, this repo will no longer be maintained.
If the problem persists and is related to running on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
