### ISSUE TITLE
Extended characters get corrupted in WebJobs output

### ISSUE THREAD

**Issue by davidebbo** [projectkudu/kudu#1418]
This comes from [StackOverflow](http://stackoverflow.com/questions/27432509/encoding-issue-on-azure-webjobs).

The WebJob has:

```
using System;

namespace TestAccents
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("e é à a");
        }
    }
}
```

And the output is corrupted:

![output](http://i.stack.imgur.com/otqF5.png)

So clearly there is an encoding issue somewhere.

**Comment by ahmelsayed** [comment]
btw, I think this might be trickier than just changing the encoding. #1420 fixes this issue but regresses international characters from node. It seems that node is able to set the output to UTF8, while standard .NET isn't. Assuming one encoding will break the other for non ASCII characters
