### ISSUE TITLE
WebJobs: Display log entries from logs stored in blob or table storage

### ISSUE THREAD

**Issue by c-eliasson** [projectkudu/kudu#1421]
As per [this discussion](http://stackoverflow.com/questions/23491907/azure-how-to-enable-full-webjob-logs#comment-43439927) on StackOverflow, I'm opening up a feature request issue.

At `https://[mysite].scm.azurewebsites.net/azurejobs/#/jobs/continuous/[myjob]` the log output is limited to X number of lines, then you receive this message:

> Reached maximum allowed output lines for this run, to see all of the job's logs you can enable website application diagnostics

Enabling website application diagnostics indeed give me the full job logs, in my table storage, but I still can't see the log output at the above mentioned address. 

It would be nice to be able to configure where the WebJob Details site pulls its logs from, so that I can keep monitor my WebJobs through that site, even though they are continuous.

**Comment by dirkju** [comment]
+1

**Comment by mteper** [comment]
:+1:

**Comment by bloomk** [comment]
+1

**Comment by gregberns** [comment]
+1

**Comment by hcapp01** [comment]
+1

**Comment by willshao** [comment]
+1

**Comment by itsmaryann** [comment]
+1

**Comment by ross2411** [comment]
+1

**Comment by kirajhpang** [comment]
+1

**Comment by kaiokassiano** [comment]
+1

**Comment by tirish** [comment]
+1

**Comment by srp324** [comment]
+1

**Comment by jvano** [comment]
Hi

Kudu will continue to run in Azure App Service. However, this repo will no longer be maintained.
If the problem persists and is related to running on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
