### ISSUE TITLE
ProcessExplorer should flatten http callback events

### ISSUE THREAD

**Issue by ahmelsayed** [projectkudu/kudu#1426]
![image001](https://cloud.githubusercontent.com/assets/645740/5551590/3809f678-8b8d-11e4-9140-29b52726167f.png)

**Comment by jvano** [comment]
Hi

Kudu will continue to run in Azure App Service. However, this repo will no longer be maintained.
If the problem persists and is related to running on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
