### ISSUE TITLE
Updating iisnode.yml takes too much time

### ISSUE THREAD

**Issue by koistya** [projectkudu/kudu#1434]
On the following step, deployment slows down and resumes after about a minute:

![img](http://snag.gy/eUJcD.jpg)

**Comment by davidebbo** [comment]
Can you give more details about your scenario? Sharing your test repo on GitHub would be best. This does not normally happen.

**Comment by koistya** [comment]
Yep, I will prepare a testing repo.

**Comment by davidebbo** [comment]
Also, you can look at the Kudu trace (in `LogFiles\kudu\trace`), which may give a better idea where the time is spent.

**Comment by koistya** [comment]
There is no `D:\home\site\LogFiles\kudu` folder.

**Comment by davidebbo** [comment]
`D:\home\LogFiles\kudu\trace`

**Comment by koistya** [comment]
Right! But there are lots of similar files, not sure how to find something useful in that folder:

![img](http://snag.gy/26AXw.jpg)

But here is an excerpt from the `D:\site\deployments\xxx\log.xml` file:

```xml
    <entry time="2015-01-10T14:41:08.0535729Z" id="e7619146-7b15-49bf-9ede-80f9f2880ac2" type="0">
      <message>Updating iisnode.yml at D:\home\site\wwwroot\iisnode.yml</message>
    </entry>
    <entry time="2015-01-10T14:44:07.903936Z" id="898d8ae6-1b6e-474c-bb5f-ca7f1194cb14" type="0">
      <message>gulp-render@0.2.2 node_modules\gulp-render</message>
    </entry>
```

As far as I understand, 3 minutes are spent on that `Update iisnode.yml` step.

**Comment by davidebbo** [comment]
You can clean the folder before running your scenario. You should see one entry for the deployment.

**Comment by regisbsb** [comment]
Same here more than 10 minutes

**Comment by jvano** [comment]
Hi

Kudu will continue to run in Azure App Service. However, this repo will no longer be maintained.
If the problem persists and is related to running on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
