### ISSUE TITLE
Webjobs: Improve hosting of custom functions for continous jobs

### ISSUE THREAD

**Issue by bunceg** [projectkudu/kudu#1436]
Hi,

With the move to microservices and azure websites seemingly being the backbone for a lot of this in the future  IMO the webjob sdk is a little clunky for migrating custom long running back end functionality. I need to declare a job host, then invoke my method via a call method, and then perform a run and block.

When the job host is eventually stopped it appears that I cannot get access to the cancellation token held internally by the job host to perform my own clean up and stop processing, so I am left with running my own cleanup code after the run and block has finished. This doesn't write to any of the dashboard logs or interact wi any of the sdk functionality we want job host for.

What would be helpful is an event or some means for me to hook into the job host pipeline so that I can intercept stages in the pipeline and inject my own functionality, e.g. On starting, on started, on stopping, on stopped etc.

I could write my own implementation of the job host that hooks into the notification file etc, but the sdk is the recommended way to use web jobs as it provides better integration with the azure website framework; it's just that all the focus for it seems to be on using it for queues, blobs etc using the sdk methods whereas trying to move brownfield functionality to the webjob architecture means moving a lot of custom code with minimal change from what is, effectively, an on-premise windows service or azure worker role is highly attractive, and this appears to be harder than it could be.

Thanks

**Comment by davidebbo** [comment]
Valid topic, but not the right place to bring it up as the WebJobs SDK is not part of Kudu. Could you post to the [Websites Forum](https://social.msdn.microsoft.com/Forums/azure/en-US/home?forum=windowsazurewebsitespreview) instead? I'll make sure to point the right SDK people to it so they can respond. Thanks!

**Comment by bunceg** [comment]
Ok, done

**Comment by davidebbo** [comment]
Thanks. I pinged some SDK people. Hopefully they can reply sometime soon.
