### ISSUE TITLE
Shared configuration on IIS

### ISSUE THREAD

**Issue by hitchhiker** [projectkudu/kudu#1438]
Had to change SiteManager.cs:

        private static ServerManager GetServerManager()
        {
            return new IIS.ServerManager();
        }

Removed the reference to app host in system32. Seems to work well now. Otherwise it's using the wrong applicationhost config (that has been redirected to shared configuration) to setup IIS sites.

**Comment by davidebbo** [comment]
Not enough info here. Can you describe what you are trying to do, and what issues you are running into? Thanks!

**Comment by hitchhiker** [comment]
My IIS is using 'shared configuration'. That relocates the applicationhost.config to a new location. By specifying the location of that file in the ServerManger constructor you've made Kudu unable to read/affect the IIS config.

Removing the constructor parameter and using the default constructor allowed Kudu to correctly continue.

**Comment by davidebbo** [comment]
I just gave this a quick try and didn't have much luck. When using `return new IIS.ServerManager()`, it just hangs when creating a site in Kudu. So it's not equivalent to what we had before on a default install. If you find a safe change that helps your scenario without affecting the existing scenario, please send a pull request and we will review.

**Comment by hitchhiker** [comment]
That's very strange, I know it works on non-shared environments like that as I've used it on another project. Also, as specified here (http://msdn.microsoft.com/en-us/library/microsoft.web.administration.servermanager%28v=vs.90%29.aspx) it merely uses the default path.

It may well have something to do with permissions? Is there any way you could check it on another box, I can't imagine why you'd *need* to specify the path.

**Comment by davidebbo** [comment]
Same on other machine. Apparently, without passing anything, it's using iisexpress instead of iis. i.e. it's finding applicationhost.config in `%USERPROFILE%\Documents\IISExpress\config`.

Conceivably, we could make it configurable thing. e.g. `applicationHostConfigurationPath` in web.config, that we would set to `%windir%\system32\inetsrv\config\applicationHost.config` by default, and you could set to empty in yours (or remove altogether to make cause it to use the default ctor).

**Comment by hitchhiker** [comment]
..a config entry would be welcome! Yes, I think the default should probably be what you had it as (most people invariably will need that).. However it's difficult to debug when this becomes a problem, maybe place a note in the setup doc because..

-The ServerManager actually writes the entries into the wrong app-config..
-Directories appear in /apps partially.
-Kudu hangs at create.
-Admin is left wondering what happened. No error really, just a long long hang on create.

**Comment by davidebbo** [comment]
Would you like to take a crack at a pull request for it? It's the fastest way to make things happen! :)

**Comment by davidebbo** [comment]
Fixed by #2036, courtesy of @WiredUK.
