### ISSUE TITLE
deploying to azure 

### ISSUE THREAD

**Issue by dtmuturi** [projectkudu/kudu#1439]
Hi, am trying to deploy my site to azure with git an it works well. what I want though is to deploy it to the site folder and not the wwwrooot on azure because of security reasons. After some reaserch i got some hints from stackoverflow http://stackoverflow.com/questions/18837772/azure-git-deploy-into-site-folder-not-wwwroot on the issue but it doesn't detail how and where to fix the issue like where are the app settings they refer to needed to set the key value pairs. 
Any help will be highly appreciated.

**Comment by davidebbo** [comment]
It's referring to App Settings that you set in the Azure portal for your site.

**Comment by dtmuturi** [comment]
hi David, thanks for prompt reply,

i changed the azure settings as on the screenshot below but still doesent
work, am i doing it wrong or what exactly am i to do?

**Comment by davidebbo** [comment]
It looks like your screenshot didn't get included. Can you repost?

**Comment by dtmuturi** [comment]
[image: Inline image 1]

**Comment by davidebbo** [comment]
Still not working for me. Are you able to see your image on Github?

**Comment by dtmuturi** [comment]
Hi David ,

no i cant view it on git hub either. No worries though, i managed to solve
the issue after hours of trial and error by setting the SCM PATH to ..\app

the forward slash was the major problem.

Thank you for all the assistance.

regards.

**Comment by davidebbo** [comment]
Ah yes, there is some quirk about forward slashes that cause them to get corrupted in the 'git push' scenario. Backslash is the way to go. Glad you figured it out!

**Comment by dtmuturi** [comment]
Hi,

I'd like to add you to my professional network on LinkedIn.

- derrick

Confirm that you know derrick: https://www.linkedin.com/e/v2?e=-wb063i-iagmi1r9-39&amp;a=preRegInvite&amp;tracking=eml-guest-invite-cta&amp;ek=invite_guest&amp;sharedKey=OpWTF49T&amp;invitationID=6011813427524169728


You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=-wb063i-iagmi1r9-39&amp;t=lun&amp;midToken=AQFmrFVhGEd36Q&amp;ek=invite_guest&amp;loid=AQGdsQpxuqD5QgAAAU25AhCCNAw26etq0wkUnXHEeajpEw0Zh66SNAhYboNfqiGoAVAr5IZmcWBJvo9HucgiqTCMJE6zyxlJyl561Jj3I_apT8KfUtzwHZhZmf4e9-Go3lqZ8Fav0_qAySx-oOh81VOR90r8utDjtUsnKVVy7bDHPWWAvtehY07bCUryrY0MNVE4&amp;eid=-wb063i-iagmi1r9-39 Learn why we included this at the following link: https://www.linkedin.com/e/v2?e=-wb063i-iagmi1r9-39&a=customerServiceUrl&ek=invite_guest&articleId=4788
&copy; 2015, LinkedIn Corporation. 2029 Stierlin Ct. Mountain View, CA 94043, USA

**Comment by dtmuturi** [comment]
Hi,

I'd like to add you to my professional network on LinkedIn.

- derrick

Confirm that you know derrick: https://www.linkedin.com/e/v2?e=-i8zq6q-iagmi1uf-3i&amp;a=preRegInvite&amp;tracking=eml-guest-invite-cta&amp;ek=invite_guest&amp;sharedKey=6y1kYHqr&amp;invitationID=6011813427725496320


You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=-i8zq6q-iagmi1uf-3i&amp;t=lun&amp;midToken=AQFmrFVhGEd36Q&amp;ek=invite_guest&amp;loid=AQHgtVeFVW8r5AAAAU25AiJ7kf8MWDi2b0HR-YJFZW22fmAXXAvb9Q9519odV2C_OiboLFX8LKC4KvgSRhwZzcBGjhLSN2_B9gPRTs2crqAAnUaIxmZUwE3GtTuk4RWBekZNUzdo-HI7yNYXIDzKKIoL3KUeZPn9GNxyNsKR7ai_Flvy59GwzfbJtazpvcGDOA7U&amp;eid=-i8zq6q-iagmi1uf-3i Learn why we included this at the following link: https://www.linkedin.com/e/v2?e=-i8zq6q-iagmi1uf-3i&a=customerServiceUrl&ek=invite_guest&articleId=4788
&copy; 2015, LinkedIn Corporation. 2029 Stierlin Ct. Mountain View, CA 94043, USA

**Comment by dtmuturi** [comment]
Hi,

I'd like to add you to my professional network on LinkedIn.

- derrick

Confirm that you know derrick: https://www.linkedin.com/e/v2?e=-w1n3gn-iagmi1ob-2z&amp;a=preRegInvite&amp;tracking=eml-guest-invite-cta&amp;ek=invite_guest&amp;sharedKey=U5vuxsse&amp;invitationID=6011813427339632642


You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=-w1n3gn-iagmi1ob-2z&amp;t=lun&amp;midToken=AQFmrFVhGEd36Q&amp;ek=invite_guest&amp;loid=AQEbLdpO0lvkhAAAAU25AmZPeuQRaxq7fHoadQttoiSRfT2DN-g4xJWWyuQTyZzDsu3PKeRO5nEUct1jSRyfBQoHJucFkFqdOrdIOO-7IjThX1z-qfpcTngdveNA1K6bl9SK6ECPgeSKwk7ZzZ87iw2qZ0kk-3Cz38wz1TMnmFvkc7k6d-73ekHpMJ2JPi2hZGUp&amp;eid=-w1n3gn-iagmi1ob-2z Learn why we included this at the following link: https://www.linkedin.com/e/v2?e=-w1n3gn-iagmi1ob-2z&a=customerServiceUrl&ek=invite_guest&articleId=4788
&copy; 2015, LinkedIn Corporation. 2029 Stierlin Ct. Mountain View, CA 94043, USA

**Comment by davidebbo** [comment]
Why are all those LinkedIn invitations ended up posted on this GitHub issue?

**Comment by dtmuturi** [comment]
Hi David,

Sorry about that, was sending invites to my email contacts using the
linkedIn app, must have sent it to all.

Is there a way to delete them?
My apologies once more

Regards,

**Comment by davidebbo** [comment]
I see. No problem, I deleted them.

**Comment by dtmuturi** [comment]
Thank you sir, appreciated.

**Comment by dtmuturi** [comment]
derrick muturi would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/blink?simpleRedirect=0Od3oOcPoVcPcTczgPcjwNcj0Sfkh9rCZFt65QqnpKqipBsTdUtnoRljRVpkJApn9xq7cCt7xBt5ZQs6lzoS4ZsTgCrT9Bq3RJ9zsZqmMCcj1vsClArCBJpn9vt7dBtmtvt7dOqmoZqSkCpnhFtCV9pSlipn9Mfm4Cq3oJrDtEtPBOomAJrCsPrz5TbjRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I6011813486659661824_500&markAsRead=

View derrick muturi&#39;s profile: https://www.linkedin.com/blink?markAsRead=&msgID=I6011813486659661824_500&simpleRedirect=q3p5dOlKtSxTen9xqkkT9mVDcSUNtQkT9iRIr7lKbnhUpnhvpmNFpCZOs2QUbmZOpmwJcj1vsClArCBJpn9vt7dBtmtvt7dOqmoJr6RBfmNFomR5qT9Q9DhUpnhvpmNFpCZOs2QUbmZOpmwJcj1vsClArCBJpn9vt7dBtmtvt7dOqmoJr6RBfmJOt2oOczAVcP8QdP8Zp6A_tSlFtyZBr6BCrT9MbSRJrScLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE

You are receiving Reminder emails for pending invitations. Unsubscribe here: https://www.linkedin.com/blink?simpleRedirect=1JrSd5cylytmxQqmt5cylVr71Bsz0Q9jhAcScPd3cMpmcVdz5xczBCc64UdSgMcj4Mc30Mc30MpCcOemgMcj1xcj8Vcj4Rp3wVcPdxemhBoClCoSgSe3hxcjxydmgScP0NcSdCcjhBoPkMc48O9nBIs6lOfmNFomRB9z0Sc30OfmhF9z8Qdz8PdzAPcPsOd3cNe34Nc3oZp6BD9z4MnT9Bp6VFrmlOnThPpnlDnThPsCBCfmJB9DhUpnhvoDlPrDkJdiRytndKtiQNc5ZOpmhKqmRBsBZQsSlRpRZQsT9FpyRIrmkZpSVFqSdxsDgCrSZDfngCq3oJrDtEtPBOomAJrCsPrz5TbjRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I6011813486659661824_500&markAsRead=

You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/blink?simpleRedirect=1EdyRKtSxTen9xqiRKpPdKcnsJfmhFpiphhzxVdANjrzhbhzleqDBNenFdmnhysm95kSFvsnlMumJqtj5cbmBqknBSel9IpmxaumRHpQgSt6ZclldWoTtcqklki4VLbjBpgm5ftmhKe59FtlkPcRFalAcMqj8JnSNglD0PhldUl6sUomNikjh9skN1dRxTpQ52gRpAd5pNh7dSsTdajnh5q5tNmmBhd38JmkpPrSdWmmwMknhChAFMgQpTcDx9cnsUsPxDblAOqCsPlk51gk5GkmhJh7t2uAVchl51fmhFrSMCcj1vsClArCBJpn9vt7dBtmtvt7dOqmoZqSkCkjoPp4l7q5p6sCR6kk4ZrClHrRhAqmQCrDlIfngCq3oJrDtEtPBOomAJrCsPrz5TbjRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&amp;msgID=I6011813486659661824_500&amp;markAsRead=This email was intended for projectkudu/kudu. Learn why we included this at the following link: https://www.linkedin.com/blink?simpleRedirect=e3wTd3RAimlIoSBQsC4Ccj1vsClArCBJpn9vt7dBtmtvt7dOqmoZqSkCr79lpmdFtD9BkT9BrmZQsTlzfm4Cq3oJrDtEtPBOomAJrCsPrz5TbjRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I6011813486659661824_500&markAsRead=
&copy; 2015, LinkedIn Corporation. 2029 Stierlin Ct. Mountain View, CA 94043, USA

**Comment by dtmuturi** [comment]
derrick muturi would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/blink?simpleRedirect=0UczsVdz4QczkTczgPcjwNcj0Sfkh9rCZFt65QqnpKqipkejh6l5tMjPRVpkJApn9xq7cCt7xBt5ZQs6lzoS4ZsTgCrT9Bq3RJ9zsZqmMCcj1vsClArCBJpn9vt7dBtmtvt7dOqmoZqSkCpnhFtCV9pSlipn9Mfm4Cr3kJrzxHuzBOomAJqjcSc69TbjRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I6011813486894542848_500&markAsRead=

View derrick muturi&#39;s profile: https://www.linkedin.com/blink?markAsRead=&msgID=I6011813486894542848_500&simpleRedirect=r3l5dOlKe6JWen9xqkkT9mAPdz1ytQkT9iRIr7lKbnhUpnhvpmNFpCZOs2QUbmZOpmwJcj1vsClArCBJpn9vt7dBtmtvt7dOqmoJr6RBfmNFomR5qT9Q9DhUpnhvpmNFpCZOs2QUbmZOpmwJcj1vsClArCBJpn9vt7dBtmtvt7dOqmoJr6RBfmJOt2oOczAVcP8QdP8Zp6A_tSlFtyZBr6BCrT9MbSRJrScLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE

You are receiving Reminder emails for pending invitations. Unsubscribe here: https://www.linkedin.com/blink?simpleRedirect=1JrSd5cylytmxQqmt5cylVr71Bsz0Q9jhAcScPd3cMpmcVdz5xczAUpzBCd6gMcj4Mc30Mc30MpCcOej1ypm4Tc6oPojAMcPxCcz4QemdBdPkTejsOpjlBpjoQozlAem4QoPxCcjhBoPkMc48O9nBIs6lOfmNFomRB9z0Sc30OfmhF9zwOdPAScjgOdjsOd3cNe34Nc3oZp6BD9z4MnT9Bp6VFrmlOnThPpnlDnThPsCBCfmJB9DhUpnhvoDlPrDkJdiRytndKtiQNc5ZOpmhKqmRBsBZQsSlRpRZQsT9FpyRIrmkZpSVFqSdxsDgCrSZDfngCr3kJrzxHuzBOomAJqjcSc69TbjRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I6011813486894542848_500&markAsRead=

You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/blink?simpleRedirect=1IdiRKe6JWen9xqiRFcPoMoDsJfmhFpipBcAoUdn9Ok45WlBdxcAcUkQJdkS5vsjlorABMdmdOrTF2d311t4ZLiDtbelh8lTl5m55qdAVvl7BFjklPhTxntC5ilPlmgD5MkndWp3tRpTFad4tmj71UoSFfqlh6sS5LjSZTsPh9cj1MgA5hd6QRlR1xcShglQoQd3lnd751nR9fgA5pr6B8oAJ5glxTqDdfcRdKiCYQgjdvhCVhlmNli6h9j5hotABhs39qlS4OqCsPlk51gnt8sBlgrSxkrT5Oi551fmhFrSMCcj1vsClArCBJpn9vt7dBtmtvt7dOqmoZqSkCkjoPp4l7q5p6sCR6kk4ZrClHrRhAqmQCrDlIfngCr3kJrzxHuzBOomAJqjcSc69TbjRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&amp;msgID=I6011813486894542848_500&amp;markAsRead=This email was intended for projectkudu/kudu. Learn why we included this at the following link: https://www.linkedin.com/blink?simpleRedirect=e3wTd3RAimlIoSBQsC4Ccj1vsClArCBJpn9vt7dBtmtvt7dOqmoZqSkCr79lpmdFtD9BkT9BrmZQsTlzfm4Cr3kJrzxHuzBOomAJqjcSc69TbjRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I6011813486894542848_500&markAsRead=
&copy; 2015, LinkedIn Corporation. 2029 Stierlin Ct. Mountain View, CA 94043, USA

**Comment by dtmuturi** [comment]
derrick muturi would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/blink?simpleRedirect=0MczcSejgRczsTczgPcjwNcj0Sfkh9rCZFt65QqnpKqipOskxpqP5VdzRVpkJApn9xq7cCt7xBt5ZQs6lzoS4ZsTgCrT9Bq3RJ9zsZqmMCcj1vsClArCBJpn9vt7dBtmtvt7dOqmoZqSkCpnhFtCV9pSlipn9Mfm4CpPoJt6FGtPBOomAJsjpNuzxFbjRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I6011813486500282368_500&markAsRead=

View derrick muturi&#39;s profile: https://www.linkedin.com/blink?markAsRead=&msgID=I6011813486500282368_500&simpleRedirect=pPp5dOlQqCFTen9xqkkT9n4SsnEUqkkT9iRIr7lKbnhUpnhvpmNFpCZOs2QUbmZOpmwJcj1vsClArCBJpn9vt7dBtmtvt7dOqmoJr6RBfmNFomR5qT9Q9DhUpnhvpmNFpCZOs2QUbmZOpmwJcj1vsClArCBJpn9vt7dBtmtvt7dOqmoJr6RBfmJOt2oOczAVcP8QdP8Zp6A_tSlFtyZBr6BCrT9MbSRJrScLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE

You are receiving Reminder emails for pending invitations. Unsubscribe here: https://www.linkedin.com/blink?simpleRedirect=1JrSd5cylytmxQqmt5cylVr71Bsz0Q9jhAcScPd3cMpmcVdz5xczAOdS8PdCgMcj4Mc30Mc30MpCcOejoNdPkVpzwRdm9BoSpBcShAdP1AejoOcj0Pdj4NczdCpmgRdmcNdChCcjhBoPkMc48O9nBIs6lOfmNFomRB9z0Sc30OfmhF9z0OcPoVd3kOdPsOd3cNe34Nc3oZp6BD9z4MnT9Bp6VFrmlOnThPpnlDnThPsCBCfmJB9DhUpnhvoDlPrDkJdiRytndKtiQNc5ZOpmhKqmRBsBZQsSlRpRZQsT9FpyRIrmkZpSVFqSdxsDgCrSZDfngCpPoJt6FGtPBOomAJsjpNuzxFbjRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I6011813486500282368_500&markAsRead=

You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/blink?simpleRedirect=1DdyRQqCFTen9xqiRNdD5We6AJfmhFpipgp6J5hklngktGrjlKe3BjdzlmqRhdj6hvgnBJgD14oj8OlnkJkmdotRhAlnxKc5BPrAp5p55vkB8Vgm9mdRwOdTFhpmYRumwPjDhcdjoSdlhlkApWrR92pSRHkTxNoTsRckwScld6tjBvtD58u518s5FVikdAskxjhjl8kRxicmR5snh6czxAcPpgqQRlrPxCkCBdtkYOrRtom6oRdSFFmn98gRxydkN1qC5BiCcOqCsPlk51gk5qhzpktCxepjpWi551fmhFrSMCcj1vsClArCBJpn9vt7dBtmtvt7dOqmoZqSkCkjoPp4l7q5p6sCR6kk4ZrClHrRhAqmQCrDlIfngCpPoJt6FGtPBOomAJsjpNuzxFbjRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&amp;msgID=I6011813486500282368_500&amp;markAsRead=This email was intended for projectkudu/kudu. Learn why we included this at the following link: https://www.linkedin.com/blink?simpleRedirect=e3wTd3RAimlIoSBQsC4Ccj1vsClArCBJpn9vt7dBtmtvt7dOqmoZqSkCr79lpmdFtD9BkT9BrmZQsTlzfm4CpPoJt6FGtPBOomAJsjpNuzxFbjRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I6011813486500282368_500&markAsRead=
&copy; 2015, LinkedIn Corporation. 2029 Stierlin Ct. Mountain View, CA 94043, USA

**Comment by dtmuturi** [comment]
derrick muturi would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/blink?simpleRedirect=30OcPoVd3kOdPsOd3cNe34Nc3oZh4BKrSBQonhFtCVF9D9Ni5BHcnASfnBBiShBsC5EsOpQu6lQnThMpmdzojRPt2pLsClEfmQCdPRFr2oNc5ZOpmhKqmRBsBZQsSlRpRZArCZzpncZqSkCpnhFtCV9pSlipn9Mfm4CsjcJpDtVpC4NoCAJsjpNuzxFbjRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I6011813486500282368_500&markAsRead=

View derrick muturi&#39;s profile: https://www.linkedin.com/blink?markAsRead=&msgID=I6011813486500282368_500&simpleRedirect=74PhjsBpDtVpC4NoCB5dOlNdD5We6B5dOkJr6NRryRQu6lQnSlIqmpLsD0Je2RLsClEbj4MnT9Bp6VFrmlOnThPpnlDnShKrSdBsORIrmkZr6BxrklHsDgCt7xBt5ZBr6BCrT9MbjwJrT9Bq2QNc5ZOpmhKqmRBsBZQsSlRpRZArCZzpncJr6RBfmJOt2oOczAVcP8QdP8Zp6A_tSlFtyZBr6BCrT9MbSRJrScLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE

You are receiving Reminder emails for pending invitations. Unsubscribe here: https://www.linkedin.com/blink?simpleRedirect=rmZzhj8BoDlEt6BDhj8BumNMpn8Md2kQp3dzcPgPc6lzejoNoj8VcztycPpAc34Nc30Mc30Mc6pzczAScjsRemoUdjlypmdCpjdAp3sMp3AScz4McPkNcj8PpClAdjlzcjpApz4QpmcRc312cylVr71BszRIqm5JpioMdz0MczRAqioMczcSejgRczsTczgPcjwNcj0SfmhFpOoNc5ZOpmhKqmRBsBZQsSlRpRZArCZzpncZqSkCt7xBt5ZytndKtiQSbm9RsSVRbj4MnT9Bp6VFrmlOnThPpnlDnShKrSdBsORIrmkZpSVFqSdxsDgCrSZDfngCsjcJpDtVpC4NoCAJsjpNuzxFbjRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I6011813486500282368_500&markAsRead=

You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/blink?simpleRedirect=74PbmpTumpxcm9Fbn4SsnEUqiQZp6BB9Cd9tzcQqR9xrkpBoA9erANKkAUQgDxEmk52nSkNs7tgdlhWcTF3pTpyi6hTiD0McTh4jPcSiDBqp3cVlClJj7lhlC9ehkZxqClLomx3il13dCgVhz1WmDcPiStLtzlCtmxpd4sMmlpDknlKm4Bvs7h3p4FWc6pSmCtypDldc4dplChFj4dfqQZGhR1Mq5xSk7l5sR9mbk9pdlpSe5wVrAlGp6hKkmVIhABzdA5bsQhKhjhlgk51pT0VkS92jzligz95kk4Zp6BLr2oNc5ZOpmhKqmRBsBZQsSlRpRZArCZzpncZqSkCkjoPp4l7q5p6sCR6kk4ZrClHrRhAqmQCrDlIfngCsjcJpDtVpC4NoCAJsjpNuzxFbjRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&amp;msgID=I6011813486500282368_500&amp;markAsRead=This email was intended for projectkudu/kudu. Learn why we included this at the following link: https://www.linkedin.com/blink?simpleRedirect=0Ue3sQfmh9pmNzqnhOoioNc5ZOpmhKqmRBsBZQsSlRpRZArCZzpncZqSkCr79lpmdFtD9BkT9BrmZQsTlzfm4CsjcJpDtVpC4NoCAJsjpNuzxFbjRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I6011813486500282368_500&markAsRead=
&copy; 2015, LinkedIn Corporation. 2029 Stierlin Ct. Mountain View, CA 94043, USA

**Comment by dtmuturi** [comment]
derrick muturi would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/blink?simpleRedirect=3wOdPAScjgOdjsOd3cNe34Nc3oZh4BKrSBQonhFtCVF9BgVd4pklT1ffnBBiShBsC5EsOpQu6lQnThMpmdzojRPt2pLsClEfmQCdPRFr2oNc5ZOpmhKqmRBsBZQsSlRpRZArCZzpncZqSkCpnhFtCV9pSlipn9Mfm4CrPkJtmJCq64NoCAJqjcSc69TbjRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I6011813486894542848_500&markAsRead=

View derrick muturi&#39;s profile: https://www.linkedin.com/blink?markAsRead=&msgID=I6011813486894542848_500&simpleRedirect=6YRhjsBtmJCq64NoCB5dOlFcPoMoDt5dOkJr6NRryRQu6lQnSlIqmpLsD0Je2RLsClEbj4MnT9Bp6VFrmlOnThPpnlDnShKrSdBsORIrmkZr6BxrklHsDgCt7xBt5ZBr6BCrT9MbjwJrT9Bq2QNc5ZOpmhKqmRBsBZQsSlRpRZArCZzpncJr6RBfmJOt2oOczAVcP8QdP8Zp6A_tSlFtyZBr6BCrT9MbSRJrScLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE

You are receiving Reminder emails for pending invitations. Unsubscribe here: https://www.linkedin.com/blink?simpleRedirect=rmZzhj8BoDlEt6BDhj8BumNMpn8Md2kQp3dzcPgPc6lzejoNoj8Ve6oVpzhAc34Nc30Mc30Mc6pzczAMoClxdP1CcS4Vc3cUpz8Nd3BzpjsRdPATcCkRpmkSd68Rp3Bxd6cUpz4QpmcRc312cylVr71BszRIqm5JpioMdz0MczRAqioUczsVdz4QczkTczgPcjwNcj0SfmhFpOoNc5ZOpmhKqmRBsBZQsSlRpRZArCZzpncZqSkCt7xBt5ZytndKtiQSbm9RsSVRbj4MnT9Bp6VFrmlOnThPpnlDnShKrSdBsORIrmkZpSVFqSdxsDgCrSZDfngCrPkJtmJCq64NoCAJqjcSc69TbjRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I6011813486894542848_500&markAsRead=

You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/blink?simpleRedirect=6YRbnlHpCxxcm9FbmAPdz1ytOQZp6BB9B1AhSRigRtJrCxSu4BUgThxoOQOoCYMk5hyik8VmD5Bt6pol7dPcmxJjBsMjCgOqkN5dkZduDF2hC8OmmATj6JRtB1phQgNtCpFl6Rfqm9jlz9iemJPs7dgi6Fqr44MrBkQiBdjckJocDlbu6tkoBdSdlhNt31aplsPmnl3sQVGt4BchzlWiRB4l4l4hPcJjmlehkBTokB6nT5dpCtApAZolmhbrnwTsP5WoBZgbkhKhjhlgk51tPdCekVxpAtNiAp8kk4Zp6BLr2oNc5ZOpmhKqmRBsBZQsSlRpRZArCZzpncZqSkCkjoPp4l7q5p6sCR6kk4ZrClHrRhAqmQCrDlIfngCrPkJtmJCq64NoCAJqjcSc69TbjRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&amp;msgID=I6011813486894542848_500&amp;markAsRead=This email was intended for projectkudu/kudu. Learn why we included this at the following link: https://www.linkedin.com/blink?simpleRedirect=0Ue3sQfmh9pmNzqnhOoioNc5ZOpmhKqmRBsBZQsSlRpRZArCZzpncZqSkCr79lpmdFtD9BkT9BrmZQsTlzfm4CrPkJtmJCq64NoCAJqjcSc69TbjRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I6011813486894542848_500&markAsRead=
&copy; 2015, LinkedIn Corporation. 2029 Stierlin Ct. Mountain View, CA 94043, USA

**Comment by dtmuturi** [comment]
derrick muturi would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/blink?simpleRedirect=0Od3oOcPoVcPcTczgPcjwNcj0Sfkh9rCZFt65QqnpKqipBsTdUtnoRljRVpkJApn9xq7cCt7xBt5ZQs6lzoS4ZsTgCrT9Bq3RJ9zsZqmMCcj1vsClArCBJpn9vt7dBtmtvp6VLoSlPfmJB9ClQqnpKimtBkClOs3Rx9DAJr7BVpC4NoCAJrCsPrz5TbjRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I6011813486659661824_500&markAsRead=

View derrick muturi&#39;s profile: https://www.linkedin.com/blink?markAsRead=&msgID=I6011813486659661824_500&simpleRedirect=1VhjsBr7BVpC4NoCB5dOlKpPdKcnt5dOkJr6NRryRQu6lQnSlIqmpLsD0Je2RLsClEbj4MnT9Bp6VFrmlOnThPpnlDnShKrSdBsORIrmkZr6BxrklHsDgCt7xBt5ZBr6BCrT9MbjwJrT9Bq2QNc5ZOpmhKqmRBsBZQsSlRpRZArCZzpncJr6RBfmJOt2oOczAVcP8QdP8Zp6A_tSlFtyZBr6BCrT9MbSRJrScLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE

You are receiving Reminder emails for pending invitations. Unsubscribe here: https://www.linkedin.com/blink?simpleRedirect=6RLoQkO9m9Rq7hFpQkO9nBIs6lOc3gBd6gPoPcQcP1BoPAScm4OemoMojwTp30Ncj0Mc30Mc31CoP8Vp30Nc64NczANcjlAe3APcS4Vp6lypmpzp3oUd64Ne68Rp3oPc34PoSoNd6lzdj0Mgz8BumNMpn8Zr6BxrmkCc3oMc38Zp6ACczgSczcSejcPdP8QcP4Ucj4MdzRAqmsCcj1vsClArCBJpn9vt7dBtmtvp6VLoSlPfmJB9DhUpnhvoDlPrDkJdyRytndKtiQNc5ZOpmhKqmRBsBZQsSlRpRZArCZzpncJr6RBfmtKqmJzon9Q9CZLpPRQ9DAJr7BVpC4NoCAJrCsPrz5TbjRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I6011813486659661824_500&markAsRead=

You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/blink?simpleRedirect=uiRIunBCoj5yqiRKpPdKcnsJfmhFpipJt5B2uyRGkQ4TkTxphktvimFUp5kRrkNUknh5pTpFsR9ItB0SqSl4jzxRpyQUi6lpd6txdk5KozxdjSoVomFie3gSe75LhSl6hCpjk7tegQsSq6tLi3wRcDled7EUrTl4qmVSsAV5qAMTellGjAJVcBpRtmRpjRZkc6RPiAkJlRgMslhgp4VUjSBvkPtGgnAMlAlGqn18pChKtShHkRxlsBpli6NkpCwTqQNzrBZ4rAkQlk51gmtyizsPkANClSJ2hB51fmhFrSMCcj1vsClArCBJpn9vt7dBtmtvp6VLoSlPfmJB9B4ScSh5hSxmhD9JhB51fmVBqSZkp6BJ9CVRr3RQ9DAJr7BVpC4NoCAJrCsPrz5TbjRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&amp;msgID=I6011813486659661824_500&amp;markAsRead=This email was intended for projectkudu/kudu. Learn why we included this at the following link: https://www.linkedin.com/blink?simpleRedirect=e3wTd3RAimlIoSBQsC4Ccj1vsClArCBJpn9vt7dBtmtvp6VLoSlPfmJB9CNOlmlzqnpOpldOpmRLt7dRoPRx9DAJr7BVpC4NoCAJrCsPrz5TbjRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I6011813486659661824_500&markAsRead=
&copy; 2015, LinkedIn Corporation. 2029 Stierlin Ct. Mountain View, CA 94043, USA

**Comment by ManfredLange** [comment]
Hi Derrick, please make sure you don't sent LinkedIn invites to this discussion group. It's not really helpful. Thank you!
