### ISSUE TITLE
[Documentation] Deploying to a server page, incorrect path for Kudu.Services.Web

### ISSUE THREAD

**Issue by juanpescador** [projectkudu/kudu#1441]
On the [Deploying to a server](https://github.com/projectkudu/kudu/wiki/Deploying-to-a-server) page, the path for Kudu.Services.Web is missing wwwroot\\. It currently says C:\inetpub\Kudu.Services.Web, but it should be C:\inetpub\wwwroot\Kudu.Services.Web.

I'd also suggest an edit to make it clearer that the directory has to be created/renamed. Something along the lines of:

> Copy the `artifacts\Release\SiteExtensions\Kudu` directory to `C:\inetpub\wwwroot` and rename it from `Kudu` to `Kudu.Services.Web`

**Comment by davidebbo** [comment]
`\inetpub\Kudu.Services.Web` is actually correct, because by default, Kudu.Web's web.config has (not the `..`):

    <add key="serviceSitePath" value="..\Kudu.Services.Web" />

I did reword the sentence to clarify the rename.

**Comment by juanpescador** [comment]
Sorry, I didn't give enough context. I initially placed the directory in C:\inetpub as per the documentation and the Admin Settings page reported an error:

![image](https://cloud.githubusercontent.com/assets/1808374/5853198/33fef52e-a221-11e4-8a20-71fd8c81f96b.png)

Moving Kudu.Services.Web to wwwroot\ and refreshing the Admin Settings page fixed the error, which is what brought me to suggest the change.

Giving it some thought, I realised maybe it's an issue of development vs deployment. For development (F5 in Visual Studio) it works: each project has a directory under the repo's root, so ..\Kudu.Services.Web from Kudu.Web\ is correct.

For deployment, though, following the documentation results in:

    C:\inetpub\
      - Kudu.Web.Services\
      [...]
      - wwwroot\
        - KuduWeb\

So, from inside KuduWeb\, traversing up one level takes you to wwwroot\ rather than inetpub\\.

**Comment by juanpescador** [comment]
This pull request transforms Kudu.Web's web.config when executing build.cmd so the paths for Kudu.Web.Services\ and apps\ match those described in the documentation. Tested locally and works, all tests passing except four in Kudu.FunctionalTests:

  - PushAndDeployMvcAppWithTypeScript. After digging around the trace files I discovered I was missing TypeScript 1.1. After installing it, deployment in test failed with `FooterUpdater.ts(13,9): error TS1068: Build: Unexpected token. A constructor, method, accessor, or property was expected.`. I've run out of time and wasn't able to debug further this or the following tests, sorry.
  - PullApiTestRepoInvalidUrl
  - PushAndDeployCsharp6Web
  - PushAndDeployAspNetAppUnicodeName

**Comment by davidebbo** [comment]
It's probably because of lack of clarity in the 'Deploying to a server' instructions, but when it says 'Copy *artifacts\Release\KuduWeb' files to C:\inetpub\wwwroot*, the key workd is **files**. i.e. you are copying the content of that folder directly inside wwwroot, so there is no KuduWeb folder on the server. In fact, if you instead end up with `\inetpub\wwwroot\kuduweb`, I don't think it would work unless you add a new IIS application pointing to this.

In the end, there is obviously more than one way of configuring this, but the structure that the doc is pushing for is:

````
C:\inetpub\
  - Kudu.Web.Services\
    - App_Data
    - web.config, ...
  - wwwroot\
    - web.config, ...
````

Does that make sense? I just added the intended folder structure to the doc, as I can see how it can be confusing.

**Comment by juanpescador** [comment]
Aha! That makes much more sense. Indeed, I added a new IIS application to get KuduWeb to work. I'll close the PR then.

**Comment by davidebbo** [comment]
Sorry for the unclear doc! On the bright side, it gave the opportunity to improve it for the next person :)
