### ISSUE TITLE
Add support for .njsproj (node js visual studio project files)

### ISSUE THREAD

**Issue by sjkp** [projectkudu/kudu#1443]
The node js tools for visual studio uses .njsproj files, these are not supported when deploying from e.g. github. 

http://nodejstools.codeplex.com/ 

If the node solutions includes TS files a build step i required.

**Comment by jvano** [comment]
Hi

Kudu will continue to run in Azure App Service. However, this repo will no longer be maintained.
If the problem persists and is related to running on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
