### ISSUE TITLE
Improve REST API wiki

### ISSUE THREAD

**Issue by miparnisari** [projectkudu/kudu#1447]
On page https://github.com/projectkudu/kudu/wiki/REST-API.

The command to create a directory `PUT /api/vfs/{path}/` should specify that the `{path}` can be nested, e.g. `folder1/folder2` is valid.

Similarly, the command to upload a zip file `PUT /api/zip/{path}` should specify that the `{path}` should exist.

**Comment by davidebbo** [comment]
Thanks María, I updated the Wiki as suggested.
