### ISSUE TITLE
Error getting zip file of "site/wwwroot": Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host.

### ISSUE THREAD

**Issue by miparnisari** [projectkudu/kudu#1448]
I'm getting this random error when downloading the ZIP file corresponding to "site/wwwroot". When the download succeeds, the file is around 20 MB.

This is the code I'm using:
`$apiUrl = "https://$websiteName.scm.azurewebsites.net/api/zip/site/wwwroot/"`
`$method = "GET"`
`$result = Invoke-RestMethod -Uri $apiUrl -Headers @{Authorization=("Basic {0}" -f $base64AuthInfo)} -Method $method -OutFile "wwwroot.zip" -TimeoutSec 600`

The error is "Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host."

**Comment by davidebbo** [comment]
As a test, can you please try the following:

- Go to the Kudu Console
- Go into the site folder
- Click the download link next to the `wwwroot` folder

This should invoke basically the same zip API that you are using from PowerShell. It will be interesting to see if you get the same issue.

**Comment by miparnisari** [comment]
Yes, that works. I don't have any issues when downloading from a browser, it's just when using PowerShell.

I tried setting the user agent to `[Microsoft.PowerShell.Commands.PSUserAgent]::Chrome` but I'm getting the same error.

This is the output with the flags `-Verbose -Debug` when it succeeds:
```
PS C:\build> .\test.ps1
Downloading contents of 'wwwroot' from the site 'websiteName'...
VERBOSE: GET https://websiteName.scm.azurewebsites.net/api/zip/site/wwwroot/ with 0-byte payload
VERBOSE: received -1-byte response of content type application/zip
```

I'll post the verbose output when I manage to reproduce the error.

**Comment by davidebbo** [comment]
Strange that it would only happen from PowerShell. I usually do this using curl, e.g.

    curl -o foo.zip %KUDU_URL%/api/zip/site/wwwroot/

Maybe worth trying. If that works reliably, then we'll have to blame PowerShell! :)

**Comment by AWahlqvist** [comment]
Found this issue through Google, having the same problem. It seems to happen when the site contains a lot of files, at least in my case.

It looks like it's tied to Invoke-RestMethod and Invoke-WebRequest though, it seems to work fine when using System.Net.WebClient instead, so that can be a workaround for this.

Basically:
`
$WebClient = New-Object System.Net.WebClient
$WebClient.Headers.Add('Authorization', 'Base 64 auth string...')
$WebClient.Headers.Add('ContentType', 'multipart/form-data')

$WebClient.DownloadFile($Uri, $OutFile)
`

**Comment by davidebbo** [comment]
That's odd. If it works reliably from the browser and using curl (as in the real curl, not the PowerShell alias), then I'll just blame it on something PowerShell is doing!

**Comment by AWahlqvist** [comment]
I tend to agree, the issue seems to exist in the built-in cmdlets Invoke-RestMethod and Invoke-WebRequest, not the Kudu API. Just added that here if someone else runs into this issue so they can see the workaround above that seems to run just fine.

But maybe this issue should be closed and a new one added to the PowerShell repo instead? I can add one there.

**Comment by davidebbo** [comment]
Yes, probably. However, to make it more convincing, it would be nice to have a repro of the PowerShell issue that doesn't involve Kudu. e.g. if you host the same zip somewhere else, does it happen with PowerShell? It could be that what makes it Kudu specific is that it can take a while for the bits to start flowing, as the zip has to first be created server side, and maybe that throws off PowerShell.

**Comment by AWahlqvist** [comment]
I'm pretty sure it wouldn't if the zip file was available already. What I've noticed is that the download slows down significantly when a folder contains a large number of files (I'm guessing it gets "streamed" while it's being packed?), and it's during this phase those cmdlets throws this error. So the download nearly finishes sometimes before this occurs.

This specific error usually means that the remote host actually sent a tcp RST to the client though, which would be a bit odd in this case?

**Comment by davidebbo** [comment]
Not sure. We just use `System.IO.Compression.ZipArchive` and `System.Net.Http.PushStreamContent` under the cover (see code [here](https://github.com/projectkudu/kudu/blob/master/Kudu.Services/Infrastructure/ZipStreamContent.cs) and [here](https://github.com/projectkudu/kudu/blob/548724016a15b2570061fad520c3d2de2684d392/Kudu.Services/Zip/ZipController.cs#L24-L44)). And the file system is slower than a typical file system, so zipping a large tree is pretty slow.

**Comment by sanjay3290** [comment]
its 2020 and i still face the same issue. Did somebody found a workaround?

**Comment by AWahlqvist** [comment]
@sanjay3290 : Not really, but we started to upload a PowerShell script that zips up the folder instead that also supports running "async" from the initial call so it doesn't get interrupted when the Azure front end cuts off the connection after 230 seconds. That has worked well for us, but not sure if it qualifies as a workaround.

**Comment by ericthomas1** [comment]
2021 here...

I don't see a `Site` option in the Kudo console anymore. How do I download a .zip from here?

![image](https://user-images.githubusercontent.com/42788729/116600458-2f051380-a8de-11eb-8a1d-50923c870022.png)

Also, hitting `https://$FunctionAppName.scm.azurewebsites.net/api/zip/site/wwwroot/` yields a `.zip` file with **only** the Function's `host.json` file, no source code or support files. 

![image](https://user-images.githubusercontent.com/42788729/116600787-8c00c980-a8de-11eb-932f-610498af4397.png)

**How does one download the .zip for a Python Function!? (please don't say "FTP")**

**Comment by jvano** [comment]
Hi

Kudu will continue to run in Azure App Service. However, this repo will no longer be maintained.
If the problem persists and is related to running on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
