### ISSUE TITLE
Kudu does not transform applicationHost.config using site\applicationHost.xdt

### ISSUE THREAD

**Issue by CThuleHansen** [projectkudu/kudu#1451]
Hi.

I have created a simple applicationHost.xdt and placed in under my site folder as described in https://github.com/projectkudu/kudu/wiki/Xdt-transform-samples.
(I have tested the functionality of the xdt file using: https://webconfigtransformationtester.apphb.com/)

The problem is, that nothing happens with the applicationHost.config located in C:\Windows\System32\inetsrv\config when I deploy.

When I look at the deployment log in Kudu Dashboard it is not mentioned either, and NO log file is placed in "LogFiles\deployment"
I have added the WEBSITE_PRIVATE_EXTENSIONS=1 to properties in configuration.

I am not using Azure but hosting the IIS myself, if it is important.

I am thinking it might be a setting I need to add?
Otherwise my fall back solution is to add some deployment steps that transforms the file in PostDeploymentActions

Can you guys help me out? I am on your JabbR channel as well.

Cheers

**Comment by davidebbo** [comment]
I know this may sound confusing, but the XDT transformation feature is actually not related to Kudu. Instead, it is a feature of Azure Websites. So when you run Kudu on your own server, that feature does not exist.

**Comment by CThuleHansen** [comment]
Thank you Davidebbo.
I will include it somehow in  some custom deployment.

**Comment by ashelley** [comment]
@CThuleHansen If you come up with a solution for this can you post it.  I'm trying to develop site extensions locally and it would be a huge help if I could some how have this feature available.
