### ISSUE TITLE
Support for `azure site deploymentscript --flask`

### ISSUE THREAD

**Issue by AndreiBarsan** [projectkudu/kudu#1453]
Right now, the official Kudu documentation claims that whatever script Azure automatically generates when no explicit `.deployment` file is present can be created locally by running `azure site deploymentscript [type]`. (Using the `azure-cli` `npm` package.)

I have a Flask app, but `azure site deploymentscript --flask` is not supported.

Running `azure site deploymentscript --python` produces an output script, but this script contains no code related to setting up virtualenv and installing pip dependencies.

I would be interested in using a custom Flask deployment script (I want to integrate gulp and automated test-on-push, among other things), but I would need a starting template first. Is there any way to obtain the script Azure automatically generates when it detects e.g. `requirements.txt`?

**Comment by davidebbo** [comment]
Go to Kudu Console and choose Tools / Download deployment scripts. You will get the exact scripts that Kudu uses by default.

**Comment by AndreiBarsan** [comment]
Awesome! This is exactly what I was looking for.
Thank you very much for the help!
