### ISSUE TITLE
Add response header to request admin operation on site

### ISSUE THREAD

**Issue by suwatch** [projectkudu/kudu#1457]
The scenario is after installing site extensions, Kudu can add response header (TBD) to indicate the site need to be restart.   For call thru Geo (ARM), geo will detect this header and perform action synchronously before returning to caller.

**Comment by jvano** [comment]
Hi

Kudu will continue to run in Azure App Service. However, this repo will no longer be maintained.
If the problem persists and is related to running on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
