### ISSUE TITLE
Issue deploying Sliverlight 5 WCF RIA

### ISSUE THREAD

**Issue by ShadowWolf** [projectkudu/kudu#1459]
We are attempting to use Kudu to integrate Git and Azure deployments. So far, it looks like we're not really able to get very far in the process. 

This error is being show in the Azure build log when building a SL5 WCF RIA project with a WCF RIA Services Link to another project in the same solution:
```
    D:\Program Files (x86)\MSBuild\Microsoft\Silverlight\v5.0\Microsoft.Ria.Client.targets(324,5): error MSB4018: The "CreateRiaClientFilesTask" task failed unexpectedly.

    D:\Program Files (x86)\MSBuild\Microsoft\Silverlight\v5.0\Microsoft.Ria.Client.targets(324,5): error MSB4018: System.IO.FileNotFoundException: Could not load file or assembly 'System.ServiceModel.DomainServices.Server, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.
```

From what I can tell, it looks like it's trying to pick up server assemblies when building the client side project. Obviously those assemblies aren't going to exist and I can't imagine we really want them to be scanned/used? Or is this is a situation where maybe the right SDK isn't available? I'm not sure.

I saw some of the previous issues and it looks like people got through this - I'm not sure how they accomplished it though.

**Comment by davidebbo** [comment]
Would you be able to [share a test repo](https://github.com/projectkudu/kudu/wiki/Using-a-git-repo-to-report-an-issue) that demonstrates the issue? Thanks!

**Comment by ShadowWolf** [comment]
I can try to work on something like that. I figured out why my use case is so funky.

We have an assembly that's being used as the server link target, which apparently the customized targets on the azure website aren't handling as well as either the VSO or Visual Studio 2013 do. Basically it looks like whatever is being executed in the targets file Microsoft.Ria.Client.targets expects that the project targeted by the LinkedServerProject property in the csproj file is actually the server, but in our case that's not true.

I don't yet know how the best way to fix this is going to be, but that looks like the problem. I'll work on a sample project when I'm off the clock, but it probably won't be until tomorrow unless I get really lucky and find a good way to give azure build what it expects.

**Comment by ShadowWolf** [comment]
It's still an issue, but i don't have time to continue working on it and we picked a new path. Closing this.
