### ISSUE TITLE
Support a 'safe' mode where Kudu doesn't write to d:\home

### ISSUE THREAD

**Issue by davidebbo** [projectkudu/kudu#1465]
Today, when d:\home is full, you can't even use Kudu to investigate, as it itself writes there, for things like log files. It fails with:

```
[IOException: There is not enough space on the disk.
]
   System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath) +11185413
   System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost) +1305
   System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share) +65
   System.IO.Abstractions.FileWrapper.Open(String path, FileMode mode, FileAccess access, FileShare share) +36
   Kudu.Core.Tracing.LogFileHelper.WriteLine(String value, IDictionary`2 attributes, Int32 depth, Boolean end) +901
   Kudu.Core.Tracing.TextTracer.Trace(String message, IDictionary`2 attributes) +22
   Kudu.Core.Tracing.CascadeTracer.Trace(String message, IDictionary`2 attributes) +36
   Kudu.Services.Web.Tracing.TraceModule.TraceStartup(HttpContext httpContext) +383
   Kudu.Services.Web.Tracing.TraceModule.OnBeginRequest(Object sender, EventArgs e) +494
   System.Web.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +136
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +69
```

I wonder whether with careful coding, we could make Kudu work in this scenario, by simply not having it write to the xdrive at all. E.g. in this case, it’s failing to write the Kudu trace file, which is totally non-essential.

We could have some kind of optional `SCM_SAFE_MODE=1` appsetting that would disable any such logic. In theory, to run Kudu console, we shouldn't need to be writing anything under d:\home afaik.

**Comment by suwatch** [comment]
Try set appSettings SCM_TRACE_LEVEL=0.  This should disable all traces.  BTW, we mentioned [Verbose](https://github.com/projectkudu/kudu/wiki/Investigating-issues#set-kudu-logging-to-verbose-level) but not OFF level.

**Comment by davidebbo** [comment]
Yes, that seems to work!

In addition, I found that even without the flag, you only hit the error on the first request, and after refresh Kudu runs fine.

Good enough for me!
