### ISSUE TITLE
Deploying an Ember CLI app

### ISSUE THREAD

**Issue by tehmaestro** [projectkudu/kudu#1467]
Hi. I'm trying to deploy an ember-cli app to Azure Websites.
I'm running the following tasks in my deployment file
 - npm install bower
 - npm install ember-cli
 - bower install
 - npm install
 - ember build

Well, it all seems to go well, until it hits the `ember build` step. I get an error:
```
this._handle.open(options.fd)

Error: EINVAL, Invalid argument
      at new Socket (net.js:156:18)
      at process.stdin (node.js:664:19)
      at ..... ember-cli\bin\ember:28:25
```

Seems to be something similar to this https://github.com/projectkudu/kudu/issues/885 
 Any ideas on how I could work around this?
  Thank you so much!

**Comment by davidebbo** [comment]
Not sure if it's the same. Does something like [this change](https://github.com/TryGhost/Ghost/pull/3608/files) apply here?

Do you have a [repro repository](https://github.com/projectkudu/kudu/wiki/Using-a-git-repo-to-report-an-issue) you can share?

**Comment by tehmaestro** [comment]
Thanks for responding. I did modify a stdin to false somewhere in the ember-cli project, and I did get a bit further, I think the build process started, but it still failed.

The script froze on 'building ..' I will make a fresh new ember cli app and give it a try. I'll be posting my progress.

**Comment by felixrieseberg** [comment]
Just to quickly add to this: I've been trying to get `ember build` to run in the cloud for a while now and didn't have any measurable luck. I do think it'd be cool to have though - if you guys find out what the trouble is, I'm happy to work with Ember Cli to fix whatever's going on.

**Comment by tehmaestro** [comment]
Hey, I posted this to stackoverflow and got a answer which might work. I am unable to test it at the moment, but here's the answer http://stackoverflow.com/questions/28493629/how-to-deploy-an-ember-cli-app-to-azure-websites/28553596#28553596

**Comment by felixrieseberg** [comment]
I actually also figured out a way - and since I'm an Open Source guy at Microsoft, I just built a small npm module that takes care of everything. If you want a long explanation, [check this out](http://www.felixrieseberg.com/deploying-ember-cli-to-azure-websites/) - if you just want the tl;dr version:

```
$ npm install ember-cli-azure-deploy --save-dev -g
$ azure-deploy init
```

**Comment by tehmaestro** [comment]
Cool, I'll link the website and this issue to stackoverflow.

**Comment by felixrieseberg** [comment]
I think we can actually close this, as https://github.com/felixrieseberg/ember-cli-azure-deploy is battle-tested at this point.

**Comment by davidebbo** [comment]
Sounds good, thanks!
