### ISSUE TITLE
Fix support for GitLab payload

### ISSUE THREAD

**Issue by davidebbo** [projectkudu/kudu#1470]
I just tried to use it from gitlab.com by manually setting up the hook. It seems our logic for gitlabhq is no longer working, possibly because the payload changed since it was written. You can find the code here.
 
Focusing only on the relevant parts, I get a payload that looks like this:

```json 
{  
   "ref":"refs/heads/master",
   "user_id":12345,
   "user_name":"David Ebbo",
   "repository":{  
      "name":"Mvc51ApplicationFx451",
      "url":"git@gitlab.com:david-ebbo/Mvc51ApplicationFx451.git",
      "description":"Test MVC project",
      "homepage":"https://gitlab.com/david-ebbo/Mvc51ApplicationFx451"
   }
}
```
 
And for a public repo (as is the case for https://gitlab.com/david-ebbo/Mvc51ApplicationFx451), we’re expecting an http URL and not ssh. So that blows up in there.

**Comment by davidebbo** [comment]
Gitlab folks wrote:

>The repository['url'] field has returned the ssh url for long time (maybe from beginning of GitLab). You can use the repository['homepage'] field and add `.git` to it to get the git over HTTP url.

**Comment by randx** [comment]
@davidebbo hey. You can follow advice and use `homepage` for HTTP url. In future we are planning to explicitly add `git_http_url` and `git_ssh_url` for hook payload

**Comment by suwatch** [comment]
As you mentioned, it was missing the is_private (or public) field as part of hook payload.   One workaround is to Http GET on  repository['homepage'] url.   For public, it returns 200.  For private, it redirect to login (302).   Of course, it is best they include this info in the playload.

```json
{
  "before": "20fb361885bc66358b7d73e1bd11eda08c643b49",
  "after": "1ba391f4d100ab8dde08e8bf77355a67325182d6",
  "ref": "refs/heads/master",
  "checkout_sha": "1ba391f4d100ab8dde08e8bf77355a67325182d6",
  "user_id": 99630,
  "user_name": "Suwat Bodin",
  "project_id": 168565,
  "repository": {
    "name": "HelloPrivate",
    "url": "git@gitlab.com:suwatch01/HelloPrivate.git",
    "description": "",
    "homepage": "https://gitlab.com/suwatch01/HelloPrivate"
  },
  "commits": [
    {
      "id": "1ba391f4d100ab8dde08e8bf77355a67325182d6",
      "message": "testing gitlab2\n",
      "timestamp": "2015-02-19T20:24:08-08:00",
      "url": "https://gitlab.com/suwatch01/HelloPrivate/commit/1ba391f4d100ab8dde08e8bf77355a67325182d6",
      "author": {
        "name": "Suwath Ch",
        "email": "suwatch@microsoft.com"
      }
    }
  ],
  "total_commits_count": 1
}
```

**Comment by randx** [comment]
From hook payload you cant say if project is public or private right now

**Comment by randx** [comment]
But we will consider including visibility flag (public/internal/private) in future version

**Comment by suwatch** [comment]
ETA?

I think unless that flag is available, it is best we always treat it as public repo and only use http.  It will fail with private repo but we will live with that limitation - well at least we have some support.

Work around by HttpGET on homepage url and decide based on 200 or 302 status is probably too weak.

**Comment by randx** [comment]
> ETA?

Possibly 7.10 

> I think unless that flag is available, it is best we always treat it as public repo and only use http. It will fail with private repo but we will live with that limitation - well at least we have some support.

What kind of problem you are trying to solve. Why you need to know if project is public from webhook?

**Comment by suwatch** [comment]
For continuous integration, once we receive the hook notification, we will perform the `git fetch` from the gitlab repository and deploy.   We need to know whether to git fetch https or ssh.  Make sense?

**Comment by randx** [comment]
Any reasons why you cant use only one method. For example SSH

**Comment by suwatch** [comment]
For public repo, it is not necessary for user to setup SSH key pair between Kudu and GitLab.  This is the simplest workflow.   For private, it is required.  

Of course, once we have the full integration (with oauth and all), it will be transparent to user.  However, best practice wise, we only want to do just necessary thing - not more.

**Comment by davidebbo** [comment]
Here is a thought: ignore whether the repo is public or private. Instead, choose to use ssh URL only if we in fact have an ssh key. If we don't, fall back to http. Problem solved!

**Comment by suwatch** [comment]
That could be another workaround.  I just think long term we should have that info.  It is available on `https://gitlab.com/api/v3/projects` rest api (`public: true`).   Just a matter of adding it to the hook, I guess. 

@randx what 7.10 means in term of date?  It is not July 10 correct?

**Comment by davidebbo** [comment]
Do we use that knowledge for anything other than determining whether to use ssh or http? If so, basic it on presence of ssh key feels pretty solid. e.g. someone might legitimately decide to use ssh to a public repo and set up an ssh key to do that. Even though that's not how we set things up by default, it's perfectly valid.

**Comment by randx** [comment]
Idea with ssh keys looks valid to me. 

> what 7.10 means in term of date? It is not July 10 correct?

We have release every 22nd each month. Right now we are 7.7. So 7.10 is April 22. But I think we can improve web hooks even earlier. It looks like an easy fix.

**Comment by randx** [comment]
How you setup integration with GitLab project. Are you using GitLab OAuth? If so you can use OAuth2 token for cloning private repo. 

`git clone https://oauth:XXXXXXXXXXX@gitlab.com/gitlab-org/gitlab-shell.git`

**Comment by randx** [comment]
We have some documentation for requesting OAuth token here - http://doc.gitlab.com/ce/api/oauth2.html

**Comment by randx** [comment]
Anyway I am going to improve web hooks soon so you will know if project is public or not.

**Comment by suwatch** [comment]
Wonderful, looking forward to try it out.  

As for setup integration, short term, one would need to do a [manual setup](https://github.com/projectkudu/kudu/wiki/Continuous-deployment) to integrate with GitLab.   We will discuss on the timeline to achieve a full OAuth integration with GitLab and Azure Portal.  Will keep you update on schedule.

**Comment by suwatch** [comment]
> Anyway I am going to improve web hooks soon so you will know if project is public or not.

Can you give a timeline how `soon` it is?  If it will be next week, we could wait.  Otherwise, we will probably do some small surgical fix to test E2E.

**Comment by randx** [comment]
I made a fix - https://github.com/gitlabhq/gitlabhq/commit/2617f8d14af870e5364c6299483164d33006e087

It will be available in current release (7.8) at Monday

**Comment by davidebbo** [comment]
Awesome, thanks Dmitriy!

**Comment by randx** [comment]
You are welcome :)

**Comment by randx** [comment]
And it was released in 7.8 yesterday and now also available on gitlab.com

**Comment by suwatch** [comment]
Thanks.  We can see the new properties (visibility, http and ssh urls) in the hook payload.   We can proceed from here.

**Comment by davidebbo** [comment]
I rewrote the documentation on setting up CI, including with GitLab. Find it on https://github.com/projectkudu/kudu/wiki/Continuous-deployment
