### ISSUE TITLE
ASP vNext: 500 Internal Server Error

### ISSUE THREAD

**Issue by joaomoreno** [projectkudu/kudu#1474]
I follow the official ASP .NET vNext steps to scaffold a project, and push it to an Azure web site.

```
yo aspnet
> WebApplication
git init
git add .
git commit -m "first commit"
git remote add azure https://joaovnext.scm.azurewebsites.net:443/joaovnext.git
git push azure master
```

Then, when accessing it, I get the following:

[![screenshot](http://i.imgur.com/veufOaV.png)](http://joaovnext.azurewebsites.net/)

How can I debug this? Shouldn't the simplest scaffolding work?

For reference, [here's what the project looks like](https://gist.github.com/joaomoreno/64cf414f27408c8bfcc3).

**Comment by davidebbo** [comment]
Is this with beta 2? If so, see this [question](http://stackoverflow.com/questions/28550153/deploying-asp-net-vnext-beta-2-on-azure-with-kudu). Currently, you need to set to App Settings in the Azure portal:

- `SCM_KRE_Version=1.0.0-beta2`
- `SCM_KRE_CLR=CoreCLR`

**Comment by joaomoreno** [comment]
Good try, but I'm still getting the same 500 error.

**Comment by davidebbo** [comment]
What version of vNext are you using? Could you [share a test repo](https://github.com/projectkudu/kudu/wiki/Using-a-git-repo-to-report-an-issue) so we can try the same? Thanks!

**Comment by joaomoreno** [comment]
`kvm list` tells me it's `1.0.0-beta2`.

Sure, [here you go](https://github.com/joaomoreno/EmptyWebApplication). You can get the same code by using the [aspnet yeoman generator](http://blogs.msdn.com/b/webdev/archive/2014/12/17/yeoman-generators-for-asp-net-vnext.aspx).

**Comment by davidebbo** [comment]
Oh I see. I think we've only tested with vNext projects created by VS, which end up with a completely different (more complex) structure. We'll need to talk to @davidfowl and other vNext folks to figure out how the two cases are different.

Also, note that beta3 should be out very soon, so we'll probably focus on making that work rather than beta2.

**Comment by ahmelsayed** [comment]
setting that app setting (`SCM_KRE_Version=1.0.0-beta2`) worked for me!
**note** that you have to *redeploy* after you set the app setting.

setting `SCM_KRE_CLR=CoreCLR` however gave me the following error

```
'Asp.NetCore,Version=v5.0' is not a target framework of the project being packed
```

which seems like a config issue so you probably aren't using CoreCLR

**Comment by davidebbo** [comment]
Ah, good call! I was setting both, and getting the same error as you. When just setting `SCM_KRE_Version`, it does work!

Anyway, let's add that to the list of scenarios to verify once we move to beta3. Well, the yeoman generator might need to add support for it first.

**Comment by joaomoreno** [comment]
Yep, confirm that it does work, thanks! I was also missing the redeployment...

**Comment by patrickmichalina** [comment]
If I am carrying over a deployment script from a different application (that performs gulp tasks) would I then need to manually setup the new runtime manually? Something similar to this: https://github.com/hfjallemark/azure-vnext/blob/master/deploy.cmd

**Comment by patrickmichalina** [comment]
Never mind, I think I answered my own question. I was able to replace my old Deploy.cmd with the project.json scripts and my project deploys fine.

"scripts":{
        "prepare": [
            "bower update",
            "npm cache clean",
            "npm install npm@2.9.1", 
            "npm install git+https://git@github.com/gulpjs/gulp.git#4.0",
            "%project:Directory%/node_modules/.bin/gulp build"]
}
