### ISSUE TITLE
Can't deploy beta3 due to KRE name format change

### ISSUE THREAD

**Issue by awec** [projectkudu/kudu#1479]
For deploying beta2 apps via Kudu i could just set the *SCM_KRE_Version* app setting in Azure to *1.0.0-beta2* .

Setting this to *1.0.0-beta3* doesn't work because it seems the name format has changed slightly. Kudu does the following:

Downloading KRE-CoreCLR-x86.1.0.0-beta3 from https://www.nuget.org/api/v2

When the package is now called kre-coreclr-win-x86.1.0.0-beta3

**Comment by davidebbo** [comment]
Yes, there are more changes in Beta3, so just setting the AppSetting is not good enough. We are working on getting proper support in Azure Websites.

**Comment by matt-podsiadlo** [comment]
:+1: , lots of breaking changes with beta3, hope you guys can figure this one out :)

**Comment by davidebbo** [comment]
BTW, we might break support for earlier beta's once we have the beta3 support out. Hope that's ok, as hopefully everyone should be moving forward. This is after all a beta!

**Comment by ahmelsayed** [comment]
This should be fixed by 4716485161bfea7a65f94a4e4f12ae064adf6c22 and 5eb7282e531904e66124e96b491d6d633a9053e6

**Comment by matt-podsiadlo** [comment]
@ahmelsayed that's awesome! What's the process of getting Kudu updated on an existing Azure Website? Do we wait for the next website 'build' ?

**Comment by davidebbo** [comment]
It should be updated everywhere now. The most you may have to do is restart your site. Can you give it a try and verify that everything is working? Thanks!

**Comment by matt-podsiadlo** [comment]
It does indeed work now, new version of Kudu automagically appeared on a running site :)

Just a note for everyone using custom deployment hooks like myself (i.e. deploy.cmd), the kpm pack command is now called kpm bundle (https://github.com/aspnet/XRE/issues/967) so old scripts will need to be updated (or re-downloaded from Kudu SCM)

Thanks guys!
