### ISSUE TITLE
Code review IBuildPropertyProvider

### ISSUE THREAD

**Issue by ahmelsayed** [projectkudu/kudu#1482]
Context is here https://github.com/projectkudu/kudu/commit/5eb7282e531904e66124e96b491d6d633a9053e6

**Comment by jvano** [comment]
Hi

Kudu will continue to run in Azure App Service. However, this repo will no longer be maintained.
If the problem persists and is related to running on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
