### ISSUE TITLE
"Deploying to a server" instructions

### ISSUE THREAD

**Issue by cjsewell** [projectkudu/kudu#1486]
I have setup a copy of Kudu on my local dev machine, and it works fine providing I run it from Visual Studio as Administrator

I would now like to deploy it to our public UAT server so we can use it for deploying testing sites. The UAT server is Windows Server 2008 R2.

I have followed the ["Deploying to a server" ](https://github.com/projectkudu/kudu/wiki/Deploying-to-a-server) instructions, however when I load the site I get the error:
```
You are running kudu against a local kudu service and are not an Administrator. Re-run this process as Administrator in order to continue.
```

While I understand Kudu needs to run as admin to create sites etc, I don't feel comfortable giving a public site admin privileges (even though it will have some form of authentication once I get it running).

The ["Deploying to a server" ](https://github.com/projectkudu/kudu/wiki/Deploying-to-a-server) instructions makes no mention of Administrator privileges, and I'm unable to find much documentation on the topic.

Are there missing steps in the documentation or am I missing something?

**Comment by davidebbo** [comment]
Well, it does say *'Change AppPool to run as LocalSystem so it can manage IIS sites'*, which I think is basically the same. And yes, I understand that it's not ideal to give it such permission, but it seems necessary for it to manage IIS.

**Comment by cjsewell** [comment]
Oh, ignore me, I'm a moron, I though I had done that, but I had changed it to LocalService!
