### ISSUE TITLE
 kudu DEPLOYMENT_SOURCE and SCM_REPOSITORY_PATH defaults to wwwroot

### ISSUE THREAD

**Issue by ranji** [projectkudu/kudu#1487]
When I do a `git push azure develop` , I see that the DEPLOYMENT_SOURCE and SCM_REPOSITORY_PATH is wwwroot when I access it from my deploy.cmd file. Why is it not d:\home\site\repository as shown as default in my scm / kudu site ?? How can I fix this to be d:\home\site\repository. I am trying to deploy a node.js site to azure website. I am also seeing that the IN_PLACE_DEPLOYMENT is set to 1.

my .deployment file just has a reference to the batch file like this:

    [config]
    command = deploy.cmd 
And in the deploy.cmd file, I echo-ed the values.

I also see that the repository path is set to 'wwwroot' and the branch is set to 'master' when I look at the app settings with the REST api 
`{"deployment_branch":"master","SCM_TRACE_LEVEL":"1","SCM_COMMAND_IDLE_TIMEOUT":"60","SCM_LOGSTREAM_TIMEOUT":"1800","SCM_BUILD_ARGS":"","aspnet:PortableCompilationOutput":"true","aspnet:PortableCompilationOutputSnapshotType":"Microsoft.Web.Compilation.Snapshots.SnapshotHelper, Microsoft.Web.Compilation.Snapshots, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35","aspnet:DisableFcnDaclRead":"true","SCM_GIT_USERNAME":"windowsazure","SCM_GIT_EMAIL":"windowsazure","webpages:Version":"3.0.0.0","webpages:Enabled":"true","WEBSITE_SITE_NAME":"xxxxxx","ScmType":"LocalGit","REMOTEDEBUGGINGVERSION":"11.0.611103.400","WEBSITE_NODE_DEFAULT_VERSION":"0.10.32","SCM_REPOSITORY_PATH":"wwwroot","branch":"master"}`

**Comment by davidebbo** [comment]
If you see `IN_PLACE_DEPLOYMENT` set to 1, then you must be setting it that way (e.g. in App Setting), because it's not there by default. And if that's the case, the behavior is expected, as that's exactly what it means.
