### ISSUE TITLE
Deployment Credentials Usernane

### ISSUE THREAD

**Issue by ryankekos** [projectkudu/kudu#1488]
To automate deployment credentials in Windows Azure Pack I'd like to set the username password as their WAP email/password but we're having a problem setting the credentials using an email due to the @ symbol. Can I bypass this somehow to make the username contain an @ symbol?

**Comment by davidebbo** [comment]
Could you please post this to the [Websites forum](https://social.msdn.microsoft.com/Forums/azure/en-US/home?forum=windowsazurewebsitespreview) instead? This does not directly relate to Kudu, and you would hit a better set of people there. Thanks!
