### ISSUE TITLE
Kudu sync fails because of Windows file path length issue

### ISSUE THREAD

**Issue by kmuthupa** [projectkudu/kudu#1490]
Kudu sync on our production azure environment fails when syncing the different node module dependencies because of the Windows file path length (255 chars) limit issue. Whats weird this happens only on the prod azure environment and does not on the dev and test instances.  @shanselman - we had a conversation on Twitter about this.

**Comment by amitapl** [comment]
this could be happening due to the length of the site name, one is probably longer and that puts it over the edge.

**Comment by kmuthupa** [comment]
The target site here is the wwwroot/. This actually started happening in our dev environment as well. Here is the exact exception that we are seeing when the deploy script executes. 

node_modules\http-signature\README.md'
Copying file: 'node_modules\bower\node_modules\bower-registry-client\node_modules\request\node_modules\http-signature\lib\index.js'
Omitting next output lines...
Processed 1456 files...
Processed 2621 files...
Processed 3476 files...
Processed 4499 files...
Processed 5705 files...
Processed 6708 files...
Error: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
An error has occurred during web site deployment.
Kudu Sync to Target failed

**Comment by davidebbo** [comment]
What is the deepest path that your site uses? It may be hitting the length limit described in the error message.

**Comment by kmuthupa** [comment]
249 ./node_modules/grunt-node-inspector/node_modules/node-inspector/node_modules/v8-debug/node_modules/node-pre-gyp/node_modules/npmlog/node_modules/gauge/node_modules/lodash.padleft/node_modules/lodash._createpad/node_modules/lodash.repeat/package.json
249 ./node_modules/grunt-node-inspector/node_modules/node-inspector/node_modules/v8-debug/node_modules/node-pre-gyp/node_modules/npmlog/node_modules/gauge/node_modules/lodash.padright/node_modules/lodash._createpad/node_modules/lodash.repeat/LICENSE.txt
250 ./node_modules/grunt-node-inspector/node_modules/node-inspector/node_modules/v8-debug/node_modules/node-pre-gyp/node_modules/npmlog/node_modules/gauge/node_modules/lodash.padright/node_modules/lodash._createpad/node_modules/lodash.repeat/package.json
251 ./node_modules/grunt-node-inspector/node_modules/node-inspector/node_modules/v8-profiler/node_modules/node-pre-gyp/node_modules/npmlog/node_modules/gauge/node_modules/lodash.padleft/node_modules/lodash._createpad/node_modules/lodash.repeat/LICENSE.txt
252 ./node_modules/grunt-node-inspector/node_modules/node-inspector/node_modules/v8-profiler/node_modules/node-pre-gyp/node_modules/npmlog/node_modules/gauge/node_modules/lodash.padleft/node_modules/lodash._createpad/node_modules/lodash.repeat/package.json
249 ./node_modules/grunt-node-inspector/node_modules/node-inspector/node_modules/v8-profiler/node_modules/node-pre-gyp/node_modules/npmlog/node_modules/gauge/node_modules/lodash.padleft/node_modules/lodash._createpad/node_modules/lodash.repeat/README.md
249 ./node_modules/grunt-node-inspector/node_modules/node-inspector/node_modules/v8-profiler/node_modules/node-pre-gyp/node_modules/npmlog/node_modules/gauge/node_modules/lodash.padright/node_modules/lodash._createpad/node_modules/lodash.repeat/index.js
252 ./node_modules/grunt-node-inspector/node_modules/node-inspector/node_modules/v8-profiler/node_modules/node-pre-gyp/node_modules/npmlog/node_modules/gauge/node_modules/lodash.padright/node_modules/lodash._createpad/node_modules/lodash.repeat/LICENSE.txt
253 ./node_modules/grunt-node-inspector/node_modules/node-inspector/node_modules/v8-profiler/node_modules/node-pre-gyp/node_modules/npmlog/node_modules/gauge/node_modules/lodash.padright/node_modules/lodash._createpad/node_modules/lodash.repeat/package.json
250 ./node_modules/grunt-node-inspector/node_modules/node-inspector/node_modules/v8-profiler/node_modules/node-pre-gyp/node_modules/npmlog/node_modules/gauge/node_modules/lodash.padright/node_modules/lodash._createpad/node_modules/lodash.repeat/README.md
./node_modules/grunt-node-inspector/node_modules/node-inspector/node_modules/v8-profiler/node_modules/node-pre-gyp/node_modules/npmlog/node_modules/gauge/node_modules/lodash.padright/node_modules/lodash._createpad/node_modules/lodash.repeat/package.json

**Comment by davidebbo** [comment]
Given this, it's clearly exceeding the limit, as this length doesn't include the base directory. One thing you can try is [npm dedupe](https://docs.npmjs.com/cli/dedupe), and potentially getting rid of deep things that aren't needed.

Closing here since this is an OS limitation, and not anything specific to Kudu.

**Comment by msingaraju** [comment]
We did try dedupe but that did not fix the issue. So to get around the problem since our site is relatively small, currently we are writing directly to the wwwroot instead of writing to repository location in azure and then kudu syncing the files to wwwroot (which is where we ran into this issue).

**Comment by davidebbo** [comment]
I'm surprised that this works, as the path limit is the same. Well, 'wwwroot' has 3 characters fewer than 'repository', so if you're right at the edge, that could explain it.
