### ISSUE TITLE
Unlisted packages are installed

### ISSUE THREAD

**Issue by sebastienros** [projectkudu/kudu#1492]
When no specific version is given for a package, the latest version is taken into account. The issue is that it also looks into the unlisted packages.

**Comment by shrimpy** [comment]
thanks for reporting this. taking a look now.

**Comment by shrimpy** [comment]
Fixed in a0ec7add404d2eba96cd01298fea0fc59fc01b5e

**Comment by davidebbo** [comment]
I think the desired behavior here should be the same as with NuGet.exe:
- if no version is passed in, you the latest that's not unlisted
- if a version is passed in, honor it regardless of whether it's listed or unlisted

Is that how your change works? Looking at the code, I'm not so sure.
