### ISSUE TITLE
SiteExtension: Avoid restart when install to WebRoot only

### ISSUE THREAD

**Issue by shrimpy** [projectkudu/kudu#1501]
need to handle case that two different installation request, one is install to webroot, one is normal site extension installation. in this case we will still need to return restart header to trigger restart.

**Comment by davidebbo** [comment]
While it's not needed for the main site, you still need the restart for the scm (used for miro-RP scenario).

**Comment by shrimpy** [comment]
can we assume that in "Micro-RP" scenario, package will always come with its own XDT?

**Comment by davidebbo** [comment]
Good question. Though if we assume that, then we wouldn't need to create an XDT at all, right?

If we make this a requirement, then we know when we need to restart.

**Comment by shrimpy** [comment]
i think we will still need to create XDT file, since install to webroot will have two scenario if i understand correctly:

scenario 1:
package do not has XDT, purely want to put content to wwwroot
in this case we will need to generate XDT file to map request to wwwroot

scenario 2:
package has XDT, at the same time want to put content to wwwroot
in this case we do not generate XDT, instead we use the XDT file come with package
(and i thought this is Micro-RP scenario)

**Comment by shrimpy** [comment]
chat with David, we will remove the logic that we generate XDT file when there isn`t one come with package.

in this case when there is no XDT file, we do not need to restart the whole site.
