### ISSUE TITLE
.NET Core

### ISSUE THREAD

**Issue by johnkors** [projectkudu/kudu#1505]
Hi, 

Is it possible to install Kudu on Linux using .NET Core? Would be sweet to do git push deploy to a Raspberry Pi / Arduino :)

**Comment by davidebbo** [comment]
I'm a bit ignorant about .NET core, but doesn't that only run the new ASP.NET 5 (vNext)? If so, it definitely wouldn't work, as Kudu is a 'standard' ASP.NET app. Eventually, we'll move to vNext, but I don't think we're ready for that now.

**Comment by johnkors** [comment]
Yeah, ASP.NET 5. Okay, thanks David.
