### ISSUE TITLE
nuget restore is not invoked

### ISSUE THREAD

**Issue by sapiens** [projectkudu/kudu#1506]
I'm trying to deploy from bitbucket and I've checked that I don't have any packages directory and of course, no nupkgs either. Deploying fails and the log doesn't show any sign that nuget restore is called.

I've successfully compiled the project locally invoking nuget manually so the code should be ok. It;s like kudu doesn't detect that it needs to restore packages.

How can I solve that?

**Comment by davidebbo** [comment]
Do you have a custom deployment script? The default script should be restoring NuGet packages if Kudu successfully detects that it's a .NET app. What does the deployment log look like?

**Comment by sapiens** [comment]
I don't have a custom deployment script. However, I do have a setting in app.config to compile a specific project. The solution has 2 websites but I want only one of them deployed. The log shows only compiling errors because of missing deps and it doesn't show anywhere anything nuget related.

**Comment by davidebbo** [comment]
Is it an ASP.NET Web App or Web Site? Can you share the output of your deployment script?

**Comment by sapiens** [comment]
It's a Web App hosted on Azure Websites. I can't share the output right now, I have disconnected it from bitbucket and deployed manually from VS (I needed the site up fast) .

**Comment by davidebbo** [comment]
Can you share your site name, either directly or [indirectly](https://github.com/projectkudu/kudu/wiki/Reporting-your-site-name-without-posting-it-publicly)? This will help us investigate. Thanks!

**Comment by sapiens** [comment]
OK, I've set up a very simple solution with 2 projects and it works properly.Then  I guess the problem is from me, I need to cleanup the little monster better. I'll try it later and will keep you informed how it went

**Comment by sapiens** [comment]
OK I think I've got it. So, if the sln file is not in the root directory, or in a directory of a higher level than the csproj, kudu ignores it. Basically, I have ~/A/A.sln and ~/B/B/csproj . If I move the sln file to be in ~/ , then the packages are restored.

I don't know if it's a bug or a missing feature, probably a case like mine with the sln file in a non-standard location (it just happened, it wasn't intentional) is pretty rare. But nevertheless, it can happen.

**Comment by davidebbo** [comment]
Kudu has default logic to find the sln, but there are ways to override this (see [here](https://github.com/projectkudu/kudu/wiki/Customizing-deployments#deploying-a-specific-aspnet-project-file-ie-a-wap)). So you could have mane that worked before, but since it was unintentional, you're better off now :)

**Comment by sapiens** [comment]
I'm already using that customization, to specify the project path. In that case the sln file is ignored if it's not in an expected location, the project starts compiling but it fails due to missing packages. Clearly the safest bet is to have it in the root directory and that's it.

**Comment by davidebbo** [comment]
You should be able to make it work by using `SCM_SCRIPT_GENERATOR_ARGS`, which takes over the command line of the generator. There, you can pass flags that tell it both where the project and solution are.
