### ISSUE TITLE
Install NPM package from VSO git

### ISSUE THREAD

**Issue by mkliu** [projectkudu/kudu#1510]
hi, i'm hosting my npm package in VSO git. But it doesn't support SSH.
How do I make npm install work in this case when deploying that to Azure?

**Comment by davidebbo** [comment]
VSO git does no use Kudu. See [this page](https://github.com/projectkudu/kudu/wiki/VSO-vs-Kudu-deployments) which explains the details.

**Comment by mkliu** [comment]
aaahh, thanks. damn it! I hate the build definition files!
