### ISSUE TITLE
Support auto-wiring post-deploy hooks from source control deployments

### ISSUE THREAD

**Issue by davidwhitney** [projectkudu/kudu#1512]
In the wiki for Kudu's support of "Post-Deployment Actions" it's suggested that you 

> To add a post deployment action hook you simply need to place a script file (.bat or .cmd) under site\deployments\tools\PostDeploymentActions.

This seems fine for deployments that have custom build and deploy actions, but I'd love this to work equally for scm deployments.
### Suggestion

Implement a convention for deployment hooks, perhaps following the conventions outlined in the ASP.NET vNext  project layout here (https://gist.github.com/davidfowl/ed7564297c61fe9ab814).

I'd suggest that the contents of any directory present matching

```
      /build/postdeploy
```

Are auto-deployed to

```
     site\deployments\tools\PostDeploymentActions
```

This would allow users to trivially supply source-controlled, post-deployment hooks.
These conventions could be matched with a corresponding set of pre-deployment conventions.

**Comment by brondavies** [comment]
Also the documentation at https://github.com/projectkudu/kudu/wiki/Customizing-deployments is out of date.  so it would be really nice if we could add to the deployment steps rather than create a whole new script for the deploy command

**Comment by jvano** [comment]
Hi

Kudu will continue to run in Azure App Service. However, this repo will no longer be maintained.
If the problem persists and is related to running on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
