### ISSUE TITLE
WebJob API being called several times per minute

### ISSUE THREAD

**Issue by Corpra** [projectkudu/kudu#1515]
I've uploaded a simple console application as a webjob to my Azure website. I have configured the website to log error pages (to LogFiles/DetailedErrors/). Several (3-6) times per minute I'm getting this error page logged:
![untitled](https://cloud.githubusercontent.com/assets/2692109/6864435/7960d408-d461-11e4-99ac-48e095db167f.png)
It seems as though the Kudu WebJob API's GET for webjob history is being called, judging by the error page.

I don't know why this is happening. There is no "api" folder in Kudu/44.40324.1452, or in any other version of Kudu (there are 7 of them).

**Comment by davidebbo** [comment]
Dup of [forum post](https://social.msdn.microsoft.com/Forums/en-US/e37c06e2-5f5e-4bd8-9c42-b6ae35b03337/azure-kudu-webjob-api-being-called-several-times-per-minute?forum=windowsazurewebsitespreview). Please do not cross post without explicit reference to the other post.
