### ISSUE TITLE
Not able to upload my application zip file by PUT /api/zip/{path}

### ISSUE THREAD

**Issue by arbarik** [projectkudu/kudu#1517]
Hi,

I am going through the wiki page of this project. My requirement is to upload application zip file to wwwroot folder from my local folder. I have used below Url to GET my app from wwwroot folder of azure website  and PUT the app to wwwroot folder of azure website.

https://$&lt;sitename&gt;:&lt;publish password&gt;@&lt;sitename&gt;.scm.azurewebsites.net/api/zip/site/wwwroot  

But it redirects me to Azure login page. I want to upload or download my application from wwwroot from a script. I can't use browser or session. My CI box is a linux box, So can't use any windows/powershell command. 

How would I pass the credential/ publish profile credentials to deploy my app to wwwroot folder.
Could anyone please guide me ?

Thanks

**Comment by davidebbo** [comment]
What tool are you using to do this? Please try with `curl`.

**Comment by arbarik** [comment]
Hi David,
Thanks for your reply.

Before I had tried with chrome REST plugin. It was giving me redirect status. As per your advice I have used curl tool. but it gives me unauthorized (401) status code. I have executed below command.

curl -i -X GET https://sitename/api/zip/site/wwwroot -u $sitename:password

It responds me Html body with 401 error code. I am using userName and UserPWD from sites publish profile. Please correct me if i am doing something wrong. give me some example , how to use it. 

Thanks,

**Comment by davidebbo** [comment]
Please try this exact command (this is a test site I just created):

    curl -i -o foo.zip -X GET https://tmp676767.scm.azurewebsites.net/api/zip/site/wwwroot -u $Tmp676767:7fgxQYjitttkwJBG5rq2AykGGickx5gGlgw8jXNX3YlE1q5rv8Sb7XY3AlAK

It works fine for me.

**Comment by arbarik** [comment]
Hi David,

I have executed the command given by you. It creates a file foo.zip. But actually doesn't download anything. size of foo.zip is just 1 KB, corrupted zip file.

Thanks,

**Comment by davidebbo** [comment]
I think we need to separate the concerns here. What you were seeing initially was a general authentication issue that had nothing to do with the zip controller. Have you moved passed this issue on your own site? Clearly, that part is working for you on my test site, so we need to understand what's different with yours.

For the zip, I was just missing a / after wwwroot, and you don't want to use `-i`. Try the corrected command above now.

As for upload, try:

    curl -X PUT --data-binary @foo.zip https://tmp676767.scm.azurewebsites.net/api/zip/site/wwwroot/ -u $Tmp676767:7fgxQYjitttkwJBG5rq2AykGGickx5gGlgw8jXNX3YlE1q5rv8Sb7XY3AlAK

**Comment by arbarik** [comment]
Thanks a lot David....
I am able to upload and download my application to/from my Azure website.
