### ISSUE TITLE
Deployment failed - miss msbuild target: pipelinePreDeployCopyAllFilesToOneFolder

### ISSUE THREAD

**Issue by YingP99** [projectkudu/kudu#1518]
My GitHub url is - https://github.com/Microsoft/ViprService 
## The deployment is:

```
Command: "D:\home\site\deployments\tools\deploy.cmd"
Handling .NET Web Application deployment.
All packages listed in packages.config are already installed.
All packages listed in packages.config are already installed.
  Restoring NuGet packages...
  To prevent NuGet from downloading packages during build, open the Visual Studio Options dialog, click on the Package Manager node and uncheck 'Allow NuGet to download missing packages'.
  All packages listed in packages.config are already installed.
  ViprService -> D:\home\site\repository\src\ViprService\bin\ViprService.dll
D:\home\site\repository\src\ViprService\ViprService.csproj : error MSB4057: The target "pipelinePreDeployCopyAllFilesToOneFolder" does not exist in the project.
Failed exitCode=1, command="D:\Windows\Microsoft.NET\Framework\v4.0.30319\MSBuild.exe" "D:\home\site\repository\src\ViprService\ViprService.csproj" /nologo /verbosity:m /t:Build /t:pipelinePreDeployCopyAllFilesToOneFolder /p:_PackageTempDir="D:\local\Temp\cec7964f-a0d6-4985-87c2-d5b12d052d13";AutoParameterizationWebConfigConnectionStrings=false;Configuration=Release /p:SolutionDir="D:\home\site\repository\.\\"
An error has occurred during web site deployment.
Handling .NET Web Application deployment.
All packages listed in packages.config are already installed.
All packages listed in packages.config are already installed.
  Restoring NuGet packages...
  To prevent NuGet from downloading packages during build, open the Visual Studio Options dialog, click on the Package Manager node and uncheck 'Allow NuGet to download missing packages'.
  All packages listed in packages.config are already installed.
  ViprService -> D:\home\site\repository\src\ViprService\bin\ViprService.dll
D:\home\site\repository\src\ViprService\ViprService.csproj : error MSB4057: The target "pipelinePreDeployCopyAllFilesToOneFolder" does not exist in the project.
Failed exitCode=1, command="D:\Windows\Microsoft.NET\Framework\v4.0.30319\MSBuild.exe" "D:\home\site\repository\src\ViprService\ViprService.csproj" /nologo /verbosity:m /t:Build /t:pipelinePreDeployCopyAllFilesToOneFolder /p:_PackageTempDir="D:\local\Temp\cec7964f-a0d6-4985-87c2-d5b12d052d13";AutoParameterizationWebConfigConnectionStrings=false;Configuration=Release /p:SolutionDir="D:\home\site\repository\.\\"
An error has occurred during web site deployment.
D:\Program Files (x86)\SiteExtensions\Kudu\44.40324.1452\bin\scripts\starter.cmd "D:\home\site\deployments\tools\deploy.cmd"
```

**Comment by davidebbo** [comment]
Can you check whether your project can deploy locally, by following [these steps](https://github.com/projectkudu/kudu/wiki/Make-sure-site-correctly-deploys-locally)?

**Comment by YingP99** [comment]
Thx. I'll try.
When creating the project, there is a n option on ASP.NET template that you can check to deploy to Azure, and there will be some scripts in the PublishScripts folder, and Web Publish Activity tab. I didn't check that box. Is it required? What's the relationship between these two publish configs?

**Comment by davidebbo** [comment]
Nothing special is needed, as Azure Web Apps work with completely regular projects. Let's do that investigation step first, and we can go from there. If it fails to deploy locally as well, then at least we can close here knowing that it is not Azure/Kudu related.

**Comment by YingP99** [comment]
@davidebbo thanks. Issue resolved (missing js file from project).

**Comment by x00105893** [comment]
Hello, what kind of a file? I have the same problem. What was the solution to this please?

**Comment by davidebbo** [comment]
@x00105893 so yours also fails to deploy locally using the steps above? In @YingP99's case, it was apparently a .js file.

**Comment by x00105893** [comment]
it runs locally normally, but when i'm trying to deploy to azure using github it gives the same error. I couldnt figure out where do i get this .js file from, i'm new to this
Thank you

**Comment by davidebbo** [comment]
Please try the steps suggested in my first reply in this thread.

**Comment by ViprService** [comment]
Mine is _reference.js under Scripts folder

**Comment by x00105893** [comment]
i went through the steps, ran it as website. All working. What is my next step please?

**Comment by davidebbo** [comment]
Next step would be the share a repo that demonstrates the issue. See [this page](https://github.com/projectkudu/kudu/wiki/Using-a-git-repo-to-report-an-issue) for details.

**Comment by x00105893** [comment]
my github https://github.com/x00105893/Project2015

**Comment by davidebbo** [comment]
And to make sure there is no misunderstanding, can you confirm that you are getting the same error as in this issue: `error MSB4057: The target "pipelinePreDeployCopyAllFilesToOneFolder" does not exist in the project`?

**Comment by x00105893** [comment]
negative, i get a fault in azure, while it trying to deploy using github. full error looks like this:



Command: "D:\home\site\deployments\tools\deploy.cmd"

Handling .NET Web Application deployment.

All packages listed in packages.config are already installed.

All packages listed in packages.config are already installed.

  ContactManager -> D:\home\site\repository\ContactManager\bin\ContactManager.dll

  Transformed Web.config using D:\home\site\repository\ContactManager\Web.Release.config into obj\Release\TransformWebConfig\transformed\Web.config.

  Copying all files to temporary location below for package/publish:

  D:\local\Temp\e6da67ac-32c0-42a8-b960-7675389e88a2.

D:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v12.0\Web\Microsoft.Web.Publishing.targets(2988,5): error : Copying file App_Data\aspnet-ContactManager-20150306010642.mdf to D:\local\Temp\e6da67ac-32c0-42a8-b960-7675389e88a2\App_Data\aspnet-ContactManager-20150306010642.mdf failed. Could not find file 'App_Data\aspnet-ContactManager-20150306010642.mdf'. [D:\home\site\repository\ContactManager\ContactManager.csproj]

Failed exitCode=1, command="D:\Windows\Microsoft.NET\Framework\v4.0.30319\MSBuild.exe" "D:\home\site\repository\ContactManager\ContactManager.csproj" /nologo /verbosity:m /t:Build /t:pipelinePreDeployCopyAllFilesToOneFolder /p:_PackageTempDir="D:\local\Temp\e6da67ac-32c0-42a8-b960-7675389e88a2";AutoParameterizationWebConfigConnectionStrings=false;Configuration=Release /p:SolutionDir="D:\home\site\repository\.\\"

An error has occurred during web site deployment.

Handling .NET Web Application deployment.
All packages listed in packages.config are already installed.
All packages listed in packages.config are already installed.
  ContactManager -> D:\home\site\repository\ContactManager\bin\ContactManager.dll
  Transformed Web.config using D:\home\site\repository\ContactManager\Web.Release.config into obj\Release\TransformWebConfig\transformed\Web.config.
  Copying all files to temporary location below for package/publish:
  D:\local\Temp\e6da67ac-32c0-42a8-b960-7675389e88a2.
D:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v12.0\Web\Microsoft.Web.Publishing.targets(2988,5): error : Copying file App_Data\aspnet-ContactManager-20150306010642.mdf to D:\local\Temp\e6da67ac-32c0-42a8-b960-7675389e88a2\App_Data\aspnet-ContactManager-20150306010642.mdf failed. Could not find file 'App_Data\aspnet-ContactManager-20150306010642.mdf'. [D:\home\site\repository\ContactManager\ContactManager.csproj]
Failed exitCode=1, command="D:\Windows\Microsoft.NET\Framework\v4.0.30319\MSBuild.exe" "D:\home\site\repository\ContactManager\ContactManager.csproj" /nologo /verbosity:m /t:Build /t:pipelinePreDeployCopyAllFilesToOneFolder /p:_PackageTempDir="D:\local\Temp\e6da67ac-32c0-42a8-b960-7675389e88a2";AutoParameterizationWebConfigConnectionStrings=false;Configuration=Release /p:SolutionDir="D:\home\site\repository\.\\"
An error has occurred during web site deployment.
D:\Program Files (x86)\SiteExtensions\Kudu\44.40324.1452\bin\scripts\starter.cmd "D:\home\site\deployments\tools\deploy.cmd"

**Comment by davidebbo** [comment]
But you started out saying you had the same problem. I think that's the root of the confusion. If you have an unrelated deployment issue, we'll definitely want a new issue. A given issue is never used to track more than one problem.

**Comment by x00105893** [comment]
ahh, i see. it felt like i had the same issue. My bad.
Apologise.

**Comment by davidebbo** [comment]
No problem. We're happy to help with your problem too. :)

**Comment by timgabrhel** [comment]
https://github.com/timgabrhel/aspnetcore-kudurepro

I've created a repository with a repro project. See the readme for steps taken to see this error.

**Comment by akakira** [comment]
Unload the project, right click it go to tools, edit, then add these lines below the only import node in the file:

    <Import Project="$(VSToolsPath)\WebApplications\Microsoft.WebApplication.targets" 
        Condition="'$(VSToolsPath)' != ''" />
    <Import Project="$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v11.0\WebApplications\Microsoft.WebApplication.targets" 
        Condition="true" />

**Comment by davidebbo** [comment]
@timgabrhel I was able to make your repo work with Kudu by simply adding a global.json at the root:

```
{
  "projects": [ "src", "test" ],
  "sdk": {
    "version": "1.0.0-preview2-1-003177"
  }
}
```

**Comment by rnelson30** [comment]
I am also getting this issue. I am working in visual studio for mac (I think that might be the issue). I added the global.json file to my WebAPI project and I am still getting "error MSB4057: The target "pipelinePreDeployCopyAllFilesToOneFolder" does not exist in the project."  When I set it as my start up project and run it I get this for a stack trace:

"at System.Web.StaticFileHandler.ProcessRequest (System.Web.HttpContext context) [0x00094] in /private/tmp/source-mono-2017-02/bockbuild-2017-02/profiles/mono-mac-xamarin/build-root/mono-x86/mcs/class/System.Web/System.Web/StaticFileHandler.cs:77 
  at System.Web.DefaultHttpHandler.BeginProcessRequest (System.Web.HttpContext context, System.AsyncCallback callback, System.Object state) [0x0007f] in /private/tmp/source-mono-2017-02/bockbuild-2017-02/profiles/mono-mac-xamarin/build-root/mono-x86/mcs/class/System.Web/System.Web/DefaultHttpHandler.cs:101 
  at System.Web.HttpApplication+<Pipeline>d__225.MoveNext () [0x008d4] in /private/tmp/source-mono-2017-02/bockbuild-2017-02/profiles/mono-mac-xamarin/build-root/mono-x86/mcs/class/System.Web/System.Web/HttpApplication.cs:1335 
  at System.Web.HttpApplication.Tick () [0x00000] in /private/tmp/source-mono-2017-02/bockbuild-2017-02/profiles/mono-mac-xamarin/build-root/mono-x86/mcs/class/System.Web/System.Web/HttpApplication.cs:927

**Comment by michael-nee-mw** [comment]
I'm getting this error for deploying any website currently to a new server.

The site builds fine on the server manually.

Windows 2012 R2 with IIS 8.5

**Comment by davidebbo** [comment]
@rnelson30 @michael-nee-mw tracked by #2530
