### ISSUE TITLE
Should use of Environment Varialbe (APPSETTING_COMMAND) disable the use of .deployment?

### ISSUE THREAD

**Issue by SyntaxC4** [projectkudu/kudu#1519]
In this [sample application](https://github.com/SyntaxC4-MSFT/WAWS-Composer) I am using a `.deployment` file to set the project, however I have a site extension installed ([Composer](http://www.siteextensions.net/packages/ComposerExtension/)) which hooks the **Command** Environment Variable to add a custom deployment script to hook up the composer.phar execution.

When the sample application is deployed using GitHub integration, the project is not picked up so it deploys the contents of the repository root, instead of just deploying the contents of the web folder.

**Comment by davidebbo** [comment]
If you set the `command`, then you are completely taking over the deployment script with your own. At that point all other deployment settings only apply if your custom script still honors them.

Or am I misunderstanding the scenario? Is the part about it coming from your site extension relevant to the question, or would your question be the same if you had set the `command` via the portal?

**Comment by SyntaxC4** [comment]
If I put the **DEPLOYMENT_SOURCE** environment variable in the portal it deploys the proper folder as expected. I will document the need to do this if you were to depend on a .deployment file in your application when using my extension which overrides the command. Thanks!

**Comment by parkersweb** [comment]
@SyntaxC4 Could you elaborate on that last item? I'm using the Composer extension - but the APPSETTING_COMMAND variable is preventing my custom deployment script from being used. I'd seen [this](https://github.com/SyntaxC4-MSFT/ComposerExtension/issues/12) issue - but wondered if there's a way to force the deployment back to using my script?

Thanks!

**Comment by shadowmute** [comment]
@parkersweb If you modify `SiteExtensions/ComposerExtension/applicationHost.xdt` where it adds the environment variable APPSETTING_COMMAND to:
`<add name="APPSETTING_COMMAND" value="%HOME%\SiteExtensions\ComposerExtension\Hooks\deploy.cmd" xdt:Transform="Remove" />` and restart the application, it should go back to deploying your custom script. 

I imagine it'd be the same process for any extensions in the future that try to do the same.
