### ISSUE TITLE
Application and Service link shows as http://localhost:XXXX/

### ISSUE THREAD

**Issue by AlexandreRoba** [projectkudu/kudu#1521]
I have deploy kudu on our dev web server.
Everytime I create a new application the urls displayed on the dashboard contains localhost such as

Application URL
http://localhost:47793/
This is the link to your website.

Service URL
http://localhost:5306/
This is the link to the kudu service.

How can I have an IP or Host name used.

I cannot use the urlBaseValue as I have no DNS and I do not want to update all the devs host files.

I can copy past the url from the dashboard and replace the host with the IP and this works. but I want to have valid values displayed on the page.

Thanks for any help.

**Comment by davidebbo** [comment]
We typically only run on local machine for testing. I know @jeme has done a lot of work with host names and bindings. Maybe he'll have some thoughts here.

I suppose it could be as simple as changing 'localhost' to the machine's name. e.g. around [this code](https://github.com/projectkudu/kudu/blob/85809ddf7538919215ff9683d6fd058054d4eceb/Kudu.SiteManagement/SiteManager.cs#L105) and a couple other places in that file.

Feel free to have a go at it.

**Comment by jeme** [comment]
This shouldn't be to difficult to add from that perspective.

I think it would be a good idea to clean up around how bindings are currently converted into strings and then parsed as urls in the UI to display certain information. But for some cases it's hard to mix the concept of a binding and a url so a better idea might be to transport some sort of binding object to the UI which would contain more detailed information about Scheme, Port, Host etc...

That binding could then allow for converting it into a usable URL.

**Comment by AlexandreRoba** [comment]
Hey all,

Thanks a lot for getting back to me on this. 
@jeme Far from me the intention to put pressure on you, :) but do you have any plan on implementing this on a near futur?

Again thanks for all the good work you are putting this.

Alex.

**Comment by jvano** [comment]
Hi

Kudu will continue to run in Azure App Service. However, this repo will no longer be maintained.
If the problem persists and is related to running on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
