### ISSUE TITLE
Nuget package restore failing

### ISSUE THREAD

**Issue by freetrialbeforebuying** [projectkudu/kudu#1524]
I am getting the below error when deploying azure web site from local git repository. I was under the impression that with the nuget's new restore flow downloading of missing packages should be automatically handled. Also some of the packages were installed successfully. The below error showed up twice in the log. 

This project references NuGet package(s) that are missing on this computer. Enable NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=317567.
Failed exitCode=1, command="D:\Windows\Microsoft.NET\Framework\v4.0.30319\MSBuild.exe" "D:\home\site\repository\Some.API\Some.API.csproj" /nologo /verbosity:m /t:Build /t:pipelinePreDeployCopyAllFilesToOneFolder /p:_PackageTempDir="D:\local\Temp\da975b77-8365-46bf-9394-fa5bf6eca016";AutoParameterizationWebConfigConnectionStrings=false;Configuration=Release /p:SolutionDir="D:\home\site\repository\.\\"
An error has occurred during web site deployment.
d:\Program Files (x86)\SiteExtensions\Kudu\44.40324.1452\bin\scripts\starter.cmd "D:\home\site\deployments\tools\deploy.cmd"

**Comment by davidebbo** [comment]
Kudu does do NuGet package restore by default, and this normally works fine. Could you [share a test repo](https://github.com/projectkudu/kudu/wiki/Using-a-git-repo-to-report-an-issue) that demonstrates what you are seeing? Thanks!

**Comment by freetrialbeforebuying** [comment]
Hi David,

The project is at https://github.com/freetrialbeforebuying/ARIA.API

One thing I noticed is that with my existing project I already had the "packages" folder and it was building fine but I got the error (posted in my issue description) when trying to deploy to azure. When I cloned a fresh project (i.e. without the "packages" folder) visual studio build gave the same error. I am not sure what am I missing ? Shouldn't the new Microsoft.Bcl.Build and nuget 2.7+ take care of restoring the packages automatically. 

Thanks

**Comment by davidebbo** [comment]
I was not able to access your project (404). In any event, if you see the same issue locally with a clean clone, we at least know it is not Azure/Kudu related!

**Comment by freetrialbeforebuying** [comment]
Sorry I had to delete the repo because connections strings slipped in. It should be up now. Thanks.

**Comment by davidebbo** [comment]
You should delete it again, as your connection strings are still in your history! :( In any case, since we established that it is not Kudu related, it becomes more of a NuGet/msbuild issue, and there are better places to discuss that.

**Comment by freetrialbeforebuying** [comment]
thats silly of me.. completely forgot the history. And you are right there are better places to discuss.. but i thought since you are the nuget expert it would be helpful to get some insights. In any case thank you for making azure web sites deployment so easy with project kudu. Its fantastic !

**Comment by davidebbo** [comment]
Thanks for the feedback!

While it's not likely that someone had time to catch your connection string, if the data is very sensitive, I would suggest regenerating the key, to be on the safe side.
