### ISSUE TITLE
Kudu Azure GitHub

### ISSUE THREAD

**Issue by ryankekos** [projectkudu/kudu#1525]
We're having a problem figuring out how to get Kudu to pull a repo from GitHub using the API in Windows Azure Pack - Web Sites. From the API (https://github.com/projectkudu/kudu/wiki/REST-API) it seems we can use something like:

```
Payload: { format: 'basic', url: 'https://github.com/SomeOrg/SomeRepo.git' } 
```

Would that work?

**Comment by davidebbo** [comment]
Yes, that looks correct. e.g. this is a sample `curl` command line:

    curl -H "Content-Type: application/json" --data "{ format: 'basic', url: 'https://github.com/KuduApps/SimpleWebApplication.git' }" %KUDU_URL%/deploy

**Comment by ryankekos** [comment]
Thanks David! We'll play around with that. How does Kudu interact with GitHub when it's a private repo however.

**Comment by davidebbo** [comment]
It's done by setting up an ssh deploy key on GitHub. Some details [here](https://github.com/projectkudu/kudu/wiki/Continuous-deployment#for-private-repos-set-up-a-deploy-key)

**Comment by ryankekos** [comment]
David,

Thanks however that SSH key via URL doesn't seem to work with Windows Azure Pack version of Kudu (build 1.23.21216.1). Ideas?

**Comment by suwatch** [comment]
This is a very old Kudu version whose actual API may not be consistent with the wiki.   Can you elaborate <b>doesn't seem to work</b>?  404?   Try remove the prefix /api see if it helps.

**Comment by ryankekos** [comment]
Nice that worked! We'll play around with that. Hopefully the Chris Compy and the WAP team can get an updated version of Kudu soon. I think they said it was a goal.

**Comment by ryankekos** [comment]
Last question. Rather than having users set the deploy SSH key in GitHub and the like is it possible to have them authorize our application to have access to their private repo's? If so how would that work with Kudu?

**Comment by suwatch** [comment]
Once you have oauth to user's github, you can use Github API to list repos for user to choose, the set the webhook as well as, for private repo, the deploy SSH key accordingly.   We have Github api [samples here](https://github.com/suwatch/AzureSourceControls/blob/master/GitHubProxy.cs).   The webhook uri is simply the uri to Kudu /deploy with embedded basic auth cred.
