### ISSUE TITLE
ASP.NET v5 deploy through git fails

### ISSUE THREAD

**Issue by timmyd983** [projectkudu/kudu#1528]
First I got a path too long exception, then I removed node_modules and tried committing/repushing:

```
remote: Using Package dependency Microsoft.Framework.Runtime.Loader 1.0.0-beta4-11087
remote:   Copying files for Asp.Net,Version=v5.0
remote:     Source: D:\home\site\repository\approot\packages\Microsoft.Framework.Runtime.Loader\1.0.0-beta4-11087
remote:     Target: D:\local\Temp\9714c587-5837-4850-947c-845e8411e93a\approot\packages\Microsoft.Framework.Runtime.Loader\1.0.0-beta4-11087
remote:     File: Microsoft.Framework.Runtime.Loader.nuspec
remote:     File: lib\aspnet50\Microsoft.Framework.Runtime.Loader.dll
remote:
remote: Using Package dependency Microsoft.Framework.FileSystemGlobbing 1.0.0-beta4-10842
remote:   Copying files for Asp.Net,Version=v5.0
remote:     Source: D:\home\site\repository\approot\packages\Microsoft.Framework.FileSystemGlobbing\1.0.0-beta4-10842
remote:     Target: D:\local\Temp\9714c587-5837-4850-947c-845e8411e93a\approot\packages\Microsoft.Framework.FileSystemGlobbing\1.0.0-beta4-10842
remote:     File: Microsoft.Framework.FileSystemGlobbing.nuspec
remote:     File: lib\aspnet50\Microsoft.Framework.FileSystemGlobbing.dll
remote:
remote: Using Project dependency GearUp 1.0.0 for Asp.Net,Version=v5.0
remote:   Copying source code from Project dependency GearUp
remote:     Source D:\home\site\repository\approot\src\GearUp\project.json
remote:     Target D:\local\Temp\9714c587-5837-4850-947c-845e8411e93a\approot\src\GearUp
remote: ....
remote:
remote: Bundling runtime KRE-CLR-win-x86.1.0.0-beta3
**remote: System.UnauthorizedAccessException: Access to the path 'D:\local\Temp\9714c587-5837-4850-947c-845e8411e93a\../../../wwwroot' is denied.**
remote: An error has occurred during web site deployment.
remote:    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
remote:    at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
remote:    at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
remote:    at System.IO.Directory.CreateDirectory(String path)
remote:    at Microsoft.Framework.PackageManager.Bundle.BundleProject.PostProcess(BundleRoot root)
remote:    at Microsoft.Framework.PackageManager.Bundle.BundleRoot.Emit()
remote:    at Microsoft.Framework.PackageManager.Bundle.BundleManager.Bundle()
remote:    at Microsoft.Framework.PackageManager.Program.<>c__DisplayClass3_2.<Main>b__4()
remote:    at Microsoft.Framework.Runtime.Common.CommandLine.CommandLineApplication.Execute(String[] args)
remote:    at Microsoft.Framework.PackageManager.Program.Main(String[] args)
remote:
remote: Error - Changes committed to remote repository but deployment to website failed.
To https://timmy@gearbuilder-test.scm.azurewebsites.net:443/gearbuilder.git
   c7d2200..09013f7  master -> master
```

**Comment by timmyd983** [comment]
I basically ran: kpm bundle -o \tmp\testout ; cd \tmp\testout ; git clone https://whatever ; cd clonedrepos; mv ../testout/* .; git add .; git commit ; git push

I originally tried pushing from my source repos rather than a bundle, but it seems that azure web apps don't support asp.net v5 without kpm bundling first.

**Comment by davidfowl** [comment]
There's 2 problems here. You're deploying beta4 bits and kudu is using the beta3 SDK. That won't work as the bundle process will end up not excluding the right bits (beta3 was bundleExclude and beta4 was recently changed to publishExclude).

Kudu doesn't currently support beta4 but it will be coming soon.

**Comment by timmyd983** [comment]
Thanks David for the quick reply. I tried targetting beta3. This error may be less helpful:

remote: Using Package dependency Microsoft.CodeAnalysis.Analyzers 1.0.0-rc1
remote:   Copying files for Asp.Net,Version=v5.0
remote:     Source: D:\home\site\repository\approot\packages\Microsoft.CodeAnalysis.Analyzers\1.0.0-rc1
remote:     Target: D:\local\Temp\b5216afa-fb5e-439f-8706-a2fc6f8aa0a0\approot\packages\Microsoft.CodeAnalysis.Analyzers\1.0.0-rc1
remote:     File: Microsoft.CodeAnalysis.Analyzers.nuspec
remote:
remote: Using Package dependency Microsoft.Framework.Runtime.Loader 1.0.0-beta3
remote:   Copying files for Asp.Net,Version=v5.0
remote:     Source: D:\home\site\repository\approot\packages\Microsoft.Framework.Runtime.Loader\1.0.0-beta3
remote:     Target: D:\local\Temp\b5216afa-fb5e-439f-8706-a2fc6f8aa0a0\approot\packages\Microsoft.Framework.Runtime.Loader\1.0.0-beta3
remote:     File: Microsoft.Framework.Runtime.Loader.nuspec
remote:     File: lib\aspnet50\Microsoft.Framework.Runtime.Loader.dll
remote:
remote: Using Project dependency GearUp 1.0.0 for Asp.Net,Version=v5.0
remote:   Copying source code from Project dependency GearUp
remote:     Source D:\home\site\repository\approot\src\GearUp\project.json
remote:     Target D:\local\Temp\b5216afa-fb5e-439f-8706-a2fc6f8aa0a0\approot\src\GearUp
remote:
remote: Bundling runtime KRE-CLR-win-x86.1.0.0-beta3
**remote: An error has occurred during web site deployment.**
remote:
remote: Error - Changes committed to remote repository but deployment to website failed.
To https://timmy@gearbuilder-test2.scm.azurewebsites.net:443/gearbuilder.git
 + cf35a53...07f1efc master -> master (forced update)

**Comment by timmyd983** [comment]
This was the error farther up:

remote: Using Package dependency Ix-Async 1.2.3
remote:   Copying files for Asp.Net,Version=v5.0
remote:     Source: D:\home\site\repository\approot\packages\Ix-Async\1.2.3
remote:     Target: D:\local\Temp\b5216afa-fb5e-439f-8706-a2fc6f8aa0a0\approot\packages\Ix-Async\1.2.3
remote:     File: Ix-Async.nuspec
remote:     File: lib\net45\System.Interactive.Async.dll
remote:
remote: Using Package dependency Remotion.Linq 1.15.15.0
remote:   Copying files for Asp.Net,Version=v5.0
remote:     Source: D:\home\site\repository\approot\packages\Remotion.Linq\1.15.15.0
remote:     Target: D:\local\Temp\b5216afa-fb5e-439f-8706-a2fc6f8aa0a0\approot\packages\Remotion.Linq\1.15.15.0
remote:     File: Remotion.Linq.nuspec
remote: System.UnauthorizedAccessException: Access to the path 'D:\local\Temp\b5216afa-fb5e-439f-8706-a2fc6f8aa0a0\../../../wwwroot' is denied.
remote:     File: lib\portable-net45+wp80+wpa81+win\Remotion.Linq.dll
remote:    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
remote:
remote:    at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
remote: Using Package dependency System.Collections.Immutable 1.1.33-beta
remote:    at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
remote:   Copying files for Asp.Net,Version=v5.0
remote:    at System.IO.Directory.CreateDirectory(String path)
remote:     Source: D:\home\site\repository\approot\packages\System.Collections.Immutable\1.1.33-beta
remote:    at Microsoft.Framework.PackageManager.Bundle.BundleProject.PostProcess(BundleRoot root)
remote:     Target: D:\local\Temp\b5216afa-fb5e-439f-8706-a2fc6f8aa0a0\approot\packages\System.Collections.Immutable\1.1.33-beta
remote:    at Microsoft.Framework.PackageManager.Bundle.BundleRoot.Emit()
remote:     File: System.Collections.Immutable.nuspec
remote:    at Microsoft.Framework.PackageManager.Bundle.BundleManager.Bundle()
remote:     File: lib\portable-net45+win8+wp8+wpa81\System.Collections.Immutable.dll
remote:    at Microsoft.Framework.PackageManager.Program.<>c__DisplayClass3_2.<Main>b__4()
remote:
remote:    at Microsoft.Framework.Runtime.Common.CommandLine.CommandLineApplication.Execute(String[] args)
remote: Using Package dependency Microsoft.Framework.CommandLineUtils 1.0.0-beta3
remote:    at Microsoft.Framework.PackageManager.Program.Main(String[] args)
remote:   Copying files for Asp.Net,Version=v5.0
remote:     Source: D:\home\site\repository\approot\packages\Microsoft.Framework.CommandLineUtils\1.0.0-beta3
remote:     Target: D:\local\Temp\b5216afa-fb5e-439f-8706-a2fc6f8aa0a0\approot\packages\Microsoft.Framework.CommandLineUtils\1.0.0-beta3
remote:     File: Microsoft.Framework.CommandLineUtils.nuspec
remote:     File: lib\aspnet50\Microsoft.Framework.CommandLineUtils.dll
remote:
remote: Using Package dependency EntityFramework.Commands 7.0.0-beta3
remote:   Copying files for Asp.Net,Version=v5.0
remote:     Source: D:\home\site\repository\approot\packages\EntityFramework.Commands\7.0.0-beta3
remote:     Target: D:\local\Temp\b5216afa-fb5e-439f-8706-a2fc6f8aa0a0\approot\packages\EntityFramework.Commands\7.0.0-beta3
remote:     File: EntityFramework.Commands.nuspec

**Comment by timmyd983** [comment]
Sorry, please ignore those. kpm still had a few beta4 packages in there

**Comment by timmyd983** [comment]
Welp... still doesn't seem to work. Seems like I'd have to go back to beta2 to get ftp deploy to work?




remote: Using Package dependency Microsoft.CodeAnalysis.Common 1.0.0-rc1
remote:   Copying files for Asp.Net,Version=v5.0
remote:     Source: D:\home\site\repository\approot\packages\Microsoft.CodeAnalysis.Common\1.0.0-rc1
remote:     Target: D:\local\Temp\655c4cdc-fa61-46b2-8733-f10ae484d979\approot\packages\Microsoft.CodeAnalysis.Common\1.0.0-rc1
remote:     File: Microsoft.CodeAnalysis.Common.nuspec
remote:     File: lib\net45\Microsoft.CodeAnalysis.Desktop.dll
remote:     File: lib\net45\Microsoft.CodeAnalysis.dll
remote:
remote: System.UnauthorizedAccessException: Access to the path 'D:\local\Temp\655c4cdc-fa61-46b2-8733-f10ae484d979\../../../wwwroot' is denied.
remote: Using Package dependency Ix-Async 1.2.3
remote:    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
remote:   Copying files for Asp.Net,Version=v5.0
remote:    at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
remote:     Source: D:\home\site\repository\approot\packages\Ix-Async\1.2.3
remote:    at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
remote:     Target: D:\local\Temp\655c4cdc-fa61-46b2-8733-f10ae484d979\approot\packages\Ix-Async\1.2.3
remote:    at System.IO.Directory.CreateDirectory(String path)
remote:     File: Ix-Async.nuspec
remote:    at Microsoft.Framework.PackageManager.Bundle.BundleProject.PostProcess(BundleRoot root)
remote:     File: lib\net45\System.Interactive.Async.dll
remote:    at Microsoft.Framework.PackageManager.Bundle.BundleRoot.Emit()
remote:
remote:    at Microsoft.Framework.PackageManager.Bundle.BundleManager.Bundle()
remote: Using Package dependency Remotion.Linq 1.15.15.0
remote:    at Microsoft.Framework.PackageManager.Program.<>c__DisplayClass3_2.<Main>b__4()
remote:   Copying files for Asp.Net,Version=v5.0
remote:    at Microsoft.Framework.Runtime.Common.CommandLine.CommandLineApplication.Execute(String[] args)
remote:     Source: D:\home\site\repository\approot\packages\Remotion.Linq\1.15.15.0
remote:    at Microsoft.Framework.PackageManager.Program.Main(String[] args)
remote:     Target: D:\local\Temp\655c4cdc-fa61-46b2-8733-f10ae484d979\approot\packages\Remotion.Linq\1.15.15.0
remote:     File: Remotion.Linq.nuspec
remote:     File: lib\portable-net45+wp80+wpa81+win\Remotion.Linq.dll

**Comment by timmyd983** [comment]
ok i got it fixed. kudu worked fine when pushing from my regular source git repo, not when I tried kpm bundling and then creating a git repo with just those files
