### ISSUE TITLE
Site Extension Cannot Configure IISNODE via web.config or iisnode.yml

### ISSUE THREAD

**Issue by ashelley** [projectkudu/kudu#1530]
Hello,

I've created a site extension as a node.js application.  However, when installed as a site extension it cannot configure IISNODE and seemingly inherits the main websites configuration. 

Symptoms:
- Install a node.js based site extension for example using my sample site extension here: https://github.com/ashelley/hellohtml
- Notice that all logging is based on the actual website settings: ie: console.log from site extension goes to d:\home\LogFiles\Application*
- Also notice that if you turn off logging here on the main website, the site extension also =does not log at all:

![image](https://cloud.githubusercontent.com/assets/3195045/7072812/ccedb2c0-dea3-11e4-95d8-634fb76302f5.png)

Problem: 

IISNODE settings including logging should be configurable from web.config or iisnode.yml of the site extension.

Reproduction:

1) install the site extension from my example following instruction in the README

https://github.com/ashelley/hellohtml

2) notice that iisnode.yml as well as web.config does not properly configure IISNODE

**Comment by shrimpy** [comment]
@ashelley i tried your app, it works fine if i run "npm install --production" to install dependencies

you will need to pack all the dependencies into your nuget package.

![image](https://cloud.githubusercontent.com/assets/79823/7076240/d2f8f008-debc-11e4-94be-cda16bf53acb.png)

**Comment by ashelley** [comment]
Hello,

Please note that it is expected that the app works. Also note that if you install as per the README you will not need to run npm install as this is automatically handled within 
https://github.com/ashelley/hellohtml/blob/master/siteextension/install.cmd.

The problem is that IISNODE cannot be configured. I should have added some log output to this app but if you do add some console.logs to it you will see that it logs to d:\home\LogFiles\Application and is controlled by the settings of the application itself.  

If you look in web.config and iisnode.yml the log files should generate into the iisnode subdirectory of the site extension:

You can see the configuration here:

https://github.com/ashelley/hellohtml/blob/master/siteextension/web.config#L62
https://github.com/ashelley/hellohtml/blob/master/siteextension/iisnode.yml

But neither of these configuration options seem to work.  The logs for this will be generated into 

D:\home\LogFiles\Application*

I have updated the repository to add some explict logging:

https://github.com/ashelley/hellohtml/blob/master/app.js#L8

You will see that the logs will be generated into the applications log:

![image](https://cloud.githubusercontent.com/assets/3195045/7076585/537c70ea-debf-11e4-90f0-982c7a63bace.png)

I'd expect them to go in here based on the above configuration:

![image](https://cloud.githubusercontent.com/assets/3195045/7076599/7b189d22-debf-11e4-985f-d1e5d4076bbc.png)

Hope this helps understand the issue.  I might be configuring it incorrectly too (i'm not sure)

**Comment by ashelley** [comment]
Sorry, additional information.  Please also note that if you install via README instructions (view nuget package) that web.config as well as iisnode.yml both get extracted into the root of the site extension directory:

![image](https://cloud.githubusercontent.com/assets/3195045/7076708/1a55f88a-dec0-11e4-9038-a56788a5c8b9.png)

**Comment by shrimpy** [comment]
@ashelley I uploaded the package to [myget.org](https://www.myget.org/F/siteextensionstry/api/v2/package/HelloHtml/1.0.6
), installed as what you describe.

but i don`t see there is any application log under under "LogFiles" folder. did you do any extra configuration?

I will need a bit more time to familiar with iisnode. will try to see if i can have a sample working for you.

![image](https://cloud.githubusercontent.com/assets/79823/7093525/e68f942a-df6e-11e4-94d6-da0f86e0d2b0.png)


![image](https://cloud.githubusercontent.com/assets/79823/7093557/206a6440-df6f-11e4-8ce9-f8071da71154.png)


![image](https://cloud.githubusercontent.com/assets/79823/7093532/fefe70ee-df6e-11e4-841b-e16ba58effca.png)

**Comment by ashelley** [comment]
The only expected step is that you make a request to the site extension https://gotry.scm.azurewebsites.net/hellohtml

As it stands right now, without any additional steps, it is expected that a log file would be generated into the iisnode subdirectory in d:\home\SiteExtensions\HelloHtml\iisnode

The reason that I expect a log file to be placed in this directory is because of 1 of the two following configuration options:

![image](https://cloud.githubusercontent.com/assets/3195045/7093814/4ea54e4a-df71-11e4-9365-92019228009e.png)

The fact that there are no log files are generated into D:\home\SiteExtensions\HelloHtml\iisnode is a symptom of the problem i am reporting.  It shows that I am unable to configure IISNODE for the site extension.

However, to answer your question: to generate a log file into d:\home\LogFiles\Application you must configure logging onto the website itself.  To do this use the azure portal to configure logging on the website:

![image](https://cloud.githubusercontent.com/assets/3195045/7093966/483f99a6-df72-11e4-9c77-599817129de9.png)

To further explain:

1) The main problem I am reporting is the inability to configure IISNODE via web.config or iisnode.yml for the site extension

2) A by-product of not being able to configure IISNODE for the site extension is that I cannot prevent the site extension from poisoning the logs of the Application.  I wish to configure my site extension to have logging independent of the main site application.

**Comment by shrimpy** [comment]
@ashelley have you tried locally with your dev machine. does it work locally with similar configuration?

**Comment by ashelley** [comment]
@shrimpy I have tested locally within a normal iis website:

![image](https://cloud.githubusercontent.com/assets/3195045/7094540/13ee642a-df77-11e4-91c4-a9419d4c5435.png)

However I cannot install site extensions locally within kudu because it does not apply the applicationHost.xdt file https://github.com/projectkudu/kudu/issues/1451#issuecomment-90750537 so I am unsure on how to test that.

**Comment by shrimpy** [comment]
@ashelley can you try with absolute path, e.g:
````xml
    <iisnode loggingEnabled="true" logDirectory="D:\home\SiteExtensions\HelloHtml\iisnode" />
````

**Comment by shrimpy** [comment]
@ashelley 

the above approach i suggested will not work. @rramachand21 is going to work on the support.

for now there is a work-around, 
1) add "DIAGNOSTICS_AZUREDRIVELOGDIRECTORY" into app settings, 
the value will be path relative to "D:\home\site\wwwroot", e.g if you specify "iisnode", it will be "D:\home\site\wwwroot\iisnode", "..\\..\\SiteExtensions\HelloHtml\iisnode" will be "D:\home\SiteExtensions\HelloHtml\iisnode". 

- PS: this will impact all nodejs application.

2) turn on "APPLICATION LOGGING(FILE SYSTEM)"


once Ranjith`s work is done (next Website release), setting from web.config will be honor

**Comment by ashelley** [comment]
Hello @shrimpy 

This is really hard to explain but I will try.  I haven't been able to observe that an absolute path helps.  

Note that from the documentation this should be a relative path anyway:
https://github.com/tjanczuk/iisnode/blob/master/src/samples/configuration/iisnode.yml#L87-94

Okay,.. again just one more disclaimer, that this is a bit complicated to explain but I will try to document what I have observed so far.

1) To start off, I have created a new branch on the test case repo with some added code to help with some diagnostics.  

https://github.com/ashelley/hellohtml/tree/change-node-env

2) You will need to `git checkout change-node-env` after fetching the test case repository to follow my next steps of diagnostics of the problem.

3) The good news: I have established that my original hypothesis that iisnode could not be configured with web.config or iisnode.yml is wrong.  To prove this I have added the node_env parameter to web.config and have proven that it works (iisnode.yml also works).

![image](https://cloud.githubusercontent.com/assets/3195045/7148193/a463289c-e2b5-11e4-983e-ed490847e19c.png)

So going forward this thread is about getting logging working properly.

4) I have change the repo slightly to log D:\home\Logfiles\SiteExtensions\HelloHtml\iisnode.  This is by-product to trying to ensure that it wasn't a permissions issue or something on the ephermeral D:\home\SiteExtensions\HelloHtml directory

You can see this change here:
- create the directory on install.cmd
https://github.com/ashelley/hellohtml/blob/change-node-env/siteextension/install.cmd#L8

- setup the logDirectory configuration on iisnode
https://github.com/ashelley/hellohtml/blob/change-node-env/siteextension/web.config#L63
or
https://github.com/ashelley/hellohtml/blob/change-node-env/siteextension/iisnode.yml#L2

5) I have setup some logging in app.js to log the "full lifecycle" of the app, you can review all of the console.log and console.error statements in this file here:

https://github.com/ashelley/hellohtml/blob/change-node-env/app.js

6) Locally, if run the app the log files look like this:

![image](https://cloud.githubusercontent.com/assets/3195045/7148312/b39ab34c-e2b6-11e4-810f-af9f925b0b98.png)

7) If you run the app as a site extension you will notice that the *only* the logs during the request are logged to the application's logs:

![image](https://cloud.githubusercontent.com/assets/3195045/7148398/701ab134-e2b7-11e4-90f6-0ae25cfe2631.png)

8) You can check the configured log directory to see that it's still empty:

![image](https://cloud.githubusercontent.com/assets/3195045/7148427/a1f00fce-e2b7-11e4-813d-d8b009c8b146.png)

9) Now, to make this more confusing I have enabled an option in web.config to force the server to synchronously throw on startup.  To enable this option simply uncomment the following line in web.config

https://github.com/ashelley/hellohtml/blob/change-node-env/siteextension/web.config#L12

This line in web.config sets an environment variable that the test case app uses to trigger a condition in which it will throw an unhandled exception on startup:

https://github.com/ashelley/hellohtml/blob/change-node-env/app.js#L7-12

10) After you enable this option in web.config and visit the site extension you will notice that the app doesn't load (this is expected).

![image](https://cloud.githubusercontent.com/assets/3195045/7148509/66939e68-e2b8-11e4-8e20-4ca0df856678.png)

11) Now if you check the log directory you will see that the *logDirectory* setting was honoured:

![image](https://cloud.githubusercontent.com/assets/3195045/7148535/a77431b8-e2b8-11e4-87e3-e4243050b246.png)

You can see that logging-errors.txt was generated into the correct location.

12) I'm not sure why the synchronous throw causes iisnode to act properly and log the errors as expected.  To further diagnose the issue I've added an intentional asynchronous throw into the program to see if it will log that correctly. To do this you must return the web.config to its original state by commenting back the HELLOHTML_THROW_ON_START environment variable.

Once you can load the app you can visit /hellohtml/throw of your site extension to invoke the asynchronous exception.  You will notice that it logs to the application directory:

![image](https://cloud.githubusercontent.com/assets/3195045/7148665/f9f2af9a-e2b9-11e4-99f9-5980f8ae0674.png)

* Conclusion

- There is a period of time on startup where IISNODE does not hookup stdout or stderr properly based on the configuration settings.  
- However IISNODE can catch errors thrown synchronously on startup and log them to the correct directory

**Comment by ashelley** [comment]
@shrimpy I didn't notice that you had already updated this thread before the above post.  Please review the information in it as it may shed some more detailed light into what exactly is working and is not working.

- Please review especially steps 10 and 11 as this may be something that is not yet realized yet.

Thank you @rramachand21 for working on this.  

Can you please update this thread once the fix is live so that I may conclude my own testing.

Thank you!

**Comment by jvano** [comment]
Hi

Kudu will continue to run in Azure App Service. However, this repo will no longer be maintained.
If the problem persists and is related to running on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
