### ISSUE TITLE
Is there anyway to force a "Deploy (clean)" at every deployment?

### ISSUE THREAD

**Issue by AlexandreRoba** [projectkudu/kudu#1532]
Dear all,

I'm having a "Strange" Behavior.I have a SiteFinity Project and I manage to have it deployed with kudu.
But when I change only a cshtml view on the project. I can clearly see my new cshtml file deployed on the site folder but the site shows still the old version.

Tis my log:
remote: Updating branch 'master'.
remote: Updating submodules.
remote: Preparing deployment for commit id '09613e2963'.
remote: Generating deployment script.
remote: Running deployment command...
remote: Handling .NET Web Application deployment.
remote: All packages listed in packages.config are already installed.
remote:   SiteFinityWebApp -> C:\inetpub\apps\hubs\site\repository\src\HubConstructor\SiteFinityWebApp\bin\SitefinityWebApp.dll
remote:   Copying all files to temporary location below for package/publish:
remote:   C:\Users\hubs\AppData\Local\Temp\16fa32b5-8f38-4a3d-8319-c1181ae9b747.
remote: ....
remote: KuduSync.NET from: 'C:\Users\hubs\AppData\Local\Temp\16fa32b5-8f38-4a3d-8319-c1181ae9b747' to: 'C:\inetpub\apps\hubs\site\wwwroot'
remote: Copying file: 'web.config'
remote: Copying file: 'Mvc\Views\CbbParagraph\Default.cshtml'
remote: Finished successfully.
remote: Deployment successful.

If I go to the deployment Tabs and select the previous deployment and then select the latest one with the option Deploy(clean) Then it takes a bit longer to deploy and I can see my latest version...
I would like all my deploy to be done as Clean Deploy to force the recompilation.

Thanks for your help.

Alex.

**Comment by davidebbo** [comment]
Is that with Kudu running in Azure, or in your own deployment?

**Comment by AlexandreRoba** [comment]
HEllo Davidebbo,

thanks for your reply.
This is happening in our own dev server.

regards,

Alex

**Comment by davidebbo** [comment]
Unfortunately, I don't think we support this today, though we probably should. Right now the only time where the clean flag can be passed in is when redeploying a previously deployed build. But for CI scenarios and direct git push, the clean flag is always false.

Conceivably we could support an appsetting that would make it default to true instead of false.

However, I would also suggest understanding why the new cshtml doesn't get picked up. At this point it's not a Kudu issue but a runtime issue. The ASP.NET runtime is supposed to make this work. Do you repro by simply hand editing it and refreshing the page?

**Comment by davidmatson** [comment]
I also the need for a "force clean" option.

My scenario is that I'm using NuGet package restore with project.json. I forgot to push one of my packages, so the deployment fails. I amend the commit and force push to redeploy. But it still won't work; it says "Lock file has not changed. Skipping lock file write."
And then it doesn't successfully build even though the feed has the packages now.

Force clean sounds like the right answer for this class of problem.

**Comment by davidebbo** [comment]
I think this is basically the same as #2160. @ratestHub added a workaround there, which you may want to look at. Though I agree that ideally this should be a first class feature.

**Comment by jvano** [comment]
Hi

Kudu will continue to run in Azure App Service. However, this repo will no longer be maintained.
If the problem persists and is related to running on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
