### ISSUE TITLE
Using Push vs Fetch for many tests

### ISSUE THREAD

**Issue by davidebbo** [projectkudu/kudu#1534]
Right now, we have lots of tests that use PushAndDeployApps, which works by cloning the repo locally, and then pushing it to Kudu. Instead, it may make sense to have an alternate FetchAndDeployApp which uses our Clone from Kudu mechanism, which is more efficient.

Of course, we still need to keep a few tests that do big git pushes to make sure that works, but when the purpose of the test is more about building and runtime behavior, we may as well make it more efficient.

**Comment by jvano** [comment]
Hi

Kudu will continue to run in Azure App Service. However, this repo will no longer be maintained.
If the problem persists and is related to running on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
