### ISSUE TITLE
Deployment failure in .NET 4.5.2 web application with Microsoft.Bcl.Async dependency

### ISSUE THREAD

**Issue by olegsych** [projectkudu/kudu#1538]
Source code: https://github.com/olegsych/AzureWebSiteWithBclAsync
Deployment: http://azurewebsitewithbclasync.azurewebsites.net

A single-page .NET 4.5.2 web application referencing a .NET 4.0 class library which depends on the Microsoft.Bcl.Async NuGet package encounters the following build warning when deployed by Kudu:

```
D:\Windows\Microsoft.NET\Framework\v4.0.30319\Microsoft.Common.targets(1605,5): warning MSB3268: The primary reference "D:\home\site\repository\WebApplication1\ClassLibrary1\bin\Release\ClassLibrary1.dll" could not be resolved because it has an indirect dependency on the framework assembly "System.Runtime, Version=4.0.10.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" which could not be resolved in the currently targeted framework. ".NETFramework,Version=v4.5.2". To resolve this problem, either remove the reference "D:\home\site\repository\WebApplication1\ClassLibrary1\bin\Release\ClassLibrary1.dll" or retarget your application to a framework version which contains "System.Runtime, Version=4.0.10.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a". [D:\home\site\repository\WebApplication1\WebApplication1\WebApplication1.csproj]
```
The same application can be built (with Visual Studio 2013 Update 4) and run locally without problems. Note that the ClassLibrary1 actually needs the System.Runtime.dll v2.6.8 from the Microsoft.Bcl NuGet package. It gets copied to the app bin folder when built by Visual Studio, but not by Kudu's build.

**Comment by olegsych** [comment]
This problem was initially reported with the Microsoft.ApplicationInsights NuGet package v0.14 on the [Application Insights forum](https://social.msdn.microsoft.com/Forums/vstudio/en-US/11263f59-579c-4401-834f-6a91c3834f21).

cc:@SergKanz, @abaranch

**Comment by davidebbo** [comment]
I think this is the same as #1485, which we need to address.
