### ISSUE TITLE
to not run kudu.exe if SCM_DISABLE_DEPLOY_ON_PUSH is set

### ISSUE THREAD

**Issue by suwatch** [projectkudu/kudu#1540]
I guess we could have done below (as opposed to  [this](https://github.com/projectkudu/kudu/commit/081c846a947324fc2358a2ce6cbb91431d437898)) or not having post-receive shell script at all if the env is set.

``` sh
#!/bin/sh
read i
echo $i > pushinfo
if [ "$SCM_DISABLE_DEPLOY_ON_PUSH" != "1" ] ; then
  echo "$KUDU_EXE" "$KUDU_APPPATH" "$KUDU_MSBUILD" "$KUDU_DEPLOYER"
fi
```

**Comment by jvano** [comment]
Hi

Kudu will continue to run in Azure App Service. However, this repo will no longer be maintained.
If the problem persists and is related to running on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
