### ISSUE TITLE
Please wrap the text file with a normal code editor

### ISSUE THREAD

**Issue by weitzhandler** [projectkudu/kudu#1543]
I often want to add some minor changes to a website that's already been deployed using this awesome service.
Anyway, it would be nice if we can add a code editor like [jQ Ace](https://github.com/ajaxorg/ace) or the zillion others out there to the [<textaread/>](https://github.com/projectkudu/kudu/blob/master/Kudu.Services.Web/DebugConsole/Default.cshtml#L105) that uses to edit the text.

I'm sure there are open-source twitter-bootstrap compatible code-editors we can find.
I'd add a pull myself if I'd know what plugin you'd prefer using.

**Comment by davidebbo** [comment]
Current editor is definitely super primitive, and it could make sense to add Ace support.

Do note that you can also enable VS Online "Monaco" on your site, which gives you a super fancy in-browser editor.

**Comment by weitzhandler** [comment]
I'm sure there are better bootsrap-compliant editors out there.
Never heard of Monaco, will check it out.

**Comment by davidebbo** [comment]
See for info: http://channel9.msdn.com/Series/Visual-Studio-Online-Monaco

**Comment by ahmelsayed** [comment]
We actually have this now in e3ce7a165d793348f4f4e37c0059f47ddccaacae thanks to @snobu
