### ISSUE TITLE
PhantomJS during deploy causes an error

### ISSUE THREAD

**Issue by lukemcgregor** [projectkudu/kudu#1544]
I would like to be able to run some automated UI tests as part of the deploy process. However phantomJS explodes if you try and run it during the deploy with the following:

> Error: OpenQA.Selenium.WebDriverException: Unexpected error. System.Net.WebException:  
> Unable to connect to the remote server ---> System.Net.Sockets.SocketException: An attempt was
> made to access a socket in a way forbidden by its access permissions 127.0.0.1:50199

I think this is because phantomjs is an external app which C# talks to via a webservice. It would be great if this could be fixed to work.

**Comment by davidebbo** [comment]
There are general limitations around send requests to localhost from an Azure WebApp. This probably relates to this error.

**Comment by lukemcgregor** [comment]
Sounds likely, but it would be good if there were some path to do UI tests at deployment. The alternatives are pretty unideal, eg run a vm with a test server on it and get it to execute the tests for you. This is both slow and expensive.

My use case is 

 - Build 
 - Deploy staging
 - UI Tests
 - Swap to prod

**Comment by jvano** [comment]
Hi

Kudu will continue to run in Azure App Service. However, this repo will no longer be maintained.
If the problem persists and is related to running on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
