### ISSUE TITLE
.gitignore syntax in kudusync ignores

### ISSUE THREAD

**Issue by kostrse** [projectkudu/kudu#1547]
When I pass some ignores to the `kudusync -i`, it fails with this error:

```
Error: Wildcard support limited to prefix matching, e.g '*txt'. Other wildcard matching (or \\) is not supported
```

It would be great to:
1. Support all ignore rules from _.gitignore_ (like NPM does for its _.npmignore_).
2. Introduce an ignores file (e.g. **.kuduignore**) which would be detected by kudusync at the `--from` location and used as an alternative to the `-i` flag. A simple declarative file in source control would be much easier to review and maintain instead of having this inside of deployment script.

**Comment by abatishchev** [comment]
Just a friendly bump /cc @davidebbo.

**Comment by davidebbo** [comment]
Would be a good one for external contribution if someone has the cycles. Thanks!

**Comment by amitapl** [comment]
The limitation exists mostly for the .NET version of kudusync in order to make it perform faster.

**Comment by davidebbo** [comment]
@kostrse and @abatishchev: are you asking for this in the context of using kudusync for some other purpose, or is it in context of Kudu deployments?

**Comment by kostrse** [comment]
In the context of kudu deployments (inspired by Heroku):

`.deployment` has a great potential in running build scripts in various languages / build systems (e.g. written in python, gulp, etc...) against sources published directly from Git repo.

But the drawback in this *build on publish* approach is that when copying build artifacts to the webserver location with kudusync, you have to ignore the source files (as well as temp files, build scripts itself etc.) to prevent them being exposed via HTTP. And the existing syntax of the `kudusync --ignore` isn't very usable for this purpose because of lack of sophisticated glob pattern rules like `.gitignore` does support. 


Please have a look at this demo project I was using on one of tech meetups to demo build on publish in Azure Web Apps:
https://github.com/kostrse/coworkingmap

Instead of concatenating command line arguments to pass list of ignores it could be much more convenient to just check-in an *ignore* file instead.

https://github.com/kostrse/coworkingmap/blob/master/deploy/deploy.py#L40-L59

``` py
deployment_ignores = [
    ".gitignore",

    # Ignoring package manager configurations
    "node_modules",
    "bower.json",

    # Ignoring NPM modules (used only for build)
    "package.json",

    # Ignoring build script
    "gulpfile.js",

    # Ignoring TypeScript type definitions and sources
    "tsd.json",
    "*.ts",

    # Ignoring SASS files
    "*.scss"
]
```

**Comment by davidebbo** [comment]
@kostrse thanks for clarifying the scenario.I think it does make sense. So the tentative design would be:

- kudusync looks for a .kuduignore file at the root of the kudusync source folder (which may or may not be the repo).
- if present, it honors that in addition to the existing command line semantic

Notes:

- I think we can get away with only making this change in kudusync.net (https://github.com/projectkudu/KuduSync.NET). The Node version is not used on Azure, and it won't break anyway when used locally (it just won't honor that file).
- We'll need to come up with the syntax of that file. Maybe following .gitignore (or maybe some subset of it) is best as it's familiar.

Sergey, any chance you want to take on that task and send a PR? :)

**Comment by kostrse** [comment]
Will have a loop if I can find some existing implementation of gitignore matcher for .NET to utilize.
Or how could it be implemented to be consistent with Git rules.

**Comment by jvano** [comment]
Hi

Kudu will continue to run in Azure App Service. However, this repo will no longer be maintained.
If the problem persists and is related to running on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
