### ISSUE TITLE
Using Kudu to change virtual directory physical path for an Azure Website

### ISSUE THREAD

**Issue by davideweaver** [projectkudu/kudu#1548]
I'm trying to change the physical path of my webroot to a folder under "wwwroot". Using Kudu and deploy.cmd, I am launching a powershell script and using Microsoft.Web.Administration.ServerManager to do it, but I get a permission error when I do CommitChanges(). Can I launch the powershell script under elevated permissions or is there a better way to do what I want?

**Comment by davidebbo** [comment]
If this is on Azure Web App, you can change the IIS mapping in the Azure Portal, at the bottom of the configuration section.

![image](https://cloud.githubusercontent.com/assets/556238/7447308/b12c00d6-f1aa-11e4-9fef-83c0612ec756.png)

**Comment by davideweaver** [comment]
That does work, however I'd really like to be able to make the modification from within the deployment script. Is there a way to run the powershell script using elevated privileges?

**Comment by davidebbo** [comment]
No way to do this using PowerShell. However, you could do it using an xdt transform. e.g see sample [here](https://github.com/projectkudu/kudu/wiki/Xdt-transform-samples#adding-new-applications-to-the-main-site).

**Comment by koistya** [comment]
@davidebbo is there an example how to deploy two Node.js apps under the same Web App in Azure with Kudu? For example, one GitHub repository should go to www.example.com, and another GitHub repository to www.example.com/api/ both built as Node.js apps.

**Comment by davidebbo** [comment]
@koistya this is not really related to this issue, which was about setting up virtual directories. Your issue is about deploying from multiple github repos, which Kudu does not directly support.

**Comment by davidebbo** [comment]
Closing this one since original issue was resolved, but feel free to open new one to discuss that other topic separately.
