### ISSUE TITLE
Add native bower integration

### ISSUE THREAD

**Issue by mkliu** [projectkudu/kudu#1551]
I have two questions:
1. What's the official way to automatically install bower when deploying a repo to azure website? I found this but don't know if that's the suggested way. http://gregtrowbridge.com/deploying-a-bower-dependent-node-app-on-windows-azure/
2. Any plan to add native bower integration? From the code change I see pull requests to add bower to path. But at least my website isn't installing bower automatically for me. And actually looks like the machine doesn't have bower install at all either.

**Comment by davidebbo** [comment]
Bower is available in `D:\Program Files (x86)\bower\1.3.12`.

Do so any kind of custom deployment, you should look into using a [custom deployment script](http://blog.amitapple.com/post/38417491924/azurewebsitecustomdeploymentpart1/).

**Comment by mkliu** [comment]
hmm, I don't really need all the extra custom deployments. I like the native things provided by kudu, if I use the custom script, does that mean I'm on my own now? I just need the extra bower install, and actually given it's popularity, is Kudu considering install that by default?

**Comment by davidebbo** [comment]
I don't think the request has really come, at least not as an issue here. If you want to help things move forward, I'd suggest starting with the custom deployment script, and then share exactly  what you had to change to make it work.

**Comment by mkliu** [comment]
sure, one question, so i was trying this http://gregtrowbridge.com/deploying-a-bower-dependent-node-app-on-windows-azure/

But looks like in many cases the generated file is a .sh, but why my generated file is cmd?

I'm asking because I'm having a difficult time testing my change now. I tried to add the deploy.cmd file in monaco and execute the cmd directly. It's giving me this:


    \> deploy.cmd
    Installing Kudu Sync
    An error has occurred during web site deployment.

The following is the my cmd, i basically just added the bower section

    @if "%SCM_TRACE_LEVEL%" NEQ "4" @echo off

    :: ----------------------
    :: KUDU Deployment Script
    :: Version: 0.1.11
    :: ----------------------

    :: Prerequisites
    :: -------------

    :: Verify node.js installed
    where node 2>nul >nul
    IF %ERRORLEVEL% NEQ 0 (
      echo Missing node.js executable, please install node.js, if already installed make sure it can be reached from current environment.
      goto error
    )

    :: Setup
    :: -----

    setlocal enabledelayedexpansion

    SET ARTIFACTS=%~dp0%..\artifacts

    IF NOT DEFINED DEPLOYMENT_SOURCE (
      SET DEPLOYMENT_SOURCE=%~dp0%.
    )

    IF NOT DEFINED DEPLOYMENT_TARGET (
      SET DEPLOYMENT_TARGET=%ARTIFACTS%\wwwroot
    )

    IF NOT DEFINED NEXT_MANIFEST_PATH (
      SET NEXT_MANIFEST_PATH=%ARTIFACTS%\manifest

      IF NOT DEFINED PREVIOUS_MANIFEST_PATH (
        SET PREVIOUS_MANIFEST_PATH=%ARTIFACTS%\manifest
      )
    )

    IF NOT DEFINED KUDU_SYNC_CMD (
      :: Install kudu sync
      echo Installing Kudu Sync
      call npm install kudusync -g --silent
      IF !ERRORLEVEL! NEQ 0 goto error

      :: Locally just running "kuduSync" would also work
      SET KUDU_SYNC_CMD=%appdata%\npm\kuduSync.cmd
    )
    goto Deployment

    :: Utility Functions
    :: -----------------

    :SelectNodeVersion

    IF DEFINED KUDU_SELECT_NODE_VERSION_CMD (
      :: The following are done only on Windows Azure Websites environment
      call %KUDU_SELECT_NODE_VERSION_CMD% "%DEPLOYMENT_SOURCE%" "%DEPLOYMENT_TARGET%" "%DEPLOYMENT_TEMP%"
      IF !ERRORLEVEL! NEQ 0 goto error

      IF EXIST "%DEPLOYMENT_TEMP%\__nodeVersion.tmp" (
        SET /p NODE_EXE=<"%DEPLOYMENT_TEMP%\__nodeVersion.tmp"
        IF !ERRORLEVEL! NEQ 0 goto error
      )
      
      IF EXIST "%DEPLOYMENT_TEMP%\__npmVersion.tmp" (
        SET /p NPM_JS_PATH=<"%DEPLOYMENT_TEMP%\__npmVersion.tmp"
        IF !ERRORLEVEL! NEQ 0 goto error
      )

      IF NOT DEFINED NODE_EXE (
        SET NODE_EXE=node
      )

      SET NPM_CMD="!NODE_EXE!" "!NPM_JS_PATH!"
    ) ELSE (
      SET NPM_CMD=npm
      SET NODE_EXE=node
    )

    goto :EOF

    ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
    :: Deployment
    :: ----------

    :Deployment
    echo Handling node.js deployment.

    :: 1. KuduSync
    IF /I "%IN_PLACE_DEPLOYMENT%" NEQ "1" (
      call :ExecuteCmd "%KUDU_SYNC_CMD%" -v 50 -f "%DEPLOYMENT_SOURCE%" -t "%DEPLOYMENT_TARGET%" -n "%NEXT_MANIFEST_PATH%" -p "%PREVIOUS_MANIFEST_PATH%" -i ".git;.hg;.deployment;deploy.cmd"
      IF !ERRORLEVEL! NEQ 0 goto error
    )

    :: 2. Select node version
    call :SelectNodeVersion

    :: 3. Install npm packages
    IF EXIST "%DEPLOYMENT_TARGET%\package.json" (
      pushd "%DEPLOYMENT_TARGET%"
      call :ExecuteCmd !NPM_CMD! install --production
      IF !ERRORLEVEL! NEQ 0 goto error
      popd
    )

    :: 4. Select node version
    IF EXIST "%DEPLOYMENT_TARGET%\bower.json" (
      pushd "%DEPLOYMENT_TARGET%"
      call bower install
      IF !ERRORLEVEL! NEQ 0 goto error
      popd
    )

    ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

    :: Post deployment stub
    IF DEFINED POST_DEPLOYMENT_ACTION call "%POST_DEPLOYMENT_ACTION%"
    IF !ERRORLEVEL! NEQ 0 goto error

    goto end

    :: Execute command routine that will echo out when error
    :ExecuteCmd
    setlocal
    set _CMD_=%*
    call %_CMD_%
    if "%ERRORLEVEL%" NEQ "0" echo Failed exitCode=%ERRORLEVEL%, command=%_CMD_%
    exit /b %ERRORLEVEL%

    :error
    endlocal
    echo An error has occurred during web site deployment.
    call :exitSetErrorLevel
    call :exitFromFunction 2>nul

    :exitSetErrorLevel
    exit /b 1

    :exitFromFunction
    ()

    :end
    endlocal
    echo Finished successfully.

**Comment by mkliu** [comment]
Actually, although testing on monaco failed, the script worked when i just blindly push that up to azure website. All bower packages are installed correctly. :)

**Comment by davidebbo** [comment]
As long as it's harmless to sites that don't need it, I think we should consider adding that logic to the default script. @amitapl what do you think?

**Comment by amitapl** [comment]
What about existing sites that have that file, could it break them in some way?

**Comment by mkliu** [comment]
to update, bower.exe isn't in the PATH, the script above worked coz I installed bower on that git repo

**Comment by ahmelsayed** [comment]
`bower.cmd` should be on the path for [any process launched by kudu](https://github.com/projectkudu/kudu/blob/1d238f13ed7672ce5d5aac0798d9b978bbbfb605/Kudu.Core/Deployment/Generator/ExternalCommandFactory.cs#L96-L101). it's installed in `D:\Program Files (x86)\bower\1.3.12\bower.cmd`.

**Comment by mkliu** [comment]
hmm, i could see it's there in program files, but really when i open up monaco console, the cmd isn't recognized.

**Comment by ahmelsayed** [comment]
Yes you are right, Monaco console isn't going to have it. This will be there only for processes launched by kudu, so things like Kudu's console and deployment workflows.

**Comment by jvano** [comment]
Hi

Kudu will continue to run in Azure App Service. However, this repo will no longer be maintained.
If the problem persists and is related to running on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
