### ISSUE TITLE
Making sure Kudu behave reasonably in Read-only env

### ISSUE THREAD

**Issue by suwatch** [projectkudu/kudu#1553]
There is a situation in Azure where the file system may be put to R/O mode.   We just need to make sure that Kudu functions reasonably in that env.   To name a few,

  - web job continue to function.   may be missing some log
  - browse to SCM site + its CO. (Debug Console/ProcessExplorer..) should be functioning.
  - REST GET apis should be functioning.   We can review case by case.

**Comment by shrimpy** [comment]
[Fixing List Deployment operation](https://github.com/projectkudu/kudu/pull/1615)

**Comment by shrimpy** [comment]
With fix https://github.com/projectkudu/kudu/commit/5d306cca27a25d1a1dd18c57da545f0d5fb0a9f8, for read-only action that require file lock, they should working as expect. 

next will work on webjob!

**Comment by shrimpy** [comment]
we are good with continuous job, if the app crash, we already [had code to handle re-run it](https://github.com/projectkudu/kudu/blob/master/Kudu.Core/Jobs/ContinuousJobRunner.cs#L79).

**Comment by shrimpy** [comment]
scheduled trigger job will also recover. we can close this issue now.
