### ISSUE TITLE
Run script when environment variables change?

### ISSUE THREAD

**Issue by ejsmith** [projectkudu/kudu#1554]
I am hosting a static site on Azure that requires a few configuration settings. I am planning to manage those configuration settings in the app settings feature of Azure. Then I am going to create a deployment hook that runs a script that pulls the environment variables into a config.json file that the static site can read. My question is, is it possible to run code when the app settings in azure change?  When they are changed does it automatically trigger the normal deployment hooks?

**Comment by amitapl** [comment]
When the app settings of your website changes, the website is restarted.
But the deployment hooks are not invoked.
You could use a triggered WebJob to run a script but you will have to invoke it yourself after changing the configuration.
You could use a continuous WebJob that checks whether changes were made that require to recreate the config file when it starts (and then just sits idle) but you'll need to enable "Always On" for your site to make sure the WebJob is always running.
