### ISSUE TITLE
Process explorer shows Java app without parent.

### ISSUE THREAD

**Issue by suwatch** [projectkudu/kudu#1555]
While bugbash Try Now with Java Coffee house, notice this on Process Explorer.

![image](https://cloud.githubusercontent.com/assets/1088218/7546582/228ef7fa-f594-11e4-8b47-7ab2399979d7.png)

**Comment by jvano** [comment]
Hi

Kudu will continue to run in Azure App Service. However, this repo will no longer be maintained.
If the problem persists and is related to running on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
