### ISSUE TITLE
Kudu and deploy from BitBucket failing with no output

### ISSUE THREAD

**Issue by MikaelEliasson** [projectkudu/kudu#1558]
Our deployments stopped working and the only message I get in the tail log is:

```
D:\Program Files (x86)\SiteExtensions\Kudu\45.40512.1539\bin\scripts\starter.cmd deploy.cmd, stackTrace:    at Kudu.Core.Infrastructure.Executable.ExecuteInternal(ITracer tracer, Func`2 onWriteOutput, Func`2 onWriteError, Encoding encoding, String arguments, Object[] args)
   at Kudu.Core.Infrastructure.Executable.ExecuteWithProgressWriter(ILogger logger, ITracer tracer, String arguments, Object[] args)
   at Kudu.Core.Deployment.Generator.ExternalCommandBuilder.RunCommand(DeploymentContext context, String command)
   at Kudu.Core.Deployment.Generator.CustomBuilder.Build(DeploymentContext context)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Kudu.Core.Deployment.DeploymentManager.<Build>d__29.MoveNext()
```

Does anyone have an idea about where to start debugging this? Without an error message I feel a bit lost.

NPM fails on several packages before this but did so even when it was working so those libraries doesn't matter for this.

**Comment by davidebbo** [comment]
Anything interesting under LogFiles\kudu\trace (use Kudu Console to get at them)? Look for logs with matching time.

**Comment by MikaelEliasson** [comment]
Not really. It's a bunch of NPM failures before that. 

This is the end

![image](https://cloud.githubusercontent.com/assets/888296/7654430/49679718-fb1d-11e4-8179-6e8c9d0b8c23.png)

I'm not 100% sure what I'm looking for either.

**Comment by MikaelEliasson** [comment]
As I said I'm pretty sure we had those NPM failures when it worked too. It would be nice to solve those I guess though.

**Comment by davidebbo** [comment]
Can you try restarting the site in the portal. Then after waiting a bit, go to the deployments tab, where presumably you'll see a failure at the top. Click it, and then click the redeploy button. Does it fail again in the same way?

Also, can you share your site name, either directly or [indirectly](https://github.com/projectkudu/kudu/wiki/Reporting-your-site-name-without-posting-it-publicly)? This will help us investigate.

**Comment by MikaelEliasson** [comment]
Yeah, got the same error. The site is salary2.azurewebsites.net.

When looking around in kudu console I saw that the trace level is 1. I will try running the deploy with  it at 4 and see if I get more information.

**Comment by davidebbo** [comment]
Another test is to try to push the same repo to another test site. This could help isolate if it's something messed up with the salary2 site, or if it's something in the state of the repo that makes it fail on any site.

**Comment by davidebbo** [comment]
Closing as the discussion has run dry, but we can re-open if more discussion is needed.

**Comment by MikaelEliasson** [comment]
We actually managed to finally figure it out today. It had to do with some libraries that npm couldn't fetch on Azure (but worked in local dev). 

    "email-templates": "^0.1.7",
    "nodemailer": "^1.0",
    "nodemailer-ses-transport": "^1.2.0",

One or more of those three were crashing with different npm errors. I'm unsure if it was something with azure or just bad luck that corrupted our repository. Once we removed them it worked again (even before with the exception it actually deployed the new files).

**Comment by davidebbo** [comment]
That's odd. Can you repro this consistently, e.g. by trying to install those same packages manually from Kudu console? On the surface, it doesn't make sense that it would fail to download some npm packages but not others, since (presumably), they all come down from the same npm server.

**Comment by MikaelEliasson** [comment]
One thing that could fail would be the path length (know problem with node on windows) but the paths where at 180 chars or something like that so it shouldn't be that. I can see if I can duplicate it to a minimal repro if there is something with the environment.

We moved to sending our emails from a dedicated service (built in .net) so it's not a problem for us anymore but I'll tell you if I manage to set up a repro.

**Comment by davidebbo** [comment]
Thanks, if you can figure something out, let us know. But if it's too much hassle and no longer relevant to you, don't worry about it :)
