### ISSUE TITLE
Do you run test before Deploy?

### ISSUE THREAD

**Issue by ricardopolo** [projectkudu/kudu#1561]
If you have a test in your project will it run and pass before deploy?
If not is there any way to do it?

I mean, maybe if you use azure and kudu you dont need a CI server?

Thanks

**Comment by amitapl** [comment]
Kudu does not run your tests before deployment unless your build process is doing that.
You can see this blog post on adding tests to the deployment process using custom deployment script - http://blog.amitapple.com/post/51576689501/testsduringazurewebsitesdeployment/

**Comment by ricardopolo** [comment]
@amitapl thanks. So I understand is posible using a custom script.
So for Azure do you think Kudu is the same that use services like http://www.appveyor.com/ or should I still pay for appveyor?

What would I miss from a CI?
