### ISSUE TITLE
Is Kudu a CI Server?

### ISSUE THREAD

**Issue by ricardopolo** [projectkudu/kudu#1562]
Hello.

For websites how kudu compares to CIs like Appveyor http://www.appveyor.com/. Do you still needs one?

**Comment by davidebbo** [comment]
I suppose you can view it as a poor man's CI. :) As discussed in #1561, it doesn't run tests automatically, although that can be achieved. But even if you do that, you won't easily achieve CI functionality. e.g. show a historical view of runs for a given test, the way TeamCity does. I haven't used AppVeyor, but there are a ton of features in TeamCity that you would not get with Kudu.

So all in all, I'd have to say that Kudu is not a good replacement for a true CI server.
