### ISSUE TITLE
Asp.Net 5 deployment from github failing

### ISSUE THREAD

**Issue by meckd** [projectkudu/kudu#1564]
I'm getting the following errors when attempting to deploy a Asp.Net 5 application to an API App in Azure using github:

Command: "D:\home\site\deployments\tools\deploy.cmd"
Handling ASP.NET 5 Web Application deployment.
Downloading dnx-clr-win-x86.1.0.0-beta4-11566 from https://www.nuget.org/api/v2
D:\Program Files (x86)\SiteExtensions\Kudu\45.40522.1562\bin\scripts\dnvm.ps1 :
 Unable to download package: The remote server returned an error: (404) Not Fou
nd.
Failed exitCode=1, command=PowerShell -NoProfile -NoLogo -ExecutionPolicy unrestricted -Command "[System.Threading.Thread]::CurrentThread.CurrentCulture = ''; [System.Threading.Thread]::CurrentThread.CurrentUICulture = '';$CmdPathFile='"D:\local\UserProfile\.dnx\temp-set-envvars.cmd"';& 'D:\Program Files (x86)\SiteExtensions\Kudu\45.40522.1562\bin\scripts\dnvm.ps1' " install 1.0.0-beta4-11566 -arch x86 -r CLR
At line:1 char:188
An error has occurred during web site deployment.
+ [System.Threading.Thread]::CurrentThread.CurrentCulture = ''; [System.Threadi
ng. ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorExcep 
   tion
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorExceptio 
   n,dnvm.ps1


However, the application deploys correctly if I use the "Publish" function from within Visual Studio.

**Comment by davidfowl** [comment]
@meckd do you have a global.json with an sdk version in it?

**Comment by meckd** [comment]
Hi David. Yes, this is the global.json file:
{
    "projects": [ "src", "test" ],
    "sdk": {
        "version": "1.0.0-beta4-11566"
    }
}

**Comment by davidebbo** [comment]
@meckd do you have a repro? Please see [this page](https://github.com/projectkudu/kudu/wiki/Using-a-git-repo-to-report-an-issue).

Here is a sample Beta 4 app that works: https://github.com/KuduApps/AspNet5With2ProjectsAndSlnFile. Maybe worth comparing with yours.

**Comment by meckd** [comment]
Hi David. Thanks for your reply.

I wanted to attempt to start over with deploying a project to azure, so I made this repository:
https://github.com/meckd/aspNet5DeploymentTest
It is a project made from the "Web API" ASP.NET 5 Preview Template in Visual Studio 2015. It is unmodified from the original template. I was able to run it on my local machine without problems.

I also made a brand new API App in Windows Azure and set up the deployment to connect to the repository. 

The initial commit of the repository was just the .gitignore file and the README.md file (created by the Github extension in Visual Studio). As expected, when I connected the new API App to the repository, the deployment was successful, because there were only the two text files in the repository.

I then pushed the second commit (containing the Web API project) to the repository. The API App  detected the change and began the deployment process. However, the deployment failed just as it did before, with the same message as I pasted in the original post.

I took a look at the solution you linked to. I'm wondering if perhaps my installation is missing something because I was unable to get it to work "out of the box". I had to do either of the following to get it build:
1) Remove "dnxcore50" from the frameworks of "AspNet5With2ProjectsAndSlnFile/project.json"
or
2) To the "ClassLibrary/project.json" file:
    Add "dnxcore50" to the frameworks section and
    Add "Microsoft.AspNet.Server.IIS": "1.0.0-beta4" to the dependencies section.

Once I did this, I was able to run the project in IIS Express and see the "Welcome from ClassLibrary" message.

The original ClassLibrary project appeared to be incompatible with dnxcore50. As I said, maybe my installation is missing something.

**Comment by davidebbo** [comment]
I investigated and I think you likely have outdated VS tooling. When I created a new ASP 5 Web API project from VS 2015, I ended up with a global.json that has:

```
{
    "projects": [ "src", "test" ],
    "sdk": {
        "version": "1.0.0-beta4"
    }
}
```

While yours has `"version": "1.0.0-beta4-11566"`. And that's the root of the problem. If I change your test repo to be just beta4 without the 11566, it works fine in Azure.

**Comment by meckd** [comment]
Works perfectly. Thank you very much for your help, David.
