### ISSUE TITLE
WebJobs: Graceful Shutdown for Triggered WebJobs

### ISSUE THREAD

**Issue by ohadschn** [projectkudu/kudu#1565]
Currently graceful shutdown is only supported by continuous WebJobs, but it could be useful for triggered WebJobs as well. This, coupled with https://github.com/projectkudu/kudu/issues/1113, will enable the scenario of long-running triggered WebJobs (for example, a triggered WebJob that runs for 3 hours every month would typically be classified as triggered, yet is not currently supported).

**Comment by YoungjaeKim** [comment]
👍 for this issue. 
I run WebJobs more than 4 hours every day and it's not that short as @amitapl assumed in 2 years ago.  
http://blog.amitapple.com/post/2014/05/webjobs-graceful-shutdown/#comment-1746234976

WebJobs are working pretty stable now for long tasks, so it would be good to provide same feature as continuous one has.

**Comment by jvano** [comment]
Hi

Kudu will continue to run in Azure App Service. However, this repo will no longer be maintained.
If the problem persists and is related to running on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
