### ISSUE TITLE
Update error message regarding low CPU activity to mention WEBJOBS_IDLE_TIMEOUT instead of SCM_COMMAND_IDLE_TIMEOUT 

### ISSUE THREAD

**Issue by miparnisari** [projectkudu/kudu#1566]
We have a **triggered webjob** (disk intensive) set up in one website. The job sometimes failed due to a "timeout" error:

`Command ... aborted due to no output and CPU activity for 121 seconds.  You may increase SCM_COMMAND_IDLE_TIMEOUT setting to solve the issue.`

We increased the value of `SCM_COMMAND_IDLE_TIMEOUT` from 60 to 9999. 

Did we set the correct parameter, or did we have to set WEBJOBS_IDLE_TIMEOUT?

**Comment by amitapl** [comment]
`WEBJOBS_IDLE_TIMEOUT` is the correct one to update, we'll need to fix the error message.

But updating `SCM_COMMAND_IDLE_TIMEOUT` shouldn't have caused any issues, can you share what random errors you see?

**Comment by miparnisari** [comment]
Oh, never mind, the error was totally unrelated :)

**Comment by HansOlavS** [comment]
I've created a PR with a fix for this in #1640.
