### ISSUE TITLE
ASP.NET MVC view not updated if only .cshtml changed

### ISSUE THREAD

**Issue by ShamsulAmry** [projectkudu/kudu#1567]
This happened twice. 
The scenario: only a .cshtml file changed in the MVC project. 
The expected result: for the generated HTML to be updated.
The actual result: the old HTML kept showing, even tested on different devices.
The workaround: I have to deploy directly from Visual Studio for the HTML to be updated.

But I can confirm that the deployment actually happened based on the app version number than I can query through a URL. Just that the HTML view itself not being updated.

For a real example of the commit, see https://github.com/ShamsulAmry/Malaysia-GST-Checker/commit/d6ba4894d2f3113efa2a2981159f4c38424edaad

**Comment by davidebbo** [comment]
First step is to determine whether this is a deployment or a runtime issue, as described in [this document](https://github.com/projectkudu/kudu/wiki/Deployment-vs-runtime-issues). Once we know which it is, we can look into the next investigation step.

**Comment by ShamsulAmry** [comment]
@davidebbo, thanks for the guide. Based on the [deployment vs runtime issues] (https://github.com/projectkudu/kudu/wiki/Deployment-vs-runtime-issues) article, I went into Kudu Console, clicked edit on the .cshtml file and confirmed that it is updated correctly.

However viewing the page through the browser still showed the old version. Tried restarting the web app in Azure Portal, no luck. It seems as though just updating the view somehow does not "compile" the changed view.

After looking around the file timestamps, I figured that the view didn't get precompiled, that's why it kept showing the old version of the view. Googling around found your blog article from way back 2011, a StackOverflow answer, and finally https://twitter.com/davidebbo/status/513429167145484288, @darrenkopp's feature request https://github.com/projectkudu/kudu/issues/1341 which was already closed.

Could you point me to the right direction on how I can have this precompilation function working?

**Comment by davidebbo** [comment]
So does your site in fact have pre-compilation enabled? I wonder if the issue you see relates to you having deployed from VS, and then from git. Normally, I'd expect precompilation to either never work (and this issue would not happen), or to fully work (and it wouldn't happen either).

Ideally, if you can share a repro (as described [here](https://github.com/projectkudu/kudu/wiki/Using-a-git-repo-to-report-an-issue)), with a sequence of steps the result in what you are seeing on a fresh site, that would make it easier for us to investigate.

Also, can you share your site name, either directly or [indirectly](https://github.com/projectkudu/kudu/wiki/Reporting-your-site-name-without-posting-it-publicly)? This might help as well.

**Comment by ShamsulAmry** [comment]
Your guess was right, I did actually deploy from VS first, and then later setup git deployment. Tested on a new Azure web with fresh deployment straight from git solved the issue I was facing, thanks.

One final question, any recommendation on having the project precompiled upon deployment, or would it make no noticable performance improvement whether it's precompiled or not for Azure web? Does your blog post [Precompile your MVC Razor views using RazorGenerator] (http://blog.davidebbo.com/2011/06/precompile-your-mvc-views-using.html) back in 2011 still apply today?

**Comment by davidebbo** [comment]
Precompilation can mean multiple things. Are you using the Precompile option in the VS publish dialog (and if so in what mode, updatable or not), or are you using RazorGenerator?

**Comment by ShamsulAmry** [comment]
Before using git deployment, I used VS publish dialog, precompile during publishing, not updatable and do not merge. Never used RazorGenerator before. 

Any possibility to just easily put in some switches to SCM_BUILD_ARGS in .deployment file to have the precompilation working? Googled and seemed like it won't be that easy.

**Comment by davidebbo** [comment]
Precompilation uses a different tool called aspnet_compiler ([doc](https://msdn.microsoft.com/en-us/library/vstudio/ms229863(v=vs.100).aspx)). But if your goal is simply to avoid the cold start compilation of the views, than RazorGenerator might be a better option, and will work in Azure Web Apps the same way as it does locally.

**Comment by davidebbo** [comment]
Closing as RazorGenerator should cover this scenario.
