### ISSUE TITLE
How would I leverage the new VSO payload for Azure deployments?

### ISSUE THREAD

**Issue by apskim** [projectkudu/kudu#1568]
I have a couple of quick questions. I saw that #1556 has been merged into master, which means that Kudu now theoretically supports deployments from VSO Git repositories natively.

1. Has this version been deployed on the Azure Portal? Can I use Kudu's CI with VSO Git repositories now?
2. [Probably a wrong forum] Is there a way to use Kudu commands in Build.vNext? For instance, can I write an Azure PowerShell deployment script that simply calls KuduSync?

**Comment by suwatch** [comment]
The feature depends on the latest VSO payload which will be live in June.  So, it can't use it just yet.

For writing powershell as deployment script, we so support it.  Please look at this [sample](https://github.com/KuduApps/CustomPowershell).

**Comment by apskim** [comment]
Thanks @suwatch. Since it's not live yet, Kudu is not used for VSO deployments at all, so I guess its deployment scripts are not going to be of any use for me yet.

**Comment by davidebbo** [comment]
Closing this one. Once the change is live, we can discuss follow up issues in any.
