### ISSUE TITLE
npm login (after sending credentials)

### ISSUE THREAD

**Issue by footmarks-skylar** [projectkudu/kudu#1570]
Hi guys,

Can you take a look at the cmd console on a azure website running default version of node.js >=0.12.0. 

I'm taking advantage of the new private npm service offered by npmjs.org. Using the latest npm-cli supporting login, I login using my credentials. Upon submitting the command, the console waits. Upon reloading the page, access to private npms works (because the login is successful). I'm sure it's a trivial fix on your side, just receive acknowledgement from the npm login command.

Thanks

**Comment by davidebbo** [comment]
I'm not quite following. Is this something you're doing in a git custom deployment script? Can give give more complete/precise steps to describe exactly what you are doing?

**Comment by footmarks-skylar** [comment]
Sure, I'd be happy to show you. It's actually quite simple to reproduce.

Create a new Azure Web app. Within the site's configure settings, add within the application settings WEBSITE_NODE_DEFAULT_VERSION: 0.12.3

Restart the website and within your browser go to the Kudo manager debug console for your new site: https://<website-name>.scm.azurewebsites.net/DebugConsole

Once you are here - within the command console type npm -v and verify npm is  version 2 or later. If so, type npm login

You will need to register for an account on npmjs.org to complete the following step. Upon entering your credentials, console remains idle. Test the same command on your local machine and cross-check the behavior. It will be obvious then.

**Comment by davidebbo** [comment]
Oh I see, you're doing this interactively in Kudu console. The problem is that Kudu console simulates a console, but is not a true console like you'd get with ssh. It works well for commands that do simple stdin/stdout, but for commands that deal with input in fancier way, it doesn't always work.

If there is any way you can pass the params directly on the npm command line, or maybe set environment variables for them before running the command, that might provide a workaround.

**Comment by footmarks-skylar** [comment]
Yeah it's a very minor issue and only wanted to surface it.

**Comment by footmarks-skylar** [comment]
Found a simple way of solving this. Just include a .npmrc within the project root directory. Details on storing credentials within this file or obtaining this file from your local system can be found [here](https://docs.npmjs.com/files/npmrc).
