### ISSUE TITLE
Schedule grace period should be configurable

### ISSUE THREAD

**Issue by amitapl** [projectkudu/kudu#1580]
https://github.com/projectkudu/kudu/blob/201e2298280b4d2b2f329fa53980f6e096b0ac45/Kudu.Core/Jobs/Schedule.cs#L49

**Comment by jvano** [comment]
Hi

Kudu will continue to run in Azure App Service. However, this repo will no longer be maintained.
If the problem persists and is related to running on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
