### ISSUE TITLE
TRX logger for vstest.console not present

### ISSUE THREAD

**Issue by lukemcgregor** [projectkudu/kudu#1583]
I thought this was included by default with VS. The other two default loggers (console and TFS) are both available.

There is no way to install the logger either as it requires write access to program files.

Can this be installed by default?

The directory containing these is:

> D:\Program Files (x86)\Microsoft Visual Studio 11.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow

**Comment by davidebbo** [comment]
If you look under `D:\Program Files (x86)\Microsoft Visual Studio 11.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow\Extensions` (e.g. via Kudu console), we do have Microsoft.VisualStudio.TestPlatform.Extensions.TrxLogger.dll in there. Is something else missing?

**Comment by lukemcgregor** [comment]
Interesting, vstest isnt picking it up, 

>D:\Program Files (x86)\Microsoft Visual Studio 11.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow>vstest.console.exe /listloggers
>Microsoft (R) Test Execution Command Line Tool Version 11.0.60315.1
Copyright (c) Microsoft Corporation.  All rights reserved.

>Warning: The Test Logger Add-Ins installed through a VSIX installation are ignored. Use the /UseVsixExtensions parameter to include them, if your installation supports vsix extensions. Example: vstest.console.exe /ListLoggers /UseVsixExtensions:true

>The following Test Logger Add-Ins are available:
    Microsoft.VisualStudio.TestPlatform.Extensions.ConsoleLogger
        Uri: logger://Microsoft/TestPlatform/ConsoleLogger/v1
        FriendlyName: Console
    Microsoft.VisualStudio.TestPlatform.Extensions.TfsLogger.TfsLogger
        Uri: logger://Microsoft/TestPlatform/TfsLogger/v1
        FriendlyName: TfsPublisher

>D:\Program Files (x86)\Microsoft Visual Studio 11.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow>

**Comment by clisc** [comment]
I know this is old and dead, but I'm hitting this issue on a very important build project.  Any fix or workaround for this?

**Comment by davidebbo** [comment]
Seems we never got a [repro](https://github.com/projectkudu/kudu/wiki/Using-a-git-repo-to-report-an-issue) on this one.

**Comment by jvano** [comment]
Hi

Kudu will continue to run in Azure App Service. However, this repo will no longer be maintained.
If the problem persists and is related to running on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
