### ISSUE TITLE
Add the ability to run scripts on scale

### ISSUE THREAD

**Issue by atrauzzi** [projectkudu/kudu#1585]
Right now the `.deployment` file supports running a script on build.  But there are times where I would like to run separate actions when new nodes are created.

On top of `command`, maybe it might be nice to have a `scale` as well?

**Comment by davidebbo** [comment]
Kudu deals with **deployment**, but not runtime changes like scaling. [forum](https://social.msdn.microsoft.com/Forums/azure/en-US/home?forum=windowsazurewebsitespreview) is the better place to discuss this, though as it stands, the answer is that I don't think this is supported.

**Comment by atrauzzi** [comment]
Gotcha, thanks! :)
