### ISSUE TITLE
Allow post-deploy commands to be run without overriding build

### ISSUE THREAD

**Issue by atrauzzi** [projectkudu/kudu#1586]
It looks like in order to run commands post-deploy, I have to override the entire deploy flow using the `deploy.sh` generated for me.

It would be nice if I could just specify a list of commands to run **after** the deploy is completed, without having to be aware of kudu's internals by overriding them.

**Comment by regisbsb** [comment]
Please refer to https://github.com/projectkudu/kudu/wiki/Post-Deployment-Action-Hooks

**Comment by atrauzzi** [comment]
Are these triggered on Azure even for FTP-uploads?

**Comment by davidebbo** [comment]
See [this post](https://social.msdn.microsoft.com/Forums/azure/en-US/c29349b1-d941-4758-a781-71b70428f52d/running-postdeploy-and-postscale-scripts-on-azure?forum=windowsazurewebsitespreview) which deals with same topic.

**Comment by atrauzzi** [comment]
By me :+1:

**Comment by davidebbo** [comment]
lol!

When possible try to cross reference the various places that deal with the same issue to help reduce duplication of investigations.

**Comment by atrauzzi** [comment]
Definitely.
