### ISSUE TITLE
Unable to Run Azure Scripts in a WebJob

### ISSUE THREAD

**Issue by ilivewithian** [projectkudu/kudu#1589]
I have a few management jobs I'd like to run as an azure powershell script, however I am unable to run scriptlets such as `Remove-AzureSqlDatabase. Am I missing something, or is managing azure not an option from an azure website?

The message I receive is 

    Remove-AzureSqlDatabase : The term 'Remove-AzureSqlDatabase' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

**Comment by davidebbo** [comment]
This is not a Kudu specific thing, but a more general Azure Web App environment limitation. Please vote up [this item](http://feedback.azure.com/forums/169385-web-apps-formerly-websites/suggestions/7155775-add-azure-commandlets) relating to adding support for it.
