### ISSUE TITLE
Install Nuget Gallery in Azure web app using External Repository option does not work

### ISSUE THREAD

**Issue by RonakThakkar** [projectkudu/kudu#1595]
Hi,

I tried to install Nuget Gallery in Azure web app using following steps;

1. Create a new Azure web app.
2. Open Azure web app, click on "Setup continuous deployment"
3. Choose source as "External Repository"
4. Repository URL = https://github.com/NuGet/NuGetGallery.git
5. Repository branch: master
6. Repository Type: Git
7. Click OK.
8. After some time received following error.

Command: build\DeployFrontend.cmd
Handling .NET Web Application deployment.
D:\home\site\repository\src\NuGetGallery\NuGetGallery.csproj(1513,5): error : This project references NuGet package(s) that are missing on this computer. Enable NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is ..\..\packages\Microsoft.Bcl.Build.1.0.21\build\Microsoft.Bcl.Build.targets.
An error has occurred during web site deployment.
Handling .NET Web Application deployment.
D:\home\site\repository\src\NuGetGallery\NuGetGallery.csproj(1513,5): error : This project references NuGet package(s) that are missing on this computer. Enable NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is ..\..\packages\Microsoft.Bcl.Build.1.0.21\build\Microsoft.Bcl.Build.targets.
An error has occurred during web site deployment.
C:\Program Files (x86)\SiteExtensions\Kudu\45.40617.1623\bin\scripts\starter.cmd build\DeployFrontend.cmdv

**Comment by davidebbo** [comment]
Unclear if it's a Kudu issue, Are you able to build it locally? See [this page](https://github.com/projectkudu/kudu/wiki/Make-sure-site-correctly-deploys-locally).

**Comment by davidebbo** [comment]
I see the project has a Kudu custom deployment file: https://github.com/NuGet/NuGetGallery/blob/master/build/DeployFrontend.cmd. My guess is that it was authored ages ago, and is now broken. The root issue is that the NuGet team just doesn't appear to be officially supporting this scenario anymore. It may be possible with enough changes, but it's not going to 'just work' out of the box the way it used to. Maybe NuGet folks will be able to help.
