### ISSUE TITLE
Kudu is incorrectly detecting my PHP application as a node.js app

### ISSUE THREAD

**Issue by atrauzzi** [projectkudu/kudu#1596]
Seems like having a `package.json` at the root of your project convinces kudu that you are deploying node.  This is not quite as reliable as once thought as many frameworks will include all kinds of different packaging tool formats from various languages.

At the very least, there should be a way to explicitly override the language kudu feels the app should run as.

**Comment by davidebbo** [comment]
It's hard to have a heuristic that works in all cases. While it's conceivable to make it smarter, there is already a mechanism to override it using `SCM_SCRIPT_GENERATOR_ARGS`. See [here](https://github.com/projectkudu/kudu/wiki/Configurable-settings#taking-over-the-script-generator-command-line) for details.

**Comment by atrauzzi** [comment]
It might be possible to set up a hierarchy, especially given that node is somewhat subordinate to the other tools.

At the very least we can prevent node from just taking every project type over.  If there's a `composer.json` and a `package.json`, it's most likely a PHP project.

But yeah, I agree, explicit is best and possibly the only realistic option.

**Comment by davidebbo** [comment]
Can you confirm that the override mechanism solved it for you?

**Comment by jvano** [comment]
Hi

Kudu will continue to run in Azure App Service. However, this repo will no longer be maintained.
If the problem persists and is related to running on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
