### ISSUE TITLE
GIF animation for .ZIP drop

### ISSUE THREAD

**Issue by snobu** [projectkudu/kudu#1598]
As the .zip drag-and-drop-and-expand thing is quite magnificent to look at, let's also have an animated GIF telling the story.

Should go here https://github.com/projectkudu/kudu/wiki/Kudu-console
Under this section: Upload and expand zip file

GIF here:
![kudu_drop](https://cloud.githubusercontent.com/assets/6472374/8329527/b0a2734c-1a82-11e5-97aa-949fbde67a8f.gif)

No image attribution necessary. I'm happy to just contribute to the Kudu project.

**Comment by davidebbo** [comment]
Done, thanks for that!
