### ISSUE TITLE
Kudu is not using latest nuget version

### ISSUE THREAD

**Issue by ellern** [projectkudu/kudu#1606]
I've had some problems restoring packages in a .NET 4.5.1 web solution. Reason for the errors, kudu is running an old nuget version. The restore problems are fixed in the latest nuget 2.8.5.

I even tried running `nuget update -Self` in my deployment script , but I didn't have the permissions overwrite the existing nuget.exe.

For others having same problems, what I did was:
```
:: Restore NuGet packages
IF /I "MySolution.sln" NEQ "" (
  call :ExecuteCmd powershell -command "& { (New-Object Net.WebClient).DownloadFile('https://www.nuget.org/nuget.exe', '%DEPLOYMENT_SOURCE%/nuget.exe') }"
  call :ExecuteCmd %DEPLOYMENT_SOURCE%/nuget.exe update -Self
  call :ExecuteCmd %DEPLOYMENT_SOURCE%/nuget.exe restore "%DEPLOYMENT_SOURCE%\MySolution.sln"
  IF !ERRORLEVEL! NEQ 0 goto error
)
```

**Comment by davidebbo** [comment]
I see the problem:

```
D:\home>where nuget
D:\Windows\Microsoft.NET\Framework\v4.0.30319\nuget.exe
C:\Program Files (x86)\SiteExtensions\Kudu\46.40630.1643\bin\Scripts\NuGet.exe
```

So Kudu brings in the latest, but (i'm guessing) due to recent OS changes, there is now another one before it on the path, and it's older.

Fix should be to put the Kudu folder first in the path so it's found before the other one.

**Comment by davidebbo** [comment]
The fix in now deployed on Azure. @ellern, please verify. Thanks!

**Comment by ellern** [comment]
@davidebbo I just cleaned my package folder and did a sync and it works fine :+1:
