### ISSUE TITLE
Relative paths are wrong when accessing VFS API over ARM

### ISSUE THREAD

**Issue by davidebbo** [projectkudu/kudu#1609]
e.g. response items look like this:

```
  {
    "name": "Application",
    "size": 0,
    "mtime": "2014-10-31T10:06:49.1390818-07:00",
    "mime": "inode/directory",
    "href": "https://mysite.scm.azurewebsites.net/api/vfs/logfiles/?api-version=2014-04-01-previewApplication/",
    "path": "D:\\home\\logfiles\\Application"
  }
```

Instead, it should give ARM hrefs.

**Comment by davidebbo** [comment]
WebJobs API has that issue too.

**Comment by suwatch** [comment]
I tried using vfs via ARM (thru extension bridge) - it did not work at all.  Something to do with query string; perhaps I was using the new api-version.  Fix https://github.com/projectkudu/kudu/commit/bb5febca4c40dc8baf648b2495cf161b7862b549

**Comment by jvano** [comment]
Hi

Kudu will continue to run in Azure App Service. However, this repo will no longer be maintained.
If the problem persists and is related to running on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
