### ISSUE TITLE
Zip drop to "special zone" also supports folder tree

### ISSUE THREAD

**Issue by snobu** [projectkudu/kudu#1610]
Just adding that the special drop zone for .zip also supports full folder trees. ("and folders" in bold at the end).

https://github.com/projectkudu/kudu/wiki/Kudu-console

Upload and expand zip file
-----------------------------------
If you try to drop a zip file into the File Explorer UI (per previews section), you'll see a special Zip file drop zone appearing. If you drop it there, it will copy the content of the expanded zip file, instead of the zip file itself. It's a much more efficient way to upload a large number of small files __and folders.__

**Comment by davidebbo** [comment]
Thanks. Also added notes that it works best with Chrome. Last I checked it didn't work at all in other browsers.

**Comment by snobu** [comment]
Works in IE11, Chrome 43 (Google's versioning is out of control) and Firefox 39. This is what I had to test with but I think we're good. Don't have a Mac to test Safari, but then again, who does? :)

**Comment by davidebbo** [comment]
Ah I see, I was talking about something different. What doesn't work is dropping folders (not zips) from WIndows explorer into Kudu. I think it's some IE limitation.
