### ISSUE TITLE
git push fails in production server

### ISSUE THREAD

**Issue by joelbugarini** [projectkudu/kudu#1614]
Hello guys, I'm running kudu in a production server, just installed git, node and azure cli (Not sure if needed), but it stops at generating the deploy script. 

```
>git push deploy master
Counting objects: 9, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (4/4), done.
Writing objects: 100% (5/5), 412 bytes | 0 bytes/s, done.
Total 5 (delta 3), reused 0 (delta 0)
remote: Updating branch 'master'.
remote: Updating submodules.
remote: Preparing deployment for commit id '353ba4d0d1'.
remote: Generating deployment script.
remote: El sistema no puede encontrar la ruta especificada.
remote:
remote: Error - Changes committed to remote repository but deployment to website failed.
To http://195.0.100.8:16740/test.git
   c50e342..353ba4d  master -> master
```

El sistema no puede encontrar la ruta especificada. **(The system cannot find the path specified.)**

I think it's related but not the same issue
https://github.com/projectkudu/kudu/issues/926

PD: I can run the script that comes in the Log site in the server but kudu can't.
azure site deploymentscript -y --no-dot-deployment -r "C:\inetpub\wwwroot\kudu\apps\test\site\repository" -o "C:\inetpub\wwwroot\kudu\apps\test\site\deployments\tools" --aspWAP "C:\inetpub\wwwroot\kudu\apps\test\site\repository\soul.csproj" --no-solution

**Comment by davidebbo** [comment]
Please take a look at the Kudu trace files (`LogFiles\kudu\trace`), which may contain more details about exactly what's failing.

**Comment by davidebbo** [comment]
Closing as issue went stale. Let us know if still relevant.

**Comment by joelbugarini** [comment]
It's not relevant, the approach I used for production server was not working. Please point this issue to some documentation for the topic "Kudu in production server". Thanks!
