### ISSUE TITLE
Typo: "because This was function was programmatically called"

### ISSUE THREAD

**Issue by frankvaneykelen** [projectkudu/kudu#1617]
When I start a Method from Program.cs with code like this:

    var host = new JobHost();
    host.Call(typeof(Functions).GetMethod("GenerateProposalReports"));

The message in the Console has a typo ("This was"):

    Executing: 'Functions.GenerateProposalReports' because This was function was 
    programmatically called via the host APIs.

That should be something like this:

    Executing 'Functions.GenerateProposalReports' because this function was 
    programmatically called via the host APIs.

**Comment by ahmelsayed** [comment]
/cc @mathewc 

This should probably go into https://github.com/Azure/azure-webjobs-sdk/issues

**Comment by mathewc** [comment]
Thanks for reporting. Yes, this is an SDK issue, and I fixed this a while ago (https://github.com/Azure/azure-webjobs-sdk/commit/605f161fa1594bd61b076271287ebccb2d373f29). The fix is in the current v1.1.0 alpha.

**Comment by mathewc** [comment]
FYI: the fix was to reformat to: Executing: 'Functions.GenerateProposalReports' - Reason: 'This function was programmatically called via the host APIs.'

**Comment by arichiardi** [comment]
I have run into this as well. Azure newbie here, what does the error entails? Is there a way to get to the worker error (in my case node)?
