### ISSUE TITLE
Streams in Executable.cs are not disposed

### ISSUE THREAD

**Issue by shrimpy** [projectkudu/kudu#1619]
https://github.com/projectkudu/kudu/blob/master/Kudu.Core/Infrastructure/Executable.cs#L66

https://github.com/projectkudu/kudu/blob/master/Kudu.Core/Infrastructure/Executable.cs#L91

**Comment by davidebbo** [comment]
How did you happen to find this? Was it via code inspection, or as a result of catching some leak?

I think you're correct about it, though in practice I'm not sure there are ill effects when dealing with memory streams (since there is no file to close, ...).

**Comment by shrimpy** [comment]
right, I am worrying about could potentially cause memory leak

I found it in [pull request](https://github.com/Azure/kudu/pull/431) from @safihamid, where he reference Executable.cs as sample.

**Comment by jvano** [comment]
Hi

Kudu will continue to run in Azure App Service. However, this repo will no longer be maintained.
If the problem persists and is related to running on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
