### ISSUE TITLE
Further improvements in Ace integration

### ISSUE THREAD

**Issue by snobu** [projectkudu/kudu#1620]
The problem:
-----------------
![image](https://cloud.githubusercontent.com/assets/6472374/8747716/0a6632f6-2c9e-11e5-831c-1581d297ed82.png)

The Ace editor is trying to syntax check `Saving changes...` and `Fetching changes...` and it will show a big red `[X]` as a result. Which is confusing - _"Was was that?" "Did it save?" "There was this.. thing like..a.. nevermind"_.

The problem has been introduced by yours truly in the initial Ace-kudu integration.

Proposed fix:
----------------
How about a status bar in the new Ace editor?

### Cloudy glyphs for file save and file load ###

![image](https://cloud.githubusercontent.com/assets/6472374/8747462/fbc837a0-2c9b-11e5-8fc0-699382b8c5cf.png)

![image](https://cloud.githubusercontent.com/assets/6472374/8747485/37352f0a-2c9c-11e5-9ab3-2a52dd0dc48d.png)

### Status bar shows filename by default: ###
![image](https://cloud.githubusercontent.com/assets/6472374/8747447/cc227650-2c9b-11e5-88b7-d6c239093486.png)

### Clicking it switches to full path: ###
![image](https://cloud.githubusercontent.com/assets/6472374/8747449/dea9853e-2c9b-11e5-87a9-bef7dfd06ed0.png)

I'm totally open to new ideas on what we could do with this new status bar.
If it looks good i will go ahead with development and pull request.

**Comment by davidebbo** [comment]
I like it. Not sure it's worth doing the clickable thing to show full path. And if we don't then maybe it doesn't have to look like a clickable button (which it isn't anyway for fetching/saving). Not sure what the bootstrap convention is for status text that's clearly non-clickable.

**Comment by snobu** [comment]
Agreed.

The closest thing to a status bar styling in Bootstrap is the `bs-callout` class. Which isn't even part of Bootstrap, but can be added rather easily: http://cpratt.co/twitter-bootstrap-callout-css-styles/

__bs-callout-info (no background):__
![image](https://cloud.githubusercontent.com/assets/6472374/8775381/4a7978cc-2ef0-11e5-8571-b6858cbd1532.png)

__bs-callout-info with gray background:__
![image](https://cloud.githubusercontent.com/assets/6472374/8775390/7095103e-2ef0-11e5-936d-adbfd191c911.png)

__bs-callout-primary (no background):__
![image](https://cloud.githubusercontent.com/assets/6472374/8775456/28c66a9a-2ef1-11e5-85c5-3ac7bbe6d91e.png)


__bs-callout-primary with gray background:__
![image](https://cloud.githubusercontent.com/assets/6472374/8775448/1b559b10-2ef1-11e5-8d78-bb2513c92767.png)

__bs-callout-so-minimal-much-wow:__
![image](https://cloud.githubusercontent.com/assets/6472374/8775492/72bc98b8-2ef1-11e5-8ca1-102855d34e4b.png)

__bs-callout-so-minimal-much-wow-on-gray:__
![image](https://cloud.githubusercontent.com/assets/6472374/8775509/9ff075f2-2ef1-11e5-96a9-6b19909ddba8.png)

Any other attempt to style this bar by filling it with a solid color results in a unstoppable urge to click it. Which should not be the case. I also think it looks nicer in the same font as Save/Cancel and not monospaced.

**Comment by davidebbo** [comment]
I guess any of those would probably work, so pick your favorite one :)

**Comment by snobu** [comment]
Merged in https://github.com/projectkudu/kudu/pull/1635
