### ISSUE TITLE
Bitbucket new webhook payload support.

### ISSUE THREAD

**Issue by Rocketlife** [projectkudu/kudu#1621]
Hi guys. I'm running Kudu service on my windows server and trying to get bitbucket webhook to trigger deployment but it seems like Kudu doesn't support Bitbucket webhook payload.
Event: `repo:push`
result: `500 Internal Server Error`
url:  http://myKuduService.com/deploy?scmType=BitbucketGit

When i'm trying to trigger deployment with bitbucket sample [payload](https://confluence.atlassian.com/display/BITBUCKET/Event+Payloads#EventPayloads-Push) via Fidder i'm getting 
````
500 Internal Server Error
Unexpected character encountered while parsing value: U. Path 'actor', line 2, position 12. 
```

Fiddler request with real payload, acquired via RequestBin didn't work too,
response:
```
400 Bad Request
The json payload is unsupported.
```

But with simple payload 
`{ format: 'basic', url:' git@bitbucket.org:sample/repository.git' } ` 
all works fine.

**Comment by shrimpy** [comment]
@Rocketlife in Azure we have support for bitbucket, so kudu did support Bitbucket payload. How did you setup your webhook?

**Comment by Rocketlife** [comment]
@shrimpy Azure supports old bitbucket webhooks aka services, but not webhhoks 2.0.  Services are using x-www-form-urlencoded payload, webhooks - application/json. I added webhooks in bitbucket repository settings.

**Comment by shrimpy** [comment]
@Rocketlife i see, thanks for reporting this. seems like Bitbucket recently added [new webhook](http://blog.bitbucket.org/2015/06/24/the-new-bitbucket-webhooks/). I will let @davidebbo to priorities this issue.

**Comment by davidebbo** [comment]
@Rocketlife, if you'd like to make a go at it and send a PR, please take a look at https://github.com/projectkudu/kudu/blob/master/Kudu.Services/ServiceHookHandlers/BitbucketHandler.cs, which has all the Bitbucket logic. It could either be a separate class or making existing class handle both cases. I didn't look at the new hook format, so I'm not sure which way works best.

**Comment by suwatch** [comment]
Bitbucket mention they will deprecate the old hook within 6 months.  I have asked them some clarification in order to plan our migration story.

**Comment by shrimpy** [comment]
tried and verified, we can invoke v2 API with current access token. so i think to address this issue, we just need to create another handler similar to current [BitbucketHandler](https://github.com/projectkudu/kudu/blob/master/Kudu.Services/ServiceHookHandlers/BitbucketHandler.cs), probably call BitbucketHandlerV2 to consume new webhook payload.

**Comment by suwatch** [comment]
With BitbuckerHandlerV2, it should be enough to close this issue.   We should discuss on different thread (very Azure specific) concerning Bitbucket v2 API.

**Comment by shrimpy** [comment]
there is an issue with the new webhook notification, it doesn`t mention it is from a git or hg repo. i opened a [bug on Bitbucket](https://bitbucket.org/site/master/issues/11665/missing-scm-info-from-bitbucket-webhooks)

**Comment by shrimpy** [comment]
[bug on Bitbucket](https://bitbucket.org/site/master/issues/11665/missing-scm-info-from-bitbucket-webhooks) was fixed. Updating Kudu to consume the new properties ["is_private" and "scm" ](https://github.com/projectkudu/kudu/pull/1670)

**Comment by davidebbo** [comment]
@Rocketlife this should now work. Please verify.
