### ISSUE TITLE
[VS 2015 Build Tools] Microsoft.Build.Utilities.Core and dependency issue

### ISSUE THREAD

**Issue by punitganshani** [projectkudu/kudu#1624]
The solution that I am trying to build and deploy on Azure comprises of ASP.NET MVC 5 website developed using RC version of VS 2015 and references .NET 4.5.2 framework  

When this solution is checked-in to VSO and build is triggered to deploy to Azure Web App, it builds fine and deployment succeeds.

When this solution is checked-in to GitHub and build is triggered using Kudu, it gives following error

```
error MSB4062: The "Microsoft.CodeAnalysis.BuildTasks.Csc" task could not be loaded from the assembly
D:\home\site\repository\packages\Microsoft.Net.Compilers.1.0.0\build\..\tools\Microsoft.Build.Tasks.CodeAnalysis.dll. 
Could not load file or assembly 'Microsoft.Build.Utilities.Core, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. 
The system cannot find the file specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.
``` 

The packages.config for has Microsoft.Net.Compilers which has developmentDependency=true

```
 <package id="Microsoft.Net.Compilers" version="1.0.0" targetFramework="net452" developmentDependency="true" />
```

Considering that this solution is building correctly on VSO, I believe [VS 2015 Build Tools](http://www.microsoft.com/en-sg/download/details.aspx?id=46882) are required to successfully compile this solution using Kudu.

Also, shouldn't this package be ignored for builds triggered outside of Visual Studio?

**Comment by npnelson** [comment]
+1 VS2015 RC Webjob targeting .Net 4.5.1  Also using Microsoft.Net.Compilers 1.0.0 so that I can use C#6 features with a kudu build.  I have similar preexisting projects that still build fine with kudu (although I might not have another webjob with a direct dependency on Microsoft.Net.Compilers 1.0.0), but I can't get the new one I set up today to build.

You have my permission to check anything you need on lwf-email-webjob-master.azurewebsites.net

**Comment by davidebbo** [comment]
Could either of you please [share a repo](https://github.com/projectkudu/kudu/wiki/Using-a-git-repo-to-report-an-issue) that demonstrates the issue? Thanks!

**Comment by punitganshani** [comment]
@davidebbo You can try this repo  https://github.com/punitganshani/NuGetViz 
This repo builds fine when I use VSO builds, but fails with Kudu

**Comment by davidebbo** [comment]
Yes, I see the issue with your repo. Interestingly, I do see `Microsoft.Build.Utilities.Core` in `D:\Program Files (x86)\MSBuild\14.0\Bin` in Kudu, but something must be not quite right.

As a test, does the issue go away if you set developmentDependency to false?

**Comment by punitganshani** [comment]
I've changed as suggested `developmentDependency=false`, but it still failed.

**Comment by ahmelsayed** [comment]
you can set an appSetting for your app `MSBUILD_PATH = D:\Program Files (x86)\MSBuild\14.0\Bin\MSBuild.exe` and that should get you unblocked. Though I'm also not yet sure why the other msbuild is failing

**Comment by npnelson** [comment]
Thanks, I can confirm that the MSBUILD_PATH workaround works.

**Comment by punitganshani** [comment]
@ahmelsayed Strange, I did not have to do this to make it work for VSO :-) Plus, everyone using VS2015 will face this issue and will have to change their appSettings

Is it possible to override the `.targets` files on the build server to correctly work with the path?

**Comment by ahmelsayed** [comment]
yes we need to figure out why this is failing and make it work without requiring app settings changes. I just mentioned the app setting as a workaround to get you unblocked :)

I'll take a look at the real reason for the failure as soon as I can

**Comment by davidebbo** [comment]
I think the real fix is to install *Microsoft Build Tools 2015* onto the VM, which we are planning. That adds `Microsoft.Build.Utilities.Core` to the GAC, which I think is what makes it work.

**Comment by punitganshani** [comment]
To add- If anyone is using packages from pre-release packages of ASP.NET, they will also have to add NuGet.config in the solution directory to make ASP.NET 5.0 builds work as the package source is different from nuget.org

**Comment by ahmelsayed** [comment]
VS 2015 Build Tools should be on all machines now.

**Comment by regisbsb** [comment]
Is https://github.com/projectkudu/kudu/blob/master/Kudu.Core/Infrastructure/PathUtility.cs published? With that the workaround still needs to be present.

**Comment by davidebbo** [comment]
No, the change to use the new msbuild is not yet published.
