### ISSUE TITLE
Cannot build .net 4.6 solution

### ISSUE THREAD

**Issue by regisbsb** [projectkudu/kudu#1629]
message: "D:\Windows\Microsoft.NET\Framework\v4.0.30319\Microsoft.Common.targets(983,5): warning MSB3644: The reference assemblies for framework ".NETFramework,Version=v4.6" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend.

**Comment by davidebbo** [comment]
Relates to [this forum thread](https://social.msdn.microsoft.com/Forums/azure/en-US/262f9f05-31b6-429d-a83a-97efc5fdb82a/net-framework-46-full-support?forum=windowsazurewebsitespreview).

**Comment by regisbsb** [comment]
Set an appSetting for your app MSBUILD_PATH = D:\Program Files (x86)\MSBuild\14.0\Bin\MSBuild.exe 
#1624 @ahmelsayed

**Comment by ahmelsayed** [comment]
This should work now without requiring any app settings.

**Comment by regisbsb** [comment]
Nice

**Comment by regisbsb** [comment]
I've removed the appsettings but somehow the deploy scripts are cached. Is there a way to delete the current script and let it be regenerated? In the SCM portal there is only a way to download the script.

**Comment by ahmelsayed** [comment]
The files are cached in `D:\home\site\deployments\tools`, you can delete the files there from DebugConsole in the scm portal.

**Comment by regisbsb** [comment]
@ahmelsayed i've done that but script was still generated with 

    IF NOT DEFINED MSBUILD_PATH (
          SET MSBUILD_PATH=%WINDIR%\Microsoft.NET\Framework\v4.0.30319\msbuild.exe
    )

**Comment by regisbsb** [comment]
@ahmelsayed i've tried again now with a new website from https://github.com/regisbsb/Dev14_Net46_Mvc5
but same result, @davidebbo said this site was fine but I can see that in the last tag it's still 4.0 not 14 the msbuild.
https://github.com/projectkudu/kudu/blob/S44/Kudu.Core/Infrastructure/PathUtility.cs vs
https://github.com/projectkudu/kudu/blob/master/Kudu.Core/Infrastructure/PathUtility.cs

**Comment by regisbsb** [comment]
https://github.com/projectkudu/kudu/issues/1659
still not deployed then..

**Comment by ahmelsayed** [comment]
I guess initially I thought that just having the new MSBuild on the box, but using the one in the framework folder would be enough. Apparently that's not correct so David made 1b85989027de7cb7f6789ddbe54d1ed5d6990c6d yesterday, which should fix this, but we are running into other issues with this change, so i'll need more time to sort that out. In the mean time setting `MSBUILD_PATH` should be a workaround

**Comment by davidebbo** [comment]
This should now work by default without setting `MSBUILD_PATH`.

**Comment by regisbsb** [comment]
I can confirm it works now without the `MSBUILD_PATH`. Thank you guys so much.
