### ISSUE TITLE
Support elixir deployments

### ISSUE THREAD

**Issue by ulrikaugustsson** [projectkudu/kudu#1631]
Is there any thoughts on supporting Elixir on azure webapps?

As the phoenix framework (http://www.phoenixframework.org/) is getting traction maybe that is something you want to support.

**Comment by davidebbo** [comment]
More of a general Azure Web App thing than Kudu specific. Can you open on entry on the [feedback site](http://feedback.azure.com/forums/169385-web-sites/)? This will let others vote for it, which helps us prioritize things. Thanks!

**Comment by ulrikaugustsson** [comment]
Sorry, I will post it in the correct place. :+1:

**Comment by ulrikaugustsson** [comment]
Just for completeness.
http://feedback.azure.com/forums/169385-web-apps-formerly-websites/suggestions/8986354-support-elixir-in-azure-webapps
