### ISSUE TITLE
Update the logic for browser download popup when stop profiling or creating a dump file

### ISSUE THREAD

**Issue by safihamid** [projectkudu/kudu#1632]
There are two feature requests here:

1) When user clicks on "Stop Profiling" button, it may take few seconds or even minutes for the browser download popup to show up. During this time we want the text of the button to change to "Stopping Profiler..."

2) If "Stop Profiling" returns an error, we want to display that in a pop-up similar to what we do for "Start Profiling", currently nothing shows up unless user does F12 or uses fiddler and look at the response error.

**Comment by safihamid** [comment]
@shrimpy

**Comment by snobu** [comment]
If no one started work on this one, @badescuga and I can have a go at it.

**Comment by badescuga** [comment]
I got this!

**Comment by davidebbo** [comment]
Go for it, thanks!

**Comment by shrimpy** [comment]
Fixed in https://github.com/projectkudu/kudu/commit/8a7739ec049fa46121976d392636731ace2466c0
