### ISSUE TITLE
Content-Disposition header when clicking the download button

### ISSUE THREAD

**Issue by snobu** [projectkudu/kudu#1634]
Trying to download an .XML or .XSL can turn into a very entertaining afternoon without a `Content-Disposition` header. I'm being offered a nice prettified render of the file content or an in-browser XML-parser error if the markup is not valid, but not prompted to save any file.

![capture2](https://cloud.githubusercontent.com/assets/6472374/8860499/eea472be-318c-11e5-87a0-238609681a37.png)

![cap3](https://cloud.githubusercontent.com/assets/6472374/8860888/6863ffc8-318f-11e5-9bb2-171c5e03cf29.PNG)

![capture](https://cloud.githubusercontent.com/assets/6472374/8860480/be8ee92e-318c-11e5-9b69-b06d972c9faf.PNG)

Is this by design or can we change it to say `Content-Disposition: attachment; filename=file.xml;`?

**Comment by davidebbo** [comment]
Yes, I suppose it could have that. The workaround is to right click the download button and choose Save Link As (at least in Chrome that works).

**Comment by snobu** [comment]
Because this is under `/api/vfs/` i fear we might break people who already use the API for widely miscellaneous purposes (I'm thinking Site extensions or who knows what else).
My proposal would be for an optional parameter (like "?download") that would trigger this additional header to be included in the reply.

Something like:
`GET https://sitename.scm.azurewebsites.net/api/vfs/LogFiles/eventlog.xml?download`

This way we don't break anything that's already in place while giving the UI a usability improvement.

**Comment by snobu** [comment]
I strongly believe the `Content-Disposition` header will have no effect whatsoever on command line tools/programmatic calls (tried PowerShell and curl - basically anything with libcurl is included - and they just ignore it). The upside is that it's now correctly convincing browsers to download the file rather than desperately try to render the content inline.



Without Content-Disposition:

``` powershell
PS> $req = iwr "https://kududev.scm.azurewebsites.net/api/vfs/site/wwwroot/hostingstart.html" `
               -Headers @{Authorization = "Basic xxxxxxxxxxxxxxx="; <few_more_req_headers>}

PS> $req.Headers

Key                             Value
---                             -----
[..]
Content-Encoding                 gzip
Content-Type                     text/html
[..]


PS> $req.ParsedHtml | select Title

title
-----
Microsoft Azure Web App - Welcome
```

```bash
$ curl -s -k "https://kududev.scm.azurewebsites.net/api/vfs/site/wwwroot/hostingstart.html" -H "Authorization: Basic xxxxxxxxxxxxxxxxxxxxxxxx=" -H <FEW_MORE_HEADERS_HERE> | grep Welcome
<!DOCTYPE html><html><head>    <title>Microsoft Azure Web App - Welcome</title>    
```

with Content-Disposition header:

``` powershell
PS> $req.Headers

Key                             Value
---                             -----
[..]
Content-Encoding                 gzip
Content-Type                     text/html
Content-Disposition              attachment
[..]

PS> $req.ParsedHtml | select Title

title
-----
Microsoft Azure Web App - Welcome
```

```bash
$ curl -s -k "https://kududev.scm.azurewebsites.net/api/vfs/site/wwwroot/hostingstart.html" -H "Authorization: Basic c25vYnVkZXY6QnJvd3NlbXlnb3BoZXI=" -H <FEW_MORE_HEADERS_HERE> | grep --color -i Welcom
<!DOCTYPE html><html><head>    <title>Microsoft Azure Web App - Welcome</title>
```



I added one line of code to these files:
https://github.com/projectkudu/kudu/blob/master/Kudu.Services/Editor/VfsController.cs#L93
```
Kudu.Services\Editor\VfsController.cs(93):
    successFileResponse.Content.Headers.Add("Content-Disposition", "attachment");
```

https://github.com/projectkudu/kudu/blob/master/Kudu.Services/Infrastructure/VfsControllerBase.cs#L54
```
Kudu.Services\Infrastructure\VfsControllerBase.cs(54):
     response.Content.Headers.Add("Content-Disposition", "attachment");
```

I'm not sure i need to add the header to `successFileResponse` as well. Do i?


Here's the Too Long Didn't Read version :)
![image](https://cloud.githubusercontent.com/assets/6472374/9828014/e366c6dc-58f0-11e5-8d17-ab06bb204eea.png)

Once i'm clear on which of the methods need to add the header and you guys are ok with the change i can send a PR.

**Comment by davidebbo** [comment]
@HenrikFrystykNielsen wrote that code a while back, in case he has a chance to take a quick look at the proposed change. I'd say add it to the one that seems to make it work. It seems strange that there would be two places to add the header since (I think) there is only one file download scenario at stake.

**Comment by davidebbo** [comment]
@snobu I think you can go ahead and send PR for this one. I agree that setting `Content-Disposition` is unlikely to hurt anything.

**Comment by davidebbo** [comment]
One downside someone just complained about with this change is that it's now a lot harder to view Failed Request Logs. Previously, you'd just click the XML, and it would display it in a new tab, automatically fetching the companion xsl. Now, it force downloads it no matter what you try.

I guess ideally we'd have both a download and a view button.

**Comment by snobu** [comment]
Yup i complained about that too two days ago then I remembered it was all me :)

Two options, hardcode a rule to not send the header for Frebs or put an additional button next to the regular download button that we have now. One for "open" and one for download.

**Comment by davidebbo** [comment]
The irony is that looking at your screenshot above, you were also dealing with an XML/XSL situation, and yet you wanted it to download and not navigate! :)

If we have two buttons, we need to talk about what it actually means at the API level. e.g. it may need to be some query string flag passed to the vfs API to drive this behavior.

**Comment by andybatescc** [comment]
Browsing the Failed request tracing is one of the most common things I do in Kudu, and has really scuppered my usage and diagnostic investigation. A extra button may well be the way forward

**Comment by davidebbo** [comment]
Maybe we should revert this change until we get a more complete solution, as here the change seems to hurt more than it helps. After all, before this change, there was always the option of "Right click / Save as" in order to avoid the navigation behavior. But with the header, there seems to be no way of causing navigation instead of download.

**Comment by andybatescc** [comment]
The following header has reversed things for now for me on chrome:
https://chrome.google.com/webstore/search/undisposition?hl=en

**Comment by snobu** [comment]
Agreed. Let's revert. I'll make the pull request in 1h, or @davidebbo just yank it out now if you can.

**Comment by davidebbo** [comment]
Ok, it's reverted. We can keep this issue open, but maybe addressing this is not highest priority at this point :)

**Comment by davidebbo** [comment]
I just noticed it also breaks [this workflow](https://github.com/projectkudu/kudu/wiki/Troubleshooting-Node-errors). Specifically this step:

> Click the down arrow next to index.html, and it should open a new tab with a page showing a list of errors.

Anyway, we'll try to redeploy Kudu soon.

**Comment by snobu** [comment]
Lesson learned. No such thing as harmless HTTP headers. 

-----Original Message-----

**Comment by snobu** [comment]
Closing for now.
