### ISSUE TITLE
Extending the logstream

### ISSUE THREAD

**Issue by sitereactor** [projectkudu/kudu#1638]
I guess this is kind of a feature request, as it doesn't seem possible OOTB. But would it be possible to extend the [logstream](https://github.com/projectkudu/kudu/wiki/Diagnostic-Log-Stream) to look at files outside the /LogFiles folder?
If you use [Umbraco](https://github.com/umbraco/Umbraco-CMS) on Azure WebApps it would be nice if the UmbracoTraceLogs.txt file (which resides in /wwwroot/App_Data/Logs) could be exposed to the /logstream just like /logstream/kudu/deployment, /logstream/application, etc.

The LogManager is restricted to that one LogFiles folder https://github.com/projectkudu/kudu/blob/master/Kudu.Services/Diagnostics/LogStreamManager.cs#L52 which there might be a very good reason for, but would it be possible to add some kind of extension points to allow other files to be "monitored" by the logstream?

**Comment by davidebbo** [comment]
Indeed, it's not something that's supported today. Would you expect the same `/api/logstream` request to stream a mix of content from the LogFiles folder and other folders? Or separate `/api/logstream` calls that each ask for a different thing?

I guess the question is whether this configuration should exist on the URL or should be something pre-configured via some kind of site setting.

**Comment by sitereactor** [comment]
I'd prefer it to be application specific, so you could do something like `/api/logstream/umbraco` - if other CMS applications have their logs written to the filesystem it would make sense if you could do something like `/api/logstream/orchard` or `/api/logstream/drupal` and it would know the path for that application or you could configure your application in an easy way (thinking you could specify endpoint and filesystem path - so for Umbraco it would be `/api/logstream/umbraco` and path `/site/wwwroot/App_Data/logs/UmbracoTraceLogs.txt`). 
I think that would tie in nicely to the rest of the diagnostics since the application specific log(s) might have different and valuable information that you don't get through IIS logs, deployment logs, trace logs, etc.

Makes sense?

**Comment by warrenbuckley** [comment]
Hi @davidebbo I brought this up with @sitereactor as I was wanting to build a little NodeJS CLI utility for their Umbraco platform/service. With this it would allow more context specific logs to the Umbraco application.

And like @sitereactor approach suggests it would be a nice solution so any folder could be added to the fileWatcher that contains log files .txt etc & any other services using Kudu with their application could see more specific & contextual logs/errors

**Comment by davidebbo** [comment]
Note that `/api/logstream/foo` already has a meaning: it means listen to changes only in the `logfiles\foo` folder, instead of the default `logfiles` (so it's more scoped).

I'm thinking it might make more sense to say that the api is still just `api/logstream`, but that this could result in additional folders being listened to if some setting was configured in the app. This way, all existing tools that do streaming would just work without having to learn new URLs.

**Comment by sitereactor** [comment]
Okay, so with the logstream being scoped to folders it would not be a good idea to have an endpoint that doesn't actually point to the folder that would otherwise be expected. That's fair enough.
So if I understand you correct you'd prefer if the logstream (on `/api/logstream') would be configured to monitor other logfiles, which could include something like the UmbracoTraceLogs.txt file, correct?

I'd be happy to work on this with a little guidance if you think it makes sense.

**Comment by davidebbo** [comment]
Yes, that sounds right.

@suwatch wrote all the existing log streaming logic, and is gone till Monday. Let's wait till he gets back to come up with a more complete design.

**Comment by suwatch** [comment]
@sitereactor  if you look at [this line](https://github.com/projectkudu/kudu/blob/master/Kudu.Services.Web/App_Start/NinjectServices.cs#L198), the log stream path is hardcoded to a specific folder (in Azure, `d:\home\logfiles`).   We could introduce a setting named `SCM_LOGSTREAM_PATH` (note: `SCM_` prefix is just [our convention](https://github.com/projectkudu/kudu/blob/master/Kudu.Contracts/Settings/SettingsKeys.cs)).  This allows users to point to any folder they want.   For instance, in umbraco case, `SCM_LOGSTREAM_PATH=site/wwwroot/App_Data/logs`.   

Will this address the issue?

**Comment by sitereactor** [comment]
@suwatch if this replaces the original path of `D:\home\logfiles` with what is specified in `SCM_LOGSTREAM_PATH` (as per your suggestion) wouldn't that mean that using `/logstream/deployment` wouldn't work, because the base folder is now different? I'm not entirely sure how the other endpoints are looked up, so please correct me if I'm wrong.

**Comment by suwatch** [comment]
@sitereactor  The idea I had earlier was for users to override the root path for `/api/logstream`.   For instance, umbraco application where logfile is at `/site/wwwroot/App_Data/logs/UmbracoTraceLogs.txt`, one could set `SCM_LOGSTREAM_PATH` to `d:\home\site\wwwroot\App_Data\logs`.   When connecting to `/api/logstream`, you would get any text files under that path automatically.  One could achieve the same by settings `SCM_LOGSTREAM_PATH` to `d:\home` and connect to `/api/logstream/site/wwwroot/App_Data/logs`.   The drawback for this design is it would break any existing tool (such one in portal) if the user were to customize the `SCM_LOGSTREAM_PATH`.

Another design is similar to what you proposed earlier in the thread.   Let say if one where to connect to `/api/logstream/foo`, we first check if `SCM_LOGSTREAM_FOO` is defined.   If not, we will interpret it as `d:\home\logFiles\foo`.   For umbraco, one would set `SCM_LOGSTREAM_UMBRACO` to `d:\home\site\wwwroot\App_Data\logs`.  When connecting to `/api/logstream/umbraco`, one will get the log from `d:\home\site\wwwroot\App_Data\logs` automatically.   I think this might be better.    

Thought?

**Comment by sitereactor** [comment]
@suwatch I like the second approach. If I understand you correct then going to `/api/logstream/umbraco` would initially look for a folder called Umbraco within `d:\home\logfiles\(umbraco)`, but if I define a variable `SCM_LOGSTREAM_UMBRACO` then it would pick that path to watch. So the variable definition would be `SCM_LOGSTREAM_{ENDPOINT} `.

If @davidebbo is also cool with that I'll start working on it.

**Comment by davidebbo** [comment]
It all depends what the goal is. With this approach, it will only stream those Umbraco logs, and not a mix of the Umbraco logs alongside all the regular logs.

Unless you extend the semantic to say that if you set `SCM_LOGSTREAM_UMBRACO=d:\home\site\wwwroot\App_Data\logs` and go to the **root** streaming endpoint (`/api/logstream`), it causes it to include `d:\home\site\wwwroot\App_Data\logs`, as if `d:\home\logFiles\umbraco` was some kind of symbolic link to `d:\home\site\wwwroot\App_Data\logs`. But that may be harder to code up.

**Comment by suwatch** [comment]
I would keep thing simple and, if needed, improve based on feedback.  Do mix log might be too complicated and client side tooling will find it hard to distinguish and digest.

**Comment by sitereactor** [comment]
I'd be happy to have it on its own endpoint, so that `/api/logstream/umbraco` shows the output of the file I define in `SCM_LOGSTREAM_UMBRACO`. It might be too confusing and not transparent if its mixed with other kudu/application logs on `/api/logstream`.

**Comment by davidebbo** [comment]
Ok, fair enough, let's keep it simple and targeted to hitting that endpoint directly. So Suwat's proposed second approach seems fine.

**Comment by sitereactor** [comment]
:+1:

**Comment by suwatch** [comment]
@sitereactor  I assume you would like to contribute to this.  Let us know if you need any assistant.   I would start create a routine to find _logPath from firstpath ([this line](https://github.com/projectkudu/kudu/blob/master/Kudu.Services/Diagnostics/LogStreamManager.cs#L283)).   Write a unit tests on this and finally e2e test.

**Comment by sitereactor** [comment]
Yes, I'll submit a pull request soon'ish :)

**Comment by suwatch** [comment]
@sitereactor  Just to touch base on this.  Any update?

**Comment by sitereactor** [comment]
@suwatch no, sorry. I haven't had any free cycles to work on this yet. Hoping to have some time over the next two weeks though.

**Comment by sitereactor** [comment]
@suwatch I've done the initial implementation of this, and was looking at the functional test for the `LogStreamManager`, but none of the functional tests work for me (running in VS2013). Does it require something specific to be in place on my local machine?

**Comment by sitereactor** [comment]
Ah, read the wiki :smile: 
Guess I need to go through this https://github.com/projectkudu/kudu/wiki/Running-tests and this https://github.com/projectkudu/kudu/wiki/Getting-started -- I'll have to get back to this once I get back from vacation :palm_tree: But my first attempt is referenced above. I'll submit a PR once I get the functional test working

**Comment by warrenbuckley** [comment]
Has this PR died @davidebbo @sitereactor ?

**Comment by jvano** [comment]
Hi

Kudu will continue to run in Azure App Service. However, this repo will no longer be maintained.
If the problem persists and is related to running on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
