### ISSUE TITLE
AzureWebjob Timeouts (SQL connection) for specific date range

### ISSUE THREAD

**Issue by saro-rez** [projectkudu/kudu#1642]
I am facing a strange issue on running a Webjob that fetches data from SQL Azure, between given date range and then does some process. I am facing this issue for August dates!!, even when debugging from my local code. The same action for the entire July month works fine, but when I set the date range for August 01st alone, SQL connection timeouts. The same SQL query that fetches the data works fine from SQL Mgmt Studio. I tried increasing WEBJOBS_IDLE_TIMEOUT value, but same issue. I tried using TransientFaultHandling block, but same behavior.

Anyone got some clue what might be wrong??

**Comment by davidebbo** [comment]
You say you're getting the same issue when debugging from your local code. If so, it would appear that Azure Web Apps and Kudu are not involved in the issue. Please use the [Azure SQL forum](https://social.msdn.microsoft.com/Forums/azure/en-US/home?forum=ssdsgetstarted) instead to reach the right experts.
