### ISSUE TITLE
Some files can't be deleted from the CMD page

### ISSUE THREAD

**Issue by sebastienros** [projectkudu/kudu#1646]
In the tree view, files with this kind of names don't work: `tenant%3dbilalaslam%3burl%3d%2fbilalaslam%2fservervalidator-a-tool-to-validate-your-server-s-configuration%3bparam%3aid%3d19%3bparam%3aversion%3d%3btheme%3dthebootstrapmachine%3b`

Deleting the file from the console works.

**Comment by davidebbo** [comment]
It repros with `hello%20world`. Must be some kind of URL encoding issue.
