### ISSUE TITLE
TriggeredJobFinished hook is not documented anywhere

### ISSUE THREAD

**Issue by chuchuva** [projectkudu/kudu#1648]
Would be nice to have some documentation. Also, `https://<mysite>.scm.azurewebsites.net/WebHooks` does not mention TriggeredJobFinished event:

![image](https://cloud.githubusercontent.com/assets/237722/9127261/5a200e80-3cfb-11e5-8cd0-04e2910f1793.png)

**Comment by davidebbo** [comment]
I think closest thing is @amitapl's post: http://blog.amitapple.com/post/2014/03/webjobs-notification/. But yes, we need some doc cleanup here.

As for the WebHooks UI, support would need to be added for this hook type. Any volunteer? :)

**Comment by sitereactor** [comment]
I gave it a shot in this PR: https://github.com/projectkudu/kudu/pull/1652 :smile:

**Comment by davidebbo** [comment]
Thanks @sitereactor change works great! This will be on Azure in our next Kudu deployment.
