### ISSUE TITLE
.net 4.6 webjobs do not load

### ISSUE THREAD

**Issue by regisbsb** [projectkudu/kudu#1653]
They fail immediately with error code -2146232576

**Comment by davidebbo** [comment]
That's most likely simply the effect of running an exe that requires .NET 4.6 on a server that doesn't have it, and is not Kudu/WebJobs specific. Please use [this thread](https://social.msdn.microsoft.com/Forums/azure/en-US/262f9f05-31b6-429d-a83a-97efc5fdb82a/net-framework-46-full-support?forum=windowsazurewebsitespreview) to track 4.6 deployment.

**Comment by davidebbo** [comment]
Ad should add that 4.6 is partially deployed. Can you try your test on a temporary site in Japan West, which has it? That would confirm that it's the problem.

**Comment by regisbsb** [comment]
I'll. Cheers.
