### ISSUE TITLE
Error : Can't find the valid AspnetMergePath - precompilation on Azure

### ISSUE THREAD

**Issue by benosman** [projectkudu/kudu#1655]
Hello,

I'm trying to attempt to configure precompilation on Azure via git deployment. I'm testing using the default Web Forms project (VS 2015), before attempting with my own project.

I've set it up similar to this [post on stackoverflow] (http://stackoverflow.com/questions/27554510/cant-deploy-precompiled-merged-webapp-to-azure/29614694) as I couldn't find much documentation about how to do it.

I've enabled precompilation, and have experimented with the other settings (all same result) e.g.
Updatable (on / off)
Merge all pages (on / off)

I've created a .deployments file with:
```
[config]
project=UpstreamTest/UpstreamTest.csproj
SCM_BUILD_ARGS=/p:Configuration=Release;PublishProfile=azure-prod /v:n
```
This deploys correctly without precompilation, and works with precompilation locally, and using the publish to azure option in VS.

Instead, when deployments are triggered by bitbucket on azure I get the following output (snipped for relevancy):

```
Command: "D:\home\site\deployments\tools\deploy.cmd"

Handling .NET Web Application deployment.

All packages listed in packages.config are already installed.

Build started 8/11/2015 11:36:18 AM.

The target "MvcBuildViews" listed in a BeforeTargets attribute at "D:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v12.0\Web\Microsoft.Web.Publishing.targets (840,131)" does not exist in the project, and will be ignored.

Project "D:\home\site\repository\UpstreamTest\UpstreamTest.csproj" on node 1 (Build;pipelinePreDeployCopyAllFilesToOneFolder target(s)).

<SNIP>

  Copying D:\home\site\repository\packages\Microsoft.Net.Compilers.1.0.0\tools\VBCSCompiler.exe.config to obj\Release\AspnetCompileMerge\Source\bin\roslyn\VBCSCompiler.exe.config.

  Copying obj\Release\TransformWebConfig\transformed\Web.config to obj\Release\AspnetCompileMerge\Source\Web.config.

D:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v12.0\Web\Transform\Microsoft.Web.Publishing.AspNetCompileMerge.targets(132,5): error : Can't find the valid AspnetMergePath [D:\home\site\repository\UpstreamTest\UpstreamTest.csproj]

Done Building Project "D:\home\site\repository\UpstreamTest\UpstreamTest.csproj" (Build;pipelinePreDeployCopyAllFilesToOneFolder target(s)) -- FAILED.

Build FAILED.

"D:\home\site\repository\UpstreamTest\UpstreamTest.csproj" (Build;pipelinePreDeployCopyAllFilesToOneFolder target) (1) ->

(GetAspNetMergePath target) -> 

  D:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v12.0\Web\Transform\Microsoft.Web.Publishing.AspNetCompileMerge.targets(132,5): error : Can't find the valid AspnetMergePath [D:\home\site\repository\UpstreamTest\UpstreamTest.csproj]

    0 Warning(s)

    1 Error(s)

Time Elapsed 00:00:10.37

Failed exitCode=1, command="D:\Windows\Microsoft.NET\Framework\v4.0.30319\MSBuild.exe" "D:\home\site\repository\UpstreamTest\UpstreamTest.csproj" /nologo /verbosity:m /t:Build /t:pipelinePreDeployCopyAllFilesToOneFolder /p:_PackageTempDir="D:\local\Temp\d34abb98-e420-4bf0-9f7f-a9194a4220b3";AutoParameterizationWebConfigConnectionStrings=false;Configuration=Release /p:SolutionDir="D:\home\site\repository\.\\" /p:Configuration=Release;PublishProfile=azure-prod /v:n

An error has occurred during web site deployment.

```
I can't find any reference to AspnetMergePath/AspNetCompileMerge in the csproj file or in any project file for that matter.

Is anyone able to shed some light on this, whether i'm doing something wrong or missing a step.

Thanks

Ben

**Comment by davidebbo** [comment]
Can you please [share a test repo](https://github.com/projectkudu/kudu/wiki/Using-a-git-repo-to-report-an-issue) that has this issue? Thanks.

**Comment by benosman** [comment]
Here is the repo

https://github.com/benosman/upstreamtest

I tested this on Azure, and it has the same error as when using bitbucket.

**Comment by shrimpy** [comment]
seems like this error "error : Can't find the valid AspnetMergePath" is not new. from below two thread, to solve the issue we will need to use the right version of build tool.

http://stackoverflow.com/questions/12713714/cant-find-the-valid-aspnetmergepath-on-visual-web-developer-publish

http://blog.maskalik.com/msbuild/2014/03/04/changes-in-msbuild-with-visual-studio-2013/


however, my first attempt failed. 
 - Since project is created from VS2015, I set below app setting
     MSBUILD_PATH = D:\Program Files (x86)\MSBuild\14.0\Bin\MSBuild.exe 

- or update .deployment to below (application is targeting .net framework 4.5)
````
[config]
project=UpstreamTest/UpstreamTest.csproj
SCM_BUILD_ARGS=/p:Configuration=Release;PublishProfile=azure-prod /v:n /p:VisualStudioVersion=14.0 /p:AspnetMergePath="D:\Program Files (x86)\Microsoft SDKs\Windows\v8.1A\bin\NETFX 4.5.1 Tools\"
````

but still getting the same error. 

digging ..

**Comment by shrimpy** [comment]
@benosman 

there is a two steps work-around as below. I tried with your sample repo and it works. Let me know if you find any other issues.

- Go to portal, add one app setting to your site:
````
Key: MSBUILD_PATH
Value: D:\Program Files (x86)\MSBuild\14.0\Bin\MSBuild.exe 
````

- Update your deployment script to below
````
[config]
project=UpstreamTest/UpstreamTest.csproj
SCM_BUILD_ARGS=/p:Configuration=Release;PublishProfile=azure-prod /v:n /p:AspnetMergePath="D:\Program Files (x86)\Microsoft SDKs\Windows\v8.1A\bin\NETFX 4.5.1 Tools"
````

Explanation:
From what i learnt, project that created by a different version of Visual Studio, it require a corresponding version of Build Tool. Also asp.net project that target different version of .net framework will have corresponding version of aspnet_merge.exe

**Comment by benosman** [comment]
@shrimpy 

Thanks for looking at this for me, the two changes you suggested worked for me and it now deploys successfully.

Many thanks

Ben
