### ISSUE TITLE
Request: Add web hook for slot swapping

### ISSUE THREAD

**Issue by BrianVallelunga** [projectkudu/kudu#1672]
I'd like to know when I've swapped my production slot with the staging slot. This could easily be done with a web hook. The hook would need to post the basic site information and source and destination slot names.

**Comment by davidebbo** [comment]
I don't think this is something that can be implemented as part of Kudu, since swapping is generally not a Kudu feature. Can you please open a suggestion on http://feedback.azure.com/forums/169385-web-sites/ instead? Thanks!

**Comment by BrianVallelunga** [comment]
Will do, thanks.
