### ISSUE TITLE
Latest Kudu doesn't show file contents

### ISSUE THREAD

**Issue by kamranayub** [projectkudu/kudu#1674]
The latest update 47.40826.1772.0 (110ec5eab0).

When I try to go to CMD/PowerShell, navigate to a file (like site\wwwroot\web.config) and hit Edit, the textarea is blank.

If I cat the file, I can see its contents.

**Comment by davidebbo** [comment]
Strange, it works for me. What browser are you seeing this with?

/cc @snobu

**Comment by kamranayub** [comment]
Chrome latest

-----Original Message-----

**Comment by davidebbo** [comment]
Works for me with Chrome 44.0.2403.157 m.

Does it happen regardless of content? e.g. try with a text file that just has hello in it.

Also, try F12 tools to see if you're getting some js error.

**Comment by snobu** [comment]
`Chrome Version 44.0.2403.157 m (64-bit)`
Looks fine for me too.

Can you reach the Ace CDN? Is the editor loading?
Try this in your browser: https://cdnjs.cloudflare.com/ajax/libs/ace/1.1.9/ace.js

**Comment by kamranayub** [comment]
I can do it fine at home, it must be something with my work Chrome, maybe a caching issue. Closing for now.
