### ISSUE TITLE
Azure Webapp build failure with .NET 4.6 and Unity

### ISSUE THREAD

**Issue by JimiSmith** [projectkudu/kudu#1675]
I'm experiencing an issue with automatic deployments from git. The issue seems to be present when building a solution that uses .NET 4.6 and references Unity DI. Here is the beginning of the build log on a sample web that reproduces the problem.

```
Command: "D:\home\site\deployments\tools\deploy.cmd"
Handling .NET Web Application deployment.
All packages listed in packages.config are already installed.
D:\Windows\Microsoft.NET\Framework\v4.0.30319\Microsoft.Common.targets(1605,5): warning MSB3268: The primary reference "Unity.WebApi, Version=5.1.0.0, Culture=neutral, PublicKeyToken=43da31bc42a85347, processorArchitecture=MSIL" could not be resolved because it has an indirect dependency on the framework assembly "System.Runtime, Version=4.0.20.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" which could not be resolved in the currently targeted framework. ".NETFramework,Version=v4.6". To resolve this problem, either remove the reference "Unity.WebApi, Version=5.1.0.0, Culture=neutral, PublicKeyToken=43da31bc42a85347, processorArchitecture=MSIL" or retarget your application to a framework version which contains "System.Runtime, Version=4.0.20.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a". [D:\home\site\repository\Unity46\Unity46.csproj]
```

There are around 50 warnings similar to the above in the log. The log ends with the following

```
App_Start\UnityConfig.cs(1,17): error CS0234: The type or namespace name 'Practices' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?) [D:\home\site\repository\Unity46\Unity46.csproj]
App_Start\UnityConfig.cs(3,7): error CS0246: The type or namespace name 'Unity' could not be found (are you missing a using directive or an assembly reference?) [D:\home\site\repository\Unity46\Unity46.csproj]
```

The project builds fine on my local machine and once deployed through Visual Studio it runs on the azure webapp without problem

The web is located here: http://unity46.azurewebsites.net
Sample repo here: http://bitbucket.org/jimi312/unity46

The same repo builds fine without the Unity reference

I don't know if this has ever worked - I first saw the issue about 5 days ago - however I'd never tried deploying a 4.6 web though kudu prior to that

**Comment by davidebbo** [comment]
I think we know the issue, and it relates to some missing files on the build machine under `\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6\Facades`. We'll look to fix this. Though in the meantime, I think you should be able to work around by simply retargeting your project to use 4.5.2. Can you give that a shot?

**Comment by JimiSmith** [comment]
Retargeting to use 4.5.2 does work. We'll use that for now. Thanks.

**Comment by davidebbo** [comment]
Great. We'll get a real fix in, though that could take 2 or 3 weeks.

**Comment by pierre-weceipt** [comment]
Any feedback on this issue? Can you tell if it will be long before we can publish 4.6 projects on azure?

**Comment by davidebbo** [comment]
@pierre-weceipt the fix is being deployed gradually now, and we're about half done. So it may actually already work for you, and if it doesn't it will in a couple days. Did you try?

**Comment by pierre-weceipt** [comment]
Good to read this,I tried earlier but was still broken for me (West-europe website).

**Comment by davidebbo** [comment]
It's not all or nothing for a region. If you want to confirm that things will work for you after it's a deployed, please try it in a temporary test site in South Central US, which is fully upgraded. Or you can wait a day or two :)

**Comment by pierre-weceipt** [comment]
It's wir==orking in West-Europe now! Thanks :)

**Comment by ahmelsayed** [comment]
Thanks for the confirmation @pierre-weceipt. It should work everywhere now.
