### ISSUE TITLE
SCM_DISABLE_SUBMODULES not being honoured.

### ISSUE THREAD

**Issue by AlanParr** [projectkudu/kudu#1677]
I've got a .deployment file as below

[config]
SCM_DISABLE_SUBMODULES=1
command = deploy.cmd

My project has a submodule in a private repository which causes the build to fail when Kudu tries to pull it even though I have the SCM_DISABLE_SUBMODULES set so that it should ignore submodules.
I have also tried setting this in AppSettings in the Azure portal, again to no effect.

**Comment by davidebbo** [comment]
Strange. Does the build output actually contain the string `Updating submodules`? Can you share the relevant output?

**Comment by AlanParr** [comment]
Just tried it now. The first item in the Deployment is Updating Submodules, relevant output is below:

Warning: Permanently added '<myrepository>,<repoip>' (RSA) to the list of known hosts.\r\nPermission denied (publickey).\r\nfatal: Could not read from remote repository.\n\nPlease make sure you have the correct access rights\nand the repository exists.\nClone of 'ssh://git@<myrepo>' into submodule path '<destination>' failed\n\r\nD:\Program Files (x86)\Git\bin\git.exe submodule update --init --recursive

**Comment by davidebbo** [comment]
Can you share your site name, either directly or [indirectly](https://github.com/projectkudu/kudu/wiki/Reporting-your-site-name-without-posting-it-publicly)? This will help us investigate. Thanks!

**Comment by AlanParr** [comment]
Dummy is dummy69.azurewebsites.net. The issue has been encountered on all sites with the cms- prefix, in that plan and also in other regions and plans within that same subscription.

**Comment by davidebbo** [comment]
Indeed, I see this. I'll try to get my own repro and debug it later today.

**Comment by davidebbo** [comment]
As actually, this setting is not expected to work when used from `.deployment`. This is due to how things are ordered in the pipeline. Kudu first does everything it needs to get the repo/submodule, and only after that does it consume .deployment (it can't consume it till it has it).

However, I just tested it using a portal App Setting, and it works fine. Maybe you had a typo when you tried? It needs to be `SCM_DISABLE_SUBMODULES`, set to `1` (no quotes).

**Comment by AlanParr** [comment]
I've just tried and it worked a treat, I must've had a typo before. I take it the same principle holds true for SCM_USE_SHALLOW_CLONE as well, another one I've tried to use in the past without success?

It's not obvious in the docs that these need to be in AppSettings.

**Comment by davidebbo** [comment]
I have added a note to https://github.com/projectkudu/kudu/wiki/Configurable-settings for both settings.
