### ISSUE TITLE
"Illegal characters in path."

### ISSUE THREAD

**Issue by mskutin** [projectkudu/kudu#1680]
We've faced next issue during deploying our webapp via kudu custom deployment script.
`.scm.azurewebsites.net/api/deployments/739c0dd94ce9ca543fd426e8b4744b2b2952000b/log` shows just:

```json
{
"log_time": "2015-09-03T09:54:09.7991397Z",
"id": "5e5e8b15-db97-43c6-a759-70f06d49a053",
"message": "An unknown error has occurred. Check the diagnostic log for details.",
"type": 2,
"details_url": null
}
```
Found next log in trace directory:
```xml
<step title="Incoming Request" date="2015-09-03T09:53:38.504" instance="30114e" url="/deploy?scmType=ExternalGit" method="POST" type="request" pid="3672,2,34" Connection="Keep-Alive" Content-Length="141" Expect="100-continue" Host="dev-stage.scm.azurewebsites.net" User-Agent="Azure-WebSites-Controller/47.1.8598.1283" x-ms-request-id="4bceb38e-89a2-4725-aca6-374fd2d17542" X-SITE-DEPLOYMENT-ID="dev" >
  <step title="FetchHandler" date="2015-09-03T09:53:38.566" >
    <step title="Attempting to fetch target branch dev" date="2015-09-03T09:53:38.769" />
    <!-- duration: 0ms -->
    <step title="Assuming git repository at D:\home\site\repository" date="2015-09-03T09:53:39.098" />
    <!-- duration: 0ms -->
    <step title="Performing fetch based deployment" date="2015-09-03T09:53:39.223" >
      <step title="Creating temporary deployment" date="2015-09-03T09:53:39.238" />
      <!-- duration: 125ms -->
      <step title="DeploymentManager.Deploy(id)" date="2015-09-03T09:53:48.004" >
        <step title="Collecting changeset information" date="2015-09-03T09:53:48.163" />
        <!-- duration: 92ms -->
        <step title="Updating submodules" date="2015-09-03T09:53:48.270" />
        <!-- duration: 109ms -->
        <step title="Determining deployment builder" date="2015-09-03T09:53:48.694" >
          <step title="Builder is CustomBuilder" date="2015-09-03T09:53:48.723" />
          <!-- duration: 0ms -->
        </step>
        <!-- duration: 44ms -->
      </step>
      <!-- duration: 781ms -->
      <step title="Error occurred" date="2015-09-03T09:53:48.785" type="error" text="Illegal characters in path." stackTrace="   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.Combine(String path1, String path2)
   at Kudu.Core.Deployment.DeploymentManager.GetDeploymentManifestPath(String id)
   at Kudu.Core.Deployment.DeploymentManager.&lt;Build&gt;d__29.MoveNext()" />
      <!-- duration: 0ms -->
      <step title="Cleaning up temp files" date="2015-09-03T09:53:48.802" />
      <!-- duration: 15ms -->
      <step title="WebHooksManager.PublishEventAsync: PostDeployment" date="2015-09-03T09:53:48.852" />
      <!-- duration: 121ms -->
    </step>
    <!-- duration: 10219ms -->
  </step>
  <!-- duration: 10892ms -->
  <step title="Outgoing response" date="2015-09-03T09:53:49.473" type="response" statusCode="200" statusText="OK" Server="Microsoft-IIS/8.0" Cache-Control="private" X-AspNet-Version="4.0.30319" />
  <!-- duration: 0ms -->
</step>
<!-- duration: 11000ms -->```

Interesting that restarting site didn't help and we decided to deploy that on another webapp and it works properly.

**Comment by davidebbo** [comment]
Is the issue 100% reproducible for a given site name? If so, what's an example site name that causes it?

**Comment by mskutin** [comment]
Hi @davidebbo,

 I don't think that issue is related to site name, it doesn't contain something special and looks like `contoso-api-dev-stage.azurewebsites.net` and resource group name is, for example: `contoso-dev`. 
This webapp was created a long time ago, and there were no changes in AppSettings or deployment script. But during last 24 hours it's not possible to deploy anything there. Restarting and swapping site didn't change anything.

At the same time, we have successfully deployed this code on another WebApp resource, with name `contoso-api-test-stage.azurewebsites.net` and resource group is `contoso-test` without any issues.

By the way, we store our code in GitHub private repository, but we have to use `External repository`, because GitHub has quota in 20 connections to one repo.

**Comment by mskutin** [comment]
Reproduced 100% on stage deployment slot, production slot works properly.

**Comment by davidebbo** [comment]
The sites contoso-api-dev-stage.azurewebsites.net and contoso-api-test-stage.azurewebsites.net don't seem to exist right now. Do you still have a site with the issue? Can you share your site name, either directly or [indirectly](https://github.com/projectkudu/kudu/wiki/Reporting-your-site-name-without-posting-it-publicly)? This will help us investigate.

**Comment by mskutin** [comment]
>The sites contoso-api-dev-stage.azurewebsites.net and contoso-api-test-stage.azurewebsites.net don't seem to exist right now.

Those were just example names.
I've [created](http://illegal.azurewebsites.net) dummy webapp using link above.
I can't predict in which deployment slot this website will be located when you will start investigate this issue.
The website with issue has next name:
 `b******-dev-f***.azurewebsites.net` or `b******-dev-f***-stage.azurewebsites.net`

Currently issue is still reproduced in production deployment slot. If you need any additional info, please let me know.

**Comment by davidebbo** [comment]
Sorry for the delay. Seems you ran into a very rare case where the `D:\home\site\deployments\active` file gets corrupted and only contains ASCII characters 0. I've fixed it up on your site, and added logic to Kudu to automatically recover when that happens (https://github.com/projectkudu/kudu/commit/a1a89baaab2e950e4c99235a0f7f4f5b71b8aa86). That's not yet deployed, but it's highly unlikely that you'll see this again.
