### ISSUE TITLE
WebJob cron sample in wiki

### ISSUE THREAD

**Issue by snobu** [projectkudu/kudu#1681]
The WebJob cron sample in the wiki is a bit confusing: 
https://github.com/projectkudu/kudu/wiki/Web-jobs

```json
{
  "schedule": "* */1 * * * *"
}
```

At first glance this looks like it will run every minute of every 1 hour (so, every minute), but in fact it's every second. The 6-star notation (first star == seconds) isn't something common.

May i suggest adding a small comment right next to the sample `This will run every second`, or to simply change the sample into

`This will run every 30 seconds:`
```json
{
  "schedule": "*/30 * * * * *"
}
```

**Comment by mathewc** [comment]
Yes, that is wrong. I think the intent was "0 */1 * * * *" which is every minute, or even more concisely "0 * * * * *". I'll update the sample, thanks :)
