### ISSUE TITLE
There is not enough space on the disk on azure 'web apps'

### ISSUE THREAD

**Issue by Anderman** [projectkudu/kudu#1682]
Tried to deploy sample site from github. But got the error There is not enough space on disk when deploy script is doing dnu publish.
The sample site is on github [Usermanagement](https://github.com/Anderman/Mvc.JQuery.Datatables)

Because it contains pre release of asp.net 5 if have to set manual the nuget source before running the deployment.
`NuGet.exe sources add -Name aspnetrelease -Source https://www.myget.org/F/aspnetrelease/api/v2`

**Comment by davidebbo** [comment]
Yes, ASP.NET 5 apps tend to eat a lot of disk space. This is more of an ASP.NET 5 issue than a Kudu issue, and the team is aware of it. Please try deploying to a Basic or Standard site, which gets much more disk space.

**Comment by marchy** [comment]
This is ridiculous. They offer a free tier for but you can't even get a Hello World web API up and running? What's more is that the storage used for a Hello World app is megabytes (of the total 1GB) but I suppose the space used during the build/deployment exceeds it. This needs to be addressed.

**Comment by davidebbo** [comment]
To be clear, this is aspnet 5 specific, which is a pre-release product and will change. For any other app type (ASP.NET, Node, PHP, ...), there is plenty of space in a free site to deploy a typical app.

**Comment by Anderman** [comment]
I have no problems anymore. At the moment I use git deploy. I there way to start a fresh install? Last time I removed all file manualy )-;
