### ISSUE TITLE
Typo for the page introducing "accessing the kudo service"

### ISSUE THREAD

**Issue by rangeryu** [projectkudu/kudu#1684]
Page url : https://github.com/projectkudu/kudu/wiki/Accessing-the-kudu-service

"If you prefer not to use Single Sign On and instead use basic auth, you can go to http://mysite.azurewebsites.net/basicauth. The scm service will prompt you for credentials. "

The url should be http://mysite.scm.azurewebsites.net/basicauth. the "SCM" was missing which was misleading.
 
Also the feature applies to the mobile service site, please mention https://myservice.scm.azure-mobile.net/basicauth

Thanks.

**Comment by davidebbo** [comment]
Good catch, fixed!
