### ISSUE TITLE
aspnet 5 dnx beta7 app fails on Azure Web Site 

### ISSUE THREAD

**Issue by hoetz** [projectkudu/kudu#1685]
I have recently upgrade my beta 6 site to beta 7 and it broke my azure web site. it is currently showing a 500 and I can't seem to find the root cause of it.
I can reproduce the error when pushing the master of this repository https://github.com/hoetz/3dshootercom to a fresh Azure Web Site.
The site is hosted here: http://3dshootercom.azurewebsites.net.

**Comment by hoetz** [comment]
Update: After deploying for the n-th time with Visual Studio I now have a working site but as soon as I deploy via git it breaks again. I am copying all the files via ftp from the azure web app and will look for any differences. This is really strange.

**Comment by davidebbo** [comment]
I just tried creating a new beta 7 MVC app using latest VS tooling, and the result does appear to work well via git publishing to a Web App. Here is my repo: https://github.com/davidebbo-test/AspNet5Beta7.

But clearly, error handling needs improvement when things go wrong with aspnet 5!

**Comment by hoetz** [comment]
I can now confirm: current master branch of my repo works when published with VS. When pushed to master and after triggering the git CI build, it is broken again with a 500. I copied the entire directory via ftp and there doesn't seem to be a difference. Strange!

**Comment by davidebbo** [comment]
@davidfowl or @DamianEdwards: any idea how to debug a 500 (smiley oops type) in an aspnet 5 Web App? As far as I can tell, there is no log file at all getting created.

**Comment by hoetz** [comment]
Apparently there is an AppSetting Key ASPNET_DETAILED_ERRORS. When set to true in the root web.config it's supposed to display detailed errors. Will check this out later. Thanks to @ahmelsayed for pointing this out.

**Comment by hoetz** [comment]
My site seems to be working now even after the git CI build. Turns out Visual Studio added a global.json in the src Folder of the Web project and this caused some trouble.

**Comment by davidebbo** [comment]
Maybe this issue? https://github.com/aspnet/dnx/issues/2656

**Comment by hoetz** [comment]
Exactly!

**Comment by ealsur** [comment]
@davidebbo To check detailed error 500s I manually add the <customErrors> node (through Kudu) to the auto-generated web.config file that Kudu creates when running the deployment script.

**Comment by davidebbo** [comment]
@ealsur yep, that's seems to be what works. Doing it via Azure App Setting does not work. Anyway, the dnx team says they'll improve error handling soon :)
