### ISSUE TITLE
JSON encode issue with WebJobs API

### ISSUE THREAD

**Issue by anweiss** [projectkudu/kudu#1687]
I'm trying to invoke a triggered Node.js WebJob via the API by passing an object to the `arguments` parameter in my client code as follows:

```node
var jobName = 'webjobtest';
var obj = {"testKey01": "testValue01"};
var uri = "https://<siteName>.scm.azurewebsites.net/api/triggeredwebjobs/" + jobName + "/run?arguments=" + encodeURIComponent(JSON.stringify(obj));
request({
  method: 'POST',
  uri: uri,
  auth: {
    username: <username>,
    password: <password>
  }  
}, function onRequest(err, res, body) {
  if (err) {
    console.error(err);
  }
  console.log(res);
});
```

In my `webjobtest` WebJob, when I simply log the request argument, for some reason, the double quotes surrounding the object's keys and values get stripped:

```node
var argv = require('minimist')(process.argv.slice(2));
console.log(argv._[0]);
```

the output shows as:

```sh
[09/09/2015 14:21:52 > 85cfbe: INFO] {testKey01:testValue01}
```

How do I pass objects to the `arguments` parameter in the API request that doesn't result in the double quotes being stripped?

**Comment by davidebbo** [comment]
Can you share what the URL you are posting to looks like, so there is no ambiguity? With encodeURIComponent/stringify, it's less obvious exactly what you end up with.

**Comment by davidebbo** [comment]
I did a quick test of trying to pass double quotes as part of the argument, and it seems to work fine, so there may be something different about your case.

Note that the arguments also get passed to your process in the `WEBJOBS_COMMAND_ARGUMENTS` environment variable, so you may want to see if that makes any difference vs the command line argument.

**Comment by anweiss** [comment]
Thanks @davidebbo. My request URL looks like this after the encoding: `https://<siteName>.scm.azurewebsites.net/api/triggeredwebjobs/webjobtest/run?arguments=%7B%22testKey01%22%3A%22testValue01%22%7D` which decodes to: `https://<siteName>.scm.azurewebsites.net/api/triggeredwebjobs/webjobtest/run?arguments={"testKey01":"testValue01"}`. So it seems to prepare the request URL properly.

I wonder if it could be related to [this](https://github.com/request/request/issues/1692) issue in the [request](https://github.com/request/request) package.

**Comment by davidebbo** [comment]
I just tried it using postmane, and it works fine for me. To isolate from what your job might be doing, please test with this trivial WebJobs: just a `run.cmd` containing:

```
@echo Hello %1!
@echo Hi %WEBJOBS_COMMAND_ARGUMENTS%!
```

Then trigger it with that URL and look under `d:\home\data\jobs\triggered\webjobtest\{latestrun}`. The output I get contains:

```
[09/10/2015 01:54:49 > DAVIDE: INFO] Hello {"testKey01":"testValue01"}!
[09/10/2015 01:54:49 > DAVIDE: INFO] Hi {"testKey01":"testValue01"}!
```

So all the quotes look happy.

**Comment by anweiss** [comment]
Interesting. So I actually already have a simple webjob that I have been using to isolate the problem as follows:

```node
console.log(process.argv[2]);
```

results in:

```sh
[09/10/2015 02:12:11 > 85cfbe: INFO] {testKey01:testValue01}
```

What I just noticed, though, is that if instead of parsing the arguments with `process.argv`, I output the `WEBJOBS_COMMAND_ARGUMENTS`, a proper JSON response is obtained:

```node
console.log(process.env.WEBJOBS_COMMAND_ARGUMENTS);
```

results in:

```sh
[09/10/2015 02:01:38 > 85cfbe: INFO] {"testKey01":"testValue01"}
```

So it seems to be an issue with parsing `process.argv`.

**Comment by davidebbo** [comment]
I'll close the issue, as it doesn't look like there is an issue on the Kudu side. I think the right value is being passed on the command line that launches the WebJob, but for some reason it's getting parsed incorrectly in the exe. You may be able to repro by running that same exe manually with the same params.
