### ISSUE TITLE
Couldn't determine an appropriate version of runtime to run

### ISSUE THREAD

**Issue by sudsy** [projectkudu/kudu#1691]
Not sure if this is an issue for you or for someone else.

I am trying to git deploy an old webforms application which is running under 4.5 .

After a successful deployment I go to visit the root in my browser and receive a 500 error.

Digging through the logs I find the "Couldn't determine an appropriate version of runtime to run" error.

A couple of things I have tried.

1. There were two projects in the repository so I created a .deployment file with the following content
```
[config]
project = Website/Website.vbproj
```
2. I made sure that my Web.Config file contained a reference for the targetFramework
<httpRuntime targetFramework="4.5" requestValidationMode="2.0" />

It seems from the following comment that I need to run dnu publish to update the config file.

https://github.com/aspnet/Home/issues/452#issuecomment-92991558

That comment seems to suggest I need to Quasi-migrate this project to dnx to get it to work. I didn't think that was necessary.

Any ideas?

**Comment by davidebbo** [comment]
That doesn't sound right. If it's a classic WebForms project, you should not have to do anything related to dnx. Any chance you can [share a repo](https://github.com/projectkudu/kudu/wiki/Using-a-git-repo-to-report-an-issue) that demonstrates the problem?

**Comment by sudsy** [comment]
Thanks for your guidance.

I decided to create a completely fresh azure website rather than a deployment slot from an existing one and everything is working there. 

So, my guess is it's not a kudu problem.
