### ISSUE TITLE
Git path is hard-coded to C:\Program Files (x86)

### ISSUE THREAD

**Issue by breiter** [projectkudu/kudu#1692]
Git path is hardcoded to C:\Program Files (x86)\Git in both the Kudu.Service.Web.csproj and Kudu.Core PathUtility.

However, Git for Windows is now available in both x64 and x86 builds. The x64 build is preferred because it removes [some issues in the 32-bit version](https://github.com/git-for-windows/git/wiki/32-bit-issues). The x64 version of Git installs into C:\Program Files\ not C:\Program Files (x86)\.

In order to build and run Kudu s47 with Git 2.x (release) x64 the workaround I have found is to create a symbolic link between C:\Program Files (x86)\Git and C:\Program Files\Git.

Proposed solution:
- PathUtility::ResolveGitPath() should be smarter about looking at C:\Program Files and then C:\Program Files (x86). It should cache the result of where it finds Git. 
- Note that the same problem potentially exists for Mercurial which appears to have both x64 and x86 builds available.
- The generation of commit.txt by executing git as a subprocess of building Kudu.Service.Web.csproj should be performed with a shell script or just remove the absolute path and require git to be in the path.

**Comment by davidebbo** [comment]
Actually, both of these places already have logic to try `Program Files` first, and fall back to `Program Files (x86)`. What specific error are you getting?

**Comment by breiter** [comment]
I was getting a yellow screen of death with a stack trace which indicated git.exe could not be found but now I'm not. Does it make a difference if the VM is restarted after Git was installed? 

- Git 2.5.2 x64
- nodejs 4.0 x65

**Comment by davidebbo** [comment]
Not sure. If the git installer was asking for a restart, then maybe it wasn't all done and the files were not there. Anyway, let's close but if you hit this again. we can debug further.

**Comment by breiter** [comment]
thanks for being so responsive! I wish I had saved the original stack trace for you.

**Comment by breiter** [comment]
Here's the build-time error that Visual Studio generates when trying to execute this part of Kudu.Services.Web.csproj post-build:

```xml
    <Message Text="Running post build events" Importance="High" />
    <Exec Command="&quot;$(ProjectDir)\updateNodeModules.cmd&quot; &quot;$(TargetDir)&quot;" Condition=" '$(BuildOutputsUpdated)' == 'true' " />
    <Exec Command="&quot;%PROGRAMFILES(X86)%\Git\bin\git.exe&quot; rev-parse HEAD &gt; &quot;$(MsBuildProjectDirectory)\commit.txt&quot;" Condition=" '$(BuildOutputsUpdated)' == 'true' " />
    <Copy SourceFiles="$(SolutionDir)\Kudu.Console\bin\$(ConfigurationName)\kudu.exe" DestinationFolder="$(TargetDir)" SkipUnchangedFiles="true" />
```

```
5>------ Rebuild All started: Project: Kudu.Services.Web, Configuration: Release Any CPU ------
5>  Kudu.Services.Web -> G:\projectkudu\kudu\Kudu.Services.Web\bin\Kudu.Services.Web.dll
5>  Info: No event source classes needing registration found in G:\projectkudu\kudu\Kudu.Services.Web\bin\Kudu.Services.Web.dll
5>  Running post build events
5>  Attempt 1 out of 5
5>  kuduscript@0.1.13 node_modules\kuduscript
5>  Γö£ΓöÇΓöÇ streamline@0.4.11
5>  ΓööΓöÇΓöÇ commander@1.1.1 (keypress@0.1.0)
5>  Finished successfully.
5>  The system cannot find the path specified.
5>G:\projectkudu\kudu\Kudu.Services.Web\Kudu.Services.Web.csproj(290,5): error MSB3073: The command ""%PROGRAMFILES(X86)%\Git\bin\git.exe" rev-parse HEAD > "G:\projectkudu\kudu\Kudu.Services.Web\commit.txt"" exited with code 3.
```

## Configuration
- windows server 2012 r2, fully patched
- visual studio 2015
- nodejs 4.0 x64
- git 2.5.2 x64
- hg 3.5.1 x64

```
c:\Program Files (x86)>mklink /d Git "C:\Program Files\Git"
symbolic link created for Git <<===>> C:\Program Files\Git
```

"The system cannot find the path specified" error goes away.

**Comment by davidebbo** [comment]
I would think it should work based on [this logic](https://github.com/projectkudu/kudu/blob/7c15ba6f0b68c9504fb5d4a227cfc66d5d40b220/Kudu.Services.Web/Kudu.Services.Web.csproj#L290-L291), which tries both locations:

```
    <Exec Command="&quot;$(ProgramW6432)\Git\bin\git.exe&quot; rev-parse HEAD &gt; &quot;$(MsBuildProjectDirectory)\commit.txt&quot;" Condition=" '$(BuildOutputsUpdated)' == 'true' AND Exists('$(ProgramW6432)\Git\bin\git.exe') " />
    <Exec Command="&quot;$(ProgramFiles)\Git\bin\git.exe&quot; rev-parse HEAD &gt; &quot;$(MsBuildProjectDirectory)\commit.txt&quot;" Condition=" '$(BuildOutputsUpdated)' == 'true' AND !Exists('$(ProgramW6432)\Git\bin\git.exe') AND Exists('$(ProgramFiles)\Git\bin\git.exe') " />
```

**Comment by breiter** [comment]
Is that in master? I was referencing the behavior in the stable s47 build.

**Comment by davidebbo** [comment]
Ah, that was actually added after, when we started moving our local machines to the new git. Are you using Kudu from sources, or are you using the binary drop?

**Comment by breiter** [comment]
I’m using build from source because I’m patching the Startup.cs to bind an BasicAuthCredentialProvider to use a Windows account that we provision and then we apply basic auth on the services and main kudu app. These ports are only accessible through internal network by VPN.

I haven't taken a snapshot in a while. I had to do a lot of fiddling to get it to build with the new git and visual studio that I have installed on my dev vm. There was also some fxcop rule to ignore or it kills the build.cmd release.

If there's a better way for me to do this than patching Startup.cs, I'd love to know.

**Comment by davidebbo** [comment]
If you have some changes that make things more flexible without breaking existing scenarios, feel free to send a PR.

**Comment by breiter** [comment]
Unfortunately, it's more of a `patch -p1 < kudu-account.diff` and then compile where the patch just changes the existing credential to something secret.

```c#
kernel.Bind<ICredentialProvider>().ToConstant(new BasicAuthCredentialProvider("admin", "kudu"));
```
