### ISSUE TITLE
MSBUILD_PATH changed and other errors

### ISSUE THREAD

**Issue by caterwomtious** [projectkudu/kudu#1694]
We use a custom Kudu deployment script and today it stopped working. The value of the MSBUILD_PATH variable has changed. I'm not sure what it was before, but the first error I hit was that my script couldn't find msbuild.exe, and that was happening because the path wasn't in quotes and it now has a space in it. It's current value is D:\Program Files (x86)\MSBuild\14.0\Bin\MSBuild.exe.

I added the quotes but now I get two further errors:

D:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(2718,5): error MSB3091: Task failed because "resgen.exe" was not found, or the correct Microsoft Windows SDK is not installed. The task is looking for "resgen.exe" in the "bin" subdirectory beneath the location specified in the InstallationFolder value of the registry key HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Microsoft SDKs\Windows\v8.0A\WinSDK-NetFx35Tools-x86. You may be able to solve the problem by doing one of the following:  1) Install the Microsoft Windows SDK.  2) Install Visual Studio 2010.  3) Manually set the above registry key to the correct location.  4) Pass the correct location into the "ToolPath" parameter of the task. [D:\home\site\repository\path-to-my-project.csproj]

The path the message refers to doesn't exist. resgen.exe is only present in the following locations:

D:\Program Files (x86)\Microsoft SDKs\Windows\v8.0A\bin\NETFX 4.0 Tools
D:\Program Files (x86)\Microsoft SDKs\Windows\v8.1A\bin\NETFX 4.5.1 Tools

I tried adding the latter to %PATH% but it didn't help. I'm seeing this in .NET 3.5 builds and the error refers to a 3.5 folder, so I wonder if support for 3.5 has been removed? 

D:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.CSharp.CurrentVersion.targets(133,9): warning MSB3884: Could not find rule set file "AllRules.ruleset"

This one relates to code analysis rules. As it's only a warning it doesn't break the build and may have been present before, but I'm including it for completeness.

**Comment by davidebbo** [comment]
We did switch to the newer msbuild, though it isn't supposed to break things like this.

For now, you should be able to work around by setting `MSBUILD_PATH=D:\Windows\Microsoft.NET\Framework\v4.0.30319\MSBuild.exe` in your Azure App Settings to go back to the old msbuild. Can you give that a try?

**Comment by caterwomtious** [comment]
That worked, thank you.

**Comment by davidebbo** [comment]
We still would like to get to the bottom of it. Any chance that you can share a repo that repos this? At this point, we're pretty puzzled why it happens.

**Comment by caterwomtious** [comment]
Yes, I can pull something together and email. Can you let me know an email address? You can DM to caterwomtious on Twitter.

**Comment by davidebbo** [comment]
Email is david.ebbo AT microsoft. Though if possible, it's easier to work with if you can make a minimal repro without anything sensitive, per [this page](https://github.com/projectkudu/kudu/wiki/Using-a-git-repo-to-report-an-issue).

**Comment by caterwomtious** [comment]
Here it is:
https://github.com/east-sussex-county-council/KuduIssue1694Demo

The issue seems to be related to a workaround we put in for a previous bug, detailed here:

https://connect.microsoft.com/VisualStudio/feedback/details/758772/generateresource-fails-for-net-3-5-application-when-net-4-5-has-been-installed

**Comment by davidebbo** [comment]
Very helpful, thanks!

Initial findings:

- On my dev machine, under `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Microsoft SDKs\Windows\v8.0A\WinSDK-NetFx35Tools-x86`, `InstallationFolder` is set to `C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\Bin\`, and that folder has RegGen.
- On the Azure build machine, the reg key `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Microsoft SDKs` is missing altogether.
- On the Azure build machine, the folder `D:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\Bin` is missing ResGen.
- When using the old msbuild with your project, it ends up successfully loading ResGen from `D:\Program Files (x86)\Microsoft SDKs\Windows\v8.0A\bin\NETFX 4.0 Tools\ResGen.exe`

**Comment by davidebbo** [comment]
Turns out the reg keys that matter are actually under `Wow6432Node`, because it's a 32 bit process on a 64 bit OS.

The only thing that's missing to make the scenario work is the reg value `InstallationFolder` under the key `HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\Microsoft SDKs\Windows\v8.0A\WinSDK-NetFx35Tools-x86`. Interestingly, even if the path it points to doesn't exist, it ends up working and using `D:\Program Files (x86)\Microsoft SDKs\Windows\v8.0A\bin\NETFX 4.0 Tools\ResGen.exe`, as it did with the old msbuild.

So this gives us a simple very targeted fix that doesn't require major new installations.

**Comment by caterwomtious** [comment]
Great stuff, thank you.
