### ISSUE TITLE
npm install failed

### ISSUE THREAD

**Issue by stackia** [projectkudu/kudu#1696]
Try to deploy from Git but npm install always fails:

```
2. Install npm packages
npm ERR! Windows_NT 6.2.9200
npm ERR! argv "D:\\Program Files (x86)\\nodejs\\4.0.0\\node.exe" "D:\\Program Files (x86)\\npm\\2.14.2\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v4.0.0
npm ERR! npm  v2.14.2
npm ERR! path D:\home\site\repository\node_modules\gulp-uglify\node_modules\fancy-log\node_modules\dateformat\node_modules\meow\node_modules\indent-string\node_modules\repeating\node_modules\is-finite\node_modules\number-is-nan\package.json.541f6c9b8df1f15f3ebad2a7c1111c43
npm ERR! code EINVAL
npm ERR! errno -4071
npm ERR! syscall rename

npm ERR! EINVAL: invalid argument, rename 'D:\home\site\repository\node_modules\gulp-uglify\node_modules\fancy-log\node_modules\dateformat\node_modules\meow\node_modules\indent-string\node_modules\repeating\node_modules\is-finite\node_modules\number-is-nan\package.json.541f6c9b8df1f15f3ebad2a7c1111c43' -> 'D:\home\site\repository\node_modules\gulp-uglify\node_modules\fancy-log\node_modules\dateformat\node_modules\meow\node_modules\indent-string\node_modules\repeating\node_modules\is-finite\node_modules\number-is-nan\package.json'
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     D:\home\site\repository\npm-debug.log
Failed exitCode=-4071, command="D:\Program Files (x86)\nodejs\4.0.0\node.exe" "D:\Program Files (x86)\npm\2.14.2\node_modules\npm\bin\npm-cli.js" install
```

Try to execute `npm install gulp-template -g` in Azure portal Console also get the same error.
```
> npm install gulp-template -g

npm ERR! Windows_NT 6.2.9200
npm ERR! argv "D:\\Program Files (x86)\\nodejs\\4.0.0\\node.exe" "D:\\Program Files (x86)\\npm\\2.14.2\\node_modules\\npm\\bin\\npm-cli.js" "install" "gulp-template" "-g"
npm ERR! node v4.0.0
npm ERR! npm  v2.14.2
npm ERR! path D:\local\AppData\npm\node_modules\gulp-template\node_modules\gulp-util\node_modules\dateformat\node_modules\meow\node_modules\indent-string\node_modules\repeating\node_modules\is-finite\node_modules\number-is-nan\package.json.60095c333fa1cad462ac0401a5e3b3fb
npm ERR! code EINVAL
npm ERR! errno -4071
npm ERR! syscall rename

npm ERR! EINVAL: invalid argument, rename 'D:\local\AppData\npm\node_modules\gulp-template\node_modules\gulp-util\node_modules\dateformat\node_modules\meow\node_modules\indent-string\node_modules\repeating\node_modules\is-finite\node_modules\number-is-nan\package.json.60095c333fa1cad462ac0401a5e3b3fb' -> 'D:\local\AppData\npm\node_modules\gulp-template\node_modules\gulp-util\node_modules\dateformat\node_modules\meow\node_modules\indent-string\node_modules\repeating\node_modules\is-finite\node_modules\number-is-nan\package.json'
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     D:\home\site\wwwroot\npm-debug.log
```

Here is my package.json:
```
{
  "name": "my-project",
  "private": true,
  "description": "Foo bar",
  "devDependencies": {
    "bower": "^1.0.0",
    "del": "^2.0.2",
    "glob": "^5.0.14",
    "gulp": "^3.0.0",
    "gulp-angular-templatecache": "^1.7.0",
    "gulp-autoprefixer": "^3.0.1",
    "gulp-concat": "^2.6.0",
    "gulp-minify-css": "^1.2.1",
    "gulp-modify-css-urls": "^0.2.0",
    "gulp-rename": "^1.2.2",
    "gulp-rev": "^6.0.1",
    "gulp-template": "^3.0.0",
    "gulp-uglify": "^1.4.1",
    "lodash": "^3.10.1"
  }
}
```

I guess the file path is too so long that the rename operation failed. But the path has not reached 260 length. I'm not sure what's going wrong...

**Comment by davidebbo** [comment]
Actually, it has reached 260:

    D:\home\site\repository\node_modules\gulp-uglify\node_modules\fancy-log\node_modules\dateformat\node_modules\meow\node_modules\indent-string\node_modules\repeating\node_modules\is-finite\node_modules\number-is-nan\package.json.541f6c9b8df1f15f3ebad2a7c1111c43

So it's most likely what the issue is.

**Comment by davidebbo** [comment]
Basically same as https://github.com/projectkudu/kudu/issues/1490. You can try using dedupe, or move to npm 3.x which is smarter about path length.

**Comment by gkorland** [comment]
Why did you close this issue? Is there any solution? I couldn't find any real solution.  #1490 doesn't really solve it. See: [npm 3.x install fails on rename long paths in Windows/Azure](http://stackoverflow.com/questions/35412935/npm-3-x-install-fails-on-rename-long-paths-in-windows-azure)

**Comment by stackia** [comment]
Didn't find any good solutions.
Now we just compile everything (JS/CSS) at commit time and avoid running npm/gulp/bower at deploy time.

**Comment by davidebbo** [comment]
Switching to npm 3.x helps reduce path lengths in some scenarios.

**Comment by gkorland** [comment]
@davidebbo it doesn't moving 3.x is the source cause of this issue since it tries to deduplicate (rename).
Is there a way to disable the deduplicate?

**Comment by davidebbo** [comment]
Referencing your question: http://stackoverflow.com/questions/35412935/npm-3-x-install-fails-on-rename-long-paths-in-windows-azure

Frankly, I don't know exactly how npm3 works, but my understanding is that the goal was to limit deep paths. But if in the process of doing its work it goes through very long paths, then this purpose seems defeated. e.g. in the case of your SO question, you show this path:

`D:\home\site\wwwroot\node_modules\azure_util\node_modules\pkgcloud\node_modules\gcloud\node_modules\gapitoken\node_modules\jws\node_modules\base64url\node_modules\meow\node_modules\indent-string\node_modules\repeating\node_modules\is-finite\node_modules\number-is-nan`

Which has 267 characters, so it blows the 260 limit. In the end, this is an npm/Windows issue, and there is little that Azure/Kudu can do. But I do which npm would fix this properly.

**Comment by stackia** [comment]
I learned that npm is using [UNC path internally which should support up to 32767 chacacters](http://stackoverflow.com/questions/6996711/how-to-create-directories-in-windows-with-path-length-greater-than-256)
https://github.com/npm/npm/issues/3697#issuecomment-34394290
And it actually created that long path on my PC (I cannot delete node_modules using Explorer due to the long path), but why it doesn't work on Azure?

**Comment by gkorland** [comment]
@stackia the issue was that we already had a running version on Azure with npm 2.x
When we upgraded to npm 3.x it tried to deduplicate the modules --> rename which in turn failed.

When we deployed the project from scratch it managed to install the modules.

**Comment by Jackychans** [comment]
is there any resolution ?

I run into the issue with firebase as it's very long path. Is there possible way to resolve?

**Comment by aroget** [comment]
Any thoughts on this issue? Im running into the same situation deploying our app to Azure, it used to work fine but after upgrading angular from RC4 to v2.1.0, its failing with the exact same error.....

```
npm ERR! node v4.4.1
npm ERR! npm  v2.14.20


npm ERR! code EINVAL
npm ERR! errno -4071
npm ERR! syscall rename

D:\home\site\wwwroot\node_modules\webpack\node_modules\watchpack\node_modules\chokidar\node_modules\anymatch\node_modules\micromatch\node_modules\braces\node_modules\expand-range\node_modules\fill-range\node_modules\isobject\node_modules\isarray\package.json.1270886937
```

**Comment by davidebbo** [comment]
@aroget that path is over the 260 limit. So you're seeing this with npm 2.x right? Did you try 3.x?

**Comment by aroget** [comment]
Nope, not yet, I read @gkorland message saying that didnt help him so havent tried that yet, on the other hand I tried deploying the app to a brand new web app on azure and it failed as well, so it has nothing to do with the existing node_modules... any how ill try upgrading NPM and see if that helps.

Any other thoughts on your end @davidebbo ? Also thanks for your quick reply

**Comment by davidebbo** [comment]
I think the best way to get to the bottom of these issues is to try manually running npm (2 or 3) from Kudu Console. In the end, we have a constraint that we can't change, which is the Windows path length (well, except for the new Linux Preview we [just announced](https://azure.microsoft.com/en-us/blog/azure-app-service-improves-node-js-and-php-developer-experience/)!)

**Comment by aroget** [comment]
Morning @davidebbo to my surprise things are working very well this morning, I just upgraded my npm version and tried to push the app again and it worked fine the code has been deployed to Azure no problems 🎉 

Thanks for your time,

**Comment by dazinator** [comment]
I just hit this issue for what it's worth.

I put this in my `deployment.cmd`:
```
:: Restore npm packages
echo Restoring Website Npm Packages
cd "D:\home\site\repository\src\DnnManager.Website\"
call npm install
```

Here is the output from kudo build:
```
Feeds used:
    https://api.nuget.org/v3/index.json
Restoring Website Npm Packages
npm ERR! Windows_NT 6.2.9200
npm ERR! argv "D:\\Program Files (x86)\\nodejs\\4.4.7\\node.exe" "D:\\Program Files (x86)\\npm\\2.15.8\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v4.4.7
npm ERR! npm  v2.15.8
npm ERR! path D:\home\site\repository\src\DnnManager.Website\node_modules\jspm\node_modules\liftoff\node_modules\fined\node_modules\parse-filepath\node_modules\is-absolute\node_modules\is-relative\node_modules\is-unc-path\node_modules\unc-path-regex\package.json.2149244318
npm ERR! code EINVAL
npm ERR! errno -4071
npm ERR! syscall rename
```

I'm going back to committing my packages to source control, attempting to restore packages on kudo environment seems a bit painful at the moment.

**Comment by xt0rted** [comment]
I haven't hit this issue since switching to npm 3. You can force the version used with the setting `WEBSITE_NPM_DEFAULT_VERSION`. Or switch to node 5+ which uses npm 3 by default.

There's more in the wiki on these [Configurable-settings#change-the-node-version](https://github.com/projectkudu/kudu/wiki/Configurable-settings#change-the-node-version)

**Comment by dazinator** [comment]
Bam! sitching to NPM  3 fixed it - all working now.. thanks a lot!
