### ISSUE TITLE
Upload button

### ISSUE THREAD

**Issue by sansjunk** [projectkudu/kudu#1705]
Kudu is great for drag 'n drop upload but blame me for trying Kudu on Edge which doesn't support drag 'n drop yet! Can we please have an explicit old-style upload button for those who dare to try the bleeding edge :-)

**Comment by davidebbo** [comment]
To be honest, I'm a bit hesitant to do work for something that is (hopefully!) a temporary limitation until they complete implementation.

**Comment by sansjunk** [comment]
Fair enough!

**Comment by christopheranderson** [comment]
Poking this issue. Drag and drop still isn't working on Edge for large zip files.

**Comment by davidebbo** [comment]
@christopheranderson and the same file works in Chrome? It probably comes down to browser limitation. Frankly, I'm hesitant to invest in adding an upload button when there is an easy workaround with Chrome. And Edge did get better in that area through the years, so hopefully it'll continue to improve.

**Comment by jvano** [comment]
Hi

Kudu will continue to run in Azure App Service. However, this repo will no longer be maintained.
If the problem persists and is related to running on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
