### ISSUE TITLE
Pick exact or, if not exist, nearest node version

### ISSUE THREAD

**Issue by suwatch** [projectkudu/kudu#1708]
nearest = rounding down version.

**Comment by davidebbo** [comment]
There are two scenarios here:

1. user picks version that doesn't exist
2. user picks version that exists, but we later decide to remove (to clean up)

Problem with 2. is that if they had picked it using package.json, it ends up hard coded in `iisnode.yml`, e.g.

    nodeProcessCommandLine: "D:\Program Files (x86)\nodejs\0.12.6\node.exe"

I'm wondering if we'd be better off trying to solve this at the iisnode level to cover all scenarios. Though that would mean backing some knowledge of our folder structure in iisnode, whereas today it just takes the full node.exe command line as is.

**Comment by jvano** [comment]
Hi

Kudu will continue to run in Azure App Service. However, this repo will no longer be maintained.
If the problem persists and is related to running on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
