### ISSUE TITLE
Deleted WAR file not reflecting correctly in Kudu

### ISSUE THREAD

**Issue by sansjunk** [projectkudu/kudu#1709]
Kudu seems to have an issue when trying to delete a deployed Tomcat WAR file on an Azure app (bridged to Java Tomcat). On drag and drop to `wwwroot/webapps` the WAR is automatically unzipped and deployed by Tomcat. Then if I attempt to delete the WAR file the deployed folder is removed which I guessing is being done by Tomcat. However the WAR still stays and Kudu doesn't report errors. Next when I attempt to delete the WAR file again, Kudu says an error occurred and continues to show the WAR but if I go back to previous folder and come in again the WAR is gone. Isn't a critical problem but thought I'd report it.

**Comment by suwatch01** [comment]
When you said, you `delete` the WAR file, how did you do that?  Try using Kudu Console command prompt to delete the WAR file and see if it succeeds.  File may be in use and the error will show up on Console.

**Comment by sansjunk** [comment]
I tried to delete using the UI. I just tried deleting using the command line and it works as expected with no errors being reported - first the WAR file goes away and a few moments later the folder vanishes because of Tomcat deleting it. So there is a difference in behavior between the command line and the UI delete.

**Comment by jvano** [comment]
Hi

Kudu will continue to run in Azure App Service. However, this repo will no longer be maintained.
If the problem persists and is related to running on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
