### ISSUE TITLE
Please document Kudu REST API

### ISSUE THREAD

**Issue by davux** [projectkudu/kudu#1710]
[That page](https://github.com/projectkudu/kudu/wiki/REST-API) is useful but it could afford more precise developer information: expected arguments, possible outputs and their meanings (e.g. on the Command API), HTTP error codes, etc.

Please provide documentation so that the REST API can be used in production scenarios.

**Comment by staticcat** [comment]
As this is the only source of information (apart from the source of-course) it is very much needed. As an example the following for "Environment" is just inadequate. 

"Environment

GET /api/environment
Get the Kudu version"

A good example of REST documentation is http://docs.aws.amazon.com/AmazonS3/latest/API/RESTBucketDELETEcors.html.

**Comment by davux** [comment]
Any news on this? Proper documentation is fundamental.

**Comment by davidebbo** [comment]
Just noticing @staticcat's comment above. There is no need to sign a CLA just for wiki contribution. The one painful factor is that github does not have a good model for contributing to wikis. They're backed by git repos (https://github.com/projectkudu/kudu.wiki.git), but don't support PRs. We can still find way around by forking that repo and doing the PR elsewhere.

**Comment by jvano** [comment]
Hi

Kudu will continue to run in Azure App Service. However, this repo will no longer be maintained.
If the problem persists and is related to running on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
