### ISSUE TITLE
Webjob Logging Retention Policy

### ISSUE THREAD

**Issue by NVentimiglia** [projectkudu/kudu#1715]
I would like to retain my log data beyond 7 hours. Right now, when I log into the WebJob details 'website' I only see 7 hours of logs.

I have configured my webjob to use Table and Blob logging from the application manager. When asked, I set my detention policy to 14 days. After all is said and done my azure webjob 'website' only retains logs for 7 hours. 

![logsettings](https://cloud.githubusercontent.com/assets/125889/10182333/da5bcfca-66d7-11e5-8e75-9db3e92ccc50.png)

**Comment by NVentimiglia** [comment]
Original : https://github.com/Azure/azure-webjobs-sdk/issues/574

**Comment by davidebbo** [comment]
Is that for a continuous WebJob or a triggered WebJob? See https://github.com/projectkudu/kudu/wiki/Web-jobs#configuration-settings and try changing `WEBJOBS_HISTORY_SIZE`.

**Comment by NVentimiglia** [comment]
@davidebbo 

Thanks for reaching out. These are triggered WebJobs. I have adjusted my config in the Azure Website Configuration portal and in the app.config file.

Did I do it right ?

`````
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <appSettings>
    <add key="WEBJOBS_HISTORY_SIZE" value="999"/>
  </appSettings>

`````

**Comment by mathewc** [comment]
You should just set it in the portal. Yes, your setting key/values look good. This setting only governs triggered jobs, and is the number of history entries that will be retained. The default is 50.

**Comment by davidebbo** [comment]
Right, this will have no effect in your app.config. It must be an Azure AppSetting, which you can set in Portal (or API, etc...)

**Comment by NVentimiglia** [comment]
This is working, thanks everyone !
