### ISSUE TITLE
Browsing IIS .xml log files no longer formats in browser

### ISSUE THREAD

**Issue by andybatescc** [projectkudu/kudu#1716]
It used to be that if I clicked download on an application failed request trace.xml file (/LogFiles/W3SVNnnnnnnnnnn/frnnnnnn.xml) from the debug console that the file would just open in the browser formatted automatically for display. This is no longer working and instead the file shows in the download bar whereupon I then have to open outside the browser session. So the autoformat is no longer working

Have there been any changes in this area, have tried this on my usual computer and another fresh install one.

**Comment by snobu** [comment]
See this issue https://github.com/projectkudu/kudu/issues/1634

We're currently investigating the best way to handle this, either roll back the change, change the UI for both actions or have an exception for XML Failed Request Tracing.

If you also download the .xsl template your downloaded XMLs should show up nicely formatted. 

Sorry for the inconvenience.

**Comment by andybatescc** [comment]
Many thanks for the response and it's good that this is in hand. So far I haven't managed to get it to display formatted though, opening the file in chrome is showing blank, but not looked any further as to what's happening.

**Comment by snobu** [comment]
You're right. Now it only works in IE when both XML and XSL are downloaded in the same folder.
I'm working on a fix as we speak.

**Comment by andybatescc** [comment]
I have found this extension which has fixed it for now and reversed the header:
https://chrome.google.com/webstore/search/undisposition?hl=en

**Comment by davidebbo** [comment]
Ok, @snobu reverted the change, so this issue will go away on the next Kudu deployment. And for now, you have that Chrome extension :)
