### ISSUE TITLE
Azure Deployment Failure: Logs Show No Errors

### ISSUE THREAD

**Issue by robfarmergt** [projectkudu/kudu#1718]
I'm having an issue where deployment fails. This is my first deployment with beta7. I've tried stopping the web app instance and redeploying, but still no luck. I've gone through every line of the Activity Log console in the Azure Portal but I don't see any errors.

Is there another place to look to see what the issue might have been?

**Comment by davidebbo** [comment]
Can you please provide more details. Specifically:

- what's the specific error you're getting?
- please share a [repro repo](https://github.com/projectkudu/kudu/wiki/Using-a-git-repo-to-report-an-issue)

**Comment by robfarmergt** [comment]
The only error I get is just that the status of the deployment was "failed".

![image](https://cloud.githubusercontent.com/assets/4447784/10223263/3edc318e-6826-11e5-8593-f3a116f21cba.png)

Here is the output of the activity log:
https://gist.github.com/robfarmergt/b7bf9439af52ffa89469

If you need me to I can add you to the repository, but I can't make it public.

**Comment by davidebbo** [comment]
Did you see [this page](https://github.com/projectkudu/kudu/wiki/Using-a-git-repo-to-report-an-issue)? It has details on what makes a good repro, which typically is not your private repo.

Also, can you share your site name, either directly or [indirectly](https://github.com/projectkudu/kudu/wiki/Reporting-your-site-name-without-posting-it-publicly)? This will help us investigate. Thanks!

**Comment by robfarmergt** [comment]
Here a dummy site:
http://pr-kudu-pub.azurewebsites.net

Ill see if I can get a

**Comment by robfarmergt** [comment]
Accidentally closed this. Opening back up.

**Comment by davidebbo** [comment]
You have multiple other sites in there, so you'll need to give additional clues about which one has the issue.

But if you can get a repo we can try, it's easier for us :)

**Comment by robfarmergt** [comment]
It's the qa site :)

Working on a repo, but might take me a little bit to get everything ready.

**Comment by robfarmergt** [comment]
@davidebbo Can it be a private repo and I can just give you and whomever else needs access to it?

**Comment by davidebbo** [comment]
Sure, if isolating to a repo that can be made public is proving difficult, we can fall back to private. I'm *davidebbo* on GitHub and Bitbucket.

**Comment by robfarmergt** [comment]
@davidebbo invite sent

Also, the mentioned dummy site (http://pr-kudu-pub.azurewebsites.net) has a failed deployment with the private repo you were invited to. Let me know if you need more than write permissions or for me to invite someone else.

**Comment by davidebbo** [comment]
Thanks. Looks like something is blowing up during the `dnu publish` bundling step, though at this point I don't know what.

**Comment by davidebbo** [comment]
Yes, basically, `dnu publish` is returning a -1 code (meaning it failed), yet it's not displaying anything that looks like an error. We'll need to get help from DNX experts for this one.

**Comment by robfarmergt** [comment]
Ok, let me know if there is anything else I can do. I really appreciate your help!

**Comment by robfarmergt** [comment]
@davidebbo has the DNX team been able to look into this?

**Comment by davidebbo** [comment]
@robfarmergt it actually came up yesterday on a thread with @davidfowl. At this point, it's not well understood, but we'll get to the bottom of it.

**Comment by robfarmergt** [comment]
@davidebbo @davidfowl Any progress in figuring out this issue?

Is there a way to manually deploy to our Azure web app in the meantime? We have a couple of other things on hold waiting to get something released.

**Comment by robfarmergt** [comment]
@davidebbo checking back in to see if there is a solution or a workaround to getting the app deployed manually to Azure?

**Comment by davidebbo** [comment]
Sorry, I'll really need the DNX experts to shine in on this one. 'dnu publish' is returning a -1 errorlevel, and I have no idea why.

**Comment by ahmelsayed** [comment]
Is your site running in Free tier by any chance? We saw dnu silently fail during publishing because of disk space issues.

**Comment by davidebbo** [comment]
No, it's not the disk space issue in this case. Something else is going on.

**Comment by robfarmergt** [comment]
It's S1 level and only 2.11% of file storage quota is used.

**Comment by robfarmergt** [comment]
@ahmelsayed Is there anything I can provide you with to assist?

**Comment by davidebbo** [comment]
@robfarmergt We're on a thread with dnx folks, and waiting for them to shine in.

**Comment by robfarmergt** [comment]
@davidebbo I know you guys are working hard on this and I don't want to be a bother. I'm at the point where I probably need to start getting alternate hosting configured. Any rough estimate as to a time frame for a fix?

**Comment by davidebbo** [comment]
Adding @davidfowl @victorhurdugaci @muratg to have the conversation directly. I really wouldn't know how to get further into that issue without some DNX help.

DNX folks, are there any debug flags or other tricks we can try to help get to the bottom of this?

**Comment by robfarmergt** [comment]
I just saw that beta8 was released yesterday. Anyone think it's worth a shot upgrading my solution and trying to publish?

**Comment by davidebbo** [comment]
They're supposed to have better error handling. We're going to move Kudu to use beta8 by default, but probably won't get to it till early next week.

**Comment by robfarmergt** [comment]
well, I branched my code and upgraded and got everything to compile. Running the solution with IIS express bombs out, with this:

```
'dnx.exe' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_32\mscorlib\v4.0_4.0.0.0__b77a5c561934e089\mscorlib.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'dnx.exe' (CLR v4.0.30319: DefaultDomain): Loaded 'Microsoft.Dnx.Host.Clr'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'dnx.exe' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'dnx.exe' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\Users\rob.farmer\.dnx\runtimes\dnx-clr-win-x86.1.0.0-beta8\bin\Microsoft.Dnx.Host.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'dnx.exe' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'dnx.exe' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'dnx.exe' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\Users\rob.farmer\.dnx\runtimes\dnx-clr-win-x86.1.0.0-beta8\bin\Microsoft.Dnx.Runtime.Abstractions.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'dnx.exe' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'dnx.exe' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\Users\rob.farmer\.dnx\runtimes\dnx-clr-win-x86.1.0.0-beta8\bin\Microsoft.Dnx.Loader.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'dnx.exe' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\Users\rob.farmer\.dnx\runtimes\dnx-clr-win-x86.1.0.0-beta8\bin\Microsoft.Dnx.ApplicationHost.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'dnx.exe' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\Users\rob.farmer\.dnx\runtimes\dnx-clr-win-x86.1.0.0-beta8\bin\Microsoft.Dnx.Compilation.Abstractions.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'dnx.exe' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\Users\rob.farmer\.dnx\runtimes\dnx-clr-win-x86.1.0.0-beta8\bin\Microsoft.Dnx.Runtime.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'dnx.exe' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\Users\rob.farmer\.dnx\runtimes\dnx-clr-win-x86.1.0.0-beta8\bin\Microsoft.Dnx.Compilation.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
**The program '[3168] dnx.exe' has exited with code 1 (0x1).**
The program '[3168] dnx.exe: Program Trace' has exited with code 0 (0x0).
The program '[10232] iisexpress.exe: Program Trace' has exited with code 0 (0x0).
The program '[10232] iisexpress.exe' has exited with code 0 (0x0).
```

**Comment by robfarmergt** [comment]
I was missing a reference to `Microsoft.AspNet.Server.Kestrel": "1.0.0-beta8` in my project.json.

@davidebbo if my references are set to beta8 should that be OK in azure now? Or wait until next week?

**Comment by davidebbo** [comment]
I think that should be fine. Right @ahmelsayed ?

**Comment by ahmelsayed** [comment]
Yes it should be okay, but remember to update, or create if you don't have, your `global.json` to point at beta8. that's how kudu would know that you want beta8. 

```json
{
  "sdk" : {
    "version": "1.0.0-beta8"
  }
}
```

**Comment by robfarmergt** [comment]
Upgraded to beta8 in a new branch and updated the CI. The build failed, but this time it looks like it's some DevExpress dll references that are wrapped.

Example failure:

```
Unable to resolve dependency DevExpress.Charts.v15.1.Core 1.0.0

  Unable to resolve dependency DevExpress.Data.v15.1 1.0.0

  Unable to resolve dependency DevExpress.Office.v15.1.Core 1.0.0

D:\home\site\repository\wrap\ProRata.Reporting.Reports\project.json(11,41): error NU1001: The dependency DevExpress.Charts.v15.1.Core >= 1.0.0-* could not be resolved.
  Unable to resolve dependency DevExpress.PivotGrid.v15.1.Core 1.0.0
D:\home\site\repository\wrap\ProRata.Reporting.Reports\project.json(12,34): error NU1001: The dependency DevExpress.Data.v15.1 >= 1.0.0-* could not be resolved.

D:\home\site\repository\wrap\ProRata.Reporting.Reports\project.json(13,41): error NU1001: The dependency DevExpress.Office.v15.1.Core >= 1.0.0-* could not be resolved.
```

If you're able it's in the original Azure instance with "qa" in the name. If you can't access it I can post the entire output.

**Comment by muratg** [comment]
@robfarmergt Where did you originally use DevExpress. packages from? I don't see them on `nuget.org`.  If you're using a different feed in your local development (perhaps a myget feed), you'll need to specify that in a nuget.config file, and deploy that with your application.

**Comment by robfarmergt** [comment]
@muratg they are local dlls. I have a classic .NET class library project outside of the /src/ folder. The ASP.NET class library project references that class .NET class library.

```
Solution
   Solutions Items
        global.json
    src
        MyApp.Services (reference to MyApp.Reporting)
        MyApp.Web
    MyApp.Reporting (reference to dlls)
```

**Comment by muratg** [comment]
Did you use `dnu wrap` to create a project.json for the `MyApp.Reporting` which then can be referenced from `MyApp.Services`?

**Comment by robfarmergt** [comment]
Yes, in the /wrap/ directory there are diretcories for the MyApp.Reporting project and each of the referenced DLLs.

**Comment by robfarmergt** [comment]
And this all builds locally just fine. Only seems to be an issue now in Azure.

**Comment by muratg** [comment]
I see.  I think you might be hitting [this issue](https://github.com/aspnet/dnx/issues/2954).  This was fixed in the dev branch 3 days ago, but unfortunately signed build is not out yet (on aspnetvnext feed.)  If you're feeling adventurous, you can try the unsigned bits from [this feed](https://www.myget.org/gallery/aspnetcidev), fresh out of dev CI. :)

**Comment by robfarmergt** [comment]
@muratg any idea when the signed build might be released and when it would also be available in Azure?

**Comment by davidebbo** [comment]
We should use a new issue specific to getting beta8 running in Kudu. Right now, we're pretty far away from the original failure that started this thread.

**Comment by robfarmergt** [comment]
@davidebbo do you want me to create a new issue? Any chance issue [DNX 2954](https://github.com/aspnet/dnx/issues/2954) was the original issue with beta7?

**Comment by davidebbo** [comment]
Oh I see. So you mean maybe it's all one issue, but it's becoming easier to diagnose with beta8 due to better error handling? If so, then let's just keep this one.

At this point, we have not tried anything related to beta8 in Kudu, but we're planning to next week. So you're ahead of us :)

**Comment by robfarmergt** [comment]
That's what I'm hoping. When the new release @muratg referred to is available, it might resolve it.

Getting an Azure Windows Server VM setup for hosting in the meantime until we can get to the bottom of this. Have a great weekend!

**Comment by robfarmergt** [comment]
@davidebbo @muratg I removed references in my solution to my csproj, hoping to eliminate the issue with wrapping (https://github.com/aspnet/dnx/issues/2954).

After doing so, I was able to deploy to our Azure Web app successfully! It seems that was the root cause of the issue and in beta7 the error handling just wasn't up to snuff and let us know. With beta8 the problem still exists but we were able to get more info about the problem with better handling.

I do need to figure out how to be able to reference the csproj from my xproj. Expanding on the suggestion of referencing the daily myget feeds, that probably woulnd't work in Azure since I would effectively be using the `rc1` release instead of `beta8` correct? Or is the solution to wait for the `rc1` release?

Also, not sure where the correct forum is to continue this. Seems like it's not an Azure issue.

**Comment by robfarmergt** [comment]
It seems like manually changing the framework in project.json in the wrap folder from net451 to dnx451 will allow me to deploy even though it breaks the build locally. It could be a work around until `rc1`.

**Comment by davidebbo** [comment]
This is what I have in [my test app](https://github.com/davidebbo-test/AspNet5Beta8/blob/56b1b407c4a2dddb3bd8bd62bc4d61432afdf93c/src/AspNet5Beta8/project.json#L37-L40), which was generated by VS.

```json
  "frameworks": {
    "dnx451": { },
    "dnxcore50": { }
  },
```

Is there anything left in this thread that we need to track as a Kudu issue, as opposed to a dnx issue?

**Comment by robfarmergt** [comment]
@davidebbo nothing else here, root cause was the DNX issue.

Huge thank you for all of your help!!!
