### ISSUE TITLE
WebJobs `schedule` should support UTC

### ISSUE THREAD

**Issue by kamranayub** [projectkudu/kudu#1723]
This isn't documented in the wiki but I believe the code is using the local time of the server when scheduling. I could see possible issues if you had multiple instances of a job and if they all weren't in the same region it could cause problems. Also if you switch regions you'd have to switch the schedules.

If it were me I'd have defaulted to UTC since it's safe by default. However, in order to not break everyone, it might be nice to provide an override: `schedule_is_utc`.

**Comment by ahmelsayed** [comment]
The time on all azure machines is in UTC regardless of the region unless you manually change it

**Comment by kamranayub** [comment]
Oh, excellent, nevermind then!
