### ISSUE TITLE
[Asp.Net 5] Unable to change web root other than 'wwwroot'

### ISSUE THREAD

**Issue by kichalla** [projectkudu/kudu#1726]
Not a high pri scenario.
My project.json has a web root called 'wwwrootrenamed' and tried doing the git based push and deployment. I still see 'wwwroot' as the root of the application when i navigate to the url resulting in hostingstart.cshtml being rendered

![image](https://cloud.githubusercontent.com/assets/6559784/10314703/22fae9ae-6c0b-11e5-9913-b5b45aa15a99.png)

![image](https://cloud.githubusercontent.com/assets/6559784/10314713/2ed96598-6c0b-11e5-8bfe-b7363e594c23.png)

![image](https://cloud.githubusercontent.com/assets/6559784/10314721/3c396db4-6c0b-11e5-8c79-3869c80d7d65.png)

project.json

```
{
  "webroot": "wwwrootrenamed",
  "version": "1.0.0-*",

  "dependencies": {
    "Microsoft.AspNet.Diagnostics": "1.0.0-beta8",
```

**Comment by davidebbo** [comment]
Generally, deployment (whether via Kudu or WebDeploy) never affects the webroot folder of the Web App, and it is something that instead gets configured separately (e.g. through the portal or via API).

**Comment by ahmelsayed** [comment]
Maybe since aspnet5 has a standard way of defining the webroot, kudu can drop an xdt that maps the root to the right folder but since that'll conflict with the setting from the API I'm not sure if it's a good idea

**Comment by davidebbo** [comment]
Well, it can be done without conflict by removing it first in the xdt (same as we do for Kudu). But we cannot drop an xdt under `d:\home\site`, as user may have one there already. We would instead need to add one under something like `D:\home\SiteExtensions\DnxPublishing`.

**Comment by jvano** [comment]
Hi

Kudu will continue to run in Azure App Service. However, this repo will no longer be maintained.
If the problem persists and is related to running on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
