### ISSUE TITLE
[ASP.NET 5] Set DNU_PUBLISH_AZURE=1 

### ISSUE THREAD

**Issue by muratg** [projectkudu/kudu#1727]
This is to enable current HttpPlatformHandler work with ASP.NET 5 beta 8.

**Comment by muratg** [comment]
cc @davidfowl @kichalla

**Comment by davidebbo** [comment]
As discussed in https://github.com/aspnet/dnx/pull/2914, this should not actually be needed.

**Comment by jvano** [comment]
Hi

Kudu will continue to run in Azure App Service. However, this repo will no longer be maintained.
If the problem persists and is related to running on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
