### ISSUE TITLE
Submodule update is broken in some scenarios with LibGit2Sharp

### ISSUE THREAD

**Issue by ahmelsayed** [projectkudu/kudu#1732]
This is the offending code  
https://github.com/projectkudu/kudu/blob/88e42b7f30a10afbf2d7d2d06635bce80b89a04f/Kudu.Core/SourceControl/Git/LibGit2SharpRepository.cs#L186-L192 

After a git push/fetch the repo in ends up in this state

```
On branch master
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

        modified:   App_Data/Submodule
```

then we do a checkout for master, this is expected to revert any files that were changed, and unstage the submodule change above.

When using git.exe we do git checkout master --force which does that.

in LibGit2Sharp we do

``` csharp
using (var repo = new LibGit2Sharp.Repository(RepositoryPath))
{
    repo.Checkout(id, new CheckoutOptions { CheckoutModifiers = CheckoutModifiers.Force });
}
```

These 2 works exactly the same as, in that if we had a change to any file it’ll revert that, except for submodule changes. It doesn’t unstage them.
I found that calling reset before the checkout fixes the issue, like this

``` csharp
using (var repo = new LibGit2Sharp.Repository(RepositoryPath))
{
    repo.Reset(ResetMode.Hard, id);
    repo.Checkout(id, new CheckoutOptions { CheckoutModifiers = CheckoutModifiers.Force });
}
```

But git’s checkout and reset are very similar and very confusing so I’m not sure if that will have some unwanted side effect.

I asked on SO (http://stackoverflow.com/questions/33030355/repository-checkout-doesnt-unstage-submodule-changes) in case before I make any changes.
### Workaround:

set an app setting `SCM_USE_LIBGIT2SHARP_REPOSITORY = 0` to disable libgit2sharp

**Comment by ahmelsayed** [comment]
ref: https://github.com/libgit2/libgit2sharp/issues/1206

**Comment by whuhacker** [comment]
Still unfixed? 
I'm running into this problem and it makes me crazy to reset manually again and again during deployment...

**Comment by davidebbo** [comment]
@whuhacker linked libgit2sharp is still active. Just use the suggested workaround above.

**Comment by jvano** [comment]
Hi

Kudu will continue to run in Azure App Service. However, this repo will no longer be maintained.
If the problem persists and is related to running on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
