### ISSUE TITLE
[IGNORE] Continuous Webjob causing multiple jobs to start in same process every 10 minutes

### ISSUE THREAD

**Issue by ashelley** [projectkudu/kudu#1733]
Webjob type: continuous
Deployment method: git
Language: javascript (node.js)
WebJobs SDK: no

Hello I'm having problem with a continuous webjob.  Every 10 minutes a new continuous job is starting without shutting down the old job.

Diagnostics:

- Currently I have a continuous webjob that logs to a database on an interval.  Currently it logs the current date, pid, and unique id per instantiation.

- Every 10 minutes a new worker is added.  I can tell this by looking at the first entry in my database for each unique id.

pid | work start | worker id |
----|-------------|------------|
5080 | 2015-10-09 18:32:47.257 | sI6giaSW0tVwBjCH2KLN2yRXXPD6lOv1 |
5080 | 2015-10-09 18:42:46.870 | W8WKafuAyhxbj-JeDA6v3ifgFHd18sfm |
5080 | 2015-10-09 18:52:47.770 | 0V-3T5CIGdHdNvlQxtrSpoGwEYc9U064 |
5080 | 2015-10-09 19:02:48.943 | -y9nKmtLFyOhud1uGRQol8F8Kdxuh-U |

Note that each worker has the same pid.  Also note that each worker continues to run after the next one starts.  In the above example I have 4 workers running at the same time.

In other words, the above table shows me that I have 4 instances of the same continuous webjob running at the same time instantiated on 10 minute intervals.  

Not shown above is that I can see that each one of these instances continues logging.   This means that the previous worker isn't being shut down.

Expected result:

- Only one continuous worker should be running at any time.
- The continuous worker shouldn't even be shut down due to the "Always on setting" (more below)

Other notes: 

I do have my application set to always on:

![image](https://cloud.githubusercontent.com/assets/3195045/10403845/a1bdca02-6e83-11e5-9fe2-5b0490cd4c60.png)

Logs:

I am not getting any application logs being logged even if I am using:

![image](https://cloud.githubusercontent.com/assets/3195045/10403877/cc97e028-6e83-11e5-9940-b8216f051977.png)

However out of my first 100 lines I can see that that azure is trying to stop and start the job:

```
[10/09/2015 19:19:29 > 13a748: SYS INFO] WebJob is stopping due to website shutting down
[10/09/2015 19:19:29 > 13a748: SYS INFO] Status changed to Stopping
[10/09/2015 19:19:34 > 13a748: SYS INFO] WebJob process was aborted
[10/09/2015 19:19:34 > 13a748: SYS INFO] Status changed to Stopped
[10/09/2015 19:19:42 > 13a748: SYS INFO] Status changed to Starting
[10/09/2015 19:19:42 > 13a748: SYS INFO] Run script 'app.js' with script host - 'NodeScriptHost'
[10/09/2015 19:19:42 > 13a748: SYS INFO] Status changed to Running
```

However, I can tell the process is not being shut down due to the fact that it continues to log to the database at the same time the next worker process is logging to the database.  Also note that the same PID is reported across all instances of the web jobs.

Problems:

1) Only one worker process should be started at the same time.  Before starting a new worker process the original one should be killed.

2) The website is set to always on and should not be telling to webjob to shut down as the site is not shutting down.  I can confirm that the website itself is not shutting down (as per the "always on" setting).  This means that the webjob process isn't correctly honouring this setting.

3) Unrelated: The webjob is not logging to the application logs.

-Adam

**Comment by amitapl** [comment]
Due to the fact the entries have the same process id, means that in fact it is the same process and so the same WebJob running.
Can you share more log lines from the problematic WebJob log?

**Comment by ashelley** [comment]
hello @amitapl ,

I'm working on a simpler example and I created a new new website from scratch to test my simpler test case... Will update shortly...

Unfortunately due to the fact logging isn't working as of right now I can't share any more logs because i don't have any. :(

**Comment by amitapl** [comment]
Note: the WebJob log is not related to the site configuration and it is always enabled.

**Comment by ashelley** [comment]
Hello @amitapl 

Thanks for letting me know... I'm still trying to get to the bottom of where the logs are going: 

The following ui shows some logs:

https://sitename.scm.azurewebsites.net/azurejobs/#/jobs/continuous/jobname

but always ends with the line:

[10/09/2015 21:18:38 > 13a748: WARN] Reached maximum allowed output lines for this run, to see all of the job's logs you can enable website application diagnostics

As per the above setting:

https://cloud.githubusercontent.com/assets/3195045/10403877/cc97e028-6e83-11e5-9940-b8216f051977.png

I believe this should enable "website application diagnostics"

Also there is this file (which is simply the same content as the above mentioned ui shows):

D:\home\data\jobs\continuous\jobname\job_log.txt

According to the documentation from here:

https://github.com/projectkudu/kudu/wiki/Web-jobs#logging

===
Logging

For continuous WebJobs - Console.Out and Console.Error are routed to the "application logs", they will show up as file, blob or table storage depends on your configuration of the application logs (similar to your Website).

Also the first 100 lines in each invocation will also go to the WebJob log file (to ease debugging pain when the WebJob fails at startup) accessible using the Azure portal (but also saved on your site's file system at data/jobs/continuous/jobName).

===

As per my above configuration and as per the documentation I'd expect that my workers would be logging to here somewhere:

D:\home\LogFiles\Application>

And also be showing in VSO

https://sitename.scm.azurewebsites.net/dev/wwwroot/:vs.output

But i don't think it is.   I'm trying to get to the bottom of this but without finding where the logs are being stored it's very hard to tell what's going on. 

-Adam

**Comment by amitapl** [comment]
The logs I refer to are the system lines in the WebJob log which are always enabled, they tells us when a WebJob starts/stops/etc..

You can find them by going to the portal in the WebJobs section.
But they are actually stored at `D:\home\data\jobs\continuous\jobname`
Use the debugconsole at `http://sitename.scm.azurewebsites.net/debugconsole`

**Comment by ashelley** [comment]
Hello @amitapl 

I think i found the problem and indeed you are correct due to the same PID it indicated that the problem was in my code.  I was calling a callback twice on an error handler in javascript.  Sorry for the confusion.  You can mark this as closed or simply delete this issue.

Sorry for wasting your time.

**Comment by amitapl** [comment]
no worries as long as you solved your issue
