### ISSUE TITLE
Show full timestamp for runs when viewing webjob details

### ISSUE THREAD

**Issue by kamranayub** [projectkudu/kudu#1736]
I appreciate having relative time (job ran 11 minutes ago) but when diagnosing specific runs, it's hard to mentally do the math when looking for an absolute time. Can you just prefix the timing information with the absolute timestamp? That'd be helpful.

**Comment by davidebbo** [comment]
Can you clarify which specific UI you are referring to? Is it one of the Azure Portals, the WebJobs dashboard, or the API?

**Comment by kamranayub** [comment]
![image](https://cloud.githubusercontent.com/assets/563819/10417919/429b874a-7012-11e5-804a-6dcf8c27a347.png)

**Comment by davidebbo** [comment]
I see, so that's the WebJobs dashboard. At the API level, the exact time is kept, but in the dashboard, it turns that into a time difference. @mathewc @rustd what's the right repo for dashboard issues?

**Comment by snobu** [comment]
If you dig inside that link there is a timestamp for every output.
![image](https://cloud.githubusercontent.com/assets/6472374/10424071/a27abf42-70d4-11e5-8749-39999a70e9d0.png)

But I agree, it would be useful to have the "4 minutes ago" as a timestamp too, cause it can get confusing really fast.

**Comment by kamranayub** [comment]
Yeah definitely since even if I click it and go back, I have to remember again which one I just clicked which is hard and since that particular job runs every 15 mins there are usually several entries within an hour.

-----Original Message-----

**Comment by mathewc** [comment]
Dashboard issues are in the azure-webjobs-sdk repo.

Sent from my Windows Phone
________________________________

**Comment by davidebbo** [comment]
Full like is https://github.com/Azure/azure-webjobs-sdk. Closing here since it is not part of Kudu.

For what it's worth, the current behavior matches the way https://twitter.com/ displays age of tweets in your timeline. :) Though I guess I probably prefer absolute time myself.
