### ISSUE TITLE
Access commit message in env variable or some other way?

### ISSUE THREAD

**Issue by kamranayub** [projectkudu/kudu#1743]
I'd like to customize my deployment further (I already have a custom script) and would like some advice.

I want to do something where I can bypass my testing for certain non-essential commits--such as changes to static files or configs to fix a broken deploy or bug.

I thought what might be nice is to take a page out of Travis CI's book and use little commands in the commit messages like:

    [notest] fix appSetting in web.config

Then when my deployment script sees "[notest]" in the commit message, it will skip running my tests.

Can I do this using Kudu? Any advice?

**Comment by kamranayub** [comment]
Figured it out.

Here's a test batch script I came up with (run it in a git repo):

```bat
@echo off

IF NOT DEFINED RUN_TESTS (
   SET RUN_TESTS=1
)

call git log -1 --pretty=oneline > commitmessage.txt
SET /p COMMIT_MESSAGE=<commitmessage.txt

echo COMMIT_MESSAGE is %COMMIT_MESSAGE%

IF NOT "x%COMMIT_MESSAGE:[notest]=%"=="x%COMMIT_MESSAGE%" (
   SET RUN_TESTS=0
)

echo RUN_TESTS is defined as
echo %RUN_TESTS%

IF /I "%RUN_TESTS%" NEQ "0" (
   echo Will run tests
) ELSE (
   echo Will not run tests
)
```

And then I just moved the relevant stuff to my Kudu deployment script...

```bat

:: Setup
:: -----


:: At the end
IF NOT DEFINED RUN_TESTS (
   SET RUN_TESTS=1
)

:: build steps, compile solution and tests

:: 4. Run unit tests
call :ExecuteCmd git log -1 --pretty=oneline > commitmessage.txt
SET /p COMMIT_MESSAGE=<commitmessage.txt

echo Latest commit message is "%COMMIT_MESSAGE%"

IF NOT "x%COMMIT_MESSAGE:[notest]=%"=="x%COMMIT_MESSAGE%" (
   SET RUN_TESTS=0
)

IF /I "%RUN_TESTS%" NEQ "0" (
	echo Running unit tests
	:: call msbuild, etc.
	IF !ERRORLEVEL! NEQ 0 goto error
) ELSE (
	echo Not running unit tests because [notest] was present in commit message
)

**Comment by davidebbo** [comment]
Note that you can use %SCM_COMMIT_ID% to get the id.

**Comment by kamranayub** [comment]
In that case, I updated the code to be:

    git log %SCM_COMMIT_ID% --pretty=%s > commitmessage.txt

**Comment by davidebbo** [comment]
Yep, a bit cleaner :)
