### ISSUE TITLE
HangProcessTest not reliable on CI

### ISSUE THREAD

**Issue by suwatch** [projectkudu/kudu#1749]
```
2015-10-16T19:17:42Z Run failed with exception
    Xunit.Sdk.FalseException: SimpleSleep should have been terminated!
    Expected: False
    Actual:   True
```

The fix would be to make get process tree more reliable.   BTW, this is not the issue on Azure env.

**Comment by jvano** [comment]
Hi

Kudu will continue to run in Azure App Service. However, this repo will no longer be maintained.
If the problem persists and is related to running on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
