### ISSUE TITLE
Web Hooks of Visual Studio Online is doesn't work with Kudu deployment trigger in Azure Websites

### ISSUE THREAD

**Issue by denisyfrolov** [projectkudu/kudu#1750]
Web Hooks of Visual Studio Online has fields below:

Content:
{
  "subscriptionId": "####",
  "notificationId": 28,
  "id": "#####",
  "eventType": "git.push",
  "publisherId": "tfs",
  "message": null,
  "detailedMessage": null,
  "resource": null,
  "createdDate": "2015-10-17T16:49:57.5382357Z",
  "resourceVersion": null
}

https://www.visualstudio.com/get-started/webhooks-and-vso-vs

And is no way to change it manually. But Kudu in /deploy triger await the url field in additional. So if I requesting the deploy from VSO to Azure Websites I receive "Internal Server Error": "Value cannot be null. Parameter name: uriString".

**Comment by davidebbo** [comment]
Not sure I completely understand the question, but please see [this page](https://github.com/projectkudu/kudu/wiki/VSO-vs-Kudu-deployments). Bottom line is that if you are deploying using VSO, you are not using Kudu, so nothing related to Kudu will apply to your scenario.

**Comment by denisyfrolov** [comment]
Yes, if you deploy the Visual Studio project. Like a C#, VB.NET or other .NET projects. But if you store static or PHP sites in VSO repository you can not use VSO build. For this case VSO have Web Hooks, which can request deploy trigers like one in Kudo. So the Kudo's triger on Azure Websites is not work properly with VSO Web Hooks. Request of the /deploy api returning Internal Serever Error (Error 500). You can check out error here: https://YOURACCOUNT.visualstudio.com/DefaultCollection/YOURPROJECT/_admin/_servicehooks

Trace files:

<step title="Incoming Request" date="2015-10-17T12:52:22.780" instance="16938d" url="/deploy" method="POST" type="request" pid="18344,2,98" Connection="Keep-Alive" Content-Length="1795" Content-Type="application/json; charset=utf-8" Expect="100-continue" Host="onetile.scm.azurewebsites.net" X-SITE-DEPLOYMENT-ID="onetile" >
  <step title="Cleanup Xml Logs" date="2015-10-17T12:52:22.796" />
  <step title="FetchHandler" date="2015-10-17T12:52:22.812" />
  <step title="Error occurred" date="2015-10-17T12:52:22.827" type="error" text="Value cannot be null.
Parameter name: uriString" stackTrace="   at System.Uri..ctor(String uriString)
   at Kudu.Services.ServiceHookHandlers.VSOHandler.GetDeploymentInfo(HttpRequestBase request, JObject payload, String targetBranch)
   at Kudu.Services.ServiceHookHandlers.VSOHandler.TryParseDeploymentInfo(HttpRequestBase request, JObject payload, String targetBranch, DeploymentInfo&amp; deploymentInfo)
   at Kudu.Services.FetchHandler.GetRepositoryInfo(HttpRequestBase request, JObject payload, String targetBranch, DeploymentInfo&amp; info)
   at Kudu.Services.FetchHandler.&lt;ProcessRequestAsync&gt;d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.TaskAsyncHelper.EndTask(IAsyncResult ar)
   at System.Web.HttpTaskAsyncHandler.System.Web.IHttpAsyncHandler.EndProcessRequest(IAsyncResult result)
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean&amp; completedSynchronously)" />
  <step title="Outgoing response" date="2015-10-17T12:52:22.843" type="response" statusCode="500" statusText="Internal Server Error" Cache-Control="private" X-AspNet-Version="4.0.30319" Content-Type="text/html; charset=utf-8" />
</step>

**Comment by denisyfrolov** [comment]
I have the trace file from Azure Website, but can't attach it here. So I put here main part:

title="Error occurred" date="2015-10-17T12:52:22.827" type="error" text="Value cannot be null.
Parameter name: uriString" stackTrace="   at System.Uri..ctor(String uriString)
   at Kudu.Services.ServiceHookHandlers.VSOHandler.GetDeploymentInfo(HttpRequestBase request, JObject payload, String targetBranch)

**Comment by davidebbo** [comment]
Oh I see, you're trying to use the new `VSOHandler`. @suwatch @shrimpy is this even supposed to work today? I'm guessing it's meant for a payload that's different. Here, base on the error, it seems that `RepoUrl` is not set.

**Comment by denisyfrolov** [comment]
I checked RepoUrl var in Azure Resource Explorer and it is set:

{
  "id": "/subscriptions/###/resourceGroups/###/providers/Microsoft.Web/sites/###/sourcecontrols",
  "name": "####",
  "type": "Microsoft.Web/sites/sourcecontrols",
  "kind": null,
  "location": "West Europe",
  "tags": {
    "hidden-related:/subscriptions/###/resourcegroups/###/providers/Microsoft.Web/serverfarms/###": "empty"
  },
  "plan": null,
  "properties": {
    "repoUrl": "https://logins:password@denisyfrolov.visualstudio.com/DefaultCollection/_git/PROJECT",
    "branch": "master",
    "isManualIntegration": true,
    "deploymentRollbackEnabled": false,
    "isMercurial": false
  }
}

**Comment by denisyfrolov** [comment]
In fact VSO is send the url field, but not in root of JSON document. It send the url of repository in two levels lower under resource -> repository section of JSON document as an two levels of a nested array:

Example:
<pre>
{
  "subscriptionId": "###",
  "notificationId": 30,
  "id": "###",
  "eventType": "git.push",
  "publisherId": "tfs",
  "message": {
    "text": "Jamal Hartnett pushed updates to branch master of repository Fabrikam-Fiber-Git."
  },
  "detailedMessage": {
    "text": "Jamal Hartnett pushed 1 commit to branch master of repository Fabrikam-Fiber-Git.\n - Fixed bug in web.config file 33b55f7c"
  },
  "resource": {
    "commits": [
      {
        "commitId": "33b55f7cb7e7e245323987634f960cf4a6e6bc74",
        "author": {
          "name": "Jamal Hartnett",
          "email": "fabrikamfiber4@hotmail.com",
          "date": "2015-02-25T19:01:00Z"
        },
        "committer": {
          "name": "Jamal Hartnett",
          "email": "fabrikamfiber4@hotmail.com",
          "date": "2015-02-25T19:01:00Z"
        },
        "comment": "Fixed bug in web.config file",
        "url": "https://fabrikam-fiber-inc.visualstudio.com/DefaultCollection/_git/Fabrikam-Fiber-Git/commit/33b55f7cb7e7e245323987634f960cf4a6e6bc74"
      }
    ],
    "refUpdates": [
      {
        "name": "refs/heads/master",
        "oldObjectId": "aad331d8d3b131fa9ae03cf5e53965b51942618a",
        "newObjectId": "33b55f7cb7e7e245323987634f960cf4a6e6bc74"
      }
    ],
    "repository": {
      "id": "278d5cd2-584d-4b63-824a-2ba458937249",
      "name": "Fabrikam-Fiber-Git",
      "url": "https://fabrikam-fiber-inc.visualstudio.com/DefaultCollection/_apis/git/repositories/278d5cd2-584d-4b63-824a-2ba458937249",
      "project": {
        "id": "6ce954b1-ce1f-45d1-b94d-e6bf2464ba2c",
        "name": "Fabrikam-Fiber-Git",
        "url": "https://fabrikam-fiber-inc.visualstudio.com/DefaultCollection/_apis/projects/6ce954b1-ce1f-45d1-b94d-e6bf2464ba2c",
        "state": "wellFormed"
      },
      "defaultBranch": "refs/heads/master",
      "remoteUrl": "https://fabrikam-fiber-inc.visualstudio.com/DefaultCollection/_git/Fabrikam-Fiber-Git"
    },
    "pushedBy": {
      "id": "00067FFED5C7AF52@Live.com",
      "displayName": "Jamal Hartnett",
      "uniqueName": "Windows Live ID\\fabrikamfiber4@hotmail.com"
    },
    "pushId": 14,
    "date": "2014-05-02T19:17:13.3309587Z",
    "url": "https://fabrikam-fiber-inc.visualstudio.com/DefaultCollection/_apis/git/repositories/278d5cd2-584d-4b63-824a-2ba458937249/pushes/14"
  },
  "createdDate": "2015-10-18T12:23:14.965571Z"
}
</pre>

**Comment by davidebbo** [comment]
Note that one key aspect of making this work is authentication. i.e. Kudu needs to be able to access the VSO repo in order to pull from it. Today, this is not supported, but it is work in progress, and hopefully will be available in the next couple of months.

**Comment by shrimpy** [comment]
We haven`t official support VSO yet. At the time we implement VSOHandler, webhook payload from VSO is static other than a short-ive [session token](https://github.com/projectkudu/kudu/blob/master/Kudu.Services/ServiceHookHandlers/VSOHandler.cs#L41), which allow Kudu to access user repo. And I have not tried since then. 

Things seems have been changed a lot, from the payload @denisyfrolov posted, i don`t see any session token. 

As @davidebbo mention there is work in progress, we will adjust our code to consume any new changes in the short coming future.

**Comment by denisyfrolov** [comment]
@davidebbo @shrimpy is no any problems with authentication and access to the VSO repo from the Kudu and Azure Websites, URL of repo contains all required data as login and password. The Kudu works fine If I manually click the Sync button in the Continuous deployment section on the Azure Portal. Any new commits from VSO successfully deployed.

I got it, the work in progress. I really hope it is will work fine in short time, thank you! I just want to you understand the issue, is no problem with authentication and session token, The Kudu works fine If I manually click the Sync button in the Continuous deployment section on the Azure Portal. Any new commits from VSO successfully deployed! The issue is WebHook Deploy api only!

**Comment by shrimpy** [comment]
@denisyfrolov 

When you click on the "Sync" button, Azure Web App actually trigger a WebHook notification, see [Test hook section](https://github.com/projectkudu/ARMClient/wiki/Vso-WebHook-Apis). 

I suspect the WebHook payload from "Test WebHook" and when you do a "Push" might be different. Is it possible for you to capture both payload? so that we can compare?

**Comment by denisyfrolov** [comment]
Yes I know, that Sync button is actually trigger to the same WebHook. That's why I say that Kudu works fine with repo in VSO, the issue happens only with request to WebHook from VSO. 

Of course I can, the full PUSH payload below:

<pre>
stdClass Object
(
    [subscriptionId] => ########-3d81-####-be18-####36c4afdc
    [notificationId] => 55
    [id] => ########-8e1f-####-b67e-####e7e9b170
    [eventType] => git.push
    [publisherId] => tfs
    [message] => stdClass Object
        (
            [text] => Denis Frolov pushed updates to branch master of PROJECT
(https://denisyfrolov.visualstudio.com/DefaultCollection/_git/PROJECT/#version=GBmaster)
            [html] => Denis Frolov pushed updates to branch <a href="https://denisyfrolov.visualstudio.com/DefaultCollection/_git/PROJECT/#version=GBmaster">master</a> of <a href="https://denisyfrolov.visualstudio.com/DefaultCollection/_git/PROJECT/">PROJECT</a>
            [markdown] => Denis Frolov pushed updates to branch [master](https://denisyfrolov.visualstudio.com/DefaultCollection/_git/PROJECT/#version=GBmaster) of [PROJECT](https://denisyfrolov.visualstudio.com/DefaultCollection/_git/PROJECT/)
        )

    [detailedMessage] => stdClass Object
        (
            [text] => Denis Frolov pushed 1 commit to branch master of PROJECT
 - Test of Continuous Deployment 6b594fbc (https://denisyfrolov.visualstudio.com/DefaultCollection/_git/PROJECT/commit/6b594fbc892118b1c3d458249fa1c3110380618f)
            [html] => Denis Frolov pushed 1 commit to branch <a href="https://denisyfrolov.visualstudio.com/DefaultCollection/_git/PROJECT/#version=GBmaster">master</a> of <a href="https://denisyfrolov.visualstudio.com/DefaultCollection/_git/PROJECT/">PROJECT</a>
<ul>
<li>Test of Continuous Deployment <a href="https://denisyfrolov.visualstudio.com/DefaultCollection/_git/PROJECT/commit/6b594fbc892118b1c3d458249fa1c3110380618f">6b594fbc</a></li>
</ul>
            [markdown] => Denis Frolov pushed 1 commit to branch [master](https://denisyfrolov.visualstudio.com/DefaultCollection/_git/PROJECT/#version=GBmaster) of [PROJECT](https://denisyfrolov.visualstudio.com/DefaultCollection/_git/PROJECT/)
* Test of Continuous Deployment [6b594fbc](https://denisyfrolov.visualstudio.com/DefaultCollection/_git/PROJECT/commit/6b594fbc892118b1c3d458249fa1c3110380618f)
        )

    [resource] => stdClass Object
        (
            [commits] => Array
                (
                    [0] => stdClass Object
                        (
                            [commitId] => 6b594fbc892118b1c3d458249fa1c3110380618f
                            [author] => stdClass Object
                                (
                                    [name] => Denis Frolov
                                    [email] => denisyfrolov@###.com
                                    [date] => 2015-10-19T20:51:40Z
                                )

                            [committer] => stdClass Object
                                (
                                    [name] => Denis Frolov
                                    [email] => denisyfrolov@###.com
                                    [date] => 2015-10-19T20:51:40Z
                                )

                            [comment] => Test of Continuous Deployment
                            [url] => https://denisyfrolov.visualstudio.com/DefaultCollection/_apis/git/repositories/########-7ba3-####-8c51-####9019219b/commits/6b594fbc892118b1c3d458249fa1c3110380618f
                        )

                )

            [refUpdates] => Array
                (
                    [0] => stdClass Object
                        (
                            [name] => refs/heads/master
                            [oldObjectId] => 76cd2432fbfa88bd5ec6efa2e9181b8d115be0a8
                            [newObjectId] => 6b594fbc892118b1c3d458249fa1c3110380618f
                        )

                )

            [repository] => stdClass Object
                (
                    [id] => ########-7ba3-####-8c51-####9019219b
                    [name] => PROJECT
                    [url] => https://denisyfrolov.visualstudio.com/DefaultCollection/_apis/git/repositories/########-7ba3-####-8c51-####9019219b
                    [project] => stdClass Object
                        (
                            [id] => ########-4e3f-####-b1c3-####cebd5fd4
                            [name] => PROJECT
                            [url] => https://denisyfrolov.visualstudio.com/DefaultCollection/_apis/projects/########-4e3f-####-b1c3-####cebd5fd4
                            [state] => wellFormed
                        )

                    [defaultBranch] => refs/heads/master
                    [remoteUrl] => https://denisyfrolov.visualstudio.com/DefaultCollection/_git/PROJECT
                )

            [pushedBy] => stdClass Object
                (
                    [id] => ########-9ff0-####-b86a-####0312861c
                    [displayName] => Denis Frolov
                    [uniqueName] => denisyfrolov@###.com
                    [url] => https://denisyfrolov.vssps.visualstudio.com/_apis/Identities/########-9ff0-####-b86a-####0312861c
                    [imageUrl] => https://denisyfrolov.visualstudio.com/DefaultCollection/_api/_common/identityImage?id=########-9ff0-####-b86a-####0312861c
                )

            [pushId] => 20
            [date] => 2015-10-19T20:51:50.9236287Z
            [url] => https://denisyfrolov.visualstudio.com/DefaultCollection/_apis/git/repositories/########-7ba3-####-8c51-####9019219b/pushes/20
            [_links] => stdClass Object
                (
                    [self] => stdClass Object
                        (
                            [href] => https://denisyfrolov.visualstudio.com/DefaultCollection/_apis/git/repositories/########-7ba3-####-8c51-####9019219b/pushes/20
                        )

                    [repository] => stdClass Object
                        (
                            [href] => https://denisyfrolov.visualstudio.com/DefaultCollection/_apis/git/repositories/########-7ba3-####-8c51-####9019219b
                        )

                    [commits] => stdClass Object
                        (
                            [href] => https://denisyfrolov.visualstudio.com/DefaultCollection/_apis/git/repositories/########-7ba3-####-8c51-####9019219b/pushes/20/commits
                        )

                    [pusher] => stdClass Object
                        (
                            [href] => https://denisyfrolov.vssps.visualstudio.com/_apis/Identities/########-9ff0-####-b86a-####0312861c
                        )

                    [refs] => stdClass Object
                        (
                            [href] => https://denisyfrolov.visualstudio.com/DefaultCollection/_apis/git/repositories/########-7ba3-####-8c51-####9019219b/refs
                        )

                )

        )

    [resourceVersion] => 1.0
    [resourceContainers] => stdClass Object
        (
            [collection] => stdClass Object
                (
                    [id] => ########-6f49-####-9b7f-####e9a93aa7
                )

            [account] => stdClass Object
                (
                    [id] => ########-ae32-####-b21b-####f8843b94
                )

            [project] => stdClass Object
                (
                    [id] => ########-4e3f-####-b1c3-####cebd5fd4
                )

        )

    [createdDate] => 2015-10-19T20:51:56.1492376Z
)

</pre>

**Comment by shrimpy** [comment]
@denisyfrolov 

alright, since you do most of the configuration manually, and you aware that we haven't officially support VSO, let`s see if we can enable you with some work-around.

About the null-ref you are experiencing, it is from [this line](https://github.com/projectkudu/kudu/blob/master/Kudu.Services/ServiceHookHandlers/VSOHandler.cs#L48), where Kudu store user`s repository url during setup (as i mention earlier, TestWebhook payload is static, only useful data is the short-live session token). Since there is no setup for you (you did it manually, there is no repo url). So you have to manually create it.

Please go to your SCM site, go to debug console and navigate to 
````
D:\home\site\deployments
````

see if there is a "settings.xml" there?

if yes, you can see the file:
   open it and see if you have "RepoUrl" there, if not, add it

if no, no such file:
    let`s create one and paste below content

````
<?xml version="1.0" encoding="utf-8"?>

<settings>
  <deployment>
    <add key="branch" value="[your branch here]" />
    <add key="RepoUrl" value="[your repo url here with basic auth]" />
  </deployment>
</settings>

````

this should get you moving, let me know if you hit other issue along the way

**Comment by denisyfrolov** [comment]
Yea, this solution do moving process, thanks. I added the RepoUrl key to my settings.xml and now I get another Internal Server Error at the same function but in another line:

<pre>
<step title="Error occurred" date="2015-10-20T11:18:19.899" type="error" text="Object reference not set to an instance of an object." stackTrace="   at Kudu.Services.ServiceHookHandlers.VSOHandler.GetDeploymentInfo(HttpRequestBase request, JObject payload, String targetBranch)
   at Kudu.Services.ServiceHookHandlers.VSOHandler.TryParseDeploymentInfo(HttpRequestBase request, JObject payload, String targetBranch, DeploymentInfo&amp; deploymentInfo)
   at Kudu.Services.FetchHandler.GetRepositoryInfo(HttpRequestBase request, JObject payload, String targetBranch, DeploymentInfo&amp; info)
   at Kudu.Services.FetchHandler.&lt;ProcessRequestAsync&gt;d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
</pre>

**Comment by suwatch** [comment]
I think you may run into [seesion token](https://github.com/projectkudu/kudu/blob/master/Kudu.Services/ServiceHookHandlers/VSOHandler.cs#L51) is null from VSO hook payload.  Note that one would need to add VSO hook in a specific way (intended for Azure the moment) in order to have sessionToken flow with the payload.  Unfortunately, there is no UI to achieve that.

You can look at the VSO APis section of the [wiki](https://github.com/projectKudu/ARMClient/wiki).  There is a sample how one would set it up manually.   If you don't see your VSO accounts, you may need to go to preview portal to link the VSO account with your Azure subscription.

**Comment by davidebbo** [comment]
I think the point is that he doesn't want to use the session token since the creds are embedded in the URL. Basically, we'd want the VSO handler to gracefully degrade to work the same as the external repo case (i.e. what happens when you click the sync button). It may be as simple as skipping the line you point to is there is no session token, and instead just using the url as is.

**Comment by shrimpy** [comment]
@denisyfrolov 

i have a fix for your latest error. PR https://github.com/projectkudu/kudu/pull/1756

if you can share your site name or tell us your site name [in-directly](https://github.com/projectkudu/kudu/wiki/Reporting-your-site-name-without-posting-it-publicly), I can patch your site to unblock you right away.

**Comment by denisyfrolov** [comment]
@shrimpy thanks a lot, lets try do that on test the site **onetile.azurewebsites.net**

**Comment by denisyfrolov** [comment]
@davidebbo @suwatch thanks for the tip, I didn't know about ARMClient, it is great to have ability to manualy setup webhooks on VSO and I will try to use it for this case. But of course the best way is work with VSO as simple as any other external hosted repos. Thanks for the help again!

**Comment by denisyfrolov** [comment]
@suwatch I try use ARMClient for VSO, but any request from ARMClient to VSO like <code>ARMClient.exe get "https://app.vssps.visualstudio.com/_apis/profile/profiles/me?api-version=1.0"</code> return the authentication page. In some time all requests to SCM like: <code>ARMClient.exe get "/subscriptions?api-version=2014-04-01"</code> is successful and return JSON.

ARMClient is authenticated in Azure through <code>ARMClient.exe login</code> and my VSO account is linked to my Azure account. Is this bug or I doing soething wrong? Maybe better is forwarding this question to ARMClient Issues?

**Comment by shrimpy** [comment]
@denisyfrolov just patched your site. can you give it a try?

**Comment by denisyfrolov** [comment]
@shrimpy just tried, it is work fine finally! However the Continuous deployment settings is missing and first try is return 403, but I re setup the connection to VSO as external repo and everything works fine now. Thanks! Is this patch will applying to all new sites? Or old sites will patched too in some time?

**Comment by davidebbo** [comment]
It will apply to all sites once we redeploy the next  build of Kudu. Once we do that, you'll want to delete your `D:\home\SiteExtensions\Kudu` folder to move away from the private build.

**Comment by denisyfrolov** [comment]
@davidebbo OK, it is great. Thank to all you guys again.

**Comment by suwatch** [comment]
@denisyfrolov I moved the discussion for issue VSO ARMClient to https://github.com/projectkudu/ARMClient/issues/23.  Let discuss it there.

**Comment by shrimpy** [comment]
Change has been published to all sites. Closing this issue now.
