### ISSUE TITLE
Wiki mobile services typo

### ISSUE THREAD

**Issue by devlead** [projectkudu/kudu#1751]
Unfortunately you can't send a PR for wikis easily, so I'll raise an issue. 

I believe there's a mobile services typo in the [Accessing-the-kudu-service.md](https://github.com/projectkudu/kudu/wiki/Accessing-the-kudu-service)

Made a fork with correction [here](https://github.com/devlead/kudu_wiki/commit/223f7a64806032695ffdc29d0131bfe6c2013b98)

**Comment by davidebbo** [comment]
Merged, thanks. Yeah, the wiki workflow sucks.

**Comment by devlead** [comment]
@davidebbo superb, yeah a shame you can't send Pr's/fork easily.
Thanks for a great service with Kudu! :+1:
