### ISSUE TITLE
DNX beta 8

### ISSUE THREAD

**Issue by ealsur** [projectkudu/kudu#1752]
When deploying ASPNet DNX Beta8 web apps that have no web.config, the auto-generated web.config by the deployment script should be equal to the one declared by the DNX team: http://blogs.msdn.com/b/webdev/archive/2015/10/15/announcing-availability-of-asp-net-5-beta8.aspx

```xml
<configuration>
  <system.webServer>
    <handlers>
      <add
        name="httpPlatformHandler"
        path="*"
        verb="*"
        modules="httpPlatformHandler"
        resourceType="Unspecified"/>
    </handlers>
    <httpPlatform
      processPath="%DNX_PATH%"
      arguments="%DNX_ARGS%"
      stdoutLogEnabled="false"
      startupTimeLimit="3600"/>
  </system.webServer>
</configuration>
```

Current autogenerated web.config:

```xml
<configuration>
  <system.webServer>
    <handlers>
      <add name="httpplatformhandler" path="*" verb="*" modules="httpPlatformHandler" resourceType="Unspecified" />
    </handlers>
    <httpPlatform processPath="%home%\site\approot\web.cmd" arguments="" stdoutLogEnabled="true" stdoutLogFile="\\?\%home%\LogFiles\stdout.log"></httpPlatform>
  </system.webServer>
</configuration>
```

**Comment by ahmelsayed** [comment]
The `web.config` that's generated as a part of the deployment is actually generated by dnx, not by the deployment script. `dnu publish` would generate that. The only difference is in replacing the `%DNX_PATH%` and `%DNX_ARGS%` envvars with the actual values. Note that these variables won't have a set value on Azure anyway,

**Comment by ealsur** [comment]
Thanks @ahmelsayed for clarifying! :)

**Comment by ahmelsayed** [comment]
actually it's interesting because the one generated by `dnx` is missing `startupTimeLimit="3600"` which seems to be required. If you have one in your repo, I think dnx will merge it and do the right thing. I think it's a bug in dnx that they aren't adding that to the generated web.config

**Comment by ealsur** [comment]
@ahmelsayed You think I should file the issue to DNX?

**Comment by davidebbo** [comment]
@ealsur I think so. The default is just 10 seconds, and with the kind of load time we're seeing, this is far to short.
