### ISSUE TITLE
Continuous Deployment integration fails to pull

### ISSUE THREAD

**Issue by ealsur** [projectkudu/kudu#1755]
When creating a Continuous Deployment setting hooked to a Mercurial repo (BitBucket), the hg pull command is not adding " to the branch name, if the branch name has spaces, the pull command fails:

![webapps](https://cloud.githubusercontent.com/assets/1633401/10609758/7730d3ec-771b-11e5-8671-8f1456494c39.PNG)

If the branch has no spaces, it works flawlessly.

**Comment by snobu** [comment]
@ahmelsayed @pranavkm Is this it?
https://github.com/projectkudu/kudu/blob/master/Kudu.Core/SourceControl/Hg/HgRepository.cs#L232
I can have a look at it if i'm on the right track here.

**Comment by ealsur** [comment]
@snobu Sounds like it might be it

**Comment by davidebbo** [comment]
Yep, that's probably it, though conceivably there could be additional places in the code that don't expect that. I've never seen a branch name with spaces. I don't think it's even valid in git, though it might be in hg.

**Comment by ealsur** [comment]
@davidebbo Yep, it's valid in HG, we got several branches on multiple repos using spaces, we don't usually apply Continuous Deployment on those branches (often is on the master/default) but today we bumped on this while trying to do it on one with spaces.

**Comment by snobu** [comment]
Let me do some tests and see what happens with quotes vs without.

**Comment by snobu** [comment]
![image](https://cloud.githubusercontent.com/assets/6472374/10634812/c35dccb6-77fc-11e5-8837-12b4a4312ba3.png)

I swear it wasn't me!

![image](https://cloud.githubusercontent.com/assets/6472374/10634859/15de7332-77fd-11e5-8880-01b2f787b1e0.png)

Waiting for BitBucket to be able to test some changes...

**Comment by ealsur** [comment]
@snobu They've been having problems the last week, looks like it's gonna be a fun day (all our Azure Web Apps use BitBucket)

**Comment by snobu** [comment]
![redirect](https://cloud.githubusercontent.com/assets/6472374/10640826/2d2c0dfc-781f-11e5-8eb5-fb3dcf217c8c.PNG)

@davidebbo @ahmelsayed 
Is this a regression in Ibiza i'm looking at? I don't think it has anything to do with Kudu.
It's the same in multiple browsers, production portal (manage.azurewebsites.net) OAuths just fine.

**Comment by snobu** [comment]
I'm able to reproduce,

```cmd
hg pull: invalid arguments\n\r\nD:\Program Files (x86)\Mercurial\hg.exe
        pull https://bitbucket.org/snobu/hgrepo --branch white space here --noninteractive
```

Wrapping `{1}` in double quotes does work but breaks unit tests.
`"pull {0} --branch \"{1}\" --noninteractive", remote, branchName, PathUtility.ResolveSSHPath());`
I'll look into that first thing tomorrow.

**Comment by ahmelsayed** [comment]
I'm guessing your portal is redirecting to ms.portal.azure.com while bitbucket expect the url you're coming from to be portal.azure.com. It's in inconvenient for us inside Microsoft who get redirected to the dog food endpoint at ms.portal.azure.com, but it shouldn't affect customers. There is a query string that you can add to the normal portal to prevent the redirect but I don't remember it. @Tuesdaysgreen would know. I'll ask him as soon as I get in the office.

**Comment by snobu** [comment]
We should probably report this to BitBucket, they don't seem to be aware or well documented on the fact that their CLI can do whitespace in branch names but the WebUI won't.

![bitbucket_whitespace](https://cloud.githubusercontent.com/assets/6472374/10641294/7f27a05a-77cd-11e5-830f-6e98e5c5c485.PNG)

![bb_website_wrong](https://cloud.githubusercontent.com/assets/6472374/10641298/7f2b842c-77cd-11e5-84a8-e4da22f1730b.png)

Their website is wrong:
![bb_website_is_wrong_cmd](https://cloud.githubusercontent.com/assets/6472374/10641297/7f2aff70-77cd-11e5-9bfa-1beeae0a6e19.png)


Creating a branch with whitespace from hg CLI does work, and i can push it with great success.
![hg_cmdline_whitespace](https://cloud.githubusercontent.com/assets/6472374/10641296/7f2ab47a-77cd-11e5-8115-303929b1839c.PNG)

One more thing to note, SourceTree replaces whitespace with underscores (i typed in `some white space` and here's what i got:

![sourcetree_whitespace](https://cloud.githubusercontent.com/assets/6472374/10641295/7f2a8662-77cd-11e5-9889-cdb3e35dc43a.PNG)

**Comment by snobu** [comment]
Thanks @ahmelsayed, totally overlooked the `ms.` thing.

**Comment by ahmelsayed** [comment]
@snobu the query string is `/?feature.customportal=false`

**Comment by snobu** [comment]
Thank you for that. It will come in handy a lot.

**Comment by snobu** [comment]
I have something working, @ealsur, please e-mail me a
![email](https://cloud.githubusercontent.com/assets/6472374/10662926/53068ee8-78c0-11e5-9918-fe962ecfe9ac.jpg)

and i'll send you a set of credentials to a Kudu site with the new build for testing.

**Comment by ealsur** [comment]
@snobu whats your bitbucket user? so we give you permissions

**Comment by snobu** [comment]
https://bitbucket.org/snobu/

**Comment by snobu** [comment]
![image](https://cloud.githubusercontent.com/assets/6472374/10666324/90642e58-78d9-11e5-9f90-aa3213cae9ae.png)

I really feel the pain there. Maybe BitBucket should seriously consider running on Azure?

**Comment by snobu** [comment]
@ealsur Did you manage to set up permissions? I didn't get any notification from BitBucket.

**Comment by ealsur** [comment]
@snobu Sorry, I have been ill :(

Added you to a repo called "kudutest" that has 1 branch called "default with whitespaces".

**Comment by snobu** [comment]
Got it. Will test tomorrow and submit a patch to Kudu if all goes well. Get well soon, that goes for me too - i have a nasty cold which doesn't seem to respond to `killall -9 flu`.

**Comment by ealsur** [comment]
@snobu Hahaha hopefully we'll get a push from the health service and a merge with the healthy branch

**Comment by davidebbo** [comment]
Let's try to work with public repos here, especially for something as simple as a test repo with a branch that has spaces.

**Comment by ealsur** [comment]
@davidebbo Done, made public on: https://bitbucket.org/autocosmos/kudutest

**Comment by davidebbo** [comment]
Thanks! I also added a branch to our existing test repo: https://bitbucket.org/kudutest/hellomercurial/branch/branch%20with%20spaces. So it should be a matter of changing [this line](https://github.com/projectkudu/kudu/blob/ffb3f90df1346d52d00d52fe6da2633935d22afb/Kudu.FunctionalTests/HgRepositoryFacts.cs#L82) to us `"branch with spaces"` instead of `"test"` to get test coverage.

**Comment by snobu** [comment]
I'll have a PR ready by tomorrow, with the white space test in.

**Comment by davidebbo** [comment]
@snobu awesome! :)
