### ISSUE TITLE
WEBSITE_START_SCM_ON_SITE_CREATION setting in kudu or Azure?

### ISSUE THREAD

**Issue by sitereactor** [projectkudu/kudu#1758]
In the Wiki section on [Configuration settings](https://github.com/projectkudu/kudu/wiki/Configurable-settings#pre-start-the-scm-site-as-part-of-site-creation-needs-to-be-set-in-the-site-creation-call) the setting `WEBSITE_START_SCM_ON_SITE_CREATION` is mentioned as "Pre-start the SCM site as part of site creation (needs to be set in the site creation call)". But the setting is not actually in the Kudu codebase as far as I can tell. 

Is this setting Azure specific?

**Comment by davidebbo** [comment]
Indeed, all settings that start with `WEBSITE_` are part of the Azure Web App platform and not part of Kudu itself. Kudu settings start with `SCM_`.
