### ISSUE TITLE
Any chance of a new release

### ISSUE THREAD

**Issue by mikkelhm** [projectkudu/kudu#1760]
Hi Kudu-team

Is there any chance of an "official" release of kudu in the near future? 
We are in the process of upgrading our current installation, and would like to have a official release to use.
Ive managed to just use a build off the local machine which will suffice for our development environment.

Thanks in advance, and thanks for doing an amazing work with the Kudu project.

**Comment by davidebbo** [comment]
Here you go: https://github.com/projectkudu/kudu/releases/tag/S48

**Comment by mikkelhm** [comment]
This is awesome, h5yr

**Comment by nul800sebastiaan** [comment]
:+1:

**Comment by sitereactor** [comment]
:fireworks:

**Comment by hartvig** [comment]
😍

**Comment by amitapl** [comment]
:100:

**Comment by davidebbo** [comment]
Wow, I didn't realize so many people wanted this. :)

We don't generally make those because we don't need them for Azure, but don't be shy about asking if you need a new one in the future. It's easy enough to do.
