### ISSUE TITLE
WebJobs RequestPassThrough "forbidden by access permissions" exception

### ISSUE THREAD

**Issue by mejje** [projectkudu/kudu#1762]
404 response with exception when posting to `/api/continuouswebjobs/{jobname}/passthrough/{class}/{function}` using the WebHookTrigger extension on a B2 instance.

`An attempt was made to access a socket in a way forbidden by its access permissions 127.0.0.1:49663`

 ```json
{
    "Message": "An error has occurred.",
    "ExceptionMessage": "An error occurred while sending the request.",
    "ExceptionType": "System.Net.Http.HttpRequestException",
    "StackTrace": "   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Kudu.Core.Jobs.ContinuousJobsManager.<HandleRequest>d__22.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Kudu.Services.Jobs.JobsController.<RequestPassthrough>d__0.MoveNext()",
    "InnerException": {
        "Message": "An error has occurred.",
        "ExceptionMessage": "Unable to connect to the remote server",
        "ExceptionType": "System.Net.WebException",
        "StackTrace": "   at System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, TransportContext& context)\r\n   at System.Net.Http.HttpClientHandler.GetRequestStreamCallback(IAsyncResult ar)",
        "InnerException": {
            "Message": "An error has occurred.",
            "ExceptionMessage": "An attempt was made to access a socket in a way forbidden by its access permissions 127.0.0.1:49663",
            "ExceptionType": "System.Net.Sockets.SocketException",
            "StackTrace": "   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)"
        }
    }
}
```

**Comment by davidebbo** [comment]
That's odd. Is this something that was working for you and started to break, or is this the first time you try it?

**Comment by mejje** [comment]
First time

**Comment by davidebbo** [comment]
It likely means that the WebJob is not listening on that port. Are there any interesting logs in the WebJobs dashboard?

**Comment by mejje** [comment]
This is output from start:

```
[10/22/2015 21:20:44 > 5ea67a: SYS INFO] Detected WebJob file/s were updated, refreshing WebJob
[10/22/2015 21:20:45 > 5ea67a: SYS INFO] Status changed to Starting
[10/22/2015 21:20:45 > 5ea67a: SYS INFO] Run script 'Foo.WebJob.exe' with script host - 'WindowsScriptHost'
[10/22/2015 21:20:45 > 5ea67a: SYS INFO] Status changed to Running
[10/22/2015 21:20:46 > 5ea67a: INFO] No functions found. Try making job classes and methods public.
[10/22/2015 21:20:46 > 5ea67a: INFO] Job host started
```

**Comment by davidebbo** [comment]
@mathewc can say more. This may be a better fit on https://github.com/Azure/azure-webjobs-sdk-extensions. It seems for whatever reason, the SDK is not starting to listen on the port, so when Kudu tries to forward the request it fails.

**Comment by ahmelsayed** [comment]
```
[10/22/2015 21:20:46 > 5ea67a: INFO] No functions found. Try making job classes and methods public.
```

The webjob SDK couldn't find any function that it could run, so it didn't even start listening for webhooks. Try making the class and functions public

**Comment by mejje** [comment]
Oh, sorry, I placed the example from https://github.com/Azure/azure-webjobs-sdk-extensions#webhooks in my (private) class Program... Thanks a lot for your time!

**Comment by diogoandrei** [comment]
I'm having this same error when trying to do a POST to a WebHookTrigger function in a WebJob running on Azure.

**Comment by mejje** [comment]
@diogoandrei is your class public as well as the attributed method?

**Comment by lars-erik** [comment]
I've set config.UseWebHooks(), and my functions class is like so:

    public class Functions
    {
        // This function will get triggered/executed when a new message is written 
        // on an Azure Queue called queue.
        public static void ProcessQueueMessage([QueueTrigger("queue")] string message, TextWriter log)
        {
            log.WriteLine(message);
        }

        public static void ProcessAnotherQueueMessage([QueueTrigger("anotherqueue")] string message, TextWriter log)
        {
            log.WriteLine(message);
        }

        public static void ProcessWebhookMessage([WebHookTrigger] string data, TextWriter log)
        {
            log.WriteLine(data);
        }
    }

Yet only the two queue triggers are found, and I get that forbidden 127.0.0.1 message as well.

Would really like for this to work. :)

**Comment by davidebbo** [comment]
Note that the passthrough API was experimental and has since been deprecated, as we moved instead toward Azure Functions for those scenarios.

**Comment by lars-erik** [comment]
Thanks. I found the info on functions vs. webjobs. I guess all the WebJobs docs could do with some CTA saying "Did you know you should do this with Functions?" ;)
