### ISSUE TITLE
Kudu.exe faulting when deploying between environments

### ISSUE THREAD

**Issue by mikkelhm** [projectkudu/kudu#1763]
We are using Kudu in our installation, which is based on Azure Pack.

I've just updated the Kudu part of the installation, meaning that it is now running the `Kudu.S48` release. Some of it seems to be working smoothly, but when we want to deploy between environments, `kudu.exe` fails. 
I don't see anything in any logs except on the webworker that runs the site, it says:

```
Faulting application name: kudu.exe, version: 48.41021.2758.0, time stamp: 0x562820d8
Faulting module name: git2-e0902fb.DLL, version: 0.22.0.0, time stamp: 0x54bee754
Exception code: 0xc0000409
Fault offset: 0x0008dd5b
Faulting process id: 0x181c
Faulting application start time: 0x01d10d75877d0429
Faulting application path: c:\kuduservice\wwwroot\bin\kudu.exe
Faulting module path: c:\kuduservice\wwwroot\bin\NativeBinaries\x86\git2-e0902fb.DLL
Report Id: c5a7ec8c-7968-11e5-80e7-000d3a214fc5
Faulting package full name: 
Faulting package-relative application ID: 
```

I've checked that the dll is actually there(`git2-e0902fb.DLL`), also tried a custom build of Kudu that was using the "old" git2 dll, version 0.20.2.0, which was what we were using before the upgrade, and it gives the same error, leaving me with the idea that it isn't related to the git2sharp, even though the log writes about that one in specific

Do any of you have any idea about what we are missing in order for this to work properly? We upgraded from `Kudu.S44` so the difference shouldn't be that big.

**Comment by davidebbo** [comment]
That's odd, as we test Kudu both on our local machines and on Azure, and I don't believe we've ever seen such thing.

**Comment by sitereactor** [comment]
We were able to get some more information out of the kudu.exe by running this command: `kudu "C:\inetpub\temp\DWASFiles\Sites\0c5095ad-fa10-4
a74-9e92-e66c294bd7b2\VirtualDirectory0\site" "C:\inetpub\temp\DWASFiles\Sites\0
c5095ad-fa10-4a74-9e92-e66c294bd7b2\VirtualDirectory0\site\wwwroot" "Mikkel"`

```
C:\KuduService\wwwroot\bin>kudu "C:\inetpub\temp\DWASFiles\Sites\0c5095ad-fa10-4
a74-9e92-e66c294bd7b2\VirtualDirectory0\site" "C:\inetpub\temp\DWASFiles\Sites\0
c5095ad-fa10-4a74-9e92-e66c294bd7b2\VirtualDirectory0\site\wwwroot" "Mikkel"
Updating branch 'master'.

Unhandled Exception: System.AggregateException: One or more errors occurred. ---
> Kudu.Core.Deployment.DeploymentFailedException: Deployment failed ---> LibGit2
Sharp.LibGit2SharpException: Failed to make directory 'C:/inetpub/temp/DWASFiles
/Sites/0c5095ad-fa10-4a74-9e92-e66c294bd7b2/VirtualDirectory0': The system canno
t find the path specified.

   at LibGit2Sharp.Core.Ensure.HandleError(Int32 result)
   at LibGit2Sharp.Core.Proxy.git_repository_set_head(RepositorySafeHandle repo,
 String refname, Signature signature, String logMessage)
   at LibGit2Sharp.ReferenceCollection.UpdateHeadTarget[T](T target, Signature s
ignature, String logMessage)
   at LibGit2Sharp.ReferenceCollectionExtensions.UpdateTarget(ReferenceCollectio
n refsColl, String name, String canonicalRefNameOrObjectish, Signature signature
, String logMessage)
   at LibGit2Sharp.Repository.Checkout(Tree tree, CheckoutOptions checkoutOption
s, String headTarget, String refLogHeadSpec, Signature signature)
   at LibGit2Sharp.Repository.Checkout(Branch branch, CheckoutOptions options, S
ignature signature)
   at LibGit2Sharp.Repository.Checkout(String committishOrBranchSpec, CheckoutOp
tions options, Signature signature)
   at Kudu.Core.SourceControl.Git.LibGit2SharpRepository.Update(String id) in c:
\Kudu Files\Public\src\master\Kudu.Core\SourceControl\Git\LibGit2SharpRepository
.cs:line 190
   at Kudu.Core.Deployment.DeploymentManager.<DeployAsync>d__0.MoveNext() in c:\
Kudu Files\Public\src\master\Kudu.Core\Deployment\DeploymentManager.cs:line 199
   --- End of inner exception stack trace ---
   at Kudu.Core.Deployment.DeploymentManager.<DeployAsync>d__0.MoveNext() in c:\
Kudu Files\Public\src\master\Kudu.Core\Deployment\DeploymentManager.cs:line 262
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceled
Exceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationTo
ken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Kudu.Console.Program.Main(String[] args) in c:\Users\Morten\Documents\GitH
ub\kudu\Kudu.Console\Program.cs:line 121
```

So far we have not been able to determine why this `Failed to make directory 'C:/inetpub/temp/DWASFiles
/Sites/0c5095ad-fa10-4a74-9e92-e66c294bd7b2/VirtualDirectory0'` occurs, as both the site and repository path from the `IEnvironment` appears to be correct. I can't remember if there is anything in libgit2sharp that barks on the symlink in `VirtualDirectory0`.

**Comment by sitereactor** [comment]
Oh, and I should mention that when we set `SCM_USE_LIBGIT2SHARP_REPOSITORY = 0` in order to disable the use of libgit2sharp then everything works fine again. So the GitExe repository-approach still works.

**Comment by sitereactor** [comment]
@davidebbo We isolated the issue to be libgit2sharp and the VirtualDirectory0, which at this point might be specific to Azure Pack (?). The `VirtualDirectory0` part in this path `C:\inetpub\temp\DWASFiles\Sites\0c5095ad-fa10-4a74-9e92-e66c294bd7b2\VirtualDirectory0\site\repository` is a symlink to a UNC Path (to Azure Pack's file server). We've actually had a similar issue with libgit2sharp before (in a non-Kudu service), but it was more then a year ago, so required some digging.

If we call kudu.exe with a path to a git repository, which is not within a "symlink folder" then everything works fine.

For reference this is what the VirtualDirectory0 looks like:
![](https://dl.dropboxusercontent.com/u/52040967/VirtualDirectory0.png)

@nulltoken Have you seen anything like this before? Where a symlink as part of the path to a repository causes problems for libgit2sharp? Stack trace is referenced above. I can summit a bug report on the libgit2sharp repo if you prefer it over there - unless its a known issue.

**Comment by nulltoken** [comment]
> @nulltoken Have you seen anything like this before? Where a symlink as part of the path to a repository causes problems for libgit2sharp?

Never seen this before. However, symlinks aren't first class citizens in Windows land. 

@carlosmn @ethomson Any thoughts?

**Comment by carlosmn** [comment]
this looks like it comes down to running `readlink()` as part of a `realpath()`. libgit2 (somewhat) recently gained support for UNC paths. I'm fairly sure they're not contained in a `e0902fb`, though they should be in the newest snapshot.

**Comment by davidebbo** [comment]
Thanks @carlosmn. We're using the latest non-prerelease libgit2sharp (`0.21.0.176`). @nulltoken: would the 0.22.x prerelease bits have this? If so, @sitereactor you can try upgrading that one package.

**Comment by nulltoken** [comment]
@davidebbo The latest prerelease package is running against https://github.com/libgit2/libgit2/commits/821131f which is pretty recent (less thann a week old)

**Comment by davidebbo** [comment]
Thanks @nulltoken. @sitereactor, worth a try for you to update that package to latest prerelease.

**Comment by mikkelhm** [comment]
Ok closing this one - various upgrades of Kudu/AzureWebApps etc have made the problem dissapear :-o
