### ISSUE TITLE
Unable to run functional tests

### ISSUE THREAD

**Issue by sitereactor** [projectkudu/kudu#1765]
I have been following this guide https://github.com/projectkudu/kudu/wiki/Getting-started in order to get the functional tests to run locally, but have been unsuccessful. All tests continue to fail even though I have been through all the steps in the guide above.

It looks like all the folders are created (ie. `C:\Kudu-Test-Files\KuduApps`), and I can see that the site(s) are created in IIS (kudu_*). But for a test like `AppChangesShouldTriggerBuildTests` I see in an `System.Net.Http.HttpRequestExceptionResponse status code does not indicate success: 401 (Unauthorized).` error, which I assume should not happen. Below is the full stack trace.

Any pointers as to what could be wrong in my setup? (I'm running VS2013 as Admin, and I've tried granting "Network Service" full control over the Kudu.Services.Web folder within the solution).

```
System.AggregateExceptionOne or more errors occurred.
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Kudu.TestHarness.ApplicationManager.Run(String testName, Action`1 action) in ApplicationManager.cs: line 242
   at Kudu.FunctionalTests.AppChangesShouldTriggerBuildTests.PushAppChangesShouldTriggerBuild() in GitRepositoryManagementTests.cs: line 329
System.AggregateExceptionOne or more errors occurred.
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Kudu.TestHarness.SitePool.<CreateApplicationInternal>d__c.MoveNext() in SitePool.cs: line 116
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Kudu.TestHarness.SitePool.<CreateApplicationAsync>d__0.MoveNext() in SitePool.cs: line 45
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Kudu.TestHarness.ApplicationManager.<RunNoCatch>d__7.MoveNext() in ApplicationManager.cs: line 259
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Kudu.TestHarness.ApplicationManager.<RunAsync>d__4.MoveNext() in ApplicationManager.cs: line 252
System.Net.Http.HttpRequestExceptionResponse status code does not indicate success: 401 (Unauthorized).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Kudu.SiteManagement.SiteManager.<WaitForSiteAsync>d__48.MoveNext() in SiteManager.cs: line 598
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Kudu.Core.Infrastructure.OperationManager.<>c__DisplayClass4.<<AttemptAsync>b__3>d__6.MoveNext() in OperationManager.cs: line 56
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Kudu.Core.Infrastructure.OperationManager.<AttemptAsync>d__9`1.MoveNext() in OperationManager.cs: line 76
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Kudu.SiteManagement.SiteManager.<CreateSiteAsync>d__15.MoveNext() in SiteManager.cs: line 180
```

**Comment by suwatch01** [comment]
If you open IIS manager and try to browse to site with prefix kudu_service_TestRunner*, what do you see on browser?  It might give some more clue.

**Comment by sitereactor** [comment]
@suwatch01 While the tests are running I usually get an error: "The site kudu_service_TestRunnerSite* does not exist". Sometimes I can browse to the site, but its empty. But I'm guessing that is mostly because the tests create and delete the two kudu_* sites in IIS as they start and terminate.

I tried running the Kudu.Web project from VS, which loads fine. But I when I try to open the Kudu.Services.Web project (which is also available with IIS Express) I get an error around the PathResolver and not being able to find the `%HOME%` directory. If I set that in my environment variables to the defatult `..\apps` folder Kudu is able to load. But I can't actually create an application as per the last part of the "Getting Started" documentation. It seems to just stall when clicking create. I see the two sites being created in IIS, but something never finishes.
Following the code I reach `CreateSiteAsync` in the `SiteManager` class, and it never gets past `await OperationManager.AttemptAsync(() => WaitForSiteAsync(serviceUrls.First()));` line 154 and when I look at the service site in IIS it says it can't read web.config. The kudu site itself only gets the hostingstart.html file. So possibly a permissions issue in reading or creating the necessary web.config file. 

Any guidance on how to continue?

And how should the `%HOME%` environment variable be configured when running from VS? And does this setting also affect the functional tests?

**Comment by suwatch** [comment]
Umm ..  strange.   Mind try clean up and some simple test.

1. On IIS Manager, delete every sites with Kudu_service_TestRunner* and Kudu_TestRunner* prefix.
2. Also, on IIS Manager, delete relevant app pools (TestRunnerSite* prefix).
3. Remove directory c:\Kudu-Test-Files.
4. Open Kudu.sln, clean and rebuild.  
5. After build successful, you should see the list of tests on the Test Explorer left pane.
6. Select SettingsApiFacts.SetGetValue (type in the Test Explorer text box) and run it.

See if the test run and successful?  Let us know the issue you ran into.

**Comment by sitereactor** [comment]
@suwatch When I run that test it just keeps spinning in what seems to be an endless loop.

The `C:\Kudu-TestFiles\KuduApps\TestRunnerSite*\` has a site and LogFiles folder. The site folder has deployments and locks, but everything is empty.

The kudu_service_TestRunnerSite* gives me the following error when going to the site.
```
Access is denied. 
  Description: An error occurred while accessing the resources required to serve this request. You might not have permission to view the requested resources. 

 Error message 401.3: You do not have permission to view this directory or page using the credentials you supplied (access denied due to Access Control Lists). Ask the Web server's administrator to give you access to 'C:\Users\Morten\Documents\GitHub\kudu\Kudu.Services.Web'.


Version Information: Microsoft .NET Framework Version:4.0.30319; ASP.NET Version:4.6.81.0 
```

The kudu_TestRunnerSite* site gives a HTTP Error 500.19 - Internal Server Error. And says it can't read the web.config, which is not surprising since there is no web.config - maybe because it can't access the kudu_service site?
```
Module
   IIS Web Core 

Notification
   Unknown 

Handler
   Not yet determined 

Error Code
   0x80070003 

Config Error
   Cannot read configuration file  

Config File
   \\?\C:\Kudu-Test-Files\KuduApps\TestRunnerSiteTHINKPAD-X2201\site\wwwroot\web.config 
```

So looks like a permissions issue, but I'm still unsure of what I'm missing or what needs special permissions? VS2013 is running in admin mode.

**Comment by davidebbo** [comment]
Definitely looks like a permission issue. At this point, I think it's best to isolate this from Kudu and VS and simply look at it as an IIS investigation. i.e. based on the site created in IIS in the given App Pool, what is preventing it from running. Please look at both the App Pool identity, and the permissions on the relevant folder.

**Comment by suwatch** [comment]
@sitereactor  if you check your apppool, they should run under NetworkService identity.  Also do check ACL for C:\Kudu-Test-Files folder.  Does it allow `authenticated user` all-but-full-control permission?  If not, try granting that and run the same test again.   I assume you have Windows 10 OS on your thinkpad,

**Comment by sitereactor** [comment]
Both Kudu sites in IIS use the same app pool, which runs under Network Service.

The `C:\Kudu-Test-Files` folder has Authenticated Users set to Modify, and the `KuduApps` folder under it has Network Service and Authenticated Users set to Modify.

The `Kudu.Services.Web` folder in the git repo has Network Service set to Modify, but only because I added it manually. I assumed it was necessary as that is what the app pool identity was set to. It doesn't have any permissions set for Authenticated Users.

I'm running Windows 8.1 on this laptop.

**Comment by sitereactor** [comment]
I removed Network Service and added Authenticated Users (Modify) to the `Kudu.Services.Web` site in my git repository, and now the `SettingsApiFacts.SetGetValue` test actually works and passes Yay! :smile: 

When I run all functional tests I still get a lot of failures though. 109 out of the 219 functional tests fail. Some stats: In the KuduApps folder I end up with 4 folders/sites, and the same in IIS. The RepositoryCache has 81 folders, and the TestRepositories folder has just one folder.

Would be great if the part about setting Authenticated Users to modify on the `Kudu.Services.Web` folder was added to the [wiki](https://github.com/projectkudu/kudu/wiki/Getting-started#additional-prerequisites-to-run-the-functional-tests).

And one more thing that I think could use some clarification is the use of the `%HOME%` environment setting when running `Kudu.Web` and `Kudu.Services.Web` from Visual Studio, as the services project does not appear to work unless that environmetn variable is set.

The list of pre-requisites probably also needs to be updated with Asp.Net 5 at some point :smile:

**Comment by suwatch** [comment]
@sitereactor, great that you have made some progress.  Concerning number of sites and cache folder, they are all expected.   

For 109 failed test, I assumed you have followed [getting started](https://github.com/projectkudu/kudu/wiki/Getting-started).   ASP.NET 5 requires HttpPlatform (also see getting started).   The remaining, we might have to try to debug it one by one.

As far as `%HOME%`, Kudu site requires `_app` vdir so we know where the deployment and so on go.  If you just run Kudu.Services.Web in VS, there will be no `_app` vdir, most Kudu functionality would like be broken anyway.   If one really wants to run in that manner, there are a few workarounds - one of which is to pre-specify the `%HOME%` before opening the VS.

**Comment by davidebbo** [comment]
Generally, you should never run `Kudu.Services.Web` directly. We never do this, and it's not meant to work.

Also, before trying to run any tests, try using Kudu manually. i.e. run Kudu.Web, create site, push some MVC app. Until you can do that successfully, no point trying to run more complex tests.

**Comment by jvano** [comment]
Hi

Kudu will continue to run in Azure App Service. However, this repo will no longer be maintained.
If the problem persists and is related to running on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
