### ISSUE TITLE
.git paths suddenly not reachable by IIS

### ISSUE THREAD

**Issue by dpayne0220** [projectkudu/kudu#1766]
Hi, I am running kudu as a service on my IIS server. I started changing repository paths using SCM_REPOSITORY_PATH for inplace deployment since I'm using it to deploy a CMS. At one point I changed SCM_REPOSITORY_PATH but it wasn't present anymore, so I re-created the variable. I created a new application, and when I try to reach the hostname:port/project.git path I'm greeted with a route error. All the other paths seem to work. It appears that kudu knows where the repo is since it shows deployment data. What could I do to repair this and avoid in the future

**Comment by davidebbo** [comment]
Changing `SCM_REPOSITORY_PATH` does not affect any routes, so if you feel your route is not resolving, I would suspect it is not related to that. Can you give details about exactly what error you are seeing?

**Comment by dpayne0220** [comment]
"No route registered for '/orchard.git'" 
Those routes are managed by kudu and I am looking to fix this in a way where I can continue to manage my sites through kudu

**Comment by davidebbo** [comment]
Strange. Does pushing to the Kudu root work? i.e. yank /orchard.git. Normally, both work. See https://github.com/projectkudu/kudu/blob/dec6cd65eca90683b1612aed472101b526f523af/Kudu.Services.Web/App_Start/NinjectServices.cs#L373-L374. You may need to debug it.

**Comment by dpayne0220** [comment]
Also around that time, I followed [this](https://social.msdn.microsoft.com/forums/azure/en-US/46cd0039-7427-4c77-b796-cabeb5eb5316/git-deployment-and-get-my-files-back) tutorial and Deleted Git Repository from the control panel. Now there is no button that says Delete Git Repository. Also checking root git status now

**Comment by dpayne0220** [comment]
Re installed Admin Tools module and everything works fine. That error message is just because looking at a git repo in browser, I can connect to the repo

**Comment by soravit3102** [comment]
d
