### ISSUE TITLE
Custom deployment crash "cygheap_user::init: NtSetSecurityObject, 0xC0000022"

### ISSUE THREAD

**Issue by francesconero** [projectkudu/kudu#1767]
I'm trying to pull a remote folder during deployment using rsync, a unix tool.

Since msysgit doesn't provide rsync, I managed to find a binary port of the tool here: [cwRsync](https://www.itefix.net/content/cwrsync-free-edition)

I added the extracted executable and DLLs to my project, and I call rsync.exe from the `deploy.cmd`

For reference, assuming the extracted rsync binaries are located in a folder called `cwRsync` under the root project folder, the `deploy.cmd` needed to replicate the crash is simple as:

```
.\cwRsync\rsync.exe --version
```

The relevant error output is:

```
remote: D:\home\site\repository>.\cwRsync\rsync.exe --version         
remote:       1 [main] rsync 13028 cygheap_user::init: NtSetSecurityObject, 0xC0000022        
remote:    1260 [main] rsync 13028 D:\home\site\repository\cwRsync\rsync.exe: *** fatal error - NtCreateDirectoryObject(\BaseNamedObjects\cygwin1S5-5537472367d23945): 0xC0000022        
remote: Stack trace:        
remote: Frame     Function  Args        
remote: 0028F6A0  6107E9F8 (FFFFFFFF, 6120E65C, 00000004, 00000000)        
remote: 0028F900  610D3704 (611ED36C, 00000005, 6119CC88, 00006D50)        
remote: 0028F940  610D4090 (00000084, 02000000, 6118C73C, 6118C740)        
remote: 0028F970  610085E9 (00000000, 00740248, 77A22128, A34B21C9)        
remote: 0028F9B0  6107D7C8 (61000000, 00000001, 0028FD24, 00000000)        
remote: 0028F9D0  77A245F2 (6107D6D0, 61000000, 00000001, 0028FD24)        
remote: 0028FA18  77A2463F (6107D6D0, 61000000, 00000001, 0028FD24)        
remote: 0028FA9C  77A27F16 (00748F30, 00748F68, 00748310, 00749278)        
remote: 0028FABC  77A27E5E (00748F30, 0028FBA0, 0028FADF, 00400080)        
remote: 0028FAE4  77A29CEC (00748310, 0028FBA0, 0028FC2F, A34B24A5)        
remote: 0028FC98  77A2E169 (0028FD24, 779D0000, A34B24CD, 00000000)        
remote: 0028FCF0  77A2D312 (0028FD24, 779D0000, 0028FD10, 77A2BC20)        
remote: 0028FD00  77A2BC56 (0028FD24, 779D0000, 00000000, 00000000)        
remote: 0028FD10  77A2BC20 (0028FD24, 779D0000, 00000000, 0001002F)        
remote: End of stack trace  
```

Is this crash sandbox related maybe?

This is all of course happening deploying to an Azure Web Site; the rsync binaries work well for example on a Windows Server 2012 (tested).

**Comment by snobu** [comment]
Most probably sandbox restriction. Take a look at Unison or try to use scp for Windows instead.

 http://www.terminally-incoherent.com/blog/2006/09/23/command-line-scp-for-windows/

**Comment by snobu** [comment]
Unison: http://www.cis.upenn.edu/~bcpierce/unison/

**Comment by davidebbo** [comment]
@ahmelsayed this is the same error you saw when trying msysgit 2.5.

**Comment by ahmelsayed** [comment]
Correct, it's a sandbox issue.

**Comment by francesconero** [comment]
@snobu I just tried unison and unfortunately it doesn't work as well. It doesn't crash but, it says that there was an error in canonizing a path. I suspect the problem being the root folder permissions of the azure website, so in a way it could still be the sandboxing.

Using scp is not really an option, since it doesn't have delta updates.

**Comment by snobu** [comment]
I'll do some research on Monday. So delta copy windows->Linux is what you're looking for, right? Linux being the source.

**Comment by francesconero** [comment]
Actually I'm trying to delta copy from a windows server on which I build the node_modules to an azure website during deploy.

Next thing I'm going to try is storing the node_modules folder in a separate git repo and then pulling from it during deploy...I hope that works at least...

**Comment by snobu** [comment]
If you can expose SMB 445/TCP robocopy is a great tool for deltas windows->windows.

I'm hitting deltacopy a lot in my search, never used it but have a look here http://www.aboutmyip.com/AboutMyXApp/DeltaCopy.jsp

**Comment by francesconero** [comment]
I'm already using deltacopy server side. I was hoping to use it in conjunction with rsync originally (but then I encountered the original issue).

I'll try to see if robocopy works from the azure website.

Thank you so much for your time.

**Comment by snobu** [comment]
<img width="487" alt="robo" src="https://cloud.githubusercontent.com/assets/6472374/10710267/dc8bb78e-7a59-11e5-9789-da712804a260.png">

Robocopy ships in the sandbox. Looking good.

**Comment by francesconero** [comment]
I need to mount a network share on the website though...it's giving me "Access is denied"

**Comment by snobu** [comment]
You're running as 
```cmd
D:\home>whoami
iis apppool\sitename
```

In `net use` try to specify `/user` as `remotecomputername\username` or `.\username'. You need to pass in the password too as the console might not be able to take keyboard input when prompted for password.

**Comment by francesconero** [comment]
Which password should I use?
This command still fails with "Access is denied",
```
net use X: \\VIRTUAL-NETWORK-IP\Share /USER:iis apppool\sitename
```
This command succeeds on another Windows Server 2012 on the same virtual network
```
net use X: \\VIRTUAL-NETWORK-IP\Share
```

**Comment by snobu** [comment]
Is your Windows Server box in a VNET and you point-to-site VPN from the Web App?

Then from your Web App,
         net use z: \\ip-addr-win-srv\folder /user:username password

where username and password are local to your Windows Server.

**Comment by francesconero** [comment]
Doesn't work, I don't know what I'm missing. The exact same command from another computer on the same VNET works. I know the site is on the VNET since I contact the same computer from it via http and it works.

Have you got it to work?

**Comment by snobu** [comment]
Odd. Let me try to reproduce the scenario on my subscription.
Can you tcpping ip-addr-win-srv on port 445 from web app?

**Comment by francesconero** [comment]
I tried to tcpping through a nodejs script and I get connect EACCES only on port 445. It's a different error than ECONNREFUSED which I get on closed ports. Other open ports ping fine.

**Comment by davidebbo** [comment]
You will not be able to `net use` a share. It is not a Kudu restriction, but is a restriction of the sandbox that both Kudu and the site run in. See https://github.com/projectkudu/kudu/wiki/Azure-Web-App-sandbox for more info on the sandbox.

**Comment by francesconero** [comment]
That's unfortunate...I don't know what else to try

**Comment by davidebbo** [comment]
Can't you expose the bits you want to download as a git repo over https or ssh and pull from there?

**Comment by snobu** [comment]
Thanks @davidebbo
@francesconero Apologies for sending you on a wild goose chase. Looks like egress on 445/TCP is restricted as well. 
<img width="795" alt="445" src="https://cloud.githubusercontent.com/assets/6472374/10714325/04eddd8e-7af4-11e5-8044-2f07095df58a.png">

**Comment by francesconero** [comment]
@snobu don't worry, I only need to thank you for giving me pther options I wouldn't have thought about!

@davidebbo I tried that yesterday, but unfortunately git on windows doesn't like long path names...even after enabling them in the git configuration (so it fails to serve some files during a clone or pull).

My next idea is to try to make kudusync work over ftp, do you think that would be very hard?

**Comment by davidebbo** [comment]
How does the long file name restriction relate to this? This restriction (260 max path length) exists regardless of what technique you use to bring down bits, so it is orthogonal to the use of git.

Note that if you're getting long paths as a result of npm, you should try upgrading to npm 3.x, which results in much shorter path.

I'm not sure I would go down the road of trying to make kudusync work over FTP. I would be quite a bit of work, and the result would likely be quite slow, because FTP just isn't very efficient.

**Comment by snobu** [comment]
...and because not even FTP works over FTP most of the time!

I'm trying to put something together around `robocopy` over `something else`. Still working on the `something else` part.

**Comment by francesconero** [comment]
I understand that this limitation is more of the tools using old Windows APIs or naming conventions (see [here](https://github.com/msysgit/msysgit/wiki/Git-cannot-create-a-file-or-directory-with-a-long-path)? For example setting that git longpaths option, I can use path names longer than 260 characters, so it mustn't be a hard limit. The fact is that without git, rsync, robocopy or unison had no problem copying the same folder over to another computer, so I don't know what to say.

Anyway relying on git seems very very hackish and prone to error, especially since I have to setup a git server on Windows, dealing with automatic commits, repo creation etc. For a simple folder synchronization it seems too much. I don't know if it would be more difficult than converting kudusync to ftp.

About FTP not being reliable...you are absolutely right, but that's what I'm using now to copy node_modules over to the website (with WinSCP diff copy), so I really can't go worse than that.

**Comment by snobu** [comment]
Robocopy over `something else` turned out to be a dead end, mainly because of the missing `something else` :)

But i found a `rsync` port for Win32 that works in the sandbox.
The "other end" is __DeltaCopy__.

Ignore the failed to set permissions stuff. You might be able to get rid of that but it doesn't really matter, t's not a fatal error.

Try it.

```
D:\home\rsync\rsyncwin32-0.0.2\win32>rsync -av rsync://10.6.0.4/share test

rsync port to Win32 by George McCollister. Version 0.0.2
Use at your own risk! This code is currently experimental.
receiving file list ... done
./

file.txt

rsync: failed to set permissions on "D:\home\rsync\rsyncwin32-0.0.2\win32/test/.file.txt.a05472": No such file or directory (2)

no change.txt

rsync: failed to set permissions on "D:\home\rsync\rsyncwin32-0.0.2\win32/test/.no change.txt.a05472": No such file or directory (2)

this doc has changed.txt

rsync: failed to set permissions on "D:\home\rsync\rsyncwin32-0.0.2\win32/test/.this doc has changed.txt.a05472": No such file or directory (2)
```

```
D:\home\rsync\rsyncwin32-0.0.2\win32>dir test

 Volume in drive D is Windows
 Volume Serial Number is FEFD-D936

 Directory of D:\home\rsync\rsyncwin32-0.0.2\win32\test

10/25/2015  05:28 PM    <DIR>          .
10/25/2015  05:28 PM    <DIR>          ..
10/25/2015  05:26 PM                 7 file.txt
10/25/2015  05:15 PM                11 no change.txt
10/25/2015  05:15 PM                12 this doc has changed.txt
               3 File(s)             30 bytes
               2 Dir(s)  53,556,121,600 bytes free
```

![share](https://cloud.githubusercontent.com/assets/6472374/10716857/4f184da8-7b4f-11e5-94dd-950d19bde4b2.PNG)

**Comment by francesconero** [comment]
@snobu that's wonderful! Have you managed to get it to delete files as well with the --delete flag? It gives an error to me.

Why do you think this version of rsync works?

**Comment by snobu** [comment]
There's no dependency on cygwin.
Try going through the source code, maybe `--delete` is not implemented or try contacting the author, George McCollister.

If you find better Win32 ports of cygwin, they are probably worth a shot too, i've been unable to find anything else that's anywhere close to usable.

**Comment by snobu** [comment]
`--delete` seems to work though.

```
D:\home\rsync\rsyncwin32-0.0.2\win32>D:\home\rsync\rsyncwin32-0.0.2\win32>rsync -vr --delete rsync://10.6.0.4/share test

rsync port to Win32 by George McCollister. Version 0.0.2
Use at your own risk! This code is currently experimental.
   receiving file list ... done
   deleting 600k.vcp
   big.file
   this doc has changed.txt

D:\home\rsync\rsyncwin32-0.0.2\win32>D:\home\rsync\rsyncwin32-0.0.2\win32>dir test

 Volume in drive D is Windows
 Volume Serial Number is FEFD-D936

 Directory of D:\home\rsync\rsyncwin32-0.0.2\win32\test

10/25/2015  07:10 PM    <DIR>          .
10/25/2015  07:10 PM    <DIR>          ..
10/25/2015  07:10 PM         4,576,633 big.file
10/25/2015  05:26 PM                 7 file.txt
10/25/2015  05:15 PM                11 no change.txt
10/25/2015  07:10 PM                 9 this doc has changed.txt
```

**Comment by francesconero** [comment]
@snobu I get weird file not found errors in nested directories with mixed backward and forward slashes

**Comment by snobu** [comment]
__receiver.c__
```c
static void delete_one(char *fn, int is_dir)
{
[..]
	if (do_rmdir(fn) != 0) {
			if (errno != ENOTEMPTY && errno != EEXIST) {
				rsyserr(FERROR, errno,
					"delete_one: rmdir %s failed",
					full_fname(fn));
			}
[..]
}
```



__syscall.c__
```c
int do_rmdir(char *pathname)
{
	if (dry_run) return 0;
	RETURN_ERROR_IF_RO_OR_LO;
	return rmdir(pathname);
}
```

Try to replace all `/` in pathname with `\` somewhere early in the code or in `syscall.c`

**Comment by francesconero** [comment]
Thanks but...I can't even get the project to compile in VS, I never used it. Honestly I think I'm going to give up. Thank you so much for your help, I cannot express my gratitude enough.

**Comment by snobu** [comment]
Did you find another way to sync your files or had to revert back to FTP?

I was thinking that i should ahead and fork http://rsyncwin32.sourceforge.net/ and get it to compile in something more this century, like MinGW. It _should_ compile in eMbedded Visual C++ 4.0 under Windows NT4, but that's not exactly anyone's first choice in development platforms, right now.

It's a chicken (rsync?) and egg (Win32) problem. Not sure if very few need `rsync` on Win32 or very few use `rsync` on Win32 because there isn't a quality native port for it.

That being said even if __rsyncwin32__ is `Alpha v0.0.2 - 7/22/2005` i think `George McCollister` did a fantastic job there. Kudos to the author!

**Comment by jvano** [comment]
Hi

Kudu will continue to run in Azure App Service. However, this repo will no longer be maintained.
If the problem persists and is related to running on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
