### ISSUE TITLE
WEBSITE_NPM_DEFAULT_VERSION is ignored when node is no 4.1.2

### ISSUE THREAD

**Issue by Philo** [projectkudu/kudu#1772]
pull request #1745 allows NPM 3.3.6 to be used when explicitly settings WEBSITE_NODE_DEFAULT_VERSION to 4.1.2 but the WEBSITE_NPM_DEFAULT_VERSION is otherwise ignored.  Surely it would be better to allow both WEBSITE_NPM_DEFAULT_VERSION and WEBSITE_NODE_DEFAULT_VERSION to be set and honoured individually for a deployment.

For example I have the requirement to use node 0.12.6 but due to node_modules nesting I wish to use npm 3+:

WEBSITE_NODE_DEFAULT_VERSION=0.12.6
WEBSITE_NPM_DEFAULT_VERSION=3.3.6

At the moment my only option is to directly alter my deploy.cmd to fix the path to NPM_JS_PATH

**Comment by davidebbo** [comment]
Setting `WEBSITE_NPM_DEFAULT_VERSION` should override all other mechanisms to select the npm version. Are you seeing otherwise?

**Comment by suwatch** [comment]
@ahmelsayed  the #1745 fix may not be complete.  we may need to also fix the [selector script] (https://github.com/projectkudu/kudu/blob/master/Kudu.Core/Scripts/selectNodeVersion.js#L36) in addition.

**Comment by ahmelsayed** [comment]
what's the scenario that this script is used for that would affect npm?

**Comment by suwatch** [comment]
The script is used during deployment in deploy.cmd to resolve the npm path to be used when calling `npm install --production` on package.json for nodejs deployment.
