### ISSUE TITLE
Error 500 with web hook with Gitlab

### ISSUE THREAD

**Issue by Mike44000** [projectkudu/kudu#1773]
Hello,

I try to configure continuous deployment with a perso gitlab server. I follow the "Setting up continuous deployment using manual steps" of the page https://github.com/projectkudu/kudu/wiki/Continuous-deployment.

When I push something on my gitlab repository, Azure receive the hook but the deployment has an exception.

In the POST_deploy log I have an error 500 : 

"Value cannot be null.
Parameter name: url" stackTrace="   at LibGit2Sharp.RemoteCollection.Add(String name, String url, String fetchRefSpec)
   at Kudu.Core.SourceControl.Git.LibGit2SharpRepository.FetchWithoutConflict(String remoteUrl, String branchName)
   at Kudu.Services.ServiceHookHandlers.ServiceHookHandlerBase.Fetch(IRepository repository, DeploymentInfo deploymentInfo, String targetBranch, ILogger logger)
   at Kudu.Services.FetchHandler.&lt;PerformDeployment&gt;d__e.MoveNext()

I don't understand which url is wrong : I don't find already the xxxHandlerFact used.

Can someone help me?

Thanks a lot.

Best regards.

Mikaël PLOUHINEC

**Comment by davidebbo** [comment]
Maybe the payload that gets sent is not compatible with what Kudu expect for some reason. See https://github.com/projectkudu/kudu/blob/16d3fa55140f15fe8517515f5fbc4f89481196ed/Kudu.Services/ServiceHookHandlers/GitlabHqHandler.cs#L10-L40 for what's expected, and compare with what's getting sent in your scenario (you can use a site like http://requestb.in/ to capture it if needed).

**Comment by suwatch** [comment]
Just try it and it seems to work.   As @davidebbo suggested, do capture it with http://requestb.in and share us the payload.

**Comment by Mike44000** [comment]
Hello,
Where can I change the url? Is that the web hook the problem or the kudu request to my gitlab? 

This is the web hook send by my gitlab : 

{
   "before":"f18bed37cdcee5cf93835cc6a071e7221b3d0b62",
   "after":"f90a1c8322164053981bc2a48329cdcdf7e5b37f",
   "ref":"refs/heads/master",
   "checkout_sha":"f90a1c8322164053981bc2a48329cdcdf7e5b37f",
   "user_id":143,
   "user_name":"Mikael Plouhinec",
   "project_id":266,
   "repository":{
      "name":"kitdefacilitation.serveur",
      "url":"git@gitlab-toulouse.sqli.com:vfruchet/kitdefacilitation.serveur.git",
      "description":"Kit de facilitation - Serveur NodeJS",
      "homepage":"http://gitlab-toulouse.sqli.com/vfruchet/kitdefacilitation.serveur"
   },
   "commits":[
      {
         "id":"f90a1c8322164053981bc2a48329cdcdf7e5b37f",
         "message":"Ajout d'un fichier README.md\n",
         "timestamp":"2015-10-26T22:58:12+01:00",
         "url":"http://gitlab-toulouse.sqli.com/vfruchet/kitdefacilitation.serveur/commit/f90a1c8322164053981bc2a48329cdcdf7e5b37f",
         "author":{
            "name":"MikeSQLIdeployment",
            "email":"mikael.plouhinec@gmail.com"
         }
      },
      {
         "id":"c38fa062c78c4368e4535e12a02262fb6311196a",
         "message":"Correction de bugs\n",
         "timestamp":"2015-10-26T17:18:05+01:00",
         "url":"http://gitlab-toulouse.sqli.com/vfruchet/kitdefacilitation.serveur/commit/c38fa062c78c4368e4535e12a02262fb6311196a",
         "author":{
            "name":"vfruchet",
            "email":"vfruchet@sqli.com"
         }
      },
      {
         "id":"f18bed37cdcee5cf93835cc6a071e7221b3d0b62",
         "message":"Merge branch 'master' of https://kitdefacilitation.scm.azurewebsites.net:443/kitdefacilitation\n\n# Conflicts:\n#\tserver.js\n",
         "timestamp":"2015-10-26T14:40:29+01:00",
         "url":"http://gitlab-toulouse.sqli.com/vfruchet/kitdefacilitation.serveur/commit/f18bed37cdcee5cf93835cc6a071e7221b3d0b62",
         "author":{
            "name":"vfruchet",
            "email":"vfruchet@sqli.com"
         }
      }
   ],
   "total_commits_count":3
}

Thanks

**Comment by davidebbo** [comment]
Your payload is missing `git_http_url` and `git_ssh_url`, which Kudu expects. I'm guessing you're running on old version of GitLab. Those fields were added around February. See https://github.com/projectkudu/kudu/issues/1470. @randx can confirm.

**Comment by Mike44000** [comment]
My GitLab Server is 7.7.2 version. 

I try with a gitlab server in version 7.11.0 : the payload contains the visibility_level, git_http_url, git_ssh_url.

The Gitlab server need an upgrade I think.

Thanks a lot for your help.

Mike

**Comment by suwatch** [comment]
@davidebbo one idea is we could consider do a small targeted Kudu fix for this (fallback to repository's url).   The other missing info is whether this is public or private repository.   We will always assume whatever defined by repository's url.   Thought?

**Comment by Mike44000** [comment]
For information, the fields were added here. https://github.com/gitlabhq/gitlabhq/commit/92434b29cc45677fe72bb6a8a5bd09d5ead8d138
