### ISSUE TITLE
Basic Authentication permissions

### ISSUE THREAD

**Issue by dpayne0220** [projectkudu/kudu#1774]
When using Basic Auth in IIS, I can access my 'kudu' site, and directly connect to both the kudu_service via port, and the kudu_sitename. However when, from the main kudu panel, I click a site, it gives a 401.1 Unauthorized. I tried the solution listed in https://github.com/projectkudu/kudu/issues/691 and changed the password in the source to match my basic auth and still no dice. Have also added the user permissions to all kudu related files.

**Comment by davidebbo** [comment]
I just tried, and it works fine for me if I add correct creds to [this line](https://github.com/projectkudu/kudu/blob/1c7c4d6855714a536dc3307dd225a5a03d499b5a/Kudu.Web/App_Start/Startup.cs#L86). Obviously, it's dirty and should be configurable outside code, as pointed out in that old thread. But beyond that, it seems to work.

**Comment by tenbits** [comment]
Thanks @davidebbo, it works, but indeed it should be moved to configuration, as after adding the Basic  Auth to kudu service, I had to change the source code, rebuild the KuduWeb and redeploy it. These is far away from convenient way to change the creds)
