### ISSUE TITLE
Intermittent nuget restore failure.

### ISSUE THREAD

**Issue by AlanParr** [projectkudu/kudu#1776]
I've got a project which deploys to 3 separate sites in West Europe, East US, and East Asia. For the last couple of weeks, the US instance fails the build on nuget restore with the following message:

```
Command: deploy.cmd
Handling .NET Web Application deployment.
All packages listed in packages.config are already installed.
All packages listed in packages.config are already installed.
Failed exitCode=-1073741818, command=nuget restore "D:\home\site\repository\Product\MySolution.sln"
An error has occurred during web site deployment.
Handling .NET Web Application deployment.\r\nAll packages listed in packages.config are already installed.\r\nAll packages listed in packages.config are already installed.\r\nFailed exitCode=-1073741818, command=nuget restore "D:\home\site\repository\Product\MySolution.sln"\r\nAn error has occurred during web site deployment.\r\nC:\Program Files (x86)\SiteExtensions\Kudu\48.41021.1874\bin\scripts\starter.cmd deploy.cmd
```

Running the nuget restore command manually in Kudu gives the "All packages listed in packages.config are already installed" message twice as above, but without the subsequent errors.

If I force a Retry/Sync via the management portal enough times and sometimes push the same commit again, it will eventually build successfully.

I have confirmed the following:
- All instances are on Kudu version 48.41021.1874.0
- There are no kudu version or msbuild overrides in place on any of the sites.
- Any SCM_\* app settings are identical across all instances. I am using SCM_BUILD_ARGS, SCM_ALLOW_SUBMODULES, and SCM_SHALLOW_CLONE.

I'm mystified as to why, out of 3 seemingly identical instances, only the US one is giving me trouble. I'm not ruling out this being an Azure Websites problem but it seemed sensible to report it here first.

**Comment by davidebbo** [comment]
When running it manually in Kudu Console, can you run `echo %errorlevel%` right after running the command? It looks like nuget.exe returning that error code, but not printing any error message itself.

**Comment by AlanParr** [comment]
Did as instructed and echo %errorlevel% returns -1073741818, the same error code as the Kudu error.
Running the same command on another instance of the site returns 0.

**Comment by davidebbo** [comment]
Can you share your site name, either directly or [indirectly](https://github.com/projectkudu/kudu/wiki/Reporting-your-site-name-without-posting-it-publicly)? This will help us investigate. Thanks!

**Comment by AlanParr** [comment]
The site with the problem is cms-staging-us-site, one of the sites that is fine is cms-staging-weu-site.

**Comment by davidebbo** [comment]
It's quite strange. Even running nuget.exe with no params, or running `nuget bogus` returns that same error code. It also seems to take a lot longer.

Maybe for now as workaround, you can tank the `IF !ERRORLEVEL! NEQ 0 goto error` check after `nuget restore` in the deploy script (since we know it's working despite the error). But we should get to the bottom of this.

This [old thread](https://social.msdn.microsoft.com/forums/en-us/07491343-36d2-4cff-bd1c-c782678ce267/deployment-failed-github-to-azure-websites) has the same error code, though it's not clear if it was nuget related or some other process.

**Comment by davidebbo** [comment]
Oh, so I just tried running a dummy msbuild command on your bad site, and the same happened. So there is something going on there that goes beyond nuget. Did you check if restarting the site helps?

**Comment by AlanParr** [comment]
I've tried restarting in the past and it doesn't seem to have an affect. Haven't tried it yet this time as I wanted to preserve the site's state for any investigations.
Will try it and let you know.

-----Original Message-----

**Comment by AlanParr** [comment]
@davidebbo Have restarted and the deployment was successful, so it seems like some bad state is being left that is disposed of by a restart.
As previously stated, I have tried restarting in the past and had it not resolve the problem, so while it is a solution in this case, it is not necessarily always so.

**Comment by davidebbo** [comment]
Yes, this is not a solved problem. At this point, this is the first report of this that we get, so let's keep the issue open and see whether others are hitting it as well. If you hit it again and are able to wait, we can try to dig deeper into it to see what's going on.

**Comment by AlanParr** [comment]
I'll be attempting another deployment later today, so if that fails I will leave it in that state and take it off the traffic manager so you can experiment with it as long as you need.

**Comment by davidebbo** [comment]
Awesome, thanks!

**Comment by AlanParr** [comment]
Typical, it's deploying now! I'll run continuous deployments next week and update this issue when it next fails.
As an aside, is there a way to see if the post-deployment git hook was fired as, even when it is deploying, it doesn't seem to fire off the hook. I've got it hooked up to Zapier and I get emails for every instance, again except this one.

**Comment by davidebbo** [comment]
If the deployment is triggered by GitHub/Bitbucket, they keep a nice log of all the hook invocations they make, with the full payload and response.

**Comment by AlanParr** [comment]
I meant the post-deployment hook that is triggered by Kudu/Azure Web Apps after a deployment is complete that can be used by services like Zapier to inform you of build success/failure, not sure if this is a Kudu feature or Azure Web Apps feature.

**Comment by davidebbo** [comment]
That just gets called at the end of the regular deployment script, so regular deployment log should saw it. But let's discuss separately is it is quite unrelated to the core NuGet issue, and it's best to side lose track of that in this one.

**Comment by AlanParr** [comment]
Fair enough. If it continues happening, I will log it as a separate issue.

**Comment by bebizzle** [comment]
Was there any followup or further occurrences of this issue? We are experiencing a similar event.

**Comment by jvano** [comment]
Hi

Kudu will continue to run in Azure App Service. However, this repo will no longer be maintained.
If the problem persists and is related to running on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
