### ISSUE TITLE
Allow storing webjobs history to Azure blob storage to make swapping experience better

### ISSUE THREAD

**Issue by kamranayub** [projectkudu/kudu#1779]
x-post from azure/azure-webjobs-sdk#586

---

So this is an interesting issue.

When I perform a swap in Azure, I noticed that the job data that Kudu displays in the web jobs dashboard _also_ swaps.

Case in point.

On my dev slot, I issued a triggered job run:

![image](https://cloud.githubusercontent.com/assets/563819/10597302/0e3d0e54-76b3-11e5-9334-3d3470341a4e.png)

Take note of the run time: Tue, 20 Oct 2015 03:36:42 GMT

Then, after I swapped, I see that **exact run** in my production slot's dashboard:

![image](https://cloud.githubusercontent.com/assets/563819/10597312/27cb2e46-76b3-11e5-8d27-2f5674e4fe2e.png)

To prove it, I also can issue an API request against the production slot and see my run ID:

```
{
  "id": "201510200336425903",
  "name": "201510200336425903",
  "status": "Success",
  "start_time": "2015-10-20T03:36:42.5903978Z",
  "end_time": "2015-10-20T03:37:02.8328967Z",
  "duration": "00:00:20.2424989",
  "output_url": "https://xxx.scm.azurewebsites.net/vfs/data/jobs/triggered/QueueUpdates/201510200336425903/output_log.txt",
  "error_url": null,
  "url": "https://xxx.scm.azurewebsites.net/api/triggeredwebjobs/QueueUpdates/history/201510200336425903",
  "job_name": "QueueUpdates",
  "trigger": "External - Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.71 Safari/537.36"
}
```

It returns a 404 if I try the same API call against the dev slot.

(I didn't include the URLs but you'll have to trust me)

I assume each time I swap, it's swapping the dashboard storage connections too. I double checked my own connection strings (AzureWebJobsDashboard and AzureWebJobsStorage) and they are Slot Settings and remain the same after a swap.

**Comment by davidebbo** [comment]
Today, Kudu never deals with storage accounts. Conceivably, there could be a provider model that would allow us to save things to alternate stores. This could be useful for both WebJobs history and Deployment history, which both behave a bit strangely during swaps when using the file system.

Maybe the simplest solution is to wait until Azure Web Apps get general support for [Azure File storage](https://azure.microsoft.com/en-us/blog/azure-file-storage-now-generally-available/). Then it would be a matter of mapping the relevant files to a different folder, without having to deal with a different protocol. Though that could take a while.

**Comment by jvano** [comment]
Hi

Kudu will continue to run in Azure App Service. However, this repo will no longer be maintained.
If the problem persists and is related to running on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
