### ISSUE TITLE
Dont copy web.config in sync

### ISSUE THREAD

**Issue by mikkelhm** [projectkudu/kudu#1781]
Hi Kudu team

This is more a question than an issue. 

We are using Kudu on our installation of Azure Pack, meaning that all sites that are created gets kudu attached. We would love to do stuff to the default deploy script for the sites that are created. 
From the documentation, i see that this can be done pr. site, my modifying the deploy.cmd file, and we have this working. The issue is that we now have to change the deploy.cmd file for each site(currently ~600) in the installation, and do it everytime we create a new site. 
We customize something globally for each site, these are the app settings like `POST_DEPLOYMENT_ACTIONS_DIR`, `SCM_USE_LIBGIT2SHARP_REPOSITORY` and `SCM_TOUCH_WEBCONFIG_AFTER_DEPLOYMENT` but i havn't had luck changing or setting which deployment script should be used globally.
The two solutions i see is possible right now is 
- 1. modify deploy.cmd for each site
- 2. modify the .deployment file to have command = _global position_ on each site

Both solutions include changing something that is site specific rather than global.

__The solution we are trying to do is:__
When a user changes some files in their repositories, KuduSync copies all changed files to the webroot. In our post deployment actions dir, we have a tool that does a web.config transform, to ensure that certain configurations gets added to the web.config. The "problem" with this approach is that the web.config now looks different for KuduSync, and therefore copies web.config next time it syncs. This means that no matter what files get changed in the repository, web.config gets transferred to the webroot, thous restarting the app.

The solution that we have come up with is changing the deploy.cmd file, and tell KuduSync to ignore the web.config. In our post deployment tool, we then to the web.config transform to a temp dir, and overwrites the web.config in the webroot, if they are different. It is working, but includes changing the deploy.cmd for every site.

Any advice on this, or are we having a wrong approach for the issues?

**Comment by davidebbo** [comment]
Sounds like the same as https://github.com/projectkudu/kudu/issues/1167, which was fixed recently. Maybe your Azure Pack has an older Kudu build?

**Comment by mikkelhm** [comment]
No not exactly we implemented the newest Kudu, exatly to get that functionality, as we thought that was the trouble maker, it was ALSO causing the app restart, but our own transform in the end is the real culpit. 
The issue is that we actualy need to inject some things in the web.config that is in the webroot, and currently it is done with web.config transforms. This results in the fine in the webroot beeing different than the one in the repository, thus KuduSync will copy again next time

**Comment by davidebbo** [comment]
But that is *supposed* to be covered by the fix. In fact, this is not a unique situation, and even a vanilla MVC app has a transform which makes the resulting file different from the one in the repo (removes the debug attribute). Read my entry that starts with "Digging into things a bit more" in that thread.

Now the question is why it doesn't work for you, which would require investigation. But on the surface, it is not a different scenario as far as I understand.

**Comment by mikkelhm** [comment]
Thanks, ill take a deeper look into the conversation in 1167, we are running the S48 release of kudu though, but something along the way might need an update aswell.

**Comment by davidebbo** [comment]
One suggestion is to check whether you get the same behavior happens on Azure. This would help isolate whether the recent fix is generally not working for you, or whether it's specific to how it's running in Azure Pack.

**Comment by mikkelhm** [comment]
Good idea to check the functionality on Azure. 
I do think the issue is because we are doing our transforms as part of the Post deployment actions, and not part of the build process. Though i cant see where in the KuduSync update it would compare a transformed config, and not just the one on source vs destination, but some magic must happen in there.

Ill dig :-)

**Comment by davidebbo** [comment]
In theory, with the new KuduSync ([this code](https://github.com/projectkudu/KuduSync.NET/blob/5ff87c07d69ed7ce250267d4657c262c89dd547b/KuduSync.NET/KuduSync.cs#L197-L208)), it should never overwrite web.config if the source and destination have the same content. And here, the 'source' normally is not what's in the repo, but already has the transforms.

How exactly are you doing your transform? Are you starting with the repo file, changing it and saving it to wwwroot? Or doing it in place in wwwroot?

**Comment by sitereactor** [comment]
We used to apply it to web.config directly in the wwwroot. But with the recent updates to KuduSync it sounds like we should maybe use the temporary folder where the git checkout is done. It sounds like the compare is between the "temp" location and wwwroot. Is that correct or?

(And just to clarify we have both a repository and a wwwroot - we don't use the in-place the repository option).

**Comment by davidebbo** [comment]
First to clarify one thing: the recent KuduSync changes should not have made anything worse, as before that it would have always copied the file anyway.

@sitereactor Yes, I believe that's the correct thing to do. We you're doing is really a deployment step, so it should be done as part of deployment and not post deployment. It should be part of the main deployment script, and make changes to `%DEPLOYMENT_TEMP%`. I'm pretty sure this will make things work the way you want.

**Comment by mikkelhm** [comment]
We agree that the changes to KuduSync hasn't changed the behaviour of copying the file, and i agree it has been changed for the better. 

Looking at what the deploy.cmd is created, and used, it makes sense that it would work for the MVC projects, as when a project is deployed by using msbuild, og builds+transforms it into a `DEPLOYMENT_TEMP` directory, and from there it does kudusync to the webroot. This ensures that the web.config files that are compared are the ones that have already been transformed.

In our case we are using the `SCM_SCRIPT_GENERATOR_ARGS = --basic` params, which turns on the basic deploy script, which only does the KuduSync from repository to webroot. 

Our transform is done by having a .cmd in the a post deployment hook, which runs
`%TRANSFORM_PATH%\ctt.exe source:%DEPLOYMENT_TARGET%\Web.config transform:%TRANSFORM_PATH%\Web.Transform.config destination:%DEPLOYMENT_TARGET%\Web.config`

This transforms the web.config, but also makes it different than the one in the repository that is compared in KuduSync

**Comment by davidebbo** [comment]
I think your best option here is a switch from using `SCM_SCRIPT_GENERATOR_ARGS` to using a full custom deployment script. Then you just need to apply your transform from within the deploy script, modifying the file in the repo (not wwwroot) just before the kudusync call.

**Comment by mikkelhm** [comment]
Is it possible to set this globally(which was one of my initial questions), so we don't have to speciy in each sites .deployment file? i.e. can `SCM_SCRIPT_GENERATOR_ARGS` have an arg that points to a specific script? I'm having a little trouble finding the proper way to implement it

**Comment by davidebbo** [comment]
If you don't want a `.deployment` file in your repo, you can instead set a `COMMAND` Azure App Setting pointing to your custom script (e.g. set it to `deploy.cmd` if your script is at the repo root). So all you have to do is add your deploy script to your repo.

**Comment by mikkelhm** [comment]
That might be the solution, thank you so much for you effort @davidebbo it is greatly appreciated, will test this out first thing on monday

**Comment by davidebbo** [comment]
Though I must say I don't quite follow something: if you're going to add a deploy.cmd at the root of your repo, why is it much harder to also commit a .deployment file next to it?

**Comment by mikkelhm** [comment]
Oh i think i misread then, i thought of adding a global deploy.cmd and point the app setting to that one, making us having only one script. 

It is true, if we need to add a deploy.cmd to each repo, its the same issue/problem as with the .deployment file. and I actually think the .deployment file would be the better approach.

We would like for it to be an app setting setting the script some where globally. That way we could ensure that it isn't too easy to change which script to use, and we control the script one place only

**Comment by davidebbo** [comment]
So stepping back, today you use a post deployment script. How are you making it global? Doesn't it need to exist in each site?

**Comment by mikkelhm** [comment]
Nope, it is simply set in an app setting to
`POST_DEPLOYMENT_ACTIONS_DIR = C:\kudu\artifacts\` which then contains the scripts that are run. We are having multiple web workers, so we ensure that each worker has the folder with the scripts located in them.

**Comment by davidebbo** [comment]
Oh, I forgot that you were using Azure Pack. On Azure, there is no way to have such shared file on the local drive. But if you can do that, I think you can simply set `COMMAND` to some global script, e.g. `c:\kudu\shareddeploy,cmd`. Give it a shot.

**Comment by mikkelhm** [comment]
cool, I will test it out.. as said.. first thing monday :-) thanks again
