### ISSUE TITLE
Deployment Taking a Long Time

### ISSUE THREAD

**Issue by ssinno28** [projectkudu/kudu#1784]
Hello,

This is my first time using kudu to deploy my site and I'm having issues with the deployment taking 15-20 minutes. I've been trying to find the source of the problem in the logs, but the only thing I can see in there is that there is some operation before the web config being transformed that is taking about 15 minutes:

```
2015-11-01T23:33:44.9834010Z,  Orchard.Web -> D:\home\site\repository\src\Orchard.Web\bin\Orchard.Web.dll,,0
2015-11-01T23:48:32.9594536Z,  Transformed Web.config using D:\home\site\repository\src\Orchard.Web\Web.examplesite.config into obj\ihaforumv2\TransformWebConfig\transformed\Web.config.,,0
```

Here is how my msbuild command is set up in the deploy script:

```
:: 2. Build to the temporary path
IF /I "%IN_PLACE_DEPLOYMENT%" NEQ "1" (
  call :ExecuteCmd "%MSBUILD_PATH%" "%DEPLOYMENT_SOURCE%\src\Orchard.Web\Orchard.Web.csproj" /nologo /verbosity:m /t:Build /t:pipelinePreDeployCopyAllFilesToOneFolder /p:_PackageTempDir="%DEPLOYMENT_TEMP%";AutoParameterizationWebConfigConnectionStrings=false;Configuration=%APPSETTING_WEBSITE_SITE_NAME% /p:SolutionDir="%DEPLOYMENT_SOURCE%\src\\" %SCM_BUILD_ARGS%
) ELSE (
  call :ExecuteCmd "%MSBUILD_PATH%" "%DEPLOYMENT_SOURCE%\src\Orchard.Web\Orchard.Web.csproj" /nologo /verbosity:m /t:Build /p:AutoParameterizationWebConfigConnectionStrings=false;Configuration=%APPSETTING_WEBSITE_SITE_NAME% /p:SolutionDir="%DEPLOYMENT_SOURCE%\src\\" %SCM_BUILD_ARGS%
)
```

I'm not using the orchard precompile build task so, I don't believe it should be taking this long.

**Comment by davidebbo** [comment]
How exactly are you deploying it. Are you using the standard repo and git pushing it to a Web App? If you are using a modified clone, can you share it?

Also, can you share your site name, either directly or [indirectly](https://github.com/projectkudu/kudu/wiki/Reporting-your-site-name-without-posting-it-publicly)? This will help us investigate. Thanks!

**Comment by Skelet0r67** [comment]
Right now I am just testing with my local git repo by pushing to the azure remote. The site name is ihaforumv2

**Comment by davidebbo** [comment]
It seems that this 15 minute step is part of the Orchard build process. @sebastienros, how long does it usually take to deploy Orchard to Azure Web App via git?

@Skelet0r67, I'm still not clear whether your local git repo is just a clone of the Orchard repo, or some highly modified version. Also, is it this slow on every deployment, or just the initial one?

**Comment by sebastienros** [comment]
@Skelet0r67 please let us know if you are using 1.9.2 which contains a recommended deployment script for Orchard on Kudu, and if not you should try with it. 

The fact is it might not be much faster as the build process implies copying lots of files with Orchard, and filesystem access is not super fast on the virtual filesystem that Kudu runs on, so it's making things worse. But let's first see if the official one makes things better.

**Comment by Skelet0r67** [comment]
@davidebbo This is a highly modified version, we have a lot of custom modules added to the solution; although, we haven't really modified any core code. It is also slow on every deployment.

@sebastienros we are on Orchard v.1.9.1.0 at the moment. I can upgrade first thing tomorrow and use the new deploy script. I'll let you know how things go.

**Comment by sebastienros** [comment]
You don't need to upgrade to 1.9.2 in full, just grab the necessary files here:
https://github.com/OrchardCMS/Orchard/blob/dev/.deployment
https://github.com/OrchardCMS/Orchard/blob/dev/deploy.cmd

**Comment by Skelet0r67** [comment]
I'm having trouble getting the deploy to finish without erroring out.. here is the error that I am receiving: 2015-11-05T01:55:40.0724231Z,An unknown error has occurred. Check the diagnostic log for details.,31181e92-40e0-4ad0-86dc-91a65327aa38,2

Where exactly is the diagnostic logs?

**Comment by davidebbo** [comment]
One thing that might lead to that is if you use a Free/Shared site and it runs out of CPU quota during the deployment (since the deployment is heavy). That would cause the site to get shutdown and kill the deployment.

**Comment by Skelet0r67** [comment]
we are actually on standard right now

**Comment by Skelet0r67** [comment]
I can try again and see if we have enough resources for the deployment

**Comment by Skelet0r67** [comment]
I know its been a while since responding, I actually had to work on a few other things before I could go back and take a look at this... it seems the error was simply related to a solution file not being in the repo:

2015-11-11T17:03:51.3659269Z,D:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\WebApplications\Microsoft.WebApplication.targets(182&comma;5): error MSB3030: Could not copy the file "Styles\Styles.css" because it was not found. [D:\home\site\repository\src\Orchard.Web\Themes\IHAF\IHAF.csproj],,0

So I added dotless and am not compiling the styles.less file before we build and deploy, but it is still taking an extremely long time to deploy.

@sebastienros I did a deploy precompiled and it took 40 minutes, I see there are other builds I can target (like FastBuild) do you think that would make a difference? I have the FastBuild target running right now, but it's already been 23 minutes since it started..

**Comment by Skelet0r67** [comment]
Does it make sense to just build and deploy the Orchard.Web.proj instead of Orchard.proj in the solution root? It seems like there is a lot going on when using the Orchard.proj file to build.. Even the FastBuild target took about 45 minutes when deploying to azure.

**Comment by Skelet0r67** [comment]
@davidebbo any other suggestions? I'd really like to take advantage of this feature, but it doesn't seem viable at the moment due to the extremely long deploys.

**Comment by davidebbo** [comment]
I think first step is to isolate whether this slowness happens with the standard Orchard repo, or is specific to your modified repo.

**Comment by jvano** [comment]
Hi

Kudu will continue to run in Azure App Service. However, this repo will no longer be maintained.
If the problem persists and is related to running on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
