### ISSUE TITLE
Add support for crash dumps

### ISSUE THREAD

**Issue by davidebbo** [projectkudu/kudu#1785]
Today, our Process Explorer lets you take a dump of its current state. Often users also need a crash dump.

We can achieve this via `procdump -t`. e.g. UI could be:
- Go to process explorer
- Right click a process and choose 'enable Crash Dump'
- Then on crash it would go in some well known folder

**Comment by ahmelsayed** [comment]
do you happen to know if these tools exist in the same place in WAP?

**Comment by davidebbo** [comment]
You mean in `d:\devtools\sysinternals`, right? Good question, I don't know. We should ask. If not, I guess we can do detection and light up?

**Comment by ahmelsayed** [comment]
yea, I wanted to check first before complicating things.

**Comment by suwatch** [comment]
One idea is to put  d:\devtools\sysinternals in the path (DWAS fix).  It will be last in the path to minimize regression.  Our kudu codes could check if exists in the path to light up feature.   Public kudu can override etc.   

Have we thought about REST apis?  For instance, ...

- Start procdump.   POST /api/processes/{id}/crashdump.   To not run forever, a timeout on how long it will monitor.  
- List crash dumps.   GET /api/crashdumps
- Get crash dump.   Get /api/crashdumps/{pname}-{time}.  We want to return zip (crash dump zip ratio is efficient).  We might compress it at storing time.
- Delete crash dump.   DELETE /api/crashdumps/{pname}-{time}.  We will also auto GC the dump files. 
- (Perhaps) Analyze crash dump.   POST /api/crashdumps/{pname}-{time}/analyze.   (!analyze -v).  This is useful, client side no need tooling at all.

Support to safe dump to blob storage etc.

**Comment by ahmelsayed** [comment]
thanks for the feedback. I'll implement these. 

What's an appropriate timeout? I thought this scenario is meant to launch it to wait forever. One problem is that killing `procdump.exe` will kill the process it's attached to. To make it not do that, you have to send `CTRL-C` signal which doesn't work in Azure.

**Comment by ahmelsayed** [comment]
Also right now I call `procdump.exe -t`, this creates a dump with only thread and handle information. `-ma` will include process memory. I think this is more useful, but the dumps will be significantly bigger. Thoughts?

**Comment by suwatch** [comment]
For timeout, don't kill it then.  It will just run forever.   

For -ma, it should be optional (not default) - eg thru query string.   We did the same for /processes/{id}/dump.  You can borrow the sematic.
