### ISSUE TITLE
Diagnostics setting api should validate the input such as TraceLevel.

### ISSUE THREAD

**Issue by suwatch** [projectkudu/kudu#1786]
In addition, it should attempt to auto-correct the file if contained invalid value.

**Comment by shrimpy** [comment]
I can work on this issue. two things need to be done i think:

 - during PUT, if there is invalid value, exception will be thrown. once we have this, the code path or scenario that place wrong value into setting file will surface themselve

 - during GET, if any value not in right format, we re-set  it to default value
