### ISSUE TITLE
Feature request: UI button to create new file

### ISSUE THREAD

**Issue by snobu** [projectkudu/kudu#1788]
We need a `New File` UI button in DebugConsole, next to the new folder __+__ glyph.

![image](https://cloud.githubusercontent.com/assets/6472374/10979068/f6c23af8-8402-11e5-9495-3528d81e7001.png)

Sure you can do a `touch filename.php` right now and get a new file but how many people know about that?

These glyphs look a bit dull but should do the job:
http://marcoceppi.github.io/bootstrap-glyphicons/

icon-file
![image](https://cloud.githubusercontent.com/assets/6472374/10979253/1bf1b3f2-8404-11e5-9c09-afca078ae8a8.png)

icon-folder-plus
![image](https://cloud.githubusercontent.com/assets/6472374/10979617/1c693880-8406-11e5-858d-daf0069953a8.png)

Or maybe we can raise a context menu when __+__ is clicked to pick between `file` and `folder`.

**Comment by snobu** [comment]
If i'm reading the API right, this should do it:

FileBrowser.js
```javascript
        createFolder: function (file) {
            return $.ajax({
                url: file.href.replace(/#/g, encodeURIComponent("#")),
                method: "PUT"
            });
        }
```

https://github.com/projectkudu/kudu/wiki/REST-API
```
PUT /api/vfs/{path}
Puts a file at path.

PUT /api/vfs/{path}/
Creates a directory at path. The path can be nested, e.g. `folder1/folder2`.
```

**Comment by badescuga** [comment]
@snobu don't bother yourself with the details.. i got this.





On Thu, Nov 5, 2015 at 11:40 AM -0800, "Adrian Calinescu" <notifications@github.com> wrote:












If i'm reading the API right, this should do it:



FileBrowser.js

        createFolder: function (file) {
            return $.ajax({
                url: file.href.replace(/#/g, encodeURIComponent("#")),
                method: "PUT"
            });
        }



https://github.com/projectkudu/kudu/wiki/REST-API

PUT /api/vfs/{path}
Puts a file at path.

PUT /api/vfs/{path}/
Creates a directory at path. The path can be nested, e.g. `folder1/folder2`.

**Comment by davidebbo** [comment]
Covered by PR #2124
