### ISSUE TITLE
Deployment Fails for AspNet5/Beta 8 Sites Targetting dnxcore50

### ISSUE THREAD

**Issue by MisterJames** [projectkudu/kudu#1789]
`dnu` fails at the last step with an error of "The project being published does not support the runtime". The project is created with the Beta 8 tooling as an empty web project in an existing solution (therefore, no global.json).

The workaround (thanks to @damienedwards) is to add a global.json to the solution and to add the following:

```
{
  "projects": [ "src", "test" ],
  "sdk": {
    "version": "1.0.0-beta8",
    "runtime": "coreclr"
  }    
}
```

However, it is not recommended to have to specify the `runtime` as part of the `sdk` object/element.

**Comment by davidebbo** [comment]
You don't need the `runtime`. I don't have it in my [test app](https://github.com/davidebbo-test/AspNet5Beta8/blob/master/global.json), and it deploys fine to Kudu.

**Comment by ahmelsayed** [comment]
why is it not recommended to specify the runtime in the sdk object? My understanding was that's exactly tge purpose of the sdk object in global.json

**Comment by MisterJames** [comment]
@davidebbo Okay, good to know. However, the issue does still repro without the global.json present.

**Comment by jvano** [comment]
Hi

Kudu will continue to run in Azure App Service. However, this repo will no longer be maintained.
If the problem persists and is related to running on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
