### ISSUE TITLE
Deadlock when ExecuteAsync is called from an ASP.NET thread

### ISSUE THREAD

**Issue by ahmelsayed** [projectkudu/kudu#1793]
Calling [`ExecuteAsync`](https://github.com/projectkudu/kudu/blob/cf89f86fbe1c06ee81c21267eb36e68154ccfe08/Kudu.Core/Infrastructure/Executable.cs#L251) from an ASP.NET thread causes a deadlock in some scenarios. I'm not too sure what the cause is, but I think it's because of blocking the thread by calling  [`WaitForExit()`](https://github.com/projectkudu/kudu/blob/bc3b8917f5d6baaf65af8bb9f630ac6d34bf9cdd/Kudu.Core/Infrastructure/IdleManager.cs#L43) on the same thread. I need to debug it more.

**Repro**: run the following on an ASP.NET thread

``` csharp
public async Task<HttpResponseMessage> Function()
{
    var exe = new Executable("someExeWithALongOutput.exe", _environment.RootPath, _settings.GetCommandIdleTimeout());
    using (MemoryStream outputStream = new MemoryStream(), errorStream = new MemoryStream())
    {
        var exitCode = await exe.ExecuteAsync(_tracer, $"args", outputStream, errorStream);
        return Request.CreateResponse(HttpStatusCode.OK, new { output = outputStream.AsString() });
    }
}
```

**Workaround**: Call it from a threadpool thread e.g: `Task.Run()`

**Comment by jvano** [comment]
Hi

Kudu will continue to run in Azure App Service. However, this repo will no longer be maintained.
If the problem persists and is related to running on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
