### ISSUE TITLE
Can we ship dig.exe in Kudu?

### ISSUE THREAD

**Issue by snobu** [projectkudu/kudu#1797]
This is probably more a Web Apps thing, but here it goes anyway:

![image](https://cloud.githubusercontent.com/assets/6472374/11091046/bd8e5c40-887f-11e5-9cc1-e6eeb4906de3.png)

Works fine, we just need `dig.exe` and a bunch of .DLLs from this BIND9 package:
https://www.isc.org/downloads/file/bind-9-10-3/?version=win-32-bit

**Comment by davidebbo** [comment]
Probably something that could go under `d:\devtools` rather than Kudu. There are various things in there already.

**Comment by ahmelsayed** [comment]
we could also [put the tools there on the path](https://github.com/projectkudu/kudu/blob/bc3b8917f5d6baaf65af8bb9f630ac6d34bf9cdd/Kudu.Core/Deployment/Generator/ExternalCommandFactory.cs#L92-L109) for the console. Right now you have to know where they are or type the full path.

**Comment by davidebbo** [comment]
Yes, we should do this. Note that it's in multiple folders, though `d:\devtools\sysinternals` is where the meat is.

**Comment by snobu** [comment]
Is this a safe way to tell which libs dig.exe is loading?
![image](https://cloud.githubusercontent.com/assets/6472374/11100416/c8dcbc74-88b9-11e5-9a0e-d9a18080701e.png)

It does seem to work with just this short list:
```
libisc.dll
libdns.dll
libeay32.dll
libbind9.dll
libisccfg.dll
liblwres.dll
```

On Linux there's `strace` which does this:
![image](https://cloud.githubusercontent.com/assets/6472374/11100535/7f0a3d8c-88ba-11e5-97db-628b7748675d.png)

Is there an "strace" for Windows?
I know Process Explorer (Sysinternals) does just that but it's not CLI.

`listdlls.exe` seems very similar to what `strace` does but i can't get it to work.
`/accepteula` does nothing.

```cmd
D:\devtools\sysinternals>listdlls.exe
listdlls.exe

D:\devtools\sysinternals> 

D:\devtools\sysinternals>listdlls.exe /accepteula
listdlls.exe /accepteula

D:\devtools\sysinternals>
```

It does pop up an EULA on first run on my desktop.

**Comment by davidebbo** [comment]
Kudu Process Explorer should give correct data. Note that many of the listed libs are system things, so you don't need to include them. You can get the full path to the lib if you click the More button.

**Comment by snobu** [comment]
Got it.

This is the full list.

```
dig.exe
host.exe
libisc.dll
libdns.dll
libeay32.dll
libbind9.dll
libisccfg.dll
liblwres.dll
libxml2.dll
```

Hey even DNSSEC validation works!
```cmd
D:\home\LogFiles>dig isc.org +dnssec +multi

; <<>> DiG 9.10.3 <<>> isc.org +dnssec +multi
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 19537
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags: do; udp: 1280
;; QUESTION SECTION:
;isc.org.		IN A

;; ANSWER SECTION:
isc.org.		60 IN A	149.20.64.69
isc.org.		60 IN RRSIG A 5 2 60 (
				20151210182703 20151110182703 6003 isc.org.
				MtYSZZRKuerhlpyyr5sVAx3ZHOiviFdGFpcCDiLMnZa+
				MNrMbtk7NxY2YIRwnPSTKvw7K99A3mYErfwHe6S0mqYp
				gG1Woi6nzIQJMW+y5fF+IB4rn8yk+TLmlZYHI2zu8Trn
				5q020inTfpY9mVR6FiVrg7qtq3YMQ0qQZ+ZtHXU= )

;; Query time: 31 msec
;; SERVER: 10.20.37.72#53(10.20.37.72)
;; WHEN: Wed Nov 11 20:04:20 Coordinated Universal Time 2015
;; MSG SIZE  rcvd: 219
```

Here's the custom package (minimal_dig.zip):
http://ge.tt/api/1/files/6X1KnbR2/0/blob?download

**Comment by snobu** [comment]
Hmm actually DNSSEC validation works (`ad` flag) but only against a server that supports it. But i digress.

```
D:\home\LogFiles>dig @8.8.8.8 isc.org +dnssec +multi

; <<>> DiG 9.10.3 <<>> @8.8.8.8 isc.org +dnssec +multi
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 17223
;; flags: qr rd ra ad; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1
```

**Comment by ahmelsayed** [comment]
the closest strace like tool for windows would be procmon.exe you can setup filters for directories and processes and get a list of all the files accessed by a given process.

**Comment by snobu** [comment]
Thanks, i've used Kudu's Process Explorer, it did a great job.

**Comment by ahmelsayed** [comment]
:+1:

**Comment by snobu** [comment]
I've made a repo in case this gets accepted into the project:
https://github.com/snobu/minimaldig4kudu

**Comment by jvano** [comment]
Hi

Kudu will continue to run in Azure App Service. However, this repo will no longer be maintained.
If the problem persists and is related to running on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
