### ISSUE TITLE
clear up master.lock 

### ISSUE THREAD

**Issue by shrimpy** [projectkudu/kudu#1798]
One customer report he failed to push content to his local git repo. after investigate we found the "master.lock" file was there causing the issue.

we have logic go clean other lock file, we may as well as to do the same to clean up master.lock.

**Comment by davidebbo** [comment]
Yes, I thought we were already doing that. Is master.lock something we create, or something git creates?

**Comment by suwatch** [comment]
It is what git created.  Somehow it got left over.   We just need to add it to [this list](https://github.com/projectkudu/kudu/blob/master/Kudu.Core/SourceControl/Git/GitExeRepository.cs#L30).    We are still investigating what led this.

**Comment by shrimpy** [comment]
One issue is, this lock is per branch. i think it is ok to add "master.lock" to our [cleanup list](https://github.com/projectkudu/kudu/blob/master/Kudu.Core/SourceControl/Git/GitExeRepository.cs#L30), since most of git user will have master branch. 

but if issue happen on a different branch, we will have to advice to manually remove it as work-around

or we clear all the locks under "refs/heads" when we perform [cleanup](https://github.com/projectkudu/kudu/blob/master/Kudu.Core/Infrastructure/DeploymentLockFile.cs#L35)

I suggest to clear all the locks under "refs/heads". what do you think? @davidebbo @suwatch

**Comment by davidebbo** [comment]
That sounds reasonable to me (with proper logging). We have our own lock, and there shouldn't be any operations going on that we're not aware of. Well, I guess it could happen if use does git commands using Kudu Console while a deployment is happening, but that's a bit of an edge case.
