### ISSUE TITLE
WebJobs Api Stop Start Settings always 403 Forbidden. 

### ISSUE THREAD

**Issue by kevinneufeld** [projectkudu/kudu#1801]
$username = "`$website"     #from publish settings file
    $jobname = "ContinuousJobName"
    $password = "hskjhskhskhkj" #from publish settings file
    $base64AuthInfo = [Convert]::ToBase64String([Text.Encoding]::ASCII.GetBytes(("{0}:{1}" -f  $username,$password)))
    $apiUrl = ("https://{0}.azurewebsites.net/api/continuouswebjobs/{1}/stop" -f {site},$jobname)
    try{
	    $r  = Invoke-RestMethod -Uri $apiUrl -Headers @{Authorization=("Basic {0}" -f $base64AuthInfo)} -Method POST;
    }catch{
	    $r = $_;
    }

Using the above sample code and publish settings files for credentials, the api returns 403 forbidden.  I have been using this pattern for all the other webjob api endpoints without issue. 

Any ideas? 

Is the problem my credentials, (which one to use?), or a possible issue with these 3 endpoints.

**Comment by ahmelsayed** [comment]
I don't see any issues with your script. If you're sure of your username and password, making sure to escape any powershell special characters in there, the next step would be to share your site name either directly or [indirectly](https://github.com/projectkudu/kudu/wiki/Reporting-your-site-name-without-posting-it-publicly)

**Comment by kevinneufeld** [comment]
Thanks, I download the publish profile again for the website. The UID and PWD were correct, tested against `DELETE /api/continuouswebjobs/{job name}` and it completed with out issue.

I have setup a dummy site, `dcl-dummy-site`, any insight is greatly appreciated.

**Comment by davidebbo** [comment]
Is the issue on your appveyor slot or the main site?

**Comment by ahmelsayed** [comment]
/cc @suwatch 

Add `-ContentType "application/json"` to your `Invoke-RestMethod`, also make sure you have `.scm.` in the URL.

**Comment by kevinneufeld** [comment]
Thanks.  it was the `-ContentType "application/json"`

**Comment by viclin-msft** [comment]
5 years later and I had the same issue. Providing at least one of these options worked for me:

- `-ContentType "application/json"`
- `-UserAgent "powershell/1.0"`
