### ISSUE TITLE
/deploy returns 500 Internal Server Error even when deployment was successful

### ISSUE THREAD

**Issue by vkoltovich** [projectkudu/kudu#1802]
I use deploy API  with a basic payload to start a new deployment of my node js application.
https://my_site.scm.azurewebsites.net/deploy
{
"url": my git repo url,
"format":  "basic",
 "scm":  "git"
}
Kudu deployment start well and finishes successfully but API returns 500 Internal Server Error after 5 minutes of waiting.
Is there a way to increase a timeout to accommodate longer deployments? Or another options is to kick a deployment, get Id and return immediatelly and then check on status periodically through other methods?

**Comment by suwatch** [comment]
Try getting the dump,  https://my_site.scm.azurewebsites.net/dump and look at `logFiles/kudu/traces` might yield some clues.   Share us the site name, we can help look as well. 

Currently `/deploy` is blocked till it is done.  Yes, we could conceivably allow knobs to say doing it in the background till done and give out DeploymentId (or link href) to poll for status.

More tips and tricks [here](https://github.com/projectkudu/kudu/wiki/Investigating-issues)

**Comment by vkoltovich** [comment]
Thanks, Suwat.  Traces are empty and deployments are actually successfully completed. You can have a look at https://pleexy-app-int.scm.azurewebsites.net. 
The problem is that API returns 500 before deployment is completed.

**Comment by suwatch** [comment]
Looking at the log, the deployment took very long time (> 10 mins).   For long request, we have a rule to terminate it after a certain timeout (hence the 500).   As you noticed the deployment did succeed.  

The reason we could not find anything in kudu traces because `POST /deploy` was originated from browser (we want keep the traces not too noisy).  How did you perform `POST /deploy`, from one of our portals?

As for workaround, you could just fire `POST /deploy` and forget; then, poll the `GET /api/deployments` instead.   Your most recent deployment activity will be the first on the list.

**Comment by vkoltovich** [comment]
Yes, it runs for sometime, but is it an unusual time for a deployment script? I mean, if I deploy node js application, that has to install npm/bower packages, this time seems to be reasonable. It can take more, actually.
POST /deploy is called from Poweshell script that runs on VisualStudio Online Build.vnext
$payload = @{
    format="basic"
    url=$repoUrl
    scm="git" 
}
$jsonPayload = $payload | ConvertTo-Json
$response = Invoke-WebRequest -Uri $websiteDeployUrl -Body $jsonPayload -Headers @{Authorization=("Basic {0}" -f $base64AuthInfo)} -Method POST -ContentType 'application/json' -UseBasicParsing -TimeoutSec 3000

As for suggested workaround, that would mean that I have to ignore result of POST /deploy (success or error) and try to understand whether or not deployment started successfully by analyzing GET /api/deployments results. This already doesn't look like a reliable solution. 
if there was I way to tell POST /deploy to return immediately after successful start of deployment, that would work much better.

**Comment by suwatch** [comment]
unfortunately we have no such option today.  we will discuss how best to support this.  we will keep you up-to-date.

**Comment by vkoltovich** [comment]
Thanks, Suwat. When should I expect to hear from you on that?

**Comment by suwatch** [comment]
We are pretty booked for the next few weeks.  We will try to see if we can allocate any time before end of year.

**Comment by shrimpy** [comment]
same as in  #1812? shall we closed this as well? @suwatch @davidebbo

**Comment by suwatch** [comment]
Please close it.  Thanks.

Sent from my Windows Phone
________________________________

**Comment by suwatch** [comment]
Reopen.   This is slightly different as it will have to be an async pattern.

**Comment by suwatch** [comment]
@vkoltovich  we have provided a support as follow.   

  - Additional query string `isAsync=true` can be passed when `POST /deploy`.   This will cause the deployment to happen in the background and the POST call will return  `202 Accepted`. 

  -  The response `Location` header will indicate where to poll (`GET`) for deployment status.   If the deployment is still ongoing, it will return `202 Accepted` and response body will contain the pending deployment result.   One should continue to poll the `Location`.

  - Once the deployment is completed (success or fail), the call will return `200 OK`.   To determine if  deployment succeeded or failed, do look at the deployment's status flag.

**Comment by vkoltovich** [comment]
Thank you, @suwatch. It works well now!
