### ISSUE TITLE
Kudu Rest Api Credential issue for VFS.

### ISSUE THREAD

**Issue by kevinneufeld** [projectkudu/kudu#1804]
```
$username = "`$website"
$password = "pwd"
$base64AuthInfo = [Convert]::ToBase64String([Text.Encoding]::ASCII.GetBytes(("{0}:{1}" -f $username,$password)))

$apiUrl = "https://{sitename}.scm.azurewebsites.net/api/vfs/site/wwwroot/"
Invoke-RestMethod -Uri $apiUrl -Headers @{Authorization=("Basic {0}" -f $base64AuthInfo)} -Method GET -ContentType "application/json";
```

Following your PS example with a the following change: 
- Endpoint: `api/vfs/site/wwwroot/` 
- ContentType: `"application/json"`

I have tried 4 different sets of Credentials: 
1. Deployment Credentials (my azure creds)
2. Deployment Credentials (azure AD creds) 
3. PublishProfile
4. Site's own deployment creds.

It either returns a 401 or i get the contents of the redirect page to login. 

Must be something simple I am missing.

**Comment by davidebbo** [comment]
Please see https://github.com/projectkudu/kudu/wiki/Deployment-credentials for details on the two kind of credentials that are valid to talk to the scm site.

**Comment by davidebbo** [comment]
Also, to isolate from PowerShell, please first test your credentials by going to https://{sitename}.scm.azurewebsites.net/basicauth in the browser.
