### ISSUE TITLE
Support git fetch git-lfs large files

### ISSUE THREAD

**Issue by suwatch** [projectkudu/kudu#1805]
see https://github.com/github/git-lfs/issues/640 and https://git-lfs.github.com/

This is scoped to just github lfs support.  In short, we need to preform `git lfs fetch` after `get fetch` (to be exact after `git update-ref`).   We might need a knob directive to explicitly tell us to do that (eg. appSettings SCM_GIT_LFS_FETCH = 1).

To get the `git lfs` command extension, we need to have [git lfs plugin](https://git-lfs.github.com/) installed.

**Comment by ejsmith** [comment]
This would be awesome! Can you please add support for this? It seems like it would be a pretty small change and a big win especially in the .net community where we are deploying assemblies.

**Comment by niemyjski** [comment]
+1

**Comment by suwatch** [comment]
If you have a public repo exercising lfs, please share with us.   Once we add support, we can verify against it.

**Comment by davidebbo** [comment]
Also, this probably won't work with libgit2sharp till https://github.com/libgit2/libgit2sharp/issues/1236 is fixed.

**Comment by niemyjski** [comment]
Yeah, we'd be more than happy to give you access to our build repo. When the time comes could you send me a private message in our gitter (https://gitter.im/exceptionless/Discuss)

**Comment by davidebbo** [comment]
@niemyjski: @suwatch was referring to some minimal public repo. e.g. it can be literally a trivial repo that pulls in a single file via lfs.

**Comment by suwatch** [comment]
Sorry for not being clear.  I have the trivial repo that I used for testing basic LFS.  I just want more coverage with one from real users to get us more confident on the support.   If you have a private repo, then we will likely to ask you to test for us etc.

**Comment by ejsmith** [comment]
GitHub supports LFS on all of their repos.

**Comment by suwatch** [comment]
FYI: this is my trivial one when I played around with it a couple of month ago.  (https://github.com/suwatch/lfstest).

**Comment by davidebbo** [comment]
When I go to https://git-lfs.github.com/ and click the Download button, I get a 404. That's not a good sign!

**Comment by davidebbo** [comment]
Ok, the links from https://github.com/github/git-lfs/releases/tag/v1.1.1 seem to work. e.g. the Windows installer is https://github.com/github/git-lfs/releases/download/v1.1.1/git-lfs-windows-1.1.1.exe.

**Comment by ejsmith** [comment]
So does that mean it can be supported in Kudu?

**Comment by davidebbo** [comment]
Probably, it could be made to work. I this point I just wanted to try it locally on my machine as I have not used it before.

Note that in the meantime, you may be able to make this work using a custom deployment script.

**Comment by davidebbo** [comment]
Good news: we now have some preliminary support for this. There are a couple manual steps, but it's pretty easy to set up. To the following:

1. In the Azur App Setting, set `SCM_USE_LIBGIT2SHARP_REPOSITORY=0`. This is necessary because libgit2sharp doesn't support lfs yet: https://github.com/libgit2/libgit2sharp/issues/1236
2. Using Kudu Console, copy `git-lfs.exe` into your `D:\home\site\deployments\tools` folder. You can get it from [here](https://github.com/github/git-lfs/releases/). e.g. download the [Windows 386 zip](https://github.com/github/git-lfs/releases/download/v1.1.1/git-lfs-windows-386-1.1.1.zip). Eventually we'll get it installed on the VM, but for now it's bring-your-own.

And that's it, lfs should just work! Please let us know how this works for you.

**Comment by ejsmith** [comment]
Awesome! Thank you. I will give this a try.

**Comment by ejsmith** [comment]
Do you know if git-lfs.exe is included in the VM image now?

**Comment by davidebbo** [comment]
Not yet. First, we'd like to validate whether steps above are functional for everyone.

**Comment by stevehansen** [comment]
Any updates on this, using the manual steps does not work (anymore?)

**Comment by dhermyt** [comment]
Unfortunately not working for me.

`git-lfs/1.4.4 (GitHub; windows 386; go 1.7.3; git cbf91a9)
git version 2.8.1.windows.1

$ git-lfs.exe smudge data/corpora/stopwords/README
Error downloading object: data/corpora/stopwords/README (abc88589ff9db0518feec1f3127e2cec915adcd12d994cf3427fcadc2370197b)

Smudge error: Error buffering media file: Object not found on the server.: 
github.com/github/git-lfs/errors.newWrappedError
	c:/go/src/github.com/github/git-lfs/errors/types.go:166
github.com/github/git-lfs/errors.NewSmudgeError
	c:/go/src/github.com/github/git-lfs/errors/types.go:252
github.com/github/git-lfs/lfs.PointerSmudge
	c:/go/src/github.com/github/git-lfs/lfs/pointer_smudge.go:69
github.com/github/git-lfs/lfs.(*Pointer).Smudge
	c:/go/src/github.com/github/git-lfs/lfs/pointer.go:64
github.com/github/git-lfs/commands.smudgeCommand
	c:/go/src/github.com/github/git-lfs/commands/command_smudge.go:66
github.com/github/git-lfs/vendor/github.com/spf13/cobra.(*Command).execute
	c:/go/src/github.com/github/git-lfs/vendor/github.com/spf13/cobra/command.go:477
github.com/github/git-lfs/vendor/github.com/spf13/cobra.(*Command).Execute
	c:/go/src/github.com/github/git-lfs/vendor/github.com/spf13/cobra/command.go:551
github.com/github/git-lfs/commands.Run
	c:/go/src/github.com/github/git-lfs/commands/run.go:65
main.main
	c:/go/src/github.com/github/git-lfs/git-lfs.go:33
runtime.main
	c:/go/src/runtime/proc.go:183
runtime.goexit
	c:/go/src/runtime/asm_386.s:1612

ENV:
LocalWorkingDir=D:\home\site\repository
LocalGitDir=D:\home\site\repository\.git
LocalGitStorageDir=D:\home\site\repository\.git
LocalMediaDir=D:\home\site\repository\.git\lfs\objects
LocalReferenceDir=
TempDir=D:\home\site\repository\.git\lfs\tmp
ConcurrentTransfers=3
TusTransfers=false
BasicTransfersOnly=false
BatchTransfer=true
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic
UploadTransfers=basic
GIT_DIR=.git
GIT_PREFIX=
`

Any ideas?

**Comment by zvonicek** [comment]
Are there any news on this? I have problems with deploying LFS files, getting this error:

```Git LFS: (0 of 1 files) 0 B / 132.38 KB                                                                                                            
batch response: Unable to parse HTTP response for POST https://myapp.scm.azurewebsites.net:443/myapp.git/info/lfs/objects/batch: json: cannot unmarshal string into Go value of type lfsapi.ClientError
error: failed to push some refs to 'https://myapp.scm.azurewebsites.net:443/myapp.git'
```

**Comment by darthwalsh** [comment]
I used Kudu deployment from github, which "worked" except it had raw LFS text pointers instead of my images. In the Kudu debug console I ran `git lfs fetch` in the repository, then copied the LFS files back to wwwroot, and then the site worked correctly. The downside to this manual strategy is after each github commit is synced, the LFS pointers would come back.

It seems like it should be easy to add an option to restore LFS files (or just always restore?), in the same way that Azure DevOs builds has. In the end, I ended up using DevOps to set up CD (also, I wanted to run tests).

**Comment by JV-conseil** [comment]
Hi @davidebbo 👋

I've followed your guidelines👇

> Good news: we now have some preliminary support for this. There are a couple manual steps, but it's pretty easy to set up. To the following:
>
> 1. In the Azure App Setting, set `SCM_USE_LIBGIT2SHARP_REPOSITORY=0`. This is necessary because libgit2sharp doesn't support lfs yet: [git lfs support libgit2/libgit2sharp#1236](https://github.com/libgit2/libgit2sharp/issues/1236)
> 2. Using Kudu Console, copy `git-lfs.exe` into your `D:\home\site\deployments\tools` folder. You can get it from [here](https://github.com/github/git-lfs/releases/). e.g. download the [Windows 386 zip](https://github.com/github/git-lfs/releases/download/v1.1.1/git-lfs-windows-386-1.1.1.zip). Eventually we'll get it installed on the VM, but for now it's bring-your-own.
>
> And that's it, lfs should just work! Please let us know how this works for you.

Still I get the `git-lfs: not found` error

```bash
git-lfs smudge '***.docx': 1: git-lfs: not found
error: external filter 'git-lfs smudge %f' failed 127
error: external filter 'git-lfs smudge %f' failed
fatal: ***.docx: smudge filter lfs failed

/usr/bin/git checkout main --force
```

My System info ⚙️

> System up time: -6.12:57:07.6840000
> OS version: Unix 5.15.116.1
> 64 bit system: True
> 64 bit process: True
> Processor count: 2
> Machine name: ***
> Instance id: ***
> Short instance id: ***
> CLR version: 6.0.21
> System directory:
> Current working directory: /opt/Kudu
> IIS command line: /opt/Kudu/Kudu.Services.Web.dll
> -- <https://{site}.scm.azurewebsites.net/>

Here is the bash script I run into Kudu Console for a dual install Linux and Windows 👇

```bash
#!/usr/bin/env bash
# -*- coding: UTF-8 -*-
#
# author        : JV-conseil
# credits       : JV-conseil
# copyright     : Copyright (c) 2019-2023 JV-conseil
#                 All rights reserved
#
# Support git fetch git-lfs large files
# see: https://github.com/projectkudu/kudu/issues/1805#issuecomment-183030812
#
#====================================================
set -euxo pipefail
shopt -s extglob failglob

alias ls="ls -FGlAhp --color=auto"

cd "${HOME}/site/deployments/tools"

echo "Installing git-lfs-windows-386..." &&
  curl -JLO "https://github.com/git-lfs/git-lfs/releases/download/v3.4.0/git-lfs-windows-386-v3.4.0.zip" &&
  unzip git-lfs-windows-386-v3.4.0.zip &&
  mv git-lfs-3.4.0/git-lfs.exe git-lfs.exe &&
  chmod +x git-lfs.exe &&
  rm -rf ./*.zip &&
  rm -rf ./git-lfs-3.4.0 &&
  ls

echo "Installing git-lfs-linux-386..." &&
  curl -JLO "https://github.com/git-lfs/git-lfs/releases/download/v3.4.0/git-lfs-linux-386-v3.4.0.tar.gz" &&
  tar -xf git-lfs-linux-386-v3.4.0.tar.gz &&
  rm -rf ./git-lfs-linux-386-v3.4.0.tar.gz &&
  cp git-lfs-3.4.0/git-lfs git-lfs &&
  ls
```

It outputs

```bash
-rwxrwxrwx 1 nobody 11M Jul 26 15:40 git-lfs
drwxrwxrwx 2 nobody   0 Nov 29 20:03 git-lfs-3.4.0/
-rwxrwxrwx 1 nobody 11M Jul 26 15:35 git-lfs.exe
```

My system is `OS version: Unix 5.15.116.1` should I install [Linux 386](https://github.com/git-lfs/git-lfs/releases/download/v3.4.0/git-lfs-linux-386-v3.4.0.tar.gz) instead of [Windows 386](https://github.com/git-lfs/git-lfs/releases/download/v3.4.0/git-lfs-windows-386-v3.4.0.zip)❓

If I attempt to install `git-lfs` from [Linux 386](https://github.com/git-lfs/git-lfs/releases/download/v3.4.0/git-lfs-linux-386-v3.4.0.tar.gz) I got `Permission denied` 👇

```bash
. ~/site/deployments/tools/git-lfs-3.4.0/install.sh
install: cannot create regular file '/usr/local/bin/git-lfs': Permission denied
```

Also when following your instructions to [Easily downloading your current deployment script](https://github.com/projectkudu/kudu/wiki/Custom-Deployment-Script#easily-downloading-your-current-deployment-script), I do not find a `Tools menu` with `Download deployment script`.

**Comment by davidebbo** [comment]
@JV-conseil Sorry, I have not been involved with Kudu in many years, so I am not up to date on this. @suwatch or others may be better able to comment.

**Comment by jvano** [comment]
Hi

For Azure related issues, we are now recommending creating an Azure incident, so we can better track and assist on Azure related cases: https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

For this issue, I've just filed an internal workitem to track this for Azure App Service, so no need to file anything at this point.

Thanks,

Joaquin
