### ISSUE TITLE
Providing a way to receive webhooks or deployment notifications in site extension

### ISSUE THREAD

**Issue by jarroda** [projectkudu/kudu#1807]
I am creating a site extension that needs to receive the deployment webhook for the same site.  Currently the webhook is unable to hit my site extension because it is blocked by Kudu's basic auth security.  

Since this is an extension for the same site the webhook is coming from, could there be a way to POST to a site extension without going through this layer of security? Or is there another way to get this kind of notification?

**Comment by davidebbo** [comment]
This is a tough one to solve, and has come up once or twice before. While it seems like a no brainer, code running in the scm site has no easy way today to make an http request to itself because of the auth.

We've discussed possible approaches where the scm site would have some kind of token available that could be used to auth back to itself via http, but we never took that too far.

**Comment by jarroda** [comment]
The token would be a good way do it, especially if the extension could use the same token to access the scm site's REST APIs.  That would allow the extension to even register itself to receive the webhook.

Is there any chance of this feature being added in the near term?

**Comment by davidebbo** [comment]
Realistically, you should not expect that near term, as there are just too many other things going on, and this has not been a super high demand point. Though I still hope it will get done at some point.

And note that the work for this would not be in Kudu, but in some deeper part of Azure that deals with auth.

**Comment by jarroda** [comment]
10-4, Thanks.

I'll leave this issue to you to leave open or close out as you see fit.

**Comment by jvano** [comment]
Hi

Kudu will continue to run in Azure App Service. However, this repo will no longer be maintained.
If the problem persists and is related to running on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
