### ISSUE TITLE
Formatting error in Microsoft Edge browser

### ISSUE THREAD

**Issue by yooakim** [projectkudu/kudu#1809]
On a fresh installation of Windows 10 (latest) the "Kudu" logotype is formatted on top / behind other text on the pages. It doesn't look very nice :-)

![2015-11-20 2](https://cloud.githubusercontent.com/assets/862546/11294046/6df46cd2-8f60-11e5-852d-aabff66aac0f.png)

Minor issue but nevertheless worth looking at.

**Comment by davidebbo** [comment]
This was just fixed yesterday and will be in the next build. See https://github.com/projectkudu/kudu/pull/1808

**Comment by davidebbo** [comment]
The change is now live in Azure.
