### ISSUE TITLE
ASP.NET 5 RC1 breaks logic for determining web application projects

### ISSUE THREAD

**Issue by djmoody** [projectkudu/kudu#1810]
[AspNet5Helper](https://github.com/projectkudu/kudu/blob/a64937bdf4b5d329a16a6eebb97ddb7838b9e2df/Kudu.Core/Infrastructure/AspNet5Helper.cs#L14) determines whether an ASP.NET 5 project is a web application by the presence of `webroot` in project.json. However RC1 moves `webroot` to hosting.json ([see here](https://github.com/aspnet/Announcements/issues/94)), hence this logic is broken for projects targeting RC1. This causes deployment of RC1 projects to fail.

**Comment by davidebbo** [comment]
Yep, that's indeed broken, and we need to adapt the detection.

**Comment by davidebbo** [comment]
The change is now live in Azure.
