### ISSUE TITLE
POST /deploy from ci should return asap

### ISSUE THREAD

**Issue by suwatch** [projectkudu/kudu#1812]
`POST /deploy` from continuous deployment such as GitHub, should return 202 (accepted) when the payload is verified.  This is to not block or timeout the callers till fetch or actual deployment done (better use of resources for callers).   

Deployment status is available thru `/api/deployments`

**Comment by shrimpy** [comment]
@suwatch 
 
is this already fixed in https://github.com/projectkudu/kudu/commit/589de7325aa6c83a9bdafe7f07272530c06ae069
