### ISSUE TITLE
Deployment of NodeJs failed with native code modules.

### ISSUE THREAD

**Issue by robblovell** [projectkudu/kudu#1814]
Deployment of a nodejs application with native code modules fails in unpredictable ways.  Sometimes it succeeds, sometimes it fails, but fails in different ways.  

Here are a few failure traces:

```
remote: D:\home\site\wwwroot\node_modules\fibers>if not defined npm_config_node_gyp (node "c:\Program Files (x86)\npm\3.3.6\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild --release )  else (node  rebuild --release )
remote: ...
remote: Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
remote:   fibers.cc
remote:   coroutine.cc
remote: ........................................................
remote: ..\src\fibers.cc : fatal error C1902: Program database manager mismatch; please check your installation [D:\home\site\wwwroot\node_modules\fibers\build\fibers.vcxproj]
remote: ..\src\coroutine.cc : fatal error C1902: Program database manager mismatch; please check your installation [D:\home\site\wwwroot\node_modules\fibers\build\fibers.vcxproj]
remote: gyp ERR! build error
remote: gyp ERR! stack Error: `msbuild` failed with exit code: 1
remote: gyp ERR! stack     at ChildProcess.onExit (c:\Program Files (x86)\npm\3.3.6\node_modules\npm\node_modules\node-gyp\lib\build.js:270:23)
remote: gyp ERR! stack     at emitTwo (events.js:87:13)
remote: gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
remote: gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
```

Another: 

```
remote: D:\home\site\wwwroot\node_modules\fibers>if not defined npm_config_node_gyp (node "c:\Program Files (x86)\npm\3.3.6\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild --release )  else (node  rebuild --release )
remote: ..................................................................................................................
remote: gyp ERR! configure error
remote: gyp ERR! stack Error: `gyp` failed with exit code: 4294967295
remote: gyp ERR! stack     at ChildProcess.onCpExit (c:\Program Files (x86)\npm\3.3.6\node_modules\npm\node_modules\node-gyp\lib\configure.js:355:16)
remote: gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
remote: gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
remote: gyp ERR! System Windows_NT 6.2.9200
remote: gyp ERR! command "node" "c:\\Program Files (x86)\\npm\\3.3.6\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--release"
remote: gyp ERR! cwd D:\home\site\wwwroot\node_modules\fibers
remote: gyp ERR! node -v v0.12.6
remote: gyp ERR! node-gyp -v v3.0.3
remote: gyp ERR! not ok
remote: Build failed
remote: Command 'starter.cmd "D:\home\site\d ...' was aborted due to no output nor CPU activity for 60 seconds. You can increase the SCM_COMMAND_IDremote: UT app setting (or WEBJOBS_IDLE_TIMEOUT if this is a WebJob) if needed.
```

**Comment by robblovell** [comment]
Here is the package.json:

{
  "name": "FireFly-API",
  "author": "Robb Lovell",
  "version": "0.0.29",
  "scripts": {
    "start": "node ./server.js",
    "test": "jest"
  },
  "dependencies": {
    "android-gcm": "^0.1.5",
    "apn": "^1.7.5",
    "apnagent": "^1.1.3",
    "applicationinsights": "^0.15.2",
    "async": "^1.5.0",
    "backbone": "^1.2.1",
    "backbone-mongo": "^0.6.10",
    "backbone-rest": "^0.7.2",
    "body-parser": "~1.13.2",
    "cookie-parser": "~1.3.5",
    "cors": "^2.7.1",
    "debug": "*",
    "express": "~4.13.1",
    "jade": "~1.11.0",
    "less-middleware": "1.0.x",
    "mojio-js-sdk": "^4.0.4",
    "mongoose": "^4.2.0",
    "mongoose-schema-extend": "^0.1.7",
    "morgan": "~1.6.1",
    "request": "^2.65.0",
    "resourcejs": "^1.0.0",
    "serve-favicon": "~2.3.0",
    "timespan": "^2.3.0",
    "underscore": "^1.8.3"
  },
  "devDependencies": {
    "assert": "^1.3.0",
    "azure-cli": "^0.9.6",
    "chai": "^3.4.0",
    "coffee-script": "*",
    "concurrent-transform": "^1.0.0",
    "gulp": "^3.5.6",
    "gulp-coffee": "*",
    "gulp-concat": "^2.2.0",
    "gulp-jade": "^1.0.0",
    "gulp-minify-css": "^0.3.0",
    "gulp-rename": "^1.2.0",
    "gulp-sourcemaps": "^1.5.2",
    "gulp-tap": "*",
    "gulp-util": "^3.0.1",
    "jest": "^0.1.40",
    "jest-cli": "^0.7.1",
    "nock": "^3.1.0",
    "proxyquire": "^1.7.3",
    "shelljs": "^0.3.0",
    "should": "^7.0.2",
    "touch": "*"
  },
  "jest": {
    "scriptPreprocessor": "preprocessor.js",
    "testFileExtensions": [
      "coffee",
      "litcoffee",
      "coffee.md",
      "js"
    ],
    "moduleFileExtensions": [
      "coffee",
      "litcoffee",
      "coffee.md",
      "js"
    ]
  },
  "engines": {
    "node": "4.1.2",
    "npm": "3.3.6"
  }
}

**Comment by robblovell** [comment]
I removed the jest development dependency and the line "test": "jest" and other jest sections. I also remove backbone, backbone-rest, and backbone-mongo. Deploys now. 

The problem still occurs:
remote: D:\home\site\wwwroot\node_modules\fibers>if not defined npm_config_node_gyp (node "c:\Program Files (x86)\npm\3.3.6\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild --release )  else (node  rebuild --release )         
remote: ...................................................................................................................        
remote: gyp ERR! configure error         
remote: gyp ERR! stack Error: `gyp` failed with exit code: 4294967295        
remote: gyp ERR! stack     at ChildProcess.onCpExit (c:\Program Files (x86)\npm\3.3.6\node_modules\npm\node_modules\node-gyp\lib\configure.js:355:16)        
remote: gyp ERR! stack     at emitTwo (events.js:87:13)        
remote: gyp ERR! stack     at ChildProcess.emit (events.js:172:7)        
remote: gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)        
remote: gyp ERR! System Windows_NT 6.2.9200        
remote: gyp ERR! command "d:\\Program Files (x86)\\nodejs\\4.1.2\\node.exe" "c:\\Program Files (x86)\\npm\\3.3.6\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--release"        
remote: gyp ERR! cwd D:\home\site\wwwroot\node_modules\fibers        
remote: gyp ERR! node -v v4.1.2        
remote: gyp ERR! node-gyp -v v3.0.3        
remote: gyp ERR! not ok         
remote: Build failed

**Comment by robblovell** [comment]
I will share the repo after I have migrated some connection strings.

**Comment by robblovell** [comment]
removed azure-cli for kicks... have this error now: 
```
remote: D:\home\site\wwwroot\node_modules\fibers>if not defined npm_config_node_gyp (node "c:\Program Files (x86)\npm\3.3.6\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild --release )  else (node  rebuild --release )         
remote: ....................................................................................................................        
remote: gyp ERR! configure error         
remote: gyp ERR! stack Error: `gyp` failed with exit code: 4294967295        
remote: gyp ERR! stack     at ChildProcess.onCpExit (c:\Program Files (x86)\npm\3.3.6\node_modules\npm\node_modules\node-gyp\lib\configure.js:355:16)        
remote: gyp ERR! stack     at emitTwo (events.js:87:13)        
remote: gyp ERR! stack     at ChildProcess.emit (events.js:172:7)        
remote: gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)        
remote: gyp ERR! System Windows_NT 6.2.9200        
remote: gyp ERR! command "d:\\Program Files (x86)\\nodejs\\4.1.2\\node.exe" "c:\\Program Files (x86)\\npm\\3.3.6\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--release"        
remote: Command 'starter.cmd "D:\home\site\d ...' was aborted due to no output nor CPU activity for 60 seconds. You can increase the SCM_COMMAND_IDLE_TIMEOUT app setting (or WEBJOBS_IDLE_TIMEOUT if this is a WebJob) if needed.        
remote: 
remote: starter.cmd "D:\home\site\deployments\tools\deploy.cmd"        
remote: gyp ERR! cwd D:\home\site\wwwroot\node_modules\fibers        
remote: gyp ERR! cwd D:\home\site\wwwroot\node_modules\fibers        
remote: gyp ERR! node -v v4.1.2        
remote: gyp ERR! node-gyp -v v3.0.3        
remote: gyp ERR! not ok         
remote: Build failed        
remote: 
remote: 
remote: npm WARN EPEERINVALID mongodb-core@1.2.24 requires a peer of kerberos@~0.0 but none was installed.        
remote: npm WARN EPACKAGEJSON FireFly-API@0.0.30 No repository field.        
remote: npm WARN EPACKAGEJSON FireFly-API@0.0.30 No license field.        
remote: npm ERR! Windows_NT 6.2.9200        
remote: npm ERR! argv "D:\\Program Files (x86)\\nodejs\\4.1.2\\node.exe" "D:\\Program Files (x86)\\npm\\3.3.6\\node_modules\\npm\\bin\\npm-cli.js" "install" "--production"        
remote: npm ERR! node v4.1.2        
remote: npm ERR! npm  v3.3.6        
remote: npm ERR! code ELIFECYCLE        
remote: npm ERR! fibers@1.0.7 install: `node build.js || nodejs build.js`        
remote: npm ERR! Exit status 4294967295        
remote: npm ERR!         
remote: npm ERR! Failed at the fibers@1.0.7 install script 'node build.js || nodejs build.js'.        
remote: npm ERR! This is most likely a problem with the fibers package,        
remote: npm ERR! not with npm itself.        
remote: npm ERR! Tell the author that this fails on your system:        
remote: npm ERR!     node build.js || nodejs build.js        
remote: npm ERR! You can get their info via:        
remote: npm ERR!     npm owner ls fibers        
remote: npm ERR! There is likely additional logging output above.        
remote: Error - Changes committed to remote repository but deployment to website failed.        
```

With this being I think the primary clue? maybe?
remote: npm WARN EPEERINVALID mongodb-core@1.2.24 requires a peer of kerberos@~0.0 but none was installed.

**Comment by robblovell** [comment]
public repo for testing: https://github.com/robblovell/azure-test-firefly-deploy.git

**Comment by robblovell** [comment]
Is there any movement on this issue?

**Comment by ahmelsayed** [comment]
I'm taking a look at it. Sorry for the delay

**Comment by robblovell** [comment]
Great, Let me know if I can run any experiments.

**Comment by ahmelsayed** [comment]
btw, you said that sometimes it succeeds? I didn't include fibers in [the list of packages known to work](https://github.com/KuduApps/NodeAppWithNativeNpmModules/blob/master/package.json#L8-L28) because there is a weird issue with it that I wasn't able to figure out why it's happening. When node-gyp launches python.exe, for whatever reason, python waits for a new line from stdin, and that causes the deployment to kill it due to inactivity. I never saw fibers work for that reason. I'd be curious to know if it ever worked for you.

To test this, get to the debug console from kudu and run `npm i fibers@1.0.8`  then when it prints an output like 

```
D:\home\test\node_modules\fibers>if not defined npm_config_node_gyp (node "c:\Program Files (x86)\npm\3.3.6\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild --release )  else (node  rebuild --release ) 
```

it'll basically block until you hit return.

**Comment by robblovell** [comment]
Interesting. There was one deployment that worked that I remember, but I haven't repeated it since, so maybe I was mistaken about it.

**Comment by robblovell** [comment]
yes, it does pause waiting for a return in the kudu console with the npm -i fibers@1.0.8 command.

**Comment by robblovell** [comment]
I am able to get the website partially up by npm -i fibers@1.0.8 hitting return when it pauses, and then doing npm install from the kudu console. The code there may be outdated, so it might be my bugs preventing the site from operating fully.

**Comment by robblovell** [comment]
Subsequent deploys don't give errors. I did find a spelling error in the config file that caused the site to only work partially, so the site works now and can be deployed after the initial manual install of fibers.

**Comment by ahmelsayed** [comment]
yes subsequent deployments are expected to succeed because the package is already built. It'll only fail if you upgrade the version of fibers that your app is depending on. We will need to understand why python is waiting for user input there and why it only happens on Azure and not locally. In the mean time the work around is to run it manually once like you've done from the console.

**Comment by davidebbo** [comment]
The "Program database manager mismatch" error came up on forum [here](https://social.msdn.microsoft.com/Forums/en-US/ee89c887-32ef-4b11-a85e-b8a4e4c3addb/issue-during-deployment-to-azure-fatal-error-c1902-program-database-manager-mismatch?forum=windowsazurewebsitespreview).

**Comment by jvano** [comment]
Hi

Kudu will continue to run in Azure App Service. However, this repo will no longer be maintained.
If the problem persists and is related to running on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
