### ISSUE TITLE
Disable StyleCode and CodeAnalysis during build deployment

### ISSUE THREAD

**Issue by suwatch** [projectkudu/kudu#1819]
These are useful at dev time.   We should disable them during Kudu build deployment time.
- `/p:StyleCopEnabled=False`  
- `/p:RunCodeAnalysis=False`

**Comment by jvano** [comment]
Hi

Kudu will continue to run in Azure App Service. However, this repo will no longer be maintained.
If the problem persists and is related to running on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
