### ISSUE TITLE
AutoSwap only work once

### ISSUE THREAD

**Issue by shrimpy** [projectkudu/kudu#1824]
setup a lot auto swap to production
after initial linking (CI), swap AutoSwap will work
however, following push to slot will not trigger any AutoSwap unless manually disable and re-enable AutoSwap again.

**Comment by shrimpy** [comment]
work-around is, when in this stuck state:
````
 go to slot, disable and re-enable auto-swap
````

close this issue since fix need to happen in Azure instead of Kudu.

**Comment by duncansmart** [comment]
Is there any tracking of this issue in Azure?

**Comment by shrimpy** [comment]
yes we do. since it is an internal bug. i am not going to paste here. We are actively looking at it and working on the fix.

**Comment by duncansmart** [comment]
:+1:
