### ISSUE TITLE
REST deploy endpoint only works with basic Git credentials for private repo?

### ISSUE THREAD

**Issue by kamranayub** [projectkudu/kudu#1825]
I have a continuous deployment set up for my Azure web app, that works perfectly fine--whenever I push a commit to Github, it deploys the site.

I tried using the `/deploy` endpoint of the Kudu site and I noticed it will only work for my private repo if I specify a `username:password` in the repo URL. Is this expected? I expected it to use the SSH key it typically uses for the webhook, but just entering the repo URL didn't work.

```
POST https://site.scm.azurewebsites.net/deploy
Authorization: basiccreds
{ format: 'basic', url: 'https://user:pass@github.com/kamranayub/repo.git#64d1eee668' }
```

**Comment by davidebbo** [comment]
But you are passing an https URL. Have you tried passing an ssh URL, e.g. git@github.com:kamranayub/repo.git?

**Comment by kamranayub** [comment]
No I didn't. That didn't occur to me, based on the docs.

**Comment by davidebbo** [comment]
Think of it as calling git fetch using whatever git URL you pass.
