### ISSUE TITLE
Git2.6.3: add unix tools path to %path%

### ISSUE THREAD

**Issue by suwatch** [projectkudu/kudu#1826]
For the new git (2.6.3), the git.exe (and a few other git related tools) are in `D:\Program Files (x86)\Git\cmd`.   This path is added to %PATH%.   The unix tools, however, are installed in `D:\Program Files (x86)\Git\mingw32\bin` and `D:\Program Files (x86)\Git\usr\bin` – which are not added to %PATH%.      By checking the 3rd checkbox, the folders will be added to %PATH%.    We might need to do some Kudu or DWAS change to add the path to %PATH%.

Fixing Kudu is preferred.   Do you need both mingw32\bin and usr\bin in the %PATH%?   I would add both to be consistent with git installation.

**Comment by davidebbo** [comment]
Yes, may as well add both. I don't have a good sense of how they compare.

We should do existence check before adding them, so we keep the path clean on machines that don't have those.
