### ISSUE TITLE
"deployment_branch" and "branch" environment variable not the same

### ISSUE THREAD

**Issue by ghost** [projectkudu/kudu#1827]
When deploying, I use the deployment branch as the information to select a publishing profile.
Apparantly the environment variable changed from branch to deployment_branch for issue #337 with commit cdb997e03d89a1dfc80bf0fc44cd1dd2e34d3929.
I've checked the difference at portal.azure.com => web app => tools => Console
![branches](https://cloud.githubusercontent.com/assets/11175617/11637051/427bff74-9d17-11e5-98d9-d20b53b72335.png)

Also the configuration at manage.windowsazure.com shows my correct deployment branch. And in D:\home\site\deployments\settings.xml on the file system I also see the correct deployment branch stored.

I expected "deployment_branch" to be my "develop" branch and be equal to "branch".

In my repo, I only pushed the "develop" branch to the Local Git repo at my Azure website.

**Comment by migarashi47** [comment]
Also I think!

**Comment by petrepopescu21** [comment]
The "branch" setting controls which Github/Bitbucket branch will be watched and pulled, the "deployment_branch" setting controls to which branch you need to push code when using the "Local Git Repository" deployment option.

These have completely different purposes, so they don't have to be in sync.
