### ISSUE TITLE
KUDU_SYNC_CMD not set correctly?

### ISSUE THREAD

**Issue by te-online** [projectkudu/kudu#1828]
I am using the source code of release S48 from this repository on a Windows Server 2012 R2. I built the project with Visual Studio 2013 Community version. Everything works fine, except the sync part of the deployment.

In deploy.cmd in each created app we have:
```BATCH
...
IF NOT DEFINED KUDU_SYNC_CMD (
  :: Install kudu sync
  echo Installing Kudu Sync
  call npm install kudusync -g --silent
  IF !ERRORLEVEL! NEQ 0 goto error

  :: Locally just running "kuduSync" would also work
  SET KUDU_SYNC_CMD=%appdata%\npm\kuduSync.cmd
)
...
```

and later

```Batch
:: 1. KuduSync
IF /I "%IN_PLACE_DEPLOYMENT%" NEQ "1" (
  echo %KUDU_SYNC_CMD%  
  call :ExecuteCmd "%KUDU_SYNC_CMD%" -v 50 -f "%DEPLOYMENT_SOURCE%" -t "%DEPLOYMENT_TARGET%" -n "%NEXT_MANIFEST_PATH%" -p "%PREVIOUS_MANIFEST_PATH%" -i ".git;.hg;.deployment;deploy.cmd"
  IF !ERRORLEVEL! NEQ 0 goto error
)
```
where the error appears.

The error message is:
```Batch
Handling node.js deployment.

'"KuduSync.NET.exe"' is not recognized as an internal or external command, operable program or batch file.

Failed exitCode=1, command="kudusync" -v 50 -f "[removed path]" -t "[removed path]" -n "[removed path]" -p "[removed path]" -i ".git;.hg;.deployment;deploy.cmd"

An error has occurred during web site deployment.
```

----

**Findings**

As far as I found out so far, the variable ``KUDU_SYNC_CMD`` always equals to ``kudusync``. This shouldn't be the case if the package might not be available, right? I tried to set the variable to an empty value, which caused the script to install kudusync and run the deployment **smoothly**. On the next run it won't work again, because the variable is set to ``kudusync``, instead of the full path, again.

Can anyone help me there? I have no clue what the cause of this problem could be.

**Comment by ahmelsayed** [comment]
`KuduSync.Net.exe` is expected to be part of kudu brought in by [this](https://github.com/projectkudu/kudu/blob/master/.nuget/packages.config#L4) 

Under `Kudu.Services.Web\bin\Scripts\` you should have `kudusync.cmd` and `KuduSync.NET.exe`. and that folder should be on the path. Can you try building from the `build.cmd` in the project root?

**Comment by te-online** [comment]
@ahmelsayed Thanks a lot for your reply! I'm sorry, but I came to the decision not to use IIS at all (not because of this issue, but after a general consideration of choices).

However, the KuduSync.NET.exe is present under packages. That's the strange thing.
I've run the build.cmd, but it threw some errors on the tests – so there might be something wrong and I would just need to start from scratch... But as I can't look into this anymore – no issue there :wink:
