### ISSUE TITLE
WEBSITE_LOCAL_CACHE_OPTION=Always requires stop and start of the site

### ISSUE THREAD

**Issue by sameercaresu** [projectkudu/kudu#1829]
How is `local cache` feature supposed to work?

I have it enabled on my site. Changes are not reflected in the site after new deployments are made until the site is stopped and started again.

Is there any option to flush the cache on new deployments or is there a cache expiry time??

**Comment by davidebbo** [comment]
The local cache feature is a runtime thing that is not related to Kudu. The best place for general Azure Web App questions in the [MSDN forum](https://social.msdn.microsoft.com/Forums/en-US/home?forum=windowsazurewebsitespreview). Thanks!
