### ISSUE TITLE
Bower install by default

### ISSUE THREAD

**Issue by christopheranderson** [projectkudu/kudu#1830]
To run `bower install` today, it requires a custom deploy script. Given that `bower install` isn't a destructive action, it should be safe to, if a bower.json file exist, run `bower install`, similar to how node and package.json works today. 

I have an example for the node deploy file here: https://github.com/christopheranderson/azure-node-native-modules-sample/blob/master/deploy.cmd#L109

**Comment by jvano** [comment]
Hi

Kudu will continue to run in Azure App Service. However, this repo will no longer be maintained.
If the problem persists and is related to running on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
