### ISSUE TITLE
Support for Powershell execution in Post deployment actions

### ISSUE THREAD

**Issue by ranganathg** [projectkudu/kudu#1833]
Currently I need to add an intermediate .cmd file to execute the powershell script. Is it possible to support powershell script first class?

Thanks!
Ranga

**Comment by suwatch** [comment]
Yes we could.   @davidebbo, it would be a quick fix in [postdeployment.cmd](https://github.com/projectkudu/kudu/blob/master/Kudu.Core/Scripts/postdeployment.cmd#L9).

**Comment by ranganathg** [comment]
Thanks!
