### ISSUE TITLE
CRON Scheduled WebJobs - Incorrect interval start

### ISSUE THREAD

**Issue by mathewc** [projectkudu/kudu#1834]
Reported in this [SO post](http://stackoverflow.com/questions/34248862/webjob-crontab-schedule-running-at-the-top-of-the-hour-and-every-15-min-thereaft). For example, when setting up a 15 minute interval, the executions should be on the 0,15,30,45,0 minute, however currently we start the first execution as soon as the job starts, leading to the job running with the correct delta, but at the wrong times.

**Comment by mathewc** [comment]
I'll fix this one

**Comment by davidebbo** [comment]
Yep, that's not desired behavior.

**Comment by jvano** [comment]
Hi

Kudu will continue to run in Azure App Service. However, this repo will no longer be maintained.
If the problem persists and is related to running on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
