### ISSUE TITLE
Is there any way to change website appsettings during custom deployment script?

### ISSUE THREAD

**Issue by mskutin** [projectkudu/kudu#1844]
I'm about to make changes in Website AppSettings within deployment scenario. 
Noticed I don't have admin rights to change the registry.
Added my variable to `$ENV:` but it's not available from portal and exist only in a current session.

**Comment by davidebbo** [comment]
You cannot affect the Azure App Settings during deployment. It's something that needs to be done using the Azure API, which you can't call from inside the sandbox.

The closest thing you can do is drop an XDT transform to add some environment variables. Sample [here](https://github.com/projectkudu/kudu/wiki/Xdt-transform-samples#adding-environment-variables). They still won't show up in the Portal/API, but they will be effective at runtime.

**Comment by mskutin** [comment]
@davidebbo Please fix me if I wrong.
There is no point to use https://github.com/projectkudu/kudu/wiki/REST-API#settings this?
Because I can't modify Azure App Settings using Kudu REST API?
When I make changes in `/api/settings` they are exists only on this page, but unavailable from portal, `/Env` and ARM, etc.

**Comment by davidebbo** [comment]
@mskutin You are correct; this API will not help. It is only used as an alternate way to set Kudu settings, but it does not have the same effect as general settings.
