### ISSUE TITLE
 Ace css issue using Input Method Editor (IME)

### ISSUE THREAD

**Issue by shibayan** [projectkudu/kudu#1845]
I use Kudu ace editor under Input method editor env (standard use in japanese). I discovered that the display becomes strange as the image below.

![aceissue](https://cloud.githubusercontent.com/assets/1356444/12020082/6302971c-adbb-11e5-920b-9a66f18e9af3.png)

It seems following definitions it is in CSS is causing, but I can not determine whether there is no problem to remove. I need advice :smile_cat: 

https://github.com/projectkudu/kudu/blob/master/Kudu.Services.Web/Content/Styles/FileBrowser.css#L165

**Comment by snobu** [comment]
`min-height` should never.. explode like that, i think it's something else. How can i reproduce what you're seeing?

I'll take a look at this tomorrow morning.

**Comment by davidebbo** [comment]
I'm guessing you need Japanese OS? I tried pasting some Japanese text from [here](http://generator.lorem-ipsum.info/_japanese) into the editor, and nothing bad happened, so there is probably more to it.

Maybe it comes down to an ACE bug? @shibayan would be good to try if you can repro this with a trivial page that uses ACE and sets `min-height`.

**Comment by snobu** [comment]
Alright, so the `min-height` was introduced in this commit:
https://github.com/projectkudu/kudu/commit/1f24ef90f150db7754c4ea0c7469158cf4df543f#diff-599dcd2b293b741d8bcf68cb863f548dR80

Not sure if this was meant to fix the older textarea-based editor or it serves a different purpose but i don't think Ace needs it at all since Ace sits directly inside a `div`, not a `textarea`.

Try to repro here: https://ace.c9.io/build/kitchen-sink.html

**Comment by snobu** [comment]
Ah, so Ace DOES use a textarea element for current line.

![image](https://cloud.githubusercontent.com/assets/6472374/12023119/e7aa55ee-ad9e-11e5-87d6-fcc9b9256828.png)

By the look of it this might be it. Let me do a bit of testing tomorrow to make sure the `min-height` doesn't affect anything else.

**Comment by shibayan** [comment]
@davidebbo Yes, This issue require Japanese OS (and IME). In the case of copy and paste, it can not be reproduced.

I tried Ace kitchen-sink. This issue did not reproduce.
![kitchen-sink](https://cloud.githubusercontent.com/assets/1356444/12028173/6f1336d2-ae16-11e5-8f6a-5c7c6ae368a2.png)


@snobu If there is no need in switching to Ace Editor, I want to delete this CSS definition.
Such as Japanese and only when IME is a required language, it seems this issue occurs.

![ignore-minheight](https://cloud.githubusercontent.com/assets/1356444/12028276/f67dd0e0-ae17-11e5-9731-6c56a3b4963f.png)

If disable the min-height, it was confirmed to be displayed correctly. I hope if there is no effect on another element..

**Comment by snobu** [comment]
Ok, i'm fairly confident removing `min-height` on `textarea` won't negatively affect anything else.

Looks like there's a textarea in jquery-console as well, but i tested that, it doesn't care about `min-height`.
```
C:\seriouswork\kudu [AceIMEfix]> grep -r "<textarea" *
Kudu.Services.Web/Content/Scripts/jquery-console/jquery.console.js:             var typer = $('<textarea class="jquery-console-typer"></textarea>');
Kudu.Services.Web/Content/Scripts/jquery.contextMenu.js:                            $input = $('<textarea name=""></textarea>')
```

Looking though the rest of the source code, `FileBrowser.css` is only referenced in `/DebugConsole/Default.cshtml`
![minheight](https://cloud.githubusercontent.com/assets/6472374/12033691/6d7d4692-ae2e-11e5-9599-4160c77831b2.PNG)

I think we're good. PR sent.

Thanks @shibayan for reporting this!

**Comment by shibayan** [comment]
@snobu Thank you for code fix! :tada: Kudu will be easier to use! (in IME required language)

**Comment by davidebbo** [comment]
Thanks, it'll be in the next Kudu deployment.
