### ISSUE TITLE
Azure App Settings don't override external config files in WebJobs

### ISSUE THREAD

**Issue by jsgoupil** [projectkudu/kudu#1847]
When using 
`<appSettings file="AppSettings.config" />` in a WebJob, the Azure Portal does not override any of the app settings.

Basically, the settings found here:
https://&lt;website>.scm.azurewebsites.net/api/settings

are not necessarily the ones used in a WebJobs.

Some discussion about the issue can be found here:
https://github.com/projectkudu/kudu/issues/1571

**Comment by davidebbo** [comment]
I think the fix would be something like this:

- Code is [here](https://github.com/projectkudu/kudu/blob/a14fc023a4fd0cd3fcc2723ac51c263e65e7d22e/Kudu.Core/Jobs/BaseJobRunner.cs#L465-L470) and looks like this:

```c#
Configuration config = ConfigurationManager.OpenExeConfiguration(exeFilePath);

foreach (var appSetting in settings.AppSettings)
{
    config.AppSettings.Settings.Remove(appSetting.Key);
    config.AppSettings.Settings.Add(appSetting.Key, appSetting.Value);
    updateXml = true;
}
```

- We'd need to look at `config.AppSettings.File`, which I think would point at the external config file.
- Take settings from there and apply them to the config
- Get rid of the external file
- Apply current logic to have Azure settings win

**Comment by jvano** [comment]
Hi

Kudu will continue to run in Azure App Service. However, this repo will no longer be maintained.
If the problem persists and is related to running on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
