### ISSUE TITLE
Question about installing KUDU on non-Azure Websites

### ISSUE THREAD

**Issue by apolloeducationgroup** [projectkudu/kudu#1849]
I host my website on a VPS and am interested in using Kudu as a deployment tool to sync from source control to the production server. Can i use Kudu on a non-azure website or do i need to transfer my site to Azure?

**Comment by davidebbo** [comment]
It is possible to use Kudu outside of Azure (see https://github.com/projectkudu/kudu/wiki/Deploying-to-a-server), though it doesn't come with its own security model.

**Comment by eydelrivero** [comment]
@davidebbo Could you please expand a bit on **_doesn't come with its own security model_** ? Is this still the case today?

**Comment by davidebbo** [comment]
Sorry, I haven't been connected to this project in quite some years so I'm not up to date.

**Comment by jvano** [comment]
Hi

Kudu will continue to run in Azure App Service. However, this repo will no longer be maintained.
If the problem persists and is related to running on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
