### ISSUE TITLE
Capture Performance Counters in Web Job / App?

### ISSUE THREAD

**Issue by pbolduc** [projectkudu/kudu#1854]
Is it possible to capture performance counter values for the current process/app?  I am trying to capture metrics about my running web job, such as % TIme in GC, Gen *N* heap size, thread contention Rate / Sec, etc.   I see Application Insights can capture these kind of metrics when enabled in my web site.

    var category = ".NET CLR Memory";
    var counter = "% Time in GC";
    var instance = Process.GetCurrentProcess().ProcessName;
    var pc = new PerformanceCounter(category, counter, instance, true);

I understand why this would fail as the Auzre/kudu runtime sandbox needs to ensure the instance is my process not some other customer's process.  Is there a way to get access to my process' counters so I can report on/collect them?  I would like the collection to occur from within the process.

**Comment by davidebbo** [comment]
This is more of a general Azure Web App sandbox question than something Kudu specific. If App Insights does it and runs within sandbox, then presumably it can be done somehow.

**Comment by pbolduc** [comment]
Sometimes I find it difficult to know were one starts and the other project starts.  I will try to find the correct location to ask this question.
