### ISSUE TITLE
Call to Api/WebJobs/ takes more than 20 seconds sometimes leading to the GeoMaster timing out and Ibiza WebJobs blade failing to load, need to improve performance

### ISSUE THREAD

**Issue by shobak101** [projectkudu/kudu#1855]

**Comment by davidebbo** [comment]
Longer Kudu issue title ever! :)

**Comment by davidebbo** [comment]
BTW, @suwatch is looking at very similar issues for /deployments. See #1853. Guessing there could be similar optimizations.

**Comment by shobak101** [comment]
Some of it should have been in the body :) maybe being in the title makes you get the needed info faster :D I talked to Suwat and he may take a look when he has time or I will get to it.

**Comment by ahmelsayed** [comment]
do we have a sample trace file for this? is it file I/O like #1853?

**Comment by shobak101** [comment]
all I have for it is HTTP logs on FEs indicating times between 14 - 24 seconds for a specific site. I need to collect those info to find out if it is related to the same issue
