### ISSUE TITLE
"Index was outside the bounds of the array" errors

### ISSUE THREAD

**Issue by bitcrazed** [projectkudu/kudu#1856]
Seeing A LOT of the following errors being reported while watching the log stream from my ASP.NET 5 (RC1) app running in an Azure Website.

```
2016-01-08T00:25:20      Error occurred, type: error, text: Index was outside the bounds of the array., stackTrace:    at Kudu.Core.Infrastructure.ProcessExtensions.EnvToDictionary(Byte[] env)
   at Kudu.Core.Infrastructure.ProcessExtensions.GetEnvironmentVariablesCore(IntPtr hProcess)
   at Kudu.Core.Infrastructure.ProcessExtensions.GetEnvironmentVariables(Process process)
   at Kudu.Services.Performance.ProcessController.SafeGetValue[T](Func`1 func, T defaultValue)
```

Let me know what additional info needed to debug etc.

**Comment by davidebbo** [comment]
Strange, we should investigate. But note that stream doesn't work out of the box for aspnet 5. Or do you have anything special to make it work?

**Comment by bitcrazed** [comment]
Haven't done anything particularly special other than add Console and Debug logging via ```LoggerFactory``` at various points in the app - am seeing my own logging messages in my local log streams and in Azure too! :)

**Comment by ahmelsayed** [comment]
What bitness is your ASP.NET 5 app running? is it different from that of w3wp.exe by any change?

**Comment by bitcrazed** [comment]
Haven't set any specific bitness. Have dnx451 and dnxcode50 enabled in the project. Having said that, seeing oddities locally - have to run in Kestrel as IISExpress termintes the process immediately after startup completes (no errors reported anywhere!)

**Comment by jvano** [comment]
Hi

Kudu will continue to run in Azure App Service. However, this repo will no longer be maintained.
If the problem persists and is related to running on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
