### ISSUE TITLE
Manage other Azure services from Azure WebJob PowerShell script

### ISSUE THREAD

**Issue by afmorris** [projectkudu/kudu#1858]
Hello.

I have no idea if this is the right location for this, but I have been hunting the internet for awhile now, to no avail.

I want to accomplish the following with an Azure WebJob PowerShell script:
* Import the Azure PowerShell module
  * I accomplished this via copying the entire `C:\Program Files (x86)\Microsoft SDKs\Azure\PowerShell\ServiceManagement` directory to my uploaded .zip file
* Import Azure Publish Settings file to load connectivity settings to my Azure Subscriptions
  * Fails due to cryptographic errors, it seems.
* Stop an Azure Cloud Service
  * Using `Stop-AzureService` cmdlet
* Start an Azure Cloud Service
  * Using `Start-AzureService` cmdlet

Are there any useful READMEs that I can go through, or do you guys have any specific direction on how to connect to an Azure Subscription via an Azure WebJob PowerShell script? Or should I post this somewhere else?

Thanks!

**Comment by davidebbo** [comment]
Unfortunately, this is not supported today. Recent thread [here](http://stackoverflow.com/questions/34551290/running-azure-powershell-commands-from-a-webjob). Closing here since it is outside of Kudu.

But it is something we do want to try to enable in Azure in the future.

**Comment by davidebbo** [comment]
Also, for reference, this had come up in #1589.
