### ISSUE TITLE
"Inaccessible instance" status for a web job on a deployment slot

### ISSUE THREAD

**Issue by tulikac** [projectkudu/kudu#1859]
If we create a continuous web job and set is_singleton=true in settings.job, the webjob status changes to "Inactive instance". 
It is probably due to a quirk in how the WebJobs API works. It ends up hitting one of the instances arbitrarily, so it may not hit the one that’s running in the singleton case. So what it reports as the status ends up being a bit bogus.
![webjob](https://cloud.githubusercontent.com/assets/4797023/12244782/445b53d6-b873-11e5-81af-77809370161f.jpg)

**Comment by davidebbo** [comment]
I doubt that this is related to deployment slots. I would expect the same behavior on a regular app scaled to multiple instances, and without slots.

**Comment by tulikac** [comment]
Yes. That is true. It is actually randomly happening on any instance including deployment slots.

**Comment by davidebbo** [comment]
I updated the subject to clarify.

Ideally, the API would be agnostic of the specific instance it runs it.

**Comment by jvano** [comment]
Hi

Kudu will continue to run in Azure App Service. However, this repo will no longer be maintained.
If the problem persists and is related to running on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
