### ISSUE TITLE
Deploying a Python web app via conda

### ISSUE THREAD

**Issue by almarklein** [projectkudu/kudu#1861]
Hi,

We're developing a Python web app to run on Azure, and for various reasons we would like to run it on [conda](http://conda.pydata.org). To do so we are using a custom `deploy.cmd` in which we use [miniconda](http://conda.pydata.org/miniconda.html) to install our own Python interpreter and any dependencies. However, we are having trouble in getting the web server to actually use the Python interpreter of our choice.

Our appsettings section in `web.config` looks like this:

```
  <appSettings>
    <add key="WSGI_ALT_VIRTUALENV_HANDLER" value="app.wsgi_app" />
    <add key="WSGI_ALT_VIRTUALENV_ACTIVATE_THIS"
         value="D:\home\path\to\our\python.exe" />
    <add key="WSGI_HANDLER"
         value="ptvs_virtualenv_proxy.get_venv_handler()" />
    <add key="PYTHONPATH" value="D:\home\site\wwwroot" />
  </appSettings>
```

For the script processor, we'd think we'd need something like this:
```
scriptProcessor="D:\home\path\to\our\python.exe|D:\path\to\wfastcgi.py"
```

However, this does not work. The site does work (with the system-Python interpreter) if we keep `scriptProcessor` to its original setting. But even if we just change the location of the `wfastcgi.py` (using an exact copy of the original file), the server will not work. The server only tells us that there has been an internal server error. Attempt to get additional logging info (a Python traceback would be great) have lead to nothing.

Any tips on how to proceed would be highly appreciated. Thank you!

**Comment by davidebbo** [comment]
First thing I'd try to determine is whether this is a deployment or runtime issue (see [this page](https://github.com/projectkudu/kudu/wiki/Deployment-vs-runtime-issues)). Kudu is only involved in the deployment side of things.

**Comment by almarklein** [comment]
Thanks @davidebbo. It's a runtime issue. The main question boils down to: how can we make our specific Python interpreter be used to run the WSGI server?

Is this the right place to ask? If not, where else could I go?

**Comment by davidebbo** [comment]
[MSDN forum](https://social.msdn.microsoft.com/Forums/en-US/home?forum=windowsazurewebsitespreview) is a good place for all Azure Web Apps related questions.
