### ISSUE TITLE
corrupt eventlog.xml prevents logging

### ISSUE THREAD

**Issue by jsandersrocks** [projectkudu/kudu#1865]
When trying to view my Events using the Kudu/Support site I went the Analyze tab and the logs would not come up or display.  Instead a spin icon just spun away for ever:

After further investigation (I opened the file using the pencil icon here) I discovered the file was corrupt and missing the closing XML formatting tags.

Solution

I could have repaired the XML and make it well formatted or delete the file.  I had all the information I needed from the file so I deleted it and all was working well again!

**Comment by davidebbo** [comment]
That sounds bad. The creation of eventlog.xml happens at runtime when there are exceptions, and is not related to Kudu logic, so not the best place to track. Forum would be best: https://social.msdn.microsoft.com/Forums/azure/en-US/home?forum=windowsazurewebsitespreview. Thanks!
