### ISSUE TITLE
Editing a .cshtml file in kudu changes the file encoding.

### ISSUE THREAD

**Issue by sao2015** [projectkudu/kudu#1866]
Editing a .cshtml file in kudu changes the file encoding.
Screws with æøå.

**Comment by davidebbo** [comment]
Please provide more detail. What encoding is the file originally in? Does it display correctly when opened, and then is only corrupted on save?

Generally, the editor should properly support any utf-8 file.

**Comment by davidebbo** [comment]
I confirm that the editor does not do well with non-utf8 files. I also tried with the much fancier VS Online Monaco editor and it doesn't support it either. I don't think we will solve this. The Kudu editor is a quick and dirty editor, and most files nowadays are utf-8.

**Comment by sao2015** [comment]
Sorry for a late reply, your messages went into the spam-folder.

The file is originally in UTF-8-BOM.
When downloaded after editing in Kudu, it is in UTF-8.
The page is correctly displayed in the Kudu editor at all times, but Norwegian characters are not displayed correctly when viewing the website after in-place editing.


Med vennlig hilsen
Ståle A. Olsen
systemutvikler
Tlf.: 926 69 505

GRAMO - musikernes, artistenes og plateselskapenes vederlagsbyrå
Karl Johansgt. 21, 0159 Oslo
Tlf:  22 00 77 77
Gramo<http://www.gramo.no/> | Facebook<https://www.facebook.com/gramoface>

- en kilde til et rikt musikkliv

**Comment by davidebbo** [comment]
Ah, now I understand the issue. The file is not corrupted, but without the BOM, some scenarios will not properly treat it as UTF-8.

The ideal solution would be for  the Kudu editor to remember whether the original file had the BOM, and save it accordingly. But if that's too hard, maybe we can't go too wrong by always saving it with the BOM.

@snobu, do you know how to do this? Seems relevant code is around [here](https://github.com/projectkudu/kudu/blob/f42028c8b2b2944aa598abd577f0fe4e6ff836fc/Kudu.Services.Web/Content/Scripts/FileBrowser.js#L370-L393). We save the string using Vfs, but evidently that doesn't include a BOM.

**Comment by davidebbo** [comment]
Ok, seems http://stackoverflow.com/questions/17879198/adding-utf-8-bom-to-string-blob has the answer: I think we just need to prepend `\ufeff` to the string.

**Comment by snobu** [comment]
Well, now I know! Thanks David :) will give this a go tomorrow.

**Comment by davidebbo** [comment]
Thanks!

**Comment by snobu** [comment]
Here are my findings:

`notepad.txt` = Text file saved in Notepad.exe as __UTF-8 with BOM__
`ef bb bf` = BOM signature
`0x54` = Uppercase T (ASCII) as in _This is utf8 with bom.._

If i do this (give me the charCode at first byte):
```
Vfs.getContent(this).done(function (data) {
     console.log("data.charCodeAt(0)=" + data.charCodeAt(0));
     ...
```

I get this (blue rectangle):

![nobom](https://cloud.githubusercontent.com/assets/6472374/12684376/3995f066-c6c7-11e5-869a-463d15756768.png)

`84` is `0x54` = ASCII "T" 

Which means that `$.ajax` is ignoring the BOM or is not requesting/receiving proper encoding.
Here is the relevant snippet from `FileBrowser.js`:
```javascript
var Vfs = {
        getContent: function (item) {
            return $.ajax({
                url: item.href,
                dataType: "text"
            });
        },
```

When that fires, this is what gets requested:

```
GET /api/vfs/site/wwwroot/notepad.txt HTTP/1.1
Host: kududev.scm.azurewebsites.net
Connection: keep-alive
Authorization: Basic xxxxxxxxxxxxxxxxxxx=
Accept: text/plain, */*; q=0.01
X-Requested-With: XMLHttpRequest
```

Now, i've played with the ajax request headers a lot, dataType too, even made the headers look exactly like `curl`'s  (or Chrome's non-ajax request).. but to no avail. I am not able to pull the BOM.

If you do this instead:

```
Surface# curl -O -s -k https://xx:xx@kududev.scm.azurewebsites.net/api/vfs/site/wwwroot/nor.txt

Surface# cat nor.txt
The Norwegian vowels are pronounced in almost the same way as in German.
There are three additional vowels. æ (Æ), ø (Ø), and å (Å).

Surface# cat nor.txt | hexdump -C
00000000  ef bb bf 54 68 65 20 4e  6f 72 77 65 67 69 61 6e  |...The Norwegian|
00000010  20 76 6f 77 65 6c 73 20  61 72 65 20 70 72 6f 6e  | vowels are pron|
00000020  6f 75 6e 63 65 64 20 69  6e 20 61 6c 6d 6f 73 74  |ounced in almost|
00000030  20 74 68 65 20 73 61 6d  65 20 77 61 79 20 61 73  | the same way as|
00000040  20 69 6e 20 47 65 72 6d  61 6e 2e 0d 0a 54 68 65  | in German...The|
00000050  72 65 20 61 72 65 20 74  68 72 65 65 20 61 64 64  |re are three add|
00000060  69 74 69 6f 6e 61 6c 20  76 6f 77 65 6c 73 2e 20  |itional vowels. |
00000070  c3 a6 20 28 c3 86 29 2c  20 c3 b8 20 28 c3 98 29  |.. (..), .. (..)|
00000080  2c 20 61 6e 64 20 c3 a5  20 28 c3 85 29 2e        |, and .. (..).|
0000008e
```
* `nor.txt` is another UTF-8 with BOM text file.

Note `ef bb bf`. It's all good. UTF-8 with BOM. So `/api/vfs` isn't selling me lies.

And `charCodeAt(0)` is not lying either:

Chrome F12 Console:
```
  >var seq = String.fromCharCode(65279) + "I am Lorde, ya ya ya";
  undefined
  >seq.charCodeAt(0)
  65279
  >seq.charCodeAt(1)
  73
```

```
  > $.ajax({ 
        url: "https://kududev.scm.azurewebsites.net/api/vfs/site/wwwroot/notepad.txt",
        dataType: "text", success: function(result) {
            console.log( result + " FIRST BYTE=" + result.charCodeAt(0) );
        } 
    })

Object {readyState: 1}
This is utf8 with bom from Notepad.exe FIRST BYTE=84
```
FIRST BYTE should be `65279`, the BOM signature. Instead it's `84`, hex for "T".

I feel like i'm missing something obvious in `$.ajax()` that would allow me to get the raw file and not a "sanitized" version.

I also have this thought that if we eventually make contact with a highly advanced alien form, the moment would be completely ruined by finding out they weren't able to fix THEIR text encoding either!

**Comment by snobu** [comment]
![image](https://cloud.githubusercontent.com/assets/6472374/12730498/ed4041ba-c934-11e5-978e-695ebbdacbc0.png)

Wiresharking the `$.ajax()` request, we have BOM.
So it looks like i can't use `result.charCodeAt(0)` after all because the browser gets in the way.

#### Plan B ####
I could go for `/api/vfs/`, somewhere here:
https://github.com/projectkudu/kudu/blob/master/Kudu.Services/Editor/VfsController.cs#L77

and add in a very nifty check for BOM:
```csharp
// http://stackoverflow.com/a/27976558
var utf8NoBom = new UTF8Encoding(false);
if (fileStream == utf8NoBom)
{
    // Add X-CONTENT-HAS-UTF8BOM HTTP header to signal BOM presence for $.ajax()
}
```

Then, in the frontend, if the header is present when we load the content, just prepend the BOM on Save.

Comments?

**Comment by jvano** [comment]
Hi

Kudu will continue to run in Azure App Service. However, this repo will no longer be maintained.
If the problem persists and is related to running on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
