### ISSUE TITLE
Pre-installed global grunt-cli with older glob is causing issues on custom deployment scripts

### ISSUE THREAD

**Issue by floydpink** [projectkudu/kudu#1869]
There is an existing issue that was raised for this in November that is now closed because the OP found a work around - https://github.com/projectkudu/kudu/issues/1787

And as mentioned in that issue, this is similar to #1573 in that the pre-installed grunt-cli is causing errors when globbing for patterns like `./**/*.js` etc. when there are network drives present.

Here is a repo with the custom deployment script that causes the error: https://github.com/floydpink/azure-glob-error

**Comment by vivmaha** [comment]
In case this helps, this SO answer offers another workaround:
http://stackoverflow.com/questions/30199739/enotup-using-grunt

**Comment by floydpink** [comment]
Thanks you, @vivmaha - I also had seen that SO question & answer and unfortunately it does not help because it is failing for me on [these lines](https://github.com/floydpink/azure-glob-error/blob/master/Gruntfile.js#L122-L139)

**Comment by jvano** [comment]
Hi

Kudu will continue to run in Azure App Service. However, this repo will no longer be maintained.
If the problem persists and is related to running on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
