### ISSUE TITLE
Kudu Diagnostic Console does not show temp files that are created from the web app

### ISSUE THREAD

**Issue by dirkju** [projectkudu/kudu#1871]
According to documentation, the web app is allowed to write to %TEMP% folder. If this is done, any files written will not show up in the Kudu Debug console file browser. I verified the temp file gets written correctly and can be read back by the IIS serving the request. However, Kudu does not show these files, leaving the user puzzled. Could this be due to a file ownership / ACL problem?

**Comment by davidebbo** [comment]
It's by design, but you can change this using `WEBSITE_DISABLE_SCM_SEPARATION`. See [wiki](https://github.com/projectkudu/kudu/wiki/Configurable-settings#use-the-same-process-for-the-user-site-and-the-scm-site) for details.
