### ISSUE TITLE
WebJob background file change handler lack tracing

### ISSUE THREAD

**Issue by suwatch** [projectkudu/kudu#1872]
WebJob has file watcher on app_data\jobs folder and handle them.  We have no tracing at all when that happens.

**Comment by jvano** [comment]
Hi

Kudu will continue to run in Azure App Service. However, this repo will no longer be maintained.
If the problem persists and is related to running on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
