### ISSUE TITLE
How to get more insight into what is going on?

### ISSUE THREAD

**Issue by dalelotts** [projectkudu/kudu#1876]
Sorry, new to Kudu and Azure. Have a node app that should be simple to deploy but is behaving strangely when pushing to a git repository on an app service.

Specifically, what is going on with the "remote: Processed 24744 files..." messages? These do not seem to be related to the files in my repository. One push it will process 11K files and the next 25K files, etc - didn't count the files in my project but I would be shocked if there are more than 1K. While file are being processed and what kind of processing is being done?  

Also seeing "Exception message: Command 'git.exe receive-pack -- ...' was aborted due to no output nor CPU activity for 60 seconds." message in the app service event log - not sure why that is taking so long.

Just got the following while entering this issue...

emote: Error - Changes committed to remote repository but deployment to website failed.
remote: .............................................................fatal: protocol error: bad line length character: <!DO
error: error in sideband demultiplexer
error: failed to push some refs to 'https://acpdev-deploy@acpdev.scm.azurewebsites.net:443/acpdev.git'
error: git-remote-https died of signal 13

Any suggestions how to get more insight into what is causing these issues would be much appreciated.

**Comment by abondoa** [comment]
Having a similar issue.

We have had an App Service running for a long time without problems and automatic deployment. Recently, we started getting the same error: "Command 'git.exe receive-pack -- ...' was aborted due to no output nor CPU activity for 60 seconds."

We increased the SCM_COMMAND_IDLE_TIMEOUT and now the error message is changed to: "Command 'git.exe receive-pack -- ...' was aborted due to no output nor CPU activity for 181 seconds."

Any insights gained during the last year on how to debug this?

**Comment by davidebbo** [comment]
If increasing the timeout doesn't help, you might be in a situation where deployment is stuck. e.g. that could happen if something is prompting for user input that can never come. One thing to try:

- set a really long timeout
- do a deployment do it gets stuck
- use Kudu process explorer to see if you can spot anything suspicious in the process tree. Also, look at the deployment logs which may give hints about where it's stuck

**Comment by jvano** [comment]
Hi

Kudu will continue to run in Azure App Service. However, this repo will no longer be maintained.
If the problem persists and is related to running on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
