### ISSUE TITLE
Site Extension system.applicationHost rewrite rule problem

### ISSUE THREAD

**Issue by gregjhogan** [projectkudu/kudu#1877]
It appears that if you attempt to set a URL rewrite rule at the system.applicationHost level it transforms the applicationhosts.config file successfully, but then the kudu site returns a 503 error for every request.  Should this work?

```xml
<?xml version="1.0"?>
<configuration xmlns:xdt="http://schemas.microsoft.com/XML-Document-Transform">
    <system.applicationHost>
        <system.webServer xdt:Transform="InsertIfMissing">
            <rewrite xdt:Transform="InsertIfMissing">
                <rules xdt:Transform="InsertIfMissing">
                    <rule name="Redirect HTTP to HTTPS" enabled="true" stopProcessing="true">
                        <match url="(.*)" />
                        <conditions>
                            <add input="{HTTPS}" pattern="^OFF$" ignoreCase="true" />
                        </conditions>
                        <action type="Redirect" url="https://{HTTP_HOST}/{R:1}" appendQueryString="true" redirectType="Permanent" />
                    </rule>
                </rules>
            </rewrite>    
        </system.webServer>
    </system.applicationHost>
</configuration>
```

**Comment by davidebbo** [comment]
Please see https://github.com/projectkudu/kudu/wiki/Xdt-transform-samples#redirect-http-traffic-to-https for a well tested xdt that does this and excluses the scm site.

**Comment by gregjhogan** [comment]
@davidebbo the issue isn't that I can't get it to work (I actually started from the example you linked to, and was just playing around with it).  I reported the issue in case you wanted to enhance things such that you don't let people shoot themselves in the foot.  If not, you can disregard.  Thanks!

**Comment by davidebbo** [comment]
Unfortunately, it's hard to completely prevent self shooting. Since the xdt can apply to both main site and scm site, and Kudu runs under scm, a bad transform can easily hose IIS.

We do have an escape pod via `WEBSITE_PRIVATE_EXTENSIONS=0`.
