### ISSUE TITLE
Problem with Restart Site button

### ISSUE THREAD

**Issue by gregjhogan** [projectkudu/kudu#1878]
If I modify a site extension applicationHost.xdt file on a web app, save, then switch to the "Site Extension" tab and click the "Restart Site" button the applicationHost.config file updates, but the changes do not actually get picked up by the website.  If I go into the Azure portal and stop and start the app, the changes get picked up immediately.

**Comment by davidebbo** [comment]
Yes, the restart button just kills the scm site's process. It's not really a true restart, as it is not possible to trigger that from Kudu. Though another thing you can do from Kudu is go to Process Explorer and kill the non-scm w3wp. That'll pick up your main site xdt.

**Comment by gregjhogan** [comment]
@davidebbo it might be helpful to update the documentation to indicate how to restart things when making site extension changes.  It is really confusing to have a button named "Restart Site" on the site extension tab which causes the applicationHost.config to update, but doesn't actually cause the changes to get applied.  I was really confused because I was going through your documented debugging/investigation procedures in the wiki, and everything looked good, but things were not working.

**Comment by davidebbo** [comment]
Fair point. I added a note under https://github.com/projectkudu/kudu/wiki/Azure-Site-Extensions#private-extensions
