### ISSUE TITLE
Support Github private submodules out the box.

### ISSUE THREAD

**Issue by abelondevdep** [projectkudu/kudu#1884]
Please, support Github private submodules so it is just work without not stable workaround which wipe out when you do redeploy.

**Comment by davidebbo** [comment]
Can you please clarify what you mean by "not stable workaround which wipe out when you do redeploy"?

**Comment by abelondevdep** [comment]
Hi David,

Personally I couldn't setup private submodules and stuck on problem "fatal: reference is not a tree: 29f0cxxxxxxxxxxxxxxxxxxxxxxxx\nUnable to checkout '29f0cxxxxxxxxxxxxxxxxxxxxxx' in submodule path 'myapp/common-dotnet'\n\r\nD:\Program Files (x86)\Git\bin\git.exe submodule update --init --recursive". But it work I personally update project by other user on another machine, so git repository is fine.
 
But the following comment on forum http://blogs.suwatbodin.com/2013/07/deploy-to-windows-azure-using-git-with.html#comment-form
 made me not continue pursue.

> I have a similar situation: Github, private module and private submodule. I was able to autodeploy after generating ssh keys for the submodule repo and copying them the private and config file to .ssh folder of Azure site , while adding the public one to the account in Github used for deployment. 
> The problem is that every time I disable the auto deployment, the files are gone, and I have to copy them again to Azure next time, pretty fast, before the auto deployment reaches the point where it fetches the submodule and needs them. 
> We use this as a deployment method for production, so every 2 weeks I need to do this dance, once for each of our sites. I wish there is a way to configure the ssh keys for the machine so they are not gone when the auto deployment is disabled.

**Comment by davidebbo** [comment]
I'll let @suwatch comment further, but what's described in his post should work and should not require re-setting up something after each deployment. If you're running into a specific issue after trying the technique he describes, please provide details.

Note saying that it wouldn't make sense to make that just work at some point, but the premise that this is needed because the workaround is not 'stable' is probably incorrect.

**Comment by abelondevdep** [comment]
Other user comments is pointing out the @suwatch post is not complete. Nothing said about how to change url to git from https. How it should be done properly, I think I don't how to do it properly I guess.

And I am interested why there is no sense to support github private submodules without dances? (when you just set deployment from Azure Portal and it works as work project without submodules)
Demand of supporting git submodules are not popular enough?

**Comment by davidebbo** [comment]
It's unclear what they were trying. Again, if you're running into a specific issue, it needs to be looked at, but you will need to provide details in the post.

> And I am interested why there is no sense to support github private submodules without dances.

How did you conclude that there was 'no sense' in supporting this? Lots of feature make potential sense but are still lower priority than other things, and this is likely one of them, given the relatively low demand and the workarounds.

**Comment by abelondevdep** [comment]
My case is not specific, today is just second day of using submodules and I probably do something wrong enough that Azure couldn't update my one submodule.
What I did:
1. I copied the deployment key (d:\home\.ssh\id_rsa.pub) and pasted to this user as user key.  Because GitHub only allows one unique key I deleted the deployment key from repo before add as a user key.
2. Then I did go into changed git link to submodule from HTTPS to SSH variant.
And I get "fatal: reference is not a tree: ". But git repositories is in fine state as I can clone them on another computer.

 It is the same as problem from 2012
http://stackoverflow.com/questions/11939728/git-push-to-azure-websites-with-submodule
you even commented that 4 years ago.

**Comment by davidebbo** [comment]
That SO question was from before we had any submodule support (not even public), and has no reference to this 'reference is not a tree' error, so it does not look directly related to your issue.

Where exactly are you seeing this error? Can you share more of the log to put it in context? [this question](http://stackoverflow.com/questions/2155887/git-submodule-head-reference-is-not-a-tree-error) deal with a similar issue.

**Comment by abelondev** [comment]
It was my feature request to "Support Github private submodules out the box." When you have many web apps and all of them has common submodule. I don't have control on everything, team is spread out in whole world. Having submodules without dances would be timesaving.

**Comment by abelondev** [comment]
Thanks for pointing out the link and I conclude the following answer will help me, which is permissions problem. But I have no way to find out what wrong with permissions inside Azure.

> "Less likely, there's a permissions problem, and the commit cannot be pulled (possible if you're using git+ssh).
> Make sure the submodule paths look ok in .git/config and .gitmodules.
> One last thing to try - inside the submodule directory: git reset HEAD --hard"

**Comment by davidebbo** [comment]
Actually, you can use [Kudu Console](https://github.com/projectkudu/kudu/wiki/Kudu-console) to run arbitrary git commands on your repos just like you would locally. That may help get to the bottom of what's going on.

**Comment by abelondevdep** [comment]
I temporarily removed submodules and setup deploying using global User SSH Key.
I tried to use Kudu Console and clone operations failed with permission denied.

Is there any instruction how to work with Kudu Console with global user SSH key. I tried make general github SSH github and it also didn't work in Kudu.
 https://help.github.com/articles/generating-an-ssh-key/

For example:
```
D:\home\.ssh>ssh-add ~/.ssh/id_rsa
Could not open a connection to your authentication agent.
```

**Comment by abelondevdep** [comment]
Sorry, Ignore about last comment about Kudu console. Git work in Kude. I use kudu console from wrong site. I have multiple asp.net sites and that why I want out of box.

**Comment by abelondevdep** [comment]
Hi David,

I figure out how to setup submodules. You actually doesn't need to change urls from HTTPS to SSH in .gitmodules file. It works with HTTPS path type even parent folder setup on SSH.

But my feature request is still needed for simplifying of work.
--
Best regards, Andrey

**Comment by davidebbo** [comment]
Yes, to summarize the situation:

- there are workarounds. They work well but require some manual work.
- it would be better to have things just work out of the box. But there is some non-trivial work that's needed for this to work well, and there is no clear ETA at this time.

Let's keep this issue active to track it.

**Comment by abelondev** [comment]
I accidentally closed this issue.

**Comment by abelondevdep** [comment]
Yes, it is not stable. It just stop working after 4 commit with
`STATUS 
Failed
TRIGGERED BY 
GitHub
AUTHOR 
Andrey Belonogov
RAN FOR 
21 seconds
REASON 
touch from log-server 4
DEPLOY TO 
logsservice
STATUS
TIME
ACTIVITY
LOG
Tue 02/09
Updating submodules.
View Log
  
Activity Logs
fatal: could not read Username for 'https://github.com': Bad file descriptor\nUnable to fetch in submodule path`

**Comment by abelondevdep** [comment]
Yes, it is not stable. It just stop working after 4 commit with

fatal: could not read Username for 'https://github.com': Bad file descriptor\nUnable to fetch in submodule path`

**Comment by abelondevdep** [comment]
What I learn if you mess up with order commiting submodule and parent repository anyway nothing will help you to restore deployment on azure. It seems all restore measures which work in unusual environment will fail in azure environment.

The submodule has to be removed and add it again to parent repository.

**Comment by abelondevdep** [comment]
Actually I couldn't setup. There is no stable workaround. I have to periodically change https: protocol to git protocol whenever it reset by some unknown yet reason. And few days I didn't have to do it.
D:\home\site\repository\.git\modules\<module name>\config

**Comment by mnuzzolilo** [comment]
@davidebbo would my suggested fix here solve this? https://github.com/projectkudu/kudu/issues/1972

**Comment by phawxby** [comment]
@davidebbo this appears to still be an issue. Two years on, is there any further advice or ETA on a fix?

**Comment by davidebbo** [comment]
@phawxby no update on this one. However, note that the steps described in the post above do work, albeit with a few more manual steps.

**Comment by jvano** [comment]
Hi

Kudu will continue to run in Azure App Service. However, this repo will no longer be maintained.
If the problem persists and is related to running on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
