### ISSUE TITLE
Sync Triggers needs to respect Disabled functions

### ISSUE THREAD

**Issue by mathewc** [projectkudu/kudu#1891]
Function metadata also supports a "disabled" attribute as follows:

``` javascript
{
  "disabled": true,
  "bindings": {
    "input": [
      {
        "type": "timerTrigger",
        "schedule": "05:00:00"
      }
    ]
  }
}
```

The function runtime does not run a disabled function (e.g. it won't be polling the queue, running the timer, etc.). Details on format can be found in the wiki here: https://github.com/Azure/azure-webjobs-sdk-script/wiki/function.json.

**Comment by davidebbo** [comment]
It'd be so much easier if there was a way to do this from the Functions app instead of Kudu.

**Comment by mathewc** [comment]
I don't understand your comment David. I created this issue because currently the Kudu API is the one choosing which functions to report back with and it needs to take this into account. The Functions app portal will have a toggle button mapping to this setting.

**Comment by davidebbo** [comment]
I meant that ideally we'd find a way for this logic to exists in the functions app instead. Right now, we're in a bit of a strange situation as Functions effectively have a split management API, some of it in Kudu and some of it in Functions app.

**Comment by jvano** [comment]
Hi

Kudu will continue to run in Azure App Service. However, this repo will no longer be maintained.
If the problem persists and is related to running on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
