### ISSUE TITLE
Unable to run custom post deployment script

### ISSUE THREAD

**Issue by litera** [projectkudu/kudu#1894]
I have an Asp.net Web application on Azure and I've also created a post deployment script, that used to run up until the end of the year (last time I was deploying was 23/12/2015) and the next time in this year when I deployed (first time in new year 11/01/2016) it wasn't running any more.

### What I have
1. I have `.deployment` file in my solution root (also git repo root)

    ```
    [config]
    SCM_POST_DEPLOYMENT_ACTIONS_PATH=deployment
    ```
2. I have folder `\deployment` in my root where I keep my special post deployment `cmd` file
3. I have set application setting in Azure portal to also define `SCM_POST_DEPLOYMENT_ACTIONS_PATH = deployment` although I think I only need to define it once (in file or app settings) even though I don't know which one takes precedence - but this is irrelevant as they both define the same value

And this used to work just fine as initially described. After *KuduSync.NET* copied changed files it automatically executed my custom post deployment script as shown in this log excerpt:
```
...
Copying file: '...'
Executing - 'D:\home\site\repository\deployment\PostDeployment.cmd'
... [my script output here]
'D:\home\site\repository\deployment\PostDeployment.cmd' executed successfully
Finished successfully.
```
But after the new year this is the output:
```
...
Copying file: '...'
Finished successfully.
```

### What I tried
1. I tried changing `SCM_POST_DEPLOYMENT_ACTIONS_PATH` to `POST_DEPLOYMENT_ACTIONS_DIR` in both my file and in Azure app settings
2. I tried setting path to `site\repository\deployment`
3. I removed setting from `.deployment` file keeping only Azure app setting
4. Changed path to be relative to deployed project instead of solution from `SCM_POST_DEPLOYMENT_ACTIONS_PATH=deployment` to `SCM_POST_DEPLOYMENT_ACTIONS_PATH=..\deployment`  

None of these worked in a sense that my custom script would even run. It doesn't get executed by Kudu at all. No error, no nothing. I don't see any changes that it would make nor do I see any output in the logs... **What am I doing wrong?**

**Comment by davidebbo** [comment]
You describe how you set things up, but don't give info about the observed behavior. Did it cause a failure? Or did the flag simply get ignored? Does it work if you don't set the flag and drop a script under `site\deployments\tools\PostDeploymentActions`? Not saying you should be doing that, but to validate if at least that works.

**Comment by litera** [comment]
@davidebbo well I did. My first paragraph says that my custom script **isn't running any more**. And this means regardless of what I tried. No change from my side changed anything about CI git deployment on Azure. I don't get any errors or anything. It's just that my app is physically deployed but **my custom script hasn't been executed** after a successful deployment. It it was I would see changes in my DB and some output in the logs.

**Comment by shrimpy** [comment]
@litera can you try to set absolute path e.g "d:\home\site\repository\deployment" ?

**Comment by litera** [comment]
#Great!

**This worked!** And while testing I can see that App settings have precedence over settings in the `.deployment` file.

Absolute path setting should be reflected in Wiki pages.

**Comment by davidebbo** [comment]
Actually, this is a regression that we are fixing per #1901. So once we deploy the fix, what you used to do will work again. Using the full path is more of a temporary workaround.

**Comment by litera** [comment]
@davidebbo That's ok, as long as fullpath will work afterwards just as well. Will you be updating this issue as well, when #1901 is fixed?

**Comment by shrimpy** [comment]
Fixes is out. Relative path should work for you now!

Thanks,
Xiaomin Wu

Sent from Outlook<http://taps.io/outlookmobile> Mobile



On Sat, Feb 20, 2016 at 1:39 AM -0800, "Robert Koritnik" <notifications@github.com<mailto:notifications@github.com>> wrote:


@davidebbo<https://github.com/davidebbo> That's ok, as long as fullpath will work afterwards just as well. Will you be updating this issue as well, when #1901<https://github.com/projectkudu/kudu/pull/1901> is fixed?

-
