### ISSUE TITLE
Webjob Webhooktrigger issue

### ISSUE THREAD

**Issue by diogoandrei** [projectkudu/kudu#1895]
I'm attempting to POST to a webjob function with webhooktrigger but I'm getting the error

An attempt was made to access a socket in a way forbidden by its access permissions

Do you have any idea why and how I could solve that? Thank you!

**Comment by davidebbo** [comment]
What kind of language/code are you using for your WebJob? The sandbox does not allow every kind of socket listening.

**Comment by diogoandrei** [comment]
I'm using C# .NET and the webjob is already running on Azure.

**Comment by davidebbo** [comment]
I just discussed with others. Webhooktrigger is an experimental thing in the WebJobs SDK (not part of Kudu), and it will likely probably be removed as we are taking a different direction. So I would suggest not using it at this time.
