### ISSUE TITLE
How to define connection string for session state

### ISSUE THREAD

**Issue by ricardopolo** [projectkudu/kudu#1903]
I am using the `RedisSessionStateProvider` using a procedimient like this https://azure.microsoft.com/en-us/documentation/articles/web-sites-dotnet-session-state-caching/

````
  <system.web>
    <compilation debug="true" targetFramework="4.6.1" />
    <httpRuntime targetFramework="4.5" />
    <globalization culture="es-CO" uiCulture="es" />
    <customErrors mode="Off" />
    <sessionState mode="Custom" customProvider="SessionStateStore">
      <providers>
        <add name="SessionStateStore" type="Microsoft.Web.Redis.RedisSessionStateProvider" connectionString="XXXXXX" throwOnError="true" applicationName="NominappSession" />
      </providers>
    </sessionState>
  </system.web>
````

As you see I need to define a connection string, in the example `XXXXXX`  but I dont want to put it in my source code. So how can i using the settings in Azure define this connection string?

Any advice please?

**Comment by davidebbo** [comment]
I don't think that relates to Kudu. For general Azure Web Apps questions, please use the [forum](https://social.msdn.microsoft.com/Forums/azure/en-US/home?forum=windowsazurewebsitespreview) or StackOverflow.

**Comment by ricardopolo** [comment]
@davidebbo Wy not is related to Kudu? 

I know Kudu replaces the connection strings, and app settings, for the one defines in Azure. But not this kind of connection string.  Am I wrong?

**Comment by davidebbo** [comment]
Kudu actually plays no part in that mechanism. It's a runtime thing that happens without the physical config file ever being modified. So at deployment time (what Kudu does), this doesn't come in the picture.

**Comment by ricardopolo** [comment]
all right, thanks!

**Comment by ricardopolo** [comment]
The solution was http://stackoverflow.com/questions/35529052/how-to-define-connection-string-for-session-state-in-azure/35641453#35641453
