### ISSUE TITLE
Webjob runs manually but does not run on a scheduled basis

### ISSUE THREAD

**Issue by ghost** [projectkudu/kudu#1904]
I have a Standard-tier web application. I use vNext (CI) to deploy my web application and webjob (with the "/p:_DestinationType=AzureWebSite" parameter). Both are deployed successfully, and I can run my webjob manually from the console. However, it is not running on a schedule (set to every hour).

My webjob-publish-settings.json looks fine. Then I learned about the settings.job file and I added it to my webjob project (again set to "schedule": "0 0 \* \* \* *"). I can actually see these settings at the webjob debugging url (https://[mywebapp].scm.azurewebsites.net/api/triggeredwebjobs/[mywebjob]). However, "scheduler_logs_url" is set to null in the returned JSON object.

The last thing that I will need to try is to start a JobHost from my webjob. Something like:
var host = new JobHost();
host.Start();

But I haven't read anywhere that this is required. My question is - other than that, and considering all the information above, what else could I try? Thank you so much.

**Comment by davidebbo** [comment]
`host.Start()` is only for continuous jobs, so you definitely don't want that. Try looking under the `D:\home\data\jobs\triggered` folder using [Kudu Console](https://github.com/projectkudu/kudu/wiki/Kudu-console) to check for interesting logs.

Also, if that doesn't help, can you share your web app name, either directly or [indirectly](https://github.com/projectkudu/kudu/wiki/Reporting-your-site-name-without-posting-it-publicly)?

**Comment by dquser** [comment]
Thank you David. I'll take a look at those logs and report back. The complete debugging URL is:
https://panoramaframework.scm.azurewebsites.net/api/triggeredwebjobs/data

**Comment by dquser** [comment]
Thanks again. I looked into that folder (D:\home\data\jobs\triggered\Data, where Data is the name of my webjob). I see a "WebJobsSdk.marker" file which just contains a timestamp ("2016-02-19T01:34:06Z") and some folders named with timestamps.

The last folder corresponds to the last time I executed my webjob manually. The "output_log.txt" file contains:
[02/20/2016 22:41:42 > 7a74f2: SYS INFO] Status changed to Initializing
[02/20/2016 22:41:46 > 7a74f2: SYS INFO] Run script 'Panorama.Infrastructure.WebJob.exe' with script host - 'WindowsScriptHost'
[02/20/2016 22:41:46 > 7a74f2: SYS INFO] Status changed to Running
[02/20/2016 22:41:47 > 7a74f2: INFO] Console.Out - Email sent successfully
[02/20/2016 22:41:47 > 7a74f2: SYS INFO] Status changed to Success

The "status" file contains:
{"Trigger":"External - Portal-Exp/5.12.0.278 (Websites) Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML%2C like Gecko) Chrome/48.0.2564.109 Safari/537.36","Status":"Success","StartTime":"2016-02-20T22:41:42.9284352Z","EndTime":"2016-02-20T22:41:47.6802613Z"}

It may be worth noting that I haven't setup the "AzureWebJobsDashboard" connection string in my webjob. However, I can run the webjob manually without this setting.

Could this missing connection string be getting in the way? Thank you so much again.

**Comment by davidebbo** [comment]
Not likely. I'll try to take a look in a bit to see what's going on.

**Comment by davidebbo** [comment]
It seems it was in a weird state that I couldn't explain. When I restarted the scm site, I instantly saw the `job_scheduler.log` getting created under `D:\home\data\jobs\triggered\Data`, so I'm guessing it's going to be ok now. But we'll need to monitor whether it gets back in that state.

**Comment by dquser** [comment]
Thank you so much David, I will keep monitoring it and report back if anything. Thank you!

**Comment by kirajhpang** [comment]
Hi David, I do have the same issues. 

my `` job_scheduler.log`` contain following message:

```
[06/23/2016 03:48:09 > e50433: SYS WARN] Missed 2 schedules, most recent at 6/18/2016 12:00:00 AM
[06/23/2016 03:48:09 > e50433: SYS INFO] Scheduling WebJob with 0 0 0 * * 6 next schedule expected in 1.20:11:50.9371058
[06/23/2016 05:37:56 > e50433: SYS WARN] Missed 2 schedules, most recent at 6/18/2016 12:00:00 AM
[06/23/2016 05:37:56 > e50433: SYS INFO] Scheduling WebJob with 0 0 0 * * 6 next schedule expected in 1.18:22:03.5008166
[06/23/2016 05:57:49 > 730653: SYS WARN] Missed 2 schedules, most recent at 6/18/2016 12:00:00 AM
[06/23/2016 05:57:49 > 730653: SYS INFO] Scheduling WebJob with 0 0 0 * * 6 next schedule expected in 1.18:02:10.4530271
[06/27/2016 01:22:00 > 730653: SYS WARN] Missed 3 schedules, most recent at 6/25/2016 12:00:00 AM
[06/27/2016 01:22:00 > 730653: SYS INFO] Scheduling WebJob with 0 0 0 * * 6 next schedule expected in 4.22:37:59.5637663
[06/27/2016 01:22:14 > e50433: SYS WARN] Missed 3 schedules, most recent at 6/25/2016 12:00:00 AM
[06/27/2016 01:22:14 > e50433: SYS INFO] Scheduling WebJob with 0 0 0 * * 6 next schedule expected in 4.22:37:45.9796019
```

My scheduler should run on every Saturday 0AM, so I put as ``0 0 0 * * 6`` which I think is correct, but the web job didn't invoke and last running record still is long long time ago. 

Any suggestion for changes?

**Comment by davidebbo** [comment]
@kirajhpang please make sure your Web App has Always On enabled.

**Comment by kirajhpang** [comment]
@davidebbo ok, let me give it a try..!! Thanks for the reply.

**Comment by JPThorne** [comment]
Hi there, we're also getting these sorts of errors: 

SYS WARN] Missed 281 schedules, most recent at ... etc. 

Our web app is not set to always on, the blurb about it: 

"Indicates that your web app needs to be loaded at all times. By default, web apps are unloaded after they have been idle. It is recommended that you enable this option when you have continuous web jobs running on the web app."

However, our web job is set to run on a schedule, every 10 minutes, not continuously. 

Is this just a somewhat poorly described item?

**Comment by nickwalkmsft** [comment]
@JPThorne Always On is also recommended for apps that contain CRON-scheduled jobs.

CRON-scheduled jobs are triggered by the Kudu site, which is liable to be unloaded just like the primary site if Always On is not enabled.

**Comment by davidebbo** [comment]
Also, more info on https://docs.microsoft.com/en-us/azure/app-service-web/web-sites-create-web-jobs#CreateScheduledCRON.

I created a doc pull request for https://docs.microsoft.com/en-us/azure/app-service-web/web-sites-configure, changing it to:

> By default, web apps are unloaded if they are idle for some period of time. This lets the system conserve resources. In Basic or Standard mode, you can enable **Always On** to keep the app loaded all the time. If your app runs continuous WebJobs or runs WebJobs triggered using a CRON expression, you should enable **Always On**, or the web jobs may not run reliably.

@JPThorne is that the doc page you were looking at?

**Comment by davidebbo** [comment]
Ok, @nickwalkmsft told me that came from Portal UI. We'll ask to get this updated as well.

**Comment by JPThorne** [comment]
Perfect feedback, thanks very much

**Comment by hahaxj** [comment]
@davidebbo ,Now the link :https://docs.microsoft.com/en-us/azure/app-service-web/web-sites-configure
has not been update, could you help confirm it ? Now it show as following, there is no info  for triggered webjob : 
Always On. By default, web apps are unloaded if they are idle for some period of time. This lets the system conserve resources. In Basic or Standard mode, you can enable Always On to keep the app loaded all the time. If your app runs continuous web jobs, you should enable Always On, or the web jobs may not run reliably.

Thanks a lot.

**Comment by davidebbo** [comment]
Indeed, the doc change had not made it. It is now updated!

**Comment by jvano** [comment]
Hi

Kudu will continue to run in Azure App Service. However, this repo will no longer be maintained.
If the problem persists and is related to running on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
