### ISSUE TITLE
WebJob CRON scheduler fails intermittently after swaps

### ISSUE THREAD

**Issue by makhdumi** [projectkudu/kudu#1906]
We're running several CRON-scheduled WebJobs, and last night two of them (unfortunately, rather important ones) did not run on schedule.

This sounds similar to https://github.com/projectkudu/kudu/issues/1796, but I see very different symptoms than what's described there (e.g. no issues with history, or weird status files from previous runs).

The very last lines in the scheduler logs for each were:

> [02/24/2016 03:39:25 > 341c6a: SYS INFO] Scheduling WebJob with 0 0 7 * * * next schedule expected in 03:20:34.2814864

> [02/24/2016 03:39:25 > 341c6a: SYS INFO] Scheduling WebJob with 0 0 6 * * * next schedule expected in 02:20:34.2006864

- The scheduler logs were "stuck" like this for 12+ hours, even on our staging slot
- There were no previous instances of the jobs still running (based on the history. They last seconds, and are run every 24 hours)
- The previous runs all ran without any errors
  - I don't expect it to run there because of WEBJOBS_STOPPED, but normally I see it still 
- I triggered the jobs manually ~7 hours later without any problems
scheduling and then "missing" the jobs - which is cool
- Other triggered jobs on the same WebApp ran fine, and I see output in the scheduler logs for them well past 03:20:34.2814864
- These two same jobs on our dev/test sites ran on schedule, without problem
- After turning on the staging site and then restarting it, the scheduler logs on the staging site updated, saying it "Missed 1 schedules, most recent at 2/24/2016 6:00:00 AM".
- Unlike https://github.com/projectkudu/kudu/issues/1796, the job information itself, e.g. history, is perfectly fine. It seems like just the scheduler had issues

Would it be possible to show more logs in the scheduler? e.g. IIRC when the scheduler triggers a job and there's an instance already running, no errors are mentioned in the scheduler logs (while you do get an error if you manually trigger the job via the API).

**Comment by makhdumi** [comment]
I had this issue happen again on a completely different job, probably because I did a swap around the time it was next scheduled. 

The two jobs I've seen the issue with before are scheduled to run around the time we normally automatically deploy/swap.

**Comment by davidebbo** [comment]
It could be caused by #1940.

**Comment by makhdumi** [comment]
This seems to have been fixed by #1940. We haven't seen it for some time now.
