### ISSUE TITLE
Specify custom script in App Settings

### ISSUE THREAD

**Issue by sudsy** [projectkudu/kudu#1909]
I have a repository with a number of projects contained within it. 

Currently I have been deploying 4 of these projects using the technique https://github.com/projectkudu/kudu/wiki/Customizing-deployments#using-app-settings-instead-of-a-deployment-file

I now have a project that requires a custom deployment script but I don't want to unintentionally break publishing settings of the other 4 projects.

Is there are way to use app settings to specify a custom deployment script? That way I could point to a project specific deployment script just for one of my projects and leave the others as they are. I have been searching the source, but haven't found a way yet.

I can see that the solution [http://blog.amitapple.com/post/38419111245/azurewebsitecustomdeploymentpart3/#.Vs_SA5N97cI](here) would allow me to use PROJECT_FLAVORS to achieve a similar thing, but it risks breaking my existing publishing processes.

**Comment by sudsy** [comment]
For anyone else with a similar issue, I have found a workaround which was to use the standard node deployment script which calls npm install --production. Then I have configured some postinstall and preinstall scripts to turn npm install --production into a custom build script. Some inspiration for this was taken from [http://blog.keithcirkel.co.uk/how-to-use-npm-as-a-build-tool/](url)

Closing this issue for now, but if there is a way to do what I was asking in the original question, please let me know.

**Comment by davidebbo** [comment]
You just need to set the `COMMAND` app setting described in that same page.

**Comment by sudsy** [comment]
Thanks for that.
