### ISSUE TITLE
Using scm azurejobs interface with deployment slot

### ISSUE THREAD

**Issue by aaronhoffman** [projectkudu/kudu#1912]
The *scm.azurewebsites.net/azurejobs/ web interface does not appear to respect the deployment slot that is currently active.

If I have an app service called `myapp`, and a deployment slot called `staging`, I see the Live (not `staging`) set of jobs listed if I navigate to `staging` deployment slot URL:

https://myapp.scm.azurewebsites.net/azurejobs/#/functions
https://myapp-staging.scm.azurewebsites.net/azurejobs/#/functions

From within the `myapp-staging` subdomain, if I navigate to an individual webjob and trigger it, it will execute the webjob within the Live deployment slot, and not the `staging` slot.

**Comment by ahmelsayed** [comment]
The dashboard view is generated from the storage account you have setup in your AppSettings. Do you have the same storage account connection string in both the production and staging slots?

**Comment by aaronhoffman** [comment]
Ah, yes, I see a connection string with a key `AzureWebJobsDashboard`, it has the same value in both the `production` and `staging` deployment slots.

I do not remember adding that key myself. Is it added by kudu? (another developer on my project may have added that key)

Seeing this, I now realize I was on the Invocation page for a WebJob from the `production` slot, even though I was on the `staging` deployment slot scm webpage. When I attempted to "replay" the function from that page, it replayed the function for the WebJob in the `production` slot.

Is the recommendation to create a different storage account for each deployment slot? Or can the same storage account be used with multiple deployment slots?

If the same WebJob is deployed to two different deployment slots, will it have the same `host-id`?

**Comment by davidebbo** [comment]
Kudu never sets any App Settings, so they probably came from somewhere else.

I think you could make cases for using the same or different. If you use different ones, make sure to make them slot settings so they stick to their slot and don't swap!

**Comment by aaronhoffman** [comment]
If you use the same Storage Account for two Deployment Slots, in my opinion, it would be nice to somehow indicate within the SCM UI which Deployment Slot each WebJob is associated with (at the current time, and the time of the invocation, on the /functions and /functions/invocations/ pages for example).

I have forked the project and hope to be able to have time to look into the possibility of this.

I would consider this issue resolved since it was my misunderstanding of how the *scm pages were working. I will close, apologies if that is not the proper workflow.

**Comment by ahmelsayed** [comment]
btw, this is the webjobs sdk (which includes the azurejobs dashboard) repo https://github.com/Azure/azure-webjobs-sdk
