### ISSUE TITLE
How to connect to remote UNC paths? Is it possible?

### ISSUE THREAD

**Issue by shamusschubert** [projectkudu/kudu#1913]
I have C# console apps that move files from place A to place B across our network.  This is an internal private Azure cloud.  

I have verified the account the WebJob is running under has access to the share.

I get:  [02/29/2016 19:07:56 > 9b2e97: ERR ] Unhandled Exception: System.UnauthorizedAccessException: Access to the path '\\***blahblah***' is denied.

I sit possible to connect to remote UNCs or windows shares?

**Comment by davidebbo** [comment]
Not a Kudu limitation, but this is likely being blocked by the [sandbox](https://github.com/projectkudu/kudu/wiki/Azure-Web-App-sandbox) that everything runs under.
