### ISSUE TITLE
US date format assumptions in unit tests

### ISSUE THREAD

**Issue by WiredUK** [projectkudu/kudu#1916]
When building Kudu using the *build.cmd* command line option I get an error due to date formats. Specifically I get is `String was not recognized as a valid DateTime`. As it errors, I am unable to build the artifacts folder.

This exception occurs in [`https://github.com/projectkudu/kudu/blob/master/Kudu.Core.Test/Jobs/ScheduleFacts.cs`](https://github.com/projectkudu/kudu/blob/master/Kudu.Core.Test/Jobs/ScheduleFacts.cs) with the 3 tests that use dates in `12/31/2014`. When I comment them out, everything builds correctly. It looks like it errors because the test assumes dates are in local format and I'm in UK which requires `21/12/2014`

**Comment by davidebbo** [comment]
Is this the line that throws?

    DateTime lastSchedule = DateTime.Parse(lastScheduleStr, CultureInfo.InvariantCulture, DateTimeStyles.AssumeLocal);

It's strange because it claims to use invariant culture. Might need some other flags. If you find correct way to make it work in all cultures, please send PR.

**Comment by mathewc** [comment]
Here is the approach that we use in the WebJobs SDK test repo: https://github.com/Azure/azure-webjobs-sdk/pull/534

Basically a class fixture for test classes that sets and restores the culture info.

**Comment by WiredUK** [comment]
@davidebbo Yes, it's that line. I think @mathewc has the right approach to fixing the issue without fixing the format that the method takes as input. Though I do like to do that, ISO8601 date format is often a good approach.

**Comment by davidebbo** [comment]
Yes, that approach sounds fine. But why is it broken in the first place given that we pass `CultureInfo.InvariantCulture` to `Parse()`?

**Comment by WiredUK** [comment]
This is only a test method anyway, so why not simply force the formatting style rather than rely on local culture?

**Comment by WiredUK** [comment]
Ah dammit, I was running off release S48, this issue was fixed in https://github.com/projectkudu/kudu/commit/ffb3f90df1346d52d00d52fe6da2633935d22afb 3 days after that.
