### ISSUE TITLE
NuGet package restore should use -NonInteractive flag

### ISSUE THREAD

**Issue by davidmatson** [projectkudu/kudu#1917]
When package restore needs credentials, it prompts by default, causing deployments to timeout. NuGet.exe has a -NonInteractive flag to prevent that kind of hang/timeout.

**Comment by davidebbo** [comment]
Yes, that would make sense. This is in a slightly different repo: https://github.com/projectkudu/KuduScript/. e.g. see [here](https://github.com/projectkudu/KuduScript/blob/53122bfdf9beda5d00e38847a4ba954100120694/lib/templates/deploy.batch.aspnet.wap.template#L10), and a few other files in the same folder.

**Comment by davidmatson** [comment]
Thanks; moved to [bug # 46 in the KuduScript repo](https://github.com/projectkudu/KuduScript/issues/46).
