### ISSUE TITLE
Support AppSettings as credentials for NuGet package restore

### ISSUE THREAD

**Issue by davidmatson** [projectkudu/kudu#1918]
NuGet allows using an environment variable NuGetPackageSourceCredentials_SOURCENAME to pass credentials for private feeds. However, app settings are prefixed, so they can't be used to set this environment variable.

A few options for a solution:

1. Provide a way to set general environment variables for a web app.
2. Specifically copy any APPSETTING_NuGetPackageSourceCredentials_* environment variables to one without the prefix.
3. Install a NuGet credential provider alongside NuGet.exe that retrieves credential data from AppSettings. Note that, unlike the built-in environment variable, a credential provider only knows the full package source URL, not just the (shorter) package source name from NuGet.config.

**Comment by davidebbo** [comment]
> app settings are prefixed, so they can't be used to set this environment variable

That is not correct. If you add an App Setting called `FOO`, you will get an environment variable called exactly `FOO`. You also get one with the prefix, but that's an implementation details and you should never write code that assumes this.

Can you try that and see if that just works? If so, we can close this.

**Comment by davidmatson** [comment]
I see; I had skimmed this [article](https://azure.microsoft.com/en-us/documentation/articles/web-sites-configure/) that documented the prefixes and missed the part about the non-prefixed copy being available. Thanks for the clarification!
