### ISSUE TITLE
Run web jobs as part of a site extension

### ISSUE THREAD

**Issue by sjkp** [projectkudu/kudu#1923]
Hi 
I took a look at the kudu code, and as far as i can see there is no way to run web jobs hosted in a site extension (under the folder siteextensions<site-extension-name>)? Is that correct or am I missing something? 

The reason for asking is that I have the letsencrypt-siteextension, that uses web jobs that the extension installs in the site\wwwroot\app_data to renew SSL certificates. This works fine, as long as people dont deploy from VS with the switch delete existing files, but when they use that switch my web jobs are deleted (which they should, since they are placed with the user code). 

If I create a pull request that adds the functionality to run webjobs as part of a site extension is that something you would consider accepting, or is my approach a no go?

**Comment by amitapl** [comment]
For site extensions the webjobs are copied from the site extension to the site during installation.

See here:
https://github.com/projectkudu/kudu/blob/d1768a01099499851611435ec872a0769e5cc10b/Kudu.Core/SiteExtensions/SiteExtensionManager.cs#L870-L875

It seems this can be overidden with the scenario you have here when someone is deploying using webdeploy and a switch to delete existing files.

**Comment by jvano** [comment]
Hi

Kudu will continue to run in Azure App Service. However, this repo will no longer be maintained.
If the problem persists and is related to running on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
