### ISSUE TITLE
Sandbox wiki page's Restricted Outgoing Ports section should use "regardless" instead of "regarding"

### ISSUE THREAD

**Issue by GageAmes** [projectkudu/kudu#1925]
I believe the [Restricted Outgoing Ports section of the sandbox wiki page](https://github.com/projectkudu/kudu/wiki/Azure-Web-App-sandbox#restricted-outgoing-ports) should state

> **Regardless** of address, applications cannot connect to anywhere using ports 445, 137, 138, and 139. 

(regardless instead of regarding).  In other words, even if connecting to a non-private IP address or the address of a virtual network, connections to ports 445, 137, 138, and 139 are not permitted.

**Comment by mathewc** [comment]
Fixed, thanks :)
