### ISSUE TITLE
webjob-publish-settings.js does not validate against schema

### ISSUE THREAD

**Issue by mteper** [projectkudu/kudu#1928]
_From @mteper on March 13, 2016 23:20_

"Continuous" job types seems incongruent with the schema. See R# discussion for more detail: https://youtrack.jetbrains.com/issue/RSRP-454885.

_Copied from original issue: Azure/azure-webjobs-sdk#658_

**Comment by mteper** [comment]
_From @mathewc on March 14, 2016 4:24_

Please move this issue to the Kudu repo, as it deals with core WebJobs, not the WebJobs SDK. Thanks :) https://github.com/projectkudu/kudu/issues

**Comment by davidebbo** [comment]
I know you'll find this confusing, but that's actually a VS file that Kudu knows nothing about. In any case @bradygaster might be able to comment.

**Comment by mteper** [comment]
@davidebbo makes sense, actually, but any help in identifying the right repo to land this issue in would be appreciated. :)

**Comment by davidebbo** [comment]
There is no repo, since VS itself is not on GitHub. But in any case, let's see if @bradygaster can help you here instead of making you jump around :)

**Comment by bradygaster** [comment]
In VS this file validates against the schema we put into the file in the project template. We're also planning a deprecation of this approach for later this year. The schema we validate against is up-to-date, stored [here](http://schemastore.org/schemas/json/webjob-publish-settings.json), and does account for the Continuous value.

**Comment by mteper** [comment]
@bradygaster as I understand it, the issue here is not that the schema on schemastore.org is out of date or does not include support for the "Continous" value, but rather that the JSON file generated by VS includes a handful of properties (`startTime`, `endTime`, etc.) that are not applicable in continuous mode and that cause schema validation to fail. Try it for yourself by plugging the schema contents and the JSON into http://jsonschemalint.com/draft4/. If you cut out the irrelevant properties, the JSON file will validate correctly.

When you say:
>  We're also planning a deprecation of this approach for later this year.

What are you referring to?

**Comment by bradygaster** [comment]
@mteper what I mean is, we'll have an update to the WebJobs tooling by end-of-2016 that no longer requires the usage of these JSON files.The schemastore JSON file does include "Continuous" and "OnDemand" for the "runMode" property.

**Comment by mteper** [comment]
@bradygaster 

> The schemastore JSON file does include "Continuous" and "OnDemand" for the "runMode" property.

Yes, I can see that, *but* the VS-generated JSON fails to validate against that schema because of the extra properties it includes. This is a (mostly) cosmetic issue because ReSharper (rightly) flags these as errors and I have a permanent half-dozen errors in my solution now. However, we all know the danger of these persistent errors/warnings -- they can cause real issues to go unnoticed / ignored.

**Comment by jvano** [comment]
Hi

Kudu will continue to run in Azure App Service. However, this repo will no longer be maintained.
If the problem persists and is related to running on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
