### ISSUE TITLE
post deployment actions stopped working?

### ISSUE THREAD

**Issue by nickmeldrum** [projectkudu/kudu#1933]
Hi Kudu :)

I have a few sites on azure - all using kudu to deploy from github off a webhook.

They all have the same setup for my custom actions:
(not overriding the default deployment script)

1. Configure an AppSetting: SCM_POST_DEPLOYMENT_ACTIONS_PATH to point to "build\post-deploy-actions"
2. add .cmd files in my repo in ~/build/post-deploy-actions to do some custom deployment stuff
3. Profit :)

All used to work fine - any .cmd files I put in there ran. However they seem to have stopped running recently - any idea why? has something changed with you or with me? :)

**Comment by nickmeldrum** [comment]
No idea if you can dig into this stuff (you have my permission to look at anything if you need it), but I have checked the logs...

on my azure website with the name "nickmeldrum" the last deployment was on the 16th Dec 2015 and this log file shows the "post-deploy-actions" scripts executing at the end of the main deployment log (the one with the message: ""Running deployment command..."):

https://nickmeldrum.scm.azurewebsites.net/api/deployments/346f8321eceb22d79cc790a32d76a5eb4fcfd7b6/log/398e0762-723b-4e99-b4ae-f43060270f37

The log output being:

```
{
log_time: "2015-12-16T14:05:02.6951853Z",
id: "",
message: "Executing - 'D:\home\site\repository\build\post-deploy-actions\robots.cmd'",
type: 0,
details_url: null
}
```

However, the oldest deployment log I can get to on my staging site (as far as I know the same setup) is from the 10th March 2016:

https://nickmeldrum-staging.scm.azurewebsites.net/api/deployments/5a00fc1b428acdeb4de13ee7e852aabe6b30d0aa/log

And it seems to have a new entry:

```
{
log_time: "2016-03-10T14:35:09.1117189Z",
id: "64a52f61-4d16-4a7c-b52e-aa79a2c9f74e",
message: "Running post deployment command(s)...",
type: 0,
details_url: null
}
```

but with no child log (to me implying that there was nothing run).

So I guess there was a change between december and march which at the least shows "post deployment commands" show up on the log in a different place... could this be linked to them not working for me any more?

**Comment by davidebbo** [comment]
It looks the same as #1894, which was a regression. However, it's supposed to have been fixed, so I'm not sure why it's still happening. @shrimpy?

@nickmeldrum the workaround is to use absolute path (see that other issue).

**Comment by nickmeldrum** [comment]
I had a dig around in the source and found that the post deployment actions used to be run from postdeployment.cmd
which just did a `dir /s /b %POST_DEPLOYMENT_ACTIONS_DIR%\*.cmd %POST_DEPLOYMENT_ACTIONS_DIR%\*.bat %POST_DEPLOYMENT_ACTIONS_DIR%\*.ps1` which I guess means this directory was relative to the repository root (or absolute of course.)

However this commit: https://github.com/projectkudu/kudu/commit/960e878b1a471c49009952c2bb6609f654d8df0a#diff-3b7400171e7196dda66add21b1326a8a
"Support multiple post deployment steps." committed on the 29th Dec 2015 changes ExternalCommandBuilder.cs to RunCommands() from the directory: `var defaultPath = Path.Combine(Environment.DeploymentToolsPath, PostDeploymentActions);` which now means the relative directory has changed to the deployment tools path instead of the repository root.

I can't work out how to change my directory in my app settings to refer to the current repository root - any ideas?

**Comment by nickmeldrum** [comment]
Sorry @davidebbo didn't see your post just then - I will try the absolute directory suggested in the issue you linked...

**Comment by nickmeldrum** [comment]
Can confirm that the absolute dir: D:\home\site\repository\build\post-deploy-actions fixed it for me yay :)

I'm sure it's obvious but I'm assuming the fix to the regression here: https://github.com/projectkudu/kudu/commit/d7c9672e73c2b62e4d045863fcf3be5261f3d76a
that allows this postdeploymentpath to be relative is just now relative to a directory other than the repository root (presumably the directory that is executing these scripts?) but I have to get a deployment out now so no time to carry on the investigation - if I get time later tonight I will have a deeper look.

**Comment by shrimpy** [comment]
Hi Nick,

I had a fix earlier to use d:\home as root for relative path.  But from your code, seems like the original root should be d:\home\site\repository

I will update the fix. Sorry for the inconvenience.
as for now please use absolute path as work-around.

Thanks,
Xiaomin Wu

Sent from Outlook<http://taps.io/outlookmobile> Mobile

**Comment by nickmeldrum** [comment]
ahhh cool makes sense - thanks loads for jumping on this :)
