### ISSUE TITLE
npm not resolved consistent with node in .sh webjobs

### ISSUE THREAD

**Issue by agilbert201** [projectkudu/kudu#1935]
If you set node version through WEBSITE_NODE_DEFAULT_VERSION and have a .sh webjob the path for node is correct. However npm doesn't resolve properly.

Looks like the version specific node subdirs have a .txt file which presumably is being used to prepend proper npm version onto path. This is set properly, but the npm specific subdirs only have .cmd files in them, no npm shell files. So resolution falls through to the root npm file in nodejs dir.

**Comment by davidebbo** [comment]
I see, so issue is that folders like `D:\Program Files (x86)\npm\3.3.12` have `npm.cmd` but not `npm`. @suwat, maybe something to fix in how we build our npm packages?

**Comment by agilbert201** [comment]
Yes. I don't think I was trying to do anything too crazy, just want to sftp a file from 3rd party and load into azure storage. With PS you have no azure powershell, plus need to bring your own scp/sftp. With shell you get scp but alas would appear not a practical node env... I will go with vm or node or c# for now but seems like a bit too much work for something so simple...

**Comment by suwatch** [comment]
Since npm bash is in `D:\Program Files (x86)\npm\3.3.12\node_modules\npm\bin`, I thought it could be as easy as adding that to %path% (simple Kudu fix).  The issue is `npm` bash script assumes `npm-cli.js` to be in `.\node_modules\npm\bin\npm-cli.js` relative to the `npm` bash itself.  

```bash
NPM_CLI_JS="$basedir/node_modules/npm/bin/npm-cli.js"
```

Hence, when actually running it, it can't find `D:\Program Files (x86)\npm\3.3.12\node_modules\npm\bin\node_modules\npm\bin\npm-cli.js`!

Yes, we will have to improve the way we package npm as well as thinking about how to fix up already installed npms.

**Comment by suwatch** [comment]
One idea to fix this without changing the way we package npm is.

1. We enhance the `D:\Program Files (x86)\node\npm` to support env if exists.  See https://github.com/suwatch/npm_diff/commit/2e9abfe9e5a7a7a1fabd21f7ee4ab7c7aec17a12.  This is just one fix up on the default node/npm.   We can have Rapid update does this.
2. kudu, when starting up, can set 2 additional envs (in addition to putting it in the path).  For instance, ...
```
WEBSITE_NODE_BASH_PATH=/d/Program Files (x86)/nodejs/5.1.1/node.exe
WEBSITE_NPM_BASH_PATH=/d/Program Files (x86)/npm/3.3.12/node_modules/npm/bin/npm-cli.js
```

Given this is rare scenario (using bash npm), I think this fix is most optimal.  Repackage npm might be too big a hammer and would likely introduce more complication to OnPrem scenario.   

@davidebbo thought?

**Comment by agilbert201** [comment]
To me this seems fine. It at least provides a workable solution.

**Comment by jvano** [comment]
Hi

Kudu will continue to run in Azure App Service. However, this repo will no longer be maintained.
If the problem persists and is related to running on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
