### ISSUE TITLE
Setting permissions on the apps folder

### ISSUE THREAD

**Issue by jozefizso** [projectkudu/kudu#1939]
I have a single `kudu` Windows account that is member of the `Administrators` group. The user can change IIS configuration files and has full permissions on the `apps` folder.

Kudu fails to create new application with this setup, because the App Pool account for the new site cannot create subfolders in the `apps` folder. I must give the `IIS_IUSRS` Modify permission set to this folder to successfuly create new applications using Kudu. This makes all other App Pools able to modify files for all other sites.

What's the correct permission set for the `apps` folder where Kudu creates application folders to have a more secure environment where each application is isolated by App Pool permissions on it's sites folder.
Does Kudu manage these permissions somehow?

**Comment by paraspatidar** [comment]
There are no permissions to set, as everything is writable (one exception, you can't write files directly in d:\home, only subfolders).

**Comment by jvano** [comment]
Hi

Kudu will continue to run in Azure App Service. However, this repo will no longer be maintained.
If the problem persists and is related to running on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
