### ISSUE TITLE
Storage issues can lead to some WebJobs not running

### ISSUE THREAD

**Issue by davidebbo** [projectkudu/kudu#1940]
- When Kudu starts, it tries to find all the WebJobs
- If the drive is troubled at that time, Kudu can fail to enumerate the files for some WebJobs, in which case it ignores them
- Then even after the drive gets healthy, it ignores the WebJob till the next restart

We need to make Kudu more resilient to these conditions.

**Comment by suwatch** [comment]
https://github.com/projectkudu/kudu/commit/9ffc3cca815b19e6867bc02049cff4d37cc76e34
