### ISSUE TITLE
Git deployment consumes far more HD space than it should

### ISSUE THREAD

**Issue by mteper** [projectkudu/kudu#1941]
We have several web apps that are part of the same Visual Studio solution / GitHub repo. Each is deployed into a dedicated Azure web app using git integration by pointing to the appropriate .csproj file via a configuration setting. One of our apps performs very light duty and for it we use the free, F1 instance that has a 1GB storage quota, and we keep bumping up against it.

Specifically, it appears that Kudu performs a complete solution-wide GitHub package restore, which brings in lots of packages that are irrelevant to this app. Worse, the packages folder is never cleaned up, and over time accumulates multiple versions of packages, some quite large.

We end up facing the choice of either completely restructuring our solution to placate Kudu, or doing regular manual cleanup, or paying $400/yr for a higher storage quota tier. None of these options are particularly appealing.

Request: Kudu ought to be more intelligent about the packages it downloads, and it should also clean out packages that are no longer used in some meaningful fashion.

**Comment by davidebbo** [comment]
SImpler compromise is to do a `git clean -dxf` from the `d:\home\site\repository` folder using [Kudu Console](https://github.com/projectkudu/kudu/wiki/Kudu-console).

**Comment by jvano** [comment]
Hi

Kudu will continue to run in Azure App Service. However, this repo will no longer be maintained.
If the problem persists and is related to running on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
