### ISSUE TITLE
Continuous Deploy from Git Hub Failed with Syntax Error

### ISSUE THREAD

**Issue by danhadv** [projectkudu/kudu#1947]
Not sure when this started or if it has been happening for a while...  In the "Running Deployment Scipt" step of the deployment on a deployment slot I'm getting a "failed" message.  The activity log is below.  However, it appears the site is deploying correctly and updating the site?

```
`Command: "D:\home\site\deployments\tools\deploy.cmd"
Handling node.js deployment.
KuduSync.NET from: 'D:\home\site\repository' to: 'D:\home\site\wwwroot'
Copying file: 'css\styles.css.map'
Copying file: 'css\sass\base\_variables.scss'
undefined:1
﻿{
^
An error has occurred during web site deployment.

SyntaxError: Unexpected token ﻿
    at Object.parse (native)
    at Object.<anonymous> (C:\Program Files (x86)\SiteExtensions\Kudu\53.50324.2154\bin\scripts\selectNodeVersion.js:132:44)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:136:18)
    at node.js:963:3
undefined:1\r\n?{\r\n^\r\n\r\nSyntaxError: Unexpected token ?\r\n    at Object.parse (native)\r\n    at Object.<anonymous> (C:\Program Files (x86)\SiteExtensions\Kudu\53.50324.2154\bin\scripts\selectNodeVersion.js:132:44)\r\n    at Module._compile (module.js:435:26)\r\n    at Object.Module._extensions..js (module.js:442:10)\r\n    at Module.load (module.js:356:32)\r\n    at Function.Module._load (module.js:311:12)\r\n    at Function.Module.runMain (module.js:467:10)\r\n    at startup (node.js:136:18)\r\n    at node.js:963:3\r\nC:\Program Files (x86)\SiteExtensions\Kudu\53.50324.2154\bin\scripts\starter.cmd "D:\home\site\deployments\tools\deploy.cmd"
```

This is happening every time I commit.  The only difference in the error message is the "copying file" it is always the file that changed on the commit.

**Comment by shrimpy** [comment]
Error seems to come from  [this line](https://github.com/projectkudu/kudu/blob/master/Kudu.Core/Scripts/selectNodeVersion.js#L132), do you think it happen that you have a malformed.package.json file? Can you double check your package.json file?

**Comment by danhadv** [comment]
Entirely possible.  I will look into it and let you know.

**Comment by davidebbo** [comment]
This occurred twice on StackOverflow:

- http://stackoverflow.com/questions/25400621/azure-git-deployment-failing-selectnodeversion-js
- http://stackoverflow.com/questions/39930099/azure-webservice-deployment-error

We'll need a [repro](https://github.com/projectkudu/kudu/wiki/Using-a-git-repo-to-report-an-issue) to investigate.

**Comment by jvano** [comment]
Hi

Kudu will continue to run in Azure App Service. However, this repo will no longer be maintained.
If the problem persists and is related to running on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
