### ISSUE TITLE
The site's home directory could not be located

### ISSUE THREAD

**Issue by kbdavis07** [projectkudu/kudu#1950]
Hi,

Keep getting this error:

The site's home directory could not be located

On a Windows 10,  IIS 10 express, Using Visual Studio 2015 I do not get this error.

But, when I try the same solution on a

Windows 2012 Server R2 Data Center
IIS8

Visual Studio 2013 when I run it get the following Error:

The site's home directory could not be located

I have the folder IIS_IUSR, System and everything I can think of read/write permissions.

But no luck in getting it to work.

Kudu looks good and works locally, but can't get it to work on Windows Server 2012 R2 Data Center.

**Comment by neutrongenious** [comment]
experiencing same issue!

**Comment by jvano** [comment]
Hi

Kudu will continue to run in Azure App Service. However, this repo will no longer be maintained.
If the problem persists and is related to running on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
