### ISSUE TITLE
Function.json not json indented properly

### ISSUE THREAD

**Issue by suwatch** [projectkudu/kudu#1952]
See below - hard to read/edit.

![image](https://cloud.githubusercontent.com/assets/1088218/14095306/b985e14e-f513-11e5-916a-81d028c06ace.png)

**Comment by mathewc** [comment]
Related issue: https://github.com/projectkudu/AzureFunctionsPortal/issues/389

Let's fix this ASAP :)

**Comment by davidebbo** [comment]
Not a Kudu issue, so keeping portal issue active.
