### ISSUE TITLE
Failed deployment - now can't open kudu console

### ISSUE THREAD

**Issue by joshuapetryk** [projectkudu/kudu#1958]
We've been attempting to use the new continuous deployment features in azure web apps.

Steps taken:

- Created a web app with free service plan
- Connected "Deployment Source" to a VSTS project with a Git repo
- Deployment fails on the step "Running deployment command..."
- Activity log shows: "Restore failed There is not enough space on the disk."
- When browsing to Kudu console to attempt to clean up space - the web app throws an error: 

Server Error in '/' Application.
Parser Error

Description: An error occurred during the parsing of a resource required to service this request. Please review the following specific parse error details and modify your source file appropriately. 

Parser Error Message: There is not enough space on the disk.
Source Error: 
Line 1:  **@using System.IO**
Line 2:  @using System.Web.Hosting
Line 3:  @using Kudu.Services.Web

Is this because of the shared infrastructure with the "Free" tier of Azure hosting?

**Comment by davidebbo** [comment]
Most likely, the error message is correct, and you reached the 1GB limit. Note that this limit is shared among all free sites in the resource group.

With Kudu enable to run, you should still be able to use FTP to look at files and clean up as needed.

**Comment by joshuapetryk** [comment]
We just tested this on a brand new Web App - new app service plan - even new resource group. The first deployment fails with the disk space error message. I'm stumped as to why it thinks we already hit 1gb.

**Comment by davidebbo** [comment]
Did you look at the files in FTP, to see if maybe some huge files end up on there? Might be worth trying with a Basic or Standard site, which has way more space.

**Comment by joshuapetryk** [comment]
I did - the total was only 50mb of files.

We even tried deploying just the VS 2015 ASP.NET 5 template project. It didn't work on Free but worked on Basic. 1gb on free should be plenty for small projects.

> System.IO.IOException: There is not enough space on the disk.
> 
>    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
>    at System.IO.FileStream.WriteCore(Byte[] buffer, Int32 offset, Int32 count)
>    at System.IO.FileStream.Write(Byte[] array, Int32 offset, Int32 count)
>    at System.IO.Stream.InternalCopyTo(Stream destination, Int32 bufferSize)
>    at System.IO.Stream.CopyTo(Stream destination)
>    at Microsoft.Dnx.Tooling.Publish.PublishOperations.ExtractFiles(ZipArchive archive, String targetPath, Func`2 shouldInclude)
>    at Microsoft.Dnx.Tooling.Publish.PublishOperations.ExtractNupkg(ZipArchive archive, String targetPath)
>    at Microsoft.Dnx.Tooling.NuGetPackageUtils.ExtractPackage(String targetPath, FileStream stream)
>    at Microsoft.Dnx.Tooling.NuGetPackageUtils.<>c__DisplayClass0_0.<<InstallFromStream>b__0>d.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.Dnx.Runtime.Internal.ConcurrencyUtilities.<ExecuteWithFileLocked>d__2`1.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.Dnx.Tooling.NuGetPackageUtils.<InstallFromStream>d__0.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.Dnx.Tooling.RestoreCommand.<InstallPackageCore>d__77.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.Dnx.Tooling.RestoreCommand.<InstallPackages>d__76.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
>    at Microsoft.Dnx.Tooling.RestoreCommand.<RestoreForProject>d__69.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.Dnx.Tooling.RestoreCommand.<>c__DisplayClass68_0.<<Execute>b__2>d.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at system.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
>    at Microsoft.Dnx.Tooling.RestoreCommand.<Execute>d__68.MoveNext()
> ----------
> Restore failed
> There is not enough space on the disk.
> 
> 
> Feeds used:
>     https://api.nuget.org/v3-flatcontainer/
> An error has occurred during web site deployment.
> \r\nC:\Program Files (x86)\SiteExtensions\Kudu\53.50324.2154\bin\scripts\starter.cmd "D:\home\site\deployments\tools\deploy.cmd

**Comment by davidebbo** [comment]
Oh, didn't realize it was ASP.NET 5. See https://github.com/projectkudu/kudu/issues/1682

**Comment by joshuapetryk** [comment]
Ah apologies for the duplicate issue, glad that the product team is aware!

**Comment by davidebbo** [comment]
Yes, it's more of a DNX issue, but we're working with them to improve this. As you likely know, their model is going through very big changes with .NET Core.
