### ISSUE TITLE
GitLab Continuous Deployment specifying branch

### ISSUE THREAD

**Issue by tbertenshaw** [projectkudu/kudu#1960]
I've set up the continuous deployment with Gitlab as documented below. However I want to be able to specify the branch. If i edit the node using the https://resources.azure.com tool it wont let me save if i specify a branch i.e. "develop".

It seems the error is with the repoUrl,(if i try and save with no changes made i get the same error) which i didn't set and seems to be set when going through the process in the document below.

```
{
  "Code": "BadRequest",
  "Message": "The parameter https://mywebsite-ci.scm.azurewebsites.net has an invalid value.",
  "Target": null,
  "Details": [
    {
      "Message": "The parameter https://mywebsite-ci.scm.azurewebsites.net has an invalid value."
    },
    {
      "Code": "BadRequest"
    },
    {
      "ErrorEntity": {
        "Code": "BadRequest",
        "Message": "The parameter https://mywebsite-ci.scm.azurewebsites.net has an invalid value.",
        "ExtendedCode": "51008",
        "MessageTemplate": "The parameter {0} has an invalid value.",
        "Parameters": [
          "https://mywebsite-ci.scm.azurewebsites.net"
        ],
        "InnerErrors": null
      }
    }
  ],
  "Innererror": null
}
```

https://github.com/projectkudu/kudu/wiki/Continuous-deployment#setting-up-continuous-deployment-using-manual-steps

**Comment by davidebbo** [comment]
What specific node are you trying to Edit? GitLab doesn't have full first class support, but you should be able to change the `branch` App Setting in your Azure App.

**Comment by tbertenshaw** [comment]
I'm trying to edit the one in the document i linked to "sourcecontrols/web", which shows how to do it for GitLab

**Comment by davidebbo** [comment]
That'll only work with those that are first class supported. The 'Manual steps' section is what you want. Did you try the app setting?

**Comment by tbertenshaw** [comment]
yes i tried the manual steps and it works, i thought i would be able to add the branch via the resources tool as there are no notes for branch in the manual steps.however it doesn't let you save even without making changes, it must have values which have been set which don't validate with the api

**Comment by davidebbo** [comment]
Yes, seems something quirky is happening with that API. Note that if you really want to set the branch using Explorer, you can do it by adding the app setting under Yoursite/config/appsettings.

**Comment by tbertenshaw** [comment]
I did notice a similar error when i first tried to add a url style value in the repooUrl field, i.e. http://github.com/tbertenshaw/myrepo

Cool I'll try that, assume lowercase "branch" is correct?
Cheers

**Comment by davidebbo** [comment]
It's not case sensitive.

**Comment by tbertenshaw** [comment]
added a property "branch": "develop" to slots\CI\config\appsettings\properties then pushed a change to master, and it triggered the Continuous Deployment for this branch (listing that changset id in the activity screen in the portal). Suspect its not reading this property.

**Comment by tbertenshaw** [comment]
come to think about it this manual deployment relies on GitLab sending details to a webhook on the Azure side when a push occurs, Its probably something on their side which is needed. This page looks like there is a ref value which is set which looks like it would be setting the repo?

http://doc.gitlab.com/ce/web_hooks/web_hooks.html

**Comment by tbertenshaw** [comment]
I've raised an issue on GitLab as I presume this is a change which is needed on their side. https://gitlab.com/gitlab-org/gitlab-ee/issues/455

**Comment by tbertenshaw** [comment]
Don't seem to be getting any notice on the Gitlab side. I could potentially look at creating an intermediary service to parse the webhook post "tweak it" and resend it to kudu if i knew Kudo could handle pulling from a branch other than master. Is the ref property the one which supplies the branch?  https://github.com/projectkudu/kudu/blob/master/Kudu.Services/ServiceHookHandlers/GitlabHqHandler.cs

**Comment by davidebbo** [comment]
Copying what I just wrote on http://stackoverflow.com/questions/36915380/gitlab-continuous-deployment-to-azure-web-app/36916121:

> Note that Azure does not rely on the WebHook payload to know what branch to deploy. So if you push to a different branch, it'll still try pulling from the branch it's been configured to use, and end up doing nothing since it's up to date. This is true even if you use GitHub instead of GitLab.

I'm really not clear what issue you are having with this. Are you saying that it's ignoring the `branch` app setting, and ends up deploying bits from `master`?

**Comment by tbertenshaw** [comment]
yeah i have two slots UAT and CI
  UAT has no branch application setting.
  CI has a application setting called branch set to "develop"  (slot setting).

i've just edited the readme.md and checked in to the master branch. And via the portal the CI/Settings/Deployment Source/  i can see 

```
Update README.md
GitlabHQ
Active
2:34 PM
```
Click on this and

```
STATUS 
Success
TRIGGERED BY 
GitlabHQ
AUTHOR 
Tim Bertenshaw
RAN FOR 
313 seconds
REASON 
Update README.md
DEPLOY TO 
_MYWEBSITENAME_(CI)
STATUS
TIME
ACTIVITY
LOG
Thu 04/28
Updating submodules.
Thu 04/28
Preparing deployment for commit id '3510b02b96'.
Thu 04/28
Generating deployment script.
View Log
Thu 04/28
Running deployment command...
View Log
Thu 04/28
Running post deployment command(s)...
Thu 04/28
Deployment successful.

```
Seems it did push it?

**Comment by davidebbo** [comment]
Ok, I think I totally misled you. Can you try naming your app setting `deployment_branch` instead?

**Comment by davidebbo** [comment]
Actually, it's a bit more complex, because there are two potential places to set the branch. In addition to the app setting, using Kudu console, go under `D:\home\site\deployments` and look for a `settings.xml` file. It may contain something like this:

```xml
<?xml version="1.0" encoding="utf-8"?>
<settings>
    <deployment>
        <add key="branch" value="master" />
    </deployment>
</settings>
```

And I believe this setting takes precedence over the app setting. So you can either delete this branch key and rely on the app setting, or change it to `develop` in this file and not use the app setting.

**Comment by tbertenshaw** [comment]
Just tested the appsetting for deployment_branch and that works. Ill update my settings.xml as well to be sure. Cheers  👍 

Incidentally is there a way of flushing your deployments (clearing the deployments for a slot )and getting it to repull for an entire slot. Now i have the deplyoment sorted i need to test and resolve the post build tasks (npm, bower gulp tsc) etc. Anything which would be quicker than deleting and recreating the slot would be ideal :)

**Comment by davidebbo** [comment]
I think deleting the whole `D:\home\site\deployments` folder (from Kudu Console) should do it.

**Comment by NiltonMorais** [comment]
This issue saved me. I added the **deployment_branch** in App Settings and deleted **D:\home\site\deployments** folder

Thanks!
