### ISSUE TITLE
GET providers/Microsoft.Web/functions/<FUNCTION_NAME>?api-version=2015-08-01 Not Found

### ISSUE THREAD

**Issue by sedouard** [projectkudu/kudu#1961]
Looks like when you use the 'resource group' flavored functions API (noted at https://github.com/projectkudu/kudu/wiki/Functions-API) it doesn't find any functions, (even though they exist) .

However if you use the 'web apps' flavored functions API (also noted at https://github.com/projectkudu/kudu/wiki/Functions-API) such as:

GET providers/Microsoft.Web/sitename/functions/<FUNCTION_NAME>?api-version=2015-08-01 -> Returns <FUNCTION_NAME>.

This is with the current version of Kudu deployed with an 'Azure Functions' creation via portal.azure.com.

**Comment by davidebbo** [comment]
Yes, the resource group flavored one is only meant to be used if the Functions App was created using the RG flavored API in the first place. So if you created the app via portal, you would not see it.
