### ISSUE TITLE
Question: Deploy function with Function API Npm Install

### ISSUE THREAD

**Issue by sedouard** [projectkudu/kudu#1963]
Hey there!

Using the [functions api](https://github.com/projectkudu/kudu/wiki/Functions-API) if you include a `package.json` file, will it npm install? Is there a way to define custom deployment similarly how you would do with git?

**Comment by davidebbo** [comment]
The function API itself doesn't do that. But it is indeed possible to do git deployment with functions using a custom deployment script that we restore npm packages. @christopheranderson or @mattchenderson, do you have a sample script somewhere?

**Comment by sedouard** [comment]
Okay no worries. I think I can get away without that. Thanks!

**Comment by sedouard** [comment]
Hey @davidebbo quick question -- what is the size limit on the `put /subscriptions/{sub}/resourceGroups/{rg}/providers/Microsoft.Web/sites/{functionapp}/functions/MyFunction?api-version=2015-08-01` request body?

**Comment by davidebbo** [comment]
@sedouard not sure exactly. I think is whatever limit is enforced by ARM in general. It should be big enough for any reasonable size function. Note that it's not for binary files.
