### ISSUE TITLE
Configure Bitbucket account

### ISSUE THREAD

**Issue by rodrigomocca** [projectkudu/kudu#1966]
Hi,
I want to configure my bitbucket account to use continuous integrations with mi staging branch.
How I do this?

**Comment by davidebbo** [comment]
Please see https://azure.microsoft.com/en-us/documentation/articles/web-sites-publish-source-control/.

**Comment by rodrigomocca** [comment]
But I dont want to use azure. I have my own IIS.

**Comment by davidebbo** [comment]
Then the steps are much more manual. e.g. see https://github.com/projectkudu/kudu/wiki/Continuous-deployment#setting-up-continuous-deployment-using-manual-steps

**Comment by rodrigomocca** [comment]
Thanks!
