### ISSUE TITLE
Failed to set up deployment source for Web App

### ISSUE THREAD

**Issue by quasilatent** [projectkudu/kudu#1968]
I started experiencing it only today, before that I was able to successfully setup the deployment and deploy from this VSTS account and this particular repository as well as from different repos in account. 

VSTS is [backed by AAD](https://github.com/projectkudu/kudu/wiki/Setting-up-a-VSTS-account-so-it-can-deploy-to-a-Web-App). 

It is about 8 hour since it started for me, in the mean time I was able to deploy using vs2015 web publish.

Here is the error description:

```
Failed to set up deployment source for web app XXX, using Visual Studio Team Services. Repository 'UpdateSiteSourceControl' operation failed with System.InvalidOperationException: Vso GetRepository: Cannot find repository https://tripcenter.visualstudio.com/DefaultCollection/_git/YYY 
at Microsoft.Web.Hosting.SourceControls.VsoProxy.<GetRepository>d__3f.MoveNext() 
--- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) 
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
 at Microsoft.Web.Hosting.Administration.VsoSiteRepositoryProvider.<UpdateSiteSourceControl>d__6.MoveNext().
```

**Comment by davidebbo** [comment]
This is a VSTS issue that is being investigated now. Please monitor [this thread](https://social.msdn.microsoft.com/Forums/azure/en-US/6a703772-aa2a-45cc-911f-09eedeb2b94e/failed-deployment-for-web-app-using-vsts?forum=windowsazurewebsitespreview) for status.
