### ISSUE TITLE
CreateTriggerdJobArm doesn't create new jobs, just updates settings for existing ones

### ISSUE THREAD

**Issue by sedouard** [projectkudu/kudu#1971]
[CreateTriggerdJobArm](https://github.com/projectkudu/kudu/blob/c3e58b6b958295538d1a4ed9e2f06cfcab8b91a5/Kudu.Services/Jobs/JobsController.cs#L236) doesn't work as implied. It doesn't create any kind of job, it only modifies existing ones.

Is there a way to create a job with ARM credentials? The portal does this using some POST request with the body as the script file contents:

```
POST https://web1.appsvcux.ext.azure.com/websites/api/Websites/AddWebJob?SubscriptionId=04f7ec88-8e28-41ed-8537-5e17766001f5&SiteId%5BName%5D=sedouard-sailstest&SiteId%5BResourceGroup%5D=sedouard-sailstest&Region=West+US&JobType=triggered&JobName=testjob&JobFileName=deploy2.ps1&JobIsSingleton=false?api-version=2015-08-01

Body: [[file_contents]]
```

**Comment by davidebbo** [comment]
Generally, ARM is a control plane API, so it doesn't support things like uploading a zip file. The Kudu API does have methods to do this, but they're not exposed over ARM. The other way to do it is by simply deploying files in the right location, not much different from deploying a Web App.

**Comment by sedouard** [comment]
If a client app wants to manipulate functions and webjobs it'll require that you have both the subscription credentials as well as the site-specific deployment credentials. I was hoping there was a way not to require both. Seems like that's not an option.

**Comment by davidebbo** [comment]
Actually, it turns out that the ARM credentials can be used with the Kudu API, though it is rarely used. Right @suwatch?

**Comment by suwatch** [comment]
Yes.

One can use ARM token to authenticate/authorize against KUDU site (passed as Bearer - like typical ARM call).  We briefly document it [here](https://github.com/projectkudu/ARMClient/wiki) - see Kudu (SCM) Apis.  Portal will be (if not already) utilizing this path.

**Comment by sedouard** [comment]
nice! was not aware of that.
