### ISSUE TITLE
Ability to deeplink into the debug console

### ISSUE THREAD

**Issue by btardif** [projectkudu/kudu#1975]
https://<sitename>.scm.azurewebsites.net/DebugConsole/<path> should land you into the right folder.
- This would prevent you form having to navigate back to the same path if you have to refresh the page.
- You can share the URL with other folks that have access to reference or take action.
- UI can use this feature to link to specific folders this is very useful for diagnostics logs feature as an alternative to using FTP to get to logs.

@davidebbo

**Comment by jvano** [comment]
Hi

Kudu will continue to run in Azure App Service. However, this repo will no longer be maintained.
If the problem persists and is related to running on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
