### ISSUE TITLE
provide API to validate cron expressions for scheduled WJ

### ISSUE THREAD

**Issue by btardif** [projectkudu/kudu#1979]

**Comment by davidebbo** [comment]
This would better fit as a function portal controller thing (https://github.com/projectkudu/AzureFunctionsPortal). No need to involve Kudu.

**Comment by davidebbo** [comment]
Let's think about best place to have this code.

**Comment by jvano** [comment]
Hi

Kudu will continue to run in Azure App Service. However, this repo will no longer be maintained.
If the problem persists and is related to running on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
