### ISSUE TITLE
Azure Deployment Fails With Powershell Deployment Script

### ISSUE THREAD

**Issue by deevus** [projectkudu/kudu#1981]
```
Command: powershell -file deploy.ps1
File D:\home\site\repository\deploy.ps1 cannot be loaded because running 
scripts is disabled on this system. For more information, see 
about_Execution_Policies at http://go.microsoft.com/fwlink/?LinkID=135170.
    + CategoryInfo          : SecurityError: (:) [], ParentContainsErrorRecord 
   Exception
    + FullyQualifiedErrorId : UnauthorizedAccess
```

I've configured the `.deployment` file as described in https://github.com/projectkudu/kudu/wiki/Customizing-deployments

**Comment by deevus** [comment]
To be precise, the build actually "succeeds" as far as the Azure portal is concerned.

**Comment by davidebbo** [comment]
Try something like this in your `.deployment` file (which is what kuduscript generates for PowerShell):

    command = powershell -NoProfile -NoLogo -ExecutionPolicy Unrestricted -Command "& "$pwd\deploy.ps1" 2>&1 | echo"

**Comment by deevus** [comment]
I'll give that a go

**Comment by deevus** [comment]
That worked. Thank you. Do you want to leave this open until either the wiki is updated or the "bug" is fixed?

**Comment by davidebbo** [comment]
I updated the wiki. I know there was a reason to have such a crazy syntax! :)

**Comment by snobu** [comment]
I added in some notes for the crazy PowerShell syntax, makes it less crazy, still a bit mad. 3 dollar signs away from "I can't believe it's not Perl!".
https://github.com/projectkudu/kudu/wiki/Customizing-deployments

**Comment by davidebbo** [comment]
Thanks @snobu! I was reading through the syntax earlier and really didn't have a clue what it was doing :)
