### ISSUE TITLE
Code analysis ruleset warning

### ISSUE THREAD

**Issue by Korijn** [projectkudu/kudu#1983]
We're seeing the following compiler warning, how should we resolve? A quick search on the debug console revealed that only `NativeRecommendedRules.ruleset` is available on the Azure machine. Why?

`D:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.CSharp.CurrentVersion.targets(133,9): warning MSB3884: Could not find rule set file "AllRules.ruleset". [D:\home\site\repository\<solution>\<project>.csproj]`

**Comment by davidebbo** [comment]
We'll need to figure out why we're missing some files under `C:\Program Files (x86)\Microsoft Visual Studio 14.0\Team Tools\Static Analysis Tools\Rule Sets`

**Comment by ahmelsayed** [comment]
`NativeRecommendedRules.ruleset` is there because of the fix for #1076. Not sure if there a stand alone installer for the analysis tools.

**Comment by ahmelsayed** [comment]
@Korijn I just wanna confirm that this is just a warning and is not actually blocking you.

**Comment by Korijn** [comment]
It's just a warning, but I'm no compiler expert. I was unsure how it might affect my builds; if there is no negative impact on my application then we can close this. Thanks for your help.

**Comment by eagle779** [comment]
Hi David, we are getting the same warning.  A lot of them, because there are lots of projects in the build, so it makes the log output somewhat harder to interpret.  Whats the best way of suppressing / eliminating these warnings?  we tried copying the actual ruleset files to a folder on the server and referring to it in the project file but didn't seem to work.

**Comment by jvano** [comment]
Hi

Kudu will continue to run in Azure App Service. However, this repo will no longer be maintained.
If the problem persists and is related to running on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
