### ISSUE TITLE
host.json may have invalid json

### ISSUE THREAD

**Issue by develohpanda** [projectkudu/kudu#1984]
It is possible that the host.json file contain invalid json - there is currently no error handling for this and an unhandled exception is thrown when parsing.

**Comment by mathewc** [comment]
Is this issue intended for the azure-webjobs-sdk-script repo? I see your PR https://github.com/Azure/azure-webjobs-sdk-script/pull/348 for this.

**Comment by develohpanda** [comment]
Nope this issue is still relevant here, malformed host.json still not handled. in the closed PR, @davidebbo mentioned behavior needs improvement.

**Comment by davidebbo** [comment]
Fixed per #1985
