### ISSUE TITLE
500 error when pushing to service

### ISSUE THREAD

**Issue by ericsmallw** [projectkudu/kudu#1989]
After pushing creating an app in Kudu, the sites are configured in IIS, but when I attempt to deploy a get project to the generated Git URL I get a 500 error.
![500 err](https://cloud.githubusercontent.com/assets/5509306/15055576/e553ff22-12d2-11e6-8a4d-6a515073e1c3.png)

When navigating to the git URL I get a message: "No route registered for '/test.git'"

I followed the instructions from the tutorial in the doc [Developing Kudu locally and on Azure](http://blog.davidebbo.com/2012/06/developing-kudu-locally-and-on-azure.html). Have I possible missed a step?

**Comment by davidebbo** [comment]
> When navigating to the git URL I get a message: "No route registered for '/test.git'"

That part is actually normal.

For the 500, look for any interesting log files in `LogFiles\kudu\trace` under the app root.

**Comment by ericsmallwood** [comment]
I just checked the logs after another push and this was the error it generated:

"Failed to make directory &apos;C:/Users/esmallwood/Documents&apos;: Cannot create a file when that file already exists.

**Comment by davidebbo** [comment]
It could be some app pool identity issue. Can you check in inetmgr what the app pool is running under?

**Comment by ericsmallwood** [comment]
It's currently running under the ApplicationPoolIdentity.

**Comment by ericsmallwood** [comment]
That was it I just changed it to LocalSystem and everything worked fine!

Thanks for the help!

**Comment by davidebbo** [comment]
Yes, that's the default. Not sure what the deal is. It's a permission issue at some level. The error doesn't have a stack? You may need to debug it to see where it's trying to create this.

**Comment by davidebbo** [comment]
Good, but note that normally it does work with ApplicationPoolIdentity. Those things can be hard to track...

**Comment by ericsmallwood** [comment]
Ok, I'll keep that in mind and see if I can figure out why it was failing with the AppPoolId.

**Comment by ericsmallwood** [comment]
It seems that when I am pushing now, the files get to the apps repository folder, but not to the wwwroot  folder. The error in the log is as follows:

"The system cannot find the path specified. C:\Users\esmallwood\Documents\kudu\Kudu.Services.Web\bin\scripts\starter.cmd "C:\Users\esmallwood\Documents\kudu\Kudu.Services.Web\bin\node_modules\.bin\kuduscript.cmd" -y --no-dot-deployment -r "C:\Users\esmallwood\Documents\kudu\apps\test3\site\repository" -o "C:\Users\esmallwood\Documents\kudu\apps\test3\site\deployments\tools" --basic --sitePath "C:\Users\esmallwood\Documents\kudu\apps\test3\site\repository""

All of the files listed exist except the bin\node_modules folder, do I need to install node as a package in Services.Web?

**Comment by davidebbo** [comment]
@ericsmallwood that is not related to the App Pool issue. You normally should have `starter.cmd` in that folder after a full build.

**Comment by pflannery** [comment]
I just got this problem too using the latest master. 
For me it's trying to run "D:\dev\github\projectkudu\kudu\Kudu.Services.Web\bin\node_modules\.bin\kuduscript.cmd" which fails because the `kuduscript.cmd` doesn't exist.

running `npm install kuduscript` under "D:\dev\github\projectkudu\kudu\Kudu.Services.Web\bin" fixed this error for me

**Comment by pflannery** [comment]
After fixing that I've hit `'nuget' is not recognized as an internal or external command` which seems odd because I can run the `deploy.cmd` directly and it succeeds at pulling all the nuget packages.

```
2017-11-19T16:41:40.7669794Z,Running deployment command...,563d4a5d-7b10-493e-8756-906efda6f479,0
	2017-11-19T16:41:40.7769682Z,Command: "D:\dev\github\projectkudu\kudu\apps\website1\site\deployments\tools\deploy.cmd",,0
	2017-11-19T16:41:41.0429663Z,Handling .NET Web Application deployment.,,0
	2017-11-19T16:41:41.0499688Z,'nuget' is not recognized as an internal or external command&comma;,,1
```

Then another issue arises with msbuild where it needs to be set to `MSBUILD_PATH=%programfiles(x86)%\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe`  because it was pointing to an older version

**Comment by davidebbo** [comment]
@pflannery so this is something you get when running Kudu locally and not on Azure, right? Sounds like some kind of PATH issue. NuGet shoudl be in Kudu.Services.Web\bin\Scripts, and that should be on the path.

**Comment by pflannery** [comment]
@davidebbo Yes I'm running Kudo locally. 

Once I did a *Release* build of the Kudu.Services.Web it outputted not only NuGet.exe but also KuduSync.NET.exe (which was another issue I ran in to at some point trying to hack fix the nuget path issue)

I've now managed to get Kudo running locally with error.

**Comment by davidebbo** [comment]
@pflannery great. The build may have some quirks that cause it to miss some targets if run in a certain way.

**Comment by jvano** [comment]
Hi

Kudu will continue to run in Azure App Service. However, this repo will no longer be maintained.
If the problem persists and is related to running on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
