### ISSUE TITLE
Wrong branch checked out

### ISSUE THREAD

**Issue by sebastienros** [projectkudu/kudu#1990]
Using the https://OrchardCMS/Orchard repository on the branch 1.10.1 doesn't work. It actually clones the 1.10.x branch. From the Kudu console if we try to checkout 1.10.1 we get an `ambiguous branch` error message.

/cc @ahmelsayed who reproed it with me

**Comment by davidebbo** [comment]
Correcting repo link: https://github.com/OrchardCMS/Orchard

**Comment by sebastienros** [comment]
I found the issue. we also had a tag called `1.10.1` and this is what is ambiguous for git.

**Comment by davidebbo** [comment]
Cool, closing then!
