### ISSUE TITLE
[Portal] Only shows 30 branches

### ISSUE THREAD

**Issue by sebastienros** [projectkudu/kudu#1991]
And I have more than that, and the name I wanted starts with `u`. Work around: create another branch with a name starting with `a` ;)

**Comment by davidebbo** [comment]
@sebastienros Note that this logic is not part of Kudu.

@Tuesdaysgreen does Portal have a 30 branch limit?

**Comment by Tuesdaysgreen** [comment]
@sebastienros - Which type of provider type (eg GitHub, BitBucket, etc...) are you using?  We don't have any limits that I'm aware of but if I know the type, I can try to repro.

**Comment by sebastienros** [comment]
https://github.com/OrchardCMS/Orchard

**Comment by davidebbo** [comment]
Looks like about 40 branches.

**Comment by Tuesdaysgreen** [comment]
It looks like we're hitting the page limit for GitHub.  I'll add a work item to add paging support.

**Comment by davidebbo** [comment]
Thanks Elliott. Closing here since it's not in Kudu.

**Comment by snobu** [comment]
If I remember right manage.windowsazure.com's continuous deployment UI asks for the branch name as user input. That might be a good workaround until we light up paging support.

**Comment by Tuesdaysgreen** [comment]
Okay I checked in a fix.  It'll be live early next week.
