### ISSUE TITLE
Modify description of "adding-ip-restrictions" in Wiki

### ISSUE THREAD

**Issue by akuryan** [projectkudu/kudu#1994]
Hi
IMHO, it is worth noting here https://github.com/projectkudu/kudu/wiki/Xdt-transform-samples#adding-ip-restrictions that this IP restriction will be applied to the **whole IIS of web app**, including SCM site.
If only web app requires IP restriction - location tag shall be added, same as here https://github.com/projectkudu/kudu/wiki/Xdt-transform-samples#registering-an-iis-managed-httpmodule

**Comment by davidebbo** [comment]
Fixed, thanks.
