### ISSUE TITLE
When can't acquire lock file, we should trace the lock info

### ISSUE THREAD

**Issue by suwatch** [projectkudu/kudu#1995]
This helps with investigation.   When we can't acquire lock file, we should trace out the lock info (containing who owned it and when acquired etc).

**Comment by suwatch** [comment]
I started looking into this.  Currently when the lock is taken, we will write the [stack trace](https://github.com/projectkudu/kudu/blob/d9e84e4d3c7673c0018a9529d1afd29c6ecde18a/Kudu.Core/Infrastructure/LockFile.cs#L123) of the owning thread to the lock file.  The intention is, to investigate when lock could not be acquired, one could look into this file and figure out what stack has the lock and when it was taken.  

There are rooms for improvement.

1) When the lock can't be acquired, we should trace the lock owner info to the kudu trace file directly.  This would help with diagnostic the issue (no need to understand where the lock file is and know that one has to read it to get such info).

2) We should return more info to caller why lock can't be taken (not just vague conflict operation, try later).  Ideally, it would be `The operation conflicts with pending Delete Repository operation started on 05/12/16 22:34 UTC.  Please try again later`.   To achieve this, I propose we enhance [IOperationLock.Lock](https://github.com/projectkudu/kudu/blob/d9e84e4d3c7673c0018a9529d1afd29c6ecde18a/Kudu.Contracts/Infrastructure/IOperationLock.cs#L8) and [IOperationLock.LockAsync](https://github.com/projectkudu/kudu/blob/d9e84e4d3c7673c0018a9529d1afd29c6ecde18a/Kudu.Contracts/Infrastructure/IOperationLock.cs#L11) to take addition info.   For instance, `_lock.Lock("Delete Reporitoy")` to indicate that lock is taken for this specific operation.  This info will be written to lock file once acquired.  Any subsequent conflicting operations can then return a meaningful error to user.

Thought?

**Comment by davidebbo** [comment]
Sounds like good improvements if you think it's worth the investment. Have you run into several cases where having that would have helped?
