### ISSUE TITLE
Scrap the cron-based settings for scheduling jobs.

### ISSUE THREAD

**Issue by 649** [projectkudu/kudu#1997]
Scrap the cron-based settings for scheduling jobs.

The cron-format is everything but intuitive and lacks several vital features like the possibility to schedule a  a job ever 25h so it does not run at the same time every day.

Instead a simple format that makes it easy and intuitive to do simple and frequent scheduling should implemented.

Perhaps inspired by: http://schemastore.org/schemas/json/webjob-publish-settings.json",

**Comment by davidebbo** [comment]
cron is not perfect and has a learning curve, but it is a widely adopted format and generally works well enough for most scenarios. So at this time, it is not likely that we will add an alternative way of defining the schedule.
