### ISSUE TITLE
Can get error trying to save diagnostics\settings.json

### ISSUE THREAD

**Issue by davidebbo** [projectkudu/kudu#1999]
This came up [here](https://github.com/Azure/azure-webjobs-sdk-script/issues/343), as well as in another case (internal report).

Here ie the stack:

```
[IOException: The process cannot access the file &#39;D:\home\site\diagnostics\settings.json&#39; because it is being used by another process.]
   System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath) +216
   System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost) +1326
   System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share) +65
   System.IO.Abstractions.FileWrapper.Open(String path, FileMode mode, FileAccess access, FileShare share) +36
   Kudu.Core.Infrastructure.FileSystemHelpers.WriteAllTextToFile(String path, String content) +68
   Kudu.Core.Settings.DiagnosticsSettingsManager.SaveSettings(DiagnosticsSettings diagnosticsSettings) +75
   Kudu.Core.Settings.DiagnosticsSettingsManager.UpdateSetting(String key, Object value) +44
   Kudu.Services.Performance.LogStreamManager.&lt;BeginProcessRequest&gt;b__21_1() +92
   Kudu.Contracts.Infrastructure.LockExtensions.TryLockOperation(IOperationLock lockObj, Action operation, TimeSpan timeout) +218
   Kudu.Contracts.Infrastructure.LockExtensions.LockOperation(IOperationLock lockObj, Action operation, TimeSpan timeout) +26
   Kudu.Services.Performance.LogStreamManager.BeginProcessRequest(HttpContext context, AsyncCallback cb, Object extraData) +347
   Kudu.Services.Performance.LogStreamHandler.BeginProcessRequest(HttpContext context, AsyncCallback cb, Object extraData) +127
   System.Web.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +103
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean&amp; completedSynchronously) +155
```

**Comment by davidebbo** [comment]
@suwatch, could it be that we try to save this file way too much? Does [this code](https://github.com/projectkudu/kudu/blob/1fd2a04404700e65cb7d12934a54dce501466bb5/Kudu.Services/Diagnostics/LogStreamManager.cs#L92-L99) imply that we'll save it on every request? Note that we seems to have no code path that sets `_enableTrace` to false.

**Comment by hanvyj** [comment]
I'm having this prevent me from running any of my functions at all. No idea why, it was working a week ago. Now with some new code... nope.

**Comment by suwatch** [comment]
Please provide site name here on [indirectly](https://github.com/projectkudu/kudu/wiki/Reporting-your-site-name-without-posting-it-publicly) and the time in UTC of the issue.

**Comment by hanvyj** [comment]
I think I solved the problem.

It occured when I was getting two separate functions have issues with a connection string. Neither could connect to the service bus connection string used by their Triggers.

Caused some confusion, I was deleting functions to try work out where the issue was - if I happened to delete _either_ of the functions (so only one had the error) it worked. This let me know what the error was, and when I fixed the connection string and re-deployed the full set of functions everything was fine again!

**Comment by jvano** [comment]
Hi

Kudu will continue to run in Azure App Service. However, this repo will no longer be maintained.
If the problem persists and is related to running on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
