### ISSUE TITLE
OneDrive deployment:The given path's format is not supported.

### ISSUE THREAD

**Issue by snobu** [projectkudu/kudu#2001]
When setting up OneDrive deployment in Ibiza, deployment is successful however a bunch of XML traces are written to `LogFiles\kudu\trace`.

###### D:\home\LogFiles\kudu\trace\2016-05-12T10-23-43_ea40a8_070_UnexpectedException.xml

```
<exception>
System.NotSupportedException: The given path's format is not supported.
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.IO.Abstractions.FileWrapper.Open(String path, FileMode mode, FileAccess access, FileShare share)
   at Kudu.Core.Infrastructure.FileSystemHelpers.AppendAllTextToFile(String path, String content)
   at Kudu.Core.Tracing.XmlTracer.WriteStartElement(String title, IDictionary`2 attribs)
</exception>
```

Any idea where in the code this is thrown?

**Comment by shrimpy** [comment]
Have a feeling onedrive might send us encoded file path cause invalid file path issue.

You can start with https://github.com/projectkudu/kudu/blob/c3e58b6b958295538d1a4ed9e2f06cfcab8b91a5/Kudu.Services/FetchHelpers/OneDriveHelper.cs

**Comment by snobu** [comment]
@shrimpy, one quick question:

https://github.com/projectkudu/kudu/blame/c3e58b6b958295538d1a4ed9e2f06cfcab8b91a5/Kudu.Services/FetchHelpers/OneDriveHelper.cs#L181

```
  "RepositoryUrl": "https://api.onedrive.com/v1.0/drive/special/approot:/kududev"
```

My `kududev` folder sits in my OneDrive under `Apps\Azure Web Apps\`
This `/special` OneDrive API ..there has to be something special going on with it. Is the magical path `Apps\Azure Web Apps` something well-known shared between the "Azure Web Sites" OneDrive app and OneDrive API and the path we ask for in the JSON payload is always relative to that one?

**Comment by shrimpy** [comment]
"Azure Web Apps" folder is come from the OAUTH application Azure register with OneDrive. It use your app name as folder name. All path from JSON payload are under this folder, and we only ask for permission to access this folder.

**Comment by snobu** [comment]
Turns out the exception was thrown [here](https://github.com/projectkudu/kudu/blob/c3e58b6b958295538d1a4ed9e2f06cfcab8b91a5/Kudu.Services/FetchHelpers/OneDriveHelper.cs#L65):

```
using (_tracer.Step("Getting delta changes with cursor: {0} ...", cursor))
```

it was trying to write this filename to disk:

``` 
d:\home\LogFiles\kudu\trace\2016-06-08T10-42-34_KUDUDE_006_Getting-delta-changes-with-cursor:-aTE09NjM2MDA5MDE2ODM5NjM7SUQ9NjlGRTJCQzNFODYxOEMwRSEzMzMzNzk7TFI9NjM2MDA5MDE4MTMxNjM7RVA9NTtTST00ODtTTz0yO1BJPTM_pending.xml
```

Which contains a colon after "__cursor:__" (invalid char in NTFS).

Fix in https://github.com/projectkudu/kudu/pull/2040

**Comment by shrimpy** [comment]
Fix is now in master https://github.com/projectkudu/kudu/commit/51c50b3d901e0e92eca847b22ef4190dedd18c3c
