### ISSUE TITLE
Not able to view all the folders (scroll down further below) in my azure debug console

### ISSUE THREAD

**Issue by roysoham** [projectkudu/kudu#2006]
Hello Team,

I am unable to scroll down to a particular folder in the Debug console of my cloud ***.azurewebsites. I am talking about the file structure above the cmd/powershell window.
Due to which I am unable to view/select/edit all the files and folders.
Is this a known issue.
Also, I tried installing mongo-express, but after deployment it shows a lot of errors.

Thanks & Regards,
Roy

**Comment by davidebbo** [comment]
Not sure I follow. How does the ability to scroll down in Kudu Console relate to the ability to install mongo-express?

Can you please rephrase the issue to focus on only one thing? And please include screen shot that shows the scrolling issue you are referring to.

**Comment by roysoham** [comment]
Sure.
http://i.prntscr.com/74ec332714364affba824ddd050dbaf1.png
In the above screenshot I am able to view till "lodash-padstart" only (you can check the scroll bar at the right), it does not let me view/scroll below that.
I even tried doing cd & entered the folder i wanted to reach, but the above file structure does not change & remains as it is

**Comment by davidebbo** [comment]
I think it's because the UI only display the first 100 files, to avoid perf issues with giant listings. To work around, do a `dir` for the console to see the full list, and `cd` into it.

**Comment by roysoham** [comment]
I did dir & cd'ed into the directory. problem is I cant edit the file (tried edit, edlin, etc) I am familiar with vim/linux. I am using mac have tried rdc (without success), currently using atom+git+azure cli through terminal to push the changes, and through the kudu cmd interface doing npm start, to understand any issues. It will be great help if you can give the right development toolset/direction here

**Comment by shrimpy** [comment]
You can work around it. Try to use cp comand to copy the file to a less file folder or a new folder and edit from there.  Once done just copy and replace the old file.

**Comment by davidebbo** [comment]
Or try using Visual Studio Online "Monaco", which has a much more powerful editor. You can enable it in Azure portal in the Tools menu for your Web App.

**Comment by snobu** [comment]
Or if you'd rather take an all command line approach, see if KuduExec fits your workflow: https://github.com/projectkudu/KuduExec

You won't be able to use `vim` in that terminal session though.
