### ISSUE TITLE
To return 400 when reject RBAC for certain Http GET

### ISSUE THREAD

**Issue by suwatch** [projectkudu/kudu#2009]
Due to certain contract with Azure, we should not return [403 (Forbidden)](https://github.com/projectkudu/kudu/blob/0bfe30f857fb61a67a31ef17e57a15bac4443845/Kudu.Services.Web/Tracing/TraceModule.cs#L66). We need to settle on either 400 (BadRequest) or 401 (Unauthorized).

**Comment by suwatch** [comment]
@davidebbo this is low hanging - 400 vs 401?   My preference is 401.

**Comment by davidebbo** [comment]
400.5. But round up if you need to :)

**Comment by suwatch** [comment]
Ah, funny.   I will go with 401 here as well as in Azure.
