### ISSUE TITLE
ASP.NET Core Web deploy script should include configuration option

### ISSUE THREAD

**Issue by hoetz** [projectkudu/kudu#2013]
When I deploy my RC2 Web App, the deploy script does this:

`call :ExecuteCmd dotnet publish "D:\home\site\repository\src\Web" --output "%DEPLOYMENT_TEMP%"`

It would be great if we could get an option to specify 
-c, --configuration [Debug|Release]

Without the configuration option, it will default to debug.

**Comment by davidebbo** [comment]
At the very least, we should default to retail. But we need to make this configurable. For msbuild, we have `SCM_BUILD_ARGS` where you can pass extra switches. Might need `SCM_DOTNETPUBLISH_ARGS`. @ahmelsayed?

Though note that we're tweaking the script, and if you have a `.sln` file, we will call msbuild instead, and pass `--no-build` to `dotnet publish`. This should go live in a day or two.

**Comment by davidebbo** [comment]
You can now use `SCM_BUILD_ARGS`, and the default is release.

**Comment by davidebbo** [comment]
It's deployed, so you can try it now.

**Comment by hoetz** [comment]
From what I see the parameter does only apply to msbuild. dotnet publish now defaults to --configuration Release which is nice.

`IF DEFINED USE_MSBUILD (
  call :ExecuteCmd "%MSBUILD_PATH%" "%DEPLOYMENT_SOURCE%\undefined" /nologo /verbosity:m /t:Build /p:AutoParameterizationWebConfigConnectionStrings=false;Configuration=Release;UseSharedCompilation=false %SCM_BUILD_ARGS%
  IF !ERRORLEVEL! NEQ 0 goto error
  call :ExecuteCmd dotnet publish "D:\home\site\repository\src\Web" --output "%DEPLOYMENT_TEMP%" --configuration Release --no-build
  IF !ERRORLEVEL! NEQ 0 goto error
) ELSE (
  call :ExecuteCmd dotnet publish "D:\home\site\repository\src\Web" --output "%DEPLOYMENT_TEMP%" --configuration Release
  IF !ERRORLEVEL! NEQ 0 goto error
)`
