### ISSUE TITLE
Code on server not being updated after deploy

### ISSUE THREAD

**Issue by 0xdeafcafe** [projectkudu/kudu#2015]
I tweeted @davidebbo about this, and he said to post it here. For some reason on my azure website development slot, when i push new code, it runs the deployment, but it's for an older version of the code than the one in the commit. I can't publicly post the code/repo, but I can share the details in a private medium.

For example, my global.json looks like this:
``` json
{
	"projects": [ "src", "test" ]
}
```

However, in the deployment output, it says this:
```
D:\home\site\repository\..\helpers-dotnet\src\***\***.xproj.metaproj : warning MSB4046: Error reading project file "..\helpers-dotnet\src\***\***.xproj": Could not find a part of the path 'D:\home\site\helpers-dotnet\src\***\***..xproj'.
```

Which was a project reference that used to be in the global.json, that i removed several commits back. Also another weird side effect is that even though the deployment runs, and is valid, it gives me this error on every page of the web app
```
You do not have permission to view this directory or page.
```

**Comment by davidebbo** [comment]
Can you share your web app name, either directly or [indirectly](https://github.com/projectkudu/kudu/wiki/Reporting-your-site-name-without-posting-it-publicly)? This will help us investigate. Thanks!

**Comment by 0xdeafcafe** [comment]
Yeah, the web app name is `helm-service-email(staging)`

**Comment by davidebbo** [comment]
It looks like a problem with your solution file. It's at the root of the repo, and has:

    Project("{8BB2217D-0F2D-49D1-97BC-3654ED321F3B}") = "Helm.Helpers", "..\helpers-dotnet\src\Helm.Helpers\Helm.Helpers.xproj", "{1E2DE855-19F5-4FDA-B605-90BCD52416E8}"

You can't `..` out of the root folder :)

**Comment by 0xdeafcafe** [comment]
That's interesting, I didn't even notice that was still in the solution file, thought it would have been removed when the global.json file was updated, although I primarily use VSCode now, so that'll have been what was playing up.

Although, even though this is unrelated to kudu I presume, do you know of any fix for the following issue I mentioned?
```
You do not have permission to view this directory or page.
```

**Comment by davidebbo** [comment]
I don't think your deployment was successful, as you have no web.config in site\wwwroot. Have you tried deploying after fixing the .sln issue?

**Comment by davidebbo** [comment]
Also, I notice you're using a custom deployment script. What did you modify vs the default script?

**Comment by 0xdeafcafe** [comment]
Yeah, just pushed a new commit after i stripped the helper data out of the sln. Seems the deployment must still be failing, as there is still no web.config.

The only thing i modified is i changed the nuget line from
```
call :ExecuteCmd nuget.exe restore -packagesavemode nuspec
```
to
```
call :ExecuteCmd dotnet restore %NUGET_RESTORE_OPTIONS%
```

So I could specify a custom source as we use myget for private packages.

**Comment by davidebbo** [comment]
How did you generate the script? What seems odd is that it has `SET USE_MSBUILD=FALSE`, while I would expect it to be true here.

**Comment by 0xdeafcafe** [comment]
Oh, sorry, I just set that in a previous commit to try something, that was set to TRUE by default.

**Comment by davidebbo** [comment]
So you mean issue still happens with TRUE? @ahmelsayed can you help investigate this one?

**Comment by 0xdeafcafe** [comment]
Yeah. Happens with either setting.

**Comment by davidebbo** [comment]
Your repo doesn't have a `web.config` in `src\Helm.Service.Email`. It instead has one under `src\Helm.Service.Email\wwwroot`, which seems wrong (wwwroot is only for static files). How exactly did you create this repo? Please see https://github.com/davidebbo-test/AspNetCoreRC2VS for what an RC2 repo normally looks like (at least when created by VS).

**Comment by 0xdeafcafe** [comment]
I created this repo with VS with the old rc1 dnx tooling. I just moved the web.config to the root on the project, rather than in the wwwroot folder, and the same error is still being thrown.

**Comment by davidebbo** [comment]
Did you check (e.g. using Kudu Console) whether you end up with a web.config in your `d:\home\site\wwwroot` after publishing?

**Comment by 0xdeafcafe** [comment]
It isn't. I went into the command line and created the web.config in that directory manually, and now the error says
```
The specified CGI application encountered an error and the server terminated the process.
```

**Comment by davidebbo** [comment]
I think there is something that's broken in your solution and that is not related to Kudu. e.g. your project.json doesn't have a publishOptions section at all (see mine [here](https://github.com/davidebbo-test/AspNetCoreRC2VS/blob/2982dc5a9cdb5c595d89d5867e526c20561bcff3/src/AspNetCoreRC2/project.json#L92-L99)), and is probably missing many other things.

I'm far from a Asp.Net Core expert, so I would suggest reaching out to them directly. You may want to start with http://www.hanselman.com/blog/NETCore10RC2UpgradingFromPreviousVersions.aspx which has several pointers for converting from RC1 to RC2.

**Comment by 0xdeafcafe** [comment]
Will try and and have another read though the migration docs. Thank's again for all the help, especially on a weekend.

**Comment by davidebbo** [comment]
I just created a new wiki page to help isolate issues locally before pushing to Kudu: https://github.com/projectkudu/kudu/wiki/Test-your-ASP.NET-Core-repo-locally. Please give it a shot and see how far you get.

Closing here for now, but we can re-open if something looks like a Kudu issue.
