### ISSUE TITLE
Git Deploy with ASP.NET Core RC2

### ISSUE THREAD

**Issue by ealsur** [projectkudu/kudu#2016]
I have a locally working ASPNET Core RC2 web app with public repo at https://github.com/ealsur/mvpstream.

It was an RC1 app that I'm migrating to RC2 but there's some problem on the autogenerated deployment script when I push to Github.

`Using cached version of deployment script (command: 'azure -y --no-dot-deployment -r "D:\home\site\repository" -o "D:\home\site\deployments\tools" --aspNet5 "D:\home\site\repository\project.json" --aspNet5Version "1.0.0-preview1-002702" --aspNet5Runtime "CLR" --aspNet5Architecture "x86"').`

This is the deployment script generation.

And then, this shows on the deployment:

    Command: "D:\home\site\deployments\tools\deploy.cmd"
    Handling ASP.NET 5 Web Application deployment.
    There are no runtimes matching the name dnx-clr-win-x86 on feed 
    https://www.nuget.org/api/v2.
    At C:\Program Files 
    (x86)\SiteExtensions\Kudu\54.50516.2223\bin\scripts\dnvm.ps1:619 char:9
    +         throw "There are no runtimes matching the name $RuntimeId on feed 
    $feed. ...
    +         
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        + CategoryInfo          : OperationStopped: (There are no ru...get.org/api 
       /v2.:String) [], RuntimeException
        + FullyQualifiedErrorId : There are no runtimes matching the name dnx-clr- 
       win-x86 on feed https://www.nuget.org/api/v2.
     
    Failed exitCode=1, command=PowerShell -NoProfile -NoLogo -ExecutionPolicy unrestricted -Command "[System.Threading.Thread]::CurrentThread.CurrentCulture = ''; [System.Threading.Thread]::CurrentThread.CurrentUICulture = '';$CmdPathFile='"D:\local\UserProfile\.dnx\temp-set-envvars.cmd"';& 'C:\Program Files (x86)\SiteExtensions\Kudu\54.50516.2223\bin\scripts\dnvm.ps1' " install 1.0.0-preview1-002702 -arch x86 -r CLR
    An error has occurred during web site deployment.
    There are no runtimes matching the name dnx-clr-win-x86 on feed \r\nhttps://www.nuget.org/api/v2.\r\nAt C:\Program Files \r\n(x86)\SiteExtensions\Kudu\54.50516.2223\bin\scripts\dnvm.ps1:619 char:9\r\n+         throw "There are no runtimes matching the name $RuntimeId on feed \r\n$feed. ...\r\n+         \r\n~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\r\n    + CategoryInfo          : OperationStopped: (There are no ru...get.org/api \r\n   /v2.:String) [], RuntimeException\r\n    + FullyQualifiedErrorId : There are no runtimes matching the name dnx-clr- \r\n   win-x86 on feed https://www.nuget.org/api/v2.\r\nC:\Program Files (x86)\SiteExtensions\Kudu\54.50516.2223\bin\scripts\starter.cmd "D:\home\site\deployments\tools\deploy.cmd"


My global.json clearly has: 

    {
    	"sdk": {
    		"version": "1.0.0-preview1-002702"}
    }

And the App is using `net461` because current Azure SDKs are not compatible with netstandard.

**Comment by davidebbo** [comment]
Is that only happening when you push to an existing site that previously was running on RC1, or even on a new site?

**Comment by davidebbo** [comment]
Oh, one thing I noticed is that your site is not yet using the latest Kudu. Can you try simply restarting the site? This will make it move up to the latest, which has all the RC2 support.

**Comment by ealsur** [comment]
Your second suggestion worked like a charm @davidebbo ! You remain "Savior of us who try new things right after they come out"! 🍻 
You can close this issue if you want, unless you need it.

**Comment by ealsur** [comment]
PD: Even though restarting made the deploy work, the process would stop by itself. Since I had Deployment Slots, I deleted the staging slot and recreated it and then the Deployment worked and the site too :)

**Comment by davidebbo** [comment]
Awesome!
