### ISSUE TITLE
Deploying a specific ASP.NET project file : project.json or .xproj also supported ?

### ISSUE THREAD

**Issue by StefH** [projectkudu/kudu#2018]
On this page https://github.com/projectkudu/kudu/wiki/Customizing-deployments some information is added about **.cspro**j web-applications.

Are **dotnet rc2 projects** also supported?

**Comment by davidebbo** [comment]
Yes, they are.

**Comment by zygimantas** [comment]
It is related to xproj - I have a webjobs.list.json in web application folder:

{
  "$schema": "http://schemastore.org/schemas/json/webjobs-list.json",
  "WebJobs": [
    {
      "filePath": "../WebJob1/WebJob1.xproj"
    }
  ]
}

and as I understand, webjob should be deployed together with the app. Does it work with kudu?

**Comment by zygimantas** [comment]
Or is Properties/webjob-publish-settings.json is the file which indicated that this project will be deployed as a webjob?

**Comment by StefH** [comment]
@davidebbo ; if possible update the documentation

**Comment by davidebbo** [comment]
@StefH Yes, I just added a new section: https://github.com/projectkudu/kudu/wiki/Customizing-deployments#deploying-a-specific-aspnet-core-project

@zygimantas I think you are replying on the wrong issue here :)
