### ISSUE TITLE
.NET Core RC2 deployment documentation

### ISSUE THREAD

**Issue by zygimantas** [projectkudu/kudu#2019]
Could you please provide more complete documentation for this scenario? I believe there will be a lot of questions regarding such deployments in next few months.

To help others and myself, here is what I already know:

Solution structure:
Project 1: Website (netcoreapp1.0, portable)
Project 2: WebJob (netcoreapp.1.0, portable)

Because WebJob project will be compiled to a DLL (portable application), to get a webjob running on Azure, `Run.cmd` file must be created with content: `dotnet WebJob.dll`
Visual Studio adds BOM character, so if you will upload your webjob to Azure, you will get misleading "dotnet command not found" error. You should open Run.cmd file with Visual Studio again and choose `File > Advanced Save Options`, and select `Unicode (UTF-8 without signature)` in the first dropdown.

To include `Run.cmd` in publish output, `project.json` must include these lines:

```
"publishOptions": {
  "include": [
    "Run.cmd"
  ]
}
```

Otherwise Run.cmd will not be included and you will not be able to launch webjob.
At this point webjob, published using `dotnet publish` can be compressed to zip archive and uploaded to Azure.

Next step, how to enable automatic deployment together with Website project. That's still a mystery to me. I have already tried adding `webjob-publish-settings.json` and `webjob-list.json` files, but they change nothing. Maybe it is not yet possible with RC2/portable apps?

It would be very nice to see a better explanation in wiki how webjob can be deployed together with website.

**Comment by davidebbo** [comment]
Generally, Kudu uses standard msbuild.exe/dotnet.exe logic to build and deploy the project, so at that level, it has no knowledge of WebJobs. The way this works for .NET 4.x project is that VS injects all kind of magic in the solution/project to make it deploy the WebJobs in the right place.

So the question is not really about Kudu, but about when VS will add support for this scenario. @danroth27 / @sayedihashimi, do you guys know if the tooling team is working on WebJobs support for Core like we have for 4.x?

**Comment by zygimantas** [comment]
I have noticed 2 files being injected (in non-Core solution):

1. WebJob/Properties/webjob-publish-settings.json

```
{
  "$schema": "http://schemastore.org/schemas/json/webjob-publish-settings.json",
  "endTime": null,
  "interval": null,
  "jobRecurrenceFrequency": null,
  "runMode": "Continuous",
  "startTime": null,
  "webJobName": "WebJob"
}
```

2. Website/webjobs-list.json

```
{
  "$schema": "http://schemastore.org/schemas/json/webjobs-list.json",
  "WebJobs": [
    {
      "filePath": "../WebJob/WebJob.csproj"
    }
  ]
}
```

I expected that by creating these files manually (and by changing csproj to xproj), we can get the same results, unfortunatelly, something is missing here. As I see in deployment log, the WebJob project is compiled, but not deployed (without any errors).

**Comment by davidebbo** [comment]
I think most of the magic in non-Core projects comes from [this line](https://github.com/davidebbo-test/WebAppWithWebJobsVS/blob/5471db17dc3ba9ccfc632dde3feecdf69c5cf853/WebAppWithWebJobsVS/WebAppWithWebJobsVS.csproj#L273) in the project file:

    <Import Project="..\packages\Microsoft.Web.WebJobs.Publish.1.0.7\tools\webjobs.targets" Condition="Exists('..\packages\Microsoft.Web.WebJobs.Publish.1.0.7\tools\webjobs.targets')" />

And I'm guessing that this target file is very non-Core specific.

**Comment by StefH** [comment]
@zygimantas : I'm also trying to deploy a **dotnet rc2 web-application** to Azure (https://github.com/projectkudu/kudu/issues/2018) but I miss some knowledge.

Do you maybe have a working example project somewhere available (e.g. github) ?

**Comment by zygimantas** [comment]
@StefH this link may help you: https://aspnetcore.slack.com/files/guardrex/F1A2C1UDN/IIS_Hotline__Links__Info___Tips
Also, enable logging on azure and check logs - usually it contains valuable information

**Comment by davidebbo** [comment]
@StefH see https://github.com/davidebbo-test/AspNetCoreRC2VS for an example of a Core RC2 app that deploys successfully using Kudu.

**Comment by StefH** [comment]
@davidebbo ; You don't need a `.deployment` file to get it published correctly to Azure ?

**Comment by davidebbo** [comment]
No, you only need one if you are going to override the standard deployment script.

**Comment by MaximRouiller** [comment]
@zygimantas @StefH 

Here's how I managed to deploy a .NET Core WebJob to Azure with an ASP.NET Core WebAPI.

https://blog.decayingcode.com/post/creating-.net-core-console-webjobs-on-an-asp.net-core-azure-webapp/

The trick is the `app_data` folder as well as the `postpublish` in the `project.json`.

Feel free to ask questions here or in the comments of the post.

**Comment by jdosullivan** [comment]
MaximRouiller, thanks for writing that post. It's the only post I've found that even remotely hints at how to set up a webjob for asp.net core without resorting to trickery with deployment etc. 
However, I tried to follow along but I just couldn't. There were too many pieces missing. I am trying to piece it together to see if I can get something working but if you'd at least point out where the sources are that you are referring to that would make it easier.

For instance, just a few words in we end at a section called "What we should have right now". Where are we getting these pieces from? 

Also the postpublish section; I already have a deployment to iis in that section, should this come after or before it. 

Thanks for writing it up anyway, it's at least a hint in the right direction.

**Comment by MaximRouiller** [comment]
@jdosullivan Here's a project where everything is up and running: https://github.com/NovawebSolutions/Invoicing/tree/master/src

### What we should have right now

* ASP.NET Core application with a folder `app_data/jobs/Triggered/MyWebJob` which contains a `run.cmd` and a `settings.job` that will contain your schedule. 

This will tell Kudu what to run and how.

* `project.json` publishOptions

This will tell `dotnet` what to include when you publish.

* `project.json` postPublish script

This is where the magic happens. It will compile/publish any console application into your `app_data` folder when you publish your ASP.NET Core application.

> Also the postpublish section; I already have a deployment to iis in that section, should this come after or before it.

I don't think it matters that much on Azure because your published output is going to be x-copied. I would go "before" but simply by preference.

**Comment by jdosullivan** [comment]
Awesome. Thank you. I got it working.

**Comment by MaximRouiller** [comment]
@jdosullivan Congrats man! Let me know if there's other way I can help!

**Comment by jvano** [comment]
Hi

Kudu will continue to run in Azure App Service. However, this repo will no longer be maintained.
If the problem persists and is related to running on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
