### ISSUE TITLE
RC1 Dependencies fail to deploy to Azure

### ISSUE THREAD

**Issue by Dillie-O** [projectkudu/kudu#2025]
I'm deploying my RC1 project from Bitbucket to Azure through Continuous Integration. The project was built off of DNX 4.5.1 RC1 libraries and I had a successful deployment back in March.

A recent code change failed to deploy and I haven't been able to track down why quite yet. When I look into the log (attached) it appears that after all my prepublish actions complete, I get an error about some RC2 library references failing to load. The odd thing is that the libraries in question aren't even specified in my project.json file.

```
 Unable to resolve dependency Microsoft.Extensions.Caching.Abstractions 1.0.0-rc2-final
  Unable to resolve dependency Microsoft.Extensions.DependencyInjection.Abstractions 1.0.0-rc2-final
  Unable to resolve dependency Microsoft.Extensions.Options 1.0.0-rc2-final
  Unable to resolve dependency Microsoft.Extensions.Caching.Abstractions 1.0.0-rc2-final
  Unable to resolve dependency Microsoft.Extensions.DependencyInjection.Abstractions 1.0.0-rc2-final
  Unable to resolve dependency Microsoft.Extensions.Options 1.0.0-rc2-final
```

I found a recent [StackOverflow post](http://stackoverflow.com/questions/37381377/azure-asp-net-rc1-deployment-failure) regarding the issue and noted that I'm already using a custom deploy script so I can run my EF migration commands. The only difference I see between the recommended script and mine is that I'm using x86 instead of x64, there is my custom EF code, and that the recommended script no longer checks for POST_DEPLOY commands to execute.

Would any of those factors be an issue? I was going to update my app service to use x64 and make those small tweaks to the script, but it was recommended I open a case anyway. I'm attaching my deploy log and my custom deploy script if it helps.
[deploy_cmd.txt](https://github.com/projectkudu/kudu/files/287249/deploy_cmd.txt)
[deploy_test_fail.txt](https://github.com/projectkudu/kudu/files/287250/deploy_test_fail.txt)

**Comment by davidebbo** [comment]
I wonder if there is some dnu/NuGet issue not directly related to Kudu here. Looking at your output, it looks like the restore is getting some RC2 packages, e.g.

    GET https://api.nuget.org/v3-flatcontainer/microsoft.extensions.caching.memory/1.0.0-rc2-final/microsoft.extensions.caching.memory.1.0.0-rc2-final.nupkg

To isolate, I'd suggest manually running that very same `dnu restore` command on your local machine, and see if you also end up with some RC2 packages.

**Comment by Dillie-O** [comment]
I will do that and let you know. For what it is worth, these are the packages in my project.json file:

```
"EntityFramework.Commands": "7.0.0-rc1-final",
    "EntityFramework.Core": "7.0.0-rc1-final",
    "EntityFramework.MicrosoftSqlServer": "7.0.0-rc1-final",
    "Microsoft.AspNet.Authentication.Cookies": "1.0.0-rc1-final",
    "Microsoft.AspNet.Authentication.OpenIdConnect": "1.0.0-rc1-final",
    "Microsoft.AspNet.Diagnostics": "1.0.0-rc1-final",
    "Microsoft.AspNet.IISPlatformHandler": "1.0.0-rc1-final",
    "Microsoft.AspNet.Mvc": "6.0.0-rc1-final",
    "Microsoft.AspNet.Mvc.TagHelpers": "6.0.0-rc1-final",
    "Microsoft.AspNet.Server.Kestrel": "1.0.0-rc1-final",
    "Microsoft.AspNet.StaticFiles": "1.0.0-rc1-final",
    "Microsoft.AspNet.Tooling.Razor": "1.0.0-rc1-final",
    "Microsoft.AspNet.Http": "1.0.0-rc1-final",
    "Microsoft.Extensions.Configuration.FileProviderExtensions": "1.0.0-rc1-final",
    "Microsoft.Extensions.Configuration.Json": "1.0.0-rc1-final",
    "Microsoft.Extensions.Configuration.UserSecrets": "1.0.0-rc1-final",
    "Microsoft.Extensions.Logging": "1.0.0-rc1-final",
    "Microsoft.Extensions.Logging.Console": "1.0.0-rc1-final",
    "Microsoft.Extensions.Logging.Debug": "1.0.0-rc1-final",
    "Microsoft.Framework.ConfigurationModel": "1.0.0-beta2",
    "Microsoft.VisualStudio.Web.BrowserLink.Loader": "14.0.0-rc1-final",
    "WindowsAzure.Storage": "6.2.2-preview",
    "Microsoft.AspNet.Session": "1.0.0-*",
    "Microsoft.Extensions.Caching.Memory": "1.0.0-*",
    "OpenXmlPowerTools": "4.1.3",
    "DocumentFormat.OpenXml": "2.5.0",
    "WindowsAzure.MediaServices": "3.5.2",
    "WindowsAzure.MediaServices.Extensions": "3.3.0",
    "Microsoft.Azure.Search": "1.0.1-preview",
    "NReco.VideoConverter": "1.0.8",
    "Microsoft.Owin": "2.0.2",
    "Microsoft.Owin.Security": "2.0.2",
    "Microsoft.Owin.Security.Cookies": "2.0.2",
    "Microsoft.ApplicationInsights.AspNet": "1.0.0-beta8"
```

I wonder if maybe the OpenXML or VideoConverter libraries would be the culprit, but I don't know how they would be looking specifically for the rc2 libraries as dependencies

**Comment by davidebbo** [comment]
Closing for now. We can reactivate if something points at a Kudu specific issue.

**Comment by Dillie-O** [comment]
Just as followup to this in case it gets stumbled upon, the issue at hand was with my 1.0.0-* dependencies. Since they were "open" on the version, they were attempting to grab rc2 dependencies which were incompatible. Once I changed these to a fixed RC1, things resolved themselves. I was unable to update to RC2 because some of my other libraries were incompatible.
