### ISSUE TITLE
Add ability to see Instances in Kudu

### ISSUE THREAD

**Issue by AussieInSeattle** [projectkudu/kudu#2030]
Would be great if you could see the current instances running for a web app so dont have to code:
http://blog.amitapple.com/post/2014/03/access-specific-instance/

For bonus points would be great if you could click a link next o an instance and it sets your affinityid cookie automatically for the website so you are hitting that instance - due to the scm url being slightly different to the web url and cookie domain rules I'm not sure if this is possible though.

**Comment by davidebbo** [comment]
Kudu is intrinsically running on one instance at a time and knows nothing about the others. But if you use the Portal, the Process Explorer covers all instances.

I use this [Chrome extension](https://chrome.google.com/webstore/detail/editthiscookie/fngmhnnpilhplaeedifhccceomclgfbg?hl=en) to see cookies.

**Comment by AussieInSeattle** [comment]
Can you provide guidance on "Process Explorer"?
I'm in the new portal under the Web App and I dont see "Process Explorer" anywhere under Settings for the Web App.

**Comment by snobu** [comment]
It's under Tools, not Setiings.
