### ISSUE TITLE
Azure WebApp Deployment Failure

### ISSUE THREAD

**Issue by robfarmergt** [projectkudu/kudu#2031]
I have a webapp that has been deployed successfully before (currently still on .NET Core beta8) but deployments today are failing with the output:

`Lock file Microsoft.DotNet.ProjectModel.Graph.LockFile contains msbuild projects but there is no export file
Published 0/1 projects successfully`

I can provide the entire output if needed.

Has there been a change in the Azure/Kudu config that might cause this to fail? The last successful deployment was Monday 5/16.

**Comment by davidebbo** [comment]
Please see http://stackoverflow.com/questions/37381377/azure-asp-net-rc1-deployment-failure/37381832#37381832 for workaround.

**Comment by robfarmergt** [comment]
@davidebbo the deployment "succeeded" but the site is returning a 503. I've tried stopping and starting the Web App and get the same result.

**Comment by davidebbo** [comment]
Can you share your web app name, either directly or [indirectly](https://github.com/projectkudu/kudu/wiki/Reporting-your-site-name-without-posting-it-publicly)? This will help us investigate. Thanks!

**Comment by robfarmergt** [comment]
It's 'prorata-qa'. Thanks!

**Comment by davidebbo** [comment]
I turned on logging in your web.config, and got this error in `d:\home\logfiles`:

```
System.InvalidOperationException: No service for type 'Microsoft.Dnx.Runtime.IApplicationEnvironment' has been registered.
   at Microsoft.Framework.DependencyInjection.ServiceProviderExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Framework.DependencyInjection.ServiceProviderExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.AspNet.Hosting.Program.Main(String[] args)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Dnx.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly, String[] args, IServiceProvider serviceProvider)
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
```

https://github.com/aspnet/Home/issues/1198 might offer clues. Maybe related to being on beta8, which is even older than rc1. The deploy.cmd I shared was for rc1. Maybe try [adjusting it](https://github.com/davidebbo-test/AspNet5RC1/blob/0e42059b5a9938ea9605542b88199f740baec55c/deploy.cmd#L84)?

**Comment by robfarmergt** [comment]
I changed the line to
`set DNX_RUNTIME="%USERPROFILE%\.dnx\runtimes\dnx-CLR-win-x64.1.0.0-beta8"`
and redeployed and got the following output:
`Command: deploy.cmd`
`Handling ASP.NET 5 Web Application deployment.`
`'dnx-clr-win-x64.1.0.0-rc1-update1' is already installed in D:\local\UserProfile\.dnx\runtimes\dnx-clr-win-x64.1.0.0-rc1-update1.`
`Adding D:\local\UserProfile\.dnx\runtimes\dnx-clr-win-x64.1.0.0-rc1-update1\bin to process PATH`
`The system cannot find the path specified.`
`An error has occurred during web site deployment.`
`The system cannot find the path specified.\r\nC:\Program Files (x86)\SiteExtensions\Kudu\55.50526.2249\bin\Scripts\starter.cmd deploy.cmd`

**Comment by davidebbo** [comment]
There is another line that refers to rc1 in the script. Probably needs to be changes as well.

**Comment by davidebbo** [comment]
Also, might be healthy to hit Restart in portal to get rid of various temp files and start clean after the various experiments.

**Comment by robfarmergt** [comment]
Ok, that worked! Thanks so much for your help again @davidebbo! Now to prioritize migration to RC2!

**Comment by davidebbo** [comment]
Awesome! I added a line clarifying that in the SO answer.
