### ISSUE TITLE
WebJob stopping and won't restart after scale down

### ISSUE THREAD

**Issue by christhecoder** [projectkudu/kudu#2033]
This is a bit of a strange one - not sure if it will be easily reproducible.  My continuous webjob was running until this happened:

```
[06/02/2016 16:18:05 > 47a949: SYS INFO] WebJob is stopping due to website shutting down
[06/02/2016 16:18:06 > 47a949: SYS INFO] Status changed to Stopping
[06/02/2016 16:18:06 > 47a949: INFO] Job host stopped
[06/02/2016 16:18:06 > 47a949: SYS INFO] Status changed to Success
[06/02/2016 16:18:06 > 47a949: SYS INFO] Status changed to Stopped
```

This coincided with my server auto scaling down an instance.  I have a settings.job file in my project to force the webjob to run on a single instance:

```
{
    "is_singleton": true
}
```

So I assume the webjob was running on the instance that was shut down.  However, it did not start automatically on another instance, and nothing I did would make it start again.  Instead, its status remained at Initializing.  I couldn't stop it or start it.  I tried stopping and starting the website to no avail.  Eventually I decided to walk away from it for a bit, and a few hours later there were a bunch of HTTP errors on my server (possibly unrelated, this frustratingly seems to happen regularly) - I got the 'Http Server Errors GreaterThan 10 (Count) in the last 5 minutes' has been resolved for xxx' email.  At which point my webjobs started again:

`[06/02/2016 19:32:17 > 61d75b: INFO] Job host started`

It's a continuous webjob written in C#, that was published to the app service.

So this is the issue I experienced, and would like to confirm whether anyone else has experienced this issue of scaling down the number of instances of their app, and having their continuous jobs stop and not able to start them again?

**Comment by davidebbo** [comment]
Is there anything interesting (like errors) in the log files under `D:\home\data\jobs\continuous\YourWebJob`?

**Comment by christhecoder** [comment]
I have the following files:

job_log.txt (which has the messages from my original post)
Two status_ files (not sure why there would be two of them)
WebJobsSdk.marker

singleton.job.lock does have an error - here are the contents:

{
  "OperationName": "Acquiring continuous WebJob singleton lock",
  "AcquiredDateTime": "2016-06-02T21:27:52.9539855Z",
  "StackTrace": "   at System.Environment.GetStackTrace(Exception e, Boolean needFileInfo)\r\n   at System.Environment.get_StackTrace()\r\n   at Kudu.Core.Infrastructure.LockFile.WriteLockInfo(String operationName, Stream lockStream)\r\n   at Kudu.Core.Infrastructure.LockFile.Lock(String operationName)\r\n   at Kudu.Core.Jobs.ContinuousJobRunner.TryGetLockIfSingleton()\r\n   at Kudu.Core.Jobs.ContinuousJobRunner.<>c__DisplayClass19_0.<StartJob>b__0()\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)\r\n   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)\r\n   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n   at System.Threading.ThreadHelper.ThreadStart()"
}

The error timestamp indicates that this occurred a couple of hours after my webjob started again.  Any thoughts on whether this may have contributed to the issue?

**Comment by davidebbo** [comment]
That's actually not an error, but is just a marker that tells us the stack at the time the lock was acquired.

Not sure what's going on, and will need to investigate in more depth later.

BTW, please use code blocks to make things more readable. :)

**Comment by christhecoder** [comment]
OK, thanks David.  When I saw the stack trace, I just assumed it was an error :).

I've updated the posts to use code blocks :).

**Comment by davidebbo** [comment]
This is the normal stack where the lock is acquired, in `StartJob` ([code](https://github.com/projectkudu/kudu/blob/44570100217a560563ce577cebc8be8fba470a96/Kudu.Core/Jobs/ContinuousJobRunner.cs#L86)).

What the logic is supposed to do is:

- each instance tries to get the lock for the singleton job every 5 seconds
- one instance has the lock
- if that instance dies, another is supposed to pick it up

Possible theories why it wouldn't happen:

1. `singleton.job.lock` is still locked by something for some reason
2. There is no other instance to pick it up

If you hit this again, check if you are able to delete the lock file.

**Comment by christhecoder** [comment]
OK, thanks for that David.  Good to know for the future, and hopefully if anyone else experiences the issue they can find this thread and report back as well.

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
