### ISSUE TITLE
Autoswap logic can cause a build to be killed halfway through

### ISSUE THREAD

**Issue by davidebbo** [projectkudu/kudu#2034]
Here is the scenario that causes this:

- Deployment request comes in and takes a while
- While it's processing a second deployment request comes in. Here, we just update the marker file to mark there there is more work to do
- The first deployment completes, and triggers a Swap
- But now, the background thread finds that there is more work to do ([here](https://github.com/projectkudu/kudu/blob/44570100217a560563ce577cebc8be8fba470a96/Kudu.Services/ServiceHookHandlers/FetchHandler.cs#L297-L298)), and loops back to start another deployment.
- While that happens, the swap takes effect and kills the second deployment

**Comment by davidebbo** [comment]
One fix here is to make sure that we don't do the swap until we're completely done with the `PerformDeployment` loop. i.e. as long as new /deploy keep coming, we won't swap.

The obvious drawback is the resulting potential starvation, but all in all it's a lesser evil.

**Comment by shrimpy** [comment]
PR is out https://github.com/projectkudu/kudu/pull/2038 for review
