### ISSUE TITLE
Simple bash deployment script hangs

### ISSUE THREAD

**Issue by davidebbo** [projectkudu/kudu#2041]
Issue comes from http://stackoverflow.com/questions/37739407/azure-web-site-kudu-publishing-failing-with-timeout/37740335.

This seems to have regressed with the new git 2.8.x. The repro is quite trivial. Here is a repo: https://github.com/KuduApps/KuduDeployBash

It just has two files. `.deployment` has:

```
[config]
command = deploy.sh
```

And deploy.sh has:

```sh
#!/bin/bash
echo "Hello"
```

Which push to Kudu, it hangs trying to launch the script.

**Comment by davidebbo** [comment]
Here is the process stack.

![image](https://cloud.githubusercontent.com/assets/556238/15985892/0cf56896-2fb0-11e6-922d-e6bee2b33c44.png)

And the command line of the 3 top processes:

```
cmd.exe: D:\Windows\system32\cmd.exe /c ""C:\Program Files (x86)\SiteExtensions\Kudu\55.50610.2267\bin\Scripts\starter.cmd" deploy.sh"
git-bach.exe: "D:\Program Files (x86)\Git\git-bash.exe" --no-cd "D:\home\site\repository\deploy.sh"
mintty.exe: usr\bin\mintty.exe -o AppID=GitForWindows.Bash -o RelaunchCommand="D:\Program Files (x86)\Git\git-bash.exe" -o RelaunchDisplayName="Git Bash" -i /mingw32/share/git/git-for-windows.ico /usr/bin/bash --login -i "D:\home\site\repository\deploy.sh"
```

**Comment by davidebbo** [comment]
The simplest repro is to just run `deploy.sh` from Kudu console, which hangs in the same way.

This triggers the `.sh` extension handler. `HKEY_CLASSES_ROOT\sh_auto_file\shell\open\command` maps to `"D:\Program Files (x86)\Git\git-bash.exe" --no-cd "%L" %*`, which is why would end up launching git-bash.exe.

Note that running `bash deploy.sh` from the command line works fine.

**Comment by davidebbo** [comment]
I found that if I change the shell reg key to `"D:\Program Files (x86)\Git\bin\bash.exe" --no-cd "%L" %*`, the issue doesn't happen.

@dscho can you explain the difference between git-bash.exe and bash.exe? Why does one use mintty but not the other?

**Comment by dscho** [comment]
@davidebbo `git-bash.exe` is supposed to run a graphical terminal, set up the environment variables appropriately, and then call the real Bash. `bin/bash.exe` does the same, but without the graphical shell (it is a console program). So it looks like you found the correct solution.

**Comment by davidebbo** [comment]
Instead of hacking the registry, a simpler change is to run the script shell explicitly instead of relying on Windows shell.

e.g. in `.deployment` file, instead of:

```
[config]
command = deploy.sh
```

We should have:

```
[config]
command = bash deploy.sh
```

Users who already generated this file will need to change it, but we should change our KuduScript generator to do it.

**Comment by davidebbo** [comment]
It turns out that our generator [already does the right thing](https://github.com/projectkudu/KuduScript/blob/dafe578f13cd300c1d1269895d75cec6efd428e5/lib/generator._js#L458). So only users hitting this probably hand won't their `.deployment` file, and can easily change that.

So I don't think we need to fix anything here.
