### ISSUE TITLE
Web job start button on azure is disable and "Never run" on kubu dashboard

### ISSUE THREAD

**Issue by ardumez** [projectkudu/kudu#2042]
I have deploy one webjob from visual studio 2015 and upload one webjob from the GUI azure portal. Code with .NET Console application, with "On demand" web job type.

In all case, the start button azure is disable. Is normal ?
![image](https://cloud.githubusercontent.com/assets/9568904/15992850/f50b263a-30d6-11e6-93a7-f61586c1cb2a.png)

And, when I go on the trigger url like this : https://testaddialgo.scm.azurewebsites.net/api/triggeredwebjobs/test/run

I have the messgae like this:
"No route registered for '/api/triggeredwebjobs/test/run'"

And, when I go on kubu dashboard I have "Never run message"

![image](https://cloud.githubusercontent.com/assets/9568904/15992829/502ddcca-30d6-11e6-9a4d-f1c40de9fd17.png)

How I can run my webJob ?

**Comment by davidebbo** [comment]
The fact that you can't run it just by browsing to https://testaddialgo.scm.azurewebsites.net/api/triggeredwebjobs/test/run is normal, since it requires a POST request.

Does the issue persist if you refresh the portal?

**Comment by hunthexaview** [comment]
Hi 
I am running into the same exact issue, I have a webjob that I am trying to run on a weekday bases at a certain time so I created this: 


 when I try to run i get the error message "No route registered for '/api/triggeredwebjobs...

Anything I can do to correct this?

**Comment by davidebbo** [comment]
@hunthexaview Please see [this thread](https://social.msdn.microsoft.com/Forums/azure/en-US/e046ef98-ae3a-4942-819f-b62e1775b533/app-service-customers-trying-to-run-a-triggered-webjob-manually-may-see-failures-and-error-message?forum=windowsazurewebsitespreview)

**Comment by hunthexaview** [comment]
Would this work for a scheduled job?

**Comment by davidebbo** [comment]
Please reply directly to that thread. What you are seeing is not related to this issue (which is an old one from more than a year ago). Thanks!

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
