### ISSUE TITLE
Schedule cron: how to turn off/disable for a given deployment?

### ISSUE THREAD

**Issue by hubert-associates** [projectkudu/kudu#2043]
Hi. WebJobs are very nice ... and we now use the cron "schedule":"0 0 1 * * *" feature which leads us to a new challenge: with the "old" azure scheduler, I could remove schedules from deployment instances. e.g. I could deploy three instances around the world and say that I only want the triggered WebJob in USA-East to run and remove the schedule for the other two. How can I do this with the now cron-scheduler?

I can use https://myinstance1.scm.azurewebsites.net/api/triggeredjobs/ to see the schedule, but how can I delete it? 

The only method I see, asside from deploying a different configuration to my 3 instances, is to delete the files under D:\home\site\wwwroot\app_data\jobs\triggered\webjobname>  

There must be a better way?

**Comment by davidebbo** [comment]
If you set a `WEBJOBS_STOPPED=1` App Setting in the Azure portal, all WebJobs will stop. Note that this will also affect continuous WebJobs.

BTW, things that are questions rather than issue reports are better asked on places like StackOverflow.
