### ISSUE TITLE
Errors on private repositories

### ISSUE THREAD

**Issue by vincent** [projectkudu/kudu#2044]
Hi,

When cloning / pulling a private repository - from Bitbucket in my case - I get a error `Fatal: Exception encountered.` From the git-for-windows folks, it may be linked with the git credentials store helper [#779](https://github.com/git-for-windows/git/issues/779)

Reproductible steps on a fresh AWS, in the Kudu console:

```
PS D:\home> mkdir tmp
PS D:\home> cd tmp
PS D:\home\tmp> git clone https://user:pass@bitbucket.org/private/project
Cloning into 'project'...
Fatal: Exception encountered.
PS D:\home\tmp>
```

As there are some other issues about private repos, I'm not sure it is a duplicate or not.

**Comment by davidebbo** [comment]
@suwatch To fix this, we need to disable the credential store when installing git on the workers.

**Comment by suwatch** [comment]
The gitconfig is stored at `D:\Program Files (x86)\Git\mingw32\etc\gitconfig`.  There, you can see the credential section was configured to `helper = manager`.   I try remove that section and it seems to disable the credential store.

**Comment by vincent** [comment]
Thank you @suwatch

So is this something we can disable with a user .gitconfig ? `D:\Program Files (x86)\Git\mingw32\etc\gitconfig` is not writable by the default AWS/Kudu user, is it ?

**Comment by suwatch** [comment]
I did a quick try but unable to.  @davidebbo?

**Comment by davidebbo** [comment]
@vincent indeed, you cannot write there. It's something we would need to update.

I'm not sure whether it's possible in git to remove a global config setting in a user file.

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
