### ISSUE TITLE
64 bit nodejs

### ISSUE THREAD

**Issue by antono** [projectkudu/kudu#2047]
Hello.

I use kudu to deploy nodejs app which requires 64bit nodejs.

System Info shows:

> 64 bit system: True
> 64 bit process: True

However when i run node i getting ia32:

```
D:\home>node -e "console.log(require('os').arch())"
ia32
```

Is there any way to configure 64bit nodejs via kudu on azure?

**Comment by davidebbo** [comment]
Indeed, the bitness selected in the portal only affects the IIS w3wp process, and has no bearing on Node. Currently, we only have 32-bit Node binaries on the worker.

If you really need 64 bit, you should be able to copy those Node binaries into your app, and point to them using web.config or iisnode.yaml.

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
