### ISSUE TITLE
Arm powershell script not working in web job

### ISSUE THREAD

**Issue by avinashsachdewani** [projectkudu/kudu#2048]
I have a working azure arm powershell scripts to create a new virtual machine and it's working fine in cloud service but when I am trying to execute in azure webjob, I am getting following Error :

New-AzureRmResourceGroup -Name $resourceGroup -Location $location

New-AzureRmResourceGroup : The Win32 internal error "The handle is invalid" 0x6 occurred while setting character attributes for the console output buffer. Contact Microsoft Customer Support Services. At D:\local\Temp\jobs\triggered\webjob\v43suxvk.lln\testDrives\WindowsServer201 2\provision.ps1:17 char:1 + New-AzureRmResourceGroup -Name $resourceGroup -Location $location + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ + CategoryInfo : CloseError: (:) [New-AzureRmResourceGroup], Host Exception + FullyQualifiedErrorId : Microsoft.Azure.Commands.Resources.NewAzureResou rceGroupCommand

**Comment by davidebbo** [comment]
Probably more of a [sandbox](https://github.com/projectkudu/kudu/wiki/Azure-Web-App-sandbox) thing than Kudu specific. Do you get the same when trying to run the same command outside of a WebJob from Kudu's PowerShell console?

**Comment by davidebbo** [comment]
You can probably get around that issue by using:

    $WarningPreference = "SilentlyContinue"

But I think you'll then hit a secondary issue for which we don't yet have a fix.

**Comment by avinashsachdewani** [comment]
yes david I am getting the same error while trying outside of a webjob.

**Comment by davidebbo** [comment]
Same error even with `SilentlyContinue`? That is not expected.

**Comment by avinashsachdewani** [comment]
Thanks David I am able to create resource groups after setting warning Preference.
But one point I want to mention here that if in any cmdlet command throw an error which is greater than 1023 characters, then code trying to set it on the title and throw an error "Window title cannot be longer than 1023 characters" So my point is actual error is not visible to developer that's been a very big problem.

**Comment by davidebbo** [comment]
Yes, there are lots of known issues with running PowerShell in the sandbox today. I just wanted to be clear what error you were getting in response to what, hence the needed clarification about whether you had tried `SilentlyContinue`.

**Comment by avinashsachdewani** [comment]
Yes, I have tried SilentlyContinue preference and my research group created successfully, but still not able to create virtual machines because now I am getting error in my next cmdlet "New-AzureRmResourceGroupDeployment " but this cmdlet also showing me the window title problem so I am not sure what is the actual problem.
I am guessing it's because of json which I am passing on it, but I am not sure.

**Comment by avinashsachdewani** [comment]
I am facing this error now  

New-AzureRmResourceGroupDeployment : The Win32 internal error "The handle is
invalid" 0x6 occurred while setting character attributes for the console 
output buffer. Contact Microsoft Customer Support Services.
At D:\local\Temp\jobs\triggered\webjob\1epcgis0.y53\testDrives\WindowsServer201
2\provision.ps1:17 char:1
+ New-AzureRmResourceGroupDeployment -ResourceGroupName $resourceGroup 
-TemplatePa ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~
    + CategoryInfo          : CloseError: (:) [New-AzureRmResourceGroupDeploym 
   ent], HostException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Resources.NewAzureResou 
   rceGroupDeploymentCommand

**Comment by davidebbo** [comment]
That is the same error as the original issue.

**Comment by avinashsachdewani** [comment]
yes but this time in different cmdlet "New-AzureRmResourceGroupDeployment"

**Comment by davidebbo** [comment]
Is that with or without `SilentlyContinue`?

**Comment by avinashsachdewani** [comment]
with SilentlyContinue

**Comment by davidebbo** [comment]
Interesting.

Anyway, at this point there are enough issues that it's probably best to just say that running Azure PowerShell CmdLets in WebJobs is not yet supported. Hopefully, it's a scenario that can be enabled later.

**Comment by venujakasun** [comment]
Hi David Ebbo,
Is there any way to use "**Login-AzureRMAccount -Credential $Cred**" to **authenticate** with azure and **create a web app** using **Powershell** inside a **web job** and is it **possible** to do this **automation**?
If not **any other way** to do the **automation** please help on this.

**Note :** The web app is **deployed inside** a separate **Azure Resource Group**.

_Thanks & Best Retards,
Venuja Kasun._

**Comment by davidebbo** [comment]
@venujakasun not currently, but there is hope that this will work in the not too distant future.

**Comment by venujakasun** [comment]
Hi David Ebbo,

Thank you very much for your quick reply.

_Thanks & Best Retards,
Venuja Kasun._

**Comment by snobu** [comment]
Have a look at Azure Automation. You definitely can do `Login-AzureRmAccount` in there and you can trigger a Runbook by calling a Webhook from your site code.

https://azure.microsoft.com/en-us/documentation/articles/automation-webhooks/

**Comment by sofipacifico** [comment]
@davidebbo Hello David, how you are doing well. There is another workaround to this issue? 
Using $WarningPreference = "SilentlyContinue" works perfectly. In advance, thanks.

**Comment by davidebbo** [comment]
@sofipacifico adding @ahmelsayed as I am no longer on the team.

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
