### ISSUE TITLE
Infinite redirect loop on accessing the Kudu Console

### ISSUE THREAD

**Issue by BrightSoul** [projectkudu/kudu#2052]
Hello everyone, I'm trying to open the Kudu Console for my Azure Web App but I'm stuck on an endless redirect loop (see a screenshot below). 
When I point my browser to https://aspitalia18.scm.azurewebsites.net/ I'm not asked to enter my publish credentials. Instead, I get redirected to the Microsoft Account login page and once I enter my email and password, the infinite loop starts.
![screenshot from 2016-06-19 23 35 43](https://cloud.githubusercontent.com/assets/1888641/16179969/a42d11ba-3676-11e6-8b68-1d5497339dea.png)

**Comment by davidebbo** [comment]
Yes, this is an unfortunate regression that only affects FF. Could you use Chrome instead for now until it is resolved?

**Comment by BrightSoul** [comment]
Sure, thanks for your reply. It's working fine when I use Google Chrome.

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
