### ISSUE TITLE
Unable to set server variable using xdt transform file because section is locked

### ISSUE THREAD

**Issue by adaam2** [projectkudu/kudu#2053]
I have setup this XDT transform file using the IISManager site extension on the Azure SCM pages:

```
<configuration xmlns:xdt="http://schemas.microsoft.com/XML-Document-Transform">  
    <system.webServer>  
        <proxy xdt:Transform="InsertIfMissing" enabled="true" preserveHostHeader="false"  
        reverseRewriteHostInResponseHeaders="false" />
        <rewrite>
            <allowedServerVariables>
                <add name="X-Prerender-Token" xdt:Transform="InsertIfMissing" />
            </allowedServerVariables>
        </rewrite>  
    </system.webServer>  
</configuration>
```

The above transform adds the X-Prerender-Token variable to the `allowedServerVariables` section. However, looking at my failed request tracing logs, it comes up with this error:
```

SET_RESPONSE_ERROR_DESCRIPTION 

ErrorDescription
The server variable "HTTP_X_PRERENDER_TOKEN" is not allowed to be set. Add the server variable name to the allowed server variable list. 
```

(Screenshot below)
![error](https://cloud.githubusercontent.com/assets/2907389/16197229/2e007eae-36f9-11e6-8932-bcb244ec5d04.PNG)

Looking at my applicationhost.config file again, I saw that the `allowedServerVariables` config section looks like this:

```
<sectionGroup name="rewrite">
        <section name="allowedServerVariables" overrideModeDefault="Deny" />
  </sectionGroup>

```

I presume that this is the setting that is preventing me from adding the HTTP_X_PRERENDER_TOKEN variable to the target section. Now I'm aware that I can't change this directly (I've tried on previous incarnations of my web app and it didn't work anyway), so I must surely write another transform to update the overrideModeDefault value to Allow. If I am barking up the wrong tree here, then how do I allow a server variable to be set?

**Comment by davidebbo** [comment]
I would think you could just set it to allow using your xdt. DId you tried that? What specifically happened?

**Comment by adaam2** [comment]
Hi David,

I tried to write a transform to set the value of `overrideModeDefault` to 'Allow' but didn't really get anywhere - here is my attempt (it doesn't work!):

```
<?xml version="1.0"?>  
<configuration xmlns:xdt="http://schemas.microsoft.com/XML-Document-Transform">  
    <configSections>
      <sectionGroup name="rewrite">
        <section name="allowedServerVariables" xdt:Transform="SetAttributes (overrideModeDefault)" overrideModeDefault="Allow"  />
      </sectionGroup>
    </configSections>
</configuration>
```

**Comment by davidebbo** [comment]
Please see the "Understanding what could go wrong with xdt transforms" section [here](https://github.com/projectkudu/kudu/wiki/Azure-Site-Extensions#understanding-what-could-go-wrong-with-xdt-transforms). WHen you say "didn't really get anywhere", are you referring to the 2nd or 3rd case?

**Comment by adaam2** [comment]
Hi David,

Thanks very much for your reply. I finally managed to write a transform that changed the value of the section below in my applicationHost.config:

```
<?xml version="1.0"?>  
<configuration xmlns:xdt="http://schemas.microsoft.com/XML-Document-Transform">  
    <configSections>
        <sectionGroup name="system.webServer"
                      xdt:Locator="Match(name)">
            <sectionGroup name="rewrite" xdt:Locator="Match(name)">
		<section name="allowedServerVariables"
                     overrideModeDefault="Allow"
                     xdt:Locator="Match(name)"
                     xdt:Transform="Replace" />
            </sectionGroup>
        </sectionGroup>
    </configSections>
    <system.webServer>  
        <proxy xdt:Transform="InsertIfMissing" enabled="true" preserveHostHeader="false"  
        reverseRewriteHostInResponseHeaders="false" />
        <rewrite>
            <allowedServerVariables>
                <add name="X-Prerender-Token" xdt:Transform="InsertIfMissing" />
            </allowedServerVariables>
        </rewrite>  
    </system.webServer>  
</configuration>

```

So that the relevant section of my `applicationHost.config` now looks like so:

```
<sectionGroup name="rewrite">
        <section name="allowedServerVariables" overrideModeDefault="Allow" />
  </sectionGroup>
```

However even with the `overrideModeDefault` section now set to `Allow`, I am still receiving the below error in my Failed Request Tracing logs (see number 61.):

![err](https://cloud.githubusercontent.com/assets/2907389/16200286/96ab3c22-3704-11e6-8ac9-bd93e8c8737e.PNG)

So evidently, this section has no effect on being able to add variables to the `allowedServerVariables` node. It's just been a bit of a time sucker, particularly because there isn't much information online on this topic! I'm at a loss with this - if I was running the application on my owns server, I could just go into IIS and set server variables there (and also have more autonomy over editing the applicationHost.config file)

FYI this is what I'm trying to achieve: https://gist.github.com/blowsie/04c183c62a432f6450c9

**Comment by davidebbo** [comment]
One thing: make sure you restart your site from the Portal after making such changes. The Restart from the IIS manager extension is not always effective.

**Comment by adaam2** [comment]
Not to worry, I've settled on another solution for this problem. Closing. Thanks for your help though.
