### ISSUE TITLE
Projects using both csproj with project.json fail to build

### ISSUE THREAD

**Issue by jrusbatch** [projectkudu/kudu#2056]
I'm attempting to publish a .csproj project that uses `project.json` instead of `packages.config` (based on [these instructions](https://oren.codes/2016/02/08/project-json-all-the-things/) by @onovotny). The `nuget restore` command completes successfully and generates `project.lock.json` and `*.nuget.props`, but the assemblies aren't passed into MSBuild which causes the build to fail.

According to a log generated by MSBuild, it appears that `C:\Program Files (x86)\MSBuild\Microsoft\NuGet\Microsoft.NuGet.props` and `C:\Program Files (x86)\MSBuild\Microsoft\NuGet\Microsoft.NuGet.targets` (imported by `C:\Program Files (x86)\MSBuild\14.0\Imports\Microsoft.Common.Props\ImportBefore\Microsoft.NuGet.ImportBefore.props` and `C:\Program Files (x86)\MSBuild\14.0\Microsoft.Common.Targets\ImportAfter\Microsoft.NuGet.ImportAfter.targets`, respectively). These seem to be responsible for resolving the assemblies that were restored by NuGet.

**Comment by davidebbo** [comment]
Would you be able to [share a sample repo](https://github.com/projectkudu/kudu/wiki/Using-a-git-repo-to-report-an-issue) that demonstrates the condition? Thanks!

**Comment by davidebbo** [comment]
Also, see [these instructions](https://github.com/projectkudu/kudu/wiki/Test-your-ASP.NET-Core-repo-locally) to help isolate the problem.

**Comment by jrusbatch** [comment]
Sure, I've pushed a sample to https://github.com/jrusbatch/KuduProjectJsonRepro. The project is an ASPNET 4.5 project with the following modifications:

1. All `<reference />` elements pointing to assemblies in the `packages` folder were removed from the project file.
2. The `packages.config` file has been replaced by a `project.json` file. All packages listed in the `packages.config` are declared in `project.json` instead.

I've confirmed that this project fails to deploy in Azure. Below is the deployment log. In it, you can see that NuGet successfully restores the packages listed in the `project.json` file and also generates the `project.lock.json` and `KuduProjectJsonRepro.nuget.props`, as it should. However, the MSBuild output later in the log indicates that assemblies restored by NuGet aren't being referenced (causing the CS0234 errors):

```
Command: "D:\home\site\deployments\tools\deploy.cmd"
Handling .NET Web Application deployment.
MSBuild auto-detection: using msbuild version '14.0' from 'D:\Program Files (x86)\MSBuild\14.0\bin'.
Restoring packages for D:\home\site\repository\src\KuduProjectJsonRepro\project.json...
Committing restore...
Lock file has not changed. Skipping lock file write. Path: D:\home\site\repository\src\KuduProjectJsonRepro\project.lock.json
Generating MSBuild file KuduProjectJsonRepro.nuget.props.
D:\home\site\repository\src\KuduProjectJsonRepro\KuduProjectJsonRepro.csproj
Restore completed in 618ms.

NuGet Config files used:
    C:\DWASFiles\Sites\#1KuduProjectJsonRepro\AppData\NuGet\NuGet.Config

Feeds used:
    https://api.nuget.org/v3/index.json
App_Start\BundleConfig.cs(2,18): error CS0234: The type or namespace name 'Optimization' does not exist in the namespace 'System.Web' (are you missing an assembly reference?) [D:\home\site\repository\src\KuduProjectJsonRepro\KuduProjectJsonRepro.csproj]
App_Start\FilterConfig.cs(2,18): error CS0234: The type or namespace name 'Mvc' does not exist in the namespace 'System.Web' (are you missing an assembly reference?) [D:\home\site\repository\src\KuduProjectJsonRepro\KuduProjectJsonRepro.csproj]
App_Start\RouteConfig.cs(5,18): error CS0234: The type or namespace name 'Mvc' does not exist in the namespace 'System.Web' (are you missing an assembly reference?) [D:\home\site\repository\src\KuduProjectJsonRepro\KuduProjectJsonRepro.csproj]
Controllers\HomeController.cs(5,18): error CS0234: The type or namespace name 'Mvc' does not exist in the namespace 'System.Web' (are you missing an assembly reference?) [D:\home\site\repository\src\KuduProjectJsonRepro\KuduProjectJsonRepro.csproj]
Global.asax.cs(5,18): error CS0234: The type or namespace name 'Mvc' does not exist in the namespace 'System.Web' (are you missing an assembly reference?) [D:\home\site\repository\src\KuduProjectJsonRepro\KuduProjectJsonRepro.csproj]
Global.asax.cs(6,18): error CS0234: The type or namespace name 'Optimization' does not exist in the namespace 'System.Web' (are you missing an assembly reference?) [D:\home\site\repository\src\KuduProjectJsonRepro\KuduProjectJsonRepro.csproj]
App_Start\BundleConfig.cs(9,44): error CS0246: The type or namespace name 'BundleCollection' could not be found (are you missing a using directive or an assembly reference?) [D:\home\site\repository\src\KuduProjectJsonRepro\KuduProjectJsonRepro.csproj]
App_Start\FilterConfig.cs(8,50): error CS0246: The type or namespace name 'GlobalFilterCollection' could not be found (are you missing a using directive or an assembly reference?) [D:\home\site\repository\src\KuduProjectJsonRepro\KuduProjectJsonRepro.csproj]
Controllers\HomeController.cs(9,35): error CS0246: The type or namespace name 'Controller' could not be found (are you missing a using directive or an assembly reference?) [D:\home\site\repository\src\KuduProjectJsonRepro\KuduProjectJsonRepro.csproj]
Controllers\HomeController.cs(11,16): error CS0246: The type or namespace name 'ActionResult' could not be found (are you missing a using directive or an assembly reference?) [D:\home\site\repository\src\KuduProjectJsonRepro\KuduProjectJsonRepro.csproj]
Controllers\HomeController.cs(16,16): error CS0246: The type or namespace name 'ActionResult' could not be found (are you missing a using directive or an assembly reference?) [D:\home\site\repository\src\KuduProjectJsonRepro\KuduProjectJsonRepro.csproj]
Controllers\HomeController.cs(23,16): error CS0246: The type or namespace name 'ActionResult' could not be found (are you missing a using directive or an assembly reference?) [D:\home\site\repository\src\KuduProjectJsonRepro\KuduProjectJsonRepro.csproj]
Failed exitCode=1, command="D:\Program Files (x86)\MSBuild\14.0\Bin\MSBuild.exe" "D:\home\site\repository\src\KuduProjectJsonRepro\KuduProjectJsonRepro.csproj" /nologo /verbosity:m /t:Build /t:pipelinePreDeployCopyAllFilesToOneFolder /p:_PackageTempDir="D:\local\Temp\8d39c414c3241ca";AutoParameterizationWebConfigConnectionStrings=false;Configuration=Release;UseSharedCompilation=false /p:SolutionDir="D:\home\site\repository\.\\"
An error has occurred during web site deployment.
\r\nC:\Program Files (x86)\SiteExtensions\Kudu\55.50620.2286\bin\Scripts\starter.cmd "D:\home\site\deployments\tools\deploy.cmd"
```

**Comment by davidebbo** [comment]
Did you try doing the same locally using the instructions I linked to above? That's a good first step to test whether the issue is Azure specific or general.

**Comment by jrusbatch** [comment]
`nuget restore & msbuild KuduProjectJsonRepro.sln /t:Build /p:Configuration=Release` work locally in a clean clone of the repository. The `dotnet` commands failed since this is not an ASP.NET Core project.

**Comment by davidebbo** [comment]
Ah sorry, I missed that it wasn't using Core. I think things are indeed broken when using Classic .NET Fx. We'll investigate!

**Comment by davidebbo** [comment]
Ok, I think I got confused by the naming. There are (at least) 3 cases:

1. Regular ASP.NET application running on .NET Framework
2. ASP.NET Core application running on .NET Framework
3. ASP.NET Core application running on .NET Core

I thought you were creating 2. in VS, but now I understand that you're creating 1.

And then on top of 1. you are changing package.config to project.json. I haven't encountered this before. Is this a supported model? How does msbuild know where the references are coming from in this case?

@vijayrkn are you familiar with this scenario?

**Comment by onovotny** [comment]
@davidebbo The NuGet targets read the `project.lock.json` file and create MSBuild Reference items as needed.

**Comment by davidebbo** [comment]
@onovotny ah, I see. We need to figure out why that's not happening on Azure.

**Comment by vijayrkn** [comment]
I haven't tried publishing this scenario (csproj with project.json).  I will try executing this target "/t:pipelinePreDeployCopyAllFilesToOneFolder" on the csproj(with project.json) to see what error is getting thrown.

**Comment by davidebbo** [comment]
@vijayrkn With @jrusbatch's solution, on an Azure Web App, I can't even run plain `msbuild` after restoring NuGet packages (same error as Justin above). And that's on a test stamp with all the newest target files you gave us yesterday. Not sure what to make of it.

**Comment by jrusbatch** [comment]
@davidebbo When I build the project on my system, the MSBuild files contained in the [NuGet.BuildTasks repository](https://github.com/NuGet/NuGet.BuildTasks/tree/3a3aeb470862ce47e013bc31a2d1adc9e2829ee6/src/Microsoft.NuGet.Build.Tasks) are imported into the MSBuild pipeline. `Microsoft.Common.props` imports [`Microsoft.NuGet.ImportBefore.props`](https://github.com/NuGet/NuGet.BuildTasks/blob/3a3aeb470862ce47e013bc31a2d1adc9e2829ee6/src/Microsoft.NuGet.Build.Tasks/ImportBeforeAfter/Microsoft.NuGet.ImportBefore.props) because of its location on the file system (`$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Imports\Microsoft.Common.props\ImportBefore\`). It in turn imports [`Microsoft.NuGet.props`](https://github.com/NuGet/NuGet.BuildTasks/blob/3a3aeb470862ce47e013bc31a2d1adc9e2829ee6/src/Microsoft.NuGet.Build.Tasks/Microsoft.NuGet.props). [`Microsoft.NuGet.targets`] gets imported in a similar fashion later in the pipeline (after `Microsoft.Common.targets` is imported).

`Microsoft.NuGet.targets` declares targets that resolve the assemblies provided by NuGet packages.

**Comment by jrusbatch** [comment]
In Kudu, the NuGet's MSBuild files are not imported into the pipeline.

**Comment by vijayrkn** [comment]
Once the restore is successful, the publish target(pipelinePreDeployCopyAllFilesToOneFolder) runs without any issues. For me I restored the packages from NuGet.org.

**Comment by jrusbatch** [comment]
@vijayrkn The deployment succeeded for you in Azure via Kudu? Did you need to make any modifications to get it to work?

**Comment by davidebbo** [comment]
No, he didn't test Azure. It's broken today, but there is a chance we'll have that fixed early next week.

**Comment by jrusbatch** [comment]
@davidebbo Awesome! Thanks for your help with this!

**Comment by moswald** [comment]
I've just run into this problem myself, and I was wondering when "early next week" might be. :)

**Comment by davidebbo** [comment]
Actually, many new things were deployed with the launch of Core 1.0. @jrusbatch's repo still doesn't quite work as is, but can be made to work with one simple change. In Azure App Settings, set `NUGET_PACKAGES` to `d:\home\.nuget`. Can you give that a try?

If you *don't* do that, then the `nuget restore` ends up restoring things into `D:\local\UserProfile\.nuget\packages`, but then the build apparently does not know to look for them there.

Does anyone understand why that is? I'm thinking there is some issue in the target files somewhere. Where does the build look for packages by default?

**Comment by moswald** [comment]
Yes, adding `NUGET_PACKAGES` to the App Settings worked like a charm! Thanks!

**Comment by davidebbo** [comment]
The specific error is:

    D:\Program Files (x86)\MSBuild\Microsoft\NuGet\Microsoft.NuGet.targets(140,5): error : The package Antlr with version 3.4.1.9004 could not be found in .nuget\packages. Run a NuGet package restore to download the package. [D:\home\site\repository\src\KuduProjectJsonRepro\KuduProjectJsonRepro.csproj]

And I found (via procmon) that it's looking for the `.nuget` folder under `D:\home\site\repository\src\KuduProjectJsonRepro`, so under the folder where the `.csproj` is.

So there is a clear disconnect between `nuget restore` and `msbuild`.

**Comment by davidebbo** [comment]
We will make this the default behavior. @ahmelsayed is working on fix and will get it out.

**Comment by jrusbatch** [comment]
@davidebbo I'm no longer seeing this behavior for my team's apps. As far as I'm concerned this issue can be closed. Thanks for all of the help!

**Comment by davidebbo** [comment]
We've just deployed an update to Kudu that automatically sets `NUGET_PACKAGES`. So now, your original test repo can be pushed successfully without any special app settings. @moswald, if you have a chance, you can verify that you no longer need it.
