### ISSUE TITLE
.Net Core multi-project solution containing website

### ISSUE THREAD

**Issue by mrfoster** [projectkudu/kudu#2059]
I have a solution that consists of a .Net Core RC2 project and a website project (API + static website). We are able to publish the .Net Core project by specifying the Project path app setting but doing the same for the website project gives the following log:

```
Using the following command to generate deployment script: 'azure site deploymentscript -y --no-dot-deployment -r "D:\home\site\repository" -o "D:\home\site\deployments\tools" --aspWebSite --solutionFile "D:\home\site\repository\Solution1.sln" --sitePath "D:\home\site\repository\website"'.
Solution file path: .\Solution1.sln
The site directory path: .\website
Generating deployment script for .NET Web Site
Generated deployment script files

Command: "D:\home\site\deployments\tools\deploy.cmd"
Handling .NET Web Site deployment.
  D:\Program Files (x86)\dotnet\dotnet.exe build "D:\home\site\repository\WebApplication1" --configuration Debug --no-dependencies
D:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Common.Targets(241,5): error : Project WebApplication1 does not have a lock file. [D:\home\site\repository\WebApplication1\WebApplication1.xproj]
D:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Common.Targets(241,5): error : Project WebApplication1 does not have a lock file. [D:\home\site\repository\WebApplication1\WebApplication1.xproj]
Failed exitCode=1, command="D:\Program Files (x86)\MSBuild\14.0\Bin\MSBuild.exe" "D:\home\site\repository\Solution1.sln" /verbosity:m /nologo
An error has occurred during web site deployment.
\r\nC:\Program Files (x86)\SiteExtensions\Kudu\55.50620.2286\bin\Scripts\starter.cmd "D:\home\site\deployments\tools\deploy.cmd"
```

Example repo can be found here:
https://github.com/mrfoster/kudu-multiproject-issue-2

**Comment by davidebbo** [comment]
Can you clarify exactly how you are specifying the project path?

**Comment by mrfoster** [comment]
The project path is being set from the Azure Portal Application settings.

`Project: website`

**Comment by davidebbo** [comment]
I see the problem: in the Websites case, the deployment script doesn't do a NuGet restore. But it still runs msbuild, which then blows up.

Does your Website depend on anything in other folders, or is the 'website' folder completely standalone. We can solve it either way.

**Comment by mrfoster** [comment]
In my case the website is completely standalone.

Thanks for your quick response.

I'd also like to reopen #2023 if at all possible which looks like the nuget restore is being attempted at the root path instead of the supplied project path.

**Comment by davidebbo** [comment]
I'm a little confused with your repo. Looking at https://github.com/mrfoster/kudu-multiproject-issue-2/tree/master/website, it has a web.config, but no other files. Deploying it as a Website basically means copying whatever is in that folder into your wwwroot folder, and clearly that's not going to run. How does this work?

**Comment by mrfoster** [comment]
Sorry about that. The problem was spotted in a much bigger closed source project so I created a solution to demonstrate the same error. It is the same error as I get in the main project but I forgot to add an index.html.

**Comment by davidebbo** [comment]
To just deploy that folder with no extra fuss, try setting the following App Setting in the portal for that Web App:

    SCM_SCRIPT_GENERATOR_ARGS=--basic --sitePath website

**Comment by mrfoster** [comment]
Thank you, that works great!

**Comment by ahmelsayed** [comment]
https://github.com/projectkudu/KuduScript/pull/51
