### ISSUE TITLE
Remove old KuduUnexpectedException analytic

### ISSUE THREAD

**Issue by davidebbo** [projectkudu/kudu#2062]
We have a comment on https://github.com/projectkudu/kudu/blob/c868bd0269a17bd57af8d8bf6dd2bdee42ff796b/Kudu.Core/Tracing/Analytics.cs#L70-L80 that says to get rid of redundant exeption analytic, but we never did. Let's clean this up.

**Comment by davidebbo** [comment]
@shrimpy seems you added that comment. Can you clean up accordingly?

            // ETW event for KuduException is not existed yet in current Antares deployment
            // "duplicate" log with KuduUnexpectedException so that we will have some data for trouble shooting for now
            // TODO: once next antares release is out, KuduUnexpectedException will be merge into KuduException

**Comment by shrimpy** [comment]
PR is out https://github.com/projectkudu/kudu/pull/2067
