### ISSUE TITLE
Continuous integration syncing after clicking "No"

### ISSUE THREAD

**Issue by mathewc** [projectkudu/kudu#2066]
See original issue in Functions repo here: https://github.com/Azure/azure-webjobs-sdk-script/issues/463

I've set-up contiuous integration for my Azure Functions. Configured a github repo as a source. When I now click sync, it asks me:

"Are you sure you want to retrieve and deploy contents from your GitHub repository?"

I wasn't completely sure the first time, so I clicked 'No' but to my surprise it started syncing anyhow. Ended up with a green checkbox so everything seems to be fine, but I didn't expect it to sync after clicking No.

**Comment by davidebbo** [comment]
If you set up continuous deployment, you don't need to click sync in order for deployment to happen. That's most likely what happened. i.e. the deployment you saw had nothing to do with you clicking the Sync button.
