### ISSUE TITLE
do not have permission to view this directory or page

### ISSUE THREAD

**Issue by estherfang09** [projectkudu/kudu#2068]
The azure website url is http://webapp6.secureenvironment.p.azurewebsites.net/.

I tried to deploy my asp.net mvc web application to azure. But somehow, I could not using web deploy in vs2015 community, I always receive an error:
Web Deploy experienced a connection problem with the server and had to terminate the connection. Contact your server administrator if the problem persists. Learn more at: http://go.microsoft.com/fwlink/?LinkId=221672#ERROR_CONNECTION_TERMINATED. WebApplication6 0.

So I changed to deploy using local git to deploy to azure. I was able to deploy, but when I typed in the url of the web app, I got:You do not have permission to view this directory or page. And I can't access any of the controller I defined in the code.

**Comment by davidebbo** [comment]
Note that Web Deploy is not part of Kudu. Please use the [forum](https://social.msdn.microsoft.com/Forums/azure/en-US/home?forum=windowsazurewebsitespreview) to discuss those issues.

For the git deployment, can you give more details about your application? e.g. is it classic .NET, .NET core, Node, etc...? If you can [share a small repo](https://github.com/projectkudu/kudu/wiki/Using-a-git-repo-to-report-an-issue) that shows the issue, that can also help investigation.

**Comment by estherfang09** [comment]
I would say it is a classic .net application using Entity Framework. No much difference from the tutorial 's web app :http://www.asp.net/mvc/overview/getting-started/introduction/adding-a-model

**Comment by davidebbo** [comment]
MVC apps should work fine in Kudu. Please do share a repo so we can try to understand what's going on with yours.

**Comment by davidebbo** [comment]
I took a look at your app, and it's a Core app based on the old RC1 release (previously called ASP.NET 5). This is no longer supported. You have two main choices for a Web App:

- Create a regular ASP.NET application
- Create a .NET Core application. To do this, get the latest bits from https://www.microsoft.com/net (it was just released on Monday)

**Comment by srinivasgnt** [comment]
Hi I have a project which is a class library and it contains angular js related files, using npm and yarn on my local machine I am able to run application, after publishing in azure as a webapp/Node js empty webapp, its showing "You do not have permission to view this directory or page." , please tell me the reason and how to solve this?

**Comment by davidebbo** [comment]
@srinivasgnt start with [this](https://github.com/projectkudu/kudu/wiki/Deployment-vs-runtime-issues).

But unless you are using an outdated Core build, your issue is unrelated to this one.
