### ISSUE TITLE
Autoswap of failed deployment

### ISSUE THREAD

**Issue by siroky** [projectkudu/kudu#2073]
Hi, I've found that there's already been similar issue - #1813, however the described problem is still happening to me. Even if the deployment fails, the swap operation is performed and the version of latest successful deploy before the erroneous deploy is used. According to our logs, we're observing the following scenario:

1. Production slot running V2, Staging slot running V1.
2. Github deployment of V3 (erroneous) to staging slot.
3. Deployment fails, swap operation is triggered.
4. Production slot running V1, staging slot running V2.

This is how it looks like in Azure portal:

![image](https://cloud.githubusercontent.com/assets/435787/16536520/d03cdde6-3ff2-11e6-8d4b-d00cd7a2522d.png)

Compared to successful deployment, the `Running post deployment command(s)...` and `Deployment successful.` items of the deployment details are missing.

**Comment by shrimpy** [comment]
@siroky taking a look now

**Comment by shrimpy** [comment]
@siroky so i guess "mews-develop-weu" is your Production slot? since i saw multiple site are next to mews-develop-weu(staging)

**Comment by siroky** [comment]
Yes, and mews-develop-weu-staging is the staging slot which had autswap turned on. But since the issue was happening, I had to turn off the autoswap and set up direct deployment from github to mews-develop-weu because we need it functional. If you need some internal details, we can discuss it over email which is in my profile.

**Comment by shrimpy** [comment]
@siroky fix is in master, will try to have this fix out to public in the coming day or two.

**Comment by siroky** [comment]
Great, thanks!

**Comment by shrimpy** [comment]
@siroky Deployment is done, issue should be gone now. Let us know if you still seeing it.
