### ISSUE TITLE
Need a way to be able to NGEN assemblies

### ISSUE THREAD

**Issue by robertmclaws** [projectkudu/kudu#2074]
The assemblies in the `Microsoft.Net.Compilers` NuGet package need to be NGENed on Azure boxes for maximum performance. If you don't, there is a > 14 second delay in the first page load for _every_ page on a site.

However, that does not appear to be presently possible from the Kudu Powershell console. Would be nice if you guys could come up with a way that would let me run the NGEN command against assemblies deployed to my Websites instance w/o requiring admin permissions.

Thanks!

**Comment by davidebbo** [comment]
Yes, that is something we are looking at.

**Comment by Benraay** [comment]
+1 Same need here

**Comment by davidebbo** [comment]
Sorry, my previous reply was not clear. I meant we were looking specifically at ngen'ing the Microsoft.Net.Compilers assemblies, and this is in fact done (specifically v1.3.1).

There is no support for users ngening arbitrary assemblies, as generally nothing that runs in the sandbox can affect machine global state. This is an Azure Web App thing, and not related to Kudu.

**Comment by Benraay** [comment]
do you mean that Microsoft.Net.Compilers are ngen'ed for now ?, are the EntityFramework.dll also beeing ngen'ed

**Comment by davidebbo** [comment]
No EntityFramework currently isn't.

Closing here since this is a pure Web App runtime topic not related to Kudu.
