### ISSUE TITLE
Unsuccessful deployment on Windows server 2012R2

### ISSUE THREAD

**Issue by egoisticum** [projectkudu/kudu#2075]
Hello dears,

First of all, we at our company just found kudu project before 2 months and now found the time to investigate more about it.

So, we implemented it on our test web server which is "Windows server 2012 R2" - virtual machine on Microsoft Azure. 
In this moment we established connection with kudu, we are enable to create the projects through kudu web interface and accessing on kudu through our test subdomain dedicated for kudu.

Kudu is really great idea and if we can manage to make everything works on our servers no doubts we will use it a lot. 

Basically, our issue is related to the "npm install" part of deployment, git push is OK and nothing to say about this except it works like a charm, even more kudu converts successfully commits to the source code on the same server, but it seems it's problem in permissions when you try to do "npm install".
Here is my npm-debg log: https://drive.google.com/file/d/0BxuRNkB4HQMmUlJXNk56VjNMNDg/view?usp=sharing
Bellow is output in my console.
Please, any help would be so appreciated by us because of we already lost a lot of time on this, but it seems it's all about permissions and few clicks.
Thank you in advance.

> C:\work\mss\freetouring-backend>git push test
> Counting objects: 4, done.
> Delta compression using up to 4 threads.
> Compressing objects: 100% (4/4), done.
> Writing objects: 100% (4/4), 363 bytes | 0 bytes/s, done.
> Total 4 (delta 3), reused 0 (delta 0)
> remote: Updating branch 'master'.
> remote: Updating submodules.
> remote: Preparing deployment for commit id '398900e808'.
> remote: Generating deployment script.
> remote: Running deployment command...
> remote: Handling node.js deployment.
> remote: KuduSync.NET from: 'F:\inetpub\wwwroot\apps\freetours-backend\site\repository' to: 'F:\inetpub\wwwroot\apps\freetours-backend\site\wwwroot'
> remote: Copying file: 'models\index.js'
> remote: Using start-up script server.js from package.json.
> remote: Generated web.config.
> remote: Node.js versions available on the platform are: 5.0.0, 5.1.0, 5.10.0, 6.0.0.
> remote: Selected node.js version 6.0.0. Use package.json file to choose a different version.
> remote: Selected npm version 3.9.5
> remote: Updating iisnode.yml at F:\inetpub\wwwroot\apps\freetours-backend\site\wwwroot\iisnode.yml
> remote: npm ERR! Windows_NT 6.3.9600
> remote: npm ERR! argv "C:\Program Files (x86)\nodejs\6.0.0\node.exe" "C:\Program Files (x86)\npm\3.9.5\bin\npm-cli.js" "install" "--production"
> remote: npm ERR! node v6.0.0
> remote: npm ERR! npm  v3.9.5
> remote: npm ERR! path C:\Windows\system32\config\systemprofile\AppData\Roaming\npm-cache\cors
> remote: npm ERR! code EPERM
> remote: npm ERR! errno -4048
> remote: npm ERR! syscall mkdir
> remote:
> remote: npm ERR! Error: EPERM: operation not permitted, mkdir 'C:\Windows\system32\config\systemprofile\AppData\Roaming\npm-cache\cors'
> remote: npm ERR!     at Error (native)
> remote: npm ERR!  { Error: EPERM: operation not permitted, mkdir 'C:\Windows\system32\config\systemprofile\AppData\Roaming\npm-cache\cors'
> remote: npm ERR!     at Error (native)
> remote: npm ERR!   errno: -4048,
> remote: npm ERR!   code: 'EPERM',
> remote: npm ERR!   syscall: 'mkdir',
> remote: npm ERR!   path: 'C:\Windows\system32\config\systemprofile\AppData\Roaming\npm-cache\cors',
> remote: npm ERR!   parent: 'freetouring-backend' }
> remote: npm ERR!
> remote: npm ERR! Please try running this command again as root/Administrator.
> remote:
> remote: npm ERR! Please include the following file with any support request:
> remote: npm ERR!     F:\inetpub\wwwroot\apps\freetours-backend\site\wwwroot\npm-debug.log
> remote: Failed exitCode=-4048, command="C:\Program Files (x86)\nodejs\6.0.0\node.exe" "C:\Program Files (x86)\npm\3.9.5\bin\npm-cli.js" install --production
> remote: An error has occurred during web site deployment.
> remote:
> remote: Error - Changes committed to remote repository but deployment to website failed.
> To http://freetours-backend.scm.kudu.mss.ba/freetours-backend.git
>    5474aa8..398900e  master -> master

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
