### ISSUE TITLE
Build link on the home page is a 404

### ISSUE THREAD

**Issue by brettcannon** [projectkudu/kudu#2080]
On the home page of my Web Apps' SCM page, there's a link to the build of Kudu being used (in this case, https://github.com/Azure/kudu/commit/1d90b266e8c346b720b9dd7cb0ae5161a82951e1). The problem is that Azure/kudu is not a valid project and I can't actually find a repo with that commit hash.

**Comment by snobu** [comment]
I think that's the Private Kudu we deploy to Azure, which is in a different (private) repo.
/cc @davidebbo

**Comment by davidebbo** [comment]
Yes, it's a bit unfortunate that this link ends up not being clickable by most people. But it does represent the true commit.

**Comment by brettcannon** [comment]
Could the link then be dropped? I understand wanting to include the hash for debugging purposes, but it's misleading to have it be clickable to a repo that isn't publicly visible when the link itself is public (and I can't even see the private repo and I'm in the Azure org on GH so does it work even for MS employees?).

**Comment by davidebbo** [comment]
Permission on private repos is on a per-repo basis, so being in org doesn't mean much. Ideally we'd find a way to include both links.

**Comment by brettcannon** [comment]
Personally, I don't need access. I'm just worried about it looking to the public like Kudu was being sloppy by having a (seemingly) busted URL that they are generating.

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
