### ISSUE TITLE
logstream is extremely slow to load

### ISSUE THREAD

**Issue by hcapp01** [projectkudu/kudu#2081]
It take forever to load https://{name}.scm.azurewebsites.net/logstream

**Comment by ahmelsayed** [comment]
Which browser are you using? The problem is that some browsers will buffer the response because of the `"text/plain"` mime type

**Comment by hcapp01** [comment]
Mac chrome and safari both take several minutes to load. Shall I try windows IE?

**Comment by davidebbo** [comment]
Closing since this is really a browser issue. If you use `curl`, it works with no delays.

**Comment by ritazh** [comment]
For others who might run into this issue in the future, try the Log Stream UI in Azure portal. It’s so much faster!!! Thanks @davidebbo! 👍

**Comment by luismesagravedeperalta** [comment]
@davidebbo It's an issue in ALL browsers... doesn't it make it an issue for kudu indeed?? I've NEVER been able to acually see this console. I used to go to Azure UI as @ritazh suggests, but now I don't have access to it and I really need the kudu console, and it doesn't work. It's been like that for years now. Could you please kindly take a look at it and make it work?
Best
PS: my console hasn't loaded yet... still waiting..

**Comment by davidebbo** [comment]
@luismesagravedeperalta Please just use `curl` instead as explained above. We should probably just remove that option from the Kudu menu.
