### ISSUE TITLE
Improve surfacing UI alerts

### ISSUE THREAD

**Issue by snobu** [projectkudu/kudu#2082]
Fellow Kudu'ers,

So, i've implemented the long awaited (or was it?) **New File** "feature" in the UI - that was trivial - i'll send a PR for that. Of course you could do `touch newfile.txt` but how discoverable is that?

Now for the more interesting part, i'm looking at improving the way errors are being surfaced to the UI.

Here's my first attempt:

#### UI alert on backend error -- Before:
![1old](https://cloud.githubusercontent.com/assets/6472374/16849112/ab8023b4-4a01-11e6-9501-d3555382ade4.gif)

#### UI alert on backend error -- After:
![1toast](https://cloud.githubusercontent.com/assets/6472374/16849114/ad4ecc90-4a01-11e6-8c60-6b74d7850165.gif)

Code addition is minimal, just a few lines of jQuery for the toast and a few lines of `.css`, no plugins.
Needs a bit more work on the styling (perhaps a broken Kudu swiss army knife replacing the current `(!)` glyph in the toast...). I'm not sold on the bright red color either, maybe it's too much.

Feedback is appreciated.

**Comment by shrimpy** [comment]
@snobu i think it is a great idea. I love demo.

some suggestions and questions:

1) For styling, Kudu has reference to bootstrap css, maybe can take a look at their [Contextual classes](http://getbootstrap.com/css/#tables-contextual-classes) ?

2) For the toast, other than jQuery, there is also also [Bootstrap Alert messages](http://getbootstrap.com/javascript/#alerts)? Maybe take a quick look and see which one works better for you in this case as well as on different browsers.

3) For the toast animation, will it auto disappear? I would suggest to NOT "auto disappear" and have a way (a x button maybe) to let user close it themselves. Since error message sometime would be long and people might not able to finish reading it before message disappear.

4) Will be good to have a easy way to copy the error message :)   (not an important improvement i think, since we can always select the text and do copy from right click menu)

**Comment by snobu** [comment]
Thanks! All very good suggestions! I'll do more research on all points.

**Comment by snobu** [comment]
Tried Bootstrap's `alert alert-danger` and `alert-warning`, they're... very washed out for the purpose of showing a fatal error.

![image](https://cloud.githubusercontent.com/assets/6472374/16918043/bb54692c-4d0c-11e6-9a66-ee38e844b50f.png)

![image](https://cloud.githubusercontent.com/assets/6472374/16918122/feefec38-4d0c-11e6-9d56-c79f43b35f97.png)


I've also looked at Bootstrap Alert but it's mainly modal and i'd have to work against it (deconstruct the modal, remove what's not needed and make a toast out of it), i think that just building from scratch around JQuery's `.animate()` and keeping it simple is good recipe for cross-browser success. It already works in Edge, Chrome, IE and Firefox since it's just jQuery. Using my killer smooth skills i'll ask my girlfriend for her Macbook to test Safari and not get into trouble!

### Here's the new improved build with manually disposable toasts (no auto hide)

![alert2](https://cloud.githubusercontent.com/assets/6472374/16918050/c022f7ac-4d0c-11e6-8d01-2a3a1148b224.gif)


```javascript
// Toast notifications for backend errors
// TODO: Move as much scaffolding as possible to WindowsConsole.cshtml

function toast(errorMsg) {
    var scaffold = `
        <div class="notification error"><!-- notification error -->
          <div class="col-sm-1"><i class="glyphicon glyphicon-remove" style="padding: 0; margin: 0;" aria-hidden="true"></i></div>
          <div class="col-sm-9">` + errorMsg + '</div>' +
        '</div>';
    var item = $(scaffold);
    $('#toastem').append($(item));
    $(item).animate({'right': '12px'}, 'fast');

    $('#toastem').on('click','.notification', function(){
  	    $(this).animate({'right': '-400px'}, function(){
            $(this).remove();
  	    });
  	});
}

**Comment by shrimpy** [comment]
@snobu thanks for the update, I think it looks great! Feel free to send out PR.

**Comment by shrimpy** [comment]
@snobu just notice below statement from you, if user want to copy the error message, they will have to click on the toast, will be good to only dismiss when click on "X" ?  Unless there is a way for user to copy error message.

````
BTW: You can click anywhere on the toast to dismiss, not just the X
````

**Comment by snobu** [comment]
Right. The close div should close it and the right part should allow you to copy.. Although I wonder if that's something people will really use since these are pretty much errors you deal with on the spot not something you'd send over to someone.. Maybe we should just `console.error()` the message.. But then again I wonder how to make that discoverable.. Let me do some more thinking around this.

**Comment by snobu** [comment]
Here's what i believe to be the final form.

I've shown this to my girlfriend (who is a DTP artist) and the color combo seems to be the best match for the Bootstrap theme and communicating a fatal error.

Of course i need this to also be Project Kudu approved not just girlfriend approved.

![final](https://cloud.githubusercontent.com/assets/6472374/17445827/2ecd55c6-5b4f-11e6-9ed8-c8f48789281e.gif)

I only need to iron out a few quirks with passing JSON from the `$.axaj` calls into the toast a bit more cleanly and i'll send the PR. But after my holiday. Which starts now. :airplane:

**Comment by davidebbo** [comment]
Looks good to me, so let's call it Project Kudu approved!

**Comment by snobu** [comment]
PR sent - https://github.com/projectkudu/kudu/pull/2124
