### ISSUE TITLE
Error creating deployment slot

### ISSUE THREAD

**Issue by bragma** [projectkudu/kudu#2084]
Hi,
I am running a web app hosted by kudu and somehow I can't create a deployment slot after deleting the previous one. Everything was working fine, when I decided to delete the staging slot and recreate it -> I can't create slots anymore on that server.

The exact sequence I did is:
1. Deployed in production several times, using VS
2. Created a deploy slot (staging)
3. Deployed to staging using VSTS
4. Moved some traffic to is, using traffic routing (50%)
5. Everything was fine, I swapped staging with production
6. Deleted staging slot (was production)

Now I can't create any slot. The returned error is so generic I can't do anything with it:

Failed to create slot staging for web app uptivoapi: {"Code":"InternalServerError","Message":null,"Target":null,"Details":[{"Message":null},{"Code":"InternalServerError"},{"ErrorEntity":{"Code":"InternalServerError","Message":null,"ExtendedCode":null,"MessageTemplate":null,"Parameters":null,"InnerErrors":null}}],"Innererror":null}

What can I do to understand what's wrong with it?
Thanks!

**Comment by davidebbo** [comment]
Kudu handles continuous deployment, but is not involved in the creation/deletion of apps and slots. Can you please ask the question on the [Web App Forum](https://social.msdn.microsoft.com/Forums/azure/en-US/home?forum=windowsazurewebsitespreview) instead? When you do, please include the site name (either directly or [indirectly](https://github.com/projectkudu/kudu/wiki/Reporting-your-site-name-without-posting-it-publicly)) and UTC time of the failure.

**Comment by bragma** [comment]
@davidebbo  thanks for directing me to the correct support site!
