### ISSUE TITLE
ScmType GitHub on a local install

### ISSUE THREAD

**Issue by jsheely** [projectkudu/kudu#2092]
Is it possible to deploy your own Kudu server / service and have GitHub support?

It looks like the ScmType doesn't have GitHub listed.

```csharp
public static class ScmType 
    { 
        public const string None = "None";
        public const string LocalGit = "LocalGit";
        public const string Tfs = "Tfs";
        public const string TfsGit = "TfsGit";
    }
```

Any advice would be appreciated. Thanks

**Comment by davidebbo** [comment]
Yes, it is possible. Those strings are only used to determine if source control is enabled, and the check just black lists some values, so everything else is considered enabled:

    return scmType != ScmType.None && scmType != ScmType.Tfs && scmType != ScmType.TfsGit;

**Comment by jsheely** [comment]
Thanks @davidebbo 

Would you mind explaining how to configure it a little further. I'm still learning some of the inner workings of Kudu.

I manually created my .git repository in the repository folder and added the remote to git pull. I also manually configured the webhook for GitHub so it calls the /deploy?scmType=GitHub

But I"m not sure how to configure the service itself for ScmType=Github as it always says LocalGit (even when I add an AppSetting in the web.config).

Thank you for the advice.

**Comment by davidebbo** [comment]
It actually should still work with LocalGit, so I think you can ignore that part.

But note that you should not be creating the git repo yourself. Instead, let Kudu create it as needed as it clones/fetches from GitHub (the payload from GitHub includes the repo URL).

**Comment by jsheely** [comment]
Ohh. That makes sense. Okay. I had tried that originally and it didn't seem to do anything. So I must have missed something else.

I'll keep plugging away. Thank you for the help.

**Comment by jsheely** [comment]
ugh, I'm dumb. I was testing with the initial X-GITHUB-EVENT: PING message. Not an actually push event. Silly me. Yes it works perfectly now.

**Comment by davidebbo** [comment]
Awesome!
