### ISSUE TITLE
Update Wiki page information about supported frameworks in Azure Websites

### ISSUE THREAD

**Issue by EvoPdf** [projectkudu/kudu#2094]
Could you please remove EvoPdf from the list of unsupported frameworks in Azure Websites in https://github.com/projectkudu/kudu/wiki/Azure-Web-App-sandbox#unsupported-frameworks page? 

As is already mentioned in that list in parantheses, EvoPdf has actually a working solution for Azure, but even so it appears in the list of unsupported frameworks. This can create unwanted confusion for EvoPdf users. The working solution is http://www.evopdf.com/azure-html-to-pdf-converter.aspx .

I think the correct content would be to have a list of not working frameworks and a list of working solutions for Azure Websites. If this is not possible then could you please remove EvoPdf from that list?

Thanks!

**Comment by davidebbo** [comment]
I've tweaked the section to make it clearer that it's supported.
