### ISSUE TITLE
Is it possible to trigger restart for httpPlatfrom via kudu deployment script?

### ISSUE THREAD

**Issue by oak-tree** [projectkudu/kudu#2097]

**Comment by davidebbo** [comment]
Do you mean restart the Web App as part of deployment? Can you give more details behind the question? Thanks!

**Comment by oak-tree** [comment]
Yes, restart the WebApp or just the `httpPlatform` Process. Tomcat can have memory issue on `reload` by war/jar files. So I prefer to take `tomcat` down and then take it up again. This is what we do in the Linux box we have. Take one instance of `tomcat` every time and wait till a specific url is available again before we take down the other one

**Comment by davidebbo** [comment]
@rramachand21 knows more than I do about tomcat. Ranjith, maybe touch web.config causes a restart?

But note that if you don't want any down time, the best approach is to rely on [slots](https://azure.microsoft.com/en-us/documentation/articles/web-sites-staged-publishing/).

**Comment by oak-tree** [comment]
Yeah, I like the idea of `slots`. But We have the same issue there as `tomcat` takes time to do `boot`, So we mark the `Always up` feature at `Webapp`. Then for configuration the `slots` the best will be `pull` from `git`; `take down` the `staging` slot; launching it up again; then when a specific url is a live do a `autoswap`. But I did not find how to do that it :)

**Comment by davidebbo** [comment]
[this post](http://ruslany.net/2015/09/how-to-warm-up-azure-web-app-during-deployment-slots-swap/) has good info on warming up slots.

**Comment by oak-tree** [comment]
Thanks I'll check it out. Any news if `touch` on `web.config` triggers `restart`?

**Comment by oak-tree** [comment]
Thanks for the information. I have another question related to the `deploying process`. I followed the blog link you posted before. We have now two slots : `production` and `staging`. Only the `staging` connected to `git - bitbucket`. 
What we are trying to achieve is the following : 


1 . push code to repo 
2. the `staging` will automaticly detect a change and pull changes 
3. it will stop tomcat server
4. pull the changes 
5. rerun tomcat
6. when its ready do a swap

It seems that for 3,4,5 we just go for `touch web.config`. But for some reason not all of the time the wepbapp is aware of change in the repo. I cannot put my finger on what is the cause but sometimes it capture `repo` update and sometimes is not

Any ideas how this subject?
Thanks

**Comment by davidebbo** [comment]
Can you clarify what you mean by "not all of the time the wepbapp is aware of change in the repo"? Are you saying that you push to bitbucket and nothing at all happens?

**Comment by oak-tree** [comment]
> Are you saying that you push to bitbucket and nothing at all happens?
Exactly, sometimes something happens and sometime nothing and then I have to go to `azure portal` and click on `sync` but this does not trigger autoswap

**Comment by davidebbo** [comment]
In that case, it sounds entirely unrelated to the core thing discussed here, which is about restarting the App during deployment. If so, why ask as part of this issue?

**Comment by oak-tree** [comment]
you right. I'll open another one

**Comment by dustinvanbuskirk** [comment]
I've come across an issue where some file changes are not picked up when kudu deployment is being done.  This was the case using the kudu automated deployment and a new manual deployment I set up.  The only way some files are picked up are with a WebApp restart.  

I'd like to know if a WebApp restart from the deployment script is possible..  I'm having a very difficult time locating any information on this in the documentation.

**Comment by davidebbo** [comment]
All Kudu itself does it deploy files to the wwwroot folder. Depending on the runtime (.net, php, ...), this may or may not cause a restart. But the key point is that it's not a Kudu concern, but a runtime concern.

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
