### ISSUE TITLE
Override a specificare subdirectory

### ISSUE THREAD

**Issue by fleed** [projectkudu/kudu#2102]
Is It possibile to deploy a specific subdirectory?

I'd like to deploy my asp.net website as "master" deployment when there are major changes, and be able to update separately a folder with static content that changes more often. Is that possible?

**Comment by davidebbo** [comment]
Do you mean that you have two separate git repos that you want to deploy to the same Web App? If so, that is not currently supported.

**Comment by fleed** [comment]
Hi David

Yes, basically I have a repo containing the website and a repo containing some documents that I'm processing with docx to generate a (static) documentation website. This generated content should be copied into a directory under my website.
So actually I don't need to deploy an entire repo, but just copy some files from a different repo to the website.

Isn't there any other option for this copy operation?

**Comment by davidebbo** [comment]
Only one repo can be set up for continuous deployment. But there are various options for bringing in arbitrary files into the WebApp outside of git deployment: FTP, Kudu fvs and zip APIs, WebDeploy.

**Comment by fleed** [comment]
Thanks, this answers my question.
