### ISSUE TITLE
Changes commited but deployment failing. Issue with Kudusync

### ISSUE THREAD

**Issue by jjkilpatrick** [projectkudu/kudu#2104]
Hi all,

Having trouble deploying as the title suggests. I've checked both Kudu.Core > Scripts > kudusync && Kudu.Core > Scripts > kudusync.cmd. Both paths are set.

Here is my error message:

```
remote: '"KuduSync.NET.exe"' is not recognized as an internal or external command,
remote: operable program or batch file.
remote: Handling node.js deployment.
remote: Failed exitCode=1, command="kudusync" -v 50 -f "C:\Code\kudu\apps\hello-node\site\repository" -t "C:\Code\kudu\apps\hello-node\site\wwwroot" -n "C:\Co  de\kudu\apps\hello-node\site\deployments\13850cf660677168148e1310921d0eed6b9c7791\manifest" -p "C:\Code\kudu\Kudu.Services.Web\bin\Scripts\firstDeploymentMani  fest" -i ".git;.hg;.deployment;deploy.cmd"
remote: An error has occurred during web site deployment.
```

remote: Error - Changes committed to remote repository but deployment to website failed.

Any help would be much appreciated, Thanks

**Comment by davidebbo** [comment]
I think the build sequence has some issue that causes it not to build kudusync when building from VS. Can you try running build.cmd from the root of the repo? You should end up with kudusync.net.exe under Kudu.Services.Web\bin\Scripts.

**Comment by jjkilpatrick** [comment]
@davidebbo That fixed the issue, thank you very much!

**Comment by davidebbo** [comment]
I'll keep it open, as it's really something we should fix.

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
