### ISSUE TITLE
OAuth error configuring SSH private bitbucket repo continuous deployment

### ISSUE THREAD

**Issue by rob3c** [projectkudu/kudu#2105]
Hi, I'm trying to set up continuous integration using a private bitbucket repository.

Unfortunately, the built-in bitbucket integration is far too intrusive in its requested access during oauth registration: it wants full access to all account info, all team repos, members, and settings with full admin access - sheesh!

Anyway, I want to set it up manually to give limited read-only access to a single repo. Therefore, I've tried to follow the instructions here, but it's not working:

https://github.com/projectkudu/kudu/wiki/Continuous-deployment

Here's what I tried:
  1. I enabled `Local Git Repository` in the azure portal, which I can successfully push to directly from my local machine.
  2. Then, I pulled the SSH public key from the azure scm URL and added it as a deployment key in the private bitbucket repo.
  3. Next, I manually set up a webhook in the bitbucket repo pointing to the scm deploy url including credentials.
  4. Then I tried setting the repoUrl property in the `sourcecontrols/web` config (via https://resources.azure.com) as described  to the ssh git repo URL.

Step 4 failed with this error when clicking PUT to save changes:

```
{
  "Code": "NotFound",
  "Message": "Cannot find SourceControlToken with name Bitbucket.",
  "Target": null,
  "Details": [
    {
      "Message": "Cannot find SourceControlToken with name Bitbucket."
    },
    {
      "Code": "NotFound"
    },
    {
      "ErrorEntity": {
        "Code": "NotFound",
        "Message": "Cannot find SourceControlToken with name Bitbucket.",
        "ExtendedCode": "51004",
        "MessageTemplate": "Cannot find {0} with name {1}.",
        "Parameters": [
          "SourceControlToken",
          "Bitbucket"
        ],
        "InnerErrors": null
      }
    }
  ],
  "Innererror": null
}
```

Since that didn't work, I tried changing the deployment source in the azure portal to `External Repository`. However, even though the SSH key is already set up as a deployment key on the bitbucket side, when I tried entering my git repo SSH clone URL, it gave me the same token error message as above when I hit OK.

It looks like kudu notices it's for a bitbucket repo from the url and expects an oauth token to be available in `providers/Microsoft.Web/sourcecontrols/Bitbucket` no matter what, even though it shouldn't need it because I'm setting everything up manually for SSH access.

Is this a bug, or am I just not configuring things correctly for this use case?

Thanks in advance,
Robert

**Comment by davidebbo** [comment]
Try just doing the first 3 steps you list, and skip 4th one (i.e. don't set `repoUrl`).

**Comment by rob3c** [comment]
Thanks for the quick response - that totally worked! Not configuring the bitbucket repo url on the azure side is a bit counterintuitive, but I now see that the webhook payload includes the info. Maybe that could be clarified in the docs?

Unfortunately, I didn't see that it was working right away because I was watching the logstream and expecting deployment activity like there is when pushing directly to azure from a local repo. However, I saw that it did eventually update the `Deployment Source` blade in the portal. In any case, the new app got deployed quickly after pushing to bitbucket :)

**Comment by davidebbo** [comment]
Glad that worked!

The doc lists three alternative workflows:

- Portal
- Resource Explorer
- Manual

So your initial attempt mostly followed the manual steps, but then also added the Resource Explorer steps, which were meant to be exclusive. If you have specific wording suggestions that you think would have made it clearer, I'm happy to edit :)

**Comment by rob3c** [comment]
You're right - the Manual steps would've worked if followed precisely and without wondering how azure would magically know where to pull from. I was definitely over-thinking it! :)

In my defense, the Resource Explorer steps right above it indicated that you have to set the repoUrl property for Azure to know the repo location. As we know, docs aren't always perfectly up-to-date, so given that and the fact that build systems often require the repo url to be configured on the pull side even with url triggers, it seemed to me that a _manual_ config would also require telling azure its location somehow.

Since the article "discusses what happens under the cover", a simple comment like this might help dispell the magic for others like me in the future who know the repo url info has to come from somewhere but don't know the webhook internals (I had to check the bitbucket request history and look at payload details to see that it was there):
```
Unlike the Resource Explorer case above, the repoUrl property should not be changed when configuring manually. The webhook payload should already contain the remote repository URL.
```
Thanks again for helping so quickly!

**Comment by davidebbo** [comment]
Thanks, I added that as a note in the beginning of the 'manual' section.
