### ISSUE TITLE
WEBSITE_SITE_MODE Environment Variable

### ISSUE THREAD

**Issue by stevenfollis** [projectkudu/kudu#2106]
Hello, 

Was digging into the environment variables exposed by Kudu [per the wiki](https://github.com/projectkudu/kudu/wiki/Azure-runtime-environment) and am unable to detect or use `WEBSITE_SITE_MODE` from Node.js.  

#1180 makes it look like `WEBSITE_SITE_MODE` was deprecated in favor of `WEBSITE_SKU` but wanted to double check.  Might be as simple as a wiki update if the former is no longer available as an environment variable. 

Worth noting that `WEBSITE_COMPUTE_MODE` works as expected.

Thanks!

**Comment by davidebbo** [comment]
Indeed, it's gone. I've yanked it from the wiki. Thanks for raising this!
