### ISSUE TITLE
Deployment Failed: Changes in submodules

### ISSUE THREAD

**Issue by deevus** [projectkudu/kudu#2108]
Activity Log:

```
error: Your local changes to the following files would be overwritten by checkout:
    ...
Please, commit your changes or stash them before you can switch branches.
Aborting
error: Your local changes to the following files would be overwritten by checkout:
    package.json
Please, commit your changes or stash them before you can switch branches.
Aborting
Unable to checkout '...' in submodule path '...'
Unable to checkout '...' in submodule path '...'

D:\Program Files (x86)\Git\cmd\git.exe submodule update --init --recursive
```

There were no changes made to the files via the kudu console, and this has come up multiple times across multiple projects. My interim solution is to log into kudu console and run `git submodule foreach git reset head --hard` from the `repository` directory.

**Comment by davidebbo** [comment]
I wonder if we just need to pass a `--force` to the `git submodule update` command that we run (code [here](https://github.com/projectkudu/kudu/blob/ecf0d7e8ebb84a724dc05316cf6975cd74ba50a1/Kudu.Core/SourceControl/Git/GitExeRepository.cs#L348)).

Do you think that would cover it?

**Comment by deevus** [comment]
I just tested that locally and it seems to do the trick

**Comment by davidebbo** [comment]
Great, that should be a pretty simple fix. @watashiSHUN do you want to take this? It's literally just about adding this one flag to the line above.

**Comment by davidebbo** [comment]
This fix is now deployed. @deevus can you please verify? Thanks!

**Comment by deevus** [comment]
@davidebbo If it happens again I'll be sure to let you know. Thanks David.
