### ISSUE TITLE
[Node.js] Application is not restarting after node_modules deployment

### ISSUE THREAD

**Issue by yvele** [projectkudu/kudu#2109]
When only changes are made within the root node_modules folder, files are deployed but the application is not restarted.

To force restart of the application I added a final step to my deploy.sh :

```bash
touch "$DEPLOYMENT_TARGET/host.json"
```

It's working but it looks kind of a hack.

1. Why is kudu not watching for changes within node_modules folder? Should kudu watch node_modules?
2. Is there a way to restart the application within my deploy script? (see [this question](https://www.bountysource.com/issues/36658865-is-it-possible-to-trigger-restart-for-httpplatfrom-via-kudu-deployment-script))

-----

Context :
- Using **Azure Function** with **Node.js**
- Building my application on my own CI machine : The builds already includes all dependencies in node_modules
- The build is deployed on Azure with git
- Default deploy strict is making an `npm install --production` and because I already have all my dependencies in ma build, I made a custom deploy script that skips the `npm install`

My structure looks like :

```none
function1
    function.json
    index.js
function2
    function.json
    index.js
.deployment
deploy.sh
host.json
package.json
```

**Comment by davidebbo** [comment]
> Why is kudu not watching for changes within node_modules folder? Should kudu watch node_modules?

I think it's important to distinguish between the deployment and the runtime of the app. Kudu's only involvement is to deploy the app, i.e. to get all the files where they belong. But it has no involvement at all in *running* the app. It's iisnode that runs the app, regardless of how it was deployed (e.g. you could use FTP).

> Is there a way to restart the application within my deploy script?

Everything Kudu does is file based, so the only channel is has to restart a site is to modify a file that would trigger a restart. I believe that Kudu by default ends up touching web.config at the end, which should restart node. You can try manually touching it in Kudu console to check this.

Not a complete answer, but hopefully some helpful context :)

**Comment by davidebbo** [comment]
Oh, I just realized that your question relates to Azure Functions and not a plain Node site. The part about Kudu not being involved in the runtime is still true, but the iisnode part is not relevant.

So the issue is really about the behavior of the Function Runtime, and how it handles change notifications. Could you open an issue on https://github.com/Azure/azure-webjobs-sdk-script/ instead, so it's tracked in the right place? Thanks!

**Comment by yvele** [comment]
Allright thank you for your reply @davidebbo (I was actually hesitating between here and webjobs-sdk on where to open the issue :bowtie:).
I "moved" the issue here : https://github.com/Azure/azure-webjobs-sdk-script/issues/608
