### ISSUE TITLE
Random delay is not that random in c2055c6 as fix to #2090

### ISSUE THREAD

**Issue by etm-admin** [projectkudu/kudu#2110]
Since the functions are triggered very close in time Random may produce same value, hence making this feature meaningless. 

I'd recommend using a static one with a lock so you don't have this issue...

#2107 

`
private static readonly Random random = new Random();
private static readonly object syncLock = new object();
public static int RandomNumber(int max)
{
    lock(syncLock) { return random.Next(max);}
}`

**Comment by davidebbo** [comment]
Related to #2090. But I don't quite follow. Each site will get a different random value, so statistically it should be evenly distributed over the defined range. Please give the feature a try once it's deployed (in next week or two), and we can take it from there.

Locking is not an option as each deployment runs in a different sandbox and they have no shared state.

**Comment by etm-admin** [comment]
They will be triggered at the same time or in very close times and Random() is dependent on time. Ok locking does not make sense in that case. 

I suggest using something specific unique to that instance as the seed e.g. `Random(instanceId.GetHashCode()).`

**Comment by davidebbo** [comment]
Sorry, I still don't follow. Why would they be triggered very close in time, unless you set the delay to some very small number? If you set the max delay to say 10 minutes (600s), then the deployment start times will be distributed over that whole period, greatly reducing the concurrency. And the larger the delay, the lesser the concurrency.

**Comment by etm-admin** [comment]
Deployment trigger happens at the same time from git to e.g. 20 sites. Then random number is generated with same value. So it will generate same delay, which defeats the purpose.

**Comment by davidebbo** [comment]
I see, you're talking about the *seed* being potentially the same. It's unlikely, but I agree we can fix that by using something like `HTTP_HOST`.

**Comment by etm-admin** [comment]
Yes that would be definitely better. Thanks a lot for the quick responses!
