### ISSUE TITLE
Wiki: Customizing deployments - Project -> PROJECT

### ISSUE THREAD

**Issue by lanwin** [projectkudu/kudu#2114]
I found no simple way of sending an pullrequest, so I raise an issue instead.

On the WikiPage "Customizing deployments" the App Setting for Projects need to be upper case. Otherwise this will not work. In the last paragraph it should be "Project" -> "PROJECT".

**Comment by davidebbo** [comment]
Hmmm, this is not supposed to be case sensitive, so that's a bit odd. In any case, I made the wiki change.
