### ISSUE TITLE
Deploying ASP.NET Core App to Azure App Service

### ISSUE THREAD

**Issue by mmillican** [projectkudu/kudu#2115]
I am attempting to get a NETCore 1.0 app running on Azure web sites, but having issues. I believe it is deployment related but can't be sure.

The app deploys fine via VS Publish, but when visiting in the browser I get a `HTTP 500` error.  Looking in the streaming logs via Kudu, I see that it's referring to potential issues with `web.config` file permissions, but does not show much more than that.

Here's part of the error that I believe is relevant

> Ensure that the NTFS permissions for the web.config file are correct and allow access to the 
Web server's machine account.</li> 	<li>Check the event logs to see if any additional information 
was logged.</li> 	<li>Verify the permissions for the DLL.</li> 	<li>Install the .NET Extensibility 
feature if the request is mapped to a managed handler.</li> 	<li>Create a tracing rule to track 
failed requests for this HTTP status code. For more information about creating a tracing rule for failed requests
...

The web.config:

```
<!-- /site/wwwroot/web.config --> 

<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <!--
    Configure your application settings in appsettings.json. Learn more at http://go.microsoft.com/fwlink/?LinkId=786380
  -->
  <system.webServer>
    <handlers>
      <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModule" resourceType="Unspecified" />
    </handlers>
    <aspNetCore processPath="dotnet" arguments=".\MattMillican.dll" stdoutLogEnabled="false" stdoutLogFile="\\?\%home%\LogFiles\stdout" forwardWindowsAuthToken="false" />
  </system.webServer>
</configuration>
<!--ProjectGuid: 299e20b7-17c9-42fc-aa86-61da7719de9d-->
```

I'm able to deploy older versions of core apps to Azure with no problem.

**Comment by davidebbo** [comment]
Can you clarify how you are deploying your app? Are you using msdeploy or git? If you are using msdeploy (i.e. deploy directly from VS to Azure), then you are not using Kudu.

**Comment by mmillican** [comment]
Oh yes, I am using direct from VS.  Let me try setting up from Git.

Another thing I'm noticing is that `appsettings.Production.json` is not being deployed either.

**Comment by davidebbo** [comment]
I don't think switching to git is the right step forward. Git deployment can have *additional* issues compared to deploying straight from VS. So if VS deployment does not work, we need to investigate this as a .NET Core runtime issue and not a deployment issue.

Closing here since we've established it is not Kudu related.

**Comment by mmillican** [comment]
@davidebbo Should I create this issue elsewhere then?

**Comment by davidebbo** [comment]
If you suspect an Azure Web App issue, then the Web App [forum](https://social.msdn.microsoft.com/Forums/azure/en-US/home?forum=windowsazurewebsitespreview) is your best bet. And point the Core guys to it, as they may have more context.

I also suggest first verifying that a vanilla Core app works for you (definitely should), which then gives you a baseline to compare against your specific non-working app.
