### ISSUE TITLE
Add support for creating a Django site

### ISSUE THREAD

**Issue by glennblock** [projectkudu/kudu#212]
Websites now supports the ability to plug in Django: https://www.windowsazure.com/en-us/develop/python/tutorials/web-sites-with-django/

Today it requires a bunch of manual steps. Similar to the work we did on node it would be great if support detecting a Django app and then just do the right thing on the server rather than pushing it to the user.

**Comment by letanloc1998** [comment]
Could you deploy Django on Azure with Windows OS and Python 3.x? I can't deploy it ~~

**Comment by jvano** [comment]
Hi

Kudu will continue to run in Azure App Service. However, this repo will no longer be maintained.
If the problem persists and is related to running on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
