### ISSUE TITLE
Clearing up the Temp folder before deployment

### ISSUE THREAD

**Issue by kunjee17** [projectkudu/kudu#2122]
Hi, 

I have restructured the project. And move one namespace from one project to another project. And then delete the project file. Now, temp folder is having old dll too. So, facing ambiguity for class as same class now exist in two different directory. 

I tried to delete it but it but no success. It is crashing the application right now and I don't know how to solve it. 

Here is image of what error is coming
![tempfolderissue](https://cloud.githubusercontent.com/assets/960605/18226505/24744080-7229-11e6-84fc-5239c3d664cd.PNG)

Please let me know if any further details are required.

**Comment by davidebbo** [comment]
Try restarting the site, which completely clears the temp folder.

**Comment by kunjee17** [comment]
@davidebbo hi, thanks for quick reply. Restart do work. Closing this issue for now. One more question doesn't new deployment clear's temp and restart the application?

**Comment by davidebbo** [comment]
New deployment may restart the App Domain if bin files are modified, but temp is not cleaned. However, that normally does not trigger this kind of issues, so something else might have been going on.
