### ISSUE TITLE
Log start and shutdown kudu event to MDS

### ISSUE THREAD

**Issue by suwatch** [projectkudu/kudu#2123]
In addition to file system, we should also log Kudu startup/shutdown event to MDS. 
- There was a case we missed these events in log files (could be file system issue).
- Facilitate the investigation when looking from logging alone.

**Comment by mathewc** [comment]
I think we should also log detailed info about our search for WebJob folders, and the number of jobs found. E.g. in the above investigation, presumably we'd see a log entry "0 continuous jobs found" which would reveal the issue.

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
