### ISSUE TITLE
Job fails to stop

### ISSUE THREAD

**Issue by markanewman** [projectkudu/kudu#2125]
Cross posted from  Azure/azure-webjobs-sdk#809 based on advice from @davidebbo

I have several always on continuous WebJobs. During maintenance windows we stop the WebJobs to prevent them from reporting our other services are down and they can't connect. Depending on how long they have been running sometimes they will error out and stick in the "Disabling" status. When I look at the logs, I see the below. The only work around I have found is kill the Kudu process in process explorer, let that recycle the jobs, then stop them normally.

In the below example we chose a time when there should not have been any incoming processing.

[08/31/2016 20:41:20 > 0991c1: SYS INFO] WebJob is still running
[09/01/2016 04:51:28 > 0991c1: SYS INFO] WebJob is still running
[09/01/2016 11:17:39 > 0991c1: SYS INFO] Status changed to Disabling
[09/01/2016 11:21:00 > 0991c1: SYS ERR ] Job failed due to exit code -1

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
