### ISSUE TITLE
Deployment error : xxx appears as both a file and a directory

### ISSUE THREAD

**Issue by yvele** [projectkudu/kudu#2126]
### Context

I'm using **local git** to deploy an **Azure function** (~0.5)  application using **node.js**.
### Problem

During local git deployment I get the following error :

> 'foo/bar.js' appears as both a file and a directory
### Reproducing the problem
1. Commit a 'foo' folder as a symlink (pointing somewhere crazy like `../../../../../bar`)
2. Publish and deploy the application with the symlink (I'm using `git push ---force`)
3. Edit `foo`folder and make it a real folder with a `foo/bar.js` file inside (it's not anymore a symlink)
4. Publish and deploy the application with the "real" folder (I'm using `git push ---force`)

Deployment will crash

> 'foo/bar.js' appears as both a file and a directory

PS: Does the error comes from this [libgit2 line](https://github.com/libgit2/libgit2/blob/ce54e77c70b5d0429a7d8a18dd31696f668ef3d0/src/index.c#L1146)?
### Known workaround

Connect within Kudu Console to manually delete folders having problems, and redeploy everything.

PS: Trying deploying multiple times doesn't work.
### Extra informations

I have a custom deployment script. My deployment script is based on **KUDU Deployment Script Version: 1.0.8**, here is the end of the file :

``` bash
##################################################################################################################################
# Deployment
# ----------

echo Handling node.js deployment with custom script.

#1. KuduSync
if [[ "$IN_PLACE_DEPLOYMENT" -ne "1" ]]; then
  "$KUDU_SYNC_CMD" -v 50 -f "$DEPLOYMENT_SOURCE" -t "$DEPLOYMENT_TARGET" -n "$NEXT_MANIFEST_PATH" -p "$PREVIOUS_MANIFEST_PATH" -i ".git;.hg;.deployment;deploy.sh"
  exitWithMessageOnError "Kudu Sync failed"
fi

#2. Select node version
selectNodeVersion

#3. Retart application (hack)
touch "$DEPLOYMENT_TARGET/host.json"

# X. Install npm packages
# if [ -e "$DEPLOYMENT_TARGET/package.json" ]; then
#   cd "$DEPLOYMENT_TARGET"
#   eval $NPM_CMD install --production
#   exitWithMessageOnError "npm failed"
#   cd - > /dev/null
# fi

##################################################################################################################################
echo "Finished successfully."
```

I'm only disabling node installation (as my repo is already shipped with dependencies) and touching host.json to fix https://github.com/Azure/azure-webjobs-sdk-script/issues/608

**Comment by watashiSHUN** [comment]
Hello, at step 3, what do you mean by "Edit foofolder and make it a real folder with a foo/bar.js file inside (it's not anymore a symlink)"

if you `rm foo` first, and then create a brand new folder `mkdir foo` and a "bar.js" inside of it `touch foo/bar.js`, `git` should consider it as simple file delete and create operation

**Comment by watashiSHUN** [comment]
Hello, while I am investigating...can you tell me how do you use this "symlink" file? if I understand correctly  it no longer behaves like a folder once you pushed it to azure, are you reading the content of `foo` as plain text in your code?

**Comment by watashiSHUN** [comment]
it seems like `libgit2` library follows default behavior when updating the index, which is 

![capture](https://cloud.githubusercontent.com/assets/6531400/18496794/bb726cc6-79dd-11e6-9683-a6b4f564db29.PNG)

you can **disable** `libgit2` by changing kudu settings, add `SCM_USE_LIBGIT2SHARP_REPOSITORY->0` entry to **App settings** in **azure portal**

![capture1](https://cloud.githubusercontent.com/assets/6531400/18496851/642df9e8-79de-11e6-950d-b57dfb08316c.PNG)

Before an actual fix comes out, this work around will allow you to change a file to a folder with `git`

**Comment by yvele** [comment]
@watashiSHUN I pushed the symlink inadvertently. I only wanted to overwrite the symlink by pushing the "real" folder

**Comment by watashiSHUN** [comment]
@yvele Can you try changing settings as I mentioned above, it should make your `git push` successful and you don't need to delete git repo in kudu anymore.

**Comment by yvele** [comment]
@watashiSHUN Thanks for your response. But I'm sorry I don't have time yet to create a dummy Azure Function + changing settings + pushing a symlink + overwrite it.. :confused: (symlink is not a real case scenario for me.. that was just a punctual mistake).

PS: If I can disable `libgit2` and expect everything to for fine (and even better).. What is `libgit2` usefull for?

**Comment by davidebbo** [comment]
libgit2 is a library that avoids launching git out of proc for every single command, so it's more efficient. But things should still work without it,

**Comment by yvele** [comment]
@davidebbo Thanks.. Now I understand 👍
