### ISSUE TITLE
Deploying WebJobs from TFS to App_Data causes DeploymentClientServerException

### ISSUE THREAD

**Issue by philmh-isams** [projectkudu/kudu#2127]
I am seeing the follow exception when deploying to Azure.

```
An error was encountered when processing operation 'Delete Directory' on 'D:\home\site\wwwroot\App_Data\jobs'.
```

It is one I have seen before and the belief is that WebJobs are running so there is a file lock which prevents this folder from being deleted.

I can set the DoNotDelete flag as a workaround for now, but I was wondering how I can release the handle of this folder so it can be deleted. Any ideas how to stop the WebJobs?

We deploy an API to a Azure web service and execute a "stop" beforehand, and if I redeploy a failed release, it works the second time.

Any guidance would be much appreciated.

**Comment by davidebbo** [comment]
You can try setting `WEBJOBS_STOPPED=1` is your Web Apps's App Settings. See https://github.com/projectkudu/kudu/wiki/Web-Jobs#configuration-settings

**Comment by philmh-isams** [comment]
I'll give that a whirl and let you know the outcome - thanks.

**Comment by philmh-isams** [comment]
@davidebbo Unfortunately, I still get the intermittent problem. One release works, the second release fails. I will continue to investigate and let you know if I find out what is causing this exception in our environment here.

**Comment by davidebbo** [comment]
You can also try [fully stopping the site](https://github.com/projectkudu/kudu/wiki/Full-stopping-a-Web-App). However, once stopped you won't be able to deploy via git or msdeploy. And once you restart, maybe the lock will be taken again. So not sure it'll help, but something to play with.

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
