### ISSUE TITLE
Ensure file system errors are handled correctly on all WebJobs codepaths

### ISSUE THREAD

**Issue by mathewc** [projectkudu/kudu#2129]
We had an instance of a continuous WebJob that mysteriously failed to start up when the instance started up. The theory is that there might be a bug in the startup scan logic for WebJobs. We need to ensure that whenever file system operations fail we fail startup.

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
