### ISSUE TITLE
NVM Support

### ISSUE THREAD

**Issue by deevus** [projectkudu/kudu#2130]
Hi guys

It would be great if kudu supported nvm. I use https://github.com/coreybutler/nvm-windows/ locally and it works a charm. 

I think that the same workflow that people use would work now as well, but where you could support more versions of node sooner. 

Thoughts?

**Comment by ramijarrar** [comment]
Is this being considered yet? 

The current selection of Node versions is very limited at best and often lags behind the latest releases (which can contain important bug fixes/patches).

**Comment by davidebbo** [comment]
> The current selection of Node versions is very limited at best and often lags behind the latest releases (which can contain important bug fixes/patches).

Can you clarify those comments? We almost always have the latest versions available (currently 6.9.1 & 7.1.0), and the version selection is quite large. Maybe you are looking in the wrong place?

**Comment by ramijarrar** [comment]
Sorry I was actually referring to latest versions across release cycles: e.g 4.6.2, 5.11.0, 0.10.48, 0.12.17, etc.

And in terms of overall selection, I'd still consider 15% (58/395) to be quite limited when constrained by dependencies/frameworks (though honestly not bad given that it is a manual process)

**Comment by yaserjarrar** [comment]
As an example demonstrating the need for versions across release cycles, the latest version of Meteor is using node v4.6.2 which is not available.

**Comment by davidebbo** [comment]
Is nvm something that can be just copied into an app and run from there, or does it it machine install? Generally, the rule in the Azure Web Apps sandbox is that you can't do anything that is machine impactful. You can only bring files, either under `d:\home` (persisted) or `d:\local` (temp). So depending on how it works, using nvm may or may not be feasible.

**Comment by ramijarrar** [comment]
Nope. It will definitely need machine install (otherwise we could get this done with a custom deploy script)

**Comment by davidebbo** [comment]
Do you know specifically what it needs that needs to be machine level? e.g. does it need to update the registry or system files? On the surface, that seems unlikely for a tool like this. My guess is that they ship it as an MSI, but that it doesn't actually need anything machine level and would probably run from xcopied files.

The bar to install something on the VM is quite high, so I'd like to exhaust alternatives first.

**Comment by deevus** [comment]
It doesn't need machine install. It can exist on the filesystem no problem.
It does however require administrator access to "install" a version of
node. I think that's because it needs to change the system path

**Comment by davidebbo** [comment]
That's definitely problematic, as that means that even if we preinstalled nvm on the VM, it wouldn't be able to *run* from the sandbox, making it useless.

But I'm surprised that it needs to change the machine level system path. I don't know anything about it, but on the surface I'd think what it really needs to do is:

- Download some files of the cloud
- Set the PATH & environment in the current shell (and **not** machine level), allowing Node to then be run in that shell.

**Comment by deevus** [comment]
Perhaps there's a way to run it without privileges.

**Comment by davidebbo** [comment]
I'll try playing around with that thing.

**Comment by ramijarrar** [comment]
From the [README](https://github.com/coreybutler/nvm-windows#whats-the-big-difference):

> NVM for Windows maintains a single symlink that is put in the system PATH during installation only. Switching to different versions of node is a matter of switching the symlink target.

It sounds like privileges are just needed for the installation.

**Comment by davidebbo** [comment]
I think we can bypass that part by simply not using the symlink, and just putting things on the PATH.

**Comment by davidebbo** [comment]
Ok, so that seems to work. Try the following steps:

- Download https://github.com/coreybutler/nvm-windows/releases/download/1.1.1/nvm-noinstall.zip
- In Kudu console, create a d:\home\nvm folder and unzip nvm-noinstall.zip into it (e.g. using Kudu drag and drop)
- In that same folder, create a batch file called nvminstall.cmd that contains this:

```
if "%1" == "" goto usage
set NVM_HOME=%~dp0%

(echo root: %NVM_HOME% && echo arch: 32 && echo proxy: none) > %NVM_HOME%\settings.txt

nvm install %1

set path=%NVM_HOME%v%1;%path%

echo Current Node on the path is now:
node --version

goto :eof
:usage
echo Usage: e.g. nvminst 4.6.2
```

Node to install and use a version of Node, run something like `nvminstall 4.6.2`. Output should look like this the first time (node that installing npm takes a little while):

```
D:\home\nvm>nvminstall 4.6.2
Downloading node.js version 4.6.2 (64-bit)... Complete
Creating D:\home\nvm\\temp

Downloading npm version 2.15.11... Complete
Installing npm v2.15.11...

Installation complete. If you want to use this version, type

nvm use 4.6.2
Current Node on the path is now:
v6.9.1
```

And that's it, node and matching npm are on the path and usable.

It should be relatively easy for someone to polish this and turn this into a site extension that adds the nvm path to the PATH (using [this technique](https://github.com/projectkudu/kudu/wiki/Xdt-transform-samples#adding-environment-variables), so that the only thing you need to do in your Kudu script is run `nvminstall 4.6.2`.

**Comment by ramijarrar** [comment]
Sounds really good. Will definitely try setting this up with a custom deploy (we maintain the [meteor-azure](https://github.com/talos-code/meteor-azure) script) and let you know how that goes.

**Comment by davidebbo** [comment]
The script ends up downloading 64 bit node even though I set it to 32 bit. Not sure why but it's probably a simple mistake somewhere.

@ramijarrar sounds good, please update with any follow up findings.

**Comment by ramijarrar** [comment]
You have to use "4.6.2 32" (otherwise it assumes 64 bit)

**Comment by davidebbo** [comment]
Ah, I see. I tried it and confirmed! I expected that having `arch: 32` in the `settings.txt` would take care of that.

**Comment by ramijarrar** [comment]
Getting this error when trying to update the NPM version:

```bash
npm ERR! tar.unpack untar error D:\local\AppData\npm-cache\npm\4.0.3\package.tgz 
npm ERR! Windows_NT 6.2.9200 npm ERR! argv "node" "D:\\home\\nvm\\v4.6.2\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "npm@latest"
npm ERR! node v0.10.28
npm ERR! npm v2.15.11
npm ERR! path D:\Program Files (x86)\nodejs\0.10.28\node_modules
npm ERR! code EPERM 

npm ERR!   errno 50
npm ERR! Error: EPERM, mkdir 'D:\Program Files (x86)\nodejs\0.10.28\node_modules'
npm ERR!  { [Error: EPERM, mkdir 'D:\Program Files (x86)\nodejs\0.10.28\node_modules']
npm ERR!   errno: 50, npm ERR! code: 'EPERM', 
npm ERR!   path: 'D:\\Program Files (x86)\\nodejs\\0.10.28\\node_modules',
npm ERR!   fstream_type: 'Directory',
npm ERR!   fstream_path: 'D:\\Program Files (x86)\\nodejs\\0.10.28\\node_modules\\npm',
npm ERR!   fstream_class: 'DirWriter',
npm ERR!   fstream_stack:
npm ERR!    [ 'D:\\home\\meteor-azure\\nvm\\v4.6.2\\node_modules\\npm\\node_modules\\fstream\\lib\\writer.js:171:25',
npm ERR!      'D:\\home\\meteor-azure\\nvm\\v4.6.2\\node_modules\\npm\\node_modules\\mkdirp\\index.js:47:53',
npm ERR!      'Object.oncomplete (fs.js:107:15)' ] }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.
```

**Comment by ramijarrar** [comment]
Getting errors relating to missing binaries: doesn't look like the app is being executed with the custom Node (I definitely have the correct version in path throughout the build process).

@davidebbo Any thoughts?

Here is the full trace for reference:
```
## There is an issue with `node-fibers` ##
`D:\home\site\wwwroot\programs\server\node_modules\fibers\bin\win32-ia32-undefined\fibers.node` is missing.

Try running this to fix the issue: D:\Program Files (x86)\nodejs\node.exe D:\home\site\wwwroot\programs\server\node_modules\fibers/build
Mon Dec 05 2016 10:10:46 GMT+0000 (Coordinated Universal Time): Application has thrown an uncaught exception and is terminated:
Error: Missing binary. See message above.
    at Object.<anonymous> (D:\home\site\wwwroot\programs\server\node_modules\fibers\fibers.js:20:8)
    at Module._compile (module.js:446:26)
    at Object..js (module.js:464:10)
    at Module.load (module.js:353:31)
    at Function._load (module.js:311:12)
    at Module.require (module.js:359:17)
    at require (module.js:375:17)
    at Object.<anonymous> (D:\home\site\wwwroot\programs\server\boot.js:1:75)
    at Module._compile (module.js:446:26)
    at Object..js (module.js:464:10)
Application has thrown an uncaught exception and is terminated:
Error: Missing binary. See message above.
    at Object.<anonymous> (D:\home\site\wwwroot\programs\server\node_modules\fibers\fibers.js:20:8)
    at Module._compile (module.js:446:26)
    at Object..js (module.js:464:10)
    at Module.load (module.js:353:31)
    at Function._load (module.js:311:12)
    at Module.require (module.js:359:17)
    at require (module.js:375:17)
    at Object.<anonymous> (D:\home\site\wwwroot\programs\server\boot.js:1:75)
    at Module._compile (module.js:446:26)
    at Object..js (module.js:464:10)
```

**Comment by davidebbo** [comment]
Right, it's only on the path during the build script, but that doesn't affect the runtime.

Try creating a file named `iisnode.yml` in your `D:\home\site\wwwroot` folder, with the following content (replacing with the real path to your node.exe):

    nodeProcessCommandLine: "D:\home\foo\bar\node.exe"

**Comment by ramijarrar** [comment]
Working now. Will let you know if I run into anything else.
