### ISSUE TITLE
64 bit dotnet.exe

### ISSUE THREAD

**Issue by michielpost** [projectkudu/kudu#2131]
I have a memory intensive webjob that uses dotnet.exe and needs to run in 64 bit mode. But the dotnet.exe currently installed by default is 32 bit.

Is there an easy way to change this to 64 bit? Or can the 64 bit dotnet.exe be installed by default?

**Comment by davidebbo** [comment]
Closing here, as Kudu is the deployment mechanism, while this is about the runtime. Short answer is that at this time we only have the 32 bit Core runtime. Can you open a feedback item on https://feedback.azure.com/forums/169385-web-sites/, and add the link here for tracking? Thanks!

**Comment by michielpost** [comment]
Ok thanks, posted it there:
https://feedback.azure.com/forums/169385-web-apps-formerly-websites/suggestions/16049980-install-64-bit-dotnet-exe-runtime
