### ISSUE TITLE
Disable WebJobs on Function apps

### ISSUE THREAD

**Issue by davidebbo** [projectkudu/kudu#2132]
There is little reason to use them in a Function app, and they add difficulties in term of metering usage.

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
