### ISSUE TITLE
Fail to deploy from GitHub Enterprise

### ISSUE THREAD

**Issue by helaili** [projectkudu/kudu#2135]
Trying to deploy an Azure web app from GitHub Enterprise following [those steps](https://nsamteladze.wordpress.com/2015/07/19/continuous-deployment-from-github-enterprise-repository-to-azure-web-app/). I've connected through the Kudu console and confirmed my deploy key is valid by manually triggering a git clone and checking the that GitHub reports usage of this key. 

Note that before I did the manual clone, the key was never used besides trying to trigger multiple deployments. 

Looking at `api/vfs/LogFiles/kudu/trace/2016-09-14T10-36-55_f61f4d_532_Background_POST_deploy_1s.xml`, I get the message `Request failed with status code: 401` 

Full log : 

```

<step title="BackgroundTrace" date="2016-09-14T10:36:55.330" instance="f61f4d" url="/deploy" method="POST">
<step title="Performing fetch based deployment" date="2016-09-14T10:36:55.346">
<step title="Creating temporary deployment" date="2016-09-14T10:36:55.346"/>
<!--  duration: 47ms  -->
<step title="LibGit2SharpRepository Fetch" date="2016-09-14T10:36:55.581"/>
<!--  duration: 176ms  -->
</step>
<!--  duration: 477ms  -->
<step title="Error occurred" date="2016-09-14T10:36:55.839" type="error" text="One or more errors occurred." stackTrace=" at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions) at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken) at Kudu.Services.FetchHandler.<>c__DisplayClass18_1.<PerformBackgroundDeployment>b__2() at Kudu.Contracts.Infrastructure.LockExtensions.TryLockOperation(IOperationLock lockObj, Action operation, String operationName, TimeSpan timeout) at Kudu.Contracts.Infrastructure.LockExtensions.LockOperation(IOperationLock lockObj, Action operation, String operationName, TimeSpan timeout) at Kudu.Services.FetchHandler.<>c__DisplayClass18_0.<PerformBackgroundDeployment>b__1()" innerText="Request failed with status code: 401" innerStackTrace=" at LibGit2Sharp.Core.Ensure.HandleError(Int32 result) at LibGit2Sharp.Core.Proxy.git_remote_fetch(RemoteSafeHandle remote, Signature signature, String logMessage) at LibGit2Sharp.Network.DoFetch(RemoteSafeHandle remoteHandle, FetchOptions options, Signature signature, String logMessage) at LibGit2Sharp.Network.Fetch(Remote remote, FetchOptions options, Signature signature, String logMessage) at Kudu.Core.SourceControl.Git.LibGit2SharpRepository.FetchWithoutConflict(String remoteUrl, String branchName) at Kudu.Services.ServiceHookHandlers.ServiceHookHandlerBase.Fetch(IRepository repository, DeploymentInfo deploymentInfo, String targetBranch, ILogger logger) at Kudu.Services.FetchHandler.<PerformDeployment>d__12.MoveNext()"/>
<!--  duration: 0ms  -->
</step>
<!--  duration: 509ms  -->
```

**Comment by davidebbo** [comment]
Hmmm, hard to tell what's going on from the error. But note that normally, you're not supposed to clone the repo yourself. Instead, you need to let Kudu do it, as it does it with some special steps. Can you try deleting your `d:\home\site\repository` folder and then deploy again?

If that doesn't help, try turning off LibGit2Sharp just to see if that makes a difference (maybe better error reporting). Just set this App Setting in portal: `SCM_USE_LIBGIT2SHARP_REPOSITORY=0`

**Comment by helaili** [comment]
I've only cloned the repo myself to check connectivity and usage of the deploy key. I did it in a temporary folder, so no harm here. 

Turning off LibGit2Sharp did bring more information : 
```
remote: Invalid username or password.\nfatal: Authentication failed for 'https://tmpghe.xxxxxx.com/helaili/SpidersFromMars/'\n\r\nD:\Program Files (x86)\Git\cmd\git.exe fetch origin --progress
``` 

So I'm quite puzzled by this https connection. It should use the git protocol over ssh in order to leverage the deploy key, right? 

In order to validate this auth problem assumption, I've fully opened my GitHub Enterprise (GHE) instance and made sure my repo was public. It then works. Enable private mode on GHE or change the repo visibility to private breaks it immediately.

**Comment by davidebbo** [comment]
Does your git repo use a submodule by a chance? That can raise interesting issues if the submodule itself is private.

Also, can you share your web app name, either directly or [indirectly](https://github.com/projectkudu/kudu/wiki/Reporting-your-site-name-without-posting-it-publicly)? This will help us investigate.

**Comment by helaili** [comment]
No submodule, it's a very basic web app. I'll invite you as collaborator so you can check for yourself. I could make it public but then the deploy would work.

**Comment by helaili** [comment]
I've also updated the [readme](https://github.com/helaili/SpidersFromMars) on the fork with the deployment trigger url in case it helps.

**Comment by davidebbo** [comment]
Thanks Alain. My guess would be that the issue actually has nothing to do with the specifics of your repo, but more with the way we process the notification from GitHub enterprise. i.e. you'd probably see the same thing with a trivial repo with just an index.html at the root.

One key line from your Kudu trace is (I've masked the real names):

    <step title="Executing external process" date="2016-09-16T08:09:08.416" type="process" path="git.exe" arguments="remote add -t master origin &quot;https://yourserver.com/YourOrg/YourRepo&quot;" />

Kudu is setting the remote to the https url, which is why it's not using ssh. But note that looking at your Web App, I don't see a `.ssh` folder under `d:\home`, and normally it should have been there. Is it right now in a state that you're able to clone your repo via ssh in a test folder? I wouldn't think that it would work without the ssh key in `d:\home\.ssh`.

**Comment by davidebbo** [comment]
Another thing worth trying: instead of setting the GitHub webhook to Kudu, try pointing it to a http://requestb.in/ URL, so you can capture exactly what GitHub Enterprise is sending. That should help debug what Kudu is doing with that payload. Normally, Kudu only uses ssh when the repo is marked as private. See code [here](https://github.com/projectkudu/kudu/blob/fc151b7bcdd6e186d6cc534456059c7f507b2fa1/Kudu.Services/ServiceHookHandlers/GitHubCompatHandler.cs#L65-L74).

**Comment by davidebbo** [comment]
@helaili my coworker @watashiSHUN will help out looking at this issue, so if you can also give him access to the repo that would be great (mostly for the info in the readme, as the rest of the repo is likely not relevant).

**Comment by helaili** [comment]
> Normally, Kudu only uses ssh when the repo is marked as private

That's it @davidebbo!!! This works perfectly with a private repo on GHE, but ironically not with a public repo. It's because my GHE has private mode enabled, which means it only allows authenticated access. 

What about adding a parameter to the deploy URL so one can force git protocol usage? 

By the way, thanks a ton for helping here!

**Comment by helaili** [comment]
Repos are still public in the sense that people not belonging to the org will see them. But you nevertheless need to be authentified, people without a login can't browse.

**Comment by davidebbo** [comment]
Understood. Maybe the simplest fix is to provide some new App Setting to override the detection. e.g. `SCM_FETCH_USING_SSH`.:

- If not set at all, we'd use our current detection based on the payload
- If set to 0 or 1, we'd honor that unconditionally

Does that sound like it would solve this scenario?

**Comment by davidebbo** [comment]
We're also looking for alternatives that don't involve a new flag. e.g. we could check if we have an ssh key set up, and always use ssh when we do.

**Comment by helaili** [comment]
GHE admins sometimes like to disable SSH, so keeping a flag might be useful, although leveraging SSH whenever possible is 👍

**Comment by davidebbo** [comment]
Ok, but if you disable ssh, you can always choose to not add the ssh key in Kudu (or yank it if already there).

Flag is more explicit, but the downside is that having too many flags is a bit dirty. I say we start with a smarter heuristic, and if we find that's not enough, we always have the option of adding an override switch.

**Comment by helaili** [comment]
Not sure I'm following you here. I didn't deploy any shh key in Kudu but rather deployed my app's Kudu public key (the one you get in `/api/sshkey?ensurePublicKey=1`) in my GitHub repo as a deploy key. 

Maybe you are suggesting to delete this one (from `/d/home/.ssh`) in case it had been generated by navigating to this `/api/sshkey?ensurePublicKey=1` URL? 

Anyway, there would still be a problem for GHE user with a public repo,  private mode on and SSH off. Would deployment credential be used then?

**Comment by davidebbo** [comment]
Right, by default, there is no ssh key at all, and the act of calling `/api/sshkey?ensurePublicKey=1` causes one to be generated if needed. Yes, you can delete it manually (e.g. via Kudu Console).

> Anyway, there would still be a problem for GHE user with a public repo, private mode on and SSH off. Would deployment credential be used then?

That is something we've never supported, so it would need additional thinking. Today, either we use https with no auth, or we use ssh. We don't have provision for using https and pass authentication headers.

**Comment by watashiSHUN** [comment]
@helaili , the new kudu is out, you don't need to set a flag or do anything, it should recognize private GHE with public repo and use SSH instead of HTTPS, please give it a try
