### ISSUE TITLE
WebJob is not always restarting when dlls are updated

### ISSUE THREAD

**Issue by brainded** [projectkudu/kudu#2136]
I am using Appveyor + WebDeploy to deploy my website and webjobs to my Azure Web Instance. Within the last few months I have seen some weird behavior from the WebJobs and it always ends up being the fact that the WebJob appears to not have restarted/been updated. This is not consistent as sometimes I will see the Webjob restart as it should.

The following are the logs for my WebJob from last night where I pushed a build and no record of it could be found:

[09/13/2016 23:52:39 > ebab45: INFO] Executed: 'Functions.ProcessWorkflow' (Succeeded)
[09/14/2016 01:09:26 > ebab45: SYS INFO] WebJob is still running
[09/14/2016 06:19:14 > ebab45: INFO] Executing: 'Functions.EvaluateWorkflowContacts' - Reason: 'New queue message detected on 'evaluateworkflowcontacts'.'
[09/14/2016 06:19:17 > ebab45: INFO] EvaluateWorkflowContacts for WorkflowId 1 complete!
[09/14/2016 06:19:17 > ebab45: INFO] Executed: 'Functions.EvaluateWorkflowContacts' (Succeeded)

**Deployment at 06:40 with no logs to correspond to it**

[09/14/2016 10:00:46 > ebab45: INFO] Executing: 'Functions.ProcessWorkflows' - Reason: 'New queue message detected on 'processworkflows'.'

The only thing I have found that works consistently to resolve this is to kill the job and then kill the w3wp.exe scm instance (kudu) and it will restart the job with the new files. If I only restart the job it still continues to run the old code. In environments where I have a swap, this does not seem to happen. Only in environments that there is only a single instance.

Any help would be appreciated!

**Comment by davidebbo** [comment]
It sounds like Kudu is not receiving the file change notification when the files are updated. As a test, when you're in this situation, does it fix it if you go to Kudu Console and 'touch' one of the files in your WebJob folder? Look under `d:\home\site\wwwroot\app_data\jobs\...`.

**Comment by roelandvh** [comment]
It seems we're experiencing this exact same issue. We have 8 background tasks that are running as WebJobs, each in their own Web App / App Service in the Azure portal. In our test environment they are _all_ deployed (using Octopus Deploy) after each build (which happens several times a day after a push, and also a scheduled nightly build). It appears 6 of these 8 background tasks haven't restarted in quite a while. For some of them the last restart was September 9th. 

When I look in the task folder under "D:\home\site\wwwroot\App_Data\jobs\continuous\[taskname]" I can see the binaries are the ones we just deployed, but when I look in the "D:\local\Temp\jobs\continuous\[taskname]\eysmbnqk.oh2\" folder (found in the Process Explorer properties of the executable that is running), I can see that indeed the binaries are older versions.

"Touching" a file worked for 1 task, but not for a few others. I can't find an explanation for this difference.

**Comment by brainded** [comment]
I haven't responded just yet because the issue is intermittent and hasn't happened since I posted. I will respond when I see the same symptoms again and can test out touching the files.

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
