### ISSUE TITLE
Create a built-in deployment script for function apps

### ISSUE THREAD

**Issue by ahmelsayed** [projectkudu/kudu#2137]
Right now function apps use the [basic site](https://github.com/projectkudu/KuduScript/blob/master/lib/templates/deploy.batch.basic.template) deployment script which just copies all the files from the repo to the site root. We should add a more specific script that also attempts to restore npm after that. 
I think the logic of the batch file would be to copy everything to the site root, just like the basic site script, then enumerate the folders, if there is a `package.json` in there, then cd there and do npm install. 

Here is a batch snippet for that

```batch
:: 2. Restore npm

FOR /F "tokens=*" %%i IN ('DIR /B %DEPLOYMENT_TARGET% /A:D') DO (
  IF EXIST "%DEPLOYMENT_TARGET%\%%i\package.json" (
    pushd "%DEPLOYMENT_TARGET%\%%i"
    npm install --production
    IF !ERRORLEVEL! NEQ 0 goto error
    popd
  )
)

```

**Comment by rnithish** [comment]
which version of kudusync will this change take effect? Greater than 0.2.3 ?

**Comment by davidebbo** [comment]
This fix in now deployed. @rnithish note that the fix in in KuduScript and not KuduSync.

**Comment by davidebbo** [comment]
The new version of KuduScript is 1.0.9 on https://www.npmjs.com/package/kuduscript. I just uploaded it as we had missed that step (though Kudu was using it already).
