### ISSUE TITLE
Error deploying from VSTS/Git - MSBuild auto-detection

### ISSUE THREAD

**Issue by lukos** [projectkudu/kudu#2138]
This the first time I have tried to deploy to App Services (Direct Publish is broken in VS2015!) so I setup a Git repo in VSTS and linked to an App Services project.

When code is pushed, the deployment is triggered but it errors:

> Command: "D:\home\site\deployments\tools\deploy.cmd"
> Handling .NET Web Application deployment.
> MSBuild auto-detection: using msbuild version '14.0' from 'D:\Program Files (x86)\MSBuild\14.0\bin'.
> The system cannot find the file specified.
> 
> Failed exitCode=1, command=nuget restore "D:\home\site\repository\MyProject.sln"
> An error has occurred during web site deployment.
> The system cannot find the file specified.\r\nD:\Program Files (x86)\SiteExtensions\Kudu\57.50831.2397\bin\Scripts\starter.cmd "D:\home\site\deployments\tools\deploy.cmd"

It looks related to nuget restore but I can't see why it is trying to use MSBuild for package restore, there is no targets files in the solution and it is not referenced in the solution either.

Perhaps a more useful error if this is a typical newbie problem?

**Comment by lukos** [comment]
Some more information. The underlying problem is related to NuGet.exe not being able to access our private NuGet repository on VSTS, which requires credentials and which don't seem to be read from the nuget.config in the root. The strange thing is that if a NuGet.exe is present in the root, the verbose information is not displayed and the error above is all you get. If you DON'T have NuGet.exe in the root, you get a much longer error which makes it more obvious that it cannot open the private feed.

**Comment by davidebbo** [comment]
One thing I'd suggest to help isolate: use [Kudu Console](https://github.com/projectkudu/kudu/wiki/Kudu-console) to go to the `D:\home\site\repository` folder, and try running msbuild manually from there. Does it also fail?

As an aside, it's generally best not commit nuget.exe in your git repo, and just rely on the one available on the build machine.

**Comment by lukos** [comment]
I hadn't intentionally added NuGet.exe, that was a hangover from what we needed to do to get TFVC working in VSTS! The whole issue is around package restore and the underlying issue here, is that if NuGet cannot restore packages (which it can't from private repos by default - or any easy way I could work out - due to a broken change in the VSTS portal) then the error is not accurate or is at best incomplete.

I don't understand why having NuGet.exe in the root would shorten the error message but could I suggest (from a newbie point of view) that either a warning is displayed in the log, "Adding your own NuGet.exe is not recommended and might mask some errors" or otherwise, if a private repo cannot be opened, that this message is displayed rather than the rather ambiguous "The system cannot find the file specified"? The shortened version (can't remember if the same on the longer error) also makes it look like MsBuild was not found, which is not the case and also sent me on a wild goose chase.

I appreciate that this isn't the most major bug but a confusion that I hit without doing anything too weird or wonderful is also likely to affect other people.
