### ISSUE TITLE
Showing invalid Certificate for Kudu URL

### ISSUE THREAD

**Issue by Ajay-MS** [projectkudu/kudu#2140]
Hello Team, 

One of our customer is facing issue in deployment to kudu, because kudu is showing invalid certifcate for kudu urll - xxxxxx.scm.azurewebsites.net . 

Customer Issue : [Invalid certificate](https://github.com/Microsoft/vsts-tasks/issues/2547)

Looking for your help in this customer issue.

**Comment by davidebbo** [comment]
@nelsonmorais Can you share your web app name, either directly or [indirectly](https://github.com/projectkudu/kudu/wiki/Reporting-your-site-name-without-posting-it-publicly)? This will help us investigate. Thanks!

**Comment by davidebbo** [comment]
@nelsonmorais Glad it works now! Would you mind sharing what region the site is in?

**Comment by nelsonmorais** [comment]
@davidebbo Yes, it was in Western Europe

**Comment by davidebbo** [comment]
Thanks. We did have an issue that affected part of West Europe, and it was solved on Friday around 3pm PST (so late Friday in Europe). If you saw the error before that and not after, that was likely it!

**Comment by nelsonmorais** [comment]
@davidebbo Ok thanks, that was probably the case! Glad it's fixed now.

**Comment by Ajay-MS** [comment]
@davidebbo  Thanks

**Comment by nelsonmorais** [comment]
@Ajay-MS Thanks!

**Comment by davidebbo** [comment]
For reference, here is where it first came up: https://social.msdn.microsoft.com/Forums/en-US/fe0ae98d-0135-45a8-849d-2e0f5d06b99f/api-app-deploy-from-vsts-breaks-due-to-certificate-for-httpssitescmazurewebsitesnet-not?forum=windowsazurewebsitespreview
