### ISSUE TITLE
Evaluate Monaco to replace Ace Editor

### ISSUE THREAD

**Issue by snobu** [projectkudu/kudu#2141]
> ### The Monaco Editor is the code editor that powers VS Code

Home page: https://github.com/Microsoft/monaco-editor
Demo: https://microsoft.github.io/monaco-editor/

If anyone has something going with Monaco hooked up to [Knockout.js](https://github.com/projectkudu/kudu/blob/master/Kudu.Services.Web/Content/Scripts/ace-init.js#L6) bindings, please share, don't be shy.

**Comment by badescuga** [comment]
is there a reason for moving to Monaco?

**Comment by snobu** [comment]
Here's one:
SOMETIMES - but absolutely random - Ace won't load. There's just an empty `<editor>` element being rendered. For the life of me i could not find out why this is happening.

Also it would be nice to have Monaco all across the board: App Service Editor, Kudu, Azure Functions (which last time i checked uses Ace).

**Comment by davidebbo** [comment]
Functions has already switched to Monaco, because we're planning to make use of its C# intellisense, ...

But for Kudu, I'm not seeing the really convincing argument to switch. I haven't personally run into the Ace loading issue.

The risk of switching is to destabilize things. I could be convinced if there are more tangible benefits, but let's not do it just for the sake of consistency with functions, etc....

**Comment by snobu** [comment]
I actually opened this to see if there's any clear preference. Both editors are great products. Actually Ace is ahead on performance for large files.. at least for now.

**Comment by badescuga** [comment]
I prefer Monaco but don't see a real value in switching. I'm not expecting a that much better experience than Ace.

Also, It'd be interesting in knowing what's the MAU for the code editor in kudu.

**Comment by davidebbo** [comment]
MAU?

**Comment by badescuga** [comment]
*Monthly Active Users.

i.e. If the experience is better in Monaco and the number of users actually using the code editor is really high, then it might we worth having the discussion. If the number of users is low, then it might not be worth it.

**Comment by snobu** [comment]
Oh, wait till the _New File_ feature hits production.. or how Apple would put it.. This changes everything. Again!

**Comment by davidebbo** [comment]
> Oh, wait till the New File feature hits production.. or how Apple would put it.. This changes everything. Again!

Hopefully later this week!
