### ISSUE TITLE
500 using git deployment (Azure, one region only, repeatable)

### ISSUE THREAD

**Issue by kierenj** [projectkudu/kudu#2146]
Hi - I realise my primary issue lies with the Azure support team, but I'm trying to be as helpful as I can to them (things are progressing.. a little slowly..)

Bit of background: I've created some App Services in different regions.  Any in the "UK South" region specifically give a 500 error when using git.  Other regions do not.

All regions were working fine until sometime yesterday.

Browsing to the git endpoint gives,
"No route registered for /myreponame.git"

I saw https://github.com/projectkudu/kudu/issues/1989 and took a look at kudu trace files, but nothing there (just one pair of largely empty startup/shutdown files for a .git endpoint).

Is there anything else I can do, or Kudu can provide, so that I can help get to a resolution please?

**Comment by davidebbo** [comment]
The fact that browsing to the git end up gives that error is by normal. It's not meant to be browsed to.

After a deployment error, can you use Kudu Console to look at the trace files under `D:\home\LogFiles\kudu\trace` that match the time. Do you see any interesting log files?
