### ISSUE TITLE
Golang build fails on private Git repository

### ISSUE THREAD

**Issue by rusenask** [projectkudu/kudu#2148]
Hello, I have noticed that Golang application build fails if it's a private repository and have internal packages. The problem could be solved by cloning it into the correct gopath since "go get" is trying to fetch all required packages that are not in vendor and since your internal packages are not in vendor - it tries to get them but fails since those are private. 

If a repo was cloned into a correct path - "go get" would find all those packages and won't try to fetch them.

**Comment by davidebbo** [comment]
I don't completely understand the issue. Bear with me as I'm no Go expert. What exactly are 'internal packages'? Are they not part of the repo? Are they exposed in some private end point, and if so using what protocol  and authentication (e.g. ssh vs https).?

**Comment by rusenask** [comment]
Apologies for vague description. So, the private Go repo looks like:

github.com/rusenask/repo_name/main.go
github.com/rusenask/repo_name/packageA/file.go
github.com/rusenask/repo_name/packageB/file.go
github.com/rusenask/repo_name/packageC/file.go

When Kudu pulls this repo it should place it into correct gopath (GOPATH/src/github.com/rusenask/repo_name) and then `go get` and `go build` tools will find 
`github.com/rusenask/repo_name/packageA` as a normal 3rd party library and happily build it without even knowing that this is a package from private repo. This strategy works for any other git provider - bitbucket/gitlab. For example if a repo is stored in bitbucket:

`bitbucket.com/scm/project_name/repo_name`

it would then have to land into:

`GOPATH/src/bitbucket.com/scm/project_name/repo_name`

Does that make sense?

**Comment by davidebbo** [comment]
Some questions/clarifications:

1. Note that the repo in Kudu always sits in `D:\home\site\repository`
1. What specific error are you getting? Can you paste the relevant chunk of the build output?
1. Do you have a custom deployment script that runs 'go get'?

Also, would you be able to share a minimal repo that demonstrates the issue?

@shrimpy is no longer on the team, but he implemented to Go support, so if he sees this maybe he'll have thoughts!

**Comment by rusenask** [comment]
2. Getting errors it fails to find packages from my own repository
3. No, just pointing it to my repo

I have look at deployment script, so at the beginning it does:
`Creating GOPATH\src D:\local\Temp\8d3e21053ef9592\gopath\src`

and then it's cloning repo to gopath as well (looks right): 
`Cloning into 'D:\local\Temp\8d3e21053ef9592\gopath\src\github.com\rusenask\gunfuzz'...
fatal: could not read Username for 'https://github.com': terminal prompts disabled`

and then more:
`
Building Go app to produce exe file
package github.com/rusenask/gunfuzz/database: exit status 128
package github.com/rusenask/gunfuzz/statik: cannot find package "github.com/rusenask/gunfuzz/statik" in any of:
	D:\Program Files\Go\1.7\src\github.com\rusenask\gunfuzz\statik (from $GOROOT)
	D:\local\Temp\8d3e21053ef9592\gopath\src\github.com\rusenask\gunfuzz\statik (from $GOPATH)
package github.com/rusenask/gunfuzz/structs: cannot find package "github.com/rusenask/gunfuzz/structs" in any of:
	D:\Program Files\Go\1.7\src\github.com\rusenask\gunfuzz\structs (from $GOROOT)
	D:\local\Temp\8d3e21053ef9592\gopath\src\github.com\rusenask\gunfuzz\structs (from $GOPATH)
`

so, it looks like it's doing what I suggested earlier that it should put it into GOPATH but is still failing to find packages. Can it be somehow related to the cloning that it doesn't copy sub directories? 
Is there a way to get into this deployment step in azure to check whether the whole repo was cloned? 

Regarding example repo - okay, will create one.

**Comment by davidebbo** [comment]
My guess is that the issue comes down to it failing to authenticate over https when the repo is private. I assume everything works when using a public repo?

Can you share your web app name, either directly or [indirectly](https://github.com/projectkudu/kudu/wiki/Reporting-your-site-name-without-posting-it-publicly)? This will help us investigate. Thanks!

**Comment by rusenask** [comment]
I also thought this and made repo public few days ago, then deployment worked, but once I made repo private again - it started failing. 
I guess that when it's public - it just `go get`s  everything what's missing, although it doesn't explain why it is missing those packages in the first place. 

Created new web app under same service plan:
http://dummy-websrv.azurewebsites.net/

**Comment by rusenask** [comment]
Did a bit more investigation, now using local Git repository inside Azure since I thought maybe it had something to do with Github integration.

So that error from previous messages about git clone failing was from `go get` - and that `go get` should have never been tried to execute anyway.

Logs from kudu:

```
Started : Monday, October 10, 2016 2:12:23 PM
   Source : D:\home\site\repository\
     Dest : D:\local\Temp\8d3f11773680650\gopath\src\azureapp\
```
This is a bit wrong and should never work for an application that has at least one internal directory (in Go those are called packages).

if my repository is in github.com/rusenask/my_app_name
then, Kudu should __not__ clone it into 
` D:\local\Temp\8d3f11773680650\gopath\src\azureapp\`
but rather clone it into
` D:\local\Temp\8d3f11773680650\gopath\src\github.com\rusenask\my_app_name`

It is one thing to do this for Github, but a bit more difficult if you are using your own git repostiory. Location, where your app will be cloned should be configurable, since if I store my application in bitbucket or somewhere else - paths will be different. 

@davidebbo can I somehow override that destination?
(`Dest : D:\local\Temp\8d3f11773680650\gopath\src\azureapp\`)

**Comment by davidebbo** [comment]
Note that the Kudu repository sites in `D:\home\site\repository` and not under tmp (though some files may get copied to tmp later).

One thing you can do is download the deployment script (from Tools menu in Kudu) to see exactly what it's doing step by step. Then if needed you can customize it by using a [custom deployment script](http://blog.amitapple.com/post/38417491924/azurewebsitecustomdeploymentpart1/).

**Comment by rusenask** [comment]
Thanks! 
Downloaded deployment script, modified
`SET FOLDERNAME=azureapp`
to
`SET FOLDERNAME=github.com\rusenask\my_app_name`

and then web.config to point to the newly created binary and it works! :)

**Comment by davidebbo** [comment]
Awesome!

Our Go support is still quite limited, so at this point, I think this is good enough of a workaround. At least now, we have it explained here is case someone else runs into it :)
