### ISSUE TITLE
Handling gzip for chunked transfer encoding?

### ISSUE THREAD

**Issue by haocs** [projectkudu/kudu#2149]
I recently tested the log-streaming service of my azure web apps followed this [wiki page](https://github.com/projectkudu/kudu/wiki/Diagnostic-Log-Stream). I found an issue when I traced my service logs.
If I omitted `accept-encoding` header or set it to `identity`, everything worked like a charm. However, if the  `accept-encoding` header included `gzip`, `content-encoding` header of response became `gzip` but the response body I got is messed up(response chunk was not decoded as expected).  I could observe this issue using`curl` or functions using Requests library in Python.
I am wondering if streaming service supports `gzip` compression when chunked transfer encoding is enabled? If yes, could you advise me what the correct steps/configs are to decode compressed stream logs on clients side? Thanks!

**Comment by davidebbo** [comment]
Can you clarify what specific request you are making? e.g. an you give the full `curl` command you're running?

**Comment by haocs** [comment]
Yes. I am tracing the service logs using curl 
``` bash
curl -u {username} https://{sitename}.scm.azurewebsites.net/logstream
# response/log stream
2016-09-26T23:18:38  Welcome, you are now connected to log-streaming service.
```
The above example worked fine, However if I added headers to `accept-encoding` like the following
``` bash
curl  -H "Accept-Encoding: gzip, deflate" -u {username} https://{sitename}.scm.azurewebsites.net/logstream
# response/log stream
��`I�%&/m�{J�J��t�`$ؐ@�������iG#)�*��eVe]f@�흼��{����{����;�N'���?\fdl��J�ɞ!���?~|?"�vv?��y���雽{��v��O�����Z����Z�Y����*�V�e>m�Y�ViY]l7m�g�by�6y}YL��o
```
curl can not decode the response content then print garbled text.
My testing webapp server is a simple Nodejs application which only writes logs per each request.

**Comment by davidebbo** [comment]
@suwatch would you expect the logstream endpoint to support gzip?

@haocs any reason why you need to use gzip in the first place for this API?

**Comment by haocs** [comment]
No, I am totally fine without gzip encoding support. The confusion here is that the response headers from server contain `content-encoding=gzip` however the response content is not gzip encoded.

**Comment by suwatch** [comment]
We do support chunked and gzip for logStream.  In fact, if you use browser, it does exactly that.   Browser looks at Content-Encoding and, if gzip, it decompresses automatically.   For curl, you will need to give a directive `--compressed`, so curl will decompress for you.
```
curl  --compressed -H "Accept-Encoding: gzip, deflate" -u {username}  https://{sitename}.scm.azurewebsites.net/logstream 
```
Under the hood, on the server, IIS does dynamic compression for each chunked it sent (for a certain block size).

**Comment by haocs** [comment]
@suwatch Thanks for your reply.
I followed your suggestion and I see the decoding issue go away. However, I observe another issue that the last line of logs won't print out until the next chunk arrives. I didnot see this issue without gzip compression before.
Wondering if it is the trailing CRLF of each chunk causes this issue?
