### ISSUE TITLE
Use webhooks for Bitbucket integration

### ISSUE THREAD

**Issue by JuntaoV5** [projectkudu/kudu#2150]
Hi,

Will we use webhooks, like we do for GitHub, for Bitbucket?

The POST services on Bitbucket has a limitation: There is a 30 seconds timeout for all POSTs in the queue. When times out, the remaining POSTs in the queue won't be executed by Bitbucket. This can happen when there are many depository and POSTs. And from customer's point of view, it's App Service doesn't work with Bitbucket.

Bitbucket now has webhooks available and they have published a notification to encourage the migration to webhooks. Will App Service create webhooks to Bithucket for integration?

**Comment by davidebbo** [comment]
Related to #1621. We should switch to this at some point.

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
