### ISSUE TITLE
The Azure App Service Support preview portal didn't show the autoheal rules configured while it was added to applicationhost.config

### ISSUE THREAD

**Issue by lczc1988** [projectkudu/kudu#2153]
After customer create an auto-heal rule in https://msdn-west-1.scm.azurewebsites.net/Support  , the web page shows it is saved successfully, However, when I refresh the page, the setting has disappeared. 

I checked the applicationhost.config file and found the rules were added successfully and confirmed works well. Could you please let me know if this is a known bug and when it will be fixed? Thank you.

What I configured:
 
![1](https://cloud.githubusercontent.com/assets/8097498/18904256/b49e779c-858f-11e6-93c2-203e4fccc4e9.png)

After refresh browser:
 
![2](https://cloud.githubusercontent.com/assets/8097498/18904269/c3d7e57c-858f-11e6-91d0-140a838f072e.png)

applicationhost.config
 
![3](https://cloud.githubusercontent.com/assets/8097498/18904279/ca552dc4-858f-11e6-9e15-03dc13691987.png)

**Comment by davidebbo** [comment]
The support page is not part of Kudu. Please use the [Web App forum](https://social.msdn.microsoft.com/Forums/azure/en-US/home?forum=windowsazurewebsitespreview) instead for this issue. Thanks!
