### ISSUE TITLE
Can't get the HTTP request body from webjobs

### ISSUE THREAD

**Issue by yaquawa** [projectkudu/kudu#2154]
I've added a webjob called `runcmd`. The contents of the webjob are something like below to get the HTTP request body from a HTTP POST request.

```php
echo file_get_contents('php://input');
```

The webhook URI for triggering this webjob is something like this `https://xxx.scm.azurewebsites.net/api/triggeredwebjobs/runcmd/run`.

If I issue a HTTP POST request against to the webhook above with the following request body.

```json
{
    "test":"test data"
}
``` 

and I'll get nothing. How could that happen? Is this a bug!?

**Comment by davidebbo** [comment]
WebJobs were not designed to handle arbitrary http requests, so this is not supported. Your options are:

- Use a regular Web API instead
- Use the new Azure Functions
