### ISSUE TITLE
httpPlatformHandler path is overwritten during deploy on Azure

### ISSUE THREAD

**Issue by durilka** [projectkudu/kudu#2155]
I have a web.config somewhere in sub-app's wwwroot/ with 
```
        <handlers>
            <add name="httpplatformhandler" path="/api/*" verb="*" modules="httpPlatformHandler" resourceType="Unspecified" />
        </handlers>
```

after the kudu_sync everything else in this file is kept (and copied over to the correct wwwroot) but the httpPlatformHandler is replaced with 
```
        <handlers>
            <add name="httpplatformhandler" path="*" verb="*" modules="httpPlatformHandler" resourceType="Unspecified" />
        </handlers>

```
losing the "api" part which breaks delivery of the static content which is configured in 
```
    <system.web>
        <compilation debug="true" targetFramework="4.0" />
        <httpHandlers>
            <add verb="*" type="Nancy.Hosting.Aspnet.NancyHttpRequestHandler" path="api/*"/>
            <add verb="*" type="System.Web.StaticFileHandler" path="*"/>
        </httpHandlers>
    </system.web>

```

The question is am I misusing the handler or not using the kudu correctly? The third option would be a bug in kudu.

**Comment by davidebbo** [comment]
Note that Kudu just uses standard dotnet/msbuild commands, and doesn't have its own logic for these transforms. So my guess is that you'd see the same behavior locally if you ran the same commands.

You can go to Kudu Console and download the deployment script from the Tools menu, which will help you investigate.

**Comment by durilka** [comment]
ah. right. it's `dnu publish` not kudu. 
thanks!

case closed.
