### ISSUE TITLE
How do you get kudu to clean the repo folder before doing a build?

### ISSUE THREAD

**Issue by xt0rted** [projectkudu/kudu#2160]
I've ran into numerous issues of old npm packages being used, and even files I thought were deleted continuing to be deployed. My most recent issue was trying to add `/p:PrecompileBeforePublish=true` via `SCM_BUILD_ARGS` but the build failed. I removed `SCM_BUILD_ARGS` and tried to redeploy which resulted in an error saying

> It is an error to use a section registered as allowDefinition='MachineToApplication' beyond application level. This error can be caused by a virtual directory not being configured as an application in IIS.

The fix to the recent issue was deleting the project's `obj` folder. In the other cases it was deleting the `node_modules` folder, or `bower_components`.

I'd like kudu to reset my repo to a clean state before each build so I don't run into these issues anymore. How do I do that?

**Comment by ratestHub** [comment]
I have achieved this by these 2 simple steps for .NET application which can be extended as well.

1. Set the key SCM_BUILD_ARGS and value = -p:Configuration=Release;PublishProfile=Azure; in app service app settings from application settings. 
2. Include the custom msbuild targets through Azure.pubxml file present at <project>\Properties\PublishProfiles\ which you can find if you have any profile created and sample as below.

```
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Target Name="BeforeBuild">
    <Message Text="###Custom Before Build Tasks Begin######" Importance="high"/>
    <Message Text="#Preparing to remove $(BaseIntermediateOutputPath)" Importance="high"/>
    <RemoveDir Directories="$(BaseIntermediateOutputPath)"></RemoveDir>
    <Message Importance="high" Condition="'$(BaseIntermediateOutputPath)' == '' Or !Exists($(BaseIntermediateOutputPath))" Text="Remove $(BaseIntermediateOutputPath) Task Finished" />
    <Message Importance="high" Condition="Exists($(BaseIntermediateOutputPath))" Text="Remove $(BaseIntermediateOutputPath) Failed" />
    <Message Text="#Preparing to remove $(OutDir)" Importance="high"/>
    <RemoveDir Directories="$(OutDir)"></RemoveDir>
    <Message Importance="high" Condition="'$(OutDir)' == '' Or !Exists($(OutDir))" Text="Remove $(OutDir) Task Finished" />
    <Message Importance="high" Condition="Exists($(OutDir))" Text="Remove $(OutDir) Failed" />
    <Message Text="###Custom Before Build Tasks End######" Importance="high"/>
  </Target>
</Project>
```

So far, this runs swiftly whenever I'm pushing code though continuous integration.

**Comment by xt0rted** [comment]
I'm now doing Zip Deploys from AppVeyor so this is no longer an issue.
