### ISSUE TITLE
Precompilation doesn't cause recompilation

### ISSUE THREAD

**Issue by MatthewSteeples** [projectkudu/kudu#2164]
We've got precompilation enabled for our git-deployed ASP.NET project. This means that Kudu precompiles all of our aspx and cshtml pages on deploy (which is awesome).

The problem is that if we make a change that _just_ affects the cshtml or aspx pages, the site doesn't actually get updated (because everything is already in dlls and doesn't get regenerated). We need a way of making the system recompile the site even if just the static pages have changed. Is that possible at the moment through config flags or something?

This is a similar bug to #1567 but only appears when we only change page content. If we change code (which forces a recompilation anyway) then the problem doesn't happen

**Comment by davidebbo** [comment]
We just call msbuild, so I'm surprised that it doesn't do the right thing in the incremental compile scenario.

But that would be solved by cleaning out the repo before building, and in that sense it is a variant of #1532 and #2160.

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
