### ISSUE TITLE
Kudu deployment error: Object AppControllers has no method 'endsWith'

### ISSUE THREAD

**Issue by robfarmergt** [projectkudu/kudu#2165]
I'm getting the following error when trying to deploy to an Azure Web App:
```
Using the following command to generate deployment script: 'azure site deploymentscript -y --no-dot-deployment -r "D:\home\site\repository" -o "D:\home\site\deployments\tools" --aspNetCore "D:\home\site\repository\src\Company.Web" --solutionFile D:\home\site\repository\Company.sln'.
Project file path: .\src\Company.Web
error: Object AppControllers has no method 'endsWith'
error: Object AppControllers has no method 'endsWith'\r\nD:\Program Files (x86)\SiteExtensions\Kudu\58.50923.2428\bin\Scripts\starter.cmd "D:\Program Files (x86)\SiteExtensions\Kudu\58.50923.2428\bin\node_modules\.bin\kuduscript.cmd" -y --no-dot-deployment -r "D:\home\site\repository" -o "D:\home\site\deployments\tools" --aspNetCore "D:\home\site\repository\src\Company.Web" --solutionFile D:\home\site\repository\Company.sln
```
Any recommendations on where to look to troubleshoot?

**Comment by ahmelsayed** [comment]
same as https://github.com/projectkudu/KuduScript/issues/55 should be fixed by https://github.com/projectkudu/KuduScript/commit/5f2dc8aca80fe31922661e238df6652740fc18ce and https://github.com/projectkudu/kudu/commit/63c5f4759cc406690b10d1f2455fcb1d3367b105

/cc @watashiSHUN

**Comment by davidebbo** [comment]
This will be deployed by end of week.

**Comment by robfarmergt** [comment]
Thanks, the workaround fixed the issue for us. Thanks again for the rapid response!

**Comment by robfarmergt** [comment]
@davidebbo @ahmelsayed Not sure if this is related (happy to open up another issue if not).

Although the deploy did succeed, the app won't run. Gettings a 500 error:

```
System.InvalidOperationException
Unable to locate a project.json at 'D:\home\site\wwwroot\'.
```

I can confirm the `project*.json` files are not there.

**Comment by davidebbo** [comment]
That sounds unrelated, so separate issue with details would be best.
