### ISSUE TITLE
Can kudu write to the site's diagnostic logs?

### ISSUE THREAD

**Issue by xt0rted** [projectkudu/kudu#2166]
Last night I had an issue come up that's hard to track down. I'm turning the diagnostic logs on and shipping them to blob storage in case this happens again. Can kudu write to these saying a deployment started, succeeded, failed, etc.? I know I can get this info from the deployment history but while looking over these logs it'd be useful to see this info in them instead of having to look somewhere else.

**Comment by davidebbo** [comment]
I think this is possible in theory, but is not done today. Though I'm not sure if everyone would want that, as that would mix their deployment logs with their runtime logs.

**Comment by xt0rted** [comment]
A deployment would trigger the site to restart so I'd see my startup messages in the log. That should be sufficient for the issue I was trying to track down. Since that's really what I was after I'm closing this.
