### ISSUE TITLE
REST API Function files/body

### ISSUE THREAD

**Issue by alzuma** [projectkudu/kudu#2167]
https://github.com/projectkudu/kudu/wiki/Functions-API

How to get the files and its content? 

> `get /subscriptions/{sub}/resourceGroups/{rg}/providers/Microsoft.Web/sites/{functionapp}/functions/MyFunction?api-version=2015-08-01`

returns function information, but file tag is empty/null

> `"files": null`

**Comment by davidebbo** [comment]
Yes, this API is not designed to return the files. There could be thousands and it wouldn't work in a json payload. Instead, you can use the [vfs and zip APIs](https://github.com/projectkudu/kudu/wiki/REST-API#vfs).

**Comment by alzuma** [comment]
@davidebbo 
Yes, I did find vfs and zip APIs, but I want to do all with Function API and don't switch context.

So mybe there is point to allow picking files by name as well? Very simple api improvment 
> `get /subscriptions/{sub}/resourceGroups/{rg}/providers/Microsoft.Web/sites/{functionapp}/functions/MyFunction/files/{filename}?api-version=2015-08-01`

Now it possible to create or update file, by adding "get", there would be a full house and no need to use zip or vfs.

Pretty, please? :)

**Comment by davidebbo** [comment]
Problem is that this really breaks down when you have binary files, since ARM API must return everything as JSON. So we can't really have a function file API that works in all cases. On the other hand the vfs & zip APIs are designed for arbitrary files, as they're not tied to json payloads.

**Comment by alzuma** [comment]
```json 
{
  "name": "run.csx",
  "extension": ".csx",
  "size": "84",
  "content": "VGhlcmUgaXMgbm8gcmVhbCBwcm9ibGVtLCB3aGljaCBjb3VsZCBub3QgYmUgc29sdmVkIHdpdGggYmFzZTY0LiBWb2lsYSE="
}
