### ISSUE TITLE
Unable to locate a project.json at 'D:\home\site\wwwroot\'.

### ISSUE THREAD

**Issue by robfarmergt** [projectkudu/kudu#2168]
I'm having trouble deploying a project and getting a 500 error when going to the site: `Unable to locate a project.json at 'D:\home\site\wwwroot\'.`

```
Line 52:              // Setup configuration sources.
Line 53:  
Line 54:              var builder = new ConfigurationBuilder()
Line 55:                  .SetBasePath(env.ContentRootPath)
Line 56:                  .AddJsonFile("config.json")
```

Last successful deployment was on 9/16 with no changes being made to `Startup.cs` since then.

**Comment by davidebbo** [comment]
Is this an error you get at deployment time, or at runtime? If runtime, then it's outside the scope of Kudu, unless you suspect that it deployed the wrong files. See [Deployment vs runtime issues](https://github.com/projectkudu/kudu/wiki/Deployment-vs-runtime-issues).

See also [Troubleshooting Node errors](https://github.com/projectkudu/kudu/wiki/Troubleshooting-Node-errors)

**Comment by davidebbo** [comment]
Hard to tell without seeing your exact repo. What gets deployed is highly dependent on the kind of project you have and how you configure things.

See [Using a git repo to report an issue](https://github.com/projectkudu/kudu/wiki/Using-a-git-repo-to-report-an-issue)

**Comment by robfarmergt** [comment]
@davidebbo added you to a reproduction repo

**Comment by davidebbo** [comment]
Indeed, I see that it's not getting copied, but it's hard to tell whether it should, and whether there is a Kudu issue in the picture.

What you should do is look at the Kudu deployment script (you can download it from Kudu under Tools menu), and see what it's doing. It comes down to 3 standard steps:

```
:: 1. Restore nuget packages
:: 2. Build
:: 3. Publish
```

Try those precise same 3 commands manual on your local machine, and check whether you end up with that file.

**Comment by robfarmergt** [comment]
Is there a way to find out what `%SCM_BUILD_ARGS%` is set to?

**Comment by robfarmergt** [comment]
I figured out the issue, in my `project.json` file I had to make sure `project.json` was included:

```
"publishOptions": {
    "include": [
      "wwwroot",
      "Views",
      "Areas/**/Views",
      "appsettings.json",
      "config.json",
      "config.*.json",
      "web.config",
      "project.json",
      "project.*.json"
    ]
```

Not sure why this may have changed in the deployment process, but it's working fine now.

**Comment by davidebbo** [comment]
Cool, I figured it was something along those lines that was not specific to Web App. You most likely would have seen the same thing locally when deploying.

**Comment by robfarmergt** [comment]
Thanks again for all the help!
