### ISSUE TITLE
Failed to set up deployment source for Web App

### ISSUE THREAD

**Issue by Meyce** [projectkudu/kudu#2170]
I am testing setting a VSO Git Repo as the deployment source for an Azure web app and running into an error.

I've encountered the error through both the Portal and Resource Explorer. I have linked VSO to Azure AD.

When I setup the deployment source I receive the following error.

`Repository 'UpdateSiteSourceControl' operation failed with Microsoft.Web.Hosting.SourceControls.OAuthException: Vso GetWebHookInfo: There is no registered handler in Team Foundation Server for the service hooks event type ms.vss-release.deployment-completed-event.`

I have successfully set this up on my own VSO/Azure subscription and suspect it may be VSO permission I lack in the environment where I am trying to configure it.

**Comment by davidebbo** [comment]
It's a VSTS issue and not Kudu. I responded on http://stackoverflow.com/questions/39922153/error-while-setting-vso-as-deployment-source-for-azure-web-app/39924388

**Comment by Meyce** [comment]
Thank you for looking into it.

**Comment by davidebbo** [comment]
VSTS engineer gave a potential workaround to try if you can't wait:

Delete any Release-related service hook subscriptions in the project … any of these event types:

![image](https://cloud.githubusercontent.com/assets/556238/19204566/523fccc2-8c92-11e6-8161-46977f654aed.png)

**Comment by Meyce** [comment]
I  can give that a try.  We do have some of those events posting to Slack.

**Comment by derekpedersen** [comment]
This error is still occurring. Any idea of when it will be resolved?
