### ISSUE TITLE
Pushing console app with multiple exes runs wrong one

### ISSUE THREAD

**Issue by davidmatson** [projectkudu/kudu#2171]
I have a solution with two exes, one of which calls into (and thus references) the other. I pick one of these to be the one built by Kudu in a .deployment file with a project= line. However, that doesn't result in this project's exe being run by the continuous web job. Instead, it picks the first exe alphabetically rather than the exe from the project I indicated in the .deployment project.

(I'm currently working around the problem by adding an "A" prefix to the project I want to be run as the web job, "AWebJob" instead of "WebJob", but it feels very hacky.)

**Comment by ahmelsayed** [comment]
Yes that's the default behavior for webJob. 
the details of the picking logic is documented here https://github.com/projectkudu/kudu/wiki/Web-Jobs 

> We use the following logic to decide which file is the script to run within the job's directory:
> 
> Per file type we look first for a file named: run.{file type extension} (for example run.cmd or run.exe).
> If it doesn't exists for all file types, we'll then look for the first file with a supported file type extension.
> The order of file types extension used is: .cmd, .bat, .exe, .ps1, .sh, .php, .py, .js.
> The recommended script file to have in your job directory is: run.cmd.
> Note: We'll only look for a script under the root directory of that job (not under sub directories of it).
> Note: make sure .bat/.cmd files don't include the UTF-8 BOM (inserted by some editors such as Visual Studio by default), which can break things!

**Comment by davidebbo** [comment]
Just include a `run.cmd` and make it run whatever you want. This has added benefit of being able to pass command line args.
