### ISSUE TITLE
Post Deployment Hook should include slot information

### ISSUE THREAD

**Issue by motasem13hamad** [projectkudu/kudu#2174]
Using post deployment hook, is there any way to do the following because it seems that it does not differentiate between a deployment slot and instances and only carry the site name,

For example, 
If there is a website that has two Slots, And each slot has 3 instances, can we have something to notify us on which instance, slot that has new deployment.

```
{
  "id": "2bdc42572263361fef1a3334c562be57dfb06c27",
  "status": "success",
  "statusText": "",
  "authorEmail": "test@test.com",
  "author": "John Doe",
  "message": "Epic new feature!",
  "progress": "",
  "deployer": "",
  "receivedTime": "2015-06-11T09:58:46.9983824Z",
  "startTime": "2015-06-11T10:39:02.1322211Z",
  "endTime": "2015-06-11T10:39:07.555094Z",
  "lastSuccessEndTime": "2015-06-11T10:39:07.555094Z",
  "complete": true,
  **"siteName": "azure-dummy-site"**
}
```

**Comment by davidebbo** [comment]
I can see how knowing the slot name could be interesting, but I don't think the specific instance could ever be relevant, since all instances share the same file system. Can you clarify why you would want the instance info?

For the slot, we don't really have the slot name, but we do have something related: the hostname. e.g. the hostname would be something like "mysite.azurewebsites.net" or "mysite-myslot.azurewebsites.net". So we could include that in the payload.

**Comment by motasem13hamad** [comment]
Thank you,  i guess its related to speed of deployment to the websites instances,  but it should be no huge difference in deployment speed between instances in the same slot,
Is there an ETA for the slot name to be added to this api?

Thanks

Get Outlook for Android<https://aka.ms/ghei36>



On Mon, Oct 10, 2016 at 3:29 AM +0300, "David Ebbo" <notifications@github.com<mailto:notifications@github.com>> wrote:


I can see how knowing the slot name could be interesting, but I don't think the specific instance could ever be relevant, since all instances share the same file system. Can you clarify why you would want the instance info?

For the slot, we don't really have the slot name, but we do have something related: the hostname. e.g. the hostname would be something like "mysite.azurewebsites.net" or "mysite-myslot.azurewebsites.net". So we could include that in the payload.

-

**Comment by davidebbo** [comment]
Sorry, I'm not following what you describe relating to speed of deployment. Can you clarify?

For the slot name, please see my previous comment about potentially using the hostname instead. Will they work in your scenario?

**Comment by motasem13hamad** [comment]
Hello,


yeah i meant to that it's required to see if all the instances and slots have been deployed successfully,

Yeah for some scenarios, but can we have something in the json payload not in the query string i guess, the customer asks for this

Best regards,
Motasem Hamad.

________________________________

**Comment by davidebbo** [comment]
> yeah i meant to that it's required to see if all the instances and slots have been deployed successfully,

Again, all instances of the same slot share the **same file system**. So the question of checking whether all instances have been deployed does not apply.

As I see it, only the slot part of this request makes sense, and the instance does not. Can we keep the instance part off the table?

**Comment by motasem13hamad** [comment]
Yes Sure, i though that each instance has separate deployment, sorry my bad

**Comment by motasem13hamad** [comment]
Hello David,
can you please send me updates on this issue.
Thank you

**Comment by davidebbo** [comment]
We'll look into adding the hostname to the payload. Sorry, there is no clear ETA at this point, as we have to prioritize against other things (this is the first time this feature request came up).

**Comment by watashiSHUN** [comment]
@motasem13hamad
I just want your clarification on the following points before we start implementing it

1. the use case you mentioned has a set up like this: **1 webiste + 2 slots, all three of them have the SAME webhook, and at the endpoint of the hook there is different logic applied depending on who's the message sender (one of the two slots)**
2.  you mentioned things like:  "add slot name to this api", "having something in the json payload not the query string". Are you thinking about the kudu HTTP GET API : `api/deployments/{id}`?

please let me know if my interpretation is off target, and I think for the use case I described in **1.** there is a work around **for now** : once the webhook is triggered, client can take the `id` and call `/api/deployments/{id}` on one of the **slot kudu site**, if the result is not found, you know deployment succeed on the **solt not being queried**

**Comment by motasem13hamad** [comment]
1- Yeah exactly.
2- im thinking about the kudu post deployment payload, something like this:
{
  "id": "2bdc42572263361fef1a3334c562be57dfb06c27",
  "status": "success",
  "lastSuccessEndTime": "2015-06-11T10:39:07.555094Z",
  "complete": true,
  "siteName": "azure-dummy-site"
''slotName":"Azure-dummy-site-production"
}

thank you for the workaround, i have told the client regarding this.

**Comment by watashiSHUN** [comment]
I am thinking about adding a field `"hostname"`, which value is basically: 
`$"{siteName}-{slotName}.azurewebsites.net"`, for example:
```
{
  "id": "2bdc42572263361fef1a3334c562be57dfb06c27",
  "status": "success",
  ...
  "siteName":  "confusedDev"
  "hostName":  "confusedDev-slot.azurewebsites.net"  // new field
}
```
I **suspect** that we added `"siteName"` because there was a client who has multiple azure websites with the **SAME** webhook...different actions take place based on siteName (slotName for our issue). We can now use `"hostName"` field to solve both issues (two birds one stone). As a matter of fact...the real `"hostName"` should have **"scm"** in the string to show it comes from kudu

I am open for suggestion on this one

**Comment by motasem13hamad** [comment]
Yeah That sound great

**Comment by davidebbo** [comment]
This work is now complete, and you'll now see a 'hostName' field.
