### ISSUE TITLE
Latest kudu release on azure broke our deployment...

### ISSUE THREAD

**Issue by niemyjski** [projectkudu/kudu#2175]
Command: bash deploy.sh
Updating configuration settings.
deploy.sh: line 70: npm: command not found
deploy.sh: line 71: npm: command not found
An error has occurred during web site deployment.
Error installing npm packages
deploy.sh: line 70: npm: command not found\r\ndeploy.sh: line 71: npm: command not found\r\nD:\Program Files (x86)\SiteExtensions\Kudu\58.51007.2458\bin\Scripts\starter.cmd bash deploy.sh

https://github.com/exceptionless/Exceptionless.UI/tree/feature/deploy

This has been working for over a year

**Comment by davidebbo** [comment]
Nothing has changed on the Kudu side. Can you check whether the issue might have started with a change to your repo, like [this one](https://github.com/exceptionless/Exceptionless.UI/commit/031cfdf1b7651ee26d9f999fbd5198176f0d7c2f)? i.e. if you go back to a commit that you had previously successfully deployed, does it also repro?

If it does, can you share your web app name, either directly or [indirectly](https://github.com/projectkudu/kudu/wiki/Reporting-your-site-name-without-posting-it-publicly)? This will help us investigate.

**Comment by niemyjski** [comment]
All the changes I made last night around deployment was to try and fix this issue. I couldn't get npm to resolve anything. Literally this has been auto deploying for a really long time without any issue. The  deploy branch is pretty much the original with updated npm `md5` dependency

The app name is ex-app. I have a dev-app instance that also is doing the same behavior.

**Comment by niemyjski** [comment]
https://github.com/exceptionless/Exceptionless.UI/commits/feature/deploy/deploy.sh has been working since July 3rd, 2015

**Comment by niemyjski** [comment]
If you'd like I'd be more than happy to share my screen (all my scripts are already on github). Feel free to make any changes to the dev-app instance on azure which is pointing to the same dev source. In the mean time I'm broken if auto deployment happens on the ex-app (I have to ftp in and make config changes).

**Comment by davidebbo** [comment]
Ok, I would investigate this morning. When you say 'dev-app', you mean the one called 'ex-dev-app' right?

**Comment by niemyjski** [comment]
yeah, that's the one :)

**Comment by niemyjski** [comment]
I tried updating the deploy script with the latest template for node (on kuduscript) and even that errored out when I did `eval npm_script?? install`.

**Comment by niemyjski** [comment]
I just tried connecting to the `Development Tools` Console to see if I could run any node / npm commands but it doesn't seem to be working (read only??) on both safari and chrome.

**Comment by davidebbo** [comment]
I'm not seeing this on the dev site. Here is what I tried:

- Went to Kudu Console
- Created d:\home\tmp folder
- In there, I ran `npm install underscore` and it worked fine

Can you give me the specific command that you tried and failed?

**Comment by niemyjski** [comment]
I can't even type into the console :\.

**Comment by davidebbo** [comment]
To make sure we're talking about the same Console: go to https://ex-dev-app.scm.azurewebsites.net/DebugConsole

**Comment by niemyjski** [comment]
I was using the console built right into the portal. scm works but the link to get there from the diagnostics page doesn't work.

```sh
D:\home\site\wwwroot>sh deploy.sh
Updating configuration settings.
deploy.sh: line 69: cd: D:\home/app_data/jobs/triggered/config: No such file or directory

module.js:340
    throw err;
          ^
Error: Cannot find module 'D:\home\site\wwwroot\run.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
Deploying site content.
Error: Source and destination directories cannot be sub-directories of each other
An error has occurred during web site deployment.
Kudu Sync failed
```

That fails but if I navigate to the app_data\jobs\triggered\config directory and do the `npm install` and `node run.js` (the same commands that deploy.sh calls) it succeeds

**Comment by niemyjski** [comment]
guess that is part of the problem, `cd "$DEPLOYMENT_SOURCE/app_data/jobs/triggered/config"` deployment source doesn't seem to be being set correctly anymore?

**Comment by davidebbo** [comment]
Ok, I found the issue. It is indeed a regression, although not with Kudu itself. What happened is `D:\Program Files (x86)\nodejs\` used to be on the PATH and no longer is.

I don't know when/how that changed and we will investigate. In the meantime, here is a workaround for you, which I already applied to the dev site, and verified that it fixed the build. Under `d:\home\site`, create an `applicationhost.xdt` file with the following content:

```xml
<?xml version="1.0"?> 
<configuration xmlns:xdt="http://schemas.microsoft.com/XML-Document-Transform"> 
  <system.webServer> 
    <runtime xdt:Transform="InsertIfMissing">
      <environmentVariables xdt:Transform="InsertIfMissing">
        <add name="PATH" value="%PATH%;%ProgramFiles(x86)%\nodejs\" xdt:Locator="Match(name)" xdt:Transform="InsertIfMissing" />    
      </environmentVariables>
    </runtime> 
  </system.webServer> 
</configuration> 
```

That will restore the missing path and should make everything work.

**Comment by niemyjski** [comment]
Thanks, is there anything I can do to add this to my deploy.sh script? So all my environments automatically get it?

**Comment by davidebbo** [comment]
Yes, I think you should be able to add it to the path there. e.g. looking at http://unix.stackexchange.com/questions/26047/how-to-correctly-add-a-path-to-path for reference, it should look like:

    PATH=$PATH:/d/Program Files (x86)/nodejs

**Comment by davidebbo** [comment]
If you try this on the dev site, make sure you yank my applicationhost.xdt first (and restart the site) to make sure you're only testing the script change.

**Comment by niemyjski** [comment]
Thanks will do! I really appreciate your help. I'll also update this issue with anything I find.

**Comment by niemyjski** [comment]
Do you have any suggestions for our deploy script that would be a better way to do what we are doing, that wouldn't of relied on the node path?

**Comment by davidebbo** [comment]
Well, this is not a normal situation. Normally, npm should just work and be on the path, so I don't think there is anything wrong with what you're doing.

We need to get to the bottom of what changed on the VM in the way we install npm.

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
