### ISSUE TITLE
Default Web.config errors 500.19 x8007000d

### ISSUE THREAD

**Issue by DavidWhit** [projectkudu/kudu#2178]
Hello, 
  I cannot find a simple solution as everything I followed from the documents using anonymous authentication etc...

The node project is successfully deployed. When trying to access the page I get 500.19 0x8007000d though this is the default web.config created from deployment. If I try to change anything in the IIS manager for the application deployed it errors until I remove/rename the web.config. 

What am I missing???

**Comment by davidebbo** [comment]
What do you mean by IIS manager? Can you try isolating the issue by editing the web.config in Kudu Console till you find the offending piece?

**Comment by DavidWhit** [comment]
So I'm using the default web.config from the push and the web.config matches the default explained here
[https://github.com/projectkudu/kudu/wiki/Using-a-custom-web.config-for-Node-apps](url)

Then to test the file is unable to be read it clicked on authentication and it hangs, but of course if the file is removed this is then accessible.

![iis](https://cloud.githubusercontent.com/assets/3008424/19402325/30be8c02-9226-11e6-8aeb-859caeead5ff.png)

There is no hint as to what the offending piece might be from the error at least with my minimal knowledge of IIS the error code from the explanation is that its malformed, but what part. 

![image](https://cloud.githubusercontent.com/assets/3008424/19402471/d6c80be6-9226-11e6-8e8b-b9d66ae10c72.png)

**Comment by davidebbo** [comment]
Oh, so you're running Kudu locally and not in Azure? I'd still try the isolating step I mentioned above.

**Comment by DavidWhit** [comment]
Yes, I did fail to mention that it was a local build and as suspected there are no errors in the kudu console as my other editor. I'll keep at it

**Comment by DavidWhit** [comment]
Found that going line by line revealed iis 7.5 doesn't have web sockets and the tag <webSocket> was causing the issue.
