### ISSUE TITLE
Microsoft.Data.Tools.Schema.SqlTasks.targets was not found (GitHub deployment)

### ISSUE THREAD

**Issue by brunoligutti** [projectkudu/kudu#2180]
Hi,

I customized the deployment scripts to build and deploy an SSDT project with msbuild.exe. I added this statement:

> call :ExecuteCmd "%MSBUILD_PATH%" "%DEPLOYMENT_SOURCE%\Database.sqlproj" /t:Build /t:Publish /p:SqlPublishProfilePath=Database.Production.publish.xml /p:TargetConnectionString="%DEFAULT_CONNECTION%"

And I get this error:

> error MSB4019: The imported project "D:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\SSDT\Microsoft.Data.Tools.Schema.SqlTasks.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.

I tried setting /property:VisualStudioVersion to 12.0 and 14.0 with no success. I also tried to delete "SET USE_MSBUILD=TRUE" from the deployment script but that statement doesn't exist in the default deployment scripts. [That fix was suggested here.](https://social.msdn.microsoft.com/Forums/lync/en-US/ede9fe01-201e-4b49-b6ae-0d2a74bca033/kudu-github-deployment-fails-ssdt?forum=windowsazurewebsitespreview)

My question is - is this possible at all? Are the other alternatives to deploy an SSDT project?

Thank you!

**Comment by ahmelsayed** [comment]
I'll add the missing target files.

**Comment by ahmelsayed** [comment]
This should be there now. @brunoligutti can you give it a try now?
