### ISSUE TITLE
How to change deployment branch via config file

### ISSUE THREAD

**Issue by cesarvarela** [projectkudu/kudu#2181]
Seen the docs entry that show an example using CURL, but Id' like a config that could be setup using a config file, is it possible?

**Comment by davidebbo** [comment]
If you look at `D:\home\site\deployments\settings.xml` in Kudu Console, there is a setting for the branch. e.g.

```
<?xml version="1.0" encoding="utf-8"?>
<settings>
    <deployment>
        <add key="branch" value="master" />
    </deployment>
</settings>
```
