### ISSUE TITLE
No support for `install.cmd` exists for private extensions

### ISSUE THREAD

**Issue by peterblazejewicz** [projectkudu/kudu#2182]
I've followed Wiki description regarding private extensions:
https://github.com/projectkudu/kudu/wiki/Azure-Site-Extensions
and created a private extension that just install command line tool within website:
https://github.com/peterblazejewicz/ng-cli-extension
The `applicationHost.xdt` transformation is applied to application settings but the `install.cmd` script is not called. 
I was under impression that `install.cmd` script is part of extension feature:
https://github.com/projectkudu/kudu/issues/1193
but this applies only to the extensions from the gallery I think. Shouldn't the same model of install (uninstall) be applied to private extension?
At the moment I have to manually go to Kudu console (after installing extension via d&d) and invoke `install.cmd` manually.

Thanks!

**Comment by davidebbo** [comment]
install.cmd is executed as part of an install from a nuget gallery (which doesn't have to be http://www.siteextensions.net/), and not at runtime. If you install it manually by copying the files, then you'll need to manually set it up in any way that is needed.

**Comment by peterblazejewicz** [comment]
Thanks!
