### ISSUE TITLE
Weird RenderBody() if/else call in layout page

### ISSUE THREAD

**Issue by peterblazejewicz** [projectkudu/kudu#2183]
The `_Layout.cshtml` contains this weird code if/else logic:
```cshtml
      @if (!showWarning)
      { 
          @RenderBody()
      }
      else 
      {
          RenderBody();
      }
```
https://github.com/projectkudu/kudu/blob/master/Kudu.Web/Views/Shared/_Layout.cshtml#L79-L86
(there could be the reason behind this code though, I'm new to ASP.NET)
Thanks!

**Comment by davidebbo** [comment]
Yes, that looks very strange. Looking at history, it dates back to a 2012 change by @davidfowl! f862a861b6cbeda2d506166f9ab693c4e4c8b036.

I don't get it, but it's probably best to leave it alone :)

**Comment by peterblazejewicz** [comment]
@davidebbo Actually I've scanning a code to find a current Kudu home page for *.scm.* website (which I found in other folder). This  Kudu.Web looks like different one - is it still used somewhere?

**Comment by davidebbo** [comment]
What you want is Kudu.**Services**.Web. Closing this since we'll probably not fix it.
