### ISSUE TITLE
Unexpected number selectNodeVersion.js Node js deployment error on Azure

### ISSUE THREAD

**Issue by VishalGulati** [projectkudu/kudu#2192]
Facing error :

undefined:5
-    "node": "6.2.1"
^
An error has occurred during web site deployment.
SyntaxError: Unexpected number

While deploying Angular2 website on Azure. The error seems to happen in package.json where I have mentioned the node version explicitly. PFB the detailed snapshot:

![image](https://cloud.githubusercontent.com/assets/14342323/19643527/6d4db082-9a08-11e6-8d30-bb9d3c5acd04.png)

**Comment by davidebbo** [comment]
Please include a sample repo as described in [this page](https://github.com/projectkudu/kudu/wiki/Using-a-git-repo-to-report-an-issue).

Also, please include the error you are getting as text instead of bitmap, as that makes it easier to work with (search, copy, etc...).

**Comment by davidebbo** [comment]
Closing until we get repro app.
