### ISSUE TITLE
Linux: Sync/deploy fails when PROJECT app setting is set

### ISSUE THREAD

**Issue by jcorioland** [projectkudu/kudu#2193]
Hi,

When using the PROJECT variable in app settings in a Web App On Linux, I get the following error message during the deployment :

“Only paths relative to the repository root path are supported, path provided: '/home/site/repository/src/ShopFront' is not a child folder of '/home/site/repository'”

Repro steps:
- Fork https://github.com/jcorioland/MyShop-NodeJS
- Configure Github CI on the Web App on Linux
- Specify the "src/ShopFront" for the PROJECT application settings
- Ask for a new source control synchronization
- Go to the Kudu deployment logs to see the above message

Thanks

**Comment by nzthiago** [comment]
It seems that any value that gets entered in the PROJECT app setting will cause this issue on the Linux Web App. In my case our web app code is under a webapp folder and any value I use (like webapp, /webapp, and several other attempts) still shows the same error:
Only paths relative to the repository root path are supported, path provided: '/home/site/repository/home/site/repository/webapp' is not a child folder of '/home/site/repository'

@davidebbo any ideas?

**Comment by davidebbo** [comment]
Yes, I think @nickwalkmsft is aware of these Linux path handling issues.

**Comment by nickwalkmsft** [comment]
I changed the name on this issue to better reflect the overall problem.

Working on a fix.

**Comment by nickwalkmsft** [comment]
Getting a fix in for this specific issue, but I still have a todo item to scour the rest of the codebase looking for obvious path handling problems on Linux (hardcoded slashes, etc.).

I don't have an ETA for when this will be rolled out to production Linux apps.

@nzthiago, regarding exactly what the value of PROJECT should be, it should be as it is in @jcorioland's repro. It sounds like it would just be "webapp" in your case.

**Comment by fcatae** [comment]
I also ran into this issue: "Only paths relative to the repository root path are supported, path provided: '/home/site/repository/src/Arda.Main' is not a child folder of '/home/site/repository'". In my case, I have a repository with many projects, and the deployment option points to startup project. 
Do we have any workaround?

**Comment by nickwalkmsft** [comment]
Hi @fcatae,

Only workaround at this point is not to use PROJECT. The next update of Kudu for App Service on Linux should include this fix.

**Comment by fcatae** [comment]
Thanks @nickwalkmsft

**Comment by nickwalkmsft** [comment]
Fix is live, PROJECT can now be used on App Service on Linux.
