### ISSUE TITLE
app service environment: kudu console has node 0.10 installed

### ISSUE THREAD

**Issue by jonathanong** [projectkudu/kudu#2194]
created a new app, and hit the following issues:
- would not deploy. difficult to see what the error is on the azure portal
- d/c and re-synced a couple of times to no avail.
- went into the kudu console. seems like node 0.10 is being used there
- i have no idea how to change the node version
- i ran `npm i -g npm@3`, but it did not update npm
- i cannot install my app because it's built with node@6

however, my app works fine in regular app services, just not this new app service environment i just created

**Comment by davidebbo** [comment]
Node version is controlled by the `WEBSITE_NODE_DEFAULT_VERSION` app setting. After creating your app on your App Service Environment, can you check whether you have this set? Also, how specifically did you create the app (e.g. portal, ARM template, etc...)

**Comment by jonathanong** [comment]
yes, i set it to 6.9.1 via Azure CLI.

it works now... i think after pressing "sync" a couple of times

**Comment by davidebbo** [comment]
I'm guessing it's an App Service on Linux quirk not directly related to Kudu, so closing here.

**Comment by jonathanong** [comment]
no, its on windows. i don't use linux on azure at all because it's not available on all regions

**Comment by davidebbo** [comment]
I'm sorry, was looking at two issues and wires got crossed in my head! :)

So if you just create an App in your ASE and go to Kudu console, it starts out with the wrong Node version that doesn't reflect `WEBSITE_NODE_DEFAULT_VERSION`?

**Comment by jonathanong** [comment]
![screen shot 2016-10-25 at 11 38 59 am](https://cloud.githubusercontent.com/assets/643505/19699419/23d09c76-9aa8-11e6-92ab-bea4d99c71db.png)
![screen shot 2016-10-25 at 11 42 11 am](https://cloud.githubusercontent.com/assets/643505/19699420/23d8c252-9aa8-11e6-8764-45d6d2264152.png)

let me know if i'm using kudu incorrectly!

**Comment by davidebbo** [comment]
Can you clarify the exact steps that lead to this? How are you creating the Web App?

Also, in Kudu, you can click on the Environment tab to see the env. Here, check the value of `WEBSITE_NODE_DEFAULT_VERSION` when you're in that state.

**Comment by jonathanong** [comment]
> Can you clarify the exact steps that lead to this? How are you creating the Web App?

1. i created an app service environment
2. created an app
3. set deployment via GitHub (note: this is super buggy - fails half the time i try to setup apps using regular app services. i usually need to set it twice because it didn't save the first time or sync multiple times like in this case)
4. set configs via CLI (how i scripted deployments as its easier than templates)
5. set a few configs via UI
6. noticed that it did not deploy. noticed that the error was that one of the node modules were not installed. tried to go into Kudu to install everything manually, but noticed this error.
 7. kept pressing "sync deployment" until it finally worked, but Kudu's version is still wrong

![screen shot 2016-10-25 at 11 52 26 am](https://cloud.githubusercontent.com/assets/643505/19699790/889053da-9aa9-11e6-86b4-ecd6d2c23921.png)

**Comment by davidebbo** [comment]
Please help me isolate this with these very simple steps:

- Create a fresh new app in your ASE. **Don't deploy anything or do any other steps**
- Go to Kudu Console and check whether `WEBSITE_NODE_DEFAULT_VERSION` matches what you see in Portal, and whether node.exe has the right version

Then based on the outcome of this smaller test, we figure out the next step.

**Comment by jonathanong** [comment]
yup. the new one matches versions.

i think it's because i set it to v6.9.1, which is the latest LTS version. do you guys not support the latest LTS versions of node.js? imo, if all fails, it should default to an LTS version of node.js v0.10 is way too old

**Comment by davidebbo** [comment]
Ah, sorry, I missed that you were trying v6.9.1! Right now, we have v6.9.0 but not yet 6.9.1. Can you try that for now?

**Comment by davidebbo** [comment]
And yes, you're right that the fallback logic is not ideal.

**Comment by jonathanong** [comment]
yep that works! also, an error message saying that the env var is invalid would be great too :)

**Comment by xt0rted** [comment]
I've run into this issue a few times as well. It'd be nice if there was a check in place so if you try to set `WEBSITE_NODE_DEFAULT_VERSION` to a version not available on your VM then it gives you an error, or at the very least a warning.

**Comment by davidebbo** [comment]
It's pretty hard to give a warning at the time you set the App Setting, because it's just a dump app setting that no one looks at until it comes alive when the site starts. But at that point it's not clear how we would convey the warning.

I think if we could change the behavior to use the closest available version, that might just be good enough.

**Comment by jonathanong** [comment]
If "closest" is too hard, I'd be okay with "the latest version with the same major"

**Comment by davidebbo** [comment]
Fair.

As an aside, 6.9.1 is now available. Also 7.0.0 if you're the adventurous type :)

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
