### ISSUE TITLE
GetTriggers needs to honor host.json Functions filter

### ISSUE THREAD

**Issue by mathewc** [projectkudu/kudu#2195]
`FunctionManager.GetTriggers` needs to honor the `host.json` functions array if specified (in [this](https://github.com/projectkudu/kudu/blob/master/Kudu.Core/Functions/FunctionManager.cs#L77) code).

The relevant corresponding code in `ScriptHost` where we only load filtered functions is [here](https://github.com/Azure/azure-webjobs-sdk-script/blob/dev/src/WebJobs.Script/Host/ScriptHost.cs#L589).

**Comment by davidebbo** [comment]
Fixing the code links to not float (please make sure you always hit 'y' when getting code links):

- [kudu](https://github.com/projectkudu/kudu/blob/75df0e3380a9191b6373eced9f08f15e4092d347/Kudu.Core/Functions/FunctionManager.cs#L77)
- [scripting](https://github.com/Azure/azure-webjobs-sdk-script/blob/194f961f2f539e2c1b7a857d4735c46a9791c001/src/WebJobs.Script/Host/ScriptHost.cs#L589)

**Comment by davidebbo** [comment]
Do we have portal UI that sets this functions array in host.json? How does one do that?

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
