### ISSUE TITLE
PUT /api/triggeredjobs/{jobname} removes existing files 

### ISSUE THREAD

**Issue by anblanco** [projectkudu/kudu#2202]
Reviewing the documentation here https://github.com/projectkudu/kudu/wiki/WebJobs-API

These two should be equivalent
PUT /api/zip/site/wwwroot/App_Data/jobs/triggered/{job name}/
which uses this ZIP API https://github.com/projectkudu/kudu/wiki/REST-API
and
PUT /api/triggeredwebjobs/{job name}

What I've noticed is that the ZIPAPI will PUT the contents on top of the webjob, but will not delete any existing files. However, the /api/triggeredwebjobs/ API will overwrite the entire directory and delete existing files.

For context: I was trying to figure out how to update only a single set of files in a webjob, such as adding newer versions of DLL's to an existing web job without updating its app.config. 

The workaround for me is to use the ZIP API, but I would have expected these APIs to behave the same given the same use of the PUT verb.

**Comment by davidebbo** [comment]
Indeed, the behavior is different. The [code](https://github.com/projectkudu/kudu/blob/121eef5fe9f1d987bc0662eee72ca166cfdcb5c0/Kudu.Core/Jobs/JobsManagerBase.cs#L168-L173) in the `/api/triggeredwebjobs/` does attempt to delete existing files.

I added a note in the wiki.
