### ISSUE TITLE
Redeploy (PUT /api/deployment/{id}) does not perform autoswap

### ISSUE THREAD

**Issue by suwatch** [projectkudu/kudu#2208]
Issue was reported by customer.   We simply forgot to add codes to do it for [this scenario](https://github.com/projectkudu/kudu/blob/master/Kudu.Services/Deployment/DeploymentController.cs#L155).   

See [This](https://github.com/projectkudu/kudu/blob/master/Kudu.Console/Program.cs#L162-L171) for the correct implementation.

**Comment by suwatch** [comment]
@davidebbo you know any explicit decision we made not to auto swap for redeploy scenario?   it seems like blatant missing codes and just want to make sure we didn't do this on purpose.

**Comment by davidebbo** [comment]
Thinking through it, it does feel like absolutely the correct thing to do. I can't recall any prior discussion about specifically leaving out that scenario, so I suspect it's an omission.

**Comment by siroky** [comment]
Hi, I believe I'm the customer who reported this issue to Azure support. If you need any further info, feel free to contact me.

**Comment by suwatch** [comment]
@siroky Thanks for reporting.  We will likely roll the fix out tomorrow.  Once done, it would be great if you could verify and confirm if indeed working.

**Comment by davidebbo** [comment]
The fix is deployed. Please give it a try and let us know!

**Comment by siroky** [comment]
Thanks. When there will be an opportunity to test it (e.g. some unexpected nondeterministic error during build which forced us last time to "Redeploy"), I'll be keeping eye on it and let you know in case it doesn't work as expected.

**Comment by suwatch** [comment]
I just verified on my site and slot and it worked.
