### ISSUE TITLE
Different nodejs versions depending on console

### ISSUE THREAD

**Issue by johnknoop** [projectkudu/kudu#2209]
I have a .NET app service which uses some nodejs scripting as part of the deploy process. I've been fiddling around in the different consoles that are available in and around the Azure Portal, and I get a different nodejs version depending on the console I'm in.

If I goto portal.azure.com and navigate to my app service and click "console", then "node -v" returns v4.4.7. If I do the same thing in the Kudu debug console, I also get v4.4.7. But in the new "App Service Editor", there is also a console, and typing "node -v" in that one yields v0.10.29. The current directory in all three cases is D:\home\site\wwwroot.

Any ideas? It's like the nodejs version setting for the app service has no effect in the new App Service Editor.

**Comment by davidebbo** [comment]
App Service Editor is not part of Kudu, so not exactly the right place. @mamaso, I think this came up before. Do you remember where we left that?

**Comment by mamaso** [comment]
Node is configured in a different way from other commands (it uses process.execPath), I'll make it into a configuration setting have it do the same environment variable / package.json snooping we do for npm version

**Comment by davidebbo** [comment]
Fixed now!
