### ISSUE TITLE
Web app reports using 2GB disk when I can find only 190MB

### ISSUE THREAD

**Issue by jojjesan** [projectkudu/kudu#2211]
I am getting errors deploying with Git deploy saying the web app is running out of disk space. It is a simple .NET 4.5.2 webapi app. I have been trying to find where this disk space is used, using the scm cmd prompt and also the extension "Azure Web Apps Disk Usage". As far as I can see only 190 MB is used, but the Environment page shows 2048 MB used. dir reports 190 MB used and 11 MB free. See screendumps for details: https://docs.google.com/document/d/1_GPVFIXlKo9xjL5ANpXyScZYRNCGXQZZsvnTWs2T7hA/edit?usp=sharing

Any idea what is going on here?

**Comment by davidebbo** [comment]
Is this in a Free site? What is the exact failure? You need to figure out if this relates to temp space or persisted state (infor [here](https://github.com/projectkudu/kudu/wiki/Azure-runtime-environment#file-system)).

**Comment by jojjesan** [comment]
Than you for the quick reply! It's in a Shared site. All of "D:\local" adds up to ~193 MB. All of "d:\home" holds ~198 MB. Anywhere else I need to look?

**Comment by davidebbo** [comment]
Can you check which of the two is hitting a limit, e.g. by manually trying to add files from Kudu Console?

**Comment by jojjesan** [comment]
As far as I can see from the logs it is D:\home that is hitting the limit:

D:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(3962,5): warning MSB3026: Could not copy "D:\home\site\repository\solutions\packages.not-nuget\Sef.Platform.Utilities\Sef.Platform.Utilities.Core.pdb" to "bin\CI\Sef.Platform.Utilities.Core.pdb". Beginning retry 10 in 1000ms. There is not enough space on the disk. [D:\home\site\repository\UnitTests\UnitTests.csproj]

**Comment by jojjesan** [comment]
I solved this problem now.  I had a number of web apps on the same app service plan and they obviously shared the disk resource. This is kind of strange because you pay per site per hour, so it doesn't cost you  more to have a separate app plan for each app. At least this is how I think it works... :)

**Comment by davidebbo** [comment]
Actually, you pay per App Service Plan and not per site (assuming you're using Basic, Standard or Premium). So the shared disk space does make sense. See https://azure.microsoft.com/en-us/pricing/details/app-service/

**Comment by jojjesan** [comment]
![image](https://cloud.githubusercontent.com/assets/5682044/19969155/d1751d6c-a1d7-11e6-8d74-1680a2655854.png)
Well, but as far as I can see this is not the case for Shared, se image. This is also what I see on my bill. I pay for each app hour.

**Comment by davidebbo** [comment]
Sorry, I missed that you were using Shared. I didn't realize disk space was shared in that case. I agree it doesn't seem to make sense. I'll ask around.
