### ISSUE TITLE
Deployment Branch App setting being removed

### ISSUE THREAD

**Issue by tbertenshaw** [projectkudu/kudu#2212]
The first time i thought it was me however its happened twice now.

I am using Gitlab backed deployment for one of my deployment slots `dev`  I configured it to pull from the develop gitlab branch by setting an  Azure `Application setting` of 

> deployment_branch  = 'develop'
_with slot setting ticked_

twice now after a few days of working ok, i have pushed to the develop gitlab branch and then some minutes later browsed the site and found master content on the dev site.  Both times i have found this setting missing. I'm not sure what is removing the setting. But can only assume its comething in the kudu deployment process which is resetting it?

**Comment by davidebbo** [comment]
There is nothing Kudu can do to modify Azure App Settings. To make sure there is no misunderstanding, are you talking about the Azure App Settings that you see in the Azure Portal?

**Comment by tbertenshaw** [comment]
yeah @davidebbo . Very strange, not sure how it could have happened. Unless its something weird related to the unusual gitlab setup required and/or the recent extended downtime. In both cases the setting was missing. i.e. not even a property there. I have another slot `UAT `which i put a value as helow

`deployment_branch = 'master'`

this slot still has this value since i originally configured it. The difference however is i haven't done the other necessary configuration for it to connect to gitlab. (i was waiting till i had the configuration for the typescript build etc correct for `dev `before it set `uat `up)

**Comment by davidebbo** [comment]
And are you using auto-swap?

**Comment by tbertenshaw** [comment]
no, just using the slots for testing, doing a manual webdeploy from visual studio for the main site slot

So the main site, and two slots  `dev`, and `uat`, with dev being the onkly slot with gitlab Continuous deployment.

**Comment by davidebbo** [comment]
Next time, you push, can you check that the branch is correct before the push? This will help isolate between:

- Some random other thing is removing your branch
- The deployment is doing it

Also, try adding some random other dummy app setting, so see if it disappears as well.

Somehow I have this deja vu that someone reported something similar before, but I can't located or recall where that went.

**Comment by chrisfoster78** [comment]
We've also experienced removed application settings.  It's just happened again after a website restart.  Appears to be the same as this issue: https://github.com/projectkudu/kudu/issues/1591

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
