### ISSUE TITLE
Not possible anymore to deploy a sln which also contains a new project.json .net core project ?

### ISSUE THREAD

**Issue by StefH** [projectkudu/kudu#2213]
I'm not sure if this is the correct entry point to ask a questions, but I noticed that's not possible anymore to deploy a webjob from github if the project contains a `project.json` .net core project.

It seems that **msbuild** is not executed ?

See error messages below: (The error message is caused because the `KendoGridBinderEx `project is not build ?

> Adding package 'KendoUIWeb.2014.1.318' to folder 'D:\home\site\repository\packages'
> Added package 'KendoUIWeb.2014.1.318' to folder 'D:\home\site\repository\packages'
> Restoring packages for D:\home\site\repository\KendoGridBinderEx\project.json...
> Committing restore...
> Writing lock file to disk. Path: D:\home\site\repository\KendoGridBinderEx\project.lock.json
> D:\home\site\repository\KendoGridBinderEx\KendoGridBinderEx.xproj
> Restore completed in 968ms.
> 
> NuGet Config files used:
>     C:\DWASFiles\Sites\#1stef-kendogridbinderex\AppData\NuGet\NuGet.Config
> 
> Feeds used:
>     https://api.nuget.org/v3/index.json
> 
> Installed:
>     46 package(s) to packages.config projects
> D:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1819,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "KendoGridBinderEx". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors. [D:\home\site\repository\KendoGridBinderEx.Examples.Business\KendoGridBinderEx.Examples.Business.csproj]
> QueryContext\QueryContext.cs(43,73): error CS0246: The type or namespace name 'KendoGridBaseRequest' could not be found (are you missing a using directive or an assembly reference?) [D:\home\site\repository\KendoGridBinderEx.Examples.Business\KendoGridBinderEx.Examples.Business.csproj]
> QueryContext\QueryContext.cs(43,16): error CS0246: The type or namespace name 'KendoGridEx<TEntity, TViewModel>' could not be found (are you missing a using directive or an assembly reference?) [D:\home\site\repository\KendoGridBinderEx.Examples.Business\KendoGridBinderEx.Examples.Business.csproj]
> QueryContext\IQueryContext.cs(18,66): error CS0246: The type or namespace name 'KendoGridBaseRequest' could not be found (are you missing a using directive or an assembly reference?) [D:\home\site\repository\KendoGridBinderEx.Examples.Business\KendoGridBinderEx.Examples.Business.csproj]
> QueryContext\IQueryContext.cs(18,9): error CS0246: The type or namespace name 'KendoGridEx<TEntity, TViewModel>' could not be found (are you missing a using directive or an assembly reference?) [D:\home\site\repository\KendoGridBinderEx.Examples.Business\KendoGridBinderEx.Examples.Business.csproj]
> Failed exitCode=1, command="D:\Program Files (x86)\MSBuild\14.0\Bin\MSBuild.exe" "D:\home\site\repository\KendoGridBinderEx.Examples.MVC\KendoGridBinderEx.Examples.MVC.csproj" /nologo /verbosity:m /t:Build /t:pipelinePreDeployCopyAllFilesToOneFolder /p:_PackageTempDir="D:\local\Temp\8d4047cf48f3562";AutoParameterizationWebConfigConnectionStrings=false;Configuration=Release;UseSharedCompilation=false /p:SolutionDir="D:\home\site\repository\.\\"
> An error has occurred during web site deployment.
> \r\nD:\Program Files (x86)\SiteExtensions\Kudu\59.51102.2512\bin\Scripts\starter.cmd "D:\home\site\deployments\tools\deploy.cmd"

I don't see any **msbuild** commands, only _restore_ ?

**Comment by davidebbo** [comment]
When you say 'not possible anymore', do you mean that the exact same scenario used to work and no longer does? Or that you had not tried it before on solutions that also have a project.json?

Note that project.json is on its way out with the new Core tooling.

**Comment by StefH** [comment]
Yes sorry for the vague description, but indeed it did work fine for several years/months and all of a sudden, it did not work anymore.

Can you indicate which log files I can review in kudo which show some more details?

**Comment by tbolon** [comment]
I has a problem which seems to cause the same errors. I have opened a bug on [nuget](https://github.com/NuGet/Home/issues/3898#issuecomment-259511042).

My workaround was to add a `.deployment` file with my specific project, because the problematic project.json was only used on a test project not necessary for my website.

**Comment by watashiSHUN** [comment]
@StefH does this issue still persist? 

Can you share a [github repository](https://github.com/projectkudu/kudu/wiki/Using-a-git-repo-to-report-an-issue) that highlights your project structure so that I can try to reproduce the issue at my end, thanks

**Comment by StefH** [comment]
This one:
https://github.com/StefH/KendoGridBinderEx/tree/master/KendoGridBinderEx.Examples.MVC

**Comment by watashiSHUN** [comment]
I just submitted a [pull request](https://github.com/StefH/KendoGridBinderEx/pull/19), it should work for you
build in Azure is different than build in VS, you probably build your entire solution (all projects) locally whereas Azure only build what's necessary (**the web project and projects it depends on**)

in your case, `KendoGridBinderEx.Examples.MVC.csproj` is the one argument consumed by `msbuild` and inside this `csproj` file, it references `KendoGridBinderEx.Examples.Business.csproj` (so `msbuild` knows it needs to build this reference)
> I don't see any msbuild commands, only restore ?

to answer your question, the error message you are seeing here:

> D:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1819,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "KendoGridBinderEx". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors. [D:\home\site\repository\KendoGridBinderEx.Examples.Business\KendoGridBinderEx.Examples.Business.csproj]

is the output of `msbuild KendoGridBinderEx.Examples.Business.csproj`, it is complaining that you referenced `KendoGridBinderEx.dll` but this file is missing. The solution it simply **tell `msbuild` that it needs to build this assembly itself**

**Comment by StefH** [comment]
This PR solved my issue.

Thanks for your help.
