### ISSUE TITLE
Nodejs and NPM version settings not respected?

### ISSUE THREAD

**Issue by johnknoop** [projectkudu/kudu#2214]
Hi

I've set the **WEBSITE_NODE_DEFAULT_VERSION** setting to **4.4.7** and **WEBSITE_NPM_DEFAULT_VERSION** to **3.10.9**. This had to be done to make my gulp script run.

This worked for a couple of days, until today. Now, when by deployment runs, I get an error during NPM install, and I see this in the error message:

```
npm ERR! node -v v4.4.7
npm ERR! npm -v 1.1.37
```

This happened once before, but I was able to remedy it by opening the console and run **npm install npm -g** and after that the deploy will work. This workaround has solved the issue until today. This time, the **npm install npm -g** doesn't even work. This is what I see in the console:

```
> npm install npm -g
D:\home\site\wwwroot
npm http GET https://registry.npmjs.org/npm
npm http GET https://registry.npmjs.org/npm
npm http GET https://registry.npmjs.org/npm
npm ERR! Error: SSL Error: CERT_UNTRUSTED
npm ERR!     at ClientRequest.<anonymous> (D:\Program Files (x86)\nodejs\node_modules\npm\node_modules\request\main.js:440:26)
npm ERR!     at ClientRequest.g (events.js:156:14)
npm ERR!     at ClientRequest.emit (events.js:67:17)
npm ERR!     at HTTPParser.parserOnIncomingClient [as onIncoming] (http.js:1256:7)
npm ERR!     at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:91:29)
npm ERR!     at CleartextStream.socketOnData [as ondata] (http.js:1288:20)
npm ERR!     at CleartextStream._push (tls.js:375:27)
npm ERR!     at SecurePair.cycle (tls.js:734:20)
npm ERR!     at EncryptedStream.write (tls.js:130:13)
npm ERR!     at Socket.ondata (stream.js:38:26)
npm ERR!  [Error: SSL Error: CERT_UNTRUSTED]
npm ERR! You may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Windows_NT 6.2.9200
npm ERR! command "D:\\Program Files (x86)\\nodejs\\\\node.exe" "D:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "npm" "-g"
npm ERR! cwd D:\home\site\wwwroot
npm ERR! node -v v0.6.20
npm ERR! npm -v 1.1.37
npm ERR! message SSL Error: CERT_UNTRUSTED
```

It looks like the nodejs version isn't 4.4.7 but 0.6.20. But when I run **node -v** it says "v4.4.7".

Not really sure whats going on here. On top of the issue with the npm version being reset, this new issue prevents me from deploying.

**Comment by davidebbo** [comment]
I think problem might be that we don't have 3.10.9, but we have 3.10.8. Note that 3.10.8 is the official build that both Node 6.9.1 and 7.0.0 (the very latest) are using, Can you try that?

**Comment by johnknoop** [comment]
I changed the NPM version to 3.10.8 and this time it worked. However, I'm puzzled as to how it could work before, when I had entered 3.10.9, when there is no such version. And I'm pretty sure I got that version number from doing an "npm install npm -g" and see what version I got.

Anyway, I'll close this issue, and if the problem arises again I'll reopen it.

Thanks!

**Comment by davidebbo** [comment]
That's highly puzzling. Let's pretend it didn't happen :)
