### ISSUE TITLE
How to call jspm install for asp netcore app

### ISSUE THREAD

**Issue by dazinator** [projectkudu/kudu#2218]
Hello,

When kudo restores my asp.net core project, I have a couple of scripts that fire to restore npm packages, and restore jspm packages.

Here is the scripts section in project.json:

```
"scripts": {
    "prerestore": [ "npm install", "jspm install" ],
```

The problem is, `jspm install` fails, because JSPM isn't available on the system PATH.

What's the correct way to get Kudo to restore JSPM packages during the build of a asp.net core project?

**Comment by ahmelsayed** [comment]
You can add jspm to your npm dependencies, and then you can use `npm run jspm install`

**Comment by dazinator** [comment]
Thanks @ahmelsayed .

I tried adding this a `postrestore` step in project.json file:

```
  "scripts": {
    "postrestore": [ "npm install", "npm run jspm install" ],

```

But that seemingly never runs when you do a `dotnet restore`

I guess it's related to this: https://github.com/dotnet/cli/issues/3436

Does Kudo manually do an `npm install` then? I always thought kudo was just doing a `dotnet restore` and the scripts in the `project.json` were meant to do the `npm install` etc but it doesn't look that way from what I can tell!

**Comment by dazinator** [comment]
Also any idea why `npm run jspm install` wouldn't work when ran locally? I get this output:


![image](https://cloud.githubusercontent.com/assets/3176632/20153528/06ee8ac2-a6bb-11e6-9c7d-28085522b8a6.png)

Is this because I have to do some additional setup / config in Package.json to get this command to run perhaps?

**Comment by dazinator** [comment]
Ok I have found that after the `npm install`, `npm. run jspm` doesn't work, but I can change into the local `node_modules\.bin\` directory, and from there I can run `jspm.cmd install`

Sadly I can't get this to happen when a `dotnet restore` occurs due to that bug I linked earlier. But I am hoping I can just chuck these commands into the `.deployment` file.

**Comment by dazinator** [comment]
Ok so now i'm completely stuck.

I'm just trying to do an `npm install` of my websites packages, as this will ensure `jspm` is installed, which I was then going to try and call.

I put this in my `deployment.cmd` to do the `npm install`:

:: Restore npm packages
echo Restoring Website Npm Packages
cd "D:\home\site\repository\src\DnnManager.Website\"
call npm install

```

Here is the output from kudo build:

```
Feeds used:
    https://api.nuget.org/v3/index.json
Restoring Website Npm Packages
npm ERR! Windows_NT 6.2.9200
npm ERR! argv "D:\\Program Files (x86)\\nodejs\\4.4.7\\node.exe" "D:\\Program Files (x86)\\npm\\2.15.8\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v4.4.7
npm ERR! npm  v2.15.8
npm ERR! path D:\home\site\repository\src\DnnManager.Website\node_modules\jspm\node_modules\liftoff\node_modules\fined\node_modules\parse-filepath\node_modules\is-absolute\node_modules\is-relative\node_modules\is-unc-path\node_modules\unc-path-regex\package.json.2149244318
npm ERR! code EINVAL
npm ERR! errno -4071
npm ERR! syscall rename

```

Any ideas why an `npm install` would fail? I take it I must be doing it wrong but I am not sure how else to do it :-/

**Comment by dazinator** [comment]
Doh ok so this issue is tracked under #1696

**Comment by dazinator** [comment]
I now pronounce my endeavour to use kudo to do simple package restore step a resounding failure. Time to go back to committing my packages to source control!

**Comment by ahmelsayed** [comment]
Hi @dazinator sorry for the delay in responding I was pretty busy today with few other issues.
I guess I thought `npm run jspm install` should magically work, but that's not correct, you need this in your `package.json`

```json
{
    "scripts": {
        "jspm": "jspm"
    },

}
```

so a simple `package.json` that achieves that would look like this

```json
{
  "scripts": {
    "jspm": "jspm"
  },
  "dependencies": {
    "jspm": "^0.16.47"
  }
}
```

then you will be able to do `npm run jspm install`

a small gotcha is if you want to run any jspm commands that take an option with a - this won't work, but you can map a script for it. For example

```json
{
  "scripts": {
    "jspm:i": "jspm install",
    "jspm:id": "jspm install --dev"
  },
  "dependencies": {
    "jspm": "^0.16.47"
  }
}
```

and now you can do `npm run jspm:i` (which will be jspm install) and `npm run jspm:id` which will be jspm install --dev and so on

**Comment by dazinator** [comment]
Thank you so much for your help.

I'm sure this will work a treat (works locally!) but sadly because 'npm install' fails on kudo (hits some max windows path length issue I linked to earlier) I can't actually verify it. Still that's a separate issue with npm on windows, so I'll close this now - thanks for figuring this out!

**Comment by ahmelsayed** [comment]
one thing you can try is to move to a 3.x version of npm? they are supposed to better handle longer paths on windows. You can get that by setting `WEBSITE_NPM_DEFAULT_VERSION` to `3.9.5` for example.
