### ISSUE TITLE
Remove temp synctriggers route

### ISSUE THREAD

**Issue by davidebbo** [projectkudu/kudu#2221]
464b0a68066b4e5e58789fb2b8af593dcf04edb6 adds a couple things needed for a workaround, that probably won't be needed later and should be cleaned up.

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
