### ISSUE TITLE
azure site is not an azure command

### ISSUE THREAD

**Issue by dazinator** [projectkudu/kudu#2222]
I'm attemtping to generate the default deployment script for my kudo deployment.
I just want to run an additional command at the start of the deployment.

I tried following [the wiki](https://github.com/projectkudu/kudu/wiki/Deployment-hooks) and that mentions to use the azure cli tool, specifically the `azure site deploymentscript [options]` command in order to generate the script - however I don't appear to have such a command available

The output of `azure site deploymentscript -h` is:

![image](https://cloud.githubusercontent.com/assets/3176632/20154266/7d180d2e-a6be-11e6-922b-7197ea846b6b.png)

I have already done an `azure login` and authenticated, but the `azure site` command still isn't anywhere to be seen.

How do I go about getting this to work! Am i doing something wrong?

**Comment by davidebbo** [comment]
Wrong repo. I think you want https://github.com/Azure/azure-xplat-cli

**Comment by davidebbo** [comment]
Well, the problem is clean, you need to set it to asm mode instead of arm.

**Comment by dazinator** [comment]
Ah Thanks, will try that.

**Comment by davidebbo** [comment]
Specifically, run: `azure config mode asm`.

**Comment by dazinator** [comment]
Yup cheers. That's quite an interesting CLI capable of being 2 different CLI's in one it seems ;-) In the end I found the kudo user interface method to get the deployment scripts. Much easier :-)

**Comment by pvasek** [comment]
@davidebbo Thanks, it works perfectly. Anyway, I think it would make sense to update the wiki page. Not sure how to contribute to the wiki, I created this change here:

https://github.com/pvasek/kudu-wiki/pull/1 

If you should do that in any other way, please let me know.

**Comment by davidebbo** [comment]
Merged, thanks!
