### ISSUE TITLE
Continuous deployment using Resource Explorer - OAuthException

### ISSUE THREAD

**Issue by neusamir** [projectkudu/kudu#2224]
I am trying to use the directions from https://github.com/projectkudu/kudu/wiki/Continuous-deployment to setup continuous deploys from GitHub and it no longer works. We used it a few months ago and it was easy to setup. Now I am getting this error:

> "Repository 'UpdateSiteSourceControl' operation failed with Microsoft.Web.Hosting.SourceControls.OAuthException: GitHub GetRepository: Not Found\r\n   at Microsoft.Web.Hosting.SourceControls.GitHubProxy.<GetRepository>d__1a.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Web.Hosting.Administration.GitHubSiteRepositoryProvider.<UpdateSiteSourceControl>d__6.MoveNext()."

We have multiple deployment slots and it is setup the exact same way for another slot but a different branch and that is working well.

**Comment by davidebbo** [comment]
Are you sure that the configured user is an admin on that repo? What happens if you try to do the same thing from the Azure Portal (using the same identity)?

**Comment by neusamir** [comment]
I am an admin on the private repo but how does the resource manager know what the configured user should be? On the azure portal it lets me log in with my github account but it doesn't show the organization that the repo lives under.

**Comment by davidebbo** [comment]
When you use the OAuth workflow once in the portal, your token gets saved, which is what it ends up using via Resource Explorer (or via ARM in general). You can see the token on https://resources.azure.com/providers/Microsoft.Web/sourcecontrols/GitHub.

Also read through https://github.com/projectkudu/kudu/wiki/Investigating-continuous-deployment

**Comment by neusamir** [comment]
I went through that and still cant see the org that I'm looking for. Maybe because its a private repo and that is the only repo I have access to under that org?

**Comment by davidebbo** [comment]
Were you able to see the token? And were you able to browse to https://github.com/{account}/{repo}/settings/hooks and see the hook UI?

**Comment by neusamir** [comment]
Yes, I see the token, can't really verify if its correct but its there. I can also see the hooks page. Maybe I need some other permissions at the organization level? Right now its saying 'outside collaborator on 1 repository' but I am an admin on the repo itself.

**Comment by davidebbo** [comment]
And you went through the step "Still can't see github org repositories in the drop down" in that doc? Make sure that all the entries that look like "Azure Management Portal" have access to that org.

**Comment by neusamir** [comment]
Yep. Azure Management Portal - Primary, Azure Management Portal 3 (ms.portal) - Primary, Azure Management Portal 3 (ms.portal) - Secondary, Windows Azure; Those all have access.

**Comment by davidebbo** [comment]
Well, then I can't explain it. Maybe try clearing the token in Resource Explorer, in case it's somehow outdated. Then see if you're able to connect to that repo from Portal. It will do a new oauth workflow and should get you a new token.

@suwatch may have other thoughts.

**Comment by suwatch** [comment]
Try what David suggested.   If still not working, share us the site name here or [indirectly](https://github.com/projectkudu/kudu/wiki/Reporting-your-site-name-without-posting-it-publicly).

**Comment by neusamir** [comment]
Tried that and still didnt work. The site starts with 'net' and is in the same resource plan as dummy8080. We are trying to setup the 'rtm' deployment slot.

**Comment by suwatch** [comment]
Taking a look.  BTW, what org do you expect to see and I can cross check with that?

**Comment by neusamir** [comment]
dotnet

**Comment by suwatch** [comment]
I check and the token belongs to your github account (neusamir).  I however can only see 2 repos (neusamir/co**cs and neusamir/vs**cs ).   There is an org (aspnet).   However, you don't seem to be ad "admin" on any of the repos.   You can try the api yourself by "https://api.github.com/orgs/aspnet/repos?access_token=<yourtoken>".   Look for permissions's admin property.

Sorry to say this again, it could mean 2 things 1. you have not yet granted access to the token for the org  2. you are not the admin.   I mentioned you did all these.   The next step is to share the snapshot of the granting - we can look if everything is as expected.

**Comment by neusamir** [comment]
Ok, I can hit the api but I dont see the private repo in there. I see a bunch of other resources under that org but not that one I am interested in.

**Comment by davidebbo** [comment]
Maybe worth starting a github support case to see what they have to say? We're at a point where you see unwanted behavior without involving Azure (using that github api url above).

**Comment by suwatch** [comment]
@neusamir the api is paging based - you will have to look at the LINK response header to get to next page.   Open chrome in incognito and browse again (before doing that making sure you have chrome debug F12 on etc).   Feel free to ping me on twitter @suwat_ch.

@davidebbo there are still things we can still try - then we will escalate.

**Comment by timgabrhel** [comment]
Thought I'd toss this in here just in case it's related. Twice today I saw this error pop up as an alert in the portal while disconnecting a Github CD connection.

>Failed to disconnect from source control: Heuristics indicate WebApiClient request timed out.

**Comment by neusamir** [comment]
Ok, I went through all the pages and still not seeing it.

**Comment by suwatch** [comment]
Let try isolate this.
1. goto https://github.com/settings/tokens and generate a token
2 . iterate thru https://api.github.com/orgs/aspnet/repos?access_token=token_from_above

If there is no secret in your repro, could you make me (suwatch) a reader temporary?  I can check from our side.

**Comment by suwatch** [comment]
@timgabrhel thanks for sharing.  It might be unrelated to this scenario.

**Comment by neusamir** [comment]
Still no luck. I have made you a reader on the repo.

**Comment by suwatch** [comment]
@neusamir forget to ask, could you provide your repo url?   just to be exact.

**Comment by suwatch** [comment]
Nevermind I just saw the invitation in email (https://github.com/dotnet/dot***ite).

**Comment by neusamir** [comment]
Yep, that is the one.

**Comment by suwatch** [comment]
OK .. we know what the issue is (why it did not show up in the list).   When we list repo, we list all repos of the user and repos of the org which user belongs to.   The repo in question is neither.  It is the repo that the user happens to have admin access.   It is our bug and we will fix it.    

Could you help verify one thing?   
1. clone https://github.com/suwatch/AzureSourceControls
2. write console app to call this [ListRepositories](https://github.com/suwatch/AzureSourceControls/blob/master/GitHubProxy.cs#L95).
3. See if the repo in question shows up.

BTW, you should be able to use https://resources.azure.com or PowerShell to work around that.   We can walk you thru if interested.

**Comment by neusamir** [comment]
I tried your test and it only returned the same 2 repos you see if you click on my profile.

I used the resources.azure.com workaround a few months ago but it stopped working for me this time. The error I get using resources.azure.com is in my first post. Maybe there is something I am missing with that also.

**Comment by suwatch** [comment]
Could you try commenting out this [predicate](https://github.com/suwatch/AzureSourceControls/blob/master/GitHubProxy.cs#L455) to return all repos you can see?  

1. check if the repo in question return
2. check repo.permissions

**Comment by neusamir** [comment]
I now see 8 repos, but not the one in question.

**Comment by suwatch** [comment]
@neusamir Could you try generate a new personal token?  But this time, select all options (very powerful token).   And see if it returns the repo + check the permissions property?   I suspect one of the permission is inadequate when we ask for OAuth. 

If you want to help us dive further, trial/error option at a time - and tell us what option does the trick?  I could have tried myself but busy at this time.

To unblock u, browse to https://resources.azure.com/providers/Microsoft.Web/sourcecontrols and set github token with your powerful token.   Go to portal and do the setup continuous again.

**Comment by neusamir** [comment]
Ok, that worked. I was actually already using a powerful token to test and that didnt work but when i regenerated the token it started to work now. Even if I reduce the scope to just 'repo', it now works which is strange. Once the new token was set, the portal still did not pickup the org still. However, I was able to go back to resources.azure.com and update the continuous integration that way and this time it took. The site kicked off the deploy and things are working as expected. Let me know if there is anything else I can do to help you fix the issue.

**Comment by suwatch** [comment]
> Once the new token was set, the portal still did not pickup the org still. 

This is expected due to the bug I mentioned earlier (the repo is neither under your account or org you belong to).   We will fix that.

@Tuesdaysgreen  Elliot, we will need another fix.   See [this](https://github.com/suwatch/AzureSourceControls/commit/40c1ab0c8a5cacaeb67530f8878d22b6f5bc398a) for reference

**Comment by neusamir** [comment]
Oh ok, thanks.

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
