### ISSUE TITLE
Support for more than 199 items

### ISSUE THREAD

**Issue by martinstenhoff** [projectkudu/kudu#2226]
When navigating to D:\home\site\wwwroot we only see the first 199 directories and files.
How would we enable showing all files in a Diagnostic Console in and not just the first 199 items?
For our app (Get-ChildItem c:\MyFolder ).Count returns 210 (in particular we want to be able to easily edit web.config, which is not shown).

**Comment by davidebbo** [comment]
It's an artificial limit we put in to avoid major perf degradations in super large folders, since we don't have any fancy support for paging. We could conceivably raise the limit a bit, but it would take fancier work to properly support arbitrarily large folders.

**Comment by martinstenhoff** [comment]
Paging support would obviously be the ideal solution. But perhaps you can give users a way to define how many items they want to retrieve with a caveat that retrieving large number of items may degrade performance.

Our problem isn't really that we need to see more than 199 items, we just want to be able to see Views folder and web.config, but due to sorting happening before items being displayed they are not among the top 199 items.

Another way would be to somehow provide a filter so users could filter the view to a more manageable set of files and folders, e.g. *.config. Or an exclude filter like *.dll.

We'd be happy with any solution that would allow us to do in-place editing of any text based file in the kudu text editor (without having to copy the file to something with a higher sort order, edit, and then copy back).

**Comment by davidebbo** [comment]
I hear you, I see how this limitation can be annoying. You could also try the App Service Editor, which has fancier UI.

For Kudu, the most low cost approach might be some app setting to set a different size. Or maybe just raise the default to 300, which is even cheaper.

**Comment by davidebbo** [comment]
Let's make this 300 for now and go from there.

**Comment by watashiSHUN** [comment]
@martinstenhoff  Although it's not documented, there is a way to change display limit in current version of kudu for advanced users, you can use [webstorage API](https://developer.mozilla.org/en-US/docs/Web/API/Web_Storage_API/Using_the_Web_Storage_API) to save your own configurations

1. if you are using chrome browser, go to your scm(kudu) site
2. open developer tools (**F12**)
3. in the console, run `window.localStorage['maxViewItems'] = 210` 

and you are done.
let me know if it works for you :)

**Comment by nikitakochar16** [comment]
Hi,

Can anyone tell me if there is anyway to get notification of Kudu log memory before it gets full/about to get full. 

Regards,
Nikita
