### ISSUE TITLE
Recent update to dotnet CLI breaks build

### ISSUE THREAD

**Issue by am11** [projectkudu/kudu#2227]
The version of dotnet CLI I have installed locally is: `1.0.0-preview2-003121`. I have an ASP.NET MVC Core 1.0 app targeting .NET Framework 4.5.1. The solution has other dependency libs targeting same TFM, but those are classy csproj-based project (added to source control via git submodules).

I have auto-deployment setup for this repo and everything was working for past couple of months (since January RC1 days till Nov 9, 2016; last successful build). I have encountered many upgrades RC1->RC2->RTM and each time fixed the problem by searching on Google/GitHub etc.

My dotnet CLI has the same version that we had in our Basic and Shared hosting plans up until very recently, when the version in cloud was bumped to `1.0.0-preview2-1-003155 `.

This caused our app build breakage. I get the following error when `donet build` triggers the csproj dependency projects:

> error MSB4044: The "GenerateDependencyFragmentJson" task was not given a value for the required parameter "CompileItems"

This sting produces zero results on Google, Bing and GitHub.

I only pushed a few lines of Sass and cshtml changes today and found that build now breaks on all hosting plans (we have multiple plans to host different environments of same app).

I know this belongs to Microsoft Azure or .NET team, but if you could help me by:

* pointing to the dontet CLI, nuget 3x or any documentation which explains which magic word to add in csproj/project.json/xproj to get it back to work
OR
* downgrading the dotnet CLI version to `1.0.0-preview2-003121` in cloud via Kudu
OR
* pointing to a person who can give us a tip

that would be highly appreciated. 🍬 🍰 🍕

**Comment by am11** [comment]
Yup, the project has global.json with SDK version. I tried echo `dotnet --version` in the deploy script and it shows `1.0.0-preview2-003121`, while Kudu console showed `1.0.0-preview2-1-003155`.
Even with `1.0.0-preview2-003121` detected by deploy script, the build fails.

I tried pressing Sync button in another web app which was successfully deployed 10 days ago and there aren't any changes in the source control, that failed with the same exact error as well.

> D:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Extensions.targets(17,5): error MSB4044: The "GenerateDependencyFragmentJson" task was not given a value for the required parameter "CompileItems".

Another difference is, on Kudu it shows `msbuld /version` is `14.0.23107.0`, while locally I have `14.0.25420.1`.  But that seems unrelated. Note that I checked the `Microsoft.DotNet.Extensions.targets` file is same as the one I have installed locally with VS2015.

**Comment by davidebbo** [comment]
Any chance you can share a test repo that demonstrates the behavior, per [wiki](https://github.com/projectkudu/kudu/wiki/Using-a-git-repo-to-report-an-issue)? Thanks!

**Comment by am11** [comment]
@davidebbo I have prepared a very quick demo: https://github.com/am11/msbuild-failure.

In `cmd`, with `git` in `PATH`:

```cmd
git clone https://github.com/am11/msbuild-failure
cd msbuild-failure
msbuild
```

Locally with MSBuild `v14.0.25420.1`, it gives:

```cmd
Build succeeded.
    0 Warning(s)
    0 Error(s)
```

on Kudu's cmd with MSBuild `v14.0.23107.0 `, it gives error:

```cmd
"D:\home\demo\msbuild-failure\msbuild-failure.sln" (default target) (1) ->

"D:\home\demo\msbuild-failure\web\web.xproj" (default target) (2) ->

"D:\home\demo\msbuild-failure\lib\lib.csproj" (_GenerateDependencyFragmentJson target) (3) ->

(_GenerateDependencyFragmentJson target) -> 

  D:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Extensions.targets(17,5): error MSB4044: The "GenerateDependencyFragmentJson" task was not given a value for the required parameter "CompileItems". [D:\home\demo\msbuild-failure\lib\lib.csproj]



    0 Warning(s)

    1 Error(s)
```

**Comment by am11** [comment]
Note that with `msbuild /v:diag` (diagnostics mode), it is evident that the version of MSBuild on Kudu failus to enumerate `Task Parameter` -> `CompileItems` for `GenerateDependencyFragmentJson` task.

**Comment by davidebbo** [comment]
I wonder if that's because the default deployment script uses msbuild and not dotnet.exe.

**Comment by am11** [comment]
With mixed solution (csproj, xproj and project.json), msbuild is the only way to build it. With `dotnet build`, we get this: https://github.com/dotnet/cli/issues/2871. 
One workaround is to issue `msbuild` commands for each non-xproj dependency project, then build the runner app with i.e.

```cmd
cd msbuild-failure/lib
msbuild
cd ..
dotnet build web
```

In our real application, where we have multiple nesting and output directory `bin` is common, this approach bring more deliberate arguments adjustments and make our custom deployment script bulky (we have a custom deployment script; derived from the stock one). :)

**Comment by am11** [comment]
Any chance that Azure team roll out the newer msbuild version in the App Service VMs anytime soon? Otherwise, I will add that aforementioned workaround in our custom deployment script.

**Comment by davidebbo** [comment]
Yep, the reason we use msbuild is in fact for the mixed case. Didn't realize that's what you had, but I see it now.

So the theories are:

1. msbuild version is old
2. some other dependency is missing on the box

Need to dig deeper.

**Comment by am11** [comment]
Thanks @davidebbo for your help. My previous workaround (`msbuild path/to/libx.csproj && dotnet build path/to/web-dir`) didn't work with our real app when libx has dependency on other libs in the same solution. For now, I resorted to building the project locally and uploading the package via FTP.

Incidentally, is it possible to build solutions using VS2015 / `devenv` command line interface in our custom development script on Kudu?

For instance, in addition to msbuild, my solution builds with:

```cmd
"\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\devenv" %cd%\Name.sln /build release
```

but on kudu, issuing this command yields:

> The application has failed to start because its side-by-side configuration is incorrect. Please see the application event log or use the command-line sxstrace.exe tool for more detail.

Unfortunately, we don't get anything in the event log (`D:\home\LogFiles`) and based on [this article](https://blogs.msdn.microsoft.com/cesardelatorre/2011/03/27/the-application-has-failed-to-start-because-its-side-by-side-configuration-is-incorrect-error-related-to-mmc-exe-programs-and-weird-cause-simple-solution/), executing the command ` sxstrace.exe Trace -logfile:D:\home\LogFiles\MySxSTrace.log` dies with blank error.

**Comment by davidebbo** [comment]
I think we know what the problem is, which comes down to incorrect DotNet target files. We'll work on fixing this.

Let's discuss the other issue you bring up separately, so we don't end up mixing the two discussions (I assume it's unrelated).

**Comment by am11** [comment]
Glad to know that the problem has been diagnosed. :)

I have opened a separate issue for devenv.exe story: #2229.

**Comment by davidebbo** [comment]
Update: hoping for a fix deployed tomorrow.

**Comment by davidebbo** [comment]
Sorry, I forgot to follow up, but the fix was deployed this morning. Please verify that all is well now. Thanks!

**Comment by am11** [comment]
Great, I have tested out and deployment from GitHub worked. Thanks a lot David! 🎉

**Comment by davidebbo** [comment]
Thanks for confirming!
