### ISSUE TITLE
Allow to deploy multiple applications via the same Kudu service

### ISSUE THREAD

**Issue by koistya** [projectkudu/kudu#2228]
For example, there are two projects:

https://github.com/company/example.web - Web front-end
https://github.com/company/example.api - GraphQL API

> It could work like this - when `example.web` is pushed to the `master` branch of the https://example.scm.azurewebsites.net/example.git repository it must be automatically deployed to the `C:\home\site\wwwroot` folder and become available under www.example.com URL; similarly when `example.api` project is pushed  to the `api` branch of the same repository it must be automatically deployed into the `C:\home\site\wwwroot\api` folder and become available at www.example.com/api/ URL.

You must be able to deploy these projects separately from each other yet making sure that deploying web front-end doesn't affect previously deployed GraphQL API endpoint and vice verse.

**P.S.**: Is Kudu the right tool for such type of deployments?

**Comment by davidebbo** [comment]
Currently, Kudu does not support this because it only deals with one repo. One thing users sometimes do is use submodules to have both repos surfaced as one. But if they're truly independent projects, it's not a great solution.

Of course, the more straightforward approach is to deploy them to two different Web Apps. Any reason that you are trying to keep them in the same Web App?

**Comment by koistya** [comment]
@davidebbo if these projects to two different Web Apps, is there a way to make one app work as it was deployed into a virtual directory? For example: www.example.com - front-end project, www.example.com/api/ - GraphQL API backend (I need both of them work under the same domain name).

**Comment by davidebbo** [comment]
Good question. Let me look into that as I'm actually not sure. If it was www.example.com vs api.example.com it would be easy, but based on subpath might be trickier.

**Comment by davidebbo** [comment]
Ok, I talked to my co worker, who blogged a way to achieve this a while back. Check out http://ruslany.net/2014/05/using-azure-web-site-as-a-reverse-proxy/
