### ISSUE TITLE
Ability to build solutions with devenv command-line

### ISSUE THREAD

**Issue by am11** [projectkudu/kudu#2229]
Is it possible to build solutions using VS2015 / `devenv` command line interface in our custom development script on Kudu?

For instance, in addition to msbuild, my solution also builds locally with `devenv`:

```cmd
"\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\devenv" %cd%\Name.sln /build release
```

but on kudu, issuing this command yields:

> The application has failed to start because its side-by-side configuration is incorrect. Please see the application event log or use the command-line sxstrace.exe tool for more detail.

Unfortunately, we don't get anything in the event log (`D:\home\LogFiles`) and based on [this article](https://blogs.msdn.microsoft.com/cesardelatorre/2011/03/27/the-application-has-failed-to-start-because-its-side-by-side-configuration-is-incorrect-error-related-to-mmc-exe-programs-and-weird-cause-simple-solution/), executing the command ` sxstrace.exe Trace -logfile:D:\home\LogFiles\MySxSTrace.log` dies with blank error.

**Comment by davidebbo** [comment]
I'm not too surprised that you can't run devenv from Kudu console, as many things are likely getting blocked by the [sandbox](https://github.com/projectkudu/kudu/wiki/Azure-Web-App-sandbox) that everything runs in.

What exactly do those commands do?

**Comment by am11** [comment]
> many things are likely getting blocked by the sandbox

Yes it definitely seems like the case; while `msbuild.exe` can run within App Service sandbox, `devenv.exe` command-line is getting blocked.

> What exactly do those commands do?

Given a VS solution file `mysolution.sln`, we can build it two ways from command line:

```cmd
:: using MSBuild.exe
msbuild mysolution.sln /p:Configuration=Release

:: using VS, devenv.exe
devenv mysolution.sln /build release
```

If we execute `devenv mysolution.sln` without a target `/build` or `/t:Build` argument, it launches the solution in VS (GUI).

Some CI systems, such as AppVeyor, provide both options to build solutions. I have seen cases where a solution will build in VS, but won't directly from msbuild due to various reasons. For example, VS searches the code tree, and will correct issues such as assemblies path relocations. Devs are mostly using VS locally instead of building solutions directly with msbuild.

**Comment by davidebbo** [comment]
I think we may have to accept that msbuild is the only supported way to build on Azure Web App. Frankly, it doesn't feel quite right to involve devenv on a CI server. Note that while devenv is there on the box, VS is not there. So it probably only has a small subsets of the files.

In the end, I'm not quite sure why it's failing, but I'd like to encourage the use of msbuild here :)
