### ISSUE TITLE
Found solution xxxxx with no deployable projects. Deploying files instead.

### ISSUE THREAD

**Issue by clarkd** [projectkudu/kudu#2231]
I'm trying to deploy a .NET Core app (VS 2015) to Azure App Services using the Bitbucket deployment options. It's a empty web application - when it runs locally it just outputs "Hello World"!

The deployment successfully triggers when I commit but when I visit the app's URL all I get is: "You do not have permission to view this directory or page.".

Digging a little deeper, it looks like Kudu isn't actually building/running the project. The logs look like this:

```
Found solution 'D:\home\site\repository\xxxx.sln' with no deployable projects. Deploying files instead.

Using cached version of deployment script (command: 'azure -y --no-dot-deployment -r "D:\home\site\repository" -o "D:\home\site\deployments\tools" --basic').

Command: "D:\home\site\deployments\tools\deploy.cmd"
Handling Basic Web Site deployment.
KuduSync.NET from: 'D:\home\site\repository' to: 'D:\home\site\wwwroot'
Copying file: 'src\xxxxx\Startup.cs'
Finished successfully.
```

Any ideas on what I'm doing wrong would be greatly appreciated! 👍

**Comment by davidebbo** [comment]
Can you share a sample repo that demonstrates the issue, per this [wiki page](https://github.com/projectkudu/kudu/wiki/Using-a-git-repo-to-report-an-issue)? Thanks!

**Comment by clarkd** [comment]
Absolutely, here's a link to a public clone: https://bitbucket.org/02DClarke/bitbucket-bot

(Thanks for the super quick response!)

**Comment by davidebbo** [comment]
Couple things:

1. it seems you're using very old tooling, as your global.json has 1.0.0-beta5
2. what you have doesn't look like a web project, so we fail to detect it as one, and deploy it like a static site

See https://github.com/davidebbo-test/AspNetCoreVS for what a Web Project normally looks like.

**Comment by clarkd** [comment]
Ah that does explain a couple of things... I've just updated VS2015 to the latest version and now being prompted to install the RC.... Doh. 

I'll get that updated, create a new project and try again. Thanks!
