### ISSUE TITLE
Deployment fails with Ionic2

### ISSUE THREAD

**Issue by digitalbanana** [projectkudu/kudu#2234]
Hi,
Am having a problem deploying an ionic-angular webapp.
Specifically when building via kudu in Azure the "npm install -g ionic" step below fails with the error

**argv
 "D:\\Program Files (x86)\\nodejs\\6.7.0\\node.exe" "D:\\Program Files 
(x86)\\npm\\3.10.3\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "ionic"
npm
 ERR! node
 v6.7.0
npm
 
ERR!
 
npm 
 v3.10.3
npm
 ERR! path D:\local\AppData\npm\node_modules\.staging\spdx-license-ids-6d45b1f8
npm
 
ERR!
 
[18:54:29.60] error in npm install ionic -g.**

Have tried other node/npm versions with similar results
This runs fine locally on both windows and mac workstations

Any help/workarounds greatly  appreciated - we are currently manually building the app and committing to VCS

**Comment by davidebbo** [comment]
In Kudu Console, I tried directly running:

    npm install -g ionic

It failed with this output:

```
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.0.15 (node_modules\ionic\node_modules\ionic-app-lib\node_modules\glob-watcher\node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.15: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"ia32"})
npm ERR! Windows_NT 6.2.9200
npm ERR! argv "D:\\Program Files (x86)\\nodejs\\6.9.1\\node.exe" "D:\\Program Files (x86)\\npm\\3.10.8\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "ionic"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! path D:\local\AppData\npm\node_modules\.staging\spdx-license-ids-6d45b1f8
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall rename

npm ERR! enoent ENOENT: no such file or directory, rename 'D:\local\AppData\npm\node_modules\.staging\spdx-license-ids-6d45b1f8' -> 'D:\local\AppData\npm\node_modules\ionic\node_modules\gulp-util\node_modules\dateformat\node_modules\meow\node_modules\normalize-package-data\node_modules\validate-npm-package-license\node_modules\spdx-correct\node_modules\spdx-license-ids'
npm ERR! enoent ENOENT: no such file or directory, rename 'D:\local\AppData\npm\node_modules\.staging\spdx-license-ids-6d45b1f8' -> 'D:\local\AppData\npm\node_modules\ionic\node_modules\gulp-util\node_modules\dateformat\node_modules\meow\node_modules\normalize-package-data\node_modules\validate-npm-package-license\node_modules\spdx-correct\node_modules\spdx-license-ids'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     D:\home\tmp\tmp\npm-debug.log
npm ERR! code 1
```

I don't completely understand what's going on here. Seems it's trying to rename the file `D:\local\AppData\npm\node_modules\.staging\spdx-license-ids-6d45b1f8` from the staging area into it's final destination in `D:\local\AppData\npm\node_modules\ionic\node_modules\gulp-util\node_modules\dateformat\node_modules\meow\node_modules\normalize-package-data\node_modules\validate-npm-package-license\node_modules\spdx-correct\node_modules\spdx-license-ids`, and failing for some reason. The path length is under the limit, so I don't think that's the problem.

**Comment by watashiSHUN** [comment]
I wasn't able to reproduce your issue, running `npm install -g packageName` seems to be running ok:
![capture](https://cloud.githubusercontent.com/assets/6531400/20412000/fe082b2e-acd8-11e6-88ff-6e51716fb74a.JPG)

@davidebbo there are similar error messages on github: npm/npm#10995, angular/angular-cli#1190,
it may be that you have an older version of `ionic` and before updating, you need to uninstall the previous version:
```
$ npm uninstall -g ionic
$ npm cache clean
$ npm install -g ionic
```

@DigitalBanana is `npm install -g ` not working for all packages? can you try installing a small packages? and paste the error message here, thanks

**Comment by DigitalBanana** [comment]
Hey @watashiSHUN

Okay so can install packages (typescript, ionic, ionic-angular) with -g switch via kudu console

![image](https://cloud.githubusercontent.com/assets/248916/20423387/d8d23360-ad67-11e6-8688-97d961410392.png)

![image](https://cloud.githubusercontent.com/assets/248916/20423471/5c657e26-ad68-11e6-880c-cab79ed87d66.png)

so i tried again invoking sync from the Azure portal - now works...very strange
I did try this (installing from kudu console) yesterday and it failed......guess this issue can be closed? thnaks for response and help

**Comment by watashiSHUN** [comment]
@DigitalBanana sorry, didn't realize that you have edited your comments, can you try [removing node-sass folder entirely from node_modules and asking npm to reinstall it](https://github.com/davezuko/react-redux-starter-kit/issues/791)

**Comment by DigitalBanana** [comment]
@watashiSHUN okay so after cleaning, setting up another site etc and doing what you recommend the problem as come back as originally reported...

![image](https://cloud.githubusercontent.com/assets/248916/21043071/10fe04cc-bded-11e6-8b83-ece716889656.png)

Do you have any ideas on what I can try next?

**Comment by DigitalBanana** [comment]
just tried this again with a fresh ionic 2 app and get the same result...

Command: deploy.cmd
[10:32:08.12] Installing ionic cli
D:\local\AppData\npm
`-- (empty)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.0.15 (node_modules\ionic\node_modules\ionic-app-lib\node_modules\glob-watcher\node_modules\chokidar\node_modules\fsevents):

npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.15: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"ia32"})
npm ERR! Windows_NT 6.2.9200
npm ERR! argv "D:\\Program Files (x86)\\nodejs\\6.9.1\\node.exe" "D:\\Program Files (x86)\\npm\\3.10.8\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "ionic"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! path D:\local\AppData\npm\node_modules\.staging\spdx-license-ids-6d45b1f8
npm ERR! code ENOENT
Handling Basic Web Site deployment.
npm ERR! errno -4058
npm ERR! syscall rename

npm ERR! enoent ENOENT: no such file or directory, rename 'D:\local\AppData\npm\node_modules\.staging\spdx-license-ids-6d45b1f8' -> 'D:\local\AppData\npm\node_modules\ionic\node_modules\gulp-util\node_modules\dateformat\node_modules\meow\node_modules\normalize-package-data\node_modules\validate-npm-package-license\node_modules\spdx-correct\node_modules\spdx-license-ids'
npm ERR! enoent ENOENT: no such file or directory, rename 'D:\local\AppData\npm\node_modules\.staging\spdx-license-ids-6d45b1f8' -> 'D:\local\AppData\npm\node_modules\ionic\node_modules\gulp-util\node_modules\dateformat\node_modules\meow\node_modules\normalize-package-data\node_modules\validate-npm-package-license\node_modules\spdx-correct\node_modules\spdx-license-ids'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     D:\home\site\repository\npm-debug.log
npm ERR! code 1
KuduSync.NET from: 'D:\home\site\repository' to: 'D:\home\site\wwwroot'
Copying file: 'npm-debug.log'
Finished successfully.

@watashiSHUN @davidebbo any ideas on this - can you suggest where i might look to try and sort this...i cant find any mention of the spdx-license anywhere online, gut feeling is that this is apermissions issue somewhere in Azure app service - really want to use ionic 2 in azure but this blocking - thanks in advance

**Comment by ncapito** [comment]
We are also experiencing this same issue.   It happened after I tried to add ionic to our package.json.  We had it as a global install before.

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
