### ISSUE TITLE
What is the recommended way to specify framework with dotnet publish

### ISSUE THREAD

**Issue by tinchou** [projectkudu/kudu#2235]
I'm deploying an App and I discovered the whole deployment process is done twice, one for each framework specificed in my `project.json` file.

I just edited `D:\home\site\deployments\tools\deploy.cmd` and added `--framework netcoreapp1.0` to the Step 2 where I call `dotnet publish`, but I was wondering if this is the right way to do it and if it wouldn't be good to add a flag to the `.deployment` file.

Thanks!

**Comment by watashiSHUN** [comment]
Is specifying multiple frameworks in `project.json` break your site or it just slows down the build process?

**Comment by tinchou** [comment]
It builds twice, one for each configuration. E.g. my webpack commands in
the post publish section are also run twice.

**Comment by watashiSHUN** [comment]
from [`dotnet publish` doc ](https://docs.microsoft.com/en-us/dotnet/articles/core/tools/dotnet-publish)
> -f|--framework <FRAMEWORK>
> 
> Publishes the application for a given framework identifier (FID). If not specified, FID is read from project.json. If no valid framework is found, the command throws an error. If multiple valid frameworks are found, the command publishes for all valid frameworks.

specifying `--framework netcoreapp1.0` on the command line is the same thing as putting the following code inside your `project.json`
```
 "frameworks": {
    "netcoreapp1.0": {
      "imports": [
        "dotnet5.6",
        "portable-net45+win8"
      ]
    }
```
if you don't want to **publish for multiple frameworks**, you can specify just **one** in your `project.json`

**Comment by tinchou** [comment]
Oh, I see now. I guess it isn't really intuitive that you can't override
the framework with that switch, but I guess it's fine. I don't need to
support more than one at the moment :).

Please close!
