### ISSUE TITLE
Is it possible to run npm install when deploying to azure ?

### ISSUE THREAD

**Issue by knuterik91** [projectkudu/kudu#2237]
Hi, I have a react server side rendered app, using asp-prerendering.  Im using team city and octopus deploy to  build and deploy the site to azure from my vsts repo.  Since Node_Modules is huge, I dont want to include it during deployment. But rather have a script in kudo that runs npm install when azure is receiving new files.  

I have tried adding a script in in  \site\deployments\tools\PostDeploymentActions. 
I have also added a .deploymnet file in \site\wwwroot.  but none of the scripts are being runned.

Is it possible to have kudo to run a npm install ? Any help is appreciated.

**Comment by davidebbo** [comment]
If you are using Octopus deploy, then your bits a likely deployed to Azure using msdeploy. In that scenario, Kudu does not come into the picture at all. Kudu is the deployment engine when doing git deployments to Azure Web Apps.
