### ISSUE TITLE
MySQL In App - can't access PHPMyAdmin from the Azure Portal Blad

### ISSUE THREAD

**Issue by andrewkrowczyk** [projectkudu/kudu#2238]
It's prompting me for username and password.

Even if I enter the username and password in the MYSQLCONNSTR_localdb.ini it doesn't work.

The Wiki information explaining this is confusing.

@suwatch - it looks like you edited the Wiki article on this.  How do I access PHPMyAdmin on a new WebApp that I turned the feature on for?

**Comment by andrewkrowczyk** [comment]
This is the confusing part...

> How to use phpMyAdmin with MySql in-app?

phpMyAdmin is enabled by default with the feature. You can access it thru https://<sitename>.scm.azurewebsites.net/phpMyAdmin/. Unlike phpMyAdmin from SiteExtenions gallery, this phpMyAdmin is aware of MySql credentials and will connect automatically. The caveat is since MySql is only started with the main site if one were to access phpMyAdmin (which is part of SCM site) without the main site (and MySql) running, it may confusingly prompt for password. We are working toward improving the phpMyAdmin experience to better inform users in this scenario.

**Comment by suwatch** [comment]
@andrewkrowczyk do you mind posting the question on [this forum]( https://social.msdn.microsoft.com/Forums/en-US/home?forum=windowsazurewebsitespreview&filter=alltypes&sort=lastpostdesc) instead?

**Comment by suresh42326** [comment]
For me, visiting <sitename>.azurewebsites.net  solved my issue.
 after that I browsed  <sitename>.scm.azurewebsites.net/phpmyadmin, it didn't ask password.

**Comment by alexberd** [comment]
Very odd situation in Azure, thanks #suresh42326 for pointing the answer out!!
