### ISSUE TITLE
Deployment script for azure functions

### ISSUE THREAD

**Issue by xt0rted** [projectkudu/kudu#2240]
When setting up continuous integration for functions do node based functions run `npm install` on each deploy? If not is there a way to add a deployment script that will do it for me? I'd like to move over to continuous integration but couldn't find anything in the docs on how the deployments work.

**Comment by davidebbo** [comment]
Currently, there is no smart by default for function apps. But you should be able to add a custom deployment script that does that.

**Comment by xt0rted** [comment]
Would this be the same as adding a `deploy.cmd` to my repo or is there a different way to extend function apps?

**Comment by davidebbo** [comment]
It's exactly the same process.

**Comment by xt0rted** [comment]
Tried it out and it worked on the first deploy. Thanks!
