### ISSUE TITLE
WebApp deployment with WebJob inside deletes the indirect references 

### ISSUE THREAD

**Issue by sguryev** [projectkudu/kudu#2241]
I have faced the following issue: during publishing WebApp+WebJob VS2015U3 removes the indirect references (which are not referenced from WebApp itself but referenced from any other project in solution) from the WebApp bin folder:
![image](https://cloud.githubusercontent.com/assets/6978458/20522922/b4481c6c-b0c3-11e6-82fb-4e7fd5bb39d0.png)
![image](https://cloud.githubusercontent.com/assets/6978458/20522819/450b6ad4-b0c3-11e6-98d3-d8b536a7956e.png)
(_sorry for Russian in the Output. I Have the Eng Windows and all English software. Except three options in the system: Control panel => Region => Format settings, Location and Administrative => Current language for non-Unicode programms. **But it's another problem**_).

The main requirement: set this option to checked "_Remove additional files at destination_".
![image](https://cloud.githubusercontent.com/assets/6978458/20523200/f211c3c6-b0c4-11e6-8ea9-19680f35cfd3.png)

I have prepared the GitHub sandbox solution: https://github.com/sguryev/azure-webapp-and-webjob-publish-issue

Prerequisites:
"_Remove additional files at destination_" option enabled
Publishing from WebApp node (**not** independent publish for WebApp nad WebJob)
Debug publishing configuration

Reprosteps:
1. Build
2. Publish (result will be OK)
3. Make a solution rebuild and publish or just a publish. (result: VS will remove the indirect references DLLs as SendGrid and even the PDB file for the Services project)
4. Now you can make any number of build\rebuild\publish and nothing will help.

Workaround:
1. Make a solution rebuild and publish to make sure that the latest DLLs are published.
2. Make any minor change to the WebApp (add the `int i = 0` to HomeController or change the Web.config)
3. Publish the WebApp. 
It looks like in this case there are no changes for the WebJob and it doesn't participate in publishing.

One more workaround: publishing **Debug-Release-Debug** to force the fresh publishing.
An finally you can uncheck the "_Remove additional files at destination_" option but in this case you will have junk in the published folder (for example removed packages, or static files)

Also I have notices that in both: Output window and Publish preview window I have two type of paths:
`/bin/SomeLibrary.dll`
`<WebAppName>/bin/SomeLibrary.dll`
It seems that the second one comes from the WebJob target file (I mean `Microsoft.Web.WebJobs.Publish.1.0.12/tools/webjobs.target`)

**Comment by davidebbo** [comment]
Not exactly a Kudu issue, as it sounds like a Visual Studio publishing bug. @mlorbetske any comments on this behavior?

**Comment by sguryev** [comment]
Hi @davidebbo. Thank you for the reply. I appreciate any advice on the best place to report the issue and get the solution

**Comment by mlorbetske** [comment]
@vijayrkn can you take a look?

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
