### ISSUE TITLE
.deployment file being ignored with git deploy

### ISSUE THREAD

**Issue by tjrobinson** [projectkudu/kudu#2243]
I have the following `.deployment` file in the root of my git repository:

```ini
[config]
SCM_BUILD_ARGS=-p:Configuration=UAT;PublishProfile=UAT
project = src/MyWebApp
SCM_TRACE_LEVEL=4
```

However, when I look at the logs I can see no evidence of this `.deployment` file being used and the Web.config transforms I've set up aren't running.

More detail can be found in my original post here: https://social.msdn.microsoft.com/Forums/azure/en-US/3586203f-0f16-4335-8bb5-4c05cce678d1/webconfig-being-replacedignored-when-auto-deploying-from-git?forum=windowsazurewebsitespreview

**Comment by tjrobinson** [comment]
The reason I don't think the file is being used is that it should be setting the `Configuration` to `UAT` but in the log file I only ever see references to `--configuration Release`.

I've also tried putting `/p:Configuration=UAT;PublishProfile=UAT` (note the slash) in the SCM_BUILD_ARGS environment variable using the Azure settings UI but it makes no difference either.

**Comment by davidebbo** [comment]
That's strange. So is it also ignoring your `project` directive, or just `SCM_BUILD_ARGS`? Can you try settings these to clearly invalid values (e.g. `SCM_BUILD_ARGS=-bogus`) to make really sure it's not being used?

**Comment by tjrobinson** [comment]
I've tried with the following `.deployment` file:

```ini
[config]
SCM_BUILD_ARGS=-bogus
project = src/Empactis.HRCM
SCM_TRACE_LEVEL=4
```

The deployment worked as before - no obvious changes in the logs, no errors and the site was deployed correctly. This was with no `SCM_BUILD_ARGS` in Application Settings, just the file above.

I noticed that `D:\home\site\deployments\tools\deploy.cmd` contained the following:

```
:: 2. Build and publish
call :ExecuteCmd dotnet publish "src\MyWebApp" --output "%DEPLOYMENT_TEMP%" --configuration Release
```

So I also tried deleting both `D:\home\site\deployments\tools\deploy.cmd` and `D:\home\site\deployments\tools\deploymentCacheKey` then issuing a redeploy from the Azure Portal. The files I deleted were recreated and I ran them through a diff tool to check they were exactly the same.

The `deploymentCache` file contains:

```
59.51122.2559.0
-y --no-dot-deployment -r "D:\home\site\repository" -o "D:\home\site\deployments\tools" --aspNetCore "D:\home\site\repository\src\MyWebApp"
```

If I delete the `.deployment` file altogether then the deployment fails (which makes sense and proves that it is looking at the `.deployment` file at least).

`Unable to determine which solution file to build. D:\home\site\repository\MyWebApp.sln, D:\home\site\repository\src\SomeOtherSolution.sln.`

So, I put the `.deployment` file back but changed it to:

```ini
[config]
SCM_BUILD_ARGS=-p:Configuration=Debug
project = src/MyWebApp
SCM_TRACE_LEVEL=4
```

But the logs still show that `dotnet publish` is being called with `--configuration Release`.

As a final test I left the `.deployment` file as-is above and added `SCM_BUILD_ARGS` `/p:Configuration=Debug` into the Application Settings (and clicked Save), then issued a redeploy.

This gave the same behaviour as the previous test, `dotnet publish` is still being called with `--configuration Release`.

**Based on this I think everything is working as expected except for `SCM_BUILD_ARGS` which is seemingly ignored whether it's in Application Settings or `.deployment`.**

I've worked round the original issue for now by creating a Site Extension to apply the configuration transforms that we needed: https://www.siteextensions.net/packages/RemoveCustomHeaders/

**Comment by davidebbo** [comment]
Is this with a .NET Core project, and if so does it use Preview2 or Preview3 tooling? I don't see any explicit mention of Core, but you are referring to 'dotnet publish'. `SCM_BUILD_ARGS` is something that currently only gets appended to the 'msbuild' command line, which is likely why it doesn't work. Take a look at your `D:\home\site\deployments\tools\deploy.cmd` for details on what the default deployment script does.

**Comment by tjrobinson** [comment]
It's ASP.NET Core 1.0 targetting .NET Framework 4.6 using the Preview2 tooling (i.e. not the tooling release at Connect(); a few days ago). Do you know if there's an equivalent to `SCM_BUILD_ARGS` that could be used? Though that at least explains what's happening - thanks!

**Comment by davidebbo** [comment]
Not currently. I think we could just overload the meaning of `SCM_BUILD_ARGS` and also pass that to the 'dotnet publish' command line.

@watashiSHUN that should be an easy change to make.

**Comment by watashiSHUN** [comment]
unlike `msbuild`, `dotnet publish` does not allow command line argument overwriting, if you want to customize it, you need to rewrite the command line all together

ie, in your own [deploy.cmd](https://github.com/projectkudu/kudu/wiki/Customizing-deployments#deploying-with-custom-script):
```
:: 2. Build and publish
call :ExecuteCmd dotnet publish "src\MyWebApp" --output "%DEPLOYMENT_TEMP%" --configuration Debug
```

**Comment by tjrobinson** [comment]
@watashiSHUN Ok thanks, I think we'll leave it as-is for now and then look into this again once the msbuild .NET Core tooling is finished.
