### ISSUE TITLE
How do I clone/pull from additional private GitHub repos in my custom deployment script?

### ISSUE THREAD

**Issue by Jehoel** [projectkudu/kudu#2244]
I have about 7 different websites, each in their own private GitHub-hosted git repo, in my GitHub organization.

These websites are all PHP websites. I want complete control over deployment through my own deployment scripts. I don't use MSBuild.

All 7 websites have a dependency on 2 libraries written in PHP that exist in 2 other separate private GitHub repos in the same organization.

So my GitHub organization looks like this:

- WebsiteFoo
- WebsiteBar
- WebsiteBaz
- ...
- PrivateLibrary1
- PrivateLibrary2

I want my deployment script to deploy each website with this arrangement:

- \* (XCOPY from WebsiteFoo repo, with certain files deleted)
- \libs\lib1 (XCOPY from PrivateLibrary1 repo)
- \libs\lib2 (XCOPY from PrivateLibrary2 repo)

I haven't written the deployment script yet, I thought I'd give it a test in the Kudu CMD Debug Console.

I have already set-up GitHub deployment through the Azure Portal (App Services > WebsiteFoo > App Deployment > Deployment options > GitHub > repo: WebsiteFoo; branch: master) which means there is a repo clone of `WebsiteFoo` in `D:\home\site\repository`.

...which means I just need to `git clone` (or `git pull` if the repos already exist) the `PrivateLibrary1` and `PrivateLibrary2` repos, however it doesn't work from the Kudu CMD Debug Console:

```
D:\home\site>mkdir gittest
D:\home\site>cd gittest
D:\home\site>git clone https://github.com/MyOrganization/PrivateLibrary1.git
Cloning into 'PrivateLibrary1'...
bash: /dev/tty: No such device or address
error: failed to execute prompt script (exit code 1)
fatal: could not read Username for 'https://github.com': Invalid argument
```

I was operating on the assumption that the Kudu context has my delegated GitHub access: it's already able to access my `WebsiteFoo` repo, so surely it would be able to access my `PrivateLibrary1` repo too?

FWIW, when I run `git pull origin master` from within the `D:\home\site\repository` directory I get this output:

```
D:\home\site\repository>git pull origin master
Warning: Permanently added the RSA host key for IP address '192.30.xxx.yyy' to the list of known hosts.
From github.com:MyOrganization/WebsiteFoo
 * branch            master     -> FETCH_HEAD
Already up-to-date
```

What do I need to do?

**Comment by davidebbo** [comment]
Try using ssh instead of https. Read through http://blogs.suwatbodin.com/2013/07/deploy-to-windows-azure-using-git-with.html to learn some relevant techinques.

**Comment by Jehoel** [comment]
Thank you! I created an SSH key-pair in `~/.ssh/`, added it to the `~/.ssh/config` file and also to  `PrivateLibrary1`'s Deploy Key section, and then did a `git clone` using the SSH URI (after having modified the hostname to match the SSH hostname entry) and it cloned it successfully!

If I'm creating multiple instances of the Azure website where do I put the commands to generate (or copy) the private key?

**Comment by davidebbo** [comment]
You could I supposed do that as part of a custom deployment script that copies the Deploy Key if it's not there. As to where you'd get the deploy key file, one possibility might be to put it in a private blob, and set the sas key to the blob as an App Setting as part of each site's creation. Then have the deployment script download the file.

Closing since this is more of a discussion and not an issue.
