### ISSUE TITLE
ZipException on deployment

### ISSUE THREAD

**Issue by poklau** [projectkudu/kudu#2250]
Tomcat returns a ZipException occasionally after syncing from Dropbox. The war appears in the correct folder according to the Kudo console when we start the deployment slot.

The error goes away after a delay - the delay could be as small as a few minutes and up to overnight sometimes.

Refer to the log file attached for details.

[catalina.2016-11-24.txt](https://github.com/projectkudu/kudu/files/632583/catalina.2016-11-24.txt)

**Comment by davidebbo** [comment]
@poklau if you see the error go away without redeploying the zip, it means that the issue is most likely unrelated to Kudu deployment. Kudu's job here is to get the files in the right place. How they behave at runtime is outside the scope of Kudu, and becomes a pure runtime issue.
