### ISSUE TITLE
Kudu doesn't read the most relevent "global.json" for dotnet core projects

### ISSUE THREAD

**Issue by watashiSHUN** [projectkudu/kudu#2253]

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
