### ISSUE TITLE
Azure Functions/Nuget/Kudu sync deleted all my functions

### ISSUE THREAD

**Issue by iain-peddie-tessella** [projectkudu/kudu#2255]
I'm writing an Azure Functions app, and I've got to the point where it would be really quite useful to use an assembly installed using NuGet. I'm using a local git repository and pushing my files up.

I wrote a project.json file with the following content:

``` json
{
  "frameworks": {
    "net46": {
      "dependencies": {
        "ExcelDataReader": "2.1.2.1"
      }
    }
  }
}
```
Initially this failed, because for some reason the parameters sent to nuget.exe restore means that PackagesDirectory has to be specified exactly. So, I got deploy.cmd and updated the call to nuget. Next, I hit [issue 2230](https://github.com/projectkudu/kudu/issues/2230), and took the fix there.

Having done that, there was an issue that I was missing a projects.json.lock, so I added the following line:
`call :ExecuteCmd dotnet restore` before the call to `dotnet publish`.

Once this worked, KuduSync.NET decided that everything excep the assemblies brought in by nuget needed to be removed from the published website. I'm fairly sure that deleting all of the run.csx, package.json and other supporting .csc files.

So, I went from having about 20 files in home/site/wwwroot to about 3, none of which run. This is clearly a bug. Is there a known workaround. Happy to (anonymously) provide a link to the functions app that I've hit this issue with...

**Comment by iain-peddie-tessella** [comment]
I'm attaching a zip with the deployment and json files that triggered the problem for me.

[problem_files.zip](https://github.com/projectkudu/kudu/files/636812/problem_files.zip)

**Comment by davidebbo** [comment]
Are you sure that all those other files that got deleted are part of your repository?

**Comment by iain-peddie-tessella** [comment]
@davidebbo Yes. I've logged in using the console and they are present in the repository area. They are all version controlled in my local git repo.

Additionally, when I delete the 4 files `.deployment, deploy.cmd, project.json, global.json` and commit the changes, the functions all reappear and work again. To get going, this is what I'm now doing, but that means I can't pull in the assemblies that I'm going to need going forward. (See my above comment for the contents of these files).

**Comment by davidebbo** [comment]
@iain-peddie-tessella it's hard to tell without knowing what's in your custom deployment script. Can you [share a repo](https://github.com/projectkudu/kudu/wiki/Using-a-git-repo-to-report-an-issue), and the steps that lead to what you are seeing?

**Comment by iain-peddie-tessella** [comment]
The repo is here:

https://github.com/iain-peddie-tessella/demo-kudu-nuget-problem

For me, I make a trivial change - enough to trigger the deployment script running, and commit and push the change up to my function app. 

For anyone else, I suspect they would need to create a new function app, tie this git repo to the app, and do a force push. (Or create one directly from the repository, if that is possible).

**Comment by davidebbo** [comment]
How did you end up with that deployment script? It looks like a deployment script to deploy ASP.NET Core applications, which is a completely different scenario. That's why it's not doing the right thing for a function app.

**Comment by iain-peddie-tessella** [comment]
I went to 'function app settings', then 'Deploy/Go to Kudu', and then in the Kudu window I went to Tools/download deployment script. I must have accidentally got the script from the App Service ASP.NET page unintentionally.

But the script downloaded only uses KuduSync, even when project.json indicates nuget pacakges. Is nuget not supported for function apps?

**Comment by davidebbo** [comment]
Right, we currently don't automatically generate a script for functions that does restore. Here is a sample: https://github.com/fabiocav/webjobs-scripts-samples/blob/master/DeploymentScript/deploy.cmd

**Comment by iain-peddie-tessella** [comment]
I have an ASP.NET core app in the same resource group, so I may well have unintentionally copied the deploy script from the Kudu Tools/Download deployment script from there by mistake.

But the reason I did this was because when I put a project.json in the code, trying to pull in a nuget package, the default script hit an issue in the nuget restore step - which suggests to me that in the functions app, the default script is the ASP.NET script rather than the functions script (which just calls KuduSync).

So, is using project.json to pull in nuget pacakges not the way to do this in function apps?

**Comment by iain-peddie-tessella** [comment]
That helps. I think that somehow the default command script must have gone wrong in functions, but I don't think that's an issue with Kudu ( I think the default deploy.cmd that runs if .deployment does not exists is the ASP.NET one for some reason).
