### ISSUE TITLE
broken link in https://***.scm.azurewebsites.net

### ISSUE THREAD

**Issue by ranjan-ranjan** [projectkudu/kudu#2259]
![1](https://cloud.githubusercontent.com/assets/16834561/21003546/feff68ce-bd51-11e6-8ffc-5c2c855e9d88.png)

**Comment by davidebbo** [comment]
It's not exactly broken, but points to a private fork of the Kudu repo. It's a bit quirky, but is the result of how it gets built into Azure. Just ignore this commit id :)
