### ISSUE TITLE
Typescript 2.1

### ISSUE THREAD

**Issue by tbertenshaw** [projectkudu/kudu#2264]
Is there a channel for reporting support of new versions of typescript on the Azure App Service? Was contemplating using Typescript 2.1 but after checking the typescript folder using the kudu console i could see that the latest version is 2.0

https://blogs.msdn.microsoft.com/typescript/2016/12/07/announcing-typescript-2-1

**Comment by tbertenshaw** [comment]
looks like 2.1 was installed on azure apps yesterday, i can now see the following folder
 `D:\Program Files (x86)\Microsoft SDKs\TypeScript\2.1` using Kudu console.

**Comment by watashiSHUN** [comment]
yes we pushed `typescript 2.1` on Jan 25

**Comment by tbertenshaw** [comment]
Is there anywhere public we should be looking for these details. Anyone using typescript in their projects and Azure deployment slots, won't know when/if they should be using the latest typescript features as its not obvious unless you check using the kudu console? The blogpost above certainly implies its ready to go, would be good it it could say check "here" for azure support, on the blogpost.
