### ISSUE TITLE
Azure git deployment started to fail due to Typescript errors

### ISSUE THREAD

**Issue by mcgri** [projectkudu/kudu#2265]
Hi
I am using git to deploy a .net 4.6 project / typescript 2.0.3. Last week, azure started to fail to build the project. I  tried to redeploy previously working commits, but they are failing too. 
Originally, I was overcoming typescript errors by including all typescript files into a tag at .csproj :

`<ItemGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">`

But now,  the deployment seems to ignore the condition and attending to build the typescript anyway.
Publishing via Visual Studio is working fine. There is no errors at all in local copy.

Here is my post at msdn with more details of my journey of finding the source of the build failure.
https://social.msdn.microsoft.com/Forums/en-US/743e0244-9f3c-4a58-8378-914a3fdc4c1d/azure-deployment-fails-jserrorscriptexception?forum=hypervrecovmgr

Any assistance with the issue will be much appreciated.  I hope , I am posting the issue at right place. I am looking to either make the server to build typescripts, or to ignore them,as I am including  already compiled JS files in my commits.

**Comment by watashiSHUN** [comment]
hello, yes, this is a good place to get help for your deployment questions. Can you share a [github repository](https://github.com/projectkudu/kudu/wiki/Using-a-git-repo-to-report-an-issue) that highlights your project structure so that I can try to reproduce the issue at my end, thanks

**Comment by mcgri** [comment]
Thanks. I will try to clean up the project from unnecessary code first. I will try to get it done by tommorow

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
