### ISSUE TITLE
[DebugConsole] Upload progress bar broken

### ISSUE THREAD

**Issue by snobu** [projectkudu/kudu#2266]
The DebugConsole upload progress indicator seems to no longer work.

To repro: Upload a large file via drag-and-drop, click the progress indicator -> the progress bar stays at 0%.

Browser console:

```
SCRIPT5022: Unable to parse bindings.
Message: SyntaxError: Expected ':';
Bindings value:  style
                                                 { width $root.getCopyPercentage($parent.copyProgStats()[item]) + '%' } , css { 'progress-bar-info'
                                                 $root.getCopyPercentage($parent.copyProgStats()[item]) < 100, 'progress-bar-success': $root.getCopyPercentage($parent.copyProgStats()[item]) >= 100  }, text: $root.getCopyPercentageDisplay($parent.copyProgStats()[item])
knockout-2.2.1.js (5,28)
```

This probably happened here:
https://github.com/projectkudu/kudu/commit/41835558895f37dbb0efb30fe6b420e99b320388#diff-07d92cee177630927569cbad46591ec8R126

There should be a `:` after `width` in `{ width $root.getCopyPercentage($parent.copyProgStats()[item])...`

**Comment by snobu** [comment]
Probably a botched copy/paste when `Default.cshtml` got split into Linux/WindowsConsole variants.
TODO: I should write some UI tests.

**Comment by badescuga** [comment]
@snobu don't do UI tests. UI tests are prone to frequent breaking. I suggest working on some functional tests, if you intend on writing any tests at all.
