### ISSUE TITLE
Strange deployment errors via GitHub / Bitbucket - SCM not enabled

### ISSUE THREAD

**Issue by devlead** [projectkudu/kudu#2269]
Last 12h I've had multiple sites (5 uptil now, different subscriptions) with the same log as below, GitHub and BitBucket web hooks get a 403 from Kudu
```xml
  <step title="FetchHandler" date="2016-12-13T09:02:03.059" >
    <step title="Scm is not enabled, reject all requests." date="2016-12-13T09:02:03.075" /><!-- duration: 0ms -->
  </step><!-- duration: 31ms -->
  <step title="Outgoing response" date="2016-12-13T09:02:03.106" type="response" statusCode="403" statusText="Forbidden" Server="Microsoft-IIS/8.0" Cache-Control="private" X-AspNet-Version="4.0.30319" /><!-- duration: 0ms -->
```
Tried restarting the deployment slot redelivering the web hook solved it. 
Don't know if it's related but all sites that had this issue are deployment slots.

Interestingly all these sites won't load in the portal, it just sits like this forever
![image](https://cloud.githubusercontent.com/assets/1647294/21134120/abaa01e2-c11c-11e6-83ed-770b3a8b5e75.png)
until I click overview, then everything loads and it's fine the next time I open the blade for that site.
![image](https://cloud.githubusercontent.com/assets/1647294/21134160/ddcc6f70-c11c-11e6-8474-05f71ef51161.png)

Then going to the deployment slot, restarting that web and redelivering web hook results in an 202 instead of 403
![image](https://cloud.githubusercontent.com/assets/1647294/21134238/2285a41a-c11d-11e6-895b-781b5e4a9ef8.png)

And everything deploys fine. Any ideas what could be causing this?

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
