### ISSUE TITLE
PowerShell WebJob that throws exception marked "Success"

### ISSUE THREAD

**Issue by gregjhogan** [projectkudu/kudu#2272]
If I create a powershell script run.ps1:
```ps1
$ErrorActionPreference = 'Stop'
throw 'error!'
```

And run it from the command line the same way I think the webjob framework runs it, it returns a non-zero result code:
```
C:\ > powershell.exe -ExecutionPolicy RemoteSigned -File run.ps1
error!
At C:\run.ps1:2
char:1
+ throw 'error!'
+ ~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (error!:String) [], RuntimeException
    + FullyQualifiedErrorId : error!
c:\ > echo %ERRORLEVEL%
1
```

However, when uploaded as a triggered webjob, the job is marked as successful.  It should fail, right?

![image](https://cloud.githubusercontent.com/assets/4112046/21244132/b6f4e0c8-c2e1-11e6-82c4-6cd45a532702.png)

**Comment by christianrondeau** [comment]
I would also expect that a non-zero exit code would be a failure, OR otherwise what would be the "correct" way to mark a job as failed from within a PowerShell script?

**Comment by gregjhogan** [comment]
@christianrondeau when you run the script from a command prompt the exit code is 1 (see original post).

**Comment by dstj** [comment]
So, a script failure is considered a webjob success? How can I make the webjob report a failure then?!

**Comment by davidebbo** [comment]
Interesting. From Kudu Console, try running it directly (the exact script above):

```
D:\home\site\wwwroot\app_data\jobs\triggered\Bar>powershell -ExecutionPolicy RemoteSigned -file ./run.ps1
error!
At D:\home\site\wwwroot\app_data\jobs\triggered\Bar\run.ps1:2 char:1
+ throw 'error!'
+ ~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (error!:String) [], RuntimeExc 
   eption
    + FullyQualifiedErrorId : error!
 

D:\home\site\wwwroot\app_data\jobs\triggered\Bar>echo %errorlevel%
0
```

Note how the errorlevel is 0, indicating success, even though it failed! That's why Kudu thinks it worked.

Not sure why it behaves that way.

**Comment by christianrondeau** [comment]
Looks like you're right. I thought I checked this before, looks like I was wrong. 

```
try {
	throw 'oops'
} catch {
	echo $_.Exception | format-list -force
	exit 1
}
```

or the old-school `trap`:

```
trap {
	echo $_.Exception | format-list -force
	exit 1
}

throw 'oops'
```

When I run `powershell -file .\oops.ps1; echo Code: $LASTEXITCODE` I can see the code is 1, so I guess this'll work. It's a shame we have to wrap every script in something like this just for Kudu to fail... Though I agree it's really PowerShell's fault, that's not something I noticed before dealing with in Kudu :(

**Comment by davidebbo** [comment]
You should test in Kudu console. I wonder if there may be sandbox issues that somehow affect the return code.

**Comment by gregjhogan** [comment]
Yes, try/catch and trap work if you put an `exit 1` in the catch/trap when run through the Kudu console or a web job, but I really wish you didn't have to do that because it is not intuitive.

**Comment by christianrondeau** [comment]
Well looks like using `trap` works fine, and fails the webjob. I don't know where this could be documented to help other people in the future, but at least my own issue is "solved" :) Now we just need to remember to add this everywhere.

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
