### ISSUE TITLE
Portal shows incorrect key when switching between GitHub WebHook functions

### ISSUE THREAD

**Issue by fabiocav** [projectkudu/kudu#2273]
#### Repro steps
- Create 2 GitHub WebHook functions (e.g. GithubWebhookCSharp1 and GithubWebhookCSharp2)
- Delete the default function key for GithubWebhookCSharp1
- Switch to GithubWebhookCSharp2
- Switch to GithubWebhookCSharp1: The incorrect key (from GithubWebhookCSharp2) will be used/displayed

**Comment by fabiocav** [comment]
@mathewc this is one of the issues I mentioned

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
