### ISSUE TITLE
Cleanup Unexpected Error written to filesystem

### ISSUE THREAD

**Issue by suwatch** [projectkudu/kudu#2275]
This turns out to be noisy than anything useful for customers.   Need to review and clean them up.

http://stackoverflow.com/questions/41177787/what-could-cause-the-too-many-changes-at-once-in-directoryd-home-site-wwwroot

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
