### ISSUE TITLE
404 files when publishing to azure using github CI but only the first time. Redeploy same commit works.

### ISSUE THREAD

**Issue by Bartmax** [projectkudu/kudu#2277]
copied from: https://github.com/aspnet/Home/issues/1879

I'm using ASPNET Core with grunt,bower version 1.1 (using project.json)
Every time I push to master, a build is triggered (configured on azure CI portal).

The first time, it publish successfully but all js and css are missing. (took like 10 mins to publish) (no files on disk and 404 errors) [grunt failed??]

Then I click on redeploy on azure portal (without touching anything from code) (it took a little less than previous one) and the second time it publishes successfully.

Note: I already published this way like 20 times, 18 out of 20 got the error but not always.
Note2: I never had to redeploy more than once. Everytime it fails, I click redeploy and every go smoothly on the 2nd try.

I find it hard to "debug" this but it's getting very annoying since the build got more frequent. Any ideas?

**Comment by watashiSHUN** [comment]
can you share your Web App name, directly or [indirectly](https://github.com/projectkudu/kudu/wiki/Reporting-your-site-name-without-posting-it-publicly)? I'll take a look at what's going on.

**Comment by Bartmax** [comment]
this one: dummyfordiscovery

**Comment by tinchou** [comment]
I'm experiencing a similar issue. Since around 2 weeks I need to deploy twice to get my changes live. I'm using VS 2017 csproj without any special configuration.

**Comment by watashiSHUN** [comment]
@Bartmax I tried to build your project locally in my VS2015, but it failed at restoring packages...

```
bower startbootstrap-sb-admin-2#^1.0.8     ENORESTARGET No tag found that was able to satisfy ^1.0.8
Additional error details:
No versions found in https://github.com/IronSummitMedia/startbootstrap-sb-admin-2.git
```
it looks like there is an [issue](https://github.com/ironsummitmedia/startbootstrap-sb-admin-2/issues/1) with bower, and after I made the following change:

![capture](https://cloud.githubusercontent.com/assets/6531400/21406239/69063b08-c77f-11e6-93e0-d6a9b813e11a.JPG)

my Azure deployment is **successful**, I wasn't able to reproduce your issue...

> Note: I already published this way like 20 times, 18 out of 20 got the error but not always.

what exactly is the error message you are seeing, mine just shows `Deployment successful`

**Comment by Bartmax** [comment]
There's no error on publish. The problem is client side files (CSS,js, etc) are not copied to target folder and you got 404 not found when accessing the site for those files. 

Sent from my iPhone 




On Wed, Dec 21, 2016 at 6:24 PM -0300, "watashiSHUN" <notifications@github.com> wrote:












@Bartmax I tried to build your project locally in my VS2015, but it failed at restoring packages...
bower startbootstrap-sb-admin-2#^1.0.8     ENORESTARGET No tag found that was able to satisfy ^1.0.8
Additional error details:
No versions found in https://github.com/IronSummitMedia/startbootstrap-sb-admin-2.git



it looks like there is an issue with bower, and after I made the following change:





my Azure deployment is successful, I wasn't able to reproduce your issue...



Note: I already published this way like 20 times, 18 out of 20 got the error but not always.



what exactly is the error message you are seeing, mine just shows Deployment successful

**Comment by Bartmax** [comment]
Please remove the project name from the image/references. I'm rather prefer to not disclose the name publicly 

Sent from my iPhone 




On Wed, Dec 21, 2016 at 6:24 PM -0300, "watashiSHUN" <notifications@github.com> wrote:












@Bartmax I tried to build your project locally in my VS2015, but it failed at restoring packages...
bower startbootstrap-sb-admin-2#^1.0.8     ENORESTARGET No tag found that was able to satisfy ^1.0.8
Additional error details:
No versions found in https://github.com/IronSummitMedia/startbootstrap-sb-admin-2.git



it looks like there is an issue with bower, and after I made the following change:





my Azure deployment is successful, I wasn't able to reproduce your issue...



Note: I already published this way like 20 times, 18 out of 20 got the error but not always.



what exactly is the error message you are seeing, mine just shows Deployment successful

**Comment by davidebbo** [comment]
@Bartmax I edited @watashiSHUN's entry.

**Comment by watashiSHUN** [comment]
My bad, 
so I looked at your project build, the problem is that you construct `wwwroot\` folder during the publish process (`prepublish`), but its not being picked up by `dotnet publish`...my theory is that it checks your `"publishOptions":{"include":["wwwroot"]}` in `project.json`, if the folder does not exist, it simply removes it from the list, **then** it runs the `prepublish scripts` followed by copy commands

so that every time you push to Azure, `wwwroot\` folder will be created under website repository during `publish` but only when you **redeploy** (republish), it will be copied since the second time, file existance test will pass

it's just a theory, not confirmed yet. But for now, your easiest workaround it simply change your `project.json`:

```
   "scripts": {
     "prepare": "...",
-    "prepublish": [ ... ],     //from this
+    "postcompile": [ ... ],    //to this
```

**Comment by Bartmax** [comment]
thank you @watashiSHUN, sounds very reasonable. I'll try that workaround and see if that helps.

**Comment by Bartmax** [comment]
@watashiSHUN now that we are in `csproj` land. Is there any alternative for this to work? Can something be done on csproj ?

**Comment by watashiSHUN** [comment]
you mean `prepublish` and `postcompile`? , I believe `.csproj` has some options: [this](https://msdn.microsoft.com/en-us/library/dd293582.aspx) and [this](https://msdn.microsoft.com/en-us/library/ms366724.aspx).

**Comment by Bartmax** [comment]
@watashiSHUN no, does options behave exactly the same as project.json. I was thinking about something about include content but i figured that my folder is not on source control, so I added a .gitignore file inside wwwroot and included the empty folder on source control. I just saw your edit: 
> or add an empty wwwroot\ folder

hope that fixes it :)

**Comment by Bartmax** [comment]
@watashiSHUN mm. having an empty wwwroot on source control does NOT fixed the publish issue. I still have to redeploy twice to get assets. Why that would be the case?

**Comment by watashiSHUN** [comment]
looks like "dummyfordiscovery" is no longer available, can you share another one?

**Comment by Bartmax** [comment]
created `dummyfordiscovery` again.

**Comment by watashiSHUN** [comment]
How did you add the `wwwroot` folder? I don't see that commit in the git logs. Here's what I tried:
1. add an empty file `src/yourProject.Web/wwwroot/.gitkeep`
2. edit the `.gitignore`:
```
-wwwroot/
+wwwroot/*
+!wwwroot/.gitkeep
```
after pushing to Azure, I verify the existence of `D:\home\site\wwwroot\wwwroot>`

**Comment by Bartmax** [comment]
![image](https://cloud.githubusercontent.com/assets/3386797/24571543/5093f0ca-1648-11e7-81a8-fe7b2a6e46ac.png)

mmmm weird, it's there on the repo

**Comment by watashiSHUN** [comment]
My mistakes, I was looking at your old project, I didn't realize that your repository is actually under `D:\local`. Unfortunately I am not an expert in `dotnet core` or `msbuild`. I am not sure why `wwwroot` is not copied(this does not look like a kudu bug), you probably need to edit your `.csproj`. I suggest you ask on stackoverflow

what I tried (and luckily worked) is this:
```
   <Target Name="PrepublishScript" BeforeTargets="PrepareForPublish">
     <Exec Command="npm install" />
     <Exec Command="bower install" />
     <Exec Command="gulp clean" />
     <Exec Command="gulp build" />
+       <ItemGroup>
+               <_CopyItems Include="wwwroot\**\*.*" />
+       </ItemGroup>
+       <Copy SourceFiles="@(_CopyItems)" DestinationFolder="$(PublishDir)\wwwroot\%(RecursiveDir)" />
   </Target>
```

you can do this kind of [recursive copy](https://blogs.msdn.microsoft.com/msbuild/2005/11/07/how-to-recursively-copy-files-using-the-copy-task/) at different stages of the build/publish life cycle, does that help?

**Comment by Bartmax** [comment]
@watashiSHUN I'll give it a try and let you know. i'm wondering why no one else seems to have this problem.

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
