### ISSUE TITLE
Show AlwaysOn disabled warning for CRON triggered jobs as well

### ISSUE THREAD

**Issue by mathewc** [projectkudu/kudu#2282]
See SO post here: http://stackoverflow.com/questions/41187818/cron-scheduled-webjob-abruptly-quit-being-called/41201892#41201892

We have logic [here](https://github.com/projectkudu/kudu/blob/master/Kudu.Core/Jobs/ContinuousJobRunner.cs#L80) in the continuous job runner to ensure that AlwaysOn is enabled. However, we don't have this currently for the TriggeredJobRunner, which is used for CRON jobs.

We should do this same check for cron jobs as well, since AlwaysOn is required for them as well.

**Comment by JoeStanton** [comment]
This caught us today. Please fix.
