### ISSUE TITLE
/deploy API: Wiki documentation doesn't specify correct github clone string for private repos

### ISSUE THREAD

**Issue by bedej** [projectkudu/kudu#2283]
In order to deploy using the REST /deploy endpoint from a private github repo, an SSH key is required. This is documented in multiple locations, including:

- https://github.com/projectkudu/kudu/wiki/REST-API
- https://github.com/projectkudu/kudu/wiki/Continuous-deployment

What doesn't seem to be documented, and what had me tearing my hear out for a while, is that when using SSH key and a private repo, the URL used to access the github repo posted as the JSON body of the /deploy call must change from:

{ format: 'basic', url: 'https://github.com/SomeOrg/SomeRepo.git' } 

To:

{ format: 'basic', url: 'git@github.com:SomeOrg/SomeRepo.git' } 

Would be great to add this information to the Wiki (assuming it is a requirement, and not a bug - maybe there's some Kudu code that is trying to magically do the conversion in the background that has broken?)

Thanks,
Bede

**Comment by davidebbo** [comment]
Thanks I added a clarification to https://github.com/projectkudu/kudu/wiki/REST-API.
