### ISSUE TITLE
404 errors after deployment

### ISSUE THREAD

**Issue by robfarmergt** [projectkudu/kudu#2285]
We are having an issue where after deployment, all of our script and css files are not being loaded by the client. All are returning 404 errors even though I can confirm using the Diagnostic Console in the Kudu tool that the files are there.

**Comment by robfarmergt** [comment]
Certain directories are served up but others aren't. For example we can point our browser to files in `/images` and `/css` just fine. However, other directories that house or .js files `/lib` and `/dist` for example, will not allow us  to access those files from a browser.

All of these directories are user `/site/wwwroot`.

Any help is appreciated.

**Comment by davidebbo** [comment]
If all the files are in the right place, it doesn't sound like a Kudu/Deployment issue. See https://github.com/projectkudu/kudu/wiki/Deployment-vs-runtime-issues.

Does restarting the site, does it still happen? What about if you go back to the previous version of your site?

**Comment by robfarmergt** [comment]
We *just* figured it out. We were setting `WEBSITE_NODE_DEFAULT_VERSION` and `WEBSITE_NPM_DEFAULT_VERSION` manually (to fix an earlier deployment issue). We removed those overrides and redeployed and it fixed it.

We do have other WebApp environments running the same exact codebase that did not result in the same issue with those npm and node variables set.

Is there some other difference in the WebApp environments that might cause issues with all the same configuration settings?

**Comment by davidebbo** [comment]
In theory no. If they have the exact same set of files and site settings (including Azure app settings and other Azure settings), they should behave the same way. Check if you have an `iisnode.yml` in wwwroot which could point to a different runtime and override the runtime node version (using `nodeProcessCommandLine`).

**Comment by robfarmergt** [comment]
No, we don't have `iisnode.yml`. Any other ideas? 

This tends to take a half day to figure out whenever it happens. We're worried something like this might happen when deploying to our production environment causing downtime.

**Comment by davidebbo** [comment]
Note that `iisnode.yml` can be created by Kudu deployments. So the question is not whether you're deploying one, but whether you end up with one. Similar setting exists [in web.config](https://github.com/tjanczuk/iisnode/blob/c816a6740ae63e2c3065653539ea18b9c5edfce6/src/samples/configuration/web.config#L150).

Do you have a site in this state now? And do you have a proper `engines` specification in your package.json?

**Comment by robfarmergt** [comment]
I checked the filesystem in the Kudu tool for the `iisnode.yml` and it wasn't there.

Our `package.json` does not specify `engines`. Should it? Do we need to make sure the versions are compatible with Azure?

**Comment by davidebbo** [comment]
Yes, you do need to make sure it's compatible. This is rarely a problem unless you hard code a build (as opposed to some ~ or ^ range), which is atypical.

If you have `engines` and you don't get an iisnode.yml, it's not normal. It should always create one. Do the sites that *didn't* have the issue have one?

**Comment by robfarmergt** [comment]
Both sites (QA and Demo) had ` WEBSITE_NODE_DEFAULT_VERSION : 4.6.0` and `WEBSITE_NPM_DEFAULT_VERSION : 3.10.3` set using the `Application settings > App settings` blade.

QA deployed just fine without issues. When we tried to deploy to Demo we had issues explained in this thread.

We removed the `WEBSITE_NODE_DEFAULT_VERSION` and `WEBSITE_NPM_DEFAULT_VERSION` entries from Demo, redeployed and it deployed and is running fine now. QA still has those set and we tried redeploying and it works. So same settings in both, different results.

Neither site currently has a `iisnode.yml`.

Is specifying `engines` any different than setting the `WEBSITE_NODE_DEFAULT_VERSION` and `WEBSITE_NPM_DEFAULT_VERSION` entries in the Application settings blade in Azure?

**Comment by davidebbo** [comment]
`engines` is processed at deployment time by Kudu, and is turned into `iisnode.yml`. `WEBSITE_NODE_DEFAULT_VERSION` directly affects the runtime if there is no hardcoded path to a node.exe in `iisnode.yml` (or `web.config`).

When you get the problem, the first thing you should do is check what actual Node version you are running (e.g. by checking the node.exe path in Kudu process explorer).

If you don't have a site in that state now, can you put back the app settings you removed so you can get a repro?

**Comment by robfarmergt** [comment]
We can't revert demo because our maintenance window is over for now.

We can try explicitly setting the versions in `engines` in dev and qa and try deploying to demo during our next update to see if that resolves the inconsistencies.

You can close this out for now until we can repro. I can always open another issue later.

**Comment by davidebbo** [comment]
Sounds good.

**Comment by robfarmergt** [comment]
Thanks for your help and have a great New Year!
