### ISSUE TITLE
Ability to add deployment history after a msdeploy deployment

### ISSUE THREAD

**Issue by slapointe** [projectkudu/kudu#2286]
I have a scenario where we would like to add a deployment to deployments history when not hooked to git/SCM (we deploy to webapp via msdeploy).

Presently, when I call PUT `/api/deployments/{id}` using the second payload (*Add a deployment status to history*) I receive the following error: "Repository could not be found."

I would like this scenario supported so we can have a history of deployments we perform manually.

**Comment by davidebbo** [comment]
The full API detail is on https://github.com/projectkudu/kudu/wiki/REST-API#deployment

@suwatch does using this API require scm type to be set to something other than None?

@slapointe as a test, try artificially setting it to "LocalGit" using https://resources.azure.com/ (under config/web under the site).

**Comment by suwatch** [comment]
> does using this API require scm type to be set to something other than None?

ScmType can be anything including None.

> Presently, when I call PUT /api/deployments/{id} using the second payload (Add a deployment status to history) I receive the following error: "Repository could not be found."

Make sure your payload have all the required properties mentioned on https://github.com/projectkudu/kudu/wiki/REST-API#deployment.   Example, ...

```
curl -X PUT "https://user:password@mysite.scm.azurewebsites.net/api/deployments/1234" -d "{status:4,message:'test message',author:'test author',deployer:'test deployer'}" -v -H "Content-Type: application/json"
```

**Comment by slapointe** [comment]
I found the problem with the help of suwatch example. I was using POSTMAN with the wrong content-type.

It does work with ScmType set to None. The body content type must be: **application/json**, anything else (Text was set by default in my case) is giving me the error message mentioned above: "Repository could not be found."

Can it be detected and/or provide a better error message?
