### ISSUE TITLE
Web client networking issues for outgoing SSL connections

### ISSUE THREAD

**Issue by PShchegolevatykh** [projectkudu/kudu#2289]
I migrated a legacy console app into the Azure Webjob. The app was automating an external website via web client (HttpWebRequest/HttpWebResponse manipulation using SSL connections via 443 port). The app does authentication (by sending proper Cookies in request header), form submits, file uploads etc. It's all done in a synchronous way (hanging thread to wait for the response).

The problem is that at some random point I'm getting disconnected from this external website only if I run the app on Azure.

If I run the exact same code (that was written using Azure Webjob SDK) as a Console App or Windows Service and it works fine.
If I run this in Kudu Console or as a WebJob it fails without any exceptions. The external website makes the cookies invalid somehow and disconnects the client.

I did request/response objects dumps on each call through the code and additional network tracing via App.config and it seems that everything's the same in terms of sending things over the wire across local and Azure Sandbox environments.

Why is this happening? I know it could be something specific but feel frustrated about it since it happens only on Azure Sandbox Environment. Maybe the default ServicePointManager settings are different from the local environments, or there's some proxy being involved on the requests, or something else.

**Comment by davidebbo** [comment]
I'm curious if you'd see the same when making the same requests using `curl` from Kudu console, to idolate from anything your console app might be doing.

**Comment by PShchegolevatykh** [comment]
I'll try to repeat that process using curl and let you know if I had anything like that.

**Comment by PShchegolevatykh** [comment]
Sorry for long reply. I repeated the whole process with curl and getting the same results. I'm getting logged out only on Azure Sandbox.

**Comment by davidebbo** [comment]
Interesting. So generally, you can curl down random other things, but it's failing just with this one server? Any chance you can share a specific URL that doesn't work? There must be something different about it.

**Comment by davidebbo** [comment]
Hmmm, it does seem reminiscent of [this thread](https://social.msdn.microsoft.com/Forums/azure/en-US/ca6372be-3169-4fb5-870f-bfbea605faf6/azure-webapp-webjob-exception-could-not-create-ssltls-secure-channel?forum=windowsazurewebsitespreview), which I'm not sure was quite resolved.

**Comment by PShchegolevatykh** [comment]
Hi David,
Yes basically:
If I curl from local machine or Azure VM it works fine.
If I curl from Azure kudu console it fails (getting logged out after some successful requests)

Here's the url. Initial requests are working fine.
https://www.ssllabs.com/ssltest/analyze.html?d=ecf-test.ilnb.uscourts.gov

If I can contact you directly by Email I could share all the steps to reproduce the issue with curl. I could not do that here for security reasons.

The topic you've mentioned is pretty similar though I do not receive any error messages from the web service.

**Comment by davidebbo** [comment]
If that's the URL, isn't the curl step to simply run `curl https://www.ssllabs.com/ssltest/analyze.html?d=ecf-test.ilnb.uscourts.gov -o test.html` from Kudu Console? Though I just tried that and it worked for me.

**Comment by PShchegolevatykh** [comment]
Sorry for the late reply. This is not the exact URL, there are some steps to reproduce that involve multiple requests in curl. I could make a screencast of how to reproduce this in two weeks or so. It would be better if I could contact you directly in some way. There are some privacy concerns. Is it possible?

**Comment by davidebbo** [comment]
@PShchegolevatykh it's best to open a support case so it can be discussed privately. Also, note that the issue here is not related to Kudu, but more likely to the sandbox environment under which both Kudu and web applications run.

**Comment by PShchegolevatykh** [comment]
@davidebbo Could you please point me to where I should open a support case for the sandbox environment issues? So I could close it here. I agree that's it must be related to the sandbox environment.

**Comment by davidebbo** [comment]
To open a new support case for a Web App, go to the Web App in Azure Portal, then choose New support request.

Also, for general (non-Kudu specific) discussions on Web Apps, you can use the [forum](https://social.msdn.microsoft.com/Forums/azure/en-US/home?forum=windowsazurewebsitespreview).
