### ISSUE TITLE
api/zip URI should include a trailing '/' in the end

### ISSUE THREAD

**Issue by cmatskas** [projectkudu/kudu#2290]
In the Kudu REST API documentation, we have a section about the `api/zip/{path}`. However, if the trailing `/` is missed, then any call will result to an HTTP 307 Redirect error.
For example, this request will fail `https://<yoursite>.scm.azurewebsites.net/api/zip/site/wwwroot` whereas this will succeed `https://cmtestfunction.scm.azurewebsites.net/api/zip/site/wwwroot/`. 

The difference may be subtle but the resulting error is extremely confusing. I'll be happy to send a PR with a fix

**Comment by davidebbo** [comment]
I clarified the doc.

**Comment by cmatskas** [comment]
Great resolution @davidebbo . Thanks for all your help today!
