### ISSUE TITLE
Kudu in German data centers

### ISSUE THREAD

**Issue by sjkp** [projectkudu/kudu#2293]
Is the kudu portal not working for websites hosted in the german azure data centers? 

I'm trying to browse my site on mysite.scm.azurewebsites.de and gets correctly redirect to the azure ad login portal for azure germany, but when it redirects me back to the kudu portal i get the unauthorized page saying that I have no azure subscription. 
![image](https://cloud.githubusercontent.com/assets/3397744/21867131/1f117baa-d84d-11e6-97ef-4ed3fc8f7b68.png)

And yes I'm typing my password correct, and if I browse portal.microsoftazure.de in the same browser sessions I get logged in without issues. 

I need access to the kudu portal in order to access my site extension, which I just updated to work in german datacenters, now for no reason :(

**Comment by audacity76** [comment]
KUDU is working on my site using the german data center. Didn't configure anything special. It worked out of the box.

**Comment by sjkp** [comment]
@audacity76 that is annoying, guess I have to open a support ticket. Wonder if it's due to the account is set as a free trial.

**Comment by sjkp** [comment]
Turns out Azure Germany support are pretty damn fast at answering. 

And it is a know issue, that the benjaminperkins answering my support ticket have blogged about before: 
https://blogs.msdn.microsoft.com/benjaminperkins/2017/01/09/how-to-kudu-using-your-publishing-profile/
