### ISSUE TITLE
Removing Azure Deployment Credentials

### ISSUE THREAD

**Issue by Baklap4** [projectkudu/kudu#2298]
By accident i created Deployment Credentials with a user/password so i could deploy by FTP.

Since i'm using Gitlab there's no need to deploy by FTP. How would i be able to remove the Deployment Credentials from Azure? Since deploying is broken now...

**Comment by davidebbo** [comment]
Deployment credentials exist as an Azure Web App concept that is separate from Kudu (e.g. they're also used for FTP), so it's not the right place to report. Can you start a thread on https://social.msdn.microsoft.com/Forums/azure/en-US/home?forum=windowsazurewebsitespreview instead, and point to it here? I'll try to get someone to respond there.
