### ISSUE TITLE
Auto Swap doesn't work with Git Push

### ISSUE THREAD

**Issue by sheam** [projectkudu/kudu#2303]
My prod site has 1 staging slot. I push my code to my staging slot, and then swap it with the production slot. When I enable the auto-swap feature, and push, I do not get an error, but I push my site with the autoswap feature enabled, the new code does not appear in on the production URL.

**Comment by davidebbo** [comment]
If you look at the full deployment log, does anything mention swapping toward the end?

**Comment by sheam** [comment]
- transform files for publish
- copying files
- then it runs my migration script (deploy.cmd)
- then it says finished successfully.

No mention of a swap.

**Comment by sheam** [comment]
I was looking in azure logs. Actually in the git window it self it mentioned the swap, and it seem to be working fine. So I am not sure why it wasn't working before. I'll close this issue, and re-open if it happens again with more info.
