### ISSUE TITLE
tsd install fails with azure deployment

### ISSUE THREAD

**Issue by ntanveer** [projectkudu/kudu#2306]
I am new to kudu and azure deployments. Any help in this would really appreciated.

I have the following pre-build script in my project:
`call cd $(ProjectDir)Client
call npm install
call tsd install`

Azure deployment triggered automatically from gitbhub commit using kudu fails with this error when publishing:
npm ERR! System Windows_NT 6.2.9200
  npm ERR! command "node" "D:\\Program Files (x86)\\npm\\1.4.28\\node_modules\\npm\\bin\\npm-cli.js" "install"
  npm ERR! cwd D:\home\site\repository\src\Empactis.Insights.Web\Client
  npm ERR! node -v v0.10.32
  npm ERR! npm -v 1.4.28
  npm ERR! code ETARGET
  npm'tsd' is not recognized as an internal or external command,
  operable program or batch file.

Azure deployment works fine when i manually publish from within VisualStudio.

**Comment by davidebbo** [comment]
Seems you are using a very old Node. In your Azure App Setting, can you try setting `WEBSITE_NODE_DEFAULT_VERSION` to `6.9.4`. Also, try isolating from the command line, per [this doc](https://github.com/projectkudu/kudu/wiki/Isolating-WebJobs-and-Deployment-script-issues).

**Comment by ntanveer** [comment]
Thanks, I will try this and post an update here.

**Comment by ntanveer** [comment]
I found the problem. Thank you for your help. Isolating from the command line did help.
