### ISSUE TITLE
Linux: Kudu uses wrong path separator in $PATH

### ISSUE THREAD

**Issue by nickwalkmsft** [projectkudu/kudu#2309]
On startup, Kudu prepends a bunch of computed paths to the PATH environment variable. It uses ";" as the path separator, which works on Windows but is broken on Linux.

https://github.com/projectkudu/kudu/blob/719319a11cf4a75608914696482e7d20aff0b56d/Kudu.Services.Web/App_Start/NinjectServices.cs#L701-L723

Needs to detect Linux and use ":" instead.

Same for Env.cshtml:
https://github.com/projectkudu/kudu/blob/719319a11cf4a75608914696482e7d20aff0b56d/Kudu.Services.Web/Env.cshtml#L84

**Comment by davidebbo** [comment]
Yep. I don't suppose there is fx support for this like we have `Path.PathSeparator` to get the right slashes?

**Comment by nickwalkmsft** [comment]
Whoa, thanks for making me actually go look :)

https://msdn.microsoft.com/en-us/library/system.io.path.pathseparator(v=vs.110).aspx

**Comment by davidebbo** [comment]
Ha, I was thinking `Path.DirectorySeparatorChar`! :)

**Comment by nickwalkmsft** [comment]
Also need to look around elsewhere in the codebase where semicolons may be hardcoded in relation to $PATH.

**Comment by nickwalkmsft** [comment]
Closing as fixed.
