### ISSUE TITLE
Functions API can return extremely large response if there is large test data

### ISSUE THREAD

**Issue by davidebbo** [projectkudu/kudu#2311]
For each function, the API returns the test data in the `test_data` field. This comes from the data file in `D:\home\data\Functions\sampledata\[functionname].dat`.

Problem is that if that data is extremely large, it can result in an ARM response that it larger than the supported limit (which I think is 4MB). In the case we ran into, the data file was 4.7MB, and with all the escaping, that resulted in a response that was about 6MB.

Conceivably, the API could omit the test data if it's too large.

The API at stake is /api/functions/MyFunc, which through ARM looks like

    get /subscriptions/{sub}/resourceGroups/{rg}/providers/Microsoft.Web/sites/{functionapp}/functions/MyFunction?api-version=2015-08-01

Details on https://github.com/projectkudu/kudu/wiki/Functions-API

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
