### ISSUE TITLE
Linux: /environment throws exception

### ISSUE THREAD

**Issue by nickwalkmsft** [projectkudu/kudu#2312]
The /environment route, which returns version and siteLastModified data, throws an exception and returns a stack trace on a Linux site.

Culprit appears to be missing $TMP env var. I don't think SiteLastModifiedTime.txt exists on Linux sites either.

https://github.com/projectkudu/kudu/blob/06eb338f81e8ef91a1fd1fa75760a104eac3868a/Kudu.Services/EnvironmentController.cs#L30

**Comment by davidebbo** [comment]
It's a file written by DWAS to tell the site when the config was last modified. However, the code does handle this file not being there.

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
