### ISSUE TITLE
Master.lock not automatically removed

### ISSUE THREAD

**Issue by etm-admin** [projectkudu/kudu#2316]
Our apps deploy from git automatically and we run into a blocker with this where we need to manually resolve. Can't this be handled automatically? E.g. looking at the date of the lock and deleting automatically if it is older than 2 hours? 

> 'D:/home/site/repository/.git/refs/remotes/origin/master.lock': File exists.\n\nIf no other git process is currently running, this probably means a\ngit process crashed in this repository earlier. Make sure no other git\nprocess is running and remove the file manually to continue.

**Comment by davidebbo** [comment]
This should not normally happen unless you run into a process crash, or something else that's abnormal. Are you getting this consistently?

I do agree that we could theoretically auto-clean up when this happens, though I prefer not to mess with git 'internal' files if we can avoid it.

**Comment by etm-admin** [comment]
We are using the largest app service instance. Each update of the source code results in at least a couple of the sites which get updates from github to have this status which is making it very difficult to find out and mitigate. auto clean-up would be great.

**Comment by davidebbo** [comment]
But when that happens, is the deployment successful? Do you see anything unusual in the deployment log?

The primary concern here should not be cleaning the lock file, but understanding why it's getting left there in the first place.

**Comment by etm-admin** [comment]
No it isn't successful. you cant delete the deployment and clicking sync doesn't work on the azure portal. only manually going to the folder and deleting the lock works which is allowed for very few persons in an organization.

It is a computer system with too many components. 100% reliability does not happen and that's okay. it is just if a lock file is blocking the deployment and it is there for more than a couple of hours it doesn't have any use anymore and needs to be cleaned up.

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
