### ISSUE TITLE
azure log tail, do not stop when application redeploys

### ISSUE THREAD

**Issue by cesarvarela** [projectkudu/kudu#2321]
I'm using Github continuous integration, and every time I deploy a new version, the log stops and I have to execute the shell command again. I think it should keep logging while redeploying otherwise you miss importan information on app startup (in this case this is a Node js project)

```
2017-02-12T22:28:17  Stream terminated due to timeout 30 min(s).
info:    <Buffer 32 30 31 37 2d 30 32 2d 31 32 54 32 32 3a 32 38 3a 31 37 20 20 53 74 72 65 61 6d 20 74 65 72 6d 69 6e 61 74 65 64 20 64 75 65 20 74 6f 20 74 69 6d 65 ... >
info:    site log tail command OK
```

**Comment by davidebbo** [comment]
Based on the output you show, the reason the stream stopped is that there had been no output for 30 minutes. It is not related to the fact that you are deploying.

If you start the log streaming right before deploying, it should not get discontinued by the deployment.

**Comment by cesarvarela** [comment]
@davidebbo well that might be the wrong example, but look at this:

```
2017-02-13T14:44:20  The application was terminated.
info:    <Buffer 0d 0a 32 30 31 37 2d 30 32 2d 31 33 54 31 34 3a 34 34 3a 32 30 20 20 54 68 65 20 61 70 70 6c 69 63 61 74 69 6f 6e 20 77 61 73 20 74 65 72 6d 69 6e 61 ... >
info:    site log tail command OK
```

I just tweaked an environment variable, and the log stopped. It's really annoying. I've seen it happening between deploys too.

**Comment by davidebbo** [comment]
Setting an Azure App Setting restarts the app, which will disconnect the log stream. But this is different from the scenario you described here, where a **Github deployment** is disconnecting the stream. That should not happen.
