### ISSUE TITLE
MiniDump write dump does not dump the thread times

### ISSUE THREAD

**Issue by suwatch** [projectkudu/kudu#2322]
`!runaway` is not working.

```
0:000> !runaway
ERROR: !runaway: extension exception 0x80004002.
    "Unable to get thread times - dumps may not have time information"
```

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
