### ISSUE TITLE
Linux: Kudu does not work when WEBSITE_DISABLE_SCM_SEPARATION is set to true

### ISSUE THREAD

**Issue by fcatae** [projectkudu/kudu#2324]
I am not sure whether it is documented, but Kudu fails when WEBSITE_DISABLE_SCM_SEPARATION is set to true.

Repro:
- Create an Azure Web App on Linux
- Select Docker Image = DotNetCore
- Set WEBSITE_DISABLE_SCM_SEPARATION = true in AppSettings
- Try to open https://<site>.scm.azurewebsites.net
- It never loads Kudu

Impact: When Docker doesn't start properly, it makes it easier to check if the binaries are present in the image.

**Comment by nickwalkmsft** [comment]
This feature (or the Docker/Linux equivalent, which would be running the Kudu site in the same container as the main site) is not available on App Service for Linux.

We will be looking at options for greater visibility into the main site container's process space and filesystem in the future, but right now Kudu's visibility into the main site is limited to the /home directory, which is mounted to both the Kudu container and the main site container.

That said, setting this to true to true shouldn't break the site, and this issue should remain open until that's fixed.

**Comment by fcatae** [comment]
Thanks for the answer!

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
