### ISSUE TITLE
Error in wiki page on manually triggering a deployment

### ISSUE THREAD

**Issue by dabide** [projectkudu/kudu#2325]
The *Manually triggering a deployment* wiki page has  an error. It says:
```
For Mercurial (hg) add `"is_hg": true` to the JSON payload.  
```

This doesn't work. It should be:
```
For Mercurial (hg) add `"scm": "hg"` to the JSON payload.
```

**Comment by davidebbo** [comment]
Looking at the [code](https://github.com/projectkudu/kudu/blob/4d1a9d99723b1674e24e5b386b3c0e5a3ee92608/Kudu.Services/ServiceHookHandlers/GenericHandler.cs#L33-L43), I think you're right. @suwatch?

**Comment by suwatch** [comment]
Fix the [wiki page](https://github.com/projectkudu/kudu/wiki/Manually-triggering-a-deployment).
```
For Mercurial (hg), unless the url begins with hg@, do add "scm": "hg" to the JSON payload.
```
