### ISSUE TITLE
Incomplete wiki page on changing the deployment branch

### ISSUE THREAD

**Issue by caterwomtious** [projectkudu/kudu#2326]
This page needs two updates:
https://github.com/projectkudu/kudu/wiki/Deployment-branch

Firstly this comment needs to be qualified:

> The Azure portal (portal.azure.com) also has UI to change this:
> Deployment options blade -> Disconnect -> Setup -> Choose branch.

This UI doesn't exist for the "Local git repository" deployment source. It does exist for github and possibly others.

Secondly it omits to mention that you can set an Azure app setting called "deployment_branch" to the name of the branch you want to deploy.

I haven't tried the API to know whether that works for the "Local git repository" option.

**Comment by davidebbo** [comment]
It's really a Portal bug that this is not possible today (we'll track this). I updated the doc for now. Thanks for reporting!
