### ISSUE TITLE
Documentation issue

### ISSUE THREAD

**Issue by prashanthmadi** [projectkudu/kudu#2327]
I don't see "Team Services accounts" anymore in Marketplace as described in below link
https://github.com/projectkudu/kudu/wiki/Setting-up-a-VSTS-account-so-it-can-deploy-to-a-Web-App

**Comment by rmarr2** [comment]
I can see this for my account. Try going to  https://app.vsaex.visualstudio.com  and log in with the same Microsoft account and see if  you see your account.

**Comment by prashanthmadi** [comment]
I remember seeing it 2 weeks back. Below is the screenshot of marketplace with search results 

![image](https://cloud.githubusercontent.com/assets/1486808/22994164/7e414e9e-f38b-11e6-9d42-80648578f4e6.png)

**Comment by davidebbo** [comment]
Don't go in Marketplace. Instead, click 'More Services' at the bottom of the list, and then type 'team'.

![image](https://cloud.githubusercontent.com/assets/556238/22995093/3ffb85c6-f37e-11e6-9f0f-8368a1cecd48.png)

![image](https://cloud.githubusercontent.com/assets/556238/22995107/4fbcf99a-f37e-11e6-8c8b-e481720bdfcc.png)

**Comment by prashanthmadi** [comment]
@davidebbo  Thanks... it worked 

I don't have access to below link.  could you please update that screenshots.
https://github.com/projectkudu/kudu/wiki/Setting-up-a-VSTS-account-so-it-can-deploy-to-a-Web-App

**Comment by davidebbo** [comment]
I added a comment that says the screenshot is a bit different now.
