### ISSUE TITLE
WALs taking so much space.

### ISSUE THREAD

**Issue by Tusharsharma3** [projectkudu/kudu#2331]
I have a hive table that is of 2.7 MB (which is stored in a parquet format). When I use impala to convert this hive table to kudu, I notice that the /tserver/ folder size increases by around 300 MB. Upon exploring further, I see it is the /tserver/wals/ folder that holds the majority of this increase. I am facing serious issues due to this. If a 2.7 MB file generates a 300 MB WAL, then I cannot really work on bigger data.

**Comment by davidebbo** [comment]
I think you are looking for a different Kudu project :)
