### ISSUE TITLE
Why does a site swap restart kudu site?

### ISSUE THREAD

**Issue by dennis-yemelyanov** [projectkudu/kudu#2332]
I noticed that during a swap the kudu site gets restarted, killing all the continuous webjobs that are executing at the moment. I've read the [Understanding site swaps](https://github.com/projectkudu/kudu/wiki/Understanding-site-swaps) wiki page and it mentions some reasons for the staging site to be restarted. In this case I don't have any 'slot' settings or any source control integration set up. What else might be causing it to restart?

Is there a way to prevent the kudu site from being restarted, so all the jobs can keep running uninterrupted?

**Comment by davidebbo** [comment]
Related to #2330

I would expect the restart behavior of the scm site (where Kudu runs) to exactly match the restart behavior of the main site. So it's likely that the main site is also getting restarted in your case.

There may be other factors that come into deciding whether a restart is needed. @ruslany may have more to say about this.

**Comment by ruslany** [comment]
Hi Dennis, if you let me know your [site name ](https://github.com/projectkudu/kudu/wiki/Reporting-your-site-name-without-posting-it-publicly)I can check what caused it to restart during swap.

**Comment by dennis-yemelyanov** [comment]
I'm trying to get a consistent repro of the issue, in the meantime I was thinking if this could be caused by enabled authentication? Is it possible that enabling it adds something to web.config and becomes 'sticky' to the slot, causing the restart?

**Comment by dennis-yemelyanov** [comment]
Ok I think I'm pretty sure Authentication might be the issue. I tried the following steps couple of times:
1. Create a new website.
2. Create a new staging slot.
3. Do a swap from staging to production, note that services are not restarted (kudu process explorer shows the same pids).
3. Enable authentication on both slots (first on production, select the AzureAD login option, create a new AzureAD app and then on staging, use newly created app).
4. Do a swap from staging to production, note that services are restarted (have different pids). Also during the swap at some point process explorer shows 3 w3wp processes, then the third process goes away.

**Comment by ruslany** [comment]
Oh right, if you use site auth then the worker processes get restarted prior to the swap in order to apply site auth settings.

**Comment by dennis-yemelyanov** [comment]
Thank you for confirming this, Ruslan. I wonder if it's possible to optimize this scenario, because auth settings for both slots are exactly the same, so maybe restart can be avoided? Or are they actually different, because slots have different application urls?
Also is there some alternative to authentication that doesn't require a restart? In this case we don't really need to know who the user is, but want to limit access so that only internal users can access it. We could probably write our own code to do it, but ideally would like to use what Azure provides out of the box.
And, lastly, as described in the related issue https://github.com/projectkudu/kudu/issues/2330, is there a way to ensure that restart will wait for currently running webjobs to gracefully shutdown? That would also solve the problem, because restart is fine as long as it doesn't kill webjobs that are in progress.

**Comment by dennis-yemelyanov** [comment]
Actually even after disabling authentication it continues to restart on swap (just tried it). Here's the website: http://dummy-swap-test3.azurewebsites.net/.
@ruslany, do you have any ideas? Maybe enabling authentication adds some config values and disabling it doesn't remove them? The issue doesn't happen if authentication was never enabled.

**Comment by ruslany** [comment]
Hi Dennis, you may be right, there might be some config setting that is left over after site auth was disabled, which causes the restart. I'll check our logs and let you know.

**Comment by dennis-yemelyanov** [comment]
Ruslan, did you have a chance to look at this issue? It seems like after I recreated the site without enabling authentication, the issues went away. However today I noticed that it started happening again, this time only one of the sites (prod/stage). Also recreating the site is obviously not a good solution for production environment, so it would be really good to know what can start causing this issue and under what conditions. This is a critical issue for my scenario, because I need to execute some long running jobs that shouldn't be interrupted during swap.
I also found that enabling CORS through the portal also causes the site to restart, however disabling this setting fixes the issue. So looks like there must be some difference in how swap handles authentication and CORS settings. Hope this info helps the investigation.

**Comment by dennis-yemelyanov** [comment]
After adding back the setting for webjobs dashboard connection the restarts don't seem to happen anymore... But it would still be good to have more understanding about the authentication setting and other setting that might affect restart behavior.

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
