### ISSUE TITLE
Graceful shutdown time for continuous webjobs due to OS updates

### ISSUE THREAD

**Issue by dennis-yemelyanov** [projectkudu/kudu#2335]
When Azure decides to update the OS running a webjob, how long does it wait for the process to shutdown gracefully before killing it? For example, the [documentation](https://msdn.microsoft.com/en-us/library/microsoft.windowsazure.serviceruntime.roleentrypoint.onstop.aspx) for Cloud Services mentions 5 minutes after the OnStop method is called. What's the time for webjobs?

It would be ideal if it waited for whatever graceful shutdown time is specified in webjob settings, but I'm not sure if that's possible.

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
