### ISSUE TITLE
Improve WebJobs Remote Debugging

### ISSUE THREAD

**Issue by mathewc** [projectkudu/kudu#2337]
From user voice here: https://feedback.azure.com/forums/169385-web-apps/suggestions/17053207-make-the-remote-debugging-of-the-webjob-more-easly

@odvoskin

**Comment by srebella** [comment]
Is there any update on this? @mathewc

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
