### ISSUE TITLE
Kudu REST call failure should be logged to azure logging table

### ISSUE THREAD

**Issue by suwatch** [projectkudu/kudu#2340]
For any REST call failure, we should log to Kusto (azure logging table).  It should contain.

  - REST api path (w/o query string)
  - Http Status
  - Exception or error message
  - RequestId for correlation - this might already be there.
  - Optionally Latency
  - Optionallu UserAgent, ClientPrincipal (these are incoming headers)

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
