### ISSUE TITLE
Some failures should be returned as 400 when going through ARM bridge

### ISSUE THREAD

**Issue by davidebbo** [projectkudu/kudu#2341]
In some cases, calls like functions listsecrets fail due to the app files being in a bad state. This ends up being an ARM 500, even though the problem really lies with the user site and not the platform.

To avoid unwanted ARM 500, we should turn those into 400 errors. But only when called via ARM.

**Comment by watashiSHUN** [comment]
Do you have a specific test case? for example if I have a key in invalid json format, I got:

```
{
  "error": {
    "code": "InternalServerError",
    "message": "System.FormatException: Invalid secrets json:...
}
```

I can add `FormatException` to the [filter](https://github.com/projectkudu/kudu/blob/master/Kudu.Services/Filters/FunctionExceptionFilterAttribute.cs), but I think this kind of error should have the same error code (400) whether its ARM/kudu REST api

**Comment by davidebbo** [comment]
Malformed json is a good example. The reason we don't want 500 level errors in the ARM case is kind of subtle. ARM APIs are being monitored for errors, and errors are counted as issues against App Service. But in this case, it's really a user error to have a malformed json, as there isn't anything we can do about it in App Service. So we want to instead return then as 400 so it doesn't screw up our API error numbers.

Yes, it's a little quirky, but it'll do what we want.

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
