### ISSUE TITLE
Function listsecret API creates secrets even when function does not exist

### ISSUE THREAD

**Issue by davidebbo** [projectkudu/kudu#2342]
e.g. doing a `POST /api/functions/bogus/listsecrets` creates and returns a secret. Instead, it should return a 404 if the Function folder does not exist.

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
