### ISSUE TITLE
The specified framework 'Microsoft.NETCore.App', version '1.1.1' was not found

### ISSUE THREAD

**Issue by tinchou** [projectkudu/kudu#2346]
Hey guys,

I'm seeing an error 502.5 when deploying my app. I went in and checked in SCM why it's not running and it turns out I get this error:

```ps
PS D:\home\site\wwwroot> dotnet .\MyProject.dll
The specified framework 'Microsoft.NETCore.App', version '1.1.1' was not found.

  - Check application dependencies and target a framework version installed at:
      D:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App
  - The following versions are installed:
      1.0.0
      1.0.0-rc2-3002702
      1.0.1
      1.0.3
      1.1.0
      1.1.0-preview1-001100-00
  - Alternatively, install the framework version '1.1.1'.
```

It was fixed when I specified a dependency on `Microsoft.NETCore.App 1.1.0`, and also when I specified `<RuntimeFrameworkVersion Condition=" '$(TargetFramework)' == 'netcoreapp1.1' ">1.1.0</RuntimeFrameworkVersion>`.

Should Kudu be installing the new runtime? Should there be any documentation for people to configure their projects?

**Comment by davidebbo** [comment]
@tinchou 1.1.1 is not quite released, so it's not yet out on Azure.

It is actually already in a couple regions if you want to give it a try and verify (just as a test): 'West Central US' and 'South East Asia'. Would appreciate if you could do a quick push test there to further help validate that the bits work for you before they go wider (which is expected to be in a few days).

**Comment by tinchou** [comment]
I'll let you know! Anyway, do you know why the app could be looking for that version if "1.1.1 is not quite released"??

**Comment by davidebbo** [comment]
I'm guessing you're app is specifically asking for this new version.

It is now deployed everywhere in Azure, so it should just work. Please verify.
