### ISSUE TITLE
Web Job Kudu maxing out azure app service CPU & RAM 

### ISSUE THREAD

**Issue by Bio2hazard** [projectkudu/kudu#2351]
Unfortunately this will be pretty vague as I had to deal with solving the issue and thus could not exactly investigate what caused it to begin with, but I will try to give as much information as I can and I hope it can be found.

We have a small app service plan that 7 days ago went from it's usual 10% CPU and 70% RAM to 30% CPU and 90+% RAM. Response time for a website hosted on the app service went from a couple of ms to 100-120 seconds.

Using the "Metrics per Instance" dashboard, we were able to trace the issue to our web jobs project.

Kudu was unresponsive, only after restarting the web app were we able to access the Kudu interface. In the process tab, we noticed that our individual web jobs were barely consuming cpu time or memory, but the w3wp.exe that hosts them was at a staggeringly high 6000s+ cpu time and 1.3 gb working set memory and 1.8 gb private memory.

We scaled the azure app service up to a medium instance, and the w3wp.exe process immediately jumped up to over 3 gb of working set memory and private memory, maxing out the medium instance.

I downloaded a minidump and profiled the w3wp.exe process, but was unable to determine where the memory was going. However, I was able to trace the CPU time usage to Newtonsoft's JSON.Net serializing.

Next, we stopped our web app completely. The "Metrics per Instance" app service remained at a high CPU and memory usage, but all sites listed under "Sites In Service Plan" showed minimal CPU and memory usage.

I *think* it started when we looked at the web job function dashboard. It had to index some 5000 items. We run a lot of small jobs, one had over 1.1 million recorded function invocations.

To fix it, I deleted all web jobs related blod storages, killed the offending w3wp.exe process from the kudu dashboard and restart the web app. So far so good.

Here are some charts showing a high app service load despite none of our sites consuming any resources.

Process Tab after turning off Web App
![image](https://cloud.githubusercontent.com/assets/2462038/23727898/db120756-040e-11e7-8c07-e5064b52b915.png)

Web App Turned Off
![image](https://cloud.githubusercontent.com/assets/2462038/23727729/07c635b6-040e-11e7-9c98-e7bbe64572a8.png)

Sites on the App Service
![image](https://cloud.githubusercontent.com/assets/2462038/23727759/366e75e0-040e-11e7-9e4e-1bb23e34a7b9.png)

App Service Load not dipping
![image](https://cloud.githubusercontent.com/assets/2462038/23727794/5ffe4f7a-040e-11e7-9d86-b0a6397c529d.png)

Extra Web Job Information:
Continuous Jobs, Web Job functions triggered through azure storage queue messages.
Deployed through Visual Studio, written in .NET using the Web Jobs SDK.

**Comment by davidebbo** [comment]
I think your theory about the WebJobs dashboard is probably correct. It does indexing, and this can be heavy if it hasn't happened in a while and there is lots of data.

If that's indeed the root of the problem, note that it is not part of Kudu,but is instead part of the WebJobs SDK: https://github.com/Azure/azure-webjobs-sdk. If so, we should close here and track there.

**Comment by Bio2hazard** [comment]
Please advise on how we should proceed or if we can find out what was causing it.

One more symptom that I neglected to mention is that the local read bytes was through the roof.

Here is a last 24-hour chart showing a staggering 81 gb local read bytes on the Web Job.
![image](https://cloud.githubusercontent.com/assets/2462038/23728744/524f7926-0413-11e7-8b68-971f8c467499.png)

**Comment by davidebbo** [comment]
If the strong suspicion is that it relates to WebJobs dashboard, we really need to get the issue over there. That does seem like an enormous amount of local read data. Which UI exactly did you get this graph from?

**Comment by Bio2hazard** [comment]
Should I copy the text of the issue and post it there?

I pulled the chart from the Azure Portal. When looking at the Web App, there is a Dashboard called "Metrics per Instance (App Service plan)". The last chart in the list is the Networks Statistics chart I pasted.

**Comment by davidebbo** [comment]
I don't understand why it would be reading so much from the file system. I would think it would just be reads/writes to storage. Anyway, let's get it over there. You can copy the relevant data from here to there.

**Comment by Infraton11** [comment]
under control

**Comment by arunp-motorq** [comment]
We seem to have the same issue. @Bio2hazard How did you fix this ?
