### ISSUE TITLE
bitbucket-pipelines azure deployment Kudu Services InvalidOperationException

### ISSUE THREAD

**Issue by chandandattahlk** [projectkudu/kudu#2353]
Hi

I have reported an issue on the atlassian support [site](https://answers.atlassian.com/questions/61587055/bitbucket-pipelines-azure-deployment-kudu-services-invalidoperationexception). Not sure if anyone from Kudu project team can  provide any insights to solving this issue

**Comment by nickwalkmsft** [comment]
@chandandattahlk From a quick look, my best guess is that you have a '/' in your password, or some other unescaped character that's causing the URL to be unparseable. Your script might need some character escaping logic in it.

**Comment by nickwalkmsft** [comment]
The exception traces you pasted actually have "$BITBUCKET_PASSWORD" in the URL; I'm assuming that there's a replacement there that actually happens, and you are just using it in the pasted output to mask out your real password?

**Comment by chandandattahlk** [comment]
Thanks. It's a strong password so it does. I will modify and check update the environment variable (https://confluence.atlassian.com/bitbucket/environment-variables-794502608.html) There's no example on the Atlassian site for escaping so I get the error when I escape the # by \#

[<b> Exception Details: </b>Newtonsoft.Json.JsonReaderException: Bad JSON escape sequence: \#. Path 'url', line 1, position 53.<br><br>](url)

The $BITBUCKET_PASSWORD in the azure script is generated by the bitbucket pipeline plugin codegen.

**Comment by nickwalkmsft** [comment]
Deployment from a private repo requires SSH; continuing conversation on https://github.com/projectkudu/kudu/issues/2353
