### ISSUE TITLE
bitbucket-pipelines azure deployment could not read Password for git submodules

### ISSUE THREAD

**Issue by chandandattahlk** [projectkudu/kudu#2355]
Hi 
I am using [azure VScode plugin ](https://azure.microsoft.com/en-us/blog/continuous-integration-delivery-of-web-apps-from-atlassian-bitbucket/)to deploy to azure, but get these exceptions on my bitbucket-pipelines console when my bitbucket repo has submodules. Any wiki article or steps I need to follow to fix this?

Bitbucket yml:
```
pipelines:
default:
- step:
script: # Modify the commands below to build and test your repository.
- chmod +x ./deploy-to-azure.bash
- ./deploy-to-azure.bash
```

deploy-to-azure.bash:

```
# Trigger a manual (fetch) Kudu deployemnt:
curl -X POST "https://\$$SITE_NAME:$FTP_PASSWORD@$SITE_NAME.scm.azurewebsites.net/deploy" \
--header "Content-Type: application/json" \
--header "Accept: application/json" \
--header "X-SITE-DEPLOYMENT-ID: $SITE_NAME" \
--header "Transfer-encoding: chunked" \
--data "{\"format\":\"basic\", \"url\":\"https://$BITBUCKET_USERNAME:$BITBUCKET_PASSWORD@bitbucket.org/$BITBUCKET_USERNAME/$REPOSITORY_NAME.git\"}"
echo Finished uploading files to site $SITE_NAME.
```

Stack trace:

```
<table width=100% bgcolor="#ffffcc">
   <tr>
      <td>
          <code>
An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.</code>
      </td>
   </tr>
</table>

            

[CommandLineException: Cloning into &#39;cda-hgf-lookup&#39;...
bash: /dev/tty: No such device or address
error: failed to execute prompt script (exit code 1)
fatal: could not read Password for &#39;https://hlk@bitbucket.org&#39;: Invalid argument
fatal: clone of &#39;https://hlk@bitbucket.org/hlk/cda-hgf-lookup.git&#39; into submodule path &#39;cda-hgf-lookup&#39; failed
D:\Program Files (x86)\Git\cmd\git.exe submodule update --init --recursive --force]
   Kudu.Core.Infrastructure.Executable.Execute(ITracer tracer, String arguments, Object[] args) +444077
   Kudu.Core.SourceControl.Git.GitExeRepository.&lt;UpdateSubmodules&gt;b__34_0() +54
   Kudu.Core.Infrastructure.OperationManager.Attempt(Func`1 action, Int32 retries, Int32 delayBeforeRetry, Func`2 shouldRetry) +80
   Kudu.Core.SourceControl.Git.GitExeRepository.ExecuteGenericGitCommandWithRetryAndCatchingWellKnownGitErrors(Func`1 func) +136
   Kudu.Core.SourceControl.Git.GitExeRepository.UpdateSubmodules() +135
   Kudu.Core.SourceControl.Git.LibGit2SharpRepository.UpdateSubmodules() +14
   Kudu.Core.Deployment.&lt;DeployAsync&gt;d__24.MoveNext() +1056
```

**Comment by nickwalkmsft** [comment]
Apologies @chandandattahlk, an important detail slipped my mind when discussing on the previous issue - we do not support private repo deployment via username/password. Please follow the instructions [here](https://github.com/projectkudu/kudu/wiki/Continuous-deployment#for-private-repos-set-up-a-deploy-key), and in your script, supply the SSH url for your repo instead of the HTTPS url.

**Comment by chandandattahlk** [comment]
Thanks. yep, it's a private repo. Is it sufficient to have SSH url for the parent bitbucket repo only? The reported stacktrace showed the build agent could not find the submodule's credentials

**Comment by nickwalkmsft** [comment]
Can you give [this](http://blogs.suwatbodin.com/2013/07/deploy-to-windows-azure-using-git-with.html) a look and see if it's helpful?.

**Comment by nickwalkmsft** [comment]
There's also a breakdown [here](https://github.com/projectkudu/kudu/issues/881).

**Comment by chandandattahlk** [comment]
I read the [blog ](http://blogs.suwatbodin.com/2013/07/deploy-to-windows-azure-using-git-with.html)saying 

> Note that you have to make sure all submodules are fetched using SSH (not https) by looking at .gitmodules file (see url property). This works well with Bitbucket but fails in GitHub.

I am using bitbucket private repos. Now I have added the gitmodules file with ssh url, but get the error  below. so do i need to setup ssh keys as well?

`url = git@bitbucket.org:hlk/hlk-cda-converter.git`

error on azure activity log:

`Cloning into 'cda-hgf-lookup'...\nrepository access denied. deployment key is not associated with the requested repository.\nfatal: Could not read from remote repository.\n\nPlease make sure you have the correct access rights\nand the repository exists.\nfatal: clone of 'git@bitbucket.org:hlk/cda-hgf-lookup.git' into submodule path 'cda-hgf-lookup' failed\n\r\nD:\Program Files (x86)\Git\cmd\git.exe submodule update --init --recursive --force`

**Comment by nickwalkmsft** [comment]
Yes, I believe you just need to add the site's SSH key (the one you get from /api/sshkey) as a deployment key for those submodule repos.

**Comment by chandandattahlk** [comment]
The ssh keys have sorted, but I get a new error (full stacktrace here: http://pastebin.com/91z6EEZd)

```
 Unable to resolve 'Hlk.Cda.Converter (>= 0.0.1)' for '.NETFramework,Version=v4.6.1'.
NuGet Config files used:
    Unable to resolve 'Hlk.GenericForm (>= 2.1.0)' for '.NETFramework,Version=v4.6.1'.


Failed exitCode=1, command=nuget.exe restore -packagesavemode nuspec "src\Hlk.Cda.WebApi\Hlk.Cda.WebApi.xproj"
An error has occurred during web site deployment.
Errors in D:\home\site\repository\src\Hlk.Cda.WebApi\Hlk.Cda.WebApi.xproj\r\n    Unable to resolve 'Hlk.Cda.Converter (>= 0.0.1)' for '.NETFramework,Version=v4.6.1'.\r\n    Unable to resolve 'Hlk.GenericForm (>= 2.1.0)' for '.NETFramework,Version=v4.6.1'.\r\nD:\Program Files (x86)\SiteExtensions\Kudu\59.60207.2684\bin\Scripts\starter.cmd "D:\home\site\deployments\tools\deploy.cmd"
```

**Comment by chandandattahlk** [comment]
From the errors, I am a bit confused on how to do the builds. I am using the old project.json structure and I have the two libraries as deps(Hlk.Cda.Converter and Hlk.GenericForm) for this project I am building. When the build agent starts, it looks for these two libraries which I think haven't been built yet in the global nuget registry. Is this what is causing the errors? If so, how to fix it?

**Comment by nickwalkmsft** [comment]
/cc @davidebbo, as I have less familiarity with nuget issues.

There's likely a solution that doesn't involve upgrading, but I strongly recommend moving to the [full release](https://blogs.msdn.microsoft.com/dotnet/2017/03/07/announcing-net-core-tools-1-0/) of the tools and moving to .csproj. The older tools and the .xproj/project.json formats will eventually no longer be supported on App Service.

**Comment by davidebbo** [comment]
That latest error looks completely unrelated to the bitbucket ssh issue discussed in this thread. Generally, we avoid discussing multiple unrelated things in one issue, so closing this one. Please open a separate issue to focus on the build part. If possible, share a [minimal repro repository](https://github.com/projectkudu/kudu/wiki/Using-a-git-repo-to-report-an-issue).
