### ISSUE TITLE
Issue with Remote 'origin' already exists.

### ISSUE THREAD

**Issue by suwatch** [projectkudu/kudu#2360]
User on [forum](https://social.msdn.microsoft.com/Forums/azure/en-US/a9b8c9cb-70ed-426d-8a47-41631401935f/azure-continuous-deployment-issue-git-remote-origin-already-exists?forum=windowsazurewebsitespreview&prof=required) reported that this issue.   Talking to @ahmelsayed, it seemed to happen to others as well.   It happened on and off.   [Our call](https://github.com/projectkudu/kudu/blob/20967437cfc2c42ffd8b0fe6b77b062fcae1bc3b/Kudu.Core/SourceControl/Git/LibGit2SharpRepository.cs#L220-L223) did remove before adding.   It was unlikely race condition in our codes given deployment lock.    Looking at [LibGit2Sharp](https://github.com/libgit2/libgit2sharp/blob/master/LibGit2Sharp/Core/Proxy.cs#L2167-L2177) did not reveal much clue.  

I suggest to fix by checking if the remote exists and has the same refspec.    If so, no need to remove and add remote (avoiding this code path in the first place).   This should be the main scenario.

```csharp
Remote 'origin' already exists.
   at LibGit2Sharp.Core.Ensure.HandleError(Int32 result)
   at LibGit2Sharp.Core.Proxy.git_remote_create_with_fetchspec(RepositorySafeHandle repo, String name, String url, String refspec)
   at LibGit2Sharp.RemoteCollection.Add(String name, String url, String fetchRefSpec)
   at Kudu.Core.SourceControl.Git.LibGit2SharpRepository.FetchWithoutConflict(String remoteUrl, String branchName)
   at Kudu.Services.ServiceHookHandlers.ServiceHookHandlerBase.Fetch(IRepository repository, DeploymentInfo deploymentInfo, String targetBranch, ILogger logger, ITracer tracer)
   at Kudu.Services.FetchHandler.<PerformDeployment>d__12.MoveNext()
```

**Comment by suwatch** [comment]
Per [this report](https://social.msdn.microsoft.com/Forums/en-US/a9b8c9cb-70ed-426d-8a47-41631401935f/azure-continuous-deployment-issue-git-remote-origin-already-exists?forum=windowsazurewebsitespreview&prof=required).

**Comment by suwatch** [comment]
I opened an issue on [LibGit2Sharp](https://github.com/libgit2/libgit2sharp/issues/1437) for tracking.   We will wait and see what the reply is.

**Comment by skapatech** [comment]
@suwatch - I'm having the same issue and able to consistently reproduce this.  Is there any thing I can send to you to help track down and resolve this issue?

Thanks!

**Comment by davidebbo** [comment]
@skapatech looks like libgit2sharp issue is still active. Can you try setting a `SCM_USE_LIBGIT2SHARP_REPOSITORY=0` app setting and check if that takes care of it?

**Comment by skapatech** [comment]
@davidebbo - thanks!  that seems to have fixed it.  Best, Ryan

**Comment by kemmis** [comment]
I'm still seeing this issue as of 8/16/2017. Using the app setting that @davidebbo mentioned DOES solve the problem for me.

**Comment by davidebbo** [comment]
The linked libgit2sharp issue did not get traction unfortunately.

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
