### ISSUE TITLE
Configuring WebHooks via Azure Resource Manager template?

### ISSUE THREAD

**Issue by glenjamin** [projectkudu/kudu#2365]
Is there any way to configure https://github.com/projectkudu/kudu/wiki/Web-hooks via the resource manager APIs?

I had a search around and couldn't find anything - I'm also not sure if this is the right place to ask this question, so feel free to direct me elsewhere

Cheers!

**Comment by davidebbo** [comment]
Unfortunately no, that API is not exposed via ARM.

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
