### ISSUE TITLE
Missing file notification causing the job to report wrong state

### ISSUE THREAD

**Issue by suwatch** [projectkudu/kudu#2369]
We used file notification to detect disable and enable webjob (disable.job).   Missing the notification (especially in case of multiple instances and azure file) caused it to report the wrong status.

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
