### ISSUE TITLE
Any way to run webjobs in the same sandbox as the website?

### ISSUE THREAD

**Issue by dennis-yemelyanov** [projectkudu/kudu#2370]
I would like to be able to create a webjob that hosts a socket listener so the parent app website can connect to it. However that doesn't seem to work, because webjobs seem to be hosted in a different sandbox than websites (different process tree).

Is there any better solution for this than starting an exe process manually from website code? Or maybe some other workarounds, such as creating a VNet?

**Comment by davidebbo** [comment]
Try setting `WEBSITE_DISABLE_SCM_SEPARATION=true`, per [wiki](https://github.com/projectkudu/kudu/wiki/Configurable-settings#use-the-same-process-for-the-user-site-and-the-scm-site).

**Comment by dennis-yemelyanov** [comment]
Thanks, David, seems like WEBSITE_DISABLE_SCM_SEPARATION should work, although the legacy part is a little discouraging... If WebJobs are first class citizens in the App Service ecosystem, I think there should be a fully supported way for the website to communicate with them. Or is the webjob functionality not really intended for any complex tasks (for which I guess the recommendation is to use Azure Service Fabric)?

**Comment by davidebbo** [comment]
WebJobs are fully supported, but the scenario of needing to have the parent app talk to it via socket is not something it was designed for (and it has not come up before afaik). I don't think this directly relate to the inability to do complex tasks. It's just one specific usage pattern that is not supported.

That being said, you might have good luck with WEBSITE_DISABLE_SCM_SEPARATION.

**Comment by dennis-yemelyanov** [comment]
Sure, I will give that setting a try and test if any issues come up. Basically the idea was to host a local microservice inside the same app service, which website and other webjobs can talk to. This is similar to what Azure Service Fabric does, but I really like the simplicity of initial setup, deployment and management of the App Service. Having all this built-in functionality such as deployment slots and A/B testing is really great. And if there was a way to easily host a small service on localhost, it would be ideal. Maybe there is still a way that I didn't consider?
Anyway, thank you for your comments, I'm sure I'll be able to either use WEBSITE_DISABLE_SCM_SEPARATION or reference the required functionality from the website code directly instead of calling the local service.
