### ISSUE TITLE
deploy.cmd fails locally ever since installing VS2017

### ISSUE THREAD

**Issue by xt0rted** [projectkudu/kudu#2373]
I have a number of sites that use a pretty standard `deploy.cmd` (the build & deploy steps are the same as the generated script). Prior to installing VS2017 I was able to run these locally and get the correct `wwwroot` output. Since installing VS2017 I now receive an error when running locally while on azure they continue to run correctly. I have both VS2015 and VS2017 installed at the moment.

### The log/error given by the failure.
```
1. Ensure nuget packages are installed
MSBuild auto-detection: using msbuild version '14.0' from 'C:\Program Files (x86)\MSBuild\14.0\bin'.
All packages listed in packages.config are already installed.

2. Build to the temporary path
C:\dev\equineexchange\website\src\Website\Website.csproj(443,3): error MSB4019: The imported project "C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v15.0\WebApplications\Microsoft.WebApplication.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
Failed exitCode=1, command="C:\Program Files (x86)\MSBuild\14.0\Bin\MSBuild.exe" "C:\dev\equineexchange\website\.\src\Website\Website.csproj" /nologo /verbosity:m /t:Build /t:pipelinePreDeployCopyAllFilesToOneFolder /p:_PackageTempDir="C:\Users\brian\AppData\Local\Temp\___deployTemp6161\temp";AutoParameterizationWebConfigConnectionStrings=false;Configuration=Release;UseSharedCompilation=false;TypeScriptCompileBlocked=true /p:SolutionDir="C:\dev\equineexchange\website\.\.\\"
An error has occurred during web site deployment.
```

### Relevant part of my deploy.cmd
```batch
@if "%SCM_TRACE_LEVEL%" NEQ "4" @echo off

:: ----------------------
:: KUDU Deployment Script
:: Version: 1.0.6
:: ----------------------

:: Prerequisites
:: -------------

:: Verify node.js installed
where node 2>nul >nul
IF %ERRORLEVEL% NEQ 0 (
  echo Missing node.js executable, please install node.js, if already installed make sure it can be reached from current environment.
  goto error
)

:: Setup
:: -----

setlocal enabledelayedexpansion

SET ARTIFACTS=%~dp0%\artifacts

IF NOT DEFINED DEPLOYMENT_SOURCE (
  SET DEPLOYMENT_SOURCE=%~dp0%.
)

IF NOT DEFINED DEPLOYMENT_TARGET (
  SET DEPLOYMENT_TARGET=%ARTIFACTS%\wwwroot
)

IF NOT DEFINED NEXT_MANIFEST_PATH (
  SET NEXT_MANIFEST_PATH=%ARTIFACTS%\manifest

  IF NOT DEFINED PREVIOUS_MANIFEST_PATH (
    SET PREVIOUS_MANIFEST_PATH=%ARTIFACTS%\manifest
  )
)

IF NOT DEFINED KUDU_SYNC_CMD (
  :: Install kudu sync
  echo Installing Kudu Sync
  call npm install kudusync -g --silent
  IF !ERRORLEVEL! NEQ 0 goto error

  :: Locally just running "kuduSync" would also work
  SET KUDU_SYNC_CMD=%appdata%\npm\kuduSync.cmd
)

IF NOT DEFINED DEPLOYMENT_TEMP (
  SET DEPLOYMENT_TEMP=%temp%\___deployTemp%random%
  SET CLEAN_LOCAL_DEPLOYMENT_TEMP=true
)

IF DEFINED CLEAN_LOCAL_DEPLOYMENT_TEMP (
  IF EXIST "%DEPLOYMENT_TEMP%" rd /s /q "%DEPLOYMENT_TEMP%"
  mkdir "%DEPLOYMENT_TEMP%"
)

IF DEFINED MSBUILD_PATH goto MsbuildPathDefined
SET MSBUILD_PATH=%ProgramFiles(x86)%\MSBuild\14.0\Bin\MSBuild.exe
:MsbuildPathDefined

::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
:: Deployment
:: ----------

echo Handling .NET Web Application deployment.

echo 1. Ensure nuget packages are installed
call :ExecuteCmd nuget restore "%DEPLOYMENT_SOURCE%\Website.sln"
IF !ERRORLEVEL! NEQ 0 goto error


echo 2. Build to the temporary path
IF /I "%IN_PLACE_DEPLOYMENT%" NEQ "1" (
  call :ExecuteCmd "%MSBUILD_PATH%" "%DEPLOYMENT_SOURCE%\src\Website\Website.csproj" /nologo /verbosity:m /t:Build /t:pipelinePreDeployCopyAllFilesToOneFolder /p:_PackageTempDir="%BUILD_TEMP%";AutoParameterizationWebConfigConnectionStrings=false;Configuration=Release;UseSharedCompilation=false;TypeScriptCompileBlocked=true /p:SolutionDir="%DEPLOYMENT_SOURCE%\.\\" %SCM_BUILD_ARGS%
) ELSE (
  call :ExecuteCmd "%MSBUILD_PATH%" "%DEPLOYMENT_SOURCE%\src\Website\Website.csproj" /nologo /verbosity:m /t:Build /p:AutoParameterizationWebConfigConnectionStrings=false;Configuration=Release;UseSharedCompilation=false;TypeScriptCompileBlocked=true /p:SolutionDir="%DEPLOYMENT_SOURCE%\.\\" %SCM_BUILD_ARGS%
)
IF !ERRORLEVEL! NEQ 0 goto error
```
Looking on my machine & azure shows there's no `C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v15.0` folder. Locally I have `C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\VisualStudio\v15.0` but that seems tied to my version of VS and not meant for use from the command line. Not to mention it doesn't exist on azure.

What I don't get is why my script is trying to load stuff from the v15 folder when I'm using MSBuild 14 and nothing has been changed in the script or my projects. All I did was install VS2017.

**Comment by davidebbo** [comment]
@watashiSHUN that sounds like the nuget registry magic you were talking about?

**Comment by watashiSHUN** [comment]
my trick only works if you are using **msbuild15**, but based on the error message, it looks like **msbuild14**  is ran instead.

I created a dummy MVC project for testing purpose and I believe the problem comes from the `$(VisualStudioVersion)` in [these lines](https://github.com/watashiSHUN/dummyMVCapp/blob/master/dummyMVCapp/dummyMVCapp.csproj#L286-L287). I too have **VS2017 and VS2015** installed on my work station, but running msbuild14 from the command line does not give me error.

you can read [this link](http://sedodream.com/PermaLink,guid,a5894bad-f2a1-441a-a5b2-74f16c6cf8aa.aspx), it talks about how `$(VisualStudioVersion)` is determined. The recommendation is that you either pass the `.sln` instead of `.csproj` as argument or specify the exact VS version on the command line: `msbuild.exe ConfusedProject.csproj /p:VisualStudioVersion=14.0`

you can also read the [stackoverflow answer](http://stackoverflow.com/questions/3980909/microsoft-webapplication-targets-was-not-found-on-the-build-server-whats-your), some simply solution like copy the missing file...

I didn't reproduce the issue successfully, maybe you can provide more information about your build environment?

**Comment by xt0rted** [comment]
I was using [OpenCommandLine](https://marketplace.visualstudio.com/items?itemName=MadsKristensen.OpenCommandLine) when running my `deploy.cmd` scripts as well as when directly running `"%ProgramFiles(x86)%\MSBuild\14.0\Bin\MSBuild.exe" WebApplication.csproj`. Using a command prompt opened with that results in the missing targets error sometimes (always if opened from VS2017), while double clicking the script or win+r cmd always works. I guess there's some magic going on with those command prompts that I was unaware of.

Adding `/p:VisualStudioVersion=14.0` to the scripts gets around this issue no matter how I run them.
