### ISSUE TITLE
bitbucket-pipelines azure deployment with git submodules for private repos

### ISSUE THREAD

**Issue by chandandattahlk** [projectkudu/kudu#2375]
I am using bitbucket private repos as gitmodules with .net core tooling for deploying a web api.   
I am using the  project.json structure (yes, I am planning to migrate this test repo to csproj .net core tooling) and I have the two libraries as deps(Hlk.Cda.Converter and Hlk.GenericForm) for this project I am building. 

When the build agent starts, it looks for these two libraries which I think haven't been built yet in the global nuget registry. Is this what is causing the errors? If so, how to fix it?

### my project.json

```
{
  "dependencies": {
    "Hlk.Cda.Converter": "0.0.1",
    "Hlk.GenericForm": "2.1.0",
    "Microsoft.AspNetCore.Mvc": "1.0.1",
    "Microsoft.AspNetCore.Mvc.Formatters.Xml": "1.1.1",
    "Microsoft.AspNetCore.Routing": "1.1.0",
    "Microsoft.AspNetCore.Server.IISIntegration": "1.0.0",
    "Microsoft.AspNetCore.Server.Kestrel": "1.0.1",
    "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.0.0",
    "Microsoft.Extensions.Configuration.FileExtensions": "1.0.0",
    "Microsoft.Extensions.Configuration.Json": "1.0.0",
    "Microsoft.Extensions.Logging": "1.1.0",
    "Microsoft.Extensions.Logging.Console": "1.1.0",
    "Microsoft.Extensions.Logging.Debug": "1.1.0",
    "Microsoft.Extensions.Options.ConfigurationExtensions": "1.0.0"
  },

  "tools": {
    "Microsoft.AspNetCore.Server.IISIntegration.Tools": "1.0.0-preview2-final"
  },

  "frameworks": {
    "net461": { }
  },

  "buildOptions": {
    "emitEntryPoint": true,
    "preserveCompilationContext": true
  },

  "publishOptions": {
    "include": [
      "wwwroot",
      "**/*.cshtml",
      "appsettings.json",
      "web.config"
    ]
  },

  "scripts": {
    "postpublish": [ "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%" ]
  }
}
```

### my gitmodules file

```
[submodule "hlk-cda-converter"]
	path = hlk-cda-converter
	url = git@bitbucket.org:hlk/hlk-cda-converter.git
[submodule "cda-hgf-lookup"]
	path = cda-hgf-lookup
	url = git@bitbucket.org:hlk/cda-hgf-lookup.git

```

### error on azure activity log:

full stacktrace here: http://pastebin.com/91z6EEZd

```
Unable to resolve 'Hlk.Cda.Converter (>= 0.0.1)' for '.NETFramework,Version=v4.6.1'.
NuGet Config files used:
    Unable to resolve 'Hlk.GenericForm (>= 2.1.0)' for '.NETFramework,Version=v4.6.1'.


Failed exitCode=1, command=nuget.exe restore -packagesavemode nuspec "src\Hlk.Cda.WebApi\Hlk.Cda.WebApi.xproj"
An error has occurred during web site deployment.
Errors in D:\home\site\repository\src\Hlk.Cda.WebApi\Hlk.Cda.WebApi.xproj\r\n    Unable to resolve 'Hlk.Cda.Converter (>= 0.0.1)' for '.NETFramework,Version=v4.6.1'.\r\n    Unable to resolve 'Hlk.GenericForm (>= 2.1.0)' for '.NETFramework,Version=v4.6.1'.\r\nD:\Program Files (x86)\SiteExtensions\Kudu\59.60207.2684\bin\Scripts\starter.cmd "D:\home\site\deployments\tools\deploy.cmd"
```

**Comment by davidebbo** [comment]
Not sure I quite follow. It looks like it's NuGet that's failing to restore the package Hlk.Cda.Converter, and that package is indeed not on nuget.org. How do you expect your git submodules to come into the picture here? Does the same build outside of Azure?

**Comment by chandandattahlk** [comment]
I want to make the dependent packages (hlk-cda-converter and cda-hgf-lookup) as git submodules. They are both private libraries, so are not on nuget registry. What's the approach for this kind of builds?

**Comment by davidebbo** [comment]
I still don't understand how this is Kudu specific. Does the same repo build outside of Kudu/Azure?

**Comment by chandandattahlk** [comment]
In the local build configuration, the nuget package manager can find it because of the private repo it can refer to in the global nuget config file. Attached. So I believe this is a kudu issue on how to build with private repos using bitbucket pipelines on azure. It builds fine on the local network. I don't want to manually change the nuget.config on a build server.

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
    <add key="ci-nexus" value="http://ci-nexus/repository/nuget-hosted/" />
  </packageSources>
</configuration>

```

**Comment by davidebbo** [comment]
So http://ci-nexus/repository/nuget-hosted/ is the NuGet repository that has those packages? How could NuGet running on Kudu possibly access this since it's on some intranet and not internet? I would expect the same behavior if you build the same project anywhere outside of your local network.

**Comment by chandandattahlk** [comment]
That was to answer your question on how the build system works fine on a local network.   I am trying to find out how we can get the src with those deps built on azure with a different mechanismbecause of course kudu doesn't have access to the local network. To try out, I have the build source of the package as a gitmodule and I have raised the question here whether it is a correct way to do it or is there any other way

**Comment by davidebbo** [comment]
I'd like to stick to Kudu specific topics here. And it sounds like you're asking a more general question about what build pattern to use when building your project outside of your local network. i.e. unless I'm mistaken, you would have the exact same question if you built it on some random VM on the internet. Correct?

**Comment by chandandattahlk** [comment]
I am paying Azure and I want to do it with bitbucket which I am also paying for, so why is it not a problem for kudu who are solving it for Azure. The general mechanism might be beneficial to all similar deployments for other providers and I will leave it to their testers to verify and solve. The problem statement is very clear on the title of this thread and I don't see a point trying to diverge off-topic.

**Comment by davidebbo** [comment]
When it comes to bitbucket, the answer is that working with private submodules can be done, but does add some extra steps. [This post](http://blogs.suwatbodin.com/2013/07/deploy-to-windows-azure-using-git-with.html) is the reference on how to make it work.

**Comment by chandandattahlk** [comment]
I would suggest the blog might be old or outdated because this statement is not correct 

> Note that you have to make sure all submodules are fetched using SSH (not https) by looking at .gitmodules file (see url property).  This works well with Bitbucket

I have followed the exact same mechanism and  have the .gitmodules files according to the blog post. It is able to ssh into the repos and fetch it but the build fails. The blog suggests that as soon as the ssh access works, the build should be fine, but it is not as per the error stacktrace from Azure.

**Comment by davidebbo** [comment]
As far as I know the post is still current. Are you saying that you got an error when Kudu tries to fetch the submodule? The error you show above relates to nuget, so it's unrelated to submodules.

**Comment by chandandattahlk** [comment]
I can't test this on the remote azure web service deployment because it's something Microsoft has control over. So even if it is a nuget issue there's no way I can replicate on my local network. Since kudu does the builds on azure, kudu team has the best shot at testing it out with XYZ version of nuget that is required and let me know the right mechanism. I have reported it to nuget (https://github.com/NuGet/Home/issues/4870) as well, but I doubt that they can exactly replicate it. From the last post by a msft team member(https://github.com/NuGet/Home/issues/4124), it seems that the VS 2017 release has the same mechanism that I am trying with project.json, but I couldn't see a tested solution or mechanism that can let me know. I believe the teams need to coordinate to propose the exact solution and put up an official Azure kb article so that many more interested developers can use the solution. I can see one here(https://azure.microsoft.com/en-us/blog/continuous-integration-delivery-of-web-apps-from-atlassian-bitbucket/) but not an article for a complete pipeline.

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
