### ISSUE TITLE
Deployed Kudu locally : can't start extensions and can't browse WebJobs

### ISSUE THREAD

**Issue by tbprince** [projectkudu/kudu#2378]
Hello,

we just attempted to deploy Kudu on a local machine and it mostly works fine. We are still checking the deployment to understand what works and what doesn't, however we found out that no extensions work and WebJobs console is not working too ("No route registered for '/azurejobs/'").

Extensions fail for the same reason

"No route registered for '/filecounter/'"
"No route registered for '/statuspage/'"

It seems that applicationhost.xdt transformations are not applied to the kudu_service_* IIS application.

What are we missing ?

thanks!

**Comment by davidebbo** [comment]
Indeed, site extensions only work on Azure App Service, and there is no easy way to use them on local IIS.

As for the WebJobs dashboard, it's actually not part of Kudu, but is instead part of the WebJobs SDK: https://github.com/Azure/azure-webjobs-sdk. So you should be able to run that.

**Comment by tbprince** [comment]
Thank you for clarifying that, @davidebbo.

Is it normal that we cannot access the git URL that Kudu is reporting for the new application ?

For example we get:

"No route registered for '/newapplication.git'"

when trying to access the URL that Kudu reports for "newapplication". Website and Kudu itself seem to be working fine.

Thanks.

**Comment by nickwalkmsft** [comment]
> "No route registered for '/newapplication.git'"

This is expected behavior. That URL is intended for use with a git client, which uses it as the base URL for the git protocol. See here if you're curious: https://git-scm.com/book/en/v2/Git-Internals-Transfer-Protocols#_http_s

**Comment by davidebbo** [comment]
Indeed, just 'git push' to it and it should work.

**Comment by tbprince** [comment]
@nickwalkmsft, @davidebbo 

yep, thanks. It is working fine. I thought I could access the URL without Git too having some kind of response instead of a generic error. I tried to push something and it is working fine. Thank you.
