### ISSUE TITLE
Better key handling in terminal

### ISSUE THREAD

**Issue by SteveALee** [projectkudu/kudu#2379]
The terminal (as presented within the Azure Functions panels) is pretty good given it's in a web page. While I'm not expecting full VT200 emulation some of the key handling is a constant source of annoyance. 

Would be it be possible to at least add

* Right arrow moving cursor - not printing a character
* Tab key auto completion (you capture the Tab key anyway)

Thanks

**Comment by davidebbo** [comment]
It sounds like you are referring to the Console in the Azure Portal, which is not part of Kudu. That one is indeed more limited. Can you try using the one in Kudu instead? It supports the two things you list.

**Comment by SteveALee** [comment]
@davidebbo  thanks my reason was @christopheranderson  said it WAS kudo!!! :)

**Comment by SteveALee** [comment]
yes, happy to use kudo one as only an extra click or 2.

**Comment by davidebbo** [comment]
Here is the deal; the Console in the portal uses Portal UI and keyboard logic, but does use a Kudu API on the backend. While the one in Kudu itself is all Kudu, and is a more 'real' command line (though still a far cry from a full ssh shell with terminal emulation).

**Comment by SteveALee** [comment]
OK. So defo sounds like a portal issue for the features I want :)
AFAiK portal is not open source so I can't do any more than nag Chris :)
