### ISSUE TITLE
Sometimes cannot get response from /api/commandstream

### ISSUE THREAD

**Issue by breezewish** [projectkudu/kudu#2385]
I'm using C# signalR client to connect Kudu commandstream interface and sometimes it cannot receive CMD response completely (like `Microsoft Windows [....]`). I opened log trace in SignalR client and verbose log in Kudu. SignalR client cannot receive anything after connected. However Kudu logs said CMD process is created.

I guess it might be related to this but I'm not sure:

https://github.com/projectkudu/kudu/blob/2ea953e532d0a44afe291dc4b9e370df9fc51686/Kudu.Services/Commands/PersistentCommandController.cs#L47

In the code above, a process might be created before a connected event is emitted.

**Comment by breeswish** [comment]
Here is the response body from Fiddler for "/api/commandstream/connect?transport=serverSentEvents&clientProtocol=1.4&.....":

```
HTTP/1.1 200 OK
Cache-Control: no-cache
Pragma: no-cache
Transfer-Encoding: chunked
Content-Type: text/event-stream
Expires: -1
Server: Microsoft-IIS/8.0
X-Content-Type-Options: nosniff
X-AspNet-Version: 4.0.30319
X-Powered-By: ASP.NET
Set-Cookie: ARRAffinity=xxxxxxxx;Path=/;Domain=xxxxxxx.scm.chinacloudsites.cn
Date: Mon, 27 Mar 2017 05:17:48 GMT

13
data: initialized


33
data: {"C":"d-A6CB852A-A,0|T,1|U,0","S":1,"M":[]}


a
data: {}


a
data: {}


a
data: {}


a
data: {}


a
data: {}


a
data: {}


a
data: {}


a
data: {}


a
data: {}


a
data: {}


a
data: {}


a
data: {}


a
data: {}


a
data: {}


a
data: {}


a
data: {}


a
data: {}


a
data: {}


a
data: {}


a
data: {}


a
data: {}


a
data: {}


a
data: {}
```

**Comment by davidebbo** [comment]
Do you see those issues only with your own client, or also when using Kudu console?

**Comment by breeswish** [comment]
Only with my own client, with a chance to fail. However according to Fiddler, CMD banners are not sending back indeed. So the issue should either be in client's request (which is made by SignalR.Client) or in server's (might be related to race condition which rarely trigger by Js client but might trigger by C# client because of .. different speed I guess?)

**Comment by ahmelsayed** [comment]
can you try enabling websockets for your app and see if the same kind of issue persists? It seems that you're using.


I'm an an expert on signalr, but I'd think that if it's because the process is created before the connection is connected, then sending an `\n` should give you back a new prompt.

**Comment by breeswish** [comment]
Hi. I've enabled WebSocket in Azure and I could see that the C# SignalR connected to Kudu using WSS. However the issue still exists. You can also directly take a look at my client code, which is very simple: https://github.com/breeswish/KuduCommandSignalR/blob/master/Program.cs

**Comment by ahmelsayed** [comment]
so when you say sometimes, how frequent is that? i tried running the code 10 times or so, and it worked every time for me.

**Comment by breeswish** [comment]
That's strange. On my colleagues's PC only 20% of the attempts would success and the success rate varies from time to time.... We are connecting to Azure service running in China from a foreign network. The Kudu version is 61.60316.2745.0. Could I send our publish file to you via email so that you can play with it?

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
