### ISSUE TITLE
Kudu can't match branches

### ISSUE THREAD

**Issue by floneo** [projectkudu/kudu#2387]
Hey there!

Kudu seems unable to match branches with just patterns instead of names. Gitflow for example uses `master` for the current production system and `release/a.b.c` as the changing branch name for qs stuff. I tried to configure a pattern for such release branches, but I got neither an error nor a checkout of the current release branch.

### Repro steps.
* Create a git flow enabled git repository
* Create two azure web apps
* Set the deploy keys for both apps
* Configure the first one to use master
* Configure the second one to use a release branch

The `settings.xml` shows whatever I configure in the form field in the azure portal.

**Comment by davidebbo** [comment]
Can you give more details about the issue? What exactly is the behavior when you set this?

Also, is this on Azure, or are you running Kudu yourself?

**Comment by floneo** [comment]
As in the steps above: It's two instances of an azure web app and I'm using the kudu which comes bundled with it.

When I set a branch like `release/.*`, `release/**`, `release/{name}` or something like this, I would expect kudu to deploy a branch which is called `release/1.0.0` for example, but it fails. The azure portal tells as the reason for failing "N/A" and the log says "No error message has been provided by the native library".

**Comment by davidebbo** [comment]
So you're trying to set the branch to a string with wildcards? There is definitely no support for this. Kudu doesn't have any special processing for the branch. All it does is use it in standard git commands like 'git checkout'.

**Comment by floneo** [comment]
Yes, that's what I was trying to do. It still could use standard git commads for the checkout and so on. The interesting part would be, what it extracts from the webhook that calls it. But for my issue, I guess, we're done. Thank you.
