### ISSUE TITLE
Trouble recognizing that the project is deployable

### ISSUE THREAD

**Issue by jeancroy** [projectkudu/kudu#2388]
### Repro steps.
1- Have web app sync using github.
2- Sync code to monitored branch
3- Look at deployment detail > activity log, no MSBUILD task, using "basic" deploy

### The log/error given by the failure.

> Found solution 'D:\home\site\repository\Xxxxx.sln' with no deployable projects. Deploying files instead.

### Remote debug
Following guide here's a dummy webapp
http://dummyzest.azurewebsites.net/

### Mention any other details that might be useful.

I could trace the error message to [this](https://github.com/projectkudu/kudu/blob/af1b4c524926ed0ad9ec6cb5b3789157256eaaf6/Kudu.Core/Deployment/Generator/SiteBuilderFactory.cs#L90)

I do not have asp.net core so I'm guessing i need wap.
[Here](https://github.com/projectkudu/kudu/blob/af1b4c524926ed0ad9ec6cb5b3789157256eaaf6/Kudu.Core/Infrastructure/VsHelper.cs#L71) and [Here](https://github.com/projectkudu/kudu/blob/af1b4c524926ed0ad9ec6cb5b3789157256eaaf6/Kudu.Core/Infrastructure/VsHelper.cs#L14)

Looking at my csproj I have

````xml
    <ProjectTypeGuids>{349c5851-65df-11da-9384-00065b846f21};{fae04ec0-301f-11d3-bf4b-00c04f79efbc};</ProjectTypeGuids>
````
So MVC 5, c#

**Comment by davidebbo** [comment]
Can you provide a minimal sample repo to help investigate, per [this page](https://github.com/projectkudu/kudu/wiki/Using-a-git-repo-to-report-an-issue)? Thanks!

**Comment by jeancroy** [comment]
This is my minimal repro
https://github.com/jeancroy/minimalreprokudu

Synced with 
http://dummyzest.azurewebsites.net/

Verified that it still show error
> Found solution 'D:\home\site\repository\Zesty.sln' with no deployable projects. Deploying files instead.

Without the build step, website show a permission error.
> You do not have permission to view this directory or page.

With the build step, website is an hello world.

**Comment by davidebbo** [comment]
@watashiSHUN can you take a look at this one? Something must be throwing off our project type detection logic.

**Comment by jeancroy** [comment]
Good it's recent changes I'm not going crazy.

I'm not sure it's linked my issue but [this unit test](https://github.com/projectkudu/kudu/blob/2ea953e532d0a44afe291dc4b9e370df9fc51686/Kudu.Core.Test/Infrastructure/VsSolutionTest.cs#L79-L81) looks out of sync with code to me.

- It check for both `IsWap` and guid `fae04`

While the [code](https://github.com/projectkudu/kudu/blob/af1b4c524926ed0ad9ec6cb5b3789157256eaaf6/Kudu.Core/Infrastructure/VsHelper.cs#L14) associate `IsWap` with guid `349c5`

And only because test csproj has both , the two are in agreements.

**Comment by watashiSHUN** [comment]
we first check the `.sln` file, if it is recognized as [KnownToBeMSBuildFormat](https://msdn.microsoft.com/en-us/library/microsoft.build.construction.solutionprojecttype.aspx), we proceed to determine whether its a web proj (ASP.NET).

in [your case](https://github.com/jeancroy/minimalreprokudu/blob/master/Zesty.sln#L6), project type GUID: `61E901DE-8FCF-4AA2-9FB2-B7F22A95362A` is not recognizable (for comparison my dummyMVCapp has [`FAE04EC0-301F-11D3-BF4B-00C04F79EFBC`](https://github.com/watashiSHUN/dummyMVCapp/blob/master/dummyMVCapp.sln#L6) which tells us its a C# project)

I compared the two `.sln` and we have the same VS version: 14.0.25420.1. Could you give us details about how you created your project?

**Comment by jeancroy** [comment]
I'm sorry the fault in on our end then.

That MVP project has been forked from another project then a new guid has been generated to allow to open both project in visual studio. (and manually replaced)

It's very possible we have wrongly overwritten the projectType too.
I'll change back to FAE04EC0-301F-11D3-BF4B-00C04F79EFBC.
