### ISSUE TITLE
Kudu stops working. 502 Bad gateway.

### ISSUE THREAD

**Issue by ghost** [projectkudu/kudu#2390]
> ---------------------------------------------------------------
Hi guys, I have been experiencing issues with my kudu site. Sometimes when I add a new custom domain and a SSL binding, Kudu stops working. I tried restarting the  AppService, but isn't work. The website is working normally, just Kudu and related things (VS publish feature, Webjobs, Process explorer, etc) are down. 

http://car-dealer.scm.azurewebsites.net/

I got the following error: 

502 - Web server received an invalid response while acting as a gateway or proxy server.
There is a problem with the page you are looking for, and it cannot be displayed. When the Web server (while acting as a gateway or proxy) contacted the upstream content server, it received an invalid response from the content server.

I have been experiencing this issues too often. The Kudu starts working again after a big time window, maybe hours. Could you help me to detect was going on?

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
