### ISSUE TITLE
WebHooks.cshtml does not implement validation on the WebHook URL and an empty URL is valid

### ISSUE THREAD

**Issue by FinVamp1** [projectkudu/kudu#2391]
On the WebHooks part in the Kudu site you can add a new WebHook URL and the WebHook URL can be empty and not required. 

[
  {
    "id": "636229099244412791",
    "event": "TriggeredJobFinished",
    "url": ""
  }
]

Looked at the code and this could be fixed on the ViewModel or on the /hooks API when the JSON is received. 

I will look and see if I can find a way to fix this.

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
