### ISSUE TITLE
KuduSync ignore list in file

### ISSUE THREAD

**Issue by robrich** [projectkudu/kudu#2395]
I know I can ignore files by listing them in the `-i` flag such as `-i ".git;.hg;.deployment;deploy.cmd"` but this list easily gets very long.  I would like to have a file similar to `.gitignore` or `.npmignore` where I can list files, globs, and other content to ignore, and pass this to kudusync.

**Comment by davidebbo** [comment]
Not unreasonable, but belongs more on this repo: https://github.com/projectkudu/KuduSync.NET

**Comment by robrich** [comment]
Moved to https://github.com/projectkudu/KuduSync.NET/issues/19
