### ISSUE TITLE
Visibility of new Azure AppService Tooling

### ISSUE THREAD

**Issue by tbertenshaw** [projectkudu/kudu#2396]
Is there a place whereby someone can monitor the installation of new tooling on Azure Appservices?

I use kudu slot based deployment for my site. And I use typescript and .Net 4.6.2. However i am aware that if i update my project to use typescript 2.2 specific syntax, it fails to deploy as typescript 2.1 is the latest.
Additionally If i try and use value tuples (c#7) my site fails to deploy as the latest msbuild version is 14.

It would be very handy to have a more visible place to check rather than using the kudu console and looking the \program files (x86)\ folder.

**Comment by davidebbo** [comment]
Sorry, there is no great page to track this. Some comments:

- For c# 7 syntax, you can make it work today. See http://stackoverflow.com/questions/43071785/can-we-deploy-a-c-sharp-7-web-app-to-azure-using-kudu/43129632#43129632
- For TypeScript, we need to get this updated. I will look into that.

**Comment by davidebbo** [comment]
TypeScript 2.2 is now deployed, and C#7 syntax can be made to work per my previous comment.

**Comment by tbertenshaw** [comment]
thanks. Presumably despite the workaround at some point in the future the v15 build tools will bedeployed.

Incidentally how do new appservice tools get deployed. Are the installations scripted against all the existing  app service vms, or so they start up kind of like containers?

**Comment by davidebbo** [comment]
Yes, we'll get the VS2017 tools, as tracked by #2350.

It's not exactly Containers, but something along those lines that cause all VMs to have the same bits.
