### ISSUE TITLE
Angular2 deployment performance

### ISSUE THREAD

**Issue by danpardo** [projectkudu/kudu#2397]
Hi, I wasn't sure to open an issue but here I am.
I am deploying 2 angular2 apps to an azure web site and deployment script takes approximately 15 minutes with node_modules folder already created and 25 without it.
Attached is  the deployment log. Any ideas on how to improve time? Does the app service configuration (ram, cpu, etc.) has something to do?
I tried to avoid kudusync, do everything in the same repository folder and in the end move the necessary files to wwwroot but I could not make it work.
Deployment script is pretty straight forward but in the end move dist\client files to wwwroot folder.

This is the deployment part of the script:
`:: 3. Install npm packages
IF EXIST "%DEPLOYMENT_TARGET%\package.json" (
  call :ExecuteCmd !NPM_CMD! set progress=false
  echo Install npm packages
  pushd "%DEPLOYMENT_TARGET%"
  call :ExecuteCmd !NPM_CMD! install
  echo Finished installing npm packages
  IF !ERRORLEVEL! NEQ 0 goto error
  popd
)

:: 4. Build the webclient
IF EXIST "%DEPLOYMENT_TARGET%\package.json" (
  echo Build the webclient
  pushd "%DEPLOYMENT_TARGET%"
  call :ExecuteCmd !NPM_CMD! run build
  echo Finished building the webclient
  IF !ERRORLEVEL! NEQ 0 goto error
  popd
)

echo Moving client folder

move /y "%DEPLOYMENT_TARGET%\dist\client\*" "%DEPLOYMENT_TARGET%"

echo Client folder moved`

[Log.txt](https://github.com/projectkudu/kudu/files/894276/Log.txt)

**Comment by ahmelsayed** [comment]
unfortunately that's just npm behavior. running npm install on my local machine for a large angular2 app takes about 2 to 3 minutes. That's with a fast SSD, on Azure the disk is significantly slower since it's a network share, etc. Aside from avoiding npm install, which won't be correct since npm is non-deterministic.
[yarn](https://yarnpkg.com/en/) on the other hand is deterministic and can know that a restore is not needed based on its lock file. Try giving that a try.

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
