### ISSUE TITLE
Azure webapp tomcat behind reverse proxy

### ISSUE THREAD

**Issue by pba-av** [projectkudu/kudu#2401]
Hi Team,

As far as I understand, when using a webapp with a Tomcat web container for instance, the webserver sits behind a reverse proxy that handles SSL encryption. Incoming request (https) are forwarded by the proxy to the tomcat as http requests so that the tomcat has no idea the original request was encrypted (except by checking some specific headers like `X-Forwarded-Proto: https` but it does not check them by default). 

I'm trying to deploy a keycloak application which is configured to run in production with SSL enabled meaning that it would reject any unsecured request (i.e https).  So to make it works properly, I had to upload my own tomcat instance and add the following line in the server.xml file:

`<Valve className="org.apache.catalina.valves.RemoteIpValve" remoteIpHeader="x-forwarded-for" proxiesHeader="x-forwarded-by" protocolHeader="x-forwarded-proto" />`

From tomcat documentation:

> Tomcat port of mod_remoteip, this valve replaces the apparent client remote IP address and hostname for the request with the IP address list presented by a proxy or a load balancer via a request headers (e.g. "X-Forwarded-For").
> 
> Another feature of this valve is to replace the apparent scheme (http/https), server port and request.secure with the scheme presented by a proxy or a load balancer via a request header (e.g. "X-Forwarded-Proto").

It works fine but it's bit painful to have to upload a custom tomcat instance just to add one line of configuration in server.xml. 
It would ease deployments if the installed tomcat instances were already setup with this configuration. 

Thanks.

**Comment by davidebbo** [comment]
You're probably in the wrong place here, as this does not sound related to Kudu. Please use https://social.msdn.microsoft.com/Forums/azure/en-US/home?forum=windowsazurewebsitespreview or StackOverflow for Azure Web App questions.
