### ISSUE TITLE
Deployment script in Azure CLI 2.0?

### ISSUE THREAD

**Issue by vidarkongsli** [projectkudu/kudu#2406]
Is there an equivalent to `azure site deploymentscript` in Azure CLI 2.0? (Ref. [Custom deployment script](https://github.com/projectkudu/kudu/wiki/Custom-Deployment-Script#custom-deployment-script-generator))

**Comment by davidebbo** [comment]
No, but it's simpler to just use kuduscript directly. Install it using `npm install -g kuduscript`, and then run `kuduscript`.
