### ISSUE TITLE
KuduSync fails when previous deployment did not use KuduSync

### ISSUE THREAD

**Issue by jbrantly** [projectkudu/kudu#2407]
I am deploying a node app to a linux app service through git. The first few deployments I had a `.deployment` and `deploy.cmd` file which did not use KuduSync. Afterward I removed those files and did a new deployment which used the default behavior of generating and executing `deploy.sh` which used KuduSync. Unfortunately this fails because KuduSync is expecting a previous manifest file from the previous deployment but that manifest file does not exist.

**Comment by davidebbo** [comment]
This is an unusual situation we have not encountered before. Try cleaning out your `D:\home\site\deployments` in Kudu Console. You'll lose your deployment history, but it'll get you out of trouble.

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
