### ISSUE TITLE
Commit id in post deployment hook

### ISSUE THREAD

**Issue by xt0rted** [projectkudu/kudu#2408]
I've been using [sgwill/hubot-azure-notifier](https://github.com/sgwill/hubot-azure-notifier) to show deploy statuses in slack, but I would like to build this out to include more information about the deploy. Some of this I can do via parsing the message (GitHub has a common format of `Merge pull request #xxx from user/branch`) but this isn't always going to work since not all of my repos use PRs. What I'd like to get is the commit id so I could include a link with it in the message. Is there any way to get more info like this in the deployment hook?

**Comment by davidebbo** [comment]
Try using `SCM_COMMIT_ID` environment variable, per https://github.com/projectkudu/kudu/wiki/Deployment-Environment.

**Comment by davidebbo** [comment]
Wait, maybe I misunderstood. Are you referring to the WebHook feature? That already has the commit id in the payload (it's just called `id`). See https://github.com/projectkudu/kudu/wiki/Web-hooks#hook-request-fired-by-the-kudu-service

**Comment by xt0rted** [comment]
For some reason I thought that was the Id of the deploy not the commit. Thanks for the clarification.
