### ISSUE TITLE
msbuild on Kudu does not support NetStandard projects

### ISSUE THREAD

**Issue by lindydonna** [projectkudu/kudu#2417]
- Use the VS project type for NetStandard 2.0 projects: https://github.com/lindydonna/NetStandardLib
- OR, from the dotnet CLI, run `dotnet new classlib -o NetStandardLib`
- Build from Kudu with the command `msbuild NetStandardLib.csproj`
- Error:

> "D:\home\site\NetStandardLib\NetStandardLib\NetStandardLib.csproj" (default target) (1) ->
  D:\home\site\NetStandardLib\NetStandardLib\NetStandardLib.csproj(1,1): error MSB4041: The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.

I can use `dotnet build NetStandardLib.csproj` just fine. Perhaps that's a suitable workaround, it just requires a custom deployment script if you're using CI.

**Comment by davidebbo** [comment]
@watashiSHUN please take an initial look. It may be that this won't work till we have new VS15 msbuild.

**Comment by watashiSHUN** [comment]
@lindydonna which version of **dotnet cli** are you using? I tested with `1.0.1` (latest available in Azure)
and the created `classlib` has `<TargetFramework>netstandard1.4</TargetFramework>` which we already had a [test](https://github.com/KuduApps/AspNetCoreRC3CliWithLib/blob/master/library/library.csproj#L4) for it

**Comment by lindydonna** [comment]
I manually changed the target framework to match the new Functions tooling. However, either way it doesn't build with `msbuild`, which we have a hard dependency on.

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
