### ISSUE TITLE
unable to deploy one resource group contains a webapp (B1) and function app (Dynamic)

### ISSUE THREAD

**Issue by globysdz** [projectkudu/kudu#2421]
> For deployment issues, please provide us with the following information:
our application contains two parts 
1. a web app which has the resource plan on uswest2, with Basic plan
2. a functional app which has the resource plan on uswest2 with Dynamic plan.
3. we would like to use a single resource group to deploy them together
I seems to unable to get this to work, is this supported? or I am forced to use different resource groups? which I need to handle the other shared resources(like storage) by myself?

**Comment by davidebbo** [comment]
Can you clarify what specific issue you are running into? *I seems to unable to get this to work* is a little vague :)

**Comment by globysdz** [comment]
my issue is a dup of this one: 
http://wp.sjkp.dk/azure-functions-the-pricing-tier-dynamic-is-not-allowed-in-this-resource-group/

after change the deployment order (first deploy the dynamic resource) it works fine.
