### ISSUE TITLE
Unable to browse site extensions from kudu and portal.azure.com

### ISSUE THREAD

**Issue by sjkp** [projectkudu/kudu#2422]
Hi 

It seems that a recent update have broken the functionality of the siteextensions UI in the kudu portal. 
![image](https://cloud.githubusercontent.com/assets/3397744/25720196/57581efc-310c-11e7-8fd4-6b18949767e1.png)
Normally there's a play button that takes you to the homepage of the installed site extension, that is missing. This is on a web app with x64 bit enabled (but also reproducable on 32bit) hosted in North Europe region. 

I think it might also have a related side effect in the portal.azure.com UI, as the browse button is not clickable. 
![image](https://cloud.githubusercontent.com/assets/3397744/25720178/46bc5824-310c-11e7-9934-4367acf863db.png)

Btw. the site extensions are still browsable, by manually typing in the full url, it is just the UI to browse to them that is not working.

**Comment by davidebbo** [comment]
Hmmm, that's odd. I wonder what could have changed here.

**Comment by suwatch** [comment]
Issue found.   Typo regression in [Kudu](https://github.com/projectkudu/kudu/blob/290284c471f6b8b9f8ffdd5abd7d53864dd56568/Kudu.Core/SiteExtensions/SiteExtensionManager.cs#L742).   We will address it in the next release.

**Comment by willvlad** [comment]
Same here

**Comment by davidebbo** [comment]
The fix is now deployed. Please verify. Uou may need to restart your site to make sure you switch to the new Kudu.
