### ISSUE TITLE
The "play" button is no longer displayed in the installed site extensions in Kudu

### ISSUE THREAD

**Issue by HansOlavS** [projectkudu/kudu#2424]
When I to go the Site Extensions in Kudu and list my installed extensions I'm no longer seeing a "play" button, but instead the "Plus" install button is displayed.

Environment:
Build 62.60425.2807.0 (d16270e428)
Azure App Service 62.1.8598.29 (rd_websites_stable.170426-1837)

See attached image.

![site_extensions_no_play_btn](https://cloud.githubusercontent.com/assets/12972203/25756705/0eaac7b0-31c8-11e7-9246-1b94ebdcb6ba.png)

**Comment by davidebbo** [comment]
Same as #2422.

**Comment by davidebbo** [comment]
The fix is now deployed.
