### ISSUE TITLE
Kudu shouldn't fire settriggers events for non-Dynamic apps

### ISSUE THREAD

**Issue by davidebbo** [projectkudu/kudu#2425]
It only makes sense for Dynamic/Consumption. Same goes for WebDeploy. /cc @suwatch

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
