### ISSUE TITLE
Kudu synctrigger logic doesn't support having 'enabled' set to an environment variable

### ISSUE THREAD

**Issue by davidebbo** [projectkudu/kudu#2428]
It's valid for functions.json to have:

```
{
  "disabled": "MyEnvVariable",
  "bindings": [ ...  ]
}
```

The runtime supports it, but Kudu does not, causing the triggers to get ignored.

And not that `MyEnvVariable` above is correct. It should not be `%MyEnvVariable%`

**Comment by davidebbo** [comment]
Issue is on https://github.com/projectkudu/kudu/blob/5a81fb0659a240c3834d627d23d7b92eb3ff1c28/Kudu.Core/Helpers/PostDeploymentHelper.cs#L278, where it assumes the value is a bool.

**Comment by suwatch** [comment]
This is not a regression, correct?  It is just that we never support it in Kudu and simply need to support (sync up) with runtime.

**Comment by watashiSHUN** [comment]
we want to duplicate [this function code](https://github.com/Azure/azure-webjobs-sdk-script/blob/a9bafba78a3a8092bfd61a8c7093200dae867efb/src/WebJobs.Script/Host/ScriptHost.cs#L1476-L1498) in kudu?

**Comment by suwatch** [comment]
we want to simply do Environment.Expand..   The reason is this code is shared with msdeploy and we need to make sure not pulling any more library than this specific one.

**Comment by davidebbo** [comment]
@suwatch correct, it's not a regression. Just something that had not come up.

Agreed, let's keep it simple, but note that `Environment.Expand` is not correct, since that requires %, and we just have it straight. So it should just be:

- Environment.GetEnvironmentVariable() is not null, use that value
- Else, convert to bool as we do now

**Comment by watashiSHUN** [comment]
in azure function, we consider [`"1" == true`](https://github.com/Azure/azure-webjobs-sdk-script/blob/a9bafba78a3a8092bfd61a8c7093200dae867efb/src/WebJobs.Script/Host/ScriptHost.cs#L1489-L1490) same applies here?

**Comment by davidebbo** [comment]
May as well throw that in!

**Comment by ahawes-clarity** [comment]
Is this fix in production yet?

**Comment by davidebbo** [comment]
Yes, it is.

**Comment by ahawes-clarity** [comment]
I can confirm on my end. Thanks

**Comment by ahawes-clarity** [comment]
However, the UI in the portal still does not display properly. I have functions that are enabled using Application Settings to set 'disabled' to false. Viewing the host log I can see the functions are enabled. This needs fixed as well.

![image](https://user-images.githubusercontent.com/6013584/27643767-96198fe4-5be7-11e7-8d63-3200b15f2fd4.png)

**Comment by davidebbo** [comment]
@ahawes-clarity https://github.com/Azure/azure-functions-ux/issues would be the right place for that part, thanks!

**Comment by ahawes-clarity** [comment]
I did back in May.
https://github.com/Azure/azure-functions-ux/issues/1349

I was hoping for a resolution by now. Sounds like 'disabled' in the function.json may be going away. Do you have any insight you can share on that?
