### ISSUE TITLE
The specified framework 'Microsoft.NETCore.App', version '1.1.2' was not found

### ISSUE THREAD

**Issue by stevenmollie** [projectkudu/kudu#2433]
when uploading my web application to Azure i get the following error after checking the stdout log file

The specified framework 'Microsoft.NETCore.App', version '1.1.2' was not found.

  - Check application dependencies and target a framework version installed at:

      D:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App

  - The following versions are installed:

      1.0.0

      1.0.0-rc2-3002702

      1.0.1

      1.0.3

      1.0.4

      1.1.0

      1.1.0-preview1-001100-00

      1.1.1

  - Alternatively, install the framework version '1.1.2'.

**Comment by davidebbo** [comment]
1.1.2 will be available by next Tuesday.

**Comment by stevenmollie** [comment]
can I solve this issue in one way or anthoer?

**Comment by davidebbo** [comment]
Sure, just use 1.1.1 until 1.1.2 is deployed.

**Comment by davidebbo** [comment]
Also, can you clarify how you are deploying to Azure? Are you using git, or deploying from VS?

**Comment by stevenmollie** [comment]
I am deploying from VS, the application is a .NETCoreApp 1.1, together with a Classlibrary .NET Standard 1.4, how can I change to 1.1.1?

**Comment by davidebbo** [comment]
Try to change this is your csproj: `<TargetFramework>netcoreapp1.1.1</TargetFramework>`.

**Comment by stevenmollie** [comment]
Ok that worked, thanks
