### ISSUE TITLE
ASP.Net Core App "storage usage quota exceeded. Cannot update or delete a server farm"

### ISSUE THREAD

**Issue by tbertenshaw** [projectkudu/kudu#2438]
I have a site which is set to deploy via git (github)

its an asp.net core app and its a very simple site using the javascript services template.

I was initially having issues deploying so i changed the site to a small basic instance. However i am unable to change the site to a shared service pricing as i get the following error below.

`Failed to update App Service plan defaultserviceplan: {"Code":"Conflict","Message":"Storage usage quota exceeded. Cannot update or delete a server farm.","Target":null,"Details":[{"Message":"Storage usage quota exceeded. Cannot update or delete a server farm."},{"Code":"Conflict"},{"ErrorEntity":{"ExtendedCode":"11006","MessageTemplate":"Storage usage quota exceeded. Cannot update or delete a server farm.","Parameters":[],"InnerErrors":[],"Code":"Conflict","Message":"Storage usage quota exceeded. Cannot update or delete a server farm."}}],"Innererror":null}`

**Comment by ahmelsayed** [comment]
It's probably telling you that your files are more than the storage allowed for shared. Shared only has 1 GB vs basic 10 GB

**Comment by davidebbo** [comment]
Indeed. Closing here since this is a general Azure App Service question and not directly related to Kudu.

**Comment by tbertenshaw** [comment]
Any ideas where i can find more out about this? the entire app folder on my local machine is 122M (nuget and node modules) does this imply that when a shared site has 1G more than 900M of that is core files and thus you have something more like 10% of this space to use for your own app content?

**Comment by ahmelsayed** [comment]
you can go to debug console and run `du -sh *` and chase it down from D:\home. It could be logs or some other left over artifacts.

**Comment by tbertenshaw** [comment]
again sorry if continuing this discussion in the wrong area? but this seems wrong? Shared is £7.21 a month and basic is £41.59  would seem massive overkill if i need a basic tier app for a very basic .Net core app. which seems well within the quoted limits?

![image](https://cloud.githubusercontent.com/assets/2010002/26142663/74af5d2c-3ad9-11e7-9be1-de2d44f4ec36.png)

**Comment by ahmelsayed** [comment]
@tbertenshaw can you share your app name either directly or [indirectly](https://github.com/projectkudu/kudu/wiki/Reporting-your-site-name-without-posting-it-publicly).

Are you trying to change the whole App Service Plan? because you might have more apps on that plan. The  problem is that the quota is plan wide, and each app on the plan takes some of it. So it might be a different app there that's the problem.
