### ISSUE TITLE
Environment variables in the .deployment file

### ISSUE THREAD

**Issue by xt0rted** [projectkudu/kudu#2441]
I set a couple app settings in the portal such as the node & npm versions. Can these be set in the `.deployment` file just like the `command` value can? I'd like to store these with the site/deployment scripts so they're easier to update and keep track of.

My project is an asp.net site with .net based webjobs, but I'm using node for part of the build & deploy process. I've run into issues a few times now where the version of node we wanted to use changed but we forgot to update the app settings to go with it, resulting in a failed deployment. Since we're already storing this value in our `project.json` and `appveyor.yml` it'd be nice if we could store the environment version in a config file as well.

**Comment by davidebbo** [comment]
Environment variables cannot be set via `.deployment`. But if your goal is to set the Node version, the best way to do it is using the `engines` field in `package.json`.
