### ISSUE TITLE
Consider: Suppress tracing from Kudu console noises

### ISSUE THREAD

**Issue by suwatch** [projectkudu/kudu#2443]
When on KuduConsole, we accumulate quite a few of below.   It is not very useful and we should consider suppress it if from browser user-agent.

```
GET /api/vfs
POST /api/filesystemhub
POST /api/commandstream
```

**Comment by watashiSHUN** [comment]
@suwatch you mean when we have `SCM_TRACE_LEVEL` set to 4? I don't see any traces from normal kudu console except some start requests?

**Comment by suwatch** [comment]
Browse to (debug console), you will see many of them.   It is more noises than being real useful.   We should try to suppress them if not explicitly SCM_TRACE_LEVEL verbose (4).

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
