### ISSUE TITLE
Some folders missing after publishing .net corre app to azure app service

### ISSUE THREAD

**Issue by handsumkenny** [projectkudu/kudu#2447]
> For deployment issues, please provide us with the following information:
> ---------------------------------------------------------------

### Repro steps.
> your project built successfully on your dev machine but failed on Azure?
Yes
{
  "userSecretsId": "aspnet-TotalCostNG.Web-6f324226-a3af-475f-8895-2956586ff994",

  "dependencies": {
    "Microsoft.NETCore.App": {
      "version": "1.0.1",
      "type": "platform"
    },
    "Microsoft.ApplicationInsights.AspNetCore": "1.0.0",
    "Microsoft.AspNetCore.Authentication.Cookies": "1.0.0",
    "Microsoft.AspNetCore.Diagnostics": "1.0.0",
    "Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore": "1.0.0",
    "Microsoft.AspNetCore.Identity.EntityFrameworkCore": "1.0.0",
    "Microsoft.AspNetCore.Mvc": "1.0.1",
    "Microsoft.AspNetCore.Razor.Tools": {
      "version": "1.0.0-preview2-final",
      "type": "build"
    },
    "Microsoft.AspNetCore.Routing": "1.0.1",
    "Microsoft.AspNetCore.Server.IISIntegration": "1.0.0",
    "Microsoft.AspNetCore.Server.Kestrel": "1.0.1",
    "Microsoft.AspNetCore.StaticFiles": "1.0.0",
    "Microsoft.EntityFrameworkCore.SqlServer": "1.0.1",
    "Microsoft.EntityFrameworkCore.SqlServer.Design": {
      "version": "1.0.1",
      "type": "build"
    },
    "Microsoft.EntityFrameworkCore.Tools": {
      "version": "1.0.0-preview2-final",
      "type": "build"
    },
    "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.0.0",
    "Microsoft.Extensions.Configuration.Json": "1.0.0",
    "Microsoft.Extensions.Configuration.UserSecrets": "1.0.0",
    "Microsoft.Extensions.Logging": "1.0.0",
    "Microsoft.Extensions.Logging.Console": "1.0.0",
    "Microsoft.Extensions.Logging.Debug": "1.0.0",
    "Microsoft.Extensions.Options.ConfigurationExtensions": "1.0.0",
    "Microsoft.VisualStudio.Web.BrowserLink.Loader": "14.0.0",
    "Microsoft.VisualStudio.Web.CodeGeneration.Tools": {
      "version": "1.0.0-preview2-final",
      "type": "build"
    },
    "Microsoft.VisualStudio.Web.CodeGenerators.Mvc": {
      "version": "1.0.0-preview2-final",
      "type": "build"
    }
  },

  "tools": {
    "BundlerMinifier.Core": "2.0.238",
    "Microsoft.AspNetCore.Razor.Tools": "1.0.0-preview2-final",
    "Microsoft.AspNetCore.Server.IISIntegration.Tools": "1.0.0-preview2-final",
    "Microsoft.EntityFrameworkCore.Tools": "1.0.0-preview2-final",
    "Microsoft.Extensions.SecretManager.Tools": "1.0.0-preview2-final",
    "Microsoft.VisualStudio.Web.CodeGeneration.Tools": {
      "version": "1.0.0-preview2-final",
      "imports": [
        "portable-net45+win8"
      ]
    }

  },

  "frameworks": {
    "netcoreapp1.0": {
      "imports": [
        "dotnet5.6",
        "portable-net45+win8"
      ]
    }
  },

  "buildOptions": {
    "emitEntryPoint": true,
    "preserveCompilationContext": true
  },

  "runtimeOptions": {
    "configProperties": {
      "System.GC.Server": true
    }
  },

  "publishOptions": {
    "include": [
      "wwwroot",
      "**/*.cshtml",
      "appsettings.json",
      "web.config"
    ]
  },

  "scripts": {
    "prepublish": [ "bower install", "dotnet bundle" ],
    "postpublish": [ "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%" ]
  }
}

### Project structures.
http://totalcostng.azurewebsites.net/

### The log/error given by the failure.
No error, just saying "You do not have permission to view this directory or page."

### Debug your Azure website remotely.
http://totalcostng.azurewebsites.net/

### Mention any other details that might be useful.

The only files that were published was those in wwwroot

**Comment by davidebbo** [comment]
A little hard to read through. Can you fix the markdown formatting? Also, the title refers to missing folder, but I see nothing in the description giving details about that, so the title and description feel disconnected.

**Comment by davidebbo** [comment]
Also, please see https://github.com/projectkudu/kudu/wiki/Make-sure-site-correctly-deploys-locally, and in particular the *Local deployment using msbuild* section.

**Comment by davidebbo** [comment]
I looked at your app and it doesn't look like you are deploying via git, so I don't think you are using Kudu at all here.

**Comment by handsumkenny** [comment]
What happened was that I was using Visual Studio web publish tool to publish an ASP.NET CORE APP to Azure app service. But after publishing all I see on my website online is "You do not have permission to view this directory or page." and viewing kudu shows just a directory the 'wwwroot' and a file hosting_start.html. I can't seem to get my way around It.

**Comment by davidebbo** [comment]
You're just using Kudu to view the files, and you'd see the same if you used FTP. There is no Kudu issue here, it's just showing you the state of your file system.

That being said, the link above should help you isolate your issue. You can use https://social.msdn.microsoft.com/Forums/azure/en-US/home?forum=windowsazurewebsitespreview for general App Service questions.
