### ISSUE TITLE
Azure Node.js deploy: index script needs to write files

### ISSUE THREAD

**Issue by MayasHaddad** [projectkudu/kudu#2448]
I am trying to deploy a node.js app to azure via git push.

I use a framework that generates a directory inside `wwwroot` with files in it at startup.

Running `node server.js` would trigger that step.

**Problem**: After I push to azure repo, the directory isn't created, and nothing indicates it.

It seems to me that it's write right issue.

**Question**: Is there a way I can grant it using kudu? 
Ideally, in a way that is scalable, as I will potentially deploy many other apps with the same boilerplate.

Thanks 🙏

**Comment by davidebbo** [comment]
@MayasHaddad can you share a [minimal repo](https://github.com/projectkudu/kudu/wiki/Using-a-git-repo-to-report-an-issue) that demonstrates the issue? Thanks!

**Comment by MayasHaddad** [comment]
@davidebbo you can deploy this: https://github.com/zeit/next.js/tree/v3-beta/examples/custom-server-express

**Comment by MayasHaddad** [comment]
Ok, I discovered [kuduscript](https://github.com/projectkudu/kudu/wiki/Custom-Deployment-Script#custom-deployment-script-generator) and managed to add the build step to `deploy.sh`.

Closing this issue.
