### ISSUE TITLE
Kudu/SCM Site stop/starting and killing web job process despite 'Always On' being enabled.

### ISSUE THREAD

**Issue by eoincgreenfinch** [projectkudu/kudu#2452]
Hey guys,

I'm clutching at straws on this one and hoping you can point me in the right direction. 

I have an web app service, containing a web job (continuous) that gets triggered by a queuetrigger. The job itself can run from anywhere between 10-30 minutes to bulk process and ETL some data into our database. 

The job however is being stopped mid run as a result of the SCM Site/w3wp process being stopped.

 - Both the application web site, and the web job are running .NET 4.6.2 and the latest web job nuget packages.
 - The app service is an "S1 Standard Instance"
 - The app service has the "Always On" setting enabled under the Application Settings Blade
 - The Kudu control panel is showing that the the $ENV variable is set to reflect the Always On Setting; `WEBSITE_SCM_ALWAYS_ON_ENABLED = 1`

Despite this, I'm still seeing occurrences where the w3wp process for the SCM will stop and start.

Under the Process Explorer I see.

`name                        pid`
`w3wp.exe                    4828`
`w3wp.exe scm                7044	 <--- after a stop/start these PIDs change.`
` cmd.exe webjob	            9584	`
`    MyWebJob.exe webjob     13412`

And in the logs on the SCM WebJob Dashboard @ https://mysite.scm.azurewebsites.net/azurejobs/#/jobs/continuous/MyWebJob the logs include the following message.

`[05/31/2017 14:32:14 > 3ecc6f: SYS INFO] WebJob is stopping due to website shutting down`
`[05/31/2017 14:32:14 > 3ecc6f: SYS INFO] Status changed to Stopping`
`[05/31/2017 14:32:16 > 3ecc6f: SYS INFO] Status changed to Success`
`[05/31/2017 14:32:17 > 3ecc6f: SYS INFO] Status changed to Stopped`
`[05/31/2017 14:32:30 > 3ecc6f: SYS INFO] Status changed to Starting`
`[05/31/2017 14:32:30 > 3ecc6f: SYS INFO] WebJob singleton setting is False`
`[05/31/2017 14:32:37 > 3ecc6f: SYS INFO] Run script 'MyWebJob.exe' with script host - 'WindowsScriptHost'`
`[05/31/2017 14:32:37 > 3ecc6f: SYS INFO] Status changed to Running`

I *think* I've been able to circumvent this by manually keeping the SCM alive by tapping on it with a powershell script every 60 seconds but to be honest this could be a red herring and I don't understand enough about what's going on under the hood and the relationship between the two W3WP processes and exactly what should be keeping the SCM always on.

Any pointers would be appreciated.

**Comment by davidebbo** [comment]
Is the site stopped by any chance? There is (or was, I forget the status) an issue that caused Always On to stop working if the main site is stopped, even though the scm site still needs it.

Other thing to look at: enable IIS logging, and check is the AlwaysOn pings are coming.

**Comment by eoincgreenfinch** [comment]
@davidebbo thanks for the quick response. No main site stayed up through out and no deployments took place.

Will turn on the IIS logs on the SCM and check that latter suggestion. Will report back. Cheers.

**Comment by eoincgreenfinch** [comment]
@davidebbo apologies I meant to come back to you on this ticket. We continued to see this issue for a short while after, but after anohter cycle of deployments it seemed to go away and the SCM (and web jobs) have stayed alive since. Gonna put this one down to a "temporary glitch" but it seems fine now. will close this ticket.

Cheers
~Eoin C

**Comment by davidebbo** [comment]
Cool, thanks for following up!

**Comment by mars-boy** [comment]
Hi @eoincgreenfinch @davidebbo , I am having the same issue with linux  Azure app service for dotnet core application where i am having a background service that does the same. any update for the same? yor reply is very much appreciated.
Thanks

**Comment by davidebbo** [comment]
@mars-boy I'm no longer on the team. But please note that the Linux support is quite different, so I'd suggest opening a separate issue to track what you're running into.

**Comment by mars-boy** [comment]
@davidebbo  sure thanks
