### ISSUE TITLE
Possibility to have a private SiteExtensions feed

### ISSUE THREAD

**Issue by sitereactor** [projectkudu/kudu#2453]
This is a feature request and not an issue 😄 

Currently the url to the siteextensions feed is hardcoded here: https://github.com/projectkudu/kudu/blob/master/Kudu.Contracts/Settings/DeploymentSettingsExtension.cs#L18

Would you accept a Pull Request that moves this to an appsetting, so it can be updated to point to a different url?

The idea would be to do something like this
```
public static string DefaultSiteExtensionFeedUrl
{
        get 
        {
	     string value = settings.GetValue(SettingsKeys.SiteExtensionFeedUrl);
	     return !String.IsNullOrEmpty(value) ? value : "https://www.siteextensions.net/api/v2/";
        }
}
```

**Comment by davidebbo** [comment]
Actually, we already have that! It's called [SCM_SITEEXTENSIONS_FEED_URL](https://github.com/projectkudu/kudu/wiki/Configurable-settings#site-extensions-gallery-feed-url).

**Comment by sitereactor** [comment]
Ahh, well perfect. I missed that one, thanks!
