### ISSUE TITLE
Disable webjob schedules for staging environment

### ISSUE THREAD

**Issue by chinarosesz** [projectkudu/kudu#2456]
I am looking for a way to disable webjobs schedules for a particular environment. For example, in staging, I only want to manually trigger each webjob after I deploy. I want to disable the schedules, but in Production slot, I want the schedules turned on. 

I use settings.job to specify the schedule for a manual triggered webjob. The only solution that I can think of is having two settings.job files and rename/transform them during build for staging and production environments. This will involve some scripting during the build process. I'm hoping there is something built in already that I didn't know about so I don't have to implement a workaround.

Ideally, what I would love to see is a setting that I can set such as WEBJOBS_DISABLE_SCHEDULE=1 to turn off the cron and have that sticky to Staging slot.

**Comment by davidebbo** [comment]
Fixed per #9a9cc16bb3adfd223535242d9b118ecb2da5f9f5. Deployment has started and is expected to complete by end of week.
