### ISSUE TITLE
Support running WebJob with jar file.

### ISSUE THREAD

**Issue by suwatch** [projectkudu/kudu#2457]
Currently, we don't support just jar file and user will have to provide companion bat script.  I think, at the minimum, we need to run `java.exe -jar file.jar`.   See [this](https://stackoverflow.com/questions/5774970/run-jar-file-in-command-prompt).   The entry point (such as Program's main) is part of the manifest in the jar file and java.exe will do the right thing.   Java.exe will be chosen from what on the path.

**Comment by snobu** [comment]
Should we leave `-Xms<heap size>` and  `-Xmx<heap size>` to whatever JDK defaults to? I guess people should wrap it in a `.cmd` if they want to be specific about memory constraints anyway... 

Here are some sane defaults:
http://jvmmemory.com/

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
