### ISSUE TITLE
Will there be any more Kudu release in the future?

### ISSUE THREAD

**Issue by lifan0127** [projectkudu/kudu#2458]
I am interested in setting up Kudu on our local IIS server to facilitate our team's transition to Azure App Service in the future. I noticed that the most recent published release is almost 20 months old and I am sure numerous upgrades have been made during that period. Will there be any new Kudu release in the near future? Thanks!

https://github.com/projectkudu/kudu/releases/tag/S48

**Comment by davidebbo** [comment]
Our primary target is Azure, so we don't consistently make public releases unless people ask. I just made a new one: https://github.com/projectkudu/kudu/releases/tag/S62

**Comment by lifan0127** [comment]
Thanks, @davidebbo I was able to install your latest Kudu release on our server. Really appreciated your help.
