### ISSUE TITLE
Miss to terminate webjob processes if 64 bits processes

### ISSUE THREAD

**Issue by suwatch** [projectkudu/kudu#2460]
This is similar to https://github.com/projectkudu/kudu/issues/2459.   In this case, Kudu running in 32 bit process is unable to read envs at all (`The current process should run in 64 bit mode to be able to get the environment of another 64 bit process.`).

The fix is to delegate reading env to kuduhandles.exe (64 bits).   We do that for reading handles.

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
