### ISSUE TITLE
Add an event sent on site swap

### ISSUE THREAD

**Issue by alexkarcher-msft** [projectkudu/kudu#2461]
I'd like the ability to have an event sent to my site when a swap occurs. This will enable logic to execute when the site enters production. 

The current workaround is to sticky an app setting to the prod site and check it's status on startup. This triggers a site restart and is not ideal for highly available sites.

See more details in [this uservoice item](https://feedback.azure.com/forums/169385-web-apps/suggestions/6542450-have-the-swap-button-trigger-the-kudu-postdeploy)
> When I swap sites between a slot and production, I'd like the PostDeployment event triggered for the "production" site, so that I can write a service that informs my New Relic account of the deployment.

**Comment by davidebbo** [comment]
This would be something that lives in the core of App Service (where swap is implemented), and not part of Kudu.
