### ISSUE TITLE
Update the Wiki for setting up external private repositories

### ISSUE THREAD

**Issue by rchakra3** [projectkudu/kudu#2464]
The wiki page for  [Continuous Deployment](https://github.com/projectkudu/kudu/wiki/Continuous-deployment#create-an-azure-web-app-and-enable-source-control-with-an-external-repository) says that the source control type needs to be set to "External Repository" when in fact the correct setting is "Local git repository". 

It would be great if someone could update the wiki page with the correct details

**Comment by davidebbo** [comment]
'External Repository' is needed to enable the sync button. Did you run into a specific issue?

**Comment by rchakra3** [comment]
Ah I see that's specifically to enable the sync button. There should probably be some information specifying that it only works if the repository is public.

If the repo is private it isn't possible to successfully set it as an external repository. However, to get GitHub webhooks working with Kudu, some form of scm needs to be set. It would be useful to add a point there specifying the workflow for a private repo.

**Comment by davidebbo** [comment]
Hmmm, not sure why that didn't work. Did you get a failure?

Also, have you tried the non-manual steps (e.g. using Resource Explorer)? Once Azure has your github token (e.g. after doing one oauth workflow in Portal), that makes things super simple with no manual steps.

**Comment by rchakra3** [comment]
Yeah the failure was something along the lines of GitHub (or SCM) credentials not set. 

If this is not expected behavior for a private repository, I can reproduce the entire process and file another issue.

By non-manual steps do you mean selecting Github in the deployment options section? I'd rather not grant access to all the repositories I have access to.

**Comment by davidebbo** [comment]
Ok, I added a note under the 'External Repository' section.
