### ISSUE TITLE
Consider: decouple sync function trigger and logic app json

### ISSUE THREAD

**Issue by suwatch** [projectkudu/kudu#2469]
Current they co-locate in the same routine, meaning sync trigger call (post deployment or explicit REST api) will also sync logic app.  In addition, the same pre-condition (function enabled and Dynamic sku) are required.   If we were to decouple them, we need to define whether we need a new api to sync logic app, what are pre-conditions, etc.

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
