### ISSUE TITLE
Problems pushing to Kudu's source control from bitbucket-pipelines

### ISSUE THREAD

**Issue by johnsonjo4531** [projectkudu/kudu#2472]
I'm trying to get my bitbucket-pipelines script to deploy successfully to azure. I followed the following guide: https://confluence.atlassian.com/bitbucket/deploy-to-microsoft-azure-900820699.html. 

The following line in the code-block below shows what line  of my pipelines.yml is failing (where in my own yml file I have replaced the necessary information with my site information such as the repo name, and I have set up the environment variables in my settings):

```
git push https://$AZURE_LOGIN:$AZURE_PASSWORD@helloworld-azure-staging.scm.azurewebsites.net/helloworld-azure.git master
```

the below error is produced from the above line in my yml file:

```
fatal: repository '<azure-kudu-repo-name>' not found
```

I have attempted narrowing down the error and tried git pushing on my local machine. Once I git pushed on my local machine I was able to recreate the same error. My azure login is an email address which includes an `@` symbol so I figured this was messing it up. I then tried encoding it with %40. This gave me a separate error message which said: 

```
fatal: Authentication failed for '<azure-kudu-repo-name>'
```

I was wondering what the best approach to manually pushing to azure's kudu is from bitbucket pipelines, and where I might be going wrong. Any help is appreciated.

My site's name is Redbirddev.

**Comment by davidebbo** [comment]
@johnsonjo4531 It looks like Web App Redbirddev is not set up for source control. I'm not sure exactly how the bitbucket set up works, but try simply setting up your app for Local Git (under Deployment Options). You *probably* don't want to set up up as bitbucket on the Azure side, as that'll mean something different.
