### ISSUE TITLE
Support an async pattern for the zip upload API

### ISSUE THREAD

**Issue by AWahlqvist** [projectkudu/kudu#2474]
**Some background**
This issue is related to #1741 

We also run into the timeout problem. As already noted in that bug thread, in our experience the problem isn't really the upload part (which is usually quick), but when the zip archive contains a huge number of files. After trying different clients it seems that this issue isn't really with Kudu nor the client, but with the load balancer in Azure which kills off idle connections after 230 seconds. If it takes the Kudu instance more than 230 seconds to expand the archive, the connection gets killed and we get the timeout error.

The exact same thing happens when uploading the zip file through a browser, the connection drops and you can see that the "paKman.gif" disappears.  If you use dev tools to monitor the request you'll see that it times out as well:
![image](https://user-images.githubusercontent.com/5821559/26974503-f0977042-4d1b-11e7-8312-884c1e960e55.png)

![image](https://user-images.githubusercontent.com/5821559/26974521-018c370c-4d1c-11e7-99fe-ab39ea5829ce.png)

However, in all these cases it seems the unpack process keeps running in the background and eventually finishes.

If you want to test this for yourself, here's a zipfile (~18 mb) with 100k txt-files divided into 100 folders:
https://kudurocks.blob.core.windows.net/repro/timeout.zip

Or create one yourself by running (PowerShell):
`1..100 | %{ "$_/100" ; $FolderName = $([Guid]::NewGuid().Guid) ; $null = New-Item -Path ".\$FolderName" -ItemType Directory ; 1..1000 | % { "$_" | Out-File .\$FolderName\$_.txt } }`

It will create the folder structure in the "current folder" which you would then need to zip and then upload.

**Feature request/workaround**
A possible workaround for this problem would be to enhance the logging for the unpack process. Like some other Kudu processes would it be possible to create a log file when the process starts which is renamed when the process has finished/a new one is created when it's done? I think this is basically how the zip-api call works when packaging a folder, and the file also includes any problems that occurred during the packaging process.

This would allow us to basically do this in a more "async" way by polling that logfile for the current status if the original API call times out, and verify that it doesn't contain any errors when done.

**Comment by davidebbo** [comment]
@AWahlqvist the 230s timeout is an App Service limit which unfortunately we have no control over. The one way to avoid it is to keep some data flowing. i.e. write to the response to keep it live. That's what we do in the 'git push' scenario. But it's harder to do in an API that needs to return a proper http code, as the minute you write the headers, you lose the ability to change the code.

The proper solution would be to provide an async pattern for this API, which is what you are suggesting. But that's a fair bit of work.

**Comment by davidebbo** [comment]
I renamed the issue to better capture what it's about (the logging part is more of an implementation detail).

**Comment by AWahlqvist** [comment]
I agree with you, thanks for your quick response!

I was mostly looking at this from my perspective where a logfile would make it possible for me to build a workaround for this issue, and I'm guessing it's quite a lot simpler to implement. But I totally agree implementing a true async pattern for this API would be the best solution long term (the same thing applies for the "create zip API" I guess, we solved that by creating our own zipping function that support running async in the the Kudu session since we needed to apply some rules regarding what to zip up anyway).

Again, thanks for your response!

**Comment by davidebbo** [comment]
Yes, I think you can build your own workaround:

- Instead of using zip API, upload a .cmd script (using vfs API) that does the unzipping, and write a marker file when it's done
- Start your script using the Command API
- Use the vfs API to poll for the marker file, so you know when it's done

A bit messy, but can be done :)

**Comment by AWahlqvist** [comment]
Yes, that's basically how the creation of the zip archive is done now :-)

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
