### ISSUE TITLE
Feature Request - REST API to return  function status in TimerTrigger webjob

### ISSUE THREAD

**Issue by chinarosesz** [projectkudu/kudu#2475]
I just finished trying out TimerTrigger. I like the fact that I can have multiple functions (child webjobs) in a parent webjob. I learned that the parent webjob has to be continuous, which is not a problem, however, we rely a lot of monitoring to know when anything fails. So if a function in the parent webjob fails, I'm not sure how to go about detecting the status and use Application Insights to raise an alert. 

With the manual triggered webjob, I can monitor when the status becomes failed, success, or is running using the REST API. Since using TimerTrigger, the status will always be running even if one of functions fails. 

The only solution that I can come up with is to use Application Insights to raise an alert if there is more than one exceptions being thrown in one of the functions.

**Comment by davidebbo** [comment]
@chinarosesz [TimerTrigger](https://github.com/Azure/azure-webjobs-sdk-extensions/wiki/TimerTrigger) is part of the WebJobs SDK, which is not par tof Kudu (yes, this can be confusing!).

The right place for this issue is https://github.com/Azure/azure-webjobs-sdk-extensions/issues.
