### ISSUE TITLE
Kudu PowerShell does not abort active commands with Esc or Ctrl+C

### ISSUE THREAD

**Issue by Jehoel** [projectkudu/kudu#2477]
I have a directory in my Azure website with a lot of files that I'm wanting to clean-up with `Get-ChildItem | Where-Object { predicates... } | Remove-ChildItem` - I often use `Get-ChildItem` by itself to get a feel for the files in the directory.

However if I start `Get-ChildItem` then the cmdlet will continue to output information one every file in the directory - this can take up to a full minute or longer, and frustratingly, I cannot stop or abort the command - I have to let it finish.

I'm using Chrome 58 on Windows and I've tried the `Esc` and `Ctrl+C` keys without success - whereas the PowerShell on my local Windows 10 desktop does honour `Ctrl+C` to abort the current command.

I couldn't find any documentation on aborting or stopping PowerShell commands in Kudu, so my apologies if this is a repost.

**Comment by davidebbo** [comment]
Unfortunately, Kudu Console is not a true console, so things like Ctrl+C just don't work, and would be hard to achieve.

Not very clean, but the simplest way to kill current command is to F5 the console in your browser.

Closing as there is no realistic hope of enabling Ctrl+C given current console architecture.

**Comment by lupinsansei** [comment]
How about just adding a little button that sends CTRL+C to the console then?
