### ISSUE TITLE
generated deploy.cmd is not applicable to all .net core web projects

### ISSUE THREAD

**Issue by lampersky** [projectkudu/kudu#2479]
### Repro steps.
1. Create an application as mentioned in this issue ( https://github.com/dotnet/cli/issues/6812 ), please make sure that your application has same structure, you can also download example project there,
2. Create a deployment script
`kuduscript -y --aspNetCore WebApplication1\WebApplication1.csproj -s WebApplication1.sln`,
3. Application built with this script won't run on Azure or even locally, because of an exception "MetadataException: Unable to load the specified metadata resource",
4. This exception is thrown because there are missing embedded resources in referenced class library.

Is there any way to create different deploy.cmd which allow us to run this kind of web projects?

## Environment data
`kuduscript --version` output:
1.0.15

**Comment by davidebbo** [comment]
All the script does is call:

    dotnet publish "WebApplication1\WebApplication1.csproj" --output "%DEPLOYMENT_TEMP%" --configuration Release

And that is expected to work. If it doesn't, then it is either an issue with the project or with `dotnet publish`, but not with Kudu.
