### ISSUE TITLE
Group WebJobs functions by containing job

### ISSUE THREAD

**Issue by BrianVallelunga** [projectkudu/kudu#2483]
This is a request for a usability improvement for the interface to WebJobs functions at https://mysite.scm.azurewebsites.net/azurejobs/#/functions

I currently have 6 continuous WebJobs executables deployed on a single App Service. Each executable has between 1 and 20 different exposed functions. Browsing through the list of functions via the web UI at the above URL is painfully slow and the functions aren't organized in any useful manner.

To improve the user experience, please group the functions by executable. Allowing me to pick an executable/job and then listing the functions would help tremendously. Alternatively, if the paging speed could be improved, that would be great first step, if nothing else could be done. Right now I often have to wait an entire minute for the next page of functions after clicking the Next button.

Thanks

**Comment by davidebbo** [comment]
This actually pertains to the WebJobs **SDK** which is quite separate from Kudu. Can you open on https://github.com/Azure/azure-webjobs-sdk/issues instead? Thanks!

**Comment by BrianVallelunga** [comment]
Done. Thanks for pointing me in the right direction.
