### ISSUE TITLE
deployement sync issue for git repos with a tag containing a special character

### ISSUE THREAD

**Issue by botmtl** [projectkudu/kudu#2485]
example:  
source repo (git system) has 3 commits that are tagged, respectively:
- "v1", "v2", "v2>2"

the sync activity will fail with Invalid reference name 'refs/tags/v2>2.

tests: you can try importing ttrss branch schema_upgrade_passed_(1.1_->_1.1.1) (https://github.com/botmtl/tt-rss-import/releases/tag/schema_upgrade_passed_(1.1_->_1.1.1).

ps.  please advise if that part of the import process is not your responsability

![untitled](https://user-images.githubusercontent.com/7614617/27262812-7f311f76-542c-11e7-85a4-03c3687e6d0c.png)

**Comment by davidebbo** [comment]
Can you try setting this Azure App Setting: `SCM_USE_LIBGIT2SHARP_REPOSITORY=0`? This would let us isolate if issue is specific to libgit2sharp.

**Comment by botmtl** [comment]
when SCM_USE_LIBGIT2SHARP_REPOSITORY=0, the import works without issue.  when I remove that variable I get an import failure with the following error message: Invalid reference name 'refs/tags/schema_upgrade_passed_(1.1_->_1.1.1)'.

I imported https://github.com/botmtl/tt-rss-import/ for both tests.  That repository has a tag containing a ">" character in its tag history.  (https://github.com/botmtl/tt-rss-import/releases/tag/schema_upgrade_passed_(1.1_->_1.1.1))

Deleting the offending tag (although not easy in itself) and trying the import again works.

**Comment by davidebbo** [comment]
Great, so this establishes that this is very likely a libgit2sharp issue (https://github.com/libgit2/libgit2sharp), and not a Kudu issue. You can stay with the flag to work around, as it shouldn't break anything. Basically, it launches git .exe instead of using a library.

**Comment by botmtl** [comment]
Thanks.  Closing.
