### ISSUE TITLE
Missing Reference Assemblies for Portable Class Library

### ISSUE THREAD

**Issue by murrayLuke** [projectkudu/kudu#2488]
> For deployment issues, please provide us with the following information:
> ---------------------------------------------------------------

### Repro steps.
> Steps to reproduce. Create a new Web Api project. Add a reference to a portable class library targeting .NET Framework 4.6 and Windows Universal 10.0
> using msbuild version '14.0' from 'D:\Program Files (x86)\MSBuild\14.0\bin\amd64'.

### Project structures.
> I don't have a project structure yet, if this isn't easily solvable which I suspect it might be I will create one for you.

### The log/error given by the failure.

Command: "D:\home\site\deployments\tools\deploy.cmd"
Handling .NET Web Application deployment.
MSBuild auto-detection: using msbuild version '14.0' from 'D:\Program Files (x86)\MSBuild\14.0\bin\amd64'.
Restoring packages for D:\home\site\repository\MyWebApi\project.json...
Committing restore...
Writing lock file to disk. Path: D:\home\site\repository\MyWebApi\project.lock.json
Restore completed in 3.11 sec for D:\home\site\repository\MyWebApi\MyWebApi.csproj.

NuGet Config files used:
    C:\DWASFiles\Sites\#MyApp\AppData\NuGet\NuGet.Config

Feeds used:
    https://api.nuget.org/v3/index.json
D:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1097,5): warning MSB3644: The reference assemblies for framework ".NETPortable,Version=v5.0" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend. [D:\home\site\repository\MyPortableClassLibrary\MyPortableClassLibrary.csproj]
Properties\AssemblyInfo.cs(9,12): error CS0246: The type or namespace name 'AssemblyTitle' could not be found (are you missing a using directive or an assembly reference?) [D:\home\site\repository\MyPortableClassLibrary\MyPortableClassLibrary.csproj]
Properties\AssemblyInfo.cs(10,12): error CS0246: The type or namespace name 'AssemblyDescription' could not be found (are you missing a using directive or an assembly reference?) [D:\home\site\repository\MyPortableClassLibrary\MyPortableClassLibrary.csproj]
Properties\AssemblyInfo.cs(11,12): error CS0246: The type or namespace name 'AssemblyConfiguration' could not be found (are you missing a using directive or an assembly reference?) [D:\home\site\repository\MyPortableClassLibrary\MyPortableClassLibrary.csproj]

### Debug your Azure website remotely.
> Because I have a work around, I am not maintaining a copy with the bug in place. Work around described below in other details.

### Mention any other details that might be useful.
> From what I can tell it seems like the computer building the project doesn't have all the portable class library SDK's installed. Since I am only using a portable class library to share c# code between my server and my front end I was able to remove the reference by copying all the files from the portable class library directly into my Web API project. Once the reference was removed the project builds and runs fine. Is there any way to use a portable class library through KUDU?

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by davidebbo** [comment]
@murrayLuke the best way to report this type of issues is to provider a minimal repo that demonstrates it. See https://github.com/projectkudu/kudu/wiki/Using-a-git-repo-to-report-an-issue

**Comment by murrayLuke** [comment]
since i haven't provided a repo i'm closing this.
