### ISSUE TITLE
ERROR_INSUFFICIENT_ACCESS_TO_SITE_FOLDER when deploying from VSTS

### ISSUE THREAD

**Issue by henningst** [projectkudu/kudu#2490]
I have a few Azure Web Apps that I'm deploying using VSTS Release. Recently the deployments have started failing more often and it seems to be caused by locked files. I'm seing the error message ERROR_INSUFFICIENT_ACCESS_TO_SITE_FOLDER even if we have set up the deployment step with "Take App Offline" and "Rename Locked Files". Usually it works fine to just trigger the deployment again without any changes, but it feels a bit unreliable.

In VSTS we have a release task using the build-in "Azure App Service Deploy" task.

The log output states this version:
`Update Azure App Service using Web Deploy / Kudu REST` `Version 3.3.8`

We are deploying to a staging slot and using a VSTS release task to swap the slots after a successful deployment.

## Log output 

Here is an example of a full log output:
```
2017-06-20T15:32:40.0227259Z Info: Deleting file (my-webapp-name\Microsoft.AspNetCore.DataProtection.Redis.dll).
2017-06-20T15:32:46.8495762Z Info: Deleting file (my-webapp-name\StackExchange.Redis.StrongName.dll).
2017-06-20T15:32:47.7445775Z ##[error]Failed to deploy web package to App Service.
2017-06-20T15:32:47.7445775Z ##[warning]Try to deploy app service again with Take application offline option selected.
2017-06-20T15:32:47.7455776Z ##[error]Error Code: ERROR_INSUFFICIENT_ACCESS_TO_SITE_FOLDER
More Information: Unable to perform the operation ("Delete File")  for the specified directory ("D:\home\site\wwwroot\StackExchange.Redis.StrongName.dll"). This can occur if the server administrator has not authorized this operation for the user credentials you are using.  Learn more at: http://go.microsoft.com/fwlink/?LinkId=221672#ERROR_INSUFFICIENT_ACCESS_TO_SITE_FOLDER.
Error: The error code was 0x80070005.
Error: Access to the path 'D:\home\site\wwwroot\StackExchange.Redis.StrongName.dll' is denied.
   at Microsoft.Web.Deployment.NativeMethods.RaiseIOExceptionFromErrorCode(Win32ErrorCode errorCode, String maybeFullPath)
   at Microsoft.Web.Deployment.FileEx.Delete(String path)
   at Microsoft.Web.Deployment.FilePathProviderBase.Delete(Boolean whatIf)
Error count: 1.
```

It looks like it is trying to delete 2 dlls, which is correct because they are removed from the app and I have selected "Remove additional files at destination". 

## VSTS Deployment task Config
Here is what the config looks like in VSTS:

![image](https://user-images.githubusercontent.com/369413/27355346-ff13a5ee-560a-11e7-9f54-260e0c6c2508.png)

Can I do anything to prevent this from happening?

**Comment by davidebbo** [comment]
In this scenario, VSTS uses msdeploy (aka WebDeploy) and not Kudu to do the deployment. The best place to report the issue would be the VSTS forum: https://social.msdn.microsoft.com/Forums/vstudio/en-US/home?forum=TFService.

**Comment by davidebbo** [comment]
To isolate, you should try manually deleting the file in Kudu Console, to see if it's indeed locked (after seeing the error).
