### ISSUE TITLE
WebJobs have stopped being built and included in deployment

### ISSUE THREAD

**Issue by davidsidlinger** [projectkudu/kudu#2495]
We have been successfully using Kudu to build and deploy our site for quite some time. We're using a custom deploy script, which is based on the one generated by Kudu. The only modifications to the script were additions to package up some stuff with `gulp`.

Today, I needed to reconfigure GitHub-based deployment because our repository was renamed. In both slots (production and CI), the build succeeded with the same source, but the continuous WebJobs — there are six — are not being included in the build or deployed bits. It has been a couple months since a build was triggered. Because I had to reconfigure our deployment, I lost deployment history and can't roll back.

I checked the `Microsoft.Web.WebJobs.Publish` to see if there had been any updates and found none.

This is a .NET 4.6 Web API application. We are using `webjobs-list.json` in the `Properties` directory of the source to include our jobs. I've been using Visual Studio 2015 to develop locally.

Please let me know what other information would be helpful.

Thanks!

**Comment by davidebbo** [comment]
Suggestion is top try building locally using the same steps as what's in your script. This will help isolate whether the issue is Azure/Kudu related, or pure msbuild.

**Comment by davidsidlinger** [comment]
@davidebbo I ran our `deploy.cmd` locally and the jobs are not included. I absolutely do not understand. This is literally the same code that was last deployed in the first week of May with no problems. Nothing has changed. The only warning I see is coming from one of our class library projects:

```
C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1820,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "Microsoft.WindowsAzure.ServiceRuntime, Version=2.7.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors. [C:\Users\David Sidlinger\Documents\GitHub\ci-segmentation\SSB.Segmentation.API\SSB.Segmentation.API.csproj]
```

I don't _think_ that's the source of my problems. It's an unneeded reference, and I don't have it because I just set up a fresh development machine. I am happy to share any other details that you'd need.

**Comment by davidsidlinger** [comment]
The web project has the following line in `packages.config`:

`<package id="Microsoft.Web.WebJobs.Publish" version="1.0.13" targetFramework="net452" />`

The content of `Properties\webjobs-list.json` is:

```JSON
{
  "$schema": "http://schemastore.org/schemas/json/webjobs-list.json",
  "WebJobs": [
    {
      "filePath": "../SSB.Segmentation.ETL.TransformPageWorker/SSB.Segmentation.ETL.TransformPageWorker.csproj"
    },
    {
      "filePath": "../SSB.Segmentation.ETL.UploadDocumentWorker/SSB.Segmentation.ETL.UploadDocumentWorker.csproj"
    },
    {
      "filePath": "../SSB.Segmentation.ETL.UploadFinalizeWorker/SSB.Segmentation.ETL.UploadFinalizeWorker.csproj"
    },
    {
      "filePath": "../SSB.Segmentation.ETL.Datasets/SSB.Segmentation.ETL.Datasets.csproj"
    },
    {
      "filePath": "../SSB.Segmentation.CampaignProcessing/SSB.Segmentation.CampaignProcessing.csproj"
    },
    {
      "filePath": "../Maintenance/Maintenance.csproj"
    }
  ]
}
```

**Comment by davidsidlinger** [comment]
`nuget restore Segmentation.sln` isn't complaining about not being able to grab anything.

**Comment by davidebbo** [comment]
What happens if you do a Publish to File System from VS? Do the WebJobs get produced? I just tried with my test solution https://github.com/davidebbo-test/WebAppWithWebJobsVS, and it works fine.

**Comment by davidsidlinger** [comment]
The WebJobs do not get produced when publishing to the file system. What in the world is going on here? This code has not changed since 2017-04-26, when it produced the jobs just fine. Would it be better to take this to the WebJobs project?

**Comment by davidebbo** [comment]
@vijayrkn may have some ideas on how to investigate.

@davidsidlinger various things:

- as a test, if you try my test app and do a local Publish, do you get the WebJobs?
- in yours, have you tried updating the `Microsoft.Web.WebJobs.Publish` package to the latest?
- are you able to simplify your repo to a simpler one that you could share, per [this page](https://github.com/projectkudu/kudu/wiki/Using-a-git-repo-to-report-an-issue)?

**Comment by davidsidlinger** [comment]
* I will clone and test.
* I am at `1.0.13` of `Microsoft.Web.WebJobs.Publish`, which appears to be the latest.
* I will work on this. Or just create a new, simple one.

I didn't have the Azure SDK stuff installed and thought that might be the problem. Installed the latest from the PI, and it still isn't building the jobs.

**Comment by davidsidlinger** [comment]
@davidebbo Publishing your solution locally results in _two_ of your jobs being included, but not the scheduled job. I see no difference in how we're specifying the `webjobs-list.json` or our publish settings JSON in the jobs themselves. The only difference I've spotted so far is your solution is on `1.0.7` of the WebJobs publication package. I am going to try upgrading it and see if I get the same behavior.

**Comment by vijayrkn** [comment]
Here is a sample WebJobs project which uses 1.0.13 version https://github.com/vijayrkn/ASPNetPublishSamples/blob/master/WebJobFullFramework/WebJobFullFramework.csproj#L54

Can you try running this command in verbose mode on your project and provide the output?
https://github.com/vijayrkn/ASPNetPublishSamples/blob/master/Publish.cmd#L68

**Comment by vijayrkn** [comment]
@davidsidlinger - Are you trying to publish the WebApp (with WebJob) or just the WebJob project itself?

**Comment by davidsidlinger** [comment]
@vijayrkn The WebApp with jobs.

**Comment by davidsidlinger** [comment]
I will try to run that publish command in my project as soon as possible.

**Comment by davidsidlinger** [comment]
@vijayrkn To be clear, what we're doing is Kudu builds from GitHub. Both locally and within the App Service, the jobs have inexplicably stopped being included in the publication output.

**Comment by vijayrkn** [comment]
ya, we just want to verify that building it locally works. Kudu uses a very similar command to build the project.

**Comment by davidsidlinger** [comment]
@vijayrkn Here is the output of running that command. The WebJobs were still not included in the build artifacts.
[buildout.txt](https://github.com/projectkudu/kudu/files/1110058/buildout.txt)

**Comment by vijayrkn** [comment]
I don't see the webjobs target getting executed. Can you please check if your webapp has this line in the csproj? 
https://github.com/vijayrkn/ASPNetPublishSamples/blob/master/WebAppWithWebJob/WebAppWithWebJob.csproj#L245

**Comment by davidsidlinger** [comment]
@vijayrkn You solved it. The `.csproj` didn't get updated when we upgraded packages. This was fine until I reconfigured deployment in the App Service, which blew away the repository on the instance and removed the "dead" reference to `1.0.12`.

`<Import Project="..\packages\Microsoft.Web.WebJobs.Publish.1.0.12\tools\webjobs.targets" Condition="Exists('..\packages\Microsoft.Web.WebJobs.Publish.1.0.12\tools\webjobs.targets')" />`

My everlasting gratitude.

**Comment by vijayrkn** [comment]
Glad I could help.

**Comment by davidebbo** [comment]
Ok, but that's the sign of a possible bug at some level if you had the correct line and it disappeared later. Do you understand the sequence of events that led to that? Or are you saying that it was a mistake on your side?

**Comment by davidsidlinger** [comment]
My guess is that the change to `packages.config` got committed without the update of the `.csproj` making it in. I _do_ think that future versions of the package should cause a MSBuild failure if the expected import is missing. I know that many other packages do this.

**Comment by xt0rted** [comment]
> I do think that future versions of the package should cause a MSBuild failure if the expected import is missing.

After just losing over an hour to asp.net mvc not serving up my new pages only to realize it was because I forgot the `Controller` suffix on my new controller...I'm definitely in favor of this change. Wasted time where the compiler could help is very frustrating.

**Comment by davidsidlinger** [comment]
@davidebbo @vijayrkn We have seven projects in the solution that reference that package. None of them were pointing to the correct version. This seems a little more likely to be a failure somewhere in the tooling than a human oversight.

**Comment by davidsidlinger** [comment]
But my problem is solved, and I am super grateful for your help.
