### ISSUE TITLE
wiki:rest api:code typo

### ISSUE THREAD

**Issue by pjmolina** [projectkudu/kudu#2496]
Hi.
In the wiki doc > REST API > last code example I found a small typo:

Line:
```
$apiUrl = "https://{sitename}.scm.azurewebsites.net/api/zip/site/wwwroot"
```
should be  (missing dollar and trailling slash):
```
$apiUrl = "https://${sitename}.scm.azurewebsites.net/api/zip/site/wwwroot/"
```

By the way, adding the same sample using `curl` here would be great too. 
Thanks!

**Comment by davidebbo** [comment]
I added the ending slash.

For the $, I think you're confusing the hostname with the optional basica auth username that can be passed in the URL. There is no $ in the hostname, so it is correct.

For a curl sample, if you have a working one, I can add it.

**Comment by pjmolina** [comment]
Yes, you are right, sorry. I though you wanted to use it as a PS variable.

**Comment by pjmolina** [comment]
An equivalent **curl** sample:
```
curl -X PUT -u {user}:{pass} --data-binary @{deployZipFile} https://{sitename}.scm.azurewebsites.net/api/zip/site/wwwroot/
```

**Comment by davidebbo** [comment]
Thanks I added the [sample](https://github.com/projectkudu/kudu/wiki/REST-API#sample-of-using-rest-api-with-curl). I left out the `:pass` part is it's not great practice. curl just prompts for it if it's not there (users can always choose to add that themselves).
