### ISSUE TITLE
VNET Integration from App Service Plan

### ISSUE THREAD

**Issue by ssatheeshkumar** [projectkudu/kudu#2497]
Hello,

I am trying to establish a P2S connection between an Azure Function running in app service plan and a VM in a VNET. I have implemented a simple function to create / read a file in one of the shared folder of the VM but unable to do so. Using a tcpping from the kudu resulted in error "An attempt was made to access a socket in a way forbidden by its access permissions ". Not sure what i am missing here. Any help is greately appreciated. 

Function info below :
2017-07-04T12:00:04.848 Function completed (Success, Id=bef785c0-e291-47e2-bfff-189b9ee7435b, Duration=3ms)

**Comment by davidebbo** [comment]
That does not sound related to Kudu. Please use https://github.com/Azure/Azure-Functions for Azure Functions issues.
