### ISSUE TITLE
Upload folder containing more than 100 files via KUDU will lost files

### ISSUE THREAD

**Issue by MSLuyi** [projectkudu/kudu#2501]
When uploading folder containing more than 100 files, only got 100 files copied. 
However, uploading the files directly into a folder, works fine.

**Comment by watashiSHUN** [comment]
if you [unzip](https://github.com/projectkudu/kudu/wiki/Kudu-console#upload-and-expand-zip-file) the folder, it works?

**Comment by MSLuyi** [comment]
Yes, this works. Thanks.

But if upload an unzipped file, it will only copy 100 files ?

**Comment by watashiSHUN** [comment]
for uploading a folder containing large amount of files, I'd suggest you submit a zip folder as it's a lot faster, I need to investigate about what happened in the regular folder case

**Comment by ahmelsayed** [comment]
looks like we're using [`readEntries`](https://github.com/projectkudu/kudu/blob/master/Kudu.Services.Web/Content/Scripts/FileBrowser.js#L838) incorrectly. it returns 100 files at a time and you need to keep calling it until you get an empty array for files.

**Comment by suwatch** [comment]
@ahmelsayed  so it is a bug which we can decide whether or not to fix it, correct?

**Comment by MSLuyi** [comment]
Seems there is also limitation uploading a zip file, it can only copy 299 files.

**Comment by MSLuyi** [comment]
Double verified from FileZilla, there are actually more than 299 files (actually 360 files) in the folder and it had been successfully uploaded, but the KUDU just displayed 299 files.

**Comment by davidebbo** [comment]
@MSLuyi that is unrelated to this issue. There is no limit for the number of files in a zip file, and what you're seeing is just the *display* limit, which is by design.

**Comment by MSLuyi** [comment]
@davidebbo Thanks for the confirmation. My bad for the confusion.

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
