### ISSUE TITLE
Preventing staging site restart during a swap

### ISSUE THREAD

**Issue by davenewza** [projectkudu/kudu#2503]
From how I understand it, the only reason a staging site would require restart is if there exists app settings or connection strings configured as [slot settings](https://docs.microsoft.com/en-us/azure/app-service-web/web-sites-staged-publishing#configuration-for-deployment-slots).

Although this doesn't always seem to be true. One of our applications will restart regardless. I have used Powershell cmdlets to be sure that there are no slot settings "hidden" from the Portal (because apparently this is a thing).

**What other factors can determine whether the staging site will be restarted during a swap?**

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
