### ISSUE TITLE
Process explorer should not filtered by users in Azure env

### ISSUE THREAD

**Issue by suwatch** [projectkudu/kudu#2505]
In  Azure env, the processes are already sandboxed and no need to filter by user name.   We need to relax [this line](https://github.com/projectkudu/kudu/blob/43248c0bd13200a33941f16354d9f063206862db/Kudu.Services/Diagnostics/ProcessController.cs#L114) for Azure.   The issue was discovered while doing warm up improvement development due to mismatch user name.

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
