### ISSUE TITLE
Application Insights Release Annotations

### ISSUE THREAD

**Issue by xt0rted** [projectkudu/kudu#2506]
Is there a process for creating application insights release annotations when kudu does a deploy? I found [this powershell script](https://github.com/Microsoft/ApplicationInsights-Home/blob/master/API/CreateReleaseAnnotation.ps1) for doing it, but I wasn't sure if the kudu deploy process had a build-in way of doing it.

**Comment by davidebbo** [comment]
Sorry for the slow response. Short answer is that there is no such feature in Kudu.

**Comment by xt0rted** [comment]
I've recently moved over to deploying from AppVeyor so one of my deploy steps is to call the powershell script.
