### ISSUE TITLE
Azure Websites TypeScript 2.4

### ISSUE THREAD

**Issue by david-grogan** [projectkudu/kudu#2509]
I have a VS2015 project I'm deploying to an Azure Website which uses the latest TypeScript (v 2.4), the deployment fails with various TypeScript errors (e.g. use of the new String Enum type). 

Using the portal console I can see that the latest version installed in the VM is 2.2 (in "D:\Program Files (x86)\Microsoft SDKs\TypeScript"), when can I expect the latest version to be installed?

Thanks,
David Grogan

**Comment by david-grogan** [comment]
btw, as a temporary workaround, for anyone else who has the same problem, I have disabled TypeScript compilation (see here https://github.com/Microsoft/TypeScript/issues/2294 - insert '<TypeScriptCompileBlocked>true</TypeScriptCompileBlocked>' into your .csproj - I just did this for the Release build, so my Debug build still compiles the .ts files) and then manually uploaded all the compiled .js files from my local machine over FTP.

**Comment by david-grogan** [comment]
This is still not working, is there any time frame on updating the build environment with the latest version?

**Comment by davidebbo** [comment]
Looks like 2.5 just got announced, so we may as well jump straight to that.

https://blogs.msdn.microsoft.com/typescript/2017/08/31/announcing-typescript-2-5/

**Comment by davidebbo** [comment]
@david-grogan I'm curious: if your app targets 2.4 and we install 2.5, will it auto roll forward to it, or do you need to explicitly change your project to target 2.5?

**Comment by david-grogan** [comment]
I don't know, but I'll try it out, and convert my project to 2.5 if needed.

**Comment by davidebbo** [comment]
@david-grogan 2.5 is now deployed in the "West US 2" region (not to be confused with West US!). Would you be able to give it a try there and let us know? i.e.

1. Try as-is first targeting 2.4. Does that fail or auto-move to 2.5?
2. Change it to target 2.5. That should definitely work.

If all is well, it will then make its way to the rest of the world over the next 4 or 5 days.

**Comment by david-grogan** [comment]
I'm running in North Europe and a bit busy to set up a new resource to test it, so will wait for a few days before trying it.

**Comment by david-grogan** [comment]
2.5 worked fine targeting 2.4. 

Everything good now.

**Comment by davidebbo** [comment]
Awesome, thanks for following up!
