### ISSUE TITLE
Getting 502.3 after swapping ASP.NET Core 1.1 application in Web App

### ISSUE THREAD

**Issue by gbellmann** [projectkudu/kudu#2510]
Hi guys,

We are trying to update a production Web API built with .NET framework 4.5 to a netcore1.1 app.
The new app works without any problems in the staging slot, but starts returning 502.3 (with the message: "The specified CGI application encountered an error and the server terminated the process.") as soon as the swap to production is finished.

Also get the following:

<h4>Detailed Error Information:</h4>
<table border="0" cellpadding="0" cellspacing="0"> 
<tr class="alt"><th>Module</th><td>&nbsp;&nbsp;&nbsp;AspNetCoreModule</td></tr> 
<tr><th>Notification</th><td>&nbsp;&nbsp;&nbsp;ExecuteRequestHandler</td></tr> 
<tr class="alt"><th>Handler</th><td>&nbsp;&nbsp;&nbsp;aspNetCore</td></tr> 
<tr><th>Error Code</th><td>&nbsp;&nbsp;&nbsp;0x80072efd</td></tr>
</table>

**Comment by watashiSHUN** [comment]
Can you share your Web App name, directly or [indirectly](https://github.com/projectkudu/kudu/wiki/Reporting-your-site-name-without-posting-it-publicly) so I can take a look, based on your description the deployment was successful until you swapped, are now you are seeing 502.3 in **prod**?

**Comment by gbellmann** [comment]
We swapped back to the old deployment, so there are no more 502s in prod.
The site is in the same App Service plan as `dummy2510` (it's the one with the same name as the App Service plan)
