### ISSUE TITLE
Kudu extension installation timeout

### ISSUE THREAD

**Issue by ahmelsayed** [projectkudu/kudu#2513]
_From @thdeltei on August 2, 2017 10:25_

In all browsers, sometimes installing an extension timeout and fails. Is there a time limit in the installation of an extension? How is the timeout triggered? Should the installation process spits out logs in order to let kudu know that the installation is still underway?

The extension concerned is:
http://www.siteextensions.net/packages/R-3.3.3x64/

_Copied from original issue: Azure/azure-functions-ux#1621_

**Comment by thdeltei** [comment]
I found in the code this parameter `DefaultCommandIdleTimeout`
Which makes me think that if the extension installation script is not logging anything out, it is considered timing out for kudu? Is that correct?

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
