### ISSUE TITLE
Interacting with blob storage during deployment

### ISSUE THREAD

**Issue by xt0rted** [projectkudu/kudu#2516]
As part of my deploy process I would like to push some files into blob storage before copying the site over. Are there command line tools pre-installed that'd let me do this?

**Comment by davidebbo** [comment]
I think the typical tool to do this is [AzCopy](https://docs.microsoft.com/en-us/azure/storage/storage-use-azcopy), but it's not preinstalled on the worker.

You'll need to just copy it into your site files. `D:\home\site\deployments\tools` is a good choice to put it in as it's on the path.

**Comment by xt0rted** [comment]
Thanks, I'll give that a try and see how it works.
