### ISSUE TITLE
Cannot Deploy from Github Repository - ASP.NET CORE

### ISSUE THREAD

**Issue by jakubsvobodacz** [projectkudu/kudu#2519]
> For deployment issues, please provide us with the following information:
> ---------------------------------------------------------------

### Repro steps.
My project built successfully on your dev machine but failed on Azure? **Yes**
Msbuild 14.0.23107.0 is located in my `MSBuild/14.0/bin` folder and in my csproj I have: `<DotNetCliToolReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Tools" Version="1.0.0" />`

### Project structures.
 .NET CORE 1.1. Web Application

### The log/error given by the failure.

```
Command: "D:\home\site\deployments\tools\deploy.cmd"
Handling ASP.NET Core Web Application deployment.
D:\home\site\repository\Basic.Database\Basic.Database.sqlproj(57,3): error MSB4019: The imported project "D:\Program Files (x86)\dotnet\sdk\2.0.0-preview2-006497\Microsoft\VisualStudio\v11.0\SSDT\Microsoft.Data.Tools.Schema.SqlTasks.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
  Restoring packages for D:\home\site\repository\Basic\Basic.csproj...
D:\home\site\repository\Basic\Basic.csproj : error NU1605: Detected package downgrade: Microsoft.EntityFrameworkCore.Design from 1.1.2 to 1.1.1. Reference the package directly from the project to select a different version.  [D:\home\site\repository\Basic.sln]
D:\home\site\repository\Basic\Basic.csproj : error NU1605:  Basic (>= 1.0.0) -> Microsoft.EntityFrameworkCore.Tools (>= 1.1.1) -> Microsoft.EntityFrameworkCore.Design (>= 1.1.2)  [D:\home\site\repository\Basic.sln]
D:\home\site\repository\Basic\Basic.csproj : error NU1605:  Basic (>= 1.0.0) -> Microsoft.EntityFrameworkCore.Design (>= 1.1.1) [D:\home\site\repository\Basic.sln]
  Restore failed in 11.5 sec for D:\home\site\repository\Basic\Basic.csproj.
  Restore completed in 691.67 ms for D:\home\site\repository\Basic\Basic.csproj.
Failed exitCode=1, command=dotnet restore "D:\home\site\repository\Basic.sln"
An error has occurred during web site deployment.
\r\nD:\Program Files (x86)\SiteExtensions\Kudu\63.60712.2926\bin\Scripts\starter.cmd "D:\home\site\deployments\tools\deploy.cmd"
```

### Debug your Azure website remotely.
My webappname - indirectly - http://dummygithubissue.azurewebsites.net

### Mention any other details that might be useful.
I do not know any :)
> Thanks! We'll be in touch soon.

**Comment by davidebbo** [comment]
Do you know what version of the SDK you are using on your machine? e.g. run `dotnet --version`.

Also, does your project have a global.json?

**Comment by jakubsvobodacz** [comment]
Hi David,

my Dotnet version is 1.0.3.

I searched for _global.json_ in my project but have not found any file.

**Comment by jakubsvobodacz** [comment]
If I have some additional file on my github repo that is not part of the solution files, does that make a difference? it is just simple json file where I store example of api fetch.

**Comment by jakubsvobodacz** [comment]
Just for the sake of being sure that the problem is not outside this particular solution, I tried to deploy from my github a basic, newly created .net core app without any of the _Microsoft.EntityFrameworkCore_ packages. The deployment was then ok. I might try to do that with the packages that are mentioned in the error log

**Comment by davidebbo** [comment]
What dotnet **runtime** you use is different from what SDK is used to build. Go to the root of your app and run `dotnet --version`.

To test that there is nothing wrong with your gitignore, just make sure it builds locally for you on a clean clone.

**Comment by jakubsvobodacz** [comment]
It is the same result **1.0.3** . 

I tried to check it also for other solution's root (which I push to github repo and subsequently deploy to azure with no problem ). and it is the same 1.0.3

**Comment by davidebbo** [comment]
Can you tried adding a global.json at the root pointing to the SDK version you want to use, in the case 1.0.3? See [here](https://github.com/davidebbo-test/AspNetCore11/blob/master/global.json) for example.

To double check that it's effective, go to the Kudu console, under `d:\home\site\repository`, and run `dotnet --version`'. That's after pushing your change of course.

**Comment by jakubsvobodacz** [comment]
Ok, I will try to do that and post back. Thanks a lot for help.

I also tried to get it to github without git ignore and redeploy but same result.

**Comment by jakubsvobodacz** [comment]
Ok, this solved it. Now it is deployed successfully :). Thanks a lot for help!

Can you maybe briefly explain me why this happened: _What dotnet runtime you use is different from what SDK is used to build._ 

And how/where did you find that this is happening?

**Comment by davidebbo** [comment]
1.0.4 is actually what I meant, not 1.0.3.

Generally, without a global.json, it always uses the latest SDK on the machine, regardless of the runtime you're targeting. But what's strange is that I would have expected the 2.0 SDK to be able to build any 1.0 app. Would you be able to [share a simple repo](https://github.com/projectkudu/kudu/wiki/Using-a-git-repo-to-report-an-issue) that we could use to investigate further? Thanks!
