### ISSUE TITLE
No route registered for '/api/continuouswebjobs/WebJobsName/run'

### ISSUE THREAD

**Issue by vanman314** [projectkudu/kudu#2520]
https://stackoverflow.com/questions/45597709/no-route-registered-for-api-continuouswebjobs-webjobsname-run

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
