### ISSUE TITLE
KUDU_SELECT_NODE_VERSION_CMD should allow retrieving node.js version from a package.json anywhere in the repo

### ISSUE THREAD

**Issue by JWess** [projectkudu/kudu#2522]
There are cases where it might make sense not to have package.json at the root of a repo. I have a .NET project that must have the frontend code tucked several layers into the repo. I only use package.json to install frontend dependencies and frontend build tools. I would like to specify the node version using the `engines` property of package.json, but KUDU_SELECT_NODE_VERSION_CMD (selectnodeversion.js) only looks for a package.json at the repo root. It would be nice to be able to specify a specific package.json path as a parameter.

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
