### ISSUE TITLE
KUDU_SELECT_NODE_VERSION_CMD should not fire up node app

### ISSUE THREAD

**Issue by JWess** [projectkudu/kudu#2523]
I have a .NET MVC site. I only use node/npm to install frontend dependencies and frontend build tools. I would like to be able to use KUDU_SELECT_NODE_VERSION_CMD in my deploy.cmd to specify what version of node I want running some of these build processes and what version of NPM during npm installs. However,  KUDU_SELECT_NODE_VERSION_CMD (selectnodeversion.js) does more than just select a node version. It tries to actually start a node app as well. This functionality should not live in a file/function named "selectnodeversion". I would like to use selectnodeversion to select the node version, however, I do not want to attempt to start a node app in the process.

**Comment by xt0rted** [comment]
I've been using the app settings `WEBSITE_NODE_DEFAULT_VERSION` and `WEBSITE_NPM_DEFAULT_VERSION` to set which versions I want my build scripts to use. It's annoying that it doesn't live with your code (such as the engines settings in package.json) but it does let you change the versions at least.

**Comment by JWess** [comment]
Yep, I also ended up going that route, and I agree that it's annoying that it doesn't live with your code. Thanks for the feedback.

**Comment by ncapito** [comment]
@xt0rted  if you set those app settings is there a need to call  selectnodeversion ?

**Comment by xt0rted** [comment]
@ncapito I'm not sure, not long after I posted that comment I moved all of my deployment builds from Kudu to AppVeyor which was already doing PR builds. My sites are all asp.net and I have some node based functions but last I checked you can't change the node version for those.

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
