### ISSUE TITLE
IIS8.5 - Deployments fails with VS 2017 build tools(v15) installed but worked with VS2015 (v14)

### ISSUE THREAD

**Issue by michael-nee-mw** [projectkudu/kudu#2530]
> For deployment issues, please provide us with the following information:
> ---------------------------------------------------------------

Error:

The target "pipelinePreDeployCopyAllFilesToOneFolder" does not exist in the project.

Server is Windows 2012 R2 with IIS 8.5 installed
Initially had VS 2017 installed with MSBuild 15
Websites built using ASP.net 4.6.2

Kudu was working fine until the build process.  I was able to manually build using my own bat files from the repository folder to www folder.

I tried with different websites and still getting the same error when building.

Uninstalled VS 2017
Installed VS 2015 with MSBuild 14.

Websites not building fine after pushing to remote branch.

**Comment by davidebbo** [comment]
@vijayrkn, is pipelinePreDeployCopyAllFilesToOneFolder not supported on msbuild 15?

/cc @watashiSHUN

**Comment by vijayrkn** [comment]
These targets are part of WAP targets that ships along with VS (it should get installed when build components are selected during VS install). These are not shipped inside msbuild. 

It is supported with msbuild 15 but the targets needs to be available in the msbuild 15 folder similar to msbuild14 (either needs to be copied over or installed).

**Comment by davidebbo** [comment]
Ah, right. This is in fact the way it always was.

If you copy `%ProgramFiles(x86)%\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\VisualStudio\v15.0` from your VS machine to your server, that should fix it.

Note that this is not a Kudu issue. It's about getting msbuild working in general on that server.
