### ISSUE TITLE
Customizing deployments for node and python apps in the same folder

### ISSUE THREAD

**Issue by sowmitranalla** [projectkudu/kudu#2532]
Hi, 
This isn't really an issue but rather a potential update to the wiki (only a couple more points). I was required to configure a custom deploy with multiple project folders in the same GIT repo. The only documentation that's listed in the [wiki](https://github.com/projectkudu/kudu/wiki/Customizing-deployments#using-app-settings-instead-of-a-deployment-file) explains how to direct the app service to a C# project. I tested doing a custom deploy by:

- listing `PROJECT` and a project folder with NodeJS app and `COMMAND` to a `nodeapp/deploy.cmd` file that I modified.
- listing `PROJECT` and a project folder with a Python Flask app and `COMMAND` to a `pythonapp/deploy.cmd` file that I modified.

After setting up the app settings for the app service for both of them, the app service was stood up as needed.

### Project structure
```
app
└── nodejs app
    └── other folders...
    └── deploy.cmd
└── python app
    └── other folders...
    └── deploy.cmd```

**Comment by davidebbo** [comment]
`COMMAND` should be all you need. Once you set that, `PROJECT` should have no effect. Did you try that?

**Comment by sowmitranalla** [comment]
I did not, I had set both values and things worked as expected. I'll try just `COMMAND` and see what happens.
