### ISSUE TITLE
Drag-and-drop upload to Debug Console doesn't work from Edge

### ISSUE THREAD

**Issue by ggailey777** [projectkudu/kudu#2546]
1. In an **_Edge browser_**, open the Debug Console for a Function App, in this case: <https://glengastorageevents.scm.azurewebsites.net/DebugConsole>
2. Drag a site extension .zip file to the top of the console and drop it in the **Drag here to upload and unzip area**:
    ![Drag here to upload and unzip area](https://user-images.githubusercontent.com/1388263/30051798-2dc4e318-91d8-11e7-8048-2728a946accd.png)
**Expected results:** Knife spins and file upload % is shown, which completes with 100%. This is how it works on IE.
**Actual results:** Knife spins and nothing else happens. Percent is not shown and upload never succeeds.

**Comment by davidebbo** [comment]
Indeed, I reproed this. Not sure if it ever worked.

**Comment by nukec** [comment]
doesn't work for chrome nor firefox
