### ISSUE TITLE
Does funcpack exist in kudu for azure functions? 

### ISSUE THREAD

**Issue by tony-gutierrez** [projectkudu/kudu#2548]
I see documentation here
https://github.com/projectkudu/kudu/wiki/Configurable-settings
indicating that I can set SCM_USE_FUNCPACK=1

This doesn't appear to have any effect. There is nothing in my azure deploy.cmd file that has anything to do with funcpack. However I do see a deploy.cmd file floating around the web that is the same version as mine (1.0.15) and does have refs to funcpack.(https://codegists.com/snippet/batchfile/deploycmd_baio_batchfile)

This is all hella confusing (typical MS). Can we get some straight answers?

**Comment by watashiSHUN** [comment]
it seems like you have a "deploy.cmd" in your repository (with a ".deployment")
this will take precedence over the deployment script created by Kudu (which is displayed in your link)

funcpack is installed in Azure, if you want to stay with your own "deploy.cmd", you just need to do a quick edit: add a call to [`funcpack pack`](https://github.com/projectkudu/KuduScript/blob/master/lib/templates/deploy.batch.functionbasic.template#L29-L33)

`SCM_USE_FUNCPACK=1` only applies to the default "deploy.cmd"

**Comment by tony-gutierrez** [comment]
I'm using the default deployment command. It is version 1.0.15. Is there some azure config that is needed to make it use a newer version?

**Comment by davidebbo** [comment]
Copying from other issue:

Yes, funcpack does get run automatically on functions repo when that App Setting is set. e.g. try pushing https://github.com/davidebbo-test/FunctionAppWithBigNpm. If you have a repo for which it doesn't work, please [share a sample repo](https://github.com/projectkudu/kudu/wiki/Using-a-git-repo-to-report-an-issue). Thanks.

**Comment by tony-gutierrez** [comment]
As I replied on the other issue...saying it does run doesn't mean anything when its not in the default deploy.cmd. IT DOES NOT RUN. Can someone update the documentation with a reason why?

**Comment by tony-gutierrez** [comment]
You can use the kudu console to download your deploy.cmd for a given Azure function instance and examine it for any mention of funcpack.

**Comment by tony-gutierrez** [comment]
https://www.dropbox.com/s/rcxweotwo02r6gg/Screenshot%202017-09-06%2018.14.59.png?dl=0

**Comment by watashiSHUN** [comment]
You said that you are using the default "deploy.cmd", and it does not have SCM_USE_FUNCPACK. But I couldn't repo, can you show me what your "deploy.cmd" looks like? it is located at `D:\home\site\deployments\tools\deploy.cmd`

mine looks like this (from line 51)
```
::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
:: Deployment
:: ----------

echo Handling function App deployment.

if "%SCM_USE_FUNCPACK%" == "1" (
  call :DeployWithFuncPack
) else (
  call :DeployWithoutFuncPack
)

goto end
...
```

One possibility that I can think of is that you are deploying a functionApp created using Visual Studio...
which uses a different template, but I can't say for sure until I see your "deploy.cmd"

**Comment by davidebbo** [comment]
@tony-gutierrez the repo is absolutely relevant. Did you try with the one I pointed to above and verified that the script indeed has the funcpack logic? If so, please share a test repo on GitHub so we can figure out why it's not working for yours.

**Comment by tony-gutierrez** [comment]
@davidebbo What is the exact technical reason you think the repo is relevant? I have nothing in my host.cmd, and am not using a custom deploy script. I am deploying via git, without any use of visual studio. 

@watashiSHUN I have seen deploy.cmd files that look like yours, but the one that azure is assigning to my node functions app does not have those lines and is versioned 1.0.15. Here it is: https://pastebin.com/8EhUsNSy

**Comment by watashiSHUN** [comment]
once we have some information about the "deploy.cmd" it is a lot easier to identify the issue.
note that in your link, there's a line:

> echo Handling node.js deployment.

whereas mine says:

> echo Handling function App deployment.

`SCM_USE_FUNCPACK` is only available for function app template. Kudu inspect your repository to determine which deployment script to use, thus the following statement is not entirely true

> It is irrelevant which repo is used unless I misunderstand how the SCM_USE_FUNCPACK works.

 To be qualified as function deployment, you need
1. deploy to a function app (I assume that you already have this condition satisfied)
2. have a **"host.json"** in your root directory (possibliy this is where the issue is)

you can add a "host.json" with just `{}` (empty json) to your repository and verify the generated "deploy.cmd"

**Comment by davidebbo** [comment]
Let's hold off until we get a sample repo, otherwise there is too much guessing involved.

**Comment by tony-gutierrez** [comment]
I have an empty host.json {had a timeout override in there but took it out just in case), and I am deploying about 5 functions from one repo, to a function app. It detects the individual functions and sets them up fine, so not sure what the difference is between a function app and a function app written in node. This is probably the heart of the problem though, someone never implemented it for node function apps.

**Comment by davidebbo** [comment]
Yep, once we have the sample repo, we should be able to get to the bottom of it and isolate the difference.

**Comment by tony-gutierrez** [comment]
Edit: I do NOT have a host.json. It was being created for me after deployment and I was editing it through the portal. Adding one does indeed change the deploy.cmd (but with the same version #. SMH)

Thanks for your help, but this seems like a pretty serious oversight to not document that that kudu setting is only available in some bizarre function, but not node??, situation...that is controlled by the presence of file that is not mandatory! This is the third Azure bug I have rooted out in the last week of attempting to get decent speed out of Azure Funcs. It is somewhat disrespectful to make your customers do your testing for you.

**Comment by tony-gutierrez** [comment]
Don't forget the bug tag.

**Comment by tony-gutierrez** [comment]
@watashiSHUN Let me know if there is any documentation describing the differences in these two "templates". Node vs function app in node. Thanks.

**Comment by davidebbo** [comment]
@tony-gutierrez It should never be treated as Node, so that's a bug. Now tracked by #2551.
