### ISSUE TITLE
Missing header files when deploying node native modules

### ISSUE THREAD

**Issue by yufeih** [projectkudu/kudu#2549]
Cannot git deploy some native node modules

### Repro steps.
- Go to scm debug console
- Run `npm install webworker-threads` in wwwroot
- Install failed: "D:\local\UserProfile\.node-gyp\8.4.0\include\node\v8.h(21): fatal error C1083: Cannot open include file: 'memory': No such file or directory [D:\home\site\wwwroot\node_modules\webworker-threads\build\WebWorkerThreads.vcxproj]"

### Mention any other details that might be useful.
\<memory> is missing from `D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include`

**Comment by davidebbo** [comment]
What node/npm version are you trying this with? With 8.4.0 (npm 5.3.0), I'm seeing a different error.

```
gyp ERR! build error 
gyp ERR! stack Error: `msbuild` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (D:\Program Files (x86)\npm\5.3.0\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 6.2.9200
gyp ERR! command "D:\\Program Files (x86)\\nodejs\\8.4.0\\node.exe" "D:\\Program Files (x86)\\npm\\5.3.0\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\home\tmp\node_modules\webworker-threads
gyp ERR! node -v v8.4.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
```

**Comment by davidebbo** [comment]
I then tried with v6.11.2, and it appears to have succeeded. Can you try that? Just change your `WEBSITE_NODE_DEFAULT_VERSION` app setting to 6.11.2.

**Comment by yufeih** [comment]
You are right. Downgrading Node to 6.11.2 did work out. 👍

**Comment by davidebbo** [comment]
Great!
