### ISSUE TITLE
I just wanna upload a new version of my site...

### ISSUE THREAD

**Issue by leidegre** [projectkudu/kudu#2550]
I'm a bit confused as to why I would want to manage a copy of my repository on the production server.

There's no way for us to really run the build as part of the deployment process, the build has nasty dependencies and must be run locally but we'd like to track what commits get deployed and log them somewhere, is it possible to put information about a different git repo in the `site/deployments` directory?

How would you otherwise facilitate this? I really just want to deploy a zip file with the new version of site but then log that a deployment did occur with information about the git revision from our repo in VSTS.

I currently just view Kudu as a nice little RESTful API for managing content and running commands on the server...

**Comment by davidebbo** [comment]
Take a look at the deployment API: https://github.com/projectkudu/kudu/wiki/REST-API#deployment. It has a flavor to just 'Add a deployment status to history', which does what you're asking. In fact, we created this for VSTS so they can call that in scenarios where they do the build.

**Comment by leidegre** [comment]
@davidebbo Thank you for the link, I really appreciate you taking the time to answer.

I have so many questions I need answers to and I cannot find any technical in depth documentation to help me. 

...but what happens when I push a deployment through the API, does that trigger some other behavior? Can the ID be anything I want? I feel as if the only way to answer many of these questions is to experiment and read the Kudu source code which is a really tedious task. Not that I won't do it but I was expecting some guide to go with the APIs, on why they exist and to what end for example the VSTS team is using the APIs and how. Things that help me get moving faster.

Like the file system layout, the documentation doesn't reflect everything I currently see when browsing the server. I also have a ticket with Azure support because I'm seeing a file from a different app hosted on the same app service plan, I thought those things should have been isolated from each other. (this is probably an issue with Azure and not Kudu)

I'm also really curious about the motivations behind Kudu? Why was it created, why does it exist? Will it continue to exist? What problem was it that you wanted to solve?

From my point of view, I see Kudu having an appeal if you have a "simple" app with a "simple" deployment process but beyond that, I'm a bit confused. There doesn't seem to be a straight forward guide on how to just put some files on an app service through the API. I've rewritten some of the Kudu toolings to help with this.

Though the APIs and power tools for managing and troubleshooting the service are great, as soon as you figure out what knobs to turn on in the Azure portal.

**Comment by leidegre** [comment]
@davidebbo to give you an example

I have feeling a lot more is going on here than what's obvious from the API.

https://github.com/projectkudu/kudu/blob/2ea953e532d0a44afe291dc4b9e370df9fc51686/Kudu.Services/Deployment/DeploymentController.cs#L90

So if I HTTP PUT a deployment to this endpoint am I expected to have uploaded the actually files for deployment to some specific place for this to work? From where I'm standing all of this is undocumented and a complete black box.

**Comment by leidegre** [comment]
@davidebbo actually wait, I think I got it now.

https://github.com/projectkudu/kudu/blob/2ea953e532d0a44afe291dc4b9e370df9fc51686/Kudu.Services/Deployment/DeploymentController.cs#L108

Looks very much like nothing really happens if we hit this branch.

**Comment by davidebbo** [comment]
That's correct. In the 'Add a deployment status to history' scenario, the only thing it does is populate a history item. It is completely detached from the actual deployment of files. It is designed to let you do your own deployment by whatever technique, and then populate the history yourself for tracking purpose.

And yes, the docs could be better. I've added clarifications to the wiki.
