### ISSUE TITLE
Unable to locate iisnode installation directory with interceptor.js file

### ISSUE THREAD

**Issue by denimaaark** [projectkudu/kudu#2558]
Hello, 

i have problem with deploying asp.net core application, please help:

 10.9.2017. 11:59:59 Updating branch '0db50cdbe441ead511fdc3b2cfc8bf487d142bf1'.
 10.9.2017. 11:59:59 Updating submodules.
 10.9.2017. 11:59:59 Preparing deployment for commit id '0db50cdbe4'.
 10.9.2017. 12:00:00 Generating deployment script. Details
 10.9.2017. 12:00:00 Running deployment command... Details

Command: "C:\inetpub\apps\tools\site\deployments\tools\deploy.cmd"
Handling node.js deployment.
KuduSync.NET from: 'C:\inetpub\apps\tools\site\repository' to: 'C:\inetpub\apps\tools\site\wwwroot'
C:\inetpub\Kudu.Services.Web\bin\Scripts\selectNodeVersion.js:160
            throw new Error('Unable to locate iisnode installation directory with interceptor.js file');
            ^
Error: Unable to locate iisnode installation directory with interceptor.js file
    at Object.<anonymous> (C:\inetpub\Kudu.Services.Web\bin\Scripts\selectNodeVersion.js:160:19)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:504:3
An error has occurred during web site deployment.
C:\inetpub\Kudu.Services.Web\bin\Scripts\selectNodeVersion.js:160\r\n            throw new Error('Unable to locate iisnode installation directory with interceptor.js file');\r\n            ^\r\n\r\nError: Unable to locate iisnode installation directory with interceptor.js file\r\n    at Object.<anonymous> (C:\inetpub\Kudu.Services.Web\bin\Scripts\selectNodeVersion.js:160:19)\r\n    at Module._compile (module.js:570:32)\r\n    at Object.Module._extensions..js (module.js:579:10)\r\n    at Module.load (module.js:487:32)\r\n    at tryModuleLoad (module.js:446:12)\r\n    at Function.Module._load (module.js:438:3)\r\n    at Module.runMain (module.js:604:10)\r\n    at run (bootstrap_node.js:389:7)\r\n    at startup (bootstrap_node.js:149:9)\r\n    at bootstrap_node.js:504:3\r\nC:\inetpub\Kudu.Services.Web\bin\Scripts\starter.cmd "C:\inetpub\apps\tools\site\deployments\tools\deploy.cmd"

**Comment by denimaaark** [comment]
I have try to set
KUDU_SELECT_NODE_VERSION_CMD
to
v6.11.2 and 6.11.2

**Comment by davidebbo** [comment]
You need to install iisnode.
