### ISSUE TITLE
Unable to Start WebJob, Job failed due to exit code -1073740771

### ISSUE THREAD

**Issue by ericebarker** [projectkudu/kudu#2559]
> For deployment issues, please provide us with the following information:
> ---------------------------------------------------------------

### Repro steps.
> your project built successfully on your dev machine but failed on Azure? YES
> please write down your build tools and their versions (ie `Msbuild 15.1.0.0`)
VS2017 Ent 15.3, deployed via publish to .zip with portal upload, then delete and FTP deploy directly.
Attempted on VS2015  as well

WebJob Deploys, fails to start. Created multiple basic WebJob template-only versions with different .Net Framework versions, from VS2017 and 2015, set conn strings in config files directly and also let env vars set conn, cannot find any other differences in the solutions that I am uploading. At first I thought it was due to Net4.6.1, or possible 5.8.3 version of the MS dependencies (See trace log below), but it appears from looking through Issue history that this is not a problem anymore. I tested a dummy webjob version that does not access storage at all, deleting queue based trigger for [NoAutomatedTrigger] decorated class, but this did not change the issue. Storage is being accessed and used correctly with the same conn for AzureWebJobsStorage and AzureWebJobsDashboard for LetsEncrypt WebJob that is running fine. I am finding no other differences, and every new webjob project I create all have the same 'failure to start' problem in Azure so I expect it may be settings there... but the LetsEncrypt WJ is running okay. Googling the KUDU exit code did not return any results (exit code -1073740771). Checking the Kudu solution here on github for where it is breaking down did not reveal anything obvious to me (BaseJobRunner.cs:201).

I am very grateful for any help, thank you in advance!

### Project structures.
> in order to reproduce your issue at our end we need a simple 
> https://github.com/ericebarker/WebJobsTest2 is a blank start up C# Azure WebJob template that fails to start. Only modification was to add NuGet pkg WebJobs.Extensions and Update All Packages.
### The log/error given by the failure.
Kudu web based log:
[09/14/2017 01:45:34 > 5702de: SYS INFO] Run script 'setup.exe' with script host - 'WindowsScriptHost'
[09/14/2017 01:45:34 > 5702de: SYS INFO] Status changed to Running
[09/14/2017 01:45:34 > 5702de: SYS ERR ] Job failed due to exit code -1073740771
[09/14/2017 01:45:34 > 5702de: SYS INFO] Process went down, waiting for 60 seconds
[09/14/2017 01:45:34 > 5702de: SYS INFO] Status changed to PendingRestart

From Trace Dump:
```
<step title="Error occurred" date="2017-09-12T03:34:37.032" instance="5702de" type="error" text="CacheJobBinaries() at C:\Kudu Files\Private\src\master\Kudu.Core\Jobs\BaseJobRunner.cs:201: Access to the path &apos;D:\home\site\wwwroot\App_Data\jobs\continuous\ATB\publish\Application Files\##Actual WebJob Dir, not webjobtest in github##\it\Microsoft.Data.Services.Client.resources.dll.deploy&apos; is denied." stackTrace="   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at System.IO.File.Copy(String sourceFileName, String destFileName, Boolean overwrite)
   at System.IO.Abstractions.FileWrapper.Copy(String sourceFileName, String destFileName, Boolean overwrite)
   at Kudu.Core.Infrastructure.FileSystemHelpers.CopyDirectoryRecursive(String sourceDirPath, String destinationDirPath, Boolean overwrite)
   at Kudu.Core.Infrastructure.FileSystemHelpers.CopyDirectoryRecursive(String sourceDirPath, String destinationDirPath, Boolean overwrite)
   at Kudu.Core.Infrastructure.FileSystemHelpers.CopyDirectoryRecursive(String sourceDirPath, String destinationDirPath, Boolean overwrite)
   at Kudu.Core.Infrastructure.FileSystemHelpers.CopyDirectoryRecursive(String sourceDirPath, String destinationDirPath, Boolean overwrite)
   at Kudu.Core.Infrastructure.FileSystemHelpers.CopyDirectoryRecursive(String sourceDirPath, String destinationDirPath, Boolean overwrite)
   at Kudu.Core.Jobs.BaseJobRunner.&lt;&gt;c__DisplayClass49_0.&lt;CacheJobBinaries&gt;b__0()
   at Kudu.Core.Infrastructure.OperationManager.&lt;&gt;c__DisplayClass2_0.&lt;Attempt&gt;b__0()
   at Kudu.Core.Infrastructure.OperationManager.Attempt[T](Func`1 action, Int32 retries, Int32 delayBeforeRetry, Func`2 shouldRetry)
   at Kudu.Core.Infrastructure.OperationManager.Attempt(Action action, Int32 retries, Int32 delayBeforeRetry)
   at Kudu.Core.Jobs.BaseJobRunner.CacheJobBinaries(JobBase job, IJobLogger logger)" >
  <step title="Cleanup Xml Logs" date="2017-09-12T03:34:37.032" >
    <step title="Cleanup Infos" date="2017-09-12T03:34:37.047" totalFiles="200" totalCleanup="40" /><!-- duration: 1216ms -->
  </step><!-- duration: 1247ms -->
</step><!-- duration: 1247ms -->

```

### Debug your Azure website remotely.
> it is recommanded that you share your Web App name, directly or [indirectly](https://github.com/projectkudu/kudu/wiki/Reporting-your-site-name-without-posting-it-publicly)
> we can take a look at what's going on.

### Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by davidebbo** [comment]
Does your WebJobs exe work if you run it directly from Kudu? See [this page](https://github.com/projectkudu/kudu/wiki/Isolating-WebJobs-and-Deployment-script-issues) for info on isolating this type of issues.

**Comment by ericebarker** [comment]
I can start it from the console, using CMD and PS. It behaves the same as the initial run when I uploaded it, and fails with the same exit code. This is both with my initial WebJob and with the empty project WebJobsTest webjob. Both return the exit code -1073740771, same as before.

It does attempt to restart every 60 seconds, so I'm not sure that it's the environment. It appears to be failing before Main() is run.
![webjobsetup](https://user-images.githubusercontent.com/11916765/30454769-77070610-996b-11e7-8c9c-23ff3e29ff3e.PNG)

[09/14/2017 20:33:27 > 5702de: SYS INFO] Run script 'setup.exe' with script host - 'WindowsScriptHost'
[09/14/2017 20:33:27 > 5702de: SYS INFO] Status changed to Running
[09/14/2017 20:33:27 > 5702de: SYS ERR ] Job failed due to exit code -1073740771
[09/14/2017 20:33:27 > 5702de: SYS INFO] Process went down, waiting for 60 seconds
[09/14/2017 20:33:27 > 5702de: SYS INFO] Status changed to PendingRestart

Thanks for taking the time look into this!

**Comment by davidebbo** [comment]
Good so at least we have WebJobs completely out of the equation.

And do you mean that even if you run a no-op console app from Kudu console it is failing in that way?

Can you share your web app name, either directly or [indirectly](https://github.com/projectkudu/kudu/wiki/Reporting-your-site-name-without-posting-it-publicly)? This will help us investigate. Thanks!

**Comment by ericebarker** [comment]
The two webjobs are AzureTwitterBot and WebJobsTest2, both are deployed as part of http://ericbarker.azurewebsites.net/ resource. WebJobsTest2 was the dummy one that is just the VS2017 template, so I could put a public repo up for you and also show that the empty template (plus NuGet updates) is also failing.

**Comment by davidebbo** [comment]
I was not able to repro this on your site from Kudu console:

```
D:\home\site\wwwroot\App_Data\jobs\continuous\WebJobTest2>setup.exe

D:\home\site\wwwroot\App_Data\jobs\continuous\WebJobTest2>echo %errorlevel%
0
```

So it runs and terminates without errors (0 means success). Are you seeing something different if you try the same steps?

**Comment by davidebbo** [comment]
Though frankly, I'm not clear whether `setup.exe` is even the exe that you expect the WebJobs to run. That doesn't even seem to be a managed binary. I would have expected to see an exe named WebJobsTest2 in there.

**Comment by ericebarker** [comment]
I would have thought so too re:setup.exe vs {{AppName}}.exe. I have checked properties to verify my publish settings are all correct, which I believe they are. I Also see it returning a success when I set it to run in the Kudu console, but it is set to run continuously, which it doesn't. It also does not fire functions that are on a Timer Trigger or have the RunOnStartup = true Attribute param.

**Comment by davidebbo** [comment]
Something doesn't make sense here. This setup.exe must be coming form somewhere. If you try a plain new solution, with no sugar added, you you also get a setup.exe?

**Comment by davidebbo** [comment]
I did notice something suspicious. You [csproj](https://github.com/ericebarker/WebJobsTest2/blob/53c3b0ed3893cb2f21f1f7d2fd4e8cdfdc576729/WebJobTest/WebJobTest.csproj#L138-L142) is referring to using .NET fx 3.5, which is outdated. You need to target 4.x.

If that doesn't work, I'll need to try a clean repo, which includes the sln file and no committed binaries.

**Comment by ericebarker** [comment]
I think you are right, there is something corrupted in my project files when published. I will have to debug VS, as this is applied to all projects I try to publish to a web job. I was able to get AzureTwitterBot running by FTP'ing directly in and manually uploading the compiled Release version which included the AzureTwitterBot.exe executable. It appears that no matter the project properties settings, VS is publishing and deploying the Debug version. You have been a huge help, David. Thank you again. Specifically pointing out the csproj version pointer and the setup.exe being odd - that should have tipped me off earlier. I will post back if I find anything wonky in VS that is causing this Debug only publish profile.

**Comment by ishafqat** [comment]
I got the same error and then realised that I was trying to run the Webjob without using the artefacts produced by **dotnet publish** command. By doing so the error went away.
