### ISSUE TITLE
Feature request: zip file deployment

### ISSUE THREAD

**Issue by nickwalkmsft** [projectkudu/kudu#2562]
**Summary: support first-class deployment of zip files, with deployment status, history tracking, locking, deployment scripts, kudusync, etc.**

App Service integration with VSTS is continually improving and awareness and usage of all brands of CI/CD systems is growing. As a result, more App Service users are deploying already-built artifacts to App Service, as opposed to deploying directly from source control and letting Kudu drive the build process.

MSDeploy is a purpose-built solution to this problem, but it is not cross platform, and it is not realistic to expect all customers of App Service (some of whom use very few Microsoft tools, or none at all) to be able to understand and use it. Doubly so with the introduction of App Service on Linux.

Zip files are easy to create, use and understand on any platform. They are the best way to move multiple files to App Service in most situations, especially with Kudu's zip API that automatically extracts the contents, so people often use them for these kinds of deployments. On Linux, this workflow is currently the only real option for such deployments.

Unfortunately, the zip API is purely a filesystem operation. It does not make use of a number of features that already exist in Kudu that are designed to make deployments safe and easy: history tracking, redeployment, locking semantics, running of deployment scripts (including smart file synchronization with kudusync), etc.

I propose we add support zip files as a first-class deployment source in order to better support deployments from external CI/CD/build systems, especially for App Service on Linux users.

Early thoughts on features:

- Support zip files as a "fetch" deployment provider - allow users to provide a URL to a zip file and deploy from it. Consider the need for auth against this URL as well.
- Support "push" deployment of zip files - be able to POST a zip file directly to an endpoint, similar to the existing zip API, but start a full deployment instead of just an extract operation. This could offer both synchronous and asynchronous modes, in the same way that the current fetch handler supports isAsync.
- Support redeployment from previously-specified zip files.
- Potentially support .tar.gz and/or other archive formats, especially on Linux.
- Consider a way to provide deployment metadata in the zip file or in the deployment request, such as with a well-known filename, to support filling in the deployment status and history.

Thoughts on implementation:
- Looking at the way that the OneDrive and Dropbox providers work within the deployment system should provide a good jumping-off point, not for their use of special APIs, but for the fact that they are simply collections of files and not source control management systems with branches, tags, commit IDs, etc.
- May need to consider revisions to the detection system that Kudu uses to determine what kind of scripts to create, or maybe a simpler/more discoverable way to indicate that Kudu should only do a "basic" deployment (kudusync copy only). Users should be able to deploy from source via zip files, and so detection and build script generation should still work properly, but it will likely be more common to use them to deploy already-built artifacts. The nature of Kudu's presence-based detection system makes it likely that it will detect the need for a build script even for already-built artifacts on most app stacks.
- The .NET zip APIs allow for manipulation and introspection of zip files in addition to simply extracting them. There is probably a lot of optimization that could be done relative to only extracting specific files, etc. There may be some special implementation needed if this is to be done in conjunction with kudusync.

**Comment by davidebbo** [comment]
Random thoughts:

- We should focus on the 'push' scenario first, which is easier to use. Also, msdeploy does already support the cloud hosted zip scenario even cross platform, so that part is sort of covered.
- Good point that maybe we don't want the whole deployment pipeline. Does it even make sense to support a custom deployment script if the zip is expected to contain everything that should go in wwwroot? Maybe not.
- The zip introspection could be most optimal, but probably a little hard to pull off. Maybe we shoudl start simple: unzip the whole thing in a local tmp folder, and KuduSync from that to wwwroot.
- It's hard to provide 'redeployment from previously-specified zip files' unless we store the historical zip files, or build a git repo on the fly to keep history (we do this from Dropbox I think). Probably simpler to not support that.

So high level, we kind of want the same as what msdeploy provides, but with plain zip.

**Comment by nickwalkmsft** [comment]
I am going to start prototyping this, starting with the push scenario, as you called out.

**Comment by nickwalkmsft** [comment]
Linking PR: https://github.com/projectkudu/kudu/pull/2570

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
