### ISSUE TITLE
Triggered Web Jobs may display a status of unknown if there is an underlying Storage issue. 

### ISSUE THREAD

**Issue by FinVamp1** [projectkudu/kudu#2565]
The main symptom is that following a storage issue the status file for triggered web jobs isn’t correct and then the WebJob will not run again until the status file is deleted.

E.G

{"EndTime":"2017-08-21T22:20:45.4996175Z"}

The status for this WebJob in the Portal and in the Dashboard will show as "Unknown" and the customer will not be able to execute the Triggered job again until they delete this file.

**Comment by davidebbo** [comment]
So you see the status file having just the end time and not any of the other fields? It's quite puzzling how that could happen.

**Comment by FinVamp1** [comment]
Yes, that's the main symptom and in at least two of the issues it coincided with a storage change on the backend.

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
