### ISSUE TITLE
Kudu console commands not being given CPU time

### ISSUE THREAD

**Issue by twschiller** [projectkudu/kudu#2566]
We're trying to run a Python/Django management command from the Kudu console (CMD). It looks like the process is being starved of CPU time. Is there some sort of throttling that the Kudu console performs? 

The process took 20 minutes to complete, with the final CPU time reported only being around 40 seconds. Here are the details for the w3wp.exe > cmd.exe > python.exe process that I captured a little over 10 minutes into the run

start time 2017-09-15T18:51:53.2442948Z
total cpu time 00:00:20.9062500
user cpu time 00:00:16.8125000
privileged cpu time 00:00:04.0937500
working set 177,864 KB
peak working set 177,884 KB
private memory 162,308 KB
virtual memory 315,092 KB
peak virtual memory 319,080 KB

The App Service plan displayed the CPU and RAM utilization at 0% the entire time

Environment:
- Instance Type: Isolated: 0 I1
- Python 3.6.1x64 extension
- Platform 64-bit

**Comment by davidebbo** [comment]
Are you on a dedicated App Service Plan? There should be no throttling happen in that case.

**Comment by davidebbo** [comment]
Actually, let's step back: are you run running this on Azure App Service or somewhere else? There is no such thing as "Isolated: 0 I1" on App Service.

**Comment by twschiller** [comment]
The application is running in an App Service Environment (ASE) on an I1 Isolated Instance. 

I will check with Azure support. Instance Count is showing as 0 with status showing as Provisioning even though I created it 2 days ago. The 0 in "Isolated: 0 I1" must be referring to the number of provisioned instanced

**Comment by davidebbo** [comment]
Oh I see, sorry, I didn't recognize that type :)

But yes, it seems to have issues that go beyond Kudu. There is no specific throttling enforced for processes launched by Kudu on this kind of instances.

Closing here, but happy to discuss further if anything on the Kudu side is suspected.
