### ISSUE TITLE
Azure Functions local git seems to initialize on the wrong folder

### ISSUE THREAD

**Issue by nelak** [projectkudu/kudu#2567]
### Repro steps.
Add an azure function deployment slot
Configure the deployment slot to use local git
The repository inits under /wwwroot instead of /repository
The issue is made visible when pushing to the local repository

### The log/error given by the failure.
![image](https://user-images.githubusercontent.com/254502/30546066-ee505052-9c61-11e7-804f-c09776fb2038.png)

**Comment by davidebbo** [comment]
So the first thing you did after creating the slot is push to it? i.e. you never did a clone operation first?

**Comment by davidebbo** [comment]
The issue is not related to slots, but is a side effect of doing a Clone before ever pushing anything. Can you try again on a clean slot without the Clone step?

**Comment by nelak** [comment]
Highly likely it's what you are mentioning.
Initially I was getting `! [remote rejected] master -> master (shallow update not allowed)` when pushing from CI, so I cloned.
I tried deleting and creating the slot again but the files were not deleted so I manually removed the .git folder from `site/wwwroot` and setup local git agai. Then I forced push and saw `! [remote rejected] master -> master (shallow update not allowed)` again, but this time I was able to see `site/repository/.git` instead of `site/wwwroot/.git` in kudu.
Not really certain on the cause of the initial issue, but this is working as it should now.
Thanks!

**Comment by davidebbo** [comment]
The likely reason you still saw the files is that they're stored in Azure Files in your storage account, and that was preserved when you deleted/recreated the site.

The behavior when doing a Clone is indeed a bit funky, and has not been well thought out in the Functions case. So it's best to just avoid it for now.

**Comment by nelak** [comment]
Excellent, good to know then.
I can live with this as it's the same setup I was using for my production environment.
I'll be testing the deployment slots in the next days, so I'll let you know if I find any other weird issues. Thanks a lot for the help 💯

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
