### ISSUE TITLE
zip-deploy not taking advantage of script caching

### ISSUE THREAD

**Issue by davidebbo** [projectkudu/kudu#2571]
We cache the script under `D:\home\site\deployments\tools`, as well as the command line that was used to produce it. Then if that doesn't change the next time, we just reuse it, which saves the time to run KuduScript and can shave a couple seconds.

But for zip-deploy, the cache key looks like `-y --no-dot-deployment -r "D:\local\Temp\vufgpk3q.tpn" -o "D:\home\site\deployments\tools" --basic --sitePath "D:\local\Temp\vufgpk3q.tpn"`, and the presence of random folders makes it 'unstable.' So each time it regenerates a new script.

I wonder if some level of use of env variable could help avoid this. It should make a measurable difference for tiny deployments. Right now, I see then take about 4 seconds in Azure (with trivial zip).

**Comment by nickwalkmsft** [comment]
Interesting. I think an easy fix for this would be to use an unchanging filename for the extraction target, which shouldn't be a problem. I'll look into this.

**Comment by nickwalkmsft** [comment]
Fixed in https://github.com/projectkudu/kudu/pull/2570/commits/f6ada04bbb6d651dc456d7e41f9b39d94a91984f

**Comment by davidebbo** [comment]
Verified! On second deployment:

    <step title="Generating deployment script" date="2017-09-28T17:12:14.995" >
        <step title="Using cached version of the deployment script for command: -y --no-dot-deployment -r &quot;D:\local\Temp\zipdeploy\extracted&quot; -o &quot;D:\home\site\deployments\tools&quot; --basic --sitePath &quot;D:\local\Temp\zipdeploy\extracted&quot;" date="2017-09-28T17:12:15.011" />
        
    </step>
