### ISSUE TITLE
Document zip-deploy API in wiki

### ISSUE THREAD

**Issue by davidebbo** [projectkudu/kudu#2572]
Just to make sure we don't forget. It should go in https://github.com/projectkudu/kudu/wiki/REST-API. Also, add any new SCM_ flags to https://github.com/projectkudu/kudu/wiki/Configurable-settings

**Comment by nickwalkmsft** [comment]
Done! Everything is marked (preview) for now.

- [Deploying from a zip file](https://github.com/projectkudu/kudu/wiki/Deploying-from-a-zip-file-(preview)), linked in the how-to guides section of the root.
- Updated [REST-API](https://github.com/projectkudu/kudu/wiki/REST-API): new section for Zip Deployment as well as a note in the Zip section.
- Updated [Configurable settings](https://github.com/projectkudu/kudu/wiki/Configurable-settings).
