### ISSUE TITLE
zip-deploy taking abnormally long to write zip file to disk

### ISSUE THREAD

**Issue by davidebbo** [projectkudu/kudu#2573]
My test zip file is 2,893 KB. If I copy it using vfs, it takes about 2 seconds. But in the context of zip-deploy, it takes over 6 seconds, e.g.

```
    <step title="ZipPushDeploy" date="2017-09-28T00:27:18.124" >
        <step title="Writing zip file to D:\local\Temp\bwbodqla.g25" date="2017-09-28T00:27:18.124" />
        <!-- duration: 6361ms -->
```

I wonder why there is such a difference.

Also, is there any benefit to writing the zip file first, vs directly unzipping it as we do in the zip controller?

**Comment by davidebbo** [comment]
Trying a 20MB zip file:

- vfs is 7 seconds
- zip-deploy 'Writing zip file' is 45 seconds

**Comment by nickwalkmsft** [comment]
Yikes, that's no good. All it's doing is `request.Content.CopyToAsync(filestream)`; I'm seeing <1s for a 32MB zip on my dev machine. What environment are you testing in? I'm not very familiar with what's under the hood for d:\local in a "realistic" environment; is it possible that the performance characteristics make it not a good use for this after all?

Regarding writing the zip file to disk - unzipping large files can take a long time, so for isAsync=true deployments it's important to wait to do the unzip async. Simply saving the zip file to disk for later processing was a simple implementation that fit most easily into the existing design. Now that other portions of the design are done I'm pretty sure this could be easily reworked to avoid the file write; I'll take a look at it tomorrow.

**Comment by davidebbo** [comment]
After more experimentation, there is some randomness here and it's likely not related to your code.
