### ISSUE TITLE
Kudu file viewer trims white space

### ISSUE THREAD

**Issue by UsmanMohammad** [projectkudu/kudu#2574]
> For deployment issues, please provide us with the following information:
> ---------------------------------------------------------------

### Repro steps.
> Create a file with space at the front of the file name
> Create a file with the same name but with no space
> Files will look identical, only way to discern difference is to use ls on the console.

### Mention any other details that might be useful.
> Ran into this as our applicationHost.xdt file had a space infront of its file name.
> Kudu's ui didn't show a space. I only realised the file had a space at the front because I created a file with the exact same name (with out the space at the front) and saw that both files existed.
> I then used ls in the prompt and saw that one of the files had a space.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by watashiSHUN** [comment]
it looks to be a html css thing, I can get the result by adding a css property `whites-pace: pre`
Although having spaces in file name is usually [not considered a good practice](https://superuser.com/questions/29111/what-technical-reasons-exist-for-not-using-space-characters-in-file-names), but since it is allowed, I guess we can make the change?
![image](https://user-images.githubusercontent.com/6531400/30983509-81f94680-a43f-11e7-9239-802197454351.png)

**Comment by davidebbo** [comment]
Using spaces is one thing, but using spaces at the beginning of the file name is another. The Windows shell doesn't even let you do that, as it auto-trims any heading/trailing spaces (even though NTFS does support it).

I don't think this is worth spending time on.

**Comment by UsmanMohammad** [comment]
Just want to clarify what happened ton us, It wasn't intentional, the file was created with the "+" button on the gui, and I had pasted the file name which also copied the space in front of the name. 

This caused issues with our applicationHost.xdt file in the site folder.

Our webconfig was using a server variable, however our site crashed when ever it was calling that variable as we didn't have "applicationHost.xdt", instead we had " applicationHost.xdt" and couldn't figure out the problem from the web ui,.

Ideally, the "+" button from the ui should remove prepended spaces when naming the file.

**Comment by davidebbo** [comment]
Ah yes, then the real issue is that the + UI should trim the white spaces around the file name, and not that the whitespace is not displayed. I would definitely be up for fixing that part, which presumably is a missing trim() call somewhere in the UI logic.

**Comment by xt0rted** [comment]
I've run into the same issue in the azure portal when setting up app settings. So much wasted time 😞
