### ISSUE TITLE
Clarify the format for the 'project' app setting when a solution has multiple projects

### ISSUE THREAD

**Issue by martinkearn** [projectkudu/kudu#2575]
In relation to the following documentation: https://github.com/projectkudu/kudu/wiki/Customizing-deployments#deploying-a-specific-aspnet-or-aspnet-core-project-file

It is not clear what the value of 'project' should be when deploying from GitHub? ... should this be the full GitHub path to the proj file? i.e.

https://github.com/someuser/somerepo/blob/master/solutionfolder/projectfolder/project.csproj

Please add an example.

**Comment by davidebbo** [comment]
There are examples in there already, e.g. `project = WebProject/WebProject.csproj`. Also, it says

> You can specify the path to the project file, relative to the root of your repo

Not sure there is much more to say about it. Does that make sense?
