### ISSUE TITLE
Updating links on WebJobs wiki page

### ISSUE THREAD

**Issue by veleek** [projectkudu/kudu#2579]
A bunch of the links on the WebJobs page on the wiki are broken (specifically the ones that point to the settings.job section).  I've fixed those in a fork of the wiki here: https://github.com/veleek/kudu.wiki.git

Is there a better way to contribute to the wiki?  This process seems arduous.

**Comment by davidebbo** [comment]
@veleek well, blame GitHub for that one! No idea why they don't support a a PR workflow for wikis :(

**Comment by davidebbo** [comment]
Merged, thanks for the edits!
