### ISSUE TITLE
How do site extensions get handled during an auto swap?

### ISSUE THREAD

**Issue by xt0rted** [projectkudu/kudu#2580]
I took an existing app service and setup a deployment slot so I could start using auto swap. Aside from needing to add the environment variable to keep the webjobs disabled in the staging slot everything seemed to be working ok.

After a deploy or two I checked app insights for the snapshot of one of the exceptions that was thrown during the deployment changes but there was no snapshot even though this was working fine prior to setting up the deployment slot.

After looking into it more I found that there was no app insights site extension on the production slot, but there was on the staging slot. In the docs I didn't see mention of how site extensions are handled. Do these need to be installed on both slots in order to work correctly after a deployment? The page I was looking at was https://docs.microsoft.com/en-us/azure/app-service/web-sites-staged-publishing

**Comment by davidebbo** [comment]
Site extensions are deployed as files, much like the rest of your site files. So if you install one in Staging and swap, it gets swapped to Prod.

As long as you have a script or ARM template which consistently installs the extensions that you need before swapping, Prod should always end up having what it needs.

**Comment by xt0rted** [comment]
Right now the only script I have is my `deploy.cmd`, is there a different setup I should be using when doing auto swap?

**Comment by davidebbo** [comment]
Not sure I follow. Deploy.cmd just does the file deployment, but doesn't deal with provisioning resources and installing site extensions. How did you install the site extension in the first place?

**Comment by xt0rted** [comment]
I installed it through the portal 6+ months ago. Earlier today is when I started to setup the deployment slot for auto swap and followed the instructions on the link above. When I created the slot it asked if I wanted to copy my settings to which I said yes, but that doesn't seem to have addressed the site extensions which is why after the swap it was missing.

**Comment by davidebbo** [comment]
Correct, you need to install the extension of each new slot.

**Comment by xt0rted** [comment]
I have post deploy webhooks setup to alert me when the deploy finishes, but it seems to take a few minutes for the live site to actually swap out after those alerts come through. Is there any way to get alerts when the swap starts/finishes?

I'm also noticing that once the swap happens it seems like my site restarts and takes ~30 seconds to come back. Isn't the auto swap setup supposed to prevent that?

**Comment by davidebbo** [comment]
Those questions are no longer about site extensions, but more general slot/swap questions.

Site does restart, but in a way that should not be causing any downtime. See http://ruslany.net/2015/09/how-to-warm-up-azure-web-app-during-deployment-slots-swap/ for discussion on this. This doesn't talk about auto-swap specifically, but everything still applies.
