### ISSUE TITLE
Deploying functionapp's as zipfiles

### ISSUE THREAD

**Issue by justinmchase** [projectkudu/kudu#2582]
I'm looking to deploy function apps as zipfiles but I am drinking from a firehose with this documentation. I'm not sure how to get started. I'm trying to build functions with nodejs and I don't want to use the github scm hook because I need to do some gulp build steps and also I am building a monorepo where the repo will have multiple functions and sites, etc. I can't assume the whole repo is a single app.

I saw [this](https://github.com/projectkudu/kudu/issues/2562) thread on a seemingly relevant feature. And the [zip](https://github.com/projectkudu/kudu/wiki/REST-API#zip) documentation seems to be just what I'm looking for but I think I need a little help putting the puzzle pieces together.

I currently have a Resource Manager template that I'm able to deploy with:
```
$ azure login
$ azure group create --name ${name} --location "${location}" --json
$ azure group deployment create --name ${name} --resource-group ${name} --template-file apps/azuredeploy.json --parameters "${params}" --json
```
I'll spare you the details but I'm creating a really basic template with storage, serverfarm and a sites resources. If I then manually upload files into the file storage under `sites/wwwroot/hello` I can then invoke my functionapp successfully with curl. But deploying files manually sucks and using the storage api to upload files 1 at a time is way to slow.

I am seeing this documentation, which looks really promising:
https://github.com/projectkudu/kudu/wiki/REST-API#zip

I'm new to azure though and I'm wondering, if I'm using the command line tool how do I get the credentials I need to call this api and what would an example PUT url be?

I think it would look something like this:
```
curl -XPUT https://example.scm.azurewebsites.net/api/zip/hello -H "Authorization=??" -H "Content-Type: multipart/form-data"
```
Where that would upload a zipfile I created and unpack it under the `sites/wwwroot/hello` directory. Does that sound right?

Also, how can I get the credentials needed to successfully call this api?

**Comment by davidebbo** [comment]
The new zip API that will support true deployment (including carrying deletions, ...) is not yet there, but soon will be in preview. But for now you can try the existing zip API, which basically unzips everything over whatever is in the folder (not incremental, no deletion).

The top of the REST-API page has info on authentication to the scm endpoint.

**Comment by justinmchase** [comment]
@davidebbo Thanks for the reply!

I have been trying to RTFM for a couple of days and am having no luck :(

So I have a few more questions about details. Specifically the part about the authentication, I'm assuming what I need is the [User Level Credentials](https://github.com/projectkudu/kudu/wiki/Deployment-credentials#user-level-credentials-aka-deployment-credentials) discussed in the authentication page. But when I follow through the documentation, which I believe is [here](https://docs.microsoft.com/en-us/azure/app-service/app-service-deployment-credentials) but my portal seems to be missing a "Deployment Credentials" section and I don't know why:

![2017-10-04](https://user-images.githubusercontent.com/10974/31262716-b0ad7ad0-aa22-11e7-8c87-7d193d838f44.png)

The Deployments section just shows a list of the times I deployed my Resource Manager template from the command line. I see no options to create credentials anywhere. What am I missing?

Also, supposing I am able to acquire the credentials somehow. Do I just use them to do Basic Authorization while calling the api?

Thanks again.

**Comment by justinmchase** [comment]
Ok I may have found a clue, when I deploy an App Service then I see the Deployment Credential options, but when I deploy a Function App I do not. I'm trying to deploy a Function App, is this api not going to help me with that after all?

**Comment by justinmchase** [comment]
Ok I think I'm getting somewhere, the screenshots here show the steps to find them for funtionapps:
https://docs.microsoft.com/en-us/azure/azure-functions/functions-continuous-deployment

Not easy to find I must say but I am making progress here. I'm thinking I need to setup the local git repo in my ARM template somehow in order to enable this.

**Comment by justinmchase** [comment]
I made some progress I think, I set it up to deploy from a local git repository and then manually set a username and password for ftp. I then used that username and password in curl and it seems to be getting passed the authentication step... I am getting an exception though that you may want to know about though.

```sh
$ gzip index.js
$ curl -XPUT -d @index.js.gz "https://abc:123@ugh.scm.azurewebsites.net/api/zip/hello/"
{"Message":"An error has occurred.","ExceptionMessage":"Specified argument was out of the range of valid values.\r\nParameter name: offset","ExceptionType":"System.ArgumentOutOfRangeException","StackTrace":"   at System.Web.HttpInputStream.Seek(Int64 offset, SeekOrigin origin)\r\n   at System.Web.Http.WebHost.SeekableBufferedRequestStream.Seek(Int64 offset, SeekOrigin origin)\r\n   at System.Net.Http.DelegatingStream.Seek(Int64 offset, SeekOrigin origin)\r\n   at System.IO.Compression.ZipArchive.ReadEndOfCentralDirectory()\r\n   at System.IO.Compression.ZipArchive.Init(Stream stream, ZipArchiveMode mode, Boolean leaveOpen)\r\n   at System.IO.Compression.ZipArchive..ctor(Stream stream, ZipArchiveMode mode, Boolean leaveOpen, Encoding entryNameEncoding)\r\n   at Kudu.Services.Zip.ZipController.<CreateDirectoryPutResponse>d__3.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Threading.Tasks.TaskHelpersExtensions.<CastToObject>d__3`1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()"}
```

It looks like I sent it a gzipped file rather than a zip archive (my bad) but it blew up in a pretty ugly way.

**Comment by davidebbo** [comment]
Not sure I completely follow. Why do you want to create a git repo if your goal is to deploy using the zip API?

BTW, we have a newer upcoming zip-based API around the corner that will work better for deployments. See https://github.com/projectkudu/kudu/wiki/Deploying-from-a-zip-file.

**Comment by davidebbo** [comment]
FYI the new zip deployment API is now available everywhere.

**Comment by justinmchase** [comment]
I'm successfully calling it, I may have a couple of minor bug reports, I'm trying to rule out user error first but I may have something later tonight.

**Comment by davidebbo** [comment]
Awesome! Please open new issues for anything you run into. I think you're literally the first user as we have not announced it widely :)

**Comment by justinmchase** [comment]
So the good news is that I ran it and it seems to work! Manually testing the function in the portal it seems to be working. It took 14s for me to deploy but I removed all of the node_modules so there were only a couple of files so we'll see how it goes when I load it up with files. 

```
[23:10:53] Starting 'uploadFunctions'...
pending: Updating submodules.
building: Running deployment command...
building: Running deployment command...
[23:11:07] 'uploadFunctions' errored after 14 s
[23:11:07] Error: Deployment failed with status 3
```

But the bad news is that I'm getting an error logged in the deployment screen in the portal:

![2017-10-11](https://user-images.githubusercontent.com/10974/31479127-bf42d920-aeda-11e7-8a6e-1455a41c0e04.png)

It doesn't really tell me what the error is either, what is this list is all of the logs. If I drill into the two "View Log" groups they just say success. When I did the deployment it gave me back a `location:` url in the headers as part of the response. I am then calling that location url to get the status of the deployment before moving on.

Eventually it gives me status 3, which from digging through your code I figured out means error but there is no error message or way for me to identify how to rectify the issue. Here is the full response from the server:
```
  app { id: '2cc4f77b482f4a97ad8c072d8b67753d',
  app   status: 3,
  app   status_text: '',
  app   author_email: 'N/A',
  app   author: 'N/A',
  app   deployer: 'Zip-Push',
  app   message: 'Created via zip push deployment',
  app   progress: '',
  app   received_time: '2017-10-12T04:30:03.6889592Z',
  app   start_time: '2017-10-12T04:30:05.8571404Z',
  app   end_time: '2017-10-12T04:30:12.0277289Z',
  app   last_success_end_time: null,
  app   complete: true,
  app   active: false,
  app   is_temp: false,
  app   is_readonly: true,
  app   url: 'https://bewmdone-justin.scm.azurewebsites.net/api/deployments/latest',
  app   log_url: 'https://bewmdone-justin.scm.azurewebsites.net/api/deployments/latest/log',
  app   site_name: 'bewmdone-justin' } +2s
```

I created a `.deployment` file with these contents:
```
[config]
command = bash deploy.sh
```

Then in `deploy.sh`
```
#!//bin/bash
echo Installed
```

It still ends in an error state.

**Comment by davidebbo** [comment]
I see this error:

2017-10-12T05:52:41.3261546Z,Syncing 1 function triggers with payload size 101 bytes failed with System.Net.Http.HttpRequestException: Response status code does not indicate success: 401 (Unauthorized).\r\n
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()\r\n
   at Kudu.Core.Helpers.PostDeploymentHelper.<PostAsync>d__32.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Kudu.Core.Helpers.PostDeploymentHelper.<SyncFunctionsTriggers>d__24.MoveNext(),4dfb590c-086e-4037-a354-ad08b9a7ea06,0

@suwatch, we need to add this new API to the list that gets the synctriggers token.

**Comment by nickwalkmsft** [comment]
> This documentation seems to indicate that the build should not happen for zip deploy by default but my test seems to indicate that it is running my deployment script.

You broke out of the default scenario by including a custom script :smiley:

Kudu performs deployments by generating scripts that it then runs. These scripts always include the file copy step that gets your files into the site root, but by default Kudu also looks through your source files to figure out what kind of app stack you're using and then includes steps like `npm install` or `dotnet publish`. This is great when you're deploying from source, but people deploying via zip are generally pushing a full ready-to-run app, so for zips is behavior is turned off.

If you provide a custom command as part of a zip deployment, Kudu skips the script generation phase entirely and just runs the command you give it.

**Comment by justinmchase** [comment]
I added the `.deployment` script because it seemed like the logs were indicating that it was trying to do some building but was having an error. So I replaced it with what I thought was a deployment script that was just a no-op. I'll take that away and try again. Its just that my app structure since this is for functionapps is that there is nothing direclty in wwwroot but instead multiple function apps in sub folders. I was thinking maybe it was getting confused by the lack of any identifiable project files in the root folder, but I'm not sure.

I do have a bit of a conundrum with whether or not I should run `npm install` on the server or not. I would agree with you that I normally want to run the build locally and then just zip that up in my deployment files and deploy it all. The problem with that though is that the server instance is Windows rather than Linux, and therefore when building native modules for node you have to build from the same platform/architecture as the server.

And this ends up being a bit of a challenge because I'm using the xplat azure cli tool, and can't make the assumption that all devs will be using windows. It turns out that the non-powershell azure cli 2.0 is only supported on Bash on Windows. So now all the binaries will be linux binaries. This works great locally but then I won't be able to deploy those binaries to azure directly from my machine.

And I love unit tests but eventually you want to do integration tests across services before deploying to prod or even to staging. Where we have multiple developers using the ARM templates I can easily spin up and down parallel resources for individual testing before merging and deploying through shared branches.

So I'm struggling a bit here with that. Either I just strictly forbid binary modules, or `npm install` on the server after deployment (assuming it has C++ build tools even installed?) or do a complex windows-in-docker local development or, what would be nice, is if the server the functionapps themselves are running on was Linux instead of Windows.

I see that that last option is not currently feasible but the beta version may enable it?

Anyway, I hope that brain dump was valuable. I'm a ex-msft employee who has been doing a lot of node and AWS over the last two years and am just trying dump some of the thoughts that are going through my head as I try out azure for the first time beyond just little demos from msdn.

The way I do this today in AWS is to essentially use a CloudFormation stack to create everything, and do zip uploads of lambda functions. We use osx as local dev machines but everything is run through docker so it can be run on linux, the same os as the final server. Meaning when I run unit tests I'm actually doing something like `docker-compose run server mocha`. We use gulp locally to automate that and shell exec to docker so its pretty seamless but the binaries are all linux.

The linux subsystem in windows actually simplifies this even more so thats pretty slick, I don't even need docker at all, except that the servers are not linux so I have to then somehow get back in windows. I could build in windows locally then shell exec into the bash subsystem just to run the azure cli I suppose...

Anyway, thanks for the help and keep up the good work.

**Comment by davidebbo** [comment]
@justinmchase we are fixing the issue you ran into, but the fix needs to go into the platform and not Kudu. So that will take 3-some weeks to be fully deployed.

And yes, we are looking at Functions on Linux, but it's a bit farther out.

**Comment by justinmchase** [comment]
Ok 👍 

Like I said it appears to unzip the files and "works" when I call the functions, so I can just ignore that error for now I think. And I can just forbid native modules for now and I should be ok for a while.

**Comment by davidebbo** [comment]
About the error, be aware that it means your triggers are not getting synced. So if you deploy a new function or change an existing function's trigger, you will need to manually sync by going to the Portal.

**Comment by justinmchase** [comment]
Is there an api in the cli I can call to force it to sync? We definitely want to setup a cosmosdb trigger on the function so I imagine I will get hit by that after all.

**Comment by davidebbo** [comment]
It's an ARM API. Here is what calling it looks like [in PowerShell](https://github.com/davidebbo/AzureWebsitesSamples/blob/aba32e3a8fe60bc50044b1a5f316ff22661359f8/PowerShell/HelperFunctions.ps1#L362-L367).
