### ISSUE TITLE
The zip api times-out on a medium sized zipfile

### ISSUE THREAD

**Issue by justinmchase** [projectkudu/kudu#2589]
### Repro steps.
* Download the attached zip file
* Upload that file to a functionapp site using the following command on Bash on Windows:
```sh
$ curl -v -XPUT --data-binary @dist/{functionname}.zip "https://{username}:{password}@{appname}.scm.azurewebsites.net/api/zip/site/wwwroot/{functionname}"
```

### Project structures.
The only file should be the attached zip file and you just need to have a `functionapp` site available to call the `api/zip`. I could provide a more complete example if you wanted but that should be pretty simple.

### The log/error given by the failure.
I've redacted some sensitive info but could provide any more details if needed.
```sh
$ curl -v -XPUT --data-binary @dist/{functionname}.zip "https://{username}:{password}@{appname}.scm.azurewebsites.net/api/zip/site/wwwroot/{functionname}"
* Hostname was NOT found in DNS cache
*   Trying {remoteip}...
* Connected to {appname}.scm.azurewebsites.net ({remoteip}) port 443 (#0)
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* SSLv3, TLS handshake, Client {functionname} (1):
* SSLv3, TLS handshake, Server {functionname} (2):
* SSLv3, TLS handshake, CERT (11):
* SSLv3, TLS handshake, Server key exchange (12):
* SSLv3, TLS handshake, Server finished (14):
* SSLv3, TLS handshake, Client key exchange (16):
* SSLv3, TLS change cipher, Client {functionname} (1):
* SSLv3, TLS handshake, Finished (20):
* SSLv3, TLS change cipher, Client {functionname} (1):
* SSLv3, TLS handshake, Finished (20):
* SSL connection using ECDHE-RSA-AES256-SHA384
* Server certificate:
*        subject: CN=*.azurewebsites.net
*        start date: 2016-09-28 21:45:23 GMT
*        expire date: 2018-05-07 17:03:30 GMT
*        subjectAltName: {appname}.scm.azurewebsites.net matched
*        issuer: C=US; ST=Washington; L=Redmond; O=Microsoft Corporation; OU=Microsoft IT; CN=Microsoft IT SSL SHA2
*        SSL certificate verify ok.
* Server auth using Basic with user '{username}'
> PUT /api/zip/site/wwwroot/{functionname} HTTP/1.1
> Authorization: Basic {authtoken}
> User-Agent: curl/7.35.0
> Host: {appname}.scm.azurewebsites.net
> Accept: */*
> Content-Length: 3850166
> Content-Type: application/x-www-form-urlencoded
> Expect: 100-continue
>
< HTTP/1.1 100 Continue
< HTTP/1.1 500
< Content-Length: 221
* Server Microsoft-HTTPAPI/2.0 is not blacklisted
< Server: Microsoft-HTTPAPI/2.0
< Set-Cookie: ARRAffinity={affinity};Path=/;HttpOnly;Domain={appname}.scm.azurewebsites.net
< Date: Sun, 08 Oct 2017 15:12:23 GMT
* HTTP error before end of send, stop sending
<
* Closing connection 0
* SSLv3, TLS alert, Client {functionname} (1):
<html><head><title>500 - The request timed out.</title></head><body>  <font color ="#aa0000">         <h2>500 - The request timed out.</h2></font>  The web server failed to respond within the specified time.</body></html>
```

What's weird is that if I look in the debug console under `D:\home\LogFiles\kudu\trace` and grab the log file for this request here is the trace:
```xml
<step title="Incoming Request" date="2017-10-08T15:08:30.632" instance="bc1dc1" url="/api/zip/site/wwwroot/hello" method="PUT" type="request" pid="5432,2,10" Connection="Keep-Alive" Content-Length="3850166" Content-Type="application/x-www-form-urlencoded" Accept="*/*" Authorization="Bas..." Expect="100-continue" Host="bewmdone-justin.scm.azurewebsites.net" User-Agent="curl/7.35.0" X-WAWS-Unencoded-URL="/api/zip/site/wwwroot/hello" X-ARR-LOG-ID="34c505d1-f3cf-42db-8d67-3249ab9348c7" X-SITE-DEPLOYMENT-ID="bewmdone-justin" WAS-DEFAULT-HOSTNAME="bewmdone-justin.scm.azurewebsites.net" X-MS-CLIENT-PRINCIPAL-NAME="3d5..." X-MS-SITE-RESTRICTED-JWT="eyJ..." X-Forwarded-Proto="https" >
    <step title="Cleanup Xml Logs" date="2017-10-08T15:08:30.679" />
    <!-- duration: **78ms** -->
    <step title="Outgoing response" date="2017-10-08T15:14:24.524" type="response" statusCode="200" statusText="OK" Server="Microsoft-IIS/8.0" x-ms-request-id="34c505d1-f3cf-42db-8d67-3249ab9348c7" Cache-Control="private" X-AspNet-Version="4.0.30319" />
    <!-- duration: 47ms -->
</step>
<!-- duration: 353970ms -->
```

Notice those durations. It sounds like the status code came back but the connection wasn't closed? That's how I'm interpretting it.

### Debug your Azure website remotely.
The sitename is `bewmdone-justin` its just a test site I've been using to figure out deployments and automation before making the real site. Feel free to poke around in it.

### Mention any other details that might be useful.

First off the zip file I"m using is 3,850,166 bytes, which is not that big frankly. I would not expect a timeout. When I run the exact same code with a zip that has only a single file in it, it works just fine though.

I'm guessing it has something to do with a file in the folder having `MAX_PATH` issues perhaps? Sometimes node creates files with really long names in the `node_modules` folder. Windows doesn't always appreciate this. Perhaps a warning or error is kicked out which disrupts the standard flow and a callback somewhere isn't called?

Zip attached:
[hello.zip](https://github.com/projectkudu/kudu/files/1366999/hello.zip)

**Comment by davidebbo** [comment]
Could it be that the client hit the 230 second timeout, but that everything unzipped correctly on server? Or are you seeing missing files or other evidence that something went wrong server side?

**Comment by davidebbo** [comment]
BTW, we have a newer API that should work much better for general deployment: https://github.com/projectkudu/kudu/wiki/Deploying-from-a-zip-file. It supports async, and is generally much more appropriate that the plain zip API, which just unzips everything blindly (and will never delete things that should no longer be there). Also, it supports an async pattern.

Can you give that a try? It's not in all regions yet, but it is in North Central US where your app is. /cc @nickwalkmsft

**Comment by justinmchase** [comment]
Like I said I didn't check every single file but it really looks like, from a cursory inspetion, that all of the files are there. The trace even seems to imply that it took 47ms to unpack it which frankly sounds about right. It just seems like some callback wasn't called somewhere and thus the connection between client and server holds open until the timeout. Also notice my client is getting a 500 vs. the 200 reported in the trace, which makes it seems like its between the server and load balancer perhaps? 

I thought the new zip deployment api wasn't available yet but if it is I'll try that out. That was my next plan in the meantime anyway but I figured you'd still want to know about this.

**Comment by davidebbo** [comment]
Yes, what you're hitting is the 230 second idle connection timeout. It happens because the zip API is synchronous, and it takes time to unzip all these files while nothing is being sent back over the connection. There isn't much we can do about this in Kudu, short of making /api/zip async. But since we have the new API for deployment and that supports async, we probably won't do that.

But please do try the new one and let us know. It's still very much in Preview, and we need all the feedback we can get.

**Comment by justinmchase** [comment]
Are you sure though? What I'm saying is that it should take about 1s to unzip this file, and the trace looks like that is how long it takes to completely unzip it (47ms) and all of the files seem like they are unpacked. It seems like there is an error happening that causes it to hang rather than a timeout because of how long it takes.

**Comment by justinmchase** [comment]
And question about the zip deployment api, how do I specify which functionapp is being deployed? Or where is it unpacking the zip to? Just `sites\wwwroot`? Will that delete other functionapps if I just deploy the one?

**Comment by justinmchase** [comment]
```
404
"No route registered for '/api/zipdeploy'"
```

**Comment by davidebbo** [comment]
There is no way it's taking 47ms to unzip thousands of files on the slow storage backed drive. The logging is confusing, but it is very likely that it's taking that long to unzip. You can probably see this by going to Kudu during the unzip and seeing files appear over time.

The new zip deploy goes to `site\wwwroot` just like git deployment or msdeploy. Note that it is a POST and not a PUT, which is likely why you got a 404. If you still get a 404, can you check what version of Kudu you're running (Kudu root tells you)?

**Comment by davidhagg** [comment]
Also got the 404 "No route registered for '/api/zipdeploy'"
We hade this working fully, then recreated resourcegroup + appserviceplan + storage with our scripts and now it stopped working

**Comment by nickwalkmsft** [comment]
Referencing https://github.com/projectkudu/kudu/issues/2653

**Comment by justinmchase** [comment]
I did manage to get this working. I'm deploying an ARM template with a function app, a site and a cosmos database. I'm using nodejs and gulp4.

Here is my full deployment script:
```js
import gulp from 'gulp'
import zip from 'gulp-zip'
import uuid from 'uuid/v4'
import { lint } from './lint'
import { clean } from './clean'
import { install } from './install'
import { test } from './test'
import { exec } from '../helpers/exec'
import { uploadZip } from '../helpers/upload'
import { group, location, stage } from '../helpers/env'

const username = uuid()
const password = uuid()

function createGroup (done) {
  const cmd = `az \
    group create \
    --name ${group}-${stage} \
    --location "${location}" \
    --output json`

  exec(cmd, { json: true }, done)
}

function createDeployment (done) {
  const cmd = `az \
    group deployment create \
    --name ${group}-${stage} \
    --resource-group ${group}-${stage} \
    --template-file apps/azuredeploy.json \
    --parameters stage="${stage}" group="${group}" location="${location}" \
    --output json`

  exec(cmd, { json: true }, done)
}

function setDeploymentCredentials (done) {
  const cmd = `az \
    functionapp deployment user set \
    --user-name ${username} \
    --password ${password}`

  exec(cmd, { json: true }, done)
}

function deploy (name) {
  function _zip () {
    const src = [
      `dist/${name}/**/*`,
      `dist/${name}/**/.*`
    ]
    return gulp
      .src(src, { follow: true })
      .pipe(zip(`${name}.zip`))
      .pipe(gulp.dest('dist'))
  }

  function _upload (done) {
    uploadZip(username, password, name, done)
  }

  _zip.displayName = `zip-${name}`
  _upload.displayName = `upload-${name}`
  return gulp.series(_zip, _upload)
}

const steps = gulp.series(
  lint(),
  clean,
  install,
  test,
  createGroup,
  createDeployment,
  setDeploymentCredentials,
  gulp.parallel(
    deploy('func'),
    deploy('site')
  )
  // migrate()
)

gulp.task('deploy', steps)
```

Here is the zipdeploy module:
```js
import fs from 'fs'
import debug from 'debug'
import request from 'request'
import { autoInject, doUntil } from 'async'
import { group, stage } from './env'

const { assign } = Object
const log = debug('app')

function token (username, password, callback) {
  const token = Buffer.from(`${username}:${password}`).toString('base64')
  log({ username, password, token })
  callback(null, token)
}

function publish (token, name, callback) {
  const params = {
    method: 'POST',
    uri: `https://${group}-${stage}-${name}.scm.azurewebsites.net/api/zipdeploy?isAsync=true`,
    headers: {
      Authorization: `Basic ${token}`
    },
    body: fs.createReadStream(`dist/${name}.zip`)
  }
  request(params, (err, res) => {
    if (err) return callback(err)
    const { statusCode, body, headers } = res
    switch (res.statusCode) {
      case 202:
        log(`Sucessfully deployed function ${name}`)
        return callback(null, headers)
      default:
        const message = `Deploy failed with code ${statusCode}: ${body}`
        const err = new Error(message)
        return callback(assign(err, { statusCode, body, headers }))
    }
  })
}

function check (token, publish, callback) {
  const { location } = publish
  function getStatus (callback) {
    const params = {
      method: 'GET',
      uri: location,
      headers: {
        Authorization: `Basic ${token}`
      }
    }
    request(params, (err, res) => {
      if (err) return callback(err)
      const { statusCode, body, headers } = res
      const data = JSON.parse(body)
      const { status, complete, progress } = data
      log(data)
      if (statusCode === 200 && complete && (status === 4)) {
        // Success
        console.log('Success.')
        return callback(null, complete)
      } else if (statusCode === 202 && !complete) {
        // In progress...
        switch (status) {
          case 0:
            console.log('pending:', progress)
            break
          case 1:
            console.log('building:', progress)
            break
          case 2:
            console.log('deploying:', progress)
            break
          default:
            throw new Error('Unknown status.') // failed / success should also be complete
        }
        return setTimeout(() => callback(null, complete), 1000)
      } else if (complete) {
        // Failed
        const message = `Deployment failed with status ${status}: ${progress}`
        const err = new Error(message)
        return callback(assign(err, { body }))
      } else {
        // Unknown error.
        const message = `Deployment status failed with code ${statusCode}: ${body}`
        const err = new Error(message)
        return callback(assign(err, { statusCode, body, headers }))
      }
    })
  }

  function checkStatus (complete) {
    return !!complete
  }

  doUntil(getStatus, checkStatus, callback)
}

export function uploadZip (username, password, name, callback) {
  const block = {
    username: (cb) => cb(null, username),
    password: (cb) => cb(null, password),
    name: (cb) => cb(null, name),
    token,
    publish,
    check
  }
  autoInject(block, callback)
}
```
