### ISSUE TITLE
Enable "clean" deployments via Kudu (at least for zip deployment)

### ISSUE THREAD

**Issue by nickwalkmsft** [projectkudu/kudu#2596]
During a Kudu deployment, files found in the target directory that are not included in the deployment are only deleted if they are found in the previous deployment's manifest (i.e. were part of the previous Kudu-powered deployment).

This is generally desirable and should remain the default everywhere, but it was designed for scenarios involving repeated deployments from a fairly stable source. Users using more casual/one-off mechanisms like zipdeploy for rapid iteration, or who are transitioning or moving back and forth between workflows that use/don't use Kudu deployments, may want their deployment to do a full clean of the target. There is no way to do this via a Kudu deployment without specifying a custom script.

At least for zipdeploy, the user should be able to specify whether or not they want a clean deployment. I see two potential implementations of the delete action:
- KuduSync has an `ignoreManifest `option that does exactly this. This will require changes to both Kudu and the KuduScript templates, and KuduSync will perform the deletions on a file-by-file basis, which may be slow if the user has many files deployed. 
- Have Kudu perform the deletion itself prior to running the deployment scripts. This will limit the changes to Kudu, offers an opportunity for better performance, and allows us to honor the "clean" option even if the user provides a custom script that doesn't do it.

**Comment by MNashDev** [comment]
Has this been implemented yet?

I am looking to clean the wwwroot directory before a customer's deployment each time to ensure there are no old files that may conflict with the deployment, and so this would be very helpful.

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
