### ISSUE TITLE
npm install doesn't work in project kudu console

### ISSUE THREAD

**Issue by michael-golfi** [projectkudu/kudu#2599]
> For deployment issues, please provide us with the following information:
> ---------------------------------------------------------------

### Repro steps.
1. Upload `package.json` to wwwroot or function root.
2. `npm install`

This is the version of npm on my laptop, it installs correctly.
```bash
$ npm version
{ npm: '3.10.10',
  node: '6.11.3'}
```

### Project structures.
Any structure could probably repro

### The log/error given by the failure.
`npm install` fails due to eperm issue.
[npm-debug.log](https://github.com/projectkudu/kudu/files/1399608/npm-debug.log)

### Mention any other details that might be useful.
I followed the tips at [pkg management](https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-node#node-version-and-package-management). I tried uploading `package.json` to `~\site\wwwroot` and `~\site\wwwroot\functionname` and tried independently running `npm install` in both directories. It puts a hidden directory called `.staging` in node_modules but then either hangs or fails with this log file error. I tried in firefox and edge if that makes any difference. I also tried with CMD and powershell.
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by michael-golfi** [comment]
I think it's also worth mentioning that I tried to delete the `.staging` file and I also got a permissions error.

**Comment by watashiSHUN** [comment]
```
$ npm version
{ npm: '3.10.10',
  node: '6.11.3'}
```
based on this output, I would assume your laptop is not running windows? I will try to reproduce this locally

**Comment by michael-golfi** [comment]
Sorry, that was me giving part of the output. I am running Windows.

**Comment by watashiSHUN** [comment]
Ah, I think I have a theory. Do you have enough disk space?
Can you check in kudu how much available storage does your `D:\home` have?
1. navigate to "Environment" tab 
![image](https://user-images.githubusercontent.com/6531400/31842159-9556f7e0-b5a1-11e7-85a0-a74f67422be6.png)
2. check under "System info"
![image](https://user-images.githubusercontent.com/6531400/31842236-f16f84e8-b5a1-11e7-8259-1d6d6d0d26c6.png)

I was testing with `npm install azure-iot-gateway`, and I realize that itself is around 250MB. You are also saying that you ran `npm install` independently under t**wo separate directories**, this could eat up a significant disk space (for my test app...I only have 1GB in total)

**Comment by leblancmeneses** [comment]
I am having the same problem.  I am guessing it times out in ui waiting for command to be executed on the backend.    ```npm install``` can take a while.

When browsing using ftp I notice a node_modules\.staging folder.  Why would that happen?

![image](https://user-images.githubusercontent.com/730804/35317168-1351f642-009b-11e8-890d-93ab10b194cc.png)

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
