### ISSUE TITLE
Gitlab deployment error on AppService

### ISSUE THREAD

**Issue by fmdufour** [projectkudu/kudu#2601]
### Repro steps.
I'm building using .NET Command Line Tools (2.0.0) on my local machine.
The error occurs when deploying to my AppService via Gitlab and when trying to execute webjobs based on ASP.NET Core 2.0.

### The log/error given by the failure.
I lost the log from the last failed deployment, and unfortunately I cannot compromise our Production environment again, but the error message is the same as on WebJob execution.
`D:\Program Files (x86)\dotnet\sdk\2.0.0\NuGet.targets(102,5): error : Could not find file 'D:\home\.nuget\microsoft.netcore.platforms\2.0.0\microsoft.netcore.platforms.nuspec'. [D:\local\Temp\jobs\continuous\prod-bearings-jobs\zp0zeytq.i22\Bearings.VG.Jobs\Bearings.VG.Jobs.csproj`

### Debug your Azure website remotely.
prod-bearings-vocationalguidance-api

Thank you for the help.

**Comment by davidebbo** [comment]
That's not enough detail to investigate. Can you provide a repro per [this page](https://github.com/projectkudu/kudu/wiki/Using-a-git-repo-to-report-an-issue)? Thanks!
