### ISSUE TITLE
Authenticating with zip API

### ISSUE THREAD

**Issue by apengwin** [projectkudu/kudu#2607]
I'm trying to deploy a functionapp with the zip API. I'm having trouble with authentication. When I log on to the Azure portal, I log in through a third party (berkeley.edu). When I use the same creds in the zip API, I get Access denied errors.
Is this the proper way to authenticate myself?
```
from requests import put
USER="apengwin@berkeley.edu"
PASS="hunter2"
AUTH = (USER, PASS)
res = put("https://appname.scm.azurewebsites.net/api/site/wwwroot/", auth = AUTH, data=zipfile)
print res

 <div class="content-container"><fieldset>
  <h2>401 - Unauthorized: Access is denied due to invalid credentials.</h2>
  <h3>You do not have permission to view this directory or page using the credentials that you supplied.</h3>
 </fieldset></div>
```

**Comment by davidebbo** [comment]
You need to use [Deployment credentials](https://github.com/projectkudu/kudu/wiki/Deployment-credentials).
