### ISSUE TITLE
Allow use Service Principal key

### ISSUE THREAD

**Issue by auxym** [projectkudu/kudu#2609]
### Repro steps.
I tried to access the REST API using a Service principal key to authenticate. The same script worked with my regular user level deployment user/password. For the Service Credential, I tried its display name, as well as App ID as the user name, and a valid key (ie, can be used to login with azure-cli or powershell AzureRM) as the password.

### The log/error given by the failure.
Using the Service Principal credentials, I get an HTTP Unauthorized response when I try to query the REST API.

### Mention any other details that might be useful.
I think it would be useful to allow service principal credentials for automated deployments. The other way to do it, is to use azure-cli to login with the credentials and pull the publishsettings for the webapp, which can then be used in kudu. This add an extra step which seems unnecessary.

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
