### ISSUE TITLE
Error response for POST /listSecrets API does not conform to RP contract

### ISSUE THREAD

**Issue by ahmelsayed** [projectkudu/kudu#2610]
> The issue is that when POST /listSecrets under a functions app returns 409 error because the app has got slots enabled, the error response does not conform to RPC. The response looks like the following
> {
>     "Message": "An error has occurred.",
>     "ExceptionMessage": "Runtime keys are stored on blob storage. This API doesn't support this configuration.",
>     "ExceptionType": "System.InvalidOperationException",
>     "StackTrace": "   at Kudu.Core.Functions.FunctionManager.<GetKeyObjectFromFile>d__9`1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Kudu.Core.Functions.FunctionManager.<GetFunctionSecretsAsync>d__12.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Kudu.Services.Functions.FunctionController.<GetSecrets>d__12.MoveNext()"
> }
> RP contract (specified here -- https://github.com/Azure/azure-resource-manager-rpc) mandates that error response must have 'code' and 'message'. In Logic Apps, we need to use the code from the response to filter out this error case.

**Comment by ahmelsayed** [comment]
https://github.com/Azure/azure-resource-manager-rpc/blob/master/v1.0/common-api-details.md#error-response-content

**Comment by davidebbo** [comment]
It's probably just a matter of wrapping the exception. Search for `ArmUtils.CreateErrorResponse` for example (Kudu.Services\Functions\FunctionController.cs).
