### ISSUE TITLE
WebJob traces should not trace executable argument literally which may contain due to PII

### ISSUE THREAD

**Issue by suwatch** [projectkudu/kudu#2611]
Message for EventId 65514

Internal ref:

https://wawscus.kusto.windows.net:443/wawsprod?query=H4sIAAAAAAAEAHXNwQqCQBCA4bvgOwyeKhAcKYLIQMhDiCDUCyy7E0q2I7uzSNDDV7eiOv8f%2fHUwIY7uMHXkCE6HpjqeyqaFHRglJP2VZnmG6xQxzRBwucHV%2fJff%2fvP5u1%2bAZiuqtx6SPZ1VGKSyZuTeim8dC2seik5kTIDdhy615mClplvx1Vrl%2fcTOPMtrJepCgFkcPQBpeWvZ3AAAAA%3d%3d

Kudu
| where TIMESTAMP > datetime(2017-11-01 14:15)
| where TIMESTAMP < datetime(2017-11-01 14:25)
| where * contains "DefaultEndpointsProtocol=http" or * contains "AccountKey=" or * contains "Password=" 
| take 10

**Comment by davidebbo** [comment]
Isn't it more generally to the Command Controller? [this code](https://github.com/projectkudu/kudu/blob/master/Kudu.Services/Commands/CommandController.cs#L41)

**Comment by suwatch** [comment]
Yes.  The one raising issue was coming from WebJobs scenario.   However, the fix may span many scenarios.

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
