### ISSUE TITLE
Suggested Wiki Edit for Deployment Script

### ISSUE THREAD

**Issue by brianbancroft** [projectkudu/kudu#2613]
Hi there, I'm just running through your docs (which are plentiful!) and I noticed a small discrepancy [here](https://github.com/projectkudu/kudu/wiki/Custom-Deployment-Script):

![image](https://user-images.githubusercontent.com/6225122/32378526-5bb1ca84-c081-11e7-9103-686bc62dd31d.png)

I'm currently running down the instructions for node, and instead of seeing the following files:
```
.deployment - Contains the command to run for deploying your site.
deploy.cmd - Contains the deployment script.
```
I'm seeing:
```
.deployment - Contains the command to run for deploying your site.
deploy.sh - Contains the deployment script.
```

Would someone be willing to change the block in question to:
```
Any of these commands will generate the files required to deploy your site, mainly:

.deployment - Contains the command to run for deploying your site.
deploy.cmd - Contains the deployment script. (deploy.sh for node apps)
Now you can edit the deploy.cmd file and add your custom steps.
```

Thanks! I'm relatively new to this game, and it threw me for a loop for couple minutes. I'm slow that way. Thanks again for maintaining such a well-maintained repo!

**Comment by davidebbo** [comment]
On Windows, it generates a .cmd by default, and on Mac/Linux a .sh (and you can override using `--scriptType`, try `--help` for details). I've clarified the doc. Thanks for bringing this up!
