### ISSUE TITLE
Site warmup for asp.net core

### ISSUE THREAD

**Issue by mattwoberts** [projectkudu/kudu#2619]
I use site warmup in my existing asp.net web apps to try and minimize downtime when we swap staging into production.

However - this doesn't work in asp.net core. The feature depends on a <applicationInitialization > module being added to the web.config but for asp.net core web apps, every time you deploy a fresh release to the staging slot, the web.config is re-generated.

How can we do application initialization for asp.net core web apps in azure?

**Comment by davidebbo** [comment]
It's more of a .NET Core than Kudu question. But I believe if you include a web.config in your deployment, the deployment logic won't create one.

**Comment by xt0rted** [comment]
I setup an asp.net core site 2 weeks ago that contains a web.config, and uses `dotnet publish /p:WebPublishMethod=Package /p:PublishProfile=Default /p:PackageLocation=../../` to generate a web deploy package that is sent over from AppVeyor. It all works fine for me. I'm not using the warmup stuff for this though as it doesn't need it, so your millage may vary with that part.
