### ISSUE TITLE
[Visual Studio] VS project downloaded from Azure Portal compiles with warnings

### ISSUE THREAD

**Issue by ahmelsayed** [projectkudu/kudu#2620]
_From @gitsparty on October 25, 2017 14:20_

I am using __Visual Studio 2017 - 15.4.__

When I download the Azure function content (including the VS project) from the Azure Portal, it compiles with couple of warnings. See below for warnings and a snapshot. I had a simple manual trigger Azure Function. 

```
warning NU1603: Microsoft.NET.Sdk.Functions 1.0.0-alpha6 depends on Microsoft.Build.Framework (>= 15.1.298-preview5) but Microsoft.Build.Framework 15.1.298-preview5 was not found. An approximate best match of Microsoft.Build.Framework 15.1.548 was resolved.

Microsoft.NET.Sdk.Functions 1.0.0-alpha6 depends on Microsoft.Build.Utilities.Core (>= 15.1.298-preview5) but Microsoft.Build.Utilities.Core 15.1.298-preview5 was not found. An approximate best match of Microsoft.Build.Utilities.Core 15.1.548 was resolved.
```

![functions_vs_warning](https://user-images.githubusercontent.com/26638048/32003531-3c478ea6-b954-11e7-9253-b999ba830bca.PNG)

_Copied from original issue: Azure/Azure-Functions#567_

**Comment by ahmelsayed** [comment]
this is currently implemented in here.

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
