### ISSUE TITLE
Kudu service failed with "the user name or password is incorrect"

### ISSUE THREAD

**Issue by qs-wang** [projectkudu/kudu#2622]
This is a FunctionApp created programmatically  via the node sdk, and I got following errors randomly.  I meant same code sometimes worked all right, but sometimes not.

While try to access the kudu service via code, or via browser I got following error.

An unhandled exception was generated during the execution of the current  web request. Information regarding the origin and location of the  exception can be identified using the exception stack trace below.
--

[IOException: The user name or password is incorrect. ]    System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath) +13010840    System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost) +12872414    System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost) +82    System.IO.Directory.CreateDirectory(String path) +33    System.IO.Abstractions.DirectoryWrapper.CreateDirectory(String path) +11    Kudu.Core.Infrastructure.FileSystemHelpers.CreateDirectory(String path) +40    Kudu.Core.Environment.get_DeploymentToolsPath() +26    Kudu.Core.Infrastructure.PathUtilityBase.GetPathFolders(IEnvironment environment) +45    Kudu.Services.Web.App_Start.NinjectServices.PrependFoldersToPath(IEnvironment environment) +30    Kudu.Services.Web.App_Start.NinjectServices.RegisterServices(IKernel kernel) +123    Kudu.Services.Web.App_Start.NinjectServices.CreateKernel() +250    Ninject.Web.Common.Bootstrapper.Initialize(Func`1 createKernelCallback) +33    Kudu.Services.Web.App_Start.NinjectServices.Start() +224  [TargetInvocationException: Exception has been thrown by the target of an invocation.]    System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor) +0    System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments) +87    System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) +101    WebActivatorEx.BaseActivationMethodAttribute.InvokeMethod() +77    WebActivatorEx.ActivationManager.RunActivationMethods(Boolean designerMode) +635    WebActivatorEx.ActivationManager.Run() +113  [InvalidOperationException: The pre-application start initialization method Run on type WebActivatorEx.ActivationManager threw an exception with the following error message: Exception has been thrown by the target of an invocation..]    System.Web.Compilation.BuildManager.InvokePreStartInitMethodsCore(ICollection`1 methods, Func`1 setHostingEnvironmentCultures) +615    System.Web.Compilation.BuildManager.InvokePreStartInitMethods(ICollection`1 methods) +141    System.Web.Compilation.BuildManager.CallPreStartInitMethods(String preStartInitListPath, Boolean& isRefAssemblyLoaded) +102    System.Web.Compilation.BuildManager.ExecutePreAppStart() +157    System.Web.Hosting.HostingEnvironment.Initialize(ApplicationManager appManager, IApplicationHost appHost, IConfigMapPathFactory configMapPathFactory, HostingEnvironmentParameters hostingParameters, PolicyLevel policyLevel, Exception appDomainCreationException) +549  [HttpException (0x80004005): The pre-application start initialization method Run on type WebActivatorEx.ActivationManager threw an exception with the following error message: Exception has been thrown by the target of an invocation..]    System.Web.HttpRuntime.FirstRequestInit(HttpContext context) +10085804    System.Web.HttpRuntime.EnsureFirstRequestInit(HttpContext context) +95    System.Web.HttpRuntime.ProcessRequestNotificationPrivate(IIS7WorkerRequest wr, HttpContext context) +254
--

**Comment by qs-wang** [comment]
refresh the url via browser can get a working version, however I'd like to know if there's anyway to make sure of the Kudu service is ready via api call?

**Comment by qs-wang** [comment]
The app is using Consumption plan.

**Comment by davidebbo** [comment]
Are you still seeing this? If so, can you share your function app name (that's the **app** name, not function name!), either directly or [indirectly](https://github.com/Azure/azure-webjobs-sdk-script/wiki/Sharing-Your-Function-App-name-privately)? This will help us investigate. Thanks!

**Comment by davidebbo** [comment]
Closing as we haven't heard back, but we can reopen if needed.

**Comment by jianghaolu** [comment]
I verify this has been fixed. Thanks!

**Comment by qs-wang** [comment]
Sorry I was on Azure summit, and didn't actively following this issue.
My assumption here is that the App was spinning off, and if I access the kudu service during that time there's an error like this. As I have written the code via the node sdk to create the funciton app, and if I access the kudu api right after there's very high chance to see this error.  If I added some delay between (say 20 seconds) to allow the azure platform run its task to provisioning the  App, it's seems the error rate became 1/10.

I think if that's the case, then a better error message could be helpful.
