### ISSUE TITLE
deploy.cmd is not executed after ftp deployment

### ISSUE THREAD

**Issue by mrmunch** [projectkudu/kudu#2623]
### Repro steps.
* create a Web App
* **don't** select a Deployment Source
* use `curl` to transfer some files to the Azure Web App (path: D:/home/site/wwwroot/), including a `.deployment` and `deploy.cmd` file

### Project structures.
* static .html-, deploy.cmd- and .deployment-file

### The log/error given by the failure.
* deploy.cmd is NOT executed after ftp upload via `curl`

### Mention any other details that might be useful.
* When I upload the same files using Git Deployment, it works fine (deploy.cmd is executed). But I prefer to deploy via ftp.

**Comment by davidebbo** [comment]
That is expected. This mechanism is specific to git deployment. There is no mechanism to automatically run a script as a result of doing an FTP upload.
