### ISSUE TITLE
Run webjob error

### ISSUE THREAD

**Issue by qdxj0532** [projectkudu/kudu#2628]
my powershell as following and it works fine local:
$ProgressPreference="SilentlyContinue"
$ctx=New-AzureStorageContext -EnvironmentName AzureChinaCloud -StorageAccountName xxxxxxx -StorageAccountKey xxxxxxx= -Debug 
$s=get-AzureStorageShare -Name 'filesharenkdms' -Context $ctx -Debug 
'1111111111'| Out-File -FilePath "D:\home\ftproot\rxuser\dd1.txt" -Append
[array]$files=Get-AzureStorageFile -Share $s -Path 'POACK'  | Get-AzureStorageFile -Debug 
'2222222222'| Out-File -FilePath "D:\home\ftproot\rxuser\dd1.txt" -Append
$files[0].Name | Out-File -FilePath "D:\home\ftproot\rxuser\dd1.txt" –Append

Get error :
[11/17/2017 08:57:21 > 3feb96: SYS INFO] Status changed to Initializing
[11/17/2017 08:57:21 > 3feb96: SYS INFO] Run script 'gp3.ps1' with script host - 'PowerShellScriptHost'
[11/17/2017 08:57:21 > 3feb96: SYS INFO] Status changed to Running
[11/17/2017 08:57:23 > 3feb96: ERR ] New-AzureStorageContext : The Win32 internal error "The handle is invalid" 0x6 
[11/17/2017 08:57:23 > 3feb96: ERR ] occurred while setting character attributes for the console output buffer. 
[11/17/2017 08:57:23 > 3feb96: ERR ] Contact Microsoft Customer Support Services.

How should I Fix the problem ? thanks

**Comment by davidebbo** [comment]
Please start with https://github.com/projectkudu/kudu/wiki/Isolating-WebJobs-and-Deployment-script-issues

**Comment by hahaxj** [comment]
@davidebbo  Thanks for your reply.

Now my ps works as webjob , There are two points 
1,Set  $ProgressPreference="SilentlyContinue"
2, Remove -Debug opinion

$ProgressPreference="SilentlyContinue"
$ctx=New-AzureStorageContext -EnvironmentName AzureChinaCloud -StorageAccountName testforps -StorageAccountKey xxxxxx #-Debug | Out-File -FilePath "D:\work\Powershell\forcase\aaa.txt" -Append
$s=get-AzureStorageShare -Name 'filesharenkdms' -Context $ctx 
#$progressPreference = 'Continue'
'1111111111'| Out-File -FilePath "D:\home\site\wwwroot\aa.txt" -Append # | Out-File -FilePath "D:\home\ftproot\rxuser\dd1.txt" -Append
[array]$files=Get-AzureStorageFile -Share $s -Path 'test'  | Get-AzureStorageFile 
#$progressPreference = 'Continue'
'2222222222' | Out-File -FilePath "D:\home\site\wwwroot\bbb.txt" -Append #| Out-File -FilePath "D:\home\ftproot\rxuser\dd1.txt" -Append
#| Out-File -FilePath "C:\Users\zhongpr\dd.txt" -Append  #| Get-AzureStorageFile -Debug 
$files[0].Name | Out-File -FilePath "D:\home\site\wwwroot\bbb.txt" –Append
#$progressPreference = 'Continue'

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
