### ISSUE TITLE
Is there a way to read Application Setting's environment variable on deploy.sh?

### ISSUE THREAD

**Issue by wy193777** [projectkudu/kudu#2629]
Our frontend project use webpack to build. In the build process, we need to read a environment variable 'REST_SITE' to let the project know which backend address supposed to be used. This address will be injected to generated JS code as global variables. But seems when run deploy.sh on Azure App Service, it knows nothing about the Application Settings. 

So is there a way to access Application Setting's environment variable? Or do we have other solution for this scenario?

**Comment by davidebbo** [comment]
Anything that you set in the Azure App Settings (e.g. via portal or API) is available as environment variable during the Kudu deployment.
