### ISSUE TITLE
Funciton extensions.csproj is treated as csproj for function app

### ISSUE THREAD

**Issue by jeffhollan** [projectkudu/kudu#2631]
[Workaround here](https://github.com/Azure-Samples/customer-car-reviews/blob/c4efb997c9d3dfe0273cf9c8428862b1915f52b2/src/deployment/template.json#L452-L453)
### Repro steps.
* Have a function app in v2 runtime that is not a class library project. These include an extensions.csproj file
* On deploy, kudu believes it is the csproj for function app and builds incorrect project
* Function app doesn't work
### Project structures.
* [Sample repository](https://github.com/Azure-Samples/customer-car-reviews)

### The log/error given by the failure.
```
Command: "D:\home\site\deployments\tools\deploy.cmd"
Handling function App deployment.
Not using funcpack because SCM_USE_FUNCPACK is not set to 1
Installing function extensions from nuget
KuduSync.NET from: 'D:\home\site\repository' to: 'D:\home\site\wwwroot'
Copying file: '.gitignore'
Copying file: 'CONTRIBUTING.md'
Copying file: 'LICENSE.md'
Copying file: 'README.md'
Copying file: 'ServerlessConfTokyo2017MicrosoftKeynote.pdf'
Copying file: '.github\ISSUE_TEMPLATE.md'
Copying file: '.github\PULL_REQUEST_TEMPLATE.md'
Copying file: 'img\documents.png'
Copying file: 'img\eventgridauthorize.png'
Copying file: 'img\eventgridconnection.png'
Copying file: 'img\office365authorize.png'
Copying file: 'img\office365connection.png'
Copying file: 'img\proxy.png'
Copying file: 'img\resourcegroup.png'
Copying file: 'src\approvalsvcfunctionapp\.gitignore'
Copying file: 'src\approvalsvcfunctionapp\host.json'
Copying file: 'src\approvalsvcfunctionapp\package-lock.json'
Copying file: 'src\approvalsvcfunctionapp\package.json'
Copying file: 'src\approvalsvcfunctionapp\ChangeFeed\function.json'
Copying file: 'src\approvalsvcfunctionapp\ChangeFeed\index.js'
Copying file: 'src\approvalsvcfunctionapp\CheckImage\function.json'
Copying file: 'src\approvalsvcfunctionapp\CheckImage\index.js'
Copying file: 'src\approvalsvcfunctionapp\CheckText\function.json'
Copying file: 'src\approvalsvcfunctionapp\CheckText\index.js'
Copying file: 'src\approvalsvcfunctionapp\SendEvent\function.json'
Copying file: 'src\approvalsvcfunctionapp\SendEvent\index.js'
Copying file: 'src\deployment\document1.json'
Copying file: 'src\deployment\document2.json'
Copying file: 'src\deployment\document3.json'
Copying file: 'src\deployment\document4.json'
Copying file: 'src\deployment\document5.json'
Copying file: 'src\deployment\parameters.json'
Copying file: 'src\deployment\template.json'
Copying file: 'src\spa\.angular-cli.json'
Copying file: 'src\spa\karma.conf.js'
Copying file: 'src\spa\package-lock.json'
Copying file: 'src\spa\package.json'
Copying file: 'src\spa\protractor.conf.js'
Copying file: 'src\spa\README.md'
Copying file: 'src\spa\tsconfig.json'
Copying file: 'src\spa\tslint.json'
Copying file: 'src\spa\e2e\app.e2e-spec.ts'
Copying file: 'src\spa\e2e\app.po.ts'
Copying file: 'src\spa\e2e\tsconfig.e2e.json'
Copying file: 'src\spa\src\favicon.ico'
Copying file: 'src\spa\src\index.html'
Copying file: 'src\spa\src\main.ts'
Copying file: 'src\spa\src\polyfills.ts'
Copying file: 'src\spa\src\styles.css'
Omitting next output lines...
Restoring npm packages in "D:\home\site\wwwroot"
Finished successfully.
```

**Comment by davidebbo** [comment]
What's missing in the steps is that `PROJECT` needs to be set to `src/proxyfunctionapp`.

@watashiSHUN let's discuss this extension logic.

**Comment by fabiocav** [comment]
Yes,  that is correct. As long as the `PROJECT` setting is correctly set, the file is in the correct location and would be processed

**Comment by davidebbo** [comment]
@fabiocav no, what I meant is that setting PROJECT is part of setting up the repro. But it is definitely broken (I tried it).

**Comment by fabiocav** [comment]
Let's chat about this. I'm guessing what you're referring to as broken is the deployment/build logic in Kudu, right? But the file is in the  correct spot

**Comment by davidebbo** [comment]
@fabiocav  Correct, it's the logic that figures out the kuduscript command line to use.

@jeffhollan I fixed your 'workaround' link to use perma link as it was broken. Please make sure at always hit 'y' to get the permalink before grabbing the URL, so it's 'forever good'. :)

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
