### ISSUE TITLE
How to abort the continuous job running for a queue from API?

### ISSUE THREAD

**Issue by rukai-kooboo** [projectkudu/kudu#2637]
Hi there,
I've a question while using the Azure WebJob.

I've a Continuous type job, than can processing queue when it comes into it. Now I meet a requirement is that sometimes I need to be able to abort the queue's processing. I found Kudu provides REST APIs to Start/Stop job runs, while they are for Trigger Jobs and Singleton type Continuous job(to stop the whole instance). But I don't want to abort whole job, cause their may other queue's processing that is not need to abort.

Any one knows how can I get this down? Thanks :)

**Comment by davidebbo** [comment]
> I found Kudu provides REST APIs to Start/Stop job runs, while they are for Trigger Jobs and Singleton type Continuous job(to stop the whole instance).

That is not correct. In fact, the Start/Stop API only applies to Continuous, and not to Triggered. Also, it applies regardless of whether it's singleton or note.

Note that if you're using the WebJobs **SDK**, that's a very different things, and whether you can stop individual functions within it is completely outside the scope of Kudu. Kudu has no knowledge to the WebJobs SDK.
