### ISSUE TITLE
Kudu changes git-url when running to long onpremise.

### ISSUE THREAD

**Issue by fisshy** [projectkudu/kudu#2642]
Hey,

I've been running Kudu onpremise on windows server for some time now and been working great.

But recently I made few changes to IIS to keep Kudu running with "Always On"

Now this strange behaviour occured.

If I leave Kudu running without restarting it, after some time it changes the git-url for me.
![test](https://user-images.githubusercontent.com/3023875/33623181-728360a0-d9f0-11e7-851f-ca36015bfcac.PNG)

But once I restart the web in IIS, it  goes back to correct url.
![test2](https://user-images.githubusercontent.com/3023875/33623182-73f73dda-d9f0-11e7-9bbb-2bd9220ff543.PNG)

Has this happened to anyone?

Thanks!

**Comment by davidebbo** [comment]
I investigated, and it comes down to this code: https://github.com/projectkudu/kudu/blob/1af247e12f5ecad59d3f84546420e0526d2c1092/Kudu.Core/Infrastructure/ServerConfiguration.cs#L49-L55. So it's a sign that for some reason, `APP_POOL_ID` is not set. Hopefully that gives you clues to go to the next step.

**Comment by fisshy** [comment]
Thanks alot @davidebbo, will give it a try :)

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
