### ISSUE TITLE
Updating Web Job's app.config at deployment time?

### ISSUE THREAD

**Issue by mrichman** [projectkudu/kudu#2643]
With app services, I can use msdeploy parameters.xml to rewrite sections of my web.config at deployment time without having to do any post-deploy edits.

With web jobs, since I don't deploy those using msdeploy, how would I update sections of its app.config? I would need to do this because not every setting in an app.config is an app setting or connection string, and therefore not overridable in the portal, for example `<mailSettings>`.

**Comment by davidebbo** [comment]
If you build your WebJobs project using VS, it does in fact use msdeploy for deployment. Did you try this?

**Comment by mrichman** [comment]
My use case is to deploy directly from TFS. If I zip up my web job in the proper format, will it deploy from TFS just like an app service?

**Comment by davidebbo** [comment]
> will it deploy from TFS just like an app service

I'm not sure what you mean here. If you upload a zip, then what gets deployed is exactly the content of your zip. Whether the process that builds the zip takes into account your config rewrite is more of a VSTS question. Kudu just uses what it's given.

**Comment by mrichman** [comment]
Web deploy does config rewrites at deploy time using parameters.xml. I guess my question is if the same process will work for web jobs as it does for app services.

**Comment by mrichman** [comment]
I've been spinning my wheels trying to get Powershell to do what I've been doing for app services all along. I don’t actually touch the Kudu API at all now.

The real trick is just to package up the zip file with the correct directory structure. You have to create a zip file with "App_Data/jobs/continuous" at the root, exactly how it will be deployed.

The deployment from TFS works perfectly now, including .config file rewrites using parameters.xml.
