### ISSUE TITLE
Value cannot be null - JobsManagerBase - Brings the App Service Down

### ISSUE THREAD

**Issue by jsgoupil** [projectkudu/kudu#2645]
### Repro steps.
On Azure, MSBUILD 14, Kudu brought **all my slots** offline while multiple pre-prod slots were deploying.
The FREB were turned on for the main slot and this is what I got:

	[ArgumentNullException: Value cannot be null.
	Parameter name: source]
	   System.Linq.Enumerable.Select(IEnumerable`1 source, Func`2 selector) +5813303
	   Kudu.Core.Jobs.JobsManagerBase`1.CleanupDeletedJobs() +317
	   Kudu.Services.Web.App_Start.NinjectServices.RegisterServices(IKernel kernel) +5485
	   Kudu.Services.Web.App_Start.NinjectServices.CreateKernel() +321
	   Ninject.Web.Common.Bootstrapper.Initialize(Func`1 createKernelCallback) +20

	[TargetInvocationException: Exception has been thrown by the target of an invocation.]
	   System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor) +0
	   System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments) +260
	   System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) +146
	   System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters) +34
	   WebActivator.BaseActivationMethodAttribute.InvokeMethod() +288
	   WebActivator.ActivationManager.RunActivationMethods() +698
	   WebActivator.ActivationManager.RunPreStartMethods() +46
	   WebActivator.ActivationManager.Run() +68

	[InvalidOperationException: The pre-application start initialization method Run on type WebActivator.ActivationManager threw an exception with the following error message: Exception has been thrown by the target of an invocation..]
	   System.Web.Compilation.BuildManager.InvokePreStartInitMethodsCore(ICollection`1 methods, Func`1 setHostingEnvironmentCultures) +874
	   System.Web.Compilation.BuildManager.InvokePreStartInitMethods(ICollection`1 methods) +169
	   System.Web.Compilation.BuildManager.CallPreStartInitMethods(String preStartInitListPath, Boolean&amp; isRefAssemblyLoaded) +166
	   System.Web.Compilation.BuildManager.ExecutePreAppStart() +176
	   System.Web.Hosting.HostingEnvironment.Initialize(ApplicationManager appManager, IApplicationHost appHost, IConfigMapPathFactory configMapPathFactory, HostingEnvironmentParameters hostingParameters, PolicyLevel policyLevel, Exception appDomainCreationException) +882

	[HttpException (0x80004005): The pre-application start initialization method Run on type WebActivator.ActivationManager threw an exception with the following error message: Exception has been thrown by the target of an invocation..]
	   System.Web.HttpRuntime.FirstRequestInit(HttpContext context) +579
	   System.Web.HttpRuntime.EnsureFirstRequestInit(HttpContext context) +112
	   System.Web.HttpRuntime.ProcessRequestNotificationPrivate(IIS7WorkerRequest wr, HttpContext context) +712

On the Azure Portal, the deployment was spinning forever. Impossible to make it stop.
I had to disconnect GIT.

Reconnected GIT, it rebuilt. Everything worked fine.

**Comment by watashiSHUN** [comment]
This happened during git deployment, do you have the deployment log? or kudu logs during that time period?

**Comment by jsgoupil** [comment]
I do not, the only thing I have is
[kudu-error.txt](https://github.com/projectkudu/kudu/files/1564120/kudu-error.txt)

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
