### ISSUE TITLE
Support Web Fonts in Azure App Services

### ISSUE THREAD

**Issue by TomONeill** [projectkudu/kudu#2647]
Currently web fonts are not supported, mentioned in the Github Wiki [here](https://github.com/projectkudu/kudu/wiki/Azure-Web-App-sandbox#pdf-generation-from-html) and [here](https://github.com/projectkudu/kudu/wiki/Azure-Web-App-sandbox#pdf-generation-from-html).

> **PDF generation from HTML**
> There are some frameworks that do not leverage User32/GDI32 extensively (wkhtmltopdf, for example) and we are working on enabling these in Basic+ the same way we enabled SQL Reporting.

> **Unsupported frameworks**
> Known issue for all PDF generators based on wkhtmltopdf or phantomjs: custom fonts are not rendered (system-installed font is used instead) because of sandbox GDI API limitations that present even in VM-based Azure Apps plans (Basic or higher).

When will you be working on fixing that issue? It's been months.

**Comment by davidebbo** [comment]
This is not directly related to Kudu, but is about the general App Service sandbox, so closing here. You can use https://feedback.azure.com/forums/169385-web-sites/ to open a feedback item about App Service (or vote up if there is already one).
