### ISSUE TITLE
Be able to set a CNAME for the Kudu service that is behind a load balancer

### ISSUE THREAD

**Issue by saendu** [projectkudu/kudu#2650]
### Repro steps.
- Deploy an App Gateway (layer 7 load balancer)
- Point Domain (https://myapp.contoso.com) to internal app gateway domain (<guid>.cloudapp.net)
- Deploy an ASE with ILB
- Point App Gateway rule to internal ILB Address (e.g.) 10.0.1.8 
- Create a Web App inside ASE
- Create CNAME for Web App to listen to myapp.contoso.com
- Create a CNAME for Web App myapp.scm.contoso.com
- Try to access KUDU via myapp.scm.contoso.com
--> this will not work because the KUDU service does not listen to that hostname. 

### Expected behaviour
Kudu is accessable because we can set custom CNAMES in Kudu config.

I hope I did not miss a detail. If so please let me know.

Thanks,
Sandro

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
