### ISSUE TITLE
process.stdin.isTTY is undefined 

### ISSUE THREAD

**Issue by CKGrafico** [projectkudu/kudu#2657]
Using node plugins like fontmin are working well on local machine but when I try to run this plugins using Kudu CMD process.stdin.isTTY is undefined.

Moved from https://github.com/Azure/Azure-WebApps-Support-Center/issues/68#event-1411832007

**Comment by davidebbo** [comment]
Can you provide more detailed steps on what you are doing to observe the issue? What exact code are you running, what Node version, ...?

**Comment by CKGrafico** [comment]
Yes the code
https://github.com/ecomfe/fontmin/blob/master/cli.js (line 125)

Node version 8.5.0

To see the issue you have to install this plugin 'npm install fontmin' and try it

**Comment by davidebbo** [comment]
No way to isolate to something simpler the just runs the relevant code?

**Comment by davidebbo** [comment]
I tried running a one-line program that just has `console.log(process.stdin);`. Then do a diff of local machine vs App Service. In App Service:

- `ReadStream` is instead `Socket`
- `TTY` is instead `Pipe`
- There are no `isRaw` and `isTTY` properties

Though I don't understand the significance of those differences, the issue is clearly related to it. It maybe be running in a different mode of sort. Would need a Node expert to help make sense of it.

**Comment by CKGrafico** [comment]
Yes.

1. Go to your computer
2. Create a file called 'issue.js'
3. Put this code inside
`console.log(process.stdin.isTTY);`
4. Run `node issue`
You will see this:
![imagetrue](https://i.imgur.com/rANDlWC.png)

Repeat this steps in Kudu console
![imagefalse](https://i.imgur.com/MMAKS37.png)

**Comment by CKGrafico** [comment]
I've just read your reply now @davidebbo I don't have any idea about what this is happening sorry

**Comment by davidebbo** [comment]
Look at https://nodejs.org/dist/latest-v7.x/docs/api/process.html#process_process_stdin, it seems expected that stdin could be of two different types:

> The process.stdin property returns a stream connected to stdin (fd 0). It is a net.Socket (which is a Duplex stream) unless fd 0 refers to a file, in which case it is a Readable stream.

But I'm not sure what causes one vs the other.

**Comment by CKGrafico** [comment]
I'm not the owner of the plugin I'm not going to modify it but it's a plugin that usually works on VSTS builds, local machines and other places that are not Azure :/

**Comment by snobu** [comment]
As a workaround maybe you could override `process.stdin.isTTY` somewhere early in your code?
```
> process.stdin.isTTY
undefined
> process.stdin.isTTY = true
true
> process.stdin.isTTY
true
```

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
