### ISSUE TITLE
The specified framework 'Microsoft.NETCore.App', version 2.0.4' was not found

### ISSUE THREAD

**Issue by Rizzen** [projectkudu/kudu#2658]
Hello!
I'm seeing an error 502.5 when deploying my app. I went in and checked in SCM why it's not running and it turns out I get this error:
```
`It was not possible to find any compatible framework version

The specified framework 'Microsoft.NETCore.App', version '2.0.4' was not found.

  - Check application dependencies and target a framework version installed at:

      \

  - Alternatively, install the framework version '2.0.4'.`
```
Should Kudu be installing the new runtime?

**Comment by davidebbo** [comment]
It's being deployed, but has not completed. As a test, would you be able to try pushing your app to a 'West US 2' site to make sure that works? That region has the new bits.

**Comment by davidebbo** [comment]
Wait, did you mean 2.0.5? That's the one that was announced yesterday and that we're deploying: https://github.com/dotnet/core/blob/master/release-notes/2.0/2.0.5.md

/cc @watashiSHUN

**Comment by Rizzen** [comment]
No, i mean 2.0.4

**Comment by davidebbo** [comment]
I see. Looks like we skipped 2.0.4 and are going from 2.0.3 to 2.0.5. Regardless, I would expect 2.0.5 to just work for you (since it's yet newer), but please do verify in West US 2.

**Comment by Rizzen** [comment]
I just deployed my app in West US 2 - it works with 2.0.4 runtime.

**Comment by davidebbo** [comment]
Great, so we're in good shape. Give it another day and it should be everywhere.

**Comment by Rizzen** [comment]
Ok, thank you!

**Comment by Rizzen** [comment]
Should I close the issue?

**Comment by davidebbo** [comment]
Yep, closing it. But if you *don't* see it working tomorrow, let me know here!

**Comment by Rizzen** [comment]
I would like to deploy my app with 2.0.3 runtime right now, but i can check 2.0.4 tomorrow.
