### ISSUE TITLE
Sites and debug console are giving permission denied errors when trying to edit files

### ISSUE THREAD

**Issue by xt0rted** [projectkudu/kudu#2660]
I just received a couple error reports of a site that couldn't read/edit a json file from disk. I tried restarting the site but that didn't help and I continue to receive an `UnauthorizedAccessException`. I then tried to edit the file from the debug console and received the same error.

Of the 4 sites i've checked on this VM they're all are giving permission denied errors when I try to edit files in the debug console.

![image](https://user-images.githubusercontent.com/831974/34854117-b29fdf2e-f705-11e7-9661-5dc408b80cc9.png)

The sites in question are part of the app service plan containing the function app `noop`.

The azure account these are on is part of a msdn subscription which is in the process of being renewed. Could that be why this is happening or is it something else that needs further looking into?

**Comment by davidebbo** [comment]
Not really a Kudu issue if the file ended up being generally read-only for some reason. Have you checked `attrib` to see if it has read-only flag?

Also, it's hard to know which site it is since there are lots of other sites in the same resource group as `noop`.

**Comment by xt0rted** [comment]
The sites `noop-web` and `roxierosedesign` are two of the ones having the issue. It just started within the last hour I think and neither have had updates recently.

**Comment by davidebbo** [comment]
It seems like your whole `d:\home` has become read-only for some reason. e.g. if you go to `D:\home\site` and try to run `md tmp`, you get access denied as well.

Definitely not Kudu related. Would you be able to open a support case for this? It will take others with different expertise to figure this one out. If you share the case #, I can try to push on it on my end.

**Comment by davidebbo** [comment]
Well, I found a potential expert who is going to try to take a look. Though having a support case to go along does make it easier to track.

**Comment by xt0rted** [comment]
Thanks for looking into this for me. The support request is 118011217452071

**Comment by davidebbo** [comment]
I'm trying a mitigation right now that should take care of it.

**Comment by davidebbo** [comment]
Ok, you should be good to go now! Basically, the VM was in some kind of bad state and I initiated a reboot, which moved you to a new VM. Reason is not known, but hopefully support case can get answers.

**Comment by xt0rted** [comment]
Everything looks to be working again. Thank you very much!

Is there a way for me to force a vm reboot? Not that I want a reason to do it, but it could be useful to know about in the future.

**Comment by davidebbo** [comment]
Yep, scale up to a medium, and right away back to small.
