### ISSUE TITLE
Deploy App Under Sub-directory of GitHub

### ISSUE THREAD

**Issue by temurih** [projectkudu/kudu#2661]
I have a microservices application in a sub folder of github repository. I am trying to deploy it to Azure.

I found that if I add `.deployment` file in my root directory, Azure will automatically deploy the application found under the given path. [Here](https://github.com/projectkudu/kudu/wiki/Customizing-deployments#deploying-a-specific-aspnet-or-aspnet-core-project-file)

I have tried the following,

```
[config]
project = myFlaskProject/helloFlask
```

Azure build the project successfully, but still it gives me `You do not have permission to view this directory or page.` Not sure why, any ideas?

P.S. It works fine if I keep all the application files in my root directory.

Here is the [live demo](https://asdfhg.azurewebsites.net/) of the site.

### Project structures.

Here you can find the git repository that I am trying to deploy to Azure. [Git Repo](https://github.com/temurih/python-docs-hello-world)

### The log/error given by the failure.

There are no errors. I am pretty sure that its a runtime issue. Because I checked the logs, and it says it deployed successfully, and I checked it deployed the right folder.

These are the logs,

```
Using the following command to generate deployment script: 'azure site deploymentscript -y --no-dot-deployment -r "D:\home\site\repository" -o "D:\home\site\deployments\tools" --python --sitePath "D:\home\site\repository\flask\helloWorld"'.
The site directory path: .\flask\helloWorld
Generating deployment script for python Web Site
Generated deployment script files

Command: "D:\home\site\deployments\tools\deploy.cmd"
Handling python deployment.
KuduSync.NET from: 'D:\home\site\repository' to: 'D:\home\site\wwwroot'
Copying file: 'requirements.txt'
Copying file: 'web.2.7.config'
Copying file: 'web.3.4.config'
Copying file: 'flask\helloWorld\.gitignore'
Copying file: 'flask\helloWorld\index.html'
Copying file: 'flask\helloWorld\LICENSE'
Copying file: 'flask\helloWorld\main.py'
Copying file: 'flask\helloWorld\ptvs_virtualenv_proxy.py'
Copying file: 'flask\helloWorld\README.md'
Copying file: 'flask\helloWorld\requirements.txt'
Copying file: 'flask\helloWorld\web.2.7.config'
Copying file: 'flask\helloWorld\web.3.4.config'
Detected requirements.txt.  You can skip Python specific steps with a .skipPythonDeployment file.
Detecting Python runtime from site configuration
Detected python-2.7
Found compatible virtual environment.
Pip install requirements.
Requirement already satisfied (use --upgrade to upgrade): Flask==0.12.1 in d:\home\site\wwwroot\env\lib\site-packages (from -r requirements.txt (line 1))
Cleaning up...
Overwriting web.config with web.2.7.config
        1 file(s) copied.
Finished successfully.
```

**Comment by davidebbo** [comment]
Same as [this thread](https://social.msdn.microsoft.com/Forums/azure/en-US/e10abf9f-64a7-4ab1-a125-ace1ee9f4d6b/deploy-app-under-subdirectory-azure?forum=windowsazurewebsitespreview)?

**Comment by temurih** [comment]
Deployment issue that causing the runtime errors, if that make sense!? lol

**Comment by davidebbo** [comment]
Ok, I think it may be a bug in the Python specific [deployment script](https://github.com/projectkudu/KuduScript/blob/master/lib/templates/deploy.batch.python.template). /cc @huguesv who added that a while back.

**Comment by temurih** [comment]
or it could be something I am doing. lol

**Comment by temurih** [comment]
That worked....!!!!!! Thank you so much!

**Comment by davidebbo** [comment]
Should be fixed in next version of Kudu (change ed6e062a407cd5793e52f261bc666a2d76aa3e81)

**Comment by watashiSHUN** [comment]
I see web.config under root of the repository and under `flask/helloWorld/`
which one do you want to apply @temurih?

**Comment by temurih** [comment]
@watashiSHUN  I thought something is wrong with my web.config files, maybe Azure deployment is not getting them properly. That's why I decided to keep them both places.

**Comment by temurih** [comment]
I actually ran into another problem. Not sure if I have to create another issue.

I successfully able to deploy my testing flask application to Azure, thanks to @davidebbo. But when try to deploy it to my project repository, I am unable to sync the recent changes with the repo.

Here is what I did,

I created a new branch to deploy the Flask App instead of master. I pushed all the changes to the git repository. When I try to choose the branch from `deployment options`, it does not show the newly created branch. Although I can see all the old branches of the project. How can I refresh/sync to my git repo.

**Comment by davidebbo** [comment]
@temurih Are you deploying via GitHub, or by directly pushing to the Azure git repo?

**Comment by temurih** [comment]
via GitHub

**Comment by davidebbo** [comment]
So you mean at the time you first connect your Web App to GitHub, the list of available branches does not include the new one?

**Comment by temurih** [comment]
That sounds about right.

![screenshot](https://user-images.githubusercontent.com/3893769/34898695-9ae75888-f7b1-11e7-8fc6-504ffea67bb9.png)

**Comment by davidebbo** [comment]
I wonder if it's a UI bug where the list can only be so big, and it runs out of space so it doesn't show all of the branches.

Try working around by picking some other branch and then manually editing `D:\home\site\deployments\settings.xml` in Kudu console.

**Comment by temurih** [comment]
Its not a UI bug, I am certain on that. I tried different branch and it is not sync any new changes. It is deploying the branch before the time I added `.deployment` file. It is not longer sync to new changes I make, doesn't matter which branch I push the changes to. It is sticking to the files and changes (version) I had when the first time I authorized GitHub connection with Azure.

Could you please elaborate on Kudu Console part.

**Comment by davidebbo** [comment]
Ok, so now I'm confused. Is the issue about:

1. Inability to choose the branch that you want at the time you set things up with GitHub
2. Problem at sync time where it doesn't reflect the branch that you selected

**Comment by temurih** [comment]
Its actually both.

It is not showing up the branch when I try to deploy using GitHub. So, I tried to push the changes to a branch that is showing up in the list. But then, it does not sync to the new changes pushed to the branch.

**Comment by davidebbo** [comment]
These seem like very different issues, so let's start by only focusing on the list of branches shown in the portal.

When you wrote:

> Its not a UI bug, I am certain on that. I tried different branch and it is not sync any new changes. It is deploying the branch before the time I added .deployment file.

It looks like you were referring to the second issue and not the portal issue. So back to the question I had there about the UI maybe just being out of space.

Also, what's the specific repo where you see this?

**Comment by temurih** [comment]
Even if I share the link, you won't able to see the repo, because its private. So basically, I am deploying from a private Github repository.

**Comment by davidebbo** [comment]
I don't see how that could happen. Is there any chance that you are confusing two repos (e.g. two forks of the same repo), and the one you're trying to connect Azure to is not the one where you are adding the branch?

**Comment by temurih** [comment]
That's actually a good point. I will double check that and get back to you.

**Comment by temurih** [comment]
@davidebbo, I double checked and find out that you are right. I forked the repository to deploy the Flask App, and I forgot about it until you mentioned.

**Comment by davidebbo** [comment]
Glad there was a logical explanation for it all! :)

**Comment by temurih** [comment]
Now, I got into another problem. Not sure where I am screwing up... :(

I am following the same work around as you mentioned. It worked with my testing repository, but it is not working with my actual repository. Any ideas where I might screwed up? I have checked that I am getting all the latest updates. Also, when I try to download the deployment script it gives me this message `Operation only supported if not using a custom deployment script`, which means it is deploying with the correct script that I have provided. But still, it is deploying the root directory of the repo instead of the sub-directory where Flask app is.

My `.deployment` file is same as before, I verified it through GitHub. I have the Flask App under `/src/LSIApp`.

`deploy.cmd`

`@if "%SCM_TRACE_LEVEL%" NEQ "4" @echo off

:: ----------------------
:: KUDU Deployment Script
:: Version: 1.0.15
:: ----------------------

:: Prerequisites
:: -------------

:: Verify node.js installed
where node 2>nul >nul
IF %ERRORLEVEL% NEQ 0 (
  echo Missing node.js executable, please install node.js, if already installed make sure it can be reached from current environment.
  goto error
)

:: Setup
:: -----

setlocal enabledelayedexpansion

SET ARTIFACTS=%~dp0%..\artifacts

IF NOT DEFINED DEPLOYMENT_SOURCE (
  SET DEPLOYMENT_SOURCE=%~dp0%.
)

IF NOT DEFINED DEPLOYMENT_TARGET (
  SET DEPLOYMENT_TARGET=%ARTIFACTS%\wwwroot
)

IF NOT DEFINED NEXT_MANIFEST_PATH (
  SET NEXT_MANIFEST_PATH=%ARTIFACTS%\manifest

  IF NOT DEFINED PREVIOUS_MANIFEST_PATH (
    SET PREVIOUS_MANIFEST_PATH=%ARTIFACTS%\manifest
  )
)

IF NOT DEFINED KUDU_SYNC_CMD (
  :: Install kudu sync
  echo Installing Kudu Sync
  call npm install kudusync -g --silent
  IF !ERRORLEVEL! NEQ 0 goto error

  :: Locally just running "kuduSync" would also work
  SET KUDU_SYNC_CMD=%appdata%\npm\kuduSync.cmd
)
goto Deployment

:: Utility Functions
:: -----------------

:SelectPythonVersion

IF DEFINED KUDU_SELECT_PYTHON_VERSION_CMD (
  call %KUDU_SELECT_PYTHON_VERSION_CMD% "%DEPLOYMENT_SOURCE%\src\LSIApp" "%DEPLOYMENT_TARGET%" "%DEPLOYMENT_TEMP%"
  IF !ERRORLEVEL! NEQ 0 goto error

  SET /P PYTHON_RUNTIME=<"%DEPLOYMENT_TEMP%\__PYTHON_RUNTIME.tmp"
  IF !ERRORLEVEL! NEQ 0 goto error

  SET /P PYTHON_VER=<"%DEPLOYMENT_TEMP%\__PYTHON_VER.tmp"
  IF !ERRORLEVEL! NEQ 0 goto error

  SET /P PYTHON_EXE=<"%DEPLOYMENT_TEMP%\__PYTHON_EXE.tmp"
  IF !ERRORLEVEL! NEQ 0 goto error

  SET /P PYTHON_ENV_MODULE=<"%DEPLOYMENT_TEMP%\__PYTHON_ENV_MODULE.tmp"
  IF !ERRORLEVEL! NEQ 0 goto error
) ELSE (
  SET PYTHON_RUNTIME=python-2.7
  SET PYTHON_VER=2.7
  SET PYTHON_EXE=%SYSTEMDRIVE%\python27\python.exe
  SET PYTHON_ENV_MODULE=virtualenv
)

goto :EOF

::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
:: Deployment
:: ----------

:Deployment
echo Handling python deployment.

:: 1. KuduSync
IF /I "%IN_PLACE_DEPLOYMENT%" NEQ "1" (
  call :ExecuteCmd "%KUDU_SYNC_CMD%" -v 50 -f "%DEPLOYMENT_SOURCE%\src\LSIApp" -t "%DEPLOYMENT_TARGET%" -n "%NEXT_MANIFEST_PATH%" -p "%PREVIOUS_MANIFEST_PATH%" -i ".git;.hg;.deployment;deploy.cmd"
  IF !ERRORLEVEL! NEQ 0 goto error
)

IF NOT EXIST "%DEPLOYMENT_TARGET%\requirements.txt" goto postPython
IF EXIST "%DEPLOYMENT_TARGET%\.skipPythonDeployment" goto postPython

echo Detected requirements.txt.  You can skip Python specific steps with a .skipPythonDeployment file.

:: 2. Select Python version
call :SelectPythonVersion

pushd "%DEPLOYMENT_TARGET%"

:: 3. Create virtual environment
IF NOT EXIST "%DEPLOYMENT_TARGET%\env\azure.env.%PYTHON_RUNTIME%.txt" (
  IF EXIST "%DEPLOYMENT_TARGET%\env" (
    echo Deleting incompatible virtual environment.
    rmdir /q /s "%DEPLOYMENT_TARGET%\env"
    IF !ERRORLEVEL! NEQ 0 goto error
  )

  echo Creating %PYTHON_RUNTIME% virtual environment.
  %PYTHON_EXE% -m %PYTHON_ENV_MODULE% env
  IF !ERRORLEVEL! NEQ 0 goto error

  copy /y NUL "%DEPLOYMENT_TARGET%\env\azure.env.%PYTHON_RUNTIME%.txt" >NUL
) ELSE (
  echo Found compatible virtual environment.
)

:: 4. Install packages
echo Pip install requirements.
env\scripts\pip install -r requirements.txt
IF !ERRORLEVEL! NEQ 0 goto error

REM Add additional package installation here
REM -- Example --
REM env\scripts\easy_install pytz
REM IF !ERRORLEVEL! NEQ 0 goto error

:: 5. Copy web.config
IF EXIST "%DEPLOYMENT_SOURCE%\web.%PYTHON_VER%.config" (
  echo Overwriting web.config with web.%PYTHON_VER%.config
  copy /y "%DEPLOYMENT_SOURCE%\web.%PYTHON_VER%.config" "%DEPLOYMENT_TARGET%\web.config"
)

:: 6. Django collectstatic
IF EXIST "%DEPLOYMENT_TARGET%\manage.py" (
  IF EXIST "%DEPLOYMENT_TARGET%\env\lib\site-packages\django" (
    IF NOT EXIST "%DEPLOYMENT_TARGET%\.skipDjango" (
      echo Collecting Django static files. You can skip Django specific steps with a .skipDjango file.
      IF NOT EXIST "%DEPLOYMENT_TARGET%\static" (
        MKDIR "%DEPLOYMENT_TARGET%\static"
      )
      env\scripts\python manage.py collectstatic --noinput --clear
    )
  )
)

popd

:postPython

::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
goto end

:: Execute command routine that will echo out when error
:ExecuteCmd
setlocal
set _CMD_=%*
call %_CMD_%
if "%ERRORLEVEL%" NEQ "0" echo Failed exitCode=%ERRORLEVEL%, command=%_CMD_%
exit /b %ERRORLEVEL%

:error
endlocal
echo An error has occurred during web site deployment.
call :exitSetErrorLevel
call :exitFromFunction 2>nul

:exitSetErrorLevel
exit /b 1

:exitFromFunction
()

:end
endlocal
echo Finished successfully.
`

**Comment by davidebbo** [comment]
If you look at the deployment log, you can see everything your custom script did, which should help debug and isolate.

BTW, you can use triple backquotes to quote multi-lines. I fixed your previous comment (click edit to see the backquotes).

**Comment by temurih** [comment]
I can't seem to find the `deployment log`, and the search box doesn't give me a helpful result. I found the `Activity log`, but that wasn't very helpful.

Thanks for fixing the comment. :)

**Comment by davidebbo** [comment]
It's under 'Deployment options' (not the best name!). Then click an item to get details.

Or you can get the raw log from Kudu under `D:\home\site\deployments`, and look for the commit id.

**Comment by temurih** [comment]
It all looks alright to me. `KuduSync.NET from: 'D:\home\site\repository\src\LSIApp' to: 'D:\home\site\wwwroot'`

`deployment logs`

```
Command: deploy.cmd
Handling python deployment.
KuduSync.NET from: 'D:\home\site\repository\src\LSIApp' to: 'D:\home\site\wwwroot'
Copying file: '.gitignore'
Copying file: 'LSIApp.py'
Copying file: 'README.md'
Copying file: 'requirements.txt'
Copying file: 'web.2.7.config'
Copying file: 'web.3.4.config'
Detected requirements.txt.  You can skip Python specific steps with a .skipPythonDeployment file.
Detecting Python runtime from site configuration
Detected python-2.7
Found compatible virtual environment.
Pip install requirements.
Requirement already satisfied (use --upgrade to upgrade): wheel in d:\home\site\wwwroot\env\lib\site-packages (from -r requirements.txt (line 1))
Requirement already satisfied (use --upgrade to upgrade): Flask in d:\home\site\wwwroot\env\lib\site-packages (from -r requirements.txt (line 2))
Requirement already satisfied (use --upgrade to upgrade): connexion in d:\home\site\wwwroot\env\lib\site-packages (from -r requirements.txt (line 3))
Cleaning up...
Overwriting web.config with web.2.7.config
        1 file(s) copied.
Finished successfully.
```

**Comment by temurih** [comment]
And it is giving me this error now. `The page cannot be displayed because an internal server error has occurred.`

P.S. It is still deploying the root directory of repo when the log says otherwise.

**Comment by davidebbo** [comment]
When using a custom script, nothing should happen other than the logic that's in your script. Try debugging further by adding various `echo` log statements to your script to make sure it's being used and to see what's going on.
