### ISSUE TITLE
RBAC access role for Kudu logs

### ISSUE THREAD

**Issue by younasmt** [projectkudu/kudu#2665]
Is there any way using custom RBAC access we can enable Kudu Tools/logs for vendors?
Attached (Microsoft.web.txt) are the operations available for "Microsoft.Web" but nothing about Kudu. 
I pulled these using PowerShell.
Any idea, please?

[Microsoft.web.txt](https://github.com/projectkudu/kudu/files/1637662/Microsoft.web.txt)

**Comment by davidebbo** [comment]
Access to Kusu (and scm site in general) is all or nothing today. Note that once you have access to Kudu tools like file explorer and vfs API, you have full control over the site (you can change the content arbitrarily and view all secrets). So if your goal is to give someone access to those tools, just make them a site contributor.

Note that this is not really about Kudu per se, but more about App Service authentication and scm site in general.
