### ISSUE TITLE
https://github.com/projectkudu/kudu/wiki/Deploying-a-WebJob-using-PowerShell-ARM-Cmdlets  trigger web job not working 

### ISSUE THREAD

**Issue by Daniellezha** [projectkudu/kudu#2666]
> For deployment issues, please provide us with the following information:
> ---------------------------------------------------------------

### Repro steps.
> your project built successfully on your dev machine but failed on Azure?
> please write down your build tools and their versions (ie `Msbuild 15.1.0.0`)

### Project structures.
> in order to reproduce your issue at our end we need a simple 
> [github repository](https://github.com/projectkudu/kudu/wiki/Using-a-git-repo-to-report-an-issue)
> that highlights structure of the project

### The log/error given by the failure.
> Normally this include a stack trace, error code and some more information.

### Debug your Azure website remotely.
> it is recommanded that you share your Web App name, directly or [indirectly](https://github.com/projectkudu/kudu/wiki/Reporting-your-site-name-without-posting-it-publicly)
> we can take a look at what's going on.

### Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by Daniellezha** [comment]
From my test, need to use this one to manage webjob actions. 


#Get list of all Webjobs
Get-AzureRmResource -ResourceGroupName $resourceGroupName -ResourceName $webAppName -ResourceType Microsoft.Web/sites/webjobs -ApiVersion $Apiversion 


Invoke-AzureRmResourceAction -ResourceGroupName $resourceGroupName -ResourceType Microsoft.Web/sites/TriggeredWebJobs -ResourceName $webAppName/$webjob -Action run -ApiVersion $Apiversion -Force

**Comment by davidebbo** [comment]
It looks like the left the issue template unmodified. The idea is to fill up the relevant parts to provide information about what your issue is, which is not clear. Even in the follow up entry, you list some PowerShell commands, but there is no info about what behavior you are seeing, and how it differs from what you expected.

Closing for now, but we can reopen if you provide an issue description.
