### ISSUE TITLE
Q: Avoiding log file contention?

### ISSUE THREAD

**Issue by mrichman** [projectkudu/kudu#2669]
How do Azure app services prevent log file contention when scaled out? Wouldn’t ~/App_Data/log.txt be locked for writing by one instance at a time, for example?

**Comment by davidebbo** [comment]
There are two angles to this.

For log files that are generated by App Service, the file names are differentiated by instance ID and process ID, so they don't conflict. e.g. Application Log file names look like `9c676b-9892-636464584072242046.txt`.

For log files where the name is driven by user logic, it's up to the application to do the right thing. e.g. you can use a piece of `%WEBSITE_INSTANCE_ID%` to get a non-conflicting name. App Service typically uses the first 6 characters (that's the `9c676b` in the example above).

**Comment by mrichman** [comment]
Thanks David. So in other words, in order to avoid contention for a single file across instances, we should probably be looking at a centralized log target that isn’t a file on disk. Perhaps Azure Table storage?

**Comment by davidebbo** [comment]
Yes, it's best to avoid the file system if possible. Even for Application Logs, while file system is supported and uses naming schemes to avoid conflicts, we suggest going to blob or table storage instead. Aside from contention, too much disk write can slow things down.
