### ISSUE TITLE
Unable to push to Azure Web App for Container using git

### ISSUE THREAD

**Issue by blueelvis** [projectkudu/kudu#2670]
> For deployment issues, please provide us with the following information:
> ---------------------------------------------------------------

### Repro steps.
> Create PHP project of Drupal and add it to local git.
> Create Web App for Container in Azure using a custom image. Do note that this works fine and is based from the official PHP image.

### Project structures.
> Project structure includes everything like composer packages, drupal core etc.

### The log/error given by the failure.

> </step>
>       <step title="Executing external process" date="2018-01-22T12:35:00.861" type="process" path="starter.sh" arguments="&quot;/home/site/d
> eployments/tools/deploy.sh&quot;" >
>         <step title="Process dump" date="2018-01-22T12:38:22.437" exitCode="1" type="processOutput" />
>       </step>
>       <step title="Error occurred" date="2018-01-22T12:38:22.496" type="error" text="
> /opt/Kudu/bin/Scripts/starter.sh &quot;/home/site/deployments/tools/deploy.sh&quot;" stackTrace="  at Kudu.Core.Infrastructure.Executable.Ex
> ecuteInternal (Kudu.Contracts.Tracing.ITracer tracer, System.Func`2[T,TResult] onWriteOutput, System.Func`2[T,TResult] onWriteError, System.
> Text.Encoding encoding, System.String arguments, System.Object[] args) [0x0018e] in &lt;e1df42f3f8d4400d9fa6e6e5c964fb58&gt;:0
>   at Kudu.Core.Infrastructure.Executable.ExecuteWithProgressWriter (Kudu.Core.Deployment.ILogger logger, Kudu.Contracts.Tracing.ITracer trac
> er, System.String arguments, System.Object[] args) [0x00071] in &lt;e1df42f3f8d4400d9fa6e6e5c964fb58&gt;:0
>   at Kudu.Core.Deployment.Generator.ExternalCommandBuilder.RunCommand (Kudu.Core.Deployment.DeploymentContext context, System.String command
> , System.String message) [0x000ff] in &lt;e1df42f3f8d4400d9fa6e6e5c964fb58&gt;:0 " />
>       <step title="Purge deployment items" date="2018-01-22T12:38:22.755" >
>         <step title="Remove b45f794ed, Failed, received at 01/22/2018 12:21:40" date="2018-01-22T12:38:22.817" />
>       </step>
>     </step>
>     <step title="Error occurred" date="2018-01-22T12:38:22.870" type="error" text="
> /opt/Kudu/bin/Scripts/starter.sh &quot;/home/site/deployments/tools/deploy.sh&quot;" stackTrace="  at Kudu.Core.Infrastructure.Executable.Ex
> ecuteInternal (Kudu.Contracts.Tracing.ITracer tracer, System.Func`2[T,TResult] onWriteOutput, System.Func`2[T,TResult] onWriteError, System.
> Text.Encoding encoding, System.String arguments, System.Object[] args) [0x0018e] in &lt;e1df42f3f8d4400d9fa6e6e5c964fb58&gt;:0
>   at Kudu.Core.Infrastructure.Executable.ExecuteWithProgressWriter (Kudu.Core.Deployment.ILogger logger, Kudu.Contracts.Tracing.ITracer trac
> er, System.String arguments, System.Object[] args) [0x00071] in &lt;e1df42f3f8d4400d9fa6e6e5c964fb58&gt;:0
>   at Kudu.Core.Deployment.Generator.ExternalCommandBuilder.RunCommand (Kudu.Core.Deployment.DeploymentContext context, System.String command
> , System.String message) [0x00131] in &lt;e1df42f3f8d4400d9fa6e6e5c964fb58&gt;:0
>   at Kudu.Core.Deployment.Generator.GeneratorSiteBuilder.Build (Kudu.Core.Deployment.DeploymentContext context) [0x00049] in &lt;e1df42f3f8d
> 4400d9fa6e6e5c964fb58&gt;:0
> --- End of stack trace from previous location where exception was thrown ---
>   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in &lt;4dc8ec68b0964e099af86e50301f5f3c&gt;:0
>   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in &lt;4dc8ec68b0964e099af8
> 6e50301f5f3c&gt;:0

### Mention any other details that might be useful.
It is just not pushing. On push, I receive the following error on the git terminal -

> remote: Processed 13695 files...
> remote: ................
> remote: Processed 15289 files...
> remote: ..........
> remote: Error: ENOENT: no such file or directory, open '/home/site/repository/vendor/bin/phpcs'
> remote: An error has occurred during web site deployment.
> remote: Kudu Sync failed
> remote:
> remote: App container will begin restart within 10 seconds.
> remote: Error - Changes committed to remote repository but deployment to website failed.
> 

Any idea what is happening?

**Comment by nickwalkmsft** [comment]
The push is successful but it's failing during the deployment step.

Can you see if /home/site/repository/vendor/bin/phpcs exists via Kudu Console?

**Comment by blueelvis** [comment]
Yes. It was existing via the Kudu Console and it was failing to delete as well. Had to rescale the app service plan to get the storage unlinked correctly. Even restarting the web app did not fix this issue... I have seen some weird permission denied errors as well while trying to delete a file even when the container web app is stopped.

More info - https://twitter.com/Blueelvis_RoXXX/status/955873765644103680

**Comment by ebibibi** [comment]
I had met similar issue.
My situation is same error and the file is symbolic link to not existing file in azure.
I replaced to actual file and problem solved.

**Comment by blueelvis** [comment]
@nickwalkmsft - It seems the issue is occurring because KuduSync is not able to traverse symlinks properly. This issue becomes more prominent when there is an issue with the Azure Storage in the backend which makes the storage read only for some time and deployments start failing. 

I have raised an issue for Kudusync over here as well - https://github.com/projectkudu/KuduSync/issues/35

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
