### ISSUE TITLE
Azure Default Logs

### ISSUE THREAD

**Issue by temurih** [projectkudu/kudu#2671]
**Not an issue**

I am new to Azure and I deployed a flask application to Azure. Just curious where Azure save the logs if I print (console log) something in the application. Just curious if there is any log folder by default or do I have to setup one of my own?

**Comment by davidebbo** [comment]
I suggest moving the question to [forum](https://social.msdn.microsoft.com/Forums/azure/en-US/home?forum=windowsazurewebsitespreview) or StackOverflow, as this doesn't directly related to Kudu (Kudu handles git deployments and WebJobs).
