### ISSUE TITLE
SiteExtensions are not filtered when using V3 feed

### ISSUE THREAD

**Issue by pakrym** [projectkudu/kudu#2672]
Repro:
1. Add application setting `SCM_SITEEXTENSIONS_FEED_URL` `https://dotnet.myget.org/F/aspnetcore-dev/api/v3/index.json`
2. Go to SCM->Site Extensions->Gallery

Expected:
List is filtered to only siteextension type packages

Actual:
All packages are displayed

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
