### ISSUE TITLE
Restarting the azure web app for container does not change the Site Uptime

### ISSUE THREAD

**Issue by blueelvis** [projectkudu/kudu#2675]
### Repro steps.
> Create a website running on web app for containers
> Open Kudu home page for the website
> Restart the website from the Azure portal.
> Observe that most of the times the site up time is not correct. Even though the container is rebooted, the counter keeps going on.

### Mention any other details that might be useful.
Not sure but this seems to happen a lot. Also, a sure shot way of ensuring that the `Site Uptime` value is changed is by scaling up/down the app service plan.

Also, is it possible for the restart button on the portal be synchronous? As in if I click the `Restart` button on the Overview blade, it will almost instantaneously say that website rebooted even though that is not the case. Ideally, the event should be made synchronous and should only report back that the website has been restarted is when the container is up and running.

**Comment by nickwalkmsft** [comment]
Is this a Linux issue? Please call out or tag with Linux if so.

The restart button is not synchronous. Most likely what you are seeing is Kudu taking a bit to perform its overlapped recycle, during which time the original instance is still running. How long do you wait before checking the counter?

**Comment by blueelvis** [comment]
@nickwalkmsft - I wait for around 5 minutes before checking the counter. Also, the docker logs show that the container started successfully. The counter refreshed after like 5 minutes. Is it possible to reduce this and make the `restart` button synchronous?

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
