### ISSUE TITLE
[Linux] Unable to SSH in Web App for Container from Kudu after scaling out app service plan

### ISSUE THREAD

**Issue by blueelvis** [projectkudu/kudu#2678]
### Repro steps.
> Deploy Linux App Service Plan
> Scale out the App Service Plan (I scaled out to 2 instances)

### The log/error given by the failure.
> The Docker logs from Kudu don't seem to be getting updated.

### Debug your Azure website remotely.
> https://pranav-experimental.azurewebsites.net/

### Mention any other details that might be useful.
On trying to SSH, I get the following in the window after some time -

> SSH CONNECTION CLOSE - Error: read EHOSTUNREACHError: Timed out while waiting for handshakeError: Timed out while waiting for handshakeError:

**Comment by laurabgs1** [comment]
Have you managed to find a workaround or fix for this? I also seem to not be able to do this after scaling out.

**Comment by blueelvis** [comment]
@laurabgs1 - Try again after some time. I figure that the Web App is moved to a different host which can take some time and hence the SSH is not available.

**Comment by salihkaragoz** [comment]
+1  WAITING FOR NEW CONTAINER(S) TO START CREDENTIALS. I'm waiting too much to connect to the VM.
