### ISSUE TITLE
Detected WebJob file/s were updated, refreshing WebJob

### ISSUE THREAD

**Issue by dmcweeney** [projectkudu/kudu#2679]
Hi,

I'm completely confused now! 
I started a "Hello World" web job on Friday, uploaded it as a zip, it ran etc.
Did this through a few iterations.

Then we spent some time working on the VSTS build/deployment steps to get this webjob build and deployed, and eventually got it to deploy with its parent web app.

However after deployment it was appearing as Stopped in the azure portal, and the following was in the logs.

```
Detected WebJob file/s were updated, refreshing WebJob
Status changed to Stopped
```
Back to zipping again and reverted the code to the bare minimum but was still getting the above error.

I tried deploying to a different Azure App Service and it worked there!!!

WebJob is built using .Net Core 2.
Parent Web App is Asp.Net Core 2.

The contents of the zip file I upload is the contents of the **dotnet publish** target folder.
Any ideas how to figure out the above error.
Apologies if this is not the correct place to ask!

```
Using VS 2017 15.5.5
Targetting .NET Core 2
<PackageReference Include="Microsoft.Azure.WebJobs" Version="3.0.0-beta4" />
<PackageReference Include="Microsoft.Azure.WebJobs.Extensions" Version="3.0.0-beta4" />
<PackageReference Include="Microsoft.Extensions.Logging" Version="2.0.0" />
<PackageReference Include="Microsoft.Extensions.Logging.Console" Version="2.0.0" />
```
Dummy site - adummysitetotracewebjobproblem
Real site - starts with b, ends with e

It runs in a different web app in same plan - starts with w ends with n

Thanks

Donal

**Comment by davidebbo** [comment]
It does seem to be in some strange state. If you look at Kudu Process Explorer, it actually appears to be running, but the status is not properly reflected.

Another strange thing is that I see a lot of API calls for both `HelloWorldB` (the WebJob) and `HelloWorldX` (which doesn't exist). I'm curious what would trigger such calls. Is that a different WebJob that you used to have in there?

Can you test whether restarting the Web App puts things back into a good state?

**Comment by davidebbo** [comment]
@dmcweeney or simpler yet, try just 'touching' a file like `run.cmd` from Kudu Console.

**Comment by davidebbo** [comment]
Sorry, I was confused when I said it is running, as I was looking at the `dotnet.exe` process in the mani site and not the scm site. It is not running, and the reason is that you have a `WEBJOBS_STOPPED` app setting that is set to 1. So that is expected behavior. See https://github.com/projectkudu/kudu/wiki/WebJobs#configuration-settings

**Comment by dmcweeney** [comment]
Hi @davidebbo. I restarted the WebApp there now but HelloWorldB is still giving that error. 

HelloWorldX was a different webjob I created with the same zip that also showed the same behaviour. It has since been deleted.

Could WEBJOBS_STOPPED have been set by the App Service?

In out VSTS release tasks we stop all the continuous jobs running before deployment and then another task at the end to start all continuous jobs. So the last good release which was last night should have cleared this flag if it was set.

Thanks

Donal

**Comment by davidebbo** [comment]
@dmcweeney App Service itself will never automatically set `WEBJOBS_STOPPED`. One possibility is that this is something the VSTS release process is doing. e.g.

- May it sets `WEBJOBS_STOPPED` before deploying WebJobs (e.g. to avoid locking issues)
- It does the deployment
- It should then remove `WEBJOBS_STOPPED`, but maybe due to some issue it forgets to do that

I would look at this as a VSTS issue, as the behavior from the App Service / Kudu standpoint looks absolutely normal.

**Comment by davidebbo** [comment]
@vincentdass could you comment on this? @dmcweeney if behavior is confirmed, you may want to open an issue on https://github.com/Microsoft/vsts-tasks/issues/ (and link it here for context).

**Comment by dmcweeney** [comment]
@davidebbo Thanks a million for your very fast solution.
We will do more investigation into the VSTS release issues tomorrow.

Donal

**Comment by vincentdass** [comment]
@dmcweeney , Are you using **Azure App Service Manage task** (Stop/Start continuous webjobs actions) to manage your WebJobs or **Azure PowerShell task**?
Azure App Service Manage task uses WebJobs API to start and stop all continuous Jobs.
Earlier, we provided a workaround to use the WEBJOBS_STOPPED variable using Azure PowerShell.

**Comment by dmcweeney** [comment]
Hi @vincentdass we are using the **Azure App Service Manage** task to stop before deployment and start after deployment. 
We have not been able to reproduce this since but keeping a close eye on it.
