### ISSUE TITLE
Q: Zip deploy and XML transformation

### ISSUE THREAD

**Issue by mrichman** [projectkudu/kudu#2680]
I currently use TFS's inbuilt web app deployment task to push my web apps to app services in Azure. This uses the msdeploy parameters.xml transform to replace certain portions on my web.config at deployment time (app settings, connection strings, and other custom config sections).

I'm experimenting with using Kudu Zip deploy API from within an Azure automation runbook. Basically, i'm doing an HTTP `POST` to `https://$webAppName.scm.azurewebsites.net/api/zipdeploy` with my .zip file.

This works fine, except I have to figure out how to rewrite the contents of the web.config just like I do from TFS at deployment time.

Is this supported somehow?

**Comment by nickwalkmsft** [comment]
No, this is not supported by zipdeploy. The transformation feature is part of msdeploy itself, as opposed to App Service or Kudu.

A few ideas for things you could do instead:
- Perform the transformation on your build server, or wherever it is you are constructing the zip.
- [Customize your deployment script](https://github.com/projectkudu/kudu/wiki/Customizing-deployments) to run a script that performs the desired transformations at deployment time.
- Use App Service app settings for your runtime configuration.

**Comment by mrichman** [comment]
@nickwalkmsft My use case entails parameterized configuration for hundreds of customers, each one unique. So, we don't want to transform at build time, lest we'd have a build output per customer environment. Unfortunately, not all settings are settable as app settings - we have `<system.identityModel>` sections and so forth in our web.configs. The deployment script is not something I've seen before. That looks as though it's specific to deployments from git repos, is that correct?

Alternatively, do you know if there a way to run msdeploy from within an Azure automation runbook?

Thanks!

**Comment by nickwalkmsft** [comment]
Custom deployment scripts work from zipdeploy as well. You just need the .deployment file with the configuration for the custom command inside the zip.

I'm not sure about msdeploy via runbook, @davidebbo might.

**Comment by mrichman** [comment]
Thanks @nickwalkmsft -- so the custom command would presumably be a .ps1 script, but if I wanted that script to edit a web.config at deploy time, I suppose the only way to do it would be to do something like this from within my runbook:

1. `GET` the file I just deployed via the Kudu API at `https://$webAppName.scm.azurewebsites.net/api/vfs/site/wwwroot/app/resources/$fileName`
2. Do my XML transforms as needed
3. `PUT` the edited web.config via the URL from [1].

What do you think?

**Comment by nickwalkmsft** [comment]
Sorry I think I missed something: if you're not generating a build output for each differently-configured environment, where does the per-instance configuration live and how is it applied currently?

If you supply a custom command in the .deployment file, that command is run by Kudu and replaces any deployment script that Kudu would otherwise generate for you (note that for zipdeploy, by default Kudu will only generate a simple script that just does a file copy, as it assumes that the zip contains your entire ready-to-run app). This script is run on the webserver, with local access to all the deployed files. This might be a fit if it were the case that the build output included your web.config template along with the environment configuration: the script would perform the template replacement prior to doing the file copy.

It sounds like what you're thinking of doing is having the _runbook_ run a script after the deployment; I don't see any issue with that.

**Comment by mrichman** [comment]
The per-instance configuration is stored in TFS definition variables as such:

![image](https://user-images.githubusercontent.com/11228/35532744-527f145e-0509-11e8-8fc4-86a39734713b.png)

As part of my App Service deploy task, I use the SetParameters.xml file to transform the web.config:

![image](https://user-images.githubusercontent.com/11228/35532796-7dc336ae-0509-11e8-8687-d3224b24d103.png)

This does a ton of web.config manipulations, using the TFS release definition variables to replace tokens of the same name at deployment time:

```xml
<?xml version="1.0" encoding="utf-8" ?>
<parameters>
    <parameter name="IIS Web Application Name" description="" defaultValue="Default Web Site" />
    <!-- App settings -->
    <parameter name="AuthenticationProvider:WsFedIssuerName" defaultValue="#{AuthenticationProvider:WsFedIssuerName}#">
        <parameterEntry kind="XmlFile" scope="\\Web\.config$" match="/configuration/appSettings/add[@key='AuthenticationProvider:WsFedIssuerName']/@value" />
    </parameter>
    <parameter name="AuthenticationProvider:WsFedCaption" defaultValue="#{AuthenticationProvider:WsFedCaption}#">
        <parameterEntry kind="XmlFile" scope="\\Web\.config$" match="/configuration/appSettings/add[@key='AuthenticationProvider:WsFedCaption']/@value" />
    </parameter>
    <parameter name="AuthenticationProvider:WsFedRealm" defaultValue="#{AuthenticationProvider:WsFedRealm}#">
        <parameterEntry kind="XmlFile" scope="\\Web\.config$" match="/configuration/appSettings/add[@key='AuthenticationProvider:WsFedRealm']/@value" />
    </parameter>
    <parameter name="AuthenticationProvider:WsFedIssuerUri" defaultValue="#{AuthenticationProvider:WsFedIssuerUri}#">
        <parameterEntry kind="XmlFile" scope="\\Web\.config$" match="/configuration/appSettings/add[@key='AuthenticationProvider:WsFedIssuerUri']/@value" />
    </parameter>
    <parameter name="AuthenticationProvider:WsFedCertificateThumbprint" defaultValue="#{AuthenticationProvider:WsFedCertificateThumbprint}#">
        <parameterEntry kind="XmlFile" scope="\\Web\.config$" match="/configuration/appSettings/add[@key='AuthenticationProvider:WsFedCertificateThumbprint']/@value" />
    </parameter>
    <parameter name="AuthenticationProvider:StaffGroupCode" defaultValue="#{AuthenticationProvider:StaffGroupCode}#">
        <parameterEntry kind="XmlFile" scope="\\Web\.config$" match="/configuration/appSettings/add[@key='AuthenticationProvider:StaffGroupCode']/@value" />
    </parameter>
    <parameter name="CnsSsrsBypassInvalidSslCertificate" defaultValue="#{CnsSsrsBypassInvalidSslCertificate}#">
        <parameterEntry kind="XmlFile" scope="\\Web\.config$" match="/configuration/appSettings/add[@key='CnsSsrsBypassInvalidSslCertificate']/@value" />
    </parameter>
    <parameter name="CertificateStoreLocation" defaultValue="#{CertificateStoreLocation}#">
        <parameterEntry kind="XmlFile" scope="\\Web\.config$" match="/configuration/appSettings/add[@key='CertificateStoreLocation']/@value" />
    </parameter>
    <parameter name="WEBSITE_LOAD_CERTIFICATES" defaultValue="#{WEBSITE_LOAD_CERTIFICATES}#">
        <parameterEntry kind="XmlFile" scope="\\Web\.config$" match="/configuration/appSettings/add[@key='WEBSITE_LOAD_CERTIFICATES']/@value" />
    </parameter>
    <parameter name="CnsSsrsWebServiceUrl" defaultValue="#{CnsSsrsWebServiceUrl}#">
        <parameterEntry kind="XmlFile" scope="\\Web\.config$" match="/configuration/appSettings/add[@key='CnsSsrsWebServiceUrl']/@value" />
    </parameter>
    <parameter name="CnsSsrsWSCredentialType" defaultValue="#{CnsSsrsWSCredentialType}#">
        <parameterEntry kind="XmlFile" scope="\\Web\.config$" match="/configuration/appSettings/add[@key='CnsSsrsWSCredentialType']/@value" />
    </parameter>
    <parameter name="CnsSsrsWSUsername" defaultValue="#{CnsSsrsWSUsername}#">
        <parameterEntry kind="XmlFile" scope="\\Web\.config$" match="/configuration/appSettings/add[@key='CnsSsrsWSUsername']/@value" />
    </parameter>
    <parameter name="CnsSsrsWSPassword" defaultValue="#{CnsSsrsWSPassword}#">
        <parameterEntry kind="XmlFile" scope="\\Web\.config$" match="/configuration/appSettings/add[@key='CnsSsrsWSPassword']/@value" />
    </parameter>
    <parameter name="CnsSsrsWSDomain" defaultValue="#{CnsSsrsWSDomain}#">
        <parameterEntry kind="XmlFile" scope="\\Web\.config$" match="/configuration/appSettings/add[@key='CnsSsrsWSDomain']/@value" />
    </parameter>
    <parameter name="CnsSsrsWebPortalUrl" defaultValue="#{CnsSsrsWebPortalUrl}#">
        <parameterEntry kind="XmlFile" scope="\\Web\.config$" match="/configuration/appSettings/add[@key='CnsSsrsWebPortalUrl']/@value" />
    </parameter>
    <parameter name="CnsSsrsReportsFolder" defaultValue="#{CnsSsrsReportsFolder}#">
        <parameterEntry kind="XmlFile" scope="\\Web\.config$" match="/configuration/appSettings/add[@key='CnsSsrsReportsFolder']/@value" />
    </parameter>
    <parameter name="ClientCacheBehavior" defaultValue="Distributed">
      <parameterEntry kind="XmlFile" scope="\\Web\.config$" match="/configuration/appSettings/add[@key='ClientCacheBehavior']/@value" />
    </parameter>
    <parameter name="DistributedCacheConnection" defaultValue="#{DistributedCacheConnection}#">
      <parameterEntry kind="XmlFile" scope="\\Web\.config$" match="/configuration/appSettings/add[@key='DistributedCacheConnection']/@value" />
    </parameter>
    <parameter name="DistributedCacheDatabaseId" defaultValue="0">
      <parameterEntry kind="XmlFile" scope="\\Web\.config$" match="/configuration/appSettings/add[@key='DistributedCacheDatabaseId']/@value" />
    </parameter>
    <parameter name="ClientCacheDefaultExpiration" defaultValue="600">
      <parameterEntry kind="XmlFile" scope="\\Web\.config$" match="/configuration/appSettings/add[@key='ClientCacheDefaultExpiration']/@value" />
    </parameter>
    <parameter name="ProcessBackgroundJobQueue" defaultValue="true">
      <parameterEntry kind="XmlFile" scope="\\Web\.config$" match="/configuration/appSettings/add[@key='ProcessBackgroundJobQueue']/@value" />
    </parameter>
    <!-- Connection strings -->
    <parameter name="CampusModel" defaultValue="#{CampusModel}#">
        <parameterEntry kind="XmlFile" scope="\\Web\.config$" match="/configuration/connectionStrings/add[@name='CampusModel']/@connectionString" />
    </parameter>
    <parameter name="dbConnection" defaultValue="#{dbConnection}#">
        <parameterEntry kind="XmlFile" scope="\\Web\.config$" match="/configuration/connectionStrings/add[@name='dbConnection']/@connectionString" />
    </parameter>
    <parameter name="WorkflowDurableInstancingConnection" defaultValue="#{WorkflowDurableInstancingConnection}#">
        <parameterEntry kind="XmlFile" scope="\\Web\.config$" match="/configuration/connectionStrings/add[@name='WorkflowDurableInstancingConnection']/@connectionString" />
    </parameter>
    <parameter name="WorkflowTrackingConnection" defaultValue="#{WorkflowTrackingConnection}#">
        <parameterEntry kind="XmlFile" scope="\\Web\.config$" match="/configuration/connectionStrings/add[@name='WorkflowTrackingConnection']/@connectionString" />
    </parameter>
    <!-- SMTP -->
    <parameter name="SmtpHost" defaultValue="#{SmtpHost}#">
      <parameterEntry kind="XmlFile" scope="\\Web\.config$" match="/configuration/system.net/mailSettings/smtp/network/@host" />
    </parameter>
    <parameter name="SmtpUsername" defaultValue="#{SmtpUsername}#">
      <parameterEntry kind="XmlFile" scope="\\Web\.config$" match="/configuration/system.net/mailSettings/smtp/network/@userName" />
    </parameter>
    <parameter name="SmtpPassword" defaultValue="#{SmtpPassword}#">
      <parameterEntry kind="XmlFile" scope="\\Web\.config$" match="/configuration/system.net/mailSettings/smtp/network/@password" />
    </parameter>
    <parameter name="SmtpSsl" defaultValue="false">
      <parameterEntry kind="XmlFile" scope="\\Web\.config$" match="/configuration/system.net/mailSettings/smtp/network/@enableSsl" />
    </parameter>
    <parameter name="SmtpPort" defaultValue="587">
      <parameterEntry kind="XmlFile" scope="\\Web\.config$" match="/configuration/system.net/mailSettings/smtp/network/@port" />
    </parameter>
    <!-- NLog -->
    <parameter name="NLog_Filename" defaultValue="${basedir}/logs/${machinename}-Cmc.Nexus.AdaptiveLog.txt">
      <parameterEntry kind="XmlFile" scope="\\NLog\.config$" match="//*[local-name()='target'][1]/@fileName" />
    </parameter>
    <parameter name="NLog_ArchiveFilename" defaultValue="${basedir}/logs/${machinename}-Cmc.Nexus.AdaptiveLog.{#####}.txt">
      <parameterEntry kind="XmlFile" scope="\\NLog\.config$" match="//*[local-name()='target'][1]/@archiveFileName" />
    </parameter>
</parameters>
```
As complicated as this appears, it actually works perfectly. I just can't orchestrate deployments using TFS the way I need, so I'm looking at the runbook approach.

**Comment by nickwalkmsft** [comment]
Got it. I assume that somehow in the runbook you will have access to the per-environment configuration? Runbooks are just scripts; in your script, could you extract the web.config from the zip, perform the transformation you need, and replace it before sending it off for deployment? This is actually one of the advantages of zips, you can manipulate them after they are built if it makes sense for your workflow.

**Comment by mrichman** [comment]
My idea is to store the per-environment configs in Key Vault. I don't see why I couldn't manipulate the .zip contents pre-deploy.

**Comment by nickwalkmsft** [comment]
Definitly. [ZipArchive](https://msdn.microsoft.com/en-us/library/system.io.compression.ziparchive(v=vs.110).aspx) should make this fairly simple and efficient.

I'm going to close this; feel free to comment back if you have any more questions or open a new issue if you run into anything else.

**Comment by mrichman** [comment]
Thanks @nickwalkmsft  much appreciated!
