### ISSUE TITLE
[Linux] Improve the quality of SSH Experience from the Kudu Website

### ISSUE THREAD

**Issue by blueelvis** [projectkudu/kudu#2683]
Request to enhance the SSH experience from the Kudu website to Azure web app for containers. Thanks!!!

### Repro steps.
> Deploy Azure Web app on container
> Try to access the SSH link on a widescreen monitor.

### Issues
1. The SSH console does not scale up/down as per window size.
2. Frequent connection drops during the SSH session which requires reloading the tab/browser window.
3. Copy pasting doesn't work properly in Nano. Same text pasted from different browsers gets pasted in different ways. It works fine in Vim though...
4. Overlap/layout issues.

**Comment by suwatch** [comment]
@michimune  mind commenting on this? if any improvement, eta for delivery and so on?

**Comment by michimune** [comment]
One alternative way is that you can now directly use SSH from your command line: https://blogs.msdn.microsoft.com/appserviceteam/2018/05/07/remotedebugginglinux/

Apparently this doesn't have terminal related issues like the window size. I am not sure about the connection drops, but please give it a try and provide feedback.

**Comment by blueelvis** [comment]
@michimune  -- Wao!! You guys are on a release spree! I will try this out and let you know with the feedback!

Thanks!!

**Comment by blueelvis** [comment]
@michimune - This works like a charm! Extremely fast and feels like native SSH experience which is what was expected from this.

Although, one minor issue. When I typed in `exit` in the terminal, I saw the following on the PowerShell window -
```
PS C:\Users\Pranav> az webapp remote-connection create -g "AAAA-Drupal-USEast2" -n "AAAA" -p 1234
Port 1234 is open
SSH is available { username: root, password: Docker! }
Start your favorite client and connect to port 1234
Websocket tracing disabled, use --verbose flag to enable
Successfully connected to local server..
Client disconnected 1
Stopped local server..
Websocket tracing disabled, use --verbose flag to enable
Client disconnected 2
Successfully connected to local server..
Traceback (most recent call last):
  File "E:\AAAA\AAAA\VSTS\Dev\src\.azure\cliextensions\webapp\azext_webapp\tunnel.py", line 151, in listen_to_web_socket
    client.sendall(response)
OSError: [WinError 10038] An operation was attempted on something that is not a socket
Stopped local server..
```

Also, not sure why the Traceback call is from a folder which is of another project and is integrated with VSTS. I don't know how the `.azure` folder is in there as well!

Overall, brilliant work guys! I think we can close this issue as well.

**Comment by blueelvis** [comment]
@michimune - Not sure but for apps on 1 ASP in my subscription, the remote SSH is not working at all. I have rescaled the App Service Plan as well but it is not working. The SSH experience through the portal is working though.

Could you please take a look? https://pranav-linux-drupal.azurewebsites.net

```
PS E:\dev\kudu> az webapp remote-connection create --resource-group "Pranav-Test" -n "pranav-linux-drupal" -p 1234
Port 1234 is open
Exception in thread Thread-1:
Traceback (most recent call last):
  File "threading.py", line 916, in _bootstrap_inner
  File "threading.py", line 864, in run
  File "E:\AAA\VSTS\Dev\src\.azure\cliextensions\webapp\azext_webapp\custom.py", line 270, in _start_tunnel
    if not _check_for_ready_tunnel(remote_debugging_enabled, tunnel_server):
  File "E:\AAA\VSTS\Dev\src\.azure\cliextensions\webapp\azext_webapp\custom.py", line 240, in _check_for_ready_tunnel
    default_port = tunnel_server.is_port_set_to_default()
  File "E:\AAA\VSTS\Dev\src\.azure\cliextensions\webapp\azext_webapp\tunnel.py", line 95, in is_port_set_to_default
    raise CLIError("Failed to connect to '{}' with status code '{}' and reason '{}'".format(url, r.status, r.reason))
knack.util.CLIError: Failed to connect to 'https://pranav-linux-drupal.scm.azurewebsites.net/AppServiceTunnel/Tunnel.ashx?GetStatus' with status code '503' and reason 'Service Unavailable'

Terminate batch job (Y/N)? ^C
PS E:\dev\kudu>
```

![image](https://user-images.githubusercontent.com/6985763/42728209-daf8b1ea-87d2-11e8-9cdd-0c0c65fb66b0.png)

When I visit this url `https://pranav-linux-drupal.scm.azurewebsites.net/AppServiceTunnel/Tunnel.ashx?GetStatus`, it actually gives me a 503. I also see that Kudu's version is up to date.
