### ISSUE TITLE
Restart couple of minutes after successful autoswap

### ISSUE THREAD

**Issue by siroky** [projectkudu/kudu#2687]
We're observing strange restarts of our instances after successful autoswap. It happens cca 5 minutes after successful swap, which effectively cancels the benefits of deployments using slots. There is no downtime during the deployment itself which is great, but several minutes later we have downtime because of the restart.

I've tried everything form this part of KUDU configuration (using the `.deployment` file): https://github.com/projectkudu/kudu/wiki/Configurable-settings#disable-the-generation-of-bindings-in-applicationhostconfig

If we turn on the first option `WEBSITE_SKIP_ALL_BINDINGS_IN_APPHOST_CONFIG`, our WCF services start failing with a protocol error. I can provide further details or reproduce it on our playground environment if needed. Lately the second option `WEBSITE_ADD_SITENAME_BINDINGS_IN_APPHOST_CONFIG` appeared, we tried it, there are no longer issues with WCF, but the restarts are still happening.

Can you please elaborate more, what do the settings actually do? The documentation is very brief. Or suggest how can we solve the restarts? Our app is business-critical for our users and random restarts after deployments are unacceptable for them.

**Comment by davidebbo** [comment]
As a test, does the same happen if you don't do a deployment, and manually do a swap? i.e. do you end up getting downtime in production? That would isolate from anything related to Kudu.

**Comment by ruslany** [comment]
As of last couple of weeks the WEBSITE_ADD_SITENAME_BINDINGS_IN_APPHOST_CONFIG is enabled by default for all webapps so you do not need to add it explicitly. With that enabled there should not be any restarts after the swap. 

Please [share your site name](https://github.com/projectkudu/kudu/wiki/Reporting-your-site-name-without-posting-it-publicly) and I'll check what's causing the restart.

**Comment by siroky** [comment]
Sorry, now I realized that on production environments we swap the slots manually and the restart happens cca 5 minutes after the swap. The site name where we observe this is https://mews-prod-weu.azurewebsites.net/ On non-production environments of our app, we have autoswap configured and don't see any restarts.

I'll try to do just the swap without deployment and let you know with the results.

**Comment by siroky** [comment]
Hi, while the first version V1 was running, I tried deploying a newer version V2 and doing couple of manual swaps. This is the outcome:
![image](https://user-images.githubusercontent.com/435787/35782629-f5aa6534-09fa-11e8-8973-c12c993c0afe.png)

S1) Manual swap after the deployment V1 -> V2.
R1) Restart after the deployment.
S2) Manual swap to the previous version (no deployment) V2 -> V1.
S3) Another manual swap to the new version (no deployment) V2 -> V1.
R2) Another restart.

In our app, we log every initialization and termination, so I also have logs that correspond to the events described above with exact times, instance numbers and process numbers. I can provide them as well if that would be of any help. Thanks.

**Comment by davidebbo** [comment]
@siroky note that site restarts during swaps are absolutely normal, but they should not happen in a way that affects Production. See https://github.com/projectkudu/kudu/wiki/Understanding-site-swaps for more details.

It is not clear from your last response whether you are describing restarts that affect Prod or not. Just the fact that you see a restart in your logs is not a concern in itself.

**Comment by siroky** [comment]
The restarts happen after successful swap in the production slot so the app performance is affected. Before the swap, the new version is warmed up correctly, then swap occurs, requests start hitting new version, the app is running correctly for several minutes and then it's suddenly restarted, seemingly for no reason.

**Comment by siroky** [comment]
NewRelic, which we use for performance monitoring, shows really similar graphs. Here's for example one of our instances:

![image](https://user-images.githubusercontent.com/435787/35783110-8f866296-0a02-11e8-9d97-27d216c325e8.png)

**Comment by davidebbo** [comment]
Yeah, this additional restart several minutes later is odd. In addition to your site name (mews-prod-weu), can you provide the UTC time where you observed this behavior? This will help @ruslany investigate what's going on (I see times on your image, but it's not clear what day and timezone they're for).

**Comment by siroky** [comment]
We have multiple instances, so I picked the `RD0003FF1F32AF`. Note that in the following logs, the times are in UTC and we log it within `Application_Start`. The version is a commit hash, so it's pretty clear from the logs that the second and fifth initialization is actually a restart, because the version is same as the previous one.  Those are the five initializations that happened during three manual swaps:

```
[04.02.2018 20:28:33.0953885 | INFO | mews-prod-weu/live/RD0003FF1F32AF/3c6fe205-dbc0-495d-9567-91cb6f64a2eb] [server] Initializing. {"Version":"f10b2e28ce","Process":684,"Roles":[],"Details":{"RequestUrl":null}}}
[04.02.2018 20:34:10.3179333 | INFO | mews-prod-weu/live/RD0003FF1F32AF/fffa3166-38af-4798-9dfb-4b1a75e1ea79] [server] Initializing. {"Version":"f10b2e28ce","Process":684,"Roles":[],"Details":{"RequestUrl":null}}}
[04.02.2018 20:48:45.1585005 | INFO | mews-prod-weu/live/RD0003FF1F32AF/7bfcbe26-6cdd-4a1c-b9ea-669784a1120c] [server] Initializing. {"Version":"a84f3209ad","Process":5880,"Roles":[],"Details":{"RequestUrl":null}}}
[04.02.2018 21:07:16.5297256 | INFO | mews-prod-weu/live/RD0003FF1F32AF/0026674c-1e01-4415-a4f1-8febef590899] [server] Initializing. {"Version":"f10b2e28ce","Process":5808,"Roles":[],"Details":{"RequestUrl":null}}}
[04.02.2018 21:16:09.7242646 | INFO | mews-prod-weu/live/RD0003FF1F32AF/559e4da6-2c76-4f33-b6f0-f80b637b16dd] [server] Initializing. {"Version":"f10b2e28ce","Process":5808,"Roles":[],"Details":{"RequestUrl":null}}}
```

**Comment by ruslany** [comment]
@siroky - I am looking into this. Will let you know what I find.

**Comment by siroky** [comment]
@ruslany Thanks, if you need anything specific or internal, feel free to email me.

**Comment by ruslany** [comment]
@siroky - this turned out to be a bug in our code. We'll work on fixing this. Meanwhile if you add this app setting to ALL deployment slots of that site it should help with restarts:

WEBSITE_ADD_SITENAME_BINDINGS_IN_APPHOST_CONFIG = 1.

**Comment by siroky** [comment]
We already have it in .deployment file. Is the workaround to put it directly to app settings?

**Comment by ruslany** [comment]
Yes, set this appsetting via Azure Portal or via Powershell/CLI. I checked your site's configuration and I do not see it set for any slot.

**Comment by siroky** [comment]
So we tested it and didn't notice any restart after deployment, except one around `07.02.2018 23:47:56.8787535 UTC`. But that happened on all our apps in West Europe, no matter if they were deployed or not so I guess it was unrelated to the deployment.

**Comment by ruslany** [comment]
Great, thanks for confirming. The unrelated restart may have been because of an upgrade that was going on in that scale unit.

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
