### ISSUE TITLE
function API. Create or update function. Wrong documentation example on wiki

### ISSUE THREAD

**Issue by kastwey** [projectkudu/kudu#2688]
In https://github.com/projectkudu/kudu/wiki/Functions-API, in the create or update a function, the example includes the config, file and test-data inside a node called "properties". However, in the FunctionManager.cs code, on CreateOrUpdateAsync method , in the FunctionEnvelope parameter Object, this property is not present.
Changing the example and removing this encapsulation, the function Works propperly.

Good example:
```json
{
	"location": "West US",
	"config": {
		"bindings": [
			{
				"webHookType": "genericJson",
				"type": "httpTrigger",
				"direction": "in",
				"name": "req"
			},
			{
				"type": "http",
				"direction": "out",
				"name": "res"
			}
		]
	},
	"files": {
		"index.js": "module.exports = function (context, data) {\r\n    context.res = {\r\n        body: { greeting: 'Hello ' + data.first + ' ' + data.last + '!'}\r\n    };\r\n\r\n    context.done();\r\n};\r\n"
	},
	"test_data": "{ 'first': 'David', 'last': 'Ebbo' }"
}
```

I tested it with my own Project and with this example all Works.

Thanks!

Juanjo.

**Comment by davidebbo** [comment]
@kastwey Are you calling the API via ARM, or directly on Kudu? The documentation is referring to the ARM call, and I believe having the `properties` is indeed necessary.

    put /subscriptions/{sub}/resourceGroups/{rg}/providers/Microsoft.Web/sites/{functionapp}/functions/MyFunction?api-version=2015-08-01

**Comment by kastwey** [comment]
Oh! I thought the structure of the call would be the same! I'm sorry! :)
Yes, I'm actually using a kudu call.
Is there documentation for function api by using kudu?
Thank you and forgive the confusion!

Juanjo.

**Comment by davidebbo** [comment]
I just added a note at the top that explains how to call it via Kudu endpoint.
