### ISSUE TITLE
Impossible to install newer site extension version from a custom feed

### ISSUE THREAD

**Issue by pakrym** [projectkudu/kudu#2689]
Repro.
1. Set `SCM_SITEEXTENSIONS_FEED_URL` to `https://dotnet.myget.org/F/aspnetcore-release/`
2. Go to scm, Site Extensions, Gallery, Seach for `Microsoft.AspNetCore.AzureAppServices.SiteExtension`
![image](https://user-images.githubusercontent.com/1697911/36053423-89307704-0da6-11e8-8b07-4b6e0ca20640.png)
4. Two entries for the same package would be displayed which is a bug in itself
5. Click install on `2.1-preview1-*` package
6. Go back to `Installed` page

![image](https://user-images.githubusercontent.com/1697911/36053543-de649fca-0da6-11e8-967e-a2eb7dd4237b.png)

### Expected: 
`2.1-preview1-*` package installed

### Actual 
`2.0.1` package installed

**Comment by davidebbo** [comment]
Yes, that's odd. Can you check if you're able to install it via API? e.g. (using a different example I had somewhere):

    curl -X PUT -H "Content-Type: application/json" --data "{ version:'1.0.16', feed_url:'https://www.myget.org/F/siteextensions-test/' }" %KUDU_URL%/api/siteextensions/FileCounter

**Comment by pakrym** [comment]
I was able to do it via ARM

**Comment by davidebbo** [comment]
Yep, so it would have worked via Kudu API as well. I think the issue is that the UI doesn't have the smarts to properly deal with pre-release versions.

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
