### ISSUE TITLE
Deploying a Docker Image from Container Registry

### ISSUE THREAD

**Issue by temurih** [projectkudu/kudu#2690]
I have pushed a working docker image to Azure Container Registry. I followed [this tutorial](https://docs.microsoft.com/en-us/azure/container-registry/container-registry-tutorial-deploy-app) to deploy it as a web application.

I followed the steps and it created a new web application, but it does not contain any files other than default Azure html that says `Your App Service app is up and running`. I am trying to figure out what went wrong. I checked the `Activity logs` and it says nothing. I checked the debug console `<my-site>.scm.azurewebsites.net`, and it does not contain any of the `Docker Image` files. How can I check what went wrong during the deployment?

**Comment by LukaszStem** [comment]
Could you try something for me? For your image name enter "**my.acr.io**/imagename:tag" if no tag is specified it will default to latest. Replace the respective fields with your acr repo and imagename/tag.

**Comment by temurih** [comment]
Okay, so here is what I did.

- I created a docker image, lets just call it `my-image`.
- I checked it is working fine on my local machine.
- I created a new tag to push the image to acr, `docker tag <my-image_id> my-acr-username.azurecr.io/my-image`.
- Then I pushed it to acr, `docker push my-acr-username.azurecr.io/my-image`
- I checked the acr repository to verify if it is pushed successfully.
- Then I followed the mentioned tutorial to deploy the image.

Let me know what do you want me to differently.

**Comment by temurih** [comment]
@LukaszStem , Any updates?

**Comment by LukaszStem** [comment]
In the mentioned tutorial, during the initial step of creating a webapp through the portal, you have a field for "Site name", "Subscription", etc. In the "Image" field, I'm assuming you just have just `my-image`. Instead please try using `my-acr-username.azurecr.io/my-image`

**Comment by temurih** [comment]
That's a readonly input field. I can't edit unless you want me to edit the html. I could do that, but hopefully that wouldn't screw up anything.

**Comment by temurih** [comment]
Well, I did it anyway. But unfortunately that didn't work either.

**Comment by LukaszStem** [comment]
Are you okay to share your site name? This way I can go in and investigate from my side.

**Comment by temurih** [comment]
[https://lsiapplication.azurewebsites.net/](SIte URL)

**Comment by temurih** [comment]
@LukaszStem is that what you were asking, right?

**Comment by LukaszStem** [comment]
Yes. Sorry for delay, taking a look.

**Comment by LukaszStem** [comment]
Can you retry with a new resource group? Instead of using Existing.

**Comment by LukaszStem** [comment]
@temurih your app won't work since we do not support windows containers

**Comment by temurih** [comment]
That explains a lot. But at least it should errors out or give warning or something. Anyways, thanks!
