### ISSUE TITLE
[Linux] Sometimes, files become read only on Web App for Containers

### ISSUE THREAD

**Issue by blueelvis** [projectkudu/kudu#2696]
The project is a composer based PHP project.

The issue is that sometimes, randomly, a folder/file will become only readable. This doesn't happen always but happens sometimes which requires manual intervention like changing the attributes using `chmod`. I have to go into SSH and then again change the attributes and then they get deleted fine.

```
root@047478e3405c:/home/site/wwwroot# cd ..
root@047478e3405c:/home/site# rm wwwroot/ -r
rm: cannot remove 'wwwroot/sites/default': Permission denied
root@047478e3405c:/home/site# ls
config  diagnostics  ipaddr_0  locks  packages.json  wwwroot
root@047478e3405c:/home/site# cd wwwroot/
root@047478e3405c:/home/site/wwwroot# ls
sites
root@047478e3405c:/home/site/wwwroot# ls -la
total 8
drwxrwxrwx 2 nobody nogroup 4096 Feb 13 20:31 .
drwxrwxrwx 2 nobody nogroup 4096 Feb 13 20:31 ..
drwxrwxrwx 2 nobody nogroup    0 Feb 13 20:24 sites
root@047478e3405c:/home/site/wwwroot# cd sites
root@047478e3405c:/home/site/wwwroot/sites# ls
default
root@047478e3405c:/home/site/wwwroot/sites# ls -la
total 8
drwxrwxrwx 2 nobody nogroup 4096 Feb 13 20:24 .
drwxrwxrwx 2 nobody nogroup 4096 Feb 13 20:31 ..
dr-xr-xr-x 2 nobody nogroup    0 Feb 13 20:24 default
root@047478e3405c:/home/site/wwwroot/sites# chmod +w default
root@047478e3405c:/home/site/wwwroot/sites# ls -l
total 0
drwxrwxrwx 2 nobody nogroup 0 Feb 13 20:24 default
root@047478e3405c:/home/site/wwwroot/sites# rm -r default
root@047478e3405c:/home/site/wwwroot/sites# cd ..
```

I have enabled the Website App Storage and set it to `TRUE` but it still happens sometimes randomly. Any idea what might be happening?

**Comment by benjamingeorgedanielryan** [comment]
I have a similar problem with my linux webapp. After finding out about WEBSITES_ENABLE_APP_SERVICE_STORAGE (that took way too long) and setting to true, when i try and use file storage within my app, I get permission denied trying to write a file to the /home directory.
`/>ls -l 
total 272
drwxr-xr-x   2 root                     root                       4096 Feb  6 01:25 bin
drwxr-xr-x   2 root                     root                       4096 Nov 19 15:32 boot
drwxr-xr-x   5 root                     root                        340 Mar 13 23:34 dev
drwxr-xr-x  98 root                     root                       4096 Mar 13 23:34 etc
drwxrwxrwx   2 nobody                   nogroup                       0 Dec 12 20:12 home
drwxr-xr-x  17 root                     root                       4096 Feb  6 01:25 lib
drwxr-xr-x   2 root                     root                       4096 Dec 10 00:00 lib64
drwxr-xr-x   2 root                     root                       4096 Dec 10 00:00 media
drwxr-xr-x   2 root                     root                       4096 Dec 10 00:00 mnt
-rwxr-xr-x   1 root                     root                     210760 Apr 10  2017 mod_mono.so.0.0.0
drwxr-xr-x  10 root                     root                       4096 Mar 13 23:34 opt
dr-xr-xr-x 156 nobody                   nogroup                       0 Mar 13 23:34 proc
drwx------  13 root                     root                       4096 Mar 13 23:35 root
drwxr-xr-x   5 root                     root                       4096 Mar 13 23:34 run
drwxr-xr-x   2 root                     root                       4096 Feb  6 01:25 sbin
drwxr-xr-x   2 root                     root                       4096 Dec 10 00:00 srv
-rwxr-xr-x   1 root                     root                       2182 Feb  6 01:01 startup.sh
dr-xr-xr-x  13 nobody                   nogroup                       0 Mar 13 22:40 sys
drwxrwxrwt   9 1f2504e13c32e8676d0b99d7 1f2504e13c32e8676d0b99d7   4096 Mar 14 00:49 tmp
drwxr-xr-x  54 root                     root                       4096 Feb  6 01:26 usr
drwxr-xr-x  37 root                     root                       4096 Mar 13 23:34 var
/>cd home
/home>touch whyisthisnotworking.txt
touch: cannot touch 'whyisthisnotworking.txt': Permission denied

/home> `
As you can see the /home directory has full access permissions. But from my linux container and in the Kudu console, I cannot write to  /home... how does that even happen?
I'm not even an `other`?

**Comment by blueelvis** [comment]
So for one of the test Web App for Container, the files seem to be there but not *actually* there -

```
root@0803a30219ea:/home/site# rm -rf wwwroot
rm: cannot remove 'wwwroot/vendor/bin': Directory not empty
root@0803a30219ea:/home/site# cd wwwroot/
root@0803a30219ea:/home/site/wwwroot# ls
vendor
root@0803a30219ea:/home/site/wwwroot# cd vendor
root@0803a30219ea:/home/site/wwwroot/vendor# ls
bin
root@0803a30219ea:/home/site/wwwroot/vendor# cd bin
root@0803a30219ea:/home/site/wwwroot/vendor/bin# ls -la
ls: cannot access dcg: No such file or directory
ls: cannot access drush: No such file or directory
ls: cannot access php-parse: No such file or directory
total 12
drwxrwxrwx 2 nobody nogroup 4096 Jun 24 20:41 .
drwxrwxrwx 2 nobody nogroup 8192 Jun 24 20:42 ..
-????????? ? ?      ?          ?            ? dcg
-????????? ? ?      ?          ?            ? drush
-????????? ? ?      ?          ?            ? php-parse
root@0803a30219ea:/home/site/wwwroot/vendor/bin# cd ..
root@0803a30219ea:/home/site/wwwroot/vendor# ls -la
total 12
drwxrwxrwx 2 nobody nogroup 8192 Jun 24 20:42 .
drwxrwxrwx 2 nobody nogroup 4096 Jun 24 20:42 ..
drwxrwxrwx 2 nobody nogroup    0 Jun 24 20:41 bin
root@0803a30219ea:/home/site/wwwroot/vendor# rm -rf bin
rm: cannot remove 'bin': Directory not empty
root@0803a30219ea:/home/site/wwwroot/vendor# cd bin
root@0803a30219ea:/home/site/wwwroot/vendor/bin# ls
dcg  drush  php-parse
root@0803a30219ea:/home/site/wwwroot/vendor/bin# ls -la
ls: cannot access dcg: No such file or directory
ls: cannot access drush: No such file or directory
ls: cannot access php-parse: No such file or directory
total 12
drwxrwxrwx 2 nobody nogroup 4096 Jun 24 20:41 .
drwxrwxrwx 2 nobody nogroup 8192 Jun 24 20:42 ..
-????????? ? ?      ?          ?            ? dcg
-????????? ? ?      ?          ?            ? drush
-????????? ? ?      ?          ?            ? php-parse
root@0803a30219ea:/home/site/wwwroot/vendor/bin#
```

Because of this, 
1. Unable to do any Git deployments
2. Tried multiple reboots of the Web App but no success. The only way I see that is to Scale/up/down the App Service plan and then delete because then the backend CIFS mounted storage will be unmounted and remounted.
3. Tried the delete operation from the Kudu (Bash) container as well but no success.

I cannot scale up or down the App Service Plan as of now because it hosts some other Non Prod applications.

@davidebbo @rramachand21 - Any idea what might be happening? I suspect issues with the CIFS mounts between OS distributions. In this case, I am using Docker image based on top of official PHP 7.1 image.

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
