### ISSUE TITLE
Allow to Publish local.settings.json using ZIP deployment

### ISSUE THREAD

**Issue by vivek201** [projectkudu/kudu#2698]
### Repro steps.
Deploying with [ZIP deployment](https://github.com/projectkudu/kudu/wiki/Deploying-from-a-zip-file) should allow to publish local.settings.json like the [Azure CLI Tools](https://docs.microsoft.com/en-us/azure/azure-functions/functions-run-local#publish) does.

If there is a way to do so using the ZIP deployment, can someone point me to the docs?

**Comment by davidebbo** [comment]
Generally, zip deployment knows nothing about Functions or about local.settings.json. Its only purpose is to take a fully cooked zip file and make sure that its content ends up deployed into wwwroot. Any fancier behavior needs to come in how you build your zip so it has the files that you want.
