### ISSUE TITLE
The WEBSITE_NODE_DEFAULT_VERSION is not respect in azure function runtime.

### ISSUE THREAD

**Issue by lijunle** [projectkudu/kudu#2701]
I am declaring `WEBSITE_NODE_DEFAULT_VERSION=8.9.4` in my `.deployment` file. It is working well in Kudo console and deployment log (with NPM@5 output).

However, the azure function runtime is still using version 6.11.2. I get this version number with my runtime `process.version` output.

![default](https://user-images.githubusercontent.com/1296500/36268335-250d340a-12b1-11e8-9886-254279a15814.png)

![default](https://user-images.githubusercontent.com/1296500/36268313-1a4e8136-12b1-11e8-8335-343297b88eb1.png)

**Comment by davidebbo** [comment]
Yes, the Functions runtime is not driven by this flag. Functions v1 uses v6.11.2. With the v2 runtime (in Preview), you can choose a v8.x Node version.

**Comment by lijunle** [comment]
@davidebbo Thank you for your information! How can I upgrade my function from v1 to v2?

**Comment by davidebbo** [comment]
You'll need to create a new Function App, and change it to "Beta" under Functions App Settings (before you create any Functions in it).

**Comment by lijunle** [comment]
I see. Thank you! I will try it!


----------
On February 17, 2018 2:13:03 AM David Ebbo <notifications@github.com> wrote:

You'll need to create a new Function App, and change it to "Beta" under 
Functions App Settings (before you create any Functions in it).
