### ISSUE TITLE
[Linux] Enable MySQL extension in Bash Container for Kudu

### ISSUE THREAD

**Issue by blueelvis** [projectkudu/kudu#2702]
### Repro steps.
> Drupal Project with Drush installed.
> Type in -- `drush.phar --root="$DEPLOYMENT_TARGET" status -v` at the directory where `drush.phar` is installed

### Project structures.
> Drupal Project with Drush installed.

### The log/error given by the failure.
```
Error: Undefined class constant 'MYSQL_ATTR_SSL_CA' in phar:///home/site/drush.phar/lib/Drush/Sql/Sqlmysql.php on line 56 #0 phar:///home/site/drush.phar/lib/Drush/Sql/SqlBase.php(165): Drush\Sql\Sqlmysql->creds()
#1 phar:///home/site/drush.phar/includes/environment.inc(393): Drush\Sql\SqlBase->query('SELECT 1;')
#2 phar:///home/site/drush.phar/lib/Drush/Boot/DrupalBoot.php(462): drush_valid_db_credentials()
#3 phar:///home/site/drush.phar/lib/Drush/Boot/DrupalBoot8.php(109): Drush\Boot\DrupalBoot->bootstrap_drupal_database_validate()
#4 phar:///home/site/drush.phar/includes/bootstrap.inc(430): Drush\Boot\DrupalBoot8->bootstrap_drupal_database_validate()
#5 phar:///home/site/drush.phar/includes/bootstrap.inc(507): drush_bootstrap_validate(4)
#6 phar:///home/site/drush.phar/includes/bootstrap.inc(456): drush_bootstrap_max()
#7 phar:///home/site/drush.phar/lib/Drush/Boot/BaseBoot.php(59): drush_bootstrap_to_phase(-2)
#8 phar:///home/site/drush.phar/includes/preflight.inc(66): Drush\Boot\BaseBoot->bootstrap_and_dispatch()
#9 phar:///home/site/drush.phar/includes/startup.inc(462): drush_main()
#10 phar:///home/site/drush.phar/includes/startup.inc(369): drush_run_main(false, '/', 'Phar detected. ...')
#11 phar:///home/site/drush.phar/drush(114): drush_startup(Array)
#12 /home/site/drush.phar(10): require('phar:///home/si...')
#13 {main}
Drush command terminated abnormally due to an unrecoverable error.       [error]
```

### Mention any other details that might be useful.
This is because the `php7.1-mysql` package is not enabled/installed on the Kudu container. Any chance if this could be enabled because Drush requires the MySQL drivers to start ?

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by blueelvis** [comment]
On a side note, is it possible to maintain the exact same PHP modules which are enabled in the Kudu Container for Windows App Service Plan and the Linux App Service Plan? I just encountered into another issue where `gd` and `curl` are not installed on the Kudu Container on Linux because of which `composer install` fails.

> PHP Modules on Kudu Windows App Service Plan --
> PS D:\home> php -m
> php -m
> [PHP Modules]
> bcmath
> calendar
> com_dotnet
> Core
> ctype
> curl
> date
> dom
> ereg
> exif
> fileinfo
> filter
> ftp
> gd
> gettext
> hash
> iconv
> imap
> intl
> json
> libxml
> mbstring
> mcrypt
> mhash
> mysql
> mysqli
> mysqlnd
> odbc
> openssl
> pcre
> PDO
> pdo_mysql
> pdo_pgsql
> pdo_sqlite
> pdo_sqlsrv
> pgsql
> Phar
> Reflection
> session
> SimpleXML
> soap
> SPL
> sqlsrv
> standard
> tidy
> tokenizer
> wddx
> wincache
> xml
> xmlreader
> xmlrpc
> xmlwriter
> xsl
> Zend OPcache
> zip
> zlib
> 
> [Zend Modules]
> Zend OPcache

> PHP Modules on Kudu Linux App Service Plan
> /home>php -m
> [PHP Modules]
> calendar
> Core
> ctype
> date
> dom
> exif
> fileinfo
> filter
> ftp
> gettext
> hash
> iconv
> json
> libxml
> mbstring
> openssl
> pcntl
> pcre
> PDO
> Phar
> posix
> readline
> Reflection
> session
> shmop
> SimpleXML
> sockets
> SPL
> standard
> sysvmsg
> sysvsem
> sysvshm
> tokenizer
> wddx
> xml
> xmlreader
> xmlwriter
> xsl
> Zend OPcache
> zip
> zlib
> 
> [Zend Modules]
> Zend OPcache

@davidebbo - What do you think? I think the installation of PHP and other things should be generalized across the App Service Plans...

**Comment by rramachand21** [comment]
We will look into this soon.

**Comment by blueelvis** [comment]
@rramachand21 - Thank you for the effort. Kindly let me know in case any more information is required.
