### ISSUE TITLE
Deploy Ubuntu Container

### ISSUE THREAD

**Issue by temurih** [projectkudu/kudu#2704]
I was trying to deploy Windows Container to ACR earlier and I have been told that Azure does not have a support for them yet. So, I switched to `Ubuntu 16.04`. I am having the [same issue](https://github.com/projectkudu/kudu/issues/2690). Could anyone tell me what exactly does Azure support, please?

I have tested the docker image on my local machine and it works without a flaw. I don't understand why it doesn't work on Azure. No logs, no errors on Azure either. Not sure what to do... :(

**Comment by davidebbo** [comment]
I don't think this is Kudu related. @LukaszStem, I'll let you decide whether you want to discuss here or redirect to a more fitting place.

**Comment by temurih** [comment]
I am pretty sure it's related to KUDU because I am having issues while deploying my Docker images. Unless KUDU does not handle Azure Container deployments?

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
