### ISSUE TITLE
ERR_CONNECTION_RESET when trying to open Kudu from azure

### ISSUE THREAD

**Issue by mcgri** [projectkudu/kudu#2707]
### Repro steps.
https://ncwebsite.scm.azurewebsites.net/ . failes to open

### Project structures.

Simple website build with .core

### The log/error given by the failure.
ERR_CONNECTION_RESET when trying to open Advanced Tools

### Mention any other details that might be useful.
Yesterday all web apps on azure stopped respond to https links. No one touched anything... When you try to navigate to https you get ERR_CONNECTION_RESET

https://nova-care.uk/ - doesn't work, don't see any logs

http://nova-care.uk/ . - works, I see logs

I tried to open advance tools to see if there any other logs...but I am getting ERR_CONNECTION_RESET as well. 

Thank you for any help :)

**Comment by mcgri** [comment]
The https link for the website are now working, however I still can't navigate to the Kudu tools

**Comment by davidebbo** [comment]
Two questions to help isolate:

- do you see this for all Web Apps or just some? e.g. try in different regions.
- do you see this from all client machines & browsers or just some?

**Comment by mcgri** [comment]
Hi @davidebbo .

Yes , I can't open any kudu tools pages in all (3) apps and same for their staging instances.

Yesterday, I could not open https://ncwebsite.azurewebsites.net, but now it works.... Other apps without custom ssl certificate won't open by default azure url


Yes, it the same on 6 different machines, in different locations.  All apps configured under one WestEurope group.

**Comment by davidebbo** [comment]
@mcgri did you get to try different regions as suggested to help isolate? I'm still guessing that your issue is client side, as we have not seen any other reports of this and many people access the scm site.

If you can create a brand new test app (unmodified in any way!) and see this issue, please share the specific URL that you are accessing when you see this.

**Comment by mcgri** [comment]
My apologies :) I checked only on macs. Checked windows Edge and it working..I guess something to do with SSL state/cache..I will try to find out how to fix that myself :)
