### ISSUE TITLE
Add API for SCHANNEL ciphers

### ISSUE THREAD

**Issue by snobu** [projectkudu/kudu#2708]
Just wondering maybe this would be useful:

![image](https://user-images.githubusercontent.com/6472374/36549504-a2fb7ae4-17fb-11e8-8101-9504a7e2dfc4.png)

Right now i've implemented it to call into `Bcrypt.dll` and list all enabled cipher suites. You can pretty much get the same thing from PowerShell's `Get-TlsCipherSuite`, but i'm not very comfortable taking a dependency on a cmdlet that may change (also we need to import `System.Management.Automation.dll`, which is mostly a PowerShell thing).

This could be exposed as:

 **/api/schannelciphers**
(as pictured)

and

**Tools &rarr; TLS Cipher Suites** which returns a View (HTML), similar to what _Tools &rarr; Webhooks_ gives you now.

The view could also have an input box to test a remote endpoint. On submit we redirect to 

    https://www.ssllabs.com/ssltest/analyze.html?d=REMOTE.API.URL&latest

or we [wrap the SSL Labs API ](https://github.com/lordmike/ssllabslib)and show our own view. The latter I believe to be a bit much, although impressive to have.

Ref: https://stackoverflow.com/questions/38392925/only-on-azure-could-not-create-ssl-tls-secure-channel (not an isolated occurrence of this question).

The _awesomest_ version of this implementation would be a **Diagnose** button, that would try to match ciphers against the remote and give our _best guess_ to why TLS is failing (for example, the remote wants to use RC4, or worse, a cipher suite only found in SSL 3.0).

**Comment by davidebbo** [comment]
But isn't that also affected by the targetFramework people set in their web.config, as we found recently? e.g. if you target 4.5, you may fail to reach a server that only supports TLS 1.2, but we would not be able to detect that as their would be no mismatch.

I'm also not sure there is enough demand for this to add a Kudu feature. Maybe as a first step, we should have a good App Service doc page that guides users step by step on what they should try when they hit this type of issues.

**Comment by snobu** [comment]
Right, an ASP.NET application would first be affected by the target framework version, picks up a protocol version - let's say TLS 1.2 - and just then is affected by the order of cipher suites enabled in the OS (SCHANNEL).

A well written doc page is an even better idea. We should try to list common pitfalls, how things work for ASP.NET, .NET console apps (WebJobs), and maybe not just for .NET, but for programming stacks that come with their own crypto library (usually OpenSSL, and usually outdated).

**Comment by snobu** [comment]
I'll try to scaffold a doc page and ask for review internally. Closing this.
