### ISSUE TITLE
Continuous deployment via GitHub fails on Nuget package restore, however succeeds when published via VS 2017

### ISSUE THREAD

**Issue by ahmelsayed** [projectkudu/kudu#2709]
_From @MrMikeFloyd on February 27, 2018 12:3_

Hey Functions Team,

I'm experiencing issues deploying Azure Functions using the GitHub Webhook. Publishing my Function to the portal from VisualStudio 2017 works fine. I followed [this guideline from the docs](https://docs.microsoft.com/en-us/azure/azure-functions/functions-continuous-deployment).

## Steps undertaken

1. Created a function in the portal
2. Downloaded its app content (via "**Download App content**" -> "**Content and Visual Studio Content**")
3. Opened in VS, made adjustments to the code
4. Added to a Git Repo, committed/pushed to branch for development
5. Added GitHub Repo/branch to functions app via "**Deployment options**" as denoted [in the docs](https://docs.microsoft.com/en-us/azure/azure-functions/functions-continuous-deployment)
6. Hit "**sync**"

## Symptoms

Deployment ends up in the "failed" state after a short while:

![deployment_details](https://user-images.githubusercontent.com/14937417/36726882-8aa4ad26-1bbb-11e8-8436-2ce0e6772136.png)

The log file for generating the deployment script shows the following:

```
Using cached version of deployment script (command: 'azure -y --no-dot-deployment -r "D:\home\site\repository" -o "D:\home\site\deployments\tools" --functionApp "D:\home\site\repository\wwwroot\functionnamexyz-dev.csproj" --no-solution').
```

The deployment command log shows the following:

```
Command: "D:\home\site\deployments\tools\deploy.cmd"
Handling function App deployment with Msbuild.
Using Msbuild from 'D:\Program Files (x86)\MSBuild-15.3.409.57025\MSBuild\15.0\Bin'.
Input file does not exist: D:\home\site\repository\undefined.
Failed exitCode=1, command=nuget.exe restore "D:\home\site\repository\undefined" -MSBuildPath "D:\Program Files (x86)\MSBuild-15.3.409.57025\MSBuild\15.0\Bin"
An error has occurred during web site deployment.
Input file does not exist: D:\home\site\repository\undefined.\r\nD:\Program Files (x86)\SiteExtensions\Kudu\71.10217.3259\bin\Scripts\starter.cmd "D:\home\site\deployments\tools\deploy.cmd"
```

I extracted the generated deployment script using the debug console in Kudu. I added the content to [this Gist here](https://gist.github.com/MrMikeFloyd/5cb2be7794c91827e4d86180a1f67ad8).

## Project setup

The directory/file structure of my project looks like this:

```
wwwroot
 | - host.json
 | - functionnamexyz-dev.csproj
 | - local.settings.json
 | - functionX
 | | - function.json
 | | - run.csx
 | - functionY
 | | - function.json
 | | - run.csx
 | - functionZ
 | | - function.json
 | | - run.csx
```

It seems as things would fail around line 56 of the [deployment script](https://gist.github.com/MrMikeFloyd/5cb2be7794c91827e4d86180a1f67ad8):

```
:: 1. Restore nuget packages
call :ExecuteCmd nuget.exe restore "%DEPLOYMENT_SOURCE%\undefined" -MSBuildPath "%MSBUILD_15_DIR%"
```

Any ideas? Thanks for your help!

_Copied from original issue: Azure/Azure-Functions#694_

**Comment by ahmelsayed** [comment]
@watashiSHUN can you take a look?

**Comment by davidebbo** [comment]
@watashiSHUN the message "Input file does not exist: D:\home\site\repository\undefined" is a sign that some env variable is messed up at some level. Though it's weird that it would evaluate as `undefined` and not just empty string.

**Comment by MrMikeFloyd** [comment]
@watashiSHUN  so are you saying that opening the downloaded project in VS and adding a solutions file (*.sln) could be a possible workaround? Could try that if this helps in tracking down the issue.

**Comment by watashiSHUN** [comment]
There are a couple of issues, 
1. the `csproj` we added with you download from portal is outdated
2. no solution file breaks Kudu assumption

both are getting fixed, but if you want to get it working **right now**... you need some hacks
1. update your csproj like [this](https://github.com/KuduApps/FunctionAppDownloadFromKudu/blob/master/VScsxtest.csproj)
2. create a dummy solution file

**Comment by MrMikeFloyd** [comment]
@watashiSHUN I'm fine with using the publish feature in VS for now, but knowing that you guys are working on fixing this is great news! Thanks a lot for your efforts!

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
