### ISSUE TITLE
WEBSITE_ADD_SITENAME_BINDINGS_IN_APPHOST_CONFIG breaking change

### ISSUE THREAD

**Issue by DuncWatts** [projectkudu/kudu#2711]
As referenced in https://github.com/projectkudu/kudu/wiki/Configurable-settings the key WEBSITE_ADD_SITENAME_BINDINGS_IN_APPHOST_CONFIG has been recently defaulted to on.

This causes the OperationContext.Current.Channel.LocalAddress.Uri within a WCF service to return an invalid uri - https://webappname/ instead of https://webappname.azurewebsites.net/

**Comment by davidebbo** [comment]
It's not a Kudu issue, but someone pointed me to [this post](https://social.msdn.microsoft.com/Forums/azure/en-US/652bbf10-4f82-4993-b9f3-76543cce7482/wcf-applications-on-azure-appservice-fail-with-error-no-protocol-binding-matches-the-given-address?forum=windowsazurewebsitespreview), which discusses it. Sounds like you already found the workaround, but please respond on that thread if you have any additional questions. Thanks!
