### ISSUE TITLE
No notification to end users if function triggers aren't successfully synchronized post deployment

### ISSUE THREAD

**Issue by ConnorMcMahon** [projectkudu/kudu#2713]
If the synchronization in PostDeploymentHelper.SyncFunctionTriggers throws an exception like in [this issue](https://github.com/projectkudu/kudu/issues/2712), the end user has no notification that something went wrong in their deployment.

These sorts of users should in some way, shape, or form be surfaced up to the end users. There should be design considerations as to whether this lack of a synchronization counts as a deployment failure, or if we should notify them in some separate manner.

**Comment by davidebbo** [comment]
What specific deployment technique were you using? e.g. Kudu or msdeploy?

**Comment by ConnorMcMahon** [comment]
This was with msdeploy.

**Comment by aklefdal** [comment]
I had the same problem, and was using a POST to api/zipdeploy in KUDU.

**Comment by davidebbo** [comment]
Yes, we should make the deployment fail if we can't sync triggers. I discussed with @suwatch. /cc @EricSten-MSFT
