### ISSUE TITLE
[URGENT] Experiencing Authentication Issues

### ISSUE THREAD

**Issue by farzadmf** [projectkudu/kudu#2717]
Hi,

I installed an extension into my app service, and now whenever I want to navigate to it, I receive the following message:

```
Experiencing authentication issues

The portal is having issues getting authentication tokens for WebsitesExtension.
```

Can you please let me know what I can do? When I search, I see people suggesting to go the web app, and modify something etc., but my problem is that I cannot even go to my app service, let alone change something.

Please, this is really, really urgent, and I have no idea how to solve it

**Comment by davidebbo** [comment]
This is likely unrelated to Kudu, so closing here. Can you instead start thread on [forum](https://social.msdn.microsoft.com/Forums/azure/en-US/home?forum=windowsazurewebsitespreview) or stackoverflow? Also, please provide much more detail: test site name, what extension are you installing, ...

Or if urgent, please open support case.
