### ISSUE TITLE
Typo in the wiki for "Continuous deployment"

### ISSUE THREAD

**Issue by mumughal** [projectkudu/kudu#2721]
While integrating Azure with Github enterprise, we noticed their is a small typo in the wiki. 
[Here](https://github.com/projectkudu/kudu/wiki/Continuous-deployment#for-private-repos-set-up-a-deploy-key) the file should be located in `d:\home\.ssh\config.` instead of `d:\home.ssh\config.` :)

**Comment by davidebbo** [comment]
Fixed, thanks!
