### ISSUE TITLE
Typo in Wiki (Azure Web App sandbox)

### ISSUE THREAD

**Issue by sgwatgit** [projectkudu/kudu#2729]
In https://github.com/projectkudu/kudu/wiki/Azure-Web-App-sandbox

"Every Azure Web App has a local directory which is temporary and is deleted when the **run** is no longer running on the VM."

should be

"Every Azure Web App has a local directory which is temporary and is deleted when the **app** is no longer running on the VM."

**Comment by davidebbo** [comment]
Fixed, thanks!
