### ISSUE TITLE
Mention accepted authentication method for Rest API

### ISSUE THREAD

**Issue by szahn** [projectkudu/kudu#2730]
The Rest API documentation here https://github.com/projectkudu/kudu/wiki/REST-API does not mention authentication method. I had to do some googling before finding an example that uses basic header authentication. 

Please include paragraph with an example of using basic authentication.

**Comment by davidebbo** [comment]
@szahn it has a couple samples at the bottom, with PowerShell and curl.

**Comment by szahn** [comment]
I'm using Postman. It doesn't explicitly state that basic authentication is the only accepted authentication method.

**Comment by davidebbo** [comment]
I added a mention at the top.
