### ISSUE TITLE
Unable to open Kudu Debug Console Suddenly

### ISSUE THREAD

**Issue by ElliotP123** [projectkudu/kudu#2731]
Good Afternoon,

I have been setting up a few functions applications and today I noticed I wasn't able to open/access the files through kudu for my functions on my subscriptions.

When I go directly to the url for the hosted applications (Hosted in Southeast Asia) it shows the directories as being empty despite there being functional and operating functions.

When I click through the function to the kudu interface and I attempt to click on the 'Debug Console' menu item, nothing happens and the url just adds a '#' to the end.

I have attempted to see my kudu files in multiple browsers, addons turned off, etc. I've created new applications and still haven't been able to use kudu to access my files. I've tried clicking on the "old console" option below to no avail.

Opening Page: https://gyazo.com/73e90cfc05a3b39664bc9dd09e53ee42

Environment Page: https://gyazo.com/2631f37c0210bc570acb4070ac6ba257

Link to msdn post: https://social.msdn.microsoft.com/Forums/azure/en-US/1cdf11f3-a264-4b3e-9295-343b636a80af/unable-to-open-kudu-debug-console-suddenly?forum=AzureFunctions#1cdf11f3-a264-4b3e-9295-343b636a80af

**Comment by davidebbo** [comment]
You wrote on MSDN thread that you are getting the same errors as in #2727, so let's use that one for discussing this.
