### ISSUE TITLE
asp.net cdn was blocked in Russia by goverment

### ISSUE THREAD

**Issue by denisyfrolov** [projectkudu/kudu#2742]
This is a realy big problem, please help https://github.com/aspnet/Docs/issues/5832
![sc4](https://user-images.githubusercontent.com/5620027/38840837-2f7c857c-41ea-11e8-8bad-ea4cc4f12aa5.png)

**Comment by davidebbo** [comment]
I'll track that other thread to see where that goes. I doesn't seem realistic to change every site that uses that CDN.

**Comment by denisyfrolov** [comment]
@davidebbo Yeah, no doubt. At least you can fix this in Kudu, please..

**Comment by denisyfrolov** [comment]
@davidebbo I could make a pull request but I'm not sure which CDN you may or want to use.

**Comment by davidebbo** [comment]
I prefer to wait for people to agree on a 'standard' solution to solve this. i.e. clear guidance that explains the best way to deal with this issue.

Note that in the meantime, you can always deploy a private Kudu site extension build to your Azure site to get around this (but each site will need it).

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
