### ISSUE TITLE
[Linux] ipaddr_0 has been removed resulting in deployments breaking across regions

### ISSUE THREAD

**Issue by blueelvis** [projectkudu/kudu#2743]
> For deployment issues, please provide us with the following information:
> ---------------------------------------------------------------

### Repro steps.
> Create a Web App for Container in Azure
> SSH into the console.
> type in `cd /home/site`
> You will notice that the file which earlier used to be there telling about the IP address of the actual web app is now missing from everywhere. This seems to be a recent change (Like most likely this week). We use that file to get the IP address of th

### Project structures.
> Blank Web App for Container

### The log/error given by the failure.
> The file is not there

### Debug your Azure website remotely.
> pranav-linux-drupal

### Mention any other details that might be useful.
1. This seems to be a recent change (Like most likely this week).
2. We use that IP address/file to run instance specific commands as part of Jenkins Git Deployment to Azure Websites. This has broken all of our automated builds from Dev to Production
3. The client has his resources in East US 2 region but I already checked Central US and the change has happened over there as well.

Right now, there is no way to determine the IP address of the actual container running the website!

**Comment by rramachand21** [comment]
@blueelvis , could you please check if the file /appsvctmp/ipaddr_0 works for you? Btw, this was supposed to be an internal only file :) If you are using it, the format is /appsvctmp/ipaddr_$WEBSITE_ROLE_INSTANCE_ID

**Comment by davidebbo** [comment]
Closing since this is a deliberate change, but discussion can continue as needed.

**Comment by blueelvis** [comment]
@rramachand21 - Thanks! Yep. That fixed the issues. I used that path because it was mentioned earlier that it would be there :) https://github.com/projectkudu/kudu/issues/2677#issuecomment-360552770

Do you mind answering the following questions?

1. Would this be file present at all times inside the container? As in my question is if this file will exist everytime (Doesn't matter if path is changed in the future)
2. Why did you guys change the path of this file?
3. Is it possible to have this ipaddr_? file's content to be available in an environment variable as well? That way, if in future, the path is changed, it wouldn't matter.
3. Is it possible to contact you via email? I have quite some issues (A lot of them are on Github as well) regarding Web App for Containers which could be fixed to improve the platform. I would really love to see this technology stack go forward since it has a lot of potential! (Azure support refuses to let me contact you guys :( )


Thanks and have a nice day!
