### ISSUE TITLE
Improve Deployment times for Angular 5 SPA Template

### ISSUE THREAD

**Issue by FinVamp1** [projectkudu/kudu#2746]
> For deployment issues, please provide us with the following information:
> ---------------------------------------------------------------

### Repro steps.
> your project built successfully on your dev machine but failed on Azure?
> please write down your build tools and their versions (ie `Msbuild 15.1.0.0`)
1) Set up a Web Site from https://github.com/watashiSHUN/coreangular5template 

### Project structures.
> in order to reproduce your issue at our end we need a simple 
> [github repository](https://github.com/projectkudu/kudu/wiki/Using-a-git-repo-to-report-an-issue)
> that highlights structure of the project
https://github.com/watashiSHUN/coreangular5template 

### The log/error given by the failure.
> Normally this include a stack trace, error code and some more information.

### Debug your Azure website remotely.
> it is recommanded that you share your Web App name, directly or [indirectly](https://github.com/projectkudu/kudu/wiki/Reporting-your-site-name-without-posting-it-publicly)
> we can take a look at what's going on.

### Mention any other details that might be useful.
deploying angular 5 with angular cli needs at least  165s + 140s + 7s + 76s = 388s (rough figure)
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by watashiSHUN** [comment]
the 165s spent on `dotnet publish` could be improved with new [dotnet cli 2.1](https://blogs.msdn.microsoft.com/dotnet/2018/04/11/announcing-net-core-2-1-preview-2/) when building incrementally:
![image](https://user-images.githubusercontent.com/6531400/39775003-688f8684-52b1-11e8-85e4-e5b13c557013.png)

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
