### ISSUE TITLE
Noticing large spikes of outbound data but there's no site activity when it happens

### ISSUE THREAD

**Issue by xt0rted** [projectkudu/kudu#2747]
Since last week I've been monitoring the data in/out chart on my dashboard and every day I've been noticing large spikes of outbound data on one of my sites that doesn't seem to align with our incoming requests or deployments. Does Kudu do anything in the background that could cause spikes in the data usage like this, specifically outbound data?

Today there's 7 spikes of data with 5 of them being about the same amount (171 - 176 MB). The first 2 are a little smaller and happened right after I did two deployments via zip push. The amount of data out doesn't match up to our zip file though, but the data in does which I'd expect.

Right now everything but the login & registration pages is private and with how little content is available when logged in, and how there's no user traffic right now, it'd be incredibly hard to serve up this much content in that short of a span. The IIS logs don't look out of the ordinary either.

I have Raygun and App Insights setup and neither is showing errors when these spikes happen. I thought this could possibly be due to the App Insights snapshot collector, but since there's no errors being logged I don't see why that would be uploading anything, and even if it did would that actually count towards my outbound data? Searching for [`ai.snapshot.id`](https://docs.microsoft.com/en-us/azure/application-insights/app-insights-snapshot-debugger#use-application-insights-search-to-find-exceptions-with-snapshots) yields no results either.

I do have a couple extensions installed, but they shouldn't be causing outbound traffic like this. I haven't tried updating any of them during this time either. The ones installed are:
- [Azure Web Apps Disk Usage](https://github.com/rajkumar-rangaraj/MAWSFileExplorer)
- [Azure Let's Encrypt](https://github.com/sjkp/letsencrypt-siteextension)
- Application Insights

**Comment by davidebbo** [comment]
The only case I can think of when Kudu would trigger this would be through the use of scheduled WebJobs which I assume is not your case. Have you looked at all incoming http requests, in case there is correlation?

**Comment by xt0rted** [comment]
I do have a number of webjobs, but they all work against blobs, queues, and an sql db so there's no outbound traffic from them aside from the occasional email, but the last time any of them ran was 4/15/18 and the others (let's encrypt) haven't run since before today's spikes showed up.

**Requests**

![image](https://user-images.githubusercontent.com/831974/39154558-98706fda-471c-11e8-84ce-aecd8cce5d60.png)

**Data in/out**

![image](https://user-images.githubusercontent.com/831974/39154567-ab4e02a2-471c-11e8-8346-cf49e4931f8c.png)

Since creating this issue an 8th spike has happened about 10 minutes ago, but there's been no noticeable site activity, and I haven't done anything to the site (no config changes, no deployments, etc.). The only thing that does seem to coincide with it is these few lines from one of the site logs:
```
message
SnapshotHelper::RestoreSnapshotInternal   SUCCESS - File.Copy
SnapshotHelper::RestoreSnapshotInternal   SUCCESS - process
SnapshotHelper::RestoreSnapshotInternal   SUCCESS - File.Copy
SnapshotHelper::RestoreSnapshotInternal   SUCCESS - process
SnapshotHelper::TakeSnapshotTimerCallback
SnapshotHelper::TakeSnapshotInternal   SUCCESS - Process
SnapshotHelper::TakeSnapshotInternal   SUCCESS - File.Copy
```

I pulled the IIS log from this past hour and according to that there's been less than 1 MB of data sent yet according to the chart there's been over 175 MB.

**Comment by davidebbo** [comment]
Sorry, I don't know what's going on. Best I could suggest is to temporarily turn off the various extensions and WebJobs to confirm that they are not involved.

**Comment by davidebbo** [comment]
@puneet-gupta is the DaaS expert. I don't know exactly how it works, but I think it may come back automatically if you delete it. In any case, it's safe to try to delete it. Would be good to identify if it's related to the issue.

**Comment by davidebbo** [comment]
> I'm not sure if this is related or not, but my continuous webjob folder is right around the same size of the spikes I'm seeing (about 168 MB). When webjobs are run they get copied to a temporary location right? That shouldn't cause bandwidth usage though would it?

Oh, that's interesting. Yes, they do get shadow copied to a local tmp folder. However, it still doesn't add up for a couple reasons:

1. It only gets shadow copied once, until you restart the app (or get moved to new VM)
1. That's not an outbound data flow

You can try changing it to inplace to help isolate: https://github.com/projectkudu/kudu/wiki/WebJobs#webjob-working-directory

**Comment by xt0rted** [comment]
I'll give the in place setting a try next. Right now I'm testing disabling all non-essential webjobs. Preliminary results do show a correlation between them being disabled and not disabled, but I'll need a few more days of them off to be certain.

If I do a deployment and swap will the jobs I've disabled in production remain disabled once staging is promoted, or do these settings follow the slot?

**Comment by davidebbo** [comment]
That depends. How did you disable them specifically? If you do it via app setting (`WEBJOBS_STOPPED=1`), you can choose the behavior based on whether you make it a slot setting or not.

**Comment by xt0rted** [comment]
For my production slot I used the azure dashboard, and for my staging slot I have `WEBJOBS_STOPPED` as a slot setting set to `1`.

**Comment by davidebbo** [comment]
`WEBJOBS_STOPPED` as a slot setting will make sure that staging never runs it. But stopping via dashboard does it in a way that the state moves with the code as it is being swapped.

**Comment by xt0rted** [comment]
Since this is a live site I'm unable to turn off all of my webjobs long enough to test this but with the bulk of them disabled I did see a much longer gap between spikes and slightly smaller ones when they finally happened about 18 hours later.

What I've done instead is to turn on the webjobs in the staging slot since that's pretty much a mirror of the production slot right now. Before turning them on I never received a spike in outbound data. Within 15 minutes of turning them on in staging I got an 87 MB spike in outbound data. This slot has zero traffic to it and none of the jobs in this slot have actually run.

At this point my next steps are to let the jobs run in the staging slot and see if more spikes show up. Then if they do to go through and disable them one by one until no more spikes show.

**Comment by davidebbo** [comment]
Are all those WebJobs continuous? Are they using WebJobs SDK?

**Comment by xt0rted** [comment]
Yea, I have 5 continuous and 1 triggered. All are .net using 2.1.0 of the sdk.

**Comment by davidebbo** [comment]
Could it be that what they are doing is causing the outbound data? e.g. if one has a blob output binding that creates blobs, that would be outbound data.

**Comment by xt0rted** [comment]
Over the last two weeks the only job of mine that's run is triggered by a queue and sends an email via sendgrid. Earlier in the week I turned off all but this job and still saw two 170 MB spikes in outbound data but during this time the job didn't process any messages.

Aside from my webjobs there's also one for the let's encrypt extension (was disabled during this time), and the one that's part of the app insights extension. I didn't try turning this one off yet only because I wasn't really sure what it was actually doing.

Some of the spikes happen right around when a deploy/swap takes place, but I'm not sure about the rest.
During startup I log a number of things that are happening, but I'm not seeing this in the application log for each of the spikes, in fact none of them seem to match up to a site restart.

I'd like to upgrade to the latest webjobs, storage, and app insights sdks to see what that does, but there's a bug in the 2.5.x version of app insights that's preventing me from updating. Once 2.6 is released I should be able to update everything and see if that helps.

**Comment by xt0rted** [comment]
My final conclusion to all of this is the spikes are a result of the webjobs starting up after the site restarts or swaps. I have no idea why it happens, but the behavior aligns with this. When webjobs are enabled in the staging slot the spikes show up there too, only not as frequently as in the production slot. Once webjobs are disabled the spikes stop entirely and only start again when the webjobs are re-enabled. I'm going to open an issue in the webjobs repo to see what they have to say about all this.

**Comment by davidebbo** [comment]
To clarify, this is the right repo for WebJobs. There is something else called the WebJobs **SDK**, which some WebJobs use, and that is in a different repo (https://github.com/Azure/azure-webjobs-sdk). Yes, the naming is confusing.

**Comment by xt0rted** [comment]
Aside from upgrading to the latest versions of everything is there anything more I could do right now that might help?

**Comment by xt0rted** [comment]
The large spikes stopped on May 2nd. There's been smaller spikes fairly consistently since then, but nothing larger than about 70 MB with the average closer to 35-40 MB. None of my deploys touched the webjobs code or dependencies. The smaller spikes don't seem to fully match up to our traffic, but at least they're a lot smaller now.

**Comment by xt0rted** [comment]
For the last month or so I haven't been seeing any large spikes after my deployments. Nothing changed on my end (I actually opened the site up more to bing & google for indexing) so I'm not sure if this was an azure fix or something else. Either way it seems to be resolved for now.
