### ISSUE TITLE
Function Creation via REST API throws error

### ISSUE THREAD

**Issue by IshamMohamed** [projectkudu/kudu#2752]
Tried to create a function for a already deployed web app as mentioned in https://docs.microsoft.com/en-us/rest/api/appservice/webapps/createfunction. The response was a 500 - internal server error. 

The error message was:
"System.NullReferenceException: Object reference not set to an instance of an object.\\r\\n at Kudu.Core.Functions.FunctionManager.<CreateOrUpdateAsync>d__6.MoveNext() in C:\\\\Kudu Files\\\\Private\\\\src\\\\master\\\\Kudu.Core\\\\Functions\\\\FunctionManager.cs:line 99\\r\\n--- End of stack trace from previous location where exception was thrown ---\\r\\n at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\\r\\n at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\r\\n at Kudu.Services.Functions.FunctionController.<CreateOrUpdateHelper>d__7.MoveNext() in C:\\\\Kudu Files\\\\Private\\\\src\\\\master\\\\Kudu.Services\\\\Functions\\\\FunctionController.cs:line 67\\r\\n--- End of stack trace from previous location where exception was thrown ---\\r\\n at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\\r\\n at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\r\\n at System.Threading.Tasks.TaskHelpersExtensions.<CastToObject>d__3`1.MoveNext()\\r\\n--- End of stack trace from previous location where exception was thrown ---\\r\\n at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\\r\\n at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\r\\n at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()\\r\\n--- End of stack trace from previous location where exception was thrown ---\\r\\n at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\\r\\n at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\r\\n at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()\\r\\n--- End of stack trace from previous location where exception was thrown --- at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()--- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__0.MoveNext()--- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()--- End of stack trace from previous location where exception was thrown --- at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()--- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__0.MoveNext()--- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()--- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()"

**Comment by IshamMohamed** [comment]
Submitted this error here as it is seems like a problem in the FunctionController.cs

**Comment by davidebbo** [comment]
Can you provide a minimal (but complete) sample body that you are sending to this API when you see this? Thanks!

**Comment by davidebbo** [comment]
Also, do isolate, do you see the same if you try it on a brand new empty Function App?

**Comment by davidebbo** [comment]
@IshamMohamed that last error looks completely unrelated, like some general issue calling ARM API. Let's leave that part out.

**Comment by davidebbo** [comment]
@IshamMohamed will really need to payload sample to move forward as per my previous request.

**Comment by davidebbo** [comment]
The root of the issue is that you are sending an invalid payload which is missing the `properties` envelope (see [details](https://github.com/projectkudu/kudu/wiki/Functions-API
67d48c3bcee0fb1ef92c018985baf95fd4a77afb.

Bt more importantly, you should probably not be using this API. See https://github.com/Azure/Azure-Functions/wiki/Deploying-Function-Apps-vs-individual-Functions for more info.
