### ISSUE TITLE
How should I set the port if I'm using custom command?

### ISSUE THREAD

**Issue by lzl124631x** [projectkudu/kudu#2760]
### Repro steps.
I'm using custom deployment command. See this [commit](https://github.com/lzl124631x/liuzhenglai/commit/c235e9f696fecd8c8379853bbad05a2400ca526e)

I got the following error:
```
remote: Found package.json
remote: Running `npm install`
remote: .................................................................
remote: up to date in 75.631s
remote: Running `npm start`
remote: npm WARN lifecycle The node binary used for scripts is D:\Program Files (x86)\nodejs\6.9.1\node.exe but npm is using D:\Program Files (x86)\nodejs\8.11.1\node.exe itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.
remote:
remote: > liuzhenglai.com@1.0.0 start D:\home\site\wwwroot
remote: > node app.js
remote:
remote: ....
remote: events.js:160
remote:       throw er; // Unhandled 'error' event
remote:       ^
remote:
remote: Failed exitCode=1, command="D:\Program Files (x86)\nodejs\8.11.1\node.exe" "D:\Program Files (x86)\npm\5.6.0\node_modules\npm\bin\npm-cli.js" start --production
remote: Error: listen EACCES 0.0.0.0:80
remote: An error has occurred during web site deployment.
```

I met this issue before when I used the default deployment command. I added `let PORT = process.env.PORT || 80;` and `process.env.PORT` worked before. But if I use custom command, the port fell back to `80` again. What should I do? How can I know the correct `PORT` when running custom command?

### Project structures.
[repo](https://github.com/lzl124631x/liuzhenglai)
```
|--- front-end
|        |--- package.json
|--- .deployment
|--- deploy.cmd
```
I want to deploy the node project in front-end folder.

**Comment by watashiSHUN** [comment]
you don't need to call `npm start`, instead kudu sets up iisnode which will start node process (listening at `process.env.PORT`) when receiving requests:

> The iisnode module takes care of lifetime management of node.exe processes making it simple to improve overall reliability. You don’t have to implement infrastructure to start, stop, and monitor the processes.

from [iisnode repo](https://github.com/tjanczuk/iisnode/wiki#benefits)

plus somes references: [[1]](https://blog.lifeishao.com/2017/03/24/custom-nodejs-deployment-on-azure-web-app/), [[2]](https://github.com/projectkudu/kudu/wiki/Using-a-custom-web.config-for-Node-apps), [[3]](https://tomasz.janczuk.org/2011/08/hosting-nodejs-applications-in-iis-on.html)

**Comment by lzl124631x** [comment]
@watashiSHUN Thanks so much for your response. I'm taking a look. A quick response: I followed [this link](https://github.com/projectkudu/kudu/wiki/Custom-Deployment-Script) for setting up with custom deployment script but there is nothing similar as you quoted above. Highly recommend adding some quote or at least a link.

**Comment by lzl124631x** [comment]
@watashiSHUN What's your alias? Can I ask you some questions about kudu?

**Comment by watashiSHUN** [comment]
you can look for my name: shun xian cai
