### ISSUE TITLE
Network transient issue could lead to continuous job status file deletion

### ISSUE THREAD

**Issue by suwatch** [projectkudu/kudu#2763]
When continuous jobs run on multiple instances, each instance will write the job status (Running/Initializing/Stopped/..) to an instance-specific status file (`d:\Home\data\jobs\continuous\<jobname>\status_<instanceid>`).   Each instance will also hold a lock on this file by only allowing R/W but not Delete to indicate that the job is still running on this instance.  This enables [the cleanup for stale status file](https://github.com/projectkudu/kudu/blob/d72713743fd891a9f2f65e438bc0bb0c993aeac4/Kudu.Core/Jobs/ContinuousJobsManager.cs#L163-L164) during list webjobs api.

During network transient issue, the instance may lose the lock.   The bug is the instance will try to refresh the jobs but didn't try to re-acquire the status lock.   The list webjobs api which lands on  other instances will attempt to delete the status and succeed.   The outcome is there is no job status eventhough the job is still running on the instance.

**Comment by davidebbo** [comment]
Interesting. And I assume this is not just theoretical, and there was an actual instance of the issue?

**Comment by suwatch** [comment]
Yes.  This was reported by a customer - I forward you the internal email.
