### ISSUE TITLE
Memory issue on dump download

### ISSUE THREAD

**Issue by siarheiskalaban** [projectkudu/kudu#2765]
### Repro steps.
> Download memory dump via Process Explorer > Memory Dumps > Full Memory Dump or via Tools > ...

### Project structures.
> AspNetCore 2.0.1 application

### The log/error given by the failure.
> No errors

### Details
> Memory usage of `scm` process hightly increased after couple of memory dump downloads. And not completely restored even after AppService restart 
#### Timeline
![github-when-and-what](https://user-images.githubusercontent.com/16192298/39623200-83832c8c-4f9d-11e8-9524-1688b879672e.png)
#### Memory usage by subs:
![memory usage by sub-instances](https://user-images.githubusercontent.com/16192298/39622515-349e16f6-4f9b-11e8-88fc-1b2bd43555eb.png)
![github-kudu-memory-by-subs-2](https://user-images.githubusercontent.com/16192298/39623432-44bfe7be-4f9e-11e8-8024-806bbcd3b660.png)
As shown on diagnostic chart, kudu takes a lot of memory
Every "jump" of memory occurred  when Memory Dumps were download from scm

#### Memory usage before restarting of App Service:
![github-kudu-before](https://user-images.githubusercontent.com/16192298/39622599-888d06a0-4f9b-11e8-94c0-37795d7527bb.png)

#### Memory usage after restarting of App Service:
![github-kudu-after](https://user-images.githubusercontent.com/16192298/39622620-9e892c18-4f9b-11e8-98e3-942db6253c01.png)

#### Memory usage after restarting of App Service + 2 mins:
![github-kudu-after2](https://user-images.githubusercontent.com/16192298/39622633-abedb496-4f9b-11e8-9bb9-af170fc946ec.png)

#### Additional details:
Memory continue to be on same value as after restart + 2mins
After every "Restart site..." from Site Extensions > Restart site it falls to 200MB and then back to 380-400MBs

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
