### ISSUE TITLE
Monospace font for Jobs Output textarea

### ISSUE THREAD

**Issue by Richard004** [projectkudu/kudu#2777]
It would be nice to use monospace font for the output window of Jobs and Functions. 

Like this:
![image](https://user-images.githubusercontent.com/8113705/40587606-b692bcf0-61d1-11e8-8fba-3867e11f9918.png)

Instead of existing default font:
![image](https://user-images.githubusercontent.com/8113705/40587609-d14e437a-61d1-11e8-8fb7-f8edf6f0e769.png)

My guess is that most of the outputs are logging-like types of output.
But feel free to cancel this issue. It is just a proposal.

Have a good day.

**Comment by davidebbo** [comment]
This is part of the WebJobs SDK (https://github.com/Azure/azure-webjobs-sdk) and not Kudu.

But note that Functions is moving away from this dashboard, and is instead using App Insights.
