### ISSUE TITLE
remote: We noticed you're using an older version of Git. For the best experience, upgrade to a newer version

### ISSUE THREAD

**Issue by asifip** [projectkudu/kudu#2780]
> For deployment issues, please provide us with the following information:
> ---------------------------------------------------------------

### Repro steps.
> The web app on Azure runs  well. The issue is about App Inservice Editor's External GIT in general.
I used Visual Studio Git Repo for the web app and it works fine. I also received UI prompt for credentials. Its great. However during push I received verbose messages stating GIT upgrade is required.  This implied upgrade is needed for webapp's scm.   

I really believe there is a way how this could be done. i just couldnt do it myself. 
 

### Project structures.
> External GIT Repo configured for web app through Azure- Visual Studio GIT Repo is used for the requisites
> [github repository](https://asifpatel.visualstudio.com/quickdirty/_git/quickdirty)
 
### The log/error given by the failure.
> #  App InService Editor - Console output
\ [master*]> git add .
\ [master+]> git commit -m "first commit" --all
[master (root-commit) d7ab7a1] first commit
 5 files changed, 68 insertions(+)
 create mode 100644 LICENSE
 create mode 100644 WindowsPowerShell/Git_webapi.ps1
 create mode 100644 WindowsPowerShell/Microsoft.PowerShell_profile.ps1
 create mode 100644 hostingstart.html
 create mode 100644 readme.md
\ [master]> git push -u origin --all
fatal: COMException encountered.
   Error HRESULT E_FAIL has been returned from a call to a COM component.
Counting objects: 8, done.
Compressing objects: 100% (8/8), done.
Writing objects: 100% (8/8), 17.70 KiB | 1.04 MiB/s, done.
Total 8 (delta 0), reused 0 (delta 0)
remote: We noticed you're using an older version of Git. For the best experience, upgrade to a newer version.        
remote: Analyzing objects... (8/8) (5 ms)        
remote: Storing packfile... done (218 ms)        
remote: Storing index... done (34 ms)        
Branch 'master' set up to track remote branch 'master' from 'origin'.
To https://asifpatel.visualstudio.com/quickdirty/_git/quickdirty
 * [new branch]      master -> master

### Debug your Azure website remotely.
> it is recommanded that you share your Web App name, directly or [indirectly](https://quickdirty.scm.azurewebsites.net)
 
 

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
