### ISSUE TITLE
Should include GCM_MODAL_PROMPT=0 in GitExeRepository environment.

### ISSUE THREAD

**Issue by suwatch** [projectkudu/kudu#2781]
Or as git config.  See https://github.com/projectkudu/kudu/issues/2664 for details.

**Comment by davidebbo** [comment]
But how would that help the Monaco scenario? In that scenario:

- Kudu is not involved in creating the git repo
- `GitExeRepository` is not used

**Comment by suwatch** [comment]
Right.   One solution is each components (Kudu, Monaco) providing git as interactive Web Application need to add this.   For Azure App Services, we can consider a common solution (to always add this env).

**Comment by davidebbo** [comment]
At this point, let's just leave this alone. Monaco is a low support scenario, and the provided workaround (`GCM_MODAL_PROMPT=0`) should be good enough for the handful of people running into it.

**Comment by suwatch** [comment]
Okey.
