### ISSUE TITLE
Custom deployment script for an asp-net Core project with node modules

### ISSUE THREAD

**Issue by ddydeveloper** [projectkudu/kudu#2782]
I have a question about the deployment script. Could you provide a suitable example of the custom deployment script to combine asp-net Core building with npm install and webpack commands, e.g.

- dotnet restore
- dotnet build
- dotnet test
- npm install
- npm run release (actually "webpack" command with prod. )
- ...

Unfortunately, I didn't find any examples but it can be useful, there are lots of questions such as "How to deploy as-net with angular/react/vue to Azure". 

Any help will be helpful!

**Comment by davidebbo** [comment]
A custom deployment script is really just a batch file where you can do whatever you want. So while there may not be a sample that does exactly what you want, you might want to start form the standard .NET Core script, and modify it for your needs.

**Comment by ddydeveloper** [comment]
Thank you for explanation! I've found the way how to create custom deployment script according to your project and extend it:

1. Use advanced tools to download a script: 
![image](https://user-images.githubusercontent.com/28873881/41081919-2d51b524-6a35-11e8-8f66-e24ac1323521.png)

2. Change the script according to your needs, e.g. npm install, webpack, dotnet test e.t.c.:
![image](https://user-images.githubusercontent.com/28873881/41082001-74c4b50a-6a35-11e8-8b43-1d0fa5678596.png)

3. Add .deployment and deploy.cmd to your repository root
