### ISSUE TITLE
Linux: Deploying web app in subfolder via git, runtime cannot find specified dll

### ISSUE THREAD

**Issue by timiles** [projectkudu/kudu#2783]
### Repro steps.
I have followed the tutorial here: https://docs.microsoft.com/en-us/azure/app-service/containers/quickstart-dotnetcore, except with one change: I have deliberately created my web app in a subfolder rather than the root of my repository.  The resulting code is here: https://github.com/timiles/hellodotnetcoresubfolder

According to the documentation here: https://github.com/projectkudu/kudu/wiki/Customizing-deployments, I should be able to specify the path of my web app, either by `PROJECT` app setting, or in the `.deployment` file.  I have included the `.deployment` file in my repo above.  I believe this part is actually working fine.

The error comes when the app starts up.  Initially I get a 404 in the browser, and the following in the docker logs:
```
2018-06-06T13:29:56.188805059Z Starting OpenBSD Secure Shell server: sshd.
2018-06-06T13:29:56.399329273Z Could not find .csproj or .dll. Using default.
2018-06-06T13:29:58.362796196Z Hosting environment: Production
2018-06-06T13:29:58.362946196Z Content root path: /defaulthome/hostingstart/
```

So I changed my Startup file in Application Settings to `hellodotnetcore.dll`, and now I get "Service Unavailable" in the browser, and the following in the docker logs:
```
2018-06-06T13:32:59.312774611Z Starting OpenBSD Secure Shell server: sshd.
2018-06-06T13:32:59.325523648Z /bin/init_container.sh: line 22: /home/site/wwwroot/hellodotnetcore.dll: No such file or directory
```

SSHing into my app, I can see that the file does exist at this location:
```
/home>ls site/wwwroot
hellodotnetcore.PrecompiledViews.dll
hellodotnetcore.PrecompiledViews.pdb
hellodotnetcore.deps.json
hellodotnetcore.dll
hellodotnetcore.pdb
hellodotnetcore.runtimeconfig.json
web.config
```

So I'm not sure why it's reporting "No such file or directory".  Any ideas?

My test app is currently up at https://hellotim2.azurewebsites.net/

Thanks,
Tim

**Comment by davidebbo** [comment]
@rramachand21 @JennyLawrance: who can help with this Linux issue?

**Comment by timiles** [comment]
Hi @davidebbo (and @rramachand21 @JennyLawrance),

I have found the cause of my problem.  The docs here https://docs.microsoft.com/en-gb/azure/app-service/containers/app-service-linux-faq#built-in-images say "For .NET Core, specify your compiled DLL name."  But actually, I need to enter `dotnet hellodotnetcore.dll` rather than just the name of the DLL.

Could someone possibly forward this over to whoever maintains the docs at that location?  I will close this issue now.

**Comment by davidebbo** [comment]
@timiles Thanks for closing the loop. Note that there is an Edit button on the doc page, so you can actually submit a change yourself if you'd like!

**Comment by sassint-git** [comment]
Hi, could you please tell me where I can set Startup file in Application Settings for azure Service App?
