### ISSUE TITLE
After "Don't include nuget.org when using custom feed" update I need a way to add nuget.org extensions as well as my feed 

### ISSUE THREAD

**Issue by mmercan** [projectkudu/kudu#2784]
In our organisation we use site extensions stored in a custom feed and site extensions from Nuget feed (app dynamics etc..)  
After the 2755 update https://github.com/projectkudu/kudu/pull/2755 
all nuget feed extensions are disappeared in our kudu console, I can bring them back with toggling SCM_SITEEXTENSIONS_FEED_URL but it is not easy for 1000+ Web, Api Apps and messing with the automation scripts. 

SCM_SITEEXTENSIONS_FEED_URL only taking a single Url, if it can take an array which GetRemoteRepositories in SiteExtensionManager.cs capable of could solve this problem

**Comment by davidebbo** [comment]
I see. Are you mostly installing extensions manually via Kudu UI, or via some automation (either ARM or Kudu API)? If the latter, there is a way to explicitly pass the feed at installation time.

**Comment by mmercan** [comment]
I am using Kudu API as a part of VSTS release some cases manually updating the our custom extensions to the latest version, but mostly Kudu Api.

**Comment by davidebbo** [comment]
When calling Kudu API to install a site extension, you can explicitly set the feed URL, which should let you get around this. e.g. just pass it as follows in the body of the PUT:

```json
{
    "feed_url":"https://www.myget.org/F/siteextensions-test/"
}
```

**Comment by mmercan** [comment]
Is Kudu keep track of what feed has been used to install the extension for allowing updates from extension page in Kudu ?

**Comment by davidebbo** [comment]
@mmercan yes it does. Updates are always on the original feed used to install.

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
