### ISSUE TITLE
"The Win32 internal error "The handle is invalid" 0x6" when execution /api/command endpoint

### ISSUE THREAD

**Issue by ssolovyev** [projectkudu/kudu#2785]
Hi all,

I'm trying to execute powershell script using KUDU /api/command endpoint in my VSTS Release task (step).
Code sample is below:
```
$json = @"
{
    "command": 'powershell.exe -command `"get-childitem * -recurse | remove-item -force`"',
    "dir" : 'site\\wwwroot',
 }
"@

$kuduApiUrl = "https://$webAppName.scm.azurewebsites.net/api/command"

$WarningPreference = "SilentlyContinue"
$ProgressPreference = "SilentlyContinue"
$debugpreference = "SilentlyContinue"

$Result = Invoke-RestMethod -Uri $kuduApiUrl `
                        -Headers @{"Authorization"=$kuduApiAuthorisationToken;"If-Match"="*"} `
                        -Body $json `
                        -Method POST `
                        -ContentType "application/json"
```
After execution, the result ($Result) shows an error: 

```
Output Error                                                                                                                                                    
------ -----                                                                                                                                                    
       remove-item : The Win32 internal error "The handle is invalid" 0x6 occurred ...         
```                                                                 
I've tried to isolate the issue while executing the POSH code directly from KUDU console (as mentioned [here](https://github.com/projectkudu/kudu/wiki/Isolating-WebJobs-and-Deployment-script-issues)) but the error is still the same:

```
PS D:\home\site\wwwroot\asfa> get-childitem * -recurse | remove-item -force
get-childitem * -recurse | remove-item -force
remove-item : The Win32 internal error "The handle is invalid" 0x6 occurred 
PS D:\home\site\wwwroot\asfa> 
while getting the console mode. Contact Microsoft Customer Support Services.
At line:1 char:28
+ get-childitem * -recurse | remove-item -force
+                            ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [Remove-Item], HostExce 
   ption
    + FullyQualifiedErrorId : GetConsoleMode,Microsoft.PowerShell.Commands.Rem 
   oveItemCommand
```
 
![image](https://user-images.githubusercontent.com/12053374/41155437-ad63ec68-6b26-11e8-8efb-6870ea309805.png)

Need some additional advice on how to deal with this errror.

**Comment by davidebbo** [comment]
Let's leave VSTS out of the equation and just focus on the PowerShell behavior in Kudu. On my test site, when I run `get-childitem * -recurse | remove-item -force` I don't get any errors. Can you share the name of a test site where this fails? Also, please isolate whether the failure comes from get-childitem or remove-item.

**Comment by ssolovyev** [comment]
Both commands are working perfectly when executed separately. 
gci displays content, rm deletes without prompt. In a pair, they produce an error.

Here's the dummy site - https://dummy06082018.azurewebsites.net.
Look around, the name of the buggy site is ****appdacpac.azurewebsites.net, substitute the first four asterisks with letters.

**Comment by davidebbo** [comment]
@ssolovyev so it repros on the real site but not on the dummy site itself? If so, it would be interesting to look at possible configuration differences that might explain in.

**Comment by ssolovyev** [comment]
@davidebbo Not certainly in that way. The dummy site justifies his name - it was created only for you to not disclose the real (buggy) site name. It is empty and has no files inside.

**Comment by davidebbo** [comment]
@ssolovyev I need to clarify this. Are you saying:

1. When you tried on dummy site, everything worked
2. You did not try at all on dummy site

**Comment by davidebbo** [comment]
Actually, I just tried the following on both sites:

- Go to Kudu PowerShell
- Create a tmp folder at the root
- Copy some small text file in there
- Run `get-childitem * -recurse | remove-item -force`

And in both cases it worked. Can you give exact steps that lead to the issue?

**Comment by ssolovyev** [comment]
No, I haven't tried on the dummy site.
Alright, here are the steps:
- for dummy site
1. Open Azure Portal, open Web Apps blade, select dummy web app
2. Click on Advanced Tools blade, go to Kudu
3. Select Debug Console - PowerShell
4. Go to wwwroot directory (`cd site/wwwroot`) from `D:\home`, create 2 folders and 2 files inside the folders, fill in the files with sample text
5. Execute command  `get-childitem * -recurse | remove-item -force` when residing in wwwroot directory
6. Receive an error `remove-item : The Win32 internal error "The handle is invalid" 0x6 occurred 
while getting the console mode. Contact Microsoft Customer Support Services.`

- for prod site
The steps are as described above, just the wwwroot directory is already filled in with files and folders

**Comment by ssolovyev** [comment]
According to my tmp directory structure described above, I've found the following:
- executing the command `get-childitem * -Recurse | remove-item -recurse -force` removes the files inside the folders, leaving the folders inside the `tmp` folder as is
- executing as the second command `get-childitem -Recurse | remove-item -recurse -force` removes both folders, leaving the `tmp` folder empty

**Comment by ssolovyev** [comment]
Hmm, seems I should apologize for raising such small issue, the aforementioned command `get-childitem -recurse | remove-item -recurse -force` works perfectly when executing using REST API. Anyway, thanks for pointing me in the right direction 🥇

**Comment by davidebbo** [comment]
I was playing with it, and the behavior is certainly puzzling. e.g.

- in your repro, if you don't have the hostingstart.html, then error doesn't happen
- OR if you keep hostingstart but delete one of your two folders, it doesn't happen either

I can't make sense of it, but if it works via REST API, I think we'll just leave this alone for now :)

**Comment by katlimruiz** [comment]
I still get this error. What could be going on is the fact that this folder I'm trying to clean has thousands of files.

**Comment by Jehoel** [comment]
I'm experiencing this issue right now and it's stopping me from deleting folders in a directory in Kudu that I can't (reasonably) delete using `cmd` because I need to use wildcards.

![image](https://user-images.githubusercontent.com/1693078/80172796-cb495b80-85a2-11ea-9aa8-9083e237459e.png)

**Comment by suwatch** [comment]
if you use CMD mode and use rmdir /s /q <dir>, would that work?  Also try FTP.   How many directory / files under that folders?

**Comment by Jehoel** [comment]
@suwatch I don't want to use `rmdir /s /q` because I want to use a wildcard to only delete a few directories, not all of them, but `rmdir` doesn't support wildcards (and I can't figure out how to get `for /D` to work with `rmdir`).

FTP is disabled on this App Service account, and also would require manually deleting or moving each folder first (granted, most FTP GUIs handle that for you).

Each directory has between 2 and ~20 files in it - nothing outrageous.

**Comment by davidebbo** [comment]
`rm` supports wildcards, e.g. `rm -rfd foo*`

**Comment by Jehoel** [comment]
@davidebbo Ah cool - I didn't realise coretools were available in Kudu on Windows boxes.

I just tried it now and it works, cool. I'll need to remember that.

Are you still interested in looking into the PowerShell "The handle is invalid" error?

**Comment by davidebbo** [comment]
I'll let @suwatch speak to that as I'm no longer on the team. But when I had looked at it above, it was super mysterious and I couldn't make sense of it (assuming it's the same root cause).

**Comment by suwatch** [comment]
@Jehoel mind trying to repro the issue to this test site, please?  We will see what we can do.

`https://$repropsissue:DAopPZKHd6akkR4nB9aZN5wDqxFEjqdGjehFK2RcZ4PzrrttQzmgPuatcLTL@repropsissue.scm.kudu2.antares-test.windows-int.net/basicauth`

**Comment by carlosb1504** [comment]
This still seems to be a problem. 

Running the command
`Get-ChildItem d:\home\site\wwwroot -Recurse -Exclude FileToExclude.txt | Select -ExpandProperty FullName | sort length -Descending | Remove-Item -Force `

Results in the error given in the original post.

Whereas the following command
`Get-ChildItem d:\home\site\wwwroot -Recurse -Exclude FileToExclude.txt | Select -ExpandProperty FullName | sort length -Descending | foreach { Remove-Item -Path "$_" -Force } `

Works as a workaround. 

For me, adding the -Recurse parameter to Remove-Item wasn't an option as that would cause my FileToExclude.txt to be deleted when the parent was recursively deleted.

**Comment by Jehoel** [comment]
@suwatch Sorry I didn't see your reply until now - and the `repropsissue.scm.kudu2.antares-test.windows-int.net` website doesn't exist anymore.

I've emailed you at the e-mail address in your GitHub profile so you don't have to post test account credentials publicly.
