### ISSUE TITLE
Fix the UX bug for “KUDU | Process Explorer” showing multiple entries for the same process

### ISSUE THREAD

**Issue by cts-shrahman** [projectkudu/kudu#2796]
Fix the UX bug for “KUDU | Process Explorer” showing multiple entries for the same process. Ex: VSDiagnostics.exe 

![kudubug](https://user-images.githubusercontent.com/20867061/41743067-82cbd4ae-7565-11e8-8c79-22b780659395.jpg)

**Comment by davidebbo** [comment]
Tracked by #1426.
