### ISSUE TITLE
Deployment of an angular 5 application randomly fails. 

### ISSUE THREAD

**Issue by solcre** [projectkudu/kudu#2797]
> For deployment issues, please provide us with the following information:
> ---------------------------------------------------------------

### Repro steps.
npm install --production
ng build

### Project structures.
Angular 5 project structure

### The log/error given by the failure.
I have found this deployments very very unstable. We were forced to use Azure App Service for a project and to be honest the experience so far is negative. Random errors are the hardest to debug, some times it works other times npm install fails, other times it's ng build that fails and other times to make matter worse we don't even get a log error. Last log is literally empty.

### Debug your Azure website remotely.
our app name is `eva-megapharma`

### Mention any other details that might be useful.
Is there any other way to build apps in azure? A service like AWS's CodePipeline, CodeDeploy or CodeBuild equivalent? It's really hard for a devop to be checking what went randomly wrong after each push to github. Sorry to whine but I can't find a solution to make this run smooth. We upgraded the plan to a B1 just to run a simple npm install. We incremented the SCM_COMMAND_IDLE_TIMEOUT to 600 and also set the SCM_REPOSITORY_PATH to D:\local\repository (because another problem we had was that deployments took 30-40 minutes, something un-acceptable for CI). 

Update: As I finished writing this issue the deployment succeeded. As I said, it's totally random.

**Comment by watashiSHUN** [comment]
maybe [VSTS](https://visualstudio.microsoft.com/team-services/continuous-integration/) will work better for you? it has dedicated build server instead of competing for your websites computing resources

when you say the restore/build (referring to `npm install`/ `ng build`) failed, do you mean they stall (take long time) or do they actually output errors?

**Comment by solcre** [comment]
Hi @watashiSHUN, thanks for your quick reply. It stalls sometimes, but other times it will output errors but very random, and some times no errores at all. Today we are going to keep on pushing code and deploying I will hit you back with a log once an error occur.

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
