### ISSUE TITLE
Scheduled webjob aborted existing running instance every schedule

### ISSUE THREAD

**Issue by suwatch** [projectkudu/kudu#2798]
The scheduled webjob generally waits for the running instance to complete before launching a new one.   However, there is a situation where it can overlap and terminating new instance every schedule.

Assuming for some unknown reason (such as short network blip in lockfile), the new scheduled job instance did not detect an ongoing instance (meaning it was able to grab the LockFile) and proceeded to start the new instance.     As part of starting new one, it terminated all the existing webjob instances.    The issue was the terminated webjob instance released the same LockFile on exit.

Now we have the new instance running but no lock was held.   Once the new schedule fires, it grab the lock and terminate existing instance (which caused the lock to be released).    This overlapping cycle led to a premature termination of webjob every schedule.

Restart or webjob  taking < schedule period to complete will auto resolve this.   We could consider improvement by using a more primitive lock (ManualResetEvent) to ensure one instance running in addition to lock file.

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
