### ISSUE TITLE
What is the username and password for kudu's zip deployment rest API

### ISSUE THREAD

**Issue by vishleshp** [projectkudu/kudu#2799]
curl -X POST -u <user> --data-binary @<zipfile> https://{sitename}.scm.azurewebsites.net/api/zipdeploy

I am trying to do curl POST request to do zipdeploy with kudu rest API. How do I get what is --user set to ?

**Comment by suwatch** [comment]
Do you mean how do you set the credential in order to HTTP POST to SCM site?   If so, please see https://github.com/projectkudu/kudu/wiki/Deployment-credentials.    If not, please clarify the scenario.

**Comment by davidebbo** [comment]
That link should definitely answer it, so closing.
