### ISSUE TITLE
Docker Logs Dropouts

### ISSUE THREAD

**Issue by yss14** [projectkudu/kudu#2800]
### Repro steps.
Deploying a NodeJS app with various logs via the following docker file. For logging, `winston` is used and the application logs are written to the console.

### Project structures.
Docker file
```
# Stage 1 - Build
FROM node:9 as build

# Create app directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Install app dependencies
COPY package.json /usr/src/app/
COPY src/* /usr/src/app/src/
COPY .npmrc /usr/src/app/
RUN npm install

# Stage 2 - Execute
FROM node:9-alpine

# Create app directory and copy assets from prev stage
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
COPY --from=build /usr/src/app /usr/src/app

ENV NODE_ENV production
ENV PORT 3000
ENV LOG_TARGET_PRODUCTION console

EXPOSE 3000

CMD npm start
```

### The log/error given by the failure.
Once all 1-2 days (often after restarting the web app), there are no live docker logs provided for a time span of roughly 1-2 hours. Neither the logs available via the web api, nor the zipped version contains that logs of the last 1-2 hours. After that periode, suddenly logging again works and the old logs are also available. Even restarting the web app during those dropouts doesn't solve the problem.

### Mention any other details that might be useful.
The web app has enough space available for writing the logs (100MB).

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
