### ISSUE TITLE
error in sideband demultiplexer

### ISSUE THREAD

**Issue by mika1111** [projectkudu/kudu#2802]
> For deployment issues, please provide us with the following information:
> ---------------------------------------------------------------

### Repro steps.
Git error during deployment

### Project structures.
Node appplication with npm5

### The log/error given by the failure.
```
remote: Node.js versions available on the platform are: 0.6.20, 0.8.2, 0.8.19, 0.8.26, 0.8.27, 0.8.28, 0.10.5, 0.10.18, 0.10.21, 0.10.24, 0.10.26, 0.10.28, 0.10.29, 0.10.31, 0.10.32, 0.10.40, 0.12.0, 0.12.2, 0.12.3, 0.12.6, 4.0.0, 4.1.0, 4.1.2, 4.2.1, 4.2.2, 4.2.3, 4.2.4, 4.3.0, 4.3.2, 4.4.0, 4.4.1, 4.4.6, 4.4.7, 4.5.0, 4.6.0, 4.6.1, 4.8.4, 5.0.0, 5.1.1, 5.3.0, 5.4.0, 5.5.0, 5.6.0, 5.7.0, 5.7.1, 5.8.0, 5.9.1, 6.0.0, 6.1.0, 6.2.2, 6.3.0, 6.5.0, 6.6.0, 6.7.0, 6.9.0, 6.9.1, 6.9.2, 6.9.4, 6.9.5, 6.10.0, 6.10.3, 6.11.1, 6.11.2, 6.11.5, 6.12.2, 6.12.3, 7.0.0, 7.1.0, 7.2.0, 7.3.0, 7.4.0, 7.5.0, 7.6.0, 7.7.0, 7.7.4, 7.10.0, 7.10.1, 8.0.0, 8.1.4, 8.4.0, 8.5.0, 8.7.0, 8.8.0, 8.8.1, 8.9.0, 8.9.3, 8.9.4, 8.10.0, 8.11.1, 10.0.0.        
remote: Selected node.js version 8.11.1. Use package.json file to choose a different version.        
remote: Selected npm version 5.6.0        
remote: Updating iisnode.yml at D:\home\site\wwwroot\iisnode.yml        
remote: .........................
remote: npm WARN notice [SECURITY] tough-cookie has the following vulnerability: 1 high. Go here for more details: https://nodesecurity.io/advisories?search=tough-cookie&version=2.3.2 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.        
remote: npm WARN notice [SECURITY] debug has the following vulnerability: 1 low. Go here for more details: https://nodesecurity.io/advisories?search=debug&version=2.6.8 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
remote: npm WARN notice [SECURITY] mime has the following vulnerability: 1 moderate. Go here for more details: https://nodesecurity.io/advisories?search=mime&version=1.3.4 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.        
remote: ....
remote: npm WARN notice [SECURITY] lodash has the following vulnerability: 1 low. Go here for more details: https://nodesecurity.io/advisories?search=lodash&version=4.6.1 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.        
fatal: The remote end hung up unexpectedly
error: error in sideband demultiplexer
To https://bmb-prod-na-wkcheetah.scm.azurewebsites.net:443/bmb-prod-na-WKCHEETAH.git
   de63f0e..446afff  master -> master`
```

We get this error from time to time during deployments but yesterday after that we get repository in detache state:
`
You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.
 
If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:
...
error: src refspec master does not match any.
error: failed to push some refs
`
### Mention any other details that might be useful.
After recreate website it get back to normal but did you have any idea why it happened? At same time deployment on other endpoints seems to be ok. 
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by davidebbo** [comment]
One case when this `error in sideband demultiplexer` error can happen is when the connection to the server gets broken. That can happen if the connection goes idle for 230 seconds. Though normally, when that happens, the deployment continues just fine on the server.

**Comment by mika1111** [comment]
Hi is it possible to increase this limit? From our experience  error in sideband demultiplexer always results 500 from websites usually the npm install is not performed

**Comment by skylaro** [comment]
Seeing similar issue as well. Output from git push:

remote: Deploy Async        
remote: Updating branch 'master'.        
remote: .
send-pack: unexpected disconnect while reading sideband packet
error: error in sideband demultiplexer

The issue seems to be Oryx related, because deployment logs indicate 'oryx build' hangs for ~30 minutes during build. Any advice for what to configure?

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
