### ISSUE TITLE
Mercurial: remote: 'ssh' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by suwatch** [projectkudu/kudu#2806]
Customer reported the above issue when hg pulled from private repo (`hg pull ssh://hg@bitbucket.org/username/repo`).    This could also happen for git fetch from private repo (`error launching git: The system cannot find the path specified.`).   This happens to few but not all customers.

The cause is the `hg pull` requires ssh.exe to be on the path and it wasn't.   It turned out that installing 64bit git (even though msi installation was successful) may not clean up the existing 32bit one entirely and left the below files.    

```
D:\Program Files (x86)\git\cmd\git.exe
D:\Program Files (x86)\git\usr\bin\ngettext.exe
```

Our [logic](https://github.com/projectkudu/kudu/commit/9cdd5256f87ce92c75a5cc16b2ad978e220c25cb) mistook the 32 bits installation and set all paths related to such,  This breaks any scenarios require tooling coming with git.     

The fix is to re-order our check to prefer 64bit git (check that first) before 32bits one.  It might break the wise versa scenario - but highly unlikely for those outside Azure.

**Comment by davidebbo** [comment]
> This could also happen for git fetch from private repo (error launching git: The system cannot find the path specified.)

Do you mean that git fetch from private repro is also broken? That seems hard to believe.

**Comment by suwatch** [comment]
Yes, I tried it.  I think this only happens to few VMs and hence we have not heard much from.

**Comment by davidebbo** [comment]
But we have tests that do private repos. Why are they not broken on private stamps?

**Comment by suwatch** [comment]
I understand the confusion now.  Installing 64bit git will remove those files.   However, on the VM where customer reported the issue, those 2 files were somehow left.  There was no warning/error in 64bit git installation.   The leftover caused the issue.   Moving customer to another VM solved the issue.  I believe this happened to few enough VMs - hence just one reported so far.
