### ISSUE TITLE
It takes some time to update the ipaddr file

### ISSUE THREAD

**Issue by blueelvis** [projectkudu/kudu#2814]
> For deployment issues, please provide us with the following information:
> ---------------------------------------------------------------

### Repro steps.
> There are no reproduction issues but I have seen this happening a few times.

### Project structures.
> Drupal site

### The log/error given by the failure.
> Relevant part of Jenkins log -
```
remote: make[1]: Leaving directory '/home/site/sshpass'        
remote: deploy.sh: line 140: sshpass: command not found        
remote: ssh: connect to host 172.20.0.4 port 2222: No route to host        
remote: ssh: connect to host 172.20.0.4 port 2222: No route to host        
remote: ssh: connect to host 172.20.0.4 port 2222: No route to host        
remote: ssh: connect to host 172.20.0.4 port 2222: No route to host        
```

Actual container IP after trying to SSH the same time -
![image](https://user-images.githubusercontent.com/6985763/42705280-6ec0775c-86f0-11e8-90b1-e876ba99e3db.png)

### Mention any other details that might be useful.
1. This is pretty more likely to occur during a reboot or the container is migrated to another host.

I know that the reboots are asynchronous in nature, but is it possible to make the change to this file synchronous?

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
