### ISSUE TITLE
[Linux] Is it possible to deploy privately built Kudu to Web App for Containers?

### ISSUE THREAD

**Issue by blueelvis** [projectkudu/kudu#2815]
Hi,

I was going through the wiki and I found this article - https://github.com/projectkudu/kudu/wiki/Deploy-locally-built-private-kudu-to-azure

I was wondering whether it is possible to deploy a privately built Kudu to Web App for Containers or not.

Thanks,
Pranav

**Comment by davidebbo** [comment]
@rramachand21 do you know whether it's possible for someone to run their own Kudu bits on Linux?

**Comment by grahamehorner** [comment]
any updates? I too would like to deploy kudu to a Linux environment to control/build/deploy from GitHub

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
