### ISSUE TITLE
VSTS/Azure setup doc says must be project admin, it's project *collection* admin

### ISSUE THREAD

**Issue by brandonh-msft** [projectkudu/kudu#2818]
On this page

https://github.com/projectkudu/kudu/wiki/Setting-up-a-VSTS-account-so-it-can-deploy-to-a-Web-App

We say that in order to see the VSTS project & link it to Azure one must be the Project Admin and able to see the 'Service Hooks' area of Settings. This isn't correct (I'm in exactly this state right now and cannot link the two together). You must be a Project *Collection* Administrator which is a very different thing. See here: https://docs.microsoft.com/en-us/vsts/billing/set-up-billing-for-your-organization-vs?view=vsts#prerequisites

**Comment by suwatch** [comment]
Thanks for the info @brandonh-msft .   Fix the wiki accordingly.
