### ISSUE TITLE
Azure Web App - bower install does not work anymore

### ISSUE THREAD

**Issue by jozefizso** [projectkudu/kudu#2819]
Running the `bower install` command from the deployment script and/or from ASP.NET Core `PrepublishScript` target will result in an error because Azure Web App service have old bower installed.

### Repro steps.

Deploy ASP.NET Core website which uses the old `bower install` in the PrepublishScript target:

```xml
  <Target Name="PrepublishScript" BeforeTargets="PrepareForPublish">
    <Exec Command="npm install" />
    <Exec Command="bower install" />
    <Exec Command="gulp copy" />
  </Target>
```

### Project structure
[github repository](https://github.com/gitattributes/gitattributes.io)

### The log/error given by the failure.

Running the command manually results in this error:
```
D:\local\repository\src>bower --version
1.7.9

D:\local\repository\src>bower install
bower bootswatch-dist#3.3.6-paper          EINVRES Request to https://bower.herokuapp.com/packages/bootswatch-dist failed with 502
```

Opening this URL in browser leads to this error message: **This Bower version is deprecated. Please update it: npm install -g bower. The new registry address is https://registry.bower.io**

### Mention any other details that might be useful.

It's hard to override the preinstalled bower using `npm install -g bower` because the old bower sits in Program Files.

**Comment by JogoShugh** [comment]
Not working for me either

**Comment by suwatch** [comment]
@ahmelsayed  what is the logistic to get new bower on the Azure App Services?

**Comment by ahmelsayed** [comment]
It's part of rapidupdate. Basically deploying bower's npm package through rapidupdate

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
