### ISSUE TITLE
Linux: Wrong log file names

### ISSUE THREAD

**Issue by WayneUong** [projectkudu/kudu#2823]
Very often the log file names are generated erroneously:

<img width="1057" alt="screen shot 2018-08-01 at 1 15 57 am" src="https://user-images.githubusercontent.com/8436742/43509912-d7a70bf0-9528-11e8-8684-8ce79a7b1068.png">
<img width="1054" alt="screen shot 2018-08-01 at 1 16 07 am" src="https://user-images.githubusercontent.com/8436742/43509913-d7be2380-9528-11e8-93c1-1011b7d9c36d.png">

**Comment by WayneUong** [comment]
@davidebbo @rramachand21 Is there an ETA for a fix? This makes debugging very hard since we don't know which files to look for. Also, the Microsoft support team isn't able to solve this and asked us to come here.

**Comment by JennyLawrance** [comment]
Looking into this.

**Comment by WayneUong** [comment]
@JennyLawrance I'm still seeing files with wrongly formatted names till today.
![screen shot 2018-09-26 at 5 40 19 pm](https://user-images.githubusercontent.com/8436742/46117032-d44e2d00-c1b3-11e8-9434-3aa73f3b01d2.png)

**Comment by JennyLawrance** [comment]
Was able to reproduce the issue locally, will try out a fix and update the thread with status later this week.

**Comment by JennyLawrance** [comment]
@WayneUong Fix for this will be part of our next deployment, ETA to completion end of October.

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
