### ISSUE TITLE
Clarification on Wiki for deploying WARs to a given app name

### ISSUE THREAD

**Issue by joefuzz** [projectkudu/kudu#2824]
Currently, as of writing this, the wiki for WAR deployment states "Deploying to web apps other than the ROOT webapp is not supported yet." 

https://github.com/projectkudu/kudu/wiki/Deploying-WAR-files-using-wardeploy#known-issues

However, to me, it appears that this functionality is available in the code here:

https://github.com/projectkudu/kudu/blob/2b34aad2e59a06be70fdb4096d24806e3907f9aa/Kudu.Services/Deployment/PushDeploymentController.cs#L99 

Is the Wiki article correct in that you do not support the feature even though it exists, or does the Wiki article need updating to reflect this feature?

**Comment by davidebbo** [comment]
@shrishrirang can you respond and/or clarify wiki? Thanks!

**Comment by shrishrirang** [comment]
@joefuzz You are right. The feature is available on Windows for quite some time now and was made available on Linux about two weeks back. The wiki has been updated to reflect that. Thanks for reporting!
