### ISSUE TITLE
Deploy failing to overwrite PrecompiledViews.dll

### ISSUE THREAD

**Issue by skendrot** [projectkudu/kudu#2825]
> For deployment issues, please provide us with the following information:
> ---------------------------------------------------------------

### Repro steps.
> When committing to branch, project is failing to deploy with the following error:
> Error: Failed to change file that is currently being used "D:\home\site\wwwroot\ASSEMBLY.PrecompiledViews.dll"\r\nD:\Program Files (x86)\SiteExtensions\Kudu\75.10629.3460\bin\Scripts\starter.cmd "D:\home\site\deployments\tools\deploy.cmd"

### Project structures.
> ASP.NET Core 2.0 project

### The log/error given by the failure.
> Copying file: 'ASSEMBLY.PrecompiledViews.dll'
> Failed exitCode=1, command="kudusync" -v 50 -f "D:\local\Temp\8d5fb6cc8f1aec8" -t "D:\home\site\wwwroot" -n "D:\home\site\deployments\8cf42941a42289b50bc1f4b4160a576f40c6533c\manifest" -p "D:\home\site\deployments\e6927448cbc2052f84335b187cbb23c87f40ef44\manifest" -i ".git;.hg;.deployment;deploy.cmd"
> An error has occurred during web site deployment.
> Error: Failed to change file that is currently being used "D:\home\site\wwwroot\ASSEMBLY.PrecompiledViews.dll"\r\nD:\Program Files (x86)\SiteExtensions\Kudu\75.10629.3460\bin\Scripts\starter.cmd "D:\home\site\deployments\tools\deploy.cmd"

### Debug your Azure website remotely.
> boothbuddy.azurewebsites.net

**Comment by skendrot** [comment]
Note: In order to deploy, I have to stop the website and sync

**Comment by davidebbo** [comment]
When it's in that state, if you go to Kudu Console, are you able to *rename* that file? Normally, kudusync tries doing that, and dll files should be renamable.

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
