### ISSUE TITLE
If WEBSITE_RUN_FROM_ZIP is enabled can we add a warning in the Kudu Console indicate the site is in Read Only mode?

### ISSUE THREAD

**Issue by FinVamp1** [projectkudu/kudu#2830]
### Repro steps.
The VSTS Azure App Service Deploy v4 Preview task will default to Run From Zip and set this application setting.  We have seen a number of customers be unclear that this means the site is read only as discussed at https://github.com/Azure/app-service-announcements/issues/84 . The customers then try to edit their sites in Kudu and get a 409 error .

E.G

Error message :409 Conflict: Could not write to local resource 'D:\\home\\site\\wwwroot\\main.462900d9385dfbaba997.bundle.js' due to error 'Invalid access to memory location. '.' 

### The log/error given by the failure.
> Normally this include a stack trace, error code and some more information.
Error message :409 Conflict: Could not write to local resource 'D:\\home\\site\\wwwroot\\main.462900d9385dfbaba997.bundle.js' due to error 'Invalid access to memory location. '.'

### Mention any other details that might be useful.
Having an indicator here in Kudu but also in the Portal UX maybe useful to help avoid customer confusion.

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
