### ISSUE TITLE
Japanese Characters produce irregular response from the Kudu Command API

### ISSUE THREAD

**Issue by takyyon** [projectkudu/kudu#2835]
**### Repro steps.**
> https://ellefunc.azurewebsites.net
> In the app mentioned, the location, _**D:/home/site/wwwroot**_ contains a folder which has a name made up of Japanese characters.
> Running commands on this folder in the console(from the Azure portal) produces irregular output.

**### Mention any other details that might be useful.**

![image](https://user-images.githubusercontent.com/11722204/44480031-13a6be00-a5f7-11e8-928c-36a3c0e4b247.png)
Though the 'ls' command returns the Japanese name correctly, other commands return back a list of questions marks instead.

![image](https://user-images.githubusercontent.com/11722204/44480095-3d5fe500-a5f7-11e8-98aa-edf653068b5e.png)
Above is the API call we are making and the response is shown in the image below,
![image](https://user-images.githubusercontent.com/11722204/44480136-5d8fa400-a5f7-11e8-982e-c17743fa7b02.png)

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
