### ISSUE TITLE
32 bit Kudu can't get environment from 64 bit processes, leading to WebJobs termination issues

### ISSUE THREAD

**Issue by davidebbo** [projectkudu/kudu#2839]
[initially filed as https://github.com/Azure/kudu/issues/448]

Seems the logic we use to get environment doesn't work when the Kudu process is 32 bit and the processes are 64 bits.

This can be a problem because our WebJobs stopping logic relies on finding env variables named WEBSITE_ALWAYS_ON_JOB_RUNNING_MyJob to decide what to kill.

Here is a test WebJob that doesn't terminate when you stop it [Test.zip](https://github.com/projectkudu/kudu/files/2328660/Test.zip). It launches php, but the parent bash processes are 64 bit and we fail to kill them.

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
