### ISSUE TITLE
Hitting <scm site>/deployments will kill ongoing deployments

### ISSUE THREAD

**Issue by patricklee2** [projectkudu/kudu#2841]
Customer reported that hitting the /deployments endpoint will kill ongoing async zip deployments
customer was using a large 100 MB zipfile

https://github.com/projectkudu/kudu/blob/master/Kudu.Core/Deployment/DeploymentManager.cs#L815
will call
https://github.com/projectkudu/kudu/blob/master/Kudu.Core/Deployment/DeploymentManager.cs#L351
CRI: https://icm.ad.msft.net/imp/v3/incidents/details/81199071/home

**Comment by ahmelsayed** [comment]
Closing as no repro
