### ISSUE TITLE
Initial git clone fail, "thread aborted"

### ISSUE THREAD

**Issue by mawtex** [projectkudu/kudu#2850]
I'm having an issue where the git process seems to be aborted after 4:45 minutes when setting up a new deployment.

I've tried adding the following application settings via the portal, without finding a resolution. `COMMAND_IDLE_TIMEOUT` (6000), `SCM_COMMAND_IDLE_TIMEOUT` (6000), `SCM_USE_LIBGIT2SHARP_REPOSITORY` (0), `SCM_USE_SHALLOW_CLONE` (1), `WEBSITE_SCM_IDLE_TIMEOUT_IN_MINUTES` (600)

### Repro steps.
Large repo (1.4 GB content, plus 1GB for .git), but otherwise simple (xcopy deployable), hosted on github. I can provide access to the repo if desired.

Setting up a new deployment, connecting to the repo on github.

### Result of repro steps
It runs for around 5 minutes and then fail, feedback is "thread aborted" during "Fetching changes". Ran for 289 seconds. 

The git repo is half initialized, a D:\home\site\repository\.git\index.lock file lingers on. 

Cloning the same repo from github works fine locally etc, given the time needed.

### The log/error given by the failure.

Trace file "2018-08-31T17-31-47_b9c40c_155_Shutdown_0s.xml"
```
<step title="Process Shutdown" date="2018-08-31T17:31:47.392" instance="b9c40c" pid="4752,2,18" uptime="00:04:45.4831500" lastrequesttime="00:00:10.7662057" >
    <step title="Cleanup Xml Logs" date="2018-08-31T17:31:47.408" />
    <!-- duration: 0ms -->
</step>
<!-- duration: 33ms -->

```
Deployment "log.log" says
```
2018-08-31T17:54:24.6086204Z,Fetching changes.,4d237805-defb-40f1-a0e2-0daca0ee072f,0
	2018-08-31T17:59:13.4430231Z,Thread was being aborted.,,2

```

**Comment by davidebbo** [comment]
To isolate, you can check whether you're able to clone it manually from Kudu Console. Though that is certainly an enormous repo. Also, make sure you have Always On enabled to make sure the scm site doesn't get unloaded during the operation.

**Comment by mawtex** [comment]
Enabling `Always On` in Application settings resolved my issue - thanks!!
