### ISSUE TITLE
Log file names are inconsistent

### ISSUE THREAD

**Issue by WayneUong** [projectkudu/kudu#2852]
We have 10 web apps running with docker, and this happens to all of them:

<img width="1039" alt="screen shot 2018-09-01 at 10 45 21 am" src="https://user-images.githubusercontent.com/8436742/44948583-12cf1280-add5-11e8-8e6c-6a10656072b7.png">

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
