### ISSUE TITLE
Can't deploy ASP.NET MVC with Angular 6 and Webpack 4 

### ISSUE THREAD

**Issue by elgendy** [projectkudu/kudu#2854]
I can build the project locally without any issues, using VS 2017, .NET 4.6.2 and TS 3.0.3

It's an ASP.NET MVC app that using Angular 6 and Webpack 4.
I'm using a custom deployment script.
deployment failure/log details attached.

[deployment failure details.txt](https://github.com/projectkudu/kudu/files/2358367/deployment.failure.details.txt)

**Comment by davidebbo** [comment]
@ahmelsayed I think this may be because we have Typescript 2.5, and this is expecting something newer.

Related: https://github.com/Microsoft/TypeScript/issues/21938

**Comment by elgendy** [comment]
@davidebbo this is my assumption, I see that the TS version that MSBuild uses is lower than 2.8 which is a minimum requirement to build Angular 6 .ts files.

Wondering if there is a way to upgrade the TS version.

**Comment by elgendy** [comment]
@ahmelsayed (cc: @davidebbo) Or at least, do you guys plan to upgrade the TS version anytime soon?

**Comment by elgendy** [comment]
thanks, @davidebbo! I guess I will consider switching to VSTS.
