### ISSUE TITLE
Change preconditions for throwing an error on retriving Function secrets from kudu 

### ISSUE THREAD

**Issue by ahmelsayed** [projectkudu/kudu#2855]
The API keys for a function can be stored either in `Files` or in `Blob`. Files mean that it's stored on the filesystem of your app, and Blob means that it's stored as blob object in your storage account. 

That used to be set using an env var `AzureWebJobsSecretStorageType`. The default value **was** `Files` and the absence of the env var assumes default. That changed with the latest release to have the default be `Blob` and the absence meaning `Blob`, and to use `Files` you have to explicitly set that. 

Kudu can only serve the secrets back if they are on `Files` because kudu has access to the same fileSystem as the main app. And while kudu has access to the storage account as well, the scenario is more complicated, so we throw an error saying that kudu doesn't support that mode.

When a request to get functions keys comes to kudu, kudu would check an environment variable `AzureWebJobsSecretStorageType` **if it exists and is set to `Blob`**, kudu would throw an error. That logic is implemented here 

https://github.com/projectkudu/kudu/blob/1193aca332f1951b7693463d07417486981b7f4c/Kudu.Core/Functions/FunctionManager.cs#L128-L135

We need to tweak that logic a bit to accommodate for the new default. The logic should be 

```
if app is v1:
    do the same as today, since there is no change in v1
if app is v2:
    if AzureWebJobsSecretStorageType is null or empty, or AzureWebJobsSecretStorageType != 'Files':
        throw InvalidOperationException("Runtime keys are stored on blob storage. This API doesn't support this configuration.");
    else:
        serve the key. 
```

**Comment by davidebbo** [comment]
Would be great to have the error tell you exactly what you need to do to fix it, or point to some aka link with more info.

**Comment by ahmelsayed** [comment]
To check the version (v1 vs v2) you need to look at env var `FUNCTIONS_EXTENSION_VERSION`. If it's `~1` or startsWith `1.0`, then it's v1, otherwise it's v2.

**Comment by ankitkumarr** [comment]
@davidebbo Is there already a link with more info that you are aware of. Or should I create one?

**Comment by davidebbo** [comment]
There probably isn't one. Idea is that we create a redirect link, so we can later point to to whatever we want.

**Comment by davidebbo** [comment]
@ankitkumarr Use https://aka.ms/funcsecrets. It's not pointing to right place yet, but we'll fix later.
