### ISSUE TITLE
Kudu REST API: AppSettings are not updated properly

### ISSUE THREAD

**Issue by ebashmakov** [projectkudu/kudu#2859]
When you add AppSettings via Kudu API the settings are not added (or updated) in the resource itself and only available at Kudu API.

**Example**:
1. POST https://appsettings-issue.scm.azurewebsites.net/api/settings

```json
{
    "MY_KUDU_APP_SETTING_1": "bug?"
}
```

2. GET https://appsettings-issue.scm.azurewebsites.net/api/settings

```
{
    ...,
    "MY_KUDU_APP_SETTING_1": "bug?"
}
```

3. GET https://management.azure.com/subscriptions/***/resourceGroups/appsettings-issue/providers/Microsoft.Web/sites/appsettings-issue/config/appsettings/list?api-version=2018-02-01

**Actual result**:
```json
{
    "id": "/subscriptions/***/resourceGroups/appsettings-issue/providers/Microsoft.Web/sites/appsettings-issue/config/appsettings",
    "name": "appsettings",
    "type": "Microsoft.Web/sites/config",
    "location": "Central US",
    "properties": {}
}
```

**Expected result**:
```json
{
    "id": "/subscriptions/***/resourceGroups/appsettings-issue/providers/Microsoft.Web/sites/appsettings-issue/config/appsettings",
    "name": "appsettings",
    "type": "Microsoft.Web/sites/config",
    "location": "Central US",
    "properties": {
        "MY_KUDU_APP_SETTING_1": "bug?"
    }
}
```

**Comment by davidebbo** [comment]
I know this is confusing, but this is actually expected behavior. This Kudu API is only for setting things that are consumed by Kudu itself, and it does not modify the actual App Service settings. Frankly, it is more meant to be used when running Kudu locally, so if you're on Azure, it's best not to use this API.

**Comment by markheath** [comment]
Would be good if the docs made this a bit clearer. Just had someone on my team attempt to use this to update App Settings
