### ISSUE TITLE
'npm install' doesn't run after KuduSync from repository subfolder

### ISSUE THREAD

**Issue by UpQuark** [projectkudu/kudu#2860]
Hi folks. I'm having an issue deploying a node API and Ember.js frontend to an Azure Windows App Service using Kudu. I have previously had success with this, deploying a git repo that contains a node app at its root, and an Ember app in a folder nested under it. I am trying to make a simple change to that structure so that instead of having a folder structure like:

`API_folder/Frontend_folder`

...I have a structure like:

`Project_folder/API_folder`
`Project_folder/Frontend_folder`

...to make it easier to eventually split these projects up.

### Repro steps.
I use Bitbucket Pipelines to push our git repo to the Kudu SCM endpoint for our web app, with the following line:

```- git push https://$AZURE_USERNAME:$AZURE_PWD@our-app-name.scm.azurewebsites.net:443/our-app-name.git $BITBUCKET_BRANCH```

...followed by copying the frontend javascript to a subfolder within `wwwroot`. This has worked fine when the node app was at the project root, but failed when it was nested inside an `API` folder. I have configured a custom deployment script to call KuduSync on the API folder as DeploymentSource, and while the repository files from the `API` directory seem to be copied correctly, `npm install` never seems to run, and the node app resultantly can't start.

The deployment script is entirely the NPM template, except for the following alteration:

``` 
 call :ExecuteCmd "%KUDU_SYNC_CMD%" -v 50 !IGNORE_MANIFEST_PARAM! -f "%DEPLOYMENT_SOURCE%"\api -t "%DEPLOYMENT_TARGET%" -n "%NEXT_MANIFEST_PATH%" -p "%PREVIOUS_MANIFEST_PATH%" -i ".git;.hg;.deployment;deploy.cmd"
```

(note `%DEPLOYMENT_SOURCE%/api` is the only difference from the template)

Full .deployment
```
[config]
command = deploy.cmd
```

Full deploy.cmd, if it's helpful. I haven't altered it from the template other than the line noted above:
```@if "%SCM_TRACE_LEVEL%" NEQ "4" @echo off

:: ----------------------
:: KUDU Deployment Script
:: Version: 1.0.17
:: ----------------------

:: Prerequisites
:: -------------

:: Verify node.js installed
where node 2>nul >nul
IF %ERRORLEVEL% NEQ 0 (
  echo Missing node.js executable, please install node.js, if already installed make sure it can be reached from current environment.
  goto error
)

:: Setup
:: -----

setlocal enabledelayedexpansion

SET ARTIFACTS=%~dp0%..\artifacts

IF NOT DEFINED DEPLOYMENT_SOURCE (
  SET DEPLOYMENT_SOURCE=%~dp0%./API
)

echo "DeploymentSource: %DEPLOYMENT_SOURCE%"


IF NOT DEFINED DEPLOYMENT_TARGET (
  SET DEPLOYMENT_TARGET=%ARTIFACTS%\wwwroot
)

IF NOT DEFINED NEXT_MANIFEST_PATH (
  SET NEXT_MANIFEST_PATH=%ARTIFACTS%\manifest

  IF NOT DEFINED PREVIOUS_MANIFEST_PATH (
    SET PREVIOUS_MANIFEST_PATH=%ARTIFACTS%\manifest
  )
)

IF NOT DEFINED KUDU_SYNC_CMD (
  :: Install kudu sync
  echo Installing Kudu Sync
  call npm install kudusync -g --silent
  IF !ERRORLEVEL! NEQ 0 goto error

  :: Locally just running "kuduSync" would also work
  SET KUDU_SYNC_CMD=%appdata%\npm\kuduSync.cmd
)

::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
:: Deployment
:: ----------

echo Handling Basic Web Site deployment.

:: 1. KuduSync
IF /I "%IN_PLACE_DEPLOYMENT%" NEQ "1" (

  IF /I "%IGNORE_MANIFEST%" EQU "1" (
    SET IGNORE_MANIFEST_PARAM=-x
  )

  call :ExecuteCmd "%KUDU_SYNC_CMD%" -v 50 !IGNORE_MANIFEST_PARAM! -f "%DEPLOYMENT_SOURCE%"\api -t "%DEPLOYMENT_TARGET%" -n "%NEXT_MANIFEST_PATH%" -p "%PREVIOUS_MANIFEST_PATH%" -i ".git;.hg;.deployment;deploy.cmd"
  IF !ERRORLEVEL! NEQ 0 goto error
)

::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
goto end

:: Execute command routine that will echo out when error
:ExecuteCmd
setlocal
set _CMD_=%*
call %_CMD_%
if "%ERRORLEVEL%" NEQ "0" echo Failed exitCode=%ERRORLEVEL%, command=%_CMD_%
exit /b %ERRORLEVEL%

:error
endlocal
echo An error has occurred during web site deployment.
call :exitSetErrorLevel
call :exitFromFunction 2>nul

:exitSetErrorLevel
exit /b 1

:exitFromFunction
()

:end
endlocal
echo Finished successfully.
```

> ---------------------------------------------------------------

### Project structures.
I'm not sure I can feasibly recreate this issue in a git repo, since it is dependent on our private bitbucket organization and its pipelines integration. However the repository does have a properly formatted package.json, and iisnode.yml at the root, and has worked flawlessly when the node app is in the root folder, rather than one level down. I've outlined the folder structure above.

### The log/error given by the failure.
Looking at the application log, I see:

```Application has thrown an uncaught exception and is terminated:
Error: Cannot find module 'dotenv'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\home\site\wwwroot\app.js:4:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

...which suggested to me that Node is attempting to start, but can't find dependencies. Looking in the `wwwroot` directory I see that all files were copied correctly, but `node_modules` is not present, and there is no node_debug file, suggesting that `npm install` never ran.

Any insight or further detail that I can offer? I feel like I'm missing something simple, since I'm sure running a node app in a subfolder is supported, and it seems like it's 99% of the way there.

Thanks much!

**Comment by UpQuark** [comment]
As it turns out just adding an explicit `call npm install` after `call :ExecuteCmd "%KUDU_SYNC_CMD%"` works totally fine. 

I was under the impression that KuduSync should run it automatically, but this is certainly a straightforward (and in retrospect increeeeedibly obvious) solution.

I'll leave this open until someone has a chance to review, because the [Kudu doc](https://github.com/projectkudu/kudu/wiki/Deployment#non-wap-site-eg-node-php-aspnet-web-site seems to indicate that `npm install` should trigger automatically. Happy to close if I'm just misunderstanding or misusing something.

**Comment by davidebbo** [comment]
Kudu has some heuristic to detect project type, and if it detects Node it should be using a deployment script that does `npm install`. Maybe for whatever reason it's not detecting yours as a Node app. There is a way to [override that](https://github.com/projectkudu/kudu/wiki/Configurable-settings#taking-over-the-script-generator-command-line).
