### ISSUE TITLE
Memory dump - 500 ("Only part of a ReadProcessMemory or WriteProcessMemory request was completed")

### ISSUE THREAD

**Issue by kierenj** [projectkudu/kudu#2861]
Using Kudu on (Windows) App Service -> Process Explorer -> My .NET Core app -> Download memory dump.

Gives me a 500 error in the console, "Only part of a ReadProcessMemory or WriteProcessMemory request was completed".  Restarting the service made no difference.

Following the guide here - https://blogs.msdn.microsoft.com/jpsanders/2017/02/02/how-to-get-a-full-memory-dump-in-azure-app-services/ - using procdump - worked.

**Comment by davidebbo** [comment]
Are you seeing 500 consistently, or only with some processes? Is this a full or mini dump? And how big is the process memory?

**Comment by kierenj** [comment]
Yes consistently - no idea I just hit the button - about 100mb :)

**Comment by kierenj** [comment]
oh - consistently for the .net core process. Others dump fine

**Comment by davidebbo** [comment]
In Kudu, if you right click on process, you choose Full vs Mini. And it happens for any process? We'd need to set up a repro.

**Comment by kierenj** [comment]
ah - I clicked Properties and hen the single dump button. Ill try the others later and advise

**Comment by kierenj** [comment]
Both right-click options also give a 500 error.  It's a pretty standard .NET Core 2.0 project, built with latest 2.1 SDK.  Is there anything else I can do to help diagnose?

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
