### ISSUE TITLE
[Linux] zipdeploy + custom deployment call fails: location or permission

### ISSUE THREAD

**Issue by camous** [projectkudu/kudu#2870]
Requirements/goal : deploy several git repositories (one is pure nodejs website, other are versioned contents (gitbooks)) into one unique linux app service from VSTS/devops.

some rework has to be done in order core app & content can be deployed & live together

* core app : custom deploy.sh ignoring books folder while kudusync in order content not being deleted if new core version
* contents : custom deploy.sh for targetting books/bookX rather wwwroot folder

![image](https://user-images.githubusercontent.com/8566299/45919416-1403d480-be95-11e8-86e9-8931da0730a6.png)
_I've tried my best to interact from VSTS/DEVOPS with kudu DEPLOYMENT_TARGET but with no luck, and as I needed to override kudusync call, I went for all custom deploy.sh_ 

On a fresh linux web app created in on 22nd of september in central US. on all my repository (never worked before)

gitroot\.deployment
```
[config]
command = deploy.sh
```

gitroot\deploy.sh
```
[standard one stealed from the linux instance through web SSH & copy paste)
```

getting following error

> /opt/Kudu/bin/Scripts/starter.sh: line 2: exec: deploy.sh: not found
/opt/Kudu/bin/Scripts/starter.sh: line 2: exec: deploy.sh: not found\n/opt/Kudu/bin/Scripts/starter.sh deploy.sh

if I remplace `command = deploy.sh` by `command = ./deploy.sh` in `.deployment` 

> /opt/Kudu/bin/Scripts/starter.sh: line 2: /tmp/zipdeploy/extracted/deploy.sh: Permission denied
/opt/Kudu/bin/Scripts/starter.sh: line 2: exec: /tmp/zipdeploy/extracted/deploy.sh: cannot execute: Permission denied

any idea what I'm doing wrong ?

**Comment by camous** [comment]
tried many ways to change/keep the execution permission without luck

tried to trick the command neither luck (not an expert in unix ...)
looked at `starter.sh` and tried to make 2 commands in a row

`command = chmod +x /tmp/zipdeploy/extracted/deploy.sh && /tmp/zipdeploy/extracted/deploy.sh`

**Comment by GroofyIT** [comment]
Same issue here.

**Comment by shadowwalker** [comment]
@bkorbuly @GroofyIT @camous 
Hi, I managed to solve the issue by adding bash before the command in .deployment file:

``` bash
[config]
command = bash scripts/deploy.sh
```

When using bash to execute a shell script, the .sh file don't have to add +x permission.

I came across some other issues you might want to notice:

1. use dos2unix to convert the file encoding to unix encoding before it complaining about error syntax
2. The highest version app service for linux support is actually `v10.1.0`, not `v10.10.0`, I found this while debugging the deploy script. However, the portal let you choose `v10.10.0`, but it's not supported yet in linux container.

**Comment by JohnLTaylor** [comment]
The problem is that some commands require elevated permissions to run.  if the custom deployment script includes printenv then permission will be denied and you can't elevate with sudo

**Comment by ggirodda** [comment]
Same issue here, this is still a problem after two years. Every time there's a new subversion of node available in the node versions list, a problem occurs, and every time I have to spent hours trying the good combination to make things work. Can someone point me out an ultimate solution to finally have a configuration that works for more than 1 month ?

**Comment by jakehockey10** [comment]
Still having this issue

**Comment by kierzorz** [comment]
Same issue :( 

[config]
command = bash build.sh

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
