### ISSUE TITLE
Does .deployment file only work with git deployment?

### ISSUE THREAD

**Issue by escobar5** [projectkudu/kudu#2873]
I'm trying to use a custom deployment script for my Azure Function. I created the .deployment and deploy.cmd files with kuduscript, but then when I publish from visual studio nothing happens. Does that deployment script only work with git deployment? or should it also work when deploying via visual studio? is there anyway I can customize the deployment when deploying from visual studio?

**Comment by davidebbo** [comment]
VS deploys using msdeploy, which is separate from Kudu. `.deployment` files are only for Kudu based deployments.
