### ISSUE TITLE
This site can’t be reached

### ISSUE THREAD

**Issue by afiqster12** [projectkudu/kudu#2874]
### Repro steps.
> Used app service editor to make changes to code yesterday (2-10-2018)
> Next day, was not able to access the editor or its advance tools
> But was able to access my other projects on azure

### The log/error given by the failure.
> **Advanced Tools**
> This site can't be reached
> The webpage at https://studybotv2.scm.azurewebsites.net/ might be temporarily down or it may 
> have moved permanently to a new web address.
> ERR_TUNNEL_CONNECTION_FAILED
> **App Service Editor**
> This site can't be reached
> The webpage at https://studybotv2.scm.azurewebsites.net/dev/wwwroot/:vs.markdown/readme.md might be temporarily down or it may 
> have moved permanently to a new web address.
> ERR_TUNNEL_CONNECTION_FAILED

### Additional Details
> This happened before on other projects
> I also can't download the source code
> I've been running the build.cmd to save my code

**Comment by davidebbo** [comment]
Is it still in that state right now? And when that happens, are you able to go to the main site, i.e. https://studybotv2.azurewebsites.net/? If not, then it could be a case where the site is generally down, and not a Kudu specific issue.

**Comment by afiqster12** [comment]
I'm still not able to access the site and the main site as well. Is there a reason on why it is down?

**Comment by davidebbo** [comment]
Right now, I can access https://studybotv2.azurewebsites.net/ just fine, so it is likely something with your connection. e.g. does it work from your cell phone, so that you go through a different provider?

Closing as it does not appear to be a server issue.
