### ISSUE TITLE
Azure Websites Typescript 3

### ISSUE THREAD

**Issue by ghost** [projectkudu/kudu#2875]
I have an ASP.Net project which uses typescript 3 but only typescript 2.5 currently available in "D:\Program Files (x86)\Microsoft SDKs\TypeScript".

Any chance of adding Typescript 3?

Similar to this issue but for newer version.
https://github.com/projectkudu/kudu/issues/2509

**Comment by davidebbo** [comment]
@chrisfoster78 we are increasingly pushing users to Azure DevOps Pipelines (previously VSTS) for their CI/CD needs, instead of relying on Kudu. That's why the Kudu build environment is not up to date. Have you given this a try?

**Comment by chrisfoster78** [comment]
@davidebbo Yes we are using Azure DevOps for many of our larger jobs but still using Kudu for the others.  It is great to hear that you are focusing on a single method of deployment so we can do the same here.

For this particular job, we disabled typescript compilation and relied on it being done in Visual Studio as suggested in the linked issue.  However we'll definitely consider moving it over to Azure DevOps.

Thanks

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
