### ISSUE TITLE
Diagnosing temp file usage in an app service plan when you have several app services

### ISSUE THREAD

**Issue by samuelbcollie** [projectkudu/kudu#2881]
I recently received an alert in azure portal about temp file usage. Collectively, we were using 721 GB's of file usage across our app services. I followed the advice the alert gave me, which was to navigate to one of my app services in this App Service Plan and follow these links: 

Diagnose and solve problems -> Best Practices -> Best Practices for Availability, Performance -> Temp File Usage On Workers

From this, I saw the name of "Machine Name" and instance id. I went to the kudu site for the app service I was on, and confirmed that it had the same instance id. However, when I checked D:/local/Temp and D:/local/AppData, I found both of them to be empty. I was on the kudu site for only one of my app services and there are several. Should I check every app service? Is there an easier way for me to diagnose which one is causing this issue? Any help would be appreciated.

**Comment by davidebbo** [comment]
The main site and the scm site do not share temp folders, so what you see under Kudu is not the temp space that your app sees. See [wiki](https://github.com/projectkudu/kudu/wiki/Understanding-the-Azure-App-Service-file-system#temporary-files) for more info.

**Comment by samuelbcollie** [comment]
"For an interim workaround, review the File System Quota Utilization table below to identify which workers are consuming more than 60% of their allotted quota. Connect to the Kudu site of each of the defaulting workers and clear the temp file contents. You may review the Understanding the Azure App Service file system article for information on where the temp files are stored." 

Why is this the suggested workaround if the kudu site and the app service site don't share temp folders? Even after setting "WEBSITE_DISABLE_SCM_SEPARATION" to true, we were unable to find the offending app service. We have 21 app services on our app service plan, and manually checking each one is not ideal. Is there another way we can troubleshoot this?

**Comment by samuelbcollie** [comment]
We've resolved the issue by deleting and re-creating all of our app services (Deleted staging slots recreated them,, deployed to staging slots, swapped, then deleted the staging slots, and recreated them). We're now down to ~300GB of file usage. We'll continue to monitor our app services in case this issue comes up again. Here's the full text of the alert:

 "Your app {app service name}, and other apps within the same App Service Plan, have been identified as apps that may be affected by an upcoming infrastructure change to improve performance and uptime. As a part of the change, we will need to apply a quota on the amount of drive space your apps can use for temporary files. The quota is applied across all apps in the same App Service Plan, and differs based on plan. Details on the limits are outlined at https://github.com/projectkudu/kudu/wiki/Understanding-the-Azure-App-Service-file-system. Based on your current plan selection, you have an expected quota limit of 58 GBs, while peak usage was observed at 721.42 GBs on 1 or more workers. You can check your current limit and usage in portal by going to "Diagnose and solve problems" section of your App Service blade, selecting "Best Practices", "Best Practices for Availability, Performance", and then "Temp File Usage On Workers". In order to avoid impact, please update your app(s) to reduce usage and reliance on temporary files before November 2018."

The instructions for the workaround came from following "Diagnose and solve problems -> Best Practices -> Best Practices for Availability, Performance -> Temp File Usage On Workers". Those instructions don't appear if you're file usage isn't above a certain threshold.

**Comment by davidebbo** [comment]
@samuelbcollie 300GB of temp file usage is still enormous. Is that something expected for you based on what your apps are doing?

**Comment by davidebbo** [comment]
@samuelbcollie it's everything that ends up in `d:\local`. Notes:

- Each site instance has a different `d:\local`
- For each site, the main site and scm site have a distinct `d:\local`, as discussed above
- `D:\local\Temp` is what %TMP% points to, so that's typically where most of the space is taken

**Comment by valeriob** [comment]
Hi,
i'm having the same problem, i'm deploying 5 aspnet core web app on a linux app service, i have no clue on what is eating up the sapce and i do not have any visibility on that. 
This guide is not right anymore (i see no Temp File Usage On Workers) : 
Diagnose and solve problems -> Best Practices -> Best Practices for Availability, Performance -> Temp File Usage On Workers
How can i diagnose what's eating up 34GB of space ? since i just deployed 5 web app each is 10mb in size. I understand that maybe the debian image is about 200mb and they all share the same base image.
Thanks

**Comment by wShaw** [comment]
I'm having the same issue - can someone please update https://github.com/projectkudu/kudu/wiki/Understanding-the-Azure-App-Service-file-system so I know where to find this metric? Diagnose and solve problems -> Best Practices -> Best Practices for Availability, Performance -> Temp File Usage On Workers doesn't exist for me.

**Comment by nmallick1** [comment]
@wShaw, did you have a Linux app ? This wasn't working for Linux apps. We've deployed a change and you should now be able to see it now.

If you still don't see it, let me know the site name and I will take a look.

**Comment by danobri** [comment]
@davidebbo - so how do you view the temp folder for the app service itself?  

I have an app service that is occasionally hitting the temp space max causing errors on the site, and I can't figure out how to troubleshoot.  The guidance still says "Connect to the Kudu site of each of the defaulting workers and clear the temp file contents."  If I am understanding correctly, it sounds like that is not possible?

**Comment by suwatch** [comment]
Is this Linux or Windows App Service?  Only the size (eg. remaining available space info is available on Kudu's Env tab) - not the actual local temp content of the main site.    You could also write codes in your application to periodically check local temp space and provide such information.

**Comment by danobri** [comment]
It's a Windows App Service.  Is implementing a custom solution in the application really the only way to monitor / troubleshoot temp space issues in an Azure App Service?

**Comment by davidebbo** [comment]
You can try setting `WEBSITE_DISABLE_SCM_SEPARATION=true`, which will make Kudu see the app's temp files. But you should only do it temporarily for testing as it's not a well supported setting. See https://github.com/projectkudu/kudu/wiki/Configurable-settings#use-the-same-process-for-the-user-site-and-the-scm-site.

Disclaimer: I'm no longer on the team, so just sharing a trick that works for some users.

**Comment by danobri** [comment]
@davidebbo Sorry if this is a dumb question, but how do you change this setting?  Also - can you explain what the risks are of changing it?  The documentation is not very clear on that, it just says it's not recommended.

**Comment by davidebbo** [comment]
Just set it as an App Setting in the Azure Portal (under Configuration). The risk is that it could break your app since it's not a well tested path. If the app is critical, I'd suggest trying that on a test site running the same bits.

**Comment by danobri** [comment]
Thanks for the assistance @davidebbo - I appreciate the help!
