### ISSUE TITLE
Doc out of date: "Setting up a VSTS account so it can deploy to a Web App"

### ISSUE THREAD

**Issue by BrendanGrant** [projectkudu/kudu#2882]
Trying to setup my own deployment from a VSTS project, I found https://github.com/projectkudu/kudu/wiki/Setting-up-a-VSTS-account-so-it-can-deploy-to-a-Web-App however it seems to be out of date in the new world of Azure DevOps Services, but not just in terms of name.

Specifically to carry out the linking I believe you have to click the "Setup Billing" option when looking at the ADOS Org, then select the Azure subscription to link it to.

**Comment by davidebbo** [comment]
Yeah, it's outdated. Hopefully there are now enough official docs that this page is no longer needed. e.g. https://docs.microsoft.com/en-us/azure/devops/pipelines/apps/cd/deploy-webdeploy-webapps. I added a note at the top.
