### ISSUE TITLE
WEBSITE_USE_ZIP vs WEBSITE_RUN_FROM_PACKAGE

### ISSUE THREAD

**Issue by berney** [projectkudu/kudu#2885]
https://github.com/projectkudu/kudu/wiki/Configurable-settings mentions `WEBSITE_USE_ZIP`, but https://github.com/Azure/app-service-announcements/issues/84 mentions `WEBSITE_RUN_FROM_PACKAGE` (which is the new name for `WEBSITE_RUN_FROM_ZIP`). Is `WEBSITE_USE_ZIP` a typo, or is it an old name (out of date docs), or is it a separate variable, if so what is the difference?

**Comment by davidebbo** [comment]
Yep, that was an even earlier name, sorry. I just updated the wiki.
