### ISSUE TITLE
Enabling ASP.NET Core 2.2 Runtime site extension in the Azure portal often does not work 

### ISSUE THREAD

**Issue by muratg** [projectkudu/kudu#2887]
_From @balachir on Tuesday, 18 September 2018 06:49:23_

### Scenario : 
- Clean machine with 15.9 Preview 2 + .NET Core 2.2 Preview 2 installed. 
- Create new ASP.NET Core 2.2 (.NET Core) web app > Empty or Web App (MVC) template 
- F5 and then Publish to Azure

### Repro Steps : 
- After publishing from VS, open the published web app on the Azure portal
- Add the "ASP.NET Core 2.2 (x86) Runtime" site extension following the instructions from [the documentation](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/azure-apps/?view=aspnetcore-2.1#deploy-aspnet-core-preview-release-to-azure-app-service). 

![image](https://user-images.githubusercontent.com/8246794/45669071-b148bc80-bad3-11e8-8020-aa1a27903d08.png)

![image](https://user-images.githubusercontent.com/8246794/45669136-e2c18800-bad3-11e8-803e-20da672f06ff.png)

### Issue : 
Gets stuck at this step. The OK button does not work most of the time. On rare occasions, it works.

![image](https://user-images.githubusercontent.com/8246794/45668535-f4099500-bad1-11e8-8740-8126a07d6136.png)
 
### Workaround: 
Enable the site extension via the Kudu site extensions tab.

![image](https://user-images.githubusercontent.com/8246794/45668542-01bf1a80-bad2-11e8-971e-132a95ff4ae9.png)

 

_Copied from original issue: aspnet/AzureIntegration#220_

**Comment by davidebbo** [comment]
To investigate, we would need:

- The app name
- The UTC time of a failed attempt

**Comment by balachir** [comment]
I tried this scenario out with 15.9 Preview 3 + 2.2 Preview 2 a few times yesterday and today, but I cannot get this issue to reproduce. I think we can close this as No Repro.
