### ISSUE TITLE
Restart site using Site Extensions tab in Kudu, it takes 5-10 minutes for the site to successfully run

### ISSUE THREAD

**Issue by balachir** [projectkudu/kudu#2888]
## SCENARIO 

1. Clean machine with 15.9 Preview 3 + .NET Core 2.2 Preview 2 installed. 
2. Create new ASP.NET Core 2.2 (.NET Core) web app > Web Application (MVC) template 
3. F5 
4. Publish to Azure
5. Add the "ASP.NET Core 2.2 (x86) Runtime" site extension using Kudu site extensions 

## REPRO STEPS 
After site extension has been added, hit the **Restart Site** button

![image](https://user-images.githubusercontent.com/8246794/47010743-be69c300-d0f4-11e8-8b54-92e1ed4ccf1c.png)

Try to view the published web app from the browser

## ACTUAL
Page still does not load on the published site. You continue to get the "internal server error" message below for about 5-10 minutes. After 5 - 10 minutes, the page loads successfully.

**App name** : BalaWeb20181016010308WebAppMvcAnc22coreNoAuth1 
**Time when restart was done** : 10/16/2018 8.15 am UTC time (approx.) 

![image](https://user-images.githubusercontent.com/8246794/47011167-1228dc00-d0f6-11e8-99ab-0ecf8e294bc3.png)

## EXPECTED
Page to load successfully immediately after the site has been restarted
![image](https://user-images.githubusercontent.com/8246794/47010899-389a4780-d0f5-11e8-8902-457aa66188b4.png)

## WORKAROUND
Use Restart button in the Azure Portal to restart the site. This allows the site to work immediately without having to wait for 5 - 10 minutes.

![image](https://user-images.githubusercontent.com/8246794/47011035-a6467380-d0f5-11e8-8312-ef4eac21ac34.png)

**Comment by davidebbo** [comment]
Note that the Restart button in the Kudu UI only restarts the scm site and not the main site. Which one are you trying to hit?

Generally, the recommended method to install site extensions is via the Azure Portal, which does a better job with the restart behavior. The Kudu UI is more of an unofficial backdoor.

**Comment by frankfuu** [comment]
hi @davidebbo,

1. Is there a way to restart the `scm` site via the [REST API](https://github.com/projectkudu/kudu/wiki/REST-API)?
2. Does restarting the `main` site also restart the `scm` site in the background?

Background information: I've automated my deployment of my `applicationHost.xdt` transform file using the [Kudu VFS API](https://github.com/projectkudu/kudu/wiki/REST-API) which neatly PUTs my file in the `d:\home\site` folder  (**WITHOUT** using the [IIS Manager](https://github.com/shibayan/IISManager) site extension) and would like to include this in my CI/CD pipeline but as I understand that any applicationHost.config changes need both the `scm` and `main` site to be restarted? Or am I missing something?

Thanks

**Comment by davidebbo** [comment]
Note: I'm no longer working at Microsoft, so others here are better contacts now.

Restarting the site does indeed restart the scm site as well.

For xdt, technically you only need to restart the site that is affected by your xdt. But since the ARM API restarts both, that's your best bet. Be aware that the Restart API is async and can take like 30s before the site is up again.

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
