### ISSUE TITLE
Improve "An error has occurred." message

### ISSUE THREAD

**Issue by ejizba** [projectkudu/kudu#2889]
Over the past several months we've had several users report issues deploying to both web apps and function apps with the unhelpful message of "An error has occurred.". This error message is not defined anywhere in our codebase (for the VS Code extensions) so I'm wondering if this is coming directly from Kudu? Are you familiar with this error? Is there any possible way to add more detail when this happens?

Here's a sampling of the issues filed:
https://github.com/Microsoft/vscode-azurefunctions/issues/645
https://github.com/Microsoft/vscode-azureappservice/issues/405
https://github.com/Microsoft/vscode-azurefunctions/issues/692
https://github.com/Microsoft/vscode-azurefunctions/issues/662
https://github.com/Microsoft/vscode-azurefunctions/issues/644

Unfortunately I've never been able to get a consistent repro myself.

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
