### ISSUE TITLE
Extend /api/diagnostics/runtime to return information about installed .NET Core runtimes

### ISSUE THREAD

**Issue by davidebbo** [projectkudu/kudu#2890]
Similar to how we return Node versions, the API should return .NET Core versions.

We need to figure out the schema that makes sense for .NET Core.

**Comment by davidebbo** [comment]
Proposed design: the API would return the following payload (stubbing out the unrelated `nodejs` and `system` nodes for conciseness):

```json
{
  "nodejs": [],
  "dotnetcore": {
    "runtime32": [ "1.0.12", "1.1.9", "2.0.9", "2.1.4", "2.1.5" ],
    "sdk32": [ "1.1.10", "2.1.402", "2.1.403" ],
    "runtime64": [],
    "sdk64": []
  },
  "system": {}
}
```

The versions would be ordered in the arrays using proper semver ordering.

**Comment by davidebbo** [comment]
@davidfowl / @vijayrkn: to get the list of runtimes, should we be looking under `dotnet\shared\Microsoft.NETCore.App`, or under `dotnet\shared\Microsoft.AspNetCore.All`? Right now in Azure, I see `Microsoft.AspNetCore.All` (and `Microsoft.AspNetCore.App`) only have 2.1.x versions, while `dotnet\shared\Microsoft.NETCore.App` also has 1.x and 2.0.x.

So I'm pretty sure looking in `dotnet\shared\Microsoft.NETCore.App` is what we want here, but please confirm.

**Comment by davidfowl** [comment]
I actually think you need all. So the schema needs shared frameworks and then versions of those shared frameworks.

**Comment by davidebbo** [comment]
Let's reverse thing: come up with the exact schema that works best for you (by giving some json example), and we can do that. e.g. you could choose to have a 32 bit prop that then contains all the 32 bit related things, rather than having 32 and 64 together using a bitness suffix. It's all equally easy to do.

**Comment by davidfowl** [comment]
That sounds good.

**Comment by vijayrkn** [comment]
+ @mlorbetske

**Comment by davidebbo** [comment]
Guys, can we please agree on a design? I can then move that forward and get it deployed.

**Comment by davidfowl** [comment]
OK so I think it should look like this:

```JSON
{
  "dotnetcore32": {
    "shared": {
      "Microsoft.NetCore.App": [ "1.0.12", "1.1.9", "2.0.9", "2.1.4", "2.1.5" ],
      "Microsoft.AspNetCore.App": [ "2.1.4", "2.1.5" ],
      "Microsoft.AspNetCore.All": [ "2.0.0", "2.0.1" ],
    },
    "sdk" : [ "1.1.10", "2.1.402", "2.1.403" ]
  },
  "dotnetcore64": {
  }
}
```

**Comment by davidfowl** [comment]
@davidebbo does the node information return the "current" information? Are there defaults? We could add that information to this schema but I'm not sure it's relevant.

**Comment by DamianEdwards** [comment]
I think we should include the host version (`dotnet.exe` version) and "default" SDK version (the one at the top of `dotnet --info` output).

**Comment by davidebbo** [comment]
Currently, nothing returned by this API is affected by the configuration of the app. It's all driven by looking through files on the VM.

@DamianEdwards is the host version basically the list of sub-folders under `dotnet\host\fxr`? Or is it the file version of `dotnet.exe` in the root `dotnet` folder.

Anyway, we can start with a core set that we understand, and add to it later. But ideally, we can avoid changing the high level structure later (i.e. only make additive non-breaking changes).

**Comment by davidfowl** [comment]
Lets start with this, the schema as defined now is extensible. I'll do a pass to see if there's any IIS/ANCM information that could be useful here.

**Comment by DamianEdwards** [comment]
All good. The proposal above is a safe place to art.

**Comment by shirhatti** [comment]
Can we also expose the version of the ANCM currently deployed? We want the file version for both ANCM (`%SYSTEM32%\inetsrv\aspnetcore.dll`) and ANCMv2 (`%PROGRAMFILES%\IIS\Asp.Net Core Module\V2\aspnetcorev2.dll`)?

**Comment by davidfowl** [comment]
@shirhatti Can you update the JSON schema

**Comment by shirhatti** [comment]
How's this?
```json
{
  "dotnetcore32": {
    "shared": {
      "Microsoft.NETCore.App": [ "1.0.12", "1.1.9", "2.0.9", "2.1.4", "2.1.5" ],
      "Microsoft.AspNetCore.App": [ "2.1.4", "2.1.5" ],
      "Microsoft.AspNetCore.All": [ "2.0.0", "2.0.1" ],
    },
    "sdk" : [ "1.1.10", "2.1.402", "2.1.403" ]
  },
  "dotnetcore64": {
  },
  "aspnetcoremodule": {
    "aspnetcoremodule": "8.1.1993.0",
    "aspnetcoremoduleV2": "12.2.18285.0"
  }
}
```

**Comment by vijayrkn** [comment]
@mlorbetske - Can you give this a try?

**Comment by davidebbo** [comment]
@shirhatti @vijayrkn please also see the discussion with @davidfowl on the PR https://github.com/projectkudu/kudu/pull/2891

But please do give it a try

**Comment by mlorbetske** [comment]
It seems like some calls to the API are returning with a 502 with the below body - would anyone be able to take a look?

cc @phil-allen-msft

```
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>
<title>502 - Web server received an invalid response while acting as a gateway or proxy server.</title>
<style type="text/css">
<!--
body{margin:0;font-size:.7em;font-family:Verdana, Arial, Helvetica, sans-serif;background:#EEEEEE;}
fieldset{padding:0 15px 10px 15px;} 
h1{font-size:2.4em;margin:0;color:#FFF;}
h2{font-size:1.7em;margin:0;color:#CC0000;} 
h3{font-size:1.2em;margin:10px 0 0 0;color:#000000;} 
#header{width:96%;margin:0 0 0 0;padding:6px 2% 6px 2%;font-family:"trebuchet MS", Verdana, sans-serif;color:#FFF;
background-color:#555555;}
#content{margin:0 0 0 2%;position:relative;}
.content-container{background:#FFF;width:96%;margin-top:8px;padding:10px;position:relative;}
-->
</style>
</head>
<body>
<div id="header"><h1>Server Error</h1></div>
<div id="content">
<div class="content-container"><fieldset>
  <h2>502 - Web server received an invalid response while acting as a gateway or proxy server.</h2>
  <h3>There is a problem with the page you are looking for, and it cannot be displayed. When the Web server (while acting as a gateway or proxy) contacted the upstream content server, it received an invalid response from the content server.</h3>
</fieldset></div>
</div>
</body>
</html>
```
