### ISSUE TITLE
Memory Leak in Kudu/Mono

### ISSUE THREAD

**Issue by phawxby** [projectkudu/kudu#2896]
We're into our 4th week of chasing around MS support regarding a memory leak, ticket number 118092619099701. 

It's pretty bad. 
<img width="508" alt="brand-engine-us-east-requests" src="https://user-images.githubusercontent.com/1090602/47579907-4cd81300-d945-11e8-9d89-07e8baf504a8.PNG">

So bad it can cause a crash and an app restart. In this case it exhausted all the memory and swap file of the host.
<img width="478" alt="brand-engine-us-east-dev" src="https://user-images.githubusercontent.com/1090602/47579926-595c6b80-d945-11e8-9f78-3897f71b722e.PNG">

You may be thinking why am I bothering you with this, well it's a node application and the memory leak is occuring in Mono.
<img width="1273" alt="smoking gun" src="https://user-images.githubusercontent.com/1090602/47579997-8a3ca080-d945-11e8-957b-af260f437e50.PNG">

Quote from MS support. 
"And the process “mono” is taking gradually the memory during the days... Mono is part of the Kudu container... This behavior is being detected by our Product Group and they are investigating how to handle."

While I realise that this is being investigated I'd quite like a public record of this for anyone else suffering from the same problem.

**Comment by davidebbo** [comment]
Adding Linux label, and tagging @rramachand21.

**Comment by phawxby** [comment]
Further updates from support.

> Most of the memory that is related to mono process as you have seen before. I have discussed the scenario with our Product Group and there is detected scenario that they are working on that.
> 
> Our Product Group is introducing two new changes that will come out shortly in the next one-two months (tentative ETA). We will announce details when we are ready. One change shall **eliminate the need for mono** for Kudu completely and hence reduce/eliminate the memory usage in mono due to Kudu.
> 
> For now, if you do reach very high memory usage, the easiest workaround is to restart the website. Restart always does an overlapped recycle – so there should be no associated downtime. Restarting the website will also restart Kudu and it will clean up the memory.

My current plan is to implement a weekly reboot cron to deal with this. Not ideal but it'll do the job until the issue is properly fixed.

**Comment by phawxby** [comment]
@blueelvis same. Things have got better in recent weeks, I would estimate the leak rate has roughly halved. 

I can no longer see the Mono process in the process list and none of the running processes I can see are showing increasing memory usage. This makes me think the leak is now occuring in the host somewhere but I can't be sure. 

In the meantime we have a automated app restart triggered by a CircleCI cron job late in a weekend and we have over provisioned the server so we have excessive memory headroom. 

Our support agent desperately wants to close the ticket we have open but I've requested to keep it open. Whatever internal reporting tool they have I want to show a Severity 2 ticket open for months so it can't drop in priority.

**Comment by blueelvis** [comment]
@phawxby - Same here. The ticket is open since quite some time now. I am still seeing the troughs when I check the memory metrics. The ASP is on Premium 2 but still this happens. We also see auto scaling out events during the week despite minimum requests and the CPU not staying in the peak for long enough. Do you experience the same as well?

Our support rep has given a workaround to scale up and then down so that the App Service Plan moves to a new VM but it requires a couple of minutes of downtime for both operations...

**Comment by phawxby** [comment]
@blueelvis no, we've never autoscaled. Our autoscaling in configured based on average CPU over 5 minutes, with 7 instances over 3 regions we've got an awful lot of performance headroom.

Application restart is the best way we've found to deal with the issue as the old processes are not recycled until the new processes are online. 0 downtime. 

If you are suffering downtime during a scale up/down which you cannot afford then I would suggest bringing a second region online and using a traffic manager. You'll be able to disable it in the balancer, scale it, then enable it again, then do the same for the other region.

**Comment by ananthb86** [comment]
@phawxby  Did the issue of increasing memory got resolved for you? I am observing similar behaviour in one of our linux container based app service running on P2V1 tier. The `average memory working set` metric in the portal shows a steady increase in memory from the time of deploy even though there is no real load on this application.  SSH'ed to the application container and see the application processes are not holding up memory. The RES/RSS is pretty stable at 12-13MB.

**Comment by phawxby** [comment]
@ananthb86 We're running P2V2 and haven't see any memory related issues in a long time. That being said we did see significantly improved memory usage when we updated from Node 10 -> 12, so I'm not sure if that's a factor. 

![image](https://user-images.githubusercontent.com/1090602/83645277-31fe6380-a5aa-11ea-93c1-62f771244f2f.png)

**Comment by ananthb86** [comment]
@phawxby Thank you for the information.  In our case we are already on node 12 also checked the node version in Kudu container it is 12.16.1.

We have raised a case with MS support and awaiting feedback

**Comment by phawxby** [comment]
@ananthb86 sorry I couldn't be more help. Good luck.
