### ISSUE TITLE
Azure Web App sandbox wiki clarification: Implications for cryptography?

### ISSUE THREAD

**Issue by benrhere** [projectkudu/kudu#2897]
The wiki states:

"Unfortunately, many core components of Windows have been designed as shared components: the registry, cryptography, and graphics subsystems, among others. This section outlines the limitations placed on usage of these often essential, yet shared components."

There is no further mention in the document about cryptography. I'd like to understand the implications here. Specifically, I'm having trouble constructing a X509Certificate2 object, only in my Azure Web App. Others have had the same problem and the posted solution seems to be to use the machine store, where the private key will be placed temporarily:

https://stackoverflow.com/questions/18959418/site-in-azure-websites-fails-processing-of-x509certificate2

Unless this store location is virtualized per user, it's surprising to me that this would work at all. Presuming that it does, I'd like to  understand if it's safe to proceed with this solution.

I'd also suggest updating that wiki doc with some related info if pertinent.

Thanks...

**Comment by suwatch** [comment]
see if [this](https://github.com/projectkudu/kudu/wiki/Configurable-settings#the-system-cannot-find-the-file-specified-issue-with-x509certificate2) help.

**Comment by benrhere** [comment]
Hi @suwatch , thank you for the prompt response. That information did indeed help me to resolve my issue. I'm still curious, though, about your thoughts on the solution posted in that SO thread. If sandboxed applications can access the machine key store, is that a risk?

**Comment by suwatch** [comment]
Umm .. scanning thru the article, the user mentioned "Access Denied" if doing such.   So what is the risk?  Maybe I am missing something.

**Comment by benrhere** [comment]
The question does state an access denied error, but the accepted solution, with 63 upvotes, states:

```
var myCertificae = new X509Certificate2(
    certificateData,
    securePasswordString,
    X509KeyStorageFlags.MachineKeySet | 
    X509KeyStorageFlags.PersistKeySet | 
    X509KeyStorageFlags.Exportable);
```

will circumvent that error.

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
