### ISSUE TITLE
Failing site start after GitHub deploy

### ISSUE THREAD

**Issue by thomassondergaard** [projectkudu/kudu#2899]
> For deployment issues, please provide us with the following information:
> ---------------------------------------------------------------

### Repro steps.
> Vue.js app created in VS Code based on standard Vue-CLI/Webpack template.
> Deployed automatically to Azure App Service when pushed to GitHub.
> Builds without errors.
> Cannot restart the container.

### Project structures.
> Standard Vue.js/Webpack.

### The log/error given by the failure.
> Container starts:

2018-11-01 07:56:49.418 INFO  - Starting container for site
2018-11-01 07:56:49.419 INFO  - docker run -d -p 44143:8080 --name [containername] -e WEBSITE_NODE_DEFAULT_VERSION=8.9 -e APPSETTING_WEBSITE_NODE_DEFAULT_VERSION=8.9 -e WEBSITE_SITE_NAME=[sitename] -e WEBSITE_AUTH_ENABLED=False -e WEBSITE_ROLE_INSTANCE_ID=0 -e WEBSITE_INSTANCE_ID=31c0e[...]89f1 -e HTTP_LOGGING_ENABLED=1 appsvc/node:8.9.4_1804040228

> Then this:

2018-11-01 08:01:25.406 ERROR - Container [containername] for site [sitename] has exited, failing site start Status_WatchFile :: Error Error: ENOENT: no such file or directory, open '/appsvctmp/status.txt'Status_WatchFile :: Error Error: ENOENT: no such file or directory, open '/appsvctmp/status.txt'

> This error does not show up if I go through the Kudu logs but I can see it in the Log Stream in Azure.

I've tried a few time and I can see that sometimes the status.txt file is present. It seems to be there when a site start is attempted. As of now, I'm unsure if this is Kudu related but I would appreciate any pointers!

### Debug your Azure website remotely. 

> Subscription GUID (partial): ec46...1414

**Comment by shadyshrif** [comment]
I had the same issue with py flask project deployment form bitbucket. seems that it was caused by a compilation error while deploying.

I don't know exactly what was the error but when I reverted to a previous version; everything worked well

**Comment by RicardoGaefke** [comment]
Hi @thomassondergaard and @shadyshrif 
Hi everyone
Did you find a solution? My Linux webapp is running into same situation and sometimes it starts, sometimes it doesn't.
Thank you very much.

**Comment by deantakacs** [comment]
Hi All!
Just ran into the same issue!  I did the following and it worked:
In the Azure App Service "Overview" section, (Where you can start and stop the app), click the "Reset Publish Profile" button.  It worked immediately after this.  The issue MAY be due to trying different deployment methods.  (IE Trying FTP or Github first, then trying local git)
Regards

**Comment by RicardoGaefke** [comment]
Hi @deantakacs ... I'll try it... It's strange because it just happens with Linux WebApps... Win ones always start file...

**Comment by DSpirit** [comment]
This happens to me when deploying dockerized linux functionapps (dotnet v2) to an elastic premium app service plan. The functionapp is then either unavailable or returning an application error. Temporarily it seems scaling out the workers helped, although it already crashed after running fine for ~20 minutes.

**Comment by pointerness** [comment]
Did anyone find a solution how to fix this. I am deploying a Python Django Webapp, via azure pipeline. The code is successfully deployed via vscode. But fails when deployed via azure pipeline

**Comment by suwatch** [comment]
Did you check the WebApp content (SCM site -> Debug Console -> d:\home\site\wwwroot)?  Are they the same whether deploying from Azure DevOps Pipeline or VSCode?

**Comment by pointerness** [comment]
It's Linux container. The container actually doesn't even start. I get a message container xxxx exited. I downloaded the artefact and ran it locally . Seems to be fine. As the container is not running. I can't ssh. Apart from log stream there is not much for me to debug

**Comment by suwatch** [comment]
Ok .. that might be a totally issue altogether - we suggest to open a new gissue to track this specifically.

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
