### ISSUE TITLE
Character entities converted to text during zip deployment

### ISSUE THREAD

**Issue by bscaspar** [projectkudu/kudu#2900]
### Repro steps.
Project deploys successfully but character entities in HTML are converted to text. `&nbsp;` -> Â, `&thinsp;` -> â€‰. 

Deployed using "az webapp up" from Azure command shell. I cloned the following repository into my cloud drive then ran that command in branch master, dir build.
https://github.com/bscaspar/PersonalSite/. This directory is the output from Webpack v 4.20.2.

web app name: personal-site-bc
url: https://personal-site-bc.azurewebsites.net/

### Mention any other details that might be useful.
First time poster 😄 I tried to do some research but didn't find anything similar. Opening an issue here since it happened during deploy. Thank you!

Edit: this also happens when I deploy using the Storage Static Website preview feature. I used the VS Code UI to deploy, URL is here: https://personalsitestorage.z22.web.core.windows.net/

This also does not happen using Surge or [GH pages](https://bscaspar.github.io/PersonalSite/).

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
