### ISSUE TITLE
AppSettings set through Azure portal are not visible in Application_End application event handler

### ISSUE THREAD

**Issue by samfromlv** [projectkudu/kudu#2903]
Recommended approach to deal with Application Settings set through Azure Portal for .NET applications is to use ConfigurationManager.AppSettings["MySetting"] in ,Net code. This works fine in almost all cases. However when accessing Application Settings from [Application_End](https://msdn.microsoft.com/en-us/library/ms178473.aspx?f=255&MSPPError=-2147217396) global event handler in Global.aspx, settings set through Azure Portal are not avaliable,  ConfigurationManager.AppSettings["MySetting"] just returns empty string or value from web.config if it was set there.

### Repro steps.
1) Clone the repo - https://github.com/samfromlv/AzureKuduApplicationEndTest
2) Deploy to new Azure App Service
3) Enable Application Logging to file system with Information level in App Service settings using Azure Portal
4) Observe that application root url ("/") when opened shows this information "connectionStringValue=ConnectionStringValueFromWebConfig settingValue=MySettingValueFromWebConfig"
5) Go to Azure porta> App Service > Application Settings tab and add new Application Setting "MySetting" with "MySettingValueFromAzurePortal"
6) In Azure Portal in Application Settings add new connection string "ApplicationEndKuduTest.Properties.Settings.MyConnectionString" with type "Custom" and value "MyConnectionStringValueFromAzurePortal"
7) Save Application Settings in Azure Portal
8) Observe that application root url when opened shows this information "connectionStringValue=MyConnectionStringValueFromAzurePortal settingValue=MySettingValueFromAzurePortal"
9) Open Log Stream in Azure Portal and switch to Application Log, wait until Log Stream is connected
10) In separate browser tab stop App Service using Azure Portal
10) Observe new entries Log stream and find entries similar to these
2018-11-06T08:20:40 PID[20532] Information connectionStringValue=ConnectionStringValueFromWebConfig 
2018-11-06T08:20:40 PID[20532] Information settingValue=MySettingValueFromWebConfig

EXPECTED: Log stream should show connectionStringValue=MyConnectionStringValueFromAzurePortal and settingValue=MySettingValueFromAzurePortal 
ACTUAL: : Log stream should show connectionStringValue=ConnectionStringValueFromWebConfig and settingValue=MySettingValueFromWebConfig

**Comment by mbrierst** [comment]
I can verify this issue.  A workaround is to store the values you need later in static attributes in Application_Start.  It may be impossible for Application_End to get the correct values as the web.config has probably been overwritten with the untransformed file, which is what led to Application_End being called in the first place.

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
