### ISSUE TITLE
no /api/deployments/latest/log file after fail

### ISSUE THREAD

**Issue by estei** [projectkudu/kudu#2906]
We have a lot of zip deploys failing because of some issue unzipping the zip file. ( see #2905 )
When this happens we cannot get the log file for the latest deployment as we are pointed to in the JSON response from the deployment.

```json
{
  "active": false,
  "author": "N/A",
  "author_email": "N/A",
  "complete": true,
  "deployer": "Push-Deployer",
  "end_time": "2018-11-08T14:03:42.7384106Z",
  "id": "temp-1b69c7fc",
  "is_readonly": false,
  "is_temp": true,
  "last_success_end_time": null,
  "log_url": "https://sitename-stage.scm.azurewebsites.net/api/deployments/latest/log",
  "message": "Deploying from pushed zip file",
  "progress": "",
  "provisioningState": null,
  "received_time": "2018-11-08T14:03:36.397168Z",
  "site_name": "sitename",
  "start_time": "2018-11-08T14:03:36.397168Z",
  "status": 3,
  "status_text": "",
  "url": "https://sitename-stage.scm.azurewebsites.net/api/deployments/latest"
}
```

We can find the log by going in to the kudu backend and looking in the `/site/deployments` folder, where it can be found under its temp name (temp-1b69c7fc). It can also be found with a call to `/api/deployments/temp-1b69c7fc/log`

I think `/api/deployments/latest` should point to the log in this folder when such an early fail happens.

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
