### ISSUE TITLE
[kudu REST API upload zip] ExceptionMessage": "Central Directory corrupt when i test the api via postman

### ISSUE THREAD

**Issue by Arun7even** [projectkudu/kudu#2912]
> When i test the api using POSTMAN by attaching the .zip file to my url (https://azur**-8257.scm.azurewebsites.net/api/zipdeploy) i am getting a 500 internal server error.

INTERNAL EXCEPTION:
"Message": "An error has occurred.",
        "ExceptionMessage": "An attempt was made to move the file pointer before the beginning of the file.\r\n",
        "ExceptionType": "System.IO.IOException",
        "StackTrace": "   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)\r\n   at System.IO.FileStream.SeekCore(Int64 offset, SeekOrigin origin)\r\n   at System.IO.FileStream.Seek(Int64 offset, SeekOrigin origin)\r\n   at System.IO.Compression.ZipArchive.ReadEndOfCentralDirectory()"
> ---------------------------------------------------------------

**Comment by suwatch** [comment]
To rule out POSTMAN, mind trying with curl?  Also if you could try with a simple zip (just few files inside) for sanity?   This would help scope down the repro and get to the bottom faster.

**Comment by Arun7even** [comment]
I changed the option in request body from form-data to binary and it works!!
