### ISSUE TITLE
Kudu routinely misses Web Job invocations

### ISSUE THREAD

**Issue by bojingo** [projectkudu/kudu#2915]
We have a critical Web Job that uses a Timer Trigger to run every 5 minutes that is a single-point of failure for a broader system. Because of this, we've instrumented up monitoring via the Kudu `azurejobs/api/jobs/continuous/{webJobName}/functions?limit={maxExecutedFunctionsCount}` API. We evaluate the results send notifications if the most recent successful invocation has aged more than 20 minutes.

However, we get a TON of false notifications indicating that the Web Job hasn't run successfully for over 20 minutes, when it has. The issue appears to be that Kudu does not correctly log some executions in its back-end for return via the API listed above.

Here are some screen snippets that illustrate the issue:
![image](https://user-images.githubusercontent.com/671018/49943818-e2f4d800-feb6-11e8-8414-d35f394506f9.png)
According to the log stream from Kudu, the job triggered at 13:50 and 13:55.

However, in Kudu's invocation list, the execution at 13:55 is missing:
![image](https://user-images.githubusercontent.com/671018/49943887-0cadff00-feb7-11e8-9e10-3e3a189d1b1f.png)
It isn't simply a delay issue because you can see the invocation at 14:00 showing. The 13:55 was just completely skipped!

If this happens more than 3 times consecutively, we get the false notification, scramble to respond to the support incident, only to discover that the job did in fact invoke successfully. This happens a handful of times per day, so it is a huge issue for the support of this system.

Request:
1. Obviously, this needs to be fixed.
2. In the meantime, if anyone has an alternative suggestion for how to best monitor that this Web Job is invoking as expected, please share!

NOTE: The Web Job is running within an Azure App Service deployment.

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
