### ISSUE TITLE
[Linux] Unable to mount storage account to /home

### ISSUE THREAD

**Issue by blueelvis** [projectkudu/kudu#2916]
> For deployment issues, please provide us with the following information:
> ---------------------------------------------------------------

### Repro steps.
> Create a Web App for Container
> Go to Application Settings
> Scroll down and add a storage account to bring your own storage. Select a File Share and set the mount path to `/home`

### Project structures.
> Empty

### The log/error given by the failure.
> ``` :( Application Error
If you are the application administrator, you can access the diagnostic resources.```

### Debug your Azure website remotely.
> https://pranav-linux-test.azurewebsites.net/

### Mention any other details that might be useful.
1. Both the Kudu site and the main website start giving the Application error.
2. Removing that setting for the particular mount path fixes the issue.

**Comment by suwatch** [comment]
@rramachand21  for assistance.

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
