### ISSUE TITLE
502 error trying to change deployment branch using wiki instructions

### ISSUE THREAD

**Issue by ecmonsen** [projectkudu/kudu#2919]
### Repro steps.
1. create App Service
1. create Deployment using Local Git
1. push code to a branch that is not master, e.g. 'mybranch' (I'm building a Node app)
1. try to update the branch using the instructions here (the first curl command. Note I had to change the single quotes to doubles in the JSON data) https://github.com/projectkudu/kudu/wiki/Deployment-branch
1. example: ```curl -vR 'https://user:pass@site.azurewebsites.net/settings' \
       --data '{key: "branch", value: "mybranch" }' \
       -H "Content-Type: application/json; charset=UTF-8"```
1. Note: I replaced user:pass@site with the site found on the Overview for the app service on portal.azure.com, and user:pass by going to Deployment Center -> Deployment Credentials -> App Credentials 

### Project structures.
n/a

### The log/error given by the failure.
<pre>
< HTTP/2 502 
< content-length: 260
< content-type: text/html
< etag: "5c162d64-104"
< server: nginx
< set-cookie: ARRAffinity=b4a2564d88fd1d8c2f6d16a087d2a017231cd4562ce17a1f3b764d08bd7a8093;Path=/;HttpOnly;Domain=stctestdeployment.azurewebsites.net
< date: Tue, 15 Jan 2019 18:09:05 GMT
< 
&lt;html&gt;
    &lt;head&gt;
        &lt;title&gt; Server Error &lt;/title&gt;
    &lt;/head&gt;
    &lt;body&gt;
        &lt;font color =\"#aa0000\"&gt;
            &lt;h2&gt;Server Error.&lt;/h2&gt;
        &lt;/font&gt;

        There was an unexpected error in the request processing.
    &lt;/body&gt;
* Connection #0 to host stctestdeployment.azurewebsites.net left intact
</pre>

### Debug your Azure website remotely.
n/a

**Comment by scoffin-mtd** [comment]
Any luck on this? I'm seeing the same HTML block returned from my service.

**Comment by ecmonsen** [comment]
I don't think I ever got this working. Best of luck!

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
