### ISSUE TITLE
Application Logging for WebJobs is not persisted to LogFiles\Application when AzureDrive is enabled.

### ISSUE THREAD

**Issue by FinVamp1** [projectkudu/kudu#2921]
There are two scenarios here. 

1) Triggered Web Jobs

In this scenario WEBJOBS_LOG_TRIGGERED_JOBS_TO_APP_LOGS  app setting = true should be output to Logfiles\Application. This isn't happening. 

2) Continuous Web Jobs

https://github.com/projectkudu/kudu/wiki/WebJobs#logging specifies that if Application Logging is enabled then the full logs would to the Application Logs. 

https://github.com/projectkudu/kudu/issues/1748 is reporting this behaviour.

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
