### ISSUE TITLE
issue about zip/zipdeploy

### ISSUE THREAD

**Issue by honorew** [projectkudu/kudu#2923]
Hi，
 For zipdeploy interface, The document says you need to use form data to upload files,but after my test, you need to upload the file in binary format.Please verify.
thanks.

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
