### ISSUE TITLE
How to update git on App Service Editor?

### ISSUE THREAD

**Issue by KazTamai** [projectkudu/kudu#2925]
### Environment
App Service Editor(Preview) in App Service and git version is "Git for Windows 2.19.1.Windows.1 (64bit).
Not sure if every App Service Editor installs the same version of Git.

### What I am trying to do
Trying to clone a remote repository (in Azure Repos) to local repository (in App Service).

### The log/error given by the failure.
Facing this error a lot.
> fatal: NullReferenceException encountered.
   Object reference not set to an instance of an object.

### Mention any other details that might be useful.
Figured out this error might be caused by git version Git for Windows 2.19.1.windows.1 (64bit).
https://stackoverflow.com/questions/53150690/fatal-nullreferenceexception-encountered-when-interacting-with-remote

I tried to run the command "git update-git-for-windows" on App Service Editor but could not execute update.

------
Any thoughts on troubleshooting on this issue?

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
