### ISSUE TITLE
Deletion of recovery directory (nfs backed) fails when Kudu restarts

### ISSUE THREAD

**Issue by samasys** [projectkudu/kudu#2926]
### Repro steps.
Configured Kudu wal/data directories on NFS mounts, with block manager as FILE
Start Kudu, Insert some data
Restart Kudu
Restart fails with error "Error 39 Directory not empty"

### The log/error given by the failure.
Tablet failed to bootstrap: IO error: Could not remove renamed recovery dir 

### Mention any other details that might be useful.
If the wal directory is on a local disk, we do not see this issue.
The code actually walks through the directories and folders in the recovery directory, deletes those and then deletes the recovery directory. The last rmdir fails directory is not empty. It will be useful if Kudu process succeeds but mark the directory for deletion which could be removed  upon next restart or through a background process.

**Comment by grishick** [comment]
> ### Repro steps.
> Configured Kudu wal/data directories on NFS mounts, with block manager as FILE
> Start Kudu, Insert some data
> Restart Kudu
> Restart fails with error "Error 39 Directory not empty"
> 
> ### The log/error given by the failure.
> Tablet failed to bootstrap: IO error: Could not remove renamed recovery dir
> 
> ### Mention any other details that might be useful.
> If the wal directory is on a local disk, we do not see this issue.
> The code actually walks through the directories and folders in the recovery directory, deletes those and then deletes the recovery directory. The last rmdir fails directory is not empty. It will be useful if Kudu process succeeds but mark the directory for deletion which could be removed upon next restart or through a background process.

I think you are posting in the wrong project. This looks like a post for Apache Kudu https://kudu.apache.org
