### ISSUE TITLE
Zip Push Deployment to vapp/vdir

### ISSUE THREAD

**Issue by IlyaFinkelshteyn** [projectkudu/kudu#2927]
Does API for [Zip Push deployment](https://blogs.msdn.microsoft.com/appserviceteam/2017/10/16/zip-push-deployment-for-web-apps-functions-and-webjobs/) to virtual app or directory exist?

Context: we in [AppVeyor](https://www.appveyor.com/) support [Zip Push deployment](https://www.appveyor.com/docs/deployment/azure-app-service-zip-push-deploy/). However some of our customers want to deploy to virtual app this way. Not sure if it is possible at all with Zip Push.

**Comment by suwatch** [comment]
@IlyaFinkelshteyn   could you look at SCM_TARGET_PATH on this https://github.com/projectkudu/kudu/wiki/Deploying-inplace-and-without-repository page?  See if that helps.

**Comment by jmck-contessa** [comment]
@IlyaFinkelshteyn funny enough, I have been tackling this issue all day with no success. Zip Push deployment does not support a virtual directory target. My thought was to set the SCM_TARGET_PATH as @suwatch suggested, but instead by using the `api/command` endpoint just before and after deployment.  Unfortunately, I manually set that environment variable through the portal as a test and attempted a zip push deployment without success. Finally, I tried using [the REST API ](https://github.com/projectkudu/kudu/wiki/REST-API) directly (see very bottom of page) to sort of force a deployment without all of the features of the zip push deployment (see [here](https://blogs.msdn.microsoft.com/appserviceteam/2017/10/16/zip-push-deployment-for-web-apps-functions-and-webjobs/) for what features it brings to the table that aren't available by hitting the API directly.) I can not seem to get it work appropriately as the dump from curl always returns the below error. I am also at a loss for how this has been overlooked and interested if anyone else has solved this problem.

```
== Info: Recv failure: Connection reset by peer
== Info: stopped the pause stream!
== Info: Closing connection 0
```

**Comment by jmck-contessa** [comment]
Apparently I did not click `Save` in the azure portal after adding the SCM_TARGET_PATH manually. I was able to do that and even use the `az webapp deployment source config-zip` cli directly to push to a virtual directory. Unfortunately, I am still having an issue with hitting any of the kudu api's successfully. I believe if we can set that environment variable before deploying, do the zip push, and unset the variable afterward then this could work. Hopefully someone can look at this trace and tell what I may be doing wrong.

Current trace from unsuccessful curl:
```
== Info:   Trying <ommitted>...
== Info: TCP_NODELAY set
== Info: Connected to <ommitted>.scm.<ommitted>.p.azurewebsites.net (<ommitted>) port 443 (#0)
== Info: Server auth using Basic with user '<ommitted>'
=> Send header, 324 bytes (0x144)
0000: POST /api/command HTTP/1.1
001c: Host: <ommitted>.scm.<ommitted>.p.azurewebsites.net:
005c: 443
0061: Authorization: Basic <ommitted>
00a1: <ommitted>
00e1: <ommitted>
00e8: User-Agent: curl/7.54.0
0101: Accept: */*
010e: Content-Type: application/json
012e: Content-Length: 65
0142: 
=> Send data, 65 bytes (0x41)
0000: {command: 'setx SCM_TARGET_PATH <virtual dir>', dir: 'site/repository'
0040: }
== Info: upload completely sent off: 65 out of 65 bytes
== Info: Recv failure: Connection reset by peer
== Info: stopped the pause stream!
== Info: Closing connection 0

```

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
