### ISSUE TITLE
Deleting custom properties that contain a colon in the name crashes the site

### ISSUE THREAD

**Issue by xt0rted** [projectkudu/kudu#293]
If I add a custom property such as `sample:key`, and then try to delete it, the site crashes saying

> Only 'http' and 'https' schemes are allowed.
> Parameter name: requestUri

**Comment by jvano** [comment]
Hi

Kudu will continue to run in Azure App Service. However, this repo will no longer be maintained.
If the problem persists and is related to running on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
