### ISSUE TITLE
Deployment fails when including Cognitive Services SDK

### ISSUE THREAD

**Issue by timheuer** [projectkudu/kudu#2931]
I have an ASPNET Core 2.2 project and it succeeds to deploy initially, but when adding a specific NuGet SDK package and deploying again, it fails with error noted below.

### Repro steps.
1. Create ASP.NET Core 2.2 app using `dotnet new webapp` and `git init` the project to have local git
2. Create App Service web app via portal choosing Linux and .NET Core 2.2 as runtime option
3. Using deployment center in portal configure Local Git deployment with Kudu option
4. Add Kudu remote branch to local git project
5. Run `git push azure master`
EXPECT: Deployment succeeds, app is available
ACTUAL: Deployment succeeds, app is available
6. Add the Cognitive Services sdk via `dotnet add package Microsoft.Azure.CognitiveServices.Vision.Face --version 2.2.0-preview` to the project
7. `git commit` the change to your local git
8. Run `git push azure master` again
EXPECT: Deployment succeeds, app is available
ACTUAL: Deployment fails with permission errors

### Project structures.
Structure of project is the result from `dotnet new webapp` output, nothing changed

### The log/error given by the failure.
PS C:\Users\timheuer\Documents\GitHub\testwebapp> dotnet add package Microsoft.Azure.CognitiveServices.Vision.Face --version 2.2.0-preview
  Writing C:\Users\timheuer\AppData\Local\Temp\tmp7BE4.tmp
info : Adding PackageReference for package 'Microsoft.Azure.CognitiveServices.Vision.Face' into project 'C:\Users\timheuer\Documents\GitHub\testwebapp\testwebapp.csproj'.
log  : Restoring packages for C:\Users\timheuer\Documents\GitHub\testwebapp\testwebapp.csproj...
info : Package 'Microsoft.Azure.CognitiveServices.Vision.Face' is compatible with all the specified frameworks in project 'C:\Users\timheuer\Documents\GitHub\testwebapp\testwebapp.csproj'.
info : PackageReference for package 'Microsoft.Azure.CognitiveServices.Vision.Face' version '2.2.0-preview' added to file 'C:\Users\timheuer\Documents\GitHub\testwebapp\testwebapp.csproj'.
info : Committing restore...
info : Assets file has not changed. Skipping assets file writing. Path: C:\Users\timheuer\Documents\GitHub\testwebapp\obj\project.assets.json
log  : Restore completed in 2.67 sec for C:\Users\timheuer\Documents\GitHub\testwebapp\testwebapp.csproj.
PS C:\Users\timheuer\Documents\GitHub\testwebapp> git commit -a -m"added back cogsvcs package"
[master 30dad60] added back cogsvcs package
 1 file changed, 1 insertion(+)
PS C:\Users\timheuer\Documents\GitHub\testwebapp> git push azure master
Enumerating objects: 5, done.
Counting objects: 100% (5/5), done.
Delta compression using up to 8 threads
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 357 bytes | 357.00 KiB/s, done.
Total 3 (delta 2), reused 0 (delta 0)
remote: Deploy Async
remote: Updating branch 'master'.
remote: Updating submodules.
remote: Preparing deployment for commit id '30dad6012f'.
remote: Generating deployment script.
remote: Running deployment command...
remote: Handling ASP.NET Core Web Application deployment.
remote: ...
remote:   Restoring packages for /home/site/repository/testwebapp.csproj...
remote:   Installing Microsoft.Rest.ClientRuntime.Azure 3.3.13.
remote:   Installing Microsoft.Rest.ClientRuntime 2.3.12.
remote:   Installing Microsoft.Azure.CognitiveServices.Vision.Face 2.2.0-preview.
remote: /opt/dotnet/sdk/2.2.100/NuGet.targets(114,5): error : Access to the path '/var/nuget/microsoft.rest.clientruntime.azure/3.3.13' is denied. [/home/site/repository/testwebapp.csproj]
remote: /opt/dotnet/sdk/2.2.100/NuGet.targets(114,5): error :   Permission denied [/home/site/repository/testwebapp.csproj]
remote: An error has occurred during web site deployment.
remote: dotnet restore failed
remote: App container will begin restart within 10 seconds.
To https://timheuer-testwebapp.scm.azurewebsites.net:443/timheuer-testwebapp.git
   106d0fd..30dad60  master -> master

**Comment by muratg** [comment]
Does the same app work when you run it locally?

**Comment by timheuer** [comment]
Yes

-th

**Comment by tvperez76** [comment]
I'm experiencing a similar issue with my WebApp.  Could this be a .NET Core 2.2 issue?

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
