### ISSUE TITLE
Support semver notation for WEBSITE_NODE_DEFAULT_VeRSION

### ISSUE THREAD

**Issue by mhoeger** [projectkudu/kudu#2933]
You should be able to use semver notation with `WEBSITE_NODE_DEFAULT_VERSION` instead of exact match.

Corresponding change will also need to be made in dwas - we are starting here.

https://github.com/projectkudu/kudu/blob/master/Kudu.Core/Infrastructure/PathUtils/PathWindowsUtility.cs#L185

(@mhoeger will work on this in functions sprint 45)

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
