### ISSUE TITLE
Deploying WebJob that references another WebJob

### ISSUE THREAD

**Issue by dmarlow** [projectkudu/kudu#2934]
I have two WebJob projects, one project references the other one. When I attempt to deploy with MSBuild, it tries to deploy both. Because they go to different App Services, the password I use doesn't work for the other WebJob that's getting deployed, so things fail.

When I deploy via Visual Studio, it looks like it's only deploying one. When I do it from MSBuild via a command, it tries to deploy both. Is there something in the targets that allows me to only deploy one. How is it that VS only deploys the correct one? (I also just became aware that I need a run.cmd in order to run the correct executable, but I still need to figure out deployment).

I'm planning on creating a shared library project to combine things, but until then, what are my options?

**Comment by suwatch** [comment]
Given the nature of question (VS related - not Kudu specific), you might get faster/better responses posting to http://aka.ms/webappMSDNforumq.

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
