### ISSUE TITLE
Need to improve the backend logging mechanism for Azure WebJobs

### ISSUE THREAD

**Issue by sunnydewangan** [projectkudu/kudu#2935]
There was an issue that occurred multiple times for Azure Web jobs where we were not able to either delete the existing Webjobs or upload a new WebJob. This issue happened 5+ times, but still, the engineering team could not provide RCA asking to repro the issue again.

They said, the existing logs do not point out any of the root cause, and they don't know what was going on when the issue occurred.

In spite of the multiple occurrences of the issue if we are not able to get RCA, then you really need to improve the backend logging mechanism so that if the similar problems occur in future, we would have better monitoring control.

Here is the IcM which I am referring to : 

**https://icm.ad.msft.net/imp/v3/incidents/details/101588095/home**

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
