### ISSUE TITLE
Error running npm install npm ERR! keytar@4.4.1 install: `prebuild-install || node-gyp rebuild`

### ISSUE THREAD

**Issue by gpazo** [projectkudu/kudu#2936]
> For deployment issues, please provide us with the following information:
> ---------------------------------------------------------------

### Repro steps.
> your project built successfully on your dev machine but failed on Azure?

npm install from inside azure function directory fails with error above

> please write down your build tools and their versions (ie `Msbuild 15.1.0.0`)
node v10.14.1
npm 6.4.1
tedious 5.0.3
async 2.6.2
readable-stream 3.2.0

### Project structures.
> in order to reproduce your issue at our end we need a simple 
> [github repository](https://github.com/projectkudu/kudu/wiki/Using-a-git-repo-to-report-an-issue)
> that highlights structure of the project

https://gist.github.com/gpazo/8ad631d3f6097d20b23af79917ab8032

### The log/error given by the failure.
```
D:\home\site\wwwroot\HttpTrigger3>npm i
npm WARN deprecated nomnom@1.5.2: Package no longer supported. Contact support@npmjs.com for more info.
npm WARN deprecated cryptiles@2.0.5: This version is no longer maintained. Please upgrade to the latest version.
npm WARN deprecated hoek@2.16.3: This version is no longer maintained. Please upgrade to the latest version.
npm WARN deprecated boom@2.10.1: This version is no longer maintained. Please upgrade to the latest version.

> keytar@4.4.1 install D:\home\site\wwwroot\HttpTrigger3\node_modules\keytar
> prebuild-install || node-gyp rebuild

prebuild-install WARN install No prebuilt binaries found (target=10.14.1 runtime=node arch=ia32 libc= platform=win32)

D:\home\site\wwwroot\HttpTrigger3\node_modules\keytar>if not defined npm_config_node_gyp (node "D:\Program Files (x86)\npm\6.4.1\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "D:\Program Files (x86)\npm\6.4.1\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild ) 
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  async.cc
  main.cc
d:\local\userprofile\.node-gyp\10.14.1\include\node\v8.h(21): fatal error C1083: Cannot open include file: 'memory': No such file or directory (compiling source file ..\src\main.cc) [D:\home\site\wwwroot\HttpTrigger3\node_modules\keytar\build\keytar.vcxproj]
  keytar_win.cc
d:\local\userprofile\.node-gyp\10.14.1\include\node\v8.h(21): fatal error C1083: Cannot open include file: 'memory': No such file or directory (compiling source file ..\src\async.cc) [D:\home\site\wwwroot\HttpTrigger3\node_modules\keytar\build\keytar.vcxproj]
  win_delay_load_hook.cc
..\src\keytar_win.cc(6): fatal error C1083: Cannot open include file: 'wincred.h': No such file or directory [D:\home\site\wwwroot\HttpTrigger3\node_modules\keytar\build\keytar.vcxproj]
gyp ERR! build error 
gyp ERR! stack Error: `msbuild` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (D:\Program Files (x86)\npm\6.4.1\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "D:\\Program Files (x86)\\nodejs\\10.14.1\\node.exe" "D:\\Program Files (x86)\\npm\\6.4.1\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\home\site\wwwroot\HttpTrigger3\node_modules\keytar
gyp ERR! node -v v10.14.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm WARN rollback Rolling back node-pre-gyp@0.10.3 failed (this is probably harmless): EPERM: operation not permitted, rmdir 'D:\home\site\wwwroot\HttpTrigger3\node_modules\fsevents\node_modules'
npm WARN azure-nodejs@1.0.0 No repository field.
npm WARN azure-nodejs@1.0.0 No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"ia32"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! keytar@4.4.1 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the keytar@4.4.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.


npm ERR! A complete log of this run can be found in:
npm ERR!     D:\local\AppData\npm-cache\_logs\2019-03-07T23_51_14_831Z-debug.log
```

### Debug your Azure website remotely.
> it is recommended that you share your Web App name, directly or [indirectly](https://github.com/projectkudu/kudu/wiki/Reporting-your-site-name-without-posting-it-publicly)
> we can take a look at what's going on.

### Mention any other details that might be useful.

I'm pretty stumped on this one, the behavior only started recently and I've been using the same packages and their versions since the major Azure V2 update.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by suwatch** [comment]
We don't have a complete support for native node module especially building it.  @ahmelsayed  what is the workaround?  Can user deploy a pre-built node native moduke?

**Comment by ahmelsayed** [comment]
yes they can deploy pre-build native modules as long as they were built on a Windows machine and are running the same node version locally and on Azure

**Comment by gpazo** [comment]
@ahmelsayed I was hoping to continue using the in-portal editing for convenience, is the typical workflow moving forward the aws approach of develop locally zip it up and deploy?

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
