### ISSUE TITLE
413 request entity too long zip

### ISSUE THREAD

**Issue by irbrownie** [projectkudu/kudu#2937]
> For deployment issues, please provide us with the following information:
> ---------------------------------------------------------------

### Repro steps.

I am attempting to api/zip a zip that's 838MB and it fails with 413 Request Entity Too Large

### Project structures.
curl script or powershell. tried both.

### The log/error given by the failure.
> Normally this include a stack trace, error code and some more information.

### Debug your Azure website remotely.
> it is recommanded that you share your Web App name, directly or [indirectly](https://github.com/projectkudu/kudu/wiki/Reporting-your-site-name-without-posting-it-publicly)
> we can take a look at what's going on.

### Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by tonykaralis** [comment]
@irbrownie did you manage to come up with a solution for this issue?

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
