### ISSUE TITLE
[Linux] Kudu Zip Deploy fails intermittently for Python Runtime stack

### ISSUE THREAD

**Issue by vincent1173** [projectkudu/kudu#2938]
### Repro steps.

Created a Linux web app with `Python 3.7` as runtime stack.

Kudu Zip Deploy fails alternatievely.
![image](https://user-images.githubusercontent.com/20121508/54023247-7d18a380-41ba-11e9-8d31-ff66fc81f6c0.png)

### Project structures.
Created a basic Flak Project [Flask.zip](https://github.com/projectkudu/kudu/files/2945365/Flask.zip) following the steps [here](https://code.visualstudio.com/docs/python/tutorial-deploy-app-service-on-linux).
### The log/error given by the failure.
> Normally this include a stack trace, error code and some more information.
![image](https://user-images.githubusercontent.com/20121508/54023317-a9ccbb00-41ba-11e9-862e-41e4a8877411.png)

```
Running pip install ...
Exception:
Traceback (most recent call last):
  File "/opt/python/3.7.1/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 143, in main
    status = self.run(options, args)
  File "/opt/python/3.7.1/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 414, in run
    options.target_dir, target_temp_dir, options.upgrade
  File "/opt/python/3.7.1/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 465, in _handle_target_dir
    shutil.rmtree(target_item_dir)
  File "/opt/python/3.7.1/lib/python3.7/shutil.py", line 489, in rmtree
    onerror(os.rmdir, path, sys.exc_info())
  File "/opt/python/3.7.1/lib/python3.7/shutil.py", line 487, in rmtree
    os.rmdir(path)
OSError: [Errno 39] Directory not empty: '/home/site/wwwroot/__oryx_packages__/markupsafe'
```

Azure DevOps kust invokes `Kudu Zip Deploy` and that fails in alternate fashion.

**Comment by satheeshpayoda** [comment]
#2946
I think both issue are same. Because i'm also getting the same error when deleting symlink files,whether its from node modules or pip modules.

**Comment by shadyshrif** [comment]
I have the same issue

`Python Version: /opt/python/3.6.8/bin/python3
rm: cannot remove '__oryx_packages__/google/protobuf/internal': Directory not empty
rm: cannot remove '__oryx_packages__/google/protobuf/pyext': Directory not empty
rm: cannot remove '__oryx_packages__/h5py/.libs': Directory not empty
rm: cannot remove '__oryx_packages__/markupsafe': Directory not empty
rm: cannot remove '__oryx_packages__/numpy/.libs': Directory not empty
rm: cannot remove '__oryx_packages__/numpy/core': Directory not empty
rm: cannot remove '__oryx_packages__/numpy/fft': Directory not empty
rm: cannot remove '__oryx_packages__/numpy/linalg': Directory not empty
rm: cannot remove '__oryx_packages__/numpy/random': Directory not empty
rm: cannot remove '__oryx_packages__/PIL/.libs': Directory not empty
rm: cannot remove '__oryx_packages__/scipy/.libs': Directory not empty
rm: cannot remove '__oryx_packages__/scipy/interpolate': Directory not empty
rm: cannot remove '__oryx_packages__/scipy/linalg': Directory not empty
rm: cannot remove '__oryx_packages__/scipy/ndimage': Directory not empty
rm: cannot remove '__oryx_packages__/scipy/sparse/csgraph': Directory not empty
rm: cannot remove '__oryx_packages__/scipy/spatial': Directory not empty
rm: cannot remove '__oryx_packages__/scipy/special': Directory not empty
rm: cannot remove '__oryx_packages__/scipy/_lib': Directory not empty
rm: cannot remove '__oryx_packages__/tensorflow/python/framework': Directory not empty


rm: cannot remove '__oryx_packages__/google/protobuf/internal': Directory not empty\nrm: cannot remove '__oryx_packages__/google/protobuf/pyext': Directory not empty\nrm: cannot remove '__oryx_packages__/h5py/.libs': Directory not empty\nrm: cannot remove '__oryx_packages__/markupsafe': Directory not empty\nrm: cannot remove '__oryx_packages__/numpy/.libs': Directory not empty\nrm: cannot remove '__oryx_packages__/numpy/core': Directory not empty\nrm: cannot remove '__oryx_packages__/numpy/fft': Directory not empty\nrm: cannot remove '__oryx_packages__/numpy/linalg': Directory not empty\nrm: cannot remove '__oryx_packages__/numpy/random': Directory not empty\nrm: cannot remove '__oryx_packages__/PIL/.libs': Directory not empty\nrm: cannot remove '__oryx_packages__/scipy/.libs': Directory not empty\nrm: cannot remove '__oryx_packages__/scipy/interpolate': Directory not empty\nrm: cannot remove '__oryx_packages__/scipy/linalg': Directory not empty\nrm: cannot remove '__oryx_packages__/scipy/ndimage': Directory not empty\nrm: cannot remove '__oryx_packages__/scipy/sparse/csgraph': Directory not empty\nrm: cannot remove '__oryx_packages__/scipy/spatial': Directory not empty\nrm: cannot remove '__oryx_packages__/scipy/special': Directory not empty\nrm: cannot remove '__oryx_packages__/scipy/_lib': Directory not empty\nrm: cannot remove '__oryx_packages__/tensorflow/python/framework': Directory not empty\n/opt/Kudu/Scripts/starter.sh oryx build /home/site/wwwroot -o /home/site/wwwroot -l python --language-version 3.6 -p virtualenv_name=antenv3.6`

**Comment by satheeshpayoda** [comment]
@shadyshrif 
You can try this little hack. 
https://github.com/projectkudu/kudu/issues/2946#issuecomment-474816627

**Comment by shadyshrif** [comment]
What I usually do is "Redeploy" I think this button clears the deployed version first, which leads to a successful deployment.

![image](https://user-images.githubusercontent.com/10328735/55712385-ae75d080-59ff-11e9-8021-54e60216977a.png)

**Comment by will-hoocht** [comment]
I have had a very similar intermittent issue.  If I create a basic flask project, on a linux webapp with python 3.7 and put "pyodbc"in the requirements.txt, then the deployment will fail ~50% of the time when trying to pip install pyodbc with an error like this:
`OSError: [Errno 18] Invalid cross-device link: '/tmp/pip-target-pzrv3ygz/lib/python/pyodbc.cpython-37m-x86_64-linux-gnu.so' -> '/home/site/wwwroot/__oryx_packages__/pyodbc.cpython-37m-x86_64-linux-gnu.so'`

Since I posted the issue [here](https://developercommunity.visualstudio.com/content/problem/503139/devops-pipeline-azure-linux-python-webapp-deployme.html?childToView=526821#comment-526821) the issue has stopped occuring however.

**Comment by issacnitin** [comment]
We're facing a similar Issue for Function App Linux Python, when App service plans are of lower tiers (Below Premium P1). File size is around 100mb with all python packages

**Comment by martinvt** [comment]
Same issue...130mb Function App (Python) and it fails to deploy from Azure DevOps when using app service plan - Tried Premium as well and still doesn't work. Only way to deploy is through VScode

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
