### ISSUE TITLE
XDT transformations on web.config

### ISSUE THREAD

**Issue by ThomasArdal** [projectkudu/kudu#2942]
I want to write a site extension that updates the deployed web applications `web.config` file. I can do transformations on `applicationHost.config` to add elements like `system.webServer` and `configSections`. But I also need to add app settings and custom elements directly to the users `web.config` file, since this doesn't seem to be supported with `applicationHost.config`.

My question is: is it possible to add elements to users `web.config` file using XDT transformations from a site extension? If not, is it possible to add these values using the `applicationHost.config` file or similar then?

**Comment by suwatch** [comment]
It is intentionally designed not to be able to modify any user's contents (eg. web.config).   Best is to try and play around with applicationHost.config transform and what might be the issue you ran into.   As far as I know, web.config is a subset of applicationHost.config - meaning you should be able to achieve anything your want to do in web.config via applicationHost.config.

**Comment by ThomasArdal** [comment]
Thanks, that makes sense. I'm not sure that I can do everything with `applicationHost.config`. Setting app settings as an example doesn't seem to be supported. But I'll see what I can do and create my solution based on that. Thanks!
