### ISSUE TITLE
Zip Deploy should support GZip and TGZ formats

### ISSUE THREAD

**Issue by nzthiago** [projectkudu/kudu#2944]
Linux systems come with GZip and TGZ baked in and are already approved in most if not all corporate environments. Whenever we ask them to install additional components, even if it's in their DevOps environment in this case, they question why that's the case, and why the native archiving features are not leveraged by Azure App Service. It is not the issue of applying apt-get install zip, but rather it is the principle of leveraging the native component of the environment instead of requiring installing an additional component for something as basic as file compression.

Customers using Azure Functions or Web Apps in their platform are using the [zip deploy feature](https://docs.microsoft.com/en-us/azure/app-service/deploy-zip) to deploy Function Apps and Web Apps.

**Current behavior**:
* Create a GZIP or a TGZ file containing the Web or Function App's tree structure with its functions.
* Publish to a Web or Function App instance using  Zip Deploy
* The publishing operation will fail since only ZIP and WAR files are supported.

**Desired Experience**: 
* Create a GZIP or a TGZ file containing the Web or Function App's tree structure with its functions.
* Publish to a Web or Function App instance using Zip Deploy
* Azure App Service ZIP deploy supports GZIP and TGZ files and correctly starts hosting the functions.

**Comment by vasireddybharath** [comment]
Do we still have this issue or tgz files are now supported?

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
