### ISSUE TITLE
Error: Failed to deploy App Service package using kudu service : Ip Forbidden (CODE: 403)

### ISSUE THREAD

**Issue by renanlq** [projectkudu/kudu#2945]
### Repro steps.
We are having trouble with a deploy step of a Vue.js application using Azure DevOps and Azure. 
#### Steps:
1. Build app with yml file: [azure-pipelines.txt](https://github.com/projectkudu/kudu/files/2971594/azure-pipelines.txt); and
2. Release app with **Azure App Service Deploy** v4.3.20 task.

### Project structures.
Our repository is in Azure DevOps in a private project. But our application is a simple Vue.js application.

### The log/error given by the failure.
I'm not able to deploy an app in a Linux App Service (PremiumV2: 1 Small), due to a 403 error on Kudu service. I've tried to add a slot so that to deploy in this new resource, but I've got the same error message (below), with and without slot deployment. Our last success deploy was on March 11.
![image](https://user-images.githubusercontent.com/15347353/54375112-3239d880-465f-11e9-9561-c6aea70c37ad.png)

I've checked our service connection, and it is working fine in UAT environment, same subscription but different resource group. See below:
![image](https://user-images.githubusercontent.com/15347353/54375004-fc94ef80-465e-11e9-875a-27cd2c112e3d.png)

### Debug your Azure website remotely.
You are able to see release debug information inside this log: [task.log](https://github.com/projectkudu/kudu/files/2971558/task.log), subscription and app ids are inside it.

#### SCP portal
Additionally, sooner I was facing an issue when accessing the SCM portal (Error 403 - this web app is stopped), but after creating a slot, Kudu portal was accessible again.
![image](https://user-images.githubusercontent.com/15347353/54377680-68c62200-4664-11e9-9c57-bf916f16b127.png)

#### Error logs
![image](https://user-images.githubusercontent.com/15347353/54380871-37048980-466b-11e9-9d34-0c436452dc37.png)
* error.log is **empty**; and
* .error.log.swp and .error.log.swp.sap are **hidden**.

**Comment by suwatch** [comment]
From the task.log (above), you seems to be hitting **"statusCode":403,"statusMessage":"Ip Forbidden"** Ipsec block.   Do you have IP rules set for SCM sites in either slots.

**Comment by renanlq** [comment]
@suwatch, do you think that we need to open all in SCM restrictions? Our network security team added Azure DevOps IP address based on this documentation: [Troubleshoot network connections and whitelist addresses](https://docs.microsoft.com/en-us/azure/devops/organizations/security/faq-network-connections?view=azure-devops).
![Access Restrictions blade](https://user-images.githubusercontent.com/15347353/54707248-6c075500-4b1f-11e9-8b4b-4df6c6391e6f.png)

**Comment by suwatch** [comment]
If your goal is to restrict to a certain client source, you don't want to open to all.   The common mistake is user configure the rule using the outbound ip showed from those "what is my ip address" sites.   Bear in mind, certain network configuration may have multiple outbound and you need to add them all.

A quick way to debug is to allow all.  Then try to browse to https://yoursite.scm.azurewebsites.net/Env.cshtml from the client.   Look at HTTP_CLIENT_IP and that would represent the address you need to whitelist.   Try multiple times - if your  network config has multiple outbound ip addresses.

**Comment by renanlq** [comment]
Hi @suwatch, I went to Env.cshtml page to see HTTP_CLIENT_IP parameters, and one of the hidden IPs are this one (here we have 2 outgoing IPs for Internet). 

But most important is that we are using a Microsoft Hosted Agent in Azure DevOps to send this package to our Azure app service, consequently we thought that adding 13.107.6.183 and 13.107.9.183 could work, but did not.
```
To ensure your organization works with any existing firewall or IP restrictions, 
ensure that dev.azure.com is open and the 13.107.6.183 and 13.107.9.183 IP addresses are allowed.
```
Text from: [A more general list of URLs for signing in to Azure DevOps and Azure
](https://docs.microsoft.com/en-us/azure/devops/organizations/security/faq-network-connections?view=azure-devops#a-more-general-list-of-urls-for-signing-in-to-azure-devops-and-azure)

So, in a test, we remove all restrictions to test again and worked fine. Is there any way to maintain our restrictions add some Azure DevOps range to make it work?

**Comment by suwatch** [comment]
The ip addresses described are the incoming IP of Azure DevOps.   It simply indicates your organization firewall rule should allow such access to those IPs.   When Azure DevOps deploys to AppService, it uses its outbound IPs (which are different).   There is no definite range given from the team - hence, one won't be able to setup the rule.   We are working with Azure DevOps team to address that.  Will keep update the outcome.

**Comment by renanlq** [comment]
@suwatch, meanwhile this update does not come, think that this issue could be closed. And I'll do it.
Thanks for the support, and have a nice weekend.

**Comment by kan-nan-k** [comment]
> The ip addresses described are the incoming IP of Azure DevOps. It simply indicates your organization firewall rule should allow such access to those IPs. When Azure DevOps deploys to AppService, it uses its outbound IPs (which are different). There is no definite range given from the team - hence, one won't be able to setup the rule. We are working with Azure DevOps team to address that. Will keep update the outcome.


@suwatch - do we have solution for this from Azure devops team  for this use case to whitelist devops outbound ips ?

**Comment by troll-os** [comment]
As always, the same old "we're working on it and keep you updated" 

What's the status of this issue today ?
