### ISSUE TITLE
Error: Failed to deploy web package to App Service. Internal Server Error (CODE: 500)

### ISSUE THREAD

**Issue by renanlq** [projectkudu/kudu#2947]
### Repro steps.
We are having trouble with a deploy step of an Azure Function App using Azure DevOps and Azure. 
#### Steps:
1. Build an app with yml file: [azure-pipelines.txt](https://github.com/projectkudu/kudu/files/2971693/azure-pipelines.txt)
2. Release app with **Azure App Service Deploy** v4.3.20 task.

### Project structures.
Our repository is in Azure DevOps in a private project. But our application is an HTTP trigger Function App, in .NET Core v2.

### The log/error given by the failure.
I'm not able to deploy an app in a Function App with consumption plan, due to a 500 error on Kudu service.

### Debug your Azure website remotely.
You are able to see release debug information inside this log: [task.log](https://github.com/projectkudu/kudu/files/2971707/task.log). And just the exception stack trace: [exception.log](https://github.com/projectkudu/kudu/files/2971709/exception.log).

### Mention any other details that might be useful.
We face this issue last week and are facing it again. A workaround was creating a new app and updating it's deploy task to this new app.

**Comment by suwatch** [comment]
Looks like the site (fa...ml) is setup with continuous integration with VSTS with Kudu as a build server which was conflicting with VSTS build and zip-deploy.   Try below for mitigation.

- Disconnect continuous deployment using Kudu and build server.
- Use Kudu Console and remove the branch setting from D:\home\site\deployments\settings.xml.

**Comment by renanlq** [comment]
Hi @suwatch, thanks for the response. 

I have noticed that our source was Kudu, then I've disconnected it on deployment center, then readd our deployment task on release pipeline, to run again to enforce TFSGit. Finally, the source changed to Azure Repos again (deployment center screen), and our relese is running again.

**Comment by renanlq** [comment]
Hi @suwatch, thanks for the response. 

I have noticed that our source was Kudu, then I've disconnected it on deployment center, then readd our deployment task on release pipeline, to run again to enforce TFSGit. Finally, the source changed to Azure Repos again (deployment center screen), and our relese is running again.

**Comment by cyptus** [comment]
i changed deployment type from "zip deploy" to "web deploy". this fixed this issue for me. seems that the webapp could not download the zip file via kudu (FAILED TO DOWNLOAD ZIP FILE.txt has been created)

**Comment by suwatch** [comment]
Please open a new gissue.
