### ISSUE TITLE
Update UI on Kudu portal to reflect the repository type. 

### ISSUE THREAD

**Issue by pranavkm** [projectkudu/kudu#295]
We assume it's a Git Repository in the portal. Need to make it so that it hides the push url when we have a hg repository

**Comment by jvano** [comment]
Hi

Kudu will continue to run in Azure App Service. However, this repo will no longer be maintained.
If the problem persists and is related to running on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
