### ISSUE TITLE
RunFromPackage and ZipDeploy: Race condition between site package update and post deployment

### ISSUE THREAD

**Issue by suwatch** [projectkudu/kudu#2950]
This could lead to callers never receive the response.

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
