### ISSUE TITLE
Server Error in '/azurejobs' Application

### ISSUE THREAD

**Issue by ashwineev** [projectkudu/kudu#2951]
I am getting below error when I click on logs for a web job

![web job error](https://user-images.githubusercontent.com/45813590/54660582-fdb19b00-4afc-11e9-9b75-1c7af59578c4.JPG)

Please let me know what is the cause of this issue.
Earlier I was getting 
Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Azure.WebJobs.Host, Version=1.1.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.

Hence I update NewtonSoft.json to 12.0 version and in config file

> 
>  <assemblyIdentity name="Newtonsoft.Json" publicKeyToken="30ad4fe6b2a6aeed" culture="neutral" />
>         <bindingRedirect oldVersion="0.0.0.0-12.0.0.0" newVersion="12.0.0.0" />

I deployed this change and after this started getting the above error page.
Please help me with this issue

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
