### ISSUE TITLE
Node version is not updated from iisnode.yml and iisnode.yml is never updated on windows

### ISSUE THREAD

**Issue by Nickman87** [projectkudu/kudu#2953]
After noticing that successive deploys on a windows instance failed, because an anciend node version was used, I started to investigate the `selectNodeVersion` script in kudu.

This lead me to the following part:
https://github.com/projectkudu/kudu/blob/a13592e6654585d5c2ee5c6a05fa39fa812ebb84/Kudu.Core/Scripts/selectNodeVersion.js#L336

And I discovered the following issues:

1. The `nodeVersion` variable is never updated when an iisnode.yml file is found, causing the whole script to fallback to the environment defined version (which is undefined for us so fallback to node v 0.10.40 is seen)
2. The iisnode.yml file is generated based on our package.json file, but is never again updated in the future should we change versions

The only solution now for us is to remove the iisnode.yml file every deploy to make sure everything is up to date...

**Comment by Nickman87** [comment]
Created a PR to tackle this issue. If more work needs to be done on this, please let me know!

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
