### ISSUE TITLE
Question: Is there a way to deploy ApplicationHost.xdt through Azure DevOps

### ISSUE THREAD

**Issue by RonnyA** [projectkudu/kudu#2956]
In some cases (like changing PATH) for your Web App you need to use Azure Site Extensions.
[https://github.com/projectkudu/kudu/wiki/Azure-Site-Extensions]

The ApplicationHost.xdt  file that configures this must be stored at D:\home\site

I can create/update this file thrugh the Kudo portal, but I really want to do this from my Azure Devops Release Pipeline. Is that possible ?

**Comment by suwatch** [comment]
if you are using WEBSITE_RUN_FROM_PACKAGE, you can't do that since it is always mounted `d:\home\site\wwwroot`.   

However, if you are not using that, you have 2 choices.    See [Customize Deployment](https://github.com/projectkudu/kudu/wiki/Customizing-deployments) or [SCM_TARGET_PATH](https://github.com/projectkudu/kudu/wiki/Deploying-inplace-and-without-repository).

**Comment by RonnyA** [comment]
I am not sure if those approaches are only available if your app is pushed through the local Git repository on App Services. I might have misunderstood the docs, but that's the way I interpret it.

In a typical DevOps workflow the application binaries are compiled in the Build-Pipeline, and in the Deploy-Pipeline the binaries are deployed to App Services using using the "Azure App Service Deploy task" [https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-rm-web-app-deployment]

In this scenario what would be the recommend approach ?
Are there some REST API's we can call to upload the xdt file ?

**Comment by suwatch** [comment]
> In this scenario what would be the recommend approach ?

Right, this may not work with Azure DevOps.

> Are there some REST API's we can call to upload the xdt file ?

You can use [FTP](https://github.com/projectkudu/kudu/wiki/Accessing-files-via-ftp) or [VFS REST API](https://github.com/projectkudu/kudu/wiki/REST-API#vfs).

**Comment by RonnyA** [comment]
Thanks. Feel free to close, or make an improvement to make it more DevOps friendly :)

**Comment by Bouke** [comment]
This seems to work: https://stackoverflow.com/a/43317778/58107.
