### ISSUE TITLE
zip deploy: Allow managed identity as Deployment user account.

### ISSUE THREAD

**Issue by asubmani** [projectkudu/kudu#2957]
--------------------------------------------------
Access denied error while using bearer token method to deploy with Managed Identities.
### Repro steps.
> Create a Linux VM/ACI container with "Managed Identity" (System) enabled
> Grant this identity "website contributor" or "owner" rights to the webApp.
> ssh in to this machine and get MI token as described [here](https://docs.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/how-to-use-vm-token#get-a-token-using-curl)
> use this token and zip deploy 
> `curl -X POST -H $access_token --data-binary @test.zip https://jbdemoapp.scm.azurewebsites.net/api/zipdeploy`

### Error.
```
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>
<title>401 - Unauthorized: Access is denied due to invalid credentials.</title>
<style type="text/css">
<!--
body{margin:0;font-size:.7em;font-family:Verdana, Arial, Helvetica, sans-serif;background:#EEEEEE;}
fieldset{padding:0 15px 10px 15px;}
h1{font-size:2.4em;margin:0;color:#FFF;}
h2{font-size:1.7em;margin:0;color:#CC0000;}
h3{font-size:1.2em;margin:10px 0 0 0;color:#000000;}
#header{width:96%;margin:0 0 0 0;padding:6px 2% 6px 2%;font-family:"trebuchet MS", Verdana, sans-serif;color:#FFF;
background-color:#555555;}
#content{margin:0 0 0 2%;position:relative;}
.content-container{background:#FFF;width:96%;margin-top:8px;padding:10px;position:relative;}
-->
</style>
</head>
<body>
<div id="header"><h1>Server Error</h1></div>
<div id="content">
 <div class="content-container"><fieldset>
  <h2>401 - Unauthorized: Access is denied due to invalid credentials.</h2>
  <h3>You do not have permission to view this directory or page using the credentials that you supplied.</h3>
 </fieldset></div>
</div>
</body>
</html>
```
### I already looked at

> ---------------------------------------------------------------
 > Deployment credentials command `az webapp deployment user set <username>` does not support managed identities.
> Please allow a deployment user to be of type "Managed Identity"

**Comment by suwatch** [comment]
Did you grant the MSI with the proper access to the site (eg. as Contributor to the site for starter)?

**Comment by asubmani** [comment]
> Did you grant the MSI with the proper access to the site (eg. as Contributor to the site for starter)?

Yes. I did. In fact I am able to get this working with `
az webapp deployment source config-zip -g my-APP-SERVICE -n myDemoApp --src /home/cloudiq/test.zip`

I traced the python file that az cli uses to push the zip file.
```python
def enable_zip_deploy(cmd, resource_group_name, name, src, timeout=None, slot=None):
    logger.warning("Getting scm site credentials for zip deployment")
    user_name, password = _get_site_credential(cmd.cli_ctx, resource_group_name, name, slot)
    scm_url = _get_scm_url(cmd, resource_group_name, name, slot)
    zip_url = scm_url + '/api/zipdeploy?isAsync=true'
    deployment_status_url = scm_url + '/api/deployments/latest'
```
You can find the code [here](https://github.com/Azure/azure-cli/blob/83b286cd563c2e2c9c1a8d6ceb7bcec0d12bcd6c/src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/custom.py)

**Comment by suwatch** [comment]
> Yes. I did. In fact I am able to get this working with az webapp deployment source config-zip -g my-APP-SERVICE -n myDemoApp --src /home/cloudiq/test.zip

You got the above working with MSI token?

> curl -X POST -H $access_token --data-binary @test.zip 

Try `-H 'Bearer $access_token'` and see if that works.

**Comment by asubmani** [comment]
> Try `-H 'Bearer $access_token'` and see if that works.

That didn't work; however I tweaked your idea a bit and found:
`curl -X POST -H  "Authorization: Bearer $access_token" --data-binary @test.zip https://jbdemoapp.scm.azurewebsites.net/api/zipdeploy`

Now I don't get access denied but a `Error 403 - This web app is stopped` error. 
I can confirm that the az webapp .... based zip upload works; so the app is running.

Not sure what url the az cli is uploading to.

**Comment by suwatch** [comment]
when requesting a MSI token, you must define `https://management.core.windows.net/` as resource not `https://management.azure.com/`.

**Comment by arun542** [comment]
Hey i am facing the exact same issue. Tried https://management.core.windows.net/ still didnt work.
I am using put request with url to zip file.

**Comment by suwatch** [comment]
What was the UTC time of you call.   We saw no call to `https://jbdemoapp.scm.azurewebsites.net/api/zipdeploy` in the past 6 hrs.

**Comment by arun542** [comment]
My url is different https://avidflowlogsec5821cba07ec3eeccu1.scm.azurewebsites.net/api/zipdeploy

**Comment by suwatch** [comment]
@arun542   you request was missing the authorization header.   Did you pass `-H "Authorization: Bearer $access_token"` to your curl call?

**Comment by asubmani** [comment]
> when requesting a MSI token, you must define `https://management.core.windows.net/` as resource not `https://management.azure.com/`.
That was it!

I got the incorrect url from the official docs on using MSI.. I have opened a github request on the docs page on generating Managed Identity tokens [here](https://github.com/MicrosoftDocs/azure-docs/issues/28414).

**Comment by asubmani** [comment]
@arun542 > My url is different https://avidflowlogsec5821cba07ec3eeccu1.scm.azurewebsites.net/api/zipdeploy

The URL is unique to your webApp. It will be: `https://<yourappname>.scm.azurewebsites.net/api/zipdeploy`

Follow the below steps:

1.  `response=$(curl 'http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&resource=https%3A%2F%2Fmanagement.core.windows.net%2F'   -H Metadata:true -s)`  

2. `access_token=$(echo   $response \| python -c 'import sys, json; print   (json.load(sys.stdin)["access_token"])')`

3. `curl -X POST -H "Authorization: Bearer $access_token" --data-binary @test.zip https://avidflowlogsec5821cba07ec3eeccu1.scm.azurewebsites.net/api/zipdeploy`
--

**Comment by arun542** [comment]
Hey thanks for the reply, i was passing the header but my token was in correct, i was generating it from MSI_ENDPOINT, now it works. But it still fails if i try to do a put request and url of zipfile with error "Number of entries expected in End Of Central Directory does not correspond to number of entries in Central Directory."

**Comment by asubmani** [comment]
@arun542 . This can be closed now. In case you can point to docs that explain the differences between:

1. `management.core.windows.net`
2. `management.azure.com`

That would be great, it seems this guidance varies from service to service (that is what it looks like to me)  and it would be great to understand when to use what.

Thank you

**Comment by suwatch** [comment]
As far as I know, `management.azure.co` is just a service hostname and never a valid ARM resource when it comes to JWT token.   I am closing this now.  Reactivate if still an issue.
