### ISSUE TITLE
Drag-and-Drop Update functionality often doesn't work in Production environment with heavy load

### ISSUE THREAD

**Issue by Christo4bx** [projectkudu/kudu#2958]
### Similar Issue
The issue we are experiencing with KUDU is essentially the same as in Issue #734 submitted by @davidebbo. Ultimately, we have narrowed down the issue in that it only occurs when an app service is under heavy load.

### Summary
The ability to *update* files via drag-and-drop in KUDU does not always work in environments with heavy load. When the functionality does not work, there is no error presented to the user, the file is just not updated. We've observed this with the following types of files:

1) svc files
2) dll files
3) web.config files

We've seen these issues occur on app services running a variety of application types, including WCF services, traditional web services, and MVC web applications. Currently, we're only using app services in App Service Environments (ASE), so I can't verify this problem on an app service with production load that's not in an ASE.

### Repro steps
1. Find a system experiencing heavy load.
2. Try to update an svc, dll, or web.config file that is constantly in use via drag-and-dropping an updated file.
3. Sit back and watch nothing happen (the majority of the time).

Reproducing this error is a bit complicated because it is dependent on the load of the system. When we have attempted to update files in our non-production environment using the drag-and-drop functionality in KUDU, everything works fine. When we try it in a production environment with little-to-no load (i.e., a newly set up app service without any load or after-hours when the application is in use much), this KUDU functionality works perfectly every time. However, when we have a hot fix that must be deployed on an active system experiencing a production load, this functionality works about a third of the time. Frequently, we've been forced to delete the file we're trying to update and then drag-and-drop the new file. 

### Known Workarounds
We understand that the use of the FTP or Web Deploy methodologies will get around this issue. Additionally, deploying to a slot is another alternative. However, I'm not reporting this issue because there are no available workarounds, but because KUDU simply does not work as expected when under heavy load and there's no message to the user to show that it has not worked as expected. Below are the workarounds within KUDU we've identified to get the drag-and-drop functionality to work.

1. Zip up the files you want to update and drag the zipped files to the "Drag here to upload and unzip" section. This works about two-thirds of the time even under heavy load.

2. Delete the file that needs to be updated, and drag-and-drop the new file. This has always worked for us but is not ideal by any stretch of the imagination. This workaround increases downtime and inevitably cause 500 errors to be presented to users.

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
