### ISSUE TITLE
Disconnecting External Git resets the SSH Keys

### ISSUE THREAD

**Issue by jcbrooks92** [projectkudu/kudu#2961]
Update the [wiki](https://github.com/projectkudu/kudu/wiki/Deploying-from-GitHub) to mention that disconnecting only the external git will reset your SSH key.

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
