### ISSUE TITLE
Support linux sh post deployment scripts

### ISSUE THREAD

**Issue by stevep0000** [projectkudu/kudu#2963]
Kudu supports cmd bat and ps1 scripts for post deployment.

See Kudu.Core/Helpers/PostDeploymentHelper.cs

```
            // Find all post action scripts and order file alphabetically for each folder
            return Directory.GetFiles(postDeploymentPath, "*", SearchOption.TopDirectoryOnly)
                                    .Where(f => f.EndsWith(".cmd", StringComparison.OrdinalIgnoreCase)
                                        || f.EndsWith(".bat", StringComparison.OrdinalIgnoreCase)
                                        || f.EndsWith(".ps1", StringComparison.OrdinalIgnoreCase))
                                    .OrderBy(n => n);
```

Can Linux scripts be supported for Linux containers on Azure ?

For a Python / Django webapp I want to be able to either move an sqlite dabatase to /tmp or change the permissions on a site folder as the database appears locked,

**Comment by stevep0000** [comment]
Here is an example of a script called mvdb.sh that needs to be run post deployment:

```
#/bin/bash

# Copy the database to /tmp due to permissions issues
cp /home/site/wwwroot/db.sqlite3 /tmp
```

**Comment by sanchitmehta** [comment]
This has been handled in https://github.com/Azure-App-Service/KuduLite/pull/30.

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
