### ISSUE TITLE
[Fix] ZipDeploy Breaking Change (400 Bad Request)

### ISSUE THREAD

**Issue by AMoghrabi** [projectkudu/kudu#2966]
Hello,

A couple of years ago we implemented zipdeploy in our deploy pipeline. I believe at the time it was required that we set the headers `content-type` and `accept` to `application/json`. 

As of this week our deploys started failing with a 400 bad request. After playing around with the API using Postman, I discovered that setting those two headers causes this error to occur:

 ```
    "Message": "An error has occurred.",
    "ExceptionMessage": "Unable to translate bytes [98] at index 12 from specified code page to Unicode.",
```

The fix is to send your request with only an Authorization header. Nothing else is required. 

I don't have an issue with the API anymore, I'm just posting this so others are aware.

Thanks!

**Comment by suwatch** [comment]
Correct - it was broken by [this](https://github.com/projectkudu/kudu/commit/2503d9ed9b69594f1043bc688f2e444aee8ed605).   The workaround (which is correct semantically) is to not pass such as content-type if not json content.     Pass something that represents binary content (eg. application/x-binary or application/octet-stream) instead.
