### ISSUE TITLE
The command Kudu.Services.Web\\updateNodeModules.cmd exited with code 1

### ISSUE THREAD

**Issue by abdullah-alimam** [projectkudu/kudu#2968]
Hi I just Download the Master Project

when I select Build -> Rebuild Solution I get this error 
![image](https://user-images.githubusercontent.com/47662548/56882878-a5f83f00-6a6d-11e9-8f22-75e6ef637640.png)

then when I select Build -> Build Solution  I get this error 
![image](https://user-images.githubusercontent.com/47662548/56882899-bd372c80-6a6d-11e9-9940-36b2ed2b78af.png)

My windows is 10
VS 2017

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
