### ISSUE TITLE
KeyError: b'search_resFromStr'  in kudu.schema.Schema.get_loc 

### ISSUE THREAD

**Issue by lujingqiao** [projectkudu/kudu#2970]
who can help me! THX!

i get strange question!
first see images:
![image](https://user-images.githubusercontent.com/33116735/57270397-ad4ac880-70bd-11e9-908e-908c93d30d0d.png)
![image](https://user-images.githubusercontent.com/33116735/57270412-c05d9880-70bd-11e9-86ef-5700ddbd8c95.png)
![image](https://user-images.githubusercontent.com/33116735/57270534-47127580-70be-11e9-9329-f70db3271179.png)

description:

1、‘search_resFromStr’ in data, data is a dict, which is checked.
2、'search_resFromStr' in kudy table, which is checked.
3、throw "KeyError: b'search_resFromStr'" when run code "op = clean_kudu_table.new_insert(data)"

kudu api: kudu_python 1.2
kudu version: kudu 1.5.0-cdh5.13.0

who can help me! 
i have no way,plz help me
thx in advance~!

**Comment by suwatch** [comment]
We might be talking about different kudu product here.
