### ISSUE TITLE
3 of 5 tablet servers cannot start:  Cannot cancel transactions that have already replicated

### ISSUE THREAD

**Issue by cjie** [projectkudu/kudu#2973]
Tablet Server cannot start, here is the log:

F0520 13:08:48.346738 62210 transaction_driver.cc:358] T 037545a12dce43c9bdf210926d6d7c84 P 3fcd4dc534b746969f96b914783fd642 S R-NP Ts 6382701727369547776: Cannot cancel transactions that have already replicated: Invalid argument: Client provided column ffirst_buy_brand[string NULLABLE] not present in tablet transaction:R-NP WriteTransaction [type=REPLICA, start_time=2019-05-20 13:08:48, state=WriteTransactionState 0x572d340 [op_id=(term: 31 index: 6191175), ts=6382701727369547776, rows=[]]]

What should I do to recover these tablet servers?

**Comment by suwatch** [comment]
wrong kudu.
