### ISSUE TITLE
[zipdeploy | .netcore webapi] ZipDeploy dotnet core project to App Service on Linux from script fails without any error

### ISSUE THREAD

**Issue by rick-hayek** [projectkudu/kudu#2982]
### Repro steps.
from powershell command window:

1. Create a dotnet core web api project:
```bash
dotnet new webapi -n myapi
cd myapi
dotnet publish -c release -o publish
Compress-Archive -Path .\publish\* -DestinationPath .\publish.zip
```
2. Create resources in Azure:
```bash
$subscriptionId=<my subscription id>
$myLocation="West US"
$myResourceGroup="myResourceGroup"
$myAsp="myasp"
$appName="myApp123"

az login
az account set --subscription $subscriptionId
az group create --location $myLocation --name $ResourceGroupName
az appservice plan create --name $myAsp --resource-group $myResourceGroup --location $myLocation --is-linux --sku B1
az webapp create --name $appName --resource-group $myResourceGroup --plan $myAsp --% --runtime "DOTNETCORE|2.2"

```

3. Zip deploy web api to Azure:
```bash
az webapp deployment source config-zip -n $appName -g $myResourceGroup --src ./publish.zip --debug
```

### Actual Results
1. Everything seems fine, but when going to the site <https://&lt;myApp123&gt;.azurewebsites.net/api/values>, it returns 404
2. By checking the scm site <https://&lt;myApp123&gt;.scm.azurewebsites.net/wwwroot>, I can find the publish files are already uploaded:

Name | Size | Last Modified
--  | --  | --
appsettings.Development.json | 146 | 5/14/19 9:50:52 AM +00:00
appsettings.json | 352 | 5/14/19 10:14:54 AM +00:00
web.config | 550 | 5/22/19 2:19:32 AM +00:00
WebApi.deps.json | 234668 | 5/22/19 10:16:22 AM +00:00
WebApi.dll | 17408 | 5/22/19 10:16:22 AM +00:00
WebApi.pdb | 2224 | 5/22/19 10:16:22 AM +00:00
WebApi.runtimeconfig.json | 224 | 5/22/19 10:16:22 AM +00:00

Have no idea why the site is not running

### Something interesting
I could make the exactly same deploy script worked if:
1. deploy the api from VisualStudio 2017 (check the site to make sure it is running correctly now)
2. modify the sample api controller (so you can be sure the next deployment works)
3. deploy from script (again):
``` bash
az webapp deployment source config-zip -n $appName -g $myResourceGroup --src ./publish.zip 
```
Check the new api, I can find the api gets updated, which means the script deployment succeeded

### Environment
az --version
> azure-cli                         2.0.60 *

systeminfo
> OS Name:                   Microsoft Windows 10 Pro
> OS Version:                10.0.17763 N/A Build 17763

dotnet --version
> 2.2.203

### The log/error given by the failure.
part of az webapp deployment log:
> {
  "active": true,
  "author": "N/A",
  "author_email": "N/A",
  "complete": true,
  "deployer": "Push-Deployer",
  "end_time": "2019-05-22T02:19:32.6034993Z",
  "id": "f187553cf89449219b1f78f30411885e",
  "is_readonly": true,
  "is_temp": false,
  "last_success_end_time": "2019-05-22T02:19:32.6034993Z",
  "log_url": "https://&lt;myApp123&gt;.scm.azurewebsites.net/api/deployments/latest/log",
  "message": "Created via a push deployment",
  "progress": "",
  "received_time": "2019-05-22T02:19:26.2940983Z",
  "site_name": "&lt;myApp123&gt;",
  "start_time": "2019-05-22T02:19:26.437735Z",
  "status": 4,
  "status_text": "",
  "url": "https://&lt;myApp123&gt;.scm.azurewebsites.net/api/deployments/latest"
}

let me know if the actual app is needed for investigation

**Comment by suwatch** [comment]
@rramachand21   could you help take a look?   This same step works just fine for Windows.
