### ISSUE TITLE
Kudu API won't redeploy after swapping WebApp slot the first time

### ISSUE THREAD

**Issue by mloeffen** [projectkudu/kudu#2983]
We noticed that after swapping a test slot to production the first time, the kudu API doesn't trigger a new deployment on the test-slot and returns a 404-error instead. I'd like to know if this current implementation of the API is working as intended.

### Repro steps.
1. Create a WebApp on Azure
2. Create a test-slot within the newly created WebApp
3. Setup a deployment for the newly created test-slot
3. After the deployment is ready use Postman to trigger another deployment using PUT to url https://yourwebappname-test.scm.azurewebsites.net/api/deployments
4. Notice that a deployment starts and wait until it completes
5. Swap the test-slot to production
6. After the swap has finished use Postman to trigger another deployment using PUT to url https://yourwebappname-test.scm.azurewebsites.net/api/deployments
7. Notice that Kudu returns a 404-error and does not start a deployment

### Project structures.
Any repro will do, there's no specific input requirement that will affect the outcome. Some background info though: our websites are build using code coming from a repository and data from a storage container. It's a common scenario that after a swap, the code is unchanged but the data is updated. Hence we use the API the force a new deployment.

### The log/error given by the failure.
A 404-error on a PUT to /api/deployments

### Other details
Swapping the slot also swaps the deployment history. When the deployment history in the test-slot is empty (after the first swap), it cannot redeploy the current head despite the documentation saying 

> PUT /api/deployments/{id}
> This API has 2 behaviors based on the payload.
> 
>   - Redeploy a current or previous deployment
>    {id} is optional. If not provided, redeploy the current head

I didn't expect the deployment history to be required since the id is optional.

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
