### ISSUE TITLE
An empty Proxies.json adds another Trigger to the Sync Trigger payload even if there is no Route specified.

### ISSUE THREAD

**Issue by FinVamp1** [projectkudu/kudu#2986]
If you create a v2 Function app via the Azure Functions VS Code Extension this adds an empty proxies.json as discussed at [Initializing Proxies.json](https://github.com/microsoft/vscode-azurefunctions/issues/426) .

Because of [This Code](https://github.com/projectkudu/kudu/blob/b22dbdf3a520c6aec3b323d4b0f2799acd300787/Kudu.Core/Helpers/PostDeploymentHelper.cs#L151-L156) this means the deployment shows that two triggers are synced. 

E.G.

10:23:03 AM NodeJSFunction101: Syncing 2 function triggers with payload size 157 bytes successful.

This could be avoided by parsing the Proxies.json to see if it does have the right data.

**Comment by suwatch** [comment]
@safihamid  what do you think about this?  the mitigation is to get rid off no-op proxies.json.

**Comment by suwatch** [comment]
Given the current state of Kudu, I will close this given a simple mitigation by removing the proxies.json.
