### ISSUE TITLE
Kudu rest api for changing app setting doesn't work

### ISSUE THREAD

**Issue by angelwen08** [projectkudu/kudu#2987]
Hi,
I was using Kudu rest api to change my app setting.
The request I was using is:
url:  https://docs-live-sitesearch-ppe.scm.azurewebsites.net/api/settings/
Method: POST
body: { "DoNotRunCrawler": "true"}
response is 204.

Then I use get API:
url:  https://docs-live-sitesearch-ppe.scm.azurewebsites.net/api/settings/DoNotRunCrawler

or  get API
url:  https://docs-live-sitesearch-ppe.scm.azurewebsites.net/api/settings/

Both results indicates the key of "DoNotRunCrawler" is "true".

But if I go to Azure portal to check this key in app service "docs-live-sitesearch-ppe",  it still shows "false", which is the original value before I changed.

And this value is consumed by my web job.  I tested my web job and it seems the old value(DoNotRunCrawler: false) is consumed.

Could I know why the change doesn't take effect?

**Comment by suwatch** [comment]
They are two different things.  Kudu can run on-premise or on Azure.  To change Azure App Service appSetting, do use portal instead.

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
