### ISSUE TITLE
Kudu.Web and GIT Security / Authentication

### ISSUE THREAD

**Issue by elmiguedev** [projectkudu/kudu#2988]
Hi!

There is anyway to make an authentication request before someone get on kudu admin web?
I just intalled it, but it is visible for everyone on the LAN. 

The same question for Kudu's git repositories: i just added a kudu repo as a remote url, then push and it is all, no passwords needed. 

I was looking at Kudu.Web webconfig, but i didn't saw anything about that

Thanks!

**Comment by suwatch** [comment]
Kudu admin web is just a simple ASP.NET application.  You can modify its [web.config](https://github.com/projectkudu/kudu/blob/master/Kudu.Web/Web.config#L106-L110) to enforce any authentication you desire.

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
