### ISSUE TITLE
Support for TLS Mutual Authentication to Access Kudu

### ISSUE THREAD

**Issue by jcbrooks92** [projectkudu/kudu#2991]
Support for TLS mutual Auth to access Kudu for customers who have security requirements for code deployments to only occur through services supporting this authentication mechanism.

**Comment by suwatch** [comment]
This will be in the context on Azure App Services.   Running Kudu outside Azure App Service, one can configure any authentication kinds themselves.

**Comment by jeffpatton1971** [comment]
Thanks Jeremy, this is good news I think for everyone.

**Comment by jeffpatton1971** [comment]
@suwatch if I understand, this effort will be to allow TLS Mutual Auth for deployments specifically for Web Apps. The reason is, for ASE, you can choose other auth mechanisms. Did I understand that correctly?

**Comment by suwatch** [comment]
ASE is still withing App Service.   So TLS mutual is not supported yet.
