### ISSUE TITLE
SiteExtension gallery support for SemVerv2

### ISSUE THREAD

**Issue by suwatch** [projectkudu/kudu#2993]
When the nuget client doesn’t correctly understand the new package versioning it shows older packages using the older versioning before the new ones. When the gallery only shows one version, it shows an old version.

These docs say you need NuGet 4.3.0+
https://docs.microsoft.com/en-us/nuget/reference/package-versioning#semantic-versioning-200

**Comment by Tratcher** [comment]
Example: https://www.nuget.org/packages/AspNetCoreRuntime.3.0.x64/3.0.0-preview6.19307.2

**Comment by suwatch** [comment]
Add @sanchitmehta.

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
