### ISSUE TITLE
Fail to setup Azure with Bitbucket due to invalid RepoUrl with empty userName.

### ISSUE THREAD

**Issue by suwatch** [projectkudu/kudu#2996]
There is an ongoing issue where Azure continuous deployment from Bitbucket indicates successful, however the first deployment will show as failed due to invalid repository url (missing username).   This only impacts the first deployment and the subsequent push will deploy successfully.

The issue was caused by the breaking changes in the Bitbucket api where certain property was removed (username).   We are working toward fixing this - hopefully by end of tomorrow (6/21) if not earlier.   

Will update any progress.

**Comment by suwatch** [comment]
The Bitbucket team deployment was delayed - we are looking at end of Mon 6/24 as ETA.

**Comment by suwatch** [comment]
This is now fixed.   For existing webapps with the issue (missing username), one will need to disconnect and re-setup the deployment with Bitbucket again.

**Comment by midhunrajeevam** [comment]
Thank you very much.
