### ISSUE TITLE
MFA Azure AD returns 403 after ordering the double factor

### ISSUE THREAD

**Issue by SRegue** [projectkudu/kudu#2997]
We have activated the MFA in AAD, with a policy for all users and for all applications. However after activating the policy, only the KUDU portal has stopped working after login and pass the double authentication. Returning the following message:
![image](https://user-images.githubusercontent.com/25037461/59905601-f2755080-9406-11e9-84f4-93dfcee3cf32.png)

**Comment by suwatch** [comment]
If you can share the [site name](https://github.com/projectkudu/kudu/wiki/Reporting-your-site-name-without-posting-it-publicly) and the UTC of issue - we can investigate why.

Off the top, the MFA is the contract between AAD and User, when it gets to Kudu endpoint, it is just a token.   It should just work, IMO.

**Comment by SRegue** [comment]
Hi, I created a WebApp for the issue.
https://testissuekudu.azurewebsites.net


> Off the top, the MFA is the contract between AAD and User, when it gets to Kudu endpoint, it is just a token. It should just work, IMO.

That's what surprises me, that only fails when the MFA policies are activated, when it should be transparent.

**Comment by suwatch** [comment]
UTC time when you access .. would help us pinpoint.

**Comment by SRegue** [comment]
Hi.

UTC 7:15 08/29/2019

Thanks for answering

**Comment by suwatch** [comment]
From our log, there is no access to https://testissuekudu.scm.azurewebsites.net  between such time.   Could you share HAR or Network Capture?

**Comment by SRegue** [comment]
Try it now:
UTC 8:29 08/29/2019

**Comment by suwatch** [comment]
Does this "https://kabel365-onmicrosoft-com.na001.access-control.cas.ms/aad_login" url looks familiar to you?   We only accept login from microsoft login - not sure why yours was issued from that.   

Do you have issue login on to Azure Portal?  I really like to see HAR if you don't mind sharing.

**Comment by turowicz** [comment]
@suwatch same problem here

site name: v-pro-we-app-walk

**Comment by turowicz** [comment]
When I click "Advanced Tools" in portal I am redirected to https://waws-prod-am2-195.sso.azurewebsites.net/ which says `403 the app is stopped.`

**Comment by turowicz** [comment]
OK turns out I'm using Brave Browser which is too private for Kudu. Opening in Safari worked fine.

**Comment by SRegue** [comment]
> 
> 
> Does this "https://kabel365-onmicrosoft-com.na001.access-control.cas.ms/aad_login" url looks familiar to you? We only accept login from microsoft login - not sure why yours was issued from that.
> 
> Do you have issue login on to Azure Portal? I really like to see HAR if you don't mind sharing.

The url it's ok.
I upload a har, the extension is changed to txt.

[waws-prod-db3-111.sso.azurewebsites.net_Archive [19-09-12 08-37-08].txt](https://github.com/projectkudu/kudu/files/3604038/waws-prod-db3-111.sso.azurewebsites.net_Archive.19-09-12.08-37-08.txt)

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
