### ISSUE TITLE
401 Unauthorized When attempting to connect to Debug LogStream via Curl

### ISSUE THREAD

**Issue by samabraham** [projectkudu/kudu#2999]
I have tried to use App and User Publisher credentials to connect to LogStream via curl (image attached). I keep getting 401 unauthorized. Any ideas please? Thanks!!

I added temp.txt file under log directory as suggested with link to this discussion.

subscription ID: db62....a7caf
![image](https://user-images.githubusercontent.com/12576711/59981306-4b8fe080-95cf-11e9-90f8-cdf53443251a.png)

**Comment by suwatch** [comment]
Please UTC time when the error occurred (to help us pinpoint) and [sitename](https://github.com/projectkudu/kudu/wiki/Reporting-your-site-name-without-posting-it-publicly).

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
