### ISSUE TITLE
Triggered Jobs using Settings.Job and Timers may never restart if a WebJob doesn't complete.

### ISSUE THREAD

**Issue by FinVamp1** [projectkudu/kudu#3003]
From CRI 129506745.

A Triggered Job may run and never complete.
(Scenario:PowerShell Triggered Web Job using settings.job Cron expression)

The WebJob Status file hasn't got an end time.

E.G

{"Trigger":"Schedule - 0 0 0,2,4,6,8,10,12,14,16,18,20,22 * * *","Status":"Running","StartTime":"2019-06-07T14:00:04.181107Z"}

Further executions of this WebJob will not succeed until this status file is deleted.

This can be mitigated in part by ensuring that the WebJob code handles errors and exits gracefully.

Could we detect this scenario and recover?

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
