### ISSUE TITLE
GET /api/zip/{path}/ support ignore paths?

### ISSUE THREAD

**Issue by mistyn8** [projectkudu/kudu#3008]
Would it be possible to add support for ignore paths when creating zip archives?
Maybe backup_filter could be used as per azure backups?

https://github.com/projectkudu/kudu/wiki/REST-API#zip

**Comment by suwatch** [comment]
Zip is implemented as simple as Windows `Sent to -> Compressed Zip Folder` - hence no option.   Of course, everything is possible.  But to make a feature (on investing in implementing), it would need to be somewhat common and applicable to many scenarios.    So it will unlikely be supported in the near future.   Hope you understand.   Do keep this open in case more people upvote it.

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
