### ISSUE TITLE
WEBSITE_RUN_FROM_PACKAGE not creating packagename.txt - deployment failed

### ISSUE THREAD

**Issue by SaebAmini** [projectkudu/kudu#3009]
### Repro steps.

Originally reported [on Azure Pipelines Tasks](https://github.com/microsoft/azure-pipelines-tasks/issues/10961), however, after some more digging it seems to be a Kudu issue.

Deploying a function app from Azure Pipelines succeeds and gets a 200 from Kudu, however when looking at the "Deployment Center" on the portal, it says the deployment failed with a "Failed to deploy to production" message and no additional details:

![image](https://user-images.githubusercontent.com/6758734/61683210-068ad580-ad58-11e9-9ef9-21e8ef62b0b5.png)

 The task says it completes successfully. The package is uploaded successfully to data/SitePackages, however the advertised `packagename.txt` file isn't created. After creating a `packagename.txt` file manually which points to the latest uploaded package, the function is recognized and starts correctly.

### The log/error given by the failure.
Here's the complete debug-level deployment log: 
[DeployLogs.zip](https://github.com/projectkudu/kudu/files/3420248/DeployLogs.zip)

### Mention any other details that might be useful.

- Function app v2 running in an IBL App Service Environment

**Comment by suwatch** [comment]
The deployment call to Kudu completed with 200 - meaning we have started (in async) or completed the deployment (in sync).  Either cases, one would need to poll/check the deployment and its log to see if success / fail.  In your case, the deployment failed - hence the packagename.txt was not updated.

As for failure, looking at the deployment log should yield a clue.  In this case, Kudu failed to inform the internal system of triggers change (by calling its own URL).   Did your ILB ASE block calls from Worker?

**Comment by SaebAmini** [comment]
> The deployment call to Kudu completed with 200 - meaning we have started (in async) **or completed the deployment (in sync)**.

How can the bolded bit (sync completion) be true when the deployment has _failed_? or are you saying 200 could mean it has successfully failed... 😄

> Either cases, one would need to poll/check the deployment and its log to see if success / fail.

I understand if it's all asynchronous all the time, although I don't agree with that design choice. Is this clearly documented somewhere? you don't usually expect a 200 to mean "I've kicked something off that might fail", especially because these APIs are used in continuous deployment tools and that 200 is all they expect to continue as if all is good.

> As for failure, looking at the deployment log should yield a clue.

I've attached the whole deployment log that's visible to me from the CD side of things which consumes the API. As far as that log is concerned, everything has went fine because it gets a 200. It doesn't get any more information from the API.

Within Azure, I don't get anything other than the above "Failed to deploy to production" message. Nothing in app insights either. Is there anywhere else I can look at?

> Kudu failed to inform the internal system of triggers change (by calling its own URL). Did your ILB ASE block calls from Worker?

That sounds like a very good guess to me. There aren't any blocks in place in the VNET. That's a big part of why the client has gone with an ASE. Everything within the VNET has access to everything else. The only way this would happen is if Kudu is trying to call the URL from _outside_ the VNET, in which case it wouldn't be able to as that's an isolated network. That seems to be where the issue lies. Seems to be Kudu should handle that "informing of the internal system" in another, more reliable way.

**Comment by damienwebdev** [comment]
This issue is still occurring, as outlined here. 

https://github.com/microsoft/azure-pipelines-tasks/issues/11444

While I can't say whether or not this is a Kudu or Azure Pipelines issue, someone from one of these teams has to get in contact with the other. Passing info back and forth like this isn't super conducive to solving this problem.

**Comment by suwatch** [comment]
@damienwebdev  please provide UTC time of incident and webapp name, we can take a look.   Multiple sample of issues would help us get to the bottom.

**Comment by WizX20** [comment]
Facing this issue today with deploy-as-package (zip) to Web App's. Multiple times, on different resource groups on different Web Apps. This is hindering us in deploying to production environments.

YAML:

- task: AzureWebApp@1
    displayName: 'Deploy Web App ''${{ parameters.artifactName }}'''
    inputs:
      azureSubscription: $(connectionName)
      appName: ${{ parameters.webAppName }}
      package: '$(Pipeline.Workspace)/${{ parameters.artifactName }}/**/*.zip'
      enableCustomDeployment: true
      deploymentMethod: runFromPackage

**Comment by suwatch** [comment]
what is the webapp name [how to share](https://github.com/projectkudu/kudu/wiki/Reporting-your-site-name-without-posting-it-publicly).

**Comment by WizX20** [comment]
> what is the webapp name [how to share](https://github.com/projectkudu/kudu/wiki/Reporting-your-site-name-without-posting-it-publicly).

63f4b44a-...-0571cf73bb62
mijn..-webapi-d
_(Added d:\home\logFiles\temp.txt with a link to this discussion)_

**Comment by suwatch** [comment]
From our log, we only see deployment making to the given free site **mijng..web-d** at 2020-12-03 13:45Z and it looked normal.   We can see below log (you should be able to see the same in the deployment history log as well).   However, we don't see any deployment attempt making to the site around 2020-12-03T14:26:17.612Z!  Please confirm the sitename.

> 2020-12-03 13:45:01Z Total 928,965 bytes written to C:\home\data\SitePackages\20201203134501.zip 
2020-12-03 13:45:04Z Updating C:\home\data\SitePackages\packagename.txt with deployment 20201203134501.zip

**Comment by WizX20** [comment]
Hi @suwatch I can confirm the site name is correct, the artifacts are not uploaded, though the pipeline tells us the have been uploaded successfully.

It seems to fail on a "fresh" web application, where the RUN_FROM_PACKAGE is set to true. If we remove this from the settings manually, and re-run the pipeline, it works and the package is deployed.

**Comment by WizX20** [comment]
Again just nog we are having issues with the deployments on
- The artifact is created properly, if I download the .zip file is can see our latest changes when inspecting the files
- The deployment is created
![image](https://user-images.githubusercontent.com/1008647/101744346-39f40e80-3acb-11eb-8b75-acc9c6ff0ce5.png)
-The AzureWebApp@1 task completes, and flags success
![image](https://user-images.githubusercontent.com/1008647/101745863-96572e00-3acb-11eb-8f95-93d78c213ab0.png)
- The zip file is not present on the WebApp
![image](https://user-images.githubusercontent.com/1008647/101746245-acfd8500-3acb-11eb-9618-2303f7122d5d.png)

**Comment by ivan-sam** [comment]
We have the same issue.
Function V3 with dotnet runtime hosted on ASE.
Deployment with MSDeploy works fine. But we'd prefer run from package to prevent issues on re-deploy.
Run from package deployment succeeded, but triggers are not synced.
Both workarounds helps bringing function to life after runFromPackage deployment:
1. create manually packagename.txt
2. remove configuration setting WEBSITE_RUN_FROM_PACKAGE

On the AppService in the folder with kude traces `D:\home\LogFiles\kudu\trace` we see that if fails to perform
1. `<step title="Begin HttpPost https://<func-name>.<ase-name>.p.azurewebsites.net/admin/host/synctriggers, `
2. `<step title="Begin HttpPost https://<func-name>.scm.<ase-name>.p.azurewebsites.net/operations/settriggers, `
The error was:
```
<step title="Syncing 1 function triggers with payload size 189 bytes failed with System.Net.Http.HttpRequestException: An error occurred while sending the request. ---&gt; System.Net.WebException: Unable to connect to the remote server ---&gt; System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond Z.Z.Z.Z:443
   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket&amp; socket, IPAddress&amp; address, ConnectSocketState state, IAsyncResult asyncResult, Exception&amp; exception)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, TransportContext&amp; context)
   at System.Net.Http.HttpClientHandler.GetRequestStreamCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Kudu.Core.Helpers.PostDeploymentHelper.&lt;PostAsync&gt;d__43.MoveNext() in C:\Kudu Files\Private\src\master\Kudu.Core\Helpers\PostDeploymentHelper.cs:line 554
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Kudu.Core.Helpers.PostDeploymentHelper.&lt;PerformSettriggers&gt;d__33.MoveNext() in C:\Kudu Files\Private\src\master\Kudu.Core\Helpers\PostDeploymentHelper.cs:line 271" date="2020-12-10T15:36:53.130" />
```

where Z.Z.Z.Z:443 - is ASE public IP.

First, we removed all ipRestrictions and scmIpRestrictions for app service
Then  started adding allowing rules for NSG, attached to subnet of ASE.
When we added rules for both outbound and inbound connection it started to work.
- any to ASE
- ASE to any

The outcomes of the troubleshooting:
1. I think documentation is not clear enough about steps of the deployment process and all requirements.
2. Also there's scarce info about troubleshooting, especially taking into account that the process has many dependencies, so many things can go wrong.

**Comment by WizX20** [comment]
We seem to have fixed the issue by sawpping out the `AzureWebApp@1` task with the `AzureRmWebAppDeployment@4` task for now. Still keeping an eye on it.

Currently using:
```
- task: AzureRmWebAppDeployment@4
    displayName: 'Deploy Web App ''${{ parameters.artifactName }}'''
    inputs:
      azureSubscription: $(connectionName)
      appType: 'webApp'
      WebAppName: ${{ parameters.webAppName }}
      Package: '$(Pipeline.Workspace)/${{ parameters.artifactName }}/**/*.zip'
      DeploymentType: 'runFr
```

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
