### ISSUE TITLE
Unauthorized: Access is denied due to invalid credentials

### ISSUE THREAD

**Issue by lshekarrao** [projectkudu/kudu#3010]
Hi, I am trying to deploy WAR file with below command cURL command and seeing 401 UNauthorized error.
I am passing username:password ( just providing username not the complete email like username@someone.com). for security reasons I masked sensitive information in the below image. Any help would be greatly apprciated.

![image](https://user-images.githubusercontent.com/43973343/62272282-96332280-b3ef-11e9-93c2-4ab9ee9be737.png)

**Comment by suwatch** [comment]
You have to use deployment credential - not your subscription account.  See [this](https://github.com/projectkudu/kudu/wiki/Deployment-credentials).
