### ISSUE TITLE
How to deploy war in app service when apache-tomcat is enabled

### ISSUE THREAD

**Issue by lshekarrao** [projectkudu/kudu#3016]
Hi, we have java based application hosted in app services and we enabled apache-tomcat on the app services.
When I try to deploy war using api/webdeploy?name=myapp , the war is getting deployed at /home/site/wwwroot/webapps/ but we want to deploy our services  at \home\site\wwwroot\bin\apache-tomcat-8.5.24\webapps>
Can you please help me how to achieve this?

Thanks,
Shekar

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
