### ISSUE TITLE
error MSB4086: A numeric comparison was attempted on "$(MSBuildVersion)" that evaluates to "" instead of a number

### ISSUE THREAD

**Issue by leniel** [projectkudu/kudu#3019]
> For deployment issues, please provide us with the following information:
> ---------------------------------------------------------------

### Repro steps.
> your project built successfully on your dev machine but failed on Azure? Yes
> please write down your build tools and their versions (ie `Msbuild 15.1.0.0`)

Visual Studio 2019

### The log/error given by the failure.
> Normally this include a stack trace, error code and some more information.

```
Command: "D:\home\site\deployments\tools\deploy.cmd"
Handling .NET Web Application deployment.
MSBuild auto-detection: using msbuild version '14.0.23107.0 built by: D14REL' from 'D:\Program Files (x86)\MSBuild\14.0\Bin'.
Restoring NuGet package Microsoft.Net.Compilers.3.1.1.
  GET https://api.nuget.org/v3-flatcontainer/microsoft.net.compilers/3.1.1/microsoft.net.compilers.3.1.1.nupkg
  OK https://api.nuget.org/v3-flatcontainer/microsoft.net.compilers/3.1.1/microsoft.net.compilers.3.1.1.nupkg 937ms
Installing Microsoft.Net.Compilers 3.1.1.
Adding package 'Microsoft.Net.Compilers.3.1.1' to folder 'D:\home\site\repository\packages'
Added package 'Microsoft.Net.Compilers.3.1.1' to folder 'D:\home\site\repository\packages'

NuGet Config files used:
    D:\local\UserProfile\AppData\Roaming\NuGet\NuGet.Config

Feeds used:
    D:\home\.nuget\
    https://api.nuget.org/v3/index.json

Installed:
    1 package(s) to packages.config projects
D:\home\site\repository\packages\Microsoft.Net.Compilers.3.1.1\tools\Microsoft.Managed.Core.targets(63,60): error MSB4086: A numeric comparison was attempted on "$(MSBuildVersion)" that evaluates to "" instead of a number, in condition "$(MSBuildVersion) >= 16.1.0". [D:\home\site\repository\MyCompany\MyCompany.csproj]
Failed exitCode=1, command="D:\Program Files (x86)\MSBuild\14.0\Bin\MSBuild.exe" "D:\home\site\repository\MyCompany\MyCompany.csproj" /nologo /verbosity:m /t:Build /t:pipelinePreDeployCopyAllFilesToOneFolder /p:_PackageTempDir="D:\local\Temp\8d727f56aa60788";AutoParameterizationWebConfigConnectionStrings=false;Configuration=Release;UseSharedCompilation=false /p:SolutionDir="D:\home\site\repository\.\\"
An error has occurred during web site deployment.
\r\nD:\Program Files (x86)\SiteExtensions\Kudu\84.10807.4030\bin\Scripts\starter.cmd "D:\home\site\deployments\tools\deploy.cmd"
```

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

More details here: https://stackoverflow.com/q/57631309/114029

**Comment by ParsaGachkar** [comment]
> Looks like you're running into the following condition in Roslyn
> 
> https://github.com/dotnet/roslyn/blob/master/src/Compilers/Core/MSBuildTask/Microsoft.Managed.Core.targets#L63
> 
> The reason this condition exists is that our editor config support required new primitives to be added to MSBuild in 16.1. These primitives are not supported on previous versions of MSBuild and, as a transition mechanism, we isolated the use of the primitives to a separate target file. The condition though is using `$(MSBuildVersion)` which isn't supported in MSBuild until 15.6 hence we end up comparing an empty string to a number which is an error.
> 
> This all means though when you attempt to load the latest package on 14.0 it will error out on the condition instead of silently ignoring the `<Import>` entirely.
> 
> It's simple enough to fix that on our side to make the condition safe in the face of missing `$(MSBuildVersion)`. At the same time though this is a scenario that we don't support. The Microsoft.Net.Compilers package, and the other variants, are all tied to a specific version of MSBuild. Loading the package into a different version will result in an error here:
> 
> https://github.com/dotnet/roslyn/blob/master/src/NuGet/Microsoft.Net.Compilers/build/Microsoft.Net.Compilers.props#L18
> 
> Often times you'll find that the package functions in an older version of MSBuild but it's still officially unsupported. The compiler team instead supports loading the package in the version of MSBuild that it is targeted for. For the 3.X compilers that is the 16.0+ versions of MSBuild.
> 
> It does look like our check in the NuPkg props file is out of date ([needs to be updated](https://github.com/dotnet/roslyn/issues/38312) to list 15.0 as unsupported as well). But 14.0 is definitely unsupported for the 3.X versions of the NuPkg.

Dude I'm using visual studio code, What do I need to do specifically?!

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
