### ISSUE TITLE
Generating deployment script fails - 'node' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by pbisku** [projectkudu/kudu#3023]
Hi all,

we are deploying our .NET Web via the Azure Deployment Center, where we connected a external git repo. Until the end of July this worked every time.

Now the last sync failed when generating the deployment script with this error message:

`Using the following command to generate deployment script: 'azure site deploymentscript -y --no-dot-deployment -r "D:\home\site\repository" -o "D:\home\site\deployments\tools" --aspWAP "D:\home\site\repository\Swiss20\Swiss20.csproj" --solutionFile "D:\home\site\repository\Swiss20.sln"'.
'node' is not recognized as an internal or external command,
operable program or batch file.
'node' is not recognized as an internal or external command,\r\noperable program or batch file.\r\nD:\Program Files (x86)\SiteExtensions\Kudu\84.10807.4030\bin\Scripts\starter.cmd "D:\Program Files (x86)\SiteExtensions\Kudu\84.10807.4030\bin\node_modules\.bin\kuduscript.cmd" -y --no-dot-deployment -r "D:\home\site\repository" -o "D:\home\site\deployments\tools" --aspWAP "D:\home\site\repository\Swiss20\Swiss20.csproj" --solutionFile "D:\home\site\repository\Swiss20.sln"`

There was an update of the Kudu Version in August:

Name|modified
--|--
82.10503.3890.installed | 6.7.2019, 16:26:18
84.10807.4030.installed | 19.8.2019, 19:02:46

We would appreciate any help leading to a solution to this problem. If any further information is needed we thankfully will provide!

Many thanks,
Peter

**Comment by suwatch** [comment]
Are you using 64 bits?   There could a known bug that we are fixing and might still be some scale units not getting the fix (ETA 4 weeks).   Try work around by switching to 32 bits (using Portal).

**Comment by pbisku** [comment]
After switching to 32 Bit in the Portal the deployment scripts are running without error - Thanks!
