### ISSUE TITLE
Multiple Triggered Webjob instances running during FileSystem ReadOnly

### ISSUE THREAD

**Issue by suwatch** [projectkudu/kudu#3024]
The lock obj used by Triggered Webjob is forgiving and allowed multiple Job instances to acquire the log.   The fix is to be more restricted similar to Continuous webjobs singleton.

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
