### ISSUE TITLE
Powershell process timeouts in Kudu

### ISSUE THREAD

**Issue by vijiniro** [projectkudu/kudu#3025]
I'm trying to run this PS script in Kudu diagnostic console, Process is terminated around in 58 mins.

$count = 3600 + 120;
$index = 0;
Write-Output "Starting timeout test. Test will run for $count seconds."
while ($count -gt $index) {
    Start-Sleep -Seconds 1
    $index = $index + 1;
    Write-Output "$index seconds passed now ..."
}
Write-Output "Completed without timeout after $index seconds!"

[output.log.txt](https://github.com/projectkudu/kudu/files/3579045/output.log.txt)
![ProcessTerminated](https://user-images.githubusercontent.com/3133579/64337780-9f2c9a80-d012-11e9-9c3b-656b2c6ae8f4.PNG)

**Comment by vijiniro** [comment]
It is as intended by Kudu But still leaving the bug as the documentation should be updated to reflect this.
https://github.com/projectkudu/kudu/blob/master/Kudu.Services/Commands/PersistentCommandController.cs#L322-L326

**Comment by twomm** [comment]
Would be great, if the timeout could be made configurable.

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
