### ISSUE TITLE
Deployment doesn't support .NET Core 3.0 applications

### ISSUE THREAD

**Issue by rangeranger** [projectkudu/kudu#3028]
### The log/error given by the failure.
Handling ASP.NET Core Web Application deployment.
D:\Program Files (x86)\dotnet\sdk\2.2.108\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.TargetFrameworkInference.targets(137,5): error NETSDK1045: The current .NET SDK does not support targeting .NET Core 3.0.  Either target .NET Core 2.2 or lower, or use a version of the .NET SDK that supports .NET Core 3.0. [D:\home\site\repository\Adient\Adient.Business.Contracts\Adient.Business.Contracts.csproj]

**Comment by kanazaca** [comment]
I'm getting this error too when using KUDU to build my .NET Core 3.0 application.
This is just sad, the runtime is there, but the sdks no.
This is happening for more than 2 months and still no fix

There is at least an ETA for this?

**Comment by elglogins** [comment]
Hi, did you solve this issue?

**Comment by EelcoKoster** [comment]
Hitting the same error... Maybe this issue should be renamed to "Git deployment doesn't support .NET Core 3.0 applications"? To raise more awareness?

**Comment by elglogins** [comment]
What you can do is, is to remove 'build or publish' responsibility from Kudu. Move it outside to place (f.x. your CD pipeline) where changes are committed and pushed to Kudu git remote.

So Kudu git remote will have only files, of published application, and then you can use .NET Core 3.0.

**Comment by akytsun** [comment]
the same problem... and still no fix

**Comment by suwatch** [comment]
@patricklee2  could you provide the ETA for kudu build support for dotnetcore 3.0?    I understand we have started rolling out in Dec (right after 3.0 was announced) - however due to some issue, we hold this off.  Not sure what the latest update is.

@akytsun  when you said same problem, please share.   The fact that you no longer use Kudu to build - it should not yield the same error.

**Comment by patricklee2** [comment]
We current have msbuild 15 on our machines, we will upgrade to msbuild 16 and then install 3.0 SDKs
As we the last few sdk builds had notable issues, we targeting the Feb sdk release.

**Comment by andreasohlund** [comment]
Any updates on this?

**Comment by patricklee2** [comment]
see https://github.com/projectkudu/kudu/issues/3138

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
