### ISSUE TITLE
Does not install with setup script

### ISSUE THREAD

**Issue by justin-romano** [projectkudu/kudu#3031]
> For deployment issues, please provide us with the following information:
> ---------------------------------------------------------------

### Repro steps.
Download KuduDevSetup.cmd from Setup
run from powershell as administrator

### The log/error given by the failure.
```console
C:\temp} .\KuduDevSetup.cmd

The software that you obtain using the Web Platform Installer Command Line Tool is licensed to you by its owner.  Microsoft grants you no rights for third party software.
Successfully loaded primary feed: https://aka.ms/webpifeed51
Failed to Load feed: C:\temp\KuduSetupCustomWebPiFeed.xml
Could not find file 'C:\temp\KuduSetupCustomWebPiFeed.xml'.
The following products are not available on this machine or already installed: KuduDevSetup
No products to be installed (either not available or already installed)

Removing applicationPoolDefaults.processModel.setProfileEnvironment attribute, since you are running on Windows 8.1
Cleared section "system.applicationHost/applicationPools" at configuration path "MACHINE/WEBROOT/APPHOST"
```

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
