### ISSUE TITLE
libstdc++.so CXXABI and GLIBCXX not found errors on pre-defined Linux App Service instance

### ISSUE THREAD

**Issue by cheempz** [projectkudu/kudu#3035]
I've followed along the ruby quick-start tutorial where the only change is I've included the AppOptics Ruby agent as a dependency in the Gemfile.  The app deploys as expected but the agent cannot load, giving this error:
```
ERROR -- : Missing AppOpticsAPM libraries.  Tracing disabled.
ERROR -- : Error: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /tmp/bundle/gems/appoptics_apm-4.9.0/lib/oboe_metal.so) - /tmp/bundle/gems/appoptics_apm-4.9.0/lib/oboe_metal.so
```

The AppOptics Ruby agent compiles a native extension during install time.  I think the error is due to the Kudu and App instances being different distros, where Kudu is Debian 9 with libstdc++ v6.0.22 while App is Debian 8 with libstdc++ v6.0.20.  So the extension compiled against Kudu is not compatible with the libstdc++ version on the App instance.  

### Repro steps.
Follow along the [Create a Ruby on Rails App in App Service on Linux](https://docs.microsoft.com/en-us/azure/app-service/containers/quickstart-ruby) tutorial using the demo app https://github.com/Azure-Samples/ruby-docs-hello-world.  Before deploying to Azure, commit a change where you add the AppOptics Ruby agent to the end of the Gemfile so that it looks like this:
```
$ tail Gemfile
  gem 'capybara', '>= 2.15'
  gem 'selenium-webdriver'
  # Easy installation and use of chromedriver to run system tests with Chrome
  gem 'chromedriver-helper'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]

gem 'appoptics_apm'
```
Then push to the azure remote GH; the deploy should complete successfully.

### The log/error given by the failure.
The application runs correctly the but agent is not loaded due to ```/usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.9' not found```

### Mention any other details that might be useful.
The Kudu instance for my App is Debian 9, while the App instance is Debian 8.  This means a difference in the stdlibc++ library of 6.0.22 (kudu) vs 6.0.20 (app):

**kudu**
```
lrwxrwxrwx 1 root root 19 Feb 14  2018 libstdc++.so.6 -> libstdc++.so.6.0.22
```
**app**
```
lrwxrwxrwx 1 root root 19 Dec 13  2018 libstdc++.so.6 -> libstdc++.so.6.0.20
```

On the App instance if I copy the installed agent gem to the shared persistent drive `/home` and then run `ldd` on the compiled extension `oboe_metal.so` I reproduce the error:
```
root@314f093478b0:/home# cp -r /tmp/bundle/gems/appoptics_apm-4.9.0/ .

root@314f093478b0:/home# ls -di /home/appoptics_apm-4.9.0/
7881299347971980 /home/appoptics_apm-4.9.0/

root@314f093478b0:/home# ldd /home/appoptics_apm-4.9.0/lib/oboe_metal.so
/home/appoptics_apm-4.9.0/lib/oboe_metal.so: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /home/appoptics_
apm-4.9.0/lib/oboe_metal.so)
/home/appoptics_apm-4.9.0/lib/oboe_metal.so: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/appoptic
s_apm-4.9.0/lib/oboe_metal.so)
        linux-vdso.so.1 (0x00007ffcf633a000)
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f3320beb000)
        liboboe-1.0.so.0 => /home/appoptics_apm-4.9.0/lib/../ext/oboe_metal/lib/liboboe-1.0.so.0 (0x00007f332063b000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f332033a000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f331ff8f000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f331fd79000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f3321113000)
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f331fb5e000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f331f95a000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f331f73d000)
```
while on the Kudu instance it goes fine:
```
root@e0ec7aa5c009:~# ls -di /home/appoptics_apm-4.9.0/
7881299347971980 /home/appoptics_apm-4.9.0/

root@e0ec7aa5c009:~# ldd /home/appoptics_apm-4.9.0/lib/oboe_metal.so
        linux-vdso.so.1 (0x00007ffdf8182000)
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fbd2fa70000)
        liboboe-1.0.so.0 => /home/appoptics_apm-4.9.0/lib/../ext/oboe_metal/lib/liboboe-1.0.so.0 (0x00007fbd2f4c0000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fbd2f1bc000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fbd2ee1d000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fbd2ec06000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fbd3000f000)
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fbd2e9ec000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fbd2e7e8000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fbd2e5cb000)
```

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
