### ISSUE TITLE
Suggestion: debug console sort by ModifiedDate

### ISSUE THREAD

**Issue by tomturnerdesign** [projectkudu/kudu#3036]
> For deployment issues, please provide us with the following information:
> ---------------------------------------------------------------
I just lost a day because the first time I ran deployment I thought I saw it sorting with the latest at the bottom.  

I was learning how to do a custom deployment script and seeing that the log output didn't change.  I thought I just didn't know how to do it.

Turns out I was clicking on the old deployment folder not my newest which is mixed in with other deployments.

If the files could sort by ModifiedDate that would help avoid this confusion, I must not be the first to do this.  

### Repro steps.
1. Goto Kudu Debug Console 
2. Deploy using /api/zipdeploy
3. See that deployments are sorted by GUID Name. 

### Project structures.
> in order to reproduce your issue at our end we need a simple 
> [github repository](https://github.com/projectkudu/kudu/wiki/Using-a-git-repo-to-report-an-issue)
> that highlights structure of the project

### The log/error given by the failure.
> Normally this include a stack trace, error code and some more information.

### Debug your Azure website remotely.
> it is recommanded that you share your Web App name, directly or [indirectly](https://github.com/projectkudu/kudu/wiki/Reporting-your-site-name-without-posting-it-publicly)
> we can take a look at what's going on.

### Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
