### ISSUE TITLE
Mysql in app auto close azure web app

### ISSUE THREAD

**Issue by letanloc1998** [projectkudu/kudu#3037]
> For deployment issues, please provide us with the following information:
> ---------------------------------------------------------------

### Repro steps.
> your project built successfully on your dev machine but failed on Azure?
No
> please write down your build tools and their versions (ie `Msbuild 15.1.0.0`)

### Project structures.
> in order to reproduce your issue at our end we need a simple 
> [github repository](https://github.com/projectkudu/kudu/wiki/Using-a-git-repo-to-report-an-issue)
> that highlights structure of the project

### The log/error given by the failure.
> Normally this include a stack trace, error code and some more information.

### Debug your Azure website remotely.
> it is recommanded that you share your Web App name, directly or [indirectly](https://github.com/projectkudu/kudu/wiki/Reporting-your-site-name-without-posting-it-publicly)
> we can take a look at what's going on.

### Mention any other details that might be useful.
MySQL in app web app auto close if no connection to web
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by suwatch** [comment]
elaborate more please.  error details etc.

**Comment by letanloc1998** [comment]
I have fix it. Mysql change port when start server. I config setting get port to fix it
