### ISSUE TITLE
Deploying Python TimerTrigger function individually using the discouraged Function API

### ISSUE THREAD

**Issue by Cescante** [projectkudu/kudu#3038]
Hi,

We are trying to deploy a simple python timer trigger to a linux functionapp with an ARM template. Because MSDeploy only supports Windows functionapps, we attempted https://github.com/projectkudu/kudu/wiki/Functions-API

by submitting the code of the python script in the "files" property.

### Repro steps.
https://blog.kloud.com.au/2018/08/16/deploying-azure-functions-with-arm-templates/

### Project structures.
Template snippet:
```
      "apiVersion": "2015-08-01",
      "type": "Microsoft.Web/sites",
      "name": "[variables('functionAppName')]",
      "location": "[parameters('location')]",
      "kind": "functionapp,linux",
      "properties": {
        "name": "[variables('functionAppName')]",
        "reserved": true,
        "config": {
          "bindings": [
            {
              "name": "myTimer",
              "type": "timerTrigger",
              "direction": "in",
              "schedule": "[variables('functionSchedule')]"
            }
          ],
          "disabled": false
        },
        "files": {
          "__init__.py": "[parameters('functionFileContent')]"
        }
      },
```
![image](https://user-images.githubusercontent.com/2474951/65461937-9b1dbc80-de09-11e9-8535-c1496223f4fa.png)

After a successful deployment (of the template via the azure pipeline, there's no error), no Function shows in the Function App

Could you tell us if this is even supported?

**Comment by suwatch** [comment]
@ahmelsayed  could you help with this?

**Comment by ahmelsayed** [comment]
That won't work on consumption linux. 

You can use the [`/zipdeploy`](https://github.com/projectkudu/kudu/wiki/Deploying-from-a-zip-file-or-url) which in ARM looks like 

```json
"resources": [
        {
          "name": "ZipDeploy",
          "type": "extensions",
          "location": "[parameters('location')]",
          "apiVersion": "2015-08-01",
          "dependsOn": [
            "[concat('Microsoft.Web/sites/', variables('functionAppName'))]"
          ],
          "properties": {
            "packageUri": "[parameters('zipFileUrl')]"
          }
        }
      ]
```

/cc @Hazhzeng

the content of the zip file should be a valid function project at the root, e.g:

```
- host.json
- requirements.txt
/ TimerFunction1
|  - function.json
|  - __init__.py
```

If you have packages in `requirements.txt`, it'll pip install them.

**Comment by Cescante** [comment]
Hi, @ahmelsayed,

I just tried zipdeploy but am getting back an InternalServerError:
```
Name: ifcontainermonitorfunctionappppe/ZipDeploy
Type: Microsoft.Web/sites/extensions
Failed
09/23/2019 17:56:20 UTC-7 
09/23/2019 17:56:22 UTC-7
InternalServerError
Operation Id: FE769748DEF66CDBCorrelation
Id: f53f222d-927c-4294-92fa-6f097b244418
Code: ResourceDeploymentFailure     Message: The response for resource had empty or invalid content.
```

I tried publishing the same zip with az cli:
`az functionapp deployment source config-zip`
and the function app core tools:
`fun azure functionapp publish`

and both of those works.

ARM snippet updated per your instructions (thanks!):
```
    {
      "apiVersion": "2015-08-01",
      "type": "Microsoft.Web/sites",
      "name": "[variables('functionAppName')]",
      "location": "[parameters('location')]",
      "kind": "functionapp,linux",
      "identity": {
        "type": "UserAssigned",
        "userAssignedIdentities": {
            "[resourceID(parameters('userIdentityResourceGroup'), 'Microsoft.ManagedIdentity/userAssignedIdentities/', parameters('userIdentityName'))]": {}
        }
      },
      "properties": {
        "name": "[variables('functionAppName')]",
        "clientAffinityEnabled": false,
        "reserved": true
      },
      "dependsOn": [
        "[resourceId('Microsoft.Insights/components', parameters('appInsightsName'))]"
      ],
      "resources": [
        {
          "apiVersion": "2015-08-01",
          "name": "appsettings",
          "type": "config",
          "dependsOn": [
            "[resourceId('Microsoft.Web/sites', variables('functionAppName'))]"
          ],
          "properties": {
            "AzureWebJobsStorage": "[concat('DefaultEndpointsProtocol=https;AccountName=',parameters('storageAccountName'),';AccountKey=',listkeys(resourceId('Microsoft.Storage/storageAccounts', parameters('storageAccountName')), '2015-05-01-preview').key1,';')]",
            "FUNCTIONS_EXTENSION_VERSION": "~2",
            "WEBSITE_NODE_DEFAULT_VERSION": "8.11.1",
            "FUNCTIONS_WORKER_RUNTIME": "[variables('functionWorkerRuntime')]",
            "APPINSIGHTS_INSTRUMENTATIONKEY": "[reference(resourceId('microsoft.insights/components/', parameters('appInsightsName')), '2015-05-01').InstrumentationKey]",
            "WEBSITE_RUN_FROM_PACKAGE": "1"
          }
        },
        {
          "name": "ZipDeploy",
          "type": "extensions",
          "location": "[parameters('location')]",
          "apiVersion": "2015-08-01",
          "dependsOn": [
            "[concat('Microsoft.Web/sites/', variables('functionAppName'))]"
          ],
          "properties": {
            "packageUri": "[parameters('msdeployPackageUrl')]"
          }
        }
      ]
    }
```

**Comment by Hazhzeng** [comment]
Hi @Cescante, I assume the function app name is **ifcontainermonitorfunctionappppe**.
However, I'm not able to see ZipDeploy request in neither Kudu table nor HttpIncomingRequests table.

cluster('Wawscus').database('wawsprod').Kudu
| where PreciseTimeStamp >= datetime(2019-09-23) and PreciseTimeStamp <= datetime(2019-09-25)
| where StampName == 'waws-prod-sn1-161'
| where siteName == 'ifcontainermonitorfunctionappppe'
| where address contains_cs 'zipdeploy'

cluster('Armprod').database('ARMProd').HttpIncomingRequests
| where PreciseTimeStamp >= datetime(2019-09-23) and PreciseTimeStamp <= datetime(2019-09-25)
| where httpMethod != 'GET'
| where targetUri has 'ifcontainermonitorfunctionappppe'
| where targetUri contains_cs 'zipdeploy'
| limit 100

Could you send me the correlation id (or screenshot) in the ARM request?
Thanks,

**Comment by Cescante** [comment]
hey @Hazhzeng, here's the error we are getting back from the ARM deployement:
![image](https://user-images.githubusercontent.com/2474951/65548905-434a8880-ded1-11e9-9ced-c96989f66b61.png)

09/23/2019 21:03:51 UTC-7
09/23/2019 21:03:54 UTC-7
 InternalServerError
Operation Id: FE769748DEF66CDB
Correlation Id: 65ba101e-a8c0-49f8-bac4-0be9b6c8bb9a
Error:  
    Code: ResourceDeploymentFailure 
    Message: The response for resource had empty or invalid content.

**Comment by Hazhzeng** [comment]
Sorry for the late reply @Cescante.
I check the Azure Resource Manager http incoming and outgoing table, the ARM is propagating your request without error.

However, once it hits the GeoMaster, the GeoMaster fails to add a header a header to the response. And this should be the reason why it fails.
```
cluster("Wawscus").database("wawsprod").AntaresAdminGeoEvents
| where PreciseTimeStamp >= datetime(2019-09-24 04:00:00) and PreciseTimeStamp <= datetime(2019-09-24 05:00:00)
| where SiteName == 'ifcontainermonitorfunctionappppe'
| where Verb == 'PUT'
| where Level < 3
```

@ahmelsayed, do you know who is the point of contact for issues in GeoMaster?

**Comment by nabeelp** [comment]
Did this issue ever get resolved?  I am running into this same "The response for resource had empty or invalid content" error when trying to use ARM to zipdeploy a Python function app on Azure Linux consumption plan.

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
