### ISSUE TITLE
Unable find/install SiteExtensions published to www.siteextensions.net

### ISSUE THREAD

**Issue by suwatch** [projectkudu/kudu#3039]
We have been in the process of deprecating `www.siteextensions.net` in favor of a more sustainable `www.nuget.org`.   We ask the owners to migrate their extensions to `www.nuget.org`.   

Recently, we made a code change that may **break** those using SiteExtensions from `www.siteextensions.net` explicitly.

**Mitigation:**  If you set `SCM_SITEEXTENSIONS_FEED_URL` to other feed url, you must also set appSettings `SCM_USE_SITEEXTENSION_V1 = 1`.   This would allow the fallback logic to use legacy feed url.

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
