### ISSUE TITLE
WEBSITE_RUN_FROM_PACKAGE does not work properly with REST API

### ISSUE THREAD

**Issue by ustun** [projectkudu/kudu#3041]
Our Linux web app is deployed with WEBSITE_RUN_FROM_PACKAGE=1 setting via Azure Devops.

We are trying to run some post-deploy actions, however the zip file is not mounted when accessing the machine via Kudu and its REST API.

I verified this with the following: 

- Executed the command `ls` on an Azure Web App via REST API.
- Verified that the contents were not the same as what we had deployed and what we were seeing when we SSH'ed through Kudu or Azure Portal.
- Tried to delete the files inside wwwroot and was able to delete them, although it should have been impossible if we had accessed the machine with WEBSITE_RUN_FROM_PACKAGE=1 since that mounts the zip file via fuse on /home/site/wwwroot.

This issue is also I believe related to the issue I created on Azure Pipelines task repo at https://github.com/microsoft/azure-pipelines-tasks/issues/11440

**Comment by damienwebdev** [comment]
I may be seeing something similar in https://github.com/microsoft/azure-pipelines-tasks/issues/11444 

All my function apps no longer appear to work after being deployed via Azure Devops.

**Comment by metu** [comment]
Facing the same issue

**Comment by suwatch** [comment]
Include @sanchitmehta.   This usually means the zip file is corrupted or not deflateable.   please check if that is the case?

**Comment by ustun** [comment]
In my case, the zip is not broken and the app functions ok. It is only when accessing via kudu rest api that it sees the file system as if nothing has been mounted.

**Comment by ustun** [comment]
Thank you very much for confirming the issue @sanchitmehta .

Is implementing that on the roadmap? 

What we are trying to achieve is to be able to run some one-off tasks (for example running migrations) when we deploy to a staging server. Can you suggest any workarounds for that then? 

What we want is the equivalent of something like `ssh server -c 'some command'` for Azure Webapps. We were using kudu in Azure Devops for this, but this no longer works after we switched to using this flag (which sped up the deployment, down to 30 seconds from 17 mins)

**Comment by ustun** [comment]
I solved this issue via `expect` utility for now.

Here is some snippet for those interested:

```tcl
     spawn az webapp ssh -g my-resource-group  --name my-app-service
     expect "root@"
     send "cd /home/site/wwwroot\r"
     expect "root@"
     send "node node_modules/sequelize-cli/lib/sequelize db:migrate\r"
     expect "root@"
     send "node node_modules/sequelize-cli/lib/sequelize db:migrate:status\r"
     expect "root@"
     send "exit\r"
     expect eof
```

**Comment by garimpeirodouniverso** [comment]
> I solved this issue via `expect` utility for now.

Hello @ustun , could you kindly provide more information about your workaround solution? I am also finding issues while running commands ("php artisan migrate" FWIW) in Kudu while the very same commands on the Web App SSH work just fine.

Where are you running these "expect" + "az webapp ssh" commands from? On the post deployment script (i.e. Kudu) or via Azure CLI task (bash) on DevOps pipeline?

If it is from the Azure CLI task, are you running it on a self-hosted VM? Because I am not able to install "expect" on the MS hosted DevOps agent (ubuntu-latest).

Thanks in advance!

**Comment by ustun** [comment]
Hi @garimpeirodouniverso unfortunately I run them from my laptop for now :)  Please let me know if you can find a workaround too.

**Comment by garimpeirodouniverso** [comment]
Hi @ustun thanks for your response!

> Maybe you could install expect inside the App Service from Kudu though

It seems like installing packages is locked down on Kudu, unfortunately. I have tried with "sudo apt-get install" and "apt-get install" but did not work.

Maybe I can make it work by using a self-hosted agent on an Ubuntu VM but I'd prefer a simpler route first :)

**Comment by garimpeirodouniverso** [comment]
For what it's worth, I was able to install expect inside the Azure CLI task in YAML Pipelines (AzureCLI@2) and execute "spawn az webapp ssh" from there.

Not ideal, but gets the job done.

**Comment by ustun** [comment]
Oh nice find, I'll give it a go.

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
