### ISSUE TITLE
Is it time to delete https://www.siteextensions.net/

### ISSUE THREAD

**Issue by tjrobinson** [projectkudu/kudu#3043]
Site Extensions finished moving to nuget in September 2018, a year ago at the time of writing. See: https://github.com/Azure/app-service-announcements-discussions/issues/34

However, https://www.siteextensions.net/ is still up and gives no indication that it's no longer used/active etc. It's also confusing as there are extensions listed on siteextensions.net that aren't actually available in Azure, and other that are in Azure but aren't listed on siteextensions.net.

Is it time to delete https://www.siteextensions.net/ and set up a redirect to nuget.org instead? If not, there should at least be a message to tell people that it's no longer the right place to be looking.

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
