### ISSUE TITLE
Can't turn off Health Check feature in Azure App Service 

### ISSUE THREAD

**Issue by oblomingo** [projectkudu/kudu#3045]
### Repro steps.
> Please enable app service Health Check feature by adding healthCheckPath in config as described in wiki page https://github.com/projectkudu/kudu/wiki/Health-Check-(Preview)/c754d62b928b2d99837e288efa071f9c6bf449f9.
> I'm using Azure resource manager (https://resources.azure.com) to remove healthCheckPath property from config. I can press "Edit" and remove this line (or set value to null), but after "Put" or "Patch" press the healthCheckPath line still there with old value. I can only change value to another string value.
Could you please tell me what I'm doing wrong? How turn off Health Check feature in App Service?

Thanks for your attention. I’m looking forward to your reply.

**Comment by suwatch** [comment]
To reset any string-type settings, set value to empty string.   Null or missing means no-change.

**Comment by oblomingo** [comment]
Thanks a lot, I've just turned off health check feature.
I think that setting empty value to reset property is not really obvious. Probably, setting null value should work either.
