### ISSUE TITLE
No Response After Zipdeploy

### ISSUE THREAD

**Issue by abramjstamper** [projectkudu/kudu#3051]
This week I implemented deploying from a ZIP file via the API for my Azure Linux App Service. However, I don't seem to get a reply after the deployment is successful. I verify that the deployment is successful by including a hidden file with the timestamp of the deployment in the zip file. I can ssh into my Linux App Service and verify that after a few minutes the hidden timestamp file updates to the latest timestamp. However, I don't get a response from the server after a successful upload.

I was following the instructions [here](https://github.com/projectkudu/kudu/wiki/Deploying-from-a-zip-file-or-url). I have some code that's omitted that creates my ZIP file correctly (as it's deploying successfully). However, I never seem to get a response from the Kudu server after running this cURL command. It definitely uploads successfully as I can verify that it's deployed with my timestamp file. I'm using a linux implementation of cURL, the `-t` option didn't work for me. However, I found `--data-binary @<file_path>` in the MS docs, and that was successful. I looked into it, but I don't think cURL has a timeout [docs](https://ec.haxx.se/usingcurl-timeouts.html). 

These are my app settings: 
```
[
  <...Omitted...>
  {
    "name": "SCM_DO_BUILD_DURING_DEPLOYMENT",
    "value": "0",
    "slotSetting": false
  },
  {
    "name": "SCM_ZIPDEPLOY_DONOT_PRESERVE_FILETIME",
    "value": "1",
    "slotSetting": false
  },
  {
    "name": "WEBSITE_HTTPLOGGING_RETENTION_DAYS",
    "value": "7",
    "slotSetting": false
  },
  {
    "name": "WEBSITE_NODE_DEFAULT_VERSION",
    "value": "10.6.0",
    "slotSetting": false
  }
]
```

What am I doing wrong? 

```
  curl                                                                     \
    https://<omitted>.scm.azurewebsites.net/api/zipdeploy \
    --progress-bar                                                         \
    -X POST                                                                \
    -u <omitted>-deploy                                                    \
    --data-binary @"build.zip"                                             \
    -o /dev/null                                                           \
    -l -D -                                                                \
```

Console output from cURL
```
HTTP/1.1 100 Continue                                                         

######################################################################## 100.0%
<it hangs here without an exit even though deployment was successful for a couple minutes>
HTTP/1.1 502 Bad Gateway
Content-Type: text/html
Server: Microsoft-IIS/10.0
Date: Fri, 04 Oct 2019 17:02:41 GMT
Content-Length: 1477

######################################################################## 100.0%
```

After adding the `-i ` and `-D -` flags, I got the response above. Keep in mind deployment was successful, so I would expect a 200?

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
