### ISSUE TITLE
Linux web apps ignore `project` setting in .deploy file and App Settings

### ISSUE THREAD

**Issue by jewpaltz** [projectkudu/kudu#3056]
### Repro steps.
- Create a linux web app
- Add App Setting project=path/to/folder/with/package.json
- or Add .deploy file to git repo root with project=path/to/folder/with/package.json
- Add kudu deployment from github with a node project in path/to/folder/with/package.json

### Project structures.
https://github.com/jewpaltz/2019Fall_WhatDoYouMeme/commit/2798e3b371567498ef6c6dab739744280be71055

### Expected results
Deployment command should be "KuduSync.NET from: 'D:\home\site\repository\path\to\folder\with\package.json' to: 'D:\home\site\wwwroot'" as it is when you run the same steps on a windows web app
Which is also the results describe in https://github.com/projectkudu/kudu/wiki/Customizing-deployments

### Actual results
Deployment command is "KuduSync.NET from: 'D:\home\site\repository\' to: 'D:\home\site\wwwroot'"
Which means that kudu can no find the package.json to run npm install or the start script

**Comment by baSSiLL** [comment]
Experiencing the same with Linux app.
- `PROJECT = <directory>` in app settings set in Azure Portal is ignored
- `project = <directory>` setting in **.deployment** file is ignored
The only way I found the build to work for a subdir of the repo was to generate a custom bash script for deployment (with kuduscript) and use `command = bash deploy.sh` in **.deployment**. Apparently I'd prefer the app setting to just work so I can set up build of different directories from the repo in different apps.

**Comment by paytience** [comment]
Any progress on this? I want to deploy a dist folder from one repository. When this dist folder is in the repository by itself the website runs fine, but not when there are other files.

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
