### ISSUE TITLE
Missing doc for two app settings

### ISSUE THREAD

**Issue by cephalin** [projectkudu/kudu#3060]
Documentation issue in https://github.com/projectkudu/kudu/wiki/Configurable-settings:

Please add documentation for the following app settings:

How to update the DNS server settings for your Azure App Service app.

- WEBSITE_DNS_SERVER with value having the IP address of the primary DNS server.
- WEBSITE_ALT_DNS_SERVER (optional), with value having the IP address of a second DNS server.

**Comment by dcbrown16** [comment]
@cephalin any progress here? I have a customer asking about how to achieve this and there is no documentation that I'm aware of.

**Comment by dcbrown16** [comment]
@cephalin I'm looking for this information again. Please have it added to an official doc, thanks!

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
