### ISSUE TITLE
CRON Expression to run webjob on 1st day of Aug every year at 01:00 AM 

### ISSUE THREAD

**Issue by Lbhagi** [projectkudu/kudu#3061]
I have given CRON as '0 0 1 1 8 *' to run on 1st day of Aug every year. But in job_scheduler.log I found as below
"Scheduling WebJob with 0 0 1 1 8 * next schedule expected in 40.00:00:00"
what is the next execution time?
Is my CRON Correct ?

More details: I have CRON 1 to run after 31 days, it worked as expected.
But i have given CRON to run after 43 days, But it didnt work as expected.

CRON 1  "0 0 1 19 11 *" - Expected next run after 31 days, 13 hours, 24 minutes  - Yes its correct
[10/18/2019 11:35:12 > ec1845: SYS INFO] Scheduling WebJob with 0 0 1 19 11 * next schedule expected in 31.13:24:47.7563432

CRON 2  "0 1 1 12 *" - Expected next run after 43 days, 13 hours, 17 minutes  - But webjob is giving wrong
[10/18/2019 11:42:58 > ec1845: SYS INFO] Scheduling WebJob with 0 0 1 1 12 * next schedule expected in 40.00:00:00

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
