### ISSUE TITLE
Zip Deploy file diff

### ISSUE THREAD

**Issue by nemenos** [projectkudu/kudu#3065]
Hello,

I think there is a bug on kudu zip deploy.
After about 1 day, trying to figure out why my new release (that got migrated from full framework runtime to notecoreapp2.2 runtime) didn't work, I realized that fluentnhibernate (v2.1.2) dll did not get updated by kudu, even if the correct version was inside the zip.

The dlls where on the same date, same size, but of course they have a different hash.
Is it a problem with kudu's zip deploy file diff check?

To get the correct version deployed I had to delete manually the file from kudu's Console, and republish

Thank you,
Andrea

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
