### ISSUE TITLE
Do scheduled webjobs leverage Azure Scheduler which will be retired?

### ISSUE THREAD

**Issue by jkewley** [projectkudu/kudu#3066]
I have a client who got an email notice saying that they are actively using Azure Scheduler which will be retired in a few months time. They are unsure what might be using it, but asked if their webjobs triggered by a schedule in settings.job might be leveraging Azure Scheduler. It doesn't look like that's the case based on the use of NCronTab, but I want to be sure before I tell them they don't need to rewrite the webjob to be triggered by some other scheduled process.

**Comment by suwatch** [comment]
App Service Webjobs triggered by a schedule in settings.job **does not** use Azure Scheduler.    In fact, App Service Webjob has little to do with Azure Scheduler.

**Comment by jkewley** [comment]
Thanks for confirming.
