### ISSUE TITLE
Accessing Azure Function on Linux via FTP

### ISSUE THREAD

**Issue by christian-vorhemus** [projectkudu/kudu#3068]
It is possible to retrieve FTP credentials for an Azure Function (based on Python in that case) running on Linux. However, when I connect via FTP, the wwwroot folder is empty. There is also a LogFiles folder which is empty as well.

Is this intended? Is it a bug? Is FTP access supported for Azure Functions on Linux? If no, what is the supported way to get or view files, my Azure Function is creating?

**Comment by suwatch** [comment]
FTP credential is available thru Portal or Azure Resource Manager CLI tool.  If this is Consumption Linux Function, you are likely using run-from-package/zip.   In that case, the content is provided thru Zip file and FTP's wwwroot will not have any content. 

@balag0 to help clarify.

**Comment by christian-vorhemus** [comment]
Thanks for the response @suwatch, I deploy the Function App via the VS Code Azure Function extension. The function runs periodically and writes content to a file. I'd like to get access to that file. I know, there are workarounds like writing those files to external storages but I thought there must be an easier way to get the file content directly on the function host.

**Comment by suwatch** [comment]
Please confirm if this is a linux consumption.   If so, I am afraid you can only push log to storage.  @balag0  is there another way to get log?

**Comment by christian-vorhemus** [comment]
Yes, it uses a Linux consumption plan.

**Comment by balag0** [comment]
Currently on Linux consumption we do not have a shared persistent drive between kudu and the main site. 
So like Suwat mentioned writing to storage is the only option for now. We adding a feature make reading/writing to a persistent store easily. We mount a storage account as a fileshare inside the container which the functions code can access using regular file system apis. 
Is this something you would be interested in?  This should be available sometime next week.

cc @anirudhgarg

**Comment by christian-vorhemus** [comment]
From a user's perspective it would be great to have more control over the Linux Function App. Because right now, I can't SSH to the host, I can't use FTP to see the files, there is no Log Streaming. I don't really know if my app on Azure is doing what it should do (without using external tools like Application Insights), it feels like a black box.

However, for my specific use case, a file share would make life already a bit easier.

**Comment by balag0** [comment]
Agreed on all the points. Most of these are already in the backlog but no ETA at this time.
Regarding the file share mounting, will provide a link to a wiki page with the instructions early next week when we are closer to deployment. Thanks for the feedback.

**Comment by et1975** [comment]
Any progress on any of this?

**Comment by balag0** [comment]
Sorry forgot to update here. Yes, we added support to mount file shares for Linux.
Let us know if you have any questions.

https://docs.microsoft.com/en-us/azure/azure-functions/storage-considerations#mount-file-shares-linux

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
