### ISSUE TITLE
Azure App Service's App Service Editor (Preview) - (request handler failed. Error code: 500) for viewing large file (444 MB)

### ISSUE THREAD

**Issue by michaelsync** [projectkudu/kudu#3072]
We got this error `request handler failed. Error code: 500` when viewing the file which is around 444 MB on App Service Editor (Preview). 

![image](https://user-images.githubusercontent.com/192911/67993902-efcd1680-fc96-11e9-9b80-d276a54ca705.png)

**Comment by michaelsync** [comment]
Any update? 

@patricklee2 @suwatch @balag0 @pragnagopa

**Comment by suwatch** [comment]
Add @soninaren for help.  @michaelsync could you look at network trace and see what api call (uri) return 500?

**Comment by michaelsync** [comment]
Thanks. u mean network trace on the Chrome Dev Tool? or Do I need to download some networking tool?

**Comment by suwatch** [comment]
Chrome F12 should do

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
