### ISSUE TITLE
WEBSITE_RUN_FROM_PACKAGE causes App Service Plan reach disk storage quota

### ISSUE THREAD

**Issue by guimabdo** [projectkudu/kudu#3077]
Hi,
My project uses asp.net core with angular server side rendering which results in a large package (~180MB).

I'm using a F1 tier App Service for development/test which has 1GB disk storage limit.

After some deployments, my pipeline starts to fail (Internal Server Error).

At first I had no idea what was happening, but after some digging up I've found that my App was reaching the storage quota.

I'm currently deleting manually older packages from /SitePackages folder as a workaround.

Do we have some retention option that makes older packages to be automatically removed?

### Repro steps.

- Make subsequent deploys until reach App Service disk storage quota

### The log/error given by the failure.

```
Updating App Service Application settings. Data: {"WEBSITE_RUN_FROM_PACKAGE":"1"}
Updated App Service Application settings and Kudu Application settings.
Package deployment using ZIP Deploy initiated.
##[error]Failed to deploy web package to App Service.
##[error]Error: Error: Failed to deploy web package to App Service. Internal Server Error (CODE: 500)
```

**Comment by suwatch** [comment]
See https://github.com/projectkudu/kudu/wiki/Configurable-settings#zipdeploy-to-keep-at-most-last-n-zip-files

**Comment by guimabdo** [comment]
@suwatch Thank you!
