### ISSUE TITLE
Cannot create deploy.cmd using --php in windows 10

### ISSUE THREAD

**Issue by ephraimlambarte** [projectkudu/kudu#3079]
im trying to generate a deploy.cmd file using kuduscript in windows 10 with command `kuduscript -y --php` but it gives me:

`no such file or directory, open 'C:\Users\USER\AppData\Roaming\npm\node_modules\kuduscript\lib\templates\deploy.batch.php.template'`

i tried downloading the kudu deployment template in https://{sitename}.scm.azurewebsites.net/api/deploymentscript 

but it just gives me an error:
`{"Message":"Operation only supported if not using a custom deployment script"}`

current kuduscript version in my machine: 1.0.17

**Comment by Vortexdude** [comment]
also facing the same issue

**Comment by jmester13** [comment]
Also facing this issue.

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
