### ISSUE TITLE
Obfuscate Kudu environment settings

### ISSUE THREAD

**Issue by Francisco-Gamino** [projectkudu/kudu#3080]
### Description
Obfuscate Kudu environment settings. This issue was reported by a customer during Ignite 2019.

**The current behavior:**
Right now, when you go to Kudu (from the function app in the portal), after you select environment, all the environment variables are displayed.

**Desired behavior:**
Environment variables should have a hidden value, just like the application settings in the function app. Please see snapshot below. 

![image](https://user-images.githubusercontent.com/12720858/69366160-92e7cf00-0c4a-11ea-919f-31795f932bc5.png)

**Comment by suwatch** [comment]
More details please.

**Comment by Francisco-Gamino** [comment]
Hello @suwatch, I've added more details for this issue. Let me know if you have any other questions. Thanks!

**Comment by suwatch** [comment]
Unlike portal, Kudu is intended for dev (Contributor role) and I would think of it is a debugger tool.   All information are readily available (no obfuscation) based on that design.
