### ISSUE TITLE
Doc on outbound connection limits refers to outdated SKUs and misses new SKUs

### ISSUE THREAD

**Issue by mmaitre314** [projectkudu/kudu#3081]
The doc here contains useful reference data about the maximum number of TCP connections for each SKU:
https://github.com/projectkudu/kudu/wiki/Azure-Web-App-sandbox#cross-vm-numerical-limits
It uses outdated SKUs though (A1/A2/A3) and misses newer SKUs like P1V2/P2V2/P3V2. Can you document the latest values across SKUs?

(cross-posted from [SO](https://stackoverflow.com/questions/58928703/what-is-the-limit-on-tcp-ports-in-azure-web-apps))

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
