### ISSUE TITLE
RunFromPackage with multiple apps in virtual directories

### ISSUE THREAD

**Issue by ggirard07** [projectkudu/kudu#3082]
Historically, we have been using a single web app with multiple virtual directories in order to share the same domain for multiple APIs. Now we would like to move those application to `RunFromPackage`.

Problem is, we can't find any documentation about how to host multiple applications in virtual directories on the same web app by using `ZipDeployment` + `RunFromPackage`. Is this a supported scenario?

Still in the same kind of issue, is there any way to deploy an ASP.Net Core app (WebApi) with an azure webjob on the same web app by using `ZipDeployment` + `RunFromPackage`?

**Comment by suwatch** [comment]
How do you deploy your application in the past?   You can definitely use ZipDeployment + RunFromPackage.  You will have to zip up your artifact with your app file structure as they would appear on d:\home\site\wwwroot folder.  RunFromPackage will just virtualize your zip as if it was literally extracted to the folder.

**Comment by ggirard07** [comment]
In the past, we used to deploy 
1. The webjobs first.
2. Each API apps separately to each virtual directories.
3. The main SPA application at wwwroot by preserving app_data folder.

The webjobs + APIs vs the SPA application are managed by different teams with different repos (and so different pipelines).
Repackaging all of this in a single zip will force us to create a single artifact to deploy and will force to redeploy every component even if a single one changed.

Also, there use to be [a simple way to package webjobs in a web app](https://docs.microsoft.com/en-us/azure/app-service/webjobs-dotnet-deploy-vs#convertlink). But this is no longer possible since moving to .Net Core and SDK style project does not support this feature ([a workaround as been provided](https://github.com/Azure/azure-webjobs-sdk/issues/745#issuecomment-428677382) but this not ideal to carry this over multiple projects).

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
