### ISSUE TITLE
FunctionAppHelper needs to support "v3" and "v3-preview"

### ISSUE THREAD

**Issue by brettsam** [projectkudu/kudu#3084]
There's a number of places that only expect V1 or V2 and things blow up if there's a V3. For example: 
- https://github.com/projectkudu/kudu/blob/master/Kudu.Core/Infrastructure/FunctionAppHelper.cs#L22

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
