### ISSUE TITLE
Kudu console doesn't unzip the files

### ISSUE THREAD

**Issue by anujsharrma** [projectkudu/kudu#3090]
I have created a Azure DevOps pipeline and when the artifact drop on the location, kudu console doesn't unzip it. Please check and let me know what is the issue.

![kuduconsole](https://user-images.githubusercontent.com/23416939/70416806-e0a36a80-1a85-11ea-8e04-bf7b9b017d4b.png)
> For deployment issues, please provide us with the following information:
> ---------------------------------------------------------------

### Repro steps.
> your project built successfully on your dev machine but failed on Azure?
> please write down your build tools and their versions (ie `Msbuild 15.1.0.0`)

### Project structures.
> in order to reproduce your issue at our end we need a simple 
> [github repository](https://github.com/projectkudu/kudu/wiki/Using-a-git-repo-to-report-an-issue)
> that highlights structure of the project

### The log/error given by the failure.
> Normally this include a stack trace, error code and some more information.

### Debug your Azure website remotely.
> it is recommanded that you share your Web App name, directly or [indirectly](https://github.com/projectkudu/kudu/wiki/Reporting-your-site-name-without-posting-it-publicly)
> we can take a look at what's going on.

### Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
