### ISSUE TITLE
Support for the 2019 SameSite changes

### ISSUE THREAD

**Issue by kapsiR** [projectkudu/kudu#3094]
Currently when connecting to the Kudu-Service via the `scm` url (e.g. `https://myservice.scm.azurewebsites.net`), the current behavior when using the updated `SameSite` changes is a 403.

Repro steps (Firefox in this case):

1. Make sure your have a fresh session 
2. Enable the new behavior via about:config `network.cookie.sameSite.laxByDefault` to `true`
3. Try to go to the Kudu service via the `scm` url

References:

- [SameSite IETF changes](https://tools.ietf.org/html/draft-west-cookie-incrementalism-00#section-3)
- [MS DevBlogs](https://devblogs.microsoft.com/aspnet/upcoming-samesite-cookie-changes-in-asp-net-and-asp-net-core/)
- [ASP.NET Docs](https://docs.microsoft.com/en-us/aspnet/samesite/system-web-samesite)

**Comment by suwatch** [comment]
Thank for the information.  We are aware of this and have made a fix which will be rolled out in Jan 2020.   Please try again end of Jan 2020.

**Comment by kapsiR** [comment]
It seems that the patch is deployed now. It works now with a SameSite default of `Lax`.

Thanks
