### ISSUE TITLE
Site auto swaps after zip deploy even though auto swap is disabled

### ISSUE THREAD

**Issue by xt0rted** [projectkudu/kudu#3098]
### Repro steps.

My staging slot has auto swap turned off in the portal (it was on and then an hour before deploying I turned it off). Each deploy I make to the staging slot auto swaps a few minutes after the site comes up.

### Project structures.

I'm using [azure/webapps-deploy](https://github.com/azure/webapps-deploy) to deploy my site from GitHub Actions. This is my deployment step:

```yml
- name: Publish To Azure
  id: publish
  uses: azure/webapps-deploy@v1
  with:
    app-name: roxierosedesign
    slot: staging
    package: artifacts/wwwroot
    publish-profile: ${{ secrets.azureWebAppPublishProfile }}
```

### The log/error given by the failure.

The output from the deployment action:

```
Finding files matching input: artifacts/wwwroot
This is folder package 
Is the package an msdeploy package : false
[GET]https://roxierosedesign-staging.scm.azurewebsites.net/api/settings
Archiving artifacts/wwwroot to d:\a\_temp\temp_web_package_4119084608050061.zip
Successfully created archive d:\a\_temp\temp_web_package_4119084608050061.zip
Package deployment using ZIP Deploy initiated.
[POST]https://roxierosedesign-staging.scm.azurewebsites.net/api/zipdeploy?isAsync=true&deployer=GITHUB_ZIP_DEPLOY
[GET]https://roxierosedesign-staging.scm.azurewebsites.net/api/deployments/latest?deployer=GITHUB_ZIP_DEPLOY&time=2019-12-15_18-21-48Z
[GET]https://roxierosedesign-staging.scm.azurewebsites.net/api/deployments/latest?deployer=GITHUB_ZIP_DEPLOY&time=2019-12-15_18-21-48Z
[GET]https://roxierosedesign-staging.scm.azurewebsites.net/api/deployments/9b81be3443ac467589a92e594a13d467
Deploy logs can be viewed at https://roxierosedesign-staging.scm.azurewebsites.net/api/deployments/9b81be3443ac467589a92e594a13d467/log
Successfully deployed web package to App Service.
[PUT]https://roxierosedesign-staging.scm.azurewebsites.net/api/deployments/b974f6e5b48b737ebfd07aaace39eaba01b03b811576434114997
Encountered a retriable status code: 409. Message: 'Conflict'.
[PUT]https://roxierosedesign-staging.scm.azurewebsites.net/api/deployments/b974f6e5b48b737ebfd07aaace39eaba01b03b811576434114997
Encountered a retriable status code: 409. Message: 'Conflict'.
[PUT]https://roxierosedesign-staging.scm.azurewebsites.net/api/deployments/b974f6e5b48b737ebfd07aaace39eaba01b03b811576434114997
Successfully updated deployment History at https://roxierosedesign-staging.scm.azurewebsites.net/api/deployments/b974f6e5b48b737ebfd07aaace39eaba01b03b811576434114997
[GET]https://roxierosedesign-staging.scm.azurewebsites.net/api/vfs/site/deployments/9b81be3443ac467589a92e594a13d467/manifest
App Service Application URL: https://roxierosedesign-staging.azurewebsites.net
```

The output from the kudu deploy log:

```json
[{
    "log_time": "2019-12-15T18:21:49.2604219Z",
    "id": "2c7937a8-25f7-409f-a4a4-fec7c6d44923",
    "message": "Updating submodules.",
    "type": 0,
    "details_url": null
}, {
    "log_time": "2019-12-15T18:21:49.3854217Z",
    "id": "0c97cf66-c425-4520-b33a-0e583d035295",
    "message": "Preparing deployment for commit id '9b81be3443'.",
    "type": 0,
    "details_url": null
}, {
    "log_time": "2019-12-15T18:21:49.8166148Z",
    "id": "1a52b058-de90-4d48-a6b0-5f2b98f8d415",
    "message": "Skipping build. Project type: Run-From-Zip",
    "type": 0,
    "details_url": null
}, {
    "log_time": "2019-12-15T18:21:49.8947182Z",
    "id": "c99d0304-b9d8-4db8-8019-195c6af3a456",
    "message": "Skipping post build. Project type: Run-From-Zip",
    "type": 0,
    "details_url": null
}, {
    "log_time": "2019-12-15T18:21:49.9416171Z",
    "id": "62695d85-db78-4842-82f8-d51a98b5aff2",
    "message": "Triggering recycle (preview mode disabled).",
    "type": 0,
    "details_url": null
}, {
    "log_time": "2019-12-15T18:21:50.1603674Z",
    "id": "dd1e55bf-e042-43d9-aea4-6d41c3f0f15d",
    "message": "Deployment successful.",
    "type": 0,
    "details_url": null
}, {
    "log_time": "2019-12-15T18:21:52.1207358Z",
    "id": "ae0cd3b0-845f-44a9-93f3-4d12fb574062",
    "message": "Requesting auto swap to 'production' slot with 'AUTOSWAPb856891f-34bd-4919-aad3-9f7cc0b65857' id successful.",
    "type": 0,
    "details_url": null
}]
```

### Debug your Azure website remotely.

The app name is `roxierosedesign`.

### Mention any other details that might be useful.

I contacted support about this the other day, the support request number is `119121124004944`.

**Comment by suwatch** [comment]
It was reproed consistently for you?  Give us the UTC time when you turned off the auto-swap and we can confirm if any wrong with that.

**Comment by xt0rted** [comment]
I haven't tried with another site, but it continues to happen on this one with every deploy to staging. The timestamp in the activity log from when I turned off auto swap is `Wed Dec 11 2019 12:50:36 GMT-0500 (Eastern Standard Time)`.

**Comment by xt0rted** [comment]
I setup a new app service plan & app service on a different account called `autoswap-test`, then deployed a site to it. I was able to reproduce the auto-swap issue there as well.

The first deploy went to the staging slot with default settings of auto-swap disabled, second deploy was with auto-swap enabled, and then the third and fourth deploys were with auto-swap disabled again and both resulted in an auto-swap.

When I turned auto-swap on and off I was using the portal. I then tried using [the cli](https://docs.microsoft.com/en-us/cli/azure/webapp/deployment/slot?view=azure-cli-latest#az-webapp-deployment-slot-auto-swap) and Cloud Shell to turn off auto-swap and that looks to have worked. Now when I deploy I'm not seeing auto-swaps after each deployment.

**Comment by suwatch** [comment]
> then the third and fourth deploys were with auto-swap disabled again

Interesting.   BTW, Kudu decides whether to AutoSwap based on [this env](https://github.com/projectkudu/kudu/blob/89720bdbcc0f94ef354a2bdd05c462c7f89c24fc/Kudu.Core/Helpers/PostDeploymentHelper.cs#L67-L70).  The env is set and reset when you enable or disable autoswap respectively.    Could you try your repro again?   However, when you disable autoswap, before doing the deployment, try browsing to SCM site (env tab) and check if the env is removed (disabled).

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
