### ISSUE TITLE
Webjob host appears to be crashing after webdeploy in US East datacenter

### ISSUE THREAD

**Issue by JiriKovar** [projectkudu/kudu#3102]
During the deployment, the webjob host in US East datacenter does not even change the status of webjob to "Stopping" and ceases all the activity - not even swap wakes it up and the only thing that helped was manually starting the webjob via portal. In EU West datacenter it appears to be fine, while the configuration, code & deployment steps are completely the same.

### Repro steps.
- Built via Microsoft (R) Build Engine version 15.9.21+g9802d43bc3 for .NET Framework
- Deployed to staging slot via `az webapp deployment source config-zip -g "..." -n "..." -s "staging" --src "..."` (in sample logs seen at 10:03 AM)
- After deployment swapped via `az webapp deployment slot swap -g "..." -n "..." -s "staging"` (in sample logs seen at 10:25 AM)
- Manually starting the webjob, because our alerting detected it was not running (in sample logs seen at 10:46 AM)

### Project structures.
- App service with "always on", .net 4.7, 64bit
- Continuous webjob processing messages from event hub (2 copies in 2 separate web apps in each datacenter, both in US are acting the same). Nothing else runs on that app service. 
- Deployed to staging slot, after potential manual testing swapped to production slot

### The log/error given by the failure.
Logs from US East datacenter (the broken ones - stopping at deployment time logs only the first line & any information from the swap time is completelly missing):
> ...
> [12/31/2019 10:03:04 > 73d9a5: SYS INFO] Detected WebJob file/s were updated, refreshing WebJob
> [12/31/2019 10:46:04 > 73d9a5: SYS INFO] Detected WebJob file/s were updated, refreshing WebJob
> [12/31/2019 10:46:04 > 73d9a5: SYS INFO] Status changed to Starting
> [12/31/2019 10:46:04 > 73d9a5: SYS INFO] WebJob singleton setting is False
> [12/31/2019 10:46:18 > 73d9a5: SYS INFO] Run script '<My_webjob>.exe' with script host - 'WindowsScriptHost'
> [12/31/2019 10:46:18 > 73d9a5: SYS INFO] Status changed to Running
> ...

Logs from EU West datacenter (the expected ones - no information about manually starting the webjob, because it wasn't necessary and therefor wasn't done):
> ...
> [12/31/2019 10:03:06 > fe93d7: SYS INFO] Detected WebJob file/s were updated, refreshing WebJob
> [12/31/2019 10:03:06 > fe93d7: SYS INFO] Status changed to Stopping
> [12/31/2019 10:03:06 > fe93d7: INFO] Job host stopped
> [12/31/2019 10:03:11 > fe93d7: ERR ] Thread was being aborted.
> [12/31/2019 10:03:11 > fe93d7: SYS INFO] WebJob process was aborted
> [12/31/2019 10:03:11 > fe93d7: SYS INFO] Status changed to Stopped
> [12/31/2019 10:03:11 > fe93d7: SYS INFO] Status changed to Starting
> [12/31/2019 10:03:11 > fe93d7: SYS INFO] Job directory change detected: Job file 'AngleSharp.dll' timestamp differs between source and working directories.
> [12/31/2019 10:03:14 > fe93d7: SYS INFO] Run script '<My_webjob>.exe' with script host - 'WindowsScriptHost'
> [12/31/2019 10:03:14 > fe93d7: SYS INFO] Status changed to Running
> [12/31/2019 10:03:24 > fe93d7: INFO] No job functions found. Try making your job classes and methods public. If you're using binding extensions (e.g. ServiceBus, Timers, etc.) make sure you've called the registration method for the extension(s) in your startup code (e.g. config.UseServiceBus(), config.UseTimers(), etc.).
> [12/31/2019 10:03:24 > fe93d7: INFO] Job host started
> [12/31/2019 10:25:17 > fe93d7: SYS INFO] WebJob is stopping due to website shutting down
> [12/31/2019 10:25:17 > fe93d7: SYS INFO] Status changed to Stopping
> [12/31/2019 10:25:17 > fe93d7: INFO] Job host stopped
> ... (running correctly without need to start manually)

I have tried to investigate the logs in "trace" folder in kudu, but I didn't find anything suspicious, or any difference between EU & US.

### Debug your Azure website remotely.
If you need subscription ID & web app name, please contact me via my primary public email of my account.

### Mention any other details that might be useful.
- It looks like it was still OK at 26.12.2019, but I will check that information with the rest of our team (I wasn't running the deployment).
- The "special" settings in app service we use:
WEBJOBS_IDLE_TIMEOUT -> 3600 (on both staging and production slots)
WEBJOBS_DISABLE_SCHEDULE -> 0 (only on staging)
WEBJOBS_STOPPED -> 0 (only on staging)

**Comment by suwatch** [comment]
Appreciate a detailed explanation of the issue @JiriKovar and apology for the delay!   

If you browse to Kudu Debug Console and try to run exe directly, it might yield some clue.   Also try to create another site in the same App Service Plan and run, see if repro.  You could try different ASP on the same region see if repro.   Feel free to share site name ([indirectly](https://github.com/projectkudu/kudu/wiki/Reporting-your-site-name-without-posting-it-publicly)) and the webjob name.

**Comment by JiriKovar** [comment]
Hi @suwatch,

I will try that next time it happens, thank you for all your suggestions. 

The subscription ID is: 52da...8f87, as far as the site name, we have 4 where this is happening, as a example 2 of those should have a name that have name "de...er-br..ge-*-usa...." and it happens on all the webjobs running there.

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
