### ISSUE TITLE
Run app service plan without exposed net interface

### ISSUE THREAD

**Issue by NoNameProvided** [projectkudu/kudu#3105]
I would expect that I can create an app service which does not bind to any http server to the provided port (use-case: the app listens to a Redis queue and process tasks without exposing any HTTP interface). Apparently this is not possible, the runtime will always kill the application after 15 seconds because it expects a HTTP server bind to the provided PORT env variable. 

#### Repro steps.

- start an app without binging to the provided PORT env variable 
- see in the logs that the app is killed because failed to bind to the given port in 15 seconds

#### Project structures.

n/a

#### The log/error given by the failure.

From Docker log (2020_01_06_RD501AC568477E_docker.log)
```
2020-01-06 16:34:08.312 ERROR - Container ap-scheduler-test_2_8544691c for site ap-scheduler-test has exited, failing site start
2020-01-06 16:34:08.322 ERROR - Container ap-scheduler-test_2_8544691c didn't respond to HTTP pings on port: 8080, failing site start. See container logs for debugging.
```

**Comment by suwatch** [comment]
This is not the right forum for this question.  Please post question to https://docs.microsoft.com/answers/topics/azure-webapps.html instead.
