### ISSUE TITLE
Cannot Stop WebJob via REST API

### ISSUE THREAD

**Issue by dannymyers** [projectkudu/kudu#3106]
I am trying to use the kudo REST API endpoint to start/stop my continuous web job. I am able to get the status of my job (using GET), but when I try to stop the job, I get a `404 Not Found`. I am using POST. Is this functionality still supported?

### Repro steps.

```csharp
// Works (for status)
var response = await client.GetAsync("/api/continuouswebjobs/Xyz.WebJob");
// Doesn't Work
var response = await client.PostAsync("/api/continuouswebjobs/Xyz.WebJob/start", null);
```

### Mention any other details that might be useful.

- My webjob name has a dot in it. `Xyz.WebJob` I doubt that makes a difference. My authorization is correct as I'm able to get the status of the web job.
- My WebJob has `Always On` enabled.

**Comment by suwatch** [comment]
Share the time when you perform operation, the site name (here or [indirectly](https://github.com/projectkudu/kudu/wiki/Reporting-your-site-name-without-posting-it-publicly)) and webjob name (full or partial name) please.

**Comment by dannymyers** [comment]
cdp-tst-usw-vgprd-app
Cdp.****Producer
~ 1/9/2020 8:37:02 PM UTC

**Comment by dannymyers** [comment]
@suwatch should this functionality still work with VNET Integration enabled?

**Comment by suwatch** [comment]
should be irrelevant to vnet integration.  In fact if not working due to such, it would not be 404 (application response).

**Comment by suwatch** [comment]
@ahmelsayed  this is continuous web with WEBSITE_RUN_FROM_PACKAGE.   Do you know if the stop/start eg. SecondaryJobManager would return 404 and if by design?    If so, what is the suggested way for people start/stop webjob with WEBSITE_RUN_FROM_PACKAGE?

**Comment by AntonChernysh** [comment]
@ahmelsayed @suwatch Regerring to original post by @dannymyers . 
Start/Stop endpoints work fine when WebJob is deployed to Virtual Application, but not when it's deployed to the root (/) of App Service. Only status endpoint works. We get "500 Internal Server Error" in debug web console when trying to stop web job from Azure portal. 

Path when deployed to root (/): site\wwwroot\App_Data\jobs\continuous\Our.App.Name
Path when deployed to Virtual App (/our_app_name): site\jobs\continuous\Our.App.Name
