### ISSUE TITLE
Getting remote: HTTP Basic: Access denied\nfatal: Authentication failed for repository with deploy token

### ISSUE THREAD

**Issue by devslb** [projectkudu/kudu#3107]
### Repro steps.
> your project built successfully on your dev machine but failed on Azure? Yes
> It is a django project in python, and Kudu engine is used to deploy from external source.
   
### Project structures.
> I have a python django project on Gitlab and followed exact steps to setup external repository with deploy token taken from kudu server. 

### The log/error given by the failure.
> Normally this include a stack trace, error code and some more information.
While syncing or deploying the app, it fails while fetching from remote repo. 
Getting remote: HTTP Basic: Access denied\nfatal: Authentication failed for repository with deploy token

### Debug your Azure website remotely.
> After logging into kudu server, I confirmed that public key matches the deploy key added on external repository. 
I also tried to run 'git fetch' and faced the same error. I tried to change config but it needs superuser. 

Please help to fix the authentication issue!

**Comment by suwatch** [comment]
Did the deployment log details show what cred being used?  For deploy key/private repo hint, Kudu supposes to use SSH not basic auth over http.

**Comment by devslb** [comment]
Thanks for response!
Yes for deploy key, I would expect it to take SSH as repoUrl but neither resource explorer nor the az cli allows me to set. 
e.g. for below command, 
az webapp deployment source config --branch master --manual-integration --name <name> --repo-url git@gitlab.com:XXXXX/XXXX.git --resource-group <rgname>

it gives me error:
### There was a conflict. Conflict with existing ScmType: ExternalGit

So if ExternalGit only works with https, how would Kudu access it with private keys. 
Please let me know if I need to set to some other values or any other fix.

**Comment by suwatch** [comment]
The conflict error was due to your site already configured with manual integration (ExternalGit) with another URL.  We don't support update one repoUrl to another on the fly.    You have to disconnect deployment and then resetup again.

**Comment by devslb** [comment]
ok the issue is resolved after deleting and creating new web app. 
Thank you
