### ISSUE TITLE
Unrecognized attribute 'useOriginalURLEncoding'

### ISSUE THREAD

**Issue by dmarlow** [projectkudu/kudu#3108]
I'm trying to set useOriginalURLEncoding=false in my web.config under configuration/system.webServer/rewrite/rules but get the following error:

Module | RewriteModule
Notification | SendResponse
Handler | StaticFile
Error Code | 0x8007000d
Config Error | Unrecognized attribute 'useOriginalURLEncoding'
Config File | \\?\D:\home\site\wwwroot\web.config

How can I enable this? Here's the blog/article for more info: https://blogs.iis.net/iisteam/url-rewrite-v2-1

**Comment by hugompfer** [comment]
Im having the same problem here, any updates on this?

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
