### ISSUE TITLE
Add Author & AuthorEmail to deployment environment variables

### ISSUE THREAD

**Issue by kim3er** [projectkudu/kudu#3109]
Hi!

It'd be incredibly useful to be able to access `Author` and `AuthorEmail` as environment variables, within post deployment scripts. My specific requirement is so I can notify Raygun of deployments, https://raygun.com/documentation/product-guides/deployment-tracking/deployments-api/.

Both values are already exposed in the `ChangeSet` class, which is used to build the `DeploymentContext`. https://github.com/projectkudu/kudu/blob/91aa97089b2f4cab997883d2ce902507ddd7e0ec/Kudu.Core/Deployment/DeploymentManager.cs#L656

If the `DeploymentContext` had both variables, it looks like they could be added as environment variables in the `ExternalCommandBuilder`. https://github.com/projectkudu/kudu/blob/787c893a9336beb498252bb2f90a06a95763f9e9/Kudu.Core/Deployment/Generator/ExternalCommandBuilder.cs#L92

Is there any appetite for this? I'd do the work myself (and am happy to do so), I'm just not sure I'd be able to adequately test it without a proper environment, as we use Azure.

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
