### ISSUE TITLE
Zip Deploy fails for branches

### ISSUE THREAD

**Issue by ryankettrey** [projectkudu/kudu#3111]
This is occurring when we deploy from zip to a function app using Azure repos.

It seems to be working fine for master, but when using a branch (such as 'development') we see it fail with:

`ChangeSetId(development) does not match f58f3ef057594d7aa6c2f71a6d97a033, 'master' or 'HEAD'`. 

The stack trace points to `Kudu.Core.SourceControl. NullRepository.ChangeSet GetChangeSet(string id)`.

Looking at that code, it appears that this will only pass if the value passed in is 'master', 'HEAD', or the change set id that the NullRepository was seeded with. That would explain why it works for master, as it just matches and passes it on through. However, when it's a branch that is passed in, it could never work.

I'm wondering if the calling code should be passing in 'HEAD'. A little further up in our ZipPushDeploy XML logs, we see a line:

`<step title="Attempting to fetch target branch HEAD" date="2020-01-25T18:39:36.939"/>`

So there it shows the branch as HEAD instead of the real name, development. Perhaps when it's a branch it is supposed to be passing in 'HEAD', which would allow it to pass the checks.

We are building and releasing the 'development' branch from Azure Release Pipelines. However, we saw the exact same error occur when we used the Deployment Center built into the Azure Portal for Function Apps to deploy the 'development' branch. It does work for master.

`<step title="None repository commit" date="2020-01-25T18:39:11.541">
<step title="Commit id: f58f3ef057594d7aa6c2f71a6d97a033" date="2020-01-25T18:39:11.572" Message="{"type":"deployment","commitId":"045760d2c313e9a6bbb93d8c0053a3a2cab9f52f","buildId":"15","releaseId":"4","buildNumber":"20200125.12","releaseName":"Release-4","repoProvider":"TfsGit","repoName":"Enterprise","collectionUrl":"https://dev.azure.com/<client-removed>/","teamProject":"<removed>","buildProjectUrl":"https://dev.azure.com/<removed>","repositoryUrl":"","branch":"development","teamProjectName":"Enterprise","slotName":"development"}" AuthorName="N/A" AuthorEmail="N/A"/>
</step>`

**Comment by mertozsaydi** [comment]
I am getting the same error when I try to deploy a function using Azure repos and pipelines. Kudu keeps returning 500 error with message ChangeSetId(main) does not match <commitId>, 'master' or 'HEAD'". Has anyone solved the issue here? @suwatch

**Comment by suwatch** [comment]
Try remove `d:\home\site\repository` folder and deploy again.

**Comment by mertozsaydi** [comment]
Unfortunately, it did not help. Still getting the error 

`<step title="Error occurred" type="error" date="2020-11-18T19:44:46.699" stackTrace=" at Kudu.Core.SourceControl.NullRepository.GetChangeSet(String id) in C:\..\NullRepository.cs:line 73 at Kudu.Core.Deployment.FetchDeploymentManager.<PerformDeployment>d__9.MoveNext()  text="ChangeSetId(main) does not match <guid>, 'master' or 'HEAD'"/>`

**Comment by suwatch** [comment]
Mind trying on a newly created site?

**Comment by mertozsaydi** [comment]
Sure thing, looks like Azure functions app deploy task worked on a newly created site but we would like to keep the same site. I am wondering what might cause this issue, any insight on this ? Thanks for your help!

**Comment by suwatch** [comment]
Understood - that is a good start for us to compare.   Could you compare the ScmType env and d:\home\site\deployments\settings.xml?  See if any differences stood out.

**Comment by mertozsaydi** [comment]
I see that newly created site do not have d:\home\site\deployments\settings.xml file. I deleted d:\home\site\deployments\settings.xml file in our current setup and looks like I am not getting 500 anymore from Azure functions app deploy task. Thanks for your help with this!🎉 @suwatch

**Comment by Fableton** [comment]
That happened to me and Azure Release Pipeline only show

```
##[error]Failed to deploy web package to App Service.
##[error]Error: Error: Failed to deploy web package to App Service. Internal Server Error (CODE: 500)
```

@suwatch [solution](#issuecomment-729937714) resolve the problem

**Comment by dmitrigw** [comment]
This issue happen two days ago in our azure account when I setup github workflow based on the following instructions: https://docs.github.com/en/actions/deployment/deploying-to-your-cloud-provider/deploying-to-azure/deploying-net-to-azure-app-service

After prolonged investigation with Azure support, the issue was resolved by deleting d:\home\site\deployments\settings.xml . This file appeared on 1 out of 3 different environments that had an identical setup. 

Notes from Azure support team:
> I'm not entirely sure why this file is only in the development environment. I check couples of web apps in my side but no one had that file.

> I believe this file might be related to the branch-related matters. My suggestion would be to inquire about it on GitHub at this link (https://github.com/projectkudu/kudu/issues/3111). You might be able to obtain more detailed information there.

**Comment by nourkilany** [comment]
Same issue happened when deploying from Azure Devops Releases to Azure app service slot
by deleting  `d:\home\site\deployments\settings.xml` the deployment worked fine
