### ISSUE TITLE
How is startup.sh generated for .Net core on Linux during zip deployment?

### ISSUE THREAD

**Issue by gpduck** [projectkudu/kudu#3119]
We're deploying a couple of .net core apps on Linux to Azure App Service via ZIP and are seeing one of them start up fine and the other is not running. On the site that is not running the `/opt/startup/startup.sh` file is configured to run `dotnet "/defaulthome/hostingstart/hostingstart.dll"` while the one that works has our project's DLL correctly specified. I've tried to locate documentation (or code) as to how the startup.sh file is generated but I have not been able to find anything.  Can someone point me in the right direction?

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
