### ISSUE TITLE
.net core projects using C# 8 features fails to build

### ISSUE THREAD

**Issue by adaneam** [projectkudu/kudu#3122]
Projects using newer C# 8 features fails to build with Kudu. I tried adding app setting for MSBUILD_PATH to %MSBUILD_15_PATH%. It did not help. 

Building project from console on azure using msbuild15 gives the same error.

ERROR => error CS1003: Syntax error, '(' expected

Above error is thrown for using newer using declaration feature in c# 8
https://www.syncfusion.com/blogs/post/csharp-8-0-using-declaration.aspx

**Comment by paulomorgado** [comment]
**C#8** needs **MSBuild 16**.

The path to **MSBuild 16** is in the `MSBUILD_16_DIR` environment variable.

**Comment by suwatch** [comment]
@patricklee2  shouldn't Kudu build use MSBUILD16 for dotnetcore by default now?  
@adaneam would you able to provide a small repro git project?

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
