### ISSUE TITLE
Kudu Browse Directory with different result as WebSSH

### ISSUE THREAD

**Issue by BjoernLaemmerzahl** [projectkudu/kudu#3126]
Hello, 

I apologize if this has been mentioned somewhere, but I have not been able to find an answer.

After deploying my Azure Function App using Zip-Deploy, my Azure function is working just fine. When I use webssh (https://xxxx.scm.azurewebsites.net/webssh/host) I can see my files in /home/site/wwwroot. However, when I use Kudu (https://xxxx.scm.azurewebsites.net/wwwroot/) the folder is empty. The same result when using FTPS (except for a few hidden files). 

How is that possible? Shouldn't they point at the same location?

![1](https://user-images.githubusercontent.com/4821787/74941378-3041d300-53f3-11ea-9ad1-8effbd16e8f0.png)

![2](https://user-images.githubusercontent.com/4821787/74941667-b52cec80-53f3-11ea-99e9-cb79e3153e8a.png)

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
