### ISSUE TITLE
build.cmd issue

### ISSUE THREAD

**Issue by awhorton** [projectkudu/kudu#3127]
I am trying to build Kudu locally on Windows Server 2016 from a fresh clone of the projectkudu repository.  I am using Visual Studio 2015 Pro, and after the initial failure, I also installed the latest MSBuild tools, which didn't help.  The msbuild.txt output is below.  What am I missing or doing wrong?

Build started 2/23/2020 10:26:48 PM.
     1>Project "C:\kudu\Build\Build.proj" on node 1 (default targets).
     1>RestorePackages:
         "C:\kudu\Build\\nuget.exe" restore -source "https://nuget.org/api/v2/" "C:\kudu\Build\..\Kudu.sln"
         MSBuild auto-detection: using msbuild version '16.4.0.56107' from 'C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\bin'.
         All packages listed in packages.config are already installed.
     1>Project "C:\kudu\Build\Build.proj" (1) is building "C:\kudu\kudu.sln" (4) on node 1 (Build target(s)).
     4>ValidateSolutionConfiguration:
         Building solution configuration "Release|Mixed Platforms".
     4>Project "C:\kudu\kudu.sln" (4) is building "C:\kudu\Kudu.Core.Test\Kudu.Core.Test.csproj" (6) on node 2 (default targets).
     6>Project "C:\kudu\Kudu.Core.Test\Kudu.Core.Test.csproj" (6) is building "C:\kudu\Kudu.Contracts\Kudu.Contracts.csproj" (8) on node 2 (default targets).
     8>BclBuildEnsureBindingRedirects:
       Skipping target "BclBuildEnsureBindingRedirects" because all output files are up-to-date with respect to the input files.
       The target "MvcBuildViews" listed in a BeforeTargets attribute at "C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\Web\Microsoft.Web.Publishing.targets (845,131)" does not exist in the project, and will be ignored.
       CoreResGen:
         No resources are out of date with respect to their source files. Skipping resource generation.
       GenerateTargetFrameworkMonikerAttribute:
       Skipping target "GenerateTargetFrameworkMonikerAttribute" because all output files are up-to-date with respect to the input files.
       CoreCompile:
         C:\Program Files (x86)\MSBuild\14.0\bin\csc.exe /noconfig /nowarn:1701,1702 /nostdlib+ /errorreport:prompt /warn:4 /define:CODE_ANALYSIS;TRACE;CODE_ANALYSIS /highentropyva+ /reference:C:\kudu\packages\Microsoft.Web.Xdt.2.1.1\lib\net40\Microsoft.Web.XmlTransform.dll /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\mscorlib.dll" /reference:C:\kudu\packages\Newtonsoft.Json.9.0.1\lib\net45\Newtonsoft.Json.dll /reference:C:\kudu\packages\NuGet.Protocol.Types.3.0.0-pre-20150220053306\lib\net45\NuGet.Client.BaseTypes.dll /reference:C:\kudu\packages\NuGet.Protocol.V2V3.3.0.0-pre-20150220053309\lib\net45\NuGet.Client.dll /reference:C:\kudu\packages\NuGet.Protocol.V2V3.3.0.0-pre-20150220053309\lib\net45\NuGet.Client.V2.dll /reference:C:\kudu\packages\NuGet.Protocol.V2V3.3.0.0-pre-20150220053309\lib\net45\NuGet.Client.V2.VisualStudio.dll /reference:C:\kudu\packages\NuGet.Protocol.V2V3.3.0.0-pre-20150220053309\lib\net45\NuGet.Client.V3.VisualStudio.dll /reference:C:\kudu\packages\NuGet.Protocol.Types.3.0.0-pre-20150220053306\lib\net45\NuGet.Client.VisualStudio.dll /reference:C:\kudu\packages\NuGet.Configuration.1.0.0-pre-20150220022717\lib\net45\NuGet.Configuration.dll /reference:nugetcore=C:\kudu\packages\NuGet.Core.2.8.3\lib\net40-Client\NuGet.Core.dll /reference:C:\kudu\packages\NuGet.Protocol.V2V3.3.0.0-pre-20150220053309\lib\net45\NuGet.Data.dll /reference:C:\kudu\packages\NuGet.Packaging.1.0.0-pre-20150220044603\lib\net45\NuGet.Frameworks.dll /reference:C:\kudu\packages\NuGet.Packaging.1.0.0-pre-20150220044603\lib\net45\NuGet.Packaging.dll /reference:C:\kudu\packages\NuGet.Packaging.1.0.0-pre-20150220044603\lib\net45\NuGet.PackagingCore.dll /reference:C:\kudu\packages\NuGet.Packaging.1.0.0-pre-20150220044603\lib\net45\NuGet.Resolver.dll /reference:C:\kudu\packages\NuGet.Versioning.1.0.7\lib\portable-net40+win\NuGet.Versioning.dll /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\System.Core.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\System.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\System.IO.Compression.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\System.Net.Http.dll" /reference:C:\kudu\packages\Microsoft.Net.Http.2.2.29\lib\net45\System.Net.Http.Extensions.dll /reference:C:\kudu\packages\Microsoft.Net.Http.2.2.29\lib\net45\System.Net.Http.Primitives.dll /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\System.Net.Http.WebRequest.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\System.Xml.Linq.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\Facades\System.Collections.Concurrent.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\Facades\System.Collections.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\Facades\System.ComponentModel.Annotations.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\Facades\System.ComponentModel.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\Facades\System.ComponentModel.EventBasedAsync.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\Facades\System.Diagnostics.Contracts.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\Facades\System.Diagnostics.Debug.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\Facades\System.Diagnostics.Tools.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\Facades\System.Diagnostics.Tracing.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\Facades\System.Dynamic.Runtime.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\Facades\System.Globalization.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\Facades\System.IO.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\Facades\System.Linq.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\Facades\System.Linq.Expressions.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\Facades\System.Linq.Parallel.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\Facades\System.Linq.Queryable.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\Facades\System.Net.NetworkInformation.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\Facades\System.Net.Primitives.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\Facades\System.Net.Requests.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\Facades\System.ObjectModel.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\Facades\System.Reflection.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\Facades\System.Reflection.Emit.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\Facades\System.Reflection.Emit.ILGeneration.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\Facades\System.Reflection.Emit.Lightweight.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\Facades\System.Reflection.Extensions.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\Facades\System.Reflection.Primitives.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\Facades\System.Resources.ResourceManager.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\Facades\System.Runtime.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\Facades\System.Runtime.Extensions.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\Facades\System.Runtime.InteropServices.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\Facades\System.Runtime.InteropServices.WindowsRuntime.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\Facades\System.Runtime.Numerics.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\Facades\System.Runtime.Serialization.Json.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\Facades\System.Runtime.Serialization.Primitives.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\Facades\System.Runtime.Serialization.Xml.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\Facades\System.Security.Principal.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\Facades\System.ServiceModel.Duplex.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\Facades\System.ServiceModel.Http.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\Facades\System.ServiceModel.NetTcp.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\Facades\System.ServiceModel.Primitives.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\Facades\System.ServiceModel.Security.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\Facades\System.Text.Encoding.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\Facades\System.Text.Encoding.Extensions.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\Facades\System.Text.RegularExpressions.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\Facades\System.Threading.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\Facades\System.Threading.Tasks.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\Facades\System.Threading.Tasks.Parallel.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\Facades\System.Threading.Timer.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\Facades\System.Xml.ReaderWriter.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\Facades\System.Xml.XDocument.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\Facades\System.Xml.XmlSerializer.dll" /debug:pdbonly /optimize+ /out:obj\Release\Kudu.Contracts.dll /ruleset:C:\kudu\Build\kudu.ruleset /subsystemversion:6.00 /resource:obj\Release\Kudu.Contracts.Resources.resources /target:library /warnaserror+ /utf8output ..\Common\CommonAssemblyInfo.cs ..\Common\Constants.cs Commands\CommandEvent.cs Commands\CommandEventType.cs Commands\CommandResult.cs Commands\ICommandExecutor.cs Deployment\DeploymentFailedException.cs Deployment\DeploymentInfoBase.cs Deployment\DeployResult.cs Deployment\DeployStatus.cs Deployment\FetchDeploymentRequestResult.cs Deployment\IDeploymentEnvironment.cs Deployment\IDeploymentManager.cs Deployment\IDeploymentManagerFactory.cs Deployment\IDeploymentStatusManager.cs Deployment\IDeploymentStatusFile.cs Deployment\IDetailedLogger.cs Deployment\IFetchDeploymentManager.cs Deployment\ILogger.cs Deployment\LogEntry.cs Deployment\LogEntryType.cs Diagnostics\ApplicationLogEntry.cs Diagnostics\DotNetCoreSharedFrameworksInfo.cs Diagnostics\ProcessInfo.cs Diagnostics\ProcessModuleInfo.cs Diagnostics\ProcessThreadInfo.cs Diagnostics\RuntimeInfo.cs Editor\VfsStatEntry.cs Functions\FunctionSecrets.cs Functions\FunctionEnvelope.cs Functions\FunctionSecretsJsonOps.cs Functions\FunctionTestData.cs Functions\IFunctionManager.cs Functions\IKeyJsonOps.cs Functions\MasterKey.cs Functions\MasterKeyJsonOps.cs HashHelpers.cs Hooks\ConflictException.cs Hooks\WebHook.cs Hooks\HooksEventTypes.cs Hooks\IWebHooksManager.cs IEnvironment.cs Infrastructure\INamedObject.cs Infrastructure\IOperationLock.cs Infrastructure\OperationLockInfo.cs Infrastructure\LockExtensions.cs Infrastructure\LockOperationException.cs Infrastructure\RS.cs Infrastructure\StringUtils.cs Jobs\ContinuousJob.cs Settings\DiagnosticsSettings.cs Jobs\JobSettings.cs Jobs\IContinuousJobsManager.cs Jobs\IJobsManager.cs Jobs\IScriptHost.cs Jobs\ITriggeredJobsManager.cs Jobs\JobBase.cs Jobs\JobSettingsKeys.cs Jobs\TriggeredJob.cs Jobs\TriggeredJobHistory.cs Jobs\TriggeredJobRun.cs Settings\ISettingsProvider.cs Settings\DeploymentSettingsExtension.cs Settings\IDeploymentSettingsManager.cs Settings\SettingsKeys.cs SiteExtensions\InvalidEndpointException.cs SiteExtensions\ISiteExtensionManager.cs SiteExtensions\SiteExtensionInfo.cs SourceControl\IFileFinder.cs SourceControl\IRepositoryFactory.cs SourceControl\ScmType.cs SSHKey\ISSHKeyManager.cs Tracing\ITracer.cs Properties\AssemblyInfo.cs SourceControl\ChangeSet.cs SourceControl\Git\IGitServer.cs SourceControl\IRepository.cs SourceControl\RepositoryInfo.cs SourceControl\RepositoryType.cs Resources.Designer.cs "C:\Users\haw7660e\AppData\Local\Temp\2\.NETFramework,Version=v4.5.2.AssemblyAttributes.cs"
         Using shared compilation with compiler from directory: C:\Program Files (x86)\MSBuild\14.0\Bin
     8>Settings\DeploymentSettingsExtension.cs(326,55): error CS1525: Invalid expression term 'int' [C:\kudu\Kudu.Contracts\Kudu.Contracts.csproj]
     8>Settings\DeploymentSettingsExtension.cs(326,59): error CS1003: Syntax error, ',' expected [C:\kudu\Kudu.Contracts\Kudu.Contracts.csproj]
     8>Done Building Project "C:\kudu\Kudu.Contracts\Kudu.Contracts.csproj" (default targets) -- FAILED.
     6>Done Building Project "C:\kudu\Kudu.Core.Test\Kudu.Core.Test.csproj" (default targets) -- FAILED.
     4>Done Building Project "C:\kudu\kudu.sln" (Build target(s)) -- FAILED.
     1>Done Building Project "C:\kudu\Build\Build.proj" (default targets) -- FAILED.

Build FAILED.

       "C:\kudu\Build\Build.proj" (default target) (1) ->
       "C:\kudu\kudu.sln" (Build target) (4) ->
       "C:\kudu\Kudu.Core.Test\Kudu.Core.Test.csproj" (default target) (6) ->
       "C:\kudu\Kudu.Contracts\Kudu.Contracts.csproj" (default target) (8) ->
       (CoreCompile target) -> 
         Settings\DeploymentSettingsExtension.cs(326,55): error CS1525: Invalid expression term 'int' [C:\kudu\Kudu.Contracts\Kudu.Contracts.csproj]
         Settings\DeploymentSettingsExtension.cs(326,59): error CS1003: Syntax error, ',' expected [C:\kudu\Kudu.Contracts\Kudu.Contracts.csproj]

    0 Warning(s)
    2 Error(s)

Time Elapsed 00:00:04.81

**Comment by suwatch** [comment]
The MSBUILD failed on the new syntax.   I think you should see the option to update your VS 2015 to latest update which will understand this syntax.

**Comment by awhorton** [comment]
Updating did resolve the issue.  Thanks.
