### ISSUE TITLE
Problem with custom warmup in app service

### ISSUE THREAD

**Issue by tom121212121212** [projectkudu/kudu#3128]
I'm trying to add a custom page for warmup so that after swapping slots in azure dev ops release pipeline, the application from the secondary slot will be warmed up.

Web.config:

...
```
<applicationInitialization>
    <add initializationPage="/Warmup.aspx">
</applicationInitialization>
```
...

aspx page:

```
public partial class Warmup : System.Web.UI.Page
{
    protected void Page_Init(object sender, EventArgs e)
    {
        Thread.Sleep(600000); // 10 minutes
    }
}
```

For test, I added Thread.Sleep without real code.

A swap takes about 3 minutes, although at least a warm-up should take 10 minutes. As a result, I get a cold application.

What am I doing wrong?

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
