### ISSUE TITLE
Install Kudu ERROR 

### ISSUE THREAD

**Issue by Su1024** [projectkudu/kudu#3130]
I want to install kudu on my Mac，So I follow the steps of the official documents，But, Execute last command `make -j4` Error, errorMessage is 
![image](https://user-images.githubusercontent.com/23012179/75938367-89fdcf00-5ec2-11ea-943a-28d894f33130.png)

env: mac os 10.15.3

help me~~

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
