### ISSUE TITLE
Sandbox home directory write violation

### ISSUE THREAD

**Issue by robertoandrade** [projectkudu/kudu#3131]
Hi,

I've been facing an issue running a web app in an Azure App Service that [other users apparently faced as well](https://stackoverflow.com/questions/55477238/why-does-this-phantomjs-process-cause-directory-x-does-not-exist-errors/55589207#comment107330157_55589207) and can't find in the [documentation](https://github.com/projectkudu/kudu/wiki/Azure-Web-App-sandbox) any evidence that this is not allowed.

When spawning a subprocess that eventually writes a single file anywhere under the home directory (`d:\home`), the whole sandbox gets into a state where it can't find files causing lots of random errors such as not finding `web.config` or `cshtml` files in the app.

Writing to the home directory from the `w3wp` (or `cmd`) process doesn't seem to cause the same issue but since the subprocess technically inherits some of the parent processes limitations in the sandbox I'm wondering what could cause this. When I repeat the same steps from within a `cmd` process, spawning the same subprocess that writes to the home directory, then the `cmd` process loses access partially to the file system, ie: trying to change directories causes a "system cannot find the path specified" error.

Any ideas if this is by design and where to find documentation for such restriction/side effect?

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
