### ISSUE TITLE
No description of network tools available for troubleshooting

### ISSUE THREAD

**Issue by phillipgibson** [projectkudu/kudu#3132]
### Issue Description

I was working with a customer and we were trying to troubleshoot some network connectivity for a VNet that was integrated to App Service. I wasn't able to use any of the normal tools to test basic network connectivity such as nc, nslookup, etc. Is there any documentation of what tools are available from the BASH console to use for network troubleshooting? 

Thanks,
PG

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
