### ISSUE TITLE
500 server error trying to use drag-and-drop in the console to PUT a non-ZIP file(s)

### ISSUE THREAD

**Issue by IanKemp** [projectkudu/kudu#3134]
Would be nice if a useful error message, something like "You need to specify a ZIP file", is displayed.

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
