### ISSUE TITLE
Healthcheck for Linux Container WebApp

### ISSUE THREAD

**Issue by bengreenier** [projectkudu/kudu#3137]
The [preview `healthCheckPath` feature](https://github.com/projectkudu/kudu/wiki/Health-Check-(Preview)) doesn't seem to be respected when configured on a Linux Container WebApp.

It's quite possible I'm misunderstanding or even abusing this feature, as I'm not really looking for health metrics collected by the platform, but instead am looking to bypass EasyAuth for an external monitor to query for health metrics. As I understand it, bypassing EasyAuth is more of a side-effect of this feature, rather than a direct feature.

### Repro steps.

+ Create Linux WebApp (AppService sku: B1), using a Docker container as the app source
+ Configure [EasyAuth](https://docs.microsoft.com/en-us/azure/app-service/configure-authentication-provider-aad) (in my specific case using Azure AD)
+ Set `healthCheckPath` using [resources.azure.com](https://resources.azure.com) under `/config/web` properties node (in my specific case using `/heath-status`)
+ Restart WebApp
+ Ensure Container logs show site is started
+ Visit `https://the-site.azurewebsites.net`, observe EasyAuth in effect, redirecting to authentication flow
+ Visit `https://the-site.azurewebsites.net/health-status`, __observe EasyAuth still in effect__

Expected outcome: EasyAuth is not in effect when visiting `https://the-site.azurewebsites.net/heath-status`.

### Workaround

To achieve my goal (hosting an unauthenticated endpoint in an Linux Container WebApp with EasyAuth enabled) it seems I'm able to use [`WEBSITE_WARMUP_PATH`](https://github.com/cgillum/easyauth/wiki/Advanced-Application-Settings), which also has a side-effect of bypassing EasyAuth for the defined route. Given that technically neither the Healthcheck preview nor the Warmup feature seem designed to deliver this auth bypass behavior, perhaps using `WEBSITE_WARMUP_PATH` is the best approach, until the broader platform can deliver other mechanisms explicitly designed to disable EasyAuth for specific routes.

+ Add `WEBSITE_WARMUP_PATH` as an appsetting (in my specific case using `/health-status`)
+ Restart site
+ Visit `https://the-site.azurewebsites.net/health-status`, observe EasyAuth is bypassed

### Project structures.

I don't have a sharable sample project at this time - hope that isn't a blocker here.

### The log/error given by the failure.

No specific log/error, more of an undesired behavior (302 to authentication flow).

### Debug your Azure website remotely.

Unable to share at this time - hope that isn't a blocker here.

### Mention any other details that might be useful.

Should this issue simply be closed, as unauthenticated health-status endpoints isn't an explicit goal of [The healthcheck preview](https://github.com/projectkudu/kudu/wiki/Health-Check-(Preview)#roadmap)?

Thanks for taking the time to review! 💙

P.S. tagging in @JasonFreeberg who seems to be the primary driver for [Healthcheck preview](https://github.com/projectkudu/kudu/wiki/Health-Check-(Preview)). 👋

**Comment by JasonFreeberg** [comment]
Hi @bengreenier, the health check feature was not originally designed to expose the specified path as an EasyAuth bypass externally. The healthcheck ping originates from within the App Service system, but any external request hitting that endpoint will first go through Easy Auth.

We are discussing this scenario internally and I will reply back on this thread with an update.

**Comment by bengreenier** [comment]
Thanks @JasonFreeberg! To keep this issue relevant for other folks as well, can you comment on the expected availability of the overall feature for Linux Container Webapp nodes?

Should the platform-driven monitoring be working and visible via the metrics pages [as documented](https://github.com/projectkudu/kudu/wiki/Health-Check-(Preview)#monitoring-and-alerts) for these type of apps?

**Comment by JasonFreeberg** [comment]
@bengreenier We actually have a bugfix deploying right now. So by the end of the month the deployment should roll through all regions. The deployment will fix the monitoring and metrics for Linux apps (including custom container apps).

**Comment by bengreenier** [comment]
Oh, Great! Thanks for sharing.

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
