### ISSUE TITLE
NetCore 3.1 Kudu build support timeline

### ISSUE THREAD

**Issue by suwatch** [projectkudu/kudu#3138]
##  .NET Core 3.1 runtime
The .NET Core 3.1 **runtime** is **currently available** on every App Service VMs.   The pre-compiled .NET Core 3.1 as well as 3.0 applications (such as  locally-build or Azure DevOps pipeline artifacts) are deployable to and runtime supported on App Services.

##  .NET Core 3.1 SDK
Unfortunately, the .NET Core 3.1 **SDK** is **not yet available**.  As a result, any .NET Core 3.1 applications which require App Services Kudu to build are not supported (see the common error message below).  Those scenarios include CI/CD git push from local or remote repository such Github.   

```
D:\Program Files (x86)\dotnet\sdk\2.2.109\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.TargetFrameworkInference.targets(137,5): error NETSDK1045: The current .NET SDK does not support targeting .NET Core 3.0.  Either target .NET Core 2.2 or lower, or use a version of the .NET SDK that supports .NET Core 3.0.
```

##  When will it be available?
Due to various factors, the current ETA for the support is **end of April'20** and we will update if any changes.  The workaround till then to pre-compile and [zipdeploy](https://github.com/projectkudu/kudu/wiki/Deploying-from-a-zip-file-or-url) or simply use Azure DevOps pipeline.   We apology for the delay.

**Comment by Pilchie** [comment]
Should this be mentioned in https://github.com/Azure/app-service-announcements-discussions/issues/129 and https://github.com/Azure/app-service-announcements-discussions/issues/118, since that's where customers are currently looking?

**Comment by suwatch** [comment]
Thanks for mentioning it!

**Comment by i-devers** [comment]
Hi, this issue also takes place with the Azure Devops Pipeline... 
Each time I do a commit and push to master the build triggers, Devops Pipeline and Release work without problem.. but then my app gives a 404...

Turning on the diagnostics logging and downloading the logs gives this:


Running oryx -appPath /home/site/wwwroot -output /opt/startup/startup.sh -defaultAppFilePath /defaulthome/hostingstart/hostingstart.dll     -bindPort 8080 -userStartupCommand 'dotnet WimApi.dll' \n\n", "level": "Informational", "EventStampType": "Stamp", "EventPrimaryStampName": "waws-prod-am2-273", "EventStampName": "waws-prod-am2-----", "Host": "RD0003----"}
Oryx Version: 0.2.20200114.13, Commit: 204922f30f8e8d41f5241b8c218425ef89106d1d, ReleaseTagName: 20200114.13
Cound not find build manifest file at '/home/site/wwwroot/oryx-manifest.toml'\n\n", "level": "Informational"
Could not find operation ID in manifest. Generating an operation id...
Build Operation ID: 326e3a3b-26e3-41f4-baa5-4058826feec7\n\n
Writing output script to '/opt/startup/startup.sh'\n\n
Running user provided startup command...
It was not possible to find any compatible framework version
WARNING: Startup command execution failed with exit code 150
Running the default application instead...
The specified framework 'Microsoft.AspNetCore.App', version '3.1.0' was not found.

I don't really understand why the CI pipeline configuration would not automatically do a zip deploy, but I am going to try to find a work around..

If anybody has tips, would be greatly appreciated...

**Comment by suwatch** [comment]
@i-devers please open another issue - this is unrelated.

**Comment by i-devers** [comment]
ok, sorry.

**Comment by suwatch** [comment]
This is now available on App Service as of 4/11/2020.
