### ISSUE TITLE
Zip deployment failed - az webapp deployment - Deploying Python Teams Bot

### ISSUE THREAD

**Issue by kayoungk** [projectkudu/kudu#3142]
Hi team,

I ran into some issues when trying to deploy my Zip file using `az webapp deployment source config-zip --resource-group "HotCrossBotRG" --name "HotCrossBotPYWebApp" --src "<myPath>\echo-bot.zip"`, and I keep getting messages saying` Zip deployment failed`. The whole output in powershell is as follows:
```
Getting scm site credentials for zip deployment
Starting zip deployment. This operation can take a while to complete ...
Deployment endpoint responded with status code 202
Configuring default logging for the app, if not already enabled
Zip deployment failed. {'id': <theAppID>, 'status': 3, 'status_text': '', 'author_email': 'N/A', 'author': 'N/A', 'deployer': 'Push-Deployer', 'message': 'Created via a push deployment', 'progress': '', 
'received_time': '2020-04-07T01:25:26.9111691Z', 
'start_time': '2020-04-07T01:25:27.0231444Z', 
'end_time': '2020-04-07T01:26:36.3530893Z', 
'last_success_end_time': None, 'complete': True, 'active': False, 'is_temp': False, 'is_readonly': True, 
'url': 'https://hotcrossbotpywebapp.scm.azurewebsites.net/api/deployments/latest', 
'log_url': 'https://hotcrossbotpywebapp.scm.azurewebsites.net/api/deployments/latest/log', 
'site_name': 'hotcrossbotpywebapp'}. 
Please run the command az webapp log tail -n HotCrossBotPYWebApp -g HotCrossBotRG 
```

The content of 'log_url' is
```
{
"ClassName": "System.IO.FileNotFoundException",
"Message": "No log found for 'latest'.",
"Data": null,
"InnerException": null,
"HelpURL": null,
"StackTraceString": "   at Kudu.Core.Deployment.DeploymentManager.GetLogEntries(String id) in /tmp/KuduLite/Kudu.Core/Deployment/DeploymentManager.cs:line 111\n   at Kudu.Services.Deployment.DeploymentController.GetLogEntry(String id) in /tmp/KuduLite/Kudu.Services/Deployment/DeploymentController.cs:line 432",
"RemoteStackTraceString": null,
"RemoteStackIndex": 0,
"ExceptionMethod": null,
"HResult": -2147024894,
"Source": "Kudu.Core",
"WatsonBuckets": null,
"FileNotFound_FileName": null,
"FileNotFound_FusionLog": null
}
```

I googled the problem and found an answer telling developers to issue this with Kudu directly(https://github.com/Azure/azure-cli/issues/11261#issuecomment-601325612). 

Additional info:
The Python Microsoft Bot example can successfully run locally. (https://docs.microsoft.com/en-us/azure/bot-service/python/bot-builder-python-quickstart?view=azure-bot-service-4.0)

The deployment instructions I followed is in this page: https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-deploy-az-cli?view=azure-bot-service-4.0&tabs=Python

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
