### ISSUE TITLE
Continuous Deployment not triggering on new Commit

### ISSUE THREAD

**Issue by Manaf-Ibrahim** [projectkudu/kudu#3143]
> For deployment issues, please provide us with the following information:
> ---------------------------------------------------------------

### Repro steps.
Updated changes in repo locally - pushed changes to Azure DevOps Repo.

### Project structures.
Standard Laravel project structure which can be found at https://docs.microsoft.com/en-us/azure/app-service/app-service-web-tutorial-php-mysql

### The log/error given by the failure.

No error - the deployemnt is not being updated as requried.

### Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by Manaf-Ibrahim** [comment]
Apologies for the lack of information prior to this - after further investigation I have found that the sync process is getting stuck on the "Update Web App Source Control Configuration" step from the Activity Monitor. 

Here is the JSON output:

`{
    "authorization": {
        "action": "Microsoft.Web/sites/sourcecontrols/write",
        "scope": "/subscriptions/d4f7a89d-5e2c-40a7-97cb-19c9849d2950/resourceGroups/quihn-nids-archive/providers/Microsoft.Web/sites/quihn-nids-archive/sourcecontrols/web"
    },
    "caller": "manaf.ibrahim@adit.net.au",
    "channels": "Operation",
    "claims": {
        "aud": "https://management.core.windows.net/",
        "iss": "https://sts.windows.net/63b3d605-e10d-4fa0-9548-663e303a6262/",
        "iat": "1587345010",
        "nbf": "1587345010",
        "exp": "1587348910",
        "http://schemas.microsoft.com/claims/authnclassreference": "1",
        "aio": "AWQAm/8PAAAA3YBtBUZc6z2eQlQNNNBLEZtElqx5fHZbZIfQWn0mB5KEiEmig7W55dFO79N1sUJhbgI5Rz99kM1mS5uNNYx6VzojvQHkRJB3MfZT0e8fzzwfndsU5PyKIOA6Faxbhm/c",
        "altsecid": "5::1003BFFDA3E83CEE",
        "appid": "c44b4083-3bb0-49c1-b47d-974e53cbdf3c",
        "appidacr": "2",
        "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress": "manaf.ibrahim@adit.net.au",
        "groups": "e0b6008b-f657-4bb4-a34c-897f32d85ee5,71e5d0ca-63ab-4226-9f13-5bcb347a2214,8473c685-6dd9-45e2-8a30-ec83bdc50112,a49cbf27-8b37-4353-a453-5a4adf1652af,6bc58c06-b2d7-464b-b9b1-d30508bff24e",
        "http://schemas.microsoft.com/identity/claims/identityprovider": "https://sts.windows.net/a7c63dc8-725d-49f4-bf7c-23fbc0171bba/",
        "ipaddr": "110.175.173.46",
        "name": "Manaf Ibrahim",
        "http://schemas.microsoft.com/identity/claims/objectidentifier": "e41714f2-5193-42dd-8014-741b90fba77e",
        "puid": "10033FFFAF2AB1B8",
        "http://schemas.microsoft.com/identity/claims/scope": "user_impersonation",
        "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier": "uXIoJI5r9M0giiHLQs9r9HHxa8sh6YYwzAGcGEuADBc",
        "http://schemas.microsoft.com/identity/claims/tenantid": "63b3d605-e10d-4fa0-9548-663e303a6262",
        "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name": "manaf.ibrahim@adit.net.au",
        "uti": "IztDTML4JUOiKWpvVUI6AA",
        "ver": "1.0",
        "wids": "62e90394-69f5-4237-9190-012177145e10,cf1c38e5-3621-4004-a7cb-879624dced7c,9b895d92-2cd3-44c7-9d02-a6ac2d5ea5c3,194ae4cb-b126-40b2-bd5b-6091b380977d"
    },
    "correlationId": "2b7d1dec-2c96-46bf-8d6c-87be4f93d10a",
    "description": "",
    "eventDataId": "e7d2f60a-1c1c-4a55-9027-f0f8d953148b",
    "eventName": {
        "value": "BeginRequest",
        "localizedValue": "Begin request"
    },
    "category": {
        "value": "Administrative",
        "localizedValue": "Administrative"
    },
    "eventTimestamp": "2020-04-20T01:26:48.9934125Z",
    "id": "/subscriptions/d4f7a89d-5e2c-40a7-97cb-19c9849d2950/resourceGroups/quihn-nids-archive/providers/Microsoft.Web/sites/quihn-nids-archive/sourcecontrols/web/events/e7d2f60a-1c1c-4a55-9027-f0f8d953148b/ticks/637229428089934125",
    "level": "Informational",
    "operationId": "2b7d1dec-2c96-46bf-8d6c-87be4f93d10a",
    "operationName": {
        "value": "Microsoft.Web/sites/sourcecontrols/write",
        "localizedValue": "Update Web App Source Control Configuration"
    },
    "resourceGroupName": "quihn-nids-archive",
    "resourceProviderName": {
        "value": "Microsoft.Web",
        "localizedValue": "Azure Web Sites"
    },
    "resourceType": {
        "value": "Microsoft.Web/sites/sourcecontrols",
        "localizedValue": "Microsoft.Web/sites/sourcecontrols"
    },
    "resourceId": "/subscriptions/d4f7a89d-5e2c-40a7-97cb-19c9849d2950/resourceGroups/quihn-nids-archive/providers/Microsoft.Web/sites/quihn-nids-archive/sourcecontrols/web",
    "status": {
        "value": "Started",
        "localizedValue": "Started"
    },
    "subStatus": {
        "value": "",
        "localizedValue": ""
    },
    "submissionTimestamp": "2020-04-20T01:27:32.1774847Z",
    "subscriptionId": "d4f7a89d-5e2c-40a7-97cb-19c9849d2950",
    "tenantId": "63b3d605-e10d-4fa0-9548-663e303a6262",
    "relatedEvents": []
}`

**Comment by suwatch** [comment]
Did you use Azure Portal to set this up?

**Comment by Manaf-Ibrahim** [comment]
Thanks @suwatch,

Yes I did - I have actually just resolved the issue by disconnecting the repo and resetting the publish profile. Everything seems to be working as required so I will close off this issue.
