### ISSUE TITLE
Can't find the /instance/all route

### ISSUE THREAD

**Issue by pvginkel** [projectkudu/kudu#3145]
### Repro steps.

* Call `/instance/all` on Azure. This returns a JSON array of instance ID's;
* Call `/instance/all` on a local Kudu instance. This returns `"No route registered for '/instance/all'"`.

### The log/error given by the failure.

`"No route registered for '/instance/all'"`

### Mention any other details that might be useful.

Would it be possible to point to the code in the Kudu GitHub project where this route is implemented and how I can test this locally?

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service

**Comment by daiplusplus** [comment]
@jvano Why did you close this issue?

**Comment by jvano** [comment]
This project is deprecated and soon it will be archived, so this repo will no longer be maintained.

Kudu will continue in Azure App Service. That's why we are recommending filing issues directly as Azure support incidents.
