### ISSUE TITLE
500 error on git deploy with inaccessible storage

### ISSUE THREAD

**Issue by jeffhollan** [projectkudu/kudu#3148]
Customer reported that when trying to do a git deploy to a function app that had a storage account with a firewall enabled they got the following

> fatal: unable to access 'https://<name>.scm.azurewebsites.net/<name>.git/': The requested URL returned error: 500
##[error]Process completed with exit code 128.

Ideally we wouldn’t throw a 500, but also would be able to return a helpful error message like “Storage account was inaccessible.”

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
