### ISSUE TITLE
Provide configurable timeout knob for outgoing HttpRequest from Kudu to 3rd party

### ISSUE THREAD

**Issue by suwatch** [projectkudu/kudu#3150]

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
