### ISSUE TITLE
zip deployment fails, does not execute pip install

### ISSUE THREAD

**Issue by mtin** [projectkudu/kudu#3151]
**tl/dr:** I am unable to deploy a **python flask web app** with a **custom startup-command/main module name**

If I change my project an rename the main module to app.py I can successfully deploy via
```
az webapp up --plan $appServicePlanName --name $app_name --resource-group $resourceGroupName
```
but I want to specify a manual startup-file command since my main module is called 'web_app' instead of app 🙄 so I tried to perform the steps manually which results in the webapp failing on required modules, apparently `pip install -r requirements` does not run, see the comments in the code for what I tried to get it to 'build'
```bash
az webapp create --plan $appServicePlanName --name $app_name --resource-group $resourceGroupName --runtime $runtime
# tried this: az webapp config appsettings set --resource-group $resourceGroupName --name $app_name --settings ENABLE_ORYX_BUILD=true
# and this: az webapp config appsettings set --resource-group $resourceGroupName --name $app_name --settings SCM_DO_BUILD_DURING_DEPLOYMENT=true
az webapp config set --resource-group $resourceGroupName --name $app_name --startup-file "gunicorn --bind=0.0.0.0 --timeout 600 web_app:app"
az webapp deployment source config-zip --verbose --resource-group $resourceGroupName  --name $app_name  --src $zip_filename
```

```
020-04-28T19:19:07.377221772Z   File "/home/site/wwwroot/web_app.py", line 2, in <module>
2020-04-28T19:19:07.405428732Z     from flask_bootstrap import Bootstrap
2020-04-28T19:19:07.405462033Z ModuleNotFoundError: No module named 'flask_bootstrap'
2020-04-28T19:19:07.405536036Z [2020-04-28 19:19:07 +0000] [40] [INFO] Worker exiting (pid: 40)
2020-04-28T19:19:07.809727128Z [2020-04-28 19:19:07 +0000] [37] [INFO] Shutting down: Master
2020-04-28T19:19:07.810127643Z [2020-04-28 19:19:07 +0000] [37] [INFO] Reason: Worker failed to boot.
```

**Comment by sanchitmehta** [comment]
@mtin Could you paster your deployment logs here ?

**Comment by mtin** [comment]
Thanks for still replying; I resorted to just renaming my app to be able to simply use `az webapp up`; I do not have the deployment logs anymore and also do not have the need to get the deployment with the specific startup file working anymore!

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
