### ISSUE TITLE
Console "dir" command file "modified" timestamp does not match file list

### ISSUE THREAD

**Issue by mwittmann** [projectkudu/kudu#3154]
In the Kudu debug console, if you run the "dir" command at the CMD prompt, you'll see that the file "modified" date/time timestamp does not match what's displayed in the file list above the command prompt. The file list at the top of the page appears to use the local timezone, while the CMD prompt appears to list the UTC timestamp. I don't know if this is intended as a feature, but it's a bit confusing.

**Comment by skylaro** [comment]
Issue still occurring. Kudu console displays both UTC and localtime timestamps for a .NET 5.0 app deployed via Github Actions. Does not seem to exist when using ZipDeploy or FTP. Is this expected behavior? If not, may we prioritize this issue? Thanks so much.

Skylar

**Comment by suwatch** [comment]
This is somewhat the behavior since day one.  For the UI - we displayed local.  For the command prompt, it is just a shell and we stdin/out from cmd running on the VM (which happens to return UTC).  We neither have plan nor resource to address it at the moment.

**Comment by skylaro** [comment]
Thanks @suwatch for clarifying. So it is expected that the shell return some modified files in UTC and some in local time? Other methods such as zip deploy are not this way.

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
