### ISSUE TITLE
CMD Debug Console filename completion malfunctions for "..\" path

### ISSUE THREAD

**Issue by mwittmann** [projectkudu/kudu#3155]
I noticed the following issue with Debug Console CMD prompt filename completion. If you are in a subfolder and type "DIR ..\file" and press the _{Tab}_ key for filename completion, the filename is completed, but the "..\\" prefix is stripped off. As a result, the "completed" filename is actually invalid.

Example:

  D:\home\site\wwwroot> **DIR ..**
   Volume in drive D is Windows
   Volume Serial Number is EA8C-FC9E

   Directory of D:\home\site

  04/27/2020  09:06 PM    <DIR>          .
  04/27/2020  09:06 PM    <DIR>          ..
  04/27/2020  09:04 PM    <DIR>          deployments
  04/27/2020  09:05 PM    <DIR>          jobs
  05/02/2020  05:12 PM    <DIR>          locks
  04/27/2020  09:06 PM    <DIR>          repository
  04/27/2020  09:05 PM    <DIR>          siteextensions
  05/02/2020  06:10 AM    <DIR>          wwwroot
               0 File(s)         24,576 bytes
               8 Dir(s)  52,388,593,664 bytes free

  D:\home\site\wwwroot> **DIR ..\site**⇐{Press tab key}

produces

  D:\home\site\wwwroot> **DIR siteextensions**

Note that the leading "..\\" has been removed.

**Comment by suwatch** [comment]
This is the current limitation since day-one.  The completion is implemented on the client side and only supports current directory.

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
