### ISSUE TITLE
Add a way to choose the version of a site extension to install

### ISSUE THREAD

**Issue by BrennanConroy** [projectkudu/kudu#3156]
Or at least don't consider preview versions by default.

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
