### ISSUE TITLE
Azure Site Extension xdt transform order.

### ISSUE THREAD

**Issue by shurivich** [projectkudu/kudu#3157]
I have my own Azure App Service Site Extension, which has an xdt transform that conflicts with another 3rd-party Site Extension. Is there any way to determine the order in which xdt transforms are applied, and can I control the order?

**Comment by suwatch** [comment]
It is the directory order (Directory.GetDirectories).   Best is to avoid conflict in the first place if possible.

**Comment by shurivich** [comment]
Great!
