### ISSUE TITLE
Dump Memory before disable the worker by health probe feature

### ISSUE THREAD

**Issue by CShen-101-solution** [projectkudu/kudu#3158]
As I learnt from support team, when the worker is disabled by health check, there is no way we can access it through kudo UI. So, could the memory been dumped before disable or we can still access the worker after it is disabled?

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
