### ISSUE TITLE
custom RBAC role assignment

### ISSUE THREAD

**Issue by SI-BenHodges** [projectkudu/kudu#3160]
Hi,

I am an azure administrator and i want to give some developers access to the editor but explicitely only to the editor and nothing else.. I.E no permisions to start/stop the app service for example.

I have been trying to create a custom role to fulfil this since azure have not created one but i am having troubles figuring out how to limit the role to only be able to access the editor.

please help!

this is my current JSON which i've added exclusions to and is giving full access to the app:

{
    "properties": {
        "roleName": "",
        "description": "",
        "assignableScopes": [
            "/subscriptions/41fb0611-5ff7-4627-8e6b-6935a3b56829/resourceGroups/red-prod-portals-rg"
        ],
        "permissions": [
            {
                "actions": [
                    "*",
                    "microsoft.web/serverfarms/hybridconnectionplanlimits/read",
                    "microsoft.web/serverfarms/hybridconnectionnamespaces/relays/sites/read",
                    "microsoft.web/serverfarms/hybridconnectionnamespaces/relays/read",
                    "microsoft.web/serverfarms/firstpartyapps/settings/read",
                    "microsoft.web/serverfarms/capabilities/read",
                    "Microsoft.Web/serverfarms/Read",
                    "microsoft.web/hostingenvironments/serverfarms/read",
                    "microsoft.web/serverfarms/virtualnetworkconnections/routes/read",
                    "microsoft.web/serverfarms/virtualnetworkconnections/read",
                    "microsoft.web/serverfarms/usages/read",
                    "microsoft.web/serverfarms/skus/read",
                    "microsoft.web/serverfarms/sites/read",
                    "microsoft.web/serverfarms/operationresults/read",
                    "microsoft.web/serverfarms/metrics/read",
                    "microsoft.web/serverfarms/metricdefinitions/read",
                    "microsoft.web/serverfarms/hybridconnectionrelays/read"
                ],
                "notActions": [
                    "Microsoft.Authorization/elevateAccess/Action",
                    "Microsoft.Blueprint/blueprintAssignments/write",
                    "Microsoft.Blueprint/blueprintAssignments/delete",
                    "microsoft.web/serverfarms/virtualnetworkconnections/gateways/write",
                    "Microsoft.Web/hostingEnvironments/Delete",
                    "Microsoft.Web/hostingEnvironments/Join/Action",
                    "Microsoft.Web/hostingEnvironments/reboot/Action",
                    "Microsoft.Web/hostingEnvironments/multiRolePools/Write",
                    "Microsoft.Web/hostingEnvironments/workerPools/Write",
                    "Microsoft.Web/serverfarms/Write",
                    "microsoft.web/serverfarms/virtualnetworkconnections/routes/delete",
                    "microsoft.web/serverfarms/hybridconnectionnamespaces/relays/delete",
                    "microsoft.web/serverfarms/firstpartyapps/settings/delete",
                    "Microsoft.Web/serverfarms/Delete",
                    "Microsoft.Web/serverfarms/restartSites/Action",
                    "microsoft.web/serverfarms/firstpartyapps/settings/write",
                    "microsoft.web/serverfarms/virtualnetworkconnections/routes/write",
                    "microsoft.web/serverfarms/workers/reboot/action"
                ],
                "dataActions": [],
                "notDataActions": []
            }
        ]
    }
}

**Comment by suwatch** [comment]
Please expand on "editor".  Do you mean https://site.scm.azurewebsites.net/dev.    If so, you need contributor for the site or at least **microsoft.web/sites/publish/action**.

**Comment by SI-BenHodges** [comment]
yes that's the one! i have played around with custom rules and only seem to get all or nothing.

Please advise how i can limit the user so they can only access and make changes to the azure app service editor and everything else is greyed out or gives them an access denied error.

**Comment by SI-BenHodges** [comment]
anyone have any clue if this is possible and if so could you share a JSON template please.

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
