### ISSUE TITLE
Webjobs API - Start/Stop a continuous job operations not working - no route registered

### ISSUE THREAD

**Issue by LucasReehorst** [projectkudu/kudu#3161]
### Repro steps.
I'm trying to use the HTTP operations documented here: https://github.com/projectkudu/kudu/wiki/WebJobs-API

When I call GET operations like /api/continuouswebjobs or /api/continuouswebjobs/{job name} I get the desired response. 

But when I try to call the POST operations: 
- POST /api/continuouswebjobs/{job name}/start
- POST /api/continuouswebjobs/{job name}/stop

I get the response: 
- "No route registered for '/api/continuouswebjobs/{job name}/stop'"

I notice the stop/start functionality also seems to have disappeared from the GUI.
Do these operations still exist?

**Comment by suwatch** [comment]
do you happen to use run-from-package?  if so, it is a known limitation.

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
