### ISSUE TITLE
Support heuristic file to indicate latest deployment event

### ISSUE THREAD

**Issue by suwatch** [projectkudu/kudu#3162]
In App Service, this will be consumed by other deployment management providing added values such as eventing, portal ui, ...   In addition, common codes are also for different deployment mechanism.

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
