### ISSUE TITLE
I cant find the User Credentials mentioned in the Deployment Credentials WIki page on the Azure App Service UI pages.

### ISSUE THREAD

**Issue by StingyJack** [projectkudu/kudu#3167]
https://github.com/projectkudu/kudu/wiki/Deployment-credentials#user-credentials-aka-deployment-credentials

> going to the Dashboard tab for any site and clicking 'Reset deployment credentials' (under quick glance).

I dont see "Quick Glance" or anything like "Reset deployment credentials" except "Reset Publish Profile", but per this wiki page, that is not what I want to use. 
![image](https://user-images.githubusercontent.com/15381181/82759334-d6b6bf00-9dba-11ea-8731-3dbecab92edd.png)

Can someone share a screenshot of where I can find this ?

**Comment by suwatch** [comment]
Apology for stale info on wiki.   We just updated it with the right instruction.

**Comment by StingyJack** [comment]
Thanks, from that I was able to locate [this page]( https://docs.microsoft.com/en-us/azure/app-service/deploy-configure-credentials).  Maybe a good idea to link to it from the wiki.
