### ISSUE TITLE
Health Checks on app services with custom domain

### ISSUE THREAD

**Issue by mk-fluency** [projectkudu/kudu#3168]
We have an app service running asp.net core using on a custom domain.
We've added the health check url to our asp.net core app and added the relevant settings to the config json. The health check metric shows 0 instances healthy though they're running fine.

When looking into the log stream I can see kudu trying to check the health but our apps responds with a 307. Is this due to the custom domain? This not in the healthy range of the health checks and I'm guessing that this is why it fails.

Is this a likely reason and how do we handle the redirect in this case to get correct state to kudu?

**Comment by suwatch** [comment]
See https://github.com/projectkudu/kudu/wiki/Health-Check-%28Preview%29#the-health-check-path.   The healthcheck needs to allow **http** and **anonymous** access.

**Comment by mk-fluency** [comment]
Ok, at least I understand now but why does it not support https?

**Comment by suwatch** [comment]
It will be supported by end of June 2020.
