### ISSUE TITLE
[Linux] ZIP Deploy fails - "Could not find a part of the path" for deployment log files

### ISSUE THREAD

**Issue by alexpilon666** [projectkudu/kudu#3169]
We're having some issues doing a .NET Core/NodeJS/VueJS app deployment in a Linux App Service via Azure DevOps, but only once in a while, for no apparent reason.

We use Azure DevOps to both build and release our application to Azure, and sometimes we'll deploy, it won't work, we will re-deploy the exact same release, using the same artifact, config, etc., and it'll work just fine.

I took the time this morning to extract logs and file a bug because this is getting somewhat annoying/problematic on our end.

See below info for details and error logs. Thanks!

### Repro steps.
- Build the frontend (using various NPM commands) and generate an artifact in ADO
- Get the artifact, run a NuGet Restore & `dotnet publish` on the project
- ZIP the package up, and deploy it to a Linux App Service
It either works...or doesn't.

### Project structures.
Cannot link project Repo, as it is a private repository.

### The log/error given by the failure.
One of the errors in the log: 
```
<step title="Error occurred" date="2020-06-04T13:52:44.294" type="error" text="Log() at /tmp/KuduLite/Kudu.Core/Deployment/StructuredTextLogger.cs:66: Could not find a part of the path '/home/site/deployments/340996a009044dd7a3d2a24b54c8dc32/log.log'." stackTrace=" at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter) at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode) at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options) at System.IO.Abstractions.FileWrapper.Open(String path, FileMode mode, FileAccess access, FileShare share) at Kudu.Core.Infrastructure.FileSystemHelpers.AppendAllTextToFile(String path, String content) in /tmp/KuduLite/Kudu.Core/Infrastructure/FileSystemHelpers.cs:line 200 at Kudu.Core.Deployment.StructuredTextDocument`1.Write(T value, Int32 depth) in /tmp/KuduLite/Kudu.Core/Deployment/StructuredTextDocument.cs:line 43 at Kudu.Core.Deployment.StructuredTextLogger.Log(String value, LogEntryType type) in /tmp/KuduLite/Kudu.Core/Deployment/StructuredTextLogger.cs:line 67"/>
<!--  duration: 38ms  -->
```
Full log file can be viewed here: https://pastebin.com/Y2kPp5DB
Log is taken from the `Background_POST_api-zipdeploy.xml` log file

### Debug your Azure website remotely.
App name isn't relevant to the issue, and cannot be accessed remotely (locked down via IP restrictions and custom internal DNS)

**Comment by sanchitmehta** [comment]
@alexpilon666 Kudu creates multiple file based logs during the deployment process to ensure that the deployment steps are atomic including writing the log of the deployment. We have identified a race condition at our end with one of these locks files and we are working to fix this with the next platform release.

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
