### ISSUE TITLE
'WEBSITE_RUN_FROM_PACKAGE' is not always hououred by the /zipdeploy API

### ISSUE THREAD

**Issue by dgard1981** [projectkudu/kudu#3171]
Deploying via the `/zipdeploy` API with App Setting `WEBSITE_RUN_FROM_PACKAGE` = `1` doesn't always result in deployment of a zip file to `\data\SitePackages`. Instead, on occasion the contents of the zip file are extracted to `\site\wwwroot`. This leads to one of two scenarios -

1. In cases where a previous deployment exists in `\data\SitePackages`, the Function App continues to use the package referenced in `packagename.txt`.
2. In cases where no previous deployment exists in `\data\SitePackages`, the Fucntion App is unable to find any functions because the existence of `WEBSITE_RUN_FROM_PACKAGE` prevents it for finding/running extracted functions in `\data\SitePackages`.

This issue is intermitant and around 50% of the time succeeds as expected. This tells me that the zip file is not corrupt.

The Kudu logs show that the deployment does not detect "project type: Run-From-Zip". I'm happy to share the relevant logs privately if required.

**Comment by dgard1981** [comment]
I've been looking at the trace logs in Kudu to compare them for deployments where `WEBSITE_RUN_FROM_PACKAGE` is honoured vs when it is not.

In cases were `WEBSITE_RUN_FROM_PACKAGE` is honoured, there seems to be four trace logs for a deployment -

1. 2020-06-18T08-34-35_7f74b1_001_Startup_GET_api-settings_0s.xml
2. 2020-06-18T08-34-36_7f74b1_002_GET_api-settings_200_1s.xml
3. 2020-06-18T08-34-36_7f74b1_003_POST_api-zipdeploy_200_8s.xml
4. 2020-06-18T08-34-51_7f74b1_004_Shutdown_0s.xml

However, in cases where `WEBSITE_RUN_FROM_PACKAGE` is not being honoured, there are only three trace logs for a deployment -

1. 2020-06-22T10-19-39_b80479_001_Startup_POST_api-zipdeploy_0s.xml
2. 2020-06-22T10-19-39_b80479_002_POST_api-zipdeploy_200_11s.xml
3. 2020-06-22T10-19-52_b80479_003_Shutdown_0s.xml

It seems that on some occasions (in some cases for every deployment to a Function App / slot) the deployment to the `/zipdelpy` API does not result settings being checked to see whether or the `WEBSITE_RUN_FROM_PACKAGE` exists.

I'm unsure of exactly how the Kudu API's work, hopefully someone from the project will be able to give me a little more insight?

Again I'd be happy to share the relevant logs / traces privately.

**Comment by jujinfu** [comment]
I have the same issue. 

I deploy 3 Function Apps using RunFromPackage. Yet two of them are updated properly. But the thrid one just did not update at all. 

The first two will show deploy using runFromPackage.

The thrid one is trying to copy the zip content into wwwroot. Which will not work because it's read-only. Eventually causing the app binary is not update. If you look at data/SitePackages, the new package is not there. 

All this is just an example, we have this behavior happening randomly. At beginning I thought this was related to me stopping the Slot. But turns out it was not. 

This is causing our production app deployment pipeline not stable. We need to fix this asap

**Comment by dgard1981** [comment]
Since it seems that no one monitors these issues, I also opened a support ticket with Microsoft. The agent contacted me this morning to say that "The platform was recently updated". So far today everything has been OK.

I still have the support ticket open, and I will update this issue with any further pertinent information.

**Comment by suwatch** [comment]
When you said you set WEBSITE_RUN_FROM_PACKAGE = 1, did you set it once and never change it as well as across all slots? 
What client tool are you using to deploy? VSTS or CLI or other?

> The thrid one is trying to copy the zip content into wwwroot. Which will not work because it's read-only. Eventually causing the app binary is not update. If you look at data/SitePackages, the new package is not there.

For above, share the site name (here or [indirectly](https://github.com/projectkudu/kudu/wiki/Reporting-your-site-name-without-posting-it-publicly)) and UTC time of the incident.

**Comment by dgard1981** [comment]
@suwatch - I set 'WEBSITE_RUN_FROM_PACKAGE = 1' in both production and our Staging slot prior to code deployment.

I'm using Azure DevOps to deploy, and as part of the 'AzureFunctionApp@1' deployment task, 'WEBSITE_RUN_FROM_PACKAGE = 1' is also set there.

**Comment by suwatch** [comment]
> The thrid one is trying to copy the zip content into wwwroot. Which will not work because it's read-only. Eventually causing the app binary is not update. If you look at data/SitePackages, the new package is not there.

For above, share the site name (here or indirectly) and UTC time of the incident.

**Comment by sanchitmehta** [comment]
@dgard1981 at times it can take a few seconds for the App Setting to be propagated to the Kudu process/container. This can cause Kudu to carry out the deployment assuming the app setting is not set(ie a normal Zip Deploy Deployment). Are you creating a new app/slot using the devops pipeline - if yes, could you try adding a wait after setting the App Settings ?

**Comment by dgard1981** [comment]
@sanchitmehta - I eventually found the answer to this. It seems that Function Apps and slots are assigned a host ID, but that the value of that host ID is truncated to 32 characters. So because our Function App name was longer than 32 characters we were seeing collisions. I must confess I don't fully understand how this fixed the issue, but manually setting `AzureFunctionsWebHost:hostID` to a unique value for production and our slot seems to have worked.
