### ISSUE TITLE
Health Check Path setting appears to be slot specific

### ISSUE THREAD

**Issue by ThomasManson** [projectkudu/kudu#3173]
> For deployment issues, please provide us with the following information:
> ---------------------------------------------------------------

### Repro steps.
On a App Service with multiple slots, use Resource Explorer to set the healthCheckPath to a path such as /heathcheck/1. 
Swap the slots
Check the value in Resource Explorer - the healthCheckPath is empty. Set it to a different path, such as /healthcheck/2.
Swap again
Path goes back to /healthcheck/1

Expected:
Either the setting is sticky to the Production slot, or there needs to be a way to set it for all the slots without having to swap to that slot first.

**Comment by suwatch** [comment]
It is the current limitation.  We will improve it (ETA early Aug 2020).   For the time being, you might have to set them all to ensure the PROD slot has healthcheckpath regardless of swap.

**Comment by simonethreechillies** [comment]
@suwatch The setting is still slot specific even now that we're in mid-september. Today we've lost all these settings after performing a slot swap and only found out what happened after spending time investigating the issue. 
Please update the documentation in the meantime, as other customers might be impacted by this aspect of the feature.

Simone

**Comment by shubDhond** [comment]
Hi @ThomasManson  and @simonethreechillies, I am the primary developer for deployment slots and wanted to confirm some things so we can investigate. It seems you are both reporting conflicting behaviour. 

@ThomasManson just to confirm you are seeing that the setting is not remaining sticky to the slot and is being swapped?

@simonethreechillies just to confirm you are reporting that the setting is slot sticky and is NOT being swapped?

If you could both provide you app names and an approximate time period for the last time you observed this behaviour I'll be happy to take a look.

**Comment by ThomasManson** [comment]
@shubDhond The behaviour I see is that the setting is sticky to a slot. When you swap the slot, the setting does not swap with it.

**Comment by shubDhond** [comment]
Hi @ThomasManson , can you please provide your app name when you get a chance? Also please provide an approximate timeframe when you performed your last swap.

**Comment by simonethreechillies** [comment]
@shubDhond  Let me clarify. The setting was enabled on the Production slot and not on the other slot, which we named Staging. After we've deployed to the Staging slot, we swapped Staging with Production. Once the swap completed I could see the setting was no longer on the Production slot, but rather on the Passive slot.

Hope this helps, any questions let me know.

Simone

**Comment by shubDhond** [comment]
Hi @simonethreechillies,
What you are reporting is actually expected behaviour. Since your healthcheck path is dependent on the content deployed to your sites, it does not remain slot sticky and moves with the content. My Microsoft email is shdhond@microsoft.com if you'd like to follow up there.

**Comment by ThomasManson** [comment]
@shubDhond I was working on this for a customer, and don't have access anymore to their environment, so can't give you the app name.

Regarding the expected behaviour: it would be good if there was a way to set the path without having to swap to a slot first. It would also be good if you could read the value for all slots, without having to swap to a slot first.

**Comment by simonethreechillies** [comment]
Fair enough if that's by design, but can you please reflect the behaviour in the documentation? Last time I've checked it was not mentioned and this has caught has by surprise when we deployed

**Comment by gallivantor** [comment]
Agreed, we were also caught out by this behaviour (we had assumed it would stick to the slot, and not swap).
Also, when we created a new deployment slot and told it to copy the config from the main production slot, it didn't seem to copy the health check settings, so the new slot ended up with the health checks disabled?

**Comment by swatisahay** [comment]
@shubDhond healthCheckPath  is still slot specific? I had added health check path in staging slot and expected it will get copied to production slot when swap happens, but it did not got copied. Do I need to specify healthcheckpath in both the slots?

**Comment by malopgrics** [comment]
@shubDhond is there any chance this ticket will be addressed ? The actual behavior is at confusing and, in our case, prevent us from automating this configuration.

**Comment by ms-kgorgi** [comment]
@shubDhond we are observing the reported behavior where our staging slot has health check config but our production slot does not. When we perform swapslot the health check config is not propogated to the production slot.

**Comment by kamilzzz** [comment]
@JiriKovar did you find any workaround?
I face the same issue where i would like slots to be working only during deployment phase so they doesn't consume any resources later on after swap is performed.

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
