### ISSUE TITLE
Kudu RunFromPackage Deploy will not update app binary. And no error given

### ISSUE THREAD

**Issue by jujinfu** [projectkudu/kudu#3174]
This issue is random. 

One time we run our deploy pipeline, it will not update the binary, run it again and it will work. 

We are using Azure Functions task to deploy.
We push a zip file to App service, and use RunFromPackage as a deploy method. 

So far we have seen a couple of cases that the deploy will not respect RunFromPackage method.

**Comment by suwatch** [comment]
Hard to investigate without UTC time, site name etc.

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
