### ISSUE TITLE
Please document the EnvSettings module and its environment variables

### ISSUE THREAD

**Issue by daiplusplus** [projectkudu/kudu#3175]
(My apologies if this isn't a Kudu issue - I assume it was because the effects of `EnvSettings` are affected by Kudu - and the team behind Azure App Services are intertwined with the team behind Kudu (I think?))

I've been hunting down an issue with an ASP.NET 4.7 web-application running in an Azure App Service where it would completely ignore its custom Configuration Settings that were set in the website's Configuration blade in the Azure Portal and instead only using values set in its `web.config` file.

After some digging, poking, and disassembly I found out that the Azure App Service's machine-wide `web.config` instructs the ASP.NET runtime to add a reference to `EnvSettings.dll` which has an `IHttpModule` that's always meant to be added to the ASP.NET pipeline using `[assembly: PreApplicationStartMethod(typeof(SettingsProcessor), "Start")]` - that's not cool, Microsoft :(

I noticed that the `EnvSettings` module sets some environment variables like `WEBSITE_CONFIGURATION_READY` and copies Environment Variables with these prefixes (`MYSQLCONNSTR_`, `SQLAZURECONNSTR_`, `CUSTOMCONNSTR_`, `APPSETTING_`, and `MACHINEKEY_`) into the current AppDomain's in-memory static `ConfigurationManager.ConnectionStrings` and `ConfigurationManager.AppSettings` collections.

Other than those prefixed environment-variables, **this isn't documented anywhere at all!** - which is surprising because you'd think after the Trustworthy Computing initiative (which killed off all the amazing easter-eggs in MS Office) that anything Microsoft does that overwrites `AppSettings` or adds itself into my web-application instance should be very-well documented! Especially as I was never asked for consent for a binary that I didn't know about to be added to my process and alter my process'  in-memory state (I thought the Configuration / Application Settings feature worked by adding a configuration provider or using something like XDT - not by manipulating `ConfigurationManager` in-memory).

Also, I don't feel comfortable with sensitive information like connection-strings (which contain passwords! because we can't use Windows Authentication between Azure App Services and Azure SQL) being exposed to applications in plaintext Environment Variables because it's easy for unintentional data disclosure: I never thought that I should keep environment-variables as secure as my connection-string passwords (I'll admit that I haven't used Azure's Vault feature yet, so I don't know how it works). This is a huge problem for PHP websites that have a publicly-exposed `<?php phpinfo(); ?>` page because that will list environment variables for everyone to see (and I use `phpinfo();` a lot when I'm troubleshooting issues with PHP and normally they don't contain any sensitive information so I just leave the files behind in case I need them later).

Anyway, my original issue with my site turned out to be caused by a recent change where the website's `web.config` was altered to add a `<clear />` to `<system.web> <compilation> <assemblies>` because this removed the inherited (non-default!) `<add assembly="EnvSettings" />` in the machine-wide `web.config` file. I had no idea that `<clear />` to runtime ASP.NET compilation would break the site's configuration, which is a completely unrelated part of .NET.

Finally, I noticed that `EnvSettings` sets the `WEBSITE_CONFIGURATION_READY` environment variable to `1`. Why does it do this and what effect does this have on our websites? I couldn't find any documentation about this anywhere online.

So I'm requesting the following:

- [ ] Make `EnvSettings` part of the open-source part of Kudu so it benefits from the "many eyes" advantages of open-source. I couldn't see anything proprietary of worthy of being kept-secret in `EnvSettings` when I disassembled it.
- [ ] Update the Azure Portal > App Service > Configuration blade to add black-box warning informing us that connection-strings and app-settings defined in the Portal will be exposed as name-prefixed environment-variables which may be exposed to the rest of the Internet if there are any pages that list environment-variables, such as those using `phpinfo()`.
    - The notice should also mention that those environment-variables are added to `ConfigurationManager` using a specific `IHttpModule` and a link to a page that describes what `EnvSettings` is and how it works - and how to opt-in/opt-out of using it.
    - [ ] Add a Checkbox to allow us to opt-out / opt-in to having `EnvSettings.dll` loaded into our applications, or at least instructions on how to manually add or remove the entry from `<compilation><assemblies>`.
- [ ] Document what `WEBSITE_CONFIGURATION_READY` does.

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service

**Comment by daiplusplus** [comment]
@jvano This is a Kudu feature request and has nothing to do with Azure...
