### ISSUE TITLE
Change guidance for "MaxJobLogLinesReached"

### ISSUE THREAD

**Issue by mhoeger** [projectkudu/kudu#3179]
https://github.com/projectkudu/kudu/blob/f022e99984d9deb1357c0a374d92bd341b6e9c28/Kudu.Core/Resources.resx#L220

This recommendation refers to enabling old Diagnostic settings feature which is now App Service Logs option in the Portal. https://docs.microsoft.com/en-us/azure/app-service/troubleshoot-diagnostic-logs

**Comment by suwatch** [comment]
Commit: https://github.com/projectkudu/kudu/commit/8b0d45a3bac7d7706a00bbfa7204e0d0c3c75c4a
