### ISSUE TITLE
Health Check - Should pass Host Header

### ISSUE THREAD

**Issue by Poil** [projectkudu/kudu#3184]
Hi,

Actually the health probe check does not pass a Header Host, I think it should pass by default the defined URL Host configuration of the App Service.

This is usefull when using an Apache HTTPd/Nginx server with a default catchall virtualhost (and a or more usefull one)

Best regards

**Comment by suwatch** [comment]
@sanchitmehta  could you help look into this?

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
