### ISSUE TITLE
Custom Deployment Script for Linux Container

### ISSUE THREAD

**Issue by mfxuus** [projectkudu/kudu#3187]
Quick Question: I'm trying to deploy a Django app to Azure Web App running on Linux / Python 3.7. I'm trying to customize the deployment script, and I've tried following 
1. [Easily downloading your current deployment script](https://github.com/projectkudu/kudu/wiki/Custom-Deployment-Script#easily-downloading-your-current-deployment-script), and 

2. [Custom Deployment Script Generator](https://github.com/projectkudu/kudu/wiki/Custom-Deployment-Script#custom-deployment-script-generator)"

But neither seemed to work.. For 1, there's no Tools Menu for me, and for 2, there were errors thrown for the default `deploy.cmd`. I think these two methods might both be aimed towards Windows containers? Is there a way to get my hands on the auto-generated deployment script for Linux containers so I can modify it slightly? Thanks!

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
