### ISSUE TITLE
Unable to Deploy Web Job to Staging Slot

### ISSUE THREAD

**Issue by blueelvis** [projectkudu/kudu#3190]
### Repro steps.
1. Create a Dot Net Core Web Job project.
2. Create a Web App with a Staging slot.
3. Use the KUDU REST API to deploy the Web Job to the staging slot.
4. You will receive -
```
<body bgcolor="#00abec">
	<div id="feature">
		<div id="content">
			<h1 id="unavailable">Error 403 - This web app is stopped.</h1>
			<p id="tryAgain">The web app you have attempted to reach is currently stopped and does not accept any
				requests. Please try to reload the page or visit it again soon.</p>
			<p id="toAdmin">If you are the web app administrator, please find the common 403 error scenarios and
				resolution <a href="https://go.microsoft.com/fwlink/?linkid=2095007" target="_blank">here</a>. For
				further troubleshooting tools and recommendations, please visit <a
					href="https://portal.azure.com/">Azure Portal</a>.</p>
		</div>
	</div>
</body>
```

I have the following headers set in Postman -
```
Authorization:Basic --redacted--
Content-Disposition:attachment; filename=Core.zip
Origin:https://localhost
Referer:https://localhost
Content-Type:application/zip
```

When I tried deploying the Web Job to the production slot, it deployed correctly without any issues. Could you please look into this?

Thanks,
Pranav

**Comment by suwatch** [comment]
I would suggest to do basic test to hit kudu root path to ensure the credential is correct.

**Comment by blueelvis** [comment]
@suwatch - I was not aware that the staging slot has its own set of credentials. This is resolved. Thanks for the reply!
