### ISSUE TITLE
Kudu doesn't run npm build from package.json on deployment for Node based Azure Functions

### ISSUE THREAD

**Issue by sandeeprawat** [projectkudu/kudu#3191]
Looks like NPM build command doesn't run in azure functions when doing automated deployment via Kudu linked to a git repository even when project.json contain build command. It only seems to be running npm install. 

Is this by design and am I suppose to run custom script to do npm build etc

if I publish directly from vscode it works fine (as this publishes the output files as well).

As a user I'm expecting that the app I create via func create as documented [here ](https://docs.microsoft.com/en-us/azure/azure-functions/functions-create-first-azure-function-azure-cli?tabs=bash%2Cbrowser&pivots=programming-language-javascript) to work immediately after pushing the same code to git repo and linking with functions app.

### Repro steps.
Create an Azure Function project and setup Kudu Deployment pipeline to a git repository
Push code to repository. Azure function should run

### Project structures.
[github test repository ](https://github.com/sandeeprawat/testfunc)

### The log/error given by the failure.
This is the error I see in azure portal
![image](https://user-images.githubusercontent.com/520749/88696379-cf949000-d120-11ea-8da3-d0bbc440d2d8.png)

Looking at the wwwroot folder I see that build output is missing which gets generated when npm run build is invoked. Looking at the log files it looks like kudu only runs npm install as part of deployment.

### Debug your Azure website remotely.
>To be shared if required. Issue seems generic enough.

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
