### ISSUE TITLE
git push deployment with NodeJs/NPM project ignores files on sync

### ISSUE THREAD

**Issue by MarioPerezEsteso** [projectkudu/kudu#3197]
When doing a `git push` in order to deploy an application, Kudu doesn't sync some files in `node_modules` because their creation date is always **26th october 1985**. The `git push` is made to the folder `site/repository` and the sync is made to `site/wwwroot`, but as the timestamp of some files in the Node dependencies doesn't change, they are not copied.

### Repro steps.
1.  `git push` to the folder `site/repository`
2. `npm install --production` inside `site/repository`. It installs the dependencies and some of the files have creation date: 26th october 1985.
3. Kudu copies the modified files from `site/repository` to `site/wwwroot`. As Kudu looks for the files that have different timestamp, it doesn't copy some of them even when they have different content.

### The log/error given by the failure.
There aren't errors. Kudu just ignores the files on the sync between `site/repository` and `site/wwwroot`.

### System and versions
- Web Application using Windows.
- Node 12.15.0
- NPM 6.13.4

This issue is similar to [this one](https://github.com/projectkudu/kudu/issues/2917), but doing a git push instead of a ZIP deployment.

Related [npm issue](https://github.com/npm/npm/issues/20439).

**Comment by suwatch** [comment]
Below is the current copying implementation.   Please file gissue to KuduSync.NET to allow CopyAlways option.  You will need to provide [custom deployment](https://github.com/projectkudu/kudu/wiki/Customizing-deployments) as a workaround.

https://github.com/projectkudu/KuduSync.NET/blob/master/KuduSync.NET/KuduSync.cs#L193

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
