### ISSUE TITLE
Fix:  Healthcheck metric may be triggered even if there is no change in the metric's value

### ISSUE THREAD

**Issue by joepperkins** [projectkudu/kudu#3198]
What is the delivery expectations for fixing the issue below.

_There is a known issue where Azure Monitor Alerts for the Healthcheck metric may be triggered even if there is no change in the metric's value. We have identified the cause and will release a patch in an upcoming release._

More Information:

In the screen shot below we will receive a false positive heath check alert when the "count" changes when viewing metrics as count not average, however when observing the instances all are active and no issue is observable.  
![image](https://user-images.githubusercontent.com/13791515/90045109-6e71ce00-dc83-11ea-8162-de405d73a349.png)

Request: 
It would be nice when we do have a instance removed from rotation and we have, the reason for the removal is logged and its continuing state viewable. 

Thanks
Joe Perkins

**Comment by suwatch** [comment]
The fix will roll out by end of Aug'2020.   To put it plainly, it was a bug and we are addressing it.

**Comment by joepperkins** [comment]
Was this update rolled out, we have not had any false positives this month.

Thanks

**Comment by suwatch** [comment]
Yes.   Will close this for now.   Please reactivate if issue still comes up again.
