### ISSUE TITLE
Feature request for deleting multiple files at a time under /DebugConsole

### ISSUE THREAD

**Issue by willherr** [projectkudu/kudu#3199]
This is a feature request, very low priority in my opinion. I wasn't sure where I should be sending this. Note, we have barely scratched the surface of what kudu can offer (and are probably using it inefficiently for what it is worth).

In the web application, under Debug Console, we are maintaining files by hand by deleting files using the `-` button and then selecting and dropping our files into the app.

What would be nice is to be able to select more than one file at a time (in just the same directory) to delete, then get one window confirmation alert, and have my selected files deleted at once. It is rather tedious to click `-`, press `enter`, click `-`, press `enter`, etc., etc. 

Thank you for your time :) 

![image](https://user-images.githubusercontent.com/22281397/90652708-5e6e6700-e20c-11ea-9ec9-3139a3f3c238.png)

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
