### ISSUE TITLE
Kudu's Zip API times out extracting zip file

### ISSUE THREAD

**Issue by suwatch** [projectkudu/kudu#3200]
For a large zip file, it could take a long time to perform unzipping and eventually timeout.   The feature request is to support async pattern (eg. make a call and poll for status).

**Comment by videepthMSFT** [comment]
+1

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
