### ISSUE TITLE
Zipdeploy restart clarification

### ISSUE THREAD

**Issue by ZachTB123** [projectkudu/kudu#3201]
I have a question with regards to zipdeploys. I don't know if this is the appropriate repo to open the issue in so feel free to point me to the necessary repo if needed.

I am looking to use zipdeploy with "WEBSITE_RUN_FROM_PACKAGE" set to "1" to deploy our app code to Function Apps. I am using the REST APIs as mentioned [here](https://docs.microsoft.com/en-us/azure/azure-functions/deployment-zip-push#rest). The initial zipdeploy works perfectly fine and the our code gets uploaded. Subsequent deployments to the Function App after making code changes do not seem to update the app code because 10 minutes later my timer trigger function was still logging old values and I've seen this with other trigger types such as event hub also. Based on the info [here](https://docs.microsoft.com/en-us/azure/azure-functions/run-functions-from-deployment-package#benefits-of-running-from-a-package-file),  it says "Can be deployed to a production app (with restart)" which sounds like you need to restart your Function App before the new code will be used. Just wanted to validate, a restart is the only method that will make sure the function app code is updated after a zipdeploy?

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
