### ISSUE TITLE
Windows AppService Not Restarted After Deployment Via LocalGit, Dotnet Core 3.1

### ISSUE THREAD

**Issue by capraynor** [projectkudu/kudu#3202]
> For deployment issues, please provide us with the following information:
> ---------------------------------------------------------------

### Repro steps.
0. Azure app service, .net Core, 
1. Push built result into localgit
1. Webapp Not Restarting, latest content not appears on the website. 

### Project structures.

We are pushing the built binary to localgit. 

Please investigate this app service and clone the content from localgit: 

https://portal.azure.com/#@alexyazure2gmail.onmicrosoft.com/resource/subscriptions/24b44...60-e4a394814213/resourceGroups/ProductSample-For-US/providers/Microsoft.Web/sites/docsol-gce...o-master/appServices

### The log/error given by the failure.
Deployment Log: 

```
Using cached version of deployment script (command: 'azure -y --no-dot-deployment -r "D:\home\site\repository" -o "D:\home\site\deployments\tools" --basic --sitePath "D:\home\site\repository"').

Command: "D:\home\site\deployments\tools\deploy.cmd"
Handling Basic Web Site deployment.
Creating app_offline.htm
Cannot removed the 'to be deleted' directory, ignoring
KuduSync.NET from: 'D:\home\site\repository' to: 'D:\home\site\wwwroot'
Copying file: 'gcdocs\gcexcel\GrapeCity.Documents.Excel.dll'
Copying file: 'gcdocs\gcexcel\ja-JP\GrapeCity.Documents.Excel.resources.dll'
Copying file: 'gcdocs\gcexcel\ko-KR\GrapeCity.Documents.Excel.resources.dll'
Copying file: 'gcdocs\gcexcel\zh-CN\GrapeCity.Documents.Excel.resources.dll'
Deleting app_offline.htm
Finished successfully.
```

Configuration: 

```
Configuration: 
[
  {
    "name": "WEBSITE_DYNAMIC_CACHE",
    "value": "0",
    "slotSetting": true
  }
]
```

### Debug your Azure website remotely.
https://portal.azure.com/#@alexyazure2gmail.onmicrosoft.com/resource/subscriptions/24b44...60-e4a394814213/resourceGroups/ProductSample-For-US/providers/Microsoft.Web/sites/docsol-gce...o-master/appServices

### Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by capraynor** [comment]
> If you restart it explicitly - does the app reflect the new content. Also indicate whether this is transient and happens all the times.

Yes, the site updates when I restart the app, always. 

But I cannot reproduce this issue on other instances.

**Comment by capraynor** [comment]
Any updates on this issue?

**Comment by Pilchie** [comment]
Tagging @jkotalik and @brennanconroy for thoughts.

**Comment by capraynor** [comment]
Still no reply for this issue, and this issue still can reproduce in our environment.

**Comment by BrennanConroy** [comment]
> I cannot reproduce this issue on other instances.

With the exact same code and repro steps you can't repro except on this one instance?

Could you share your diagnostic logs
https://docs.microsoft.com/aspnet/core/host-and-deploy/aspnet-core-module?view=aspnetcore-3.1#enhanced-diagnostic-logs

**Comment by capraynor** [comment]
@BrennanConroy 
Thanks for your concern. 
We will provide you a instance later, you can do anything with it. 

And we will provide you a diagnostic log later, please wait for our work. 

Thanks

**Comment by capraynor** [comment]
@BrennanConroy 
>But I cannot reproduce this issue on other instances.

This means I cannot reproduce this issue on Linux instance. 

Sorry for confusing.

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
