### ISSUE TITLE
You do not have permission to view this directory or page. Zip Push Deploy Asp.net Core 2.1

### ISSUE THREAD

**Issue by xsamms** [projectkudu/kudu#3204]
### Repro steps.
> Project built on Visual Studio 2019 successfully with Xamarin Forms App. 
> Msbuild 15.1.0.0

###The log/error given by the failure.
> Tried to access the web app on Azure severally but got this: "You do not have permission to view this directory or page."

### Debug your Azure website remotely.
>

**Comment by suwatch** [comment]
Browse to [Kudu](https://gleeworldapp.scm.azurewebsites.net) and check if the content at d:\home\wwwroot is as expected.   I am not sure if we support such - but do try local IIS and see if that works first.

**Comment by xsamms** [comment]
@suwatch it's working perfectly on IIS, I have tried it several times and again now. I its part or a Xamarin App

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
