### ISSUE TITLE
Update Health Check Documentation

### ISSUE THREAD

**Issue by nerddtvg** [projectkudu/kudu#3207]
This is just a request to update some information on the Health Check documentation: https://github.com/projectkudu/kudu/wiki/Health-Check-(Preview)

>If the site has HTTPS enabled, then the healthcheck will honor HTTPS and send the request using that protocol.

I think this needs rewording:

>If HTTPS Only is enabled, the healthcheck will hit the HTTP endpoint first and then honor the 307 HTTP redirect to the HTTPS endpoint.

>You can secure the healthcheck endpoint itself by requiring that the User-Agent of the incoming request matches `ReadyForRequest/1.0+(HealthCheck)`. The User-Agent cannot be spoofed, since the request was already validated by the prior security features.

The correct User Agent is `HealthCheck/1.0`

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
