### ISSUE TITLE
Health Check - Azure http logs indicate useragent "-\" although as per documentation it should be ReadyforRequest/1.0+(HealthCheck)

### ISSUE THREAD

**Issue by Prasanth1911** [projectkudu/kudu#3209]
> For deployment issues, please provide us with the following information:
> ---------------------------------------------------------------

### Repro steps.
> Configured Health check for an azure app service using health check blade in azure portal. Using linux host with .Net core 3.1 version.

Validated in app service Http logs and useragent is "-\". Although as per documentation it should be ReadyForRequest/1.0+(HealthCheck).

Any thoughts or suggestions to overcome this issue is much appreciated.

**Comment by suwatch** [comment]
@sanchitmehta  please advise,

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
