### ISSUE TITLE
available node versions are not the same than in azure app service

### ISSUE THREAD

**Issue by ggirodda** [projectkudu/kudu#3210]
I'm on an azure linux appservice with node 12-LTS version.
The only available node 12-LTS version during kudu deployment is now node 12.18.2 (it has recently changed), so I move the node version in my package.json from 12.16.3 to 12.18.2.
No problem on deployment now, but when the app starts, I get the current error
`The engine "node" is incompatible with this module. Expected version "12.18.2". Got "12.16.3"`
The kudu node version are not sync with appservice 12-LTS version of node ?
How can I solve the problem please ?

**Comment by ggirodda** [comment]
I also added `WEBSITE_NODE_DEFAULT_VERSION` and `WEBSITE_NPM_DEFAULT_VERSION` in env configuration from azure portal, but nothing changes.
I'm sorry, but this is really urgent, my app doesn't work anymore

**Comment by ggirodda** [comment]
I temporairly put this on package.json to make my app run again
```
"engines": {
    "node": "12.16.3 || 12.18.2",
    "npm": "6.14.4 || 6.14.5"
  }
```

**Comment by hasandogu** [comment]
I just came across this problem as one of my dependencies required Node 12 and above. I was receiving a message similar to the one in [this](https://stackoverflow.com/questions/56617209/the-engine-node-is-incompatible-with-this-module). So, I used  `yarn install --ignore-engines` during deploy in case it helps anyone.

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
