### ISSUE TITLE
Deployment status returned Error 403

### ISSUE THREAD

**Issue by MP-okui** [projectkudu/kudu#3212]
I use Asynchronous zip deployment.
And the status is polled every 30 seconds.

The status sometimes returns an error 403.
However, looking at the ZipDeployUI, it seems to be successful.

Is it possible that auto-swap is the cause?

**Comment by suwatch** [comment]
if you are using site cred to poll, yes it could.  Since you may start polling on the recently swapped site which has a different password.

**Comment by MP-okui** [comment]
This is the response.
Is there a possibility of rebooting by swap?

```html
<body bgcolor="#00abec">
    <div id="feature">
            <div id="content">
                <h1 id="unavailable">Error 403 - This web app is stopped.</h1>
                <p id="tryAgain">The web app you have attempted to reach is currently stopped and does not accept any requests. Please try to reload the page or visit it again soon.</p>
                <p id="toAdmin">If you are the web app administrator, please find the common 403 error scenarios and resolution <a href="https://go.microsoft.com/fwlink/?linkid=2095007" target="_blank">here</a>. For further troubleshooting tools and recommendations, please visit <a href="https://portal.azure.com/">Azure Portal</a>.</p>
        </div>
    </div>
</body>
```

**Comment by suwatch** [comment]
The 403 often times meant wrong credentials.  If you provided the exact UTC time of the 403 request and site name here or [indirectly](https://github.com/projectkudu/kudu/wiki/Reporting-your-site-name-without-posting-it-publicly).   We can help pinpoint.

**Comment by MP-okui** [comment]
UTC time: 23 September 2020, 01:08:28 UTC to 23 September 2020, 01:10:39 UTC
site: ssk**********************************ase.scm.azurewebsites.net

Is this enough?

**Comment by suwatch** [comment]
Also .. _share partial info about your subscription GUID. For instance, if your subscription is 30dd879c-ee2f-11db-8314-0800200c9a66, you can share part of prefix and suffix like 30dd...9a66 as your subcription_...

**Comment by MP-okui** [comment]
This is part of the subscription GUID.
1bfb****3c0f

**Comment by suwatch** [comment]
umm.. we can't locate the site nor the sub.   could you ping your site hostname and share the CName (which should be in form of waws-prod-xxx.cloudapp.net)?

**Comment by MP-okui** [comment]
Sorry, the subscription ID was wrong. This is correct.
1b00****b3a4

Site: ssk-****-prod.azurewebsites.net
Slot: ssk-****-prod-release.azurewebsites.net
CName: waws-prod-ty1-015.cloudapp.net

Deploying to the `release` slot. After that, it auto-swap to the production slot.

**Comment by suwatch** [comment]
there were many sites starting with ssk and ended with prod - please make sure to _Share partial info about your site name (enough to **uniquely** identify within the subscription_.

**Comment by MP-okui** [comment]
I don't know the names of all the sites in subscription...
How's this? `ssk-por****in-prod.azurewebsites.net`

**Comment by suwatch** [comment]
Do you own the subscription?  Due to security reason, we can't assist if you are not the owner.

**Comment by MP-okui** [comment]
I have confirmed my role in the subscription. My role is the owner.
Maybe this is unique. `ssk-por****nd-win-prod.azurewebsites.net`

**Comment by suwatch** [comment]
This had to do with race condition with auto-swap.  Your last poll for latest deployment happened after the deployment completion and autoswap was on-going.   Depending on what stage of auto-swap, you could be polling on the swapped slot which will give you wrong information.   The 403 was the quirk due to swapping cred during swap.

Unfortunately, this is the combination (polling and autoswap) which does not work well.  If you need to poll the status, either poll and do swap explicitly upon deployment completion (meaning no using auto-swap).

**Comment by MP-okui** [comment]
I will think about changing to explicit swap.
I am grateful for your support.
