### ISSUE TITLE
How to MSDeploy from ARM template without deleting existing files?

### ISSUE THREAD

**Issue by viclin-msft** [projectkudu/kudu#3214]
On the MSDeploy command line, there is the option `-enableRule:DoNotDeleteRule` to have "incremental "deployments. This is useful if we want to do something like deploy a new WebJob while keeping existing ones. Is there a way to specify that in ARM templates?

**Comment by EricSten-MSFT** [comment]
See: https://stackoverflow.com/a/45869099/4267736

**Comment by viclin-msft** [comment]
@EricSten-MSFT thanks, this is what I am looking for.
