### ISSUE TITLE
Change SCM_HTTPCLIENT_TIMEOUT for Mooncake to 5 mins

### ISSUE THREAD

**Issue by suwatch** [projectkudu/kudu#3216]
Mooncake env had long latency issue downloading from nuget.org leading to siteextension installation failure.  We should have a better default for Mooncake env (eg. 5 mins).

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
