### ISSUE TITLE
Kudu is not running npm install after deploy for node projects

### ISSUE THREAD

**Issue by bernardoflynn** [projectkudu/kudu#3217]
> For deployment issues, please provide us with the following information:
> ---------------------------------------------------------------

### Repro steps.
> your project built successfully on your dev machine but failed on Azure?
Yes. Locally I have to copy the node_modules folder across to get it to work (or run npm install) 

> please write down your build tools and their versions (ie `Msbuild 15.1.0.0`)
npm ci
npm run build (runs next build && next export)
cp -paR out $(Build.ArtifactStagingDirectory)/out
cp -paR .next $(Build.ArtifactStagingDirectory)/.next
cp ./next.config.js $(Build.ArtifactStagingDirectory)
cp ./package.json $(Build.ArtifactStagingDirectory)
cp ./package-lock.json $(Build.ArtifactStagingDirectory)

### Project structures.
> in order to reproduce your issue at our end we need a simple 
> [github repository](https://github.com/projectkudu/kudu/wiki/Using-a-git-repo-to-report-an-issue)
> that highlights structure of the project
Just create a simple next js app and set it up as a server app (not serverless) 

### The log/error given by the failure.
> Normally this include a stack trace, error code and some more information.
no errors on deploy. But on start up, next is not found in node_modules as npm install is not run in wwwroot.

### Debug your Azure website remotely.
> it is recommanded that you share your Web App name, directly or [indirectly](https://github.com/projectkudu/kudu/wiki/Reporting-your-site-name-without-posting-it-publicly)
Subscription id 50b5...a22b
Site be...st
> we can take a look at what's going on.

### Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by bernardoflynn** [comment]
See temp.txt for proof of ownership

**Comment by bernardoflynn** [comment]
Just to provide more detail. I know that there is the app setting SCM_DO_BUILD_DURING_DEPLOYMENT that runs npm install.
However this also runs npm build which doesn't work for this type of project. The build is done as part of CI and then only the output is published as build artifacts. So when kudu runs npm build, the build fails and then deploy then fails.

Also copying over node_modules locally works (provided you use -paR in the cp command) but doing this as part of the build, package, publish, download and deploy loop fails. The node_modules are not 'found' even though they're there. I guess because the sym links, etc. are lost somewhere in there.

**Comment by sanchitmehta** [comment]
@bernardoflynn Thanks, is this an app on App Service on Linux?

cc: @kichalla @arroyc

**Comment by bernardoflynn** [comment]
Yep - as its a Next.js React app running on linux using SSR and static web page.

**Comment by sanchitmehta** [comment]
@bernardoflynn Can you open an issue at [Microsoft Oryx](https://github.com/microsoft/Oryx), Linux Apps build system is managed by Oryx.

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
