### ISSUE TITLE
How to deploy war files from azure DevOps private build agents to azure web app (Private Endpoint is raised already for the web app)

### ISSUE THREAD

**Issue by surya2155** [projectkudu/kudu#3218]
HI All,

I have two web apps in my subscription for which two Private endpoints are raised for preventing the public access. Now When I am trying to deploy the application war files to these web apps from my azure DevOps pipeline with self hosted build agents, I am getting the following error:
##[error]Failed to deploy web package to App Service.
##[error]Error: Error: Failed to deploy web package to App Service. Ip Forbidden (CODE: 403)

How to enable my pipelines to deploy war files to these web apps? **Is there any workaround for this scenario?**

usually after configuring DNS for the web app, I should able to connect from pipeline. But we don't have that chance to wait till this happens.
Please note that we haven't configured any custom DNS as of now. So I am not even able to open webapp.scm from my browser. I am getting 403 error not found.

**Comment by suwatch** [comment]
Once you enable private endpoint, your app can only be accessed via private endpoint (from VNET).   Hence, the error when DevOps is trying to access your app directly.   An idea you can explore.    You can use ARM to deploy instead.   You will need to upload war package to storage (or make package accessible via https).  Then you can call ARM to WarDeploy (similar to call with ZipDeploy).

**Comment by kan-nan-k** [comment]
I have the same problem, do we have an alternate solution to this use case ? We can't have our source code in public even though we block access using access key.

**Comment by leandromsft** [comment]
I was having the same problem, to be able to deploy my application within a private webapp, I created a virtual machine (you can also use an ACI) within the same subnet and installed the azure build agent within that vm. 

This way Azure DevOps can access the webapp and deploy

**Comment by suwatch** [comment]
@leandromsft   this is great.   If you could elaborate more (or share the link how to install and configure azure build agent), it would be beneficial to others.

**Comment by leandromsft** [comment]
> @leandromsft this is great. If you could elaborate more (or share the link how to install and configure azure build agent), it would be beneficial to others.

In my case, I choose to create a docker image with the AzDevOps agent

Bellow I describe the steps

1. Create Docker Image (azdevops-dockeragent-linux) 
https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/docker?view=azure-devops
 
2. Send the image (azdevops-dockeragent-linux) to Azure Container Registry

3. Create new agent pool in the Azure DevOps organization (**azureaci**)

4. Run the image (azdevops-dockeragent-linux) using Azure Container Instance. Here we have the parameters to configure Vnet /  SubNet and the Azure DevOps organization
 
az container create --resource-group <my-rg> --name azdevops-dockeragent-linux --image myregistry.azurecr.io/azdevops-dockeragent-linux:latest --registry-username <username> --registry-password <password> --os-type Linux --cpu 2 --memory 3.5 --vnet <my-vnet> --subnet <my-sub-net> --environment-variables AZP_URL=https://dev.azure.com/myorg AZP_TOKEN=1234567890 AZP_AGENT_NAME=azdevops-dockeragent-linux-vnet AZP_POOL=**azureaci**
 
5. Configure the release process to use agent pool **azureaci**

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
