### ISSUE TITLE
Restart when add "Microsoft.Web/sites/config" change in deploy ARM template

### ISSUE THREAD

**Issue by Zoe1808** [projectkudu/kudu#3219]
Hi team, When we add "Microsoft.Web/sites/config" config changes in deploy ARM template with mode "Incremental", it will cause restart in both staging and product slot during every deployments, which will bring some downtime in our service.
What we expect is when we add site config change in ARM template for the first time, it could be a restart during deployment, but after that when we deploy with the same ARM template, it should not be any restart.

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
