### ISSUE TITLE
log user agent string to Kudu tables for eventid = 65516

### ISSUE THREAD

**Issue by ranovoa** [projectkudu/kudu#3224]
Upon meeting with Suwat, the analytics team would like to count on what we call 'deployment client' so that we can expose in our tables greater deployment details for every site. This would allow several of our partner teams to analyze and identify opportunities in customer retention based on client/source cohorts, allowing us to concentrate on improving experiences where needed.

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
