### ISSUE TITLE
Suggestion: Support large monitors

### ISSUE THREAD

**Issue by rkuiper1** [projectkudu/kudu#3225]
Hi,

The Debug Console seems to have a fixed width viewport.
This is sub-optimal to very annoying when you have a large wide monitor (IMHO).
Please look at the attached screenshot to see my point.
I could probably see the entire width of this log file on my 5120x2160 monitor, but I have to scroll horizontally because of CSS...
Of course I can install a plug-in that fixes this problem, but wouldn't it be nice if the page/site would consider modern monitors.

Cheers,
Richard

![Screenshot 2020-10-09 173351](https://user-images.githubusercontent.com/44542446/95603064-11fa1780-0a56-11eb-8956-d0936e2d704b.png)

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
