### ISSUE TITLE
Failed to Install Extension, Extension Not Found

### ISSUE THREAD

**Issue by Silvenga** [projectkudu/kudu#3226]
### Repro steps.

- Using the light weight NuGet server Baget setup a custom feed (`SCM_SITEEXTENSIONS_FEED_URL`).
- Verify packages show up in the Gallery.
- Attempt to install package.

### Project structures.
Not relevant, but using the ASP.NET Core Docker sample project (not running in a Docker container, published via FTP).

### The log/error given by the failure.

PUT https://ws.scm.azurewebsites.net/api/siteextensions/extension
404 Not Found

### Mention any other details that might be useful.

I see in Baget's logs that the registration endpoint is hit, returning 200. There are no other requests to the NuGet server during install. This is the same as the official endpoint:

```
https://api.nuget.org/v3/registration5-semver1/extension/index.json
```

This suggests that at least endpoint discovery is working in Kudu. The data appears to be the same and this extension was published on NuGet, so it works from there, just not from the private feed.

I worry that the problem is from using the unmaintained NuGet.Core package from 2014. I believe Baget is compliant with the spec, but it is much newer (ASP.NET Core based).

I do not know how to enable trace logging. Setting `SCM_TRACE_LEVEL` to 4 doesn't appear to provide any useful information.

----

We really need a self-hosted feed for testing.

**Comment by suwatch** [comment]
I assume this is Linux App Service, correct?

**Comment by Silvenga** [comment]
@suwatch not this one. I'm testing this out with App Service running under Windows using the .NET Core 3.1 runtime via IIS.

**Comment by Silvenga** [comment]
@suwatch is there a way to get trace logging under Kudu? Is the version of Kudu in master deployed to Azure?

**Comment by suwatch** [comment]
the trace is under `d:\home\logfiles\kudu\trace` folder.

**Comment by Silvenga** [comment]
@suwatch I don't see the message I see in the code in any of those log files. Are those messages logged to that folder?

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
