### ISSUE TITLE
Wiki is missing a note about deploying webjobs via Azure DevOps release pipeline's App Service Deployment task

### ISSUE THREAD

**Issue by StingyJack** [projectkudu/kudu#3227]
[This section](https://github.com/projectkudu/kudu/wiki/WebJobs#Deployment) specifically. 

We have lots of webjobs that dont belong to any Web App (like windows services), they are also deployed on different schedules. Instead of rolling a script to do the deployment in one of the ways mentioned, we setup a Virtual Application on the App service with a virtual path of the webjob name (for example `/WebJob_DbCleanup`  and a physical path of `site\wwwroot\app_data\jobs\continuous\WebJob_DbCleanup` . Then in the release pipeline we choose the app service and specify the virtual application name (`WebJob_DbCleanup`) and the path to the artifact folder. 

This is pretty easy and avoids all the plumbing for auth and connections and stuff, and works with versions 2 and 3 of WebJobs

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
