### ISSUE TITLE
Allow more than 20 apps per github repo

### ISSUE THREAD

**Issue by zgirod** [projectkudu/kudu#3230]
**Describe the solution you'd like**
We deploy the same repo to a bunch of different app services.  We have multiple webjobs on different app services hosted on different app service plans.  They are deployed from the same github repo and we are running into a limit of 20 webhooks, therefore I can build a max of 20 apps from one repo.  The number is even less if we use webhooks for other stuff.  I would like Kudu to update their deployment infrastructure to have one webhook supporting deployments for multiple app services.

At the very least I think the documentation should be updated to reflect this constraint.

**Comment by suwatch** [comment]
This is github constraints of 20 hook limits.  Kudu supports any amount of Hook for other such as Bitbucket, ...   I suggested you file this with Github team.

**Comment by zgirod** [comment]
@suwatch Thanks for the reply.  I did reach out to Github before opening the ticket.  They said:

> ...All of those existing webhooks are being triggered by the same exact events (push) and making the same exact webhook deliveries to the same service. That means there are multiple webhooks doing the same exact thing -- they're delivering the same events multiple times to the same service. That kind of behavior is wasteful, and the webhook limits were introduced to prevent exactly that kind of behavior since it's a performance and reliability concern. We can't support a higher number of webhooks for such a use-case.
> 
> Instead, the service(s) you're using should be able to work with just one webhook defined on the repository since the events they get from that webhook are the same as the events they get from multiple webhooks they have now. You'd need to reach out to the support staff for the service you're using and ask them to make these changes.

What do you recommend as a path forward?

**Comment by suwatch** [comment]
I think the confusion is the definition of "same" service.   For us, App Service is a unit of a service and different App Service will have different webhook uri.    Are you setting up multiple webhooks to the same exact App Service?

**Comment by zgirod** [comment]
No.  We have multiple different app services that get deployed with different webjobs from the same repo.  There are about 6 in dev, 6 in staging and 6+ in production.  That quickly gets to the 20 limit. The dev/staging/production come from different branches in the same repo.

I think what I am doing in pretty standard stuff.  Setting up an app service with deployment via Kudu linked to Github.  Not setting up multiple webhooks to the same exact app service.  I wouldn't even know how to do that?!

There are any deployment slots either, they are all distinct separate app services.  Some are in the same app service plan and some are spread across different app service plans.

If I look at my webhooks in Github each does have a different uri based upon the app service.

**Comment by suwatch** [comment]
Hence, it is a GitHub limitation that does not support more 20 different service webhooks.   I recalled it did come up for people using App Services but very rarely.   Perhaps, ask GitHub again if you have more than 20 services, how to workaround this?   I guess they will tell you to write to proxy that fan out to different App Services/Slots.

**Comment by zgirod** [comment]
Part of the initial conversation with Github was about a proxy. How would a proxy work?  Kudu automatically connects to GitHub to create a callback.

I guess I would have to have Kudu auto connect to Github and create a webhook then take the webhook uri and place that in a central webhook proxy that contains a list of webhook uris and for the correct branch fan out to the correct app service?

I really think the documentation should be updated to note this limitation.  Figuring it out while trying to deploy production infrastructure was not the best way to figure it out.  Also the error you get when this happens in the Azure Portal is unhelpful.  It just says there was an error.  It took a support ticket and talking to multiple people to figure out what was going on.  There should be better error notifications in the portal about what is going on.

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
