### ISSUE TITLE
Azure Service App - unable to fork (Deployment Center)

### ISSUE THREAD

**Issue by aspexi** [projectkudu/kudu#3231]
### Repro steps.
> your project built successfully on your dev machine but failed on Azure?

Yes.

> please write down your build tools and their versions (ie `Msbuild 15.1.0.0`)

Azure App Service, Build with Kudu, source repository: Github.

### Project structures.

WordPress website.

### The log/error given by the failure.

error: cannot run ssh: No such file or directory\nfatal: unable to fork\n\n/usr/bin/git fetch origin --progress

### Mention any other details that might be useful.

This has started few days ago with no changes to the Service App or the codebase, simple code changes as usual. Anyone else is experiencing this? The day it started was around 29.10 when the Bitbucket experienced issues with hooks (https://bitbucket.status.atlassian.com/). Not sure if related.

**Comment by sanchitmehta** [comment]
@aspexi Could you try setting the App Setting: `SCM_USE_LIBGIT2SHARP_REPOSITORY=0` and see if it fixes the problem.

We have migrated certain apps to use ASP NETCore 3.1 based Kudu on App Service on Linux,  `SCM_ENABLE_DYNAMIC_INSTALL=false` should revert back to the old Kudu version.

**Comment by aspexi** [comment]
@sanchitmehta thank you, this was helpful.

Setting `SCM_USE_LIBGIT2SHARP_REPOSITORY=0` didn't help.

`SCM_ENABLE_DYNAMIC_INSTALL=false` solved the problem from this issue although that issue came back: https://github.com/microsoft/Oryx/issues/822

Luckily my application is not JAVA so setting `DISABLE_JAVA_BUILD=true` solved the problem with deployment for good.

**Comment by MCKLMT** [comment]
I encounter the same issue with BitBucket and a PHP web site. Kudu is unable to fork the project until I add the SCM_ENABLE_DYNAMIC_INSTALL = false environment variable.
