### ISSUE TITLE
azure appservice not using correct version of NPM when using child process

### ISSUE THREAD

**Issue by kAvItHa-cL** [projectkudu/kudu#3232]
0

I am trying to use child process in my dot net core application to run some npm and ng commands. I have set WEBSITE_NODE_DEFAULT_VERSION =12.18.0 and WEBSITE_NPM_DEFAULT_VERSION=6.14.4 and in kudu powershell/cmd its showing correct version

D:\home>npm --version 6.14.4

D:\home>node -v v12.18.0

My code in c# to run npm commands :

        ProcessStartInfo processInfo = new ProcessStartInfo();
        processInfo.FileName = @"cmd.exe";
        processInfo.ErrorDialog = true;
        processInfo.UseShellExecute = false;
        processInfo.RedirectStandardOutput = true;
        processInfo.RedirectStandardError = true;
        processInfo.Arguments = $"/C npm -version";
       
        Process process = Process.Start(processInfo);
        process.WaitForExit();
        string output = process.StandardOutput.ReadToEnd();
        string error = process.StandardError.ReadToEnd();

shows npm version as as 1.1.37 but it will display node version correclty if i use node -v as command.

Deploying from VS to AZURE

I hope some one has solution for my problem. Thank you

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
