### ISSUE TITLE
azure zipdeploy returns 403 with an token retrieved through first party app, but it did work with the token retrieved from az cli

### ISSUE THREAD

**Issue by luhan2017** [projectkudu/kudu#3237]
> For deployment issues, please provide us with the following information:
> ---------------------------------------------------------------

### Repro steps.
Previous, we are calling this API using the token got from "az account get-access-token"
https://{hostname}.scm.azurewebsites.net/zipdeploy/?isAsync=true
But when we switched to use the token got from first part app, we always got such error

<h1 id="unavailable">Error 403 - This web app is stopped.</h1>
<p id="tryAgain">The web app you have attempted to reach is currently stopped and does not accept any requests. Please try to reload the page or visit it again soon.</p>
<p id="toAdmin">If you are the web app administrator, please find the common 403 error scenarios and resolution
<a href="https://go.microsoft.com/fwlink/?linkid=2095007" target="_blank">here</a>. For further troubleshooting tools and recommendations, please visit
<a href="https://portal.azure.com/">Azure Portal</a>.

Per the suggestion from the comments, I also tried this API:  
get https://luhan0603-dev.scm.azurewebsites.net/api/vfs/site/wwwroot/ 
I got the same result, token got from azure cli works well, but token got from first party app returns 403. 

Here is the diff of the two decoded tokens. left is az cli token, right is first part app token.
![image](https://user-images.githubusercontent.com/32191031/98795585-53128c80-2445-11eb-8346-9ceb8319509d.png)

More context. We use the same first part app tokens to provision the web app beforehand, in case that makes a difference. So we acquire a token, provision web app, talk to kudu zip deploy. When we acquire the token through az cli it works, when we acquire the token through the first party app it fails while accessing kudu as described above.

### Project structures.
> in order to reproduce your issue at our end we need a simple 
> [github repository](https://github.com/projectkudu/kudu/wiki/Using-a-git-repo-to-report-an-issue)
> that highlights structure of the project

### The log/error given by the failure.
> Normally this include a stack trace, error code and some more information.

### Debug your Azure website remotely.
> it is recommanded that you share your Web App name, directly or [indirectly](https://github.com/projectkudu/kudu/wiki/Reporting-your-site-name-without-posting-it-publicly)
> we can take a look at what's going on.

### Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by suwatch** [comment]
communicate internally.

**Comment by suwatch** [comment]
We will fix the issue.  ETA will be around end of JAN or early FEB 2021.

**Comment by carlosscastro** [comment]
Hello @suwatch ! Is this still on track? What is the estimate release date? Our release of Bot Framework Composer depends on the release of this so I wanted to check in. Also, is there an open tracking issue since this one is closed?

**Comment by suwatch** [comment]
Yes it is on track.   It is part of AppService version 92 - eta for rollout in Feb'21.   

Internal Tracking: https://msazure.visualstudio.com/Antares/_workitems/edit/8898423

**Comment by carlosscastro** [comment]
Thanks!
