### ISSUE TITLE
Update synctriggers for Function app deployment

### ISSUE THREAD

**Issue by ankitkumarr** [projectkudu/kudu#3238]
**Problem**
We recently update Kudu to call synctirggers through Functions runtime during a deployment. This brought up some concerns. One of them being if kudu calls sync triggers before Runtime has picked up the new payload, Runtime will synctriggers on the old payload.

**Proposed Solution**
The change proposed by Kranthi is to make Kudu call SetTriggers with an empty payload after PackageName.txt is updated. Kudu should then call SyncTriggers on the Functions Runtime 1 minute after this, in order to allow the main site’s worker process to detect that a new zip is available and go through a shutdown.

**Comment by suwatch** [comment]
@ankitkumarr   thanks for tracking this!

**Comment by ankitkumarr** [comment]
Closed by https://github.com/projectkudu/kudu/commit/86918e0c0f1098afefcd5e1a03e1d7281cb850c8
