### ISSUE TITLE
Azure App Settings don't override WebJob App Setting if it is deployed "in place"

### ISSUE THREAD

**Issue by robert-shattock** [projectkudu/kudu#3243]
### Problem
There is a bug with WebJobs in Kudu not always having their appSettings overridden by Azure App Service app settings

**Expectation:** AppSettings in app.config of a WebJob deployed in place should be overridden if set in the hosting Azure App Service application settings.
**Actual:** AppSetting as per WebJob is used, the Azure App Service application setting is not used by the WebJob.

**NOTE:** This only occurs for in place deployment, if "is_in_place" in the settings.job file of the WebJob is false then its AppSettings are correctly overridden by the hosting Azure App Service application settings.

### Repro steps and Git Repo

https://github.com/robert-shattock/DemoOfKuduWebJobAppSettingIssue/blob/main/README.md

* This repo contains a web project for hosting the WebJobs and two WebJobs - one set to be deployed in place and the other to be deployed to a temp location.  Each project has an Application Setting called settingOrigin... which is set to Website, WebJob - In Place and WebJob - Not in Place respectively.
* Clone repository
* Deploy web project to app service (it should also deploy the two WebJobs - if it doesn't then right click the web project and choose "Add Existing Project as Azure WebJob" - do this for both web jobs and then deploy web project again).
* When each project is run locally they will say:
  * Web: settingOrigin = Website
  * WebJob: settingOrigin = WebJob - In Place
  * WebJobNoInPlace: settingOrigin = WebJob - Not In Place
* Create Application Setting in the Azure portal for the website with key=settingOrigin and value=Azure App Service Application Setting, save setting.
* When each project is run in Azure they will now say:
  * Web: settingOrigin = Azure App Service Application Setting
  * WebJob: settingOrigin = WebJob - In Place **(this is the bug, it should be Azure App Service Application Setting)**
  * WebJobNoInPlace: settingOrigin = Azure App Service Application Setting

### Debug your Azure website remotely.

Web App name https://demoofkuduwebjobappsettingissue.azurewebsites.net/

### Image

![Picture showing differences in Application Setting Used in each project scenario](https://github.com/robert-shattock/DemoOfKuduWebJobAppSettingIssue/blob/main/BugDemoImageForReadMe.jpg?raw=true)

### Other Details
* Problem has been previously noted on Stackoverflow https://stackoverflow.com/a/43380614/1450351
* Expected behaviour is touched on here (even if some of it is out of date) https://blog.ploeh.dk/2014/05/16/configuring-azure-web-jobs/

**Comment by suwatch** [comment]
From the codes, it seems to be by design, see [this](https://github.com/projectkudu/kudu/blob/master/Kudu.Core/Jobs/BaseJobRunner.cs#L135-L140) returns before reaching the [UpdateAppSettings](https://github.com/projectkudu/kudu/blob/master/Kudu.Core/Jobs/BaseJobRunner.cs#L188) step.  Since is_in_place will cause Job to from the original repo location and it tries to avoid and alter the repo file.

The workaround is, instead of reading from ConfigurationManager.AppSettings, to write a webjob to read from Environment.GetVariable(appSettingName) instead.   Hope this help.

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
