### ISSUE TITLE
App Service Editor - Git features unavailable | statusCode : 400 - message "Not at the repository root"

### ISSUE THREAD

**Issue by ansheppa** [projectkudu/kudu#3246]
Issue summary : After initializing a git repository from within the App Service Editor, the git blade shows the message "Open the repository's root directory in order to access Git features". 

Repro steps :

1. From a new App Service (Windows) in the Portal, click "App Service Editor" > [GO]

2. Select Git icon from left hand menu 

![image](https://user-images.githubusercontent.com/74782466/99824664-ed618700-2b4d-11eb-88d7-2eae07962b6d.png)
3. Choose "Initialize git repository"

![image](https://user-images.githubusercontent.com/74782466/99824521-b9866180-2b4d-11eb-9bd5-d2cbb6d397ea.png)

No features are shown and am unsure how to "Open the repository's root directory in order to access Git features".

During this process, there are 2 two web requests that fail...

GET https://{your-site}.scm.azurewebsites.net/dev/api/git/wwwroot/init
GET https://{your-site}.scm.azurewebsites.net/dev/api/git/wwwroot/status

Both have the same response...

{
    "statusCode": 400,
    "message": "Not at the repository root",
    "code": 400,
    "data": {
        "error": null,
        "message": "Not at the repository root",
        "stdout": null,
        "stderr": null,
        "exitCode": null,
        "gitErrorCode": "NotAtRepositoryRoot",
        "gitCommand": null
    }
}

This appears to be coming from D:\Program Files (x86)\SiteExtensions\Monaco\1.0.0-20200601\server\contrib\git\rawGitService.js

        RawGitService.prototype.checkRoot = function () {
            var _this = this;
            if (!this.repoRealRootPath) {
                this.repoRealRootPath = pfs.realpath(this.repo.path);
            }
            return this.repo.getRoot().then(function (root) {
                return winjs.Promise.join([
                    _this.repoRealRootPath,
                    pfs.realpath(root)
                ]).then(function (paths) {
                    if (!pathsAreEqual(paths[0], paths[1])) {
                        return winjs.Promise.wrapError(new gitlib.GitError({
                            message: "Not at the repository root",
                            gitErrorCode: gitlib.GitErrorCodes.NotAtRepositoryRoot
                        }));
                    }
                });
            });
        };

..but I do not understand the underlying issue causing the error.

I have not been able to find any documentation regarding the git features but am aware that this has changed/broken recently.

Any assistance greatly appreciated.

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
