### ISSUE TITLE
[Linux] [Python] [Django] SCM_POST_DEPLOYMENT_ACTIONS_PATH

### ISSUE THREAD

**Issue by piotrjez** [projectkudu/kudu#3247]
### Repro steps.
- create project in Django
- create folder with deployment script: **deployment/postbuild.sh**
- **postbuild.sh** file: 
```
cd /home/site/wwwroot
. pythonenv3.8/bin/activate
python manage.py migrate
```
- define **SCM_POST_DEPLOYMENT_ACTIONS_PATH** = /home/site/wwwroot/**deployment** in Configuration section on Azure Portal
- build Python app with GitHub Action: [azure/appservice-build@v2](https://github.com/Azure/appservice-build)
- deploy Python app with GitHub Action: [azure/webapps-deploy@v2](https://github.com/Azure/webapps-deploy)

### Project structures.
> [django-realworld-example-app](https://github.com/gothinkster/django-realworld-example-app)

### The log/error given by the failure.
Error on deploy:
```
Processed 13779 files...
Finished successfully.
Running post deployment command(s)...
Add execute permission for post build script /home/site/wwwroot/deployment/postbuild.sh
postbuild
Command: "/home/site/wwwroot/deployment/postbuild.sh"
  File "manage.py", line 14
    ) from exc
         ^
SyntaxError: invalid syntax
  File "manage.py", line 14
    ) from exc
         ^
SyntaxError: invalid syntax
  File "manage.py", line 14
    ) from exc
         ^
SyntaxError: invalid syntax
File "manage.py", line 14\n    ) from exc\n         ^\nSyntaxError: invalid syntax\n  File "manage.py", line 14\n    ) from exc\n         ^\nSyntaxError: invalid syntax\n  File "manage.py", line 14\n    ) from exc\n         ^\nSyntaxError: invalid syntax\n/opt/Kudu/Scripts/starter.sh "/home/site/wwwroot/deployment/postbuild.sh"
Error: Failed to deploy web package to App Service.
Error: Deployment Failed with Error: Package deployment using ZIP Deploy failed. Refer logs for more details.
```
When **SCM_DO_BUILD_DURING_DEPLOYMENT = true** and **POST_BUILD_COMMAND = deployment/postbuild.sh** there's no problem with running this script, but I need build process on GitHub Actions...

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
