### ISSUE TITLE
ASP.NET Core 5 az webapp config-zip fails to serve static assets in wwwroot

### ISSUE THREAD

**Issue by seangwright** [projectkudu/kudu#3249]
> For deployment issues, please provide us with the following information:
> ---------------------------------------------------------------

### Repro steps.
I have a .NET 5 ASP.NET Core app running on a Linux App Service.

I run a `.ps1` using `az webapp` to deploy my site from a zip.

```powershell
$publishDir = '.\publish'

if (Test-Path $publishDir) {
    Remove-Item $publishDir -Recurse
}

$publishZip = 'publish.zip'

if (Test-Path $publishZip) {
    Remove-Item $publishZip
}

dotnet publish -o $publishDir -c Release -r linux-x64
Compress-Archive -Path "$($publishDir)\*" -DestinationPath $publishZip

$resourceGroupName = 'my-resource-group'
$appName = 'my-app-service'

az webapp deployment source config-zip --resource-group $resourceGroupName --name $appName --src $publishZip
```

The site publishes fine and the docker container initializes, however, my app does not serve **any** static files in the ASP.NET Core `\wwwroot` directory (not the App Service `\wwwroot`).

When I use KUDU to browse the file system and look at the .zip that my app is running from, and unzip that .zip file, I can see that the static files are in the ASP.NET Core `\wwwroot` folder.

![Screenshot 2020-12-01 004741](https://user-images.githubusercontent.com/1382768/100702026-d8b39900-336e-11eb-8935-55ce1d987dfa.jpg)

In this screenshot I show the unzipped contents of the ASP.NET Core `\wwwroot` folder.

### Project structures.

Standard ASP.NET Core .NET 5 application with static assets in the project `\wwwroot` folder.

### The log/error given by the failure.
No error logs, but there are 404 errors when I try to load those assets in the browser.

This includes:
- robots.txt
- index.html
- logo.svg

and any other files located under the ASP.NET Core `wwwroot` folder.

### Mention any other details that might be useful.

When I deploy my app via FTP to the `site\wwwroot` folder of the App Service, the static assets load without any issue.

I am using the `app.UseStaticFiles();` middleware in my ASP.NET Core app, and again, everything works fine when deploying the _exact same_ `.\publish` folder contents via FTP.

I was originally deploying my app this way and everything worked correctly, but that resulted in locked files so I wanted to use .zip deploy instead.

**Comment by suwatch** [comment]
@sanchitmehta Is this something you could help?

**Comment by seangwright** [comment]
Any recommendations here on what I should check to help troubleshoot?

**Comment by seangwright** [comment]
Bump...

**Comment by sanchitmehta** [comment]
@seangwright do you see static files when using webssh to the main app container (not the Kudu bash console)?

cc: @arroyc

**Comment by seangwright** [comment]
@sanchitmehta  I haven't tried ssh'ing into the container - is there documentation on how I would do this?

Do you think that the static files aren't being volume mapped to the container correctly?

**Comment by seangwright** [comment]
Bump...

**Comment by sanchitmehta** [comment]
@seangwright  Yeah that might be an issue. Here are the docs how you can SSH to your app container: https://docs.microsoft.com/en-us/azure/app-service/configure-linux-open-ssh-session

**Comment by beforan** [comment]
Sorry to bump this issue a year on, but it's still open ¯\_(ツ)_/¯

I'm having this issue today on .NET6, all other details the same (config-zip to Linux app service).

I can see the static files in webssh, in `~/site/wwwroot/wwwroot` (the second wwwroot being ASP.NET Core's one, containing the static files)

**Comment by sergeystoma** [comment]
Just ran into what feels like a similar issue, but using classic 4.8 ASP.NET Web API... it appears that UseFileServer or UseStaticFiles (both from Owin.StaticFiles middleware) don't work when combined with WEBSITE_RUN_FROM_PACKAGE. Either method results into 500.19 error (invalid web.config blah blah, when detailed errors enabled), or "The page cannot be displayed because an internal server error has occurred" message otherwise, with no further details really being logged anywhere else...

Standard controllers/routes work just fine however. Since I'm not that concerned about the speed of delivering our static files (it is a backend SPA), I simply rewrote the thing using standard FileResult...

**Comment by KennyNuggets** [comment]
I am also having this same exact issue with dot net core 7 WEBSITE_RUN_FROM_PACKAGE.  This is with angular though and speed is important for serving these files. Is there any solution for this?

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
