### ISSUE TITLE
Cannot access kudu console

### ISSUE THREAD

**Issue by DVGY** [projectkudu/kudu#3252]
I cannot access kudu console, I have node function running, there is no ASP.NETCORE app, why I am seeing this. 

![image](https://user-images.githubusercontent.com/46158826/101913224-b9c3cb00-3be8-11eb-9a5f-7fcc24ab8843.png)

Please let me know what information you need, I can send you personally

**Comment by suwatch** [comment]
@sanchitmehta  / @purva-vasudeo please advise,
