### ISSUE TITLE
Remove Sentinel file on Kudu Startup

### ISSUE THREAD

**Issue by suwatch** [projectkudu/kudu#3254]
This should scope to Azure and Windows only.

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
