### ISSUE TITLE
ZipDelpoy on azure web app fails

### ISSUE THREAD

**Issue by MP-okui** [projectkudu/kudu#3256]
I changed the deployment method from Github to ZipDeploy.
However, ZipDeploy fails.

I checked the status and logs, but I don't understand the cause.
What else can I do?

## deployment status
https://****.scm.azurewebsites.net/api/deployments/latest?deployer=ZipDeploy&time=2021-01-04_10-27-27Z

```json
{
    "id":"temp-14a76051",
    "status":3,
    "status_text":"",
    "author_email":"N/A",
    "author":"N/A",
    "deployer":"ZipDeploy",
    "message":"Deploying from pushed zip file",
    "progress":"",
    "received_time":"2021-01-04T10:27:26.8802135Z",
    "start_time":"2021-01-04T10:27:26.8802135Z",
    "end_time":"2021-01-04T10:28:02.9130943Z",
    "last_success_end_time":null,
    "complete":true,
    "active":false,
    "is_temp":true,
    "is_readonly":false,
    "url":"https://****.scm.azurewebsites.net/api/deployments/latest",
    "log_url":"https://****.azurewebsites.net/api/deployments/latest/log",
    "site_name":"****",
    "provisioningState":null
}
```

## log
https://****.azurewebsites.net/api/deployments/latest/log

```json
{
    "Message":"An error has occurred.",
    "ExceptionMessage":"No log found for 'latest'.",
    "ExceptionType":"System.IO.FileNotFoundException",
    "StackTrace":"   at Kudu.Core.Deployment.DeploymentManager.GetLogEntries(String id) in C:\\Kudu Files\\Private\\src\\master\\Kudu.Core\\Deployment\\DeploymentManager.cs:line 97\r\n   at Kudu.Services.Deployment.DeploymentController.GetLogEntry(String id) in C:\\Kudu Files\\Private\\src\\master\\Kudu.Services\\Deployment\\DeploymentController.cs:line 375"
}
```

## Kudu site

- 2021-01-04T10:27:26.8802135Z : Deploying from pushed zip file
    - 2021-01-04T10:27:27.0364757Z : Fetching changes.
        - 2021-01-04T10:27:27.0364757Z : Cleaning up temp folders from previous zip deployments and extracting pushed zip file D:\local\Temp\zipdeploy\tbmgjvsn.zip (20.22 MB) to D:\local\Temp\zipdeploy\extracted

**Comment by suwatch** [comment]
If the site was setup CI/CD from Github - you must disconnect that first by going to portal and disconnect deployment from Github.     The other mitigation would be to remove d:\home\site\repository directory before performing ZipDeploy.   You only need to do that once.

**Comment by MP-okui** [comment]
I disconnected the CI/CD from Github before doing ZipDeploy.
It was notified as a "failure". But, it seems that CI/CD is disconnected.

I also tried the following:

1. I removed the webhook from the Github repository settings.
2. Deleted the `d:\home\site\repository` directory. But, `d:\home\site\repository\.git` cannot be deleted.

> 409 Conflict: Cannot delete directory. It is either not empty or access is not allowed.

I haven't solved it yet.

**Comment by yoozek** [comment]
@MP-okui did you managed to solve it? I have the same 3 years later

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
