### ISSUE TITLE
User accessible logs are close to useless

### ISSUE THREAD

**Issue by zmarty** [projectkudu/kudu#3259]
We are an internal Microsoft team. We would like to understand why deployments fail. The user-accessible logs provided by Kudu are both extremely hard to navigate (a very long list of small files), and also very difficult to understand. We often see a stack trace and that's about it. We asked for help from the Azure App Service team but my impression is that they are also often stumped.

At the moment we feel powerless, the only way to really debug is to beg the Kudu team to look at their logs and figure it out. This is not sustainable with so many external customers.

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
