### ISSUE TITLE
Deployment of Azure Function doesn't delete old DLL's (MSDeploy, ZipDeploy)

### ISSUE THREAD

**Issue by HassanBadir** [projectkudu/kudu#3260]
Hello,

As part of our migration to **.Net Core Azure Functions**, we moved most of our projects to **.NetStandard**, for some reason when deploying our functions in AzureDevOps .. (With ARM Template) some of the NetStandard DLL's aren't being extracted to the Function file system and we are stuck with the old **.NetFrameWork** DLL's, which cause failures to my functions.

of course, if I delete the old net framework dll, it would copy the new .netstandard dll to the function files and everything work fine, I can't take this as a solution when we want to deploy the change worldwide with many functions versions (i check in kudo).  

for building we use: MSBuild
everything on building works fine, also creates the Zip files that's for the functions with the correct dll's.

we deploy our azure function with **ARM Templates**.

what I have tried so far:

this didn't work, ZipDeploy didn't exactly overwrite everything, old dlls still exist.
1. https://github.com/projectkudu/kudu/wiki/MSDeploy-VS.-ZipDeploy

tried adding this app setting property (bottom of page), also didn't help, deployment works but dlls don't get overwritten
2. https://github.com/projectkudu/kudu/wiki/Deploying-from-a-zip-file-or-url

3. I think WEBSITE_RUN_FROM_PACKAGE isn't an option for me, tried also doesn't work since it has problems working with "list-keys", and I get an error like NotFound

the functions are deployed correctly, but when trying to use list-keys this fails .. 
these images related to using run_from_package: 
![image](https://user-images.githubusercontent.com/37299319/104321916-ea02d000-54ec-11eb-9a14-9f2f9dc89ab6.png)

![image](https://user-images.githubusercontent.com/37299319/104321729-ad36d900-54ec-11eb-9dae-8b64b911a53d.png)

also SitePackages are empty:
![image](https://user-images.githubusercontent.com/37299319/104322027-0e5eac80-54ed-11eb-89a1-138f73f31ef9.png)

is there an option to make a clean deployment? which overwrites everything or remove everything? with arm templates?

Thank you.

**Comment by suwatch** [comment]
The new deployment was supposed to update the old files as well as remove those no longer present in the new deployment.  We will need to look at the log (share the site name (here or [indirectly](https://github.com/projectkudu/kudu/wiki/Reporting-your-site-name-without-posting-it-publicly)), UTC time of the deployment and names of problematic files.

For a clean fresh deployment, you can create a new slot, deploy and then swap.

**Comment by HassanBadir** [comment]
hey @suwatch, thank you for your reply,

I have multiple runs, those are the details as requested on Functions Link of a simple run from portal:

Files(dll's) that aren't replaced, we moved to .NetStandard, and some of these stuck with .NetFramework, maybe there is more but these are the ones we need:
Microsoft.Azure.Security.Detection.SecurityAlertPublisher
Microsoft.Azure.Security.Detection.Discovery.Client
Microsoft.Azure.Security.Detection.AlertContracts
DataSec.PAL.Azure.Asc.Alerting

**1- FirstFunction: ZipDeploy**
FuncID: 286083d1-70d4-4d9a-9c75-65861c12d6cf
TIME: 2021-01-13T07:07:48.612
Region: WestEurope

the actual deployment failure happened at 12 Jan 2021, 05:56 AM UTC
this was ZipDeployment
as mentioned here: https://github.com/projectkudu/kudu/wiki/MSDeploy-VS.-ZipDeploy

**2- Second Function: ZipDeploy with SCM_ZIPDEPLOY_DONOT_PRESERVE_FILETIME=1**
FuncID: c6962c91-d0b9-4450-abd9-779d2c7c8c0e
TIME: 2021-01-13T06:54:07.056
Region: WestEurope

the actual deployment failure happened at 12 Jan 2021, 08:13 AM UTC
this deployment was ZipDeployment, with the option: SCM_ZIPDEPLOY_DONOT_PRESERVE_FILETIME=1 
as mentioned on this link at the bottom: https://github.com/projectkudu/kudu/wiki/Deploying-from-a-zip-file-or-url


**3- Third Function Deployment: ZipDeploy with WEBSITE_RUN_FROM_PACKAGE**
FuncID: 582ca245-b9f7-4f6d-a98a-0cd0c8281c76
TIME: 2021-01-13T07:20:54.141
Region: WestEurope

the actual deployment failure happened at 11 Jan 2021, 08:49 AM UTC 
the functions sitepackage file is empty.

this was the best option to use but it won't work for me
this deployment fails when trying to use **listkeys** 
I have an ARM template which listkeys to keyvault for my http triggered functions, Example:

 ```
{
            "name": "[concat(parameters('keyVaultName'), '/', 'FunctionKey')]",
            "type": "Microsoft.KeyVault/vaults/secrets",
            "apiVersion": "2019-09-01",
            "properties": {
                "value": "[listkeys(resourceId('Microsoft.Web/sites/functions', variables('FunctionAppName'), 'Function'), '2019-08-01').default]"
            }
        }
```
I would guess that because the functions are in a package they aren't found, which causes NotFound Error: failed to retrieve function keys .. where the functions pass deployment step but listingkeys step which fails.

Thank you, hope i gave enough details :D

**Comment by HassanBadir** [comment]
as for creating zip file in the sitePackages file it's been creating zip lately after i updated the API versions not sure if that's related or not.

as for the other problem i m still facing still couldn't find a solution:

the problem:

I have multiple azure functions, some of them HTTP triggered so I use list-keys to list the functions keys in KeyVault to use later to Trigger them.

I use ARM Template as well to do this step (i deploy functions before and have dependency).

if i use WEBSITE_RUN_FROM_PACKAGE, this step fails with this error:

![image](https://user-images.githubusercontent.com/37299319/104915033-b7e3e900-5998-11eb-892d-6429339d56e2.png)

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
