### ISSUE TITLE
Site Credential changed after web app backup restore? 

### ISSUE THREAD

**Issue by Kapkan-Lesion** [projectkudu/kudu#3261]
Hi,

A rather simple yet strange question. 

We know that there's a single set of **Site/App Credential** which can be used for deployment purposes. **userPWD** inside the web app's given publish profile can be leveraged to execute deployment operations at commandline. 

We use MsBuild CLI with the userPWD inside publishing profile on an Azure web app to deploy our apps to azure. Previously we have assumed that this userPWD is static, in that it will not change regardless of the management operations happening to this web app. 

However, just now I did a backup & restore with this web app to test certain scenarios where the userPWD may change. I was under the impression that a restore should not change the publishing profile, but surprisingly enough this was changed. 

I did a quick repro with a blank web app, this time, however, restore conserved the original userPWD inside the publishing profile, nothing was touched there. 

Was wondering why did this happen? Are there any scenarios where site credential will change without us touching it (or resetting it)?

Thanks!

**Comment by suwatch** [comment]
Not kudu related - please post this question on on stackoverflow or msdn forum.
