### ISSUE TITLE
Kudu & Kudu Lite Version history seems not updated.

### ISSUE THREAD

**Issue by yutaro113** [projectkudu/kudu#3263]
Hello, this seems documentation issue but version history page of Kudu and Kudu Lite seems not updated recently.
Is there any way for user to notice the major change which will have impact on their usage. (like Kudu API output change etc..)
Or should this page be maintained? 

Kindly confirm and Thank you very much in advance!

https://github.com/projectkudu/kudu/wiki/Version-history
> ---------------------------------------------------------------

### Repro steps.
> your project built successfully on your dev machine but failed on Azure?
> please write down your build tools and their versions (ie `Msbuild 15.1.0.0`)

### Project structures.
> in order to reproduce your issue at our end we need a simple 
> [github repository](https://github.com/projectkudu/kudu/wiki/Using-a-git-repo-to-report-an-issue)
> that highlights structure of the project

### The log/error given by the failure.
> Normally this include a stack trace, error code and some more information.

### Debug your Azure website remotely.
> it is recommanded that you share your Web App name, directly or [indirectly](https://github.com/projectkudu/kudu/wiki/Reporting-your-site-name-without-posting-it-publicly)
> we can take a look at what's going on.

### Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by suwatch** [comment]
Unfortunately, it hasn't been maintained for awhile.

**Comment by yutaro113** [comment]
@suwatch Thanks for the quick confirmation. Understood this page is currently not maintained. Then is there any way for User to notice the major design change like Kudu API output..?

**Comment by suwatch** [comment]
Any particular issue you are running into?
