### ISSUE TITLE
Some Kudu REST-APIs like "api/logs/docker/zip" are not mentioned in the Wiki.

### ISSUE THREAD

**Issue by yutaro113** [projectkudu/kudu#3264]
In the below Kudu API page, some API like "api/logs/docker/zip" seems not mentioend.
Should this page be updated?

https://github.com/projectkudu/kudu/wiki/REST-API

Kindly confirm and Thank you very much in advance!

> ---------------------------------------------------------------

### Repro steps.
> your project built successfully on your dev machine but failed on Azure?
> please write down your build tools and their versions (ie `Msbuild 15.1.0.0`)

### Project structures.
> in order to reproduce your issue at our end we need a simple 
> [github repository](https://github.com/projectkudu/kudu/wiki/Using-a-git-repo-to-report-an-issue)
> that highlights structure of the project

### The log/error given by the failure.
> Normally this include a stack trace, error code and some more information.

### Debug your Azure website remotely.
> it is recommanded that you share your Web App name, directly or [indirectly](https://github.com/projectkudu/kudu/wiki/Reporting-your-site-name-without-posting-it-publicly)
> we can take a look at what's going on.

### Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by suwatch** [comment]
It is not part of this public kudu.  It is internal fork for Linux usage.

**Comment by yutaro113** [comment]
Thanks for the quick confirmation!

Understood this API is belonging not to public Kudu but to kudu for Linux.
Should any page (Kudu Lite wiki?) be updated for it? In the MS Docs, this API is mentioned but there seems no corresponding explanation in Kudu / KuduLite wikis.
https://docs.microsoft.com/en-us/azure/app-service/troubleshoot-diagnostic-logs#access-log-files
