### ISSUE TITLE
Writing temporary data to azure app service question

### ISSUE THREAD

**Issue by vinceve** [projectkudu/kudu#3267]
> For deployment issues, please provide us with the following information:
> ---------------------------------------------------------------

### Repro steps.
> your project built successfully on your dev machine but failed on Azure?
> please write down your build tools and their versions (ie `Msbuild 15.1.0.0`)

1. Use a linux docker image with Mapproxy (https://github.com/kartoza/docker-mapproxy/blob/master/Dockerfile)
2. We add a cache folder to our container

```
  FROM kartoza/mapproxy:latest
  
  COPY file.yaml /mapproxy/mapproxy.yaml
  COPY cache_data/ /mapproxy/cache_data/
  
  USER root
  
  RUN chmod -R 777 /mapproxy
  RUN chown -R mapproxy /mapproxy

  USER mapproxy
```

3. We deploy this on an Azure app service (via azure devops)
4. In the logs we see the following:

```
2021-01-27T15:59:42.983486075Z PermissionError: [Errno 13] Permission denied: '/mapproxy/./cache_data/tile_locks'
2021-01-27T15:59:42.983489375Z fatal error in wmts for /wmts/satellite/webmercator/7/46/41.png?
```

So my question is: Is it possible to generate temporary data in the azure app service itself? And if not, how to solve this problem? Is there another way to write my cache somewhere? Note that this is temporary data (and that I don't mind when a restart occurs that it is gone) and that I rather would not use a virtual disk.

**Comment by suwatch** [comment]
@sanchitmehta  / @purva-vasudeo  could you help with this?
