### ISSUE TITLE
Kudu controller adds extra deployment when processing ZIP and WAR  

### ISSUE THREAD

**Issue by JasonFreeberg** [projectkudu/kudu#3268]
When deploying with GitHub Actions (uses /zipdeploy and /wardeploy) Kudu adds an extra deployment object in the `/deployments` list. This clutters the deployments list, and the deployment logs are stored in this extra object, not in the deployment object from GitHub Actions, so it's hard for users to find the right logs.

- It looks like the message is added to every push deployment handler: https://github.com/projectkudu/kudu/blob/13824205c60a4bdb53896b9553ef1f370a93b911/Kudu.Services/Deployment/PushDeploymentController.cs#L34
- This method adds the deployment to the deployments API: https://github.com/projectkudu/kudu/blob/13824205c60a4bdb53896b9553ef1f370a93b911/Kudu.Core/Deployment/ArtifactDeploymentInfo.cs#L8

**Comment by ehamai** [comment]
Just a little more context.  Since the extra deployment object isn't tied to a real commit id, this affects the portal experience because it means that we're not able to group all the logs from GitHub Actions to Zip Deploy based on commit id.

@suwatch do you know who we should talk to about this by chance?

**Comment by suwatch** [comment]
There were 2 calls making to KUDU from Github action – both instructed Kudu to create deployment entry (one being ZipDeploy and another to create deployment entry).   I would follow up to the team owning github action task on DevOps.

**Comment by JasonFreeberg** [comment]
Thanks Suwat! I'll follow up with them.

Best,
Jason

**Comment by suwatch** [comment]
Wonderful.   Will close this for now.
