### ISSUE TITLE
Cannot delete file named con.config from Kudu API.

### ISSUE THREAD

**Issue by gkgaurav31** [projectkudu/kudu#3270]
A file named con.config was created under D:\home\site\wwwroot during deployment (not sure how). We were getting HTTP 404 when trying to delete it from Kudu the kudu console via UI:

![image](https://user-images.githubusercontent.com/9574170/108669920-f6267800-7503-11eb-989e-045d9ab093ae.png)

We were able to delete it via cmd in Kudu. 

However, we also noticed that the same issue happens if we create a file named con.config manually from kudu. (It works well for other files.)

**Steps to reproduce:**

- Go to Kudu console of a Windows WebApp
- Create a file named con.config under D:\home\site\wwwroot
- Try to delete via kudu console UI (it fails)
- Try to delete from cmd (it works)

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
