### ISSUE TITLE
unable to store folder in /usr/share/fonts 

### ISSUE THREAD

**Issue by DVGY** [projectkudu/kudu#3272]
I SSH into my `https://xxxxx.scm.azurewebsites.net/webssh/host`

I moved a folder into /usr/share/fonts and I was following the below guide. 

```
cd fonts
mv *.ttf /usr/share/fonts/truetype
cd /usr/share/fonts/truetype
mkfontscale
mkfontdir
fc-cache
xset fp rehash
```

I came back again, and I could not find my folder. How can i store a folder permanently ?

**Comment by DVGY** [comment]
@suwatch can you redirect me to appropriate  GitHub repo  so that my question can be answered ?

**Comment by suwatch** [comment]
This is Linux correct?

**Comment by DVGY** [comment]
> This is Linux correct?

Yes this is linux. I think it is debian
