### ISSUE TITLE
Kudu Deployment Locking Exception: Building From Azure Pipeline

### ISSUE THREAD

**Issue by Westmorland** [projectkudu/kudu#3279]
### Repro steps.
The project builds locally and runs fine. The solution has been deployed (Built using DotNetCoreCLI@2) to another environment successfully. The issue started Friday 19/03/2021. The problem is difficult to repo and seems to stop at different points during the deployment.

### Project structures.
The project is 13 API functions (.NET Core 3.1) on a basic app service plan. 

### The log/error given by the failure.

**Azure pipeline error:**

`2021-03-22T20:30:30.3057723Z Thread was being aborted.
2021-03-22T20:30:30.3059955Z ##[error]Failed to deploy web package to App Service.`

**Kudu Trace:**

```
<step title="BackgroundTrace" date="2021-03-22T20:30:18.573" instance="568aee" url="/api/zipdeploy" method="POST" >
  <step title="LockFile &apos;C:\home\site\locks\deployments.lock&apos; acquired" date="2021-03-22T20:30:18.636" /><!-- duration: 31ms -->
  <step title="Creating temporary deployment" date="2021-03-22T20:30:18.698" /><!-- duration: 219ms -->
  <step title="Performing fetch based deployment" date="2021-03-22T20:30:18.948" >
    <step title="Cleaning up temp folders from previous zip deployments and extracting pushed zip file C:\local\Temp\zipdeploy\5bzcw1uq.zip (15.52 MB) to C:\local\Temp\zipdeploy\extracted" date="2021-03-22T20:30:19.323" >
      <step title="Extracting 148 entries to C:\local\Temp\zipdeploy\extracted directory" date="2021-03-22T20:30:19.370" >
        <step title="Extracting to C:\local\Temp\zipdeploy\extracted\BidProcessor\function.json ..." date="2021-03-22T20:30:19.417" /><!-- duration: 31ms -->
        <step title="Extracting to C:\local\Temp\zipdeploy\extracted\BidProcessorParameters\function.json ..." date="2021-03-22T20:30:19.464" /><!-- duration: 31ms -->
        <step title="Extracting to C:\local\Temp\zipdeploy\extracted\BidProcessor_AbandonBid\function.json ..." date="2021-03-22T20:30:19.526" /><!-- duration: 31ms -->
        <step title="Extracting to C:\local\Temp\zipdeploy\extracted\BidProcessor_GetBlobPaths\function.json ..." date="2021-03-22T20:30:19.589" /><!-- duration: 31ms -->
        <step title="Extracting to C:\local\Temp\zipdeploy\extracted\BidProcessor_IsWorthProgressing\function.json ..." date="2021-03-22T20:30:19.839" /><!-- duration: 31ms -->
        <step title="Omitting extracting file traces ..." date="2021-03-22T20:30:19.901" /><!-- duration: 31ms -->
      </step><!-- duration: 1828ms -->
    </step><!-- duration: 1938ms -->
    <step title="DeploymentManager.Deploy(id:c09f57ede6f549bb913d4a0004395df7)" date="2021-03-22T20:30:21.292" >
      <step title="Collecting changeset information" date="2021-03-22T20:30:21.386" /><!-- duration: 344ms -->
      <step title="Updating submodules" date="2021-03-22T20:30:21.761" /><!-- duration: 297ms -->
      <step title="LockFile &apos;C:\home\site\locks\deployments.lock&apos; released" date="2021-03-22T20:30:22.589" /><!-- duration: 16ms -->
      <step title="Error occurred" date="2021-03-22T20:30:22.948" type="error" text="Thread was being aborted." stackTrace="   at System.Threading.Monitor.ObjWait(Boolean exitContext, Int32 millisecondsTimeout, Object obj)
   at System.Threading.Monitor.Wait(Object obj, Int32 millisecondsTimeout, Boolean exitContext)
   at System.Threading.Monitor.Wait(Object obj, Int32 millisecondsTimeout)
   at System.Threading.ManualResetEventSlim.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.SpinThenBlockingWait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.InternalWait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Kudu.Core.Deployment.FetchDeploymentManager.&lt;&gt;c__DisplayClass11_1.&lt;PerformBackgroundDeployment&gt;b__3() in C:\Kudu Files\Private\src\master\Kudu.Core\Deployment\FetchDeploymentManager.cs:line 339
   at Kudu.Contracts.Infrastructure.LockExtensions.TryLockOperation(IOperationLock lockObj, Action operation, String operationName, TimeSpan timeout) in C:\Kudu Files\Private\src\master\Kudu.Contracts\Infrastructure\LockExtensions.cs:line 34
   at Kudu.Contracts.Infrastructure.LockExtensions.LockOperation(IOperationLock lockObj, Action operation, String operationName, TimeSpan timeout) in C:\Kudu Files\Private\src\master\Kudu.Contracts\Infrastructure\LockExtensions.cs:line 46
   at Kudu.Core.Deployment.FetchDeploymentManager.&lt;&gt;c__DisplayClass11_0.&lt;PerformBackgroundDeployment&gt;b__1() in C:\Kudu Files\Private\src\master\Kudu.Core\Deployment\FetchDeploymentManager.cs:line 323" /><!-- duration: 31ms -->
    </step><!-- duration: 1703ms -->
```

### Debug your Azure website remotely.
Subscription Guid: d88498da-####-####-####-2da386bf3072

Error URL:
https://sal########et-dev-######-api-###ding.scm.azurewebsites.net/api/vfs/LogFiles/kudu/trace/2021-03-22T20-30-18_568aee_003_Background_POST_api-zipdeploy_pending.xml

### Mention any other details that might be useful.
A recent change made to file where the exception is being thrown:

[FetchDeploymentManager.cs](https://github.com/projectkudu/kudu/blob/master/Kudu.Core/Deployment/FetchDeploymentManager.cs)

This has only started happening since 19/03/21.

EDIT (23/03/2021):

After looking at the trace logs again I can see an exception was thrown:

`<exception>System.Threading.ThreadAbortException: Thread was being aborted. at Microsoft.Win32.Win32Native.GetFileType(SafeFileHandle handle) at Microsoft.Win32.Win32Native.SafeCreateFile(String lpFileName, Int32 dwDesiredAccess, FileShare dwShareMode, SECURITY_ATTRIBUTES securityAttrs, FileMode dwCreationDisposition, Int32 dwFlagsAndAttributes, IntPtr hTemplateFile) at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost) at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share) at System.IO.Abstractions.FileWrapper.Open(String path, FileMode mode, FileAccess access, FileShare share) at Kudu.Core.Infrastructure.FileSystemHelpers.AppendAllTextToFile(String path, String content) in C:\Kudu Files\Private\src\master\Kudu.Core\Infrastructure\FileSystemHelpers.cs:line 196 at Kudu.Core.Tracing.XmlTracer.WriteStartElement(String title, IDictionary2 attribs) in C:\Kudu Files\Private\src\master\Kudu.Core\Tracing\XmlTracer.cs:line 123</exception>`

**Comment by suwatch** [comment]
See if [this common issue](https://github.com/projectkudu/kudu/wiki/WEBSITE_RUN_FROM_PACKAGE-and-WEBSITE_CONTENTAZUREFILECONNECTIONSTRING-Best-Practices) applies to your scenario.

**Comment by Westmorland** [comment]
Thanks will take a look

**Comment by Westmorland** [comment]
I've looked through the common issues provided and I've noticed that WEBSITE_RUN_FROM_PACKAGE=1 in the azure function configuration. 

The documentation says this is automatically added however this does not seem to be the case for this environment. As a test, I added it to the ARM template deployment script and the build successes. However, when I checked the functions there were no function endpoints listed.

**Comment by Westmorland** [comment]
After speaking with Microsoft Support it looks like the following was missing from my build/deployment scripts:

ARM:

For each resource being deployed the below configuration properties were needed:

`"WEBSITE_RUN_FROM_PACKAGE": 1`
`"WEBSITE_ENABLE_SYNC_UPDATE_SITE": true`

YAML:

Next the build script in my case the YAML required a deployment method to be set. This was initially set to "auto". I've updated this to:

`deploymentMethod: "runFromPackage"`
