### ISSUE TITLE
Cannot get Azure environment variable WEBSITE_INSTANCE_ID

### ISSUE THREAD

**Issue by WenJinfeng** [projectkudu/kudu#3280]
WEBSITE_INSTANCE_ID does not exist in the environment variable, please help me. Thanks!

**Comment by CynthiaWendy** [comment]
In python applications, I obtain all environment variables by using the command "os.environ", but the parameter WEBSITE_INSTANCE_ID can not find.

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
