### ISSUE TITLE
Incrementally add function to Azure Function Host without overwriting already deployed functions

### ISSUE THREAD

**Issue by christian-vorhemus** [projectkudu/kudu#3281]
I'm working with multiple teams that develop & test Azure Functions independently from each other but want to deploy all functions to a centralized Azure Function host, like so:

![deployment](https://user-images.githubusercontent.com/3229424/112200019-1898d780-8c0f-11eb-9b7f-31cdf72bb51a.png)

The publishing methods I know overwrite the existing content on the host which is not wanted, we strive for an **incremental update**.

My question is: What is the easiest way to do this (assuming that hosts.json and function settings are the same for both projects)?

If team A runs

`curl -X POST -u <user> --data-binary @"./func1-2.zip" https://<funcname>.scm.azurewebsites.net/api/zipdeploy`

in their release pipeline and afterwards team B runs

`curl -X POST -u <user> --data-binary @"./func3-4.zip" https://<funcname>.scm.azurewebsites.net/api/zipdeploy`

func1 and func2 from team A are gone. Using PUT on the `https://<funcname>.scm.azurewebsites.net/api/zip/` endpoint as indicated [here](https://github.com/projectkudu/kudu/wiki/REST-API#zip) didn't seem to publish the functions at all. When using FTP, I don't see any files in site/wwwroot/ at all, even after already publishing functions. Sidenote: Azure Python functions on Linux are used here.

**Comment by suwatch** [comment]
The deployment semantic will ensure latest content (and only latest content - eg. removing the old one).   It is not intended for two sources to mix and merge into the same app.   If you want the latter, you simply want to do a pure file transfer (no deployment semantic).   You can use FTP or POST /api/zip/site/wwwroot/ to place any files to wwwroot directly.

**Comment by christian-vorhemus** [comment]
How does the URI and payload have to look like when I want to deploy using the POST /api/zip/site/wwwroot/ endpoint? When I pack the function directories individually into a zip file and do a `curl -X POST -u <username> --data-binary @"./func1.zip" https://<functionname>.scm.azurewebsites.net/api/zip/site/wwwroot/`  func1 doesn't show up in the portal.

If I simply use a FTP client to put the func1 and func2 directories into the site/wwwroot/ folder, they are present there
![1](https://user-images.githubusercontent.com/3229424/112437368-2b162c80-8d47-11eb-91ca-928a21e8f2c0.png)

but in the portal I still see only func3 and func4 (those I deployed using /api/zipdeploy)
![2](https://user-images.githubusercontent.com/3229424/112437384-2ea9b380-8d47-11eb-9cfe-1bf699bbb86f.png)

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
