### ISSUE TITLE
KuduSync Ignoring File Case Change on Linux

### ISSUE THREAD

**Issue by owenneil** [projectkudu/kudu#3282]
### Repro steps.
I deployed a project to a linux appservice using ZipDeploy (RunFromPackage=0) that used a file named appsettings.Int.json. Later, this file was renamed to appsettings.int.json and deployed again. The deployment completed without error, but the file would not load. Upon checking it, I see that on the service it is still named appsetting.Int.json. I deployed several more times with the same result, then finally deleted the file from the instance directly using the Bash console and redeployed. After this the file was copied correctly using the correct casing. 

### Mention any other details that might be useful.
I'm not sure, but it appears the KuduSync code is using case-insensitive comparisons at all times. This should might need to be adjusted when running on Linux.

**Comment by suwatch** [comment]
@purva-vasudeo  could you help with this - especially the case in-sensitive part suggestion about KuduSync?

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
