### ISSUE TITLE
Communicating between Web App site process and SCM

### ISSUE THREAD

**Issue by k15tfu** [projectkudu/kudu#3285]
Hi!

I want to do some service module which is loaded into my Web App, and then connects to the host process (some kind of controller, actually) running from Kudu console (SCM). But it is not entirely clear what kind of communication (sockets, named pipes, files, other options?) are supposed to work in this case. Can anyone shed some light on this?

1. Does Kudu console run in a separate sandbox? It seems that yes: _Each app is viewed by the sandbox as a tree of processes, rooted by the app's main IIS (w3wp.exe) process_ (https://github.com/projectkudu/kudu/wiki/Azure-Web-App-sandbox#definition-of-the-sandbox), but the other places state it doesn't: _The Kudu site runs in the same sandbox as the real site [...]_ (https://github.com/projectkudu/kudu/wiki/Kudu-architecture#security-model), and _The Kudu service site runs in the same sandbox as the site. By default, it runs in the different process as the site_ (https://github.com/projectkudu/kudu/wiki/Kudu-architecture#process-model).

2. Is it possible to use named pipes for communication in this case? It works now, but according to the docs it shouldn't (suppose the answer to 1. is Yes): _Within the sandbox, applications can create named pipes which accessible only within the sandbox (much like how listen sockets are allowed within sandbox)_ (https://github.com/projectkudu/kudu/wiki/Azure-Web-App-sandbox#named-pipes). Why does it work for different sandboxes and can we rely on this in the future?

3. Is it possible to use TCP sockets for communication in this case? Seems that it doesn't work, but according to this page https://github.com/projectkudu/kudu/wiki/Azure-Web-App-sandbox#named-pipes it should work in all cases when named pipes works.

4. Is there a local folder that can be accessed (read/write) both for Web App site and the process running from Kudu console?
It seems that they both can access files in D:\local\Temp, and it should work: _The only thing that really 'connects' the Kudu site to the real site is the file system, and that works regardless of what process or machine they each run on_ (https://github.com/projectkudu/kudu/wiki/Kudu-architecture#process-model), _You can use it to do most standard console operations: changing folder, copy/rename/delete files, etc_ (https://github.com/projectkudu/kudu/wiki/Kudu-console#use-it-to-run-commands-for-example-git-operations),
but in the other places say it is not accessible: _Note that the d:\local folder in the scm site (where Kudu runs) is not the same as the one in the main site (where the web app runs). As a result, they cannot see each other's local files._ (https://github.com/projectkudu/kudu/wiki/Azure-Web-App-sandbox#local-directory-access-dlocal), _With separation, the Main and scm sites each have their own local files. So you won't see the Main site's temp files from Kudu console._ (https://github.com/projectkudu/kudu/wiki/Configurable-settings#use-the-same-process-for-the-user-site-and-the-scm-site), _Another important note is that the Main site and the scm site do not share temp files. So if you write some files there from your site, you will not see them from Kudu Console (and vice versa). You can make them use the same temp space if you disable separation (via WEBSITE_DISABLE_SCM_SEPARATION). But note that this is a legacy flag, and its use is not recommended/supported._ (https://github.com/projectkudu/kudu/wiki/Understanding-the-Azure-App-Service-file-system#temporary-files).
Why does it work and can we rely on this in the future?

5. Does Web App on Linux have the same restrictions? Is it possible to configure access to local folder for Web App and SCM, and can we use TCP / named pipes for communication?

6. With WEBSITE_DISABLE_SCM_SEPARATION option enabled, we can use TCP and access local files. But this option is considered to be a legacy mode that is no longer fully supported, and it doesn't exist on Linux. Are there any other options what I can use/do? Can Web Sockets (https://docs.microsoft.com/en-us/azure/app-service/faq-app-service-linux#web-sockets) or VNet (https://docs.microsoft.com/en-us/azure/virtual-network/virtual-networks-faq) help me somehow?

Thanks in advance!

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
