### ISSUE TITLE
Ability to Disable 'Efficient file copy' on zip deployments

### ISSUE THREAD

**Issue by MNashDev** [projectkudu/kudu#3287]
We are hitting issues with how Kudu does its 'Efficient file copy' when doing a zip deployment.

> 'Efficient file copy: Files will only be copied if their timestamps don't match what is already deployed. Generating a zip using a build process that caches outputs can result in faster deployments.'
https://github.com/projectkudu/kudu/wiki/Deploying-from-a-zip-file-or-url

We have files within our zip that keep appearing as if they were created on the 1/1/1980 12:00am, this happens every single deployment, even after the filesc are manually removed, which means the file timestamps are not being recognised as 'updated' and so the files are not updating.

![image](https://user-images.githubusercontent.com/13762297/114573302-2bcc1f80-9c70-11eb-9c7c-9cbeed8511c3.png)
You can see here the handler.js and handler.js.map files both have the 1/1/1980 12:00am timestamp.

Options for resolution I can see are:

* Set a variable at deployment time to 'Clean directory before deployment', removing all the files in the wwwroot folder so that it writes all the files again. (Similar suggestion here : #2596 )
* Set a variable to disable the 'Efficient file copy' so all the files in the wwwroot folder are overwritten.
* Update the 'Efficient file copy' so that it is not only looking at the timestamp, but is looking at other file details such as size aswell.

**Comment by suwatch** [comment]
Mind trying [this solution](https://github.com/projectkudu/kudu/wiki/Deploying-from-a-zip-file-or-url#issues-and-investigation) originally intended for different issue - see if it solves issue for you.

**Comment by MNashDev** [comment]
That has worked, Thank you very much!

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
