### ISSUE TITLE
Linux vs Windows App Service Plans

### ISSUE THREAD

**Issue by carlo-quinonez** [projectkudu/kudu#3290]
This may not be the right forum for this question, if so, please let me know a better place to ask.

So we've got a mixed environment of AppServices from Code and Containers running on Linux App Service Plans. Our company CIS team recently asked us to integrate into our corporate Signal Sciences account.

Fortunately, there's an AppService [site extension for Signal Sciences](https://docs.fastly.com/signalsciences/install-guides/paas/azure-app-service/).

Unfortunately doesn't seem like linux App Services support extensions nor a single Windows appservice plan can not run apps from both containers and code.

Is this correct?

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
