### ISSUE TITLE
409 When Attempting To Run Parallel Triggered Webjobs

### ISSUE THREAD

**Issue by gasserma** [projectkudu/kudu#3291]
Hi,

My goal, which I thought would be relatively straightforward, is to run a manually triggered webjob concurrently. 

The simple repro version of this is: I have a manually triggered python webjob that sleeps for 10 minutes and intermittently prints a message. I want to be able to invoke it such that I have two of those jobs running at once.

I have two instances in my app service plan, set to always on, and a pricing tier at Production - P1V2. I have navigated to the D:\home\site\wwwroot\App_Data\jobs\triggered\PythonTest directories in both instances and found the python script.

I am triggering the job using the kudu API and the first time I trigger I get a 202, then I get 409s until the 10 minutes have passed and the first job completes. I have no settings.job file, so I don't believe I have these set to singleton accidentally. I can see the python script doing exactly what I think it should be doing in the logs and it is very simple, so I don't think it is the issue.

Apologies in advance if this is something obvious I missed in the documentation.

Thanks in advance regardless :)

**Comment by suwatch** [comment]
By design, only one running instance per triggered job is allowed.

**Comment by gasserma** [comment]
Ah, that is a shame from my perspective. 

1. Are there any common workarounds people use here? I'm considering just deploying N of my jobs like <jobname[1-N]> or something like that.
2. If it would be possible to change the documentation on this I think it might be helpful to others. Neither https://docs.microsoft.com/en-us/azure/app-service/webjobs-create or https://github.com/projectkudu/kudu/wiki/WebJobs-API gave me the impression manually triggered jobs couldn't scale out. The two changes I might make are 
  a. https://github.com/projectkudu/kudu/wiki/WebJobs-API: List the possible 409 in the kudu api docs and change "This is the same behavior as regular requests sent to the site." which makes it seem like triggered jobs will run concurrently.
  b. https://docs.microsoft.com/en-us/azure/app-service/webjobs-create:Change "Runs on a single instance that Azure selects for load balancing." to "Runs on a single instance that Azure selects for load balancing. Concurrently invocations are not supported."

**Comment by RES-TophWells** [comment]
I am also having trouble with this. Are there any recommended workarounds?

**Comment by gasserma** [comment]
We ended up going with azure functions, and using blob triggers to get around timing issues related to http triggers.

**Comment by RES-TophWells** [comment]
Thanks! I'll look into it.

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
