### ISSUE TITLE
System.UnauthorizedAccessException: Attempted to perform an unauthorized operation. at Microsoft.Win32.RegistryKey.Win32Error

### ISSUE THREAD

**Issue by jayendranarumugam** [projectkudu/kudu#3296]
All of sudden Its actually  happened again ,https://github.com/Azure/azure-functions-host/issues/5893

Dotnet Core 3.1

StackTrace:

```
remote: System.UnauthorizedAccessException: Attempted to perform an unauthorized operation.        
remote:    at Microsoft.Win32.RegistryKey.Win32Error(Int32 errorCode, String str)        
remote:    at Microsoft.Win32.RegistryKey.SetValueCore(String name, Object value, RegistryValueKind valueKind)        
remote:    at Microsoft.Win32.RegistryKey.SetValue(String name, Object value, RegistryValueKind valueKind)        
remote:    at Microsoft.DotNet.Cli.Utils.WindowsRegistryEnvironmentPathEditor.Set(String value, SdkEnvironmentVariableTarget sdkEnvironmentVariableTarget)        
remote: Failed exitCode=1, command=dotnet restore "C:\home\site\repository\Test.sln"        
remote:    at Microsoft.DotNet.ShellShim.WindowsEnvironmentPath.AddPackageExecutablePathToUserPath()        
remote: An error has occurred during web site deployment.        
remote:    at Microsoft.DotNet.Configurer.DotnetFirstTimeUseConfigurer.Configure()        
remote:    at Microsoft.DotNet.Cli.Program.ConfigureDotNetForFirstTimeUse(IFirstTimeUseNoticeSentinel firstTimeUseNoticeSentinel, IAspNetCertificateSentinel aspNetCertificateSentinel, IFileSentinel toolPathSentinel, Boolean isDotnetBeingInvokedFromNativeInstaller, DotnetFirstRunConfiguration dotnetFirstRunConfiguration, IEnvironmentProvider environmentProvider)        
remote:    at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)        
remote:    at Microsoft.DotNet.Cli.Program.Main(String[] args)      
```

Fix worked for me is `DOTNET_ADD_GLOBAL_TOOLS_TO_PATH=false`

Would like to confirm this is really a fix ? or a workaround ?

**Comment by suwatch** [comment]
It is a workaround for dotnet restore issue.   BTW, this is not the default Kudu build experience - I assume you are doing custom deployment of some sort.   Otherwise, we would have had more complaints from many users.

**Comment by jcbartle** [comment]
Morning, folks. @suwatch - this error just started cropping up on Friday (March 4th, 2022) when deploying code to an app service in my development tenant. I found this thread today and tried the workaround of adding an app setting for DOTNET_ADD_GLOBAL_TOOLS_TO_PATH = false. This fixed the issue. I'm not seeing similar behavior in my production tenant, thankfully. I'm using the standard zipdeploy process of:

az bot prepare-deploy --lang Csharp --code-dir "." --proj-file-path "<file_name>.csproj"
az webapp deployment source config-zip --resource-group "<resource_group_name>" --name "<app_service_name>" --src "<file_name>.zip"

This has been working for over a year without issue. Not sure what has caused this to suddenly crop up.
