### ISSUE TITLE
[ Question ] Log Retention Policy of Logs generated on home/LogFiles/Transform

### ISSUE THREAD

**Issue by yutaro113** [projectkudu/kudu#3298]
Hi, in the below docs, it would be helpful to get information about retention policy of xdt transform logs generated in home/LogFiles/Transform.

https://github.com/projectkudu/kudu/wiki/Azure-Site-Extensions#finding-the-log-of-what-happened-during-the-transform

Thank you very much in advance!

**Comment by suwatch** [comment]
Update the wiki.  No retention in term of datetime but rather keeping at most 40 recent log files.
