### ISSUE TITLE
applicationHost.xdt and applicationHost.config file disappear even if Transform logs exist.

### ISSUE THREAD

**Issue by yutaro113** [projectkudu/kudu#3301]
Hi Team, 
Is there any possiblity Kudu platform erace applicationHost.xdt / applicationHost.config after some time etc? (I suspect there was some explicit user operation to erase those)

**Backgroud:**
My customer is confusing about the situation above.

Based on the below guidance, Previously customer placed applicationHost.xdt file for transform and transform logs were generated under LogFiles/Transform.
https://github.com/projectkudu/kudu/wiki/Azure-Site-Extensions#top-level-private-extension

But on the other day when they check those again, applicationHost.xdt and applicationHost.config under %TMP% disappeared but transform logs exists as it is.

**Comment by suwatch** [comment]
Let's focus on files being removed first.  Kudu won't remove files - unless user explicit action, either thru deployment or plain old Debug Console and delete file.   We would suggest to try to narrow the time down (wait for it to repro again).  It might reveal more clues.

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
