### ISSUE TITLE
how to remove redundancy of schedule configuration for timer-triggered azure web job?

### ISSUE THREAD

**Issue by Liphi** [projectkudu/kudu#3303]
Hi, My timer-triggered azure web job is written with c# web job v3 SDK, and I use TimerTrigger attribute to decorate my timer callback. Problem is, this attribute has to take a schedule parameter in cron or scheduleType format, so i have to duplicate this schedule in both settings.job and TimerTrigger decorator. Is there any mechanism for my c# code to get the schedule from settings.job, so that in my code base i only need to define this schedule in 1 place (settings.job) ?
One work-around I can think of is to maybe define this web job as a continuous job, so that i don't need to config schedule on settings.job, and i only need to hard-code the schedule in c# code. But I feel it's not ideal.

        // timer callback
        public static async Task TimerCallback([TimerTrigger("0 0 */1 * * *")] TimerInfo timerInfo)
        {
            // business logic
        }

Any suggestion would be helpful. Thanks!

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
