### ISSUE TITLE
Proposed change for zip deployment wiki page

### ISSUE THREAD

**Issue by daveaglick** [projectkudu/kudu#3305]
Unfortunately PRs can't be opened against the GitHub wiki repo or I'd just make this directly. I propose adding some additional information to https://github.com/projectkudu/kudu/wiki/Deploying-from-a-zip-file-or-url in order to describe the expected result of polling for asynchronous success.

More specifically, under the heading "Asynchronous zip deployment" I propose adding:

> When polling the URL provided in the `Location` header, you will receive a HTTP 202 (Accepted) response while the process is ongoing and a HTTP 200 (OK) response once the archive has been expanded and the deployment has completed successfully.

The response codes make sense, but I couldn't find them documented anywhere and being explicit about it may save folks some trial-and-error time.

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
