### ISSUE TITLE
[VFS API] delete API call is returning 409 but still deleting directories.

### ISSUE THREAD

**Issue by msft-noorjaber** [projectkudu/kudu#3306]
### Issue
VFS delete endpoint /api/vfs/:path?recursive=true is deleting items although the returned status code is 409, 

### Repro
1. Go to kudu console and create a file with read-only access (/site/read-only.txt):![image](https://user-images.githubusercontent.com/85546535/121402727-ea4fac00-c962-11eb-9cdc-429a9e3347d7.png)
2. Execute the API call (/api/vfs/site?recursive=true).
3. Observe the returned message: ![image](https://user-images.githubusercontent.com/85546535/121401213-22ee8600-c961-11eb-85ea-0b240b2f50f5.png)
4. Navigate to kudu console and observe the deleted directories: 
![image](https://user-images.githubusercontent.com/85546535/121402847-05222080-c963-11eb-93e0-3298c356a238.png)

_**Note: check /Kudu.Services/Infrastructure/VfsControllerBase.cs:line 153**_

**Comment by suwatch** [comment]
When delete recursive, the windows iterates and deletes files one by one till completion or error.   Do try in on your local machine, see what the behavior is.

**Comment by msft-noorjaber** [comment]
That's correct Suwat, but isn't the error message somehow misleading?

**Comment by 0969397110** [comment]
> ### Issue
> 
> VFS delete endpoint /api/vfs/:path?recursive=true is deleting items although the returned status code is 409, 
> 
> 
> 
> ### Repro
> 
> 1. Go to kudu console and create a file with read-only access (/site/read-only.txt):![image](https://user-images.githubusercontent.com/85546535/121402727-ea4fac00-c962-11eb-9cdc-429a9e3347d7.png)
> 
> 2. Execute the API call (/api/vfs/site?recursive=true).
> 
> 3. Observe the returned message: ![image](https://user-images.githubusercontent.com/85546535/121401213-22ee8600-c961-11eb-85ea-0b240b2f50f5.png)
> 
> 4. Navigate to kudu console and observe the deleted directories: 
> 
> ![image](https://user-images.githubusercontent.com/85546535/121402847-05222080-c963-11eb-93e0-3298c356a238.png)
> 
> 
> 
> _**Note: check /Kudu.Services/Infrastructure/VfsControllerBase.cs:line 153**_

-

**Comment by 0969397110** [comment]
> > ### Issue
> > VFS delete endpoint /api/vfs/:path?recursive=true is deleting items although the returned status code is 409,
> > ### Repro
> > 
> > 1. Go to kudu console and create a file with read-only access (/site/read-only.txt):![image](https://user-images.githubusercontent.com/85546535/121402727-ea4fac00-c962-11eb-9cdc-429a9e3347d7.png)
> > 2. Execute the API call (/api/vfs/site?recursive=true).
> > 3. Observe the returned message: ![image](https://user-images.githubusercontent.com/85546535/121401213-22ee8600-c961-11eb-85ea-0b240b2f50f5.png)
> > 4. Navigate to kudu console and observe the deleted directories:
> > 
> > ![image](https://user-images.githubusercontent.com/85546535/121402847-05222080-c963-11eb-93e0-3298c356a238.png)
> > _**Note: check /Kudu.Services/Infrastructure/VfsControllerBase.cs:line 153**_

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
