### ISSUE TITLE
Kudu on permise - webjob continuous stopped every 15 minutes

### ISSUE THREAD

**Issue by michaelmarzouk** [projectkudu/kudu#3308]
Hello,

I use Kudu localy on my server and i host Webjobs with queue trigger. I see that every 15 minutes, Webjobs stopped. 

I see that on Azure you have Always On option and i try to add on Kudu Web.config file this option but it doesn't work:
<add key="WEBSITE_SCM_ALWAYS_ON_ENABLED" value="1" />

I also set the Application pool of my IIS kudu service web site on AlwaysRunning but no impact.

I then create a script that ping Kudu Api Webjob page every minute in order to keep the web site alive but still no effect.

Do you have any idea?

Thanks,

Michael

**Comment by suwatch** [comment]
This is more of an IIS question - how to keep w3wp running without incoming requests.   I would suggest to close this and post it on stackoverflow instead.

**Comment by michaelmarzouk** [comment]
Done https://stackoverflow.com/questions/68030626/kudu-on-permise-webjob-continuous-stopped-every-15-minutes
