### ISSUE TITLE
ZipDeploy ARM Template fails with (500) Internal Server Error: The response for resource had empty or invalid content.

### ISSUE THREAD

**Issue by BBergquist** [projectkudu/kudu#3310]
### Repro steps.
1. Create a template for a Linux web app
2. Try to deploy a package via the ZipDeploy subresource.

### The log/error given by the failure.
Status message from Deployment details:
```
{
    "status": "Failed",
    "error": {
        "code": "ResourceDeploymentFailure",
        "message": "The response for resource had empty or invalid content."
    }
}
```

### Debug your Azure website remotely.
Subscription: 7e48...07fe
Site Name: MTE...eus

### Mention any other details that might be useful.
From the Deployment details:
Request
```
{
    "content": {
        "properties": {
            "packageUri": "https://REDACTED.blob.core.windows.net/test/package.zip?sv=2019....",
            "AppOffline": "true"
        }
    }
}
```
Response
```
{
    "content": ""
}
```

When I look in the app logs, the deployment succeeds. It seems to just be an issue w/ the ARM integration.

**Comment by BBergquist** [comment]
@suwatch - it looks like you own the code? https://github.com/projectkudu/kudu/blob/b544b9813d93a7699c572bac8c1a615b61f00f44/Kudu.Services/Zip/ZipController.cs#L65

**Comment by suwatch** [comment]
@BBergquist  My apology I did not see the UTC time of the failure.  If you used ARM template, do provide correlationId as well.

@sanchitmehta / @purva-vasudeo  this is linux.  BTW, Kudu in Linux used a slightly different codes/repos.

**Comment by BBergquist** [comment]
The failure is persistent, across multiple tenants. One timestamp of a failure for that web app was: 6/24/2021, 01:26:15 (UTC)

**Comment by purva-vasudeo** [comment]
Hi @BBergquist , thanks for reporting this. 

We have a fix for this in our upcoming release. As a workaround you can use a raw ARM request for zipdeploy. One way to do this is via [ARMClient ](https://github.com/projectkudu/ARMClient)-

`ARMClient.exe put "/subscriptions/<SubscriptionId>/resourceGroups/<ResourceGroup>/providers/Microsoft.Web/sites/<SiteName>/extensions/ZipDeploy?api-version=2016-09-01"`
