### ISSUE TITLE
Access file created under /home/LogFiles in Linux based function app

### ISSUE THREAD

**Issue by shary-sharath** [projectkudu/kudu#3311]
I have a function app developed Python and it creates an output file something.txt at path given /home/LogFiles/.
I published this function app to portal, and I could see the file actually got created under /home/LogFiles but unfortunately I can't open it or I might not know how to do so.

I used Kudu to do this task, but all I can do is listing them in Bash terminal and nothing else.
Any help to access this file? or is there any better way to create output file on Azure?

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
