### ISSUE TITLE
Deployment from External Git with Bicep Template fails

### ISSUE THREAD

**Issue by Pietervanhove** [projectkudu/kudu#3312]
Hi,

Since last week, we noticed that our deployment of our Web App service is failing, which was working before.
I have created a Bicep Template file to deploy the App Service plan and the App Service. (see attachment)
The web site that I want to deploy is stored on my GitHub Repository, as you can see in the sourcecontrols section.
In the config section, I have configured an application setting "PROJECT", which points to the project file that is stored on my GitHub repository.

When I try to deploy my Bicep Template, the Deployment Center gets configured with my external Git Repository. However, I noticed that the PROJECT property is not created anymore. This causes a failure of the deployment with reason "Unable to determine which solution file to build." This is normal, because the PROJECT property is missing.

When I remove the App Service again, but I don't disconnect my External GitHub, and redeploy, it succeeds because the PROJECT property is configured.

So it seems when my GitHub repository is not connected yet to the deployment center, it is failing...

The Web App name is called eaeaedemoapp.

[WebApp.txt](https://github.com/projectkudu/kudu/files/6731823/WebApp.txt)
![Screenshot 2021-06-29 103346](https://user-images.githubusercontent.com/25530010/123764908-8830f980-d8c5-11eb-9586-64b102a49eee.jpg)

**Comment by suwatch** [comment]
It could be the limitation in App Settings api where it is async in nature (meaning may take time upto 10s to propagate to the VM even after the api returns successfully).   Try to put a delay (say 10s) (not sure if possible - not familiar with this bicep template) between the app settings and source control step and see it that helps or confirms it was an issue.

**Comment by Pietervanhove** [comment]
Hi Suwat,

Adding a delay in Bicep template is not possible.
However, I've found another workaround.
And you're indeed correct, with the delay between the app settings and the source control, the deployment works.

Thanks for the feedback!

Pieter

**Comment by click2install** [comment]
@Pietervanhove What was your workaround? Using `cli` instead, maybe? Have a similar case where I want to deploy an event grid subscription with the app as the webhook endpoint.

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
