### ISSUE TITLE
RBAC access role for Kudu

### ISSUE THREAD

**Issue by christopherwoodland** [projectkudu/kudu#3313]
Is it possible to access Kudu within an Azure Web Application with a read-only role or is the role of "contributor" required to access Kudu in the instance?

Thank you

**Comment by suwatch** [comment]
See if [this](https://github.com/projectkudu/kudu/wiki/Accessing-the-kudu-service#security) helps.

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
