### ISSUE TITLE
Request to support ARM async pattern for PUT / deployments API 

### ISSUE THREAD

**Issue by miyukiabe-baxter** [projectkudu/kudu#3314]
<html>
<body>
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; color: rgb(51, 51, 51); font-family: &quot;Segoe UI&quot;, &quot;Helvetica Neue&quot;, Arial, &quot;Noto Sans&quot;, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">If API PUT "deployments/{commtId}" call does not complete within 60 seconds, it is returning 499 with timeout error message. Once ARM call is timeout, the portal does not have a way to tell whether the deployment is still in progress, deployment completed or failed after this 60 seconds point. Ideally, we would like this API to support ARM async pattern so that the portal side can display the appropriate notification when the deployment is fully completed. </p>

<p> please take a look at this ICM for more details >>> <a href="https://portal.microsofticm.com/imp/v3/incidents/details/249645764/home" target="_blank">https://portal.microsofticm.com/imp/v3/incidents/details/249645764/home</a></p>

<p>Below is one of examples redeployment which did not complete within 60seconds. Therefore, ARM call was timeout and returning 499.</p>
<span style="color: rgb(51, 51, 51); font-family: &quot;Segoe UI&quot;, &quot;Helvetica Neue&quot;, Arial, &quot;Noto Sans&quot;, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">Execute in [</span><a href="https://dataexplorer.azure.com/clusters/azportalpartner/databases/AzurePortal?query=H4sIAAAAAAAAA22RzU4CMRSF9z5FwwZIZoZOYaYjhgVBE1lgiI4bd/25QIVpx/ZOiMaHt2oCRk266e2Xc885PQCSgDMtENA0MGCU5Snl8dSMTfNiynhWFeNiUlRPwytyiDj8h1c1pX/wC3XoAoIf9IVvWu90to93lx2N1e4YMgvYH2ZRTEgRYNCf36/WkYqzW8R2aZVrjN3ew0sHAcPFOznuwAOpl6ubh3q+WhMJeASwg4BZBjg8EaGTQXnTonF2qclsRnqXLC8V0+O0LLlIJ0oVqZywKpVFQSupFM+B9U4CKPwW8NEbopxFYWwgvT3o4Lo3kb45DyMN7cG9NmAxjKSimko94XIjohbltATGRVzIx6XKx4UWclNW/KwfkzXC6jvRwJc7D996izg3eOZ2sYcV4M59h1g/1p9vscpnUEjWHpQJUMefeEDRtAm5PrlKfpWQfGlFDLuwcBoSUouw/zSQ/NiSnJMnP01+AGHIDKUnAgAA" target="_blank" style="box-sizing: border-box; color: var(--primary); text-decoration: none; background-color: rgb(255, 255, 255); cursor: pointer; font-family: &quot;Segoe UI&quot;, &quot;Helvetica Neue&quot;, Arial, &quot;Noto Sans&quot;, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px;">Web</a><span style="color: rgb(51, 51, 51); font-family: &quot;Segoe UI&quot;, &quot;Helvetica Neue&quot;, Arial, &quot;Noto Sans&quot;, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">] [</span><a href="https://azportalpartner.kusto.windows.net/AzurePortal?query=H4sIAAAAAAAAA22RzU4CMRSF9z5FwwZIZoZOYaYjhgVBE1lgiI4bd/25QIVpx/ZOiMaHt2oCRk266e2Xc885PQCSgDMtENA0MGCU5Snl8dSMTfNiynhWFeNiUlRPwytyiDj8h1c1pX/wC3XoAoIf9IVvWu90to93lx2N1e4YMgvYH2ZRTEgRYNCf36/WkYqzW8R2aZVrjN3ew0sHAcPFOznuwAOpl6ubh3q+WhMJeASwg4BZBjg8EaGTQXnTonF2qclsRnqXLC8V0+O0LLlIJ0oVqZywKpVFQSupFM+B9U4CKPwW8NEbopxFYWwgvT3o4Lo3kb45DyMN7cG9NmAxjKSimko94XIjohbltATGRVzIx6XKx4UWclNW/KwfkzXC6jvRwJc7D996izg3eOZ2sYcV4M59h1g/1p9vscpnUEjWHpQJUMefeEDRtAm5PrlKfpWQfGlFDLuwcBoSUouw/zSQ/NiSnJMnP01+AGHIDKUnAgAA&amp;web=0" target="_blank" style="box-sizing: border-box; color: var(--primary); text-decoration: none; background-color: rgb(255, 255, 255); cursor: pointer; font-family: &quot;Segoe UI&quot;, &quot;Helvetica Neue&quot;, Arial, &quot;Noto Sans&quot;, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px;">Desktop</a><span style="color: rgb(51, 51, 51); font-family: &quot;Segoe UI&quot;, &quot;Helvetica Neue&quot;, Arial, &quot;Noto Sans&quot;, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">] [</span><a href="https://dataexplorer.azure.com/clusters/azportalpartner/databases/AzurePortal" target="_blank" style="box-sizing: border-box; color: var(--primary); text-decoration: none; background-color: rgb(255, 255, 255); cursor: pointer; font-family: &quot;Segoe UI&quot;, &quot;Helvetica Neue&quot;, Arial, &quot;Noto Sans&quot;, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px;">cluster('azportalpartner.kusto.windows.net').database('AzurePortal')</a><span style="color: rgb(51, 51, 51); font-family: &quot;Segoe UI&quot;, &quot;Helvetica Neue&quot;, Arial, &quot;Noto Sans&quot;, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">]</span><span style="box-sizing: border-box; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; color: rgb(0, 128, 0); background-color: rgb(255, 255, 254); font-family: Consolas, &quot;Courier New&quot;, monospace; font-size: 14px; white-space: pre;"></span><div style="box-sizing: border-box; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; color: rgb(0, 0, 0); background-color: rgb(255, 255, 254); font-family: Consolas, &quot;Courier New&quot;, monospace; font-size: 14px; line-height: 19px; white-space: pre;"><div style="box-sizing: border-box;"><span style="box-sizing: border-box; color: rgb(0, 128, 0);"></span></div><div style="box-sizing: border-box;">let st=<span style="box-sizing: border-box; color: rgb(0, 0, 255);">datetime</span>(<span style="box-sizing: border-box; color: rgb(25, 25, 112);">2021</span>-<span style="box-sizing: border-box; color: rgb(25, 25, 112);">07</span>-<span style="box-sizing: border-box; color: rgb(25, 25, 112);">07</span>T22<span style="box-sizing: border-box; color: rgb(205, 49, 49);">:</span><span style="box-sizing: border-box; color: rgb(25, 25, 112);">15</span><span style="box-sizing: border-box; color: rgb(205, 49, 49);">:</span><span style="box-sizing: border-box; color: rgb(25, 25, 112);">27.8535458</span>Z); let et=<span style="box-sizing: border-box; color: rgb(0, 0, 255);">datetime</span>(<span style="box-sizing: border-box; color: rgb(25, 25, 112);">2021</span>-<span style="box-sizing: border-box; color: rgb(25, 25, 112);">07</span>-<span style="box-sizing: border-box; color: rgb(25, 25, 112);">08</span>T00<span style="box-sizing: border-box; color: rgb(205, 49, 49);">:</span><span style="box-sizing: border-box; color: rgb(25, 25, 112);">15</span><span style="box-sizing: border-box; color: rgb(205, 49, 49);">:</span><span style="box-sizing: border-box; color: rgb(25, 25, 112);">27.8535458</span>Z);</div><div style="box-sizing: border-box;">cluster(<span style="box-sizing: border-box; color: rgb(178, 34, 34);">'armprod.kusto.windows.net'</span>).database(<span style="box-sizing: border-box; color: rgb(178, 34, 34);">'ARMProd'</span>).HttpIncomingRequests</div><div style="box-sizing: border-box;">| <span style="box-sizing: border-box; color: rgb(204, 55, 0);">where</span> TIMESTAMP between(st..et)</div><div style="box-sizing: border-box;">| <span style="box-sizing: border-box; color: rgb(204, 55, 0);">where</span> subscriptionId == <span style="box-sizing: border-box; color: rgb(178, 34, 34);">"9216c2d3-667a-4cc5-b428-b5508bcc71e2"</span></div><div style="box-sizing: border-box;">| <span style="box-sizing: border-box; color: rgb(204, 55, 0);">where</span> targetUri <span style="box-sizing: border-box; color: rgb(0, 0, 255);">contains</span> <span style="box-sizing: border-box; color: rgb(178, 34, 34);">"kedsouza-zore/deployments/bc0d0bd47bfa8bc0706e27a16c736c135dabf687"</span></div><div style="box-sizing: border-box;">| <span style="box-sizing: border-box; color: rgb(204, 55, 0);">where</span> commandName == <span style="box-sizing: border-box; color: rgb(178, 34, 34);">"redeployCommit"</span></div><div style="box-sizing: border-box;">| <span style="box-sizing: border-box; color: rgb(204, 55, 0);">where</span> httpMethod == <span style="box-sizing: border-box; color: rgb(178, 34, 34);">"PUT"</span></div><div style="box-sizing: border-box;">| <span style="box-sizing: border-box; color: rgb(204, 55, 0);">project</span> PreciseTimeStamp, Deployment, subscriptionId, httpStatusCode, TaskName, httpMethod, targetUri, commandName</div></div><div style="box-sizing: border-box; color: rgb(51, 51, 51); font-family: &quot;Segoe UI&quot;, &quot;Helvetica Neue&quot;, Arial, &quot;Noto Sans&quot;, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px;"><br style="box-sizing: border-box;"></p><header style="box-sizing: border-box; display: block;">Table0</header>

PreciseTimeStamp | Deployment | subscriptionId | httpStatusCode | TaskName | httpMethod | targetUri | commandName
-- | -- | -- | -- | -- | -- | -- | --
2021-07-07T23:17:25.0247361Z | cc13241aa72642e1afad66f39f4e5150 | 9216c2d3-667a-4cc5-b428-b5508bcc71e2 | -1 | HttpIncomingRequestStart | PUT | https://management.azure.com:443/subscriptions/9216c2d3-667a-4cc5-b428-b5508bcc71e2/resourceGroups/kedsouza-win/providers/Microsoft.Web/sites/kedsouza-zore/deployments/bc0d0bd47bfa8bc0706e27a16c736c135dabf687?api-version=2018-11-01 | redeployCommit
2021-07-07T23:17:55.5767843Z | cc13241aa72642e1afad66f39f4e5150 | 9216c2d3-667a-4cc5-b428-b5508bcc71e2 | 499 | HttpIncomingRequestEndWithClientFailure | PUT | https://management.azure.com:443/subscriptions/9216c2d3-667a-4cc5-b428-b5508bcc71e2/resourceGroups/kedsouza-win/providers/Microsoft.Web/sites/kedsouza-zore/deployments/bc0d0bd47bfa8bc0706e27a16c736c135dabf687?api-version=2018-11-01 | redeployCommit
2021-07-07T23:15:18.621617Z | cc13241aa72642e1afad66f39f4e5150 | 9216c2d3-667a-4cc5-b428-b5508bcc71e2 | 499 | HttpIncomingRequestEndWithClientFailure | PUT | https://management.azure.com:443/subscriptions/9216c2d3-667a-4cc5-b428-b5508bcc71e2/resourceGroups/kedsouza-win/providers/Microsoft.Web/sites/kedsouza-zore/deployments/bc0d0bd47bfa8bc0706e27a16c736c135dabf687?api-version=2018-11-01 | redeployCommit
2021-07-07T23:14:18.6086505Z | cc13241aa72642e1afad66f39f4e5150 | 9216c2d3-667a-4cc5-b428-b5508bcc71e2 | -1 | HttpIncomingRequestStart | PUT | https://management.azure.com:443/subscriptions/9216c2d3-667a-4cc5-b428-b5508bcc71e2/resourceGroups/kedsouza-win/providers/Microsoft.Web/sites/kedsouza-zore/deployments/bc0d0bd47bfa8bc0706e27a16c736c135dabf687?api-version=2018-11-01 | redeployCommit

</div><br class="Apple-interchange-newline">
</body>
</html>

**Comment by suwatch** [comment]
@miyukiabe-baxter  we will close this since the ICM has been resolved with investigation details and limitation.
