### ISSUE TITLE
Unable to use Linux App Service with Azure Functions because of what seems like issues with Kudu

### ISSUE THREAD

**Issue by DavidZidar** [projectkudu/kudu#3315]
I have unsuccessfully been trying for two days to deploy a Azure Functions .NET Worker app to Linux App Service. Most of my attempts result in all requests to Kudu returning 503 Service Unavailable, one time it actually managed to start but my changes to app settings in the Azure Portal was never reflected in Kudu despite many attempts of restarting the app, stopping the app, waiting till the next day and so on.

### Repro steps.
Create a new Azure Function app targeting Linux App Service on an app service plan (not consumption), set app setting `FUNCTIONS_WORKER_RUNTIME` to `dotnet-isolated`, Kudu is now entirely unavailable.

The one time I managed to get Kudu to start I opened the SCM site before changing app settings, but then my changes to app settings in the portal were never reflected in Kudu so any deployment I tried to make would fail because `FUNCTIONS_WORKER_RUNTIME` was stuck at the default value `dotnet`.

### The log/error given by the failure.
503 Service Unavailable.

### Mention any other details that might be useful.
I am using a B1 app service plan, I tried multiple times to delete the app and recreate it but always get the same result. I even tried creating a brand new app service plan, same result regardless.

**Comment by suwatch** [comment]
@purva-vasudeo, @sanchitmehta, @rabollin and @abathinimsft please help with Kudu on Linux issue.

**Comment by DavidZidar** [comment]
@suwatch Has anyone looked at this? I just tried it again and it is still broken.

**Comment by DavidZidar** [comment]
Still broken. :(

**Comment by DavidZidar** [comment]
@purva-vasudeo Thank you, that did seem to make Kudu start working again. Is this documented anywhere? I have never seen this setting before, it is certainly not exposed in the UI and the magic string `"DOTNET-ISOLATED|5.0"` is hard to guess.

**Comment by DavidZidar** [comment]
I'm closing this issue as I'm now successfully using functions in Linux, though it was rather rough getting it working but there are other issues covering those problems.
