### ISSUE TITLE
Safe to use disable.job in repository?

### ISSUE THREAD

**Issue by gbdeboer** [projectkudu/kudu#3319]
Hello all,

I've noticed that disabling a triggered webjob through the Azure portal creates a disable.job file in the directory of the webjob. Re-enabling the webjob removes this file and allows the webjob to be triggered again. 

I'd like to make use of this feature by adding a disable.job file to a number of webjobs in my repository, so I can control which webjobs are enabled and which are not (we're in the process of a migration between Azure web apps and we're switching webjobs one at the time). 

However: I can't find any in the documentation regarding this disable.job file. Is it safe to use it in above way?

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
