### ISSUE TITLE
An API endpoint to cancel running zipdeploys

### ISSUE THREAD

**Issue by nturinski** [projectkudu/kudu#3320]
It would very helpful if there was a way to cancel zip deployments for Web Apps or Function Apps.  

We have users who either accidentally deploy to the wrong app, the wrong project, or if a deployment is taking a long time. 

Sorry if there is already a way to do this.  I was looking through the documentation and didn't see an endpoint for it.

**Comment by zargaryanlilit** [comment]
Restating that this option is critical for us, especially for the deployments that seem stale and can take up to 3 hours to resolve, and we have critical updates to deploy.

**Comment by fsobh** [comment]
This is a crucial Functional requirement, i have been hung up for 3 hours trying to find a solution

**Comment by destroyer22719** [comment]
Hey there if the Kudu team can please do this I would appreciate it, it would resolve so much issues and save everyone so much time. TYSM.

**Comment by mrx88** [comment]
+ 1

**Comment by itlackey** [comment]
Another one permanently running.
+1 to a way to kill it 🙏

**Comment by Kaloszer** [comment]
How is this even an issue? +1

**Comment by Rookian** [comment]
We just moved a way from zipdeploy as it is not reliable and moved over to the good old FTP protocol, which is working very reliable.

**Comment by jvano** [comment]
Hi

Hi

Thanks for letting us know, it would be super useful for us if you could create an Azure support incident for us to better track and assist you in this case:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

I understand you might be now happy using FTP instead but if there is any other Azure related incident, please contact us using an Azure support incident.

Thanks, and sorry for the inconvenience,

Joaquin
