### ISSUE TITLE
Update document to include alternatives to use for Restricted Outgoing Ports

### ISSUE THREAD

**Issue by nelroosevelt** [projectkudu/kudu#3329]
Because connections to ports 445, 137, 138, and 139 are not permitted, could the document "https://github.com/projectkudu/kudu/wiki/Azure-Web-App-sandbox" include the alternatives that can be used such as Azure Files or REST calls.  

Also. you can use Windows or Linux Containers to mount Azure Storage as a network share. 

Access Azure Storage (preview) as a network share from a container in App Service : https://docs.microsoft.com/en-us/azure/app-service/configure-connect-to-azure-storage?pivots=container-linux 

“Bring Your Own Storage” feature to App Service on Linux and Web App for Containers: https://azure.github.io/AppService/2018/09/24/Announcing-Bring-your-own-Storage-to-App-Service.html

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
