### ISSUE TITLE
Question about Performance Counters for App Service

### ISSUE THREAD

**Issue by yutaro113** [projectkudu/kudu#3330]
Hi Team, I have 1 question but below perf counter's value is for each worker instance, is my understanding correct? (not for App Service (if it's running with multiple instances), or App Service Plan) 
https://github.com/projectkudu/kudu/wiki/Perf-Counters-exposed-as-environment-variables

I reached to this doc from [here](https://docs.microsoft.com/en-us/azure/azure-monitor/app/performance-counters#performance-counters-for-applications-running-in-azure-web-apps) so it would be helpful to have this point documented if possible.

Thank you very much!

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
