### ISSUE TITLE
Misleading applicationHost.xdt example for adding allowedServerVariables

### ISSUE THREAD

**Issue by Bouke** [projectkudu/kudu#3336]
The section on [Add an allowedServerVariables](https://github.com/projectkudu/kudu/wiki/Xdt-transform-samples#add-an-allowedservervariables) is misleading. The example shown only works for adding a single variable, it needs an `xdt:Locator` directive to add additional variables:

Before:
```xml
<?xml version="1.0"?> 
<configuration xmlns:xdt="http://schemas.microsoft.com/XML-Document-Transform"> 
  <system.webServer> 
    <rewrite>
      <allowedServerVariables>
        <add name="CONTENT_TYPE" xdt:Transform="InsertIfMissing" />
      </allowedServerVariables>
    </rewrite>
  </system.webServer>
</configuration>
```

After:
```xml
<?xml version="1.0"?> 
<configuration xmlns:xdt="http://schemas.microsoft.com/XML-Document-Transform"> 
  <system.webServer> 
    <rewrite>
      <allowedServerVariables>
        <add name="CONTENT_TYPE" xdt:Transform="InsertIfMissing" xdt:Locator="Match(name)" />
      </allowedServerVariables>
    </rewrite>
  </system.webServer>
</configuration>
```

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
