### ISSUE TITLE
Forbidden (401 - Missing Cookies) when making requests to APIs in SCM

### ISSUE THREAD

**Issue by colin-higgins** [projectkudu/kudu#3337]
Missing cookies server side.

### Repro steps.
1. Create Azure App Service Web App
1. Add manual site extension with scmApplicationHost.xdt
1. Add aspnetcore3.1 sub application to SCM site
1. Make call to SCM Kudu API from sub application with propagated cookies
1. FedAuth* and LoginNonce* cookies are missing
1. Receive 401 Forbidden response

I manually output the cookies and headers from the server side and notice most of the cookies are missing in `Request.Cookies` while they are present in Chrome/Edge/Firefox.

Cookies in chrome developer tools
![image](https://user-images.githubusercontent.com/1801443/138470894-4e9a96df-7d09-4ef5-9b8e-85f436657d7c.png)
Headers as examined from the server side HttpContext:
![image](https://user-images.githubusercontent.com/1801443/138471552-12615435-6127-4c1a-af00-96a89824c5bc.png)

### Project structures.
> Create template netcore3.1 app
> Return headers to browser as string
> Publish app to folder with `scmApplicationHost.xdt`

Point virtual directory to relative folder in `C:\Home\SiteExtensions\MySiteExtension`
Add this content with your app information to the `scmApplicationHost.xdt`

```
<?xml version="1.0"?>
<configuration xmlns:xdt="http://schemas.microsoft.com/XML-Document-Transform">
  <system.applicationHost>
    <sites>
      <site name="%XDT_SCMSITENAME%" xdt:Locator="Match(name)">
        <application path="/sub-app-test" xdt:Locator="Match(path)" xdt:Transform="Remove" />
        <application path="/sub-app-test" applicationPool="%XDT_APPPOOLNAME%" xdt:Transform="Insert">
          <virtualDirectory path="/" physicalPath="%XDT_EXTENSIONPATH%\sub-app-directory" />
        </application>
      </site>
    </sites>
  </system.applicationHost>
</configuration>
```

### The log/error given by the failure.
> 401 Forbidden when making requests to SCM app or deployed template app.

**Comment by suwatch** [comment]
Could you even make a AJAX call to your own app (MySubApp)?  I would start with that first.  BTW, Kudu Debug Console or other extensions (such as /dev editor) do make AJAX calls to the SCM all the times (you can see from F12 -> Network).  Not sure why it would be any difference in your scenarios.

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
