### ISSUE TITLE
Files are locked by another process UnathorizedAccessException

### ISSUE THREAD

**Issue by mbenedykconfigit** [projectkudu/kudu#3342]
### Repro steps.
I'm including git repo with simple project allowing to reproduce issue: https://github.com/mbenedykconfigit/WebApp_AccessDenied

1. Create new App Service
2. Configure App:
```
{
    "name": "ASPNETCORE_ENVIRONMENT",
    "value": "Development",
    "slotSetting": false
  },
  {
    "name": "PluginDirectory",
    "value": "C:\local\temp\plugins",
    "slotSetting": false
  },
  {
    "name": "WEBSITE_DISABLE_OVERLAPPED_RECYCLING",
    "value": "1",
    "slotSetting": false
  },
```
2. Deploy to app service - WebDeploy
3. Navigate to `<APP_URL>/api/plugin`
4. AccessDeniedException!
5. If problem didn't occured, redeploy or change deployment method to ZipDeploy - problem occures for both Web and Zip deployment

With target project I'm getting this exception consistantly for 8/10 deployments

### Project structures.
[github repository](https://github.com/mbenedykconfigit/WebApp_AccessDenied)

### The log/error given by the failure.
![image](https://user-images.githubusercontent.com/75312900/143479161-d581b506-099c-4e47-8d5d-bd2ee547db53.png)

### Debug your Azure website remotely.
If needed

### Mention any other details that might be useful.
On startup app will create new workspace and copy Plugin.dll in path pointed in PluginDirectory setting - from embedded resource, then it will remove all old plugins from path defined in PluginDirectory.

Locked file is not part of app - binaries being deployed

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
