### ISSUE TITLE
Please support deploying function app from sub folder in root of repository

### ISSUE THREAD

**Issue by rachelxj-ms** [projectkudu/kudu#3347]
Posted new issue here(https://github.com/Azure/Azure-Functions/issues/2065) before, but I was suggested to create a ticket here.
Refer to this wiki: https://github.com/projectkudu/kudu/wiki/Customizing-deployments#deploying-a-specific-folder-for-a-node-php-or-aspnet-site
If the folder you want to deploy is not the root of the repository, you can specify which folder to deploy. e.g.

[config]
project = MyWebRoot

This is not working for Function app with local git enabled.
Reproduce steps:

create Nodejs function app
enable local git from deployment center
function app is in sub folder in root of the repository as screenshot
![image](https://user-images.githubusercontent.com/66855967/146281305-c652c897-1ced-4381-b1e7-23761f2a0d67.png)
create .deployment in the root of repository
![image](https://user-images.githubusercontent.com/66855967/146281335-1d731f61-76e2-4282-9d7b-43a5229c520f.png)

commit the code, got error: Source and destination directories cannot be sub-directories of each other
![image](https://user-images.githubusercontent.com/66855967/146281351-064580ee-31d7-4ffc-96a4-ddce5e050138.png)

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
