### ISSUE TITLE
Deploying a Function App from Azure Devops results in Offset to Central Directory cannot be held in an Int64.

### ISSUE THREAD

**Issue by BoutemineOualid** [projectkudu/kudu#3348]
### Repro steps.
We have an Azure DevOps CICD pipeline that deploys a function app to an elastic windows app service plan with 10 instances. From time to time, we get this error message : Offset to Central Directory cannot be held in an Int64. Bellow are the details of the error log as obtained from azure.

### The log/error given by the failure.
```
<step title="BackgroundTrace" date="2021-12-21T14:27:07.673" instance="5b00b5" url="/api/zipdeploy" method="POST">
<step title="Updating shutdown sentinel last write time" date="2021-12-21T14:27:07.720" SemaphoreCount="7"/>
<!--  duration: 16ms  -->
<step title="LockFile 'C:\home\site\locks\deployments.lock' acquired" date="2021-12-21T14:27:07.751"/>
<!--  duration: 31ms  -->
<step title="Creating temporary deployment" date="2021-12-21T14:27:07.798"/>
<!--  duration: 156ms  -->
<step title="Performing fetch based deployment" date="2021-12-21T14:27:07.985"/>
<!--  duration: 719ms  -->
<step title="LockFile 'C:\home\site\locks\deployments.lock' released" date="2021-12-21T14:27:08.735"/>
<!--  duration: 16ms  -->
<step title="Deleting shutdown sentinel file" date="2021-12-21T14:27:08.782" SemaphoreCount="8"/>
<!--  duration: 31ms  -->
<step title="Error occurred" date="2021-12-21T14:27:08.860" type="error" text="One or more errors occurred." stackTrace=" at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions) at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken) at Kudu.Core.Deployment.FetchDeploymentManager.<>c__DisplayClass11_1.<PerformBackgroundDeployment>b__3() in C:\Kudu Files\Private\src\master\Kudu.Core\Deployment\FetchDeploymentManager.cs:line 399 at Kudu.Contracts.Infrastructure.LockExtensions.TryLockOperation(IOperationLock lockObj, Action operation, String operationName, TimeSpan timeout) in C:\Kudu Files\Private\src\master\Kudu.Contracts\Infrastructure\LockExtensions.cs:line 34 at Kudu.Contracts.Infrastructure.LockExtensions.LockOperation(IOperationLock lockObj, Action operation, String operationName, TimeSpan timeout) in C:\Kudu Files\Private\src\master\Kudu.Contracts\Infrastructure\LockExtensions.cs:line 46 at Kudu.Core.Deployment.FetchDeploymentManager.<>c__DisplayClass11_0.<PerformBackgroundDeployment>b__1() in C:\Kudu Files\Private\src\master\Kudu.Core\Deployment\FetchDeploymentManager.cs:line 383" innerText="Offset to Central Directory cannot be held in an Int64." innerStackTrace=" at System.IO.Compression.ZipArchive.ReadEndOfCentralDirectory() at System.IO.Compression.ZipArchive.Init(Stream stream, ZipArchiveMode mode, Boolean leaveOpen) at System.IO.Compression.ZipArchive..ctor(Stream stream, ZipArchiveMode mode, Boolean leaveOpen, Encoding entryNameEncoding) at System.IO.Compression.ZipFile.Open(String archiveFileName, ZipArchiveMode mode, Encoding entryNameEncoding) at Kudu.Services.Deployment.PushDeploymentController.ExtractTriggers(IRepository repository, ArtifactDeploymentInfo deploymentInfo) in C:\Kudu Files\Private\src\master\Kudu.Services\Deployment\PushDeploymentController.cs:line 553 at Kudu.Services.Deployment.PushDeploymentController.<LocalZipHandler>d__14.MoveNext() in C:\Kudu Files\Private\src\master\Kudu.Services\Deployment\PushDeploymentController.cs:line 539 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Kudu.Core.Deployment.FetchDeploymentManager.<PerformDeployment>d__9.MoveNext() in C:\Kudu Files\Private\src\master\Kudu.Core\Deployment\FetchDeploymentManager.cs:line 181 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at Kudu.Core.Deployment.FetchDeploymentManager.<PerformDeployment>d__9.MoveNext() in C:\Kudu Files\Private\src\master\Kudu.Core\Deployment\FetchDeploymentManager.cs:line 295"/>
<!--  duration: 16ms  -->
</step>
<!--  duration: 1219ms  -->

```
### Debug your Azure website remotely.
App name: func-acq.....ite-qa-01
We can provide more details if needed.

### Mention any other details that might be useful.
Seems like a random error that happens often when the approval on the deployment stage is performed hours after the build was initially kicked.

Azure Devops Task Details:
`

              - task: AzureFunctionApp@1
                displayName: 'Deploy function app'
                inputs:
                  appType: functionApp
                  appName: $(tfOut.function_name)
                  azureSubscription: ${{ variables.subscription }}
                  package:  ${{ variables.artifactPath }}
                  deploymentMethod: runFromPackage
`

Tried also using deploymentMethod auto and runFromZip but nothing changed.

The generated package size does not exceed 20mb.

**Comment by Lootvoet** [comment]
Is there more info about this? We're having the exact same issue.

**Comment by neel015** [comment]
+1 Similar problem , Works after 2-3 Reattempts. Using AzureFunctionApp@1 task in Devops to deploy to azure function.
Also, seems to be happening for one particular function app. Same code, if deployed to another function app with same pipeline doesn't seem to cause a problem.

**Comment by jfcroteau** [comment]
Same problem here. It's mostly random now.

**Comment by jfcroteau** [comment]
Linking something pretty similar to this issue: https://github.com/microsoft/azure-pipelines-tasks/issues/14201

**Comment by dixitpatel89** [comment]
I had same issue in azure functions with node JS. Just tried with restart azure instance and try again, it will work.

**Comment by xsurfer** [comment]
I am facing the same issue, moreover I am not able to access any log within the function app. Any idea how to troubleshoot the issue?

**Comment by jwidmer** [comment]
Check in Azure if your App Service or Function App is set up under Deployment Center.  We had originally set up the build pipeline and release pipeline through the Azure Deployment Center.  Then when we tried to create a new release pipeline to the same app service we ended up with the error:

    Offset to Central Directory cannot be held in an Int64.
    Error: Failed to deploy web package to App Service.
    Error: To debug further please check Kudu stack trace URL
    Error: Package deployment using ZIP Deploy failed. Refer logs for more details.

The solution is to go into Azure Portal > App Service (or deployment slot) > Deployment Center and then Disconnect your app.

**Comment by John-Bosch** [comment]
This issue is making me seriously consider other technologies for our integration services. 5 out of 6 attempts at deployment have failed this morning because of this exact problem.

**Comment by blaineross** [comment]
After weeks of back and forth with Microsoft on a support ticket (where I was bounced between half a dozen people/departments with no solutions given) I finally managed to figure out what was causing this for me.

Prior to the `AzureFunctionApp@1` task being run I ran a command in my pipeline to stop the function app.

```
        - task: AzureAppServiceManage@0
          displayName: 'Stop Azure App Service: ${{parameters.envName}}-func-${{parameters.moduleName}}'
          inputs:
            azureSubscription: ${{parameters.serviceConnection}}
            Action: 'Stop Azure App Service'
            WebAppName: '${{parameters.envName}}-func-${{parameters.moduleName}}'
```

I have now **removed** this step so the function app is not getting stopped before it is deployed to and this has resolved the issue. Importantly this was only an issue for me when I moved to an elastic plan. Any functions that are on consumption plan still deployed fine.

This may not be the issue for everyone, but take a look if your functions apps are being stopped prior to deployment. It may be the case that the step needs removed, or that there is some timer delay that could be added if it is some sort of race condition with the function not being stopped properly.

**Comment by amitjaura** [comment]
> Check in Azure if your App Service or Function App is set up under Deployment Center. We had originally set up the build pipeline and release pipeline through the Azure Deployment Center. Then when we tried to create a new release pipeline to the same app service we ended up with the error:
> 
> ```
> Offset to Central Directory cannot be held in an Int64.
> Error: Failed to deploy web package to App Service.
> Error: To debug further please check Kudu stack trace URL
> Error: Package deployment using ZIP Deploy failed. Refer logs for more details.
> ```
> 
> The solution is to go into Azure Portal > App Service (or deployment slot) > Deployment Center and then Disconnect your app.

This hack fixed the issue for me. I didn't try any other solution from this thread through.

**Comment by John-Bosch** [comment]
> 
> This hack fixed the issue for me. I didn't try any other solution from this thread through.

This is a known "solution". The problem is it will eventually come back, and you will need to disconnect the function again. I eventually built my release pipeline to use the "continueOnError" property of AzureFunctionApp. If the first deployment fails, it does a disconnect using AzureCLI, then tries the deployment again.

**Comment by fjdean** [comment]
The workaround that worked for me was to entirely replace the `AzureFunctionApp@1 `task with an `AzureCLI@2 `task, and run the `az functionapp deployment source config-zip` command as an inline script.

Example:

```
- task: AzureCLI@2
  inputs:
    scriptType: 'pscore'
    scriptLocation: 'inlineScript'
    azureSubscription: '<subscription or SP>'
    inlineScript: |
      az functionapp deployment source config-zip --name <name> --resource-group <rg name> --src <zip file>
```

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
