### ISSUE TITLE
Application Settting to enable Health Check?

### ISSUE THREAD

**Issue by adamyager** [projectkudu/kudu#3349]
> ---------------------------------------------------------------

### Repro steps.
We are looking for automation option for Health Check and do not use ARM. The easiest thing for us to do is to have an application setting.
healthCheckPath  =  Sting seems to be the indicator that its been enabled in the portal but how do we enable via an application setting, if possible?
These values work to configure it but there is nothing public to enable.
WEBSITE_HEALTHCHECK_MAXPINGFAILURES
WEBSITE_HEALTHCHECK_MAXPINGFAILURES

### Debug your Azure website remotely.
)
> we can take a look at what's going on.

### Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
