### ISSUE TITLE
Zip Deploy fails for branches other than master

### ISSUE THREAD

**Issue by sysadmin256** [projectkudu/kudu#3350]
I think this is similar to issue #3111 but the fix there isn't working for me.  I have an Azure function app (built on PowerShell) that fails to deploy via DevOps Pipeline when deploying to a branch other than master.  

```ChangeSetId(Test) does not match 3305e1c221984b2692fb5e6fff91f60e, 'master' or 'HEAD'```

I've found that if I use the 'Disconnect' option in the Azure portal -> Function app -> Deployment Center, then run the pipeline again it will succeed.  The Deployment Center will then update to show it's connected but references the branch of master even though the deployment is from my 'Test' branch.  See the picture below.

![image](https://user-images.githubusercontent.com/48481549/148588796-2b49b964-d92e-4d89-be32-f69a1a15d1c8.png)

I checked c:\home\site\deployments\settings.xml and it does correctly reference the 'Test' branch.

Any help is appreciated!

**Comment by sysadmin256** [comment]
One other thing I just noticed is when I click on the Deployment Center page, it shows the correct branch for 1-2 seconds like this: 
![image](https://user-images.githubusercontent.com/48481549/148615656-b6495b01-dc89-4493-8adc-4e1e4e3de8e5.png)

then it switches back to this:
![image](https://user-images.githubusercontent.com/48481549/148615773-461e5256-e6da-4eb3-9cce-0f5c0ae024f8.png)

If I click the refresh button at the top or refresh the entire page, the same thing happens again where it shows the Test branch, then changes to master.

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
