### ISSUE TITLE
Graceful shutdown when autoscaling down?

### ISSUE THREAD

**Issue by Bouke** [projectkudu/kudu#3352]
I have a continuous WebJob that I want to autoscale. I've also configured graceful shutdown so that my application doesn't abort any work in progress. However I've found that on autoscale down, the WebJob doesn't shutdown gracefully. Is this a bug, or a missing feature of WebJobs/Kudu?

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
