### ISSUE TITLE
Linux Function App ZipDeploy succeeds, but no functions listed on console

### ISSUE THREAD

**Issue by pkaminski** [projectkudu/kudu#3353]
I'm doing a ZipDeploy to a Function App (https://reviewable-test-1.azurewebsites.net/).  I created a zip file of the directory structure that I had previously deployed successfully using `func azure functionapp publish` and POSTed it via `curl` using application scope credentials found via `az webapp deployment list-publishing-profiles`.  The POST succeeds with return code 200 and the deployment is listed on https://reviewable-test-1.scm.azurewebsites.net/ with the last message in the log being "Deployment successful.".  The Function App is configured with `FUNCTIONS_WORKER_RUNTIME` set to `node`, `WEBSITE_RUN_FROM_PACKAGE` set to `1`, and `AzureWebJobsStorage` set to an appropriate value.

However, no functions are listed in the Azure console for the Function App, and attempting to call them via HTTP triggers fails with 404 errors.

What might be going wrong and how should I go about debugging this?  Thanks!

**Comment by pkaminski** [comment]
I should've mentioned that the Function App above is running on Linux.  The same process works fine with a Windows Function App, so the bug (if it is such) appears to be specific to Linux.

**Comment by khkh-ms** [comment]
Zip deployment is not supported by Linux Consumption.  For Linux Consumption, Core tools actually uploads the package to storage and sets the `WEBSITE_RUN_FROM_PACKAGE=<SAS token>.

**Comment by pkaminski** [comment]
I see.  What is the recommended way to upload functions to Linux Consumption from application code then?

**Comment by khkh-ms** [comment]
`WEBSITE_RUN_FROM_PACKAGE=1` is not supported by Linux Consumption. Please try the zip deployment again after removing `WEBSITE_RUN_FROM_PACKAGE` config from the function app.

**Comment by pkaminski** [comment]
Thank you, I didn't see that detail in the docs!  Everything's working as expected now.
