### ISSUE TITLE
No option for site extension in scm.azurewebsites.net (phpMyAdmin)

### ISSUE THREAD

**Issue by teohsinyee** [projectkudu/kudu#3354]
Refering to this video (https://www.youtube.com/watch?v=0TBRb-nmzVs), the author suggests adding phpMyAdmin by clicking on Site Extension option. However, I don't have this option on my end. Is this already deprecated?

**Comment by suwatch** [comment]
From portal, try adding AppSettings - phpMyAdmin_EXTENSION_VERION = latest - to your App Service.   See if you can now access ..scm.azurewebsites.net/phpMyAdmin.

**Comment by teohsinyee** [comment]
I've tried it. May I know is this only works for Linux?

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
