### ISSUE TITLE
File explorer in /DebgConsole does not sync current directory with cmd emulator after process terminate.

### ISSUE THREAD

**Issue by georgeOsdDev** [projectkudu/kudu#3355]
File explorer in /DebgConsole does not sync cmd emulator after process terminate.

<img width="556" alt="image" src="https://user-images.githubusercontent.com/1381907/158125312-2c12fef2-4e26-4c45-8937-23c32f1c5c61.png">

### Repro steps.

Build
96.40113.5578.0 ([34d7f185e5](https://github.com/Azure/kudu/commit/34d7f185e58d33f792f11b3728b1afd90a0d9fa3))
Azure App Service
97.0.7.606

1. Open /DebugConsole
2. cd site
3. wait 60 min until `process [pid] terminated!  Press ENTER to start a new cmd process.`
4. After new cmd process created, File explorer will not sync current directory with cmd.

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
