### ISSUE TITLE
MSDEPLOY_RENAME_LOCKED_FILES=1 appears to not rename locked files into .delete extension but .MSDEPLOYTMP

### ISSUE THREAD

**Issue by YusukeTobo** [projectkudu/kudu#3356]
Regarding the following doc, locked files are renamed into .delete files in the middle of MsDeploy. 

https://github.com/projectkudu/kudu/wiki/Dealing-with-locked-files-during-deployment#for-msdeploy-there-is-another-option-to-rename-locked-files
`This causes msdeploy to attempt to rename DLLs if they can't be copied during deployment. This often works because even when DLLs are loaded, they can typically still be renamed. It renames them with a .delete extension, which it then cleans up on the next round.`

As you may see the following screenshot, the extension appears to be .MSDEPLOYTMP.

![image](https://user-images.githubusercontent.com/46416479/158127190-ba3119e8-a3ce-4973-b077-af5b450d4785.png)

If MsDeploy would rename the locked files into .MSDEPLOYTMP extension, I think it would be nice to correct the wiki.

### Repro steps.
1. set MSDEPLOY_RENAME_LOCKED_FILES=1 in AppSettings.
2. lock a dll in %HOME%\site\wwwroot in .NET stack (I tried in .net core 3.1).
3. MS Deploy

**Comment by YusukeTobo** [comment]
Kudu version: 96.40113.5578.0
VisualStudio 2022: Version 17.1.1

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
