### ISSUE TITLE
[Doc Update] Install Site Extension REST API requires request body with 'Id' property

### ISSUE THREAD

**Issue by amolmehrotra** [projectkudu/kudu#3358]
The below REST API call requires a request body with an 'Id' property with the value of the site extension ID by passed in its call or it returns a 400 (BadRequest) response:
[Web Apps - Install Site Extension - REST API (Azure App Service) | Microsoft Docs](https://docs.microsoft.com/en-us/rest/api/appservice/web-apps/install-site-extension)
 
The above documentation does not specify that a request body is required and this call is only successful when a valid request body is passed.

Below is a sample of a request body to send with this API call to install a site extension:
{
    "Id":"siteExtensionId"
}
 
**Ask:** Update to documentation above confirming that request body is needed to successfully call API and update to Try-It section that provides a sample JSON request body for requests.

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
