### ISSUE TITLE
ZIP deploy to Linux Consumption plan returns 200 OK, deployment is not visible

### ISSUE THREAD

**Issue by maartenba** [projectkudu/kudu#3362]
ZIP deploy to Linux Consumption plan returns 200 OK, yet deployment is not visible/active.

### Repro steps.

* Create a function app, using the default template (e.g. v4, default worker).
* Add an anonymous HTTP trigger function
* Create a ZIP file of it
* Deploy to Azure Functions, Linux, Consumption plan using the `https://xxxxxx.scm.azurewebsites.net/api/zipdeploy?isAsync=true` endpoint
* Observe a status 200 is returned
* No functions are listed in the Azure portal, nor do expected endpoints exist

**Comment by maartenba** [comment]
Further investigation learns that `SCM_DO_BUILD_DURING_DEPLOYMENT=false` has to be set, and then deployment works.

**Comment by MattJeanes** [comment]
@maartenba I'd just like to say thank you so much, this has saved my bacon tonight!
