### ISSUE TITLE
Outdated documentation on disk-limits

### ISSUE THREAD

**Issue by stefnnn** [projectkudu/kudu#3365]
We are currently running into disk full issues during deployment (see our question and setup description here: https://docs.microsoft.com/en-us/answers/questions/827223/actual-disk-space-requirements-for-azure-appservic.html)

I believe the information on quotas is outdated, as I cannot find our currentl SKU and am confused, if our limit is still 15 GB with a P2V3 plan or if it is (hopefully) a bit higher than that:

https://github.com/projectkudu/kudu/wiki/Understanding-the-Azure-App-Service-file-system

Thanks for checking (and possibly updating) the docs.

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
