### ISSUE TITLE
Typo on wiki

### ISSUE THREAD

**Issue by outwebbed** [projectkudu/kudu#3366]
Just pointing out a small typo. Cheers!

https://github.com/projectkudu/kudu/wiki/Post-Deployment-Action-Hooks

> The location of these scripts is set as a default setting which can be overwritten by updating the setting: SCM_POST_DEPLOYMENT_ACTIONS_PATH. That can be set to
> 
> **And** absolute path
> A relative path from D:\home\site\repository

**Comment by suwatch** [comment]
fixed, thanks.
