### ISSUE TITLE
SiteExtensionV2 should follow link for more results

### ISSUE THREAD

**Issue by suwatch** [projectkudu/kudu#3367]
Feed url https://www.nuget.org/api/v2/Search?searchTerm=%27tags:AzureSiteExtension%27&includePrerelease=true&semVerLevel=2.0.0 contains link and it should be followed to get the remaining.

```
<link rel="next" href="https://www.nuget.org/api/v2/Search?searchTerm=%27tags%3AAzureSiteExtension%27&amp;targetFramework=%27%27&amp;includePrerelease=true&amp;$skip=100&amp;semVerLevel=2.0.0" />
```

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
