### ISSUE TITLE
Empty WAR deployment to /api/publish

### ISSUE THREAD

**Issue by skylaro** [projectkudu/kudu#3369]
> For deployment issues, please provide us with the following information:
> ---------------------------------------------------------------

### Repro steps.
> your project built successfully on your dev machine but failed on Azure?
> please write down your build tools and their versions (ie `Msbuild 15.1.0.0`)
Apache Maven

### Project structures.
> in order to reproduce your issue at our end we need a simple 
> [github repository](https://github.com/projectkudu/kudu/wiki/Using-a-git-repo-to-report-an-issue)
> that highlights structure of the project
Project is a simple hello world app from spring initializr website.

### The log/error given by the failure.
> Normally this include a stack trace, error code and some more information.
Deployment is successful and WAR file can be seen at 0kb from Kudu console

### Debug your Azure website remotely.
> it is recommanded that you share your Web App name, directly or [indirectly](https://github.com/projectkudu/kudu/wiki/Reporting-your-site-name-without-posting-it-publicly)
> we can take a look at what's going on.

### Mention any other details that might be useful.
1. Tried on multiple Java versions on both Tomcat and JBoss MCR images.
2. Other deployment methods such as maven deploy and cli deploy work just fine.
3. '-T' parameter for curl changes data format to 'file' instead of 'binary', which also works.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
