### ISSUE TITLE
question: what is the REMOTEDEBUGGINGPORT in remote debugging

### ISSUE THREAD

**Issue by jeremysimmons-ent** [projectkudu/kudu#3372]
What is the purpose of the REMOTEDEBUGGINGPORT value in the app service environment variables?
It shows up as the /port parameter of msvsmon. 
D:\msvsmon\16.0.30709.132\vx64\msvsmon.exe /silent /hostname 127.0.0.1 /port 54919 /anyuser /noauth /timeout 4233600 /FallbackLoadRemoteManagedPdbs

Connecting to msvsmon from visual studio works great on the listed ports from this page: https://docs.microsoft.com/en-us/visualstudio/debugger/remote-debugger-port-assignments?view=vs-2022

example of REMOTE* variables from app service environments.
REMOTE_ADDR=10.216.17.112
REMOTE_HOST=10.216.17.112
REMOTE_PORT=63566
REMOTE_USER=
REMOTEDEBUGGINGBITVERSION = vx64
REMOTEDEBUGGINGPORT = 54920
REMOTEDEBUGGINGVERSION = 16.0.30709.132

**Comment by t-behardin** [comment]
This variable is used for Azure App Service remote debugging. The port listed on the page you linked (such as 4024) connects to App Service. Your request is then forwarded through various internal layers and uses the port listed by REMOTEDEBUGGINGPORT to connect to the remote debugger running on your application.

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
