### ISSUE TITLE
Kudu OpenApi specification

### ISSUE THREAD

**Issue by maikelvanhaaren** [projectkudu/kudu#3375]
I really like the Kudu API! I use it for retrieving realtime logs from the web jobs, stop and start them and display a small dashboard. 

Is there an OpenApi specification file for the API definition?

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
