### ISSUE TITLE
Extra line feed founded in log streaming API provided by kudu

### ISSUE THREAD

**Issue by Flanker32** [projectkudu/kudu#3396]
For linux web app, we could find extra line feed through kudu log stream api (through browser or tooling based on same API like IntelliJ/VSCode extensions), but when when we check the file logging, the result is fine

![image](https://user-images.githubusercontent.com/12445236/187834849-e97dc991-289d-465e-a50f-465dcf1b4312.png)

![image](https://user-images.githubusercontent.com/12445236/187834891-1c6a21f0-79fd-45bd-adce-a5b7be2dbd4d.png)

### Repro steps.
> your project built successfully on your dev machine but failed on Azure?
> please write down your build tools and their versions (ie `Msbuild 15.1.0.0`)
- Clone https://github.com/spring-projects/spring-petclinic 
- Package and deploy to an linux web app
- Trigger an exception and check log streaming through kudu `api/logstream`

### Project structures.
> in order to reproduce your issue at our end we need a simple 
> [github repository](https://github.com/projectkudu/kudu/wiki/Using-a-git-repo-to-report-an-issue)
> that highlights structure of the project

demo project: [petclininc](https://github.com/spring-projects/spring-petclinic )

### The log/error given by the failure.
> Normally this include a stack trace, error code and some more information.

### Debug your Azure website remotely.
> it is recommanded that you share your Web App name, directly or [indirectly](https://github.com/projectkudu/kudu/wiki/Reporting-your-site-name-without-posting-it-publicly)
> we can take a look at what's going on.

### Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
