### ISSUE TITLE
Document ?recursive=true in the wiki for delete

### ISSUE THREAD

**Issue by zippy1981** [projectkudu/kudu#3398]
I would make the changes to the wiki myself if there was a way to send PRs to the wiki.

The VFS REST Delete api can recureively delete a directory with ?recursive=true but that is not documented.

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
