### ISSUE TITLE
Is really required a rebuild on deployment?

### ISSUE THREAD

**Issue by flixman** [projectkudu/kudu#3400]
I have a Single Page App, written with React on the frontend, and with python flask on the backend. Using the Azure App Service, an starter workflow was created for me. Giving a look to it, and to the existence of the variable SCM_DO_BUILD_DURING_DEPLOYMENT=1, I have the feeling something is off: In my workflow currently we pip-install and npm-install all required packages, so that we can run the required tests. Then everything we want to deploy gets zipped and... seems that, because of that environment variable, the whole build process happens again? Or am I not reading properly the documentation?

On the other hand, I see in the deployment an additional 'antenv' folder, which I assume gets generated by kudu? Does kudu detect there is a requirements.txt file on the root of my app and runs automatically pip with it?

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
