### ISSUE TITLE
Stop a continuous job via API doesn't work

### ISSUE THREAD

**Issue by maikelvanhaaren** [projectkudu/kudu#3412]
### Repro steps.

1. Add a continuous web job to an Windows azure app service
2. Start the continuous and let it run
3. Try to stop the webjob with the api endpoint '(..)/api/continuouswebjobs/JOBNAME/stop'
4. You will receive a 404 error message

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
