### ISSUE TITLE
A compatible .NET SDK was not found - 6.0.302 

### ISSUE THREAD

**Issue by jayendranarumugam** [projectkudu/kudu#3413]
### Project structures.
We are using Dotnet 6 App and using Kudu Build for the deployment, Our app is targets to build on 6.0.302 SDK(global.json) which was working fine till 1 week before on kudu. But now this SDK has been removed from azure kudu and not available anymore. The only available versions are below

```
remote: 1.1.14 [C:\Program Files (x86)\dotnet\sdk]        
remote: 2.1.526 [C:\Program Files (x86)\dotnet\sdk]        
remote: 2.2.109 [C:\Program Files (x86)\dotnet\sdk]        
remote: 3.1.118 [C:\Program Files (x86)\dotnet\sdk]        
remote: 3.1.422 [C:\Program Files (x86)\dotnet\sdk]        
remote: 3.1.423 [C:\Program Files (x86)\dotnet\sdk]        
remote: 5.0.406 [C:\Program Files (x86)\dotnet\sdk]        
remote: 5.0.408 [C:\Program Files (x86)\dotnet\sdk]        
remote: 6.0.400 [C:\Program Files (x86)\dotnet\sdk]        
remote: 6.0.401 [C:\Program Files (x86)\dotnet\sdk]
```

### The log/error given by the failure.

```
A compatible .NET SDK was not found.       
Requested SDK version: 6.0.302             
remote: global.json file: C:\home\site\repository\Web\global.json 

remote: 1.1.14 [C:\Program Files (x86)\dotnet\sdk]        
remote: 2.1.526 [C:\Program Files (x86)\dotnet\sdk]        
remote: 2.2.109 [C:\Program Files (x86)\dotnet\sdk]        
remote: 3.1.118 [C:\Program Files (x86)\dotnet\sdk]        
remote: 3.1.422 [C:\Program Files (x86)\dotnet\sdk]        
remote: 3.1.423 [C:\Program Files (x86)\dotnet\sdk]        
remote: 5.0.406 [C:\Program Files (x86)\dotnet\sdk]        
remote: 5.0.408 [C:\Program Files (x86)\dotnet\sdk]        
remote: 6.0.400 [C:\Program Files (x86)\dotnet\sdk]        
remote: 6.0.401 [C:\Program Files (x86)\dotnet\sdk]  
```

### Debug your Azure website remotely.
> it is recommanded that you share your Web App name, directly or [indirectly](https://github.com/projectkudu/kudu/wiki/Reporting-your-site-name-without-posting-it-publicly)
> we can take a look at what's going on.

Sub: **aec......fb3**
Site: **grc..inter...01**

### Question:

- Is there a way we can install a specific version of dotnet SDK ? If it's removed ?
- We don't know why this particular version go removed. Is there any documentation on which dotnet SDK will be supported for long term ?

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
