### ISSUE TITLE
Not able to deploy a repo subfolder to Azure app services

### ISSUE THREAD

**Issue by mproschowsky** [projectkudu/kudu#3415]
Context:

- nodejs project stored in Azure DevOps repository
- The code and `package.json` are in a subfolder called `server`
- Code should be deployed to Azure App Service, using continuous deployment from the Azure DevOps repository
- For deployment to work, Kudu/oryx need to know to look into the `server ` folder and not in the root of the repository. 

According to documentation this can be done by the PROJECT configuration: 
https://github.com/projectkudu/kudu/wiki/Customizing-deployments#deploying-a-specific-folder-for-a-node-php-or-aspnet-site

On the list of ORYX configurations, PROJECT is listed as a only working for .NET:
https://github.com/microsoft/Oryx/blob/main/doc/configuration.md

### Repro steps
Add application setting in Azure: PROJECT = server
Commit changes to repo to trigger Kudu

### The log/error given by the failure.
Detecting platforms...
Error: Could not find the .NET Core project file.

Is this a documentation error, or is the PROJECT command expected to work as described?

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
