### ISSUE TITLE
Trigger function manually with Web Jobs SDK 3

### ISSUE THREAD

**Issue by gabbsmo** [projectkudu/kudu#3418]
Since upgrading to Azure Web Jobs SDK 3 Kudu no longer shows our functions in the web jobs dashboard. How can I trigger a time triggered function manually when it is bundled inside a continous web job?

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service

**Comment by gabbsmo** [comment]
@jvano unfortunately I do not have a support subscription that includes technical support. You would have to create the ticket for me.

And yes the issue persists. If not I go to the Web Jobs Dashboard in Kudu there is no run history since mid 2021.
