### ISSUE TITLE
Support deferred symlinks by turning off Kudu comparison between ready-to-deploy files and files already in the webapp

### ISSUE THREAD

**Issue by antoine-coulon** [projectkudu/kudu#3420]
Hello, 

I'm currently struggling using the `zipDeploy` deployment method using the `AzureWebApp@1` task which appears to not support symlinks (related https://github.com/Azure/webapps-deploy/issues/54, #3295, #3229).

A workaround we found for that we removed all the symlinks from the artifact we try to "zipDeploy". It works well, as the `webappLinux` can handle correctly symlinks (**created after the deployment**). However when doing other deployments afterwards, `kudusync` does heavy comparisons about files that should be added/removed between the artifact we're trying to deploy and the one that was already shipped in the webapp. This has for consequence of triggering errors during the deploy phase such as ```Error: ENOENT: no such file or directory, stat '/home/site/wwwroot/common/temp/node_modules/.pnpm/@fastify+static@6.5.1/node_modules``` because Kudu can't handle symlinks correctly.

Is there any way of disabling that comparison and just remove everything from the destination folder and re-deploy everything with **no comparison process trying to resolve symlinks**? Currently it prevents us from deploying correctly our monorepos and prevent us from benefiting of the latest features available in the Node.js ecosystem.

> For deployment issues, please provide us with the following information:
> ---------------------------------------------------------------

### Repro steps.

- Use "zipDeploy" on an artifact containing only `.js` files and `node_modules` (artifact without symlinks).
- Create symlinks on the linux webapp once the deployment done
- Change something in the artifact node_modules
- Process the deploy again
- Observe the failure when trying to compare **current node_modules** with the **old ones (containing symlinks)**

### Project structures.

Simple `Rush` monorepo using symlinks.

### The log/error given by the failure.
> Normally this include a stack trace, error code and some more information.

```Error: ENOENT: no such file or directory, stat '/home/site/wwwroot/common/temp/node_modules/.pnpm/@fastify+static@6.5.1/node_modules```

**Comment by antoine-coulon** [comment]
@suwatch any update or information about this issue please?

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
