### ISSUE TITLE
Preventing accidental deletion of kudu applications within the dashboard

### ISSUE THREAD

**Issue by outwebbed** [projectkudu/kudu#3422]
Is there any mechanism available to prevent applications from being deleted via the Kudu Dashboard?

![image](https://user-images.githubusercontent.com/18011046/208264255-a791e10f-1ab1-4496-aaa1-64b9ae2afb90.png)

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
