### ISSUE TITLE
Zipdeploy failed most of the time. But it get's passed once disconnect the Developement center.  After that, again create release pipeline it is failed in azure devOps pipepine for azure function 

### ISSUE THREAD

**Issue by mithunpandi91** [projectkudu/kudu#3423]
> For deployment issues, please provide us with the following information:
> ---------------------------------------------------------------

### Repro steps.
Once disconnect the Developement center again create release pipeline deployment is passed in azure portal.
After that, next release pipeline got failed everytime. 

### Project structures.
I am developing Azure function app using .net 7. Deploy via Azure devOps CI/CD pipeline.
Azure function version: 4
dot net runtime: dotnet-isolated

Failed to deploy web package to App Service.

To debug further please check Kudu stack trace URL : https://$bieno-energyhub-d-901603-funcapp-01:***@bieno-energyhub-d-901603-funcapp-01.scm.azurewebsites.net/api/vfs/LogFiles/kudu/trace 

Error: Package deployment using ZIP Deploy failed. Refer logs for more details.
![image](https://user-images.githubusercontent.com/121481742/210206932-3ae2e32f-830a-43fd-a5e0-70ed168b68ea.png)

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by FinVamp1** [comment]
@mithunpandi91  can you check if you have a file d:/home/site/deployments/settings.xml. If you have please back it up and  then delete it and let us know if the issue reproduces.

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
