### ISSUE TITLE
My Sit is not loading due to same issue related to ZipFS

### ISSUE THREAD

**Issue by raiajithkumarr** [projectkudu/kudu#3426]
> For deployment issues, please provide us with the following information:
> ---------------------------------------------------------------

### Repro steps.
> After deploying web app into Azure web app in event log we are able see below issue.
> Locally it is working fine.

### The log/error given by the failure.
> 
<Events>
    <Event>
        <System>
            <Provider Name="ZipFS"/>
            <EventID>0</EventID>
            <Level>1</Level>
            <Task>0</Task>
            <Keywords>Keywords</Keywords>
            <TimeCreated SystemTime="2023-01-11T06:50:18Z"/>
            <EventRecordID>-2090867343</EventRecordID>
            <Channel>Application</Channel>
            <Computer>dw1sdwk0000QZ</Computer>
            <Security/>
        </System>
        <EventData>
            <Data>Failed to open siteversion.txt. ZipFS setup failed. Error: 0x80070003</Data>
        </EventData>
    </Event>
    <Event>
        <System>
            <Provider Name="ZipFS"/>
            <EventID>0</EventID>
            <Level>1</Level>
            <Task>0</Task>
            <Keywords>Keywords</Keywords>
            <TimeCreated SystemTime="2023-01-11T06:50:18Z"/>
            <EventRecordID>-2090867328</EventRecordID>
            <Channel>Application</Channel>
            <Computer>dw1sdwk0000QZ</Computer>
            <Security/>
        </System>
        <EventData>
            <Data>Failed to copy zip from remote source.</Data>
        </EventData>
    </Event>
    <Event>
        <System>
            <Provider Name="ZipFS"/>
            <EventID>0</EventID>
            <Level>1</Level>
            <Task>0</Task>
            <Keywords>Keywords</Keywords>
            <TimeCreated SystemTime="2023-01-11T06:50:18Z"/>
            <EventRecordID>-2090867328</EventRecordID>
            <Channel>Application</Channel>
            <Computer>dw1sdwk0000QZ</Computer>
            <Security/>
        </System>
        <EventData>
            <Data>Adding virtual directory from failure zip file \\?\d:\local\SitePackages\2204094828.zip</Data>
        </EventData>
    </Event>
    <Event>
        <System>
            <Provider Name="ZipFS"/>
            <EventID>0</EventID>
            <Level>1</Level>
            <Task>0</Task>
            <Keywords>Keywords</Keywords>
            <TimeCreated SystemTime="2023-01-11T13:42:55Z"/>
            <EventRecordID>-2066110468</EventRecordID>
            <Channel>Application</Channel>
            <Computer>dw1sdwk0000QZ</Computer>
            <Security/>
        </System>
        <EventData>
            <Data>Invalid operation on Read Only File System: Create New File</Data>
        </EventData>
    </Event>
    <Event>
        <System>
            <Provider Name="ZipFS"/>
            <EventID>0</EventID>
            <Level>1</Level>
            <Task>0</Task>
            <Keywords>Keywords</Keywords>
            <TimeCreated SystemTime="2023-01-11T13:42:55Z"/>
            <EventRecordID>-2066110453</EventRecordID>
            <Channel>Application</Channel>
            <Computer>dw1sdwk0000QZ</Computer>
            <Security/>
        </System>
        <EventData>
            <Data>Invalid operation on Read Only File System: Write to File</Data>
        </EventData>
    </Event>
    <Event>
        <System>
            <Provider Name="ZipFS"/>
            <EventID>0</EventID>
            <Level>1</Level>
            <Task>0</Task>
            <Keywords>Keywords</Keywords>
            <TimeCreated SystemTime="2023-01-11T13:43:28Z"/>
            <EventRecordID>-2066078078</EventRecordID>
            <Channel>Application</Channel>
            <Computer>dw1sdwk0000QZ</Computer>
            <Security/>
        </System>
        <EventData>
            <Data>Invalid operation on Read Only File System. Create New File failures in last 32 seconds: 3</Data>
        </EventData>
    </Event>
    <Event>
        <System>
            <Provider Name="ZipFS"/>
            <EventID>0</EventID>
            <Level>1</Level>
            <Task>0</Task>
            <Keywords>Keywords</Keywords>
            <TimeCreated SystemTime="2023-01-11T13:43:28Z"/>
            <EventRecordID>-2066078078</EventRecordID>
            <Channel>Application</Channel>
            <Computer>dw1sdwk0000QZ</Computer>
            <Security/>
        </System>
        <EventData>
            <Data>Invalid operation on Read Only File System. Write to File failures in last 32 seconds: 3</Data>
        </EventData>
    </Event>
    <Event>
        <System>
            <Provider Name="ZipFS"/>
            <EventID>0</EventID>
            <Level>1</Level>
            <Task>0</Task>
            <Keywords>Keywords</Keywords>
            <TimeCreated SystemTime="2023-01-11T13:43:52Z"/>
            <EventRecordID>-2066053359</EventRecordID>
            <Channel>Application</Channel>
            <Computer>dw1sdwk0000QZ</Computer>
            <Security/>
        </System>
        <EventData>
            <Data>Invalid operation on Read Only File System: Delete File</Data>
        </EventData>
    </Event>
    <Event>
        <System>
            <Provider Name="ZipFS"/>
            <EventID>0</EventID>
            <Level>1</Level>
            <Task>0</Task>
            <Keywords>Keywords</Keywords>
            <TimeCreated SystemTime="2023-01-11T13:44:23Z"/>
            <EventRecordID>-2066022750</EventRecordID>
            <Channel>Application</Channel>
            <Computer>dw1sdwk0000QZ</Computer>
            <Security/>
        </System>
        <EventData>
            <Data>Invalid operation on Read Only File System. Delete File failures in last 30 seconds: 2</Data>
        </EventData>
    </Event>
    <Event>
        <System>
            <Provider Name="W3SVC-WP"/>
            <EventID>2303</EventID>
            <Level>2</Level>
            <Task>0</Task>
            <Keywords>Keywords</Keywords>
            <TimeCreated SystemTime="2023-01-12T04:45:51Z"/>
            <EventRecordID>-2011934843</EventRecordID>
            <Channel>Application</Channel>
            <Computer>dw1sdwk0000QZ</Computer>
            <Security/>
        </System>
        <EventData>
            <Data>supportservice-westus2-dev__b339</Data>
            <Binary>02000780</Binary>
        </EventData>
    </Event>
    <Event>
        <System>
            <Provider Name="W3SVC-WP"/>
            <EventID>2303</EventID>
            <Level>2</Level>
            <Task>0</Task>
            <Keywords>Keywords</Keywords>
            <TimeCreated SystemTime="2023-01-12T04:45:51Z"/>
            <EventRecordID>-2011934750</EventRecordID>
            <Channel>Application</Channel>
            <Computer>dw1sdwk0000QZ</Computer>
            <Security/>
        </System>
        <EventData>
            <Data>supportservice-westus2-dev__b339</Data>
            <Binary>02000780</Binary>
        </EventData>
    </Event>
    <Event>
        <System>
            <Provider Name="ZipFS"/>
            <EventID>0</EventID>
            <Level>1</Level>
            <Task>0</Task>
            <Keywords>Keywords</Keywords>
            <TimeCreated SystemTime="2023-01-12T05:30:40Z"/>
            <EventRecordID>-2009245828</EventRecordID>
            <Channel>Application</Channel>
            <Computer>dw1sdwk0000QZ</Computer>
            <Security/>
        </System>
        <EventData>
            <Data>Failed to load dwasmod.dll</Data>
        </EventData>
    </Event>
</Events>
### Debug your Azure website remotely.
>it is not public

### Mention any other details that might be useful.
>Target framework : .NET 6.0
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by marspox** [comment]
Hi,
did you figure out where the problem was?

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
