### ISSUE TITLE
.NET Core memory dumps all invalid

### ISSUE THREAD

**Issue by kierenj** [projectkudu/kudu#3427]
# Context
- Kudu Build 99.41021.5971.0 (Commit: a909ac0974)
- Azure App Service 99.0.10.793
- .NET Core (`net6.0` / `win-x64`)

# The problem
When I use the Process Explorer -> Properties -> Download memory dump feature, the resulting file is always approx. 12.1kb - despite the working set being ~1.9GB, private memory ~2.5GB. The dump file size doesn't vary with memory usage.

Have tried manually changing the `dumpType` query parameter to other values (1 through 5 - I don't know which are valid!) and either get the same ~12.1kb file or a ~4.1kb one.

When I open any of these dumps in VS 2022 and try `Debug with Native Only` (the only option I get), it says `Failed to launch minidump. The minidump file is corrupt`.

When I open any of them in dotMemory, it says, `Unable to import the dump: The dump contains no CLR data.`.

**Comment by kierenj** [comment]
As an aside, if I use `Microsoft.Diagnostics.Runtime` (`DataTarget.CreateSnapshotAndAttach`) to get memory diagnostics info myself, then that works fine.

**Comment by kierenj** [comment]
I don't know how/why this happened, but I discovered that the process running on the App Service was an x64 (64-bit) process.

This is despite the App Service being set to 32-bit mode - surely that shouldn't be possible?

When I set the App Service to 64-bit mode, Kudu started displaying the command line for the process in question, and the `Download memory dump` process works.

**Comment by kierenj** [comment]
Now however I get a 504 Gateway Timeout trying to get the dump. Because it's large. Which is why I want the dump! :)

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
