### ISSUE TITLE
APP SERVICE / SERVER ERROR

### ISSUE THREAD

**Issue by glenn1925** [projectkudu/kudu#3428]
Hi Kudu Team,

Anyone encounter this error and what is the fix?

Server Error in '/' Application.

The environment block used to start a process cannot be longer than 65535 bytes. Your environment block is 68453 bytes long. Remove some environment variables and try again.

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack race for more information about the error and where it originated on the code.

You can access the image in the link below.

![image](https://user-images.githubusercontent.com/39537420/214355688-f869cf36-0a14-4d6c-a64d-64d6e5968a19.png)

Thanks,
GCE

**Comment by akorkiatupa** [comment]
Just encountered this same issue with .NET 6  application running on Azure App Services. Which is particularly weird is that we have a production slot and a staging slot, production slot kudu works fine. Staging slot kudu throws that exact error. 

Also our application in the staging slot reports to be healthy and responds to health request normally. 

Application event logs are also missing and cannot be retrieved.

We have 163 application settings configuring different aspects of the application.

![image](https://github.com/projectkudu/kudu/assets/45167282/ac403908-624f-4d66-940a-9517413f8a0f)

**Comment by akorkiatupa** [comment]
Update:

Actually when looked into it, that one production slot is the only one where it works. We have three environments which all have two slots each. Kudu is broken in 5/6 applications because of the threshold which has been breached.

**Comment by Prologh** [comment]
Bumping this issue as it affects my deployments as well.

**Comment by renrutsirhc** [comment]
Could be something to do with this: https://devblogs.microsoft.com/oldnewthing/20230404-00/?p=108009

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service

**Comment by Prologh** [comment]
@jvano Did you just copy & pasted this generic placeholder response to half of open issues on this project? People are devoting their precious time to create and discuss issues and this is all you can do? How shameful and disrespectful.

The least you could do is report this back to the appropriate department **ON YOUR OWN** instead of pushing this responsibility onto the community. Otherwise, these issues will die out, but probably this is exactly what you are after, that is, problems _"solved"_.

![image](https://github.com/projectkudu/kudu/assets/19705370/e23ace74-fa19-4b66-b647-fddc8d9b3f2b)

**Comment by jvano** [comment]
I'm sorry but this project has not been maintained properly for quite some time. Kudu will continue in Azure App Service, but this repo will no longer be maintained. That's why we are asking to open Azure support incidents moving forward.
