### ISSUE TITLE
Start triggered webjob from the webjobs dashboard

### ISSUE THREAD

**Issue by robbendavid** [projectkudu/kudu#3429]
The webjobs dashboard (/azurejobs/#/jobs) gives an overview of all webjobs.
However, to start a particular job, you need to go to the Azure portal.
It would be useful to have a start button there - and perhaps a stop button too.

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
