### ISSUE TITLE
File lock issue in site extensions when called by Azure API (via Terraform AzAPI)

### ISSUE THREAD

**Issue by SeanKilleen** [projectkudu/kudu#3435]
> For deployment issues, please provide us with the following information:
> ---------------------------------------------------------------

### Repro steps.
> your project built successfully on your dev machine but failed on Azure?
> please write down your build tools and their versions (ie `Msbuild 15.1.0.0`)

This occurred during a possibly interesting edge case. 

We deployed an instance of the Datadog site extension via the AzAPI provider of Terraform:

```terraform
resource "azapi_resource" "mainapp_datadog_extension" {
  count = var.uses_app_slot ? 0 : 1 # Don't run it when we're running for a slot

  type      = "Microsoft.Web/sites/siteextensions@2022-03-01"
  name      = "Datadog.AzureAppServices.DotNet"
  parent_id = jsondecode(data.azapi_resource.azapi_site_mainapp.output).id
}
```

The `count` line was subsequently added because I'd forgotten it causing the extension to be deleted as expected until the time I deployed to an environment that uses the main app (this current client is using app slots as full-fledged environments. I know, I know. I'm working on it.) 

When deploying to the main site once again, I saw the error in the Terraform apply response.

So in summary I think the step is:

* Enable an extension via Az API (maybe with terraform, but likely independent of it)
* Remove the extension via Az API (maybe with terraform, but likely independent of it)
* Enable the same extension again for the same site/slot.
* Expected behavior: Enabling it once again works
* Actual behavior: See error message shown below.

### Project structures.
> in order to reproduce your issue at our end we need a simple 
> [github repository](https://github.com/projectkudu/kudu/wiki/Using-a-git-repo-to-report-an-issue)
> that highlights structure of the project

I can work on this if needed but since it's a straight-forward API call I'm hoping I don't need to. I might be able to work out some curl requests to see if I can reproduce but since this is my client's infrastructure I'd prefer to avoid recreating the symptom.

### The log/error given by the failure.

> "System.IO.IOException: The process cannot access the file because it is being used by another process.\r\n   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)\r\n   at System.IO.File.InternalMove(String sourceFileName, String destFileName, Boolean checkHost)\r\n   at System.IO.Abstractions.FileWrapper.Move(String sourceFileName, String destFileName)\r\n   at Kudu.Core.Infrastructure.FileSystemHelpers.MoveDirectory(String sourceDirName, String destDirName) in C:\\Kudu Files\\Private\\src\\master\\Kudu.Core\\Infrastructure\\FileSystemHelpers.cs:line 68\r\n   at Kudu.Core.Infrastructure.FileSystemHelpers.MoveDirectory(String sourceDirName, String destDirName) in C:\\Kudu Files\\Private\\src\\master\\Kudu.Core\\Infrastructure\\FileSystemHelpers.cs:line 75\r\n   at Kudu.Core.Infrastructure.FileSystemHelpers.MoveDirectory(String sourceDirName, String destDirName) in C:\\Kudu Files\\Private\\src\\master\\Kudu.Core\\Infrastructure\\FileSystemHelpers.cs:line 75\r\n   at Kudu.Core.Infrastructure.OperationManager.<>c__DisplayClass2_0.<Attempt>b__0() in C:\\Kudu Files\\Private\\src\\master\\Kudu.Core\\Infrastructure\\OperationManager.cs:line 18\r\n   at Kudu.Core.Infrastructure.OperationManager.Attempt[T](Func`1 action, Int32 retries, Int32 delayBeforeRetry, Func`2 shouldRetry) in C:\\Kudu Files\\Private\\src\\master\\Kudu.Core\\Infrastructure\\OperationManager.cs:line 43\r\n   at Kudu.Core.Infrastructure.OperationManager.Attempt(Action action, Int32 retries, Int32 delayBeforeRetry) in C:\\Kudu Files\\Private\\src\\master\\Kudu.Core\\Infrastructure\\OperationManager.cs:line 20\r\n   at Kudu.Core.SiteExtensions.SiteExtensionManagerV2.EnsureInstallationEnvironment(String installationDir, ITracer tracer) in C:\\Kudu Files\\Private\\src\\master\\Kudu.Core\\SiteExtensions\\SiteExtensionManagerV2.cs:line 525\r\n   at Kudu.Core.SiteExtensions.SiteExtensionManagerV2.<InstallExtension>d__26.MoveNext() in C:\\Kudu Files\\Private\\src\\master\\Kudu.Core\\SiteExtensions\\SiteExtensionManagerV2.cs:line 479\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Kudu.Core.SiteExtensions.SiteExtensionManagerV2.<TryInstallExtension>d__25.MoveNext() in C:\\Kudu Files\\Private\\src\\master\\Kudu.Core\\SiteExtensions\\SiteExtensionManagerV2.cs:line 259"

### Debug your Azure website remotely.
> it is recommanded that you share your Web App name, directly or [indirectly](https://github.com/projectkudu/kudu/wiki/Reporting-your-site-name-without-posting-it-publicly)
> we can take a look at what's going on.

### Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by SeanKilleen** [comment]
Interesting side note to this -- once in this state, I'm not sure how to get Kudu to recover. This error persists across app service restarts and I'm unaware of a way to restart the kudu service itself for a given app service.

**Comment by SeanKilleen** [comment]
Another update - Migration the app service from one app service plan to another does not appear to have released this file lock. I'm not sure what to do next but I am surprised that I cannot seem to get anything to release the lock that the AzAPI + Kudu services sees on a file. (I am able to add and remove the site extension within the UI just fine).

As a next step I'll try to scale the app down and up again. Hoping that will kill the worker process and release the hold. 🤞

**Comment by SeanKilleen** [comment]
Scaling the app up and down again, which I swore would restart the worker process, also does not appear to have any effect on fixing this.

**Comment by chintavasisht** [comment]
> > ## For deployment issues, please provide us with the following information:
> 
> ### Repro steps.
> > your project built successfully on your dev machine but failed on Azure?
> > please write down your build tools and their versions (ie `Msbuild 15.1.0.0`)
> 
> This occurred during a possibly interesting edge case.
> 
> We deployed an instance of the Datadog site extension via the AzAPI provider of Terraform:
> 
> ```terraform
> resource "azapi_resource" "mainapp_datadog_extension" {
>   count = var.uses_app_slot ? 0 : 1 # Don't run it when we're running for a slot
> 
>   type      = "Microsoft.Web/sites/siteextensions@2022-03-01"
>   name      = "Datadog.AzureAppServices.DotNet"
>   parent_id = jsondecode(data.azapi_resource.azapi_site_mainapp.output).id
> }
> ```
> 
> The `count` line was subsequently added because I'd forgotten it causing the extension to be deleted as expected until the time I deployed to an environment that uses the main app (this current client is using app slots as full-fledged environments. I know, I know. I'm working on it.)
> 
> When deploying to the main site once again, I saw the error in the Terraform apply response.
> 
> So in summary I think the step is:
> 
> * Enable an extension via Az API (maybe with terraform, but likely independent of it)
> * Remove the extension via Az API (maybe with terraform, but likely independent of it)
> * Enable the same extension again for the same site/slot.
> * Expected behavior: Enabling it once again works
> * Actual behavior: See error message shown below.
> 
> ### Project structures.
> > in order to reproduce your issue at our end we need a simple
> > [github repository](https://github.com/projectkudu/kudu/wiki/Using-a-git-repo-to-report-an-issue)
> > that highlights structure of the project
> 
> I can work on this if needed but since it's a straight-forward API call I'm hoping I don't need to. I might be able to work out some curl requests to see if I can reproduce but since this is my client's infrastructure I'd prefer to avoid recreating the symptom.
> 
> ### The log/error given by the failure.
> > "System.IO.IOException: The process cannot access the file because it is being used by another process.\r\n   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)\r\n   at System.IO.File.InternalMove(String sourceFileName, String destFileName, Boolean checkHost)\r\n   at System.IO.Abstractions.FileWrapper.Move(String sourceFileName, String destFileName)\r\n   at Kudu.Core.Infrastructure.FileSystemHelpers.MoveDirectory(String sourceDirName, String destDirName) in C:\Kudu Files\Private\src\master\Kudu.Core\Infrastructure\FileSystemHelpers.cs:line 68\r\n   at Kudu.Core.Infrastructure.FileSystemHelpers.MoveDirectory(String sourceDirName, String destDirName) in C:\Kudu Files\Private\src\master\Kudu.Core\Infrastructure\FileSystemHelpers.cs:line 75\r\n   at Kudu.Core.Infrastructure.FileSystemHelpers.MoveDirectory(String sourceDirName, String destDirName) in C:\Kudu Files\Private\src\master\Kudu.Core\Infrastructure\FileSystemHelpers.cs:line 75\r\n   at Kudu.Core.Infrastructure.OperationManager.<>c__DisplayClass2_0.b__0() in C:\Kudu Files\Private\src\master\Kudu.Core\Infrastructure\OperationManager.cs:line 18\r\n   at Kudu.Core.Infrastructure.OperationManager.Attempt[T](Func`1 action, Int32 retries, Int32 delayBeforeRetry, Func`2 shouldRetry) in C:\Kudu Files\Private\src\master\Kudu.Core\Infrastructure\OperationManager.cs:line 43\r\n   at Kudu.Core.Infrastructure.OperationManager.Attempt(Action action, Int32 retries, Int32 delayBeforeRetry) in C:\Kudu Files\Private\src\master\Kudu.Core\Infrastructure\OperationManager.cs:line 20\r\n   at Kudu.Core.SiteExtensions.SiteExtensionManagerV2.EnsureInstallationEnvironment(String installationDir, ITracer tracer) in C:\Kudu Files\Private\src\master\Kudu.Core\SiteExtensions\SiteExtensionManagerV2.cs:line 525\r\n   at Kudu.Core.SiteExtensions.SiteExtensionManagerV2.d__26.MoveNext() in C:\Kudu Files\Private\src\master\Kudu.Core\SiteExtensions\SiteExtensionManagerV2.cs:line 479\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Kudu.Core.SiteExtensions.SiteExtensionManagerV2.d__25.MoveNext() in C:\Kudu Files\Private\src\master\Kudu.Core\SiteExtensions\SiteExtensionManagerV2.cs:line 259"
> 
> ### Debug your Azure website remotely.
> > it is recommanded that you share your Web App name, directly or [indirectly](https://github.com/projectkudu/kudu/wiki/Reporting-your-site-name-without-posting-it-publicly)
> > we can take a look at what's going on.
> 
> ### Mention any other details that might be useful.
> > Thanks! We'll be in touch soon.



> Interesting side note to this -- once in this state, I'm not sure how to get Kudu to recover. This error persists across app service restarts and I'm unaware of a way to restart the kudu service itself for a given app service.

+1 @SeanKilleen  Have been running into the same exact issue even before this issue was created. Restarting the kudu console does not get me past this issue either. So I restart the entire website through the Azure portal, then log back in to the kudu console(You can find it from under Development Tools->Advanced Tools). 

Go to the Site Extensions tab and move to the gallery section from there, find the extension Im looking for and then install it from there (If it still throws the file locked error, just retry the process). Then I restart the site from within Kudu and uninstall it again from Kudu(from the Installed section) and do a final restart from Kudu because I need to get it to work with Terraform.

It would be great if this were fixed. I don't know what causes the file to get locked up, but Im interested in working together and fix this issue

**Comment by jvano** [comment]
Hi

Please file incidents in Azure, so we can better track and assist on this case:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

Thanks,

Joaquin
