### ISSUE TITLE
Where to get the su password in Linux App Service?

### ISSUE THREAD

**Issue by saigkill** [projectkudu/kudu#3438]
I set up a new project by using the Linux App Service. Now i would experiment a little bit with the Deployment Groups on Azure DevOps. For installing and configuring there is a bash script what can be used. That script contains `sudo` commands, what not work, because sudo isnt availble on Kudu.
In general it could be possible to use `su` inside the script instead. But how can i get the su password? Itried to use the PAT and also that password, what is inside the publish profile from the app.

**Comment by kamilwasyl** [comment]
did you find ?

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
