### ISSUE TITLE
Azure Web App  No Such Host Is Known

### ISSUE THREAD

**Issue by glenn1925** [projectkudu/kudu#3439]
Hi Kudu Team,

Anyone encounter this error " No Such Host Is Known" before when using Azure Application insights transactional search?

The error occurs between two web App service with VNET integration. 

Exact: Error Message in Application Insight Transaction Search

Problem Id:System.Net.Sockets.SocketException at xxxxxxx.webappproxy.Shared.Services.UserSubscriptionService+<GetUserSubscriptions>d_24MoveNext

Any thoughts?

Thanks,

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
