### ISSUE TITLE
Adding environment variable in applicationHost.xdt doesn't work with Azure Function main process.

### ISSUE THREAD

**Issue by tanaka-takayoshi** [projectkudu/kudu#3444]
> For deployment issues, please provide us with the following information:
> ---------------------------------------------------------------

### Repro steps.
1. Deploy a simple Azure Function app to Azure. (I'm using a project template in VS.)
2. Open a kudu.
3. Add applicationhost.xdt with the following content under `d:\home\site\`. The step and sample file is provided [in this project's wiki](https://github.com/projectkudu/kudu/wiki/Xdt-transform-samples#adding-environment-variables).
   ```
   <configuration xmlns:xdt="http://schemas.microsoft.com/XML-Document-Transform"> 
     <system.webServer> 
       <runtime xdt:Transform="InsertIfMissing">
         <environmentVariables xdt:Transform="InsertIfMissing">
           <add name="FOO" value="BAR" xdt:Locator="Match(name)" xdt:Transform="InsertIfMissing" />    
         </environmentVariables>
       </runtime> 
     </system.webServer> 
   </configuration> 
   ```
4, Restart the function.

### Project structures.
Using a template Azure Function project by Visual Studio.

### The log/error given by the failure.
The environment variable "FOO" is not in the main w3wp process.
![image](https://user-images.githubusercontent.com/846156/222475614-898ee252-5ea6-401e-8fac-48f867e1d254.png)

However, that environment variable is in the scm w3wp process.
![image](https://user-images.githubusercontent.com/846156/222475735-31573940-a1f4-49fb-819e-ab3150fe916f.png)

I couldn't find the Transformation log for the main process.
![image](https://user-images.githubusercontent.com/846156/222476871-7c3f8dd9-5381-443b-bad3-3440f9a34cf4.png)

When I test this feature with Azure Web Apps, it works fine. Therefore, is this an Azure Function-specific issue or constraint?

### Debug your Azure website remotely.
```
2023-03-02T15:29:49.925 [Information] Executed 'Function1' (Succeeded, Id=ece41929-204b-4b3a-806a-c42fb4da121b, Duration=8ms)
```

### Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
