### ISSUE TITLE
Are azure function instances share the same quota for `%tmp%` inside the sandbox?

### ISSUE THREAD

**Issue by xiaomi7732** [projectkudu/kudu#3446]
According to [this wiki](https://github.com/projectkudu/kudu/wiki/Understanding-the-Azure-App-Service-file-system), sites share disk spaces for the same plan.

Could you please clarify, upon scale out, are the instances getting their own space or are they share the same quota?

For example, **1 site** on EP1, **10 instances**, are they getting 15GB each in `%tmp%`, or will they share 15GB?

We are seeing out of disk space exceptions in some of our EP2/EP3 functions, trying to extract content into %tmp%.

Also, is there a better place than `%tmp%` for local disk? The remote disk (%HOME%) is not fast enough for us.

FWIW, here's the quote from the wiki above that talking about sharing between sites:

```
...
For instance, if you have 10 sites in S2 App Service Plan, those sites (and their scm sites) will have a combined limit of 15 GB. See limit for other SKU below.
...
```

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
