### ISSUE TITLE
Kudu API '/api/dump' has some limitations to get response?

### ISSUE THREAD

**Issue by mshyatsu** [projectkudu/kudu#3447]
I believe Kudu API `/api/dump` does not return entire files under the LogFiles directory if a lot of files exist there. It likely depends on the file size (http response size). If we have a lot of files on the Logfiles directory, we can get only old-date files, and somehow, we miss new-date files. If we have some limitation on `/api/dump`, it would be nice if we could add a description on the doc. Thanks.

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
