### ISSUE TITLE
SiteExtensionInstallationLock needs a ShutdownDelaySemaphore

### ISSUE THREAD

**Issue by eliaslopezgt** [projectkudu/kudu#3449]
### Repro steps.
When ARM invokes the SiteExtension installation controller the operation returns immediately since it is performed in the background. This operation can be interrupted by a site config change that triggers a recycle for the SCM site.

### Mention any other details that might be useful.
This happens due to the fact that the `SiteExtensionInstallationLock` does not use a `ShutdownDelaySemaphore` in the same way that `DeploymentLock` uses it.  This will guarantee that the recycle only takes place after the Site Extension installation has been completed.

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service

**Comment by wsmelton** [comment]
This issue was created because of a case with my company and Dynatrace software developers troubleshooting for 3+ months because we could replicate the error for 3+ months straight...frankly still can even now (over a YEAR LATER). 

😆 😆 🤣

**Comment by jvano** [comment]
That's the problem, that this repo hasn't been properly maintained. Soon, we will be archiving this repo as it won't be maintained, and that's why we are asking to file Azure incidents moving forward. That way we will be able to help right away.
