### ISSUE TITLE
Using AzureFunctionApp@2 in ADO, the pipeline always fails if the action updates the configuration of the app

### ISSUE THREAD

**Issue by Gabriel123N** [projectkudu/kudu#3456]
> For deployment issues, please provide us with the following information:
> ---------------------------------------------------------------

### Repro steps.
1. Create an ADO repository
2. Push the default ASP.NET Core application to the repository
3. Create an app service webapp (tested on I2v2 and B1 plans)
4. Configure a service connection for the deployment
5. Create a pipeline with two stage:
 - Build and publish stage of the ASP.NET app 
 - Deployment using the task `AzureFunctionApp@2`
6. Deploy the pipeline
- The pipeline should fail to deploy after 25 minutes
8. Redeploy the pipeline
- The pipeline will succeed
9. Delete "WEBSITES_ENABLE_APP_SERVICE_STORAGE":"true" and "WEBSITE_RUN_FROM_PACKAGE":"1" from the app service webapp
10. Redeploy the pipeline
- The pipeline will fail again after 25 minutes
11. Repeat step 9 and 10 indefinitely and the pipeline will always fail

### Project structures.
Basic ASP.NET Core app generated by dotnet cli and a basic azure-pipelines.yml deployment pipeline

### The log/error given by the failure.
> Got service connection details for Azure App Service:'*********'
(node:23614) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
Trying to update App Service Application settings. Data: {"WEBSITES_ENABLE_APP_SERVICE_STORAGE":"true","WEBSITE_RUN_FROM_PACKAGE":"1"}
Updated App Service Application settings and Kudu Application settings.
Package deployment using ZIP Deploy initiated.
Updating submodules.
Preparing deployment for commit id '219a881b-c'.
PreDeployment: context.CleanOutputPath False
PreDeployment: context.OutputPath /home/site/wwwroot
Generating deployment script.
Using cached version of deployment script (command: 'azure -y --no-dot-deployment -r "/tmp/zipdeploy/extracted" -o "/home/site/deployments/tools" --basic --sitePath "/tmp/zipdeploy/extracted"').
Running deployment command...
Command: "/home/site/deployments/tools/deploy.sh"
Handling Basic Web Site deployment.
Kudu sync from: '/tmp/zipdeploy/extracted' to: '/home/site/wwwroot'
Copying file: 'host.json'
Copying file: '***/function.json'
Copying file: '***/function.json'
Copying file: 'bin/***.dll'
Copying file: 'bin/***.pdb'
Copying file: 'bin/***.dll'
Copying file: 'bin/***.pdb'
Copying file: 'bin/***.dll'
Copying file: 'bin/***.pdb'
Copying file: 'bin/***.dll'
Copying file: 'bin/***.pdb'
Copying file: 'bin/***.dll'
Copying file: 'bin/***.pdb'
Copying file: 'bin/extensions.json'
Copying file: 'bin/function.deps.json'
Finished successfully.
Running post deployment command(s)...
Triggering recycle (preview mode disabled).
Deployment successful. deployer = VSTS_ZIP_DEPLOY_FUNCTIONS_V2 deploymentPath = Functions App ZipDeploy. Extract zip.
##[error]Failed to deploy web package to App Service.
##[error]To debug further please check Kudu stack trace URL : https://$***:***@***.scm.***.appserviceenvironment.net/api/vfs/LogFiles/kudu/trace
##[error]Error: Package deployment using ZIP Deploy failed. Refer logs for more details.
Successfully added release annotation to the Application Insight :***
Successfully updated deployment History at https://***.scm.***.appserviceenvironment.net/api/deployments/214281681374449739
App Service Application URL: https://***.***.appserviceenvironment.net/
Finishing: Deploy function ***

Even though this line is present `Deployment successful.`, the deployment is reported as failed in the deployment center and pipeline

## Additional information

While on the I2v2 plan, the issue only happens when the plan is reaching high RAM usage, this issue is 100% replicable on the B1 plan.

**Comment by FinVamp1** [comment]
@Gabriel123N  are you deploying a Standard Asp.Net Core App? We have the AzureRMWebAppDeployment v4 task for those rather than the Function Task?

**Comment by FinVamp1** [comment]
@Gabriel123N are you deploying to a Linux plan? Which SKU? I will try and reproduce this and see if there's a better way to handle this.

**Comment by FinVamp1** [comment]
@Gabriel123N  I've tried to reproduce this and need a bit more information. Can you share anything more?

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
