### ISSUE TITLE
Can kudu console show non-English words?

### ISSUE THREAD

**Issue by yuanweilei** [projectkudu/kudu#3458]
Can kudu console show non-English words?

### Repro steps.
> Open kudu console and upload a file with non-English file name (e.g. Japanaese file name)
> Input dir command and see the results. The file name becomes ???

![image](https://user-images.githubusercontent.com/26296423/232944867-98accb93-4962-4013-a0ae-5f9413bd1a60.png)

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
