### ISSUE TITLE
Using Github Actions In two repos; Same App service; API and Frontend; Thread Aborted, 25% of time works.

### ISSUE THREAD

**Issue by John-Donalson** [projectkudu/kudu#3461]
Have two repos. One for frontend, deploy .vue app.
Another in .net, deploys /api of app service

both are suppose to deploy to same azure webapp service with github actions leaving the other in tact;

I have tried the following: appending /api to the end of zipdeploy publish profile for api repo;
setting the following app settings; 

    WEBSITE_WEBDEPLOY_USE_SCM                                           = "true"
    WEBSITE_RUN_FROM_PACKAGE                                            = "0"
    WEBSITE_WEBDEPLOY_DO_NOT_DELETE                                     = "true"
    MSDEPLOY_RENAME_LOCKED_FILES                                        = "0"
    MSDEPLOY_USE_CHECKSUM                                               = "true"
    WEBSITE_LOCAL_CACHE_OPTION                                          = "Never"
    SCM_TOUCH_WEBCONFIG_AFTER_DEPLOYMENT                                = "0"
    SCM_COMMAND_IDLE_TIMEOUT                                            = "900"

This deploys them correctly, however sometimes the .vue app i will have to rerun, and get several different errors such as; handler error; thread aborted; starts copying the files, but then stops halfway with thread aborted. etc
- Thread Aborted

any suggestions to achieve multiple deployments to the same app service; with github actions... 
![timeout](https://user-images.githubusercontent.com/113437897/235964215-2d46582a-943e-4d40-9b36-1e815af7daff.PNG)

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
