### ISSUE TITLE
Git Deployment to Azure

### ISSUE THREAD

**Issue by lili9000** [projectkudu/kudu#3462]
Tried to use git to deploy PHP web application. Found some old files remained at wwwroot while the old files were removed in repository after a new deployment. Any idea why the repo and wwwroot were not synchronized? Should I use .deployment file to add the ClearOutputPath parameter to clean up the wwwroot?

[config]
command = deploy.cmd
ClearOutputPath = true

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
