### ISSUE TITLE
Git deploy to Azure - how to set context.CleanOutputPath True?

### ISSUE THREAD

**Issue by lili9000** [projectkudu/kudu#3463]
Now I got PreDeployment: context.CleanOutputPath False, the files in wwwroot could not be cleaned up before a new deployment.

How to set context.CleanOutputPath True?

**Comment by bonjarno** [comment]
I have the same issue. The first deployment succeeds and then all the rest fail due to Onyx not being able to copy files to /home/wwwroot. Hoping that not only is this the problem but that someone out there knows how to change that setting?

**Comment by bGN4** [comment]
According to this document: https://learn.microsoft.com/en-us/azure/app-service/deploy-zip?tabs=api#kudu-publish-api-reference
I have tried to set the deploy url like this: https://${APP_NAME}.scm.azurewebsites.net/api/zipdeploy?clean=true
but it doesn't work ...

**Comment by jvano** [comment]
You will need to use the following /publish endpoint (aka OneDeploy)
https://<app-name>.scm.azurewebsites.net/api/publish

For more information on the parameters that you can pass:
https://learn.microsoft.com/en-us/azure/app-service/deploy-zip?tabs=api#kudu-publish-api-reference
