### ISSUE TITLE
Support for more than 299 items

### ISSUE THREAD

**Issue by qian1628** [projectkudu/kudu#3464]
When navigating to C:\home\site\wwwroot we only see the first 299 directories and files.

Expected: Could you please help us change the max file limit to 400?

**Comment by qian1628** [comment]
I refer to this commit https://github.com/projectkudu/kudu/commit/719319a11cf4a75608914696482e7d20aff0b56d

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
