### ISSUE TITLE
Confusing Docs entry on KUDU security

### ISSUE THREAD

**Issue by askpatrickw** [projectkudu/kudu#3469]
https://github.com/projectkudu/kudu/wiki/Accessing-the-kudu-service#security

>Ones with Kudu access are ones owning the site - regardless if read-only or not. To expand, they can deploy any codes (good or malicious) to and able to read any secret settings of the site (eg. KeyVault, SQL and Storage credentials, Private Certificates, etc.). Hence for Azure, only those with Contributor / Owner access (to be exact, with microsoft.web/sites/publish/action or, for slot, microsoft.web/sites/slots/publish/action) can access to Kudu (SCM).

This paragraph is confusing and needs a review and edit.
Is the intent to say, Anyone with access to KUDU has full control of the app and their is no Reader access to KUDU?

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
