### ISSUE TITLE
publish using zip deploy is not supported for virtual application

### ISSUE THREAD

**Issue by skarlapudi** [projectkudu/kudu#3474]
> For deployment issues, please provide us with the following information:
> ---------------------------------------------------------------

### Repro steps.
> your project built successfully on your dev machine but failed on Azure? Yes

### The log/error given by the failure.
> I am tyring to deploy an application as virtual application in Azure app service (eg site/wwwroot/app1) using zip deploy. But im getting the following error. 
"publish using zip deploy is not supported for virtual application"

i came acrorss this thread https://github.com/Microsoft/azure-pipelines-tasks/issues/10035, where the same problem was reported. and closing notes as "it is a feature request to Azure App Service. Can you please post your query [here](https://github.com/projectkudu/kudu/issues)?" 

is this feature  still not available?
![Screenshot 2023-07-14 173731](https://github.com/projectkudu/kudu/assets/1932777/33d93452-3b63-436f-9a1a-35dddf964644)

**Comment by jvano** [comment]
Hi

You can use the new /publish endpoint (aka OneDeploy) on App Service.

For more info: 
https://learn.microsoft.com/en-us/azure/app-service/deploy-zip?tabs=cli#kudu-publish-api-reference

If the problem persists, please file incidents in Azure, so we can better track and assist on this case:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

Thanks,

Joaquin
