### ISSUE TITLE
Online editor changes file content using auto-formatting and causes errors in specific cases for xml mimetype

### ISSUE THREAD

**Issue by dvanwissen** [projectkudu/kudu#3475]
> For deployment issues, please provide us with the following information:
> ---------------------------------------------------------------

### Repro steps.
When:
- editing an xml-mimetype file in the online editor (like xslt)

### Project structures.
any xml mimetype file, but with XSLT files it is generating faulty output

### The log/error given by the failure.
File content changes which gives errors in our use-case

### Debug your Azure website remotely.
n.a.

### Mention any other details that might be useful.
Auto-formatting changes the file contents automatically. Auto-formatting should be an optional setting (couldn't find one) and not be the default. It should also not change file content that could alter the desired output like with XSLT-files. For example: When using `<xsl:value-of select="selectedvalue"/>` it put this tag on a new line automatically.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service

**Comment by jvano** [comment]
Sorry, this project has been maintained properly for quite some time. Kudu will continue in Azure App Service. However, this repo will no longer be maintained. That's why we are asking to open Azure support incidents moving forward.

**Comment by dvanwissen** [comment]
> Sorry, this project has been maintained properly for quite some time. Kudu will continue in Azure App Service. However, this repo will no longer be maintained. That's why we are asking to open Azure support incidents moving forward.

Thank you for your reply, that makes a bit more sense then :) I'll open an Azure support incident.
