### ISSUE TITLE
ZipDeploy/Web/Ftp Deploy (Kudu) via VS 2022 painfully slow the last 3-5 days?

### ISSUE THREAD

**Issue by caliberdigitalllc** [projectkudu/kudu#3480]
hi all,

I've had an azure subscription for a couple of years - we're on a P2V2 ASP, all has been working really well. My microservices usually take about 1 minute to deploy, and my blazor apps take 2-4 minutes, give or take.

Starting quite suddenly on Thursday/Friday last week, deployments are now taking anywhere from 20-60 minutes. I've tried all the usual things - resetting the publish profile, restarting the instance, scaling up, scaling out - I even tried creating a completely fresh API project and fresh web app in azure, and that ran for close to 40 minutes as well - completely bare template app.

I'm quite stumped here. It's not even just one of my apps - it's all of my microservices and all of my blazor apps.

I did trip over this old thread: https://github.com/projectkudu/kudu/issues/1693#issuecomment-142779944

Seems unlikely that's still the fix? especially very suddenly? I will try it.. but I welcome any feedback, because this is a huge setback for productivity.

**Comment by caliberdigitalllc** [comment]
FYI this is still occuring. @davidebbo are you still on this project?

**Comment by davidebbo** [comment]
@caliberdigitalllc sorry, I've been off this project for about 5 years, but hopefully others can jump in.

**Comment by suwatch** [comment]
@caliberdigitalllc   could you start by sharing the subscription and site name (first 3-4 characters of each would do) as well the UTC time of most recent slow deployment?  The more precise time would help us pinpoint easier.

**Comment by caliberdigitalllc** [comment]
@suwatch - the subscription ID is "b0db6839-2057-40e5-9491-7f22b432b3f9" - literally every deployment I've attempted since August 3rd has taken 25-65 minutes - where before over the last 2 years, deployments have never taken more than 1-4 minutes for all of the same applications.

I have tried switching to the Azure CLI - same result.

I have tried deleting one of the app services and re-creating it from scratch - same result.

I have tried reinstalling visual studio - same result.

I have tried different internet connection  - same result.

We have 10 API's and 5 blazor server apps in the subscription - they are all having the same problem. API's used to take 1-2 minutes to deploy via VS2022, now they take 25-35 minutes. The blazor apps used to take 3-5 minutes, now they take over an hour. All of this happened over night with no action from my end. They were working fine prior to 8/3/2023.

I have an active ticket in with Azure support but it's been taking several days between replies and no action plan in place yet.

"SCM Deploy Failing - TrackingID#2308040040008936" is the ticket title and #.

Thanks

**Comment by caliberdigitalllc** [comment]
@suwatch  - here is a typical log entry (August 10th, 9:17AM Eastern Time Started) for one of my blazor app deploys now (folder/domains replaced for privacy). As noted, this same app and my other 4 blazor apps used to take no more than 3-4 minutes (5 minutes TOPS) to deploy.

<redacted app name> -> G:\Development\appfolder\appname\bin\Release\net8.0\linux-x64\appname.dll
appname -> G:\Development\appfolder\appname\obj\Release\net8.0\linux-x64\PubTmp\Out\
Publishing G:\Development\appfolder\appname\obj\Release\net8.0\linux-x64\PubTmp\appname-20230810091753188.zip to https://appname.scm.azurewebsites.net/api/zipdeploy...
Zip Deployment succeeded.
========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
========== Build started at 9:17 AM and took 01:05:27.588 hours ==========
========== Publish: 1 succeeded, 0 failed, 0 skipped ==========

**Comment by suwatch** [comment]
@caliberdigitalllc  are you sure that is the subscription id?   Is your subscription Id "44f1...."?     Understand the privacy on sitename - give us enough and suffix to help identify among your sites in the subscription - such as partial site name is 'bs...ny' etc.

**Comment by caliberdigitalllc** [comment]
Ah yeah. It’s the xxxconfig subscription with all apps prefixed by “bsc”.



Mitchell D. Russell
Founder / Caliber Digital LLC

c: 215-630-6661
e: ***@***.***
w: https://www.caliber-digital.com

**Comment by caliberdigitalllc** [comment]
@suwatch Ah yeah. It’s the xxxconfig subscription with all apps prefixed by “bsc”.

**Comment by caliberdigitalllc** [comment]
FWIW too - just to rule out .net core 8 preview, I tried rolling back to preview 6 from preview 7, and I also tried rolling back to core 7.xx. Nothing changed the outcome.

**Comment by suwatch** [comment]
@caliberdigitalllc  I have gathered and passed along the info to the product team and they should be able to help.   Sorry for the inconvenience.

**Comment by caliberdigitalllc** [comment]
@suwatch thank you. Will they contact me here? This has been an immense productivity impact so I hope the issue can be nailed down soon. I appreciate you connecting with me on it outside of the support ticket.

**Comment by caliberdigitalllc** [comment]
@suwatch  FYI, did another one today - new record for time taken :(  This app used to take 3-5 minutes max before whatever changed.

AppJobTracker -> G:\Development\BSCPlatform\AppJobTracker\bin\Release\net8.0\linux-x64\AppJobTracker.dll
AppJobTracker -> G:\Development\BSCPlatform\AppJobTracker\obj\Release\net8.0\linux-x64\PubTmp\Out\
Publishing G:\Development\BSCPlatform\AppJobTracker\obj\Release\net8.0\linux-x64\PubTmp\AppJobTracker-20230814083718483.zip to https://bscappjobtracker.scm.azurewebsites.net/api/zipdeploy...
Zip Deployment succeeded.
========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
========== Build started at 8:36 AM and took 01:12:48.727 hours ==========
========== Publish: 1 succeeded, 0 failed, 0 skipped ==========
========== Publish started at 8:36 AM and took 01:12:48.727 hours ==========
Waiting for Web App to be ready...
Restarting the Web App...
Successfully restarted Web App.
Web App is ready.

**Comment by suwatch** [comment]
@caliberdigitalllc  Apology for the delay.  The product team has investigated and they would be able to share the finding soon.   Thanks for your patience.

**Comment by caliberdigitalllc** [comment]
Great @suwatch thanks. API's are taking consistently 25 minutes, and blazor apps are taking consistently 1h-1h5m - comparative to before, 1-2 minutes and 3-5 minutes respectively. Glad the team is looking into it actively.

**Comment by vivekjilla** [comment]
@caliberdigitalllc we observed multiple apps in your subscription which are hitting into the slowness, and all of them seem to be taking time at the initial step of uploading the payload zip, before the kudu starts processing it. We also noticed that time taken is proportional to payload sizes, like ~60MB taking ~20 min and ~160MB taking around ~1hr.

Given that you noticed this issue across ZipDeploy, Web/Ftp deploy and also with new apps, current theory is this could be due to any network issue (like VPN etc) on the client which might be slowing down the zip upload step.

To get more insights on this, can you try uploading the zip to a blob storage and then deploy using the az cli with `az webapp deploy` by passing `--src-url`​ as the blob endpoint and let us know if you are still facing issue with this approach also. More details on this: https://learn.microsoft.com/en-us/azure/app-service/deploy-zip?tabs=cli#deploy-a-zip-package

**Comment by caliberdigitalllc** [comment]
@vivekjilla  that did the trick, thank you. it seems to be something wrong with the upload speed on my PC via Comcast which I wouldn't have suspected. For some reason I'm only getting 5mbps upload when I'm contracted for 45mbps.

Funny enough, when I turn my cloudflare VPN (WARP) *on*, the upload speed jumps up to 45mbps and I was just able to upload one of my APIs in under a minute which is back to normal.

Question - where in Azure Portal can I observe the logs that you observed to show that the upload was the slow step?

If I could get one take away from this is that Zipdeploy should have a progress bar on the upload in VS 2022 and the azure CLI so you know where the bottleneck is. Right now you have no idea if it's uploading, deploying, or what, until the upload is completed.

Anyhow - thank you @suwatch  and @vivekjilla for looking into this. Please let me know on the log question.

**Comment by vivekjilla** [comment]
Thanks for the update and the feedback @caliberdigitalllc . I will follow up with my team to see how we can improve this experience. 

Regarding the logs, I don't think we explicitly call out the time taken to upload the zip today in logs. 
But one indicator we can checkout is the Portal -> Deployment Center -> Click on the deployment -> This will show the logs with timestamps. Here, I believe the first log timestamp itself starts 20 mins to 1 hr after the deployment is queued, which kind of indicates the deployment hasn't started until then.

**Comment by jvano** [comment]
Hi

If the problem persists, please file incidents in Azure, so we can better track and assist on this case:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

Thanks,

Joaquin
