### ISSUE TITLE
Azure China Function app ：Why is the bear token authorization for the deployed scm site not ARM Endpoint？ 

### ISSUE THREAD

**Issue by GHL2770** [projectkudu/kudu#3482]
Azure China We use “https://<app_name>.scm.chinacloudsites.cn/api/zipdeploy” deployed ZIP files for Function app, 
we got an error 403 when we got  bear token auth using: “https://management.azure.com/.default”  ARM Endpoint.
But use https://management.core.chinacloudapi.cn/.default ASM Endpoint can be successfully deployed in Azure China.

We want to confirm that the“https://<app_name>.scm.chinacloudsites.cn/api/zipdeploy”authentication is not updated to ARM the endpoint authentication management? If not, are there any relevant instructions
In document  https://learn.microsoft.com/en-us/azure/reliability/asm-retirement ASM Endpoint will outage in August 2024, Will this have an influence on Azure China？
 
![image](https://github.com/projectkudu/kudu/assets/103106974/9b9cb60c-5c0b-4078-a774-2cf4db6e5288)
![image](https://github.com/projectkudu/kudu/assets/103106974/ceca4205-83b1-4e4d-b5ee-8ee0dad4d7f9)
At the same time found in Azure China using “az account get - access - auth token ”using url is https://management.**core.**chinacloudapi.cn ASM Endpoint too.
referenced document:https://docs.azure.cn/en-us/azure-functions/deployment-zip-push#azure-ad-authentication 
![image](https://github.com/projectkudu/kudu/assets/103106974/9bdcb7c3-f32d-44e0-977f-3d539a0dc88f)
![image](https://github.com/projectkudu/kudu/assets/103106974/b1a6ff22-e737-41cb-9ebc-ef73b4e8d19e)

**Comment by suwatch** [comment]
This is a known issue and the fix is being rollout (ETA end of 2024).    In the meantime, continue to use https://management.core.chinacloudapi.cn/ as audience (resource) for now.   This is the audience URL and should continue to work till then.

**Comment by GHL2770** [comment]
Thank you very much~
