### ISSUE TITLE
Diagnostic Dump excludes some logfiles

### ISSUE THREAD

**Issue by tippmar-nr** [projectkudu/kudu#3484]
### Repro steps.
* Create an Azure WebApp and add the `New Relic .NET Agent` extension.
* NewRelic logfiles are written to `C:\home\LogFiles\NewRelic` and can be browsed, downloaded and edited via the Kudu Debug Console. 
* Browse to `C:\home\LogFiles\NewRelic` in the Kudu Debug Console and note which files are present.
* Generate a Kudu Diagnostic Dump.
* Note that two files are missing - one of the `NewRelic.Profiler.*.log` files and the `newrelic_agent_xxx.log` file.
* Stop the WebApp
* Generate a new Kudu Diagnostic Dump
* Note that the two missing files are now included.

NewRelic uses Serilog for writing the log files, which retains an open handle to the file, but opens the file for shared access. There would appear to be some conflict with the Diagnostic Dump tool where it's trying to gain an exclusive lock on the files it adds to the output zip file.
 
### Debug your Azure website remotely.
My website is at https://sampleazurewebappcore.azurewebsites.net/

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
