### ISSUE TITLE
PeriodicRestart not working for App Service configs

### ISSUE THREAD

**Issue by arvindsing** [projectkudu/kudu#3485]
My customer is testing updates to applicationhost.config using XDT trasforms per this documentation: https://github.com/projectkudu/kudu/wiki/Xdt-transform-samples

 and had some questions as it doesn’t appear to be working as expected. Here is the existing config for their test site:
 
### <applicationPools>
      <add name="mgb-cps-test1-dev-e2-app" managedRuntimeVersion="v4.0">
        <processModel identityType="ApplicationPoolIdentity" />
        <recycling logEventOnRecycle="Schedule">
          <periodicRestart>
            <schedule>
              <clear />
              <add value="19:04:00" />
            </schedule>
          </periodicRestart>
        </recycling>
      </add>
      <add name="~1mgb-cps-test1-dev-e2-app" managedRuntimeVersion="v4.0" managedPipelineMode="Integrated">
        <processModel identityType="ApplicationPoolIdentity" />
        <recycling logEventOnRecycle="Schedule">
          <periodicRestart>
            <schedule>
              <clear />
              <add value="19:04:00" />
            </schedule>
          </periodicRestart>
        </recycling>
      </add>
    </applicationPools>
 
**Questions:
Does setting this periodicRestart actually work for App Service configs?
How can we confirm? I was expecting to find something in Logfiles\eventlog.xml and there’s nothing.**

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
