### ISSUE TITLE
Kudo Tabs not showing up

### ISSUE THREAD

**Issue by csanghavi** [projectkudu/kudu#3487]
Kudu Windows does not come up on clicking Web App Service -> Development Tools -> Advanced Tools -> Go

It launches my web app instead. It used to show up the window with all tabs till yesterday. 

How do I get it back ?

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
