### ISSUE TITLE
Zip Deploy Not Deleting Old Zip Files

### ISSUE THREAD

**Issue by sam-karl** [projectkudu/kudu#3492]
Hello I am having issues with the zip deploy function not deleting old zip which leads to my remote machine getting to full and not being able to zip deploy without manually going in and deleting the old zip deploys. 

### Repro steps.
In azure devops pipelines/releases

steps:
- task: AzureRmWebAppDeployment@4
  displayName: 'Azure App Service Deploy: xxx'
  inputs:
    azureSubscription: 'xxxx'
    appType: webAppLinux
    WebAppName: xxx
    packageForLinux: '$(System.DefaultWorkingDirectory)/xxx/appArchive/xxxEngApp.zip'

Zip Deploy Log:
`<step title="Incoming Request" date="2023-11-13T17:08:07.938" instance="7f3fa8" url="/api/zipdeploy?isAsync=true&amp;deployer=VSTS_ZIP_DEPLOY&amp;message=%7B%22type%22%3A%22deployment%22%2C%22commitId%22%3A%2290765f469da1e4e5ec2372a3dfd53fc46c03ed14%22%2C%22buildId%22%3A%222654%22%2C%22releaseId%22%3A%223320%22%2C%22buildNumber%22%3A%2220231113.1%22%2C%22releaseName%22%3A%22Release-10%22%2C%22repoProvider%22%3A%22TfsGit%22%2C%22repoName%22%3A%22xxxs%22%2C%22collectionUrl%22%3A%22https%3A%2F%2Fxxxx%2F%22%2C%22teamProject%22%3A%229512cefc-34ad-4301-bb27-9d93fdc8a8dd%22%2C%22buildProjectUrl%22%3A%22https%3A%2F%2Fxxxx%2F9512cefc-34ad-4301-bb27-9d93fdc8a8dd%22%2C%22repositoryUrl%22%3A%22%22%2C%22branch%22%3A%22main%22%2C%22teamProjectName%22%3A%22xxxx%20IS%20Dept%22%2C%22slotName%22%3A%22production%22%7D" method="POST" type="request" pid="87,1,27" Host="xxxxengineeringtools.scm.azurewebsites.net" User-Agent="VSTS_40c18f3f-47e6-475e-b8c0-d62ae570f413_Release__3320_3339_1" Authorization="Bas..." Content-Type="application/octet-stream" Cookie="ARRAffinity=7f3fa815cc6855aaa408be337cba7c192593dc17293b812c6a2a3f2eeac7d903;Path=/;HttpOnly;Secure;Domain=xxxengineeringtools.scm.azurewebsites.net; ARRAffinitySameSite=7f3fa815cc6855aaa408be337cba7c192593dc17293b812c6a2a3f2eeac7d903;Path=/;HttpOnly;SameSite=None;Secure;Domain=xxxengineeringtools.scm.azurewebsites.net" Transfer-Encoding="chunked" X-ARR-LOG-ID="9a5068e3-729f-4557-a52a-32b1b3c87c69" CLIENT-IP="104.45.203.48:2049" X-Client-IP="104.45.203.48" X-SITE-DEPLOYMENT-ID="xxxEngineeringTools" WAS-DEFAULT-HOSTNAME="xxxengineeringtools.scm.azurewebsites.net" X-Forwarded-Proto="https" X-AppService-Proto="https" X-Forwarded-TlsVersion="1.2" X-WAWS-Unencoded-URL="/api/zipdeploy?isAsync=true&amp;deployer=VSTS_ZIP_DEPLOY&amp;message=%7B%22type%22%3A%22deployment%22%2C%22commitId%22%3A%2290765f469da1e4e5ec2372a3dfd53fc46c03ed14%22%2C%22buildId%22%3A%222654%22%2C%22releaseId%22%3A%223320%22%2C%22buildNumber%22%3A%2220231113.1%22%2C%22releaseName%22%3A%22Release-10%22%2C%22repoProvider%22%3A%22TfsGit%22%2C%22repoName%22%3A%22xxxEngineeringTools%22%2C%22collectionUrl%22%3A%22https%3A%2F%2Fxxxx%2F%22%2C%22teamProject%22%3A%229512cefc-34ad-4301-bb27-9d93fdc8a8dd%22%2C%22buildProjectUrl%22%3A%22https%3A%2F%2Fxxxx%2F9512cefc-34ad-4301-bb27-9d93fdc8a8dd%22%2C%22repositoryUrl%22%3A%22%22%2C%22branch%22%3A%22main%22%2C%22teamProjectName%22%3A%22xxxx%20IS%20Dept%22%2C%22slotName%22%3A%22production%22%7D" X-Client-Port="2049" >
  <step title="ZipPushDeploy" date="2023-11-13T17:08:07.976" >
    <step title="ZipDeploy. Run from package." date="2023-11-13T17:08:07.989" />
    <step title="None repository commit" date="2023-11-13T17:08:08.018" >
      <step title="Commit id: bfe6326b-4c26-4b7e-a00d-4b2aa9e3b7a1" date="2023-11-13T17:08:08.022" Message="N/A" AuthorName="N/A" AuthorEmail="N/A" />
    </step>
    <step title="Writing zip file to /home/data/SitePackages/20231113170807.zip" date="2023-11-13T17:08:08.044" />
    <step title="Start deployment in the background" date="2023-11-13T17:08:13.426" >
      <step title="Acquiring Deployment Lock" date="2023-11-13T17:08:13.505" />
    </step>
    <step title="There is a deployment currently in progress. Please try again when it completes." date="2023-11-13T17:08:13.551" />
  </step>
  <step title="Outgoing response" date="2023-11-13T17:08:13.577" type="response" statusCode="409" statusText="Conflict" />
</step>`

### The log/error given by the failure.
2023-11-13T17:08:07.5750811Z Package deployment using ZIP Deploy initiated.
2023-11-13T17:08:20.4873602Z ##[error]Failed to deploy web package to App Service.
2023-11-13T17:08:20.4891740Z ##[error]Error: Error: Failed to deploy web package to App Service. Bad Request (CODE: 400)
2023-11-13T17:08:21.5410345Z ##[warning]Error: Failed to update deployment history. Error: Bad Request (CODE: 400)
2023-11-13T17:08:22.3077796Z App Service Application URL: https://xxxengineeringtools.azurewebsites.net
2023-11-13T17:08:22.3137678Z ##[section]Finishing: Azure App Service Deploy: xxxEngineeringTools

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
