### ISSUE TITLE
503 (Service Unavailable) when adding TMPDIR application setting to Azure PHP 8.2 App Service

### ISSUE THREAD

**Issue by Will-at-FreedomDev** [projectkudu/kudu#3494]
### Repro steps.
1. Create a PHP 8.2 App Service
2. Create an application setting named TMPDIR (the value I used was tmpdir).
3. Try to access Advanced Tools (Kudu)

### Project structures.
Doesn't matter.

### The log/error given by the failure.
HTML: Application Error :(
DevTools: Status 503 (Service Unavailable)

### Debug your Azure website remotely.
Doesn't matter.

### Mention any other details that might be useful.
Azure blacklists other app setting names such as TMP and TEMP. If TMPDIR is essential for Kudu to operate, this should be added to that blacklist or Kudu shouldn't be broken when the setting is being used.

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
