### ISSUE TITLE
2bytes character becomes "?" on console

### ISSUE THREAD

**Issue by georgeOsdDev** [projectkudu/kudu#3499]
### Repro steps.
- Create directory or file which contains 2bytes character such as Japanese(`ディレクトリ`) from Kudu UI operation.
- execute dir command in console

2 bytes characters are displayed as "?"

<img width="524" alt="image" src="https://github.com/projectkudu/kudu/assets/1381907/189547f1-0478-4634-90ad-5cafea05675a">

Also we moved to `ディレクトリ` by clicking explorer menu, console current directly was not synced
 
<img width="525" alt="image" src="https://github.com/projectkudu/kudu/assets/1381907/b4e4df5a-018a-4b24-95a9-048c00b4d408">

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
