### ISSUE TITLE
web.config reset to default values

### ISSUE THREAD

**Issue by cmerinogeg** [projectkudu/kudu#3500]
We saved the web.config using App Services Editor and Kudu with our parameters for IIS.
The configuration is ok.
But, a new day, a new web.config (by default).
How to avoid this behavior?

Thanks!

**Comment by cmerinogeg** [comment]
Put web.config at root of project,

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
