### ISSUE TITLE
Upgrade KUDU to .NET Core

### ISSUE THREAD

**Issue by saasaTom** [projectkudu/kudu#3507]
> For deployment issues, please provide us with the following information:
> ---------------------------------------------------------------

### Repro steps.
> your project built successfully on your dev machine but failed on Azure?
> please write down your build tools and their versions (ie `Msbuild 15.1.0.0`)
Add lots of long environment variables to an app service then navicate to kudu site

### Project structures.
> in order to reproduce your issue at our end we need a simple 
> [github repository](https://github.com/projectkudu/kudu/wiki/Using-a-git-repo-to-report-an-issue)
> that highlights structure of the project

### The log/error given by the failure.
> Normally this include a stack trace, error code and some more information.
![image](https://github.com/projectkudu/kudu/assets/2855865/24b3fe51-6491-4d2f-8f87-2d33d9ce5a6a)

### Debug your Azure website remotely.
> it is recommanded that you share your Web App name, directly or [indirectly](https://github.com/projectkudu/kudu/wiki/Reporting-your-site-name-without-posting-it-publicly)
> we can take a look at what's going on.

### Mention any other details that might be useful.
We have lots of configuration set in environment variables and can now not use the kudu service.  It appears to be using .NET framework which has an issue with these environment variables. I believe .NET core doesn't.

It would be great it you could upgrade kudu to use .NET core so we can avoid this issue

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
