### ISSUE TITLE
New image not being downloaded upon restart

### ISSUE THREAD

**Issue by jasonfluent** [projectkudu/kudu#3514]
Hello.  The way in which we are deploying is from Azure Dev Ops, a pipeline that is pushing a new docker image of our Azure Web App running on a linux instance.  The last step is a restart of the App Service, which is supposed to pull the latest image (tag) upon restart.  That is our deployment model.

Even though the logs state that it is pulling the container, and maybe it is, the old container is still what runs even after a restart, and even after waiting for hours.  Some times, it takes a few manual restarts or full stop/start, and the new image will work as hoped.

We have verified that the image is in fact available from the ACR, no network issues, and no errors in the log.  

From all signs, the new image / container should be available to pull and use.  

In our development environment, we have only 1 instance of our Web App, so there's no scaling issue or orphaned processes around unless the log entries for stop and delete container are not truly what is happening.  

The logs do not output the SHA digest of the image, which would be helpful to verify what is what, and I do not see a way to trigger that type of output.  We are not able to SSH to the machine because our stack does not allow this in an Azure web app.

Please kindly advise what we might do next, it is greatly appreciated.

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
