### ISSUE TITLE
Windows App Service Zip Deploy

### ISSUE THREAD

**Issue by Shaieb524** [projectkudu/kudu#3515]
I usually deploy my angular application to windows app service manually as zip push deploy
now it is not working and the deploy goes to 50% and fails after with this log message:

Cleaning up temp folders from previous zip deployments and extracting pushed zip file C:\local\Temp\zipdeploy\ to C:\local\Temp\zipdeploy\extracted

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
