### ISSUE TITLE
Switch to using libgit2sharp instead of msysgit

### ISSUE THREAD

**Issue by davidebbo** [projectkudu/kudu#401]
Currently, we do all our git operations by just launching msysgit git.exe, which is inefficient. We should attempt to switch to using libgit2sharp (https://github.com/libgit2/libgit2sharp).

It doesn't have to be an all or nothing deal, as we can incrementally switch over a subset of operations.

In the early days, we tried to do that but it just wasn't ready for prime time. Now both Github for Windows and the new Visual Studio git pluggin uses it, so I expect it to be in pretty good shape.

**Comment by jvano** [comment]
Hi

Kudu will continue to run in Azure App Service. However, this repo will no longer be maintained.
If the problem persists and is related to running on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
