### ISSUE TITLE
'git clone --depth 1' fails

### ISSUE THREAD

**Issue by davidebbo** [projectkudu/kudu#405]
Steps:
- Create a Kudu site and push `https://github.com/KuduApps/SimpleWebApplication` to it
- Now try to clone from the Kudu git end point with option `--depth 1` to create a shallow clone.

Result: it fails with

```
fatal: protocol error: bad line length character: <!DO
fatal: write error: Invalid argument
```

**Comment by dei79** [comment]
Do you have any updates on this? Since a couple month I deploy via Git-Push and it works well but now the local sync takes longer and longer A shallow copy would make this much faster.

**Comment by davidebbo** [comment]
This issue is about shallow **cloning** from the Kudu git endpoint. Maybe what you're looking for is having a shallow clone on Kudu itself which is unrelated.

**Comment by dei79** [comment]
I want to do a shallow clone from the Kudu-Endpoint into my build machines. After that the build machine copies the compiled and minified angular.js app and the build step commits the changes back to the Kudu-Endpoint. Currently I do this with a full clone which takes a couple minutes now because of the growing history. Any Ideas to realize this?

**Comment by davidebbo** [comment]
Shallow cloning from the Kudu endpoint is unfortunately broken due to the git issue described here. Normally, this is not much of an issue for Kudu users, because Kudu **is** the build server.

As an alternative, I suppose you could try using the vfs or zip APIs to directly copy does the relevant files, rather than relying on git.

**Comment by dei79** [comment]
The main reason why I rely on git is that the Azure Portal shows the different deployments and it's easy to switch between them. Is this possible with the zip endpoints as well?

**Comment by davidebbo** [comment]
You can populate the deployment history without using git (details [here](https://github.com/projectkudu/kudu/wiki/REST-API#deployment)). However, in that mode, you cannot republish a previous deployment. The history is read only, for tracking purpose only.

**Comment by dei79** [comment]
So republishing is only supported via Git, then I think Shallow Clones would be helpful.

**Comment by davidebbo** [comment]
Yes, but at this point we have no idea how to make this work, as the issue seems to be in `git upload-pack` more than in Kudu.

**Comment by snoopdouglas** [comment]
[Just ran into this myself.](https://social.msdn.microsoft.com/Forums/en-US/e57fc3bc-fc8f-457d-b606-1c0ed72567c7/shallow-cloning-of-functions-local-git-repository-fails?forum=AzureFunctions) This'd be useful for quicker deployments. Any progress?

**Comment by dei79** [comment]
Probably this workaround can help: https://blog.dirk-eisenberg.de/2017/07/24/git-deployment-shallow-clone-support-in-azure-app-services-the-missing-piece/

**Comment by snoopdouglas** [comment]
@dei79 As I'm not particularly interested in storing any history within Azure's git repo, I've also managed to work around this by just keeping a single commit within the repo, amending it, and force pushing.

**Comment by manolof** [comment]
Facing the same issue - trying to do a shallow clone end up in the error mentioned earlier.

_I was pointed here after reporting this issue to Azure's support page_
