### ISSUE TITLE
Public submodules that use ssh don't work

### ISSUE THREAD

**Issue by davidebbo** [projectkudu/kudu#408]
Repro:
- Clone and push https://github.com/KuduApps/RepoWithPublicSubModuleSsh to Kudu

Result: it fails with:

```
Host key verification failed.
fatal: The remote end hung up unexpectedly
Clone of 'git@github.com:KuduApps/HelloKudu.git' into submodule path 'HelloKudu' failed
```

**Comment by jvano** [comment]
Hi

Kudu will continue to run in Azure App Service. However, this repo will no longer be maintained.
If the problem persists and is related to running on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
