### ISSUE TITLE
Kudu incorrectly detects static HTML site as node.js site

### ISSUE THREAD

**Issue by paulbatum** [projectkudu/kudu#560]
The logic for determining whether an app is a node.js app needs to be a bit smarter - if you try to upload a HTML site that has a "app.js" file in it this will be incorrectly detected as a node.js site and fail to load.

My suggestion is that the site should only be treated as node.js site if there is an app.js and no default document (index.html, etc).

**Comment by atrauzzi** [comment]
It's incorrect to assume that a `package.json` file at the root of the project is a clear indicator of a node project.  Many projects will use node for assets and development times utilities.
