### ISSUE TITLE
Automated KuduDevSetup.cmd Pulls down 32-bit version of node, but tests need x64. 

### ISSUE THREAD

**Issue by ghost** [projectkudu/kudu#612]
The default webpi feed I'm relying on pulls down the x86 version of node rather than the x64 version which breaks some of the tests.

**Comment by jvano** [comment]
Hi

Kudu will continue to run in Azure App Service. However, this repo will no longer be maintained.
If the problem persists and is related to running on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
