### ISSUE TITLE
Consider supporting VFS POST requests 

### ISSUE THREAD

**Issue by pranavkm** [projectkudu/kudu#650]
Per https://github.com/c9/vfs-http-adapter#post-pathtotarget, POST requests are used for adhoc commands such as rename and copy. We could expand our current VFS implementation to support these commands.

**Comment by jvano** [comment]
Hi

Kudu will continue to run in Azure App Service. However, this repo will no longer be maintained.
If the problem persists and is related to running on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
