### ISSUE TITLE
Settings get deleted alongside the repo when disconnecting from git

### ISSUE THREAD

**Issue by davidebbo** [projectkudu/kudu#663]
Today, when we 'disconnect' from git, we end up deleting the whole `/site/deployments`, which contains the settings. But those settings are not always related to deployment, so deleting them is wrong.

Ideally, the settings file should live elsewhere, but until then we should make deletion more selective,

**Comment by jvano** [comment]
Hi

Kudu will continue to run in Azure App Service. However, this repo will no longer be maintained.
If the problem persists and is related to running on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
