### ISSUE TITLE
KuduDevSetup.cmd doesn't install VS2010 target files

### ISSUE THREAD

**Issue by davidebbo** [projectkudu/kudu#673]
One manual steps that it doesn't do is:

*The Web and WebApplications folders need to be present under \Program Files (x86)\MSBuild\Microsoft\VisualStudio\v10.0. If you don't have them, you may need to copy them from a machine that has VS 2010 installed. This is needed because some of the test apps target these.*

**Comment by ahmelsayed** [comment]
@shrimpy fixed this in ef95a2160b9c1c507ab97b94575ec9abace22f64
