### ISSUE TITLE
KuduDevSetup.cmd doesn't fix up setProfileEnvironment

### ISSUE THREAD

**Issue by davidebbo** [projectkudu/kudu#674]
One manual step that it's missing is:

* Open your %WINDIR%\System32\inetsrv\config\applicationHost.config and look for `<applicationPoolDefaults>`. Under `<processModel>`, make sure you don't have `setProfileEnvironment="false"`. If you do, set it to true.

**Comment by ahmelsayed** [comment]
@shrimpy fixed this in ef95a2160b9c1c507ab97b94575ec9abace22f64
