### ISSUE TITLE
KuduDevSetup.cmd installs old version of iisnode

### ISSUE THREAD

**Issue by davidebbo** [projectkudu/kudu#675]
The one it installs is missing `interceptor.js` and some other files, causing Kudu failures.

**Comment by jvano** [comment]
Hi

Kudu will continue to run in Azure App Service. However, this repo will no longer be maintained.
If the problem persists and is related to running on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
