### ISSUE TITLE
Consider making Git-Receive-pack not build when receiving push requests for branches it's not deploying

### ISSUE THREAD

**Issue by pranavkm** [projectkudu/kudu#685]
By default, Kudu builds and deploys the master branch. However, when receiving a push request, we deploy regardless of the branch that's being received. This leads to some confusion because you notice Kudu building pushing a different branch, but it's the master branch that ends up being deployed. 

If there's a way to identify the branch that was received or if we know the changeset remains unchanged before and after push we could skip the deployment.

**Comment by jvano** [comment]
Hi

Kudu will continue to run in Azure App Service. However, this repo will no longer be maintained.
If the problem persists and is related to running on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
