### ISSUE TITLE
How can I enable basic authentication for my deployment service?

### ISSUE THREAD

**Issue by BeekeeperAlex** [projectkudu/kudu#691]
I setup Kudu on my virtual machine. I modified the IIS endpoints so I can hit my site and the related Kudu service externally. I can successfully deploy to the service, but it's not secure.

In IIS I enabled "basic authentication". It now asks me for a username and password when I hit the service which is good, but I don't know where to change the username and password.

Am I enabling basic authentication properly? If so, how do I determine the username and password that is needed.

**Comment by dpayne0220** [comment]
So you changed "admin/kudu" to your basic auth and it worked? Were there any other steps, I'm not able to get it to work without disabling basic auth.
