### ISSUE TITLE
Ability to specify environment variables in Kudu.Web interface?

### ISSUE THREAD

**Issue by catdadcode** [projectkudu/kudu#693]
It took me a bit to find documentation on how to specify environment variables for my node app running on Kudu. I eventually found that I had to go to kudu/apps/codetunnel/site/wwwroot/web.config and add an appSettings node under the configuration node. Then I could add name value pairs that would turn into environment variables.

It would be a lot more awesome if I could just go to the Kudu.Web interface, click my application, click "configuration", and then add name value pairs to the custom properties section and get those as environment variables. Or else add another section just titled "environment variables".

**Comment by niemyjski** [comment]
+1

**Comment by jvano** [comment]
Hi

Kudu will continue to run in Azure App Service. However, this repo will no longer be maintained.
If the problem persists and is related to running on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
