### ISSUE TITLE
Remove webpages:Enabled Custom Properties from Kudu.Web

### ISSUE THREAD

**Issue by yaminij** [projectkudu/kudu#700]
We do not allow setting appSettings in web.config using Kudu.Web. We should remove this configuration property because its misleading and cannot be overridden.

![untitled](https://f.cloud.github.com/assets/4481640/801560/3332cd74-eda4-11e2-857d-5ca2b0c52962.png)

**Comment by jvano** [comment]
Hi

Kudu will continue to run in Azure App Service. However, this repo will no longer be maintained.
If the problem persists and is related to running on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
