### ISSUE TITLE
Ensure TypeScripts projects are supported

### ISSUE THREAD

**Issue by amitapl** [projectkudu/kudu#721]
- Verify whether typescript projects are supported with recent changes
- Add test to make sure they stay that way
- Document support

Relates to #556

@gissues:{"order":83.17307692307682,"status":"backlog"}

**Comment by smithkl42** [comment]
@davidebbo - Sorry to bug you again :-). 1.4 is out now - any update on when that'll make its way onto Azure websites?

**Comment by davidebbo** [comment]
Yes, we're trying to get 1.4 on there soon. It may only be in some regions to begin with. Are you set up to verify that it works well, once it's ready on our side?

**Comment by smithkl42** [comment]
Yup, can do it in 5 minutes.

**Comment by davidebbo** [comment]
Ok, can you create a test site in South Brazil now and give it a try? Ironically, it has 1.4 but not 1.3 (which will come later). Don't ask...

**Comment by luisrudge** [comment]
Awesome! That's why I love Brazil! :)

**Comment by davidebbo** [comment]
Yes, for some reason, we have a 'tradition' of deploying Brazil first! But the rest shouldn't be far behind. :)

**Comment by smithkl42** [comment]
@davidebbo - I was able to successfully deploy to South Brazil with 1.4. Looking forward to it landing in US West :-).

**Comment by davidebbo** [comment]
It's everywhere now.

**Comment by luisrudge** [comment]
That was fast. Thanks @davidebbo!

**Comment by smithkl42** [comment]
Awesome! Thanks!

**Comment by davidebbo** [comment]
Were you able to try a test scenario? It works for us, but it would be good confirmation as we didn't try anything too fancy.

**Comment by smithkl42** [comment]
@davidebbo - Nothing too fancy, but I was able to get my web project to compile and deploy with the TSTools set to 1.4 - which was the scenario that had failed yesterday.

**Comment by davidebbo** [comment]
Awesome, thanks for confirming!

**Comment by sjkp** [comment]
What about visual studio node js projects? It doesn't compile typescript in those :(

**Comment by ahmelsayed** [comment]
@sjkp Do you have a sample repo for that somewhere I can take a look at?

**Comment by sjkp** [comment]
https://github.com/sjkp/SJKP.CvrRegnskabsData this is the one i tried with. Build in VS2015.

**Comment by ahmelsayed** [comment]
I see. We currently don't support `.njsproj` projects in Kudu. Can you please open another issue for tracking this?
