### ISSUE TITLE
Stress: git repository can be corrupted under stress when a site is restarted

### ISSUE THREAD

**Issue by hongdai** [projectkudu/kudu#757]
Once git repository is corrupted, all kudu operations will fail. Zumo operations could fail as well because of corrupted scripts. Currently the only fix is to hand fix the git repository and Zumo scripts.

 It's a valid customer scenario to restart a Zumo site when there are many incoming requests.
a. The Antares File server reboots, or

b. A Update Site config change is issued, for example, redeployment runtime.

 We should make this scenario work

**Comment by jvano** [comment]
Hi

Kudu will continue to run in Azure App Service. However, this repo will no longer be maintained.
If the problem persists and is related to running on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
