### ISSUE TITLE
Add automated test to verify upgrade scenario

### ISSUE THREAD

**Issue by davidebbo** [projectkudu/kudu#783]
The idea is to have a test that:
- creates a site and uses Kudu using the previous official version (the one that's live in Azure).
- switch it over to using the latest Kudu
- Verify that everything still works

This way if we make some incompatible changes, we can catch them early.

**Comment by jvano** [comment]
Hi

Kudu will continue to run in Azure App Service. However, this repo will no longer be maintained.
If the problem persists and is related to running on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
