### ISSUE TITLE
Kudu should not create unnecessary folders

### ISSUE THREAD

**Issue by davidebbo** [projectkudu/kudu#790]
Today, if you have a site that doesn't use any Kudu based publishing, but just uses Kudu in other ways (e.g. streaming), Kudu still creates a bunch of folders that don't make sense, e.g.

```
LogFiles
  Git
Site
  deployments
  diagnostics
  repository
```

Would be nice to avoid this creation until a feature is used that calls for it.

**Comment by jvano** [comment]
Hi

Kudu will continue to run in Azure App Service. However, this repo will no longer be maintained.
If the problem persists and is related to running on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
