### ISSUE TITLE
Project Kudu available via Web Platform Installer

### ISSUE THREAD

**Issue by wwahammy** [projectkudu/kudu#807]
Currently, in order to use Kudu one needs to build Kudu by itself in order to install it on IIS. Is there any way Kudu can get hosted on the base Web Platform Installer feed? Short of that, is there a way to host a custom Web Platform Installer feed for Kudu itself?
@gissues:{"order":93.26923076923073,"status":"backlog"}

**Comment by jvano** [comment]
Hi

Kudu will continue to run in Azure App Service. However, this repo will no longer be maintained.
If the problem persists and is related to running on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
