### ISSUE TITLE
REST endpoint to allow users to test their XDT

### ISSUE THREAD

**Issue by suwatch** [projectkudu/kudu#814]
It is quite hard to verify that XDT that you wrote will work the way you expect.   In order to test, one need to get the XDT binary, download the applicationHost.config from one of their sites (not straight forward), write console app codes to do a transform and check resulting config.  

The idea I have is a way for user to HTTP POST XDT to one of extension endpoint (may or may not be kudu) and the result is success/fail + the transformed applicationHost.config.    Think of it like a similar facility for server-side generate deployment script.

**Comment by jvano** [comment]
Hi

Kudu will continue to run in Azure App Service. However, this repo will no longer be maintained.
If the problem persists and is related to running on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
