### ISSUE TITLE
Error updating private sub-module on Azure Web Sites

### ISSUE THREAD

**Issue by ThatRendle** [projectkudu/kudu#841]
I'm trying to deploy a site with a submodule from GitHub.

I followed the instructions in this blog post ( http://blogs.suwatbodin.com/2013/07/deploy-to-windows-azure-using-git-with.html ) and set up a GitHub user with the SSH key (I downloaded the id_rsa.pub from the Azure site using FTP). That user has pull permission on the site repo and the submodule.

When I switched the Azure keys into my ~/.ssh folder locally I could `clone` and `submodule update --init --recursive` no problem.

But when the WAWS deployment process runs, I get this error:

```
fatal: Needed a single revision
Unable to find current revision in submodule path 'src/MySite/MySubModule'

D:\Program Files (x86)\Git\bin\git.exe submodule update --init --recursive
```

This seems unreasonable to me.

I'm going to drink myself senseless now and hope that someone has a suggestion when I check back in the morning.

**Comment by abelondev** [comment]
Why not implement support github submodules out the box?
