### ISSUE TITLE
WebJob: Fix jobs manager singleton issue

### ISSUE THREAD

**Issue by amitapl** [projectkudu/kudu#845]
Currently ninject disposes the jobs manager after the first request,
The jobs manager is a singleton which should never be disposed,
To fix it for now the dispose method will basically do nothing, but a real fix should be that the dispose method is not called.

**Comment by jvano** [comment]
Hi

Kudu will continue to run in Azure App Service. However, this repo will no longer be maintained.
If the problem persists and is related to running on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
