### ISSUE TITLE
Test to cover Windows Azure GitHub WebHook

### ISSUE THREAD

**Issue by suwatch** [projectkudu/kudu#849]
We could go either using token (like Dropbox) or SSH to setup Windows Azure Hook and do Test Hook.

**Comment by jvano** [comment]
Hi

Kudu will continue to run in Azure App Service. However, this repo will no longer be maintained.
If the problem persists and is related to running on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
