### ISSUE TITLE
DebugConsole: can't exit out of interactive console app

### ISSUE THREAD

**Issue by davidebbo** [projectkudu/kudu#864]
In the new console, when running a REPL command line tool, there is no easy way to get out. e.g. try running `cat`. It correctly takes input and echos it, but neither Ctrl-C, Ctrl-Break nor Ctrl-Z work to get out.

We may need to add some support for control characters.

**Comment by davidebbo** [comment]
This is not likely to happen. Kudu Console is not a true console, and things like Ctrl-C are hard to achieve. If you really need to kill a process, you can do it from Process Explorer.

**Comment by fab2903** [comment]
I face this same issue today. It will be nice to have this feature enable.

**Comment by felipepessoto** [comment]
Do you have any alternative to close procdump without killing the process?

**Comment by jvano** [comment]
Hi

Kudu will continue to run in Azure App Service. However, this repo will no longer be maintained.
If the problem persists and is related to running on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
