### ISSUE TITLE
The Environment is created on each request

### ISSUE THREAD

**Issue by davidebbo** [projectkudu/kudu#873]
We currently create the `IEnvironment` in request scope, so it gets created each time, even though it never changes.

I think there was some chicken/egg trickiness around it, but it would be nice to solve it.

**Comment by jvano** [comment]
Hi

Kudu will continue to run in Azure App Service. However, this repo will no longer be maintained.
If the problem persists and is related to running on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
