### ISSUE TITLE
Give way to force a deployment after a local git push fails

### ISSUE THREAD

**Issue by davidebbo** [projectkudu/kudu#889]
e.g. in the case of #878, we end up in a state where it's hard to cause a deployment without creating a bogus commit. We need to give users an easier way to deal with this.

**Comment by snobu** [comment]
I remember running into this too and using `git push --mirror` and probably a `--force` too to trigger a redeploy, of course it's a very unnatural thing to do but it did work.

```powershell
C:\localrepo [master]> git push
Everything up-to-date
C:\localrepo [master]> git push --mirror
Total 0 (delta 0), reused 0 (delta 0)
remote: Updating branch 'master'.
remote: Updating submodules.
remote: Preparing deployment for commit id 'b7eb192658'.
remote: Generating deployment script.
remote: Running deployment command...
remote: Handling Basic Web Site deployment.
remote: KuduSync.NET from: 'D:\home\site\repository' to: 'D:\home\site\wwwroot'
remote: Finished successfully.
remote: Deployment successful.
To https://snobudev@kuduvanilla.scm.azurewebsites.net/kuduvanilla.git
 * [new branch]      master/master -> master/master
C:\localrepo [master]>
```

**Comment by davidebbo** [comment]
Nice, never used this flag before!

**Comment by ahmelsayed** [comment]
wait, what does `--mirror` do here? The man page description doesn't seem to make sense for this scenario

**Comment by snobu** [comment]
Well, I'm not entirely sure why that worked, but in theory `--mirror` overwrites the remote repo and probably this triggered a redeploy in Kudu.

```
--mirror

Set up a mirror of the source repository. This implies --bare. Compared to --bare, --mirror
not only maps local branches of the source to local branches of the target, it maps all refs
(including remote-tracking branches, notes etc.) and sets up a refspec configuration such
that all these refs are overwritten by a git remote update in the target repository.

https://www.kernel.org/pub/software/scm/git/docs/git-clone.html
```

**Comment by abhijitnathwani** [comment]
Hi @suwatch 

> We have such already. `curl '<scm-uri>/deployments' -X PUT -k -data "{}"`

I can't seem to get this working. Does this method still work? Or any other command has replaced this setting for Azure App Service?

**Comment by suwatch** [comment]
Did you try with `--mirror` suggested above?

**Comment by abhijitnathwani** [comment]
Yes, it gives error 
`error: --mirror can't be combined with refspecs`
I'm using Kudu for Azure App Service deployments.

**Comment by suwatch** [comment]
I suspected below also does not support refspecs.   Could you share your commit command syntax?  Also share the site name here or [indirectly](https://github.com/projectkudu/kudu/wiki/Reporting-your-site-name-without-posting-it-publicly) and the UTC time when you called below and it did not work.

> We have such already. curl '<scm-uri>/deployments' -X PUT -k -data "{}"
