### ISSUE TITLE
Add REST API to return Kudu system info

### ISSUE THREAD

**Issue by davidebbo** [projectkudu/kudu#890]
e.g. it could return the same info that we currently display on `/env.aspx`, but as JSON that can be machine processed.

**Comment by jvano** [comment]
Hi

Kudu will continue to run in Azure App Service. However, this repo will no longer be maintained.
If the problem persists and is related to running on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
