### ISSUE TITLE
Enable https protocol in custom site binding

### ISSUE THREAD

**Issue by davorgrubelic** [projectkudu/kudu#923]
It would be great if you could implement possibility to choose between HTTP and HTTPS protocol in custom site binding. This is specially good reason with service applications to increase service security.

Is there any reason why this isn't supported yet?

Happy coding... :)
@gissues:{"order":66.34615384615365,"status":"backlog"}

**Comment by davidebbo** [comment]
Fixed by d42e4fbcbd64ba4f48895520849e8106d453ddcb
