### ISSUE TITLE
Add logic to trigger a deployment on 'git push' to recover from certain errors

### ISSUE THREAD

**Issue by davidebbo** [projectkudu/kudu#925]
When git push fails so badly that kudu.exe doesn't start, we end up in a weird state with no deployment, and git pushing again doesn't help.

We should add logic to recover better from this without forcing dummy commits on users.

**Comment by jvano** [comment]
Hi

Kudu will continue to run in Azure App Service. However, this repo will no longer be maintained.
If the problem persists and is related to running on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
