### ISSUE TITLE
'git push' fails when Kudu path contains space

### ISSUE THREAD

**Issue by mwtian-zz** [projectkudu/kudu#926]
I was running Kudu locally (its path contains spaces), created a new application and tried to 'git' to push a website to the new application. An error was returned. There seem to be multiple parts of code where paths containing spaces will result in errors.
@gissues:{"order":64.42307692307672,"status":"backlog"}

**Comment by jvano** [comment]
Hi

Kudu will continue to run in Azure App Service. However, this repo will no longer be maintained.
If the problem persists and is related to running on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
