### ISSUE TITLE
Engineering: combine all ninjected interfaces into one IServiceProvider 

### ISSUE THREAD

**Issue by suwatch** [projectkudu/kudu#927]
There are 2 problems motivating this.

If you look at DeploymentManager ctor for examples, you will see multiple interfaces as arg.  These are instantiated by Ninject during  instance creation.  The problem is ctor args become bloated and, as one need more interface, this ctor args will keep expanding.

Similar for api such as [this](https://github.com/projectkudu/kudu/blob/master/Kudu.Core/Infrastructure/Executable.cs#L116), multiple interfaces can be consolidated into one IServiceProvider keeping api cleaner.

**Comment by jvano** [comment]
Hi

Kudu will continue to run in Azure App Service. However, this repo will no longer be maintained.
If the problem persists and is related to running on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
