### ISSUE TITLE
Support for Github deployment API in Windows Azure

### ISSUE THREAD

**Issue by Jaxwood** [projectkudu/kudu#958]
Would like to see Windows Azure support Github deployment API when it's released.

http://developer.github.com/v3/repos/deployments/#preview-mode

**Comment by XVincentX** [comment]
I'd like to try work on it. What do you think about?

**Comment by davidebbo** [comment]
I think part of the difficulty is that after initial setup (which sets up WebHook and Deploy key), Kudu does not keep a token that lets it talk to the GitHub API. For private repos, it does have an ssh key. Not sure if that can be used. But for public repos, it would be harder.

Need to see if @suwatch and others have thoughts on this.

**Comment by atmos** [comment]
Yeah, you'll need a personal access token or OAuth access. SSH keys will only grant access to the code, not act on behalf of a user via the API.

**Comment by davidebbo** [comment]
Thanks @atmos for confirming. We'd need to do some work in Azure outside of Kudu itself to make this possible.

**Comment by suwatch** [comment]
At this moment, we plan to ship a sample demonstrating how one could achieve the integration.  Depending on feedbacks, we may decide to make it part of the product.

**Comment by jvano** [comment]
Hi

Kudu will continue to run in Azure App Service. However, this repo will no longer be maintained.
If the problem persists and is related to running on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
