### ISSUE TITLE
Get cdb.exe to work with DebugConsole

### ISSUE THREAD

**Issue by ahmelsayed** [projectkudu/kudu#988]
add cdb.exe to kudu and get it hooked to a minidump of the worker process automatically.

**Comment by jvano** [comment]
Hi

Kudu will continue to run in Azure App Service. However, this repo will no longer be maintained.
If the problem persists and is related to running on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
