### ISSUE TITLE
building Kudu using build.cmd fails if only VS 2013 is installed on the machine

### ISSUE THREAD

**Issue by ahmelsayed** [projectkudu/kudu#992]
build.cmd doesn’t work if you only have VS 2013 (v12.0) installed due to this build error 

C:\proj\kudu\Kudu.Services.Web\Kudu.Services.Web.csproj(191,3): error MSB4019: The imported project "C:\Progra m Files (x86)\MSBuild\Microsoft\VisualStudio\v11.0\WebApplications\Microsoft.WebApplication.targets" was not f ound. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.

updating the csproj files to pick a newer VS works. at least we should pick the newest VS installed

**Comment by jvano** [comment]
Hi

Kudu will continue to run in Azure App Service. However, this repo will no longer be maintained.
If the problem persists and is related to running on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
