### ISSUE TITLE
Remove solution conditional in generated custom scripts

### ISSUE THREAD

**Issue by davidebbo** [projectkudu/kudu#993]
It looks like this, and this part doesn’t seem to make sense:

```
:: 1. Restore NuGet packages
IF /I "Mvc51ApplicationFx451.sln" NEQ "" (
  call "%NUGET_EXE%" restore "%DEPLOYMENT_SOURCE%\Mvc51ApplicationFx451.sln"
  IF !ERRORLEVEL! NEQ 0 goto error
)
```

Normally, we only do conditionals on things that are variable and not hard coded. Instead it seems the logic to decide whether to run it or not should be in the generator, and not happen at build time.

**Comment by jvano** [comment]
Hi

Kudu will continue to run in Azure App Service. However, this repo will no longer be maintained.
If the problem persists and is related to running on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
